"""Paper 1 · Computer Literacy · P1-CL-05 Unit 3 – MS PowerPoint (2 sub-topics × 20).
References: Microsoft Support – PowerPoint keyboard shortcuts and help pages (Microsoft 365 / PowerPoint 2016–2021);
NIELIT CCC courseware.
Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question number)
with new questions. Official answers come from KEA's final keys: Karnataka Legislative Council Secretariat 2024 (Computer
Operator P2, Junior Console Operator P2, Data Entry Operator P2, Assistant/Jr Assistant P2 – booklet A1; final key
09-04-2025) and GTTC 2024 (Officer Gr-II / Assistant Gr-III Kannada, English & Computer – booklet A1; final key
30-12-2024). Obvious printing typos are corrected."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"

SLIDES = [
    # --- real previous-year questions (official keys) ---
    ("Which PowerPoint view displays each slide of the presentation as a thumbnail and is useful for rearranging slides?",
     ["Slide Master", "Slide Show", "Slide Design", "Slide Sorter"], 3,
     "Slide Sorter shows all slides as thumbnails that can be dragged into a new order." + KLC,
     "Legislative Council 2024 Asst/Jr Asst P2 · Q93"),
    ("Which of the following is a default Page Setup orientation in PowerPoint?",
     ["Vertical", "Landscape", "Portrait", "None of the above"], 1,
     "Slides are landscape by default; notes and handouts are portrait." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q87"),
    ("How to add a Header/Footer in handout?",
     ["View → Page Setup", "View → Header/Footer", "View → Handout Master", "None of the above"], 2,
     "Handout headers and footers are edited in View → Handout Master." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q90"),
    ("How to insert a slide number in a presentation?",
     ["Insert a text box & Select insert → number → page number", "Insert Page → page number → slide number", "Insert a new text box & select insert → slide number", "Insert & Select → slide number"], 2,
     "Insert → Slide Number (inside a text box or the footer placeholder) adds a field that updates automatically." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q91"),
    ("Answer true or false for MS PowerPoint\n(a) To remove a tab, drag the marker off the ruler\n(b) A slideshow is a series of slides",
     ["Both a & b are true", "a is true but b is false", "a is false but b is true", "Both a & b are false"], 0,
     "A tab stop is removed by dragging it off the ruler; a slide show presents slides one after another." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q94"),
    ("Match the following extensions with the file types.\nList-1: (a) .docx  (b) .xlsx  (c) .pptx  (d) .accdb\nList-2: i) MS Access  ii) MS PowerPoint  iii) MS Excel  iv) MS Word",
     ["a – iv, b – iii, c – ii, d – i", "a – iv, b – ii, c – iii, d – i", "a – ii, b – iv, c – iii, d – i", "a – i, b – ii, c – iii, d – iv"], 0,
     ".docx Word, .xlsx Excel, .pptx PowerPoint, .accdb Access." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q95"),
    ("Identify the correct statements.\n(a) A PowerPoint template is saved as .potx.\n(b) To insert a new slide, the shortcut key is ctrl-M.",
     ["Both a & b are correct", "Only a is correct", "None of the statements is correct", "Only b is correct"], 0,
     ".potx is the template format; Ctrl + M inserts a new slide." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q98"),
    ("Which of the following statements about Microsoft PowerPoint are true?\n(i) You can set a slideshow to advance automatically after a set period without user interaction.\n(ii) Slide master allows you to apply consistent formatting to all slides in a presentation.\n(iii) The SmartArt feature allows you to insert pre-designed graphic diagrams like flowcharts and hierarchies.\n(iv) PowerPoint does not support embedding videos directly, only links to videos are allowed",
     ["i, ii and iii are true", "ii and iv are true", "i, iii and iv are true", "iii and iv are true"], 0,
     "PowerPoint can embed video files directly (Insert → Video), so (iv) is false." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q93"),
    ("Match the following:\nList-I: a. Excel  b. PowerPoint  c. Access  d. Outlook\nList-II: i. Used for creating presentations  ii. Used for managing emails  iii. Used for data analysis and visualization  iv. Used for managing databases",
     ["a – iv, b – i, c – iii, d – ii", "a – iii, b – iv, c – i, d – ii", "a – iii, b – i, c – iv, d – ii", "a – iv, b – ii, c – i, d – iii"], 2,
     "Excel – data analysis; PowerPoint – presentations; Access – databases; Outlook – e-mail." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q94"),
    # --- new questions ---
    ("In MS PowerPoint, a file is called a ____ and each page of it is called a ____.",
     ["presentation; slide", "workbook; sheet", "document; page", "database; record"], 0,
     PYQ + "Excel files are workbooks of worksheets; Word files are documents."),
    ("The default view in which PowerPoint opens, showing the current slide with slide thumbnails and a notes pane, is:",
     ["Normal view", "Slide Sorter view", "Reading view", "Slide Show view"], 0,
     PYQ + "Views are on the View tab and on the status bar."),
    ("Speaker notes can be printed together with a picture of each slide using:",
     ["Notes Page view / printing Notes Pages", "Slide Sorter view", "Outline view only", "Handout Master with 9 slides"], 0,
     "The audience does not see the notes during the show."),
    ("A slide layout determines:",
     ["The arrangement of placeholders (title, content, pictures) on a slide", "The speed of transitions", "The file format", "The printer settings"], 0,
     "e.g. Title Slide, Title and Content, Two Content, Comparison."),
    ("A placeholder in PowerPoint is:",
     ["A box with a dotted border that holds title, text, pictures or other content", "A hidden slide", "A sound file", "A password"], 0,
     "'Click to add title' appears inside an empty placeholder."),
    ("A set of coordinated colours, fonts and effects applied to a whole presentation from the Design tab is called a:",
     ["Theme", "Transition", "Macro", "Handout"], 0,
     PYQ + "Variants on the Design tab change the colour scheme of the theme."),
    ("What happens to a slide marked as 'Hide Slide'?",
     ["It stays in the file but is skipped during the slide show", "It is deleted permanently", "It is printed in red", "It becomes the first slide"], 0,
     "Hidden slides appear faded with a slashed number in Slide Sorter."),
    ("When printing handouts, PowerPoint can place at most how many slides on one page?",
     ["9", "4", "6", "12"], 0,
     PYQ + "Handout options: 1, 2, 3, 4, 6 or 9 slides per page."),
    ("The keyboard shortcut to duplicate the selected slide in PowerPoint is:",
     ["Ctrl + D", "Ctrl + M", "Ctrl + N", "Ctrl + Shift + S"], 0,
     "Ctrl + M inserts a new blank slide; Ctrl + N opens a new presentation."),
    ("Consider the statements:\nI. Changes made on the Slide Master appear on all slides that use that master.\nII. Typing text on one slide in Slide Sorter view automatically copies it to every slide.\nWhich is/are correct?",
     I_II, 0, "Only the master applies formatting to every slide; text cannot even be typed in Slide Sorter."),
    ("Assertion (A): Hidden slides are not shown during a slide show.\nReason (R): Hidden slides are deleted from the presentation file.",
     AR, 2, "They remain in the file and can be unhidden, so R is false."),
]

SHOW = [
    # --- real previous-year questions (official keys) ---
    ("Match the following shortcut keys (List I) of MS PowerPoint with their actions (List II)\nList-I: (a) Ctrl - M  (b) Ctrl - O  (c) Ctrl - H  (d) Ctrl - K\nList-II: i) Insert hyperlink  ii) Replace particular text  iii) New slide  iv) Open existing presentation",
     ["a – iii, b – iv, c – ii, d – i", "a – iii, b – ii, c – iv, d – i", "a – ii, b – iii, c – i, d – iv", "a – ii, b – iv, c – i, d – iii"], 0,
     "Ctrl + M new slide, Ctrl + O open, Ctrl + H replace, Ctrl + K hyperlink." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q82"),
    ("In MS PowerPoint, the key used to run the slide show from the beginning is",
     ["F5", "F11", "F7", "F1"], 0,
     "F7 runs the spelling check; F1 opens Help." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q89"),
    ("Match the following in relation to MS PowerPoint.\nList-A: (a) startOnclick  (b) Transition  (c) Slide Master  (d) Text Box\nList-B: i) Container for adding text  ii) Option that will start animation  iii) Special effect that controls how slide changes  iv) Tool to create consistent background & layout",
     ["a – ii, b – iv, c – iii, d – i", "a – ii, b – iii, c – iv, d – i", "a – ii, b – i, c – iii, d – iv", "a – i, b – ii, c – iv, d – iii"], 1,
     "'On Click' starts an animation; a transition controls how one slide changes to the next; the Slide Master gives a uniform layout; a text box holds text." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q97"),
    ("The shortcut keys for slide show in MS PowerPoint are",
     ["Shift + F5", "Shift + F7", "Ctrl + F2", "Ctrl + F5"], 0,
     "Shift + F5 starts the show from the current slide (F5 starts from the beginning)." + KLC,
     "Legislative Council 2024 Data Entry Operator P2 · Q96"),
    ("In PowerPoint, which feature allows you to apply animation effects to individual element of a slide rather than to the entire slide?",
     ["Slide Transition", "Custom Animation", "Animation Painter", "Motion Paths"], 1,
     "Animations act on objects within a slide; transitions act on whole slides." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q87"),
    ("In power point, which of the following file types can be used to export your presentation in order to preserve animations and Multimedia?",
     ["PDF", "HTML", "MP4", "GIF"], 2,
     "File → Export → Create a Video saves the show as MP4 with timings, animations and media." + GTTC,
     "GTTC 2024 Officer/Asst Gr-III KEC · Q71"),
    # --- new questions ---
    ("The difference between a transition and an animation in PowerPoint is that:",
     ["A transition is the effect when moving from one slide to the next; an animation is an effect on an object within a slide", "Both mean exactly the same thing", "A transition applies only to text", "An animation changes the slide's layout"], 0,
     PYQ + "Transitions tab vs Animations tab."),
    ("The four groups of animation effects in PowerPoint are:",
     ["Entrance, Emphasis, Exit and Motion Paths", "Start, Middle, End and Loop", "Fade, Wipe, Push and Cut only", "Header, Footer, Body and Title"], 0,
     PYQ + "Entrance effects are green, emphasis yellow, exit red in the gallery."),
    ("The Animation Pane in PowerPoint is used to:",
     ["See and change the order, timing and options of all animations on a slide", "Insert new slides", "Check spelling", "Print handouts"], 0,
     "Animations → Advanced Animation → Animation Pane."),
    ("The 'Start' options for an animation are:",
     ["On Click, With Previous and After Previous", "Fast, Medium and Slow", "Left, Right and Centre", "Before, During and After the show"], 0,
     "Duration and Delay are set beside Start."),
    ("'Rehearse Timings' in PowerPoint is used to:",
     ["Record how long each slide is shown so the show can advance automatically", "Check grammar", "Set a password", "Compress pictures"], 0,
     "Slide Show tab → Rehearse Timings."),
    ("To end a running slide show and return to the editing view, press:",
     ["Esc", "F5", "Ctrl + M", "Tab"], 0,
     PYQ + "The hyphen key also ends the show."),
    ("During a slide show, pressing the B key:",
     ["Turns the screen black (press again to resume)", "Goes to the first slide", "Ends the show", "Starts recording"], 0,
     "W turns the screen white."),
    ("To make a presentation play over and over until Esc is pressed (e.g. at an exhibition), use:",
     ["Slide Show → Set Up Slide Show → Loop continuously until 'Esc'", "Transitions → Repeat", "Animations → Loop", "File → Options → Repeat"], 0,
     PYQ + "Often combined with automatic slide timings."),
    ("A custom slide show allows you to:",
     ["Show only a chosen group of slides from the presentation, in a chosen order", "Change the theme colours", "Insert charts", "Save the file as PDF"], 0,
     "Slide Show → Custom Slide Show."),
    ("Presenter View lets the presenter:",
     ["See the notes, the next slide and a timer while the audience sees only the current slide", "Edit the Slide Master during the show", "Hide all slides", "Print the presentation"], 0,
     "It needs a second screen or projector."),
    ("Match the animation type with its effect:\na. Entrance  b. Emphasis  c. Exit  d. Motion path\n1. The object moves along a drawn line  2. The object leaves the slide  3. Draws attention to an object already on the slide  4. The object appears on the slide",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Animation types are often matched in KEA computer sections."),
    ("Consider the statements:\nI. A transition applies to a whole slide.\nII. An animation can be applied to a single picture or line of text.\nWhich is/are correct?",
     I_II, 2, "That is the basic difference between them."),
    ("Assertion (A): An animation set to 'After Previous' starts without a mouse click.\nReason (R): It begins automatically when the previous animation finishes.",
     AR, 0, "'With Previous' starts at the same time as the previous one."),
    ("In a classroom, PowerPoint is used best when it:",
     ["Supports the teacher's explanation with key points, pictures and diagrams", "Replaces the teacher completely", "Shows long paragraphs of text on every slide", "Is used without any planning"], 0,
     "Good slides are brief and visual; the teacher still explains and interacts."),
]

TOPICS = {
    "Unit 3 – MS PowerPoint": [("1 · Slides, Views, Layouts and Slide Master", SLIDES),
                               ("2 · Animations, Transitions and Slide Show", SHOW)],
}
