"""Paper 1 · Current Affairs, month by month from January 2026 (owner's rule: 75% Karnataka, 25% national;
important schemes included). Each month = one topic with two sets: "1 · Karnataka" (30 Q) and "2 · National" (10 Q).
Every fact was checked on the web (two sources where they disagreed); the source is named in each explanation.
Do not add facts from memory for current affairs."""
from packlib import AR, I_II

JAN26_KARNATAKA = [
    ("In January 2026, who became the longest-serving Chief Minister in Karnataka's history?",
     ["Siddaramaiah", "D. K. Shivakumar", "B. S. Yediyurappa", "S. M. Krishna"], 0,
     "Siddaramaiah equalled the record on 6 January 2026 and surpassed it the next day (Deccan Herald, India TV, The Federal)."),
    ("Whose record did Siddaramaiah break to become Karnataka's longest-serving Chief Minister?",
     ["D. Devaraj Urs", "S. Nijalingappa", "Ramakrishna Hegde", "Veerendra Patil"], 0,
     "Devaraj Urs held the record with 2,792 days over two terms (1972–77 and 1978–80) (Deccan Herald)."),
    ("On 6 January 2026 Siddaramaiah equalled the record tenure of how many days as Karnataka Chief Minister?",
     ["2,792 days", "2,113 days", "1,829 days", "3,650 days"], 0,
     "2,792 days ≈ 7 years 235 days. 2,113 was Urs' first term and 1,829 Siddaramaiah's first term (Deccan Herald)."),
    ("Siddaramaiah's record tenure as Chief Minister was built up over which two terms?",
     ["2013–2018, and again from May 2023", "2008–2013, and again from 2018", "2004–2006, and again from 2013", "Only one continuous term from 2018"], 0,
     "First term 13 May 2013 – 15 May 2018 (1,829 days); second term from 20 May 2023 (India TV)."),
    ("Consider the statements about D. Devaraj Urs:\nI. He served two terms as Karnataka Chief Minister in the 1970s.\nII. He is remembered for land reforms and social justice.\nWhich is/are correct?",
     I_II, 2, "Urs was CM from 1972 to 1977 and 1978 to 1980 and is regarded as an icon of land reforms and social justice (India TV)."),
    ("Which Karnataka personality received the Padma Bhushan in the Padma Awards 2026?",
     ["Shatavadhani R. Ganesh", "Anke Gowda", "Suresh Hanagavadi", "S. G. Susheelamma"], 0,
     "R. Ganesh received the Padma Bhushan for art (avadhana); the others received the Padma Shri (Asianet Newsable, NewsFirst Prime)."),
    ("Shatavadhani R. Ganesh, a Padma Bhushan awardee of 2026, is famous for which art?",
     ["Avadhana, a Kannada/Sanskrit literary performance art", "Yakshagana", "Carnatic violin", "Kathakali"], 0,
     "'Shatavadhani' refers to his mastery of avadhana; he is also a scholar and writer (Asianet Newsable)."),
    ("Anke Gowda of Karnataka, awarded the Padma Shri in 2026, is known for:",
     ["Building 'Pustaka Mane', a huge free-access library near Mysuru", "Planting thousands of banyan trees on highways", "Reviving dried-up lakes in Bengaluru", "Running free schools for tribal children"], 0,
     "A former bus conductor from Haralahalli near Mysuru, he built one of the largest private free libraries (PTI report quoted by news sites)."),
    ("How many achievers from Karnataka were named in the Padma Awards 2026 list?",
     ["8", "3", "12", "5"], 0, "One Padma Bhushan (R. Ganesh) and seven Padma Shri awards (NewsFirst Prime, Asianet Newsable)."),
    ("T. T. Jagannathan, honoured posthumously with the Padma Shri 2026, was known in the field of:",
     ["Trade and industry (TTK group)", "Classical music", "Mountaineering", "Agricultural science"], 0,
     "Called the 'kitchen mogul', he led TTK Prestige for decades and invented the GRS safety system for pressure cookers (Daily Excelsior, GKToday)."),
    ("Dr Suresh Hanagavadi, a Padma Shri 2026 awardee, is recognised for medical service in which district of Karnataka?",
     ["Davanagere", "Kalaburagi", "Udupi", "Kodagu"], 0, "Asianet Newsable describes his medical service in Davanagere."),
    ("Match the Karnataka Padma awardee (2026) with the field:\na. Shatavadhani R. Ganesh  b. Anke Gowda  c. Suresh Hanagavadi  d. T. T. Jagannathan\n1. Trade and industry  2. Medicine  3. Social work (library)  4. Art (avadhana)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "As listed in the Padma Awards 2026 announcement of 25 January 2026."),
    ("At the joint sitting of the Karnataka Legislature on 22 January 2026, Governor Thaawarchand Gehlot:",
     ["Read only two lines and walked out without reading the government's prepared address", "Read the full address prepared by the government", "Dissolved the Assembly", "Did not attend and sent the Speaker to read it"], 0,
     "The two-line speech and walk-out became a major controversy (The Week, India TV)."),
    ("The joint session of the Karnataka Legislature from 22 January 2026 was called mainly to discuss:",
     ["The Centre's VB-G RAM G Act, which replaces MGNREGA", "The Karnataka Budget 2026-27", "Delimitation of Assembly constituencies", "The Mahadayi water dispute"], 0,
     "The State wanted a resolution seeking the restoration of MGNREGA (Deccan Herald, Outlook)."),
    ("Which Karnataka minister, in charge of Law and Parliamentary Affairs, led the government's handling of the January 2026 joint session?",
     ["H. K. Patil", "G. Parameshwara", "Krishna Byre Gowda", "Priyank Kharge"], 0,
     "H. K. Patil explained the session's purpose and led the delegation that met the Governor (Deccan Herald, India TV)."),
    ("Assertion (A): In January 2026 the Karnataka Cabinet decided not to accept the VB-G RAM G Act and to challenge it legally.\nReason (R): The VB-G RAM G Act provides 125 days of wage employment per rural household.",
     AR, 1, "Both true, but the 125-day provision is not why the State opposed it; it objected to the repeal of MGNREGA and the new sharing pattern (Deccan Herald, PRS)."),
    ("In January 2026, what did the Karnataka Governor do with the Karnataka Hate Speech and Hate Crimes (Prevention and Control) Bill, 2025?",
     ["Reserved it for the consideration of the President", "Gave assent to it immediately", "Returned it to the Assembly for re-voting", "Referred it to the High Court"], 0,
     "The Governor reserved the Bill, passed in December 2025, for the President's consideration (Deccan Herald)."),
    ("A State Bill reserved by the Governor for the President's consideration is then dealt with under which Article of the Constitution?",
     ["Article 201", "Article 356", "Article 123", "Article 368"], 0, "Article 200 lets the Governor reserve a Bill; Article 201 covers the President's decision on it."),
    ("In January 2026, the Supreme Court set a deadline of 30 June 2026 for elections to the municipal corporations under the:",
     ["Greater Bengaluru Authority (GBA)", "Mysuru Urban Development Authority", "Hubballi-Dharwad Municipal Corporation", "Mangaluru City Corporation"], 0,
     "The deadline was later extended, first to 31 August and then to 31 December 2026 (The South First)."),
    ("How many municipal corporations function under the Greater Bengaluru Authority?",
     ["5", "3", "7", "8"], 0, "The GBA replaced the single BBMP with five corporations (The South First)."),
    ("The Greater Bengaluru Authority replaced which earlier civic body?",
     ["Bruhat Bengaluru Mahanagara Palike (BBMP)", "Bangalore Development Authority (BDA)", "BMRCL", "BWSSB"], 0, "The BBMP's elected council's term ended in 2020 (The South First)."),
    ("In January 2026, the Bangalore Development Authority (BDA) handed over how many of its layouts to the Greater Bengaluru Authority?",
     ["8", "2", "15", "20"], 0, "An Urban Development Department order of January 2026 transferred eight BDA layouts to the GBA (Deccan Herald)."),
    ("In January 2026, CM Siddaramaiah said tigers straying out of forests into villages of Mysuru district would be:",
     ["Captured and relocated to other forests", "Culled", "Sent to zoos abroad", "Left alone"], 0,
     "The rising tiger population near Bandipur and Nagarhole led to more sightings near villages (The Hindu, Deccan Chronicle)."),
    ("Which Karnataka tiger reserves border the villages of Mysuru district where tiger sightings rose in 2025–26?",
     ["Bandipur and Nagarhole", "Kali and Bhadra", "Dandeli and Anshi", "BRT and Kudremukh"], 0, "Tigers moved out of Bandipur and Nagarhole into farmlands (Deccan Chronicle)."),
    ("The final of the Vijay Hazare Trophy 2025–26, played on 18 January 2026 at the BCCI Centre of Excellence in Bengaluru, was won by:",
     ["Vidarbha", "Karnataka", "Saurashtra", "Delhi"], 0, "Vidarbha beat Saurashtra by 38 runs for their first title (ESPNcricinfo, ETV Bharat)."),
    ("Assertion (A): Karnataka could not defend its Vijay Hazare Trophy title in 2025–26.\nReason (R): Karnataka lost to Vidarbha in the semi-final on 15 January 2026.",
     AR, 0, "The semi-final defeat ended the defending champions' campaign (ESPNcricinfo)."),
    ("From January 2026, Karnataka's Excise Department began something for the first time since it was set up in 1965. What was it?",
     ["E-auction of unused retail liquor licences", "Total prohibition of liquor", "Online liquor home delivery", "A new excise tax on milk"], 0,
     "The auction was expected to raise about ₹1,000 crore (The South First)."),
    ("Under the modified Anna Bhagya scheme, the extra 5 kg of rice is replaced by an 'Indira Kit'. The kit contains:",
     ["Tur dal, green gram, sugar, salt and cooking oil", "Wheat, jowar and ragi", "Milk powder and eggs", "Vegetables and fruits"], 0,
     "The Cabinet approved the change in October 2025 (IREF, Deccan Herald)."),
    ("Match the Karnataka guarantee scheme with its benefit:\na. Shakti  b. Gruha Jyothi  c. Gruha Lakshmi  d. Yuva Nidhi\n1. Monthly allowance for unemployed graduates and diploma holders  2. ₹2,000 a month to the woman head of the family  3. Free electricity up to 200 units  4. Free travel for women in state-run buses",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Together with Anna Bhagya these are the State's five guarantee schemes."),
    ("Karnataka's farmer database FRUITS, used to verify farmers for government schemes, stands for:",
     ["Farmer Registration and Unified beneficiary InformaTion System", "Farmers' Rural Unified Income and Trade Scheme", "Food Resource Utilisation and Irrigation Tracking System", "Farm Revenue and Unified Insurance Tracking Service"], 0,
     "Each farmer gets a FRUITS ID (FID) linked to land records, bank account and Aadhaar (NeGD, Karnataka e-Governance)."),
]

JAN26_NATIONAL = [
    ("Who were the Chief Guests at India's 77th Republic Day parade on 26 January 2026?",
     ["António Costa and Ursula von der Leyen of the European Union", "The President of France", "The President of Indonesia", "The Prime Minister of Japan"], 0,
     "The top EU leadership attended together for the first time (All India Radio News)."),
    ("On 27 January 2026, at the 16th India–EU Summit in New Delhi, India and the European Union:",
     ["Concluded negotiations on a free trade agreement", "Signed a nuclear energy treaty", "Created a common currency", "Ended all trade ties"], 0,
     "It is the largest trade deal either side has concluded; it still needs formal signing and ratification (European Commission, PIB)."),
    ("Which two personalities received the Padma Vibhushan 2026 posthumously?",
     ["Dharmendra and V. S. Achuthanandan", "Rohit Sharma and N. Rajam", "K. T. Thomas and P. Narayanan", "Mammootty and R. Ganesh"], 0,
     "The five Padma Vibhushan awardees were Dharmendra, V. S. Achuthanandan, N. Rajam, K. T. Thomas and P. Narayanan (The Federal)."),
    ("How many Padma awards were announced in 2026?",
     ["131", "106", "139", "120"], 0, "5 Padma Vibhushan, 13 Padma Bhushan and 113 Padma Shri (The Federal)."),
    ("Nitin Nabin, who took charge on 20 January 2026, became the national president of which party?",
     ["Bharatiya Janata Party", "Indian National Congress", "Janata Dal (United)", "Rashtriya Janata Dal"], 0,
     "He succeeded J. P. Nadda and, at 45, became the party's youngest national president (All India Radio News)."),
    ("In January 2026, the Supreme Court stayed the implementation of which regulations?",
     ["The UGC Equity Regulations, 2026", "The RBI digital lending rules", "The SEBI F&O regulations", "The Motor Vehicles (Amendment) rules"], 0,
     "The stay came on 29 January 2026 after nationwide protests (2026 in India, Wikipedia)."),
    ("The VB-G RAM G Act, which replaces MGNREGA, guarantees how many days of wage employment per rural household in a year?",
     ["125 days", "100 days", "150 days", "90 days"], 0, "Viksit Bharat – Guarantee for Rozgar and Ajeevika Mission (Gramin); MGNREGA guaranteed at least 100 days (PRS India)."),
    ("According to the World Economic Forum's Global Risks Report 2026 (21st edition), the top short-term global risk is:",
     ["Geoeconomic confrontation", "Extreme weather", "Pandemics", "Asteroid impact"], 0, "It rose from third place in 2025 (Drishti IAS, WEF)."),
    ("On 13 January 2026, Tamil Nadu signed an MoU with Sarvam AI to set up India's first:",
     ["Sovereign AI Park, in Chennai", "Semiconductor fab", "Space port", "Quantum computer centre"], 0, "It aims to keep data within the State and build Tamil-language AI models (Drishti IAS)."),
    ("'Anjadip', delivered to the Indian Navy in January 2026, is:",
     ["An Anti-Submarine Warfare Shallow Water Craft built by GRSE, Kolkata", "An aircraft carrier", "A nuclear submarine", "A frigate built abroad"], 0, "The third indigenous ASW-SWC, delivered at INS Adyar, Chennai (Drishti IAS)."),
]

TOPICS = {
    "January 2026": [("1 · Karnataka", JAN26_KARNATAKA), ("2 · National", JAN26_NATIONAL)],
}
