"""Paper 1 · Computer Literacy · P1-CL-06 Unit 3 – MS Excel (2 sub-topics × 20).
Coverage (planner): simple formulas, alignment, formatting, merge cells, wrapping, pie/bar/line charts, print preview.
References: Microsoft Support – Excel functions, keyboard shortcuts and help pages (Microsoft 365 / Excel 2016–2021); NIELIT CCC
courseware. Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question
number) with new ones. Official answers come from KEA's final keys: Legislative Council Secretariat 2024 (Computer Operator P2,
Data Entry Operator P2, Junior Console Operator P2, Assistant P2 – booklet A1; final key 09-04-2025) and GTTC 2024 (Technician
Gr-III CS – booklet C1, Officer/Assistant KEC – booklet A1; final keys 30-12-2024). Questions from the KEA 2025–26 Kannada-
English-Computer papers have no published key; their answers are worked out by ExamSim and say so."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

FORMULAS = [
    # --- real previous-year questions ---
    ("Which of the following function is used to find the highest number in a series of number?",
     ["MAX (B1:B3)", "MAXIMUM (B1:B3)", "HIGH (B1:B3)", "HIGHEST (B1:B3)"], 0,
     "MAX returns the largest value; MIN the smallest." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q85"),
    ("In MS Excel, the cell reference for a range of cells that starts in cell C1 and goes over to column H and down to row 10 is",
     ["C1 : 10H", "1C : 10H", "C1 : H10", "C1 : R10"], 2,
     "A range is written top-left cell : bottom-right cell, column letter before row number." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q92"),
    ("Identify the correct statement in MS Excel.\n(a) You can only select cells that are adjacent to each other\n(b) Rows & Columns can be inserted by selecting cell command from insert menu",
     ["a is true but b is false", "Both a & b are true", "a is false but b is true", "Both a & b are false"], 2,
     "Non-adjacent cells can be selected with Ctrl + click, so (a) is false." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q93"),
    ("=SUM(A1:E1) formula in MS Excel performs which of the following task?",
     ["calculates the sum of all the values in cells from A1 to E1", "calculates the sum of values in cells A1 and E1 only", "calculates the sum of the values in cells A1 to A10", "calculates the sum of values in cells E1 to E10"], 0,
     "The colon means 'through': A1, B1, C1, D1 and E1." + KLC,
     "Legislative Council 2024 Data Entry Operator P2 · Q78"),
    ("In MS-EXCEL, the full form of 'PV' is",
     ["Past Value", "Present Value", "Post Value", "Pet Value"], 1,
     "PV() is a financial function; FV() gives the future value." + KLC,
     "Legislative Council 2024 Data Entry Operator P2 · Q98"),
    ("What is the purpose of spreadsheet program?",
     ["To process words", "To browse the internet", "To organize and analyze data", "To create presentation"], 2,
     "Spreadsheets organise data in rows and columns and calculate with formulas." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q74"),
    ("What is the maximum number of columns available in Excel 2016?",
     ["1024", "256", "16384", "4096"], 2,
     "Since Excel 2007 a sheet has 16,384 columns (A to XFD) and 1,048,576 rows; Excel 2003 had 256 columns." + GTTC,
     "GTTC 2024 Officer/Asst Gr-III KEC · Q96"),
    ("Macros means ____ in MS Excel.",
     ["Small add-on programs", "Programming language used to customize Ms Word", "Tool to use mail merge", "VBA Program used in MS Excel and can be called repetitively using VBA"], 3,
     "A macro is a recorded or written VBA procedure that automates repeated tasks." + GTTC,
     "GTTC 2024 Officer/Asst Gr-III KEC · Q84"),
    ("In Google Sheet, which sign is used in the formula for absolute reference?",
     ["Underscore ( _ )", "Dollar ($)", "Equal (=)", "Colon (:)"], 1,
     "As in Excel, $A$1 is an absolute reference." + NOTE,
     "KEA 2026 KEC (NHK, 11 Jan 2026) · Q79"),
    ("In Microsoft Excel, you have a table with customer names in column A, dates in column B, and sales amount in column C. You want to calculate the total sales for a specific customer within a given date range. Which formula would you use?",
     ["=SUM (A2:A10, \"CustomerName\", C2:C10)", "=SUMIFS (C2:C10, A2:A10, \"CustomerName\", B2:B10, \">01/01/2024\", B2:B10, \"<12/31/2024\")", "=SUMPRODUCT (A2:A10, \"CustomerName\", B2:B10, \">01/01/2024\")", "=AVERAGEIFS (C2:C10, A2:A10, \"CustomerName\", B2:B10, \">01/01/2024\", B2:B10, \"<12/31/2024\")"], 1,
     "SUMIFS adds the values in C that meet several conditions at once." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q90"),
    # --- new questions ---
    ("The intersection of a row and a column in a worksheet is called a:",
     ["Cell", "Range", "Workbook", "Field"], 0,
     PYQ + "Each cell has an address such as B5 (column B, row 5)."),
    ("Every formula in Excel must begin with:",
     ["An equal sign (=)", "A dollar sign ($)", "A hash (#)", "A colon (:)"], 0,
     PYQ + "Without '=', Excel treats the entry as text or a number."),
    ("In Excel, $A$1 is an absolute reference, A1 is relative, and A$1 is:",
     ["A mixed reference – the row is fixed, the column changes when copied", "An absolute reference", "A relative reference", "An error"], 0,
     PYQ + "Press F4 to cycle through the reference types."),
    ("Cell C1 contains =A1+B1. If C1 is copied to C2, the formula in C2 becomes:",
     ["=A2+B2", "=A1+B1", "=A1+B2", "=$A$1+$B$1"], 0,
     "Relative references adjust to their new position."),
    ("What value does =2+3*4 return in Excel?",
     ["14", "20", "24", "9"], 0,
     "Multiplication is done before addition."),
    ("What does =AVERAGE(10, 20, 30) return?",
     ["20", "60", "30", "10"], 0,
     "(10 + 20 + 30) / 3 = 20."),
    ("Which function counts only the cells that contain numbers in a range?",
     ["COUNT", "COUNTA", "COUNTBLANK", "SUM"], 0,
     "COUNTA counts all non-empty cells; COUNTIF counts cells meeting a condition."),
    ("Match the Excel error value with its usual cause:\na. #DIV/0!  b. #NAME?  c. #####  d. #REF!\n1. A referenced cell has been deleted  2. Column too narrow to show the value  3. Misspelt function name  4. Division by zero",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Error-value questions appear in KEA computer sections."),
    ("The keyboard shortcut for AutoSum in Excel is:",
     ["Alt + =", "Ctrl + S", "Shift + F3", "Ctrl + A"], 0,
     "It inserts =SUM() for the adjacent range."),
    ("Dragging the small square at the bottom-right of a selected cell to copy a value or continue a series (1, 2, 3 … or Jan, Feb …) uses the:",
     ["Fill handle (AutoFill)", "Format Painter", "Name Box", "Status bar"], 0,
     "Double-clicking the fill handle fills down to the end of the adjacent data."),
]

FORMAT_CHARTS = [
    # --- real previous-year questions ---
    ("Which of the following statements about Microsoft Excel are true?\n(i) Conditional Formatting can be used to highlight cells based on specific criteria like values, text or dates.\n(ii) The IF function can only return numeric values.\n(iii) PivotTables can be used to summarize and analyse data dynamically by dragging and dropping fields.\n(iv) The VLOOKUP function is case-sensitive by default.",
     ["i and iii are true", "ii and iv are true", "i, iii and iv are true", "i, ii and iii are true"], 0,
     "IF can return text too, and VLOOKUP is not case-sensitive." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q92"),
    ("In Microsoft Excel, which feature can be used to combine data from multiple worksheets into a single summary worksheet?",
     ["Power Query", "VLOOKUP()", "Data Validation", "Consolidate"], 3,
     "Data → Consolidate summarises ranges from several sheets." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q86"),
    ("Match the following shortcuts with its function in the excel workbook.\nShortcut Keys: a) Ctrl + W  b) Alt + N  c) Alt + M  d) Ctrl + O\nFunction: i. Go to insert tab  ii. Go to Formula Tab  iii. Close a workbook  iv. Hide selected columns",
     ["a – i, b – ii, c – iv, d – iii", "a – ii, b – i, c – iii, d – iv", "a – i, b – ii, c – iii, d – iv", "a – iii, b – i, c – ii, d – iv"], 3,
     "Ctrl + W closes the workbook; Alt + N opens Insert; Alt + M opens Formulas. KEA's key pairs d with hiding columns – that shortcut is Ctrl + 0 (zero)." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q80"),
    ("____ chart shows the proportional size of items that make up only one data series to the sum of the items.",
     ["Bar Chart", "Pie Chart", "Line Chart", "Area Chart"], 1,
     "A pie chart shows parts of a whole for one data series." + KLC,
     "Legislative Council 2024 Asst/Jr Asst P2 · Q96"),
    ("In MS Excel, ____ key combination is used to hide a row.",
     ["Ctrl+Delete", "Ctrl+F9", "Ctrl+9", "Alt+F9"], 2,
     "Ctrl + 9 hides rows; Ctrl + 0 hides columns; Ctrl + Shift + 9 unhides rows." + NOTE,
     "KEA 2026 KEC (NHK, 25 Jan 2026) · Q97"),
    ("Possible zoom range in MS-Excel is",
     ["10% to 400%", "15% to 300%", "20% to 400%", "10% to 200%"], 0,
     "Excel's zoom slider runs from 10% to 400%." + NOTE,
     "KEA 2025 KEC (HK, 21 Dec 2025) · Q99"),
    ("What does \"Data series\" indicate in a chart in Microsoft Excel?",
     ["Chart title", "Label on the Y axis", "Legend of the chart", "Numeric values plotted on a chart"], 3,
     "A data series is a row or column of values plotted together, e.g. one set of bars." + NOTE,
     "KEA 2026 KEC-2 (HK, 27 Apr 2026) · Q75"),
    ("Match List I with List II and select the correct answer from the codes given below the lists.\nList I (Chart type): a. Line chart  b. Pie chart  c. Column chart  d. Funnel chart\nList II (Description): i. Displays data as vertical bars  ii. Shows trends over time by connecting data points with lines  iii. Shows proportions of a whole as slices of a circle  iv. Shows stages in a process and the amount of data at each stage",
     ["a-iii, b-iv, c-ii, d-i", "a-ii, b-i, c-iii, d-iv", "a-ii, b-iii, c-i, d-iv", "a-i, b-ii, c-iv, d-iii"], 2,
     "Line – trends; pie – parts of a whole; column – vertical bars; funnel – stages of a process." + NOTE,
     "KEA 2026 KEC-1 (NHK, 26 Apr 2026) · Q91"),
    ("Match the following application software.\nList-I: a. Word processor  b. Spreadsheet  c. DBMS  d. Web browser\nList-II: i. Used to organize, manipulate and analyse numerical data  ii. Software for creating, storing and managing data  iii. Used for viewing websites and accessing information online  iv. Used for creating, editing and formatting text document",
     ["a – iv, b – ii, c – iii, d – i", "a – iv, b – i, c – iii, d – ii", "a – iv, b – i, c – ii, d – iii", "a – i, b – ii, c – iii, d – iv"], 2,
     "Word processor – text; spreadsheet – numbers; DBMS – stored data; browser – websites." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q78"),
    # --- new questions ---
    ("'Merge & Center' in Excel:",
     ["Combines the selected cells into one larger cell and centres the content", "Deletes the selected cells", "Sorts the data", "Adds the selected numbers"], 0,
     PYQ + "Often used for headings over a table; only the upper-left cell's content is kept."),
    ("To show a long entry on several lines inside the same cell, use:",
     ["Wrap Text", "Merge Cells", "AutoSum", "Freeze Panes"], 0,
     PYQ + "Alt + Enter inserts a manual line break within a cell."),
    ("The Alignment group, with options for horizontal and vertical alignment and text orientation, is on the ____ tab.",
     ["Home", "Insert", "Review", "View"], 0,
     "The same options are in the Format Cells dialog."),
    ("The keyboard shortcut that opens the Format Cells dialog box is:",
     ["Ctrl + 1", "Ctrl + F", "Ctrl + P", "Ctrl + K"], 0,
     "It has Number, Alignment, Font, Border, Fill and Protection tabs."),
    ("To show monthly sales over a year so that the trend is clear, the most suitable chart is a:",
     ["Line chart", "Pie chart", "Doughnut chart", "Funnel chart"], 0,
     PYQ + "Column or bar charts are best for comparing categories."),
    ("To compare the marks of five students in a subject, the most suitable chart is a:",
     ["Bar or column chart", "Pie chart of a single student", "Line chart with no categories", "Scatter chart of dates"], 0,
     PYQ + "Bars make comparisons between separate items easy."),
    ("The chart element that tells which colour stands for which data series is the:",
     ["Legend", "Plot area", "Gridline", "Axis title"], 0,
     "Chart elements are added from the '+' button or the Chart Design tab."),
    ("Pressing F11 with data selected in Excel:",
     ["Creates a default chart on a new chart sheet", "Saves the workbook", "Opens Help", "Prints the sheet"], 0,
     "Alt + F1 creates the chart on the same sheet."),
    ("Print Preview in Excel (File → Print) can be opened with:",
     ["Ctrl + F2 or Ctrl + P", "Ctrl + Z", "Ctrl + Y", "F7"], 0,
     PYQ + "It shows how the sheet will look on paper before printing."),
    ("To keep the heading row visible while scrolling down a long list, use:",
     ["View → Freeze Panes", "Insert → Header", "Home → Wrap Text", "Data → Sort"], 0,
     PYQ + "Freeze Top Row is the quickest option."),
    ("Consider the statements:\nI. Wrap Text displays long text on several lines within one cell.\nII. Merge & Center keeps the contents of every merged cell.\nWhich is/are correct?",
     I_II, 0, "Only the upper-left cell's content is kept when merging."),
]

TOPICS = {
    "Unit 3 – MS Excel": [("1 · Cells, Ranges, Formulas and Functions", FORMULAS),
                          ("2 · Formatting, Charts and Printing", FORMAT_CHARTS)],
}
