"""Paper 1 · Computer Literacy · P1-CL-01 Unit 1 – Introduction to Computer (2 sub-topics × 20).
References: P. K. Sinha, Computer Fundamentals; NCERT/KTBS ICT textbooks."""
from packlib import AR, I_II

BASICS = [
    ("A computer is best described as an electronic device that:",
     ["Accepts data, processes it according to instructions, stores it and produces output", "Only stores data permanently", "Only performs arithmetic on paper", "Thinks and decides on its own without instructions"], 0, "Input → process → output, with storage, all under program control."),
    ("The word 'computer' is derived from the word 'compute', which means:",
     ["To calculate", "To store", "To print", "To communicate"], 0, "Early computers were built mainly for calculation."),
    ("Which of the following is NOT a characteristic of a computer?",
     ["It has its own intelligence (IQ) and feelings", "High speed", "Accuracy", "Diligence – no tiredness"], 0, "A computer has zero IQ; it only follows the instructions given to it."),
    ("The principle GIGO means:",
     ["Garbage In, Garbage Out – wrong input or instructions give wrong output", "Good Input, Good Output – the computer corrects errors", "Graphics In, Graphics Out", "Gigabyte In, Gigabyte Out"], 0, "Computer errors are mostly caused by wrong data or wrong programs."),
    ("On the basis of how they work (the type of data they handle), computers are classified as:",
     ["Analog, digital and hybrid", "Micro, mini and super", "General-purpose and special-purpose", "Desktop, laptop and tablet"], 0, "Size gives micro/mini/mainframe/super; purpose gives general/special."),
    ("A car's speedometer showing speed by a moving needle is an example of an:",
     ["Analog device", "Digital computer", "Hybrid computer", "Supercomputer"], 0, "It measures a continuously changing quantity."),
    ("A machine in a hospital ICU that measures a patient's heartbeat and blood pressure (analog) and displays them as numbers (digital) is an example of a:",
     ["Hybrid computer", "Pure analog computer", "Mainframe", "Microcomputer only"], 0, "Hybrid computers combine analog measurement with digital processing."),
    ("Arrange computers by size and computing power, from smallest to largest:",
     ["Microcomputer → minicomputer → mainframe → supercomputer", "Mainframe → micro → mini → super", "Supercomputer → mainframe → mini → micro", "Mini → micro → super → mainframe"], 0, "Supercomputers are the fastest and most powerful."),
    ("PARAM, India's first supercomputer series, was developed by:",
     ["C-DAC, Pune", "ISRO, Bengaluru", "BARC, Mumbai", "IIT Delhi"], 0, "PARAM 8000 was released in 1991."),
    ("The speed of supercomputers is usually measured in:",
     ["FLOPS (floating-point operations per second)", "Kilobytes", "Pixels", "Words per minute"], 0, "Modern supercomputers work in petaFLOPS and exaFLOPS."),
    ("Large organisations such as banks and railway reservation systems, which support thousands of users at the same time, mainly use:",
     ["Mainframe computers", "Hybrid computers", "Analog computers", "Calculators"], 0, "Mainframes handle huge volumes of transactions reliably."),
    ("A computer built into a washing machine to control its washing cycle is called:",
     ["An embedded computer", "A supercomputer", "A workstation", "A mainframe"], 0, "Embedded systems are special-purpose computers inside other devices."),
    ("Desktop PCs, laptops, tablets and smartphones are all examples of:",
     ["Microcomputers", "Mainframes", "Supercomputers", "Analog computers"], 0, "They are built around a microprocessor and are used by one person at a time."),
    ("A computer that provides files, web pages or other services to other computers on a network is called a:",
     ["Server", "Client only", "Scanner", "Router"], 0, "Clients request services; servers provide them."),
    ("Match the computer with a typical use:\na. Supercomputer  b. Mainframe  c. Microcomputer  d. Embedded computer\n1. Controlling a microwave oven  2. Personal work at home or office  3. Bank transaction processing  4. Weather forecasting",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Weather forecasting needs the huge speed of supercomputers."),
    ("Consider the statements:\nI. A general-purpose computer can run many different kinds of programs.\nII. A special-purpose computer is designed for one particular task.\nWhich is/are correct?",
     I_II, 2, "E.g. a PC is general-purpose; a traffic-signal controller is special-purpose."),
    ("Consider the statements:\nI. Digital computers work with discrete values (digits).\nII. Analog computers are more accurate than digital computers.\nWhich is/are correct?",
     I_II, 0, "Digital computers are more accurate; analog ones work with continuous quantities."),
    ("Assertion (A): Computers can work for long hours without loss of accuracy.\nReason (R): Computers do not suffer from tiredness or lack of concentration.",
     AR, 0, "This quality is called diligence."),
    ("Assertion (A): A computer can decide by itself what problem to solve.\nReason (R): A computer works only according to the instructions given in a program.",
     AR, 3, "Because it only follows programs, it cannot decide by itself; R shows why A is false."),
    ("Assertion (A): Supercomputers are used for weather forecasting.\nReason (R): Supercomputers are the smallest and cheapest computers.",
     AR, 2, "A is true because forecasting needs enormous calculation; R is false – they are the largest and costliest."),
]

LANG_MEM_HW_SW = [
    ("The only language a computer can execute directly, written in 0s and 1s, is:",
     ["Machine language", "Assembly language", "High-level language", "HTML"], 0, "All other languages must be translated into machine language."),
    ("Assembly language uses:",
     ["Mnemonics (short codes) such as ADD and MOV", "Only 0s and 1s", "English sentences", "Pictures"], 0, "An assembler translates it into machine code."),
    ("Match the translator with its job:\na. Compiler  b. Interpreter  c. Assembler\n1. Translates assembly language to machine code  2. Translates and executes a high-level program line by line  3. Translates a whole high-level program at once",
     ["a-3, b-2, c-1", "a-2, b-3, c-1", "a-3, b-1, c-2", "a-1, b-2, c-3"], 0, "Compilers produce a complete object program; interpreters do not."),
    ("Which of the following is a high-level language?",
     ["Python", "Machine code", "Binary", "Assembly language"], 0, "High-level languages are close to human language and machine-independent."),
    ("1 kilobyte (KB) is equal to:",
     ["1024 bytes", "1000 bits", "1024 bits", "100 bytes"], 0, "2¹⁰ = 1024; 1 byte = 8 bits."),
    ("Half a byte (4 bits) is called a:",
     ["Nibble", "Word", "Bit", "Kilobit"], 0, "A byte has two nibbles."),
    ("Arrange in increasing order of size:",
     ["Byte, kilobyte, megabyte, gigabyte, terabyte", "Kilobyte, byte, gigabyte, megabyte, terabyte", "Byte, megabyte, kilobyte, terabyte, gigabyte", "Terabyte, gigabyte, megabyte, kilobyte, byte"], 0, "Each unit is 1024 times the previous one."),
    ("Which memory loses its contents when the power is switched off?",
     ["RAM", "ROM", "Hard disk", "Pen drive"], 0, "RAM is volatile; the others keep data without power."),
    ("The BIOS program that starts a computer is usually stored in:",
     ["ROM (firmware)", "RAM", "Cache only", "A DVD"], 0, "Software permanently stored in ROM chips is called firmware."),
    ("Arrange in order from fastest to slowest:",
     ["CPU registers, cache memory, RAM, hard disk", "Hard disk, RAM, cache, registers", "RAM, registers, hard disk, cache", "Cache, hard disk, registers, RAM"], 0, "Faster memory is smaller and costlier per byte."),
    ("A standard single-layer DVD can store about:",
     ["4.7 GB", "700 MB", "1.44 MB", "25 GB"], 0, "A CD holds about 700 MB and a single-layer Blu-ray about 25 GB."),
    ("Which of these is secondary (auxiliary) storage?",
     ["Solid-state drive (SSD)", "RAM", "Cache", "CPU registers"], 0, "Secondary storage is non-volatile and holds data permanently."),
    ("Intel and AMD are well-known manufacturers of:",
     ["Processors (CPUs)", "Printers only", "Operating systems", "Antivirus software"], 0, "Dell, HP and Lenovo make complete computers; Microsoft makes Windows."),
    ("Match the software with its type:\na. Windows  b. MS Word  c. Antivirus program  d. Device driver\n1. Software that lets the OS control a hardware device  2. Utility software  3. Application software  4. Operating system (system software)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Operating systems and drivers are system software."),
    ("Software whose source code is freely available to be studied, changed and shared, such as Linux, is called:",
     ["Open-source software", "Proprietary software", "Shareware only", "Firmware"], 0, "Windows and MS Office are proprietary (closed-source)."),
    ("Software that can be used free for a trial period, after which the user is asked to pay, is called:",
     ["Shareware", "Freeware", "Open source", "Malware"], 0, "Freeware is free to use without payment."),
    ("Consider the statements:\nI. Hardware refers to the physical parts of a computer.\nII. Software can work without any hardware.\nWhich is/are correct?",
     I_II, 0, "Hardware and software need each other: software runs on hardware."),
    ("Consider the statements:\nI. ATMs and online banking are applications of computers in banking.\nII. E-governance uses computers to deliver government services to citizens.\nWhich is/are correct?",
     I_II, 2, "Both are common applications of computers."),
    ("Assertion (A): Programs written in a high-level language must be translated before execution.\nReason (R): A computer can directly execute only machine language.",
     AR, 0, "Compilers or interpreters convert them into machine code."),
    ("Assertion (A): RAM is used to store data permanently.\nReason (R): RAM is volatile memory.",
     AR, 3, "Because RAM is volatile, it cannot store data permanently; R shows why A is false."),
]

TOPICS = {
    "Unit 1 – Introduction to Computer": [("1 · What is a Computer, Categories and Types", BASICS),
                                          ("2 · Languages, Applications, Memory, Hardware and Software", LANG_MEM_HW_SW)],
}
