"""Paper 1 · Computer Literacy · P1-CL-07 Unit 3 – MS Paint (2 sub-topics × 20).
Coverage (planner): applications and tools in Paint.
References: Microsoft Support pages for Paint (Windows 10 / 11), Paint's own ribbon and keyboard shortcuts, NCERT / DSERT ICT
textbooks (classes 3–6). Only one REAL previous-year question fits this topic (KEA 2026 Kannada-English-Computer paper, 26 Apr 2026;
answer worked out by ExamSim). The rest are "PYQ pattern" questions on Paint themes common in KEA / KPSC / TET computer sections.
Questions describe the classic ribbon Paint of Windows 7–11, which school labs use."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KPSC / TET computer literacy). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

BASICS = [
    ("What are .bas, .doc, .htm, .png, .bmp examples of in computing ?",
     ["Protocols", "Domains", "Database", "Extensions"], 3,
     "They are file-name extensions that show the file type; .png and .bmp are image formats that Paint saves." + NOTE,
     "KEA 2026 KEC-1 (NHK, 26 Apr 2026) · Q96"),
    ("MS Paint is mainly used to:",
     ["Draw and edit simple pictures (raster images)", "Type letters with mail merge", "Create spreadsheets", "Manage databases"], 0,
     PYQ + "It is a simple bitmap (raster) graphics editor that comes free with Windows."),
    ("Which command typed in the Run box (Win + R) opens Paint?",
     ["mspaint", "paint.doc", "pbrush.xls", "calc"], 0, "calc opens Calculator; notepad opens Notepad."),
    ("The default file format in which Paint (Windows 7 and later) saves a picture is:",
     ["PNG", "DOCX", "MP3", "TXT"], 0, PYQ + "Older versions (Windows XP and earlier) saved as BMP by default."),
    ("Which of these file types can NOT be saved from MS Paint?",
     ["MP4 video", "JPEG", "GIF", "BMP"], 0, "Paint saves PNG, JPEG, BMP, GIF, TIFF and HEIC (newer versions)."),
    ("The two main ribbon tabs of Paint in Windows 7–10 are:",
     ["Home and View", "Insert and Design", "Data and Review", "Mailings and References"], 0,
     "Home holds Clipboard, Image, Tools, Shapes, Colours; View holds Zoom, Show or hide, Display."),
    ("The drawing area in Paint, where the picture is made, is called the:",
     ["Canvas", "Slide", "Worksheet", "Template"], 0, PYQ + "The canvas size can be changed by dragging its handles or with Resize / Image Properties."),
    ("In Paint, 'Colour 1' and 'Colour 2' are the:",
     ["Foreground colour (left mouse button) and background colour (right mouse button)", "Two colours of the title bar",
      "Colours of the ruler", "Colours used only for text"], 0, "Drawing with the right mouse button uses Colour 2."),
    ("Which Paint tool fills a closed area with the selected colour?",
     ["Fill with colour (paint bucket)", "Pencil", "Magnifier", "Colour picker"], 0,
     PYQ + "If the area has a gap in its outline, the colour spills into the surrounding area."),
    ("The Colour picker tool in Paint is used to:",
     ["Pick a colour from the picture and set it as the current colour", "Remove all colours", "Print in colour", "Save the colour palette"], 0,
     "It looks like an eye-dropper."),
    ("Which tool draws thin, free-form lines one pixel wide in Paint?",
     ["Pencil", "Airbrush", "Fill with colour", "Text"], 0, "Brushes draw thicker strokes with textures such as calligraphy, oil, crayon and watercolour."),
    ("The Paint brush that sprays dots of colour like a spray can is the:",
     ["Airbrush", "Calligraphy brush", "Marker", "Natural pencil"], 0, PYQ + "Paint's brushes: brush, calligraphy (2), airbrush, oil, crayon, marker, natural pencil, watercolour."),
    ("The Eraser tool in Paint replaces the erased area with:",
     ["Colour 2 (the background colour)", "Colour 1", "Black always", "Transparent pixels always"], 0,
     "With the right mouse button it replaces only Colour 1 with Colour 2."),
    ("The 'A' button in the Tools group of Paint is used to:",
     ["Add text to the picture", "Increase font size in Word", "Align objects", "Open the Address book"], 0,
     PYQ + "A Text tab appears with font, size, bold, italic and transparent / opaque background options."),
    ("To zoom in on part of a picture in Paint, you use the:",
     ["Magnifier tool or the zoom slider", "Eraser", "Fill with colour", "Crop button"], 0,
     "Ctrl + Page Up zooms in and Ctrl + Page Down zooms out."),
    ("Which Paint command changes the canvas width and height in pixels or other units and sets colour / black-and-white?",
     ["Image Properties (Ctrl + E)", "Crop", "Invert selection", "Flip vertical"], 0, "Resize and Skew (Ctrl + W) resizes the picture by percentage or pixels."),
    ("Consider the statements:\nI. Paint is a vector graphics program.\nII. Paint pictures are made of pixels.",
     I_II, 1, "Paint is a raster (bitmap) editor; vector programs include CorelDRAW and Illustrator."),
    ("Assertion (A): A JPEG picture saved from Paint may lose some quality.\nReason (R): JPEG uses lossy compression.",
     AR, 0, "PNG uses lossless compression and keeps every pixel."),
    ("Which keyboard shortcut saves a picture in Paint?",
     ["Ctrl + S", "Ctrl + P", "Ctrl + N", "Ctrl + O"], 0, PYQ + "F12 opens Save As; Ctrl + P prints, Ctrl + N starts a new picture."),
    ("In Windows 10, the newer app that added 3D shapes and effects alongside classic Paint was:",
     ["Paint 3D", "Photos", "Snipping Tool", "WordPad"], 0, "It arrived with the Creators Update (2017); Windows 11 Paint later added layers and background removal."),
]

EDITING = [
    ("To draw a perfect circle with the Oval shape in Paint, hold down the:",
     ["Shift key while dragging", "Ctrl key while dragging", "Alt key while dragging", "Tab key while dragging"], 0,
     PYQ + "Shift also gives a perfect square with Rectangle and straight horizontal, vertical or 45° lines."),
    ("The Shapes group of Paint lets you choose an Outline and a Fill. 'Fill: Solid colour' fills the shape with:",
     ["Colour 2", "Colour 1", "White always", "A picture"], 0, "The outline uses Colour 1."),
    ("Which Paint selection type lets you draw any shape around the part to select?",
     ["Free-form selection", "Rectangular selection", "Select all", "Invert selection"], 0, "Rectangular selection selects a rectangle; Select all is Ctrl + A."),
    ("'Transparent selection' in Paint means that when a selection is moved:",
     ["Its background colour (Colour 2) is not copied, so the picture underneath shows through", "The selection becomes invisible",
      "The selection is deleted", "Only the outline moves"], 0, PYQ + "Useful when placing one drawing over another."),
    ("Which Paint command removes everything outside the current selection?",
     ["Crop (Ctrl + Shift + X)", "Delete", "Invert selection", "Rotate"], 0, "Delete removes the selected part instead."),
    ("To turn a picture upside down as in a mirror image across a horizontal axis, use:",
     ["Flip vertical", "Flip horizontal", "Rotate right 90°", "Skew"], 0, PYQ + "Flip horizontal gives a left–right mirror image."),
    ("The Rotate options available in Paint are:",
     ["Rotate right 90°, rotate left 90°, rotate 180°, flip vertical, flip horizontal", "Rotate 30° and 60° only",
      "Rotate any angle by typing it", "No rotation is possible"], 0, "Skewing (in Resize and Skew) slants the picture by degrees."),
    ("'Skew' in Paint is used to:",
     ["Slant the picture or selection horizontally or vertically by some degrees", "Change the colour", "Add text", "Remove the background"], 0,
     "It is in the Resize and Skew dialogue (Ctrl + W)."),
    ("The Paint feature 'Edit colours' is used to:",
     ["Create a custom colour by choosing hue, saturation and brightness or RGB values", "Delete the picture",
      "Change the file name", "Print the colour palette"], 0, PYQ + "The custom colour is added to the palette for use."),
    ("Which items can be shown or hidden from the View tab of Paint?",
     ["Rulers, gridlines and the status bar", "Formulas and gridlines", "Slides and notes", "Header and footer"], 0, "Ctrl + R shows rulers and Ctrl + G gridlines."),
    ("The status bar at the bottom of Paint shows:",
     ["Pointer position, selection size, picture size and zoom", "Word count", "Sum of selected cells", "Slide number"], 0,
     "Picture size is shown in pixels."),
    ("To copy part of a picture from Paint into a Word document, you would:",
     ["Select it, press Ctrl + C, then paste it in Word with Ctrl + V", "Use Ctrl + X in Word first", "Save it as a .txt file", "Use Format Painter"], 0,
     PYQ + "Paint's Clipboard group has Cut, Copy and Paste; Paste from can insert another picture file."),
    ("Which shortcut undoes the last action in Paint?",
     ["Ctrl + Z", "Ctrl + Y", "Ctrl + U", "Ctrl + D"], 0, "Ctrl + Y redoes the action."),
    ("A screenshot taken with the Print Screen key can be pasted into Paint for editing using:",
     ["Ctrl + V", "Ctrl + P", "Alt + F4", "Ctrl + B"], 0, PYQ + "Alt + Print Screen copies only the active window."),
    ("In Paint, the Text tool's 'Transparent' background option means the text:",
     ["Is placed without a box of Colour 2 behind it", "Becomes invisible", "Is deleted when saved", "Is always black"], 0,
     "'Opaque' puts the text on a box filled with Colour 2."),
    ("Which of the following can be used to set a Paint picture as the desktop wallpaper?",
     ["File → Set as desktop background", "Home → Crop", "View → Gridlines", "Image → Skew"], 0, "Options: Fill, Tile or Centre."),
    ("Consider the statements:\nI. In Paint, Ctrl + W opens the Resize and Skew dialogue.\nII. In Paint, Ctrl + E opens Image Properties.",
     I_II, 2, "Both shortcuts are correct."),
    ("Assertion (A): The Fill with colour tool may colour the whole background.\nReason (R): The area clicked had a gap in its outline.",
     AR, 0, "Close all gaps (zoom in to check) before filling."),
    ("Assertion (A): In Paint, 'Invert selection' deletes the selected part.\nReason (R): Invert selection selects everything that was not selected.",
     AR, 3, "Invert selection only swaps the selected and unselected areas; it does not delete anything."),
    ("Match the Paint item with its use:\na. Pencil  b. Fill with colour  c. Colour picker  d. Magnifier\n1. Free-hand thin line  2. Colour a closed area  3. Copy a colour from the picture  4. Zoom in",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Tool matching is a common question type."),
]

TOPICS = {
    "Unit 3 – MS Paint": [("1 · Paint Window, Tools, Brushes and Colours", BASICS),
                          ("2 · Shapes, Selection, Image Editing and Shortcuts", EDITING)],
}
