"""Paper 1 · Computer Literacy · P1-CL-03 Unit 2 – Window Settings & Advanced Windows (2 sub-topics × 20).
References: Microsoft Windows 10/11 support documentation (Settings, Control Panel, keyboard shortcuts); NIELIT CCC courseware."""
from packlib import AR, I_II

CONTROL_PANEL = [
    ("In Windows, the Control Panel is used mainly to:",
     ["View and change system settings such as hardware, programs, users and appearance", "Write documents", "Browse the Internet", "Play videos only"], 0, "In Windows 10/11 many of these settings have moved to the Settings app."),
    ("Which keyboard shortcut opens the Settings app in Windows 10/11?",
     ["Windows key + I", "Windows key + E", "Ctrl + S", "Alt + F4"], 0, "Win + E opens File Explorer."),
    ("To uninstall a program using the Control Panel, you go to:",
     ["Programs → Programs and Features", "Appearance → Fonts", "Clock and Region", "Ease of Access"], 0, "In Settings it is Apps → Installed apps."),
    ("The picture displayed as the background of the Windows desktop is called the:",
     ["Wallpaper (desktop background)", "Screen saver", "Icon", "Taskbar"], 0, "It is changed under Personalization → Background."),
    ("A moving picture or pattern that appears when the computer is idle for a set time is a:",
     ["Screen saver", "Wallpaper", "Theme", "Cursor"], 0, "It was originally used to prevent image burn-in on CRT monitors."),
    ("A Windows 'theme' is:",
     ["A combination of desktop background, colours, sounds and mouse cursor", "A type of virus", "A word-processing template only", "A network setting"], 0, "Applying a theme changes several appearance settings at once."),
    ("Changing screen resolution in Windows is done from:",
     ["Settings → System → Display", "Settings → Accounts", "Control Panel → Programs", "Settings → Privacy"], 0, "Right-clicking the desktop and choosing Display settings also opens it."),
    ("A higher screen resolution (e.g. 1920 × 1080 instead of 1366 × 768) means:",
     ["More pixels, so items look smaller and sharper and more fits on screen", "Fewer pixels and bigger items", "The monitor becomes larger physically", "Colours are removed"], 0, "Resolution is the number of pixels horizontally × vertically."),
    ("Which Control Panel/Settings category is used to set the system date, time and time zone?",
     ["Clock and Region (Time & language in Settings)", "Hardware and Sound", "User Accounts", "Programs"], 0, "Region settings also control date and number formats."),
    ("Ease of Access (Accessibility) settings include:",
     ["Narrator, Magnifier and On-Screen Keyboard", "Disk Cleanup only", "Antivirus scans", "Printer drivers only"], 0, "They help users with visual, hearing or motor difficulties."),
    ("The Windows tool that reads aloud text on the screen for visually impaired users is:",
     ["Narrator", "Magnifier", "Notepad", "Paint"], 0, "Magnifier enlarges part of the screen."),
    ("To add a new user account on a Windows PC, you use:",
     ["User Accounts in Control Panel / Accounts in Settings", "Device Manager", "Task Manager", "Disk Management"], 0, "Accounts can be standard users or administrators."),
    ("Device Manager in Windows is used to:",
     ["View hardware devices and update, disable or uninstall their drivers", "Edit photos", "Create presentations", "Send e-mail"], 0, "A yellow warning sign marks a device with a problem."),
    ("Mouse settings in Control Panel allow you to:",
     ["Swap primary and secondary buttons and change pointer speed and double-click speed", "Change the monitor's brightness only", "Install printers", "Delete files"], 0, "Left-handed users often swap the buttons."),
    ("Which setting controls how long the computer waits before turning off the display or sleeping?",
     ["Power Options (Power & sleep)", "Fonts", "Themes", "Sound"], 0, "It is found under System in Settings or Hardware and Sound in Control Panel."),
    ("Match the Windows item with its purpose:\na. Device Manager  b. Narrator  c. Programs and Features  d. Personalization\n1. Changing background, colours and themes  2. Uninstalling software  3. Reading screen text aloud  4. Managing hardware drivers",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each is found through Control Panel or Settings."),
    ("Consider the statements:\nI. The screen saver and the desktop background are the same thing.\nII. Screen resolution can be changed in Display settings.\nWhich is/are correct?",
     I_II, 1, "The background is always visible behind windows; the screen saver appears only when the PC is idle."),
    ("Consider the statements:\nI. Windows lets you change the mouse pointer size and colour.\nII. Windows lets left-handed users swap the mouse buttons.\nWhich is/are correct?",
     I_II, 2, "Both are available in mouse and accessibility settings."),
    ("Assertion (A): The Control Panel lets a user uninstall programs.\nReason (R): Programs and Features lists the installed software with an Uninstall option.",
     AR, 0, "That is where uninstallation is done."),
    ("Assertion (A): A higher screen resolution makes icons appear larger.\nReason (R): Resolution is the number of pixels displayed on the screen.",
     AR, 3, "More pixels make each item smaller on the same screen; A is false."),
]

MENUS_SHORTCUTS = [
    ("Right-clicking an item in Windows usually opens a:",
     ["Context (shortcut) menu with actions for that item", "New window of the Control Panel", "Help page on the Internet", "Shutdown dialog"], 0, "The options depend on what was right-clicked."),
    ("The keyboard shortcut to copy selected items is:",
     ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"], 0, "Ctrl + X cuts and Ctrl + V pastes."),
    ("The keyboard shortcut to undo the last action is:",
     ["Ctrl + Z", "Ctrl + Y", "Ctrl + U", "Ctrl + A"], 0, "Ctrl + Y usually redoes."),
    ("Alt + Tab is used to:",
     ["Switch between open windows", "Close the current window", "Open the Start menu", "Lock the computer"], 0, "Keep Alt held and press Tab repeatedly to move through windows."),
    ("Alt + F4 is used to:",
     ["Close the active window (or shut down when on the desktop)", "Rename a file", "Copy a file", "Open Task Manager"], 0, "On the desktop it opens the Shut Down Windows dialog."),
    ("Which shortcut opens Task Manager directly?",
     ["Ctrl + Shift + Esc", "Ctrl + Alt + Tab", "Win + D", "Ctrl + P"], 0, "Ctrl + Alt + Del opens a screen that includes Task Manager."),
    ("Windows key + D is used to:",
     ["Show or hide the desktop", "Open File Explorer", "Lock the computer", "Open Settings"], 0, "Win + L locks the computer."),
    ("Windows key + L is used to:",
     ["Lock the computer", "Log off permanently and delete files", "Open the Run box", "Minimise all windows"], 0, "It protects the PC when you step away."),
    ("Windows key + R opens:",
     ["The Run dialog box", "The Recycle Bin", "Settings", "The Start menu only"], 0, "You can type commands such as 'notepad' or 'control' there."),
    ("The F2 key, with a file selected in File Explorer, is used to:",
     ["Rename the file", "Delete the file", "Open Help", "Refresh the window"], 0, "F5 refreshes; F1 opens Help."),
    ("Shift + Delete on a file in Windows:",
     ["Deletes it permanently without sending it to the Recycle Bin", "Moves it to the Recycle Bin", "Copies the file", "Renames the file"], 0, "Windows asks for confirmation first."),
    ("The bar at the bottom of the Windows screen showing the Start button, pinned and open programs is the:",
     ["Taskbar", "Title bar", "Menu bar", "Status bar"], 0, "The notification area (system tray) is at its right end."),
    ("The bar at the top of a window that shows its name and the Minimise, Maximise and Close buttons is the:",
     ["Title bar", "Taskbar", "Scroll bar", "Status bar"], 0, "Double-clicking it maximises or restores the window."),
    ("A toolbar in an application is:",
     ["A row of buttons or icons giving quick access to commonly used commands", "A list of files on disk", "A hardware component", "A type of virus"], 0, "The Quick Access Toolbar in MS Office is an example."),
    ("A menu item followed by three dots (…), such as 'Save As…', means that choosing it will:",
     ["Open a dialog box asking for more information", "Run immediately with no questions", "Close the program", "Open a submenu only"], 0, "A small arrow (▶) indicates a submenu."),
    ("Snapping a window to the left half of the screen can be done with:",
     ["Windows key + Left arrow", "Ctrl + Left arrow", "Alt + Left arrow", "Shift + Left arrow"], 0, "Windows 11 also offers Snap layouts with Win + Z."),
    ("Match the shortcut with its action:\na. Ctrl + A  b. Ctrl + X  c. Win + E  d. Ctrl + Shift + Esc\n1. Open Task Manager  2. Open File Explorer  3. Cut  4. Select all",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These are standard Windows shortcuts."),
    ("Consider the statements:\nI. Shift + Delete sends a file to the Recycle Bin.\nII. Ctrl + V pastes the contents of the clipboard.\nWhich is/are correct?",
     I_II, 1, "Shift + Delete bypasses the Recycle Bin."),
    ("Assertion (A): Keyboard shortcuts can make work faster.\nReason (R): They perform commands without navigating through menus with the mouse.",
     AR, 0, "That is their purpose."),
    ("Assertion (A): Win + L locks the computer.\nReason (R): Win + D closes all open programs permanently.",
     AR, 2, "A is true; R is false – Win + D only shows the desktop; programs keep running."),
]

TOPICS = {
    "Unit 2 – Window Settings & Advanced Windows": [("1 · Control Panel and Personalisation", CONTROL_PANEL),
                                                    ("2 · Menus, Toolbars, Right-click and Shortcuts", MENUS_SHORTCUTS)],
}
