"""Paper 1 · Computer Literacy · P1-CL-04 Unit 3 – MS Office (Word) (2 sub-topics × 20).
References: Microsoft Support – Word keyboard shortcuts and help pages (Microsoft 365 / Word 2016–2021); NIELIT CCC courseware.
Explanations starting "PYQ pattern" follow questions that recur in KPSC / KEA / SSC computer-knowledge sections."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "

DOC_SETTING = [
    ("The default file extension of a document saved in Word 2007 and later versions is:",
     [".docx", ".doc", ".txt", ".xlsx"], 0, PYQ + "Word 97–2003 used .doc; .docx is an XML-based format."),
    ("A Word template file (without macros) has the extension:",
     [".dotx", ".docx", ".pptx", ".xltx"], 0, "Templates give a ready-made layout for new documents."),
    ("Which key opens the 'Save As' dialog box in Word?",
     ["F12", "F7", "F5", "F1"], 0, PYQ + "F7 checks spelling, F5 opens Go To, F1 opens Help."),
    ("The difference between Save and Save As is that Save As:",
     ["Lets you save the document with a new name, location or format", "Deletes the old file", "Prints the document", "Only works for new documents"], 0, "Save simply updates the existing file."),
    ("Page orientation (portrait or landscape) is changed from the:",
     ["Layout tab → Orientation", "Insert tab → Table", "Review tab → Track Changes", "View tab → Zoom"], 0, "Older versions call it the Page Layout tab."),
    ("A document page wider than it is tall has:",
     ["Landscape orientation", "Portrait orientation", "Narrow margins", "Two columns"], 0, "Portrait is taller than it is wide."),
    ("The standard A4 paper size is:",
     ["210 mm × 297 mm", "8.5 in × 11 in", "297 mm × 420 mm", "148 mm × 210 mm"], 0, "8.5 × 11 inches is US Letter; 297 × 420 mm is A3."),
    ("The blank space between the text and the edges of a page is called the:",
     ["Margin", "Gutter only", "Indent", "Border"], 0, "Margins are set under Layout → Margins."),
    ("Text that appears at the top of every page, such as a document title, is placed in the:",
     ["Header", "Footer", "Footnote", "Text box"], 0, PYQ + "The footer is at the bottom; both are inserted from the Insert tab."),
    ("Which keyboard shortcut inserts a manual page break in Word?",
     ["Ctrl + Enter", "Shift + Enter", "Alt + Enter", "Ctrl + Tab"], 0, PYQ + "Shift + Enter inserts a line break within the same paragraph."),
    ("To show text in newspaper-style side-by-side columns, you use:",
     ["Layout → Columns", "Insert → Table only", "Home → Bullets", "View → Ruler"], 0, "Column breaks can be added from Layout → Breaks."),
    ("Faint text such as 'CONFIDENTIAL' behind the main text on every page is a:",
     ["Watermark", "Header", "Footnote", "Hyperlink"], 0, "It is added from the Design tab (Page Layout in older versions)."),
    ("Which Word feature creates personalised letters for many recipients from one main document and a data list?",
     ["Mail Merge", "Track Changes", "Macro", "Thesaurus"], 0, PYQ + "It is on the Mailings tab."),
    ("Word can save a document directly in which format for sharing without allowing easy editing?",
     ["PDF", "EXE", "MP3", "JPG only"], 0, "Use File → Save As and choose PDF."),
    ("AutoRecover in Word:",
     ["Periodically saves recovery information so work can be restored after a crash", "Corrects spelling automatically", "Recovers deleted e-mails", "Prints automatically"], 0, "The interval is set in File → Options → Save."),
    ("Line spacing of a paragraph is changed from the:",
     ["Paragraph group of the Home tab", "Mailings tab", "Review tab", "References tab"], 0, "Common values are 1.0, 1.15, 1.5 and 2.0."),
    ("Match the Word tab with a command found on it:\na. Insert  b. Layout  c. Mailings  d. Review\n1. Track Changes  2. Start Mail Merge  3. Margins  4. Header",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Knowing where commands live on the Ribbon is often tested."),
    ("Consider the statements:\nI. Portrait orientation is taller than it is wide.\nII. Headers appear at the bottom of each page.\nWhich is/are correct?",
     I_II, 0, "Footers appear at the bottom."),
    ("Assertion (A): Save As can be used to keep the original file unchanged while saving an edited copy.\nReason (R): Save As saves the document under a new name or location.",
     AR, 0, "The original file remains as it was last saved."),
    ("Assertion (A): Shift + Enter starts a new page.\nReason (R): Ctrl + Enter inserts a page break.",
     AR, 3, "Shift + Enter inserts a line break; A is false, R is true."),
]

EDITING = [
    ("In Word 2007 and later, the menus and toolbars of older versions were replaced by the:",
     ["Ribbon", "Status bar", "Title bar", "Taskbar"], 0, PYQ + "The Ribbon groups commands into tabs such as Home, Insert and Layout."),
    ("The small customisable toolbar above or below the Ribbon, holding commands such as Save and Undo, is the:",
     ["Quick Access Toolbar", "Status bar", "Formula bar", "Navigation pane"], 0, "You can add your most-used commands to it."),
    ("Which shortcut makes selected text bold?",
     ["Ctrl + B", "Ctrl + I", "Ctrl + U", "Ctrl + D"], 0, PYQ + "Ctrl + I = italic, Ctrl + U = underline; Ctrl + D opens the Font dialog."),
    ("Which shortcut centres the selected paragraph?",
     ["Ctrl + E", "Ctrl + C", "Ctrl + J", "Ctrl + R"], 0, PYQ + "Ctrl + L left, Ctrl + R right, Ctrl + J justify."),
    ("Ctrl + J applies which alignment?",
     ["Justify (aligned to both margins)", "Left", "Right", "Centre"], 0, "Justified text has straight edges on both sides."),
    ("Which shortcut opens Find and Replace with the Replace tab selected?",
     ["Ctrl + H", "Ctrl + F", "Ctrl + R", "Ctrl + G"], 0, PYQ + "Ctrl + F opens Find (Navigation pane); Ctrl + G opens Go To."),
    ("Which key starts the spelling and grammar check in Word?",
     ["F7", "F12", "F2", "F9"], 0, PYQ + "Shift + F7 opens the Thesaurus."),
    ("Shift + F7 in Word opens the:",
     ["Thesaurus", "Spell check", "Print preview", "Save As dialog"], 0, "It suggests synonyms for the selected word."),
    ("Which shortcut redoes (or repeats) the last action?",
     ["Ctrl + Y", "Ctrl + Z", "Ctrl + R", "Ctrl + X"], 0, "Ctrl + Z undoes it."),
    ("Ctrl + Home moves the cursor to the:",
     ["Beginning of the document", "Beginning of the current line", "End of the document", "Next page"], 0, "Ctrl + End moves to the end of the document; Home alone goes to the start of the line."),
    ("The Format Painter tool is used to:",
     ["Copy formatting from one piece of text and apply it to another", "Draw pictures", "Change the page colour only", "Paint table borders only"], 0, PYQ + "Double-click it to apply the format to several places."),
    ("The Office Clipboard in Word can hold up to how many copied items?",
     ["24", "10", "1", "100"], 0, PYQ + "The Windows clipboard alone holds only the last item (without clipboard history)."),
    ("To arrange a list of names in alphabetical order in Word, you use:",
     ["Home → Paragraph group → Sort", "Insert → Symbol", "Review → Spelling", "View → Outline only"], 0, "Sort can order text, numbers or dates, ascending or descending."),
    ("Which shortcut makes the selected text superscript (as in x²)?",
     ["Ctrl + Shift + =", "Ctrl + =", "Ctrl + Shift + S", "Alt + ="], 0, "Ctrl + = makes subscript (as in H₂O)."),
    ("Ctrl + Shift + > applied to selected text:",
     ["Increases the font size", "Decreases the font size", "Makes it bold", "Moves it to the next page"], 0, "Ctrl + Shift + < decreases the font size."),
    ("Track Changes, used when several people edit a document, is found on the:",
     ["Review tab", "Home tab", "Insert tab", "Layout tab"], 0, "Each change can later be accepted or rejected."),
    ("Match the shortcut with its action in Word:\na. Ctrl + L  b. Ctrl + U  c. Ctrl + P  d. Ctrl + N\n1. New document  2. Print  3. Underline  4. Align left",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "A frequent matching question."),
    ("Consider the statements:\nI. Ctrl + F opens Find in Word.\nII. Ctrl + H opens the Replace tab of Find and Replace.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Format Painter saves time when formatting documents.\nReason (R): It copies formatting, not text, from one place to another.",
     AR, 0, "Only the look is transferred."),
    ("Assertion (A): F7 opens the Thesaurus in Word.\nReason (R): Word can check spelling and grammar.",
     AR, 3, "F7 starts the spelling and grammar check; Shift + F7 opens the Thesaurus. A is false, R is true."),
]

TOPICS = {
    "Unit 3 – MS Office (Word)": [("1 · Document Setting, Page Layout and Save Options", DOC_SETTING),
                                  ("2 · Editing, Toolbars, Sorting and Shortcuts", EDITING)],
}
