"""Paper 1 · Computer Literacy · P1-CL-08 Unit 3 – Google Platform (2 sub-topics × 20).
Coverage (planner): Google Classroom, Google Form, Google Drive, digital repository.
References: Google Workspace for Education help centre (Classroom, Forms, Drive, Docs, Sheets, Meet), NCERT / DSERT ICT texts,
DIKSHA and NDLI (National Digital Library of India) websites. REAL previous-year questions come from GTTC 2024 Lecturer CS and the
KEA 2025–26 Kannada-English-Computer papers; KEA's key could not be matched for the GTTC question and the KEA papers have no
published key, so their answers were worked out by ExamSim and say so."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KPSC / TET computer literacy). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

CLASSROOM_FORMS = [
    ("Which Google product allows you to Survey, Quiz or question students with multiple choice open ended and other questions?",
     ["Google drawing", "Google slides", "Google forms", "Google Docs"], 2,
     "Google Forms creates surveys and self-grading quizzes; responses can be viewed in Google Sheets." + NOTE, "GTTC 2024 Lecturer CS · Q1"),
    ("State which of the following statements about Google Classroom are true or false.\n(a) Teachers can create, distribute and grade assignments efficiently.\n(b) There are no accessibility features provided in Google Classroom.",
     ["(a) true, (b) true", "(a) true, (b) false", "(a) false, (b) true", "(a) false, (b) false"], 1,
     "Classroom supports screen readers, captions in Meet, and other accessibility features." + NOTE, "KEA 2026 KEC-1 (HK, 22 Feb 2026) · Q82"),
    ("Google Classroom is mainly used to:",
     ["Create classes, share material, give assignments and return grades online", "Edit photos", "Browse the web", "Store passwords"], 0,
     PYQ + "It was launched in 2014 as part of Google Workspace for Education."),
    ("Students join a Google Classroom class by using:",
     ["A class code or an invitation link from the teacher", "The teacher's password", "A phone number only", "A printer"], 0, "Teachers can also invite students by e-mail."),
    ("In Google Classroom, the page where the teacher posts announcements and students can comment is the:",
     ["Stream", "Classwork", "People", "Grades"], 0, PYQ + "Classwork holds assignments, quizzes and materials; People lists teachers and students."),
    ("The Google Classroom tab that lists all students and co-teachers is:",
     ["People", "Stream", "Classwork", "Calendar"], 0, "Teachers can also invite guardians to receive summaries."),
    ("When a teacher creates an assignment in Google Classroom, the files are automatically stored in:",
     ["Google Drive (a Classroom folder)", "The student's phone gallery", "A USB drive", "Gmail spam"], 0, PYQ + "Each class gets its own Drive folder."),
    ("A teacher wants each student to get a separate editable copy of a worksheet in Google Classroom. The option to choose is:",
     ["Make a copy for each student", "Students can view file", "Students can edit file", "Share by e-mail only"], 0, "'Students can edit file' gives one shared file to all students."),
    ("The meeting tool integrated with Google Classroom for live online classes is:",
     ["Google Meet", "Google Keep", "Google Earth", "Google Maps"], 0, PYQ + "A class Meet link can be generated from the class settings."),
    ("In Google Forms, a 'Quiz' setting allows the teacher to:",
     ["Assign point values, set answer keys and release scores automatically", "Edit videos", "Send SMS", "Create a website"], 0, "Feedback can be added for right and wrong answers."),
    ("The responses to a Google Form can be collected automatically into a:",
     ["Google Sheet", "Google Slide", "Google Drawing", "Gmail label"], 0, PYQ + "Summary charts also appear in the Responses tab."),
    ("Which of the following is NOT a question type in Google Forms?",
     ["Video editing", "Multiple choice", "Checkboxes", "Short answer"], 0, "Other types include paragraph, dropdown, linear scale, grid, date, time and file upload."),
    ("A Google Forms question type that lets respondents choose more than one option is:",
     ["Checkboxes", "Multiple choice", "Dropdown", "Linear scale"], 0, PYQ + "Multiple choice and dropdown allow only one answer."),
    ("To show different questions depending on a respondent's answer in Google Forms, use:",
     ["Sections with 'Go to section based on answer'", "Spell check", "Themes", "Print"], 0, "This is called branching logic."),
    ("To stop a Google Form from accepting new answers, the owner turns off:",
     ["'Accepting responses' in the Responses tab", "The internet", "Gmail", "The theme"], 0, PYQ + "A custom closing message can be shown."),
    ("Consider the statements:\nI. Google Forms can be shared by a link, e-mail or embedded in a website.\nII. Google Forms can automatically grade quizzes.",
     I_II, 2, "Both are features of Google Forms."),
    ("Assertion (A): Google Classroom reduces paper work for teachers.\nReason (R): Assignments are created, submitted and graded online, with files kept in Google Drive.",
     AR, 0, "Due dates also appear in Google Calendar."),
    ("Assertion (A): Students need the teacher's Google password to join a class.\nReason (R): Teachers share a class code with students.",
     AR, 3, "Students join with the class code or link, never with the teacher's password."),
    ("Match:\na. Google Classroom  b. Google Forms  c. Google Meet  d. Google Sheets\n1. Manage class work  2. Surveys and quizzes  3. Video meetings  4. Spreadsheets",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Google tools matching."),
    ("In Google Classroom, a teacher can schedule a post to appear later using:",
     ["The 'Schedule' option beside Assign / Post", "Print preview", "Ctrl + P", "A class code"], 0, "Drafts can also be saved and reused across classes."),
]

DRIVE_REPO = [
    ("Match the following:\n(a) Gmail\n(b) Google Drive\n(c) Google Doc\n(d) Google Form\n(i) Class assignment folder\n(ii) Creating project report\n(iii) City survey\n(iv) Creating labels",
     ["a – ii, b – iii, c – iv, d – i", "a – ii, b – i, c – iv, d – iii", "a – iv, b – i, c – ii, d – iii", "a – iii, b – ii, c – i, d – iv"], 2,
     "Gmail – labels to organise mail; Drive – folders; Docs – documents such as reports; Forms – surveys." + NOTE, "KEA 2025 KEC (HK, 21 Dec 2025) · Q76"),
    ("Match the following types of productivity tools (List-I) with their examples (List-II):\nList-I\n(a) Project management\n(b) Time management\n(c) Communication management\n(d) File storage\nList-II\n(i) Zoom\n(ii) Google Drive\n(iii) Trello\n(iv) Google Calendar",
     ["a – iv, b – i, c – ii, d – iii", "a – iii, b – iv, c – i, d – ii", "a – ii, b – i, c – iv, d – iii", "a – iv, b – iii, c – i, d – ii"], 1,
     "Trello – project boards; Google Calendar – time; Zoom – communication; Google Drive – file storage." + NOTE, "KEA 2025 KEC (HK, 21 Dec 2025) · Q80"),
    ("Which the following is/are cloud-based collaboration tools?\na. Google Docs\nb. Microsoft Teams\nc. MS Paint\nd. Zoom",
     ["a, b and c", "a only", "a, b and d", "a and c"], 2,
     "Google Docs, Teams and Zoom work over the Internet; MS Paint is a local desktop program." + NOTE, "KEA 2026 KEC-1 (NHK, 26 Apr 2026) · Q82"),
    ("Google Drive is a:",
     ["Cloud storage and file-sharing service", "Web browser", "Operating system", "Antivirus"], 0, PYQ + "It was launched in 2012."),
    ("A free personal Google account currently includes cloud storage of:",
     ["15 GB shared across Gmail, Drive and Photos", "1 GB", "100 GB", "Unlimited"], 0, "More storage is available through Google One plans."),
    ("To let others edit a Google Drive file, the owner shares it with the role:",
     ["Editor", "Viewer", "Commenter", "Guest"], 0, PYQ + "Viewer can only read; commenter can add comments."),
    ("Files that have been shared with you by others appear in Google Drive under:",
     ["Shared with me", "Trash", "Starred", "Spam"], 0, "Items in Trash are deleted permanently after 30 days."),
    ("Google Docs, Sheets and Slides are Google's online equivalents of:",
     ["Word processor, spreadsheet and presentation software", "Paint, Notepad and Calculator", "Web browser, e-mail and chat", "Antivirus, firewall and backup"], 0,
     PYQ + "Several people can edit the same file at the same time."),
    ("In Google Docs, the feature that shows older saved states of a document and lets you restore them is:",
     ["Version history", "Spell check", "Explore", "Word count"], 0, "File → Version history → See version history."),
    ("Google Docs saves changes:",
     ["Automatically, as you type, to Google Drive", "Only when you press Ctrl + S", "Only when printing", "Never"], 0, PYQ + "That is why there is no Save button."),
    ("A 'digital repository' in education is:",
     ["An online collection where digital learning resources are stored, organised and shared", "A physical library cupboard", "A printer queue", "A type of virus"], 0,
     "Examples: NDLI, DIKSHA, e-Pathshala, NROER, Shodhganga."),
    ("The National Digital Library of India (NDLI) was developed by:",
     ["IIT Kharagpur, under the Ministry of Education", "ISRO", "RBI", "NASSCOM"], 0, PYQ + "It gives a single-window search of millions of learning resources."),
    ("NROER, a repository of open educational resources for schools, is maintained by:",
     ["CIET-NCERT", "UGC", "AICTE", "NIOS only"], 0, "NROER = National Repository of Open Educational Resources."),
    ("Which of these is India's national repository of PhD theses?",
     ["Shodhganga", "SWAYAM", "DIKSHA", "e-Pathshala"], 0, PYQ + "It is maintained by INFLIBNET."),
    ("A Google Drive link set to 'Anyone with the link – Viewer' means:",
     ["Anyone who has the link can open and read the file but not edit it", "Only the owner can open it", "Anyone can edit it", "The file is deleted"], 0,
     "Restricted access limits it to added people."),
    ("Consider the statements:\nI. Files in Google Drive can be accessed from any device with internet and a Google account.\nII. Google Drive can store only Google Docs files.",
     I_II, 0, "Drive can store almost any file type – PDFs, images, videos, Office files."),
    ("Assertion (A): Cloud storage protects data even if the user's computer is lost.\nReason (R): Files are stored on remote servers and synchronised to the account.",
     AR, 0, "Still, strong passwords and two-step verification are needed."),
    ("Assertion (A): Google Drive works only on Android phones.\nReason (R): Google Drive is a cloud service accessible through a web browser and apps.",
     AR, 3, "Drive works in any browser and on Windows, macOS, Android and iOS."),
    ("Match:\na. Google Drive  b. Google Docs  c. DIKSHA  d. Shodhganga\n1. Cloud storage  2. Online word processing  3. School e-content platform  4. Theses repository",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Tool and repository matching."),
    ("The Google tool used to keep quick notes and checklists that sync across devices is:",
     ["Google Keep", "Google Earth", "Google Ads", "Google Fonts"], 0, "Notes can be shared and turned into Docs."),
]

TOPICS = {
    "Unit 3 – Google Platform": [("1 · Google Classroom and Google Forms", CLASSROOM_FORMS),
                                 ("2 · Google Drive, Docs and Digital Repositories", DRIVE_REPO)],
}
