"""Paper 1 · Computer Literacy · P1-CL-02 Unit 2 – Operating Systems (2 sub-topics × 20).
Control Panel, wallpaper, shortcuts and Windows set-up belong to P1-CL-03 and are not covered here.
References: P. K. Sinha, Computer Fundamentals; KTBS/NCERT ICT textbooks; Microsoft Windows help."""
from packlib import AR, I_II

OS_BASICS = [
    ("An operating system is best described as:",
     ["System software that manages the computer's hardware and resources and acts as an interface between the user and the hardware", "An application for typing letters", "A hardware device inside the CPU", "A computer virus"], 0, "Without an OS, users and application programs could not use the hardware easily."),
    ("Which of the following is NOT a function of an operating system?",
     ["Typing and formatting a letter", "Memory management", "File management", "Managing input/output devices"], 0, "Typing letters is done by application software such as a word processor."),
    ("The core part of an operating system that stays in memory and directly controls the hardware is the:",
     ["Kernel", "Shell only", "Desktop", "Recycle Bin"], 0, "The shell (command line or GUI) is the part that interacts with the user."),
    ("The Linux kernel was first released in 1991 by:",
     ["Linus Torvalds", "Bill Gates", "Steve Jobs", "Dennis Ritchie"], 0, "Linux is free and open-source."),
    ("Red Hat is best known as:",
     ["A company that develops and supports a distribution of Linux (Red Hat Enterprise Linux)", "Apple's operating system", "A version of MS-DOS", "An antivirus program"], 0, "Other Linux distributions include Ubuntu, Debian and Fedora."),
    ("The operating system used on Apple's Macintosh computers is:",
     ["macOS", "Windows", "Android", "MS-DOS"], 0, "It was earlier called Mac OS X / OS X."),
    ("Windows is developed by:",
     ["Microsoft", "Apple", "Google", "IBM"], 0, "Windows 1.0 was released in 1985."),
    ("MS-DOS differs from Windows mainly because MS-DOS has a:",
     ["Command-line interface where commands are typed", "Graphical user interface with icons", "Touch interface", "Voice interface"], 0, "Windows provides a GUI with windows, icons, menus and a pointer."),
    ("An operating system that must respond to inputs within strict time limits, such as in air-traffic control or medical equipment, is a:",
     ["Real-time operating system", "Batch operating system", "Single-user desktop OS only", "Network printer driver"], 0, "Missing a deadline in such systems can be dangerous."),
    ("In a batch operating system:",
     ["Similar jobs are collected and run one after another without user interaction", "Many users interact with the computer at the same time", "Each job must respond in real time", "Only mobile apps are run"], 0, "It was common in early mainframe computing."),
    ("An operating system that allows several users to work on one computer at the same time, each through a terminal, is:",
     ["Multi-user (time-sharing)", "Single-user", "Real-time only", "Batch only"], 0, "UNIX and Linux are multi-user operating systems."),
    ("Android, the mobile operating system, is based on the:",
     ["Linux kernel", "Windows kernel", "MS-DOS", "macOS kernel"], 0, "Android is developed by Google."),
    ("Loading the operating system into main memory when the computer is switched on is called:",
     ["Booting", "Formatting", "Compiling", "Scanning"], 0, "A cold boot starts from power-off; a warm boot is a restart."),
    ("The program that starts first when a PC is switched on and begins the boot process is stored in:",
     ["BIOS/UEFI firmware on a ROM chip", "The Recycle Bin", "A text file on the desktop", "The printer"], 0, "It tests the hardware (POST) and then loads the OS."),
    ("Restarting a computer that is already on, without switching off the power, is called a:",
     ["Warm boot", "Cold boot", "Shutdown", "Log off"], 0, "Switching on from a powered-off state is a cold boot."),
    ("Match the operating system with its developer:\na. Windows  b. macOS  c. Android  d. Red Hat Enterprise Linux\n1. Red Hat  2. Google  3. Apple  4. Microsoft",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "iOS (for iPhones) is also developed by Apple."),
    ("Consider the statements:\nI. Linux is open-source software.\nII. Windows is open-source software.\nWhich is/are correct?",
     I_II, 0, "Windows and macOS are proprietary; their source code is not freely available."),
    ("Consider the statements:\nI. The operating system manages memory and files.\nII. The operating system provides the user interface.\nWhich is/are correct?",
     I_II, 2, "Both are standard functions of an operating system."),
    ("Assertion (A): A computer cannot be used conveniently without an operating system.\nReason (R): The operating system manages the hardware and provides an interface for users and programs.",
     AR, 0, "The OS is the link between users, programs and hardware."),
    ("Assertion (A): MS Word is an operating system.\nReason (R): An operating system manages the computer's hardware resources.",
     AR, 3, "MS Word is application software, since it does not manage hardware; R shows why A is false."),
]

WINDOWS_MOUSE = [
    ("The four main elements of a graphical user interface are summarised as WIMP, which stands for:",
     ["Windows, Icons, Menus, Pointer", "Words, Images, Mouse, Printer", "Web, Internet, Mail, Programs", "Windows, Internet, Memory, Processor"], 0, "Windows introduced a WIMP-style GUI for PCs."),
    ("The strip, usually at the bottom of the Windows screen, that holds the Start button, open programs and the clock is the:",
     ["Taskbar", "Title bar", "Status bar", "Scroll bar"], 0, "The area near the clock is the notification area (system tray)."),
    ("A small picture on the desktop that represents a program, file or folder is called an:",
     ["Icon", "Cursor", "Window", "Menu"], 0, "Double-clicking an icon opens the item."),
    ("A desktop icon with a small curved arrow at its lower-left corner is a:",
     ["Shortcut to a file, folder or program", "Deleted file", "Hidden system file", "Virus-infected file"], 0, "Deleting a shortcut does not delete the original item."),
    ("Files deleted from the hard disk in Windows normally go first to the:",
     ["Recycle Bin, from where they can be restored", "Taskbar", "Start menu", "Control unit"], 0, "They are removed permanently only when the Recycle Bin is emptied."),
    ("Pressing Shift + Delete on a selected file in Windows:",
     ["Deletes it permanently without sending it to the Recycle Bin", "Copies it", "Renames it", "Moves it to the desktop"], 0, "Windows usually asks for confirmation first."),
    ("Match the mouse action with its usual result:\na. Single click  b. Double click  c. Right click  d. Drag and drop\n1. Moves an item to a new place  2. Opens a context (shortcut) menu  3. Opens a file or program  4. Selects an item",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These are the basic mouse operations in Windows."),
    ("To move an icon to another place on the desktop, the user should:",
     ["Drag it with the left mouse button held down and release it at the new place", "Double-click it", "Press the Delete key", "Right-click it once"], 0, "If 'Auto arrange icons' is on, Windows arranges them automatically."),
    ("The three buttons at the right end of a window's title bar are:",
     ["Minimise, Maximise/Restore and Close", "Cut, Copy and Paste", "Back, Forward and Refresh", "Save, Open and Print"], 0, "A minimised window stays available on the taskbar."),
    ("Which keyboard shortcut switches between open windows in Windows?",
     ["Alt + Tab", "Ctrl + C", "Alt + F4", "Ctrl + Z"], 0, "Alt + F4 closes the active window."),
    ("Match the Windows shortcut with its action:\na. Windows key + D  b. Windows key + E  c. Windows key + L  d. Alt + F4\n1. Close the active window  2. Lock the computer  3. Open File Explorer  4. Show the desktop",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Keyboard shortcuts speed up common tasks."),
    ("The Windows program used to view, copy, move and organise files and folders is:",
     ["File Explorer (Windows Explorer)", "Notepad", "Paint", "Calculator"], 0, "It can be opened with Windows key + E."),
    ("To select several files that are NOT next to each other in File Explorer, the user holds down:",
     ["Ctrl while clicking each file", "Shift while clicking each file", "Alt while double-clicking", "Tab while scrolling"], 0, "Shift + click selects a continuous range of items."),
    ("The mouse pointer changes to a spinning circle (or hourglass in older Windows) when:",
     ["The computer is busy and the user should wait", "The mouse battery is low", "A file has been deleted", "The internet is disconnected"], 0, "An I-beam pointer appears over text that can be edited."),
    ("Dragging a file with the RIGHT mouse button and releasing it shows a menu with options such as:",
     ["Copy here, Move here and Create shortcuts here", "Print, Save and Close", "Bold, Italic and Underline", "Restart, Shut down and Sleep"], 0, "It lets the user choose exactly what should happen."),
    ("The main screen that appears after logging in to Windows, with icons and the taskbar, is called the:",
     ["Desktop", "Control unit", "Clipboard", "BIOS"], 0, "Windows are opened on top of the desktop."),
    ("Consider the statements:\nI. A folder can contain files and other folders.\nII. Deleting a shortcut icon also deletes the original program.\nWhich is/are correct?",
     I_II, 0, "A shortcut is only a link to the original item."),
    ("Consider the statements:\nI. Double-clicking an icon normally opens the item it represents.\nII. Right-clicking an item normally shows a context menu of actions for that item.\nWhich is/are correct?",
     I_II, 2, "Both are standard mouse actions in Windows."),
    ("Assertion (A): A file deleted with the Delete key can usually be recovered in Windows.\nReason (R): Such files are first moved to the Recycle Bin.",
     AR, 0, "Files can be restored from the Recycle Bin until it is emptied."),
    ("Assertion (A): Minimising a window closes the program.\nReason (R): A minimised window remains available as a button on the taskbar.",
     AR, 3, "The program keeps running on the taskbar, which shows why A is false."),
]

TOPICS = {
    "Unit 2 – Operating Systems": [("1 · Operating System: Meaning, Functions and Types", OS_BASICS),
                                   ("2 · Windows Concepts, Mouse and Icons", WINDOWS_MOUSE)],
}
