"""Paper 1 · General English · P1-ENG-02 Verbs – Tense, Time and Aspect (2 sub-topics × 20).
Auxiliaries and modals are the next topic (P1-ENG-03).
References: Wren & Martin; Raymond Murphy, English Grammar in Use; Michael Swan, Practical English Usage."""
from packlib import AR, I_II

PRESENT_PAST = [
    ("Choose the correct form: 'She ___ to school by bus every day.'",
     ["goes", "is going", "has gone", "go"], 0, "The simple present is used for habits and routines."),
    ("Choose the correct form: 'Look! The children ___ in the rain.'",
     ["are playing", "play", "played", "have played"], 0, "The present continuous is used for an action happening now."),
    ("Choose the correct form: 'I ___ the answer to this question now.'",
     ["know", "am knowing", "have been knowing", "knowing"], 0, "Stative verbs such as know, like and believe are not normally used in continuous forms."),
    ("Choose the correct form: 'The sun ___ in the east.'",
     ["rises", "is rising", "rose", "has risen"], 0, "Universal truths take the simple present."),
    ("Choose the correct form: 'I ___ my homework already, so I can play now.'",
     ["have finished", "finished yesterday", "am finishing", "finish"], 0, "The present perfect links a past action with the present."),
    ("Choose the correct sentence about a finished past event.",
     ["I saw him yesterday.", "I have seen him yesterday.", "I have saw him yesterday.", "I seen him yesterday."], 0, "The present perfect is not used with a definite past time such as yesterday."),
    ("Choose the correct form: 'She ___ for two hours and is still at her desk.'",
     ["has been studying", "studied", "is studying since", "had studied"], 0, "The present perfect continuous shows an action continuing up to now."),
    ("Choose the correct word: 'They have lived in Mysuru ___ 2010.'",
     ["since", "for", "from", "by"], 0, "'Since' + a point in time; 'for' + a period."),
    ("Choose the correct form: 'I ___ dinner when the phone rang.'",
     ["was having", "had", "am having", "have had"], 0, "The past continuous shows an action in progress, interrupted by a short past action."),
    ("Choose the correct form: 'When we reached the station, the train ___.'",
     ["had already left", "already left", "has already left", "leaves"], 0, "The past perfect shows the earlier of two past actions."),
    ("Choose the correct negative: 'He ___ yet.'",
     ["hasn't come", "didn't came", "hasn't came", "don't come"], 0, "'Yet' is typical with the present perfect in negatives and questions."),
    ("Choose the correct question.",
     ["Did she go to the market?", "Did she went to the market?", "Does she went to the market?", "Did she gone to the market?"], 0, "After did, the base form of the verb is used."),
    ("Name the tense of: 'They had been waiting for an hour when the bus came.'",
     ["Past perfect continuous", "Past continuous", "Present perfect continuous", "Past perfect"], 0, "had been + -ing."),
    ("Match the sentence with its tense:\na. I write.  b. I am writing.  c. I have written.  d. I wrote.\n1. Simple past  2. Present perfect  3. Present continuous  4. Simple present",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each combines a tense (present/past) with an aspect."),
    ("Choose the correct form: 'Water ___ at 100 °C at sea level.'",
     ["boils", "is boiling", "boiled", "has boiled"], 0, "Scientific facts take the simple present."),
    ("Consider the statements:\nI. 'She has been living here since 2015' shows an action continuing up to now.\nII. 'She lived here since 2015' is correct standard English.\nWhich is/are correct?",
     I_II, 0, "'Since' with a situation continuing to now needs a perfect form."),
    ("Consider the statements:\nI. The past continuous describes an action in progress at a moment in the past.\nII. The past perfect shows the earlier of two past actions.\nWhich is/are correct?",
     I_II, 2, "Both are standard uses."),
    ("Assertion (A): 'I am knowing him for many years' is incorrect.\nReason (R): 'Know' is a stative verb, not normally used in continuous forms.",
     AR, 0, "The correct form is 'I have known him for many years'."),
    ("Assertion (A): 'I have seen him yesterday' is correct.\nReason (R): The present perfect is not used with a definite past time expression such as 'yesterday'.",
     AR, 3, "R is the rule, which shows A is incorrect."),
    ("Assertion (A): The simple present is used for universal truths.\nReason (R): The simple present always refers to actions happening at the moment of speaking.",
     AR, 2, "A is true; R is false – actions happening now take the present continuous."),
]

FUTURE_ASPECT = [
    ("Strictly by the form of the verb, English has how many tenses?",
     ["Two – present and past; future time is shown with helpers such as will", "Three – present, past and future", "Twelve", "Six"], 0, "Many grammarians (e.g. Quirk, Swan) distinguish tense (present/past) from aspect (progressive/perfect)."),
    ("In grammar, 'aspect' shows:",
     ["How an action is viewed in time – for example as ongoing (progressive) or completed (perfect)", "Whether the subject is singular or plural", "The mood of the speaker only", "The voice (active or passive)"], 0, "Tense locates an action in time; aspect describes its progress or completion."),
    ("The sentence 'She has been writing' combines:",
     ["The perfect and progressive aspects in the present tense", "The simple aspect in the past tense", "Only the progressive aspect", "The future tense"], 0, "have been + -ing = present perfect progressive."),
    ("Choose the correct form: 'Look at those dark clouds! It ___ rain.'",
     ["is going to", "will be going", "rains", "has rained"], 0, "'Be going to' predicts from present evidence."),
    ("Choose the correct form: 'I ___ my uncle in Hubballi tomorrow; I have already bought the ticket.'",
     ["am visiting", "visit", "visited", "had visited"], 0, "The present continuous is used for fixed personal arrangements."),
    ("Choose the correct form: 'The train ___ at 6.30 tomorrow morning.'",
     ["leaves", "is leaving yesterday", "left", "has left"], 0, "The simple present is used for timetables and schedules."),
    ("Choose the correct form: 'By next March, I ___ my degree.'",
     ["will have completed", "will complete since", "complete", "have completed"], 0, "The future perfect shows completion before a future time."),
    ("Choose the correct form: 'This time tomorrow, we ___ to Mysuru.'",
     ["will be travelling", "travel", "will have travel", "travelled"], 0, "The future continuous shows an action in progress at a future moment."),
    ("Choose the correct form: 'I will call you when I ___ home.'",
     ["reach", "will reach", "reached", "would reach"], 0, "In time clauses about the future, the simple present is used."),
    ("Choose the correct form: 'If it ___ tomorrow, the match will be cancelled.'",
     ["rains", "will rain", "rained", "would rain"], 0, "First conditional: if + simple present, will + base verb."),
    ("Choose the correct reported form: He said, 'I am tired.' → He said that he ___ tired.",
     ["was", "is", "has been", "will be"], 0, "After a past reporting verb, the present usually shifts to the past (sequence of tenses)."),
    ("Choose the correct reported form: The teacher said, 'The earth revolves round the sun.' → The teacher said that the earth ___ round the sun.",
     ["revolves", "revolved", "had revolved", "was revolving"], 0, "Universal truths keep the present tense in reported speech."),
    ("Choose the correct reported form: She said, 'I saw the film yesterday.' → She said that she ___ the film the day before.",
     ["had seen", "saw", "has seen", "sees"], 0, "The simple past shifts to the past perfect."),
    ("Choose the correct form: 'By June, she ___ at this school for ten years.'",
     ["will have been teaching", "teaches", "is teaching", "had taught"], 0, "The future perfect continuous stresses duration up to a future point."),
    ("'Shall I open the window?' is used mainly to:",
     ["Make an offer or ask for a suggestion", "Give an order", "Talk about the past", "Express a universal truth"], 0, "'Shall' with I/we in questions offers help or asks for advice."),
    ("Match the future form with its typical use:\na. will  b. be going to  c. present continuous  d. simple present\n1. Timetables and schedules  2. Fixed personal arrangements  3. Predictions from present evidence and intentions  4. Instant decisions, promises and predictions",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "English uses several forms to talk about the future."),
    ("Consider the statements:\nI. English refers to future time with will, be going to and the present continuous, among other forms.\nII. The future perfect describes an action that will be completed before a point in the future.\nWhich is/are correct?",
     I_II, 2, "Both statements are correct."),
    ("Assertion (A): 'I will call you when I will reach home' is incorrect.\nReason (R): In time clauses referring to the future, the simple present is used instead of will.",
     AR, 0, "Correct: 'I will call you when I reach home'."),
    ("Assertion (A): 'The train leaves at six tomorrow' is correct English.\nReason (R): 'Will' can be contracted to 'll.",
     AR, 1, "Both true, but the sentence is correct because timetables take the simple present."),
    ("Assertion (A): In formal reported speech, 'He said that he is ill' follows the usual sequence of tenses.\nReason (R): A past reporting verb is normally followed by a past tense in the reported clause.",
     AR, 3, "By the rule in R, the usual form is 'He said that he was ill', so A is false."),
]

TOPICS = {
    "Verbs – Tense, Time and Aspect": [("1 · Present and Past Tenses", PRESENT_PAST),
                                       ("2 · Future Time, Aspect and Sequence of Tenses", FUTURE_ASPECT)],
}
