"""Paper 1 · General English · P1-ENG-05 Punctuation (2 sub-topics × 20).
References: Wren & Martin, High School English Grammar and Composition (ch. on Punctuation); Michael Swan, Practical English
Usage; Oxford Guide to Style. Two REAL previous-year questions (KEA 2026 Kannada-English-Computer papers, NHK) are used word
for word; KEA has published no key for them, so their answers are worked out by ExamSim and say so."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC English). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

STOPS_COMMAS = [
    # --- real previous-year questions ---
    ("Identify the sentence with correct punctuation.",
     ["Rama, ravi and Arjun attended the conference.", "Rama, Ravi and arjun attended the conference", "Rama, Ravi and Arjun attended the conference.", "Rama Ravi and Arjun attended the conference."], 2,
     "Proper nouns take capitals, items in a list are separated by commas, and the sentence ends with a full stop." + NOTE,
     "KEA 2026 KEC (NHK, 25 Jan 2026) · Q70"),
    ("Punctuate the following sentence:\nHe asked me where I was going",
     ["He asked me where I was going?", "He asked me where I was going,", "He asked me where I was going!", "He asked me where I was going."], 3,
     "An indirect (reported) question is a statement, so it ends with a full stop, not a question mark." + NOTE,
     "KEA 2026 KEC (NHK, 11 Jan 2026) · Q53"),
    # --- new questions ---
    ("A full stop (period) is used at the end of:",
     ["A statement or a command", "A direct question", "An exclamation", "Every word"], 0,
     PYQ + "It is also used after some abbreviations, e.g. 'etc.'"),
    ("Choose the correctly punctuated direct question.",
     ["Where are you going?", "Where are you going.", "Where are you going!", "Where, are you going?"], 0,
     PYQ + "A direct question ends with a question mark."),
    ("Choose the correctly punctuated exclamatory sentence.",
     ["What a beautiful sunset!", "What a beautiful sunset?", "What a beautiful sunset,", "What, a beautiful sunset."], 0,
     PYQ + "An exclamatory sentence expressing strong feeling ends with an exclamation mark."),
    ("Which sentence uses commas correctly in a list?",
     ["I bought apples, bananas, grapes and mangoes.", "I bought, apples bananas grapes and mangoes.", "I bought apples bananas, grapes, and, mangoes.", "I bought apples bananas grapes, and mangoes."], 0,
     "Items in a series are separated by commas (a comma before 'and' – the Oxford comma – is optional in British usage)."),
    ("Choose the correctly punctuated sentence with a vocative (person addressed).",
     ["Ravi, please close the door.", "Ravi please, close the door.", "Ravi please close, the door.", "Ravi please close the door,"], 0,
     PYQ + "The name of the person spoken to is separated by a comma."),
    ("Choose the sentence with correct punctuation after an introductory word.",
     ["However, the train was late.", "However the train, was late.", "However the train was late,", "However: the train was late."], 0,
     "An introductory word such as 'however' is followed by a comma."),
    ("Choose the correctly punctuated sentence with a non-defining clause.",
     ["My brother, who lives in Mysuru, is a doctor.", "My brother who lives in Mysuru, is a doctor.", "My brother, who lives in Mysuru is a doctor.", "My brother who, lives in Mysuru, is a doctor."], 0,
     PYQ + "Extra (non-essential) information is enclosed by a pair of commas."),
    ("Choose the sentence with correct punctuation after an introductory clause.",
     ["If it rains, we will stay at home.", "If it rains we, will stay at home.", "If, it rains we will stay at home.", "If it rains we will stay, at home."], 0,
     "A comma usually follows an introductory 'if' clause."),
    ("Choose the correctly punctuated date.",
     ["On 15 August, 1947, India became independent.", "On 15, August 1947 India, became independent.", "On 15 August 1947 India became, independent.", "On, 15 August 1947, India became independent."], 0,
     "In the day–month–year style the comma after the month is optional; the comma after the year separates the introductory phrase."),
    ("Choose the correctly punctuated sentence with a question tag.",
     ["You are coming, aren't you?", "You are coming aren't you?", "You are coming, aren't you.", "You are coming aren't, you?"], 0,
     PYQ + "A comma comes before the tag and a question mark at the end."),
    ("Which of these abbreviations is correctly punctuated in British usage?",
     ["Dr Rao met Mr Gowda at 10 a.m.", "Dr. Rao met Mr. Gowda at 10 am.", "Dr Rao, met Mr Gowda at 10 a.m", "Dr, Rao met Mr, Gowda at 10 am"], 0,
     "British style often drops the full stop after Dr and Mr (which end with the word's last letter); a.m. keeps its stops."),
    ("Choose the sentence in which the comma changes the meaning to show that the speaker is talking TO grandma.",
     ["Let's eat, Grandma.", "Let's eat Grandma.", "Lets eat Grandma.", "Let's, eat Grandma."], 0,
     "The famous example: the comma marks 'Grandma' as the person addressed."),
    ("Choose the correctly punctuated sentence joining two independent clauses with a conjunction.",
     ["I was tired, but I finished my homework.", "I was tired but, I finished my homework.", "I was, tired but I finished my homework.", "I was tired but I, finished my homework."], 0,
     "A comma often comes before a coordinating conjunction (and, but, or, so) joining two clauses."),
    ("Joining two complete sentences with only a comma, as in 'It was late, we went home.', is an error called a:",
     ["Comma splice", "Fragment", "Dangling modifier", "Split infinitive"], 0,
     PYQ + "Use a full stop, a semicolon or a conjunction instead."),
    ("Choose the correctly punctuated sentence with an interjection.",
     ["Alas! He is no more.", "Alas, he is no more?", "Alas he is, no more.", "Alas? He is no more."], 0,
     "Interjections expressing strong emotion are followed by an exclamation mark."),
    ("Match the use with the punctuation mark:\na. End of a statement  b. End of a direct question  c. After a strong exclamation  d. Letters left out in a contraction\n1. Apostrophe  2. Exclamation mark  3. Question mark  4. Full stop",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Indirect questions, e.g. 'She asked if I was ready.', also end with a full stop."),
    ("Consider the statements:\nI. A direct question ends with a question mark.\nII. An indirect question ends with a question mark.\nWhich is/are correct?",
     I_II, 0, "An indirect question is a statement and ends with a full stop."),
    ("Assertion (A): 'My sister, who lives in Delhi, is a nurse.' has commas around the clause.\nReason (R): A non-defining relative clause gives extra information and is separated by commas.",
     AR, 0, "A defining clause would not take commas."),
]

OTHER_MARKS = [
    ("Choose the correct possessive form.",
     ["The boys' hostel (a hostel for many boys)", "The boy's' hostel", "The boys hostel's", "The boyses hostel"], 0,
     PYQ + "For plural nouns ending in -s, add only an apostrophe: boys'."),
    ("Choose the sentence that uses its and it's correctly.",
     ["It's raining, and the cat is licking its paw.", "Its raining, and the cat is licking it's paw.", "It's raining, and the cat is licking it's paw.", "Its raining, and the cat is licking its paw."], 0,
     PYQ + "It's = it is; its = possessive (no apostrophe)."),
    ("In 'don't' and 'I'll', the apostrophe shows:",
     ["That letters have been left out (contraction)", "Possession", "A plural", "A quotation"], 0,
     "don't = do not; I'll = I will / I shall."),
    ("Choose the correct possessive for a plural noun that does not end in -s.",
     ["The children's books", "The childrens' books", "The childrens books", "The children books'"], 0,
     "Irregular plurals take 's: men's, women's, children's."),
    ("Choose the correctly punctuated sentence using a colon.",
     ["Bring three things: a pen, a notebook and a ruler.", "Bring: three things a pen, a notebook and a ruler.", "Bring three: things, a pen, a notebook and a ruler.", "Bring three things a pen: a notebook and a ruler."], 0,
     PYQ + "A colon introduces a list after a complete clause."),
    ("Choose the correctly punctuated sentence using a semicolon.",
     ["I wanted to go; however, it was raining.", "I wanted; to go however it was raining.", "I wanted to go however; it was raining.", "I wanted to go, however; it was raining."], 0,
     PYQ + "A semicolon joins two closely related independent clauses, often before 'however' or 'therefore'."),
    ("A semicolon is also used to separate:",
     ["Items in a list when the items themselves contain commas", "Every pair of words", "The subject from the verb", "A question from its answer"], 0,
     "e.g. Mysuru, Karnataka; Chennai, Tamil Nadu; and Pune, Maharashtra."),
    ("Choose the correctly punctuated direct speech.",
     ["\"I am happy,\" she said.", "\"i am happy\", she said.", "\"I am happy.\" She said.", "\"I am happy\" she said,"], 0,
     PYQ + "The comma goes inside the closing quotation mark; the reporting clause continues in lower case."),
    ("Which sentence correctly punctuates a quoted command?",
     ["The teacher said, \"Open your books.\"", "The teacher said \"open your books\".", "The teacher said, \"open your books\"", "The teacher said. \"Open your books.\""], 0,
     "A comma introduces the quotation; the quoted sentence begins with a capital letter."),
    ("Choose the correctly punctuated direct question in speech.",
     ["He asked, \"Where is the station?\"", "He asked, \"Where is the station\"?", "He asked \"where is the station.\"", "He asked, \"Where is the station.\"?"], 0,
     "When the quoted words are a question, the question mark goes inside the quotation marks."),
    ("The title of a short poem or story within running text is usually placed in:",
     ["Quotation marks (inverted commas)", "Brackets", "Hyphens", "Semicolons"], 0,
     "Titles of whole books are usually italicised."),
    ("Which sentence uses a hyphen correctly?",
     ["She is a well-known writer.", "She is a well known-writer.", "She is a-well known writer.", "She is well-known-writer."], 0,
     PYQ + "Compound adjectives before a noun are hyphenated."),
    ("Which number is correctly written in words?",
     ["Twenty-five", "Twenty five-", "Twentyfive-", "Twenty–five–"], 0,
     "Compound numbers from twenty-one to ninety-nine take a hyphen."),
    ("A dash (—) is used to:",
     ["Mark a sudden break or add an emphatic explanation, e.g. 'He had one aim — to win.'", "End every sentence", "Show possession", "Join the parts of a date"], 0,
     "A hyphen (-) joins words; a dash (—) separates parts of a sentence."),
    ("Brackets (parentheses) are used to:",
     ["Enclose extra information or an explanation, e.g. 'The WHO (World Health Organization) …'", "Mark direct speech", "Show possession", "End a question"], 0,
     "The sentence should still be complete without the bracketed words."),
    ("Which word should begin with a capital letter in all positions?",
     ["Monday", "summer", "river", "city"], 0,
     PYQ + "Days, months, proper nouns and the pronoun 'I' are capitalised; seasons are not."),
    ("Choose the correctly capitalised sentence.",
     ["Last July, my friend and I visited the Taj Mahal.", "last july, my friend and i visited the taj mahal.", "Last july, my Friend and I visited the taj Mahal.", "Last July, My Friend And I Visited The Taj Mahal."], 0,
     "Capitalise the first word, the month, 'I' and proper nouns."),
    ("Match the mark with its use:\na. Apostrophe  b. Colon  c. Semicolon  d. Hyphen\n1. Joins words in a compound adjective  2. Joins two related independent clauses  3. Introduces a list or explanation  4. Shows possession or omission",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Mark–use matching appears in SSC and KEA English sections."),
    ("Consider the statements:\nI. 'Its' is the possessive form of 'it'.\nII. 'It's' is the possessive form of 'it'.\nWhich is/are correct?",
     I_II, 0, "It's always means 'it is' or 'it has'."),
    ("Assertion (A): In 'women's college', the apostrophe comes before the s.\nReason (R): Plural nouns that do not end in -s form the possessive by adding 's.",
     AR, 0, "So: women's, men's, children's."),
]

TOPICS = {
    "Punctuation": [("1 · Full Stop, Comma, Question Mark and Exclamation Mark", STOPS_COMMAS),
                    ("2 · Apostrophe, Colon, Semicolon, Quotation Marks, Hyphen, Dash and Capitals", OTHER_MARKS)],
}
