"""Paper 1 · General English · P1-ENG-03 Auxiliaries and Modals (2 sub-topics × 20).
References: Wren & Martin, High School English Grammar and Composition; R. Murphy, English Grammar in Use; Quirk et al., A Comprehensive Grammar of the English Language."""
from packlib import AR, I_II

PRIMARY = [
    ("The three primary auxiliary verbs in English are:",
     ["be, have and do", "can, may and must", "shall, will and would", "need, dare and ought"], 0, "They can also be used as main verbs."),
    ("In 'She is writing a letter', the word 'is' is:",
     ["A primary auxiliary forming the progressive", "A modal auxiliary", "A main verb", "An adverb"], 0, "Be + -ing forms the continuous (progressive) aspect."),
    ("In 'They have finished their work', 'have' is used to form the:",
     ["Present perfect tense", "Passive voice", "Simple past", "Future tense"], 0, "Have + past participle forms the perfect aspect."),
    ("In 'He has a new bicycle', 'has' is used as a:",
     ["Main verb meaning 'possess'", "Auxiliary of the perfect tense", "Modal verb", "Linking adverb"], 0, "There is no other verb in the sentence."),
    ("In 'The letter was posted yesterday', 'was' helps to form the:",
     ["Passive voice", "Present perfect", "Future continuous", "Imperative"], 0, "Be + past participle forms the passive."),
    ("Choose the correct negative form of 'She likes coffee':",
     ["She does not like coffee.", "She not likes coffee.", "She do not like coffee.", "She does not likes coffee."], 0, "Do-support: does + not + base form."),
    ("Choose the correct question form of 'They went to Mysuru':",
     ["Did they go to Mysuru?", "Did they went to Mysuru?", "Do they went to Mysuru?", "Went they to Mysuru?"], 0, "After 'did', the main verb is in its base form."),
    ("In 'I DO want to help you', the auxiliary 'do' is used for:",
     ["Emphasis", "Negation", "Forming a question", "Forming the passive"], 0, "Emphatic 'do' is stressed in speech."),
    ("Fill in the blank: 'Neither of the boys ___ present yesterday.'",
     ["was", "were", "are", "have"], 0, "'Neither' takes a singular verb in formal English."),
    ("Fill in the blank: 'The children ___ been playing since morning.'",
     ["have", "has", "is", "was"], 0, "Plural subject + have been + -ing (present perfect continuous)."),
    ("Choose the correct question tag: 'She is a teacher, ___?'",
     ["isn't she", "is she", "doesn't she", "wasn't she"], 0, "Positive statement → negative tag with the same auxiliary."),
    ("Choose the correct question tag: 'You didn't call me, ___?'",
     ["did you", "didn't you", "do you", "have you"], 0, "Negative statement → positive tag."),
    ("Choose the correct question tag: 'I am late, ___?'",
     ["aren't I", "amn't I", "am not I", "isn't I"], 0, "'Aren't I' is the standard tag for 'I am'."),
    ("Choose the correct question tag: 'Let's go for a walk, ___?'",
     ["shall we", "will we", "don't we", "won't you"], 0, "Suggestions with 'Let's' take 'shall we'."),
    ("Choose the correct question tag: 'Everyone has arrived, ___?'",
     ["haven't they", "hasn't he", "hasn't it", "haven't we"], 0, "Indefinite pronouns like 'everyone' take 'they' in tags."),
    ("Identify the sentence in which 'do' is a MAIN verb:",
     ["He does his homework every evening.", "Do you know her?", "I do not agree.", "She does look tired."], 0, "Here 'does' means 'performs'; in the others it is an auxiliary."),
    ("Match the use of the auxiliary with the example:\na. Progressive  b. Perfect  c. Passive  d. Emphasis\n1. I did lock the door.  2. The bridge was built in 2010.  3. She has left.  4. They are singing.",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Be, have and do each have typical uses."),
    ("Consider the statements:\nI. 'Have' can be used both as an auxiliary and as a main verb.\nII. After the auxiliary 'did', the main verb takes its past form.\nWhich is/are correct?",
     I_II, 0, "After 'did' the main verb is in its base form: 'Did he go?'"),
    ("Assertion (A): 'He doesn't knows the answer' is incorrect.\nReason (R): After 'does', the main verb is used in its base form.",
     AR, 0, "Correct: 'He doesn't know the answer.'"),
    ("Assertion (A): 'Be' is used to form the perfect tenses.\nReason (R): 'Be' is used to form the passive voice.",
     AR, 3, "The perfect tenses use 'have'; A is false, R is true."),
]

MODALS = [
    ("Which of the following is a modal auxiliary?",
     ["might", "has", "being", "does"], 0, "Modals: can, could, may, might, shall, should, will, would, must, ought to."),
    ("A modal auxiliary is always followed by:",
     ["The base form of the verb (without 'to', except 'ought to')", "The -ing form", "The past participle only", "The -s form"], 0, "e.g. 'She can swim', not 'She can swims'."),
    ("Which sentence expresses ABILITY?",
     ["She can speak three languages.", "You must wear a helmet.", "It may rain today.", "You should rest."], 0, "'Can' (and 'could' in the past) express ability."),
    ("'You may leave now' expresses:",
     ["Permission", "Ability", "Obligation", "Habit"], 0, "'May' is a formal way of giving permission."),
    ("'It might rain this evening' expresses:",
     ["A weak possibility", "Certainty", "Permission", "Obligation"], 0, "'Might' shows less certainty than 'may'."),
    ("'You must stop at the red light' expresses:",
     ["Obligation or necessity", "Permission", "Weak possibility", "Ability"], 0, "'Must' shows strong obligation."),
    ("'He must be tired after the long journey' expresses:",
     ["A logical conclusion (deduction)", "Obligation", "Permission", "Ability"], 0, "'Must' can express a confident inference."),
    ("'You should visit a doctor' expresses:",
     ["Advice", "Permission", "Ability", "Prohibition"], 0, "'Should' and 'ought to' give advice."),
    ("Fill in the blank: 'We ___ respect our elders.'",
     ["ought to", "ought", "ought for", "ought be"], 0, "'Ought' is followed by 'to'."),
    ("The negative of 'You must go' meaning 'it is not necessary for you to go' is:",
     ["You needn't go (you don't have to go).", "You mustn't go.", "You can't went.", "You must not to go."], 0, "'Mustn't' means prohibition: it is forbidden."),
    ("'You mustn't smoke here' expresses:",
     ["Prohibition", "Lack of necessity", "Permission", "Ability"], 0, "Compare 'You don't have to' = not necessary."),
    ("'When I was young, I would walk to school every day' — 'would' here expresses:",
     ["A past habit", "Permission", "A future plan", "Obligation"], 0, "'Used to' can also express past habits."),
    ("'Would you please open the window?' is:",
     ["A polite request", "An order", "A prohibition", "A statement of ability"], 0, "'Would' and 'could' make requests polite."),
    ("Fill in the blank: 'When he was five, he ___ swim across the river.'",
     ["could", "can", "may", "must"], 0, "'Could' is the past form expressing ability."),
    ("Choose the correct sentence:",
     ["She can drive a car.", "She can drives a car.", "She cans drive a car.", "She can to drive a car."], 0, "Modals take no -s and are followed by the base form."),
    ("'You should have told me earlier' expresses:",
     ["Regret or criticism about a past action", "Future advice", "Present ability", "Permission"], 0, "Modal + have + past participle refers to the past."),
    ("Fill in the blank: 'How ___ you insult him like that?'",
     ["dare", "dares", "dared to", "daring"], 0, "'Dare' used as a modal takes no -s and no 'to'."),
    ("Match the modal with its meaning in context:\na. can (She can swim)  b. may (May I come in?)  c. must (You must obey the law)  d. should (You should exercise)\n1. Advice  2. Obligation  3. Permission  4. Ability",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These are the core meanings of the modals."),
    ("Consider the statements:\nI. 'Mustn't' and 'needn't' have the same meaning.\nII. Modal auxiliaries do not take -s in the third person singular.\nWhich is/are correct?",
     I_II, 1, "'Mustn't' = prohibited; 'needn't' = not necessary."),
    ("Assertion (A): 'He can plays chess' is incorrect.\nReason (R): A modal auxiliary is followed by the base form of the verb.",
     AR, 0, "Correct: 'He can play chess.'"),
]

TOPICS = {
    "Auxiliaries and Modals": [("1 · Primary Auxiliaries: Be, Have and Do", PRIMARY),
                               ("2 · Modal Auxiliaries", MODALS)],
}
