"""Paper 1 · General English · P1-ENG-04 Phonology – Vowels, Consonants, Stress (2 sub-topics × 20).
References: Daniel Jones, English Pronouncing Dictionary; J. Sethi & P. V. Dhamija, A Course in Phonetics and Spoken English;
T. Balasubramanian, A Textbook of English Phonetics for Indian Students (Received Pronunciation)."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET / GPSTR). "

SOUNDS = [
    ("How many phonemes (distinct sounds) are there in British English (RP)?",
     ["44", "26", "40", "52"], 0, PYQ + "20 vowel sounds and 24 consonant sounds, though the alphabet has 26 letters."),
    ("How many vowel sounds are there in RP English?",
     ["20", "12", "5", "8"], 0, PYQ + "12 pure vowels (monophthongs) and 8 diphthongs."),
    ("How many consonant sounds are there in RP English?",
     ["24", "21", "26", "20"], 0, PYQ + "21 consonant letters represent 24 consonant sounds."),
    ("How many diphthongs are there in RP English?",
     ["8", "12", "5", "20"], 0, PYQ + "/eɪ, aɪ, ɔɪ, əʊ, aʊ, ɪə, eə, ʊə/."),
    ("A diphthong is:",
     ["A glide from one vowel quality to another within a single syllable", "Two consonants together", "A long pure vowel", "A silent letter"], 0, "E.g. /aɪ/ in 'time'."),
    ("The vowel sound in 'seat' (/iː/) differs from that in 'sit' (/ɪ/) mainly in:",
     ["Length and quality – /iː/ is a long vowel", "Being a consonant", "Being a diphthong", "Nasality"], 0, "Long vowels are marked with ː."),
    ("Which word contains the diphthong /aɪ/?",
     ["time", "team", "tame", "tomb"], 0, "'team' /iː/, 'tame' /eɪ/, 'tomb' /uː/."),
    ("The most common vowel in English, found in unstressed syllables such as the first syllable of 'about', is:",
     ["Schwa /ə/", "/iː/", "/æ/", "/ɔː/"], 0, "Schwa occurs only in unstressed syllables."),
    ("Which pair differs only in voicing?",
     ["/p/ and /b/", "/p/ and /m/", "/s/ and /ʃ/", "/k/ and /ŋ/"], 0, "Both are bilabial plosives; /b/ is voiced, /p/ voiceless."),
    ("Sounds made with both lips, such as /p/, /b/ and /m/, are called:",
     ["Bilabial", "Dental", "Velar", "Alveolar"], 0, "Velar sounds such as /k/ and /g/ use the back of the tongue."),
    ("The English nasal consonants are:",
     ["/m/, /n/, /ŋ/", "/p/, /b/, /m/", "/s/, /z/, /ʃ/", "/l/, /r/, /j/"], 0, "Air passes through the nose."),
    ("The final sound of 'sing' is:",
     ["/ŋ/ (velar nasal)", "/g/", "/n/", "/ŋg/ always"], 0, "In RP the 'g' is not pronounced separately."),
    ("The 'th' in 'think' is pronounced as:",
     ["/θ/, a voiceless dental fricative", "/ð/, a voiced dental fricative", "/t/", "/d/"], 0, "'this' has the voiced /ð/."),
    ("The English plosives (stops) are:",
     ["/p, b, t, d, k, g/", "/f, v, s, z/", "/m, n, ŋ/", "/l, r, w, j/"], 0, "The air is completely stopped and then released."),
    ("The affricates of English are:",
     ["/tʃ/ as in 'church' and /dʒ/ as in 'judge'", "/f/ and /v/", "/w/ and /j/", "/l/ and /r/"], 0, "A stop followed by a fricative at the same place."),
    ("The '-ed' ending is pronounced /ɪd/ in:",
     ["wanted", "walked", "played", "laughed"], 0, PYQ + "/ɪd/ after /t/ or /d/; /t/ after other voiceless sounds; /d/ after voiced sounds."),
    ("The plural ending '-s' is pronounced /ɪz/ in:",
     ["buses", "cats", "dogs", "books"], 0, "/ɪz/ after sibilants (s, z, ʃ, ʒ, tʃ, dʒ); /s/ in 'cats', /z/ in 'dogs'."),
    ("Match the word with the sound of the underlined/key part:\na. 'ch' in 'chair'  b. 's' in 'measure'  c. 'sh' in 'ship'  d. 'j' in 'jam'\n1. /dʒ/  2. /ʃ/  3. /ʒ/  4. /tʃ/",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Common sound-identification items."),
    ("Consider the statements:\nI. English has more sounds than letters.\nII. Every English vowel letter always has one fixed sound.\nWhich is/are correct?",
     I_II, 0, "44 sounds versus 26 letters; one vowel letter can stand for many sounds."),
    ("Assertion (A): The 'k' in 'knife' is not pronounced.\nReason (R): English spelling does not always match pronunciation.",
     AR, 0, "Silent letters show that spelling and sound differ."),
]

STRESS = [
    ("A syllable is a unit of pronunciation that normally contains:",
     ["One vowel sound (with or without consonants around it)", "Exactly two consonants", "One letter", "A whole word always"], 0, "'Cat' has one syllable; 'banana' has three."),
    ("How many syllables are there in the word 'examination'?",
     ["5", "4", "6", "3"], 0, "ex-am-i-na-tion."),
    ("How many syllables are there in 'university'?",
     ["5", "4", "3", "6"], 0, "u-ni-ver-si-ty."),
    ("In 'PREsent' (noun) and 'preSENT' (verb), the change is in:",
     ["Word stress", "Spelling", "Number of syllables", "Vowel letters"], 0, PYQ + "Many two-syllable noun/verb pairs: noun stress first, verb stress second (REcord / reCORD)."),
    ("Which word is stressed on the second syllable?",
     ["begin", "table", "water", "happy"], 0, "be-GIN; the others are stressed on the first syllable."),
    ("Words ending in '-tion' are usually stressed on:",
     ["The syllable just before '-tion'", "The first syllable", "The '-tion' syllable", "The last syllable"], 0, PYQ + "e.g. edu-CA-tion, infor-MA-tion."),
    ("Words ending in '-ity' are usually stressed on:",
     ["The syllable just before '-ity'", "The '-ity' syllable", "The first syllable always", "No syllable"], 0, "e.g. a-BIL-i-ty, responsi-BIL-i-ty."),
    ("Words ending in '-ic' are usually stressed on:",
     ["The syllable just before '-ic'", "The first syllable", "The '-ic' syllable", "The last-but-two syllable always"], 0, "e.g. scien-TIF-ic, eco-NOM-ic."),
    ("Choose the correct stress pattern:",
     ["PHOtograph, phoTOgrapher, photoGRAphic", "phoTOgraph, PHOtographer, photoGRAphic", "photoGRAPH, phoTOgrapher, PHOtographic", "PHOtograph, PHOtographer, PHOtographic"], 0, PYQ + "Stress moves as suffixes are added."),
    ("In the IPA, primary stress is marked by:",
     ["A raised vertical line ˈ before the stressed syllable", "A colon after the vowel", "Underlining the word", "A full stop"], 0, "Secondary stress is marked with a lowered line ˌ."),
    ("In connected speech, 'and' is often pronounced /ən/ or /n/. This is called a:",
     ["Weak form", "Strong form", "Diphthong", "Syllabic stress"], 0, "Function words are usually unstressed and reduced."),
    ("In sentence stress, the words normally stressed are:",
     ["Content words – nouns, main verbs, adjectives, adverbs", "Articles and prepositions", "Auxiliary verbs only", "Conjunctions"], 0, "Function words are usually unstressed."),
    ("In the compound noun 'BLACKboard', the stress falls on:",
     ["The first part", "The second part", "Both parts equally", "Neither part"], 0, "Compare 'a black BOARD' (adjective + noun)."),
    ("The intonation normally used for a yes/no question such as 'Are you coming?' is:",
     ["Rising", "Falling", "Level", "Rise-fall"], 0, "Statements and wh-questions usually have a falling tone."),
    ("The intonation normally used for a wh-question such as 'Where do you live?' is:",
     ["Falling", "Rising", "Level", "Fall-rise"], 0, "Wh-questions usually fall at the end."),
    ("The word 'cat' has the syllable structure:",
     ["CVC (consonant–vowel–consonant)", "VC", "CV", "CCVC"], 0, "/k/ + /æ/ + /t/."),
    ("Match the word with the syllable that carries its main stress:\na. happy  b. begin  c. education  d. responsibility\n1. Fourth syllable  2. Third syllable  3. Second syllable  4. First syllable",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "HAP-py, be-GIN, ed-u-CA-tion, re-spon-si-BIL-i-ty."),
    ("Consider the statements:\nI. Every syllable must contain a vowel sound (or a syllabic consonant).\nII. A word can have only one syllable.\nWhich is/are correct?",
     I_II, 0, "Words can have many syllables."),
    ("Assertion (A): 'reCORD' is a verb and 'REcord' is a noun.\nReason (R): In many two-syllable noun–verb pairs, nouns are stressed on the first syllable and verbs on the second.",
     AR, 0, "That pattern explains the pair."),
    ("Assertion (A): Function words such as 'to' and 'of' are usually stressed in sentences.\nReason (R): Weak forms of function words are common in connected speech.",
     AR, 3, "Function words are usually unstressed, so A is false."),
]

TOPICS = {
    "Phonology – Vowels, Consonants, Stress": [("1 · Vowels and Consonants", SOUNDS),
                                               ("2 · Syllables and Word Stress", STRESS)],
}
