"""Paper 1 · General English · P1-ENG-01 Parts of Speech (2 sub-topics × 20).
References: Wren & Martin, High School English Grammar and Composition; Raymond Murphy, Essential English Grammar."""
from packlib import AR, I_II

NOUN_PRON_ADJ = [
    ("In the sentence 'A flock of sheep was grazing on the hill', the word 'flock' is a:",
     ["Collective noun", "Proper noun", "Abstract noun", "Material noun"], 0, "A collective noun names a group taken as one whole."),
    ("Which of the following is an abstract noun?",
     ["Honesty", "Teacher", "Gold", "Bengaluru"], 0, "Abstract nouns name qualities, states or actions that cannot be touched."),
    ("The plural of 'passer-by' is:",
     ["passers-by", "passer-bys", "passers-bys", "passer-by's"], 0, "In compound nouns the main word takes the plural: mothers-in-law, commanders-in-chief."),
    ("The plural of 'criterion' is:",
     ["criteria", "criterions", "criterias", "criterion"], 0, "Similarly phenomenon → phenomena."),
    ("Choose the correct sentence.",
     ["He gave me a piece of advice.", "He gave me an advice.", "He gave me advices.", "He gave me a advice."], 0, "'Advice' is uncountable; so are furniture, information and luggage."),
    ("In 'The boy who won the prize is my cousin', the word 'who' is a:",
     ["Relative pronoun", "Interrogative pronoun", "Demonstrative pronoun", "Personal pronoun"], 0, "It joins the clause to the noun 'boy'; in 'Who is there?' it would be interrogative."),
    ("In 'I myself saw the accident', the word 'myself' is used as a/an:",
     ["Emphatic pronoun", "Reflexive pronoun", "Possessive pronoun", "Relative pronoun"], 0, "It emphasises 'I'. In 'I hurt myself' it is reflexive (object of the verb)."),
    ("Choose the correct option: 'This is a secret between you and ___.'",
     ["me", "I", "myself", "mine"], 0, "After a preposition the object form is needed."),
    ("Choose the correct option: 'Each of the students must bring ___ own book.'",
     ["his or her", "their own's", "our", "its"], 0, "'Each' is singular, so a singular possessive is traditional (Wren & Martin)."),
    ("In 'This book is mine' and 'This is my book', the word 'this' is respectively a:",
     ["Demonstrative adjective; demonstrative pronoun", "Demonstrative pronoun; demonstrative adjective", "Pronoun in both", "Adjective in both"], 0, "Before a noun it qualifies the noun; standing alone it replaces the noun."),
    ("Choose the correct order of adjectives:",
     ["a beautiful old red Italian car", "a red old beautiful Italian car", "an Italian red old beautiful car", "an old beautiful Italian red car"], 0, "Usual order: opinion – size – age – shape – colour – origin – material – purpose."),
    ("Choose the correct sentence comparing two persons.",
     ["She is the more intelligent of the two sisters.", "She is the most intelligent of the two sisters.", "She is more intelligenter of the two sisters.", "She is the intelligentest of the two sisters."], 0, "With two persons the comparative degree is used."),
    ("'He has ___ friends, so he never feels lonely.' Choose the right word.",
     ["a few", "few", "a little", "little"], 0, "'A few' (some) is positive; 'few' means hardly any; 'little' is used with uncountable nouns."),
    ("Choose the correct form: 'The ___ toys were scattered on the floor.'",
     ["children's", "childrens'", "childrens", "children"], 0, "'Children' is a plural not ending in s, so it takes 's."),
    ("Identify the adjective in: 'The tall boy runs very fast.'",
     ["tall", "runs", "very", "fast"], 0, "'Tall' describes the noun boy; 'fast' here tells how he runs (adverb)."),
    ("Match the noun with its kind:\na. Delhi  b. Iron  c. Army  d. Kindness\n1. Abstract  2. Collective  3. Material  4. Proper",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Proper nouns name particular persons or places; material nouns name substances."),
    ("Consider the statements:\nI. In 'She is taller than I (am)', the pronoun 'I' is correct.\nII. 'Everyone have finished their work' is grammatically correct.\nWhich is/are correct?",
     I_II, 0, "'Everyone' takes a singular verb: 'Everyone has finished …'."),
    ("Assertion (A): 'Furniture' has no plural form 'furnitures'.\nReason (R): 'Furniture' is an uncountable noun.",
     AR, 0, "Uncountable nouns are not normally used in the plural; we say 'pieces of furniture'."),
    ("Assertion (A): 'Mathematics' is followed by a plural verb, as in 'Mathematics are difficult'.\nReason (R): 'Mathematics' ends in -s.",
     AR, 3, "Though it ends in -s, it is a singular subject name: 'Mathematics is difficult'. R is true, A is false."),
    ("Assertion (A): In 'The rich are not always happy', 'rich' is used as a noun.\nReason (R): An adjective preceded by 'the' can stand for a whole class of people.",
     AR, 0, "'The rich' means rich people; similarly 'the poor', 'the blind'."),
]

VERB_ADV_PREP_CONJ = [
    ("In 'The baby slept peacefully', the verb 'slept' is:",
     ["Intransitive", "Transitive", "Auxiliary", "Linking"], 0, "It has no object; 'peacefully' is an adverb of manner."),
    ("In 'She has finished her work', the word 'has' is a/an:",
     ["Auxiliary (helping) verb", "Main verb", "Adverb", "Preposition"], 0, "'Finished' is the main verb; 'has' helps to form the present perfect."),
    ("In 'He seems tired', the verb 'seems' is a:",
     ["Linking verb", "Transitive verb", "Modal verb", "Phrasal verb"], 0, "It links the subject to a word describing it."),
    ("In 'Swimming is a good exercise', the word 'swimming' is a:",
     ["Gerund (verbal noun)", "Present participle used as an adjective", "Finite verb", "Adverb"], 0, "It is the subject of the sentence, so it works as a noun."),
    ("Identify the kind of adverb in 'He will come tomorrow.'",
     ["Adverb of time", "Adverb of place", "Adverb of manner", "Adverb of frequency"], 0, "'Tomorrow' tells when."),
    ("In which sentence is 'fast' used as a verb?",
     ["Many people fast during festivals.", "He runs fast.", "This is a fast train.", "The colours are fast and will not fade."], 0, "The same word can be different parts of speech depending on its use."),
    ("'He works hard' and 'He hardly works' mean:",
     ["He works with effort; he does almost no work", "The same thing", "He works a lot; he works a lot slowly", "Both mean he does not work"], 0, "'Hardly' means scarcely; it is not the adverb form of 'hard'."),
    ("Choose the correct preposition: 'She is good ___ mathematics.'",
     ["at", "in", "on", "with"], 0, "The fixed expression is 'good at'."),
    ("Choose the correct preposition: 'Divide the sweets ___ the four children.'",
     ["among", "between", "within", "amongst of"], 0, "'Between' is used for two; 'among' for more than two."),
    ("Choose the correct option: 'He has been living here ___ 2015.'",
     ["since", "for", "from", "by"], 0, "'Since' marks a point of time; 'for' marks a period (for ten years)."),
    ("Choose the correct option: 'I prefer tea ___ coffee.'",
     ["to", "than", "over than", "from"], 0, "'Prefer' takes 'to', not 'than'."),
    ("Which of the following is a pair of correlative conjunctions?",
     ["neither … nor", "and … but", "because … so", "if … while"], 0, "Correlatives work in pairs: either … or, not only … but also, both … and."),
    ("Choose the correct verb: 'Neither Ravi nor his friends ___ come yet.'",
     ["have", "has", "is", "was"], 0, "With neither … nor, the verb agrees with the nearer subject ('friends')."),
    ("In 'I stayed at home because it was raining', the word 'because' is a:",
     ["Subordinating conjunction", "Coordinating conjunction", "Preposition", "Adverb of place"], 0, "It introduces a dependent (adverb) clause of reason."),
    ("'Alas! He is no more.' The word 'Alas' is an interjection expressing:",
     ["Sorrow", "Joy", "Surprise", "Approval"], 0, "'Hurrah!' expresses joy; 'Bravo!' approval."),
    ("Match the word in the sentence with its part of speech:\na. 'He walked AFTER me.'  b. 'He came AFTER I had left.'  c. 'He came soon AFTER.'  d. 'In AFTER years he became rich.'\n1. Adjective  2. Adverb  3. Conjunction  4. Preposition",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "A word's part of speech depends on its function in the sentence (Wren & Martin)."),
    ("Consider the statements:\nI. 'And', 'but', 'or' and 'so' are coordinating conjunctions.\nII. 'Although' is a coordinating conjunction.\nWhich is/are correct?",
     I_II, 0, "'Although' introduces a subordinate clause."),
    ("Assertion (A): In 'She sings beautifully', 'beautifully' is an adverb.\nReason (R): It modifies the verb 'sings', telling how she sings.",
     AR, 0, "Adverbs of manner answer the question 'how?'."),
    ("Assertion (A): 'The book is on the table' contains a preposition.\nReason (R): A preposition always comes at the end of a sentence.",
     AR, 2, "A is true ('on'). R is false: prepositions usually come before a noun or pronoun."),
    ("Assertion (A): In 'Birds fly', the verb 'fly' is intransitive.\nReason (R): Some verbs can be used both transitively and intransitively.",
     AR, 1, "Both true; 'fly' is intransitive here because it has no object, not because some verbs can be used both ways."),
]

TOPICS = {
    "Parts of Speech": [("1 · Nouns, Pronouns and Adjectives", NOUN_PRON_ADJ),
                        ("2 · Verbs, Adverbs, Prepositions, Conjunctions and Interjections", VERB_ADV_PREP_CONJ)],
}
