"""Paper 1 · General English · P1-ENG-07 Transformation – Degrees of Comparison (2 sub-topics × 20).
References: Wren & Martin, High School English Grammar and Composition (§ 'Comparison of Adjectives' and 'Transformation of
Sentences'); Michael Swan, Practical English Usage. Three REAL previous-year questions come from the KEA 2026 Kannada-English-Computer
paper (25 Jan 2026); KEA has published no key, so their answers were worked out by ExamSim and say so."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KPSC / SSC English). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

FORMS = [
    ("Read the sentence given below to find out whether there is an error which will be in one part of the sentence. The letter of that part is the answer.\nIt is better / to die / on your feet then / live on your knees.",
     ["It is better", "to die", "on your feet then", "live on your knees."], 2,
     "A comparative is followed by 'than', not 'then': 'It is better to die on your feet than live on your knees.'" + NOTE, "KEA 2026 KEC (NHK, 25 Jan 2026) · Q45"),
    ("Fill in the blank with suitable preposition given in the choices.\nPoorvika prefers fruit juice ____ coffee.",
     ["to", "than", "with", "against"], 0,
     "'Prefer' takes 'to', not 'than': prefer A to B. Likewise superior / inferior / senior / junior / prior + to." + NOTE, "KEA 2026 KEC (NHK, 25 Jan 2026) · Q50"),
    ("The three degrees of comparison of adjectives are:",
     ["Positive, comparative and superlative", "Simple, complex and compound", "Active, passive and middle", "Present, past and future"], 0,
     PYQ + "Positive: tall; comparative: taller; superlative: tallest."),
    ("Choose the correct comparative and superlative forms of 'good':",
     ["better, best", "gooder, goodest", "more good, most good", "well, better"], 0, "Irregular: good/well – better – best; bad/ill – worse – worst."),
    ("The comparative and superlative of 'bad' are:",
     ["worse, worst", "badder, baddest", "more bad, most bad", "worst, worse"], 0, PYQ + "Do not write 'more worse'."),
    ("Which of the following pairs is correctly matched with its superlative?",
     ["little – least", "many – mostest", "far – farest", "old – oldest only, never eldest"], 0,
     "little – less – least; many/much – more – most; far – farther/further – farthest/furthest; old – older/elder – oldest/eldest."),
    ("Choose the correct sentence about comparison of family members:",
     ["My elder brother is a doctor.", "My elder brother is elder than me.", "He is the oldest son of the family than me.", "She is elder to me by two years than him."], 0,
     PYQ + "'Elder/eldest' are used only for persons of the same family and are not followed by 'than'; 'older than' is used for others."),
    ("Fill in the blank: Of the two sisters, Meena is the ____ .",
     ["more intelligent", "most intelligent", "intelligentest", "much intelligent"], 0, "With two persons or things, use the comparative with 'the'."),
    ("Fill in the blank: Rahul is ____ than his brother.",
     ["taller", "tallest", "more tall", "the tallest"], 0, PYQ + "One-syllable adjectives take -er and -est."),
    ("Adjectives of three or more syllables form the comparative with:",
     ["more (e.g. more beautiful)", "-er (e.g. beautifuler)", "most only", "-est only"], 0, "Superlative: most beautiful."),
    ("Which sentence uses a double comparative wrongly?",
     ["This road is more wider than that one.", "This road is wider than that one.", "This is the widest road in town.", "That road is not as wide as this one."], 0,
     PYQ + "Use either '-er' or 'more', never both."),
    ("Which sentence uses the Latin comparative 'senior' correctly?",
     ["He is senior to me.", "He is senior than me.", "He is more senior than me to.", "He is seniorer than me."], 0,
     "Latin comparatives (senior, junior, superior, inferior, prior, anterior, posterior) take 'to'."),
    ("Fill in the blank: The climate of Bengaluru is better than ____ of Chennai.",
     ["that", "it", "this", "those"], 0, PYQ + "Compare like with like – climate with climate ('that of'). Plural nouns take 'those of'."),
    ("Which adjective is NOT normally compared (it is an 'absolute' adjective)?",
     ["unique", "big", "happy", "strong"], 0, "Unique, perfect, complete, round, square, supreme, ideal are not usually compared."),
    ("Choose the correct form: This is the ____ of the two plans.",
     ["better", "best", "most good", "goodest"], 0, PYQ + "Two plans → comparative."),
    ("Fill in the blank: The more you practise, ____ you become.",
     ["the better", "better", "the best", "more good"], 0, "The pattern 'the + comparative …, the + comparative' shows parallel increase."),
    ("Consider the statements:\nI. 'Farther' is used mainly for distance.\nII. 'Further' can also mean 'additional'.",
     I_II, 2, "Farther station; further information."),
    ("Assertion (A): 'She is the most cleverest girl in the class' is incorrect.\nReason (R): A double superlative should not be used.",
     AR, 0, "Correct: 'She is the cleverest girl' or 'the most clever girl'."),
    ("Assertion (A): 'Elder than' is correct English.\nReason (R): 'Elder' is used only for members of the same family.",
     AR, 3, "R is true, but 'elder' is not followed by 'than'; we say 'older than'."),
    ("Match the adjective with its superlative:\na. far  b. little  c. much  d. late (time)\n1. farthest  2. least  3. most  4. latest",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "late – later – latest (time); late – latter – last (order)."),
]

TRANSFORM = [
    ("Identify the Positive Degree of the sentence given below.\nRohan is more brilliant than any other boy in the class.",
     ["Rohan is more brilliant of all boys in the class.", "No other boy is as brilliant as Rohan in the class.", "Rohan is brilliant boy in the class.",
      "No any other boy is as brilliant as Rohan in the class."], 1,
     "Comparative 'more … than any other' → positive 'No other … is as … as'." + NOTE, "KEA 2026 KEC (NHK, 25 Jan 2026) · Q53"),
    ("Change into the comparative degree: Mount Everest is the highest peak in the world.",
     ["Mount Everest is higher than any other peak in the world.", "Mount Everest is higher than all peak in the world.",
      "No peak is as high as Mount Everest in the world is higher.", "Mount Everest is more high than other peaks."], 0,
     PYQ + "Superlative → comparative: 'higher than any other + singular noun'."),
    ("Change into the positive degree: Mount Everest is the highest peak in the world.",
     ["No other peak in the world is as high as Mount Everest.", "Mount Everest is very high.", "Mount Everest is higher than other peaks.", "Some peaks are as high as Mount Everest."], 0,
     "Superlative → positive: 'No other … is as … as'."),
    ("Change into the superlative degree: No other metal is as useful as iron.",
     ["Iron is the most useful metal.", "Iron is more useful than other metal.", "Iron is very useful.", "Iron is as useful as other metals."], 0,
     PYQ + "Positive 'No other … as … as' → superlative 'the most …'."),
    ("Change into the comparative degree: Very few cities in India are as large as Mumbai.",
     ["Mumbai is larger than most other cities in India.", "Mumbai is larger than any other city in India.", "Mumbai is the largest city in India.", "Mumbai is not larger than many cities."], 0,
     "'Very few … as … as' → 'larger than most other …' → superlative 'one of the largest'."),
    ("Change into the superlative degree: Very few cities in India are as large as Mumbai.",
     ["Mumbai is one of the largest cities in India.", "Mumbai is the largest city in India.", "Mumbai is larger than all cities in India.", "Mumbai is a large city in India."], 0,
     PYQ + "'Very few' keeps the meaning 'one of the …'."),
    ("Change into the positive degree: Gold is more precious than silver.",
     ["Silver is not as precious as gold.", "Silver is as precious as gold.", "Gold is the most precious.", "Gold is not so precious as silver."], 0,
     "'A is more … than B' → 'B is not as/so … as A'."),
    ("Change into the comparative degree: Ravi is not so strong as Mohan.",
     ["Mohan is stronger than Ravi.", "Ravi is stronger than Mohan.", "Mohan is the strongest.", "Ravi is as strong as Mohan."], 0, PYQ + "Reverse the subjects when changing 'not so … as'."),
    ("Change into the superlative degree: Kalidasa is greater than any other Sanskrit poet.",
     ["Kalidasa is the greatest Sanskrit poet.", "Kalidasa is one of the greatest Sanskrit poets.", "Kalidasa is a great Sanskrit poet.", "No Sanskrit poet is greater than Kalidasa."], 0,
     "'Than any other' → 'the greatest' (not 'one of')."),
    ("Change into the positive degree: Kalidasa is the greatest Sanskrit poet.",
     ["No other Sanskrit poet is as great as Kalidasa.", "Some Sanskrit poets are as great as Kalidasa.", "Kalidasa is greater than some poets.", "Kalidasa is not so great as other poets."], 0,
     PYQ + "Superlative → positive with 'No other'."),
    ("Change into the comparative degree: Some boys are at least as clever as Arun.",
     ["Arun is not cleverer than some boys.", "Arun is cleverer than all the boys.", "Arun is the cleverest boy.", "Some boys are cleverer than all."], 0,
     "'At least as … as' → 'not … -er than'."),
    ("Change into the positive degree: Lead is heavier than all other metals.",
     ["No other metal is as heavy as lead.", "Lead is as heavy as other metals.", "Lead is the heaviest metal of all metals than.", "Some metals are as heavy as lead."], 0,
     PYQ + "(The sentence is for practice; in fact osmium is denser than lead.)"),
    ("Choose the correct transformation: 'This is one of the best books I have read.' (comparative)",
     ["This is better than most other books I have read.", "This is better than any other book I have read.", "No other book is as good as this.", "This is the best book."], 0,
     "'One of the best' = 'better than most other'."),
    ("Which sentence is grammatically correct?",
     ["Kolar is richer in gold than any other place in Karnataka.", "Kolar is richer in gold than any place in Karnataka.",
      "Kolar is richest in gold than any other place in Karnataka.", "Kolar is more richer in gold than other places in Karnataka."], 0,
     PYQ + "When comparing within the same group, use 'any other'; 'any' alone would include Kolar itself."),
    ("Which sentence correctly compares within a group?",
     ["Bengaluru is larger than any other city in Karnataka.", "Bengaluru is larger than any city in Karnataka.",
      "Delhi is larger than any other city in Karnataka.", "Bengaluru is largest than all the cities in Karnataka."], 0,
     "Delhi is not in Karnataka, so 'any other' would be wrong there – one would say 'any city in Karnataka'."),
    ("Change into the comparative degree: I have never seen so beautiful a sight.",
     ["This is more beautiful than any other sight I have seen.", "This is the more beautiful sight.", "This sight is beautiful than any.", "I have seen more beautiful sights."], 0,
     PYQ + "Superlative: 'This is the most beautiful sight I have ever seen.'"),
    ("Consider the statements:\nI. 'A is the tallest' can be changed to 'A is taller than any other …'.\nII. 'A is one of the tallest' can be changed to 'A is taller than any other …'.",
     I_II, 0, "'One of the tallest' becomes 'taller than most other …'."),
    ("Assertion (A): 'No other boy is as tall as Ravi' and 'Ravi is the tallest boy' have the same meaning.\nReason (R): Transformation of degrees changes the form of a sentence without changing its meaning.",
     AR, 0, "That is the rule for all transformations."),
    ("Assertion (A): 'Very few poets are as great as Kuvempu' becomes 'Kuvempu is the greatest poet' in the superlative.\nReason (R): 'Very few … as … as' means that a few others are equally great.",
     AR, 3, "It becomes 'Kuvempu is one of the greatest poets'; R is true."),
    ("Arrange to form the correct comparative sentence:\nP: than any other\nQ: Sachin scored\nR: more runs\nS: batsman in the match",
     ["QRPS", "QPRS", "RQPS", "QRSP"], 0, PYQ + "Sachin scored more runs than any other batsman in the match."),
]

TOPICS = {
    "Transformation – Degrees of Comparison": [("1 · Forms of Comparison and Common Errors", FORMS),
                                               ("2 · Transformation – Positive, Comparative and Superlative", TRANSFORM)],
}
