"""Paper 1 · General Knowledge · P1-GK-01 and P1-GK-02 (4 sub-topics × 20). Only long-established facts (no current affairs).
References: Lucent's General Knowledge; NCERT Science textbooks; Jnanpith award records."""
from packlib import AR, I_II

INDIAN_BOOKS = [
    ("Who was the first Kannada writer to receive the Jnanpith Award (1967)?",
     ["Kuvempu", "D. R. Bendre", "Shivaram Karanth", "Masti Venkatesha Iyengar"], 0, "Kuvempu was honoured for Sri Ramayana Darshanam."),
    ("'Sri Ramayana Darshanam' was written by:",
     ["Kuvempu", "V. K. Gokak", "Pampa", "Kumaravyasa"], 0, "An epic retelling of the Ramayana in modern Kannada."),
    ("'Naku Tanti', the work for which he received the Jnanpith Award, was written by:",
     ["D. R. Bendre", "Girish Karnad", "U. R. Ananthamurthy", "Chandrashekhara Kambara"], 0, "Bendre received the award in 1973."),
    ("'Mookajjiya Kanasugalu' is a Jnanpith-winning novel by:",
     ["K. Shivaram Karanth", "S. L. Bhyrappa", "Poornachandra Tejasvi", "A. N. Krishna Rao"], 0, "Karanth received the Jnanpith in 1977."),
    ("'Chikkaveera Rajendra', a historical novel about the last king of Kodagu, was written by:",
     ["Masti Venkatesha Iyengar", "Kuvempu", "Shivaram Karanth", "Girish Karnad"], 0, "Masti received the Jnanpith Award (1983) for it."),
    ("Match the Kannada work with its author:\na. Samskara  b. Tughlaq  c. Parva  d. Karvalo\n1. S. L. Bhyrappa  2. Poornachandra Tejasvi  3. U. R. Ananthamurthy  4. Girish Karnad",
     ["a-3, b-4, c-1, d-2", "a-4, b-3, c-1, d-2", "a-3, b-4, c-2, d-1", "a-1, b-4, c-3, d-2"], 0, "Samskara (novel), Tughlaq (play), Parva (Mahabharata novel), Karvalo (novel)."),
    ("'Bharata Sindhu Rashmi', for which he received the Jnanpith Award in 1990, was written by:",
     ["V. K. Gokak", "Masti Venkatesha Iyengar", "D. R. Bendre", "Kuvempu"], 0, "An epic on the Vedic sage Vishwamitra."),
    ("'Kavirajamarga', the earliest available literary work in Kannada (on poetics), is attributed to:",
     ["Srivijaya, at the court of Amoghavarsha I", "Pampa", "Ranna", "Basavanna"], 0, "Written in the 9th century in the Rashtrakuta court."),
    ("'Vikramarjuna Vijaya' (Pampa Bharata) and 'Adipurana' were written by:",
     ["Adikavi Pampa", "Ponna", "Ranna", "Janna"], 0, "Pampa (10th century) is called the Adikavi of Kannada."),
    ("'Karnata Bharata Kathamanjari' (Gadugina Bharata) was written by:",
     ["Kumaravyasa", "Lakshmisha", "Harihara", "Raghavanka"], 0, "Kumaravyasa's Mahabharata is in the shatpadi metre."),
    ("Which pair of book and author is INCORRECTLY matched?",
     ["Anandamath – Premchand", "Gitanjali – Rabindranath Tagore", "Godan – Premchand", "The Discovery of India – Jawaharlal Nehru"], 0, "Anandamath (which contains 'Vande Mataram') was written by Bankim Chandra Chatterjee."),
    ("'Wings of Fire', an autobiography, was written by:",
     ["A. P. J. Abdul Kalam (with Arun Tiwari)", "Vikram Sarabhai", "C. V. Raman", "Homi Bhabha"], 0, "It traces Kalam's life and India's missile programme."),
    ("Match the ancient Indian work with its author:\na. Arthashastra  b. Abhijnana Shakuntalam  c. Panchatantra  d. Indica\n1. Megasthenes  2. Vishnu Sharma  3. Kalidasa  4. Kautilya",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Megasthenes was the Greek ambassador at Chandragupta Maurya's court."),
    ("'Ain-i-Akbari' was written by:",
     ["Abul Fazl", "Babur", "Amir Khusrau", "Badauni"], 0, "It is part of the Akbarnama and describes Akbar's administration."),
    ("'Poverty and Un-British Rule in India', which put forward the 'drain theory', was written by:",
     ["Dadabhai Naoroji", "Bal Gangadhar Tilak", "Gopal Krishna Gokhale", "R. C. Dutt"], 0, "Naoroji argued that Britain drained India's wealth."),
    ("'Gita Rahasya' was written by Bal Gangadhar Tilak while he was imprisoned at:",
     ["Mandalay", "Andaman (Cellular Jail)", "Yerwada", "Tihar"], 0, "Tilak wrote it during his imprisonment in Mandalay (Burma), 1908–14."),
    ("Which Kannada work, translated into English, won the International Booker Prize in 2025?",
     ["Heart Lamp by Banu Mushtaq (translated by Deepa Bhasthi)", "Parva by S. L. Bhyrappa", "Samskara by U. R. Ananthamurthy", "Chomana Dudi by Shivaram Karanth"], 0, "It was the first Kannada book to win the prize."),
    ("Consider the statements:\nI. Arundhati Roy won the Booker Prize for 'The God of Small Things'.\nII. Aravind Adiga won the Booker Prize for 'The White Tiger'.\nWhich is/are correct?",
     I_II, 2, "Roy won in 1997 and Adiga in 2008."),
    ("Assertion (A): Gandhiji's 'Hind Swaraj' criticises modern Western civilisation.\nReason (R): 'My Experiments with Truth' is Gandhiji's autobiography.",
     AR, 1, "Both true, but his autobiography does not explain the argument of Hind Swaraj (1909)."),
    ("Assertion (A): 'Malgudi Days' is set in a fictional South Indian town.\nReason (R): Malgudi was created by R. K. Narayan.",
     AR, 0, "Malgudi is Narayan's imaginary town, the setting of many of his stories."),
]

WORLD_BOOKS = [
    ("'War and Peace' was written by:",
     ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Maxim Gorky"], 0, "A Russian novel set during Napoleon's invasion of Russia."),
    ("'Das Kapital' was written by:",
     ["Karl Marx", "Adam Smith", "Lenin", "J. M. Keynes"], 0, "The first volume appeared in 1867."),
    ("'The Wealth of Nations' (1776), the foundation of classical economics, was written by:",
     ["Adam Smith", "David Ricardo", "Karl Marx", "Thomas Malthus"], 0, "Smith is called the father of economics."),
    ("'On the Origin of Species' (1859) was written by:",
     ["Charles Darwin", "Gregor Mendel", "Alfred Russel Wallace", "Jean-Baptiste Lamarck"], 0, "It set out the theory of evolution by natural selection."),
    ("'The Republic', which describes an ideal state ruled by philosopher-kings, was written by:",
     ["Plato", "Aristotle", "Socrates", "Cicero"], 0, "Socrates wrote nothing; Plato presents his ideas in dialogues."),
    ("'Emile', a famous book on the natural education of a child, was written by:",
     ["Jean-Jacques Rousseau", "John Locke", "Friedrich Froebel", "John Dewey"], 0, "Rousseau also wrote 'The Social Contract'."),
    ("Match the book with its author:\na. Hamlet  b. Paradise Lost  c. Divine Comedy  d. Don Quixote\n1. Cervantes  2. Dante  3. John Milton  4. William Shakespeare",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "English, English, Italian and Spanish classics respectively."),
    ("'Animal Farm' and 'Nineteen Eighty-Four' were written by George Orwell, who was born in:",
     ["Motihari, India", "London, England", "Dublin, Ireland", "Rangoon, Burma"], 0, "Orwell (Eric Arthur Blair) was born in Bihar in 1903."),
    ("'The Prince', a classic work on political power, was written by:",
     ["Niccolò Machiavelli", "Thomas Hobbes", "John Locke", "Montesquieu"], 0, "Written in 1513 in Florence."),
    ("Which of these world classics is paired with the WRONG author?",
     ["Oliver Twist – Victor Hugo", "Pride and Prejudice – Jane Austen", "Les Misérables – Victor Hugo", "The Old Man and the Sea – Ernest Hemingway"], 0, "Oliver Twist was written by Charles Dickens."),
    ("'A Brief History of Time' was written by:",
     ["Stephen Hawking", "Albert Einstein", "Carl Sagan", "Richard Feynman"], 0, "A popular book on cosmology (1988)."),
    ("'Long Walk to Freedom' is the autobiography of:",
     ["Nelson Mandela", "Martin Luther King Jr.", "Barack Obama", "Desmond Tutu"], 0, "It describes his struggle against apartheid in South Africa."),
    ("'The Diary of a Young Girl' was written during the Second World War by:",
     ["Anne Frank", "Helen Keller", "Malala Yousafzai", "Virginia Woolf"], 0, "She wrote it while hiding from the Nazis in Amsterdam."),
    ("The epics 'Iliad' and 'Odyssey' are attributed to:",
     ["Homer", "Virgil", "Sophocles", "Ovid"], 0, "Virgil wrote the Latin epic 'Aeneid'."),
    ("Match the book with its author:\na. Gulliver's Travels  b. Robinson Crusoe  c. Uncle Tom's Cabin  d. Crime and Punishment\n1. Dostoevsky  2. Harriet Beecher Stowe  3. Daniel Defoe  4. Jonathan Swift",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Uncle Tom's Cabin strengthened the anti-slavery movement in the USA."),
    ("'One Hundred Years of Solitude' was written by:",
     ["Gabriel García Márquez", "Paulo Coelho", "Pablo Neruda", "Jorge Luis Borges"], 0, "A Colombian novel of magical realism."),
    ("'Leviathan', which argues for a strong sovereign to escape the 'state of nature', was written by:",
     ["Thomas Hobbes", "John Locke", "Rousseau", "Machiavelli"], 0, "Hobbes described life in the state of nature as 'solitary, poor, nasty, brutish and short'."),
    ("Consider the statements:\nI. 'Utopia' was written by Thomas More.\nII. 'Faust' was written by Goethe.\nWhich is/are correct?",
     I_II, 2, "More's Utopia (1516); Goethe's Faust (German drama)."),
    ("Assertion (A): 'Uncle Tom's Cabin' is linked with the anti-slavery movement in the USA.\nReason (R): The novel showed the cruelty of slavery and strengthened public opinion against it.",
     AR, 0, "Its vivid picture of slavery made it a powerful abolitionist book."),
    ("Assertion (A): 'The Social Contract' was written by Jean-Jacques Rousseau.\nReason (R): Rousseau also wrote 'Leviathan'.",
     AR, 2, "A is true. R is false: Leviathan was written by Thomas Hobbes."),
]

INVENTIONS = [
    ("The telephone was invented in 1876 by:",
     ["Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi", "Samuel Morse"], 0, "Bell received the patent for the telephone in 1876."),
    ("Match the invention with its inventor:\na. Printing press (movable type)  b. Dynamite  c. Aeroplane  d. Television\n1. John Logie Baird  2. Wright brothers  3. Alfred Nobel  4. Johannes Gutenberg",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Gutenberg c. 1440; Nobel 1867; Wright brothers 1903; Baird 1926."),
    ("The World Wide Web was invented in 1989 by:",
     ["Tim Berners-Lee", "Vint Cerf", "Bill Gates", "Charles Babbage"], 0, "He proposed it at CERN; Vint Cerf co-designed the TCP/IP protocols of the Internet."),
    ("Radio communication (wireless telegraphy) is associated mainly with:",
     ["Guglielmo Marconi", "Graham Bell", "Michael Faraday", "James Watt"], 0, "Marconi sent radio signals across the Atlantic in 1901; J. C. Bose also did pioneering work on microwaves."),
    ("James Watt is famous for:",
     ["Greatly improving the steam engine", "Inventing the telephone", "Discovering electricity", "Inventing the diesel engine"], 0, "His separate condenser made steam engines efficient; the unit of power is named after him."),
    ("The first vaccine, against smallpox, was developed in 1796 by:",
     ["Edward Jenner", "Louis Pasteur", "Jonas Salk", "Robert Koch"], 0, "Jenner used cowpox material to give protection against smallpox."),
    ("Match the medical invention with its inventor:\na. Rabies vaccine  b. Polio (injected) vaccine  c. Stethoscope  d. Insulin (isolation for treatment)\n1. Banting and Best  2. René Laennec  3. Jonas Salk  4. Louis Pasteur",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Pasteur 1885; Salk 1955; Laennec 1816; Banting and Best 1921."),
    ("The telegraph and the code of dots and dashes used with it are associated with:",
     ["Samuel Morse", "Graham Bell", "Edison", "Marconi"], 0, "Morse code was developed for the electric telegraph in the 1830s–40s."),
    ("The ballpoint pen in its modern form was invented by:",
     ["László Bíró", "Lewis Waterman", "George Parker", "Christopher Sholes"], 0, "In many countries a ballpoint pen is still called a 'biro'."),
    ("The mercury barometer was invented by:",
     ["Evangelista Torricelli", "Galileo Galilei", "Blaise Pascal", "Daniel Fahrenheit"], 0, "Torricelli made it in 1643."),
    ("The jet engine was developed independently by Frank Whittle in Britain and:",
     ["Hans von Ohain in Germany", "Rudolf Diesel", "Karl Benz", "Igor Sikorsky"], 0, "Both worked on turbojets in the 1930s."),
    ("The Analytical Engine, a design for a general-purpose mechanical computer, was proposed by:",
     ["Charles Babbage", "Blaise Pascal", "Herman Hollerith", "Alan Turing"], 0, "Babbage is called the father of the computer."),
    ("Which pair of invention and inventor is INCORRECTLY matched?",
     ["Revolver – Rudolf Diesel", "Safety lamp for miners – Humphry Davy", "Electric battery – Alessandro Volta", "Motor car (petrol) – Karl Benz"], 0, "The revolver was made popular by Samuel Colt; Diesel invented the diesel engine."),
    ("The transistor was invented in 1947 at Bell Laboratories by:",
     ["John Bardeen, Walter Brattain and William Shockley", "Jack Kilby and Robert Noyce", "Thomas Edison and Nikola Tesla", "Tim Berners-Lee and Robert Cailliau"], 0, "Kilby and Noyce later invented the integrated circuit."),
    ("The first working laser was built in 1960 by:",
     ["Theodore Maiman", "Albert Einstein", "C. V. Raman", "Niels Bohr"], 0, "Einstein had predicted stimulated emission, the principle behind lasers."),
    ("The cinematograph, used for the first public film shows in 1895, was developed by:",
     ["The Lumière brothers", "The Wright brothers", "Thomas Edison", "Dadasaheb Phalke"], 0, "Phalke made India's first full-length feature film, 'Raja Harishchandra' (1913)."),
    ("Consider the statements:\nI. Thomas Edison invented the phonograph.\nII. Thomas Edison invented the telephone.\nWhich is/are correct?",
     I_II, 0, "Edison invented the phonograph (1877) and a practical electric bulb; the telephone was Bell's."),
    ("Consider the statements:\nI. Michael Faraday discovered electromagnetic induction, the principle of the dynamo.\nII. Elisha Otis developed the safety elevator.\nWhich is/are correct?",
     I_II, 2, "Faraday 1831; Otis's safety brake made tall buildings practical."),
    ("Assertion (A): Alfred Nobel became very wealthy.\nReason (R): Nobel invented dynamite, which was widely used in mining and construction.",
     AR, 0, "His fortune from dynamite funded the Nobel Prizes."),
    ("Assertion (A): The Wright brothers made the first controlled, powered aeroplane flight in 1903.\nReason (R): The Wright brothers also invented the helicopter.",
     AR, 2, "A is true (Kitty Hawk). R is false: the practical helicopter is credited to Igor Sikorsky."),
]

DISCOVERIES = [
    ("The electron was discovered in 1897 by:",
     ["J. J. Thomson", "Ernest Rutherford", "James Chadwick", "Niels Bohr"], 0, "He used cathode rays."),
    ("The neutron was discovered in 1932 by:",
     ["James Chadwick", "J. J. Thomson", "Marie Curie", "Enrico Fermi"], 0, "Chadwick received the Nobel Prize in Physics in 1935."),
    ("The atomic nucleus was discovered through the gold-foil (alpha-scattering) experiment by:",
     ["Ernest Rutherford", "John Dalton", "J. J. Thomson", "Max Planck"], 0, "Most alpha particles passed through; a few bounced back from a small dense nucleus."),
    ("Radioactivity was discovered in 1896 by:",
     ["Henri Becquerel", "Marie Curie", "Wilhelm Röntgen", "Rutherford"], 0, "He observed uranium salts affecting photographic plates; the Curies then discovered polonium and radium."),
    ("X-rays were discovered in 1895 by:",
     ["Wilhelm Röntgen", "Henri Becquerel", "Marie Curie", "Michael Faraday"], 0, "Röntgen received the first Nobel Prize in Physics (1901)."),
    ("Penicillin was discovered in 1928 by:",
     ["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Joseph Lister"], 0, "He noticed that the Penicillium mould killed bacteria."),
    ("The circulation of blood in the human body was described in 1628 by:",
     ["William Harvey", "Edward Jenner", "Karl Landsteiner", "Robert Hooke"], 0, "Harvey showed that the heart pumps blood round the body."),
    ("The cell was first observed and named in 1665 by:",
     ["Robert Hooke", "Antonie van Leeuwenhoek", "Robert Brown", "Schleiden and Schwann"], 0, "He saw cells in a thin slice of cork."),
    ("The double-helix structure of DNA was proposed in 1953 by:",
     ["James Watson and Francis Crick", "Gregor Mendel", "Hugo de Vries", "Louis Pasteur"], 0, "X-ray work by Rosalind Franklin and Maurice Wilkins helped them."),
    ("The ABO blood groups were discovered by:",
     ["Karl Landsteiner", "William Harvey", "Edward Jenner", "Alexander Fleming"], 0, "This made safe blood transfusion possible."),
    ("The laws of inheritance were discovered from experiments on pea plants by:",
     ["Gregor Mendel", "Charles Darwin", "Hugo de Vries", "Lamarck"], 0, "Mendel is called the father of genetics."),
    ("The Raman Effect, discovered on 28 February 1928, is celebrated in India as:",
     ["National Science Day", "National Technology Day", "Teachers' Day", "Engineers' Day"], 0, "C. V. Raman received the Nobel Prize in Physics in 1930."),
    ("Match the scientist with the discovery:\na. Isaac Newton  b. Johannes Kepler  c. Archimedes  d. Nicolaus Copernicus\n1. Heliocentric (Sun-centred) theory  2. Principle of buoyancy  3. Laws of planetary motion  4. Law of universal gravitation",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each is a landmark of the history of physics and astronomy."),
    ("Match the Indian scientist with the work:\na. S. N. Bose  b. S. Chandrasekhar  c. Srinivasa Ramanujan  d. Jagadish Chandra Bose\n1. Response of plants to stimuli (crescograph)  2. Number theory and infinite series  3. Maximum mass of a white dwarf star  4. Statistics of photons (bosons)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Bosons are named after S. N. Bose; the Chandrasekhar limit is about 1.4 solar masses."),
    ("Oxygen was discovered independently in the 1770s by Joseph Priestley and:",
     ["Carl Wilhelm Scheele", "Henry Cavendish", "John Dalton", "Antoine Lavoisier"], 0, "Lavoisier named it and explained its role in burning; Cavendish discovered hydrogen."),
    ("The periodic table of elements arranged by atomic mass, with gaps for undiscovered elements, was proposed in 1869 by:",
     ["Dmitri Mendeleev", "Henry Moseley", "John Newlands", "Lothar Meyer"], 0, "Moseley later arranged elements by atomic number."),
    ("Consider the statements:\nI. Antonie van Leeuwenhoek was the first to observe bacteria with a microscope.\nII. Robert Koch identified the bacterium that causes tuberculosis.\nWhich is/are correct?",
     I_II, 2, "Leeuwenhoek (1670s) saw 'animalcules'; Koch identified Mycobacterium tuberculosis in 1882."),
    ("Consider the statements:\nI. Albert Einstein received the Nobel Prize for his theory of relativity.\nII. Albert Einstein explained the photoelectric effect.\nWhich is/are correct?",
     I_II, 1, "His 1921 Nobel Prize was for the photoelectric effect, not for relativity."),
    ("Assertion (A): Marie Curie received Nobel Prizes in two different sciences.\nReason (R): She won in Physics (1903) for work on radioactivity and in Chemistry (1911) for discovering polonium and radium.",
     AR, 0, "R describes exactly the two prizes that make A true."),
    ("Assertion (A): Galileo is known for improving the telescope and using it to observe Jupiter's moons.\nReason (R): Galileo discovered the law of universal gravitation.",
     AR, 2, "A is true (1610). R is false: universal gravitation was Newton's discovery."),
]

TOPICS = {
    "Famous Books and Authors": [("1 · Indian and Kannada Books and Authors", INDIAN_BOOKS),
                                 ("2 · World Classics and Famous Books", WORLD_BOOKS)],
    "Important Inventions and Discoveries": [("1 · Important Inventions", INVENTIONS),
                                             ("2 · Scientific Discoveries", DISCOVERIES)],
}
