"""Paper 1 · General Knowledge · real previous-year questions for GK-01 … GK-05 (topics generated before the owner asked for real
questions, 2 Oct 2026). Each topic gets one extra set, "Previous-Year Questions", so that people who already imported the topic
receive it on re-import. Questions are copied word for word (spacing lost in the scans restored, obvious typos corrected).
GTTC 2024 Assistant Gr-II GK answers come from KEA's official final key (30-12-2024); the others (KEA 2025–26 GK papers, VAO 2024,
PSI 2023/2024, Legislative Council 2024 Paper-1, KRIES entrance tests, GFGC 2021 GK, UPSC-coaching entrance tests) have no
reliable key online, so their answers were worked out by ExamSim and say so."""

KEY = " (Official answer: KEA final key.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

BOOKS = [
    ("The book, which made Kuvempu win \"Jnanpith Award\" in 1967 was",
     ["Malegalalli Madumagalu", "Kanooru Heggadati", "Sri Ramayana Darshanam", "Agnihamsa"], 2,
     "Kuvempu was the first Kannada writer to win the Jnanpith (1967), for his epic Sri Ramayana Darshanam." + NOTE, "PSI 2023 General Paper · Q44"),
    ("The author of the book 'Hasuru Honnu' is",
     ["B.G.L. Swamy", "D.V. Gundappa", "K.P. Poornachandra Tejaswi", "Shivaram Karanth"], 0,
     "Botanist-writer B. G. L. Swamy won the Kendra Sahitya Akademi award (1978) for Hasuru Honnu." + NOTE, "KRIES 2024 entrance · Q66"),
    ("The book written by Mummadi Krishnaraja Odeyar is",
     ["Padmini Parinaya", "Soundarya Kavya", "Sritattvanidhi", "Pujyapada Charitre"], 2,
     "Sritattvanidhi is an illustrated encyclopaedia of iconography compiled under Krishnaraja Wodeyar III." + NOTE, "Legislative Council 2024 Asst/Computer Operator P1 · Q75"),
    ("The book \"An Era of Darkness: The British Empire in India\" was written by:",
     ["Bipin Chandra", "V.D. Mahajan", "Urvashi Butalia", "Shashi Tharoor"], 3,
     "Published in 2016 (titled 'Inglorious Empire' outside India)." + NOTE, "KEA 2026 GK-2 (NHK, 25 Jan 2026) · Q30"),
    ("\"Chamarajokti Vilasa\" - is a Kannada translation of which book?",
     ["Vyasa's Mahabharata", "Valmiki's Ramayana", "Chamarasa's Prabhulingaleele", "Vishnu Sharma's Panchatantra"], 1,
     "It is a prose Kannada rendering of the Valmiki Ramayana made in the court of Chamaraja Wodeyar." + NOTE, "Legislative Council 2024 Programmer P1 · Q77"),
    ("Choose the incorrect pair from the following about literature and their author:",
     ["Bharavi - Kiratarjuniya", "Dandi - Dashakumara Charita", "Dharmapala - Mattavilas Prahasana", "Shiva Bhattaraka - Hara Parvatiya"], 2,
     "Mattavilasa Prahasana was written by the Pallava king Mahendravarman I." + NOTE, "VAO 2024 Paper-1 · Q86"),
    ("Who are the great poets of Hoysala period?\na. Ranna  b. Janna\nc. Harihara  d. Srinatha\nChoose the correct answer from the following codes.",
     ["b and c are correct", "a and d are correct", "a and b are correct", "c and d are correct"], 0,
     "Janna and Harihara wrote under the Hoysalas; Ranna was a court poet of the Kalyani Chalukyas, and Srinatha a Telugu poet of the Vijayanagara period." + NOTE,
     "Legislative Council 2024 Data Entry P1 · Q57"),
    ("Consider the following statements regarding 'Gatha-Saptasati'.\n(a) It was written by Hala.\n(b) It was written in Sanskrit language.\n(c) It has 700 verses.\n(d) It is in the form of Arya metre.\nChoose the correct answer from the following options.",
     ["(a) only is true", "(a) and (b) are true", "(a), (c) and (d) are true", "(a), (b) and (c) are true"], 2,
     "The Satavahana king Hala compiled it in Maharashtri Prakrit, not Sanskrit." + NOTE, "KEA 2026 GK-3 (NHK, 10 May 2026) · Q22"),
    ("Identify the mismatched pair between the poets and the literary works of the Hoysala period.",
     ["Nagachandra - Ramachandra Puranam", "Rajaditya - Vyavahara Ganitha", "Janna - Neminatha Purana", "Harihara - Girija Kalyana"], 2,
     "Janna wrote Yashodhara Charite and Anantanatha Purana; Neminatha Purana is by Karnaparya." + NOTE, "UPSC coaching entrance 2026 (HK) · Q82"),
]

INVENTIONS = [
    ("'Computer mouse' was invented by",
     ["Donat Banki", "Douglas Carl Engelbart", "David Alter", "Dr. Dennis Gabor"], 1,
     "Engelbart demonstrated the mouse in 1968; Gabor invented holography." + NOTE, "PSI 2023 General Paper · Q41"),
    ("Match the discoveries with the scientists:\nList-I: a) X-rays  b) Electron  c) Neutron  d) Proton\nList-II: i) J.J. Thomson  ii) James Chadwick  iii) Earnest Rutherford  iv) W.C. Roentgen",
     ["a – i, b – ii, c – iii, d – iv", "a – ii, b – i, c – iv, d – iii", "a – iv, b – ii, c – iii, d – i", "a – iv, b – i, c – ii, d – iii"], 3,
     "Roentgen – X-rays (1895); Thomson – electron (1897); Rutherford – proton (1917–19); Chadwick – neutron (1932)." + NOTE,
     "Legislative Council 2024 Asst/Computer Operator P1 · Q83"),
    ("The Telephone was invented by",
     ["Graham Bell", "Marconi", "John Baird", "Wright Brothers"], 0,
     "Alexander Graham Bell patented the telephone in 1876; Marconi – radio; Baird – television." + NOTE, "KRIES 2024 entrance · Q89"),
    ("Who among the following has discovered the phenomenon of photoelectric emission?",
     ["Einstein", "Faraday", "Millikan", "Heinrich Hertz"], 3,
     "Hertz observed it in 1887; Einstein explained it (1905) and won the 1921 Nobel Prize for it." + NOTE, "KEA 2026 GK-3 (HK, 4 Jul 2026) · Q44"),
    ("Name the Bangladeshi scientist who has developed the 'Sonali bag' - a jute-based eco-friendly alternative for polythene bag",
     ["Mubarak Ahmed Khan", "Abdus Sattar Khan", "Jamal Nazrul Islam", "Samir Kumar Saha"], 0,
     "The 'Sonali bag' is a biodegradable jute-cellulose sheet." + KEY, "GTTC 2024 Asst Gr-II GK · Q90"),
]

SCIENCE = [
    ("Which of the following statement/statements about cell is/are INCORRECT?\n(a) A cell is a structural and functional unit of living organism.\n(b) A cell has cytoplasm and nucleus.",
     ["Only a", "Both a and b", "Only b", "None"], 3,
     "Both statements are correct, so none is incorrect." + KEY, "GTTC 2024 Asst Gr-II GK · Q22"),
    ("The gravitational force between two bodies is:",
     ["Always repulsive", "Always attractive", "Attractive only at large distance", "Repulsive only at large distance"], 1,
     "Gravity is always attractive." + KEY, "GTTC 2024 Asst Gr-II GK · Q25"),
    ("The commercial unit of electric energy in electric meter is",
     ["Joule (J)", "Watt (W)", "Kilowatt hour (kWh)", "Horse Power (hp)"], 2,
     "1 kWh = 1 'unit' = 3.6 × 10⁶ J; the watt is a unit of power." + KEY, "GTTC 2024 Asst Gr-II GK · Q28"),
    ("When cold water is poured on a tin can filled with hot water and fitted with lid, it gets distorted because,",
     ["The pressure of air inside the can increases", "The pressure of air inside the can decreases", "Some amount of water in tin can become steam", "Volume of water inside the can increases"], 1,
     "The steam inside condenses, the inside pressure falls and atmospheric pressure crushes the can." + KEY, "GTTC 2024 Asst Gr-II GK · Q31"),
    ("Photosynthetic yield increases in which of these two coloured lights?",
     ["White and Green colour", "Red and Yellow colour", "Red and Blue colour", "Green and Yellow colour"], 2,
     "Chlorophyll absorbs red and blue light most; green is reflected." + KEY, "GTTC 2024 Asst Gr-II GK · Q32"),
    ("Yellowing of leaves is one of the symptoms of mineral deficiency in plants. This is due to",
     ["Loss of chlorophyll", "Death of tissue", "Death of cells", "Loss of flowering"], 0,
     "This is chlorosis – e.g. from a lack of nitrogen, magnesium or iron." + KEY, "GTTC 2024 Asst Gr-II GK · Q34"),
    ("Which layer has the coldest temperature in the atmosphere?",
     ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], 2,
     "The top of the mesosphere (about −90 °C) is the coldest part of the atmosphere." + KEY, "GTTC 2024 Asst Gr-II GK · Q38"),
    ("Which of the following is/are the gasses which cause greenhouse effect?\n(a) Nitrogen gas  (b) Water vapour\n(c) Oxygen gas  (d) Argon gas",
     ["a only", "b only", "c only", "Both c and d"], 1,
     "Water vapour, CO₂, methane, N₂O and CFCs are greenhouse gases; N₂, O₂ and Ar are not." + KEY, "GTTC 2024 Asst Gr-II GK · Q40"),
    ("The gases mixtures present in tanks used by scuba divers are",
     ["Helium, Oxygen, Nitrogen", "Oxygen, Nitrogen, Hydrogen", "Hydrogen, Oxygen, Helium", "Hydrogen, Helium, Nitrogen"], 0,
     "Deep-diving mixtures (trimix) use helium to reduce nitrogen narcosis." + NOTE, "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q6"),
    ("Food storing cans are made from electroplating of other metals onto iron. The metal used for electroplating of food cans is",
     ["Arsenic", "Copper", "Stannum", "Plumbum"], 2,
     "Stannum = tin; tin is less reactive than iron and non-toxic. Plumbum = lead." + NOTE, "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q8"),
    ("Production of bioethanol is through fermentation of ____ and starch components.",
     ["milk", "acid", "alcohol", "sugar"], 3,
     "Yeast ferments sugars (from cane, molasses or starch) into ethanol." + NOTE, "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q97"),
    ("Green coat on the surface of copper, brown coat on the surface of iron, blackening of silver on the surface. The above phenomena are due to",
     ["reduction of corresponding metal oxides", "conversion of metal oxide to the respective metals", "conversion of metal sulphide to the respective metals", "oxidation of corresponding metals"], 3,
     "These are forms of corrosion – copper carbonate, rust and silver sulphide form on the surface." + NOTE, "KEA 2026 GK-1 (NHK, 11 Jan 2026) · Q63"),
    ("A long steel rail is struck to produce sound. A person holding his ear near the rail at the other end hears the sound waves",
     ["once through steel only", "once through air only", "twice, first through steel and then through air", "twice, first through air and then through steel"], 2,
     "Sound travels much faster in solids (about 5,000 m/s in steel) than in air (about 340 m/s)." + NOTE, "KEA 2026 GK-1 (NHK, 11 Jan 2026) · Q69"),
    ("Sublimation is a process which converts",
     ["Liquid state into gaseous state", "Gaseous state into liquid state", "Solid state into gaseous state", "Solid state into liquid state"], 2,
     "Camphor, naphthalene and dry ice sublime." + NOTE, "Legislative Council 2024 Data Entry P1 · Q28"),
    ("Which of the following is NOT a hormone?",
     ["Insulin", "Melanin", "Melatonin", "Prolactin"], 1,
     "Melanin is a skin pigment; melatonin is the sleep hormone." + NOTE, "Legislative Council 2024 Data Entry P1 · Q30"),
    ("Name the Electromagnetic radiation used in MRI (Magnetic Resonance Imaging) scanning",
     ["Ultraviolet rays", "Radio waves", "Microwaves", "Gamma radiation"], 1,
     "MRI uses a strong magnetic field and radio-frequency waves – no ionising radiation." + NOTE, "VAO 2024 Paper-1 · Q76"),
    ("Which one of the following chemicals cannot be stored in a glass vessel?",
     ["Hydrochloric acid", "Sulphuric acid", "Hydrofluoric acid", "Tartaric acid"], 2,
     "HF attacks silica in glass; it is used for etching glass and stored in plastic." + NOTE, "VAO 2024 Paper-1 · Q72"),
    ("Eatables fried in oil and fat like chips, when exposed to moist air over a period of time develop bad odour due to rancidification of oil and fat. To avoid this, chips fried in oil are packed in flush bags by filling an inert gas. The inert gas usually is",
     ["O₂", "N₂", "Cl₂", "H₂"], 1,
     "Nitrogen prevents oxidation (rancidity)." + NOTE, "VAO 2024 Paper-1 · Q91"),
    ("Royal solvent is used to dissolve noble metals like gold and platinum. Aqua regia is a mixture of",
     ["Concentrated Hydrochloric acid and concentrated Nitric acid in the ratio 1:3", "Concentrated Hydrochloric acid and concentrated Nitric acid in the ratio 3:1", "Concentrated Sulphuric acid and concentrated Hydrochloric acid in the ratio 1:1", "Concentrated Sulphuric acid and concentrated Nitric acid in the ratio 1:1"], 1,
     "Aqua regia = 3 parts HCl : 1 part HNO₃." + NOTE, "KEA 2025 GK (HK, 21 Dec 2025) · Q82"),
    ("A metallic oxide that imparts purple colour to pottery is",
     ["Manganese dioxide", "Sodium oxide", "Copper oxide", "Lead oxide"], 0,
     "Manganese compounds give purple-brown tints to glazes and glass; copper gives green or blue." + NOTE, "PSI 2023 General Paper · Q39"),
    ("This part of a animal cell called as suicide bag is",
     ["Lysosome", "Ribosome", "Mitochondria", "Centrosome"], 0,
     "Lysosomes contain digestive enzymes; mitochondria are the 'powerhouse'." + NOTE, "PSI 2023 General Paper · Q46"),
    ("The planet that is called morning star is:",
     ["Earth", "Mercury", "Mars", "Venus"], 3,
     "Venus is also the 'evening star' and the brightest planet." + NOTE, "KRIES 2024 entrance · Q80"),
    ("An example for an artificial element is",
     ["Oxygen", "Plutonium", "Hydrogen", "Gold"], 1,
     "Plutonium is mainly made in nuclear reactors (technetium was the first artificial element)." + NOTE, "KRIES 2025 entrance · Q62"),
    ("Which of these two gases make the bulk of the atmosphere?",
     ["O₂ and CO₂", "N₂ and O₂", "H₂ and O₂", "H₂ and N₂"], 1,
     "Nitrogen about 78% and oxygen about 21%." + NOTE, "UPSC coaching entrance 2025 GS-1 · Q51"),
]

HEALTH = [
    ("Our body produces iodine containing hormone A the deficiency of which causes a disease called goitre. The hormone A is known as",
     ["Thyroxine", "Oxytocin", "Insulin", "Glucagon"], 0,
     "Thyroxine is made by the thyroid gland using iodine." + KEY, "GTTC 2024 Asst Gr-II GK · Q33"),
    ("Excess secretion of growth hormone in adults leads to a condition called",
     ["Goitre", "Acromegaly", "Beriberi", "Tetany"], 1,
     "In children, excess growth hormone causes gigantism." + KEY, "GTTC 2024 Asst Gr-II GK · Q35"),
    ("Match the following:\nList-I (Disease): a) Goitre  b) Acromegaly  c) Diabetes insipidus  d) Diabetes mellitus\nList-II (Deficiency): i. Vasopressin  ii. Insulin  iii. Growth hormone  iv. Iodine",
     ["a – iv, b – iii, c – i, d – ii", "a – i, b – ii, c – iii, d – iv", "a – iii, b – ii, c – i, d – iv", "a – ii, b – iii, c – iv, d – i"], 0,
     "Acromegaly is due to excess (not deficiency) of growth hormone – the list header is loose, but the pairing is standard." + NOTE, "PSI 2024 General Paper · Q44"),
    ("A person exhibits the symptoms such as increased alertness, Pupillary dilation, piloerection, sweating etc. These are due to the emergency situation and hormones responsible for this are",
     ["Oxytocin and Vasopressin", "Insulin and Glucagon", "Estrogen and Progesterone", "Adrenaline and Noradrenaline"], 3,
     "The adrenal medulla releases these 'fight or flight' hormones." + NOTE, "PSI 2024 General Paper · Q43"),
    ("Select the incorrect match.",
     ["Rhinovirus - Common cold", "Plasmodium - Pneumonia", "Entamoeba - Amoebiasis", "Trichophyton - Ringworm"], 1,
     "Plasmodium causes malaria; pneumonia is caused mainly by bacteria such as Streptococcus pneumoniae." + NOTE, "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q2"),
    ("Saturnism and Plumbism refer to",
     ["Diseases caused due to inhalation of clean static air", "Lead contamination", "Pulmonary disease caused due to ingestion of iron", "Mercury contamination"], 1,
     "Both are old names for lead poisoning (plumbum = lead; Saturn was the alchemists' symbol for lead)." + NOTE, "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q98"),
    ("Identify the correct statement with respect to AIDS/HIV.\nStatement I: AIDS is not a disease but it's a syndrome.\nStatement II: HIV belongs to retrovirus and its genetic material is RNA.",
     ["Statements I and II are incorrect", "Statement I is correct but Statement II is incorrect", "Statement I is incorrect but Statement II is correct", "Statements I and II are correct"], 3,
     "AIDS = Acquired Immuno-Deficiency Syndrome; HIV is an RNA retrovirus." + NOTE, "KEA 2026 GK-1 (NHK, 11 Jan 2026) · Q73"),
    ("Read the statements with regard to the diseases mentioned below\na. Amoebiasis spreads by house fly\nb. Malaria is mainly caused by contaminated food\nc. Pneumonia is mainly spread by mosquitoes\nd. Typhoid is generally spread by contaminated water\nIdentify the correct statements",
     ["a and b", "c and d", "b and c", "a and d"], 3,
     "Malaria is spread by female Anopheles mosquitoes; pneumonia by droplets." + NOTE, "Legislative Council 2024 Data Entry P1 · Q27"),
    ("The disease caused by the deficiency of Vitamin 'C' is:",
     ["Scurvy", "Rickets", "Night blindness", "Beriberi"], 0,
     "Rickets – vitamin D; night blindness – vitamin A; beriberi – vitamin B1." + NOTE, "KRIES 2024 entrance · Q73"),
    ("A person who had suffered from smallpox recovered from the disease and do not get the same disease normally in his lifetime. It is because",
     ["His body produces antibodies and the immunity is called natural active immunity", "His body produces antibodies and the immunity is called artificial active immunity", "His body produces antibodies and the immunity is called natural passive immunity", "His body produces antibodies and the immunity is called artificial passive immunity"], 0,
     "Immunity after an infection is natural active; after vaccination, artificial active." + NOTE, "KEA 2026 GK-3 (HK, 4 Jul 2026) · Q42"),
    ("Nipah virus primarily spreads through",
     ["Contaminated water", "Mosquito bites", "Fruit bats and infected animals", "Air pollution"], 2,
     "Fruit bats (Pteropus) are the natural host; outbreaks have occurred in Kerala." + NOTE, "KEA 2026 GK-3 (HK, 4 Jul 2026) · Q96"),
    ("A disease shows following symptoms:\n(a) Nasal congestion and discharge\n(b) Sore throat\n(c) Cough\n(d) Headache\n(e) Tiredness\nIdentify the disease showing these symptoms",
     ["Malaria", "Amoebic dysentery", "Ringworm", "Common cold"], 3,
     "The common cold is caused mainly by rhinoviruses." + NOTE, "KEA 2026 GK-2 (HK, 9 May 2026) · Q9"),
    ("Which of the following pairs of Vitamins and diseases is correctly matched?\na. Vitamin B6: Convulsions\nb. Vitamin B12: Pernicious anemia\nc. Vitamin A: Xerophthalmia\nSelect the correct answer using the options given below:",
     ["Only b", "Only b and c", "Only a and c", "a, b and c"], 3,
     "All three pairs are correct." + NOTE, "KEA 2026 GK-2 (NHK, 25 Jan 2026) · Q41"),
    ("Which of the following is incorrect regarding insulin?",
     ["It is an animal protein.", "It is secreted in liver.", "It controls the levels of sugar in blood.", "It is a hormone."], 1,
     "Insulin is secreted by the beta cells of the islets of Langerhans in the pancreas." + NOTE, "UPSC coaching entrance 2026 (HK) · Q59"),
    ("Viruses cause diseases in plants and animals. Viruses which infect bacteria are known as",
     ["Viroids", "Prions", "Lichens", "Bacteriophages"], 3,
     "Bacteriophages ('bacteria eaters') were used in phage therapy." + NOTE, "Legislative Council 2024 Programmer P1 · Q46"),
]

KARNATAKA = [
    ("Match the following:\nPrinting Press: a) Ambavilasa Printing Press  b) Basel Mission Press  c) Government Press  d) Subuddhi Prakasha Press\nPlace of Establishment: i. Bengaluru  ii. Mangalore  iii. Belgaum  iv. Mysore",
     ["a – ii, b – iii, c – iv, d – i", "a – iv, b – ii, c – iii, d – i", "a – iv, b – ii, c – i, d – iii", "a – iii, b – iv, c – ii, d – i"], 2,
     "Ambavilasa – Mysore; Basel Mission – Mangaluru (1841); Government Press – Bengaluru; Subuddhi Prakasha – Belagavi." + KEY, "GTTC 2024 Asst Gr-II GK · Q10"),
    ("Consider the following:\n(a) Mysore Civil Services Examination  (b) Prajapratinidhi Sabha\n(c) Agriculture Department  (d) Museum of Manuscripts\nHow many of the above were established / started during the time of K. Sheshadri Iyer?",
     ["Only one", "Only two", "Only three", "All the four"], 2,
     "KEA's key: three of them. The Representative Assembly (Prajapratinidhi Sabha, 1881) was started under C. Rangacharlu." + KEY, "GTTC 2024 Asst Gr-II GK · Q14"),
    ("Which of the following places are known for mural painting?\n(a) Badami caves  (b) Sittannavasal\n(c) Lepakshi  (d) Padmanabhapuram Palace",
     ["Only a and b are correct", "Only a, b and c are correct", "Only a and c are correct", "a, b, c and d are correct"], 3,
     "All four have famous murals (Badami – Chalukya; Sittannavasal – Pandya/Jaina; Lepakshi – Vijayanagara; Padmanabhapuram – Travancore)." + KEY, "GTTC 2024 Asst Gr-II GK · Q16"),
    ("Which Kannada Newspaper was published from Hindupura to support the formation of a responsible Government in Mysore and to create awareness of the struggle among Kannadigas?",
     ["Pauravani", "Mysore Star", "Karnataka Vartha", "Dhikkara"], 0,
     "It was published from Hindupur (just outside Mysore State) to escape press restrictions." + KEY, "GTTC 2024 Asst Gr-II GK · Q19"),
    ("Who was the first President of Akhanda Karnataka Rajya Nirmana Parishath?",
     ["Ramakrishna Karanth", "Benegal Ramaraya", "Alur Venkata Rao", "S. Nijalingappa"], 0,
     "As per KEA's key. Aluru Venkata Rao is called 'Kannada Kulapurohita'." + KEY, "GTTC 2024 Asst Gr-II GK · Q21"),
    ("The cave temples at Badami are built using",
     ["Soapstone", "Cuddapah stone", "Marble", "Sandstone"], 3,
     "The Badami Chalukyas cut their caves in red sandstone; Hoysala temples use soapstone (chloritic schist)." + NOTE, "KRIES 2024 entrance · Q94"),
    ("Ghatikas during the time of Hoysalas were:",
     ["Education Centre", "Trade Centre", "Spiritual Centre", "Industrial Centre"], 0,
     "Ghatikas and agraharas were centres of learning attached to temples." + NOTE, "GFGC 2021 GK · Q6"),
    ("The period of ____ is called the 'Golden Age of Mysore'.",
     ["Narasaraja II", "Chamaraja VI", "Krishnaraja Wodeyar IV", "Nanjaraja II"], 2,
     "Under Nalvadi Krishnaraja Wodeyar (1902–1940), with Diwans Visvesvaraya and Mirza Ismail." + NOTE, "PSI 2023 General Paper · Q72"),
    ("Identify the persons with historical connection with Shravanabelagola.\na) Chandragupta Maurya\nb) Chavundaraya\nc) Queen Shantala\nd) Chikka Devaraja Wodeyar\ne) Malik Kafur\nSelect the correct answer using the codes given below:",
     ["a, b and c", "a, b, c and d", "a, c, d and e", "b, c, d and e"], 1,
     "Chandragupta Maurya died there; Chavundaraya built the Gommateshwara statue; Shantala's death is recorded there; Chikkadevaraja built the Kalyani tank." + NOTE,
     "VAO 2024 Paper-1 · Q14"),
    ("With reference to the Hoysala temples, consider the following:\na) Ekakuta: Channakesava Temple, Belur\nb) Dwikuta: Hoysaleswara Temple, Halebeedu\nc) Trikuta: Lakshmi Temple, Doddagaddavalli\nd) Chatushkuta: Veeranarayana Temple, Belavadi\nHow many of the above temples are correctly matched?",
     ["Only one", "Only two", "Only three", "All the four"], 1,
     "Doddagaddavalli's Lakshmi Devi temple is chatushkuta (four shrines) and Belavadi's Veeranarayana temple is trikuta, so only (a) and (b) are right." + NOTE,
     "PSI 2024 General Paper · Q56"),
    ("Consider the following statements regarding the cave temples of Badami.\n(a) The first cave is a Shaiva cave\n(b) The second cave is a Vaishnavite cave\n(c) The third cave is a Shaiva cave\n(d) The fourth cave is a Jaina cave",
     ["All the four are correct", "Only three are correct", "Only two are correct", "Only one is correct"], 1,
     "Cave 3, the largest (578 CE, Mangalesha), is Vaishnava; cave 1 is Shaiva and cave 4 Jaina." + NOTE, "KEA 2026 GK-1 (NHK, 11 Jan 2026) · Q4"),
    ("The first co-operative society in Karnataka was established in",
     ["Kanakumbi", "Kadakol", "Kodihal", "Kanaginahal"], 3,
     "Kanaginahal (Gadag district), 1905 – also the first in India." + NOTE, "KEA 2026 GK-1 (NHK, 11 Jan 2026) · Q15"),
    ("Who is considered as the father of Co-operative Movement in Karnataka?",
     ["Kagodu Ganapathiappa", "Kadidal Manjappa", "Siddanagouda Sanna Ramanagouda Patil", "Shanthaveri Gopala Gowda"], 2,
     "He founded the Kanaginahal society in 1905." + NOTE, "KEA 2026 GK-1 (NHK, 11 Jan 2026) · Q16"),
]

TOPICS = {
    "Famous Books and Authors": [("3 · Previous-Year Questions", BOOKS)],
    "Important Inventions and Discoveries": [("3 · Previous-Year Questions", INVENTIONS)],
    "Basic Science – Concepts and Scientific Phenomena": [("4 · Previous-Year Questions", SCIENCE)],
    "Health and Hygiene": [("3 · Previous-Year Questions", HEALTH)],
    "Karnataka History, Culture and Art": [("4 · Previous-Year Questions", KARNATAKA)],
}
