"""Paper 1 · General Knowledge · P1-GK-07 Indian History and Culture – Medieval (3 sub-topics × 20).
References: NCERT Themes in Indian History II and Our Pasts II; Satish Chandra, Medieval India; KTBS Social Science;
Suryanath U. Kamath, A Concise History of Karnataka.
Each set includes REAL previous-year questions (exact English wording and printed option order, `source` = paper and question).
GTTC 2024 answers are from KEA's official final key; the others (KEA 2025–26 GK papers, VAO 2024, PSI 2023/2024, Legislative
Council 2024 Paper-1, UPSC-coaching entrance tests) have no reliable key online, so their answers were worked out by ExamSim
and say so. Spacing lost in the scans is restored; obvious typos are corrected."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "
KEY = " (Official answer: KEA final key.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

SULTANATE = [
    # --- real previous-year questions ---
    ("Assertion (A): Mahmud Ghazni made 17 raids on India\nReason (R): He wanted to establish a Muslim empire in India\nWhich one of the following options is correct with respect to the above statements?",
     ["Both statements 'A' and 'R' are correct and 'R' explains 'A'", "Both statements 'A' and 'R' are correct but 'R' does not explain 'A'", "Statement 'A' is correct but statement 'R' is incorrect", "Statement 'A' is incorrect but statement 'R' is correct"], 2,
     "Mahmud raided India 17 times (1000–1027) for its wealth, not to set up an empire here." + NOTE,
     "PSI 2024 General Paper · Q73"),
    ("Assertion (A): Iltutmish was the real founder of the Sultanate of Delhi\nReason (R): Iltutmish was the son of Qutb ud-Din Aibak\nWhich one of the following is correct in respect of the above statements?",
     ["Both Statements 'A' and 'R' are correct and 'R' explains 'A'", "Both Statements 'A' and 'R' are correct but 'R' does not explain 'A'", "Statement 'A' is correct but Statement 'R' is incorrect", "Statement 'A' is incorrect but Statement 'R' is correct"], 2,
     "Iltutmish consolidated the Sultanate, but he was Aibak's slave and son-in-law, not his son." + NOTE,
     "VAO 2024 Paper-1 · Q87"),
    ("With reference to the economic reforms of Alauddin Khalji, the term 'Sera-i-Adl' refers to what?",
     ["The market of horse and slave trade", "The central market for manufactured goods and imported cloth", "The office of the municipal grain inspector", "The tax-free zones established for local artisans"], 1,
     "Sera-i-Adl was the regulated market for cloth and other manufactured goods; Shahna-i-Mandi supervised the grain market." + NOTE,
     "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q50"),
    ("Identify the cities founded by Firoz Shah Tughlaq.",
     ["Delhi and Lahore", "Topra and Meerut", "Panipat and Sikandra", "Fatehabad and Hisar"], 3,
     "Firoz Shah also founded Firozabad and Jaunpur and brought the Topra and Meerut Ashokan pillars to Delhi." + NOTE,
     "KEA 2025 GK (HK, 21 Dec 2025) · Q36"),
    # --- new questions ---
    ("Mahmud of Ghazni plundered the famous Somnath temple in:",
     ["1025 CE", "1192 CE", "1206 CE", "1398 CE"], 0,
     PYQ + "Al-Biruni came to India with Mahmud and wrote Kitab-ul-Hind."),
    ("In the Second Battle of Tarain (1192):",
     ["Muhammad Ghori defeated Prithviraj Chauhan", "Prithviraj Chauhan defeated Muhammad Ghori", "Babur defeated Ibrahim Lodi", "Akbar defeated Hemu"], 0,
     PYQ + "Prithviraj had won the First Battle of Tarain in 1191."),
    ("The founder of the Slave (Mamluk) dynasty of Delhi in 1206 was:",
     ["Qutb-ud-din Aibak", "Iltutmish", "Balban", "Alauddin Khalji"], 0,
     PYQ + "He began the Qutub Minar, which Iltutmish completed."),
    ("The silver coin 'tanka' and the copper coin 'jital' were introduced by:",
     ["Iltutmish", "Balban", "Muhammad bin Tughlaq", "Sher Shah Suri"], 0,
     "Iltutmish also organised the iqta system."),
    ("The first and only woman ruler of the Delhi Sultanate was:",
     ["Razia Sultan", "Nur Jahan", "Rani Durgavati", "Chand Bibi"], 0,
     PYQ + "She ruled from 1236 to 1240."),
    ("The Sultan who introduced 'sijda' and 'paibos' and called the king 'Zil-i-Ilahi' (shadow of God) was:",
     ["Balban", "Iltutmish", "Firoz Shah Tughlaq", "Ibrahim Lodi"], 0,
     "His theory of kingship stressed the Sultan's majesty."),
    ("Branding of horses (dagh) and descriptive rolls of soldiers (huliya) were introduced by:",
     ["Alauddin Khalji", "Qutb-ud-din Aibak", "Bahlul Lodi", "Razia Sultan"], 0,
     PYQ + "His general Malik Kafur led campaigns deep into South India."),
    ("The Sultan who shifted the capital from Delhi to Daulatabad (Devagiri) and introduced token currency was:",
     ["Muhammad bin Tughlaq", "Firoz Shah Tughlaq", "Alauddin Khalji", "Sikandar Lodi"], 0,
     PYQ + "Both experiments failed."),
    ("The Moroccan traveller Ibn Battuta, author of the Rihla, visited India during the reign of:",
     ["Muhammad bin Tughlaq", "Akbar", "Krishnadevaraya", "Balban"], 0,
     PYQ + "He served as qazi of Delhi."),
    ("Timur invaded India and sacked Delhi in 1398 during the rule of the:",
     ["Tughlaq dynasty", "Lodi dynasty", "Slave dynasty", "Mughal dynasty"], 0,
     "The Sultan was Nasir-ud-din Mahmud Tughlaq."),
    ("The city of Agra was founded in 1504 by:",
     ["Sikandar Lodi", "Akbar", "Babur", "Bahlul Lodi"], 0,
     "Bahlul Lodi founded the Lodi dynasty in 1451."),
    ("The correct chronological order of the dynasties of the Delhi Sultanate is:",
     ["Slave → Khalji → Tughlaq → Sayyid → Lodi", "Khalji → Slave → Tughlaq → Lodi → Sayyid", "Slave → Tughlaq → Khalji → Sayyid → Lodi", "Tughlaq → Slave → Sayyid → Khalji → Lodi"], 0,
     PYQ + "1206–1526."),
    ("Amir Khusrau, called 'Tuti-i-Hind' (Parrot of India), was a disciple of:",
     ["Nizamuddin Auliya", "Muinuddin Chishti", "Kabir", "Guru Nanak"], 0,
     PYQ + "He is credited with developing qawwali and Hindavi poetry."),
    ("Match the Sultan with the measure:\na. Qutb-ud-din Aibak  b. Alauddin Khalji  c. Muhammad bin Tughlaq  d. Firoz Shah Tughlaq\n1. Canals and new towns such as Hisar  2. Token currency  3. Market control  4. Founded the Slave dynasty",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Ruler–measure matching is very common in KEA GK papers."),
    ("Consider the statements:\nI. Muhammad Ghori won the Second Battle of Tarain.\nII. Prithviraj Chauhan won the First Battle of Tarain.\nWhich is/are correct?",
     I_II, 2, "1191: Prithviraj won; 1192: Ghori won."),
    ("The Qutub Minar in Delhi was begun by Qutb-ud-din Aibak and completed by:",
     ["Iltutmish", "Balban", "Akbar", "Sher Shah Suri"], 0,
     "It was later repaired by Firoz Shah Tughlaq and Sikandar Lodi; it is a UNESCO World Heritage Site."),
]

MUGHAL_MARATHA = [
    # --- real previous-year questions ---
    ("Match the following:\nMughal Kings: a) Babur  b) Bahadur Shah II  c) Jahangir  d) Akbar\nTombs: i) Sikandra near Agra  ii) Kabul  iii) Rangoon  iv) Shahdara, Lahore",
     ["a - iii, b - ii, c - i, d - iv", "a - ii, b - iii, c - iv, d - i", "a - i, b - ii, c - iii, d - iv", "a - iv, b - iii, c - ii, d - i"], 1,
     "Babur – Kabul; Bahadur Shah II (exiled 1858) – Rangoon; Jahangir – Shahdara, Lahore; Akbar – Sikandra." + NOTE,
     "Legislative Council 2024 Asst/Computer Operator P1 · Q43"),
    ("Identify the brother of Abul Fazal, one of the Navaratnas who lived in Akbar's court.",
     ["Faizi", "Utbi", "Abdul Rahim", "Nazari"], 0,
     "Faizi, the poet laureate, was Abul Fazl's elder brother." + NOTE,
     "Legislative Council 2024 Asst/Computer Operator P1 · Q56"),
    ("Who among the following introduced the Zabti system and Dahasala system?",
     ["Raja Thodar Mal", "Raja Mansingh", "Iltutmish", "Balban"], 0,
     "Akbar's revenue minister Todar Mal measured land (zabt) and fixed revenue on ten-year averages (dahsala, 1580)." + NOTE,
     "KEA 2026 GK-2 (HK, 9 May 2026) · Q24"),
    ("Akbar built Buland Darwaza at Fatehpur Sikri to commemorate his victory over which province?",
     ["Gujarat", "Sindh", "Punjab", "Mewar"], 0,
     "Built c. 1575 after the conquest of Gujarat." + NOTE,
     "KEA 2026 GK-2 (HK, 9 May 2026) · Q25"),
    ("The two forms of taxes imposed upon the people during Shivaji's rule\n(i) Chauth\n(ii) Sardeshmukhi\n(iii) Swarajya\n(iv) Hoon",
     ["(i) and (ii)", "(ii) and (iii)", "(iii) and (iv)", "(i) and (iv)"], 0,
     "Chauth (one-fourth) and sardeshmukhi (an extra one-tenth) were collected from neighbouring territories." + NOTE,
     "KEA 2025 GK (HK, 21 Dec 2025) · Q27"),
    ("During his South Indian military expedition (1676-1679), with which rulers did Shivaji form an alliance?",
     ["Adil Shahi of Bijapur", "Qutub Shahi of Golconda", "Mughals", "Nayakas of Madurai"], 1,
     "Shivaji allied with Abul Hasan Qutb Shah of Golconda and his ministers Madanna and Akkanna." + NOTE,
     "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q52"),
    ("In 1672, Shivaji's army defeated the Mughals in which battle?",
     ["Battle of Pratapgad", "Battle of Salher", "Battle of Torna", "Battle of Purandar"], 1,
     "Salher (1672) was one of the first open-field Maratha victories over the Mughals; Pratapgad (1659) was against Afzal Khan of Bijapur." + NOTE,
     "KEA 2026 GK-2 (NHK, 25 Jan 2026) · Q18"),
    ("Chronologically arrange the following successors of Shivaji:\n(a) Shivaji II\n(b) Sambhaji\n(c) Shahu\n(d) Rajaram",
     ["(a), (b), (d), (c)", "(b), (d), (a), (c)", "(d), (a), (c), (b)", "(c), (d), (a), (b)"], 1,
     "Sambhaji (1680) → Rajaram (1689) → Shivaji II under Tarabai's regency (1700) → Shahu (1707)." + NOTE,
     "KEA 2026 GK-2 (HK, 9 May 2026) · Q76"),
    ("Arrange the following Maratha Peshwas in chronological order",
     ["Madhava Rao - Balaji Baji Rao - Baji Rao I - Balaji Vishwanath", "Balaji Vishwanath - Madhava Rao - Baji Rao I - Balaji Baji Rao", "Baji Rao I - Madhava Rao - Balaji Vishwanath - Balaji Baji Rao", "Balaji Vishwanath - Baji Rao I - Balaji Baji Rao - Madhava Rao"], 3,
     "Balaji Vishwanath (1713) → Baji Rao I (1720) → Balaji Baji Rao / Nana Saheb (1740) → Madhava Rao I (1761)." + NOTE,
     "KEA 2026 GK-2 (HK, 9 May 2026) · Q94"),
    # --- new questions ---
    ("The First Battle of Panipat (1526) was fought between:",
     ["Babur and Ibrahim Lodi", "Akbar and Hemu", "Ahmad Shah Abdali and the Marathas", "Humayun and Sher Shah"], 0,
     PYQ + "It founded Mughal rule in India."),
    ("Babur's autobiography, written in Turki, is the:",
     ["Tuzuk-i-Baburi (Baburnama)", "Akbarnama", "Humayun-nama", "Ain-i-Akbari"], 0,
     PYQ + "Humayun-nama was written by his daughter Gulbadan Begum."),
    ("Sher Shah Suri, who defeated Humayun at Chausa (1539) and Kannauj (1540), is remembered for:",
     ["Introducing the silver rupiya and rebuilding the road from Sonargaon to Peshawar (Grand Trunk Road)", "Building the Taj Mahal", "Founding the Sikh religion", "Starting the Din-i-Ilahi"], 0,
     PYQ + "His tomb is at Sasaram in Bihar."),
    ("The Second Battle of Panipat (1556) was fought between:",
     ["Akbar (under Bairam Khan) and Hemu", "Babur and Rana Sanga", "Aurangzeb and Shivaji", "Marathas and Abdali"], 0,
     "Hemu was the general of the Sur ruler Adil Shah."),
    ("The Mansabdari system and the Din-i-Ilahi (1582) are associated with:",
     ["Akbar", "Shah Jahan", "Aurangzeb", "Jahangir"], 0,
     PYQ + "Mansabs fixed rank (zat) and cavalry (sawar)."),
    ("The 'Chain of Justice' hung so that the oppressed could appeal to the emperor is associated with:",
     ["Jahangir", "Babur", "Aurangzeb", "Humayun"], 0,
     "Sir Thomas Roe visited his court (1615–19)."),
    ("The Taj Mahal, the Red Fort of Delhi and the Jama Masjid of Delhi were built by:",
     ["Shah Jahan", "Akbar", "Aurangzeb", "Jahangir"], 0,
     PYQ + "Shah Jahan's reign is called the golden age of Mughal architecture."),
    ("Jizya was reimposed on non-Muslims in 1679 by:",
     ["Aurangzeb", "Akbar", "Babur", "Jahangir"], 0,
     "Akbar had abolished it in 1564."),
    ("Shivaji's council of eight ministers was called the:",
     ["Ashtapradhan", "Navaratna", "Panchayat", "Diwan-i-Am"], 0,
     PYQ + "He was crowned Chhatrapati at Raigad in 1674."),
    ("The Third Battle of Panipat (1761) was fought between:",
     ["The Marathas and Ahmad Shah Abdali", "Babur and Ibrahim Lodi", "Akbar and Hemu", "The British and Tipu Sultan"], 0,
     PYQ + "The Maratha defeat weakened them for a decade."),
    ("Match the ruler with the monument:\na. Akbar  b. Shah Jahan  c. Sher Shah Suri  d. Qutb-ud-din Aibak\n1. Qutub Minar (begun)  2. His own tomb at Sasaram  3. Taj Mahal  4. Fatehpur Sikri",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Monument matching is a favourite GK question."),
]

SOUTH_BHAKTI = [
    # --- real previous-year questions ---
    ("Identify the dynasty to which Queen Rudramadevi belonged:",
     ["Chalukyas of Badami", "Pandyas of Madurai", "Kakatiyas of Warangal", "Eastern Chalukyas of Vengi"], 2,
     "Rudramadevi ruled the Kakatiya kingdom in the 13th century; Marco Polo praised her rule." + NOTE,
     "PSI 2023 General Paper · Q2"),
    ("Identify the Kings of Sangama dynasty who ruled Vijayanagara Empire.\na) Bukka II\nb) Vira Narasimha\nc) Deva Raya I\nd) Mallikarjuna\nSelect the correct answer using the codes given below:",
     ["a and b only", "b and d only", "a, b and d only", "a, c and d only"], 3,
     "Vira Narasimha belonged to the later Saluva/Tuluva lines; the other three were Sangamas." + NOTE,
     "VAO 2024 Paper-1 · Q13"),
    ("Which of the following works was NOT composed during the Vijayanagara Empire?",
     ["Karnataka Shabdanushasana", "Mahanataka Sudhanidhi", "Vasucharithramu", "Jagannatha Vijaya"], 3,
     "Jagannatha Vijaya was written by Rudrabhatta in the Hoysala period (12th century)." + KEY,
     "GTTC 2024 Asst Gr-II GK · Q9"),
    ("Consider the following and identify the founders of the dynasties.\nA: a) Bijapur Sultans  b) Ahmadnagar Sultans  c) Berar Sultans  d) Golconda Sultans\nB: i) Malik Ahmed  ii) Fateh Ulla Imad Shah  iii) Qutb Shah  iv) Yusuf Adil Shah",
     ["a - iii, b - iv, c - i, d - ii", "a - iv, b - i, c - ii, d - iii", "a - i, b - ii, c - iii, d - iv", "a - iv, b - iii, c - ii, d - i"], 1,
     "Yusuf Adil Shah (Bijapur), Malik Ahmad Nizam Shah (Ahmadnagar), Fathullah Imad Shah (Berar), Sultan Quli Qutb Shah (Golconda)." + NOTE,
     "Legislative Council 2024 Asst/Computer Operator P1 · Q68"),
    ("The Deccan Muslim state which declared Hindvi or Dakhni Urdu as the official language of the state instead of Persian was:",
     ["Bijapur", "Ahmadnagar", "Golconda", "Berar"], 0,
     "Ibrahim Adil Shah I of Bijapur replaced Persian with Hindavi (Dakhni) in state records." + NOTE,
     "UPSC coaching entrance 2026 (HK) · Q80"),
    ("The correct chronology of Religious Reformers is",
     ["Shankaracharya, Ramanujacharya, Madvacharya, Basaveshvara", "Sri Chaithanya, Ramanujacharya, Madvacharya, Basaveshvara", "Shankaracharya, Madvacharya, Ramanujacharya, Basaveshvara", "Madvacharya, Sri Chaithanya, Ramanujacharya, Shankaracharya"], 0,
     "Shankara (8th c.), Ramanuja (11th–12th c.), Madhva (13th c.). Strictly, Basavanna (12th c.) came before Madhva, but option 1 is the only one with the first three in order." + KEY,
     "GTTC 2024 Asst Gr-II GK · Q8"),
    ("Dara Shikoh belongs to the following Sufi order.",
     ["Qadiri order", "Nakshabandhi order", "Chishti order", "Suhrawardi order"], 0,
     "Dara Shikoh was a disciple of the Qadiri saint Mian Mir and translated the Upanishads into Persian (Sirr-i-Akbar)." + NOTE,
     "UPSC coaching entrance 2025 GS-1 · Q13"),
    # --- new questions ---
    ("The correct order of the four dynasties that ruled Vijayanagara is:",
     ["Sangama → Saluva → Tuluva → Aravidu", "Tuluva → Sangama → Aravidu → Saluva", "Saluva → Sangama → Tuluva → Aravidu", "Aravidu → Tuluva → Saluva → Sangama"], 0,
     PYQ + "Krishnadevaraya was the greatest Tuluva ruler."),
    ("The Brihadeeswara (Rajarajeswara) temple at Thanjavur was built by the Chola king:",
     ["Rajaraja I", "Rajendra I", "Karikala", "Kulottunga I"], 0,
     PYQ + "Completed about 1010 CE; it is part of the UNESCO 'Great Living Chola Temples'."),
    ("The Chola king who sent a naval expedition to Srivijaya (South-East Asia) and took the title 'Gangaikonda Chola' was:",
     ["Rajendra I", "Rajaraja I", "Parantaka I", "Vijayalaya"], 0,
     "He built a new capital, Gangaikonda Cholapuram."),
    ("The Uttaramerur inscriptions of Parantaka I are famous for describing:",
     ["Elections to village assemblies (sabha) in the Chola period", "The Battle of Talikota", "Akbar's revenue system", "The Delhi Sultanate's market reforms"], 0,
     PYQ + "Members were chosen by lot (kudavolai) from qualified candidates."),
    ("The Ramappa (Rudreswara) temple, a UNESCO World Heritage Site since 2021, was built under the:",
     ["Kakatiyas", "Hoysalas", "Cholas", "Bahmanis"], 0,
     "It is near Warangal, the Kakatiya capital, in Telangana."),
    ("The Tamil Bhakti saints called Alvars and Nayanars were devotees of, respectively:",
     ["Vishnu and Shiva", "Shiva and Vishnu", "Rama and Krishna", "Buddha and Mahavira"], 0,
     PYQ + "Their hymns started the Bhakti movement in South India (6th–9th centuries)."),
    ("The Bhakti saint who was a weaver and wrote dohas criticising rituals of both Hindus and Muslims was:",
     ["Kabir", "Tulsidas", "Chaitanya", "Ramananda"], 0,
     "Guru Nanak, founder of Sikhism, shared similar ideas."),
    ("The Adi Granth, the Sikh scripture, was compiled in 1604 by:",
     ["Guru Arjan Dev", "Guru Nanak", "Guru Gobind Singh", "Guru Tegh Bahadur"], 0,
     PYQ + "Guru Gobind Singh later declared the Granth Sahib the eternal Guru."),
    ("The Ramcharitmanas, the Awadhi retelling of the Ramayana, was written by:",
     ["Tulsidas", "Surdas", "Kabir", "Valmiki"], 0,
     "Surdas wrote the Sursagar in praise of Krishna."),
    ("The Sufi saint Khwaja Bande Nawaz Gesu Daraz, whose dargah is at Kalaburagi, belonged to the:",
     ["Chishti order", "Qadiri order", "Naqshbandi order", "Suhrawardi order"], 0,
     PYQ + "Muinuddin Chishti (Ajmer) and Nizamuddin Auliya (Delhi) were also Chishtis."),
    ("Match the Bhakti saint with the region:\na. Jnaneshwar  b. Shankaradeva  c. Mirabai  d. Chaitanya\n1. Bengal  2. Rajasthan  3. Assam  4. Maharashtra",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Saint–region matching is common in KEA papers."),
    ("Match the saint with the teaching:\na. Ramanuja  b. Madhva  c. Basavanna  d. Chaitanya\n1. Krishna bhakti in Bengal  2. Vachanas and the Lingayat movement  3. Dvaita (dualism)  4. Vishishtadvaita (qualified non-dualism)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Saint–philosophy matching is common in KEA papers."),
    ("Consider the statements:\nI. The Alvars sang in praise of Vishnu.\nII. Jnaneshwar wrote a Marathi commentary on the Bhagavad Gita.\nWhich is/are correct?",
     I_II, 2, "The Jnaneshwari (1290) is that commentary."),
]

TOPICS = {
    "Indian History and Culture – Medieval": [("1 · Early Invasions and the Delhi Sultanate", SULTANATE),
                                              ("2 · The Mughals and the Marathas", MUGHAL_MARATHA),
                                              ("3 · Medieval South India, the Deccan and the Bhakti–Sufi Movements", SOUTH_BHAKTI)],
}
