"""Paper 1 · General Knowledge · P1-GK-06 Indian History and Culture – Ancient (3 sub-topics × 20).
References: NCERT Themes in Indian History I; R. S. Sharma, India's Ancient Past; KTBS Social Science.
Each set includes REAL previous-year questions (exact English wording and printed option order, `source` = paper and question).
GTTC 2024 and Legislative Council 2024 answers are from KEA's official final keys; the others (KEA 2026 GK, VAO 2024, PSI 2024)
have no key online, so their answers were worked out by ExamSim and say so."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "
KEY = " (Official answer: KEA final key.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

INDUS_VEDIC = [
    ("Consider the following:\n(a) The Great Granary\n(b) The Great Bath\n(c) The Lower Town\n(d) The Dockyard\nHow many of the above was / were found at Mohenjodaro?",
     ["Only one", "Only two", "Only three", "All the four"], 2,
     "Granary, Great Bath and Lower Town are at Mohenjo-daro; the dockyard is at Lothal." + KEY, "GTTC 2024 Asst Gr-II GK · Q15"),
    ("Match the following:\nSites: a. Harappa  b. Mohenjo-daro  c. Kalibangan  d. Lothal\nExcavators: i) S.R. Rao  ii) M.S. Vatsa  iii) Y.D. Sharma  iv) B.K. Thapar  v) George F. Dales",
     ["a – i, b – ii, c – iii, d – v", "a – ii, b – v, c – iv, d – i", "a – iii, b – ii, c – v, d – i", "a – iv, b – v, c – ii, d – i"], 1,
     "Vatsa (Harappa), Dales (Mohenjo-daro, 1964), Thapar with B.B. Lal (Kalibangan), S.R. Rao (Lothal)." + KEY,
     "Legislative Council 2024 Data Entry P1 · Q8"),
    ("Match the following:\nSites: a) Harappa  b) Mohenjodaro  c) Kalibangan  d) Lothal\nProofs: i. Dockyard  ii. Granaries  iii. Gold coins  iv. Fire altars  v. The statue of dancing girl",
     ["a – i, b – iii, c – v, d – ii", "a – v, b – iv, c – iii, d – ii", "a – ii, b – v, c – iv, d – i", "a – iv, b – iii, c – ii, d – i"], 2,
     "Harappa – granaries; Mohenjo-daro – bronze dancing girl; Kalibangan – fire altars; Lothal – dockyard." + NOTE, "VAO 2024 Paper-1 · Q3"),
    ("Harappa was the first Indus site to be excavated (1921) under:",
     ["Daya Ram Sahni", "R. D. Banerji", "John Marshall alone", "Mortimer Wheeler"], 0, PYQ + "R. D. Banerji excavated Mohenjo-daro in 1922."),
    ("Evidence of a ploughed field has been found at:",
     ["Kalibangan", "Lothal", "Chanhudaro", "Dholavira"], 0, PYQ + "Kalibangan is in Rajasthan, on the Ghaggar river."),
    ("The Harappan city Dholavira was inscribed as a UNESCO World Heritage Site in 2021. It is in:",
     ["Gujarat", "Rajasthan", "Haryana", "Punjab"], 0, "It is in the Rann of Kutch and is known for its water management."),
    ("The famous 'Pashupati' seal was found at:",
     ["Mohenjo-daro", "Lothal", "Kalibangan", "Banawali"], 0, "It shows a seated figure surrounded by animals."),
    ("Most Harappan seals were made of:",
     ["Steatite (soapstone)", "Gold", "Iron", "Copper only"], 0, "Iron was unknown to the Harappans."),
    ("The Indus Valley people were the earliest known to cultivate:",
     ["Cotton", "Tea", "Coffee", "Rubber"], 0, PYQ + "The Greeks later called cotton 'sindon'."),
    ("The script of the Harappan civilisation:",
     ["Has not yet been deciphered", "Was deciphered by James Prinsep", "Is the same as Brahmi", "Was written on palm leaves"], 0, PYQ + "Prinsep deciphered Ashoka's Brahmi script."),
    ("The Rigveda consists of:",
     ["10 mandalas (books) and 1,028 hymns", "18 parvas", "7 kandas", "4 vedas"], 0, PYQ + "It is the oldest of the four Vedas."),
    ("The Gayatri Mantra, addressed to the Sun-god Savitri, is found in the:",
     ["Rigveda", "Samaveda", "Yajurveda", "Atharvaveda"], 0, PYQ + "It is in the third mandala."),
    ("The Veda that deals with melodies for chanting is the:",
     ["Samaveda", "Rigveda", "Yajurveda", "Atharvaveda"], 0, "It is regarded as the source of Indian music."),
    ("India's national motto 'Satyameva Jayate' is taken from the:",
     ["Mundaka Upanishad", "Rigveda", "Bhagavad Gita", "Ramayana"], 0, PYQ + "It appears below the national emblem."),
    ("Two popular assemblies of the early Vedic period were:",
     ["Sabha and Samiti", "Lok Sabha and Rajya Sabha", "Gram Sabha and Panchayat", "Parishad and Mandal"], 0, "They advised the chief (rajan)."),
    ("Match the Veda with its main content:\na. Rigveda  b. Samaveda  c. Yajurveda  d. Atharvaveda\n1. Charms, spells and medicine  2. Sacrificial formulae  3. Chants and melodies  4. Hymns of praise to gods",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "A frequently asked matching question."),
    ("Consider the statements:\nI. The Harappans used iron tools.\nII. The Great Bath was found at Mohenjo-daro.\nWhich is/are correct?",
     I_II, 1, "Harappans used copper and bronze; iron came later."),
    ("Consider the statements:\nI. The Rigveda is the oldest Veda.\nII. Upanishads are called Vedanta, the end part of the Vedas.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Lothal was an important Harappan port.\nReason (R): A dockyard has been found at Lothal.",
     AR, 0, "The dockyard shows its role in trade."),
    ("Assertion (A): The Harappan script was deciphered by James Prinsep.\nReason (R): James Prinsep deciphered the Brahmi script of Ashoka's edicts.",
     AR, 3, "The Harappan script is still undeciphered, so A is false."),
]

MAURYA = [
    ("Arrange the following Magadha dynasties in the chronological order:\na. Nandas\nb. Shungas\nc. Mauryas\nd. Haryankas\nChoose the answer from the options given below:",
     ["b, a, d, c", "d, a, c, b", "c, b, a, d", "a, c, d, b"], 1,
     "Haryanka → (Shishunaga) → Nanda → Maurya → Shunga." + NOTE, "KEA 2026 GK-2 (NHK, 25 Jan 2026) · Q23"),
    ("Identify the correct sequence of the dynasties who ruled Magadha.",
     ["Haryanka - Maurya - Shishunaga - Nanda - Shunga", "Haryanka - Shishunaga - Nanda - Maurya - Shunga", "Shishunaga - Nanda - Maurya - Shunga - Haryanka", "Shunga - Haryanka - Maurya - Shishunaga - Nanda"], 1,
     "Bimbisara and Ajatashatru (Haryanka) came first; Pushyamitra Shunga ended Maurya rule." + NOTE, "VAO 2024 Paper-1 · Q6"),
    ("Arrange the following Jain Tirthankars in chronological order.\n(a) Rishabhanatha\n(b) Shantinatha\n(c) Mallinatha\n(d) Neminatha",
     ["(a), (b), (c), (d)", "(a), (c), (d), (b)", "(c), (a), (d), (b)", "(a), (c), (b), (d)"], 0,
     "They are the 1st, 16th, 19th and 22nd Tirthankaras." + NOTE, "KEA 2026 GK-3 (HK, 4 Jul 2026) · Q25"),
    ("With reference to the Buddhist councils and their patronage of the dynasties, consider the following pairs:\na) First Buddhist Council: Shishunaga\nb) Second Buddhist Council: Haryanka\nc) Third Buddhist Council: Maurya\nd) Fourth Buddhist Council: Kushana\nWhich of the above pairs are correctly matched?",
     ["a, b and c", "b and d", "c and d", "b, c and d"], 2,
     "First council under Ajatashatru (Haryanka), second under Kalashoka (Shishunaga), third under Ashoka, fourth under Kanishka." + NOTE,
     "PSI 2024 General Paper · Q59"),
    ("By which name the special reporters in Ashoka's administration were called?",
     ["Rajukas", "Yuktas", "Pativedakas", "Amatyas"], 2,
     "Pativedakas reported public affairs to the king at any time (Rock Edict VI)." + NOTE, "KEA 2026 GK-3 (HK, 4 Jul 2026) · Q16"),
    ("The list of the sixteen Mahajanapadas is found in the Buddhist text:",
     ["Anguttara Nikaya", "Dipavamsa", "Mahavamsa", "Milindapanho"], 0, PYQ + "Jain texts such as the Bhagavati Sutra give another list."),
    ("The earliest capital of Magadha was:",
     ["Rajagriha (Girivraja)", "Pataliputra", "Vaishali", "Taxila"], 0, "The capital later moved to Pataliputra."),
    ("Vardhamana Mahavira, the 24th Tirthankara, was born at:",
     ["Kundagrama near Vaishali", "Lumbini", "Kapilavastu", "Pava"], 0, PYQ + "He attained nirvana at Pavapuri."),
    ("The 23rd Tirthankara of Jainism was:",
     ["Parshvanatha", "Rishabhanatha", "Neminatha", "Mallinatha"], 0, "Mahavira was the 24th."),
    ("Gautama Buddha delivered his first sermon (Dharmachakra Pravartana) at:",
     ["Sarnath", "Bodh Gaya", "Kushinagar", "Lumbini"], 0, PYQ + "Born at Lumbini, enlightened at Bodh Gaya, died at Kushinagar."),
    ("The three Pitakas of Buddhist literature are:",
     ["Vinaya, Sutta and Abhidhamma", "Rig, Sama and Yajur", "Anga, Upanga and Sutra", "Jataka, Dipavamsa and Mahavamsa"], 0, "Together called the Tripitaka."),
    ("Megasthenes, author of 'Indica', came to the court of Chandragupta Maurya as the ambassador of:",
     ["Seleucus Nikator", "Alexander", "Darius", "Ptolemy"], 0, PYQ + "Indica survives only in quotations by later writers."),
    ("The 'Arthashastra', a treatise on statecraft, is attributed to:",
     ["Kautilya (Chanakya)", "Kalidasa", "Megasthenes", "Banabhatta"], 0, PYQ + "He is traditionally the minister of Chandragupta Maurya."),
    ("Ashoka's change of heart and adoption of Dhamma followed his war against:",
     ["Kalinga", "Magadha", "Avanti", "Kosala"], 0, PYQ + "It is described in his Rock Edict XIII."),
    ("Chandragupta Maurya, according to Jain tradition, spent his last days at:",
     ["Shravanabelagola", "Pataliputra", "Ujjain", "Taxila"], 0, "Chandragiri hill there is named after him."),
    ("The last Mauryan ruler, Brihadratha, was killed by:",
     ["Pushyamitra Shunga", "Kanishka", "Kharavela", "Mahapadma Nanda"], 0, "This began the Shunga dynasty."),
    ("Match the place with the event in the Buddha's life:\na. Lumbini  b. Bodh Gaya  c. Sarnath  d. Kushinagar\n1. Mahaparinirvana  2. First sermon  3. Enlightenment  4. Birth",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "The four great places of Buddhist pilgrimage."),
    ("Consider the statements:\nI. Ashoka's edicts in most of India are in the Brahmi script.\nII. Some north-western edicts are in the Kharosthi script.\nWhich is/are correct?",
     I_II, 2, "Some are also in Greek and Aramaic."),
    ("Assertion (A): Ashoka gave up conquest by war after the Kalinga war.\nReason (R): The suffering caused by the war is described with regret in his Rock Edict XIII.",
     AR, 0, "The edict records his remorse."),
    ("Assertion (A): Mahavira founded Jainism as its first Tirthankara.\nReason (R): Jain tradition counts 24 Tirthankaras.",
     AR, 3, "Mahavira was the 24th Tirthankara; Rishabhanatha was the first. A is false."),
]

GUPTA = [
    ("Which of the following statements is INCORRECT regarding Gandhara Art?",
     ["It was the great contribution of Kanishka", "It was the centre of Mahayana sect", "It used red sandstone for idols", "Worshipping Buddha in the form of idol began"], 2,
     "Gandhara sculptures used grey-blue schist and stucco; red sandstone is typical of the Mathura school." + NOTE,
     "KEA 2026 GK-3 (HK, 4 Jul 2026) · Q23"),
    ("Consider the following books of Ancient India:\n(a) Buddhacharita\n(b) Saundarananda\n(c) Madhyamaka\n(d) Mahavibhasa\n(e) Sariputraprakarana\nWhich of the above books have been authored by Ashvaghosha?",
     ["(a), (b) and (c) only", "(a), (b) and (e) only", "(a), (c) and (e) only", "(b), (c) and (d) only"], 1,
     "Madhyamaka (Mulamadhyamakakarika) is by Nagarjuna; the Mahavibhasa is an Abhidharma commentary compiled in Kanishka's time." + NOTE,
     "KEA 2026 GK-1 (NHK, 11 Jan 2026) · Q10"),
    ("Choose from the following the incorrect statement about Guptas:",
     ["Chandragupta-I married a Licchavi princess and strengthened his kingdom", "Samudra Gupta began 'Gupta Era' in 320 C.E.", "Samudra Gupta was a great poet and music lover", "Chandra Gupta-II earned the title of \"Vikramaditya\""], 1,
     "The Gupta era of 320 CE is linked with Chandragupta I, not Samudragupta." + NOTE, "VAO 2024 Paper-1 · Q85"),
    ("Consider the following:\n(a) Harshavardhana\n(b) Pulikeshi II\n(c) Narasimha Verman II\nFor how many of the above kings courts did Huen Tsang visit?",
     ["Only one", "Only two", "All the three", "None"], 1,
     "Hiuen Tsang met Harsha and Pulakeshin II; at Kanchi the Pallava king was Narasimhavarman I, not II." + KEY,
     "GTTC 2024 Asst Gr-II GK · Q11"),
    ("The Saka era, used in India's national calendar, began in 78 CE and is associated with:",
     ["Kanishka", "Ashoka", "Chandragupta I", "Harsha"], 0, PYQ + "The Gupta era began in 320 CE."),
    ("The Allahabad Pillar inscription (Prayaga Prashasti) praising Samudragupta was composed by:",
     ["Harisena", "Kalidasa", "Banabhatta", "Ravikirti"], 0, PYQ + "Ravikirti wrote the Aihole inscription of Pulakeshin II."),
    ("Because of his many conquests, the historian V. A. Smith called Samudragupta the:",
     ["Napoleon of India", "Akbar of the South", "Ashoka of the North", "Caesar of India"], 0, PYQ + "His conquests are listed in the Allahabad Pillar inscription."),
    ("The Chinese pilgrim Fa-Hien visited India during the reign of:",
     ["Chandragupta II", "Harsha", "Ashoka", "Kanishka"], 0, PYQ + "Hiuen Tsang came later, during Harsha's reign."),
    ("Kalidasa, author of 'Abhijnanashakuntalam', is traditionally placed at the court of:",
     ["Chandragupta II (Vikramaditya)", "Ashoka", "Harsha", "Kanishka"], 0, "He is counted among the 'nine gems' (navaratnas)."),
    ("Aryabhata, author of 'Aryabhatiya', was a famous:",
     ["Mathematician and astronomer of the Gupta period", "Court poet of Harsha", "Buddhist monk of Nalanda", "Physician of Kanishka"], 0, PYQ + "He stated that the earth rotates on its axis."),
    ("Nalanda Mahavihara, the great centre of learning, was founded in the 5th century CE by:",
     ["Kumaragupta I", "Ashoka", "Harsha", "Kanishka"], 0, PYQ + "It flourished further under Harsha and the Palas."),
    ("The rust-free Iron Pillar at Mehrauli (Delhi) belongs to the period of the:",
     ["Guptas", "Mauryas", "Kushanas", "Satavahanas"], 0, "It is usually linked with Chandragupta II."),
    ("'Harshacharita', the biography of Harshavardhana, was written by:",
     ["Banabhatta", "Kalidasa", "Kalhana", "Bilhana"], 0, PYQ + "Harsha himself wrote the plays Nagananda, Ratnavali and Priyadarshika."),
    ("The Ajanta caves, famous for their wall paintings, are mainly:",
     ["Buddhist", "Jain", "Hindu", "Islamic"], 0, "They are in Maharashtra and are a UNESCO World Heritage Site."),
    ("Charaka, the author of the 'Charaka Samhita' on medicine, is traditionally said to be the court physician of:",
     ["Kanishka", "Chandragupta Maurya", "Harsha", "Samudragupta"], 0, "Sushruta is known for surgery (Sushruta Samhita)."),
    ("The three Tamil kingdoms of the Sangam age were:",
     ["Cheras, Cholas and Pandyas", "Chalukyas, Pallavas and Cholas", "Satavahanas, Kadambas and Gangas", "Kushanas, Sakas and Pahlavas"], 0, PYQ + "'Tolkappiyam' is the oldest surviving Tamil grammar."),
    ("Match the scholar with the work:\na. Kalidasa  b. Banabhatta  c. Aryabhata  d. Varahamihira\n1. Brihat Samhita  2. Aryabhatiya  3. Harshacharita  4. Meghaduta",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Classical authors and their works."),
    ("Consider the statements:\nI. Fa-Hien visited India during Harsha's reign.\nII. Hiuen Tsang studied at Nalanda.\nWhich is/are correct?",
     I_II, 1, "Fa-Hien came under Chandragupta II."),
    ("Assertion (A): The Gupta period is often called the 'Classical Age' of ancient India.\nReason (R): It saw great achievements in literature, art, science and mathematics.",
     AR, 0, "Kalidasa, Aryabhata and Gupta temples belong to this period."),
    ("Assertion (A): Gandhara art used mainly red sandstone.\nReason (R): Gandhara art was influenced by Greek (Hellenistic) styles.",
     AR, 3, "Gandhara used grey-blue schist; A is false, R is true."),
]

TOPICS = {
    "Indian History and Culture – Ancient": [("1 · Indus Valley and Vedic Age", INDUS_VEDIC),
                                            ("2 · Mahajanapadas, Jainism, Buddhism and the Mauryas", MAURYA),
                                            ("3 · Post-Mauryan and Gupta Age", GUPTA)],
}
