"""Paper 1 · General Knowledge · P1-GK-08 Indian History and Culture – Modern (3 sub-topics × 20).
Coverage (planner): modern India, freedom struggle, reformers.
References: NCERT Themes in Indian History III and Our Pasts III; Bipan Chandra, India's Struggle for Independence; Spectrum,
A Brief History of Modern India; KTBS Social Science.
Each set includes REAL previous-year questions (exact English wording and printed option order, `source` = paper and question).
GTTC 2024 answers are from KEA's official final key; the others (KEA 2025–26 GK papers, VAO 2024, PSI 2023, Legislative Council
2024 Paper-1, UPSC-coaching entrance tests) have no reliable key online, so their answers were worked out by ExamSim and say so.
Spacing lost in the scans is restored; obvious typos are corrected. Karnataka-specific events already covered in GK-04/05 are
not repeated."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "
KEY = " (Official answer: KEA final key.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

BRITISH = [
    # --- real previous-year questions ---
    ("Match the following places with the significant events during the Revolt of 1857:\nPlaces: a) Meerut  b) Delhi  c) Behrampur  d) Kanpur\nEvents: i. Early refusal by sepoys to use the Enfield Rifle happened here  ii. Sepoy attacked the British cantonment and captured the city  iii. Nanasaheb led the uprising  iv. The revolt officially began here on May 10, 1857",
     ["a – ii, b – iv, c – i, d – iii", "a – iii, b – iv, c – i, d – ii", "a – i, b – ii, c – iii, d – iv", "a – iv, b – ii, c – i, d – iii"], 3,
     "The revolt began at Meerut on 10 May 1857; the rebels captured Delhi; the 19th Native Infantry at Berhampore refused the new cartridges in February 1857; Nana Saheb led at Kanpur." + KEY,
     "GTTC 2024 Asst Gr-II GK · Q17"),
    ("Which of the following statements regarding the rule of Viceroy Lord Ripon is/are correct?\n(a) He enacted the First Factory Act in 1881.\n(b) He established the District Board and Taluk Boards by issuing local resolutions in 1882.\n(c) The Mysore Wodeyar dynasty's power was restored.\n(d) In 1878, the Vernacular Press Act was introduced.",
     ["All the four are correct", "Only (a) and (b) are correct", "Only (a), (b) and (c) are correct", "Only (a), (b) and (d) are correct"], 2,
     "The Rendition of Mysore (1881) happened under Ripon; the Vernacular Press Act (1878) was Lytton's, and Ripon repealed it in 1882." + NOTE,
     "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q59"),
    ("Consider the following statements with regard to permanent settlement:\n(a) It was introduced by Cornwallis in 1793.\n(b) This system was executed in southern parts of India.\n(c) Zamindars paid 89% tax to the Government.\n(d) According to this system, the land ownership rights of the Zamindars were not hereditary.\nHow many of the above statement/statements is/are correct?",
     ["Only one statement is correct", "Only two statements are correct", "Only three statements are correct", "All four statements are correct"], 1,
     "(a) and (c) are correct (about 10/11 of the rent went to the Company). It applied to Bengal, Bihar and Orissa, and zamindari rights were hereditary." + NOTE,
     "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q60"),
    ("Who tried to implement 'Ryotwari' system in South India?\na) Alexander Read\nb) Holt Mackenzie\nc) Thomas Munro\nd) James Grant Duff\nChoose the correct answer from below:",
     ["a and b only", "a, b and c only", "a and c only", "b, c and d only"], 2,
     "Alexander Read began it in Baramahal and Thomas Munro extended it in Madras; Holt Mackenzie is linked with the Mahalwari system." + NOTE,
     "VAO 2024 Paper-1 · Q25"),
    # --- new questions ---
    ("In the Battle of Plassey (1757), Robert Clive defeated:",
     ["Siraj-ud-Daulah, Nawab of Bengal", "Mir Qasim", "Tipu Sultan", "Shah Alam II"], 0,
     PYQ + "Mir Jafar's betrayal helped the British win."),
    ("The Treaty of Allahabad (1765), after the Battle of Buxar, gave the East India Company:",
     ["The Diwani (right to collect revenue) of Bengal, Bihar and Orissa", "Control of Delhi", "The whole of South India", "Ownership of Mysore"], 0,
     PYQ + "Buxar (1764) defeated Mir Qasim, Shuja-ud-Daulah and Shah Alam II together."),
    ("Under the Regulating Act of 1773, the first Governor-General of Bengal was:",
     ["Warren Hastings", "Robert Clive", "Lord Cornwallis", "Lord Wellesley"], 0,
     PYQ + "The Act also set up a Supreme Court at Calcutta (1774)."),
    ("The Subsidiary Alliance system was introduced by:",
     ["Lord Wellesley", "Lord Dalhousie", "Lord Cornwallis", "Lord Curzon"], 0,
     PYQ + "The Nizam of Hyderabad was the first to accept it (1798)."),
    ("The Doctrine of Lapse, under which Satara was the first state annexed (1848), was applied by:",
     ["Lord Dalhousie", "Lord Canning", "Lord Ripon", "Lord Lytton"], 0,
     PYQ + "Jhansi, Nagpur and Sambalpur were also annexed under it."),
    ("The first railway line in India (1853) ran between:",
     ["Bombay and Thane", "Calcutta and Delhi", "Madras and Arcot", "Howrah and Hooghly"], 0,
     "It was opened during Lord Dalhousie's term."),
    ("The Mahalwari system of land revenue, settled with village communities, is associated with:",
     ["Holt Mackenzie", "Lord Cornwallis", "Thomas Munro", "Alexander Read"], 0,
     "It was used in the North-Western Provinces, Punjab and parts of Central India."),
    ("The immediate cause of the Revolt of 1857 was:",
     ["The use of greased cartridges for the new Enfield rifle", "The Partition of Bengal", "The Rowlatt Act", "The Vernacular Press Act"], 0,
     PYQ + "Mangal Pandey's attack at Barrackpore (March 1857) was an early sign."),
    ("Match the centre of the 1857 revolt with its leader:\na. Lucknow  b. Jhansi  c. Jagdishpur (Bihar)  d. Kanpur\n1. Nana Saheb  2. Kunwar Singh  3. Rani Lakshmibai  4. Begum Hazrat Mahal",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "A very common matching question."),
    ("By the Government of India Act, 1858:",
     ["Power passed from the East India Company to the British Crown, and the Governor-General became Viceroy", "India became independent", "Provinces were given full autonomy", "The Indian National Congress was founded"], 0,
     PYQ + "Lord Canning was the first Viceroy; Queen Victoria's Proclamation followed on 1 November 1858."),
    ("The Vernacular Press Act (1878) and the Delhi Durbar of 1877 are associated with:",
     ["Lord Lytton", "Lord Ripon", "Lord Curzon", "Lord Minto"], 0,
     "Ripon repealed the Vernacular Press Act in 1882."),
    ("The Partition of Bengal (1905) was carried out by:",
     ["Lord Curzon", "Lord Hardinge", "Lord Minto", "Lord Irwin"], 0,
     PYQ + "It was annulled in 1911 under Lord Hardinge."),
    ("The correct chronological order is:",
     ["Battle of Plassey → Battle of Buxar → Regulating Act → Permanent Settlement", "Battle of Buxar → Battle of Plassey → Permanent Settlement → Regulating Act", "Regulating Act → Battle of Plassey → Battle of Buxar → Permanent Settlement", "Permanent Settlement → Regulating Act → Battle of Buxar → Battle of Plassey"], 0,
     "1757, 1764, 1773, 1793."),
    ("Consider the statements:\nI. Lord Ripon is called the father of local self-government in India.\nII. The Ilbert Bill controversy took place during Ripon's rule.\nWhich is/are correct?",
     I_II, 2, "Both are true (1882 resolution; Ilbert Bill 1883)."),
    ("Assertion (A): The Revolt of 1857 led to the end of the East India Company's rule.\nReason (R): The Government of India Act, 1858 transferred power to the British Crown.",
     AR, 0, "The Act was the direct result of the revolt."),
    ("The Permanent Settlement of Bengal (1793) was introduced by:",
     ["Lord Cornwallis", "Lord Wellesley", "Warren Hastings", "Lord Dalhousie"], 0,
     "Cornwallis is also known for the Cornwallis Code and reforms in the civil services."),
]

REFORM_EARLY = [
    # --- real previous-year questions ---
    ("With reference to the first session of the Indian National Congress of 1885, consider the following:\n(a) Bhau Saheb Bhate\n(b) Gangadhar Rao Deshpande\n(c) Kolachalam Venkata Rao\n(d) Sabhapathi Mudaliyar\nHow many of the above participated from Karnataka?",
     ["Only one", "Only two", "Only three", "All the four"], 2,
     "KEA's key: three delegates from the Karnataka region attended the first session at Bombay." + KEY,
     "GTTC 2024 Asst Gr-II GK · Q13"),
    ("Consider the following statements regarding the sessions of Indian National Congress.\n(a) Founder A.O. Hume was the President of first session held at Bombay.\n(b) Extremist leader Bala Gangadhar Tilak was the President of 1907 Surat session.\n(c) Annie Besant became the first woman President of INC held at Calcutta session in 1917.\n(d) Jawahar Lal Nehru was the President of Lahore session in 1929.\nHow many of the above statement/s is/are correct?",
     ["All the four statements are correct", "Only three statements are correct", "Only two statements are correct", "Only one statement is correct"], 2,
     "Only (c) and (d) are correct: W. C. Bonnerjee presided over the first session, and Rash Behari Ghosh over Surat (1907)." + NOTE,
     "KEA 2026 GK-2 (HK, 9 May 2026) · Q16"),
    ("National Handloom Day is being observed on August 7. It is in commemoration of launch of which movement?",
     ["Quit India Movement", "Civil Disobedience Movement", "Non-Cooperation Movement", "Swadeshi Movement"], 3,
     "The Swadeshi Movement was launched at Calcutta Town Hall on 7 August 1905." + NOTE,
     "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q18"),
    ("Who founded first Hindu female school in Kolkata, India?",
     ["Jyothiba Phule", "Ishwarchandra Vidyasagar", "J.E.D. Bethune", "Macaulay"], 2,
     "John Elliot Drinkwater Bethune founded the Hindu Female School (later Bethune School) in 1849, with Vidyasagar's support." + NOTE,
     "UPSC coaching entrance 2026 (HK) · Q87"),
    ("Why did Gandhiji go to South Africa?",
     ["On invitation by the Indians in South Africa", "To study Law", "To fight a case of a Gujarati businessman", "To visit South Africa with family"], 2,
     "In 1893 he went to assist in a lawsuit of the merchant Dada Abdulla." + NOTE,
     "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q100"),
    ("Which of the following authors works influenced Gandhiji to start Sathyagraha Movement?\n(a) Leo Tolstoy\n(b) John Ruskin\n(c) Kallenbach\n(d) Raichand Bhai\nChoose the correct answer:",
     ["(a) and (b)", "(b) and (c)", "(a), (b) and (c)", "(a), (b) and (d)"], 3,
     "Tolstoy (The Kingdom of God Is Within You), Ruskin (Unto This Last) and his spiritual guide Raychandbhai; Kallenbach was a friend and supporter." + NOTE,
     "KEA 2026 GK-2 (HK, 9 May 2026) · Q75"),
    ("Assertion (A): Rash Behari Bose was captured and executed by the British\nReason (R): He along with Sachin Sanyal planned to organise a coordinated revolt in February 1915.",
     ["Assertion (A) is correct but Reason (R) is wrong", "Assertion (A) is wrong but Reason (R) is correct", "Both Assertion (A) and Reason (R) are correct and Reason (R) explains Assertion (A)", "Both Assertion (A) and Reason (R) are correct but Reason (R) does not explain Assertion (A)"], 1,
     "Rash Behari Bose escaped to Japan in 1915 and later handed over the Indian Independence League and INA to Subhas Bose." + NOTE,
     "KEA 2026 GK-1 (NHK, 11 Jan 2026) · Q40"),
    # --- new questions ---
    ("The Brahmo Samaj (1828) was founded by:",
     ["Raja Ram Mohan Roy", "Swami Dayananda Saraswati", "Swami Vivekananda", "Keshab Chandra Sen"], 0,
     PYQ + "His campaign led to the abolition of Sati by Lord William Bentinck in 1829."),
    ("The Arya Samaj (1875), with the call 'Go back to the Vedas', was founded by:",
     ["Swami Dayananda Saraswati", "Raja Ram Mohan Roy", "Jyotiba Phule", "Sri Narayana Guru"], 0,
     PYQ + "His major work is Satyarth Prakash."),
    ("The Ramakrishna Mission (1897) was founded by:",
     ["Swami Vivekananda", "Ramakrishna Paramahamsa", "Annie Besant", "Dayananda Saraswati"], 0,
     PYQ + "He spoke at the Parliament of the World's Religions in Chicago in 1893."),
    ("The Satyashodhak Samaj (1873) and the book 'Gulamgiri' are associated with:",
     ["Jyotiba Phule", "B. R. Ambedkar", "Periyar", "Gopal Krishna Gokhale"], 0,
     "Phule and Savitribai Phule opened a girls' school in Pune in 1848."),
    ("The Hindu Widows' Remarriage Act, 1856 was passed mainly through the efforts of:",
     ["Ishwar Chandra Vidyasagar", "Raja Ram Mohan Roy", "Sir Syed Ahmad Khan", "Bal Gangadhar Tilak"], 0,
     PYQ + "Lord Dalhousie drafted it; Lord Canning passed it."),
    ("The Aligarh Movement and the Muhammadan Anglo-Oriental College (1875) were started by:",
     ["Sir Syed Ahmad Khan", "Muhammad Ali Jinnah", "Maulana Azad", "Allama Iqbal"], 0,
     "The college became Aligarh Muslim University in 1920."),
    ("'One caste, one religion, one God for mankind' was the message of:",
     ["Sri Narayana Guru", "Swami Vivekananda", "Ramakrishna Paramahamsa", "Dayananda Saraswati"], 0,
     PYQ + "He led the social reform movement of the Ezhavas in Kerala."),
    ("The Indian National Congress was founded in 1885 by A. O. Hume; its first session was held at:",
     ["Bombay, presided over by W. C. Bonnerjee", "Calcutta, presided over by Dadabhai Naoroji", "Madras, presided over by Badruddin Tyabji", "Lahore, presided over by Nehru"], 0,
     PYQ + "72 delegates attended."),
    ("'Swaraj is my birthright and I shall have it' was said by:",
     ["Bal Gangadhar Tilak", "Lala Lajpat Rai", "Gopal Krishna Gokhale", "Subhas Chandra Bose"], 0,
     PYQ + "Lal–Bal–Pal were the leading extremists."),
    ("The split between the Moderates and the Extremists in the Congress took place at the:",
     ["Surat session, 1907", "Lucknow session, 1916", "Lahore session, 1929", "Belgaum session, 1924"], 0,
     "They reunited at Lucknow in 1916."),
    ("The All-India Muslim League was founded in 1906 at:",
     ["Dacca", "Lahore", "Aligarh", "Lucknow"], 0,
     PYQ + "The Morley–Minto Reforms (1909) then introduced separate electorates for Muslims."),
    ("The Home Rule Leagues of 1916 were started by:",
     ["Bal Gangadhar Tilak and Annie Besant", "Gandhi and Nehru", "Gokhale and Ranade", "Jinnah and Iqbal"], 0,
     "Tilak's league began in April and Besant's in September 1916."),
    ("Match the reformer with the organisation:\na. Raja Ram Mohan Roy  b. Dayananda Saraswati  c. Swami Vivekananda  d. Jyotiba Phule\n1. Satyashodhak Samaj  2. Ramakrishna Mission  3. Arya Samaj  4. Brahmo Samaj",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Reformer–organisation matching is very common."),
]

GANDHIAN = [
    # --- real previous-year questions ---
    ("Consider the following:\n(a) Mysore Chalo Movement  (b) Vidurashwatha Tragedy\n(c) Isuru Tragedy  (d) Shivapura Flag Satyagraha\nIdentify the correct chronology of the above events:",
     ["b, d, c, a", "d, c, b, a", "d, b, c, a", "b, d, a, c"], 2,
     "Shivapura Flag Satyagraha (April 1938) → Vidurashwatha firing (25 April 1938) → Isur (1942) → Mysore Chalo (1947)." + KEY,
     "GTTC 2024 Asst Gr-II GK · Q12"),
    ("Consider the following events:\n(a) Establishment of Swaraj Party\n(b) Jallianwala Bagh Massacre\n(c) Congress-Muslim League Pact\n(d) Chauri-Chaura incident\nChoose the correct chronological order.",
     ["(b), (c), (d), (a)", "(b), (c), (a), (d)", "(c), (b), (a), (d)", "(c), (b), (d), (a)"], 3,
     "Lucknow Pact 1916 → Jallianwala Bagh 1919 → Chauri Chaura 1922 → Swaraj Party 1923." + NOTE,
     "KEA 2026 GK-1 (HK, 22 Feb 2026) · Q43"),
    ("Arrange the following in their chronological sequence and choose the correct option.\n(A) Cripps Mission  (B) Montague Chelmsford Report\n(C) Simon Commission  (D) Morley-Minto Reforms",
     ["B, C, A, D", "D, B, C, A", "C, A, B, D", "A, D, C, B"], 1,
     "Morley–Minto 1909 → Montagu–Chelmsford Report 1918 → Simon Commission 1927–28 → Cripps Mission 1942." + NOTE,
     "Legislative Council 2024 Data Entry P1 · Q55"),
    ("Which day was declared as 'Direct Action Day' by the Muslim League?",
     ["16 August 1943", "16 August 1946", "16 August 1945", "16 August 1944"], 1,
     "The call led to large-scale riots in Calcutta." + NOTE,
     "Legislative Council 2024 Data Entry P1 · Q68"),
    ("Identify the incorrect pair from the following:",
     ["Gandhi-Irwin Pact - 1931", "Nehru Report - 1928", "August Offer - 1939", "Wavell Plan - 1945"], 2,
     "The August Offer was made by Lord Linlithgow in 1940." + NOTE,
     "VAO 2024 Paper-1 · Q41"),
    ("Who declared in the British Parliament in February, 1947 that, \"British would quit India very soon\"?",
     ["Sir MacDonald", "William Gladstone", "Clement Attlee", "Pitt the Elder"], 2,
     "On 20 February 1947 Prime Minister Attlee announced British withdrawal by June 1948." + NOTE,
     "KEA 2025 GK (HK, 21 Dec 2025) · Q91"),
    ("What is the reason for the breakout of Khilafat Movement in India?",
     ["Hindu-Muslim unity", "Awakening religious consciences among Muslims", "The nationalist trend among the Muslims took the form of the Khilafat agitation", "It was a dissent shown by the Indian Muslims towards British on Turkey"], 3,
     "Indian Muslims protested against Britain's harsh treatment of Turkey and the Caliph after the First World War." + NOTE,
     "UPSC coaching entrance 2025 GS-1 · Q11"),
    ("Write the following events in chronological order:\na. August Offer\nb. Poona Pact\nc. Third Round Table Conference\nd. Communal award.",
     ["d, c, b, a", "d, b, c, a", "a, b, c, d", "c, b, a, d"], 1,
     "Communal Award (August 1932) → Poona Pact (September 1932) → Third RTC (November–December 1932) → August Offer (1940)." + NOTE,
     "UPSC coaching entrance 2025 GS-1 · Q21"),
    ("The last Governor General of India is",
     ["Lord Mountbatten", "C. Rajagopalachari", "Dr. Rajendra Prasad", "Lord Wavell"], 1,
     "Rajagopalachari succeeded Mountbatten in June 1948 and held office until India became a republic in 1950." + NOTE,
     "PSI 2023 General Paper · Q20"),
    # --- new questions ---
    ("Gandhiji's first satyagraha in India (1917), for indigo cultivators, was at:",
     ["Champaran", "Kheda", "Ahmedabad", "Bardoli"], 0,
     PYQ + "Kheda (peasants) and Ahmedabad (mill workers) followed in 1918."),
    ("The Jallianwala Bagh massacre at Amritsar on 13 April 1919 was ordered by:",
     ["General Reginald Dyer", "Lord Chelmsford", "Michael O'Dwyer", "Lord Irwin"], 0,
     PYQ + "People had gathered to protest against the Rowlatt Act and the arrest of local leaders."),
    ("Gandhiji withdrew the Non-Cooperation Movement in February 1922 because of:",
     ["The violence at Chauri Chaura", "The Simon Commission", "The Poona Pact", "The Cripps Mission"], 0,
     PYQ + "A mob set fire to a police station, killing 22 policemen."),
    ("The Purna Swaraj resolution was adopted at the Lahore session of 1929, and Independence Day was first celebrated on:",
     ["26 January 1930", "15 August 1930", "26 November 1929", "2 October 1930"], 0,
     PYQ + "This is why the Constitution came into force on 26 January 1950."),
    ("The Dandi March of 1930 began from Sabarmati Ashram on:",
     ["12 March 1930", "6 April 1930", "8 August 1942", "26 January 1930"], 0,
     PYQ + "Gandhi broke the salt law at Dandi on 6 April 1930, starting the Civil Disobedience Movement."),
    ("The Quit India Movement was launched with the slogan 'Do or Die' on:",
     ["8 August 1942, at Gowalia Tank, Bombay", "26 January 1930", "15 August 1947", "12 March 1930"], 0,
     PYQ + "Usha Mehta ran the underground Congress Radio during the movement."),
    ("'Give me blood, and I will give you freedom' was the call of:",
     ["Subhas Chandra Bose", "Bhagat Singh", "Chandrashekhar Azad", "Lala Lajpat Rai"], 0,
     PYQ + "He formed the Provisional Government of Azad Hind in 1943 and led the INA."),
    ("Bhagat Singh and Batukeshwar Dutt threw bombs in the Central Legislative Assembly in:",
     ["1929", "1919", "1942", "1905"], 0,
     "Bhagat Singh, Rajguru and Sukhdev were hanged on 23 March 1931."),
    ("Lala Lajpat Rai died after a police lathi-charge during protests against the:",
     ["Simon Commission (1928)", "Rowlatt Act (1919)", "Partition of Bengal (1905)", "Cripps Mission (1942)"], 0,
     "The commission had no Indian member, hence 'Simon, Go Back'."),
    ("The only session of the Indian National Congress presided over by Mahatma Gandhi was held in 1924 at:",
     ["Belgaum (Belagavi)", "Lahore", "Haripura", "Calcutta"], 0,
     PYQ + "The session was held at Tilakwadi, Belagavi."),
    ("The plan of 3 June 1947 for the partition of India is known as the:",
     ["Mountbatten Plan", "Cripps Plan", "Wavell Plan", "Cabinet Mission Plan"], 0,
     PYQ + "The Indian Independence Act was passed in July 1947."),
]

TOPICS = {
    "Indian History and Culture – Modern": [("1 · British Expansion, Administration and the Revolt of 1857", BRITISH),
                                            ("2 · Social Reform and the Early National Movement", REFORM_EARLY),
                                            ("3 · The Gandhian Era and Independence", GANDHIAN)],
}
