"""Paper 1 · General Knowledge · P1-GK-03 Basic Science – Concepts and Scientific Phenomena (3 sub-topics × 20).
School level (NCERT / KTBS Classes 6–10), with some reasoning and numerical questions."""
from packlib import AR, I_II

PHYSICS = [
    ("The SI units of force, work and power are respectively:",
     ["newton, joule, watt", "joule, newton, watt", "watt, joule, newton", "newton, watt, joule"], 0, "1 W = 1 J/s; 1 J = 1 N·m."),
    ("The speed of light in vacuum is about:",
     ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "340 m/s", "3 × 10¹⁰ m/s"], 0, "Sound in air travels only about 340 m/s."),
    ("Sound travels fastest in:",
     ["Solids such as steel", "Air", "Vacuum", "Water vapour"], 0, "Sound needs a medium and travels fastest in solids; it cannot travel through a vacuum."),
    ("The blue colour of the clear sky is due to:",
     ["Scattering of sunlight by air molecules", "Reflection from the oceans", "Absorption of red light by clouds", "Dispersion by raindrops"], 0, "Shorter (blue) wavelengths are scattered much more than red (Rayleigh scattering)."),
    ("A rainbow is formed mainly because of:",
     ["Dispersion, refraction and internal reflection of sunlight in raindrops", "Scattering by dust only", "Reflection from clouds only", "Diffraction by trees"], 0, "Each colour bends by a different amount."),
    ("Stars twinkle but planets usually do not, because of:",
     ["Atmospheric refraction of the light from point-like stars", "Stars switching on and off", "Reflection from the Moon", "The rotation of the stars"], 0, "Planets appear as tiny discs, so the fluctuations average out."),
    ("A mirage seen on a hot road is caused by:",
     ["Refraction and total internal reflection of light in layers of hot air", "Water on the road", "Scattering of blue light", "Magnetism"], 0, "Light from the sky bends upward and appears to come from the road."),
    ("Passengers in a bus fall forward when the bus stops suddenly. This is explained by:",
     ["Newton's first law (inertia of motion)", "Newton's third law", "The law of gravitation", "Archimedes' principle"], 0, "The body tends to continue moving."),
    ("The recoil of a gun and the motion of a rocket are explained by:",
     ["Newton's third law of motion", "Newton's first law", "Ohm's law", "Pascal's law"], 0, "Every action has an equal and opposite reaction."),
    ("A car starts from rest and accelerates uniformly at 2 m/s² for 5 s. Its final velocity is:",
     ["10 m/s", "2.5 m/s", "7 m/s", "25 m/s"], 0, "v = u + at = 0 + 2 × 5."),
    ("A 12 V battery is connected across a 4 Ω resistor. The current is:",
     ["3 A", "48 A", "0.33 A", "16 A"], 0, "Ohm's law: I = V/R."),
    ("An electric iron draws 5 A from a 220 V supply. Its power is:",
     ["1100 W", "44 W", "225 W", "1.1 W"], 0, "P = V × I."),
    ("One 'unit' of electricity on an electricity bill is:",
     ["1 kilowatt-hour = 3.6 × 10⁶ J", "1 joule", "1 watt", "1 kilowatt"], 0, "1 kW × 3600 s = 3.6 MJ."),
    ("An object's mass is 60 kg on Earth. On the Moon, its mass and weight are:",
     ["Mass 60 kg; weight about one-sixth of its weight on Earth", "Mass 10 kg; weight unchanged", "Both one-sixth", "Both unchanged"], 0, "Mass is constant; weight depends on the gravity of the Moon."),
    ("Myopia (short-sightedness) is corrected with a:",
     ["Concave lens", "Convex lens", "Plane mirror", "Prism"], 0, "Hypermetropia (long-sightedness) is corrected with a convex lens."),
    ("A sharp knife cuts more easily than a blunt one because:",
     ["The same force acts on a smaller area, producing greater pressure", "It has more mass", "It reduces friction to zero", "It has more energy stored"], 0, "Pressure = force / area."),
    ("Food cooks faster in a pressure cooker because:",
     ["The higher pressure raises the boiling point of water", "The pressure lowers the boiling point", "Steam is colder than water", "The cooker is made of metal"], 0, "At high altitudes the lower pressure makes water boil below 100 °C."),
    ("Match the phenomenon with the principle behind it:\na. Floating of a ship  b. Working of a hydraulic lift  c. Blue sky  d. Electric motor\n1. Force on a current-carrying conductor in a magnetic field  2. Scattering of light  3. Pascal's law  4. Archimedes' principle",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each is a common school-level application."),
    ("Assertion (A): Sound cannot be heard on the Moon without radio.\nReason (R): Sound needs a material medium to travel, and the Moon has practically no atmosphere.",
     AR, 0, "Astronauts use radio waves, which do not need a medium."),
    ("Assertion (A): A convex lens is used to correct myopia.\nReason (R): A convex lens is a converging lens.",
     AR, 3, "R is true, but myopia is corrected with a diverging (concave) lens, so A is false."),
]

CHEMISTRY = [
    ("The chemical symbols of iron, gold and lead are respectively:",
     ["Fe, Au, Pb", "Ir, Ag, Pd", "Fe, Ag, Pb", "I, Au, Le"], 0, "They come from Latin names: ferrum, aurum, plumbum."),
    ("The pH of pure water at 25 °C is:",
     ["7", "0", "14", "1"], 0, "Acids have pH below 7 and bases above 7."),
    ("The chemical name of baking soda is:",
     ["Sodium hydrogen carbonate (NaHCO₃)", "Sodium carbonate", "Calcium carbonate", "Sodium chloride"], 0, "Washing soda is sodium carbonate decahydrate, Na₂CO₃·10H₂O."),
    ("Match the common name with the compound:\na. Washing soda  b. Bleaching powder  c. Plaster of Paris  d. Common salt\n1. NaCl  2. CaSO₄·½H₂O  3. CaOCl₂  4. Na₂CO₃·10H₂O",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These are standard Class 10 compounds."),
    ("The gas present in the largest proportion in the Earth's atmosphere is:",
     ["Nitrogen (about 78%)", "Oxygen (about 78%)", "Carbon dioxide", "Argon"], 0, "Oxygen is about 21%."),
    ("Rusting of iron requires:",
     ["Both oxygen (air) and water (moisture)", "Only dry air", "Only water without air", "Only sunlight"], 0, "Coating iron with zinc (galvanisation) or paint prevents rusting."),
    ("The hardest natural substance, which is an allotrope of carbon, is:",
     ["Diamond", "Graphite", "Coal", "Quartz"], 0, "Graphite, another allotrope, is soft and conducts electricity."),
    ("Which of the following is a chemical change?",
     ["Burning of paper", "Melting of ice", "Dissolving sugar in water", "Breaking a glass"], 0, "Burning forms new substances; the others change only the physical state or form."),
    ("When an acid reacts with a base, the products are:",
     ["Salt and water", "Only hydrogen gas", "Only oxygen", "Acid and oxygen"], 0, "This reaction is called neutralisation."),
    ("Milk of magnesia is taken to relieve acidity because it is:",
     ["A mild base (magnesium hydroxide) that neutralises excess stomach acid", "A strong acid", "A salt that increases acid", "A sugar"], 0, "Such medicines are called antacids."),
    ("Laughing gas, used as a mild anaesthetic, is:",
     ["Nitrous oxide (N₂O)", "Carbon monoxide", "Nitrogen dioxide", "Methane"], 0, "It was one of the first anaesthetics."),
    ("Helium is used to fill weather balloons because it is:",
     ["Very light and chemically inert (non-flammable)", "Heavier than air", "Highly flammable", "Poisonous"], 0, "Hydrogen is lighter but highly flammable."),
    ("An element has atomic number 11. Its electronic configuration and valency are:",
     ["2, 8, 1 and valency 1", "2, 9 and valency 9", "2, 8, 1 and valency 7", "8, 2, 1 and valency 2"], 0, "It is sodium; it loses its one outer electron."),
    ("Isotopes of an element have:",
     ["The same atomic number but different mass numbers", "Different atomic numbers but the same mass number", "Different numbers of protons", "Different chemical symbols"], 0, "They differ in the number of neutrons, e.g. carbon-12 and carbon-14."),
    ("Brass is an alloy of:",
     ["Copper and zinc", "Copper and tin", "Iron and carbon", "Lead and tin"], 0, "Bronze is copper and tin; steel is iron with carbon."),
    ("LPG used as cooking gas is mainly:",
     ["Butane (with propane)", "Methane", "Hydrogen", "Ethylene"], 0, "CNG is mainly methane."),
    ("The ozone layer protects life on Earth by:",
     ["Absorbing most of the harmful ultraviolet radiation from the Sun", "Producing oxygen for breathing", "Causing rain", "Blocking visible light"], 0, "CFCs released by some sprays and refrigerants damage it."),
    ("Consider the statements:\nI. Lemon juice is acidic.\nII. Soap solution is basic.\nWhich is/are correct?",
     I_II, 2, "Lemon juice contains citric acid; soap solutions are alkaline."),
    ("Assertion (A): Iron articles are galvanised to prevent rusting.\nReason (R): A zinc coating keeps air and moisture away from the iron and corrodes in preference to it.",
     AR, 0, "Zinc protects iron both as a barrier and as a sacrificial metal."),
    ("Assertion (A): Graphite is used in pencils and as a lubricant.\nReason (R): Graphite is the hardest natural substance.",
     AR, 2, "A is true because graphite is soft and slippery; R is false – diamond is the hardest."),
]

BIOLOGY = [
    ("The cell organelle known as the 'powerhouse of the cell' is the:",
     ["Mitochondrion", "Ribosome", "Nucleus", "Golgi apparatus"], 0, "It releases energy from food by cellular respiration."),
    ("Which structures are present in plant cells but NOT in animal cells?",
     ["Cell wall and chloroplasts", "Nucleus and mitochondria", "Cell membrane and cytoplasm", "Ribosomes"], 0, "Plant cells also usually have a large central vacuole."),
    ("The raw materials of photosynthesis are:",
     ["Carbon dioxide and water, in the presence of sunlight and chlorophyll", "Oxygen and glucose", "Nitrogen and water", "Carbon dioxide and oxygen"], 0, "Products: glucose and oxygen."),
    ("The universal donor and universal recipient blood groups are respectively:",
     ["O negative and AB positive", "AB positive and O negative", "A and B", "B and O"], 0, "O− red cells have no A, B or Rh antigens; AB+ plasma has no anti-A or anti-B antibodies."),
    ("Red blood cells carry oxygen with the help of:",
     ["Haemoglobin, which contains iron", "Insulin", "Chlorophyll", "Antibodies"], 0, "Iron deficiency causes anaemia."),
    ("Match the blood component with its function:\na. Red blood cells  b. White blood cells  c. Platelets  d. Plasma\n1. Liquid part that carries dissolved substances  2. Help blood to clot  3. Fight infection  4. Carry oxygen",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These are the four main components of blood."),
    ("The largest organ, the largest gland and the smallest bone of the human body are respectively:",
     ["Skin, liver and stapes (in the ear)", "Liver, skin and femur", "Brain, pancreas and stapes", "Skin, pancreas and femur"], 0, "The femur (thigh bone) is the longest bone."),
    ("An adult human skeleton has how many bones?",
     ["206", "300", "106", "212"], 0, "A newborn has about 300, many of which fuse."),
    ("Match the vitamin with the deficiency disease:\na. Vitamin A  b. Vitamin B₁  c. Vitamin C  d. Vitamin D\n1. Rickets  2. Scurvy  3. Beriberi  4. Night blindness",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Vitamin K is needed for blood clotting."),
    ("Insulin, which controls blood sugar, is secreted by the:",
     ["Pancreas", "Liver", "Thyroid", "Kidney"], 0, "Too little insulin action causes diabetes mellitus."),
    ("The normal human body temperature is about:",
     ["37 °C (98.6 °F)", "40 °C", "32 °C", "100 °F"], 0, "It varies slightly during the day."),
    ("The human heart has:",
     ["Four chambers – two atria and two ventricles", "Two chambers", "Three chambers", "Six chambers"], 0, "Normal adult blood pressure is about 120/80 mm Hg."),
    ("The structural and functional unit of the kidney is the:",
     ["Nephron", "Neuron", "Alveolus", "Villus"], 0, "Each kidney has about a million nephrons."),
    ("Malaria is caused by ______ and spread by the bite of the female ______ mosquito.",
     ["Plasmodium (a protozoan); Anopheles", "a virus; Aedes", "a bacterium; Culex", "a fungus; Anopheles"], 0, "Dengue is caused by a virus spread by Aedes mosquitoes."),
    ("Which disease is caused by a bacterium?",
     ["Tuberculosis", "AIDS", "Dengue", "Measles"], 0, "AIDS, dengue and measles are caused by viruses."),
    ("A normal human body cell has how many chromosomes?",
     ["46 (23 pairs)", "23", "44", "48"], 0, "Sex cells (gametes) have 23."),
    ("The sex of a human baby is determined by:",
     ["The father – an X or a Y chromosome from the sperm", "The mother – her egg carries a Y chromosome", "The mother's diet", "The season of birth"], 0, "XX gives a girl; XY gives a boy."),
    ("Digestion of starch begins in the mouth by the enzyme:",
     ["Salivary amylase (ptyalin)", "Pepsin", "Lipase", "Trypsin"], 0, "Pepsin digests proteins in the stomach."),
    ("Assertion (A): Green plants are called producers.\nReason (R): Green plants make their own food by photosynthesis.",
     AR, 0, "All other organisms depend directly or indirectly on this food."),
    ("Assertion (A): Antibiotics cure viral diseases such as the common cold.\nReason (R): Antibiotics act against bacteria.",
     AR, 3, "Because antibiotics act on bacteria, they do not cure viral infections; R shows why A is false."),
]

TOPICS = {
    "Basic Science – Concepts and Scientific Phenomena": [("1 · Physics: Concepts and Phenomena", PHYSICS),
                                                          ("2 · Chemistry: Concepts and Phenomena", CHEMISTRY),
                                                          ("3 · Biology: Concepts and Phenomena", BIOLOGY)],
}
