"""Paper 1 · General Knowledge · P1-GK-04 Health and Hygiene (2 sub-topics × 20).
References: NCERT Science (Classes 6–10) and Biology (Class 12, Ch. 'Human Health and Disease'); ICMR–NIN Dietary Guidelines; Ministry of Health & Family Welfare / PIB.
Explanations starting "PYQ pattern" follow questions that recur in KPSC / KEA / SSC general-knowledge papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "

NUTRITION = [
    ("Deficiency of vitamin C causes:",
     ["Scurvy", "Rickets", "Beriberi", "Night blindness"], 0, PYQ + "Bleeding gums and slow wound healing are typical signs."),
    ("Rickets in children is caused by deficiency of:",
     ["Vitamin D", "Vitamin C", "Vitamin B1", "Vitamin K"], 0, PYQ + "Vitamin D is needed to absorb calcium; bones become soft and bent."),
    ("Night blindness is caused by deficiency of:",
     ["Vitamin A", "Vitamin D", "Vitamin E", "Vitamin B12"], 0, PYQ + "Severe deficiency leads to xerophthalmia."),
    ("Beriberi is caused by deficiency of:",
     ["Vitamin B1 (thiamine)", "Vitamin B3 (niacin)", "Vitamin C", "Vitamin A"], 0, PYQ + "It affects the nerves and heart; it was common with polished rice diets."),
    ("Pellagra, with the 'three Ds' (dermatitis, diarrhoea, dementia), is caused by deficiency of:",
     ["Vitamin B3 (niacin)", "Vitamin B1", "Vitamin D", "Vitamin K"], 0, "It is associated with maize-based diets."),
    ("Which vitamin is essential for blood clotting?",
     ["Vitamin K", "Vitamin A", "Vitamin C", "Vitamin B1"], 0, PYQ + "Newborns are often given a vitamin K injection."),
    ("Goitre is caused by deficiency of:",
     ["Iodine", "Iron", "Calcium", "Sodium"], 0, PYQ + "Iodine is needed to make thyroid hormones; iodised salt prevents goitre."),
    ("Anaemia is most commonly caused by deficiency of:",
     ["Iron", "Iodine", "Vitamin K", "Fluoride"], 0, "Iron is needed to make haemoglobin."),
    ("Kwashiorkor is a deficiency disease caused mainly by lack of:",
     ["Protein", "Vitamin C", "Iodine", "Water"], 0, "Marasmus results from lack of both protein and energy (calories)."),
    ("The fat-soluble vitamins are:",
     ["A, D, E and K", "B and C", "A, B, C and D", "C, D, E and K"], 0, PYQ + "B-complex and C are water-soluble and are not stored in the body for long."),
    ("Which vitamin contains the metal cobalt?",
     ["Vitamin B12 (cobalamin)", "Vitamin C", "Vitamin D", "Vitamin A"], 0, "Deficiency causes pernicious anaemia."),
    ("The skin produces vitamin D when exposed to:",
     ["Sunlight", "Cold water", "Noise", "Dust"], 0, "Ultraviolet B rays convert a cholesterol derivative in the skin."),
    ("Amla (Indian gooseberry) is a very rich source of:",
     ["Vitamin C", "Vitamin D", "Vitamin B12", "Vitamin K"], 0, "Citrus fruits and guava are also good sources."),
    ("One gram of fat provides about how much energy?",
     ["9 kcal", "4 kcal", "7 kcal", "1 kcal"], 0, "Carbohydrates and proteins give about 4 kcal per gram."),
    ("Excess fluoride in drinking water causes:",
     ["Fluorosis (mottled teeth and bone problems)", "Goitre", "Scurvy", "Night blindness"], 0, "A little fluoride prevents tooth decay, but too much is harmful."),
    ("Match the vitamin with the disease caused by its deficiency:\na. Vitamin A  b. Vitamin B1  c. Vitamin C  d. Vitamin D\n1. Rickets  2. Scurvy  3. Beriberi  4. Night blindness",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "The most frequently asked vitamin set."),
    ("Consider the statements:\nI. Vitamin C is fat-soluble.\nII. Vitamin C is easily destroyed by heat during cooking.\nWhich is/are correct?",
     I_II, 1, "Vitamin C is water-soluble and heat-sensitive."),
    ("Consider the statements:\nI. A balanced diet contains all nutrients in the right proportion.\nII. Roughage (dietary fibre) helps prevent constipation.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Iodised salt helps prevent goitre.\nReason (R): Iodine is needed to make thyroid hormones.",
     AR, 0, "Without iodine the thyroid gland enlarges."),
    ("Assertion (A): Vitamin D deficiency can occur even with a good diet if a person gets no sunlight.\nReason (R): Vitamin D is water-soluble.",
     AR, 2, "A is true; R is false – vitamin D is fat-soluble."),
]

DISEASES = [
    ("Malaria is caused by:",
     ["Plasmodium, a protozoan, spread by the female Anopheles mosquito", "A virus spread by Aedes mosquitoes", "A bacterium spread through water", "A fungus spread through air"], 0, PYQ + "Plasmodium vivax and P. falciparum are the common species in India."),
    ("Dengue is caused by a virus and spread mainly by:",
     ["Aedes aegypti mosquitoes", "Anopheles mosquitoes", "Houseflies", "Rats"], 0, PYQ + "Aedes breeds in clean stored water and bites in the daytime."),
    ("The BCG vaccine gives protection against:",
     ["Tuberculosis", "Polio", "Measles", "Cholera"], 0, PYQ + "TB is caused by the bacterium Mycobacterium tuberculosis."),
    ("The first vaccine (against smallpox) was developed by:",
     ["Edward Jenner", "Louis Pasteur", "Alexander Fleming", "Robert Koch"], 0, PYQ + "Jenner used cowpox material in 1796."),
    ("The rabies vaccine was developed by:",
     ["Louis Pasteur", "Edward Jenner", "Jonas Salk", "Ronald Ross"], 0, "Pasteur first used it on a human in 1885."),
    ("Penicillin, the first widely used antibiotic, was discovered by:",
     ["Alexander Fleming (1928)", "Louis Pasteur (1885)", "Robert Koch (1882)", "Edward Jenner (1796)"], 0, PYQ + "It came from the mould Penicillium notatum."),
    ("The injectable polio vaccine (IPV) was developed by Jonas Salk; the oral polio vaccine (OPV) was developed by:",
     ["Albert Sabin", "Edward Jenner", "Louis Pasteur", "Robert Koch"], 0, "OPV is given as drops in the Pulse Polio programme."),
    ("India (with the WHO South-East Asia Region) was certified polio-free in:",
     ["2014", "2004", "2011", "2019"], 0, PYQ + "The certificate was issued on 27 March 2014; India's last wild polio case was in January 2011."),
    ("Cholera, a water-borne disease causing severe watery diarrhoea, is caused by:",
     ["Vibrio cholerae, a bacterium", "A virus", "Plasmodium", "A fungus"], 0, "Oral rehydration solution (ORS) saves lives by replacing lost water and salts."),
    ("Typhoid is caused by:",
     ["Salmonella typhi, a bacterium", "Vibrio cholerae", "A virus", "Plasmodium"], 0, "It spreads through contaminated food and water."),
    ("AIDS is caused by HIV, which mainly destroys the body's:",
     ["Helper T-lymphocytes (CD4 cells)", "Red blood cells", "Platelets", "Nerve cells"], 0, "World AIDS Day is observed on 1 December."),
    ("Ringworm and athlete's foot are caused by:",
     ["Fungi", "Viruses", "Protozoa", "Worms"], 0, "Despite its name, ringworm is not caused by a worm."),
    ("Assertion (A): Leprosy is an incurable disease.\nReason (R): Leprosy is caused by the bacterium Mycobacterium leprae.",
     AR, 3, "Leprosy is curable with multi-drug therapy (MDT); A is false, R is true."),
    ("World No Tobacco Day is observed every year on:",
     ["31 May", "7 April", "1 December", "5 June"], 0, PYQ + "It is promoted by the WHO; 7 April is World Health Day and 5 June is World Environment Day."),
    ("The Swachh Bharat Mission was launched on:",
     ["2 October 2014", "15 August 2014", "26 January 2015", "2 October 2019"], 0, PYQ + "It was launched on Gandhi Jayanti to make India open-defecation free."),
    ("Mission Indradhanush, launched by the Government of India in December 2014, aims to:",
     ["Increase full immunisation coverage of children and pregnant women", "Build rural roads", "Provide free electricity", "Promote sports"], 0, "It targets children who missed routine vaccinations."),
    ("Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana (2018) provides health cover of up to:",
     ["₹5 lakh per family per year", "₹1 lakh per person per year", "₹50,000 per family", "₹10 lakh per person"], 0, PYQ + "It covers secondary and tertiary hospital care."),
    ("Match the disease with the type of pathogen:\na. Tuberculosis  b. Polio  c. Malaria  d. Ringworm\n1. Fungus  2. Protozoan  3. Virus  4. Bacterium",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Knowing the pathogen type is a common question."),
    ("Consider the statements:\nI. Antibiotics are effective against viral infections such as the common cold.\nII. Washing hands with soap reduces diarrhoeal diseases.\nWhich is/are correct?",
     I_II, 1, "Antibiotics act on bacteria, not viruses."),
    ("Assertion (A): Removing stagnant water around houses helps control malaria and dengue.\nReason (R): Mosquitoes lay their eggs in standing water.",
     AR, 0, "Breaking the breeding cycle reduces mosquito numbers."),
]

TOPICS = {
    "Health and Hygiene": [("1 · Nutrition, Vitamins and Deficiency Diseases", NUTRITION),
                           ("2 · Diseases, Immunisation and Public Health", DISEASES)],
}
