"""Paper 1 · General Knowledge · P1-GK-05 Karnataka History, Culture and Art (3 sub-topics × 20).
References: Suryanath U. Kamath, A Concise History of Karnataka; KTBS Social Science textbooks (Classes 6–10); UNESCO World Heritage List;
Karnataka Gazetteer. Explanations starting "PYQ pattern" follow questions that recur in KPSC / KEA / SSC papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "

EARLY = [
    ("The Kadamba dynasty, the first native ruling dynasty of Karnataka, was founded by:",
     ["Mayurasharma", "Pulakeshin I", "Dantidurga", "Vishnuvardhana"], 0, PYQ + "He founded it in about 345 CE after a quarrel at the Pallava capital Kanchi."),
    ("The capital of the Kadambas was:",
     ["Banavasi", "Talakad", "Badami", "Manyakheta"], 0, PYQ + "Banavasi is in present-day Uttara Kannada district."),
    ("The Halmidi inscription (c. 450 CE), the earliest known inscription in Kannada, belongs to the period of the:",
     ["Kadambas", "Hoysalas", "Rashtrakutas", "Vijayanagara rulers"], 0, PYQ + "It was found in Halmidi village, Hassan district, and is attributed to Kakusthavarma's time."),
    ("The Ashokan minor rock edict at Maski (Raichur district) is famous because it:",
     ["Was the first edict found to mention Ashoka by name", "Is written in Kannada", "Was issued by the Kadambas", "Records the Kalinga war in detail"], 0, PYQ + "Other edicts call him 'Devanampiya Piyadasi'."),
    ("The later capital of the Western Gangas was:",
     ["Talakad", "Banavasi", "Kalyana", "Hampi"], 0, "Their early capital was Kolar (Kuvalala)."),
    ("The monolithic statue of Gommateshwara (Bahubali) at Shravanabelagola was commissioned in about 983 CE by:",
     ["Chavundaraya, a minister of the Western Gangas", "Pulakeshin II", "Krishnadevaraya", "Amoghavarsha I"], 0, PYQ + "It is about 57 feet (17 m) tall."),
    ("The Badami Chalukya king who defeated Harshavardhana on the banks of the Narmada was:",
     ["Pulakeshin II", "Pulakeshin I", "Vikramaditya II", "Kirtivarman I"], 0, PYQ + "This is recorded in the Aihole inscription."),
    ("The Aihole inscription (634 CE), praising Pulakeshin II, was composed by the court poet:",
     ["Ravikirti", "Pampa", "Ranna", "Bilhana"], 0, PYQ + "It is written in Sanskrit."),
    ("Which place is called the 'cradle of Indian temple architecture'?",
     ["Aihole", "Hampi", "Belur", "Srirangapatna"], 0, PYQ + "It has over 100 early Chalukyan temples."),
    ("The Virupaksha temple at Pattadakal was built by Queen Lokamahadevi to commemorate:",
     ["Vikramaditya II's victory over the Pallavas", "The founding of Vijayanagara", "Pulakeshin II's victory over Harsha", "The Battle of Talikota"], 0, "Pattadakal became a UNESCO World Heritage Site in 1987."),
    ("The Rashtrakuta dynasty was founded by:",
     ["Dantidurga", "Amoghavarsha I", "Krishna I", "Tailapa II"], 0, PYQ + "He overthrew the Badami Chalukyas in the mid-8th century."),
    ("The Rashtrakuta capital Manyakheta (Malkhed, Kalaburagi district) was established by:",
     ["Amoghavarsha I", "Dantidurga", "Govinda III", "Mayurasharma"], 0, "He ruled for more than 60 years."),
    ("The rock-cut Kailasa temple at Ellora was built by the Rashtrakuta king:",
     ["Krishna I", "Amoghavarsha I", "Dantidurga", "Indra III"], 0, PYQ + "It is carved from a single rock, from the top down."),
    ("'Kavirajamarga', the earliest available Kannada work on poetics, is associated with the court of:",
     ["Amoghavarsha I (attributed to the poet Srivijaya)", "Krishnadevaraya", "Vishnuvardhana", "Tipu Sultan"], 0, PYQ + "It describes the Kannada land as stretching from the Kaveri to the Godavari."),
    ("The 'three gems' (Ratnatraya) of early Kannada literature are:",
     ["Pampa, Ponna and Ranna", "Basavanna, Allama and Akka Mahadevi", "Purandara Dasa, Kanakadasa and Vyasaraya", "Kuvempu, Bendre and Karanth"], 0, PYQ + "All three wrote in the 10th century."),
    ("'Mitakshara', the famous commentary on Hindu law, was written by Vijnaneshwara at the court of:",
     ["Vikramaditya VI of the Kalyani Chalukyas", "Pulakeshin II", "Amoghavarsha I", "Krishnadevaraya"], 0, "Bilhana wrote 'Vikramankadeva Charita' about the same king."),
    ("Match the dynasty with its capital:\na. Kadambas  b. Western Gangas  c. Badami Chalukyas  d. Rashtrakutas\n1. Manyakheta  2. Badami (Vatapi)  3. Talakad  4. Banavasi",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Dynasty–capital matching is a favourite question."),
    ("Consider the statements:\nI. The Halmidi inscription is in Kannada.\nII. The Aihole inscription was composed by Ranna.\nWhich is/are correct?",
     I_II, 0, "The Aihole inscription was composed by Ravikirti."),
    ("Assertion (A): Aihole is called the cradle of Indian temple architecture.\nReason (R): It contains many early experimental temples of the Chalukyas.",
     AR, 0, "Styles developed there were refined at Badami and Pattadakal."),
    ("Assertion (A): The Kailasa temple at Ellora was built by the Hoysalas.\nReason (R): The Kailasa temple is carved out of a single rock.",
     AR, 3, "It was built by the Rashtrakuta king Krishna I; A is false, R is true."),
]

LATER = [
    ("The Chennakeshava temple at Belur was built in 1117 by the Hoysala king:",
     ["Vishnuvardhana", "Veera Ballala II", "Narasimha III", "Vinayaditya"], 0, PYQ + "It commemorates his victory over the Cholas at Talakad."),
    ("The Hoysala king Vishnuvardhana (Bittideva) is said to have become a Vaishnava under the influence of:",
     ["Ramanujacharya", "Madhvacharya", "Basavanna", "Shankaracharya"], 0, "His queen Shantala Devi remained a Jain."),
    ("The Hoysala capital, where the Hoysaleshwara temple stands, was:",
     ["Dwarasamudra (Halebidu)", "Banavasi", "Kalyana", "Hampi"], 0, "It was sacked by Malik Kafur's forces in the early 14th century."),
    ("The Hoysala temples of Belur, Halebidu and Somanathapura were inscribed together on the UNESCO World Heritage List in:",
     ["2023", "1986", "1987", "2014"], 0, PYQ + "As the 'Sacred Ensembles of the Hoysalas'."),
    ("The Vijayanagara Empire was founded in 1336 by:",
     ["Harihara I and Bukka I of the Sangama dynasty", "Krishnadevaraya", "Alauddin Hasan Bahman Shah", "Pulakeshin II"], 0, PYQ + "The sage Vidyaranya is traditionally said to have guided them."),
    ("Krishnadevaraya of Vijayanagara wrote the Telugu work:",
     ["Amuktamalyada", "Kavirajamarga", "Gadayuddha", "Vikramankadeva Charita"], 0, PYQ + "Eight great poets, the Ashtadiggajas, adorned his court."),
    ("The Battle of Talikota (Rakkasa–Tangadi), which led to the fall of Vijayanagara, was fought in:",
     ["1565", "1526", "1336", "1799"], 0, PYQ + "The Deccan Sultanates defeated Aliya Rama Raya."),
    ("Assertion (A): The Vijayanagara Empire was founded by Krishnadevaraya.\nReason (R): Krishnadevaraya belonged to the Tuluva dynasty.",
     AR, 3, "It was founded in 1336 by Harihara I and Bukka I; A is false, R is true."),
    ("The Persian ambassador who visited Vijayanagara during the reign of Devaraya II was:",
     ["Abdur Razzaq", "Domingo Paes", "Nicolo Conti", "Fernao Nuniz"], 0, PYQ + "Paes and Nuniz were Portuguese; Conti was Italian."),
    ("The Bahmani Sultanate was founded in 1347 by:",
     ["Alauddin Hasan Bahman Shah", "Mahmud Gawan", "Yusuf Adil Shah", "Mohammed Adil Shah"], 0, "Its first capital was Gulbarga (Kalaburagi); later Bidar."),
    ("Consider the statements:\nI. The Bahmani capital was shifted from Gulbarga to Bidar.\nII. The madrasa at Bidar was built by the minister Mahmud Gawan.\nWhich is/are correct?",
     I_II, 2, "Both are correct; the madrasa was completed in 1472."),
    ("Gol Gumbaz at Vijayapura (Bijapur), famous for its whispering gallery, is the tomb of:",
     ["Mohammed Adil Shah", "Ibrahim Adil Shah II", "Yusuf Adil Shah", "Tipu Sultan"], 0, PYQ + "It has one of the largest domes in the world."),
    ("Shivappa Nayaka of Keladi is remembered for his land-revenue system called:",
     ["Shist", "Ryotwari", "Mahalwari", "Zabti"], 0, PYQ + "It was based on land survey and classification."),
    ("Rani Chennamma of Kittur led an armed revolt against the British East India Company in:",
     ["1824", "1857", "1799", "1831"], 0, PYQ + "Her general Sangolli Rayanna continued the struggle and was hanged in 1831."),
    ("Tipu Sultan died in 1799 at Srirangapatna during the:",
     ["Fourth Anglo-Mysore War", "Third Anglo-Mysore War", "Battle of Plassey", "First Anglo-Mysore War"], 0, PYQ + "The Wodeyars were then restored to the Mysore throne."),
    ("Mahatma Gandhi called Nalvadi Krishnaraja Wodeyar:",
     ["Rajarshi (saintly king)", "Karnataka Kulapurohita", "Tiger of Mysore", "Father of Carnatic music"], 0, PYQ + "His reign saw the KRS dam and the University of Mysore (1916)."),
    ("Aluru Venkata Rao, a leader of the Karnataka unification movement, is known as:",
     ["Karnataka Kulapurohita", "Rajarshi", "Karnataka Ratna", "Kannada Kanmani"], 0, PYQ + "He wrote 'Karnataka Gatha Vaibhava'."),
    ("The state of Mysore was renamed Karnataka on 1 November 1973, when the Chief Minister was:",
     ["D. Devaraj Urs", "S. Nijalingappa", "Kengal Hanumanthaiah", "Ramakrishna Hegde"], 0, PYQ + "The unified Mysore State itself was formed on 1 November 1956."),
    ("Match the ruler with the event:\na. Vishnuvardhana  b. Krishnadevaraya  c. Kittur Chennamma  d. Tipu Sultan\n1. Died at Srirangapatna, 1799  2. Revolt against the British, 1824  3. Author of Amuktamalyada  4. Built the Belur temple",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Four landmark rulers of Karnataka."),
    ("Assertion (A): The Battle of Talikota marked the decline of the Vijayanagara Empire.\nReason (R): After the battle, the capital Hampi was plundered and abandoned.",
     AR, 0, "The empire survived in a reduced form, but its capital was lost."),
]

CULTURE = [
    ("Basavanna, the 12th-century social reformer, served as a minister of:",
     ["Kalachuri king Bijjala at Kalyana", "Hoysala king Vishnuvardhana", "Krishnadevaraya", "Amoghavarsha I"], 0, PYQ + "He started the Anubhava Mantapa, a forum for spiritual and social discussion."),
    ("The Vachana poet Akka Mahadevi addressed her vachanas to:",
     ["Chennamallikarjuna", "Kudalasangama", "Guheshwara", "Purandara Vithala"], 0, "Kudalasangama was Basavanna's signature; Guheshwara was Allama Prabhu's."),
    ("Purandara Dasa is honoured as the:",
     ["Father (Pitamaha) of Carnatic music", "First Kannada poet", "Founder of Vijayanagara", "Author of Kavirajamarga"], 0, PYQ + "He systematised the teaching of Carnatic music."),
    ("'Kanakana Kindi' (Kanaka's window) is associated with the temple at:",
     ["Udupi", "Belur", "Hampi", "Sringeri"], 0, "Kanakadasa wrote 'Mohanatarangini' and 'Ramadhanya Charite'."),
    ("The first Kannada writer to receive the Jnanpith Award (1967) was:",
     ["Kuvempu", "D. R. Bendre", "Shivaram Karanth", "Masti Venkatesha Iyengar"], 0, PYQ + "For 'Sri Ramayana Darshanam'."),
    ("How many Jnanpith Awards have been won by Kannada writers?",
     ["8", "6", "7", "11"], 0, PYQ + "Kuvempu, Bendre, Karanth, Masti, V. K. Gokak, U. R. Ananthamurthy, Girish Karnad and Chandrashekhara Kambara."),
    ("Karnataka's state song (Nada Geethe), 'Jaya Bharata Jananiya Tanujate', was written by:",
     ["Kuvempu", "D. R. Bendre", "G. S. Shivarudrappa", "K. S. Narasimhaswamy"], 0, PYQ + "It was declared the state song in 2004."),
    ("Yakshagana is a traditional:",
     ["Dance-drama of coastal Karnataka", "Style of temple architecture", "Painting style of Mysore", "Kannada grammar book"], 0, PYQ + "It combines music, dance, dialogue and elaborate costumes."),
    ("Assertion (A): Dollu Kunitha is a folk dance of Karnataka.\nReason (R): Dollu Kunitha is performed only in the royal court of Mysuru.",
     AR, 2, "A is true; R is false – it is a vigorous drum dance of the Kuruba community, performed at village festivals."),
    ("Bidriware, a metal craft with silver inlay on a blackened alloy of zinc and copper, originated in:",
     ["Bidar", "Channapatna", "Ilkal", "Mysuru"], 0, PYQ + "It has a Geographical Indication (GI) tag."),
    ("Channapatna in Karnataka is famous for its:",
     ["Lacquered wooden toys", "Silk sarees", "Sandalwood oil", "Bidri work"], 0, "It is called 'Gombegala Ooru' (town of toys)."),
    ("Mysore painting is known for:",
     ["Gesso work – a raised, gold-covered paste on the painting", "Tribal wall motifs only", "Glass painting only", "Black-and-white sketches"], 0, "It developed under the patronage of the Wodeyars."),
    ("Hoysala temples are typically built of soapstone and stand on a:",
     ["Star-shaped (stellate) raised platform (jagati)", "Circular brick base", "Wooden frame", "Rock-cut cave"], 0, PYQ + "Soft chloritic schist allowed very fine carving."),
    ("Pattadakal is notable because its temples show:",
     ["Both the Nagara (northern) and Dravida (southern) styles", "Only Indo-Islamic style", "Only Hoysala style", "Only rock-cut caves"], 0, "It was a place of royal coronations for the Chalukyas."),
    ("The Mysuru Dasara festival in its present royal form was started in 1610 by:",
     ["Raja Wodeyar", "Tipu Sultan", "Haider Ali", "Krishnadevaraya"], 0, "It continued the Mahanavami festival of Vijayanagara; it is the 'Nada Habba' of Karnataka."),
    ("The Mahamastakabhisheka of Gommateshwara at Shravanabelagola is held once every:",
     ["12 years", "5 years", "1 year", "25 years"], 0, PYQ + "The most recent one before 2026 was in 2018."),
    ("The state emblem of Karnataka shows the:",
     ["Gandabherunda (two-headed mythical bird)", "Lion Capital", "Elephant and lotus only", "Peacock"], 0, "It was used earlier by Vijayanagara and the Wodeyars."),
    ("Match the writer with the work:\na. Pampa  b. Ranna  c. Kuvempu  d. D. R. Bendre\n1. Naku Tanti  2. Sri Ramayana Darshanam  3. Gadayuddha  4. Vikramarjuna Vijaya",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Bendre won the Jnanpith in 1973 for Naku Tanti."),
    ("Consider the statements:\nI. Kanakadasa and Purandara Dasa were Haridasa saint-composers.\nII. Basavanna was a court poet of the Rashtrakutas.\nWhich is/are correct?",
     I_II, 0, "Basavanna was a minister of the Kalachuri king Bijjala."),
    ("Assertion (A): Hoysala sculpture is extremely detailed.\nReason (R): Soapstone is soft when quarried and hardens on exposure, allowing fine carving.",
     AR, 0, "This explains the intricate friezes at Belur and Halebidu."),
]

TOPICS = {
    "Karnataka History, Culture and Art": [("1 · Early Dynasties of Karnataka", EARLY),
                                           ("2 · Hoysalas to Unification", LATER),
                                           ("3 · Culture, Literature, Art and Architecture", CULTURE)],
}
