"""Paper 1 · Health Education · P1-HE-06 Reproductive Health (2 sub-topics × 20).
Coverage (planner): RTIs & STIs – prevention & control.
References: WHO fact sheets on sexually transmitted infections and HIV; NACO (National AIDS Control Organisation) – NACP Phase V,
Suraksha clinics, ICTCs; MoHFW RCH / RMNCH+A and RKSK guidelines; HIV and AIDS (Prevention and Control) Act 2017; NCERT Biology
class 12 ch. 'Reproductive Health'. One REAL previous-year question (KEA 2026 GK-3, NHK) is used; KEA has published no key, so its
answer was worked out by ExamSim. Other items are "PYQ pattern" questions on themes common in KPSC / KEA / TET health sections."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / TET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

INFECTIONS = [
    ("Infections of the reproductive tract that are spread mainly through sexual contact are called:",
     ["Sexually transmitted infections (STIs)", "Vector-borne diseases", "Deficiency diseases", "Genetic disorders"], 0,
     PYQ + "They are also called STDs or venereal diseases (VD)."),
    ("Reproductive tract infections (RTIs) include:",
     ["STIs, endogenous infections (e.g. candidiasis, bacterial vaginosis) and iatrogenic infections from unsafe procedures", "Only HIV", "Only diseases spread by mosquitoes", "Only genetic diseases"], 0,
     "Not every RTI is sexually transmitted."),
    ("Gonorrhoea is caused by:",
     ["The bacterium Neisseria gonorrhoeae", "A virus", "A fungus", "A protozoan"], 0, PYQ + "It can be cured with antibiotics if treated early."),
    ("Syphilis is caused by:",
     ["Treponema pallidum, a spirochaete bacterium", "Human papillomavirus", "Herpes simplex virus", "Trichomonas"], 0, "Untreated syphilis can damage the heart and brain; a mother can pass it to her baby."),
    ("Which of the following STIs is caused by a virus?",
     ["Genital herpes", "Gonorrhoea", "Syphilis", "Chlamydiasis"], 0, PYQ + "Viral STIs: HIV, herpes (HSV-2), hepatitis B, genital warts (HPV)."),
    ("Trichomoniasis is caused by a:",
     ["Protozoan (Trichomonas vaginalis)", "Virus", "Bacterium", "Worm"], 0, "It is treated with metronidazole."),
    ("Long-lasting infection with certain types of human papillomavirus (HPV) can cause:",
     ["Cervical cancer", "Diabetes", "Malaria", "Tuberculosis"], 0, PYQ + "HPV vaccination protects against it; India's indigenous HPV vaccine is Cervavac."),
    ("AIDS is caused by:",
     ["HIV, a retrovirus that attacks helper T-lymphocytes (CD4 cells)", "A bacterium", "Vitamin deficiency", "A fungus"], 0, "AIDS = Acquired Immune Deficiency Syndrome."),
    ("HIV is NOT transmitted by:",
     ["Shaking hands, hugging, sharing food or mosquito bites", "Unprotected sexual contact", "Sharing infected needles", "Transfusion of infected blood"], 0,
     PYQ + "It can also pass from an infected mother to her baby."),
    ("The commonly used screening test for HIV is:",
     ["ELISA", "Widal test", "Mantoux test", "Pap smear"], 0, "Western blot or nucleic-acid tests are used for confirmation."),
    ("HIV infection is managed with:",
     ["Antiretroviral therapy (ART), which controls the virus but does not cure it", "A single dose of antibiotics", "Vitamin tablets", "Surgery"], 0,
     PYQ + "NACO provides free ART in government centres."),
    ("Untreated gonorrhoea or chlamydia in women can lead to:",
     ["Pelvic inflammatory disease (PID), ectopic pregnancy and infertility", "Better fertility", "No problems", "Only skin rashes"], 0, "Early diagnosis and treatment prevent complications."),
    ("Which statement about STIs is correct?",
     ["Many STIs show few or no symptoms at first, so testing is important", "All STIs show symptoms within a day", "STIs affect only adults over 50", "STIs cannot be prevented"], 0,
     PYQ + "Chlamydia is often called a 'silent' infection."),
    ("Hepatitis B, which can be spread sexually and through blood, can be prevented by:",
     ["Vaccination", "Antibiotics", "Vitamin C", "Wearing a mask"], 0, "It is part of India's Universal Immunisation Programme."),
    ("The time between HIV infection and the appearance of AIDS symptoms is usually:",
     ["Several years (often 5–10)", "One day", "One week", "Two hours"], 0, PYQ + "Opportunistic infections such as TB appear when immunity falls."),
    ("Consider the statements:\nI. Bacterial STIs such as syphilis and gonorrhoea can be cured with antibiotics.\nII. Viral STIs such as HIV can be completely cured with antibiotics.",
     I_II, 0, "Antibiotics do not act on viruses."),
    ("Assertion (A): A person with an STI should inform the partner so that both are treated.\nReason (R): Otherwise the infection can pass back and forth (re-infection).",
     AR, 0, "Partner treatment is part of STI management."),
    ("Assertion (A): HIV spreads through mosquito bites.\nReason (R): HIV can spread through infected blood.",
     AR, 3, "HIV does not survive or multiply in mosquitoes."),
    ("Match:\na. Gonorrhoea  b. Syphilis  c. Genital herpes  d. Trichomoniasis\n1. Neisseria  2. Treponema  3. Herpes simplex virus  4. Protozoan",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "STI and causative organism matching."),
    ("The symbol of solidarity with people living with HIV is the:",
     ["Red ribbon", "Pink ribbon", "Green leaf", "Blue star"], 0, "The pink ribbon is for breast-cancer awareness."),
]

PREVENTION = [
    ("'Once a week' contraceptive pill ____ with few side effects and high contraceptive value is produced at Central Drug Research Institute (CDRI) located at ____",
     ["i - Ratna, ii - Delhi", "i - Jaya, ii - Bangalore", "i - Saheli, ii - Lucknow", "i - Sonalika, ii - Pune"], 2,
     "Saheli (centchroman / ormeloxifene), a non-steroidal weekly pill, was developed by CDRI, Lucknow; it is supplied free as 'Chhaya'." + NOTE,
     "KEA 2026 GK-3 (NHK, 10 May 2026) · Q14"),
    ("The most effective way of preventing the spread of STIs during sexual contact, apart from abstinence, is:",
     ["Correct and consistent use of condoms", "Taking vitamins", "Using antiseptic soap", "Drinking more water"], 0, PYQ + "Mutual faithfulness to one uninfected partner also lowers risk."),
    ("Which practice helps prevent HIV spread through blood?",
     ["Using sterile, disposable needles and screened blood", "Sharing razors", "Reusing syringes", "Tattooing with unsterilised needles"], 0, "All donated blood in India is screened for HIV, hepatitis B and C, syphilis and malaria."),
    ("The national body that implements the HIV/AIDS control programme in India is:",
     ["NACO (National AIDS Control Organisation)", "ICMR only", "NITI Aayog", "WHO"], 0, PYQ + "NACO was set up in 1992 under the Ministry of Health and Family Welfare."),
    ("India's HIV/AIDS law that protects people living with HIV from discrimination is the:",
     ["HIV and AIDS (Prevention and Control) Act, 2017", "MTP Act, 1971", "PCPNDT Act, 1994", "RTE Act, 2009"], 0, "It also makes informed consent and confidentiality mandatory for testing."),
    ("World AIDS Day is observed on:",
     ["1 December", "7 April", "5 June", "14 November"], 0, PYQ + "7 April is World Health Day; 5 June is World Environment Day."),
    ("Designated STI/RTI clinics run under the national programme are branded:",
     ["Suraksha clinics", "Jan Aushadhi Kendras", "Anganwadis", "Sakhi centres"], 0, "They offer syndromic management, counselling and condoms."),
    ("Integrated Counselling and Testing Centres (ICTCs) provide:",
     ["Voluntary HIV counselling and testing", "Only eye tests", "Vaccination for travel", "Dental care"], 0, PYQ + "Pregnant women are tested to prevent parent-to-child transmission."),
    ("Treating RTIs/STIs on the basis of groups of symptoms (syndromes), without waiting for laboratory tests, is called:",
     ["Syndromic management", "Surgical management", "Isolation", "Quarantine"], 0, "WHO recommends it where laboratories are not available."),
    ("Reproductive health, according to WHO, means:",
     ["Total well-being in all physical, mental and social aspects of reproduction, not merely absence of disease", "Only the ability to have children", "Only absence of STIs", "Only family planning"], 0,
     PYQ + "It includes safe sex, choice of contraception, safe motherhood and healthy children."),
    ("The national programme for adolescent health launched in 2014, which includes sexual and reproductive health, is:",
     ["Rashtriya Kishor Swasthya Karyakram (RKSK)", "Janani Suraksha Yojana", "Mission Indradhanush", "Ayushman Bharat – PMJAY"], 0, "Peer educators ('Saathiya') and adolescent-friendly health clinics are part of it."),
    ("The legal minimum age of marriage in India for girls and boys under the Prohibition of Child Marriage Act is:",
     ["18 years and 21 years", "16 years and 18 years", "21 years for both", "18 years for both"], 0, PYQ + "Early marriage and pregnancy increase health risks."),
    ("An injectable contraceptive (DMPA) available free under the government programme is named:",
     ["Antara", "Saheli", "Mala-N", "Nirodh"], 0, "Mala-N is an oral pill; Nirodh is a condom brand; Copper-T is an intrauterine device."),
    ("Menstrual hygiene education for adolescent girls helps to prevent:",
     ["Reproductive tract infections", "Myopia", "Rickets", "Malaria"], 0, PYQ + "Use of clean sanitary pads and safe disposal is encouraged."),
    ("Prevention of parent-to-child transmission (PPTCT) of HIV is achieved mainly by:",
     ["Testing pregnant women and giving ART to HIV-positive mothers and preventive medicine to babies", "Avoiding all hospital visits", "Vitamins only", "Stopping vaccination"], 0,
     "India aims to eliminate vertical transmission of HIV and syphilis."),
    ("Consider the statements:\nI. Early diagnosis and complete treatment of STIs reduce the risk of HIV infection.\nII. Talking about reproductive health in schools increases risky behaviour.",
     I_II, 0, "Age-appropriate education reduces risky behaviour."),
    ("Assertion (A): People living with HIV should not be discriminated against in schools or workplaces.\nReason (R): HIV does not spread through casual contact.",
     AR, 0, "The 2017 Act makes such discrimination illegal."),
    ("Assertion (A): Condoms give no protection against STIs.\nReason (R): Condoms act as a barrier to body fluids.",
     AR, 3, "Because they are a barrier, condoms greatly reduce STI and HIV transmission."),
    ("Match:\na. NACO  b. ICTC  c. Suraksha clinic  d. ART centre\n1. National HIV programme  2. HIV counselling and testing  3. STI/RTI care  4. Free antiretroviral treatment",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Programme-facility matching."),
    ("The national toll-free HIV/AIDS helpline number is:",
     ["1097", "108", "112", "1098"], 0, "108 – ambulance; 112 – emergency; 1098 – Childline."),
]

TOPICS = {
    "Reproductive Health": [("1 · RTIs and STIs – Types, Causes and Effects", INFECTIONS),
                            ("2 · Prevention and Control of RTIs, STIs and HIV/AIDS", PREVENTION)],
}
