"""Paper 1 · Health Education · P1-HE-03 Non-Communicable & Lifestyle Diseases (2 sub-topics × 20).
References: WHO fact sheets (Noncommunicable diseases; Hypertension; Diabetes; Physical activity; Salt); NCERT Biology; MoHFW / PIB.
Explanations starting "PYQ pattern" follow questions that recur in KPSC / KEA / SSC papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / SSC). "

NCD = [
    ("Non-communicable diseases (NCDs) are diseases that:",
     ["Are not passed from person to person and usually last a long time", "Spread through air and water", "Are always caused by bacteria", "Last only a few days"], 0, "They are also called chronic diseases."),
    ("According to the WHO, the four main groups of NCDs are:",
     ["Cardiovascular diseases, cancers, chronic respiratory diseases and diabetes", "Malaria, dengue, typhoid and cholera", "Measles, mumps, rubella and polio", "Scurvy, rickets, beriberi and goitre"], 0, PYQ + "Together they cause most NCD deaths."),
    ("According to the WHO, NCDs cause about what share of all deaths worldwide?",
     ["About three-quarters (≈ 74%)", "About one-tenth", "About one-quarter", "Almost none"], 0, "About 41 million deaths a year."),
    ("The four main modifiable behavioural risk factors for NCDs are:",
     ["Tobacco use, physical inactivity, harmful use of alcohol and unhealthy diet", "Mosquitoes, flies, rats and cockroaches", "Age, sex, height and blood group", "Sunlight, rain, wind and cold"], 0, PYQ + "Changing these behaviours prevents much NCD illness."),
    ("Insulin is produced by the:",
     ["Beta cells of the islets of Langerhans in the pancreas", "Liver", "Thyroid gland", "Adrenal cortex"], 0, PYQ + "It lowers blood glucose."),
    ("Type 1 diabetes is caused mainly by:",
     ["The body's immune system destroying insulin-producing cells, so little or no insulin is made", "Eating too much sugar in one day", "A virus spread by mosquitoes", "Lack of vitamin C"], 0, PYQ + "Type 2 diabetes involves insulin resistance and is strongly linked to lifestyle."),
    ("A fasting plasma glucose level of how much or above indicates diabetes?",
     ["126 mg/dL", "70 mg/dL", "100 mg/dL", "90 mg/dL"], 0, "100–125 mg/dL is 'prediabetes' (impaired fasting glucose)."),
    ("Hypertension is generally diagnosed when blood pressure is persistently at or above:",
     ["140/90 mmHg", "120/80 mmHg", "100/60 mmHg", "90/60 mmHg"], 0, PYQ + "Around 120/80 mmHg is considered normal."),
    ("Hypertension is often called the 'silent killer' because:",
     ["It usually causes no symptoms while damaging the heart, brain and kidneys", "It makes no sound in a stethoscope", "It affects only old people", "It is always fatal within days"], 0, "Regular checking is the only way to detect it early."),
    ("A cancer that spreads from its original site to other parts of the body is said to have:",
     ["Metastasised", "Healed", "Become benign", "Become infectious"], 0, "Malignant tumours can metastasise; benign ones do not."),
    ("Chewing tobacco is a major cause of which cancer in India?",
     ["Oral (mouth) cancer", "Skin cancer", "Bone cancer", "Blood cancer only"], 0, "India bears a large share of the world's oral-cancer cases."),
    ("Chronic obstructive pulmonary disease (COPD) is caused mainly by:",
     ["Smoking and long exposure to smoke and dust", "Mosquito bites", "Eating fruits", "Drinking clean water"], 0, "It makes breathing progressively harder."),
    ("World Diabetes Day is observed on:",
     ["14 November", "7 April", "4 February", "29 September"], 0, PYQ + "It is the birthday of Frederick Banting, co-discoverer of insulin."),
    ("World Cancer Day is observed on:",
     ["4 February", "14 November", "31 May", "1 December"], 0, PYQ + "It is led by the Union for International Cancer Control."),
    ("World Heart Day is observed on:",
     ["29 September", "4 February", "7 April", "21 June"], 0, "It is promoted by the World Heart Federation."),
    ("India's national programme for prevention and control of cancer, diabetes, cardiovascular diseases and stroke, launched in 2010, was abbreviated as:",
     ["NPCDCS", "NVBDCP", "RNTCP", "NACP"], 0, PYQ + "It has since been renamed the National Programme for Prevention and Control of Non-Communicable Diseases (NP-NCD)."),
    ("Match the NCD with the organ mainly affected:\na. Diabetes  b. Hypertension  c. COPD  d. Stroke\n1. Brain  2. Lungs  3. Blood vessels and heart  4. Pancreas (insulin) and blood sugar control",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "NCDs affect different organ systems."),
    ("Consider the statements:\nI. Diabetes can be caught from a diabetic person.\nII. Regular screening helps detect hypertension early.\nWhich is/are correct?",
     I_II, 1, "Diabetes is non-communicable."),
    ("Assertion (A): Tobacco use is a major risk factor for NCDs.\nReason (R): Tobacco increases the risk of cancer, heart disease and lung disease.",
     AR, 0, "Tobacco is the single largest preventable cause of NCDs."),
    ("Assertion (A): Type 1 diabetes is caused mainly by overeating sweets.\nReason (R): In type 1 diabetes the body produces little or no insulin.",
     AR, 3, "Type 1 is an autoimmune condition; A is false, R is true."),
]

LIFESTYLE = [
    ("Lifestyle diseases are diseases that are caused or made worse mainly by:",
     ["Daily habits such as diet, physical activity, smoking and stress", "Germs spread by insects", "Injuries in accidents", "Genetic mutations alone"], 0, "Examples: obesity, type 2 diabetes, hypertension and heart disease."),
    ("Body Mass Index (BMI) is calculated as:",
     ["Weight (kg) ÷ height (m)²", "Height (cm) ÷ weight (kg)", "Weight (kg) × height (m)", "Weight (kg) ÷ age (years)"], 0, PYQ + "It is a simple screening measure of body weight."),
    ("A person weighs 72 kg and is 1.8 m tall. Their BMI is about:",
     ["22.2", "40", "25.8", "18.0"], 0, "72 ÷ (1.8 × 1.8) = 72 ÷ 3.24 ≈ 22.2."),
    ("A person weighs 90 kg and is 1.5 m tall. Their BMI is:",
     ["40", "60", "30", "22.5"], 0, "90 ÷ 2.25 = 40 – obese by WHO criteria."),
    ("By the WHO's international classification, a BMI of 18.5–24.9 is:",
     ["Normal weight", "Underweight", "Overweight", "Obese"], 0, PYQ + "25–29.9 is overweight and 30 or more is obese (lower cut-offs are often used for Asians)."),
    ("The WHO recommends that adults do at least how much moderate-intensity physical activity per week?",
     ["150 minutes", "30 minutes", "60 minutes", "500 minutes"], 0, PYQ + "Or 75 minutes of vigorous activity."),
    ("The WHO recommends that adults consume less than how much salt per day?",
     ["5 grams", "15 grams", "25 grams", "50 grams"], 0, "Excess salt raises blood pressure."),
    ("Atherosclerosis is:",
     ["Narrowing and hardening of arteries due to fatty deposits (plaque)", "Inflammation of the liver", "A lung infection", "Loss of bone density"], 0, "It can lead to heart attacks and strokes."),
    ("A heart attack (myocardial infarction) occurs when:",
     ["Blood flow in a coronary artery is blocked and heart muscle is damaged", "The lungs fill with water", "The kidneys stop filtering blood", "A bone breaks"], 0, "Chest pain spreading to the arm or jaw is a warning sign."),
    ("A stroke occurs when:",
     ["The blood supply to part of the brain is interrupted or a blood vessel in the brain bursts", "The heart beats too slowly for a moment", "The stomach is inflamed", "A muscle is strained"], 0, "Sudden weakness of one side of the body or slurred speech are signs."),
    ("Which habit most increases the risk of lifestyle diseases?",
     ["Sitting for long hours with little physical activity", "Walking daily", "Eating fruits and vegetables", "Sleeping 7–8 hours"], 0, "A sedentary lifestyle contributes to obesity, diabetes and heart disease."),
    ("Trans fats, found in some fried and bakery foods made with partially hydrogenated oils, are harmful mainly because they:",
     ["Raise 'bad' LDL cholesterol and lower 'good' HDL cholesterol", "Contain vitamin C", "Improve heart health", "Are rich in fibre"], 0, "The WHO has called for their elimination from the food supply."),
    ("Adults are generally advised to sleep about:",
     ["7–9 hours a night", "3–4 hours a night", "12–14 hours a night", "1–2 hours a night"], 0, "Poor sleep is linked to obesity, diabetes and heart disease."),
    ("The Fit India Movement was launched on National Sports Day, 29 August:",
     ["2019", "2014", "2021", "2016"], 0, PYQ + "National Sports Day marks the birth anniversary of Major Dhyan Chand."),
    ("International Day of Yoga is observed on:",
     ["21 June", "5 June", "29 August", "2 October"], 0, PYQ + "It was first observed in 2015 after a UN General Assembly resolution in 2014."),
    ("The 'Eat Right India' movement, promoting safe, healthy and sustainable food, is led by:",
     ["FSSAI (Food Safety and Standards Authority of India)", "ISRO", "RBI", "NITI Aayog only"], 0, "It was launched in 2018."),
    ("Match the lifestyle factor with the disease it most directly raises the risk of:\na. Excess salt  b. Smoking  c. Excess sugar and obesity  d. Excess alcohol\n1. Liver cirrhosis  2. Type 2 diabetes  3. Lung cancer  4. Hypertension",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each habit targets particular organs."),
    ("Consider the statements:\nI. Regular exercise helps control blood sugar and blood pressure.\nII. Yoga and meditation can help manage stress.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Obesity increases the risk of type 2 diabetes.\nReason (R): Excess body fat makes the body's cells resistant to insulin.",
     AR, 0, "Insulin resistance is the main mechanism of type 2 diabetes."),
    ("Assertion (A): Lifestyle diseases can be largely prevented.\nReason (R): International Day of Yoga is observed on 21 June.",
     AR, 1, "Both true, but R does not explain A; A is explained by risk factors being modifiable habits."),
]

TOPICS = {
    "Non-Communicable & Lifestyle Diseases": [("1 · Non-Communicable Diseases", NCD),
                                              ("2 · Lifestyle Diseases: Causes and Prevention", LIFESTYLE)],
}
