"""Paper 1 · Health Education · P1-HE-01 Health Education – Basics (2 sub-topics × 20).
References: DSERT Health Education syllabus; K. Park, Textbook of Preventive and Social Medicine; WHO fact sheets."""
from packlib import AR, I_II

HEALTH_ED = [
    ("According to the WHO (1948), health is:",
     ["A state of complete physical, mental and social well-being and not merely the absence of disease or infirmity", "The absence of disease only", "Physical fitness only", "Having enough money for treatment"], 0, "This definition is in the Preamble to the WHO Constitution."),
    ("World Health Day is observed every year on:",
     ["7 April", "1 December", "5 June", "21 June"], 0, "It marks the founding of the WHO in 1948. 1 Dec – World AIDS Day; 5 June – Environment Day; 21 June – Yoga Day."),
    ("The headquarters of the World Health Organization is at:",
     ["Geneva", "New York", "Paris", "Rome"], 0, "WHO is a specialised agency of the United Nations."),
    ("Which of the following is NOT one of the commonly stated dimensions of health?",
     ["Financial dimension of a nation", "Physical", "Mental", "Social"], 0, "Physical, mental, social (and also spiritual and emotional) dimensions are discussed."),
    ("Health education is best described as:",
     ["A process of learning experiences that helps people adopt behaviour which promotes health", "Giving medicines free of cost", "Building hospitals", "Treating diseases after they occur"], 0, "Its focus is on knowledge, attitudes and practices (KAP)."),
    ("The three components commonly aimed at by health education are summed up as:",
     ["Knowledge, attitude and practice (KAP)", "Diagnosis, drugs and doctors", "Food, fees and furniture", "Tests, tablets and treatment"], 0, "Knowing is not enough; attitudes and habits must change."),
    ("'Health education is the translation of what is known about health into desirable individual and community behaviour patterns by means of the educational process.' This definition is by:",
     ["Ruth E. Grout", "Florence Nightingale", "Edward Jenner", "Mahatma Gandhi"], 0, "Grout's definition is widely quoted in health education texts."),
    ("Which principle of health education says teaching should start from what people already know?",
     ["Proceeding from the known to the unknown", "Punishment", "Fear alone", "Memorisation without understanding"], 0, "Other principles include interest, participation, motivation, comprehension, reinforcement and learning by doing."),
    ("A health message is more likely to change behaviour when the people take an active part in discussions and activities. This is the principle of:",
     ["Participation", "Credibility", "Soil, seed and sower", "Reinforcement"], 0, "Active participation leads to acceptance of new health habits."),
    ("The Alma-Ata Declaration (1978) is associated with:",
     ["Primary health care and the goal 'Health for All by 2000'", "Eradication of smallpox only", "The founding of the WHO", "The Red Cross"], 0, "It made primary health care the key to health for all."),
    ("The three main components of a school health programme are:",
     ["School health services, a healthful school environment and health instruction", "Fees, uniform and transport", "Examinations, results and ranks", "Sports day, annual day and tours"], 0, "Health education in schools covers all three."),
    ("Health education is important mainly because:",
     ["Prevention of disease is easier and cheaper than cure", "It replaces all doctors", "It guarantees that nobody falls ill", "It is required only for sick people"], 0, "Healthy habits prevent many diseases."),
    ("A teacher displays charts on hand-washing, demonstrates the steps and asks pupils to practise daily. The teacher is applying the principle of:",
     ["Learning by doing", "Fear arousal", "Competition only", "Rote memory"], 0, "Practice turns knowledge into habit."),
    ("Match the day with its date:\na. World Health Day  b. World AIDS Day  c. International Day of Yoga  d. World No Tobacco Day\n1. 31 May  2. 21 June  3. 1 December  4. 7 April",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These days are used for health awareness campaigns."),
    ("Consider the statements:\nI. Health includes mental and social well-being, not only physical fitness.\nII. A person without any disease is always completely healthy according to the WHO.\nWhich is/are correct?",
     I_II, 0, "The WHO definition says health is not merely the absence of disease."),
    ("Consider the statements:\nI. Health education aims at changing health behaviour, not only giving information.\nII. Health education is useful for healthy people as well as sick people.\nWhich is/are correct?",
     I_II, 2, "Both are central ideas of health education."),
    ("Assertion (A): Health education gives importance to changing attitudes and habits.\nReason (R): Knowledge alone does not always lead people to adopt healthy practices.",
     AR, 0, "Many people know that smoking is harmful and still smoke."),
    ("Assertion (A): Health education is needed only after a disease has broken out.\nReason (R): Health education aims at the prevention of disease.",
     AR, 3, "Because its aim is prevention, it is needed before diseases occur; R shows why A is false."),
    ("Assertion (A): The WHO was established in 1948.\nReason (R): The WHO's definition of health includes social well-being.",
     AR, 1, "Both true, but unrelated."),
    ("Assertion (A): Health education in schools can influence the health of the whole community.\nReason (R): Children carry health habits and messages to their families.",
     AR, 0, "Pupils act as agents of change at home."),
]

HYGIENE = [
    ("The word 'hygiene' comes from Hygieia, who in Greek mythology was the goddess of:",
     ["Health", "Wisdom", "War", "Harvest"], 0, "Hygiene is the science and practice of preserving health."),
    ("Personal hygiene refers to:",
     ["Keeping one's own body, clothes and surroundings clean to stay healthy", "Cleaning public roads only", "Treatment in hospitals", "Taking medicines daily"], 0, "It includes care of skin, hair, teeth, nails, eyes, ears and clothes."),
    ("Health agencies recommend washing hands with soap and water for at least:",
     ["20 seconds", "2 seconds", "5 minutes", "1 second"], 0, "Scrubbing all parts of the hands for about 20 seconds removes most germs."),
    ("Global Handwashing Day is observed on:",
     ["15 October", "7 April", "5 September", "14 November"], 0, "It promotes hand-washing with soap to prevent diarrhoea and respiratory infections."),
    ("Which disease is spread mainly by the faeco-oral route and is prevented by hand-washing and safe water?",
     ["Typhoid", "Malaria", "Dengue", "Tetanus"], 0, "Malaria and dengue are spread by mosquitoes; tetanus enters through wounds."),
    ("Keeping fingernails short and clean helps mainly to prevent:",
     ["Worm infestation and other faeco-oral infections", "Short-sightedness", "Anaemia due to blood donation", "Sunburn"], 0, "Worm eggs and germs collect under long nails and reach the mouth."),
    ("Dental experts advise brushing the teeth:",
     ["At least twice a day, especially at night before sleeping", "Once a week", "Only when there is pain", "Only after sweets"], 0, "Brushing removes plaque that causes dental caries and gum disease."),
    ("Scabies, an itchy skin disease that spreads by close contact, is caused by a:",
     ["Mite", "Virus", "Vitamin deficiency", "Mosquito bite"], 0, "Personal cleanliness and not sharing clothes help prevent it."),
    ("Head lice infestation (pediculosis) is best prevented by:",
     ["Keeping hair clean and not sharing combs, caps and towels", "Eating more sugar", "Sleeping more", "Wearing spectacles"], 0, "Lice spread through close contact and shared personal items."),
    ("The '20-20-20 rule' for people who use screens for long hours means:",
     ["Every 20 minutes, look at something about 20 feet away for 20 seconds", "Sleep 20 hours in 20 days", "Drink 20 glasses of water", "Use the screen only for 20 minutes a day"], 0, "It relaxes the eye muscles and reduces eye strain."),
    ("According to the WHO, children and adolescents aged 5–17 years should do moderate-to-vigorous physical activity of, on average, at least:",
     ["60 minutes a day", "10 minutes a week", "5 hours a day", "30 minutes a month"], 0, "Regular activity builds fitness and healthy bones and muscles."),
    ("Adolescents (13–18 years) are generally advised to sleep about:",
     ["8–10 hours a night", "4–5 hours a night", "12–14 hours a night", "2–3 hours a night"], 0, "Adequate sleep supports growth, memory and attention."),
    ("Which practice is harmful to the ears?",
     ["Inserting sharp objects such as pins to clean them", "Keeping them dry after bathing", "Avoiding very loud music", "Cleaning the outer ear with a soft cloth"], 0, "Sharp objects can damage the ear drum."),
    ("Which of the following is a good food-hygiene practice?",
     ["Washing fruits and vegetables before eating and keeping food covered", "Eating food left uncovered on the roadside", "Using the same knife for raw meat and salad without washing", "Keeping cooked food in the sun"], 0, "Covering food prevents flies and dust from contaminating it."),
    ("Match the body part with a hygiene practice:\na. Teeth  b. Eyes  c. Skin  d. Hair\n1. Regular washing and combing  2. Daily bathing  3. Washing with clean water and resting them  4. Brushing twice daily",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each part of the body needs its own care."),
    ("Consider the statements:\nI. Sharing towels and combs can spread skin infections and lice.\nII. Good posture while sitting and standing is part of personal health.\nWhich is/are correct?",
     I_II, 2, "Both are aspects of personal health and hygiene."),
    ("Consider the statements:\nI. Drinking boiled or purified water helps prevent diarrhoea and cholera.\nII. Washing hands only with water is as effective as washing with soap.\nWhich is/are correct?",
     I_II, 0, "Soap removes germs and grease much better than water alone."),
    ("Assertion (A): Washing hands with soap reduces diarrhoeal diseases.\nReason (R): Many diarrhoea-causing germs reach the mouth through dirty hands.",
     AR, 0, "Hand-washing breaks the faeco-oral route of transmission."),
    ("Assertion (A): Personal hygiene is important for good health.\nReason (R): Hygieia was the Greek goddess of health.",
     AR, 1, "Both true, but the origin of the word does not explain why hygiene matters."),
    ("Assertion (A): Long nails are good for health because they protect the fingers.\nReason (R): Dirt and worm eggs can collect under long nails.",
     AR, 3, "Because dirt and eggs collect under them, long nails are unhygienic; R shows why A is false."),
]

TOPICS = {
    "Health Education – Basics": [("1 · Health Education: Meaning, Definition and Importance", HEALTH_ED),
                                  ("2 · Personal Health and Hygiene", HYGIENE)],
}
