"""Paper 1 · Health Education · P1-HE-02 Health and Diseases (2 sub-topics × 20).
References: DSERT Health Education syllabus; K. Park, Textbook of Preventive and Social Medicine; NCERT Class 9 Biology
('Why Do We Fall Ill?'); Indian Public Health Standards; National Health Mission documents."""
from packlib import AR, I_II

HEALTH_SYSTEMS = [
    ("In India's public health system, primary health care is provided mainly through:",
     ["Sub-centres and Primary Health Centres (PHCs)", "Medical colleges only", "Private super-speciality hospitals", "District courts"], 0, "Community Health Centres and district hospitals form the secondary level; medical colleges the tertiary level."),
    ("Arrange the levels of health care in India from the first contact point upwards:",
     ["Sub-centre → PHC → CHC → district hospital → medical college/tertiary hospital", "CHC → sub-centre → PHC → medical college → district hospital", "District hospital → PHC → sub-centre → CHC", "Medical college → CHC → PHC → sub-centre"], 0, "Patients are referred upwards when more specialised care is needed."),
    ("Under the Indian Public Health Standards, a sub-centre in the plains serves a population of about:",
     ["5,000 (3,000 in hilly and tribal areas)", "30,000", "1,20,000", "500"], 0, "A PHC serves about 30,000 (20,000 in hilly/tribal areas) and a CHC about 1,20,000 (80,000)."),
    ("ASHA, the community health worker under the National Rural Health Mission, stands for:",
     ["Accredited Social Health Activist", "Assistant Staff for Hospital Administration", "All-India Scheme for Health Awareness", "Auxiliary Sanitary Health Assistant"], 0, "There is roughly one ASHA per 1,000 rural population."),
    ("The National Health Mission has two sub-missions:",
     ["National Rural Health Mission (2005) and National Urban Health Mission (2013)", "Swachh Bharat and Jal Jeevan", "Mid-day Meal and Anganwadi", "Pulse Polio and Mission Indradhanush"], 0, "Both aim to strengthen public health systems."),
    ("Ayushman Bharat (2018) has two components:",
     ["Health and Wellness Centres (now Ayushman Arogya Mandirs) and the Pradhan Mantri Jan Arogya Yojana (PM-JAY) health insurance", "Free textbooks and uniforms", "Village roads and electricity", "Mid-day meals and scholarships"], 0, "PM-JAY provides hospital cover of up to ₹5 lakh per family per year."),
    ("Janani Suraksha Yojana promotes:",
     ["Institutional deliveries by giving cash assistance to pregnant women", "Free higher education", "Old-age pensions", "Road safety"], 0, "It aims to reduce maternal and newborn deaths."),
    ("Mission Indradhanush (2014) aims to:",
     ["Increase full immunisation coverage of children and pregnant women", "Supply electricity to villages", "Clean rivers", "Provide mobile phones"], 0, "It strengthens the Universal Immunisation Programme."),
    ("Match the level of prevention with an example:\na. Primary prevention  b. Secondary prevention  c. Tertiary prevention  d. Primordial prevention\n1. Promoting healthy lifestyles in children before risk factors appear  2. Physiotherapy and rehabilitation after a stroke  3. Screening to detect breast cancer early  4. Immunisation against measles",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Primary prevention acts before disease occurs; secondary detects it early; tertiary limits disability."),
    ("Vaccination is an example of which kind of prevention?",
     ["Primary prevention (specific protection)", "Secondary prevention", "Tertiary prevention", "Rehabilitation"], 0, "It prevents the disease from occurring at all."),
    ("The Infant Mortality Rate (IMR) is the number of deaths of infants under one year of age per:",
     ["1,000 live births in a year", "100 live births", "1,00,000 population", "10,000 women"], 0, "The Maternal Mortality Ratio is expressed per 1,00,000 live births."),
    ("Which of the following is NOT usually listed as a determinant of health?",
     ["The colour of one's clothes", "Heredity (biological factors)", "Environment and sanitation", "Income, education and access to health services"], 0, "Behaviour and lifestyle are also important determinants."),
    ("An essential principle of primary health care is:",
     ["Community participation and equitable distribution of services", "Care only in big city hospitals", "Care only for the rich", "Use of the most expensive technology"], 0, "Inter-sectoral coordination and appropriate technology are other principles."),
    ("The Universal Immunisation Programme of India was launched in:",
     ["1985", "1947", "2005", "2018"], 0, "It provides free vaccines against several childhood diseases."),
    ("In India, the telephone number 108 is widely used for:",
     ["Emergency ambulance services", "Railway enquiries", "Police only", "Weather reports"], 0, "Many states, including Karnataka, run 108 emergency ambulance services."),
    ("Consider the statements:\nI. A Community Health Centre is a referral unit for several PHCs.\nII. A sub-centre is headed by a specialist surgeon.\nWhich is/are correct?",
     I_II, 0, "Sub-centres are run by health workers (ANM and male health worker)."),
    ("Consider the statements:\nI. Screening tests are a form of secondary prevention.\nII. Rehabilitation is a form of tertiary prevention.\nWhich is/are correct?",
     I_II, 2, "Both statements are correct."),
    ("Assertion (A): Prevention is given great importance in public health.\nReason (R): Preventing disease is usually easier and cheaper than treating it.",
     AR, 0, "It saves lives and money."),
    ("Assertion (A): Primary health care depends only on doctors in city hospitals.\nReason (R): Primary health care stresses community participation and services close to where people live.",
     AR, 3, "R describes primary health care correctly, which shows that A is false."),
    ("Assertion (A): ASHAs work at the village level.\nReason (R): The Universal Immunisation Programme began in 1985.",
     AR, 1, "Both true but unrelated."),
]

INFECTIOUS = [
    ("An infectious (communicable) disease is one that:",
     ["Is caused by a pathogen and can spread from one person or animal to another", "Is always inherited", "Is caused only by poor diet", "Can never be prevented"], 0, "Pathogens include viruses, bacteria, protozoa, fungi and worms."),
    ("The time between the entry of a pathogen into the body and the appearance of the first symptoms is called the:",
     ["Incubation period", "Recovery period", "Quarantine period", "Immune period"], 0, "It differs from disease to disease."),
    ("Match the disease with its main mode of transmission:\na. Tuberculosis  b. Cholera  c. Dengue  d. Hepatitis B\n1. Infected blood and body fluids  2. Bite of an Aedes mosquito  3. Contaminated water and food  4. Airborne droplets",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Knowing the route of spread tells us how to prevent the disease."),
    ("Match the mosquito with a disease it spreads:\na. Anopheles  b. Aedes  c. Culex\n1. Filariasis (elephantiasis)  2. Dengue and chikungunya  3. Malaria",
     ["a-3, b-2, c-1", "a-2, b-3, c-1", "a-3, b-1, c-2", "a-1, b-2, c-3"], 0, "Only female mosquitoes bite and spread these diseases."),
    ("The Aedes aegypti mosquito, which spreads dengue, mainly:",
     ["Bites during the day and breeds in clean stored water in containers, coolers and tyres", "Bites only at midnight and breeds in sewage", "Breeds only in rivers", "Does not bite humans"], 0, "Removing stagnant water around homes is the key to prevention."),
    ("A cough lasting more than two weeks, with fever and weight loss, is a typical warning sign of:",
     ["Tuberculosis", "Common cold", "Malaria", "Tetanus"], 0, "TB is caused by Mycobacterium tuberculosis; the BCG vaccine protects children against severe forms."),
    ("'Rice-water' stools with severe dehydration are characteristic of:",
     ["Cholera", "Typhoid", "Dengue", "Measles"], 0, "Cholera is caused by Vibrio cholerae; oral rehydration is life-saving."),
    ("Oral Rehydration Solution (ORS) is given in diarrhoea mainly to:",
     ["Replace the water and salts lost from the body", "Kill the bacteria", "Stop vomiting permanently", "Provide vitamins"], 0, "Zinc supplements are also given to children with diarrhoea."),
    ("Typhoid fever is caused by:",
     ["Salmonella Typhi, spread through contaminated food and water", "A virus spread by mosquitoes", "A fungus on the skin", "Lack of vitamin C"], 0, "The Widal test is a traditional blood test used in diagnosis."),
    ("After a dog bite, the correct first-aid step is to:",
     ["Wash the wound thoroughly with soap and running water for about 15 minutes and get anti-rabies vaccination promptly", "Apply chilli powder and wait", "Bandage it tightly and ignore it", "Wait until symptoms appear"], 0, "Rabies is almost always fatal once symptoms appear, so treatment must start early."),
    ("Tetanus is caused by bacteria that usually enter the body through:",
     ["Wounds contaminated with soil, dust or rusty objects", "Mosquito bites", "Drinking water", "Coughing"], 0, "It is prevented by tetanus toxoid (Td) vaccination."),
    ("Which pair of diseases is spread mainly by the faeco-oral route (contaminated food and water)?",
     ["Hepatitis A and hepatitis E", "Hepatitis B and HIV", "Malaria and dengue", "Tuberculosis and measles"], 0, "Hepatitis B and C spread through blood and body fluids."),
    ("Measles is caused by a ______ and is prevented by the ______ vaccine.",
     ["virus; MR (measles-rubella)", "bacterium; BCG", "protozoan; polio", "fungus; DPT"], 0, "Measles causes fever, cough and a spreading rash."),
    ("The correct order of the 'chain of infection' is:",
     ["Infectious agent → reservoir → portal of exit → mode of transmission → portal of entry → susceptible host", "Host → agent → reservoir → exit → entry → transmission", "Transmission → agent → host → reservoir → entry → exit", "Reservoir → host → agent → transmission → exit → entry"], 0, "Breaking any one link stops the spread of the disease."),
    ("Isolation and quarantine differ in that:",
     ["Isolation separates people who are sick; quarantine restricts healthy people who may have been exposed", "They are the same", "Quarantine is only for animals", "Isolation is for healthy people"], 0, "Both limit the spread of infection."),
    ("Immunity produced by a vaccine is:",
     ["Artificially acquired active immunity", "Naturally acquired passive immunity", "Artificially acquired passive immunity", "Inherited immunity"], 0, "Antibodies passed from mother to baby give naturally acquired passive immunity."),
    ("Consider the statements:\nI. Antibiotics are effective against bacterial infections.\nII. Using mosquito nets and removing stagnant water helps prevent malaria.\nWhich is/are correct?",
     I_II, 2, "Both are correct; antibiotics do not act on viruses."),
    ("Consider the statements:\nI. HIV spreads through shaking hands and sharing food.\nII. Tuberculosis spreads through droplets when an infected person coughs or sneezes.\nWhich is/are correct?",
     I_II, 1, "HIV does not spread through casual contact; it spreads through blood, sexual contact and from mother to child."),
    ("Assertion (A): Hand-washing and safe drinking water reduce cholera and typhoid.\nReason (R): These diseases spread mainly through contaminated food and water.",
     AR, 0, "Breaking the faeco-oral route prevents them."),
    ("Assertion (A): Dengue can be prevented by taking antibiotics.\nReason (R): Dengue is caused by a virus.",
     AR, 3, "Antibiotics do not act on viruses, so A is false; prevention relies on mosquito control."),
]

TOPICS = {
    "Health and Diseases": [("1 · Health and Health Systems", HEALTH_SYSTEMS),
                            ("2 · Infectious Diseases: Causes, Symptoms, Transmission, Prevention and Control", INFECTIOUS)],
}
