"""Paper 1 · Health Education · P1-HE-05 Food for Healthy Living (2 sub-topics × 20).
Coverage (planner): dietary requirements, balanced diet, malnutrition types, eating disorders.
References: ICMR–NIN Dietary Guidelines for Indians (2024) and Nutrient Requirements for Indians (2020); WHO fact sheets on
malnutrition and healthy diet; NCERT Science (classes 6, 10) and Biology (class 11); POSHAN Abhiyaan / Anaemia Mukt Bharat (MoHFW).
REAL previous-year questions come from KRIES entrance tests 2024–26, the Legislative Council 2024 Paper-1, a UPSC-coaching entrance
test and PGCET 2025 MCA (general-knowledge section); none has a published key, so their answers are worked out by ExamSim."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / TET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

DIET = [
    ("The nutrient which is helpful for our body growth is",
     ["Carbohydrates", "Protein", "Lipid", "Vitamin"], 1,
     "Proteins are body-building foods – they make and repair tissues. Carbohydrates and fats give energy; vitamins protect." + NOTE,
     "KRIES 2025 entrance · Q64"),
    ("Which vitamin is enriched in outer surface of rice?",
     ["A", "B", "C", "D"], 1,
     "The bran layer of rice is rich in B vitamins, especially thiamine (B1); polishing removes it, which is why polished-rice diets caused beriberi." + NOTE,
     "KRIES 2026 entrance · Q70"),
    ("This is not an example for denatured protein.",
     ["Boiled egg albumin (white)", "Curding of milk", "Starch solution", "Coagulation of insulin"], 2,
     "Starch is a carbohydrate, not a protein. Heat (boiled egg), acid (curdling of milk) and clumping (insulin) denature proteins." + NOTE,
     "Legislative Council 2024 Asst/Computer Operator P1 · Q48"),
    ("A balanced diet is one that:",
     ["Contains all nutrients in the right amounts for the body's needs, along with roughage and water", "Contains only proteins and vitamins",
      "Has equal amounts of every food", "Avoids fats completely"], 0, PYQ + "Needs vary with age, sex, body size, activity and physiological state (pregnancy, lactation)."),
    ("Carbohydrates and fats are known as:",
     ["Energy-giving foods", "Body-building foods", "Protective foods", "Roughage"], 0,
     "Proteins are body-building foods; vitamins and minerals are protective foods."),
    ("1 gram of carbohydrate, protein and fat gives about ____ kcal of energy respectively.",
     ["4, 4 and 9", "9, 4 and 4", "4, 9 and 4", "2, 4 and 9"], 0, PYQ + "Fat is the most concentrated source of energy."),
    ("Which of the following is a fat-soluble vitamin?",
     ["Vitamin D", "Vitamin C", "Vitamin B12", "Vitamin B1"], 0, "Fat-soluble: A, D, E, K. Water-soluble: B-complex and C."),
    ("Dietary fibre (roughage) mainly helps to:",
     ["Prevent constipation and aid bowel movement", "Give a lot of energy", "Build muscles", "Clot blood"], 0,
     PYQ + "Sources: whole grains, pulses, fruits and leafy vegetables."),
    ("The richest natural source of vitamin C among these is:",
     ["Amla (Indian gooseberry)", "Rice", "Milk", "Egg yolk"], 0, "Citrus fruits and guava are also rich sources; vitamin C is lost on prolonged cooking."),
    ("The 'sunshine vitamin', made in the skin when it is exposed to sunlight, is:",
     ["Vitamin D", "Vitamin A", "Vitamin K", "Vitamin E"], 0, PYQ + "It helps the absorption of calcium and phosphorus."),
    ("Which mineral is needed for the formation of haemoglobin?",
     ["Iron", "Iodine", "Sodium", "Fluorine"], 0, "Green leafy vegetables, jaggery, ragi and meat are good sources."),
    ("According to ICMR–NIN's 'My Plate for the Day', the largest share of a day's food should come from:",
     ["Vegetables and fruits together with cereals", "Fats and oils", "Sugar", "Nuts only"], 0,
     "About half the plate should be vegetables and fruits; cereals, pulses/meat, milk and nuts make up the rest."),
    ("Which food group is a good source of complete (first-class) protein?",
     ["Milk, eggs, fish and meat", "Rice and wheat only", "Sugar and jaggery", "Oils and fats"], 0,
     PYQ + "A cereal–pulse combination (e.g. rice and dal) also gives good-quality protein for vegetarians."),
    ("Iodine is added to common salt mainly to prevent:",
     ["Goitre and other iodine-deficiency disorders", "Scurvy", "Night blindness", "Rickets"], 0, "India's universal salt iodisation began under the National Goitre Control Programme (1962)."),
    ("The amount of energy a person needs depends mainly on:",
     ["Age, sex, body weight and physical activity", "Only the colour of the skin", "Only height", "The season of birth"], 0,
     "A heavy worker needs much more energy than a sedentary person."),
    ("Water is considered an essential part of the diet because it:",
     ["Regulates body temperature and carries nutrients and wastes", "Gives a lot of energy", "Is a source of protein", "Builds bones"], 0,
     PYQ + "About 60% of an adult's body weight is water."),
    ("Consider the statements:\nI. Vitamins are needed in small amounts but are essential.\nII. Excess intake of fat-soluble vitamins can be harmful because they are stored in the body.",
     I_II, 2, "Too much vitamin A or D, for example, causes toxicity (hypervitaminosis)."),
    ("Assertion (A): Pregnant and lactating women need extra protein, iron and calcium.\nReason (R): Their bodies support the growth of the baby and the production of milk.",
     AR, 0, "Iron–folic acid supplements are given under Anaemia Mukt Bharat."),
    ("Assertion (A): Polished rice is more nutritious than unpolished rice.\nReason (R): Polishing removes the bran layer of rice.",
     AR, 3, "Removing the bran loses B vitamins, fibre and minerals, so polished rice is less nutritious."),
    ("Ragi (finger millet) is especially valued in a Karnataka diet because it is rich in:",
     ["Calcium and dietary fibre", "Vitamin C", "Vitamin B12", "Iodine"], 0, PYQ + "Millets were promoted during the International Year of Millets, 2023."),
]

DEFICIENCY = [
    ("'Rickets' is caused due to the deficiency of which of the following Vitamins?",
     ["C", "D", "A", "B"], 1,
     "Vitamin D deficiency softens and bends children's bones (rickets); in adults it causes osteomalacia." + NOTE, "KRIES 2024 entrance · Q77"),
    ("Match the Vitamins in List-I with their deficiency diseases in List-II by choosing correct option:\nList-I (Vitamins)\n(a) Vitamin B12\n(b) Vitamin B1\n(c) Vitamin C\n(d) Vitamin K\nList-II (Deficiency diseases / conditions)\n(i) Haemorrhages\n(ii) Scurvy\n(iii) Beri Beri\n(iv) Pernicious Anaemia",
     ["(a)-(iv) (b)-(ii) (c)-(iii) (d)-(i)", "(a)-(ii) (b)-(iii) (c)-(i) (d)-(iv)", "(a)-(iii) (b)-(ii) (c)-(iv) (d)-(i)", "(a)-(iv) (b)-(iii) (c)-(ii) (d)-(i)"], 3,
     "B12 – pernicious anaemia; B1 (thiamine) – beriberi; C – scurvy; K – bleeding (haemorrhages), since it is needed for blood clotting." + NOTE,
     "UPSC coaching entrance 2026 (HK) · Q71"),
    ("Which of the following statements about the vitamins are correct?\n(a) Vitamin A and Vitamin B were discovered by Elmer McCollum.\n(b) Deficiency of Vitamin D causes weak bones.\n(c) Vitamin C was invented by Albert Szent-Gyorgyi.\n(d) Deficiency of Vitamin B causes scurvy.\nSelect the correct answer using the codes given below:",
     ["a, b and d", "b, c and d", "a, c and d", "a, b and c"], 3,
     "Scurvy is caused by lack of vitamin C, so (d) is wrong. McCollum identified 'fat-soluble A' and 'water-soluble B'; Szent-Györgyi isolated vitamin C (Nobel 1937)." + NOTE,
     "PGCET 2025 MCA · Q74"),
    ("Malnutrition includes:",
     ["Both undernutrition and overnutrition (overweight and obesity)", "Only undernutrition", "Only obesity", "Only vitamin deficiency"], 0,
     PYQ + "WHO: malnutrition = undernutrition (wasting, stunting, underweight), micronutrient deficiencies, and overweight/obesity."),
    ("Kwashiorkor is caused mainly by a deficiency of:",
     ["Protein (with relatively adequate calories)", "Both protein and calories severely", "Vitamin C", "Iodine"], 0,
     "Signs: swollen (oedematous) belly and feet, skin and hair changes, pot belly."),
    ("A child who is extremely thin, with 'skin and bones' appearance due to severe lack of both energy and protein, has:",
     ["Marasmus", "Kwashiorkor", "Goitre", "Scurvy"], 0, PYQ + "Both are forms of protein-energy malnutrition (PEM)."),
    ("Low height for age, showing long-term (chronic) undernutrition, is called:",
     ["Stunting", "Wasting", "Obesity", "Underweight"], 0, "Wasting = low weight for height (acute); underweight = low weight for age."),
    ("Night blindness and xerophthalmia are caused by deficiency of:",
     ["Vitamin A", "Vitamin D", "Vitamin B12", "Vitamin K"], 0, PYQ + "Bitot's spots on the eye are an early sign."),
    ("The most common nutritional deficiency disorder in India, especially among women and adolescent girls, is:",
     ["Iron-deficiency anaemia", "Scurvy", "Rickets", "Beriberi"], 0, "NFHS-5 (2019–21) found over half of Indian women aged 15–49 anaemic."),
    ("Pellagra, with the 'three Ds' – dermatitis, diarrhoea and dementia – is due to deficiency of:",
     ["Niacin (vitamin B3)", "Riboflavin (vitamin B2)", "Vitamin C", "Vitamin A"], 0, "It was common where maize (jowar) was the staple food."),
    ("Cretinism in children and goitre are caused by the deficiency of:",
     ["Iodine", "Iron", "Calcium", "Zinc"], 0, PYQ + "Iodine is needed to make thyroid hormones."),
    ("An eating disorder in which a person severely restricts food because of an intense fear of gaining weight is:",
     ["Anorexia nervosa", "Bulimia nervosa", "Binge-eating disorder", "Pica"], 0, "The person sees himself or herself as fat even when dangerously thin."),
    ("Repeated episodes of overeating followed by self-induced vomiting or use of laxatives is typical of:",
     ["Bulimia nervosa", "Anorexia nervosa", "Marasmus", "Kwashiorkor"], 0, PYQ + "Weight may stay near normal, so it is often hidden."),
    ("Craving for and eating non-food substances such as mud, chalk or paper is called:",
     ["Pica", "Bulimia", "Anorexia", "Obesity"], 0, "It is common in children and is often linked to iron deficiency."),
    ("Obesity is commonly measured by Body Mass Index (BMI), which is:",
     ["Weight (kg) ÷ height (m)²", "Height ÷ weight", "Weight × height", "Waist ÷ height"], 0,
     PYQ + "For Asian Indians, a BMI of 23–24.9 is considered overweight and 25 or more obese."),
    ("The Government of India's flagship programme to improve nutrition among children, pregnant women and lactating mothers, launched in 2018, is:",
     ["POSHAN Abhiyaan", "Swachh Bharat Mission", "Ayushman Bharat", "Jal Jeevan Mission"], 0,
     "September is observed as Poshan Maah (nutrition month); the PM POSHAN scheme gives school mid-day meals."),
    ("Consider the statements:\nI. Wasting indicates acute (recent) undernutrition.\nII. Overweight children cannot be malnourished.",
     I_II, 0, "Overweight children can still lack micronutrients – the 'double burden' of malnutrition."),
    ("Assertion (A): Scurvy is common among sailors on long voyages without fresh food.\nReason (R): Vitamin C is found mainly in fresh fruits and vegetables.",
     AR, 0, "James Lind showed in 1747 that citrus fruit cures scurvy."),
    ("Assertion (A): Anorexia nervosa is caused mainly by lack of food in poor families.\nReason (R): Anorexia nervosa is an eating disorder linked to body image and fear of weight gain.",
     AR, 3, "It is a psychological disorder, not a result of poverty."),
    ("Match the deficiency with the disease:\na. Vitamin B1  b. Vitamin D  c. Protein  d. Iodine\n1. Beriberi  2. Rickets  3. Kwashiorkor  4. Goitre",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Deficiency-disease matching is asked in almost every GK paper."),
]

TOPICS = {
    "Food for Healthy Living": [("1 · Nutrients, Dietary Requirements and Balanced Diet", DIET),
                                ("2 · Malnutrition, Deficiency Diseases and Eating Disorders", DEFICIENCY)],
}
