"""Paper 1 · Health Education · P1-HE-04 Mental Health (2 sub-topics × 20).
References: WHO fact sheet 'Mental health: strengthening our response' and WHO Constitution (1948); S. K. Mangal, Advanced
Educational Psychology (mental health, adjustment, defence mechanisms); Mental Healthcare Act 2017; MoHFW / PIB (NMHP, Tele-MANAS).
One REAL previous-year question (KSET 2023 Education) is used word for word; KEA has published no key for it, so its answer is
worked out by ExamSim and says so. Explanations starting "PYQ pattern" follow themes that recur in KPSC / KEA / TET papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KPSC / KEA / TET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

MEANING = [
    # --- real previous-year question ---
    ("Identify the correct statements regarding mental health:\nI. It involves a state of being free from psychological disorders.\nII. It involves a state of emotional well-being.\nIII. It requires the ability to cope with stress.\nIV. It is influenced by social and environmental factors.\nV. It is merely an absence of mental illness.",
     ["I, II and III only", "II, III and IV only", "I, II, III and IV only", "I, II and V only"], 2,
     "Mental health is a positive state of well-being, not merely the absence of illness, so V is wrong." + NOTE,
     "KSET 2023 Education · Q2"),
    # --- new questions ---
    ("WHO describes mental health as a state of well-being in which a person:",
     ["Realises his or her abilities, can cope with the normal stresses of life, can work productively and contributes to the community", "Never feels sad or angry", "Has a high IQ", "Is free from all physical disease"], 0,
     PYQ + "It is more than the absence of mental disorder."),
    ("According to the WHO Constitution (1948), health is:",
     ["A state of complete physical, mental and social well-being and not merely the absence of disease or infirmity", "Only the absence of disease", "Only physical fitness", "Only mental peace"], 0,
     PYQ + "One of the most frequently asked definitions."),
    ("The mental hygiene movement was started by Clifford Beers, whose book about his own illness was:",
     ["A Mind That Found Itself (1908)", "The Interpretation of Dreams", "Emile", "Walden Two"], 0,
     PYQ + "Mental hygiene aims at preserving mental health and preventing mental disorders."),
    ("Which is a characteristic of a mentally healthy person?",
     ["Accepts himself and others, sees reality as it is, and adjusts to changing situations", "Avoids all responsibility", "Is never anxious in any situation", "Depends entirely on others for decisions"], 0,
     "Emotional maturity and good relationships are other signs."),
    ("In psychology, 'adjustment' means:",
     ["A harmonious relationship between a person's needs and the demands of the environment", "Changing one's address", "Moving furniture", "Always obeying others"], 0,
     "Maladjustment shows up as anxiety, aggression or withdrawal."),
    ("The 'General Adaptation Syndrome' of stress, with the stages alarm, resistance and exhaustion, was described by:",
     ["Hans Selye", "Sigmund Freud", "Carl Rogers", "Kurt Lewin"], 0,
     PYQ + "Selye also distinguished eustress (helpful stress) from distress."),
    ("A conflict in which a person must choose between two equally attractive goals is called:",
     ["Approach–approach conflict", "Avoidance–avoidance conflict", "Approach–avoidance conflict", "Double approach–avoidance conflict"], 0,
     PYQ + "Kurt Lewin classified conflicts this way."),
    ("Frustration arises when:",
     ["A person's effort to reach a goal is blocked", "A goal is reached easily", "There is no goal", "A person sleeps well"], 0,
     "Repeated frustration can lead to aggression or withdrawal."),
    ("A student who fails an exam says, 'The paper was unfair anyway.' This defence mechanism is:",
     ["Rationalisation", "Sublimation", "Regression", "Identification"], 0,
     PYQ + "It gives a reasonable-sounding excuse ('sour grapes')."),
    ("Directing an unacceptable impulse, such as aggression, into a socially valued activity such as boxing or debating is:",
     ["Sublimation", "Projection", "Repression", "Denial"], 0,
     PYQ + "Freud considered sublimation the healthiest defence mechanism."),
    ("Attributing one's own unacceptable feelings or faults to others is called:",
     ["Projection", "Compensation", "Displacement", "Regression"], 0,
     "e.g. a dishonest person thinking everyone cheats."),
    ("A man scolded by his boss comes home and shouts at his child. This is:",
     ["Displacement", "Sublimation", "Rationalisation", "Identification"], 0,
     "The feeling is shifted to a safer target."),
    ("A seven-year-old starts sucking his thumb again after a baby sister is born. This is:",
     ["Regression", "Projection", "Compensation", "Sublimation"], 0,
     "Returning to behaviour of an earlier stage."),
    ("World Mental Health Day is observed every year on:",
     ["10 October", "7 April", "5 June", "21 June"], 0,
     PYQ + "7 April is World Health Day; 21 June is International Yoga Day."),
    ("India's Mental Healthcare Act, 2017:",
     ["Gives a right to mental healthcare and effectively decriminalises attempted suicide", "Bans all psychiatric treatment", "Applies only to children", "Created NIMHANS"], 0,
     PYQ + "The National Mental Health Programme began in 1982; Tele-MANAS (helpline 14416) started in 2022."),
    ("A teacher can best promote pupils' mental health by:",
     ["Creating a friendly, fearless classroom, praising effort and guiding pupils with problems", "Using ridicule to improve discipline", "Comparing pupils openly with toppers", "Ignoring emotional problems"], 0,
     "The school is second only to the home in shaping mental health."),
    ("Match the defence mechanism with the example:\na. Rationalisation  b. Projection  c. Displacement  d. Compensation\n1. A weak student excels in sports  2. Shouting at a younger brother after a scolding  3. Blaming others for one's own dishonesty  4. 'The grapes are sour anyway'",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Defence-mechanism matching is common in TET and KSET Education papers."),
    ("Consider the statements:\nI. Mental health is influenced by heredity, family, school and society.\nII. A mentally healthy person never feels stress.\nWhich is/are correct?",
     I_II, 0, "Mentally healthy people feel stress but cope with it."),
    ("Assertion (A): Defence mechanisms protect a person from anxiety.\nReason (R): They distort or deny reality, usually without the person being aware of it.",
     AR, 0, "Freud and Anna Freud described them as unconscious processes; overuse becomes unhealthy."),
]

DISORDERS = [
    ("The main difference between psychosis and neurosis is that in psychosis:",
     ["The person loses contact with reality (e.g. hallucinations, delusions)", "The person keeps full insight into the problem", "There are no symptoms", "Only physical illness is present"], 0,
     PYQ + "In neurosis (anxiety-based disorders) the person keeps contact with reality."),
    ("Hearing voices that are not there is an example of a:",
     ["Hallucination", "Delusion", "Phobia", "Obsession"], 0,
     "A delusion is a fixed false belief."),
    ("Schizophrenia is a mental disorder marked mainly by:",
     ["Disturbed thinking, hallucinations, delusions and withdrawal from reality", "Fear of heights", "Excessive hand washing only", "Short attention span in children"], 0,
     PYQ + "It is a psychotic disorder."),
    ("Persistent sadness, loss of interest, poor sleep and feelings of worthlessness are typical of:",
     ["Depression", "Mania", "Phobia", "Dyslexia"], 0,
     "Depression is one of the leading causes of disability worldwide (WHO)."),
    ("A disorder in which periods of extreme elation (mania) alternate with periods of depression is:",
     ["Bipolar disorder", "Schizophrenia", "Phobia", "Autism"], 0,
     "It was earlier called manic-depressive psychosis."),
    ("An intense, irrational fear of a specific object or situation is a:",
     ["Phobia", "Delusion", "Hallucination", "Mania"], 0,
     PYQ + "e.g. acrophobia (heights), claustrophobia (closed spaces)."),
    ("Repeated unwanted thoughts with urges to perform acts such as checking or hand-washing again and again indicate:",
     ["Obsessive–compulsive disorder (OCD)", "Bipolar disorder", "Schizophrenia", "Amnesia"], 0,
     "Obsessions are thoughts; compulsions are acts."),
    ("A child who is constantly restless, impulsive and unable to sustain attention may have:",
     ["ADHD (Attention-Deficit / Hyperactivity Disorder)", "Dyslexia", "Acrophobia", "Bipolar disorder"], 0,
     "Teachers should refer such children for assessment and use structured routines."),
    ("Early detection and prompt treatment of a mental disorder is which level of prevention?",
     ["Secondary prevention", "Primary prevention", "Tertiary prevention", "No prevention"], 0,
     PYQ + "Primary prevention stops a disorder from arising; tertiary prevention is rehabilitation."),
    ("Client-centred (person-centred) therapy was developed by:",
     ["Carl Rogers", "Sigmund Freud", "Aaron Beck", "B. F. Skinner"], 0,
     PYQ + "It stresses empathy, genuineness and unconditional positive regard."),
    ("Psychoanalysis, using free association and dream analysis, was developed by:",
     ["Sigmund Freud", "Carl Rogers", "Albert Ellis", "Ivan Pavlov"], 0,
     PYQ + "It seeks to bring repressed conflicts into awareness."),
    ("Cognitive behaviour therapy (CBT) mainly works by:",
     ["Identifying and changing faulty thinking patterns and behaviours", "Hypnotising the patient", "Surgery on the brain", "Only giving medicines"], 0,
     "Aaron Beck developed cognitive therapy; Albert Ellis developed REBT."),
    ("The National Institute of Mental Health and Neuro-Sciences (NIMHANS) is located in:",
     ["Bengaluru", "New Delhi", "Chennai", "Pune"], 0,
     PYQ + "It is an Institute of National Importance."),
    ("Which of these helps promote mental health in daily life?",
     ["Regular exercise, yoga and meditation, enough sleep and supportive relationships", "Isolation from friends", "Skipping meals", "Using alcohol to relax"], 0,
     "WHO also stresses avoiding harmful use of alcohol and drugs."),
    ("Dependence on alcohol or drugs that harms a person's health and social life is called:",
     ["Substance use disorder (addiction)", "Sublimation", "Phobia", "Schizophrenia"], 0,
     "Tobacco, alcohol and drug use are major risks for mental and physical health."),
    ("Match the phobia with its object of fear:\na. Acrophobia  b. Claustrophobia  c. Hydrophobia  d. Agoraphobia\n1. Open or crowded public places  2. Water  3. Closed spaces  4. Heights",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Phobia matching appears in GK and Education papers."),
    ("Match the therapy with its originator:\na. Psychoanalysis  b. Client-centred therapy  c. Cognitive therapy  d. Behaviour therapy (systematic desensitisation)\n1. Joseph Wolpe  2. Aaron Beck  3. Carl Rogers  4. Sigmund Freud",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     "Systematic desensitisation is widely used to treat phobias."),
    ("Consider the statements:\nI. In psychosis, the person often loses contact with reality.\nII. Mental illness is always caused by weak will power.\nWhich is/are correct?",
     I_II, 0, "Mental illnesses have biological, psychological and social causes."),
    ("Assertion (A): Stigma prevents many people from seeking help for mental illness.\nReason (R): Mental illness is often wrongly seen as a personal weakness or something shameful.",
     AR, 0, "Awareness campaigns aim to reduce this stigma."),
    ("Assertion (A): Electroconvulsive therapy (ECT) is the first treatment for every mild mental problem.\nReason (R): ECT is used in some cases of severe depression that do not respond to other treatment.",
     AR, 3, "ECT is reserved for severe cases, so A is false."),
]

TOPICS = {
    "Mental Health": [("1 · Meaning, Characteristics, Stress and Defence Mechanisms", MEANING),
                      ("2 · Mental Disorders, Prevention and Treatment", DISORDERS)],
}
