"""Paper 1 · Educational Psychology · P1-PSY-08 Gifted, Backward and Creative Children (2 sub-topics × 20).
References: S. K. Mangal, Advanced Educational Psychology; Cyril Burt, The Backward Child (1937); J. S. Renzulli's three-ring
conception of giftedness; J. P. Guilford; E. P. Torrance; Graham Wallas, The Art of Thought (1926); NPE 1986; DSERT D.El.Ed. texts.
Real previous-year questions (exact wording, `source` = paper and question number) come from the KSET Education papers of
2023, 2024 and 2025; KEA has not published keys for them, so their answers are worked out by ExamSim."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KSET / GPSTR / KARTET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

GIFTED_BACKWARD = [
    # --- real previous-year question ---
    ("Which situations may lead to educational backwardness?\nI. Sensory impairment\nII. Motor disability\nIII. Long diseases and health problems",
     ["I and II only", "II and III only", "I and III only", "I, II and III"], 3,
     "Physical causes of backwardness include defects of sight or hearing, motor disability and long illness that keeps a child away from school." + NOTE,
     "KSET 2023 Education · Q73"),
    # --- new questions ---
    ("On Terman's and Wechsler's scales, children are usually called gifted when their IQ is about:",
     ["130 or above (Terman used 140+)", "90 to 110", "70 to 85", "Below 70"], 0,
     PYQ + "Terman's 'Genetic Studies of Genius' (from 1921) followed over 1,500 children with IQs of about 135–140 and above."),
    ("Renzulli's 'three-ring' conception of giftedness consists of:",
     ["Above-average ability, creativity and task commitment", "High IQ, wealth and good health", "Memory, speed and obedience", "Reading, writing and arithmetic"], 0,
     PYQ + "Giftedness lies where the three rings overlap."),
    ("Which is a typical characteristic of gifted children?",
     ["Learn quickly, show deep curiosity and a wide vocabulary, and may get bored by routine work", "Need many repetitions to learn", "Always obey without questioning", "Avoid books and puzzles"], 0,
     "Boredom can make some gifted children restless or underachieving."),
    ("Allowing a gifted child to skip a class or finish the syllabus faster is called:",
     ["Acceleration", "Enrichment", "Remedial teaching", "Detention"], 0,
     PYQ + "Other forms: early admission, grade skipping, subject acceleration."),
    ("Providing a gifted child with broader and deeper learning experiences within the regular class (projects, extra reading) is called:",
     ["Enrichment", "Acceleration", "Retention", "Segregation"], 0,
     PYQ + "Horizontal enrichment broadens; vertical enrichment goes deeper or more advanced."),
    ("Jawahar Navodaya Vidyalayas were set up under the National Policy on Education 1986 mainly for:",
     ["Talented children, especially from rural areas", "Children with severe disabilities only", "Only children of government employees", "Adult learners"], 0,
     PYQ + "They are fully residential, co-educational schools."),
    ("Cyril Burt described a backward child as one who, in the middle of the school career, is unable to do the work of:",
     ["The class next below that which is normal for his age", "The class two years above his age", "Any class at all", "His own class in one subject only"], 0,
     PYQ + "From The Backward Child (1937)."),
    ("Educational backwardness is usually indicated by an Educational Quotient (EQ) below:",
     ["85", "100", "120", "140"], 0,
     PYQ + "EQ = (Educational Age ÷ Chronological Age) × 100."),
    ("The Accomplishment (Achievement) Quotient is calculated as:",
     ["(Educational Age ÷ Mental Age) × 100", "(Mental Age ÷ Chronological Age) × 100", "(Chronological Age ÷ Educational Age) × 100", "Educational Age − Mental Age"], 0,
     "An AQ below 100 means a pupil is achieving less than his ability allows."),
    ("A child whose achievement is well below what his intelligence would predict is called a(n):",
     ["Underachiever", "Overachiever", "Gifted achiever", "Prodigy"], 0,
     "Even gifted children can be underachievers."),
    ("Children with IQ roughly between 75/80 and 90, who learn more slowly than average, are usually called:",
     ["Slow learners", "Gifted", "Superior", "Geniuses"], 0,
     PYQ + "They need more time, concrete examples and repetition, not a separate school."),
    ("Which is NOT a usual cause of educational backwardness?",
     ["High intelligence with suitable teaching", "Poor home environment and poverty", "Defects of sight or hearing", "Frequent absence and faulty teaching methods"], 0,
     "Causes may be intellectual, physical, emotional, social or educational."),
    ("Teaching planned specially to correct the learning difficulties found by a diagnostic test is called:",
     ["Remedial teaching", "Enrichment", "Acceleration", "Programmed instruction only"], 0,
     PYQ + "Diagnosis comes first, then remedy."),
    ("Match the term with its meaning:\na. Acceleration  b. Enrichment  c. Remedial teaching  d. Underachiever\n1. Performs below his ability  2. Teaching to correct diagnosed weaknesses  3. Broader, deeper learning in the same class  4. Faster progress through the curriculum",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Exceptional-children terminology is matched in KSET Education papers."),
    ("Consider the statements:\nI. A gifted child can also be an underachiever.\nII. Every backward child has low intelligence.\nWhich is/are correct?",
     I_II, 0, "Backwardness can arise from physical, emotional or social causes even with normal intelligence."),
    ("Consider the statements:\nI. Educational Quotient compares educational age with chronological age.\nII. Accomplishment Quotient compares educational age with mental age.\nWhich is/are correct?",
     I_II, 2, "EQ = EA/CA × 100; AQ = EA/MA × 100."),
    ("Assertion (A): Gifted children need special educational provision.\nReason (R): Ordinary class work may not challenge them, leading to boredom and wasted talent.",
     AR, 0, "Enrichment and acceleration meet this need."),
    ("Assertion (A): Backward children should be labelled and punished to make them work harder.\nReason (R): Backwardness often has causes such as poor health, poverty or emotional problems.",
     AR, 3, "Diagnosis and remedial help, not labelling or punishment, are recommended; R is true."),
    ("The first step in helping a backward child is to:",
     ["Diagnose the causes of backwardness", "Promote the child to a higher class", "Send the child home", "Give the child more homework without guidance"], 0,
     "Diagnostic tests, health check-ups and home visits help identify causes."),
]

CREATIVE = [
    # --- real previous-year questions ---
    ("Identify the correct sequence of creative problem-solving",
     ["Incubation, Preparation, Verification, Illumination", "Preparation, Incubation, Illumination, Verification", "Illumination, Incubation, Preparation, Verification", "Preparation, Illumination, Incubation, Verification"], 1,
     "Graham Wallas (1926): preparation → incubation → illumination → verification." + NOTE,
     "KSET 2024 Education · Q24"),
    ("Given below are two statements, one labelled as Assertion (A) and other labelled as Reason (R).\nAssertion (A): Creativity is innate as well as acquired\nReason (R): Creativity is a means as well as an end in itself\nExamine the statements and choose the correct answer.",
     ["Both (A) and (R) are true but (R) is not the correct explanation of (A)", "Both (A) and (R) are true and (R) is the correct explanation of (A)", "(A) is true but (R) is false", "(A) is false but (R) is true"], 0,
     "Creative potential is partly inborn and can be nurtured; that it is both a means and an end does not explain where it comes from." + NOTE,
     "KSET 2025 Education · Q29"),
    # --- new questions ---
    ("J. P. Guilford linked creativity mainly with:",
     ["Divergent thinking – producing many different answers to an open problem", "Convergent thinking – finding the one correct answer", "Rote memory", "Reaction time"], 0,
     PYQ + "Convergent thinking is what most intelligence tests measure."),
    ("The four components of divergent (creative) thinking are:",
     ["Fluency, flexibility, originality and elaboration", "Speed, accuracy, memory and attention", "Reading, writing, listening and speaking", "Knowledge, comprehension, application and analysis"], 0,
     PYQ + "Used in scoring Torrance's tests."),
    ("In a test of creativity, the number of relevant ideas a child produces is a measure of:",
     ["Fluency", "Flexibility", "Originality", "Elaboration"], 0,
     "Flexibility = variety of categories; originality = rarity; elaboration = detail."),
    ("Unusual, rare responses given by very few people are scored as:",
     ["Originality", "Fluency", "Flexibility", "Elaboration"], 0,
     PYQ + "Common answers earn fluency but not originality."),
    ("The Torrance Tests of Creative Thinking (TTCT) were developed by:",
     ["E. Paul Torrance", "Alfred Binet", "Charles Spearman", "David Wechsler"], 0,
     PYQ + "They have verbal and figural forms."),
    ("An Indian test of creativity with verbal and non-verbal forms was developed by:",
     ["Baqer Mehdi", "C. M. Bhatia", "S. M. Mohsin", "M. C. Joshi"], 0,
     PYQ + "B. K. Passi also constructed a test of creativity."),
    ("Brainstorming as a technique for generating ideas was introduced by:",
     ["Alex Osborn", "B. F. Skinner", "Jean Piaget", "Lev Vygotsky"], 0,
     PYQ + "Its rule: no criticism while ideas are being produced."),
    ("In Wallas's model, the stage in which the mind works on the problem unconsciously, while the person is occupied with something else, is:",
     ["Incubation", "Preparation", "Illumination", "Verification"], 0,
     "Illumination is the sudden 'Aha!' insight that follows."),
    ("The relation between intelligence and creativity is best described as:",
     ["Positively related up to a point, but high intelligence does not guarantee creativity", "Identical – they are the same ability", "Always negatively related", "Completely unrelated in every case"], 0,
     "Getzels and Jackson (1962) found many highly creative pupils who were not the highest in IQ."),
    ("Which is a typical characteristic of creative children?",
     ["Curiosity, independence of thought, tolerance of ambiguity and a sense of humour", "Strict conformity to rules", "Dislike of new experiences", "Preference for only one right answer"], 0,
     PYQ + "They often ask unusual questions."),
    ("A teacher can best foster creativity by:",
     ["Asking open-ended questions and accepting unusual answers without ridicule", "Insisting on one standard answer", "Discouraging questions", "Rewarding only rote memorisation"], 0,
     PYQ + "A free, non-threatening climate encourages creative thinking."),
    ("Which question is most likely to call for divergent thinking?",
     ["List as many uses of a brick as you can.", "What is 12 × 8?", "Who wrote the national anthem?", "What is the capital of Karnataka?"], 0,
     "Unusual-uses tasks are standard creativity items."),
    ("Match the stage of creative thinking (Wallas) with its description:\na. Preparation  b. Incubation  c. Illumination  d. Verification\n1. Testing and refining the idea  2. Sudden insight  3. Unconscious mulling over  4. Gathering information about the problem",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Wallas's stages appear in KSET Education papers."),
    ("Consider the statements:\nI. Creativity is linked with divergent thinking.\nII. Intelligence tests mainly measure divergent thinking.\nWhich is/are correct?",
     I_II, 0, "IQ tests mainly measure convergent thinking."),
    ("Consider the statements:\nI. Brainstorming postpones criticism of ideas.\nII. Creativity can be developed through suitable training and environment.\nWhich is/are correct?",
     I_II, 2, "Both are widely accepted."),
    ("Assertion (A): Fear of ridicule can block a child's creativity.\nReason (R): Creative ideas are often unusual and may at first seem odd to others.",
     AR, 0, "So teachers should welcome unusual ideas."),
    ("Assertion (A): Every child with a high IQ is highly creative.\nReason (R): Creativity requires divergent thinking, which IQ tests do not fully measure.",
     AR, 3, "High IQ does not guarantee creativity, so A is false; R is true."),
    ("A 'creative child' as distinct from a 'gifted child' is identified mainly by:",
     ["Originality and novelty of ideas and products", "A high score on a vocabulary test", "Speed of copying notes", "Obedience in class"], 0,
     "Giftedness is often defined by high general ability; creativity by original production."),
]

TOPICS = {
    "Gifted, Backward and Creative Children": [("1 · Gifted and Backward Children", GIFTED_BACKWARD),
                                               ("2 · Creativity and Creative Children", CREATIVE)],
}
