"""Paper 1 · Educational Psychology · P1-PSY-11 Motivation (2 sub-topics × 20).
Coverage (planner): meaning, types, importance, techniques, Maslow's theory.
References: S. K. Mangal, Advanced Educational Psychology; Woolfolk, Educational Psychology; A. H. Maslow, Motivation and
Personality (1954); McClelland, The Achieving Society; DSERT D.El.Ed. psychology texts. Two REAL previous-year questions come from
the GFGC 2021 Education paper (no published key; answers worked out by ExamSim). The rest are "PYQ pattern" questions on themes
common in KSET Education / TET / GPSTR papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KSET Education / TET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

MEANING = [
    ("The word 'motivation' is derived from the Latin word 'movere', which means:",
     ["To move", "To learn", "To think", "To remember"], 0, PYQ + "Motivation is the process that arouses, directs and sustains behaviour."),
    ("Motivation is best described as:",
     ["An inner force that energises, directs and sustains behaviour towards a goal", "A permanent change in behaviour due to experience",
      "The ability to solve problems", "A fixed inherited trait"], 0, "The second option is a definition of learning."),
    ("The correct sequence in the motivation cycle is:",
     ["Need → Drive → Incentive (goal) → Reduction of drive", "Drive → Need → Goal → Incentive", "Goal → Need → Drive → Satisfaction", "Incentive → Drive → Need → Goal"], 0,
     PYQ + "A need creates a drive (tension), which pushes the person towards an incentive that satisfies it."),
    ("Hunger, thirst and the need for sleep are examples of:",
     ["Primary (biological) motives", "Social motives", "Personal motives", "Acquired motives"], 0, "Social / acquired motives include achievement, affiliation and power."),
    ("A pupil studies because he enjoys the subject itself. This is:",
     ["Intrinsic motivation", "Extrinsic motivation", "Negative motivation", "Physiological motivation"], 0,
     PYQ + "Intrinsic motivation comes from within – interest, curiosity, satisfaction."),
    ("A student studies hard to get a prize and the praise of the teacher. This is:",
     ["Extrinsic motivation", "Intrinsic motivation", "Amotivation", "Instinct"], 0, "Rewards, marks, praise and punishment are external incentives."),
    ("Which type of motivation is generally considered more lasting and desirable in learning?",
     ["Intrinsic motivation", "Extrinsic motivation through punishment", "Fear of failure", "Competition alone"], 0,
     PYQ + "Extrinsic rewards are useful to start an activity but should lead to intrinsic interest."),
    ("The need to excel and to do things better than before was studied by:",
     ["David McClelland (need for achievement)", "Ivan Pavlov", "Jean Piaget", "Wolfgang Köhler"], 0,
     "McClelland and Atkinson studied n-Ach (achievement), n-Aff (affiliation) and n-Pow (power)."),
    ("The level of performance a person expects to reach in a task is called the:",
     ["Level of aspiration", "Intelligence quotient", "Reaction time", "Span of attention"], 0,
     PYQ + "Success tends to raise it and failure to lower it (Hoppe, Lewin)."),
    ("According to the Yerkes–Dodson law, performance on a task is best at:",
     ["A moderate level of arousal", "The lowest level of arousal", "The highest level of arousal", "Any level of arousal"], 0,
     "For difficult tasks the best arousal is lower; for easy tasks it is higher."),
    ("Which theory holds that people are motivated to reduce the tension caused by biological needs?",
     ["Drive-reduction theory (Clark Hull)", "Insight theory", "Field theory", "Cognitive-dissonance theory"], 0,
     PYQ + "The aim is to restore homeostasis."),
    ("Behaviour that is motivated by what a person believes about his chances of success and the value of the goal is explained by:",
     ["Expectancy–value theory", "Instinct theory", "Trial-and-error theory", "Classical conditioning"], 0,
     "Motivation = Expectancy × Value (Atkinson, Vroom)."),
    ("Weiner's attribution theory says that students who attribute failure to lack of effort (rather than lack of ability) tend to:",
     ["Try harder next time", "Give up", "Blame the teacher always", "Lose interest permanently"], 0,
     PYQ + "Effort is internal, unstable and controllable, so it can be changed."),
    ("Repeated failure that makes a pupil believe that nothing he does will succeed leads to:",
     ["Learned helplessness", "Self-actualisation", "Sublimation", "Insight"], 0, "The term comes from Martin Seligman's experiments."),
    ("Curiosity and the desire to explore are examples of:",
     ["Intrinsic (psychological) motives", "Biological drives such as hunger", "Extrinsic rewards", "Reflexes"], 0, "They are strong in young children."),
    ("Consider the statements:\nI. Motivation directs behaviour towards a goal.\nII. Motivation has no effect on attention or learning.",
     I_II, 0, "Motivated pupils pay attention and learn better, so II is false."),
    ("Assertion (A): Motivation is called the 'heart of the learning process'.\nReason (R): Without motivation a learner does not attend, persist or practise.",
     AR, 0, "Hence the teacher's first task is to motivate the class."),
    ("Assertion (A): Extrinsic rewards always increase intrinsic interest.\nReason (R): Rewards are external incentives.",
     AR, 3, "Giving rewards for an activity already enjoyed can lower intrinsic interest (the 'overjustification effect')."),
    ("Which of these is an example of negative motivation?",
     ["Threat of punishment or fear of failure", "Praise", "A prize", "Interest in the subject"], 0,
     PYQ + "Negative motivation works by fear; it is less desirable than positive motivation."),
    ("Kurt Lewin's 'field theory' explains motivation in terms of:",
     ["Forces in the person's life space – valences of goals and barriers", "Conditioned reflexes", "Instincts only", "Heredity"], 0,
     "Positive valence attracts; negative valence repels."),
]

MASLOW_TECH = [
    ("According to Maslow, the higher level needs are\nI. Intellectual achievement\nII. Aesthetic appreciation\nIII. Esteem needs\nIV. Self-actualization needs",
     ["I, II and III only", "I, II and IV only", "II, III and IV only", "I, III and IV only"], 1,
     "In Maslow's extended hierarchy the growth (being) needs are cognitive (knowledge / intellectual achievement), aesthetic and self-actualisation; esteem is still a deficiency need." + NOTE,
     "GFGC 2021 Education · Q35"),
    ("The correct sequence according to Maslow's hierarchy of human needs is\nI. Esteem needs\nII. Safety needs\nIII. Love & Belongingness\nIV. Self-actualization",
     ["I, II, III, IV", "II, III, I, IV", "III, II, IV, I", "IV, I, II, III"], 1,
     "Physiological → safety → love and belonging → esteem → self-actualisation." + NOTE, "GFGC 2021 Education · Q37"),
    ("The need at the base of Maslow's hierarchy is:",
     ["Physiological needs", "Safety needs", "Esteem needs", "Self-actualisation"], 0, PYQ + "Food, water, sleep and shelter must be met first."),
    ("The highest need in Maslow's original five-level hierarchy is:",
     ["Self-actualisation", "Esteem", "Belongingness", "Safety"], 0, "Self-actualisation is 'to become everything one is capable of becoming'."),
    ("Maslow called the lower four needs 'deficiency needs' because:",
     ["Their lack creates tension that motivates the person until they are met", "They are not important",
      "They are learnt in school", "They never arise in adults"], 0, "Self-actualisation is a growth (being) need."),
    ("Maslow's theory is classified as a:",
     ["Humanistic theory of motivation", "Behaviourist theory", "Psychoanalytic theory", "Cognitive-developmental theory"], 0,
     PYQ + "Humanistic psychology (Maslow, Carl Rogers) is called the 'third force'."),
    ("A hungry child cannot concentrate on the lesson. In Maslow's terms this shows that:",
     ["Lower needs must be met before higher needs motivate behaviour", "Self-actualisation comes first",
      "Esteem needs are the most basic", "Needs have no order"], 0, "This is one reason for the mid-day meal scheme."),
    ("Which of the following is a characteristic of a self-actualised person, according to Maslow?",
     ["Acceptance of self and others, creativity and peak experiences", "Constant need for approval",
      "Fear of new experiences", "Dependence on others for decisions"], 0, PYQ + "Maslow studied people such as Lincoln and Einstein."),
    ("Herzberg's two-factor theory divides work factors into:",
     ["Hygiene factors and motivators", "Needs and drives", "Rewards and punishments", "Instincts and habits"], 0,
     "Hygiene factors (salary, conditions) prevent dissatisfaction; motivators (achievement, recognition) give satisfaction."),
    ("Which of the following is the BEST technique to motivate pupils in the classroom?",
     ["Linking the lesson to pupils' interests and real life", "Frequent punishment", "Long lectures without activity", "Comparing pupils with each other publicly"], 0,
     PYQ + "Use of interest, curiosity, activity and success motivates pupils."),
    ("Telling pupils clearly what they will learn and why it is useful motivates them because:",
     ["Knowing the goal gives direction and purpose to learning", "It shortens the period", "It avoids questions", "It replaces practice"], 0,
     "Clear goals and knowledge of progress are basic motivational techniques."),
    ("Giving pupils immediate knowledge of their results (feedback) motivates them because:",
     ["They see their progress and can correct mistakes", "It frightens them", "It reduces competition", "It makes the test easy"], 0, PYQ + "Feedback is also called knowledge of results."),
    ("Which of the following is NOT a sound way to use praise in the classroom?",
     ["Praising everything a pupil does, whether or not it deserves praise", "Praising specific effort and improvement",
      "Praising sincerely and soon after the work", "Praising pupils of all abilities for genuine progress"], 0,
     "Indiscriminate praise loses its value."),
    ("Healthy competition motivates pupils best when it is:",
     ["Group competition or competition with one's own past record", "Cut-throat rivalry between individuals",
      "Only for the brightest pupils", "Always linked to punishment"], 0, PYQ + "Competing with one's own past record avoids discouraging weaker pupils."),
    ("A teacher sets tasks that are challenging but achievable for each pupil. This mainly helps to:",
     ["Give experience of success and raise the level of aspiration", "Make pupils lazy", "Increase fear of failure", "Reduce attention"], 0,
     "Success breeds success."),
    ("Consider the statements:\nI. In Maslow's hierarchy, safety needs come before love and belonging.\nII. Esteem needs come after self-actualisation.",
     I_II, 0, "Esteem comes before self-actualisation."),
    ("Assertion (A): A child from a disturbed home may not show interest in learning.\nReason (R): Unmet safety and belongingness needs block higher needs, according to Maslow.",
     AR, 0, "Teachers should provide a secure, accepting classroom."),
    ("Assertion (A): Punishment is the most effective long-term motivator.\nReason (R): Punishment can stop undesirable behaviour for the moment.",
     AR, 3, "Punishment suppresses behaviour temporarily and can create fear and dislike for the subject."),
    ("Match the theorist with the idea:\na. Maslow  b. McClelland  c. Hull  d. Weiner\n1. Hierarchy of needs  2. Need for achievement  3. Drive reduction  4. Attribution of success and failure",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Theorist matching is very common in KSET Education."),
    ("In the expanded version of Maslow's hierarchy, the need above self-actualisation is:",
     ["Transcendence (helping others reach their potential)", "Physiological", "Safety", "Esteem"], 0,
     "The expanded hierarchy has eight levels: physiological, safety, belonging, esteem, cognitive, aesthetic, self-actualisation, transcendence."),
]

TOPICS = {
    "Motivation": [("1 · Meaning, Types and Theories of Motivation", MEANING),
                   ("2 · Maslow's Hierarchy and Techniques of Motivating Pupils", MASLOW_TECH)],
}
