"""Paper 1 · Educational Psychology · P1-PSY-09 Emotional Intelligence (2 sub-topics × 20).
Coverage (planner): meaning, importance, dimensions (Daniel Goleman's five).
References: Daniel Goleman, Emotional Intelligence (1995) and Working with Emotional Intelligence (1998); Salovey & Mayer (1990);
Reuven Bar-On's EQ-i; S. K. Mangal, Advanced Educational Psychology; CASEL framework for social and emotional learning.
Real previous-year questions (exact wording, `source` = paper and question number) come from the KSET Education papers of
2023, 2024 and 2025; KEA has not published keys for them, so their answers are worked out by ExamSim."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KSET / GPSTR / KARTET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

MEANING_MODELS = [
    # --- real previous-year questions ---
    ("Emotional Intelligence does not involve:",
     ["the ability to carry out accurate reasoning about emotions.", "the ability to constantly neglect emotions.", "the ability to accurately perceive, appraise and express emotions.", "the ability to use emotions and emotional knowledge to enhance thought."], 1,
     "EI means perceiving, using, understanding and managing emotions – not ignoring them." + NOTE,
     "KSET 2023 Education · Q9"),
    ("Which among the following perspectives on emotional intelligence and the proposers of the model is/are correctly matched?\n(i) Goleman - EI Performance Model\n(ii) Bar-On - Competencies Model\n(iii) Mayer, Salovey and Caruso - Ability Model",
     ["(i) only", "(i) and (ii) only", "(ii) and (iii) only", "(i), (ii) and (iii)"], 3,
     "Goleman's mixed/performance model, Bar-On's emotional-social competencies model and the Mayer–Salovey–Caruso ability model are all correctly paired." + NOTE,
     "KSET 2024 Education · Q29"),
    ("The other name of social competence is",
     ["Cognitive competence", "Interpersonal competence", "Emotional competence", "Constructive competence"], 1,
     "Social competence is the ability to interact effectively with others – interpersonal competence." + NOTE,
     "KSET 2025 Education · Q23"),
    # --- new questions ---
    ("The term 'emotional intelligence' was first formally defined in 1990 by:",
     ["Peter Salovey and John Mayer", "Daniel Goleman", "Howard Gardner", "Alfred Binet"], 0,
     PYQ + "They defined it as the ability to monitor one's own and others' feelings and use them to guide thinking and action."),
    ("Emotional intelligence became widely popular through the 1995 book 'Emotional Intelligence: Why It Can Matter More Than IQ' by:",
     ["Daniel Goleman", "Reuven Bar-On", "Robert Sternberg", "Carl Rogers"], 0,
     PYQ + "Goleman was a psychologist and science journalist."),
    ("The four branches of the Mayer–Salovey ability model of EI are:",
     ["Perceiving, using, understanding and managing emotions", "Self-awareness, self-regulation, motivation and empathy", "Knowledge, comprehension, application and analysis", "Fluency, flexibility, originality and elaboration"], 0,
     PYQ + "It is measured by the MSCEIT test."),
    ("The term 'EQ' (emotional quotient) and the EQ-i inventory are associated with:",
     ["Reuven Bar-On", "Charles Spearman", "Lewis Terman", "E. L. Thorndike"], 0,
     PYQ + "Bar-On's model stresses emotional and social competencies."),
    ("The MSCEIT (Mayer-Salovey-Caruso Emotional Intelligence Test) measures EI as a(n):",
     ["Ability, using performance tasks", "Personality trait by self-report only", "IQ score", "Physical skill"], 0,
     "Self-report measures, such as Bar-On's EQ-i, are also used."),
    ("Emotional intelligence is best defined as the ability to:",
     ["Recognise, understand and manage one's own emotions and those of others", "Solve mathematical problems quickly", "Memorise facts", "Hide all feelings"], 0,
     PYQ + "It includes both intrapersonal and interpersonal abilities."),
    ("Gardner's intelligences most closely related to emotional intelligence are:",
     ["Intrapersonal and interpersonal intelligence", "Logical-mathematical and spatial intelligence", "Musical and naturalist intelligence", "Bodily-kinaesthetic and linguistic intelligence"], 0,
     "Goleman built on these 'personal intelligences'."),
    ("Compared with IQ, emotional intelligence:",
     ["Can be developed and improved through learning and practice", "Is completely fixed at birth", "Cannot be measured in any way", "Has no effect on success"], 0,
     PYQ + "Goleman argued that EI matters greatly for success in life and work."),
    ("Paul Ekman's six basic emotions are:",
     ["Happiness, sadness, fear, anger, surprise and disgust", "Love, hate, envy, pride, shame and guilt", "Hunger, thirst, sleep, sex, pain and rest", "Joy, trust, hope, peace, calm and faith"], 0,
     "They are recognised from facial expressions across cultures."),
    ("Goleman used the phrase 'amygdala hijack' to describe:",
     ["A sudden, overwhelming emotional reaction that overrides rational thinking", "A type of memory loss", "A learning disability", "A method of teaching"], 0,
     "The amygdala in the brain plays a key role in fear and other emotions."),
    ("A teacher with high emotional intelligence is most likely to:",
     ["Stay calm in difficult classroom situations and respond to pupils' feelings with understanding", "Shout whenever a pupil makes a mistake", "Ignore pupils' feelings to finish the syllabus", "Avoid talking to parents"], 0,
     "EI supports classroom management and good relationships."),
    ("An emotionally mature person typically:",
     ["Controls emotions, expresses them in acceptable ways and tolerates frustration", "Has no emotions at all", "Reacts with extreme anger to small problems", "Depends on others for every decision"], 0,
     "Emotional maturity grows with age and experience."),
    ("Which statement about emotions is correct?",
     ["An emotion has physiological, cognitive and behavioural components", "Emotions have no effect on learning", "Emotions occur only in adults", "Emotions are always harmful"], 0,
     "e.g. fear raises heart rate, involves a thought of danger and may cause running away."),
    ("Match the psychologist with the contribution:\na. Salovey and Mayer  b. Goleman  c. Bar-On  d. Gardner\n1. Multiple intelligences, including interpersonal intelligence  2. Emotional Quotient Inventory (EQ-i)  3. Popular 1995 book on EI and its five dimensions  4. First formal definition of EI (1990)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "A common matching question on EI."),
    ("Consider the statements:\nI. Emotional intelligence involves managing one's own emotions.\nII. Emotional intelligence is fixed at birth and cannot change.\nWhich is/are correct?",
     I_II, 0, "EI can be learned and improved."),
    ("Assertion (A): Teachers with high emotional intelligence handle classroom conflicts better.\nReason (R): They can recognise and regulate their own emotions and respond to pupils' emotions.",
     AR, 0, "That is the core of emotional intelligence."),
    ("Goleman's EI model is often called a 'mixed model' because it:",
     ["Combines emotional abilities with personality traits and competencies such as motivation and social skills", "Mixes IQ with memory tests", "Uses only physical measures", "Was developed by several countries"], 0,
     "Mayer and Salovey's model, by contrast, treats EI purely as an ability."),
]

DIMENSIONS = [
    # --- real previous-year questions ---
    ("Identify the one which is NOT included in emotional intelligence skills.",
     ["Self awareness and self-management", "Social awareness", "Emotional suppression and social control", "Relationship management"], 2,
     "Goleman's four domains are self-awareness, self-management, social awareness and relationship management; suppressing emotions is not an EI skill." + NOTE,
     "KSET 2024 Education · Q23"),
    ("Given below are two statements, one labelled as Assertion (A) and the other labelled as Reason (R).\nAssertion (A): Social competence is the condition of possessing well-developed, social-emotional and intellectual skills.\nReason (R): It is one of the most widely investigated areas of human social behaviour.\nExamine the statements and select the correct answer.",
     ["Both (A) and (R) are true but (R) is not the correct explanation of (A)", "Both (A) and (R) are true and (R) is the correct explanation of (A)", "(A) is true but (R) is false", "(A) is false but (R) is true"], 0,
     "Both statements are true, but how widely it is studied does not explain what social competence is." + NOTE,
     "KSET 2025 Education · Q30"),
    # --- new questions ---
    ("Goleman's five dimensions (components) of emotional intelligence are:",
     ["Self-awareness, self-regulation, motivation, empathy and social skills", "Perception, memory, thinking, reasoning and imagination", "Fluency, flexibility, originality, elaboration and sensitivity", "Knowledge, comprehension, application, analysis and synthesis"], 0,
     PYQ + "The most frequently asked fact on this topic."),
    ("Which of these is NOT one of Goleman's five dimensions of EI?",
     ["Intelligence quotient", "Empathy", "Self-regulation", "Social skills"], 0,
     PYQ + "IQ is a separate measure of cognitive ability."),
    ("Recognising one's own emotions, strengths and weaknesses and their effect on others is:",
     ["Self-awareness", "Empathy", "Social skill", "Motivation"], 0,
     PYQ + "Goleman calls it the foundation of emotional intelligence."),
    ("Controlling or redirecting disruptive impulses and moods, and thinking before acting, is:",
     ["Self-regulation (self-management)", "Self-awareness", "Empathy", "Social skill"], 0,
     "It includes trustworthiness and adaptability."),
    ("In Goleman's model, 'motivation' refers to:",
     ["An inner drive to achieve for its own sake, with optimism even after failure", "Working only for money or status", "Fear of punishment", "Copying others"], 0,
     "It includes commitment and initiative."),
    ("Understanding and sharing the feelings of others, and seeing things from their point of view, is:",
     ["Empathy", "Self-regulation", "Self-awareness", "Sympathy only"], 0,
     PYQ + "Sympathy is feeling sorry for someone; empathy is feeling with them."),
    ("Managing relationships, communicating clearly, resolving conflicts and working in teams make up:",
     ["Social skills", "Self-awareness", "Motivation", "Self-regulation"], 0,
     "Leadership and influence also belong here."),
    ("In Goleman's grouping, personal competence includes ____ and social competence includes ____.",
     ["Self-awareness, self-regulation and motivation; empathy and social skills", "Empathy and social skills; self-awareness and motivation", "Only IQ; only EQ", "Memory; attention"], 0,
     PYQ + "Personal competence is about managing oneself; social competence is about handling relationships."),
    ("Goleman's later four-domain model of EI consists of:",
     ["Self-awareness, self-management, social awareness and relationship management", "Perceiving, using, understanding and managing emotions", "Knowing, feeling, willing and doing", "Id, ego, superego and libido"], 0,
     "The KSET 2024 question above uses these terms."),
    ("A pupil feels angry when teased but takes a deep breath and answers calmly. This shows:",
     ["Self-regulation", "Empathy", "Social awareness only", "Lack of emotion"], 0,
     "He recognises the anger and controls its expression."),
    ("A teacher notices that a usually cheerful pupil is quiet and sad and gently asks what is wrong. This shows:",
     ["Empathy", "Self-regulation", "Motivation", "Self-awareness only"], 0,
     "Reading others' emotional cues is part of empathy and social awareness."),
    ("Walter Mischel's 'marshmallow test' on children's ability to wait for a bigger reward is linked to which EI skill?",
     ["Delaying gratification – self-regulation", "Empathy", "Social skill", "Physical strength"], 0,
     "Goleman cites it as evidence for the importance of impulse control."),
    ("Which classroom activity best helps develop pupils' emotional intelligence?",
     ["Role play and discussion of feelings in real-life situations", "Copying notes silently", "Memorising definitions of emotions", "Punishing pupils who show emotions"], 0,
     PYQ + "Journaling, cooperative learning and circle time also help."),
    ("SEL, used in schools to develop emotional intelligence, stands for:",
     ["Social and Emotional Learning", "Self-Evaluated Learning", "Systematic Education for Life", "Scientific Experimental Learning"], 0,
     "CASEL's five SEL competencies closely follow Goleman's dimensions."),
    ("Match the EI dimension with the behaviour:\na. Self-awareness  b. Self-regulation  c. Empathy  d. Social skills\n1. Resolving a quarrel between classmates  2. Sensing that a friend is worried  3. Controlling the urge to shout  4. Knowing that one gets nervous before speaking in public",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Dimension–behaviour matching is common in TET and KSET papers."),
    ("Consider the statements:\nI. Empathy and social skills are part of social competence.\nII. Self-awareness is part of social competence in Goleman's grouping.\nWhich is/are correct?",
     I_II, 0, "Self-awareness belongs to personal competence."),
    ("Assertion (A): Self-awareness is the foundation of the other emotional-intelligence skills.\nReason (R): A person cannot manage emotions that he or she does not recognise.",
     AR, 0, "Goleman places self-awareness first for this reason."),
    ("Assertion (A): Empathy means feeling sorry for someone.\nReason (R): Empathy means understanding and sharing another person's feelings from their point of view.",
     AR, 3, "Feeling sorry for someone is sympathy, so A is false."),
]

TOPICS = {
    "Emotional Intelligence": [("1 · Meaning, Models and Importance of Emotional Intelligence", MEANING_MODELS),
                               ("2 · Goleman's Five Dimensions and Developing EI", DIMENSIONS)],
}
