"""Paper 1 · Educational Psychology · P1-PSY-07 Intelligence (2 sub-topics × 20).
References: S. K. Mangal, Advanced Educational Psychology; Anastasi & Urbina, Psychological Testing; Wechsler's IQ classification;
DSERT D.El.Ed. texts. "PYQ pattern" questions follow themes in the downloaded KSET/GFGC Education papers (sources/pyq):
IQ descriptive bands, verbal vs non-verbal tests (Binet, Army Beta, Raven), Guilford / Thurstone / Cattell."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KSET / GPSTR / KARTET). "

MEANING_IQ = [
    ("The formula for (ratio) Intelligence Quotient is:",
     ["IQ = (Mental Age ÷ Chronological Age) × 100", "IQ = (Chronological Age ÷ Mental Age) × 100", "IQ = Mental Age − Chronological Age", "IQ = Mental Age × Chronological Age"], 0, PYQ + "The concept of IQ was proposed by William Stern (1912) and popularised by Terman."),
    ("A child aged 10 years has a mental age of 12 years. The child's IQ is:",
     ["120", "83", "100", "112"], 0, "12 ÷ 10 × 100 = 120."),
    ("A child aged 10 years has a mental age of 8 years. The child's IQ is:",
     ["80", "125", "108", "90"], 0, "8 ÷ 10 × 100 = 80."),
    ("A 15-year-old has a mental age of 12 years. The IQ is:",
     ["80", "125", "120", "75"], 0, "12 ÷ 15 × 100 = 80."),
    ("The term 'Intelligence Quotient' was coined by:",
     ["William Stern", "Alfred Binet", "Charles Spearman", "Howard Gardner"], 0, PYQ + "Binet and Simon introduced 'mental age'."),
    ("The concept of 'mental age' was introduced by:",
     ["Alfred Binet (with Théodore Simon)", "David Wechsler", "L. L. Thurstone", "J. P. Guilford"], 0, "Their 1905 scale arranged tasks by the age at which most children pass them."),
    ("David Wechsler defined intelligence as:",
     ["The aggregate or global capacity to act purposefully, think rationally and deal effectively with the environment", "Only the ability to remember facts", "The score on any test", "A single inherited trait that never changes"], 0, PYQ + "A frequently quoted definition."),
    ("Terman defined intelligence as:",
     ["The ability to carry on abstract thinking", "The ability to run fast", "Emotional control", "Memory for faces"], 0, "Terman revised the Binet scale as the Stanford–Binet (1916)."),
    ("Intelligence scores in a large population are distributed in a:",
     ["Normal (bell-shaped) curve with mean 100", "Straight line", "U-shaped curve", "Random pattern with no average"], 0, PYQ + "Most people are near the average; few are at the extremes."),
    ("On Wechsler scales (mean 100, SD 15), about what percentage of people have IQs between 85 and 115?",
     ["About 68%", "About 95%", "About 50%", "About 99.7%"], 0, "±1 standard deviation covers about 68% of a normal distribution."),
    ("About what percentage of people have IQs between 70 and 130 (mean 100, SD 15)?",
     ["About 95%", "About 68%", "About 34%", "About 2%"], 0, "±2 standard deviations."),
    ("On Wechsler's classification, an IQ of 130 and above is described as:",
     ["Very superior", "High average", "Borderline", "Average"], 0, PYQ + "120–129 superior; 110–119 high average; 90–109 average."),
    ("On Wechsler's classification, an IQ of 70–79 is described as:",
     ["Borderline", "Average", "Superior", "Very superior"], 0, PYQ + "Below 70 indicates intellectual disability."),
    ("Wechsler replaced the ratio IQ with the deviation IQ mainly because:",
     ["Mental age stops increasing in adulthood, so MA/CA does not work for adults", "Deviation IQ is easier to calculate by hand", "Ratio IQ cannot be computed for children", "Binet asked him to"], 0, "Deviation IQ compares a person with others of the same age."),
    ("Intelligence is generally considered to be influenced by:",
     ["Both heredity and environment", "Heredity alone", "Environment alone", "Neither"], 0, "Heredity sets the potential; environment influences how much is realised."),
    ("Match the IQ range (Wechsler) with its description:\na. 130 and above  b. 110–119  c. 90–109  d. 70–79\n1. Borderline  2. Average  3. High average  4. Very superior",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "IQ classification matching appears in KSET Education papers."),
    ("Consider the statements:\nI. A child whose mental age equals chronological age has an IQ of 100.\nII. An IQ of 100 means the child is below average.\nWhich is/are correct?",
     I_II, 0, "100 is the average IQ."),
    ("Consider the statements:\nI. The distribution of intelligence follows the normal curve.\nII. Very few people have extremely high or extremely low IQs.\nWhich is/are correct?",
     I_II, 2, "Both follow from the normal distribution."),
    ("Assertion (A): The ratio IQ is not suitable for adults.\nReason (R): Mental age stops growing in adulthood while chronological age keeps increasing.",
     AR, 0, "So MA/CA would fall with age even if ability did not."),
    ("Assertion (A): An IQ of 120 is below average.\nReason (R): The average IQ is 100.",
     AR, 3, "120 is above average, so A is false."),
]

THEORIES_TESTS = [
    ("The two-factor theory of intelligence (general 'g' factor and specific 's' factors) was proposed by:",
     ["Charles Spearman", "L. L. Thurstone", "J. P. Guilford", "E. L. Thorndike"], 0, PYQ + "Spearman, 1904."),
    ("The theory of Primary Mental Abilities was proposed by:",
     ["L. L. Thurstone", "Charles Spearman", "Howard Gardner", "Robert Sternberg"], 0, PYQ + "Seven abilities, e.g. verbal comprehension, number, space, memory, reasoning."),
    ("The 'Structure of Intellect' model, with dimensions of contents, operations and products, was proposed by:",
     ["J. P. Guilford", "Raymond Cattell", "David Wechsler", "Alfred Binet"], 0, PYQ + "His cube model originally had 120 abilities (5 × 5 × 6 in later versions)."),
    ("The distinction between fluid and crystallised intelligence was made by:",
     ["Raymond Cattell", "Charles Spearman", "Howard Gardner", "E. L. Thorndike"], 0, PYQ + "Fluid = reasoning in new situations; crystallised = acquired knowledge."),
    ("The theory of Multiple Intelligences (1983) was proposed by:",
     ["Howard Gardner", "Robert Sternberg", "Daniel Goleman", "J. P. Guilford"], 0, PYQ + "It includes linguistic, logical-mathematical, spatial, musical, bodily-kinaesthetic, interpersonal, intrapersonal and naturalist intelligences."),
    ("Which is NOT one of Gardner's multiple intelligences?",
     ["Mechanical intelligence", "Musical intelligence", "Interpersonal intelligence", "Naturalist intelligence"], 0, "Mechanical intelligence appears in Thorndike's classification, not Gardner's."),
    ("Sternberg's triarchic theory describes intelligence as:",
     ["Analytical, creative and practical", "Verbal, numerical and spatial", "Fluid and crystallised", "General and specific"], 0, "Robert Sternberg, 1985."),
    ("E. L. Thorndike's multifactor theory classified intelligence into:",
     ["Abstract, social and concrete (mechanical)", "Fluid and crystallised", "g and s", "Analytical, creative and practical"], 0, "Thorndike rejected a single general factor."),
    ("The first practical intelligence test was developed in 1905 by:",
     ["Binet and Simon", "Terman and Merrill", "David Wechsler", "Raven"], 0, PYQ + "It was made to identify children needing special help in French schools."),
    ("The Army Alpha and Army Beta tests were developed during:",
     ["World War I, for selecting soldiers", "World War II, for pilots only", "The 1950s, for schools", "The 1990s, for computers"], 0, PYQ + "Army Alpha was verbal (for literates); Army Beta was non-verbal (for illiterates)."),
    ("Raven's Progressive Matrices is a:",
     ["Non-verbal, largely culture-fair test of reasoning", "Verbal vocabulary test", "Personality inventory", "Achievement test in mathematics"], 0, PYQ + "It uses patterns with a missing piece."),
    ("Which pair consists of non-verbal intelligence tests?",
     ["Army Beta test and Raven's Progressive Matrices", "Binet's test and Army Alpha", "Stanford–Binet and Army Alpha", "Binet's test and a comprehension test"], 0, PYQ + "A KSET Education paper asked this as a choice among such pairs."),
    ("The Indian performance test battery that includes Koh's Block Design and Alexander's Pass-along test was developed by:",
     ["C. M. Bhatia", "S. M. Mohsin", "Jalota", "P. N. Mehrotra"], 0, PYQ + "Bhatia's Battery of Performance Tests of Intelligence (1955)."),
    ("An intelligence test given to one person at a time by a trained examiner, such as the Stanford–Binet, is called a(n):",
     ["Individual test", "Group test", "Achievement test", "Aptitude test only"], 0, "Group tests, like Army Alpha, test many people at once."),
    ("The Wechsler Adult Intelligence Scale (WAIS) gives separate scores for:",
     ["Verbal and performance (later index) scales", "Personality and attitude", "Speed and spelling only", "Reading and writing only"], 0, "Wechsler scales combine verbal and non-verbal subtests."),
    ("A main educational use of intelligence tests is to:",
     ["Help identify gifted and slow learners for suitable instruction and guidance", "Label children permanently", "Replace teaching", "Decide caste or religion"], 0, "Results should guide, not label."),
    ("Match the psychologist with the theory:\na. Spearman  b. Thurstone  c. Guilford  d. Gardner\n1. Multiple intelligences  2. Structure of intellect  3. Primary mental abilities  4. Two-factor theory",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "The most common matching question on intelligence."),
    ("Consider the statements:\nI. Army Alpha was a verbal test.\nII. Army Beta was a verbal test for literates.\nWhich is/are correct?",
     I_II, 0, "Army Beta was the non-verbal test."),
    ("Assertion (A): Non-verbal tests are useful for people who cannot read.\nReason (R): Non-verbal tests use pictures, patterns and objects instead of language.",
     AR, 0, "So literacy does not limit performance."),
    ("Assertion (A): Gardner's theory includes musical intelligence.\nReason (R): Spearman proposed the theory of multiple intelligences.",
     AR, 2, "A is true; R is false – it was Gardner."),
]

TOPICS = {
    "Intelligence": [("1 · Meaning, IQ and Distribution of Intelligence", MEANING_IQ),
                     ("2 · Theories and Tests of Intelligence", THEORIES_TESTS)],
}
