"""Paper 1 · Educational Psychology · P1-PSY-12 Attention (2 sub-topics × 20).
Coverage (planner): meaning, types, importance, techniques.
References: S. K. Mangal, Advanced Educational Psychology; Woolfolk, Educational Psychology; William James, Principles of Psychology;
Bandura, Social Learning Theory; DSERT D.El.Ed. psychology texts. Two REAL previous-year questions come from GFGC 2021 Education and
KSET 2025 Education (no published key; answers worked out by ExamSim). The rest are "PYQ pattern" questions on themes common in KSET
Education / TET / GPSTR papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KSET Education / TET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

MEANING = [
    ("Identify the correct sequence of steps in social learning theory.\nI. Retention\nII. Motivation\nIII. Attention\nIV. Reproduction",
     ["I, II, III, IV", "II, III, IV, I", "III, I, IV, II", "IV, II, III, I"], 2,
     "Bandura: attention → retention → reproduction (motor reproduction) → motivation. Without attention there is no observational learning." + NOTE,
     "GFGC 2021 Education · Q36"),
    ("Attention is best defined as:",
     ["Focusing consciousness on one object or idea while ignoring others", "Storing information permanently", "Reacting without thinking", "Recalling past experiences"], 0,
     PYQ + "William James: 'taking possession by the mind, in clear and vivid form, of one out of several possible objects'."),
    ("Attention that is drawn without any effort by a loud noise or a bright light is:",
     ["Involuntary (non-volitional) attention", "Voluntary attention", "Habitual attention", "Divided attention"], 0, "It is caused by the strength of the stimulus."),
    ("A student keeps attending to a difficult lesson by effort of will because of the examination. This is:",
     ["Voluntary (volitional) attention", "Involuntary attention", "Spontaneous attention", "Reflex attention"], 0,
     PYQ + "Voluntary attention needs effort and is tiring."),
    ("Attention that has become natural because of interest and practice, such as a cricket fan following the score, is:",
     ["Habitual (non-voluntary) attention", "Enforced attention", "Explicit voluntary attention", "Reflex attention"], 0, "Interest is 'latent attention'; attention is 'interest in action'."),
    ("Who said 'Interest is latent attention and attention is interest in action'?",
     ["McDougall", "Pavlov", "Piaget", "Skinner"], 0, PYQ + "Interest and attention are two sides of the same coin."),
    ("The number of objects a person can grasp at a single glance is called the:",
     ["Span of attention", "Fluctuation of attention", "Division of attention", "Shifting of attention"], 0, "For adults it is about 6–8 items (Miller's 'seven plus or minus two' for memory)."),
    ("The instrument used to measure the span of attention is the:",
     ["Tachistoscope", "Ergograph", "Stethoscope", "Kymograph"], 0, PYQ + "It flashes material for a fraction of a second; the ergograph measures fatigue."),
    ("Attention cannot stay fixed on one object for long and keeps moving to and fro. This is called:",
     ["Fluctuation (oscillation) of attention", "Span of attention", "Distraction", "Concentration"], 0,
     "Fluctuation lasts a few seconds; it can be shown with a dim sound or the ambiguous 'double-figure' drawing."),
    ("Attending to two activities at the same time, such as driving and talking, is:",
     ["Division of attention", "Span of attention", "Fluctuation of attention", "Sustained attention"], 0,
     PYQ + "It is possible only when one activity is automatic (habitual)."),
    ("Which is an objective (external) determinant of attention?",
     ["Intensity, size, colour, movement, novelty and contrast of the stimulus", "Interest", "Mood", "Goal of the person"], 0,
     "Subjective (internal) determinants include interest, need, motive, mood, habit and aim."),
    ("Which is a subjective (internal) determinant of attention?",
     ["Interest and motive", "Size of the stimulus", "Colour", "Repetition"], 0, PYQ + "A hungry person notices food shops."),
    ("A sudden change in the teacher's voice catches pupils' attention because of:",
     ["Change and contrast in the stimulus", "Fatigue", "Habit", "Distraction"], 0, "A monotonous voice makes attention wander."),
    ("Match the following learning disabilities\nList-I\na) ADHD\nb) Dyscalculia\nc) Dyslexia\nd) Dysgraphia\nList-II\ni. Reading\nii. Writing\niii. Calculation\niv. Attention deficit, hyperactivity disorder",
     ["a-iii, b-ii, c-iv, d-i", "a-iv, b-iii, c-i, d-ii", "a-iv, b-i, c-ii, d-iii", "a-iii, b-iv, c-i, d-ii"], 1,
     "ADHD = attention-deficit hyperactivity disorder; dyscalculia – arithmetic; dyslexia – reading; dysgraphia – writing." + NOTE, "KSET 2025 Education · Q99"),
    ("Children with ADHD typically show:",
     ["Inattention, hyperactivity and impulsivity", "Only reading difficulty", "High concentration for long periods", "Physical disability only"], 0,
     PYQ + "Short, structured tasks, seating near the teacher and frequent feedback help them."),
    ("Selective attention means:",
     ["Focusing on certain stimuli while filtering out others", "Paying equal attention to everything", "Remembering everything", "Sleeping in class"], 0,
     "The 'cocktail party effect' – hearing your name in a noisy room – shows it."),
    ("Consider the statements:\nI. Attention is selective.\nII. Attention is always steady and never fluctuates.",
     I_II, 0, "Attention fluctuates naturally."),
    ("Assertion (A): Attention is a pre-condition of learning.\nReason (R): What is not attended to cannot be perceived, understood or remembered.",
     AR, 0, "So the teacher's first task is to secure attention."),
    ("Assertion (A): Involuntary attention needs great effort of will.\nReason (R): Involuntary attention is caused by strong or sudden stimuli.",
     AR, 3, "Involuntary attention needs no effort; voluntary attention does."),
    ("Match:\na. Involuntary attention  b. Voluntary attention  c. Habitual attention  d. Span of attention\n1. Sudden loud noise  2. Studying a dull subject for an exam  3. A musician noticing a wrong note  4. Number of objects seen at a glance",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Types of attention are frequently matched."),
]

TECHNIQUES = [
    ("Inattention or distraction in the classroom is most often caused by:",
     ["Monotonous teaching, lack of interest and poor physical conditions", "Too many teaching aids used well", "A lesson linked to pupils' needs", "Short, varied activities"], 0,
     PYQ + "Physical causes include fatigue, hunger, poor light, noise and uncomfortable seating."),
    ("Which of the following is the BEST way for a teacher to secure pupils' attention?",
     ["Linking the lesson to pupils' interests and using varied teaching methods", "Shouting at the class", "Lecturing continuously for an hour", "Threatening punishment"], 0,
     "Interest is the strongest basis of attention."),
    ("Using teaching aids such as charts, models and videos helps attention because they:",
     ["Appeal to several senses and add novelty", "Make the lesson longer", "Remove the need for the teacher", "Reduce pupil activity"], 0, PYQ + "Audio-visual aids make abstract ideas concrete."),
    ("Asking questions at intervals during a lesson mainly helps to:",
     ["Keep pupils alert and check their understanding", "Waste time", "Punish weak pupils", "Finish the syllabus faster"], 0, "Questions involve pupils actively."),
    ("A teacher changes the activity every 10–15 minutes in a primary class because:",
     ["Young children have a short span of sustained attention", "The syllabus demands it", "Pupils dislike learning", "Teachers get tired"], 0,
     PYQ + "Sustained attention grows with age."),
    ("Which classroom condition best supports attention?",
     ["Good light, ventilation and comfortable seating with few distractions", "A noisy room facing a busy road", "Very hot room", "Dim light"], 0, "Physical comfort reduces distraction."),
    ("Gagne's first event of instruction, before presenting new content, is:",
     ["Gaining attention", "Assessing performance", "Enhancing retention", "Providing feedback"], 0,
     PYQ + "Gagne's nine events: gain attention, inform objectives, stimulate recall, present content, guide learning, elicit performance, give feedback, assess, enhance retention and transfer."),
    ("Telling pupils the objective of the lesson at the start helps attention by:",
     ["Giving a purpose that directs their attention", "Making them anxious", "Reducing interest", "Ending curiosity"], 0, "A clear purpose turns involuntary attention into voluntary attention."),
    ("'Distraction' in psychology means:",
     ["Diversion of attention from the object one wants to attend to", "Total concentration", "Memory loss", "A kind of intelligence"], 0,
     PYQ + "Mild, steady distraction may even raise effort; strong or changing distraction lowers performance."),
    ("Concentration is best described as:",
     ["Sustained voluntary attention on one task for a long time", "Fluctuation of attention", "Division of attention", "Involuntary attention"], 0,
     "It can be improved with interest, practice and good habits."),
    ("Which of the following helps develop habitual attention in pupils?",
     ["Regular practice and creating lasting interest in subjects", "Random punishment", "Avoiding all homework", "Teaching without a plan"], 0, PYQ + "Good study habits make attention easier."),
    ("A teacher writes the key word in coloured chalk and underlines it. This uses which determinant of attention?",
     ["Colour and contrast (objective factors)", "Mood", "Need", "Habit"], 0, "Size, intensity, colour, movement and novelty attract attention."),
    ("Starting a lesson with a story, puzzle or surprising fact is done mainly to:",
     ["Arouse curiosity and gain attention", "Finish the period", "Test memory", "Punish latecomers"], 0, PYQ + "Herbart's first step is 'preparation'."),
    ("Which statement about the span of attention is correct?",
     ["It increases with age, practice and meaningful grouping of material", "It is the same for everybody", "It decreases with practice", "It cannot be measured"], 0,
     "Grouping items (chunking) increases the span."),
    ("Learner participation through activities, group work and discussion improves attention because:",
     ["Active involvement leaves less room for mind-wandering", "It reduces learning", "It replaces the teacher", "It shortens the syllabus"], 0, PYQ + "Learning by doing (Dewey)."),
    ("A pupil looks out of the window during class. The teacher should first:",
     ["Check the lesson's interest and involve the pupil through a question or activity", "Punish the pupil publicly", "Send the pupil out", "Ignore the whole class"], 0,
     "Re-engage rather than punish."),
    ("Consider the statements:\nI. Fatigue and poor health reduce attention.\nII. Interest has no effect on attention.",
     I_II, 0, "Interest is the most important internal determinant of attention."),
    ("Assertion (A): Teachers should vary their voice, pace and methods.\nReason (R): Change and novelty are determinants of attention.",
     AR, 0, "Monotony is the enemy of attention."),
    ("Assertion (A): Fear of punishment is the best way to secure lasting attention.\nReason (R): Attention secured by fear lasts only while the threat is present.",
     AR, 3, "Fear gives only temporary, forced attention."),
    ("Match the technique with the factor of attention it uses:\na. Using a model of the heart  b. Linking a lesson to cricket  c. Moving pictures on the screen  d. Short breaks between activities\n1. Concreteness / sensory appeal  2. Interest  3. Movement  4. Reducing fatigue",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Classroom applications of attention are often asked."),
]

TOPICS = {
    "Attention": [("1 · Meaning, Types, Span, Fluctuation and Determinants of Attention", MEANING),
                  ("2 · Distraction, Concentration and Classroom Techniques", TECHNIQUES)],
}
