"""Paper 1 · Educational Psychology · P1-PSY-01 and P1-PSY-02 (4 sub-topics × 20).
References: S. K. Mangal, Advanced Educational Psychology; J. C. Aggarwal, Essentials of Educational Psychology; Woolfolk; Santrock."""
from packlib import AR, I_II

PSYCHOLOGY = [
    ("The word 'psychology' comes from two Greek words, 'psyche' and 'logos', which mean:",
     ["Soul and study (science)", "Mind and behaviour", "Brain and nerves", "Child and teaching"], 0, "Psychology literally meant 'the study of the soul'."),
    ("Arrange the historical meanings of psychology in the order in which they developed:",
     ["Science of soul → science of mind → science of consciousness → science of behaviour", "Science of behaviour → mind → soul → consciousness", "Science of mind → soul → behaviour → consciousness", "Science of consciousness → soul → mind → behaviour"], 0,
     "Each earlier meaning was dropped because its subject could not be studied scientifically."),
    ("Who remarked that psychology first lost its soul, then its mind, then its consciousness, and still has behaviour of a sort?",
     ["R. S. Woodworth", "Sigmund Freud", "Jean Piaget", "B. F. Skinner"], 0, "Woodworth summed up the changing definitions of psychology in this way."),
    ("Psychology was defined as 'the science of behaviour', rejecting the study of consciousness, by:",
     ["J. B. Watson", "Wilhelm Wundt", "William James", "E. B. Titchener"], 0, "Watson founded behaviourism (1913): only observable behaviour can be studied scientifically."),
    ("The first laboratory of experimental psychology was established in 1879 at Leipzig by:",
     ["Wilhelm Wundt", "William James", "Ivan Pavlov", "Hermann Ebbinghaus"], 0, "This event is taken as the birth of psychology as a separate science."),
    ("'Psychology is the science of mental life, both of its phenomena and of their conditions.' This definition was given by:",
     ["William James", "J. B. Watson", "Kurt Koffka", "Carl Rogers"], 0, "From The Principles of Psychology (1890); James is associated with functionalism."),
    ("The most widely accepted modern definition of psychology is:",
     ["The scientific study of behaviour and mental processes", "The study of the soul", "The study of consciousness only", "The study of abnormal people"], 0, "It includes both overt behaviour and inner processes such as thinking and feeling."),
    ("Which of the following is an example of covert (internal) behaviour?",
     ["Thinking about a problem", "Writing an answer", "Running in a race", "Raising a hand in class"], 0, "Covert behaviour cannot be seen directly; overt behaviour can be observed by others."),
    ("Which of the following is an APPLIED branch of psychology?",
     ["Educational psychology", "General psychology", "Physiological psychology", "Experimental psychology"], 0, "Applied branches use psychological principles in fields such as education, industry and clinics."),
    ("Match the school of psychology with its founder or chief exponent:\na. Structuralism  b. Behaviourism  c. Gestalt  d. Psychoanalysis\n1. Sigmund Freud  2. Max Wertheimer  3. J. B. Watson  4. E. B. Titchener (after Wundt)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-1, b-3, c-2, d-4"], 0, "Gestalt psychology was founded by Wertheimer with Köhler and Koffka."),
    ("The German word 'Gestalt' means:",
     ["Whole, form or pattern", "Stimulus", "Reward", "Unconscious"], 0, "Gestalt psychologists held that the whole is different from the sum of its parts."),
    ("Which school of psychology stressed the role of the unconscious mind?",
     ["Psychoanalysis", "Behaviourism", "Structuralism", "Functionalism"], 0, "Freud held that repressed wishes in the unconscious influence behaviour."),
    ("Humanistic psychology, called the 'third force' in psychology, is associated mainly with:",
     ["Abraham Maslow and Carl Rogers", "Pavlov and Skinner", "Wundt and Titchener", "Freud and Jung"], 0, "It came after behaviourism and psychoanalysis and stresses self-actualisation and free will."),
    ("Psychology is generally called a 'positive science' because it:",
     ["Studies behaviour as it is, not as it ought to be", "Always gives positive results", "Deals only with happy feelings", "Is based on religious values"], 0, "Normative sciences such as ethics deal with what ought to be."),
    ("Which of the following is NOT part of the scope of psychology?",
     ["Fixing the prices of goods in a market", "Behaviour of human beings and animals", "Normal and abnormal behaviour", "Individual and group behaviour"], 0, "Market prices belong to economics, although psychology may study consumer behaviour."),
    ("Consider the statements:\nI. Structuralists used introspection to analyse consciousness into its elements.\nII. Behaviourists relied mainly on introspection.\nWhich is/are correct?",
     I_II, 0, "Behaviourists rejected introspection as unscientific and studied observable behaviour."),
    ("Consider the statements:\nI. Modern psychology studies animals as well as human beings.\nII. Modern psychology studies both normal and abnormal behaviour.\nWhich is/are correct?",
     I_II, 2, "Both are within its scope, e.g. animal learning experiments and abnormal psychology."),
    ("Assertion (A): Psychology is no longer defined as the 'science of the soul'.\nReason (R): The soul cannot be observed or studied by scientific methods.",
     AR, 0, "Because the soul could not be studied scientifically, the definition changed."),
    ("Assertion (A): Behaviourism rejected the study of consciousness.\nReason (R): Wundt set up the first psychology laboratory at Leipzig.",
     AR, 1, "Both statements are true, but Wundt's laboratory does not explain why behaviourists rejected consciousness."),
    ("Assertion (A): Psychology is an exact science like physics.\nReason (R): Human behaviour is complex and varies from person to person and situation to situation.",
     AR, 3, "Because behaviour is variable, psychology's predictions are probable, not exact; R is true and A is false."),
]

EDU_PSYCHOLOGY = [
    ("'Educational psychology is that branch of psychology which deals with teaching and learning.' This definition was given by:",
     ["Charles E. Skinner", "J. B. Watson", "Wilhelm Wundt", "Sigmund Freud"], 0, "C. E. Skinner (not B. F. Skinner) edited a well-known educational psychology text."),
    ("'Educational psychology describes and explains the learning experiences of an individual from birth through old age.' This definition is by:",
     ["Crow and Crow", "William James", "Kurt Lewin", "Carl Rogers"], 0, "It stresses that learning continues throughout life."),
    ("Who is regarded as the father of educational psychology?",
     ["E. L. Thorndike", "Jean Piaget", "John Dewey", "Ivan Pavlov"], 0, "Thorndike's Educational Psychology (1903) and his laws of learning founded the field."),
    ("The nature of educational psychology is best described as:",
     ["An applied, positive and behavioural science", "A normative science like ethics", "A branch of philosophy only", "A physical science"], 0, "It applies psychological principles to education and studies behaviour as it is."),
    ("Which of the following is NOT within the scope of educational psychology?",
     ["Preparing the school's financial budget", "The learner and individual differences", "The learning process", "Evaluation of learning"], 0, "Budgeting belongs to educational administration."),
    ("The central concern of educational psychology is:",
     ["The teaching–learning process", "The history of education", "School buildings", "Educational finance"], 0, "Its knowledge is used to improve how learners learn and teachers teach."),
    ("'I wish to psychologise education.' This famous statement was made by:",
     ["Pestalozzi", "Plato", "Kothari", "Tagore"], 0, "Pestalozzi wanted teaching to follow the natural development of the child."),
    ("Educational psychology helps a teacher most directly in:",
     ["Understanding individual differences and choosing suitable methods", "Deciding the aims of education", "Writing school laws", "Planning the national budget"], 0, "Aims come from philosophy; psychology helps with how to teach different learners."),
    ("Philosophy of education decides the aims of education, while educational psychology mainly helps in:",
     ["Choosing the means and methods to achieve those aims", "Deciding the aims again", "Building schools", "Appointing teachers"], 0, "It is often said: philosophy gives the 'why', psychology gives the 'how'."),
    ("Educational psychology is not an exact science mainly because:",
     ["Human behaviour is complex and its predictions are only probable", "It does not use any methods", "It has no laws at all", "It studies only animals"], 0, "Its principles are verified scientifically but apply with individual variation."),
    ("A bright student who does well in mathematics has great difficulty in reading. Knowledge of educational psychology helps the teacher mainly to:",
     ["Diagnose the learning difficulty and plan remedial teaching", "Punish the child", "Ignore the problem", "Move the child to a lower class immediately"], 0, "Diagnosis and remediation of learning difficulties are part of its practical use."),
    ("Which area is commonly included in the subject matter of educational psychology?",
     ["Growth and development, learning, intelligence, personality and mental health", "Land revenue and taxation", "Chemical reactions", "Constitutional law"], 0, "These are the standard units of educational psychology courses."),
    ("Match the psychologist with the contribution:\na. Wilhelm Wundt  b. E. L. Thorndike  c. J. B. Watson  d. Sigmund Freud\n1. Psychoanalysis  2. Behaviourism  3. Father of educational psychology  4. First psychology laboratory",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-3, c-1, d-2", "a-2, b-3, c-4, d-1"], 0, "Wundt 1879 Leipzig; Thorndike 1903; Watson 1913; Freud's psychoanalysis."),
    ("The main aim of educational psychology is to:",
     ["Improve the teaching–learning process", "Replace teachers with machines", "Decide the syllabus of every subject", "Conduct examinations only"], 0, "All its topics serve more effective teaching and learning."),
    ("The three main focal points of educational psychology are usually stated as:",
     ["The learner, the learning process and the learning situation", "Buildings, furniture and fees", "Parents, officers and politicians", "Books, pens and notebooks"], 0, "The teacher uses knowledge of all three to plan instruction."),
    ("Consider the statements:\nI. Educational psychology studies the behaviour of the learner in educational situations.\nII. Educational psychology decides the ultimate aims of education.\nWhich is/are correct?",
     I_II, 0, "Deciding aims is the task of the philosophy of education."),
    ("Consider the statements:\nI. Knowledge of educational psychology helps in classroom management and discipline.\nII. It helps in constructing and using tests for evaluation.\nWhich is/are correct?",
     I_II, 2, "Both are practical uses of educational psychology for teachers."),
    ("Assertion (A): A teacher needs knowledge of educational psychology.\nReason (R): Pupils differ in abilities, interests and needs, and teaching must suit them.",
     AR, 0, "Understanding individual differences is a key reason why teachers study educational psychology."),
    ("Assertion (A): Educational psychology is an applied branch of psychology.\nReason (R): It was founded by Wilhelm Wundt at Leipzig.",
     AR, 2, "A is true. R is false: Wundt founded experimental psychology; Thorndike is the father of educational psychology."),
    ("Assertion (A): Educational psychology is a positive science.\nReason (R): Educational psychology deals with teaching and learning.",
     AR, 1, "Both true; it is positive because it studies behaviour as it is, not because of its subject matter."),
]

INTRO_OBS = [
    ("Introspection means:",
     ["Looking within – observing and reporting one's own mental processes", "Observing other people's behaviour", "Conducting a controlled experiment", "Studying the history of a case"], 0, "Also called self-observation."),
    ("Introspection was the main method of which school of psychology?",
     ["Structuralism (Wundt and Titchener)", "Behaviourism", "Psychoanalysis", "Gestalt only"], 0, "Trained observers reported the elements of their conscious experience."),
    ("Which of the following is a major limitation of introspection?",
     ["It is subjective and its reports cannot be verified by others", "It needs very costly equipment", "It can be used only with animals", "It takes many years for each report"], 0, "Only the person concerned can observe his or her own mind."),
    ("Introspection cannot be used satisfactorily with:",
     ["Young children, animals and mentally ill persons", "Trained adults", "Teachers", "University students"], 0, "They cannot analyse and report their own mental states reliably."),
    ("A student recalls and describes the fear felt during yesterday's examination. This form of introspection is sometimes called:",
     ["Retrospection", "Projection", "Participant observation", "Experimentation"], 0, "The experience is examined after it is over, since observing strong emotions while they occur changes them."),
    ("A merit of introspection is that it:",
     ["Gives direct knowledge of one's own experiences without any apparatus", "Is perfectly objective", "Can be used with infants", "Is always verified by others"], 0, "It is simple and can be used anywhere, but it is subjective."),
    ("The observation method in psychology involves:",
     ["Systematically watching and recording the behaviour of others", "Looking into one's own mind", "Manipulating variables in a laboratory", "Studying only past records"], 0, "Observation studies overt behaviour as it occurs."),
    ("In participant observation, the observer:",
     ["Becomes a member of the group being observed", "Watches from behind a one-way mirror without joining", "Asks the subject to introspect", "Only reads records"], 0, "In non-participant observation the observer stays outside the group."),
    ("The best method to study how children behave while playing freely in the playground is:",
     ["Naturalistic observation", "Introspection", "Laboratory experiment", "Questionnaire"], 0, "Behaviour is watched in its natural setting without interference."),
    ("Arrange the steps of the observation method in the correct order:",
     ["Planning → observing → recording → analysing and interpreting → generalising", "Recording → planning → observing → generalising → analysing", "Observing → generalising → planning → recording → analysing", "Analysing → observing → planning → recording → generalising"], 0, "Careful planning comes first and conclusions come last."),
    ("An anecdotal record is:",
     ["A brief, factual description of a significant incident in a pupil's behaviour", "A standardised intelligence test", "A child's own diary", "A report card of marks"], 0, "Teachers write them soon after the incident, keeping facts separate from comments."),
    ("Which tools help to make observation more objective?",
     ["Check-lists, rating scales and audio-video recording", "Guessing and memory alone", "Only the child's own report", "Horoscopes"], 0, "Structured tools and recordings reduce the observer's personal bias."),
    ("A major limitation of the observation method is:",
     ["Observer bias, and subjects may change their behaviour when they know they are watched", "It cannot study behaviour at all", "It can only be used on the observer himself", "It needs no planning"], 0, "Inner mental processes also cannot be observed directly."),
    ("Match the type of observation with its description:\na. Participant  b. Non-participant  c. Naturalistic  d. Controlled\n1. Conducted under pre-arranged conditions  2. Observer joins the group  3. Behaviour in its normal setting  4. Observer stays outside the group",
     ["a-2, b-4, c-3, d-1", "a-4, b-2, c-3, d-1", "a-2, b-4, c-1, d-3", "a-2, b-3, c-4, d-1"], 0, "Controlled observation is often done in a laboratory or a structured situation."),
    ("Consider the statements:\nI. Introspection is an objective method.\nII. Observation can be used with children who cannot yet speak.\nWhich is/are correct?",
     I_II, 1, "Introspection is subjective; observation of overt behaviour works even with infants."),
    ("Consider the statements:\nI. Behaviourists rejected introspection because its data cannot be verified by others.\nII. Observation cannot directly reveal a person's inner thoughts.\nWhich is/are correct?",
     I_II, 2, "Both are standard criticisms: one of introspection, the other a limit of observation."),
    ("Assertion (A): Introspection is not suitable for studying very young children.\nReason (R): Young children cannot analyse and report their own mental processes.",
     AR, 0, "The method depends on the subject's ability to observe and describe his or her own mind."),
    ("Assertion (A): Observation is considered more objective than introspection.\nReason (R): In observation, observers never have any personal bias.",
     AR, 2, "A is true because others can verify observations; R is false – observer bias is a well-known limitation."),
    ("Assertion (A): Participant observation can give deep insight into group behaviour.\nReason (R): Anecdotal records are written by teachers.",
     AR, 1, "Both true, but unrelated: insight comes from the observer living as a group member."),
    ("Assertion (A): Introspection gives objective, verifiable data.\nReason (R): In introspection, only the individual can observe his or her own mental processes.",
     AR, 3, "Because the experience is private, others cannot verify it; R shows why A is false."),
]

CASE_EXPT = [
    ("The case study method is:",
     ["An intensive, in-depth study of a single individual (or unit) to understand and solve a problem", "A study of large groups using questionnaires", "A laboratory experiment with many subjects", "Looking into one's own mind"], 0, "It is also called the clinical or case history method."),
    ("The case study method is most suitable for studying:",
     ["A problem child, such as a delinquent or a chronic truant", "The average height of a class", "The effect of light on reaction time in 100 students", "The syllabus of a subject"], 0, "It aims at diagnosis and remedy for an individual."),
    ("Which of the following is NOT usually a source of information in a case study?",
     ["A horoscope", "Family and developmental history", "School records and teachers' reports", "Medical history and psychological tests"], 0, "Only objective and relevant data about the individual are collected."),
    ("Arrange the steps of a case study in the correct order:",
     ["Identifying the case → collecting data → diagnosis → remedial measures → follow-up", "Diagnosis → identifying the case → follow-up → collecting data → remedy", "Remedy → diagnosis → collecting data → identifying the case → follow-up", "Collecting data → remedy → identifying the case → diagnosis → follow-up"], 0, "Follow-up checks whether the remedy worked."),
    ("A limitation of the case study method is that:",
     ["It is time-consuming and its findings cannot easily be generalised", "It gives no information about the individual", "It needs a laboratory", "It can only be used with animals"], 0, "It deals with one case, so conclusions apply mainly to that case."),
    ("The experimental method is considered the most scientific method in psychology because:",
     ["It studies cause-and-effect relationships under controlled conditions", "It needs no planning", "It depends only on the subject's own report", "It studies only one person"], 0, "Only the independent variable is changed while others are held constant."),
    ("In an experiment, the variable that the experimenter deliberately changes is called the:",
     ["Independent variable", "Dependent variable", "Extraneous variable", "Intervening variable"], 0, "Its effect is measured on the dependent variable."),
    ("A researcher studies whether background music affects how many words students can memorise. The dependent variable is:",
     ["The number of words recalled", "The background music", "The room temperature", "The researcher"], 0, "Music is the independent variable; recall score is the outcome measured."),
    ("Variables such as noise, time of day or fatigue that may affect the result but are not being studied are called:",
     ["Extraneous (confounding) variables, which must be controlled", "Independent variables", "Dependent variables", "Hypotheses"], 0, "Control keeps them from spoiling the cause-effect conclusion."),
    ("In an experiment, the group that does NOT receive the special treatment is called the:",
     ["Control group", "Experimental group", "Focus group", "Case group"], 0, "Comparing the two groups shows the effect of the treatment."),
    ("A hypothesis in the experimental method is:",
     ["A tentative statement about the relationship between variables, to be tested", "The final proven law", "The list of subjects", "The report of results"], 0, "The experiment either supports or rejects it."),
    ("Arrange the steps of the experimental method in the correct order:",
     ["Stating the problem → forming a hypothesis → planning and controlling conditions → conducting the experiment → analysing data → drawing conclusions", "Drawing conclusions → stating the problem → hypothesis → experiment → analysis → planning", "Hypothesis → conclusions → problem → planning → experiment → analysis", "Experiment → problem → hypothesis → conclusions → planning → analysis"], 0, "This follows the general scientific method."),
    ("Hermann Ebbinghaus used nonsense syllables to study memory and forgetting. He used the:",
     ["Experimental method", "Case study method", "Introspection only", "Survey method"], 0, "He controlled the material and measured retention over time (the forgetting curve)."),
    ("In a rotation-group experimental design:",
     ["Each group receives each treatment in turn", "Only one group is used throughout", "Two groups are matched and given different treatments once", "No treatment is given"], 0, "Rotation balances differences between groups; the other designs are single-group and parallel-group."),
    ("A limitation of the experimental method in educational psychology is that:",
     ["Laboratory situations can be artificial, and many problems cannot be studied for ethical reasons", "It never shows cause and effect", "It needs no control", "It cannot be repeated"], 0, "For example, one cannot deliberately deprive children of food to study its effects."),
    ("Match the method with its most suitable use:\na. Introspection  b. Observation  c. Case study  d. Experiment\n1. Testing whether a new teaching method improves scores  2. Diagnosing a child's persistent stealing  3. Studying children's behaviour at play  4. Describing one's own feelings",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each method suits a different kind of question."),
    ("Consider the statements:\nI. In an experiment, the dependent variable is measured, not manipulated.\nII. The case study method studies a large random sample.\nWhich is/are correct?",
     I_II, 0, "A case study examines one individual in depth."),
    ("Assertion (A): The experimental method can establish cause-and-effect relationships.\nReason (R): Only the independent variable is varied while extraneous variables are controlled.",
     AR, 0, "Controlling everything else lets the change in the dependent variable be attributed to the independent variable."),
    ("Assertion (A): Findings of a case study can easily be generalised to all children.\nReason (R): A case study is an intensive study of a single individual.",
     AR, 3, "Because it studies one case, generalisation is limited; R shows why A is false."),
    ("Assertion (A): The experimental method is called the most scientific method of psychology.\nReason (R): It was first used systematically in Wundt's laboratory at Leipzig.",
     AR, 1, "Both true, but its scientific status comes from control and verifiability, not from where it was first used."),
]

TOPICS = {
    "Psychology & Educational Psychology": [("1 · Psychology: Meaning and Scope", PSYCHOLOGY),
                                            ("2 · Educational Psychology: Meaning, Nature, Scope and Need", EDU_PSYCHOLOGY)],
    "Methods of Psychology": [("1 · Introspection and Observation", INTRO_OBS),
                              ("2 · Case Study and Experimental Method", CASE_EXPT)],
}
