"""Paper 1 · Educational Psychology · P1-PSY-03 Growth and Development (2 sub-topics × 20).
References: Elizabeth B. Hurlock, Developmental Psychology / Child Development; S. K. Mangal, Advanced Educational Psychology."""
from packlib import AR, I_II

GROWTH_DEV = [
    ("Growth refers mainly to:",
     ["Quantitative changes such as increase in height, weight and size of body parts", "Qualitative changes in the way a person thinks", "Learning new skills from teachers", "Changes in moral values only"], 0, "Growth is measurable and mostly physical."),
    ("Development is best described as:",
     ["Progressive, orderly and coherent changes – both quantitative and qualitative – in all aspects of a person", "Only an increase in body weight", "Only a change in height", "A change that stops at the end of childhood"], 0, "It covers physical, mental, emotional, social and moral aspects."),
    ("'Development means a progressive series of orderly, coherent changes.' This definition is associated with:",
     ["Elizabeth B. Hurlock", "Sigmund Freud", "J. B. Watson", "Wilhelm Wundt"], 0, "Hurlock's texts on child and developmental psychology are standard references."),
    ("Which statement about growth and development is correct?",
     ["Growth stops at maturity, but development continues throughout life", "Development stops at maturity, but growth continues throughout life", "Both stop at the age of 10", "Neither changes after birth"], 0, "Development is 'from womb to tomb'."),
    ("Which of the following is an example of development rather than mere growth?",
     ["A child becoming able to reason about abstract ideas", "A child's height increasing by 5 cm", "A child's weight increasing by 2 kg", "An increase in the size of the child's feet"], 0, "Reasoning ability is a qualitative change in function."),
    ("Growth can be measured directly, whereas development is:",
     ["Observed and assessed through changes in behaviour and functions", "Impossible to notice", "Measured only in kilograms", "Measured only with a tape"], 0, "Development involves complex qualitative changes."),
    ("Which statement shows the relationship between growth and development?",
     ["Growth is one part of the wider process of development", "Development is one part of growth", "They are unrelated", "They are exactly the same"], 0, "Development includes growth as well as changes in functioning."),
    ("Changes that occur because of the natural unfolding of inherited potential, without special training – such as an infant beginning to walk – are due to:",
     ["Maturation", "Learning", "Punishment", "Conditioning"], 0, "Learning depends on experience and practice."),
    ("Development results from the interaction of:",
     ["Maturation (heredity) and learning (environment)", "Heredity alone", "Environment alone", "Diet alone"], 0, "Both nature and nurture contribute."),
    ("Which of the following is NOT usually listed as a dimension of development?",
     ["Financial development", "Physical development", "Intellectual (cognitive) development", "Social and emotional development"], 0, "Moral and language development are also dimensions."),
    ("Growth may take place without corresponding development. Which example illustrates this?",
     ["A child gains weight but shows no improvement in skills or functioning", "A child learns to read fluently", "A child becomes more cooperative with peers", "A child starts solving problems logically"], 0, "Increase in size does not always bring better functioning."),
    ("Match the term with its meaning:\na. Growth  b. Development  c. Maturation  d. Learning\n1. Change through experience and practice  2. Unfolding of inherited potential  3. Overall orderly qualitative and quantitative change  4. Increase in size",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These four terms are often confused in examinations."),
    ("The main reason a teacher should understand growth and development is to:",
     ["Plan learning experiences suited to the pupils' stage and readiness", "Increase the pupils' height", "Decide the school fees", "Predict every pupil's future income"], 0, "Teaching must match what children are ready to learn."),
    ("Which statement is INCORRECT?",
     ["Development is purely quantitative", "Growth is mostly physical", "Development is continuous", "Development depends on both maturation and learning"], 0, "Development is both quantitative and qualitative."),
    ("Consider the statements:\nI. Growth refers to structural and physiological changes.\nII. Development refers to changes in functions and behaviour as well.\nWhich is/are correct?",
     I_II, 2, "Both describe the usual distinction."),
    ("Consider the statements:\nI. Development is a lifelong process.\nII. Growth continues at the same rate throughout life.\nWhich is/are correct?",
     I_II, 0, "Growth is fastest in the prenatal period and infancy, and it stops at maturity."),
    ("Assertion (A): Development is wider in scope than growth.\nReason (R): Development includes qualitative changes in functioning as well as quantitative changes.",
     AR, 0, "Growth covers only the quantitative part."),
    ("Assertion (A): Growth continues throughout a person's life.\nReason (R): Growth refers to quantitative changes in the body.",
     AR, 3, "R is true, but physical growth stops around maturity, so A is false."),
    ("Assertion (A): An infant usually begins to walk at about the same age whether or not it is trained.\nReason (R): Walking depends mainly on maturation.",
     AR, 0, "Training cannot make a child walk before the nervous system and muscles are ready."),
    ("Assertion (A): Development can be measured exactly with a scale or a tape.\nReason (R): Growth can be measured in units such as centimetres and kilograms.",
     AR, 3, "R is true; development involves qualitative changes that cannot be measured exactly with such tools, so A is false."),
]

PRINCIPLES_STAGES = [
    ("The principle that development proceeds from the head downwards to the feet is the:",
     ["Cephalocaudal principle", "Proximodistal principle", "Principle of individual differences", "Principle of integration"], 0, "Babies control their head before they control their legs."),
    ("The principle that development proceeds from the centre of the body outwards to the extremities is the:",
     ["Proximodistal principle", "Cephalocaudal principle", "Principle of continuity", "Principle of predictability"], 0, "Control of shoulders and arms comes before control of fingers."),
    ("An infant first moves its whole body or whole arm and only later performs precise finger movements. This shows development proceeds:",
     ["From general to specific responses", "From specific to general responses", "Without any order", "Only through training"], 0, "Mass activity gives way to specific, refined responses."),
    ("Children sit before they stand, and stand before they walk. This illustrates the principle of:",
     ["A uniform, predictable sequence of development", "Individual differences in sequence", "Development without order", "Punishment and reward"], 0, "The sequence is the same for all; the rate differs."),
    ("According to the principle of individual differences:",
     ["Children follow the same sequence of development but at different rates", "All children develop at exactly the same rate", "Development has no sequence", "Only heredity matters"], 0, "Teachers must allow for different rates of development."),
    ("The principle of continuity states that development:",
     ["Is a continuous process with no sudden breaks, from conception to death", "Stops completely at intervals", "Happens only at school", "Is complete at birth"], 0, "Earlier development forms the base for later development."),
    ("The principle of interrelation (integration) means that:",
     ["Physical, mental, emotional and social aspects of development influence one another", "Each aspect develops completely separately", "Only physical development matters", "Development depends only on the environment"], 0, "E.g. poor health can affect learning and social behaviour."),
    ("Development is often described as spiral rather than linear because:",
     ["A child may seem to slip back and then move forward to a higher level", "It moves in a perfect straight line", "It repeats the same level forever", "It stops after each stage"], 0, "Progress includes periods of consolidation."),
    ("In common Indian texts, the period of infancy usually covers:",
     ["Birth to about 2 years", "2 to 6 years", "6 to 12 years", "12 to 18 years"], 0, "It is a period of very rapid growth."),
    ("The pre-school period of about 2 to 6 years is called:",
     ["Early childhood", "Later childhood", "Adolescence", "Adulthood"], 0, "Hurlock also calls it the 'pre-gang' or 'toy' age."),
    ("Hurlock called later childhood (about 6 to 12 years) the:",
     ["Gang age", "Toy age", "Age of stress and storm", "Age of retirement"], 0, "Children form peer groups (gangs) at this age."),
    ("The description of adolescence as a period of 'stress and storm' is associated with:",
     ["G. Stanley Hall", "Jean Piaget", "Ivan Pavlov", "E. L. Thorndike"], 0, "Hall wrote the influential book 'Adolescence' (1904)."),
    ("Arrange the stages of human development in the correct order:",
     ["Prenatal → infancy → early childhood → later childhood → adolescence → adulthood", "Infancy → prenatal → adolescence → early childhood → adulthood → later childhood", "Early childhood → infancy → prenatal → adolescence → later childhood → adulthood", "Prenatal → early childhood → infancy → adolescence → later childhood → adulthood"], 0, "Old age follows adulthood."),
    ("The primary school years (Classes 1–7) mostly fall in the stage of:",
     ["Later childhood", "Infancy", "Adulthood", "Prenatal period"], 0, "About 6 to 12 years."),
    ("Match the principle with its example:\na. Cephalocaudal  b. Proximodistal  c. General to specific  d. Individual differences\n1. Two children learn to read at different ages  2. Whole-hand grasp before a pincer grasp  3. Arm control before finger control  4. Head control before walking",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Principles of development help teachers predict and plan."),
    ("Because development is predictable, a teacher can:",
     ["Anticipate the kind of abilities and needs pupils will have at each stage", "Know each pupil's exact future marks", "Ignore individual differences", "Skip all early learning"], 0, "Predictability applies to the pattern, not to exact individual outcomes."),
    ("Consider the statements:\nI. All children pass through the same general sequence of development.\nII. All children develop at the same rate.\nWhich is/are correct?",
     I_II, 0, "Rates differ; the sequence is common."),
    ("Consider the statements:\nI. Development results from the interaction of heredity and environment.\nII. Development is continuous and gradual.\nWhich is/are correct?",
     I_II, 2, "Both are principles of development."),
    ("Assertion (A): A baby controls its head before it controls its legs.\nReason (R): Development follows the cephalocaudal direction.",
     AR, 0, "Head-to-foot development explains the order of motor control."),
    ("Assertion (A): Adolescence is described as a period of stress and storm.\nReason (R): The term 'gang age' was used by Hurlock for later childhood.",
     AR, 1, "Both true, but the gang-age label concerns a different stage and does not explain A."),
]

TOPICS = {
    "Growth and Development": [("1 · Growth and Development: Concept and Differences", GROWTH_DEV),
                               ("2 · Principles and Stages of Development", PRINCIPLES_STAGES)],
}
