"""Paper 1 · Educational Psychology · P1-PSY-05 Adolescence; P1-PSY-06 Individual Differences (4 sub-topics × 20).
References: E. B. Hurlock, Developmental Psychology; R. J. Havighurst, Developmental Tasks and Education; G. Stanley Hall, Adolescence (1904);
S. K. Mangal, Advanced Educational Psychology; DSERT D.El.Ed. texts; MoHFW (RKSK).
Explanations starting "PYQ pattern" follow questions that recur in KARTET / GPSTR / KPSC / KEA papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KARTET / GPSTR / KEA). "

ADOLESCENCE = [
    ("The word 'adolescence' comes from the Latin word 'adolescere', which means:",
     ["To grow to maturity", "To play", "To obey", "To learn by heart"], 0, PYQ + "Adolescence is the transition from childhood to adulthood."),
    ("Who described adolescence as a period of 'storm and stress' (stress and strain)?",
     ["G. Stanley Hall", "Jean Piaget", "Sigmund Freud", "B. F. Skinner"], 0, PYQ + "Hall's book 'Adolescence' was published in 1904."),
    ("G. Stanley Hall is also known as the:",
     ["Father of the scientific study of adolescence (and of child study in America)", "Father of behaviourism", "Father of psychoanalysis", "Founder of Gestalt psychology"], 0, "He founded the American Psychological Association in 1892."),
    ("The World Health Organization defines adolescents as people aged:",
     ["10–19 years", "13–21 years", "6–14 years", "15–24 years"], 0, PYQ + "15–24 is the UN definition of 'youth'."),
    ("Puberty refers to the:",
     ["Period of rapid physical change when a person becomes sexually mature", "Period of old age", "First year of life", "Period of formal schooling"], 0, "It marks the beginning of adolescence."),
    ("During the adolescent growth spurt, girls generally:",
     ["Begin about two years earlier than boys", "Begin about two years later than boys", "Show no growth spurt", "Grow at exactly the same time as boys"], 0, "Hence girls are often taller than boys around ages 11–13."),
    ("According to Piaget, adolescents enter the formal operational stage, in which they can:",
     ["Think abstractly and reason about hypotheses", "Only think about concrete objects", "Only use reflexes", "Not use language"], 0, PYQ + "This stage begins at about 11–12 years."),
    ("According to Erikson, the central crisis of adolescence is:",
     ["Identity vs role confusion", "Industry vs inferiority", "Trust vs mistrust", "Intimacy vs isolation"], 0, PYQ + "Adolescents ask 'Who am I?'"),
    ("Physical features such as the growth of facial hair in boys and breast development in girls are called:",
     ["Secondary sexual characteristics", "Primary reflexes", "Intelligence traits", "Learned habits"], 0, "They are brought on by sex hormones at puberty."),
    ("The first menstruation in girls is called:",
     ["Menarche", "Menopause", "Ovulation", "Puberty spurt"], 0, "It usually occurs between 10 and 15 years."),
    ("Hurlock describes adolescence as a period of:",
     ["Transition, change and search for identity, and the threshold of adulthood", "Complete emotional stability", "No physical change", "Total dependence on parents"], 0, "Hurlock also calls it a 'problem age' and a 'time of unrealism'."),
    ("Heightened emotionality and sudden mood swings in adolescence are due to:",
     ["Rapid physical and hormonal changes and new social pressures", "Lack of intelligence", "Old age", "Only poor nutrition"], 0, "This is why Hall called it 'storm and stress'."),
    ("A strong tendency towards hero-worship and daydreaming is typical of:",
     ["Adolescence", "Infancy", "Early childhood", "Old age"], 0, "Adolescents look for ideals and models."),
    ("David Elkind's term 'imaginary audience' refers to the adolescent's belief that:",
     ["Everyone is watching and judging them", "Nobody exists except themselves", "Objects have life", "Rules can never change"], 0, "It is part of adolescent egocentrism, together with the 'personal fable'."),
    ("During adolescence, the influence of which group becomes especially strong?",
     ["The peer group", "Grandparents only", "Infants", "Strangers"], 0, "Acceptance by peers matters greatly to adolescents."),
    ("Match the theorist with the idea about adolescence:\na. Stanley Hall  b. Erikson  c. Piaget  d. Elkind\n1. Imaginary audience and personal fable  2. Formal operational thinking  3. Identity vs role confusion  4. Storm and stress",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "A frequent matching question."),
    ("Consider the statements:\nI. Adolescence is a period of rapid physical growth.\nII. Adolescents cannot think abstractly.\nWhich is/are correct?",
     I_II, 0, "Abstract thinking develops in adolescence."),
    ("Consider the statements:\nI. Adolescents seek independence from parents.\nII. Adolescents are strongly influenced by their peers.\nWhich is/are correct?",
     I_II, 2, "Both are typical characteristics."),
    ("Assertion (A): Adolescence is called a period of stress and strain.\nReason (R): Rapid physical, emotional and social changes occur during this period.",
     AR, 0, "These changes cause conflict and tension."),
    ("Assertion (A): Adolescence begins at the same age for all children.\nReason (R): The onset of puberty varies from individual to individual.",
     AR, 3, "Because puberty timing varies, A is false."),
]

TASKS_EDUCATION = [
    ("The concept of 'developmental tasks' was put forward by:",
     ["Robert J. Havighurst", "Erik Erikson", "Lawrence Kohlberg", "Jean Piaget"], 0, PYQ + "He described tasks for each stage from infancy to later maturity."),
    ("According to Havighurst, successful achievement of a developmental task leads to:",
     ["Happiness and success with later tasks, while failure leads to unhappiness, social disapproval and difficulty with later tasks", "No change at all", "Only physical growth", "Punishment by teachers"], 0, PYQ + "This is Havighurst's definition of a developmental task."),
    ("According to Havighurst, developmental tasks arise from:",
     ["Physical maturation, cultural pressures of society and the individual's own values and aspirations", "Only heredity", "Only school examinations", "Only parents' income"], 0, "These are the three sources of developmental tasks."),
    ("Which of the following is a developmental task of adolescence according to Havighurst?",
     ["Achieving emotional independence from parents and other adults", "Learning to walk", "Learning to take solid food", "Adjusting to retirement"], 0, PYQ + "Learning to walk belongs to infancy; retirement to later maturity."),
    ("Which of the following is NOT one of Havighurst's developmental tasks of adolescence?",
     ["Learning to read, write and calculate", "Accepting one's physique and using the body effectively", "Preparing for an economic career", "Acquiring a set of values and an ethical system"], 0, "The 3 Rs are tasks of middle childhood."),
    ("'Achieving new and more mature relations with age-mates of both sexes' is a developmental task of:",
     ["Adolescence", "Infancy", "Early childhood", "Later maturity"], 0, "It reflects growing social maturity."),
    ("A common problem of adolescence is:",
     ["Identity confusion, peer pressure and examination stress", "Learning to crawl", "Loss of all memory", "Inability to speak"], 0, "Substance abuse and adjustment problems may also arise."),
    ("An important need of adolescents is:",
     ["Independence and recognition as a responsible person", "Constant supervision in every activity", "Complete isolation", "Avoidance of all responsibility"], 0, "Giving responsibility builds maturity."),
    ("The Rashtriya Kishor Swasthya Karyakram (RKSK), launched in 2014, is a health programme for adolescents aged:",
     ["10–19 years", "0–6 years", "20–30 years", "6–14 years"], 0, PYQ + "It covers nutrition, sexual and reproductive health, mental health, substance misuse and more."),
    ("The Adolescence Education Programme (AEP) in schools aims to:",
     ["Give adolescents accurate information and life skills about growing up, health and relationships", "Increase examination marks only", "Replace science teaching", "Teach only sports"], 0, "It is run with NCERT support in schools."),
    ("The best way for a teacher to deal with a rebellious adolescent is to:",
     ["Listen with understanding, respect their views and guide them", "Punish them publicly", "Ignore them completely", "Compare them with other pupils"], 0, "Adolescents respond to respect and fairness."),
    ("Guidance and counselling in secondary schools is important mainly because adolescents:",
     ["Face choices about careers, relationships and personal problems", "Have no problems", "Cannot talk", "Do not attend school"], 0, "Career and personal guidance help them decide wisely."),
    ("Co-curricular activities such as sports, NSS, NCC and drama help adolescents mainly to:",
     ["Channel their energy constructively and develop leadership and social skills", "Avoid studying", "Increase conflicts", "Remain isolated"], 0, "They also meet the need for recognition."),
    ("Juvenile delinquency refers to:",
     ["Law-breaking behaviour by minors (below 18 years)", "Excellence in studies", "A learning disability", "A physical illness"], 0, "Family problems and bad company are common causes."),
    ("Match the developmental task with the stage (Havighurst):\na. Learning to walk  b. Learning to read and write  c. Preparing for an economic career  d. Adjusting to retirement\n1. Later maturity  2. Adolescence  3. Middle childhood  4. Infancy and early childhood",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Stage-wise tasks are a frequent question."),
    ("Consider the statements:\nI. Havighurst's developmental tasks are the same in every culture.\nII. Failure in a developmental task can make later tasks difficult.\nWhich is/are correct?",
     I_II, 1, "Cultural pressures are one source of tasks, so they vary between societies."),
    ("Consider the statements:\nI. Adolescents need guidance about careers.\nII. Sex education should be avoided completely in schools.\nWhich is/are correct?",
     I_II, 0, "Age-appropriate adolescence education is recommended."),
    ("Assertion (A): Teachers should give adolescents responsibilities in school.\nReason (R): Adolescents need independence and recognition.",
     AR, 0, "Responsibility meets these needs."),
    ("Assertion (A): Emotional independence from parents is a developmental task of adolescence.\nReason (R): Havighurst's theory deals only with infancy.",
     AR, 2, "A is true; R is false – Havighurst covers the whole life span."),
    ("Assertion (A): Peer pressure can lead adolescents into risky behaviour.\nReason (R): Havighurst wrote 'Developmental Tasks and Education'.",
     AR, 1, "Both true, but R does not explain A."),
]

ID_MEANING = [
    ("Individual differences means that:",
     ["People differ from one another in physical, mental, emotional and social traits", "All people are exactly alike", "Only twins differ", "Differences exist only in height"], 0, PYQ + "No two individuals are exactly alike, not even identical twins."),
    ("The scientific study of individual differences is generally traced to:",
     ["Francis Galton", "Ivan Pavlov", "B. F. Skinner", "Wolfgang Köhler"], 0, PYQ + "Galton set up an anthropometric laboratory in London in 1884."),
    ("Francis Galton's book 'Hereditary Genius' (1869) argued that:",
     ["Ability runs in families and is largely inherited", "Environment alone decides ability", "Intelligence cannot be measured", "Learning happens by conditioning"], 0, "Galton was a cousin of Charles Darwin."),
    ("Differences between two different persons are called:",
     ["Inter-individual differences", "Intra-individual differences", "No differences", "Group norms"], 0, "Intra-individual differences are within one person."),
    ("A pupil is very good at mathematics but weak in drawing. This is an example of:",
     ["Intra-individual difference", "Inter-individual difference", "Group difference", "No difference"], 0, PYQ + "Abilities vary within the same person."),
    ("When a trait such as height or intelligence is measured in a large population, the scores usually form a:",
     ["Normal (bell-shaped) distribution", "Straight line", "U-shaped curve", "Single point"], 0, "Most people are near the average; few are at the extremes."),
    ("Which of the following is an area of individual differences?",
     ["Intelligence, aptitude, interest, attitude, personality and learning style", "Only height", "Only the name", "Only the date of birth"], 0, "Physical and emotional differences also exist."),
    ("The Dalton Plan of individualised instruction was developed by:",
     ["Helen Parkhurst", "Maria Montessori", "Carleton Washburne", "William Kilpatrick"], 0, PYQ + "Pupils work on monthly assignments at their own pace."),
    ("The Winnetka Plan of individualised instruction was developed by:",
     ["Carleton Washburne", "Helen Parkhurst", "John Dewey", "Froebel"], 0, "Pupils progress through self-instructional units."),
    ("Programmed instruction, which lets each learner proceed at their own pace, was developed from the work of:",
     ["B. F. Skinner", "Sigmund Freud", "Jean Piaget", "Alfred Binet"], 0, PYQ + "It uses small steps with immediate feedback."),
    ("The theory of multiple intelligences, which explains differences in kinds of ability, was proposed by:",
     ["Howard Gardner", "Charles Spearman", "Alfred Binet", "Lewis Terman"], 0, "He proposed linguistic, logical-mathematical, spatial and other intelligences."),
    ("A teacher uses pictures for some pupils, discussion for others and hands-on activities for others. This responds to differences in:",
     ["Learning styles", "Height", "Age only", "Family income only"], 0, "Visual, auditory and kinaesthetic learners benefit from varied methods."),
    ("The main educational implication of individual differences is that teachers should:",
     ["Adapt teaching methods, pace and material to learners' needs", "Teach every pupil in exactly the same way", "Ignore slow learners", "Teach only gifted children"], 0, PYQ + "This is called differentiated instruction."),
    ("Remedial teaching is provided mainly for:",
     ["Pupils who are lagging behind in particular skills", "Only gifted pupils", "Teachers", "Pupils who have left school"], 0, "Enrichment programmes are given to gifted pupils."),
    ("Match the plan or theory with its proponent:\na. Dalton Plan  b. Winnetka Plan  c. Programmed learning  d. Multiple intelligences\n1. Howard Gardner  2. B. F. Skinner  3. Carleton Washburne  4. Helen Parkhurst",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "All address individual differences."),
    ("Consider the statements:\nI. Individual differences can be measured with psychological tests.\nII. Every pupil in a class learns at the same rate.\nWhich is/are correct?",
     I_II, 0, "Rates of learning differ widely."),
    ("Consider the statements:\nI. Most human traits are normally distributed.\nII. Intra-individual differences exist within the same person.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Ability grouping is one way of meeting individual differences.\nReason (R): Pupils of similar ability can be taught at a suitable pace.",
     AR, 0, "Though it must be used carefully to avoid labelling."),
    ("Assertion (A): Individual differences are found only in intelligence.\nReason (R): Individuals differ in interests, attitudes and personality too.",
     AR, 3, "Because differences exist in many traits, A is false."),
    ("Assertion (A): Teachers should know the individual differences among their pupils.\nReason (R): Galton set up an anthropometric laboratory in 1884.",
     AR, 1, "Both true, but R does not explain A."),
]

HEREDITY_ENV = [
    ("Heredity refers to:",
     ["The transmission of traits from parents to offspring through genes", "The influence of school and friends", "Nutrition after birth", "Training given by teachers"], 0, PYQ + "Heredity is fixed at conception."),
    ("The 'father of genetics', who discovered the laws of inheritance through experiments on pea plants, is:",
     ["Gregor Mendel", "Charles Darwin", "Francis Galton", "Hugo de Vries"], 0, PYQ + "His work was published in 1866."),
    ("A normal human body cell contains:",
     ["46 chromosomes (23 pairs)", "23 chromosomes", "44 chromosomes", "48 chromosomes"], 0, PYQ + "Each gamete (egg or sperm) carries 23."),
    ("The sex of a child is determined by:",
     ["The chromosome (X or Y) contributed by the father's sperm", "The mother's egg alone", "The mother's diet", "The season of birth"], 0, "XX gives a girl and XY a boy."),
    ("Genes are made of:",
     ["DNA", "Protein only", "Fat", "Starch"], 0, "Genes are segments of DNA on chromosomes."),
    ("Environment, as a cause of individual differences, includes:",
     ["All external influences from conception onwards – home, nutrition, school, culture and society", "Only the genes", "Only the colour of the eyes", "Only the blood group"], 0, "It begins in the mother's womb."),
    ("Identical (monozygotic) twins are important in studying heredity and environment because they:",
     ["Have the same heredity, so differences between them reflect environment", "Always live in different countries", "Have different genes", "Never differ in any way"], 0, PYQ + "Twins reared apart are especially informative."),
    ("The phrase 'nature versus nurture' was popularised by:",
     ["Francis Galton", "John B. Watson", "Gregor Mendel", "Arnold Gesell"], 0, "Nature = heredity; nurture = environment."),
    ("The Jukes family study (1877), used to argue that criminality runs in families, was conducted by:",
     ["Richard Dugdale", "Henry Goddard", "Francis Galton", "Lewis Terman"], 0, PYQ + "Critics point out that the environment was also poor across generations."),
    ("The Kallikak family study (1912) was conducted by:",
     ["Henry Goddard", "Richard Dugdale", "Alfred Binet", "Charles Spearman"], 0, PYQ + "It compared two lines of descendants of one man."),
    ("'Give me a dozen healthy infants … and I'll guarantee to take any one at random and train him to become any type of specialist' – this claim for environment was made by:",
     ["John B. Watson", "Francis Galton", "Gregor Mendel", "Sigmund Freud"], 0, PYQ + "Watson was the founder of behaviourism."),
    ("R. S. Woodworth described development as the product of heredity and environment (not their sum). This means:",
     ["If either factor is zero, there is no development – both are essential", "Heredity alone decides development", "Environment alone decides development", "They have no effect"], 0, PYQ + "Development = Heredity × Environment."),
    ("Galton's 'law of regression' states that:",
     ["Children of very tall (or very able) parents tend to be closer to the average than their parents", "Children are always exactly like their parents", "Traits skip every generation", "Only the father's traits are inherited"], 0, "Extreme traits tend to move back towards the mean."),
    ("The law of variation states that:",
     ["Children differ from their parents and from each other", "Children are copies of their parents", "Brothers and sisters are identical", "Only twins differ"], 0, "Different combinations of genes cause variation."),
    ("Which statement about heredity and environment is most widely accepted today?",
     ["Both interact; neither alone explains development", "Only heredity matters", "Only environment matters", "Neither matters"], 0, "Heredity sets potential; environment decides how far it is realised."),
    ("Match the person with the contribution:\na. Mendel  b. Galton  c. Watson  d. Goddard\n1. Kallikak family study  2. Extreme environmentalism  3. Hereditary Genius  4. Laws of inheritance",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "A common matching question."),
    ("Consider the statements:\nI. A teacher can change a pupil's heredity.\nII. A teacher can provide a rich learning environment.\nWhich is/are correct?",
     I_II, 1, "Heredity is fixed; environment can be improved."),
    ("Consider the statements:\nI. Heredity sets the limits of possible development.\nII. Environment determines how far that potential is realised.\nWhich is/are correct?",
     I_II, 2, "Both together describe the interaction view."),
    ("Assertion (A): Differences between identical twins reared apart are due mainly to environment.\nReason (R): Identical twins have the same genes.",
     AR, 0, "With heredity held constant, remaining differences come from environment."),
    ("Assertion (A): Environment has no effect before birth.\nReason (R): Environmental influences begin at conception, e.g. the mother's nutrition and health.",
     AR, 3, "Because environment acts from conception, A is false."),
]

TOPICS = {
    "Adolescence": [("1 · Adolescence: Concept, Characteristics and Development", ADOLESCENCE),
                    ("2 · Developmental Tasks, Problems, Needs and Education", TASKS_EDUCATION)],
    "Individual Differences": [("1 · Individual Differences: Meaning and Areas", ID_MEANING),
                               ("2 · Causes: Heredity and Environment", HEREDITY_ENV)],
}
