"""Paper 1 · Educational Psychology · P1-PSY-13 Memory (2 sub-topics × 20).
Coverage (planner): meaning, importance, types, process, techniques.
References: S. K. Mangal, Advanced Educational Psychology; Woolfolk, Educational Psychology; Atkinson & Shiffrin (1968), Baddeley &
Hitch (1974), Ebbinghaus, Über das Gedächtnis (1885); DSERT D.El.Ed. psychology texts. One REAL previous-year question (KSET 2023
Education, on the memory level of teaching) is used; its answer was worked out by ExamSim. The rest are "PYQ pattern" questions on
themes common in KSET Education / TET / GPSTR papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KSET Education / TET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

PROCESS_TYPES = [
    ("Memory is best defined as:",
     ["The ability to encode, store and later retrieve information and experiences", "The ability to see clearly", "A type of intelligence test", "Forgetting what is learnt"], 0,
     PYQ + "Without memory, no learning would be possible."),
    ("The correct sequence of the memory process is:",
     ["Encoding (learning) → Storage (retention) → Retrieval (recall / recognition)", "Retrieval → Storage → Encoding", "Storage → Encoding → Retrieval", "Recall → Learning → Retention"], 0,
     "Older texts list four steps: learning, retention, recall and recognition."),
    ("According to the Atkinson–Shiffrin (multi-store) model, information passes through:",
     ["Sensory memory → Short-term memory → Long-term memory", "Long-term → Short-term → Sensory", "Only long-term memory", "Working memory → sensory memory"], 0,
     PYQ + "Attention moves information from sensory to short-term memory; rehearsal moves it to long-term memory."),
    ("Iconic memory, which holds visual images for less than a second, is a kind of:",
     ["Sensory memory", "Long-term memory", "Semantic memory", "Procedural memory"], 0, "Echoic memory holds sounds for 2–4 seconds."),
    ("George Miller's 'magical number' for the capacity of short-term memory is:",
     ["7 ± 2 items", "3 ± 1 items", "20 items", "Unlimited"], 0, PYQ + "Information lasts about 15–30 seconds unless rehearsed."),
    ("Grouping digits of a phone number into 98450-12345 to remember them is called:",
     ["Chunking", "Repression", "Interference", "Decay"], 0, "Chunking increases the amount held in short-term memory."),
    ("The model of working memory with a central executive, phonological loop and visuospatial sketchpad was proposed by:",
     ["Baddeley and Hitch", "Atkinson and Shiffrin", "Ebbinghaus", "Piaget"], 0, PYQ + "The episodic buffer was added in 2000."),
    ("Memory for personal experiences and events, such as one's first day at school, is:",
     ["Episodic memory", "Semantic memory", "Procedural memory", "Sensory memory"], 0, "Endel Tulving distinguished episodic and semantic memory."),
    ("Memory of facts and general knowledge, such as 'Bengaluru is the capital of Karnataka', is:",
     ["Semantic memory", "Episodic memory", "Procedural memory", "Iconic memory"], 0, PYQ + "Episodic and semantic are both explicit (declarative) memory."),
    ("Knowing how to ride a bicycle or type without looking is stored as:",
     ["Procedural (implicit) memory", "Episodic memory", "Semantic memory", "Echoic memory"], 0, "Procedural memory is shown in performance rather than words."),
    ("Recall differs from recognition in that recall:",
     ["Requires producing the information without the item being present", "Only needs identifying a familiar item", "Is easier than recognition", "Needs no memory"], 0,
     PYQ + "Essay questions test recall; multiple-choice questions test recognition."),
    ("Memorising the exact words of a poem by repeating it again and again is:",
     ["Rote memory", "Logical memory", "Episodic memory", "Sensory memory"], 0, "Logical (meaningful) memory relates new material to what is understood."),
    ("Which type of memory is generally more durable and useful in education?",
     ["Logical (meaningful) memory", "Rote memory", "Iconic memory", "Echoic memory"], 0, PYQ + "Understanding leads to better retention and transfer."),
    ("Who propounded the Memory Level model of teaching?",
     ["Morrison", "Herbart", "Hunt", "All of the above"], 1,
     "Herbart – memory level; Morrison – understanding level; Hunt (and Bigge) – reflective level." + NOTE, "KSET 2023 Education · Q44"),
    ("A person who can recall a page of text in great detail after a brief look is said to have:",
     ["Eidetic (photographic) memory", "Amnesia", "Retroactive interference", "Repression"], 0, "It is more common in children than adults."),
    ("Consider the statements:\nI. Short-term memory has limited capacity and duration.\nII. Long-term memory has practically unlimited capacity.",
     I_II, 2, "Both are standard features of the multi-store model."),
    ("Assertion (A): Rehearsal helps transfer information to long-term memory.\nReason (R): Information in short-term memory fades within about 20–30 seconds without rehearsal.",
     AR, 0, "Elaborative rehearsal (linking to meaning) works better than simple repetition."),
    ("Assertion (A): Sensory memory stores information for several hours.\nReason (R): Sensory memory holds a brief copy of what the senses receive.",
     AR, 3, "Sensory memory lasts only a fraction of a second to a few seconds."),
    ("Match:\na. Sensory memory  b. Short-term memory  c. Episodic memory  d. Procedural memory\n1. Less than a few seconds  2. About 7 ± 2 items  3. Personal events  4. Skills and habits",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Types of memory are often matched."),
    ("The feeling of being sure that you know a word but cannot quite recall it is called the:",
     ["Tip-of-the-tongue phenomenon", "Serial position effect", "Zeigarnik effect", "Eidetic image"], 0, "It shows that the memory is stored but retrieval fails."),
]

FORGET_TECH = [
    ("The 'curve of forgetting', showing rapid forgetting soon after learning, was given by:",
     ["Hermann Ebbinghaus", "Jean Piaget", "B. F. Skinner", "Wolfgang Köhler"], 0, PYQ + "He used nonsense syllables to study memory (1885)."),
    ("According to Ebbinghaus's curve, most forgetting occurs:",
     ["Within the first few hours after learning", "After one year", "Only after sleep", "Evenly over time"], 0, "Revision soon after learning slows forgetting."),
    ("When new learning interferes with the recall of old learning, it is called:",
     ["Retroactive interference (inhibition)", "Proactive interference", "Repression", "Decay"], 0, PYQ + "'Retro' = backward."),
    ("When old learning interferes with recall of new learning (e.g. writing last year's date in January), it is:",
     ["Proactive interference", "Retroactive interference", "Amnesia", "Chunking"], 0, "'Pro' = forward."),
    ("According to Freud, unpleasant memories may be pushed into the unconscious. This is called:",
     ["Repression (motivated forgetting)", "Decay", "Chunking", "Rehearsal"], 0, PYQ + "It is a defence mechanism."),
    ("The theory that memories fade simply because they are not used is the:",
     ["Decay (trace decay / disuse) theory", "Interference theory", "Retrieval-cue theory", "Repression theory"], 0, "Thorndike's law of disuse is similar."),
    ("Loss of memory due to brain injury or disease is called:",
     ["Amnesia", "Aphasia", "Dyslexia", "Ataxia"], 0, PYQ + "Retrograde amnesia – loss of past memories; anterograde – inability to form new ones."),
    ("In a list of words, items at the beginning and at the end are remembered better than those in the middle. This is the:",
     ["Serial position effect (primacy and recency)", "Zeigarnik effect", "Halo effect", "Placebo effect"], 0, "Primacy reflects long-term memory; recency reflects short-term memory."),
    ("The tendency to remember unfinished tasks better than completed ones is the:",
     ["Zeigarnik effect", "Recency effect", "Primacy effect", "Pygmalion effect"], 0, PYQ + "Named after Bluma Zeigarnik."),
    ("Learning a long poem a few stanzas at a time and then joining them is the:",
     ["Part method", "Whole method", "Massed method", "Rote method"], 0, "For short, meaningful material the whole method is usually better."),
    ("Spacing study sessions over several days instead of cramming in one long session is called:",
     ["Distributed (spaced) practice", "Massed practice", "Overlearning", "Rote learning"], 0, PYQ + "Distributed practice gives better long-term retention."),
    ("Continuing to practise even after material has been learnt perfectly is called:",
     ["Overlearning", "Underlearning", "Forgetting", "Chunking"], 0, "Overlearning reduces forgetting."),
    ("Remembering the colours of the rainbow through 'VIBGYOR' is an example of a:",
     ["Mnemonic device (acronym)", "Repression", "Proactive interference", "Rote drill only"], 0, PYQ + "Other mnemonics: rhymes, method of loci, keyword method."),
    ("The 'method of loci' memory technique involves:",
     ["Imagining items placed at familiar locations along a route", "Repeating aloud", "Writing in capitals", "Studying at night only"], 0, "It dates back to ancient Greek orators."),
    ("Testing yourself by trying to recall information, rather than re-reading it, is called:",
     ["Retrieval practice (testing effect)", "Massed reading", "Repression", "Passive review"], 0, PYQ + "It is one of the most effective study strategies."),
    ("SQ3R, a study method that improves understanding and memory, stands for:",
     ["Survey, Question, Read, Recite, Review", "Study, Quiz, Read, Repeat, Rest", "Search, Question, Record, Rewrite, Relax", "See, Question, Remember, Repeat, Recall"], 0,
     "It was proposed by Francis Robinson."),
    ("Consider the statements:\nI. Meaningful material is retained longer than nonsense material.\nII. Sleep after learning helps memory consolidation.",
     I_II, 2, "Both are supported by research."),
    ("Assertion (A): A teacher should revise a lesson soon after teaching it.\nReason (R): Forgetting is most rapid immediately after learning.",
     AR, 0, "Periodic revision follows the forgetting curve."),
    ("Assertion (A): Massed practice (cramming) gives the best long-term retention.\nReason (R): Distributed practice spreads learning over several sessions.",
     AR, 3, "Distributed practice gives better long-term retention."),
    ("Match:\na. Ebbinghaus  b. Retroactive inhibition  c. Mnemonics  d. Overlearning\n1. Curve of forgetting  2. New learning blocks old  3. Memory aids like VIBGYOR  4. Practice beyond mastery",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Forgetting and memory-technique matching."),
]

TOPICS = {
    "Memory": [("1 · Meaning, Process and Types of Memory", PROCESS_TYPES),
               ("2 · Forgetting and Techniques for Improving Memory", FORGET_TECH)],
}
