"""Paper 1 · Educational Psychology · P1-PSY-04 Childhood (2 sub-topics × 20).
References: E. B. Hurlock, Developmental Psychology / Child Development; J. Piaget; E. Erikson; NEP 2020; NCF-FS 2022; DSERT D.El.Ed. child psychology texts."""
from packlib import AR, I_II

CHILDHOOD_CONCEPT = [
    ("In developmental psychology, 'childhood' usually refers to the period:",
     ["From the end of infancy (about 2 years) until the onset of puberty (about 11–13 years)", "From conception to birth", "From birth to 2 weeks", "From puberty to 18 years"], 0, "It is commonly divided into early childhood (2–6) and later childhood (6 to puberty)."),
    ("Early childhood is generally taken to span the ages of about:",
     ["2 to 6 years", "6 to 12 years", "0 to 2 years", "12 to 18 years"], 0, "It ends roughly when the child enters formal schooling."),
    ("Later (late) childhood is generally taken to span the ages of about:",
     ["6 years to sexual maturity (about 11–13 years)", "2 to 6 years", "Birth to 2 years", "18 to 21 years"], 0, "It covers the primary school years."),
    ("Hurlock called early childhood the 'pre-gang age' because:",
     ["Children are learning the basics of social behaviour but do not yet form organised peer groups", "Children form strong gangs", "Children avoid all play", "Children stop speaking"], 0, "Organised peer groups ('gangs') appear in later childhood."),
    ("Parents often call early childhood the 'troublesome' or 'problem' age because:",
     ["The child shows stubbornness, negativism and disobedience while asserting independence", "The child sleeps all day", "The child cannot move", "The child has no emotions"], 0, "Growing independence brings frequent clashes with adults."),
    ("Early childhood is called the 'toy age' because:",
     ["Children spend much of their play time with toys", "Children earn money", "Children stop playing", "Children read only books"], 0, "Interest in toys declines as the child reaches school age."),
    ("Early childhood is called the 'questioning age' because:",
     ["Curiosity leads the child to ask many 'why' and 'how' questions", "The child answers exam questions", "The child refuses to speak", "Teachers question the child all day"], 0, "Questions show the child's growing curiosity and language."),
    ("Early childhood is called the 'imitative age' because children:",
     ["Copy the speech and actions of the people around them", "Invent new languages", "Avoid all adults", "Learn only from books"], 0, "This is why adult models matter so much."),
    ("Early childhood is often called the 'preschool age' by educators because:",
     ["It prepares the child for formal schooling through play-based learning", "Children are in college", "Children have finished primary school", "It is the age of higher education"], 0, "Anganwadis and pre-primary classes serve this stage."),
    ("Hurlock called later childhood the 'gang age' because:",
     ["Children form peer groups and become strongly influenced by them", "Children prefer to be alone", "Children depend only on parents", "Children lose interest in friends"], 0, "Belonging to the group becomes very important."),
    ("Later childhood is called the 'elementary school age' by educators and the 'troublesome age' by parents. Psychologists also call it the:",
     ["Age of conformity (to the peer group)", "Pre-gang age", "Toy age", "Age of creativity only"], 0, "Children want to look and behave like their peers."),
    ("Hurlock notes that parents call later childhood the 'sloppy age' because:",
     ["Children tend to be careless about their appearance and belongings", "Children love bathing", "Children stay indoors", "Children only read"], 0, "Play and peer activities take priority over neatness."),
    ("Freud called later childhood (about 6 years to puberty) the:",
     ["Latency stage", "Oral stage", "Anal stage", "Genital stage"], 0, "Sexual interests are said to be dormant while social and intellectual skills grow."),
    ("Erikson's psychosocial crisis of the primary school years (about 6–12 years) is:",
     ["Industry vs inferiority", "Trust vs mistrust", "Identity vs role confusion", "Intimacy vs isolation"], 0, "Success in school tasks gives a sense of competence."),
    ("Erikson's crisis of the preschool years (about 3–6 years) is:",
     ["Initiative vs guilt", "Industry vs inferiority", "Autonomy vs shame and doubt", "Integrity vs despair"], 0, "Children plan and start activities; too much criticism causes guilt."),
    ("Childhood is considered important in education mainly because:",
     ["The foundations of personality, language, habits and learning are laid in it", "Nothing important happens then", "Children cannot learn before 12", "Only physical growth happens in childhood"], 0, "Early experiences have long-lasting effects."),
    ("Match the label with the period of childhood (Hurlock):\na. Pre-gang age  b. Gang age  c. Toy age  d. Age of conformity\n1. Children want to look and act exactly like their peers  2. Much play time is spent with toys  3. Children form organised peer groups  4. Children learn the basics of social behaviour but have no organised groups",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Pre-gang and toy age: early childhood; gang age and conformity: later childhood."),
    ("Consider the statements:\nI. Early childhood is called the questioning age.\nII. Later childhood is called the pre-gang age.\nWhich is/are correct?",
     I_II, 0, "Later childhood is the gang age; early childhood is the pre-gang age."),
    ("Assertion (A): Later childhood is called the gang age.\nReason (R): In this period children form peer groups and want to be accepted by them.",
     AR, 0, "Peer acceptance becomes very important."),
    ("Assertion (A): Early childhood is called the toy age.\nReason (R): Freud called early childhood the latency stage.",
     AR, 2, "A is true; R is false – Freud's latency stage is later childhood."),
]

CHILDHOOD_DEVELOPMENT = [
    ("According to Piaget, a child of about 2–7 years is in the:",
     ["Pre-operational stage", "Sensorimotor stage", "Concrete operational stage", "Formal operational stage"], 0, "Language and symbols grow, but thinking is not yet logical."),
    ("According to Piaget, a child of about 7–11 years is in the:",
     ["Concrete operational stage", "Pre-operational stage", "Formal operational stage", "Sensorimotor stage"], 0, "Logical thinking about concrete objects develops."),
    ("A 4-year-old believes that the sun follows her because it 'wants to'. This is an example of:",
     ["Animism", "Conservation", "Reversibility", "Hypothetical reasoning"], 0, "Pre-operational children give life and feelings to non-living things."),
    ("A pre-operational child thinks that everyone sees the world as she does. Piaget called this:",
     ["Egocentrism", "Decentration", "Seriation", "Object permanence"], 0, "The three-mountain task demonstrated it."),
    ("A child understands that the amount of water stays the same when poured into a taller, thinner glass. This ability, typical of the concrete operational stage, is:",
     ["Conservation", "Animism", "Centration", "Symbolic play"], 0, "It depends on reversibility and decentration."),
    ("Arranging sticks in order of length, which children can do well in the concrete operational stage, is called:",
     ["Seriation", "Animism", "Egocentrism", "Artificialism"], 0, "Classification is another concrete operational skill."),
    ("Focusing on only one feature of a situation (for example, the height of water) while ignoring others is called:",
     ["Centration", "Conservation", "Decentration", "Classification"], 0, "It explains why pre-operational children fail conservation tasks."),
    ("According to Kohlberg, most children below about 9 years judge right and wrong mainly by:",
     ["Punishment and reward (the pre-conventional level)", "Universal ethical principles", "Social contract", "Law and order only"], 0, "Moral reasoning is based on consequences to oneself."),
    ("Which kind of play, in which a child pretends a stick is a horse, is typical of early childhood?",
     ["Symbolic (make-believe) play", "Games with rules only", "Solitary reading", "Competitive sports"], 0, "It shows the child's growing ability to use symbols."),
    ("Games with rules, such as kho-kho and kabaddi, become popular in:",
     ["Later childhood", "Infancy", "Prenatal period", "Early infancy"], 0, "Children now understand and follow shared rules."),
    ("Under NEP 2020, the Foundational Stage covers the age group:",
     ["3 to 8 years (three years of pre-school plus Classes 1 and 2)", "6 to 14 years", "11 to 14 years", "14 to 18 years"], 0, "NEP 2020 introduced the 5 + 3 + 3 + 4 structure."),
    ("NEP 2020 names the early childhood component of education as:",
     ["ECCE – Early Childhood Care and Education", "RTE – Right to Education", "SSA – Sarva Shiksha Abhiyan", "RMSA"], 0, "It aims at universal access to quality ECCE."),
    ("The National Mission on Foundational Literacy and Numeracy launched in 2021 is called:",
     ["NIPUN Bharat", "Samagra Shiksha", "PM POSHAN", "DIKSHA"], 0, "It aims for every child to achieve FLN by the end of Grade 3."),
    ("The Right of Children to Free and Compulsory Education Act, 2009 covers children aged:",
     ["6 to 14 years", "3 to 8 years", "0 to 6 years", "14 to 18 years"], 0, "It came into force on 1 April 2010."),
    ("Educationally, the most suitable approach for early childhood is:",
     ["Play-based, activity-based learning", "Long lectures", "Written examinations every week", "Memorising textbooks"], 0, "Children learn through play, exploration and talk."),
    ("A primary teacher uses bottle caps and beads for addition because children in later childhood:",
     ["Think logically about concrete, tangible objects", "Think only in abstract terms", "Cannot count", "Learn only by reading"], 0, "Abstract reasoning comes later, in the formal operational stage."),
    ("Match the Piagetian concept with its meaning:\na. Animism  b. Egocentrism  c. Conservation  d. Seriation\n1. Arranging items in order  2. Quantity stays the same despite change in shape  3. Seeing things only from one's own view  4. Giving life to non-living things",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "The first two are pre-operational; the last two concrete operational."),
    ("Consider the statements:\nI. Children in the concrete operational stage can reason about abstract hypothetical problems easily.\nII. Children in the concrete operational stage can classify objects.\nWhich is/are correct?",
     I_II, 1, "Hypothetical reasoning belongs to the formal operational stage (11+)."),
    ("Assertion (A): Pre-operational children fail conservation tasks.\nReason (R): They centre on one feature of a situation and lack reversibility.",
     AR, 0, "Both limitations explain the failure."),
    ("Assertion (A): Under NEP 2020, the Foundational Stage begins at age 6.\nReason (R): NEP 2020 brings pre-school into the Foundational Stage.",
     AR, 3, "The stage begins at 3 because it includes three years of pre-school; A is false."),
]

TOPICS = {
    "Childhood": [("1 · Childhood: Concept, Characteristics and Importance", CHILDHOOD_CONCEPT),
                  ("2 · Development in Childhood and Its Education", CHILDHOOD_DEVELOPMENT)],
}
