"""Paper 1 · Educational Psychology · P1-PSY-10 Learning & Maturation (2 sub-topics × 20).
Coverage (planner): learning – meaning & characteristics; maturation – meaning & importance.
References: S. K. Mangal, Advanced Educational Psychology; Crow & Crow, Educational Psychology; Arnold Gesell's maturation studies;
DSERT D.El.Ed. texts. Real previous-year questions (exact wording, `source` = paper and question number) come from the KSET
Education papers (2023, 2025) and the GFGC 2021 Education paper; KEA has not published keys for them, so their answers are
worked out by ExamSim. Learning theories (Thorndike, Pavlov, Skinner, Köhler, Bandura) come later as PSY-17/18."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KSET / GPSTR / KARTET). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

LEARNING = [
    # --- real previous-year questions ---
    ("The purpose of learning is",
     ["Storing new knowledge in the mind", "Acquiring more information", "Utilize old experiences", "Modification of behaviour"], 3,
     "Learning is defined as a relatively lasting modification of behaviour through experience." + NOTE,
     "KSET 2025 Education · Q24"),
    ("Given below are two statements, One labelled as Assertion (A) and the other labelled as Reason (R).\nAssertion (A): Motivation is important in the process of teaching & learning.\nReason (R): Motivation energizes the person so that he reaches the goal.",
     ["Both (A) & (R) are true and (R) is the correct explanation of (A).", "Both (A) & (R) are true but (R) is not the correct explanation of (A).", "(A) is true but (R) is false.", "(A) is false but (R) is true."], 0,
     "Motivation arouses, sustains and directs behaviour towards a goal, which is why it matters for learning." + NOTE,
     "GFGC 2021 Education · Q31"),
    ("According to Cognitive Theory, learning is primarily influenced by:",
     ["Rewards and punishments", "Observational learning", "Mental processes and understanding", "Social interactions"], 2,
     "Cognitive theories stress perception, thinking and understanding; rewards belong to behaviourism, observation to social learning." + NOTE,
     "KSET 2023 Education · Q6"),
    ("Latent learning is a concept enunciated by",
     ["Hull", "Piaget", "Tolman", "Skinner"], 2,
     "E. C. Tolman's rats learned a maze without reward and showed it only when food was later offered." + NOTE,
     "GFGC 2021 Education · Q28"),
    # --- new questions ---
    ("'Learning is the modification of behaviour through experience and training.' This definition was given by:",
     ["Gates and others", "Sigmund Freud", "Jean Piaget", "Alfred Binet"], 0,
     PYQ + "Probably the most frequently quoted definition of learning."),
    ("Which of the following changes in behaviour is NOT learning?",
     ["Changes due to fatigue, drugs or illness", "Learning to ride a bicycle", "Acquiring a new word", "Developing a habit of punctuality"], 0,
     PYQ + "Learning is a relatively permanent change due to experience, not temporary states or maturation."),
    ("Which is a characteristic of learning?",
     ["It is a continuous, lifelong and universal process", "It happens only in school", "It stops at the age of 18", "It never brings change in behaviour"], 0,
     "Learning is also purposeful, active and transferable."),
    ("A graph that shows a learner's progress over successive trials or time is called a:",
     ["Learning curve", "Normal curve", "Bell curve of intelligence", "Growth chart"], 0,
     PYQ + "Its shape reveals the rate of learning."),
    ("A flat stretch in a learning curve, where there is little or no progress for some time, is called a:",
     ["Plateau", "Peak", "Slope", "Valley"], 0,
     PYQ + "It is usually followed by further progress."),
    ("Which is a common cause of a plateau in learning?",
     ["Fatigue, loss of interest or a faulty method of learning", "Too much motivation", "Perfect teaching", "Learning only easy material"], 0,
     "Teachers can remove plateaus by changing methods and renewing motivation."),
    ("A learning curve that rises steeply at first and then flattens out (rapid early progress) is called:",
     ["Negatively accelerated (convex)", "Positively accelerated (concave)", "S-shaped", "A straight line"], 0,
     "Positively accelerated curves show slow early progress that later speeds up."),
    ("Which is a factor related to the LEARNER that affects learning?",
     ["Motivation, readiness, health and intelligence", "The colour of the classroom walls only", "The number of school buses", "The teacher's salary"], 0,
     PYQ + "Teacher-related, content-related and environmental factors also matter."),
    ("The principle 'learning by doing' is mainly associated with:",
     ["John Dewey", "Ivan Pavlov", "Sigmund Freud", "Charles Spearman"], 0,
     PYQ + "Dewey stressed activity and experience in education."),
    ("Learning that happens without any intention to learn, e.g. remembering an advertisement jingle, is:",
     ["Incidental learning", "Formal learning", "Programmed learning", "Rote learning only"], 0,
     "It happens as a by-product of other activity."),
    ("Learning that takes place in a planned, structured setting such as a school with set curriculum and certification is:",
     ["Formal learning", "Informal learning", "Incidental learning", "Latent learning"], 0,
     "Non-formal learning, such as adult literacy classes, is organised but flexible."),
    ("In a learner-centred classroom, the teacher acts mainly as a:",
     ["Facilitator and guide of learning", "Only a lecturer", "Strict controller of every action", "Passive observer"], 0,
     "NCF 2005 stresses the learner's active construction of knowledge."),
    ("Match the psychologist with the definition of learning:\na. Gates  b. Crow and Crow  c. Woodworth  d. Skinner\n1. A process of progressive behaviour adaptation  2. Any activity that develops the individual and makes later behaviour different  3. Acquisition of habits, knowledge and attitudes  4. Modification of behaviour through experience and training",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Definition matching appears in TET and KSET papers."),
    ("Consider the statements:\nI. Learning is a lifelong process.\nII. Every change in behaviour is learning.\nWhich is/are correct?",
     I_II, 0, "Changes due to maturation, fatigue or drugs are not learning."),
    ("Assertion (A): Learning brings about a relatively permanent change in behaviour.\nReason (R): Learning results from experience and practice.",
     AR, 0, "That is why temporary changes are excluded."),
    ("Assertion (A): A plateau means that the learner has reached the final limit of learning.\nReason (R): A plateau is a period of little apparent progress in a learning curve.",
     AR, 3, "Progress usually resumes after a plateau, so A is false."),
]

MATURATION = [
    ("Maturation refers to:",
     ["The natural unfolding of inherited potential through growth, without special training", "Changes caused by practice and teaching", "Memorising facts", "Learning from books"], 0,
     PYQ + "It depends mainly on heredity and follows a fixed sequence."),
    ("The psychologist best known for studies of maturation, including the co-twin control (stair-climbing) experiment, is:",
     ["Arnold Gesell", "B. F. Skinner", "Albert Bandura", "Edward Thorndike"], 0,
     PYQ + "Twin T trained early, twin C trained later caught up quickly."),
    ("Gesell's co-twin experiment showed that:",
     ["Training given before a child is maturationally ready gives little lasting advantage", "Early training always gives a permanent advantage", "Maturation has no role in learning", "Twins never learn at the same rate"], 0,
     "Readiness depends on maturation."),
    ("Maturation depends mainly on ____, while learning depends mainly on ____.",
     ["heredity; experience and environment", "experience; heredity", "teaching; food", "books; play"], 0,
     PYQ + "Both interact in development."),
    ("Which of the following is an example of maturation rather than learning?",
     ["A baby beginning to walk", "Learning to type", "Learning to ride a bicycle", "Learning the multiplication table"], 0,
     PYQ + "Walking appears when the nervous and muscular systems are ready."),
    ("The breaking of the voice at puberty is mainly due to:",
     ["Maturation", "Learning", "Training", "Imitation"], 0,
     "It is a biological change that does not need practice."),
    ("Which change is due to maturation and not to learning?",
     ["The appearance of permanent teeth", "Learning to swim", "Speaking a second language", "Solving equations"], 0,
     "It happens with age, without any teaching."),
    ("The relationship between learning and maturation is best described as:",
     ["Learning depends on maturation; a child learns best when the necessary maturation has taken place", "They are unrelated", "Maturation depends on schooling alone", "Learning always comes before maturation"], 0,
     PYQ + "Maturation sets the limit; learning fills it."),
    ("For a teacher, the main educational importance of maturation is that:",
     ["The curriculum and methods should match the pupils' level of maturity", "All children should be taught the same thing at the same age regardless of readiness", "Maturation can be speeded up by punishment", "It has no importance in teaching"], 0,
     "Premature teaching wastes effort and may cause frustration."),
    ("'Readiness' for learning depends on:",
     ["Maturation, motivation and previous learning", "Only the teacher's wish", "Only the child's age in years", "Only the textbook"], 0,
     PYQ + "Reading readiness is a classic example."),
    ("Which statement about maturation is TRUE?",
     ["It is internal, follows a fixed sequence and is largely the same for all members of a species", "It requires special training", "It occurs only in adults", "It can be skipped by practice"], 0,
     "Individual differences appear only in its rate."),
    ("Development proceeding from the head downwards to the feet is called the:",
     ["Cephalocaudal principle", "Proximodistal principle", "Principle of individual differences", "Principle of integration"], 0,
     PYQ + "Proximodistal development proceeds from the centre of the body outwards."),
    ("A child gains control of the arms before control of the fingers. This illustrates the:",
     ["Proximodistal principle", "Cephalocaudal principle", "Principle of learning by doing", "Law of effect"], 0,
     "Control spreads from the central axis to the extremities."),
    ("Forcing a child to learn to write before the hand muscles are mature is likely to:",
     ["Waste effort and cause frustration", "Make the child a genius", "Speed up maturation", "Have no effect at all"], 0,
     "Learning cannot go beyond the level permitted by maturation."),
    ("'Growth' as distinct from 'maturation' usually refers to:",
     ["Quantitative increase in size, height and weight", "Learning new skills", "Changes in attitudes", "Moral development only"], 0,
     "Development is the broader, qualitative and quantitative change."),
    ("Match the term with its meaning:\na. Maturation  b. Learning  c. Readiness  d. Growth\n1. Quantitative increase in size  2. Being prepared to learn something  3. Change in behaviour through experience  4. Natural unfolding of inherited traits",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Term matching is common in TET papers."),
    ("Consider the statements:\nI. Maturation is largely controlled by heredity.\nII. Learning is completely independent of maturation.\nWhich is/are correct?",
     I_II, 0, "Learning depends on maturation."),
    ("Assertion (A): Teaching reading too early often wastes effort.\nReason (R): Learning depends on reaching a suitable level of maturation.",
     AR, 0, "Readiness must come first."),
    ("Assertion (A): Maturation requires practice and training.\nReason (R): Maturation is the natural unfolding of inherited potential.",
     AR, 3, "Maturation happens without training, so A is false."),
    ("Which pair correctly matches the process with its example?",
     ["Maturation – crawling; Learning – reciting a poem", "Maturation – reciting a poem; Learning – crawling", "Maturation – typing; Learning – teething", "Maturation – swimming; Learning – walking"], 0,
     "Crawling appears with readiness of muscles; reciting needs practice."),
]

TOPICS = {
    "Learning & Maturation": [("1 · Learning – Meaning, Characteristics and Factors", LEARNING),
                              ("2 · Maturation – Meaning, Importance and Relation to Learning", MATURATION)],
}
