"""Paper 1 · Value Education · P1-VE-05 Theories of Behaviour (2 sub-topics × 20).
Coverage (planner): universality, rationality & morality, moral egoism, rational self-interest.
References: William Lillie, An Introduction to Ethics; James Rachels, The Elements of Moral Philosophy (chs. 5–6 on egoism); Kant,
Groundwork of the Metaphysics of Morals; Hobbes, Leviathan; Joseph Butler, Fifteen Sermons; Ayn Rand, The Virtue of Selfishness;
DSERT D.El.Ed. value-education texts. No previous-year KEA / KSET question on this topic was found in the downloaded papers, so the
sets use "PYQ pattern" questions on themes common in TET / GPSTR value-education sections."""
from packlib import AR, I_II

PYQ = "PYQ pattern (GPSTR / TET value education). "

UNIVERSAL_RATIONAL = [
    ("The principle that a moral rule must apply equally to everyone in similar circumstances is called:",
     ["Universality (universalisability)", "Egoism", "Relativism", "Hedonism"], 0, PYQ + "If an act is right for me, it is right for anyone in the same situation."),
    ("Kant's test 'Act only on that maxim which you can at the same time will to become a universal law' expresses:",
     ["Universalisability", "Psychological egoism", "Utilitarianism", "Cultural relativism"], 0, "Kant called it the first formulation of the categorical imperative."),
    ("Kant argued that lying is wrong because:",
     ["If everyone lied, trust would collapse, so the maxim cannot be universalised", "It always causes pain", "It is illegal", "It is unpopular"], 0, PYQ + "Kant judged acts by duty, not consequences."),
    ("The view that morality is grounded in reason, so that every rational being can know what is right, is called:",
     ["Rationalism in ethics", "Emotivism", "Egoism", "Nihilism"], 0, "Kant is the leading rationalist moral philosopher."),
    ("Aristotle described the human being as a:",
     ["Rational animal", "Selfish machine", "Blank slate", "Political robot"], 0, PYQ + "He held that a good life is one lived according to reason and virtue."),
    ("David Hume's famous statement 'Reason is, and ought only to be, the slave of the passions' means:",
     ["Reason guides us to goals set by our desires; it does not by itself move us to act", "Reason should control all feelings", "Feelings are always wrong", "Reason creates desires"], 0,
     "Hume is a sentimentalist, contrasted with Kant's rationalism."),
    ("A categorical imperative differs from a hypothetical imperative in that it:",
     ["Commands unconditionally, whatever one's desires", "Depends on a goal such as 'if you want to pass, study'", "Is a legal rule", "Applies only to children"], 0,
     PYQ + "Hypothetical imperatives say 'If you want X, do Y'."),
    ("Kant's 'formula of humanity' says that we should:",
     ["Treat humanity always as an end and never merely as a means", "Seek the greatest pleasure", "Follow the majority", "Obey only the law"], 0, "Using people merely as tools is wrong."),
    ("Moral judgements are said to be 'impartial' when:",
     ["Everyone's interests are given equal weight, without favouring oneself", "Only friends are considered", "Only the judge's interest counts", "No reasons are given"], 0,
     PYQ + "Impartiality is closely linked with universality."),
    ("Which of the following is an example of applying the principle of universality in a classroom?",
     ["The same rule on late submission applies to every student", "Rules change for the teacher's favourite", "Only toppers get extensions", "Rules are kept secret"], 0,
     "Fairness to all builds trust."),
    ("The 'Golden Rule' – treat others as you would like to be treated – is closely related to:",
     ["Universality and reciprocity", "Egoism", "Hedonism", "Fatalism"], 0, PYQ + "It appears in almost every religious tradition."),
    ("The view that what is morally right depends entirely on what each culture approves is:",
     ["Cultural relativism", "Universalism", "Rational egoism", "Kantian ethics"], 0, "Universalists argue some principles (e.g. against cruelty) hold for all cultures."),
    ("Rationality in moral behaviour mainly means:",
     ["Acting on good reasons that can be explained and defended to others", "Acting on sudden impulse", "Following any tradition blindly", "Doing whatever brings profit"], 0,
     PYQ + "Moral reasoning weighs facts and principles."),
    ("Kohlberg's highest stage, in which a person follows self-chosen universal ethical principles, shows:",
     ["Morality based on reason and universality", "Fear of punishment", "Desire for rewards", "Following the crowd"], 0, "Stage 6 – universal ethical principles orientation."),
    ("Consider the statements:\nI. A universal moral rule allows exceptions only for oneself.\nII. Universality requires treating similar cases alike.",
     I_II, 1, "Making exceptions for oneself violates universality."),
    ("Assertion (A): For Kant, an act done only out of fear of punishment has no moral worth.\nReason (R): Kant held that an act has moral worth only when done from duty.",
     AR, 0, "Kant valued the 'good will' acting from duty."),
    ("Assertion (A): Hume held that reason alone is the source of morality.\nReason (R): Hume thought moral distinctions come from sentiments (feelings) of approval and disapproval.",
     AR, 3, "Hume grounded morality in sentiment, not reason alone."),
    ("Match:\na. Kant  b. Hume  c. Aristotle  d. Mill\n1. Categorical imperative  2. Reason as slave of passions  3. Virtue and the rational animal  4. Utilitarianism",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Philosopher–idea matching is common."),
    ("A person returns extra change given by mistake at a shop because 'if everyone kept such money, honesty would disappear'. This reasoning uses:",
     ["Universalisability", "Psychological egoism", "Hedonism", "Fatalism"], 0, "Asking 'what if everyone did this?' is a universalisability test."),
    ("The view that moral principles bind all rational beings regardless of time and place is:",
     ["Moral universalism", "Moral relativism", "Subjectivism", "Egoism"], 0, PYQ + "Human-rights declarations rest on universalist ideas."),
]

EGOISM = [
    ("Psychological egoism is the theory that:",
     ["All people always act from self-interest", "People ought to act from self-interest", "People always act for others", "Morality is based on duty"], 0,
     PYQ + "It is a descriptive claim about how people do act."),
    ("Ethical (moral) egoism is the theory that:",
     ["Each person ought to pursue his or her own self-interest exclusively", "All people actually act selfishly", "We should maximise everyone's happiness", "Duty must override self-interest"], 0,
     "It is a normative claim about how people should act."),
    ("The philosopher who described the life of man in the state of nature as 'solitary, poor, nasty, brutish and short' and is associated with egoism is:",
     ["Thomas Hobbes", "Immanuel Kant", "J. S. Mill", "Aristotle"], 0, PYQ + "He argued that people accept a social contract for self-protection (Leviathan, 1651)."),
    ("The writer who defended 'rational self-interest' and called selfishness a virtue in 'The Virtue of Selfishness' was:",
     ["Ayn Rand", "Joseph Butler", "Mahatma Gandhi", "Adam Smith"], 0, "Her philosophy is called Objectivism."),
    ("Rational self-interest means:",
     ["Pursuing one's long-term interests guided by reason, not by every passing impulse", "Doing whatever one feels like at the moment", "Harming others for fun", "Always sacrificing oneself"], 0,
     PYQ + "A rational egoist may keep promises because it pays in the long run."),
    ("Bishop Joseph Butler criticised psychological egoism by arguing that:",
     ["We often desire things (like others' welfare) for their own sake, and pleasure follows from getting them", "All desires are selfish", "Reason has no role", "Pleasure is the only good"], 0,
     "This is the 'paradox of hedonism' argument."),
    ("Behaviour aimed at the welfare of others without expecting reward is called:",
     ["Altruism", "Egoism", "Hedonism", "Narcissism"], 0, PYQ + "The term was coined by Auguste Comte."),
    ("A common objection to ethical egoism is that it:",
     ["Cannot resolve conflicts of interest fairly and ignores the equal worth of others", "Is too generous to others", "Requires self-sacrifice", "Is the same as utilitarianism"], 0,
     "Rachels argues it makes an arbitrary distinction between oneself and others."),
    ("Which idea, often raised against egoism and hedonism, says that people who aim directly at their own pleasure often fail to find it?",
     ["The paradox of hedonism", "The categorical imperative", "The golden mean", "The veil of ignorance"], 0, PYQ + "Happiness usually comes as a by-product of other pursuits (Sidgwick)."),
    ("Which of the following is an example of enlightened (rational) self-interest?",
     ["A shopkeeper is honest because it builds customers' trust and long-term business", "Cheating customers for quick profit", "Giving away all savings to strangers", "Breaking promises when convenient"], 0,
     "Honesty here serves long-term interest."),
    ("Adam Smith's idea that individuals pursuing their own interest in a market can benefit society is known as:",
     ["The invisible hand", "The categorical imperative", "The veil of ignorance", "The golden mean"], 0, PYQ + "He also wrote 'The Theory of Moral Sentiments' on sympathy."),
    ("The 'prisoner's dilemma' shows that:",
     ["When each person pursues narrow self-interest, both can end up worse off than if they cooperated", "Selfishness always gives the best result", "Prisoners are always honest", "Cooperation is impossible"], 0,
     "It is used to explain the value of trust and rules."),
    ("According to Indian ethical traditions such as the Bhagavad Gita, the ideal is:",
     ["Nishkama karma – doing one's duty without selfish attachment to results", "Pursuit of only personal pleasure", "Avoiding all action", "Acting only for reward"], 0,
     PYQ + "It contrasts sharply with ethical egoism."),
    ("Moral egoism differs from rational self-interest mainly in that moral egoism:",
     ["Claims self-interest is the only moral standard, while rational self-interest stresses long-term, reasoned pursuit of interests", "Supports altruism", "Rejects reason", "Is a scientific law"], 0,
     "Many rational egoists accept cooperation as serving self-interest."),
    ("Consider the statements:\nI. Psychological egoism is a descriptive theory.\nII. Ethical egoism is a normative theory.",
     I_II, 2, "One describes what people do; the other prescribes what they ought to do."),
    ("Assertion (A): A teacher who helps a weak student after school without any reward shows altruistic behaviour.\nReason (R): Altruism is concern for the welfare of others.",
     AR, 0, "Value education aims to develop such concern."),
    ("Assertion (A): Psychological egoism is proved by the fact that people feel pleasure after helping others.\nReason (R): Butler argued that pleasure is the result of satisfying a desire for others' good, not its aim.",
     AR, 3, "Feeling pleasure does not show that pleasure was the motive – R is the standard reply."),
    ("Match:\na. Hobbes  b. Ayn Rand  c. Butler  d. Comte\n1. Social contract from self-interest  2. Virtue of selfishness  3. Critique of psychological egoism  4. Coined 'altruism'",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Thinker–theory matching."),
    ("Which statement best describes the relation between rationality and morality according to most moral philosophers?",
     ["Moral rules can be justified by reasons that every rational person can accept", "Morality has nothing to do with reason", "Only selfish acts are rational", "Rationality means obeying authority"], 0,
     "Contractarians and Kantians both link morality with reason."),
    ("The 'veil of ignorance' thought experiment, which asks us to choose rules without knowing our own position in society, was proposed by:",
     ["John Rawls", "Thomas Hobbes", "Ayn Rand", "David Hume"], 0, PYQ + "It aims at impartial, universal principles of justice (A Theory of Justice, 1971)."),
]

TOPICS = {
    "Theories of Behaviour": [("1 · Universality, Rationality and Morality", UNIVERSAL_RATIONAL),
                              ("2 · Moral Egoism, Altruism and Rational Self-interest", EGOISM)],
}
