"""Paper 1 · Value Education · P1-VE-04 Rules and Principles of Human Behaviour (2 sub-topics × 20).
Coverage (planner): rules & principles; factors affecting individual behaviour.
References: William Lillie, An Introduction to Ethics; J. N. Sinha, A Manual of Ethics; S. K. Mangal, Advanced Educational
Psychology; Kohlberg's and Piaget's work on moral development; DSERT D.El.Ed. value-education texts. Only one real previous-year
question fits this topic (KSET 2025 Education, answer worked out by ExamSim); the rest are "PYQ pattern" questions on themes common
in TET / GPSTR value-education and psychology sections."""
from packlib import AR, I_II

PYQ = "PYQ pattern (GPSTR / TET value education). "
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

RULES = [
    ("Which philosophy of education condemns enforced discipline and advocates social discipline based on child's interests?",
     ["Naturalism", "Idealism", "Pragmatism", "Realism"], 2,
     "Pragmatists (John Dewey) want discipline to grow out of purposeful, shared social activity that interests the child; naturalism relies on the natural consequences of acts." + NOTE,
     "KSET 2025 Education · Q12"),
    ("Rules of behaviour that a society expects its members to follow, and that are enforced by approval or disapproval, are called:",
     ["Social norms", "Instincts", "Reflexes", "Aptitudes"], 0, PYQ + "Folkways, mores, customs and laws are kinds of social norms."),
    ("Norms whose violation brings strong moral condemnation (for example, rules against theft) are called:",
     ["Mores", "Folkways", "Fashions", "Fads"], 0, "W. G. Sumner divided norms into folkways (everyday customs) and mores (morally important rules)."),
    ("Ordinary everyday customs such as ways of greeting or dressing, whose violation brings only mild disapproval, are:",
     ["Folkways", "Mores", "Laws", "Taboos"], 0, "Breaking a folkway is seen as odd or rude, not as immoral."),
    ("The difference between a law and a moral rule is that a law is:",
     ["Enforced by the State with legal penalties", "Followed only out of conscience", "Never written down", "Personal and private"], 0,
     PYQ + "Moral rules are enforced by conscience and social approval; laws by courts and the State."),
    ("The 'Golden Rule' of human behaviour says:",
     ["Treat others as you would like them to treat you", "The end justifies the means", "Might is right", "Obey without question"], 0,
     "It is found in almost every religion and ethical tradition."),
    ("Kant's categorical imperative asks us to act only on that maxim which we can will to become a:",
     ["Universal law", "Personal habit", "Social fashion", "Temporary rule"], 0, "Kant also said: treat humanity always as an end, never merely as a means."),
    ("The principle of 'the greatest happiness of the greatest number' belongs to:",
     ["Utilitarianism (Bentham, Mill)", "Kantian ethics", "Stoicism", "Existentialism"], 0, PYQ + "It judges actions by their consequences."),
    ("A rule of behaviour that a person follows because he has accepted it as right, without needing an outside authority, shows:",
     ["Autonomy (self-discipline)", "Heteronomy", "Conformity under fear", "Imitation"], 0,
     "Piaget: young children show heteronomous morality (rules come from adults); older children move to autonomous morality."),
    ("According to Kohlberg, a person who obeys rules mainly to avoid punishment is at the:",
     ["Pre-conventional level", "Conventional level", "Post-conventional level", "Universal-ethical level"], 0,
     PYQ + "Stage 1 – punishment and obedience orientation."),
    ("In Kohlberg's theory, 'good boy – nice girl' orientation and 'law and order' orientation belong to the:",
     ["Conventional level", "Pre-conventional level", "Post-conventional level", "Sensori-motor stage"], 0,
     "Stages 3 and 4 – behaviour is guided by the approval of others and by respect for social rules."),
    ("The highest stage in Kohlberg's moral development, where a person follows self-chosen ethical principles of justice, is:",
     ["Universal ethical principles orientation", "Social contract orientation", "Law and order orientation", "Instrumental relativist orientation"], 0,
     "Stage 6; stage 5 is the social-contract orientation. Both are post-conventional."),
    ("The inner sense that tells a person what is right and wrong and makes him feel guilty after wrong action is:",
     ["Conscience", "Instinct", "Intelligence", "Temperament"], 0, "Freud linked it to the superego."),
    ("In a school, rules are most likely to be followed willingly when they are:",
     ["Few, clear, fair and made with the pupils' participation", "Many and changed every day",
      "Kept secret from the pupils", "Enforced only by punishment"], 0, PYQ + "Democratic discipline builds self-discipline."),
    ("Which principle says that a person should be free to act as he wishes as long as he does not harm others?",
     ["Harm principle (J. S. Mill)", "Pleasure principle", "Reality principle", "Principle of reinforcement"], 0,
     "Mill set it out in 'On Liberty' (1859)."),
    ("Consider the statements:\nI. Rules make social life orderly and predictable.\nII. Moral principles are more general than rules and help us judge which rules are right.",
     I_II, 2, "Principles (truth, justice, non-violence) lie behind particular rules."),
    ("Assertion (A): Discipline imposed only through fear rarely produces lasting good behaviour.\nReason (R): Behaviour controlled by fear tends to disappear when the authority is absent.",
     AR, 0, "That is why educators stress self-discipline and inner motivation."),
    ("Assertion (A): Customs and traditions are the same in all societies.\nReason (R): Norms of behaviour are learnt through socialisation.",
     AR, 3, "Customs differ between societies and over time; R is true."),
    ("The process by which a child learns the norms, values and behaviour patterns of his society is:",
     ["Socialisation", "Maturation", "Assimilation of food", "Sublimation"], 0, PYQ + "Family is the primary agency; school, peers and media follow."),
    ("Gandhiji's principles of human behaviour – truth and non-violence – are known as:",
     ["Satya and Ahimsa", "Dharma and Karma", "Shama and Dama", "Artha and Kama"], 0, "He called his life 'My Experiments with Truth'."),
]

FACTORS = [
    ("Individual behaviour is the result of the interaction of:",
     ["Heredity and environment", "Heredity only", "Environment only", "Luck and chance"], 0, PYQ + "Woodworth: behaviour = f(heredity × environment)."),
    ("Kurt Lewin expressed behaviour as B = f(P, E), where P and E stand for:",
     ["Person and Environment", "Punishment and Effort", "Perception and Emotion", "Parent and Education"], 0,
     "Lewin's field theory: behaviour depends on the person and his psychological environment (life space)."),
    ("Which of the following is a biological (internal) factor affecting behaviour?",
     ["Functioning of the endocrine glands", "Family climate", "Peer group", "Mass media"], 0,
     "Hormones from the thyroid, adrenal and other glands affect energy, mood and emotion."),
    ("Over-secretion of the thyroid hormone usually makes a person:",
     ["Restless, excitable and irritable", "Sluggish and dull", "Very tall", "Colour-blind"], 0,
     PYQ + "Under-secretion causes sluggishness and, in children, cretinism."),
    ("The primary social group that has the earliest and deepest influence on a child's behaviour is the:",
     ["Family", "School", "Peer group", "Political party"], 0, "C. H. Cooley called family and play groups primary groups."),
    ("During adolescence the most powerful influence on behaviour such as dress, speech and interests usually comes from the:",
     ["Peer group", "Grand-parents", "Textbooks", "Government"], 0, PYQ + "Conformity to peers is strongest in early adolescence."),
    ("Behaviour that is learnt by observing and imitating a model is explained by:",
     ["Bandura's social (observational) learning theory", "Pavlov's classical conditioning", "Köhler's insight theory", "Freud's psychoanalysis"], 0,
     "Bandura's Bobo-doll experiment showed children imitating aggression."),
    ("Values, attitudes and beliefs affect behaviour because they:",
     ["Act as inner guides for choosing actions", "Change body height", "Are inherited unchanged from parents", "Have no link with action"], 0,
     "An attitude has cognitive, affective and behavioural components."),
    ("A need that, according to Maslow, must be met before a person seeks esteem and self-actualisation is:",
     ["Safety and belonging (love) needs", "Aesthetic needs only", "Transcendence", "Self-actualisation"], 0,
     PYQ + "Maslow's hierarchy: physiological → safety → love/belonging → esteem → self-actualisation."),
    ("A child who is repeatedly scolded and compared with others is likely to develop:",
     ["Low self-esteem and withdrawal or aggression", "High self-confidence", "Better health", "Increased intelligence"], 0,
     "Self-concept is shaped by how significant others treat the child."),
    ("Which of the following is a cultural factor affecting behaviour?",
     ["Customs, religion and language of the community", "Blood group", "Nervous system", "Body build"], 0,
     "Culture defines what behaviour is acceptable."),
    ("Emotional stress and frustration commonly lead to:",
     ["Defence mechanisms such as rationalisation, projection or displacement", "Better memory", "Higher IQ", "Taller stature"], 0,
     PYQ + "Defence mechanisms protect the self from anxiety."),
    ("Blaming others for one's own faults is the defence mechanism called:",
     ["Projection", "Sublimation", "Compensation", "Identification"], 0, "Sublimation channels energy into socially approved activity."),
    ("Giving a socially acceptable but false reason for one's behaviour (e.g. 'the grapes are sour') is:",
     ["Rationalisation", "Repression", "Regression", "Day-dreaming"], 0, "The 'sour grapes' and 'sweet lemon' mechanisms are forms of rationalisation."),
    ("The term 'temperament' refers to:",
     ["A person's characteristic emotional nature, partly inborn", "His school marks", "His height and weight", "His vocabulary"], 0,
     "Children may be 'easy', 'difficult' or 'slow to warm up' (Thomas and Chess)."),
    ("Which factor affects a pupil's classroom behaviour the most directly?",
     ["The teacher's personality, attitude and methods", "The colour of the school building", "The school's postal address", "The number of holidays"], 0,
     PYQ + "A warm, fair, democratic teacher reduces indiscipline."),
    ("Consider the statements:\nI. Heredity sets the limits of development.\nII. Environment decides how far those limits are reached.",
     I_II, 2, "Both act together; neither alone explains behaviour."),
    ("Assertion (A): Two children of the same family may behave very differently.\nReason (R): Individual differences arise from differences in heredity, environment and experience.",
     AR, 0, "Even siblings differ in heredity (except identical twins) and in their experiences."),
    ("Assertion (A): Behaviour is fixed at birth and cannot be changed.\nReason (R): Education aims at bringing desirable changes in behaviour.",
     AR, 3, "Behaviour can be modified through learning; R is the usual definition of education."),
    ("Which of the following best explains why the same person behaves differently in different situations?",
     ["Behaviour depends on the situation as well as on the person", "Behaviour is completely random",
      "Only heredity decides behaviour", "Situations never affect behaviour"], 0, "This is the person–situation interaction view."),
]

TOPICS = {
    "Rules and Principles of Human Behaviour": [("1 · Rules, Norms and Moral Principles", RULES),
                                                ("2 · Factors Affecting Individual Behaviour", FACTORS)],
}
