"""Paper 1 · Value Education · P1-VE-01 Value Education – Basics (2 sub-topics × 20).
References: DSERT Sadhana Patha training literature; NCERT (1979) Documents on Social, Moral and Spiritual Values in Education;
National Policy on Education 1986; Kothari Commission report."""
from packlib import AR, I_II

VALUES_MEANING = [
    ("The word 'value' is derived from the Latin word 'valere', which means:",
     ["To be of worth, to be strong", "To teach", "To obey rules", "To pray"], 0, "Values are what a person or society considers worthwhile."),
    ("Values are best described as:",
     ["Standards or principles that people consider desirable and that guide their choices and behaviour", "Marks obtained in examinations", "Prices of goods", "Rules written only in law books"], 0, "They direct what we think is good, right and important."),
    ("Which of the following is NOT a characteristic of values?",
     ["They are inherited genetically and cannot change", "They are learnt through experience and socialisation", "They guide behaviour", "They can be arranged in a hierarchy of importance"], 0, "Values are acquired and can change over time."),
    ("The saying often used about value education, 'Values are caught, not taught', means that:",
     ["Pupils learn values mainly by observing the example of teachers, parents and society", "Values cannot be learnt at all", "Values must be memorised from books", "Only punishment can teach values"], 0, "Hence the teacher's own conduct is very important."),
    ("The main objective of value education is:",
     ["The all-round development of character so that the learner becomes a good person and a good citizen", "Increasing examination marks only", "Teaching one particular religion", "Preparing students only for jobs"], 0, "It develops moral, social, emotional and spiritual aspects of personality."),
    ("Which committee (1959) was appointed specially to examine religious and moral instruction in educational institutions?",
     ["Sri Prakasa Committee", "Kothari Commission", "Mudaliar Commission", "Yashpal Committee"], 0, "It recommended moral instruction in schools."),
    ("The Education Commission of 1964–66, which recommended education in moral, social and spiritual values, is popularly known as the:",
     ["Kothari Commission", "Radhakrishnan Commission", "Mudaliar Commission", "Hunter Commission"], 0, "It was chaired by Dr D. S. Kothari."),
    ("The University Education Commission (1948–49), which also stressed moral and spiritual values in higher education, was chaired by:",
     ["Dr S. Radhakrishnan", "Dr D. S. Kothari", "Dr A. L. Mudaliar", "Sri Prakasa"], 0, "It is known as the Radhakrishnan Commission."),
    ("The National Policy on Education (1986) wanted value education mainly to help:",
     ["Eliminate obscurantism, religious fanaticism, violence, superstition and fatalism", "Increase the number of examinations", "Promote one religion over others", "Reduce the number of schools"], 0, "It saw value education as a force for social cohesion and national integration."),
    ("A teacher who is always punctual, honest and fair to all pupils is teaching values mainly through:",
     ["Personal example (modelling)", "Punishment", "Lecturing only", "Homework"], 0, "Pupils imitate the behaviour of admired adults."),
    ("Which method of value education uses stories, dramatisation and discussion of moral dilemmas?",
     ["Indirect or integrated method", "Physical punishment", "Rote learning", "Examination method"], 0, "Values are drawn out of activities rather than preached."),
    ("Values are said to be 'relative' in the sense that:",
     ["Their priority may differ between persons, cultures and situations", "They are the same for everybody at all times", "They can be measured in rupees", "They depend on height and weight"], 0, "Universal values also exist, but the importance given to values varies."),
    ("Which of the following is an objective of value education?",
     ["Developing respect for others and a sense of social responsibility", "Encouraging selfishness", "Increasing competition at any cost", "Avoiding all rules"], 0, "Respect, responsibility and cooperation are core aims."),
    ("Match the commission or policy with its year:\na. University Education Commission  b. Sri Prakasa Committee  c. Kothari Commission  d. National Policy on Education\n1. 1986  2. 1964–66  3. 1959  4. 1948–49",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "All of them stressed values in education."),
    ("Consider the statements:\nI. Values influence a person's attitudes and behaviour.\nII. Values once formed can never change.\nWhich is/are correct?",
     I_II, 0, "Values develop and can be modified with experience and education."),
    ("Consider the statements:\nI. The family is the first school of values.\nII. The school and the teacher also play a major role in developing values.\nWhich is/are correct?",
     I_II, 2, "Family, school, peers, media and society all shape values."),
    ("Assertion (A): The teacher's own behaviour is very important in value education.\nReason (R): Children learn values largely by imitating the people they admire.",
     AR, 0, "Values are 'caught' from models."),
    ("Assertion (A): Value education aims only at improving examination results.\nReason (R): Value education aims at the development of character.",
     AR, 3, "Its aim is character and all-round development; R is true and A is false."),
    ("Assertion (A): The Kothari Commission recommended education in moral, social and spiritual values.\nReason (R): The Kothari Commission was the first commission appointed after Independence.",
     AR, 2, "A is true. R is false: the University Education Commission (1948–49) came first."),
    ("Assertion (A): Values are learnt and not inborn.\nReason (R): The word 'value' comes from the Latin 'valere'.",
     AR, 1, "Both true, but the origin of the word does not explain how values are acquired."),
]

VALUES_TYPES = [
    ("The NCERT document on social, moral and spiritual values in education (1979) listed approximately how many values?",
     ["83", "10", "25", "100"], 0, "The list of 83 values is widely quoted in value education courses."),
    ("Values that are desirable for their own sake, as ends in themselves, are called:",
     ["Intrinsic (terminal) values", "Extrinsic (instrumental) values", "Material values", "Temporary values"], 0, "Instrumental values are means to achieve other ends."),
    ("Milton Rokeach classified values into two types:",
     ["Terminal and instrumental values", "Good and bad values", "Old and new values", "Rural and urban values"], 0, "Terminal values are desired end-states; instrumental values are modes of behaviour."),
    ("Eduard Spranger's six types of values are theoretical, economic, aesthetic, social, political and:",
     ["Religious", "Physical", "Military", "Legal"], 0, "The Allport–Vernon–Lindzey Study of Values is based on Spranger's types."),
    ("Enjoying music, painting and the beauty of nature reflects which kind of value?",
     ["Aesthetic value", "Economic value", "Political value", "Theoretical value"], 0, "Aesthetic values relate to beauty and art."),
    ("Standing respectfully when the national anthem is played reflects a:",
     ["National value", "Aesthetic value", "Economic value", "Personal hygiene value"], 0, "Patriotism and respect for national symbols are national values."),
    ("Helping flood victims and taking part in community service reflect:",
     ["Social values", "Aesthetic values", "Theoretical values", "Economic values"], 0, "Social values include cooperation, service and concern for others."),
    ("Punctuality, self-discipline and cleanliness are usually classed as:",
     ["Personal values", "National values", "Political values", "Religious values"], 0, "They relate to an individual's own conduct."),
    ("Truth, non-violence, peace and love, accepted by people everywhere, are called:",
     ["Universal values", "Local values", "Temporary values", "Economic values"], 0, "They are not limited to any one religion, region or culture."),
    ("The core values mentioned in the Preamble to the Indian Constitution include:",
     ["Justice, liberty, equality and fraternity", "Wealth, power and fame", "Competition and profit", "Obedience only"], 0, "These are constitutional values every citizen should respect."),
    ("Which of the following is NOT one of the core elements listed in the National Policy on Education (1986)?",
     ["Competitive examinations for all jobs", "Protection of the environment", "Equality of the sexes", "Inculcation of the scientific temper"], 0, "Other core elements include India's freedom movement, constitutional obligations, common cultural heritage, egalitarianism, democracy and secularism."),
    ("Returning a lost wallet with all the money to its owner shows mainly the value of:",
     ["Honesty", "Punctuality", "Aesthetic sense", "Thrift"], 0, "Honesty is both a personal and a moral value."),
    ("Mahatma Gandhi's life and teaching emphasised above all the values of:",
     ["Truth and non-violence", "Power and wealth", "Competition and success", "Luxury and comfort"], 0, "Satya and ahimsa were the basis of his philosophy."),
    ("Human values such as compassion and respect for human dignity are values that:",
     ["Relate to our common humanity and apply to all people", "Apply only to one's own family", "Can be bought", "Apply only to adults"], 0, "They form the basis of human rights."),
    ("Match the value with its category:\na. Patriotism  b. Cooperation  c. Truthfulness  d. Appreciation of beauty\n1. Aesthetic  2. Moral  3. Social  4. National",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Categories overlap in practice, but these are the usual classifications."),
    ("Consider the statements:\nI. Intrinsic values are valued for their own sake.\nII. Money is usually regarded as an intrinsic value.\nWhich is/are correct?",
     I_II, 0, "Money is valued as a means to other ends, so it is an instrumental (extrinsic) value."),
    ("Consider the statements:\nI. Secularism and democracy are among the values promoted by the Indian Constitution.\nII. Protection of the environment is a core element of the National Policy on Education (1986).\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Truth and non-violence are called universal values.\nReason (R): They are accepted as good in almost all cultures and religions.",
     AR, 0, "Wide acceptance across cultures is what makes a value universal."),
    ("Assertion (A): Spranger classified values into six types.\nReason (R): Spranger also listed the 83 values in the NCERT document.",
     AR, 2, "A is true. R is false: the list of 83 values comes from the NCERT document of 1979."),
    ("Assertion (A): Social values help people live together in harmony.\nReason (R): Personal values relate to the individual's own conduct.",
     AR, 1, "Both true, but R describes personal values and does not explain the role of social values."),
]

TOPICS = {
    "Value Education – Basics": [("1 · Values: Meaning, Definition, Objectives and Characteristics", VALUES_MEANING),
                                 ("2 · Classification of Values and NCERT Core Values", VALUES_TYPES)],
}
