"""Paper 1 · Value Education · P1-VE-02 Teaching Methods of Value Education (2 sub-topics × 20).
References: DSERT Sadhana Patha / D.El.Ed. value-education texts; NCERT (2012) Education for Values in Schools – A Framework; NCF 2005; NEP 2020."""
from packlib import AR, I_II

METHODS = [
    ("In the direct method of value education, values are taught:",
     ["Through planned, separate lessons or periods devoted specifically to values", "Only through chance events", "Only through sports", "Without any teacher"], 0, "Moral instruction periods and talks are examples."),
    ("In the indirect method of value education, values are:",
     ["Integrated with the teaching of school subjects and co-curricular activities", "Taught in a separate period only", "Taught through punishment", "Ignored completely"], 0, "For example, a science lesson can bring out honesty in recording results."),
    ("The incidental method of value education means:",
     ["Using events that occur unexpectedly in school or society as occasions to discuss values", "Teaching values only on holidays", "Writing values on the blackboard every day", "Testing values in exams"], 0, "A quarrel in class or a news event can become a value lesson."),
    ("A pupil returns a lost purse to the office and the headteacher praises this honesty in the morning assembly. This is an example of the:",
     ["Incidental method", "Direct method", "Lecture method", "Project method only"], 0, "A real event is used to highlight a value."),
    ("A history teacher discusses the sacrifices of freedom fighters while teaching the national movement. This illustrates the:",
     ["Indirect (integrated) method", "Direct method", "Incidental method", "Punishment method"], 0, "Values come through the subject lesson itself."),
    ("A school has a weekly 'moral science' period where the teacher narrates stories and explains their morals. This is the:",
     ["Direct method", "Incidental method", "Indirect method", "Laissez-faire method"], 0, "It is a separate, planned period for values."),
    ("Presenting a story with a moral problem and asking pupils what the character should do is the:",
     ["Moral dilemma discussion method", "Rote method", "Drill method", "Dictation method"], 0, "It is associated with Kohlberg's work on moral reasoning."),
    ("In role play for value education, pupils:",
     ["Act out situations to experience different viewpoints and feelings", "Only listen to lectures", "Copy notes from the board", "Take written tests"], 0, "It builds empathy and understanding."),
    ("The 'value clarification' approach (Raths, Harmin and Simon) mainly helps students to:",
     ["Become aware of their own values through choosing, prizing and acting", "Memorise a list of values", "Accept the teacher's values without thought", "Avoid thinking about values"], 0, "It focuses on the process of valuing rather than preaching."),
    ("Celebrating national festivals, observing Environment Day and organising a school cleanliness drive teach values through:",
     ["Co-curricular activities", "Examinations", "Homework only", "Punishment"], 0, "Such activities give practice in citizenship and cooperation."),
    ("Community service such as visiting an old-age home mainly develops the value of:",
     ["Compassion and social service", "Competition", "Selfishness", "Obedience only"], 0, "Pupils learn through direct experience of serving others."),
    ("Which statement best describes the limitation of relying only on the direct method?",
     ["Values may remain as information that is not practised in behaviour", "It takes no time at all", "It needs no teacher", "It always changes behaviour instantly"], 0, "Values must be experienced and practised, not only explained."),
    ("School assembly with prayers, thought for the day and news reading is a means of value education because it:",
     ["Gives daily, shared experiences of discipline, reflection and awareness", "Replaces all subject teaching", "Is meant only for punishment", "Has no educational purpose"], 0, "It sets the tone for the school day."),
    ("Match the method with its example:\na. Direct method  b. Indirect method  c. Incidental method  d. Role play\n1. Pupils enact a scene of helping an injured person  2. Discussing a fight in the playground when it happens  3. Bringing out cooperation while teaching a group experiment in science  4. A separate moral-education period with stories",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Schools generally combine all these methods."),
    ("Consider the statements:\nI. In the indirect method, values are integrated into subject teaching.\nII. In the incidental method, the teacher uses events that happen by chance.\nWhich is/are correct?",
     I_II, 2, "Both descriptions are correct."),
    ("Consider the statements:\nI. Value education is effective only when it is examined through written tests.\nII. Stories and discussions can be used in value education.\nWhich is/are correct?",
     I_II, 1, "Values show in behaviour; written tests alone cannot measure them."),
    ("Assertion (A): The incidental method makes value lessons meaningful.\nReason (R): It uses real situations that pupils have just experienced.",
     AR, 0, "Real events make the value concrete and relevant."),
    ("Assertion (A): Values can be developed only through a separate moral-science period.\nReason (R): Every subject and activity in school can carry values.",
     AR, 3, "Because every subject and activity can carry values, A is false."),
    ("Assertion (A): Role play helps pupils understand others' feelings.\nReason (R): Role play requires expensive equipment.",
     AR, 2, "A is true; R is false – role play needs almost no materials."),
    ("Assertion (A): Discussing moral dilemmas develops moral reasoning.\nReason (R): Kohlberg proposed three levels of moral development.",
     AR, 1, "Both true, but Kohlberg's levels do not by themselves explain how discussion helps."),
]

MEDIA_TEACHER = [
    ("Mass media such as television, newspapers and the Internet influence values mainly because they:",
     ["Reach large numbers of people and present models of behaviour", "Are used only by teachers", "Cannot affect children", "Show only educational content"], 0, "Children often imitate what they see on screen."),
    ("A negative influence of media on children's values can be:",
     ["Exposure to violence, consumerism and stereotypes", "Learning about other cultures", "Awareness of current events", "Access to educational videos"], 0, "Guidance helps children view media critically."),
    ("A positive use of media in value education is:",
     ["Showing a documentary on environmental conservation followed by discussion", "Letting pupils watch any content without guidance", "Banning all newspapers", "Using media only for entertainment"], 0, "Discussion turns viewing into learning."),
    ("'Media literacy' means the ability to:",
     ["Access, analyse, evaluate and create media messages critically", "Read only newspapers", "Repair television sets", "Avoid all media"], 0, "It protects children against misinformation and manipulation."),
    ("Checking whether a message forwarded on social media is true before sharing it shows the value of:",
     ["Responsibility and truthfulness", "Carelessness", "Blind obedience", "Competition"], 0, "Fake news can cause real harm."),
    ("Cyberbullying is best prevented in school by:",
     ["Teaching respectful online behaviour, empathy and how to report problems", "Ignoring it", "Encouraging anonymous insults", "Punishing the victim"], 0, "Digital citizenship is part of modern value education."),
    ("The most important role of the teacher in value education is to:",
     ["Be a role model whose own conduct shows the values taught", "Only give moral lectures", "Punish every mistake severely", "Leave value education to parents"], 0, "Pupils notice whether a teacher practises what they preach."),
    ("A teacher treats all pupils equally regardless of caste, religion or gender. This models the value of:",
     ["Equality and social justice", "Favouritism", "Competition", "Obedience only"], 0, "Equal treatment is also a constitutional value."),
    ("Creating a classroom climate where pupils feel safe to express opinions promotes the values of:",
     ["Freedom of expression and mutual respect", "Fear and silence", "Blind obedience", "Rivalry"], 0, "A democratic classroom teaches democracy by practice."),
    ("Involving parents in value education is important because:",
     ["Values learnt at school are reinforced (or weakened) at home", "Parents set examination papers", "Parents replace teachers", "Values are learnt only at home"], 0, "Home and school must work together."),
    ("The NCERT (2012) document on values in schools is titled:",
     ["Education for Values in Schools – A Framework", "Learning Without Burden", "Samagra Shiksha", "Inclusive Education Guidelines"], 0, "It advocates a whole-school approach to values."),
    ("A 'whole-school approach' to value education means:",
     ["Values are reflected in the school's policies, climate, relationships and all activities", "Only one teacher is responsible", "Only the principal teaches values", "Values are taught once a year"], 0, "Everyone in the school contributes."),
    ("A teacher who comes late regularly but lectures pupils on punctuality is likely to:",
     ["Fail to develop the value, because the example contradicts the words", "Develop punctuality very well", "Make no difference at all", "Improve pupils' marks"], 0, "Values are caught more than they are taught."),
    ("Match the medium with a value-education use:\na. Newspaper  b. Film  c. Radio  d. Internet\n1. Researching a social issue online for a project  2. Listening to an educational broadcast programme  3. Viewing and discussing a story of courage  4. A news-reading and discussion session in assembly",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "All media can serve value education with guidance."),
    ("Consider the statements:\nI. Media can influence children's values both positively and negatively.\nII. The teacher should help pupils evaluate media messages critically.\nWhich is/are correct?",
     I_II, 2, "That is the purpose of media literacy."),
    ("Consider the statements:\nI. The teacher's behaviour has little effect on pupils' values.\nII. Parents also shape children's values.\nWhich is/are correct?",
     I_II, 1, "The teacher is one of the strongest models for pupils."),
    ("Assertion (A): Teachers should model the values they teach.\nReason (R): Pupils learn values largely by imitating people they respect.",
     AR, 0, "Modelling is the most powerful method."),
    ("Assertion (A): All media content is harmful to children.\nReason (R): Media can present violence and stereotypes.",
     AR, 3, "Some content is harmful, but much is educational; A is false."),
    ("Assertion (A): Media literacy should be part of value education today.\nReason (R): Media literacy means avoiding all use of the Internet.",
     AR, 2, "A is true; R is false – media literacy means using media critically, not avoiding it."),
    ("Assertion (A): A democratic classroom helps develop democratic values.\nReason (R): The Constitution of India came into force on 26 January 1950.",
     AR, 1, "Both true, but the date does not explain why a democratic classroom develops those values."),
]

TOPICS = {
    "Teaching Methods of Value Education": [("1 · Direct, Indirect and Incidental Methods", METHODS),
                                            ("2 · Values and Media, and the Role of Teachers", MEDIA_TEACHER)],
}
