"""Paper 1 · Value Education · P1-VE-03 Theories of Goodness (2 sub-topics × 20).
Coverage (planner): internal & external goodness, hedonism, moral pluralism, moral qualities & self-evolution.
References: William Lillie, An Introduction to Ethics; J. N. Sinha, A Manual of Ethics; W. D. Ross, The Right and the Good;
J. S. Mill, Utilitarianism; DSERT D.El.Ed. value-education texts. No previous-year KEA/KSET question on this topic was found
in the downloaded papers, so the set uses "PYQ pattern" questions on themes common in TET / GPSTR value-education sections."""
from packlib import AR, I_II

PYQ = "PYQ pattern (GPSTR / TET value education). "

GOODNESS_HEDONISM = [
    ("Something that is good in itself, valued as an end and not for anything else, has:",
     ["Internal (intrinsic) goodness", "External (instrumental) goodness", "Market value only", "No value"], 0,
     PYQ + "Happiness and virtue are common examples of intrinsic goods."),
    ("Something that is good because it helps us get something else has:",
     ["External (instrumental) goodness", "Internal (intrinsic) goodness", "Absolute goodness", "Aesthetic goodness only"], 0,
     "Money is good as a means to food, shelter, education and so on."),
    ("Which of these is usually given as an example of an external (instrumental) good?",
     ["Money", "Happiness", "Virtue", "A good will"], 0,
     PYQ + "Its value lies in what it can buy or achieve."),
    ("Kant held that the only thing good without any qualification is:",
     ["A good will", "Pleasure", "Wealth", "Power"], 0,
     PYQ + "Opening idea of Kant's Groundwork of the Metaphysics of Morals (1785)."),
    ("Hedonism is the ethical theory that:",
     ["Pleasure (happiness) is the highest good", "Duty for duty's sake is the highest good", "Knowledge is the only good", "Self-denial is the highest good"], 0,
     PYQ + "From Greek hēdonē, 'pleasure'."),
    ("Psychological hedonism holds that:",
     ["By nature, people always seek pleasure and avoid pain", "People ought to seek the pleasure of others", "Pleasure is evil", "Only animals seek pleasure"], 0,
     "Ethical hedonism says what people OUGHT to seek; psychological hedonism describes what they DO seek."),
    ("The Greek philosopher associated with egoistic, sensual hedonism (the Cyrenaic school) is:",
     ["Aristippus", "Epicurus", "Socrates", "Aristotle"], 0,
     PYQ + "He valued the intense pleasures of the present moment."),
    ("Epicurus taught that the highest pleasure is:",
     ["Freedom from pain in the body and from disturbance in the mind (ataraxia)", "Constant feasting", "Wealth and power", "Fame"], 0,
     "He preferred simple, lasting, refined pleasures."),
    ("Utilitarianism, a form of universalistic hedonism, judges an action right if it produces:",
     ["The greatest happiness of the greatest number", "The greatest pleasure for the doer only", "Obedience to rules regardless of results", "Pain for the wrongdoer"], 0,
     PYQ + "Associated with Jeremy Bentham and J. S. Mill."),
    ("Jeremy Bentham's hedonic (felicific) calculus measures pleasures by their:",
     ["Quantity – intensity, duration, certainty, nearness, fecundity, purity and extent", "Quality only", "Colour and shape", "Religious merit"], 0,
     "Bentham: 'quantity of pleasure being equal, pushpin is as good as poetry'."),
    ("J. S. Mill differed from Bentham by holding that pleasures differ in:",
     ["Quality as well as quantity – higher (intellectual) pleasures are better than lower (bodily) ones", "Colour only", "Nothing at all", "Price"], 0,
     PYQ + "'It is better to be a human being dissatisfied than a pig satisfied; better to be Socrates dissatisfied than a fool satisfied.'"),
    ("The 'paradox of hedonism' states that:",
     ["Those who chase pleasure directly often fail to find it; it comes as a by-product of other pursuits", "Pleasure and pain are the same", "Everyone is always happy", "Pain is the highest good"], 0,
     "Discussed by Henry Sidgwick."),
    ("The Indian school that held 'as long as you live, live happily' (yāvat jīvet sukhaṃ jīvet) is:",
     ["Charvaka (Lokayata)", "Jainism", "Advaita Vedanta", "Yoga"], 0,
     PYQ + "A materialist, hedonistic school."),
    ("For Aristotle, the highest human good is:",
     ["Eudaimonia – flourishing or well-being achieved through a life of virtue", "Sensual pleasure", "Money", "Obedience to the king"], 0,
     "It is a life of activity in accordance with virtue, not mere pleasure."),
    ("A common criticism of hedonism is that:",
     ["It ignores values such as duty, justice and character, which we prize even when they bring no pleasure", "It values pleasure too little", "It is too difficult to understand", "It forbids happiness"], 0,
     "Critics such as Kant and the idealists stressed duty and self-realisation."),
    ("Match the thinker with the idea:\na. Aristippus  b. Epicurus  c. Bentham  d. Mill\n1. Pleasures differ in quality  2. Quantitative hedonic calculus  3. Freedom from pain and mental calm  4. Intense pleasure of the moment",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Thinker-idea matching is common in value-education sections."),
    ("Consider the statements:\nI. Money is an example of external goodness.\nII. Happiness is usually considered an internal good.\nWhich is/are correct?",
     I_II, 2, "Money is a means; happiness is sought for its own sake."),
    ("Consider the statements:\nI. Bentham measured pleasures by quality alone.\nII. Mill accepted that some pleasures are higher than others.\nWhich is/are correct?",
     I_II, 1, "Bentham measured quantity; Mill added quality."),
    ("Assertion (A): Utilitarianism is called universalistic hedonism.\nReason (R): It aims at the happiness of all people affected, not only of the doer.",
     AR, 0, "Egoistic hedonism seeks only one's own pleasure."),
    ("Assertion (A): According to hedonism, knowledge is the highest good.\nReason (R): Hedonism treats pleasure as the highest good.",
     AR, 3, "A contradicts the theory itself; R states it correctly."),
]

PLURALISM_SELF = [
    ("Moral pluralism holds that:",
     ["There are many genuine moral values or duties that cannot all be reduced to a single one", "Only pleasure is good", "There is no right or wrong", "Every culture has exactly the same rules"], 0,
     PYQ + "Monism, by contrast, reduces all value to one supreme principle."),
    ("The philosopher who proposed several 'prima facie duties' (fidelity, reparation, gratitude, justice, beneficence, self-improvement, non-maleficence) is:",
     ["W. D. Ross", "Jeremy Bentham", "Epicurus", "Karl Marx"], 0,
     PYQ + "A classic statement of moral pluralism (The Right and the Good, 1930)."),
    ("In moral pluralism, when two duties conflict (e.g. keeping a promise vs helping someone in danger), a person must:",
     ["Use judgement to decide which duty is weightier in that situation", "Always follow the first duty learned", "Ignore both duties", "Toss a coin"], 0,
     "Ross called the winning duty one's 'actual' duty in that case."),
    ("The view that the single highest good is pleasure is an example of:",
     ["Ethical monism", "Moral pluralism", "Relativism", "Scepticism"], 0,
     "Pluralists accept several independent goods."),
    ("Which of the following is a moral quality (virtue)?",
     ["Honesty", "Height", "Wealth", "Good handwriting"], 0,
     PYQ + "Moral qualities concern character and conduct."),
    ("Plato's four cardinal virtues are:",
     ["Wisdom, courage, temperance and justice", "Faith, hope, charity and love", "Truth, non-violence, celibacy and non-stealing", "Speed, strength, skill and stamina"], 0,
     PYQ + "Each corresponds to a part of the soul or a class in the ideal state."),
    ("Self-control, especially over desires and appetites, is called:",
     ["Temperance", "Prudence", "Courage", "Generosity"], 0,
     "Aristotle placed it as the mean between excess and insensibility."),
    ("The self-realisation (self-evolution) theory says that the highest good is:",
     ["The full development of a person's true self – intellectual, emotional and moral", "Maximum bodily pleasure", "Blind obedience to rules", "Accumulation of wealth"], 0,
     PYQ + "Associated with Hegel, T. H. Green and F. H. Bradley; in India with ātma-sākṣātkāra."),
    ("Which statement best expresses self-evolution as a moral ideal?",
     ["A person grows morally by steadily developing good qualities and controlling lower impulses", "A person is born perfect and cannot change", "Morality is only about external rewards", "Character depends only on heredity"], 0,
     "Education aims at this all-round growth."),
    ("For Mahatma Gandhi, the ultimate aim of life was:",
     ["Self-realisation – seeing God (Truth) face to face", "Wealth", "Political power", "Sensual pleasure"], 0,
     PYQ + "From the introduction to his autobiography, The Story of My Experiments with Truth."),
    ("Aristotle described a virtue as:",
     ["A mean between two extremes – excess and deficiency", "Doing whatever gives pleasure", "An inborn quality that cannot be learned", "Obeying the strongest person"], 0,
     "Courage is the mean between rashness and cowardice."),
    ("Courage, according to Aristotle's doctrine of the mean, lies between:",
     ["Rashness and cowardice", "Pride and humility", "Wealth and poverty", "Anger and joy"], 0,
     "Rashness is excess; cowardice is deficiency."),
    ("Moral qualities are developed in school children mainly through:",
     ["Example of teachers, practice in daily life and reflection on experiences", "Memorising definitions only", "Punishment alone", "Watching advertisements"], 0,
     "Values are 'caught' as much as 'taught'."),
    ("The Bhagavad Gita's teaching of nishkāma karma means:",
     ["Doing one's duty without attachment to its fruits", "Seeking only pleasure", "Giving up all work", "Working only for rewards"], 0,
     PYQ + "Contrasts with hedonism, which judges acts by the pleasure they bring."),
    ("Match the theory with its central idea:\na. Hedonism  b. Moral pluralism  c. Self-realisation  d. Kantian ethics\n1. Duty done from a good will  2. Full development of the true self  3. Many independent duties and values  4. Pleasure is the highest good",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Theory-idea matching."),
    ("Consider the statements:\nI. Moral pluralism accepts that duties can conflict.\nII. Moral pluralism reduces every value to pleasure.\nWhich is/are correct?",
     I_II, 0, "Reducing everything to pleasure is hedonistic monism."),
    ("Consider the statements:\nI. Wisdom, courage, temperance and justice are Plato's cardinal virtues.\nII. Self-realisation theory sees moral life as growth of the whole personality.\nWhich is/are correct?",
     I_II, 2, "Both are standard textbook statements."),
    ("Assertion (A): According to the self-realisation theory, mere pleasure cannot be the highest good.\nReason (R): The theory sees the highest good in the harmonious development of all sides of the self.",
     AR, 0, "Pleasure satisfies only one side of human nature."),
    ("Assertion (A): Virtues can be developed through practice.\nReason (R): Aristotle said that we become just by doing just acts.",
     AR, 0, "Habituation builds character."),
    ("Which pair is correctly matched?",
     ["Moral pluralism – W. D. Ross", "Hedonic calculus – Kant", "Good will – Bentham", "Cardinal virtues – Charvaka"], 0,
     "Bentham devised the hedonic calculus; Kant spoke of the good will; Plato listed the cardinal virtues."),
]

TOPICS = {
    "Theories of Goodness": [("1 · Internal and External Goodness, and Hedonism", GOODNESS_HEDONISM),
                             ("2 · Moral Pluralism, Moral Qualities and Self-evolution", PLURALISM_SELF)],
}
