"""Paper 2 · Unit 1 · topics U1-01 and U1-02 (6 sub-topics × 30)."""
from packlib import AR, I_II

INTRO = [
    ("A computer is best defined as an electronic device that:",
     ["Accepts data, processes it under the control of stored instructions, and produces and stores results", "Only performs arithmetic calculations",
      "Works only when connected to the Internet", "Thinks and takes decisions on its own"], 0,
     "A computer accepts input, processes it according to a stored program, produces output and can store data and results."),
    ("The characteristic 'diligence' of a computer means that it:",
     ["Can think creatively", "Works for long hours without fatigue or loss of accuracy", "Can repair itself", "Understands human emotions"], 1,
     "Unlike humans, a computer does not get tired or lose concentration while performing repetitive work."),
    ("GIGO in computing stands for:",
     ["Gigabyte In, Gigabyte Out", "Garbage In, Garbage Out", "General Input, General Output", "Graphical Input, Graphical Output"], 1,
     "If the input data or instructions are wrong, the output will also be wrong, even if the computer works perfectly."),
    ("Which of the following is NOT a characteristic of a computer?",
     ["Speed", "Accuracy", "Storage capacity", "Ability to take independent decisions without instructions"], 3,
     "Computers have no intelligence of their own (zero IQ); they only follow instructions."),
    ("'Information' differs from 'data' because information is:",
     ["Raw, unorganised facts", "Processed data that is meaningful and useful for decision making", "Always numeric", "Only stored on paper"], 1,
     "Data are raw facts; processing turns them into information such as totals, averages and reports."),
    ("According to P. K. Sinha, the five basic operations performed by every computer are:",
     ["Inputting, storing, processing, outputting and controlling", "Typing, printing, scanning, copying and saving",
      "Fetching, decoding, executing, storing and printing", "Compiling, linking, loading, executing and debugging"], 0,
     "These five operations are carried out by the input, storage, processing (CPU), output and control units."),
    ("One nanosecond equals:",
     ["10^-3 second", "10^-6 second", "10^-9 second", "10^-12 second"], 2,
     "milli = 10^-3, micro = 10^-6, nano = 10^-9, pico = 10^-12."),
    ("Arrange the time units from the longest to the shortest:",
     ["millisecond → microsecond → nanosecond → picosecond", "microsecond → millisecond → nanosecond → picosecond",
      "nanosecond → picosecond → microsecond → millisecond", "picosecond → nanosecond → microsecond → millisecond"], 0,
     "Each step down is a factor of 1000: ms (10^-3), µs (10^-6), ns (10^-9), ps (10^-12)."),
    ("'Versatility' as a characteristic of computers means:",
     ["They can perform a wide variety of tasks", "They never make mistakes", "They are portable", "They run without electricity"], 0,
     "The same computer can be used for word processing, calculations, games, communication and much more."),
    ("In computing, the term 'liveware' (humanware) refers to:",
     ["Firmware stored in ROM", "The people who operate and use computers", "Live video streaming", "Anti-virus software"], 1,
     "A computer system consists of hardware, software and liveware (users, operators, programmers)."),
    ("The 'word length' of a computer is:",
     ["The number of characters in a word document", "The number of bits the CPU processes as a single unit", "The length of the keyboard",
      "The number of words stored in RAM"], 1, "A 64-bit processor handles 64-bit words in its registers and ALU operations."),
    ("MIPS, used as a measure of processor performance, stands for:",
     ["Million Instructions Per Second", "Memory Instructions Per Second", "Mega Input Processing System", "Million Integer Processes Simultaneously"], 0,
     "MIPS counts how many millions of instructions a processor executes per second."),
    ("A processor clock of 3 GHz produces how many clock cycles per second?",
     ["3 × 10^3", "3 × 10^6", "3 × 10^9", "3 × 10^12"], 2, "Giga = 10^9, so 3 GHz = 3 × 10^9 cycles per second."),
    ("The smallest unit of data in a computer is the:",
     ["Byte", "Nibble", "Bit", "Word"], 2, "A bit (binary digit) is 0 or 1; 4 bits make a nibble and 8 bits make a byte."),
    ("In binary units, 1 TB is equal to:",
     ["1000 MB", "1024 GB", "1024 MB", "1000 KB"], 1, "1 KB = 1024 bytes, 1 MB = 1024 KB, 1 GB = 1024 MB and 1 TB = 1024 GB."),
    ("Which of the following is information rather than raw data?",
     ["The marks 45, 67 and 89 written on a paper", "A class report card showing each student's total and rank",
      "A list of roll numbers", "The digits typed at a keyboard"], 1, "Totals and ranks are the result of processing raw marks, so they are information."),
    ("A computer's ability to carry out a whole program without human intervention once started is called:",
     ["Automation", "Diligence", "Versatility", "Accuracy"], 0, "The stored program lets the computer perform all the steps automatically."),
    ("Digital computers operate on:",
     ["Continuously varying quantities", "Discrete values, represented in binary", "Only analog signals", "Mechanical gears"], 1,
     "Digital computers represent all data as discrete binary digits."),
    ("Which statement about computers is correct?",
     ["A computer can correct wrong instructions by itself", "A computer has no common sense and follows instructions exactly as given",
      "A computer feels tired after long work", "A computer learns only from emotions"], 1,
     "A computer cannot judge whether instructions are sensible; it just executes them."),
    ("The data processing cycle is correctly represented as:",
     ["Output → Processing → Input", "Input → Processing → Output (with storage)", "Processing → Input → Output", "Storage → Output → Input"], 1,
     "Data are input, processed, and the results are output and/or stored (the IPO cycle)."),
    ("Which of the following is liveware in a computer system?",
     ["The operating system", "A computer programmer", "The motherboard", "The BIOS"], 1, "People such as programmers and operators form the liveware."),
    ("A computer with a 2 GHz clock completes one clock cycle in:",
     ["0.5 ns", "2 ns", "0.5 µs", "5 ns"], 0, "Cycle time = 1 / frequency = 1 / (2 × 10^9) s = 0.5 × 10^-9 s = 0.5 ns."),
    ("Most errors in computer output are caused by:",
     ["Faulty electronic circuits", "Human errors in input data or programs", "Too much memory", "High clock speed"], 1,
     "Modern hardware is extremely reliable; errors usually come from incorrect data or program logic (GIGO)."),
    ("Consider the statements:\nI. A computer can take decisions without being given any program.\nII. A computer never needs input data to produce useful output.\nWhich is/are correct?",
     I_II, 3, "Both are false: a computer follows programs and needs input data to process."),
    ("Assertion (A): A computer can produce wrong results even when its hardware works perfectly.\nReason (R): Computers can work continuously for long hours without fatigue.",
     AR, 1, "Both statements are true, but diligence does not explain wrong results; the real reason is GIGO (wrong input or program)."),
    ("Hardware refers to:",
     ["The physical, tangible components of a computer", "The programs that run on a computer", "The people who use computers", "Data stored in memory"], 0,
     "Keyboards, CPUs, memory chips and monitors are hardware; programs are software."),
    ("How many bytes are there in 1 KB (binary)?",
     ["1000", "1024", "512", "8"], 1, "1 KB = 2^10 = 1024 bytes."),
    ("Which unit is used to measure the storage capacity of memory?",
     ["Hertz", "Bytes", "MIPS", "Pixels"], 1, "Storage is measured in bytes (KB, MB, GB, TB); hertz measures frequency."),
    ("The term 'computer' is derived from the word 'compute', which means:",
     ["To store", "To calculate", "To communicate", "To display"], 1, "Early computers were built mainly to perform calculations."),
    ("Which of the following is a limitation of computers?",
     ["High speed", "Large storage", "Lack of feelings, judgement and common sense", "High accuracy"], 2,
     "Computers cannot use judgement or feelings; the other options are strengths."),
]

FUNCTIONAL = [
    ("Which unit of a computer converts data entered by the user into binary form that the computer can understand?",
     ["Output unit", "Input unit", "Storage unit", "Control unit"], 1, "Input devices capture data and convert them into machine-readable binary codes."),
    ("The Arithmetic Logic Unit (ALU) performs:",
     ["Only addition", "Arithmetic operations and logical operations such as comparisons", "Storage of programs", "Input and output operations"], 1,
     "The ALU adds, subtracts, compares values (>, <, =) and performs logical AND, OR and NOT."),
    ("Which of the following operations is performed by the ALU?",
     ["Fetching an instruction from memory", "Comparing two numbers to see which is larger", "Printing a document", "Decoding an instruction"], 1,
     "Comparisons are logical operations carried out by the ALU; fetching and decoding are control-unit tasks."),
    ("The Control Unit is often compared to the human:",
     ["Heart", "Central nervous system, which coordinates all activities", "Eyes", "Stomach"], 1,
     "The CU directs and coordinates the other units, just as the nervous system coordinates the body."),
    ("The Central Processing Unit consists of:",
     ["ALU, control unit and registers", "Monitor, keyboard and mouse", "RAM and hard disk", "Printer and scanner"], 0,
     "The CPU contains the ALU, the control unit and a set of fast registers."),
    ("Which register usually stores the result of an arithmetic or logic operation?",
     ["Program counter", "Accumulator", "Memory address register", "Instruction register"], 1,
     "In accumulator-based architectures, the accumulator holds one operand and the result of ALU operations."),
    ("The Memory Address Register (MAR) holds:",
     ["The data read from memory", "The address of the memory location to be read or written", "The current instruction", "The result of the ALU"], 1,
     "The MAR sends the address to memory over the address bus."),
    ("The Memory Data Register (MDR/MBR) holds:",
     ["The address of the next instruction", "The data being transferred to or from memory", "The status flags", "The opcode only"], 1,
     "Data read from memory, or to be written to memory, pass through the MDR."),
    ("The Instruction Register (IR) contains:",
     ["The next instruction's address", "The instruction currently being decoded and executed", "The result of the last addition", "The stack pointer"], 1,
     "After fetching, the instruction is placed in the IR so the control unit can decode it."),
    ("The address bus is:",
     ["Bidirectional", "Unidirectional, carrying addresses from the CPU to memory and I/O", "Used to carry data only", "Used only for interrupts"], 1,
     "Only the CPU places addresses on the address bus."),
    ("The data bus is:",
     ["Unidirectional from memory to CPU only", "Bidirectional, carrying data to and from the CPU", "Used only for addresses", "Only used during booting"], 1,
     "Data move both ways: from memory to the CPU when reading and from the CPU to memory when writing."),
    ("The control bus carries:",
     ["Only data values", "Signals such as memory read/write, interrupt requests and clock", "Only memory addresses", "Only power supply"], 1,
     "Control signals coordinate the timing and direction of transfers."),
    ("A CPU with 16 address lines can address how many memory locations?",
     ["16", "256", "65,536", "1,048,576"], 2, "2^16 = 65,536 locations (64 K)."),
    ("The basic instruction cycle consists of:",
     ["Input, output and storage", "Fetch, decode and execute", "Compile, link and load", "Read, print and save"], 1,
     "The CPU fetches an instruction, decodes it and executes it, then repeats."),
    ("Which part of the CPU decodes the opcode of an instruction?",
     ["The ALU", "The control unit (instruction decoder)", "The accumulator", "The data bus"], 1, "The control unit interprets the opcode and issues control signals."),
    ("Secondary storage differs from primary memory because it is:",
     ["Faster and volatile", "Non-volatile, larger and slower, and not directly accessed by the CPU", "Part of the ALU", "Always smaller"], 1,
     "Hard disks and SSDs keep data without power but must be loaded into RAM before processing."),
    ("The output unit:",
     ["Converts binary results into a form understandable by humans", "Stores programs permanently", "Performs calculations", "Decodes instructions"], 0,
     "Monitors, printers and speakers present results in human-readable form."),
    ("Main memory is also called:",
     ["Secondary memory", "Primary memory", "Auxiliary memory", "Backing storage"], 1, "RAM is the primary (main) memory directly accessible by the CPU."),
    ("Which component sets the pace at which the CPU performs its operations?",
     ["The system clock", "The hard disk", "The power supply", "The keyboard"], 0, "The clock generates regular pulses that synchronise CPU operations."),
    ("Which of the following is the fastest storage in a computer?",
     ["Cache memory", "Main memory (RAM)", "CPU registers", "SSD"], 2, "Registers are inside the CPU and are accessed within a single clock cycle."),
    ("The flag (status) register records:",
     ["The address of the next instruction", "Conditions such as zero, carry, sign and overflow after an operation", "Keyboard input", "The contents of the monitor"], 1,
     "Branch instructions test these flags to take decisions."),
    ("Which of the following is NOT a function of the control unit?",
     ["Fetching instructions", "Decoding instructions", "Performing the addition of two numbers", "Generating control signals"], 2, "Addition is done by the ALU."),
    ("After an instruction is fetched, the program counter is:",
     ["Cleared to zero", "Incremented to point to the next instruction", "Copied into the accumulator", "Sent to the printer"], 1,
     "The PC is incremented (unless a jump changes it) so the next instruction can be fetched."),
    ("The width of the data bus mainly determines:",
     ["The maximum memory size", "How much data can be transferred at one time", "The screen resolution", "The keyboard layout"], 1,
     "A 64-bit data bus moves 64 bits per transfer; the address bus width determines the memory size."),
    ("Consider the statements:\nI. The width of the address bus determines the maximum memory that can be addressed.\nII. The width of the data bus determines the maximum memory that can be addressed.\nWhich is/are correct?",
     I_II, 0, "n address lines give 2^n addressable locations; the data bus affects transfer size, not memory size."),
    ("Assertion (A): The control unit is called the nerve centre of the computer.\nReason (R): It directs and coordinates the operations of all the other units.",
     AR, 0, "Coordinating all units is exactly why it is called the nerve centre."),
    ("How many bytes does a 32-bit data bus transfer in one bus cycle?",
     ["2", "4", "8", "32"], 1, "32 bits ÷ 8 = 4 bytes."),
    ("In a stored-program (von Neumann) computer, instructions and data are held in:",
     ["Separate ROM chips", "The same main memory", "The ALU", "The output unit"], 1, "Both share one memory, which is the essence of the stored-program concept."),
    ("General-purpose registers are used to:",
     ["Store the BIOS", "Temporarily hold data and intermediate results during processing", "Connect peripherals", "Store files permanently"], 1,
     "They are fast working storage for the CPU."),
    ("Which unit stores data and instructions before, during and after processing?",
     ["Storage (memory) unit", "Output unit", "Input unit", "Control bus"], 0, "The memory unit holds programs, data and results."),
]

EVOLUTION = [
    ("Which is considered the earliest known calculating device?",
     ["Abacus", "Pascaline", "Napier's bones", "Slide rule"], 0, "The abacus, using beads on rods, was used thousands of years ago in Mesopotamia and China."),
    ("Napier's bones (1617), used for multiplication, were invented by:",
     ["Blaise Pascal", "John Napier", "William Oughtred", "Gottfried Leibniz"], 1, "John Napier, the Scottish mathematician who also introduced logarithms."),
    ("The slide rule, based on logarithms, was invented by:",
     ["William Oughtred", "Charles Babbage", "Herman Hollerith", "John Napier"], 0, "William Oughtred developed the slide rule around 1620–1630."),
    ("The Pascaline (1642), a mechanical calculator, could perform:",
     ["Only addition and subtraction", "All four arithmetic operations and square roots", "Only multiplication", "Logical operations"], 0,
     "Blaise Pascal's machine added and subtracted using gears; Leibniz's Stepped Reckoner could also multiply and divide."),
    ("The Stepped Reckoner, which could also multiply and divide, was built by:",
     ["Blaise Pascal", "Gottfried Wilhelm Leibniz", "Joseph Jacquard", "Charles Babbage"], 1, "Leibniz improved on Pascal's design with his stepped drum mechanism."),
    ("Joseph Marie Jacquard's loom (1804) is important in computing history because it used:",
     ["Vacuum tubes", "Punched cards to control the weaving pattern", "Transistors", "Magnetic tapes"], 1,
     "The idea of storing instructions on punched cards later influenced Babbage and Hollerith."),
    ("Charles Babbage is called the 'father of the computer' mainly because of his design of the:",
     ["Pascaline", "Analytical Engine", "ENIAC", "Tabulating machine"], 1,
     "The Analytical Engine (1830s) had a store, a mill, control via punched cards and output, like a modern computer."),
    ("Babbage's Difference Engine was designed to:",
     ["Play chess", "Calculate polynomial tables using the method of finite differences", "Weave cloth", "Sort census cards"], 1,
     "It was meant to compute mathematical tables automatically and accurately."),
    ("Who is regarded as the world's first computer programmer?",
     ["Grace Hopper", "Ada Lovelace", "Alan Turing", "Charles Babbage"], 1,
     "Ada Lovelace wrote an algorithm for the Analytical Engine to compute Bernoulli numbers."),
    ("Herman Hollerith's tabulating machine was first used for the:",
     ["1890 US census", "Second World War code-breaking", "Apollo moon mission", "First railway timetable"], 0,
     "It processed punched cards and greatly reduced the time needed to tabulate the census."),
    ("The company founded by Herman Hollerith later became:",
     ["Microsoft", "IBM", "Intel", "Apple"], 1, "The Tabulating Machine Company merged into CTR, renamed IBM in 1924."),
    ("The Harvard Mark I (1944), designed by Howard Aiken with IBM, was:",
     ["A fully electronic computer", "An electromechanical computer using relays", "The first microcomputer", "A transistor computer"], 1,
     "Mark I used electromechanical switches and relays and read instructions from punched paper tape."),
    ("The Atanasoff–Berry Computer (ABC) is significant as:",
     ["The first commercial computer", "One of the first electronic digital computers, using vacuum tubes and binary arithmetic", "The first laptop", "The first supercomputer"], 1,
     "John Atanasoff and Clifford Berry built it at Iowa State between 1937 and 1942."),
    ("ENIAC was developed by:",
     ["J. Presper Eckert and John Mauchly", "Alan Turing and John von Neumann", "Howard Aiken", "Maurice Wilkes"], 0,
     "ENIAC was built at the University of Pennsylvania and completed in 1945–46."),
    ("ENIAC was programmed by:",
     ["Loading programs from a hard disk", "Setting switches and plugging cables (rewiring)", "Typing in C", "Using a mouse"], 1,
     "ENIAC was not a stored-program computer at first; reprogramming meant rewiring."),
    ("The 'First Draft of a Report on the EDVAC' (1945), which described the stored-program concept, was written by:",
     ["John von Neumann", "Alan Turing", "Charles Babbage", "Konrad Zuse"], 0, "This report gave its name to the von Neumann architecture."),
    ("EDSAC (1949), one of the first practical stored-program computers, was built at:",
     ["Harvard University", "Cambridge University under Maurice Wilkes", "MIT", "Bell Labs"], 1, "EDSAC ran its first program in May 1949."),
    ("Colossus (1943–44), used for breaking German codes, was built in:",
     ["The USA", "Britain, at Bletchley Park, by Tommy Flowers", "Germany", "Japan"], 1, "Colossus was an electronic, programmable machine used for code-breaking."),
    ("Konrad Zuse's Z3 (1941) was:",
     ["The first programmable, fully automatic electromechanical computer", "The first transistor computer", "The first supercomputer", "An analog computer"], 0,
     "The Z3 used relays and binary floating-point arithmetic."),
    ("In 1936 Alan Turing described an abstract model of computation now known as the:",
     ["Von Neumann machine", "Turing machine", "Difference engine", "Stepped reckoner"], 1, "The Turing machine defines what can be computed algorithmically."),
    ("The first computer installed in India (1956) was the HEC-2M at the:",
     ["Indian Institute of Science, Bengaluru", "Indian Statistical Institute, Kolkata", "IIT Bombay", "TIFR, Mumbai"], 1,
     "The ISI, founded by P. C. Mahalanobis, installed the HEC-2M in 1956."),
    ("TIFRAC, the first computer designed and built in India, was developed at:",
     ["C-DAC, Pune", "Tata Institute of Fundamental Research (TIFR), Mumbai", "ISRO", "ECIL, Hyderabad"], 1, "TIFRAC (TIFR Automatic Calculator) was commissioned in 1960."),
    ("Arrange chronologically: ENIAC, Analytical Engine design, Pascaline, UNIVAC I.",
     ["Pascaline → Analytical Engine → ENIAC → UNIVAC I", "Analytical Engine → Pascaline → UNIVAC I → ENIAC",
      "Pascaline → ENIAC → Analytical Engine → UNIVAC I", "ENIAC → Pascaline → UNIVAC I → Analytical Engine"], 0,
     "1642, 1830s, 1945–46 and 1951 respectively."),
    ("UNIVAC I became famous in 1952 for:",
     ["Landing on the moon", "Correctly predicting the result of the US presidential election", "Breaking the Enigma code", "Beating a chess champion"], 1,
     "On live TV, UNIVAC predicted Eisenhower's landslide victory."),
    ("Which of the following machines was electromechanical rather than fully electronic?",
     ["ENIAC", "Harvard Mark I", "EDSAC", "UNIVAC I"], 1, "Mark I used relays; the others used vacuum tubes."),
    ("In Babbage's Analytical Engine, the 'Store' corresponds to:",
     ["The processor", "Memory", "The printer", "The punched-card reader"], 1, "The Store held numbers; the Mill performed calculations."),
    ("ECIL (Electronics Corporation of India Ltd), which manufactured some of India's early indigenous computers, is headquartered in:",
     ["Bengaluru", "Hyderabad", "Pune", "Mumbai"], 1,
     "ECIL, set up under the Department of Atomic Energy in 1967, is based in Hyderabad."),
    ("Consider the statements:\nI. The Analytical Engine was fully built and used during Babbage's lifetime.\nII. Ada Lovelace wrote an algorithm intended for the Analytical Engine.\nWhich is/are correct?",
     I_II, 1, "The Analytical Engine was never completed in Babbage's lifetime; Lovelace's notes (1843) contain an algorithm for computing Bernoulli numbers."),
    ("Assertion (A): Punched cards played an important role in early data processing.\nReason (R): Charles Babbage introduced punched cards for processing the 1890 US census.",
     AR, 2, "A is true. R is false: Herman Hollerith used punched cards for the 1890 census (Jacquard had used them for looms in 1804)."),
    ("The stored-program concept was first put into practice in the late 1940s by machines such as:",
     ["ENIAC and Mark I", "Manchester Baby and EDSAC", "Pascaline and Stepped Reckoner", "Z3 and Colossus"], 1,
     "The Manchester Baby (1948) and EDSAC (1949) stored their programs in memory."),
]

GENERATIONS = [
    ("First-generation computers (about 1940–1956) used:",
     ["Transistors", "Vacuum tubes", "Integrated circuits", "Microprocessors"], 1, "Vacuum tubes were large, hot and unreliable."),
    ("Second-generation computers (about 1956–1963) were based on:",
     ["Vacuum tubes", "Transistors", "VLSI chips", "Optical processors"], 1, "Transistors were smaller, faster, cheaper and more reliable than tubes."),
    ("Third-generation computers (about 1964–1971) were based on:",
     ["Integrated circuits (ICs)", "Vacuum tubes", "Relays", "Microprocessors only"], 0, "ICs placed many transistors on a single chip."),
    ("Fourth-generation computers (1971 onwards) are characterised by:",
     ["Vacuum tubes", "Microprocessors using VLSI technology", "Relays", "Punched cards only"], 1, "An entire CPU was put on a single chip (e.g. Intel 4004)."),
    ("Fifth-generation computing is mainly associated with:",
     ["Vacuum tubes", "Artificial intelligence, parallel processing and ULSI", "Punched cards", "Magnetic drums"], 1,
     "Japan's Fifth Generation Computer Systems project (1982) focused on AI and parallel processing."),
    ("First-generation computers were programmed mainly in:",
     ["Machine language", "C++", "Python", "SQL"], 0, "Programs were written in binary machine code; assembly came into wide use in the second generation."),
    ("High-level languages such as FORTRAN and COBOL came into use during the:",
     ["First generation", "Second generation", "Fourth generation", "Fifth generation"], 1, "FORTRAN (1957) and COBOL (1959) appeared with transistorised computers."),
    ("Magnetic core memory was the main primary memory of:",
     ["First-generation computers", "Second-generation computers", "Fifth-generation computers", "Smartphones"], 1,
     "Second-generation machines used magnetic cores; first-generation machines often used magnetic drums."),
    ("Which of the following was a second-generation computer?",
     ["ENIAC", "IBM 1401", "IBM System/360", "IBM PC"], 1, "The IBM 1401 (1959) used transistors; the System/360 (1964) used ICs."),
    ("The IBM System/360 (1964) belongs to the:",
     ["First generation", "Second generation", "Third generation", "Fifth generation"], 2, "It was one of the most famous third-generation families using IC-based technology."),
    ("Operating systems with multiprogramming became common in the:",
     ["First generation", "Third generation", "Zeroth generation", "Pre-mechanical era"], 1, "Third-generation computers had operating systems allowing several programs in memory."),
    ("The transistor was invented in 1947 at:",
     ["IBM", "Bell Laboratories", "Intel", "Texas Instruments"], 1, "Bardeen, Brattain and Shockley invented it at Bell Labs."),
    ("The integrated circuit was invented independently by:",
     ["Jack Kilby and Robert Noyce", "Bardeen and Brattain", "Eckert and Mauchly", "Gates and Allen"], 0, "Kilby (Texas Instruments, 1958) and Noyce (Fairchild, 1959)."),
    ("The first commercial microprocessor, the Intel 4004, was released in:",
     ["1965", "1971", "1981", "1990"], 1, "The 4004 marked the beginning of the fourth generation."),
    ("The IBM Personal Computer was launched in:",
     ["1971", "1981", "1991", "2001"], 1, "The IBM PC (1981) used the Intel 8088 processor and MS-DOS."),
    ("Which generation had the problems of high heat, huge size and frequent breakdowns?",
     ["First", "Third", "Fourth", "Fifth"], 0, "Thousands of vacuum tubes produced great heat and often burned out."),
    ("Keyboards and monitors replaced punched cards and printouts as the main interface in the:",
     ["First generation", "Third generation", "Zeroth generation", "Second generation only"], 1,
     "Third-generation systems introduced interactive use through keyboards and monitors."),
    ("Graphical user interfaces, personal computers and networking became widespread in the:",
     ["Second generation", "Third generation", "Fourth generation", "First generation"], 2, "GUIs, PCs and the Internet belong to the microprocessor era."),
    ("Which technology term refers to integrating a very large number of transistors (thousands to millions) on one chip?",
     ["SSI", "MSI", "VLSI", "Relay logic"], 2,
     "SSI, MSI, LSI, VLSI and ULSI indicate increasing levels of integration."),
    ("Arrange the generations' main electronic components in order:",
     ["Vacuum tubes → Transistors → ICs → Microprocessors (VLSI)", "Transistors → Vacuum tubes → ICs → Microprocessors",
      "ICs → Transistors → Vacuum tubes → Microprocessors", "Vacuum tubes → ICs → Transistors → Microprocessors"], 0,
     "This is the standard classification of the first four generations."),
    ("Which of the following is an example of a first-generation computer?",
     ["UNIVAC I", "IBM 1401", "PDP-8", "Apple II"], 0, "UNIVAC I used vacuum tubes."),
    ("The PDP-8 (1965), a popular minicomputer, belongs to the:",
     ["First generation", "Second generation", "Third generation", "Fifth generation"], 2, "Minicomputers like the PDP-8 were made possible by IC technology."),
    ("Which statement about fourth-generation computers is correct?",
     ["They used vacuum tubes", "Their entire CPU could be placed on a single chip", "They could not be networked", "They used only machine language"], 1,
     "The microprocessor made small, affordable personal computers possible."),
    ("The Apple II (1977) belongs to which generation?",
     ["Second", "Third", "Fourth", "First"], 2, "It was an early microprocessor-based personal computer."),
    ("Which input/output media were typical of first-generation computers?",
     ["Punched cards and paper tape", "Touch screens", "USB drives", "DVDs"], 0, "Input was via punched cards and output via printouts."),
    ("Consider the statements:\nI. Transistor-based computers consumed less power than vacuum-tube computers.\nII. Third-generation computers used integrated circuits.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Fourth-generation computers are much cheaper and smaller than earlier ones.\nReason (R): VLSI technology places a whole processor on a single chip.",
     AR, 0, "Mass-produced microprocessors reduced size and cost dramatically."),
    ("Natural language processing, expert systems and robotics are goals typically associated with:",
     ["The second generation", "The third generation", "The fifth generation", "The first generation"], 2, "These AI goals characterise fifth-generation computing."),
    ("In which generation did time-sharing and remote terminals become common?",
     ["First", "Third", "Zeroth", "Pre-electronic"], 1, "Time-sharing systems allowed many users to share a computer interactively."),
    ("Which device made second-generation computers more reliable than first-generation ones?",
     ["Relay", "Transistor", "Magnetic drum", "Punched card"], 1, "Transistors had no filament to burn out and produced much less heat."),
]

CLASSIFICATION = [
    ("On the basis of working principle, computers are classified as:",
     ["Micro, mini, mainframe and super", "Analog, digital and hybrid", "General-purpose and special-purpose", "Desktop and laptop"], 1,
     "Analog computers use continuous quantities, digital computers discrete values, and hybrids combine both."),
    ("An analog computer works on:",
     ["Discrete binary digits", "Continuously varying physical quantities such as voltage, temperature or pressure", "Punched cards only", "Characters only"], 1,
     "Examples include speedometers and older analog simulators."),
    ("Which of these is an example of an analog device?",
     ["A digital watch", "A mercury thermometer", "A calculator", "A laptop"], 1, "A thermometer shows a continuously varying quantity."),
    ("On the basis of size and capacity, computers are classified as:",
     ["Analog, digital and hybrid", "Micro, mini, mainframe and supercomputers", "Special-purpose and general-purpose", "Online and offline"], 1,
     "This classification is based on processing power, size, number of users and cost."),
    ("Which type of computer is the most powerful and is used for weather forecasting and nuclear simulations?",
     ["Microcomputer", "Minicomputer", "Mainframe", "Supercomputer"], 3, "Supercomputers perform enormous numbers of floating-point operations per second."),
    ("The performance of supercomputers is usually measured in:",
     ["MIPS", "FLOPS", "RPM", "DPI"], 1, "FLOPS = floating-point operations per second; today's fastest reach exaFLOPS."),
    ("Which was India's first supercomputer?",
     ["Pratyush", "PARAM 8000", "Mihir", "Aaditya"], 1, "C-DAC's PARAM 8000 (1991); Pratyush and Mihir (2018) are later HPC systems for weather and climate."),
    ("Mainframe computers are mainly used by:",
     ["Individual home users", "Large organisations such as banks and railways for bulk transaction processing", "Only for gaming", "Embedded devices"], 1,
     "Mainframes handle huge numbers of simultaneous users and transactions reliably."),
    ("A minicomputer is best described as:",
     ["A computer smaller than a smartphone", "A mid-range multi-user computer, more powerful than a microcomputer but less than a mainframe",
      "A single-chip computer", "An analog computer"], 1, "The PDP and VAX series were well-known minicomputers."),
    ("A microcomputer is a computer whose CPU is a:",
     ["Set of vacuum tubes", "Microprocessor", "Relay circuit", "Mainframe board"], 1, "Desktops, laptops, tablets and smartphones are microcomputers."),
    ("A workstation is:",
     ["A computer without a CPU", "A high-performance single-user computer used for engineering, graphics and scientific work", "A dumb terminal", "A calculator"], 1,
     "Workstations have powerful processors, large memory and advanced graphics."),
    ("A computer designed to perform one specific task, such as controlling a washing machine, is a:",
     ["General-purpose computer", "Special-purpose (embedded) computer", "Supercomputer", "Mainframe"], 1, "Embedded controllers run fixed programs for dedicated tasks."),
    ("Which of these is a general-purpose computer?",
     ["A traffic-light controller", "A personal laptop", "A microwave-oven controller", "A digital thermometer"], 1, "A laptop can run many different programs."),
    ("A hybrid computer combines:",
     ["Micro and mainframe features", "Analog and digital features", "Hardware and software", "Input and output devices"], 1,
     "Hybrid computers are used, for example, in hospital ICUs and some scientific applications."),
    ("A server in a network is:",
     ["A computer that provides services and resources to other computers (clients)", "Any laptop", "A printer", "A network cable"], 0,
     "File, web, database and mail servers provide services to clients."),
    ("Which statement about tablets and smartphones is correct?",
     ["They are mainframes", "They are handheld microcomputers", "They are analog computers", "They are supercomputers"], 1, "They are microprocessor-based personal computers."),
    ("Frontier (USA), recognised in 2022, was the first supercomputer to officially exceed:",
     ["1 teraFLOPS", "1 petaFLOPS", "1 exaFLOPS", "1 megaFLOPS"], 2, "Frontier at Oak Ridge National Laboratory crossed the exascale (10^18 FLOPS) barrier."),
    ("Arrange in increasing order of processing power:",
     ["Microcomputer → Minicomputer → Mainframe → Supercomputer", "Mainframe → Microcomputer → Supercomputer → Minicomputer",
      "Supercomputer → Mainframe → Minicomputer → Microcomputer", "Minicomputer → Microcomputer → Mainframe → Supercomputer"], 0,
     "This is the traditional size-and-capacity classification."),
    ("Which of the following is a digital device?",
     ["A speedometer with a needle", "A voltmeter with a needle", "A digital multimeter", "A mercury barometer"], 2, "It displays discrete numeric values."),
    ("Which of the following best describes an embedded system?",
     ["A computer system built into another device to control it", "A cloud server", "A supercomputer cluster", "A web browser"], 0,
     "Cars, ATMs, printers and washing machines contain embedded systems."),
    ("The 'Pratyush' and 'Mihir' HPC systems are mainly used for:",
     ["Banking transactions", "Weather and climate forecasting", "Railway reservations", "Online gaming"], 1,
     "They are installed at IITM Pune and NCMRWF Noida respectively."),
    ("Which type of computer typically supports the largest number of simultaneous users?",
     ["Microcomputer", "Workstation", "Mainframe", "Laptop"], 2, "Mainframes can support thousands of users at once."),
    ("A personal digital assistant (PDA) is a type of:",
     ["Mainframe", "Handheld microcomputer", "Supercomputer", "Analog computer"], 1, "PDAs were forerunners of smartphones."),
    ("Consider the statements:\nI. Analog computers are generally more accurate than digital computers.\nII. Digital computers work with discrete data.\nWhich is/are correct?",
     I_II, 1, "Digital computers are generally more accurate; analog computers are limited by the precision of physical measurements."),
    ("Assertion (A): Analog computers are generally more accurate than digital computers.\nReason (R): Digital computers process data in discrete (binary) form.",
     AR, 3, "A is false: digital computers are more accurate, since analog results depend on the precision of physical measurements. R is true."),
    ("IBM's 'Z' series machines are examples of:",
     ["Supercomputers", "Mainframe computers", "Microcontrollers", "Analog computers"], 1, "IBM Z is IBM's current mainframe line."),
    ("Which of these is the best example of a special-purpose computer?",
     ["A computer in an automatic teller machine", "A desktop PC", "A laptop", "A mainframe running many applications"], 0, "An ATM computer runs one dedicated application."),
    ("On the basis of purpose, computers are classified as:",
     ["General-purpose and special-purpose", "Analog and digital", "Micro and mini", "Online and offline"], 0, "This classification is based on what the computer is designed to do."),
    ("A smartwatch is best classified as a:",
     ["Mainframe", "Wearable microcomputer", "Supercomputer", "Minicomputer"], 1, "It contains a microprocessor and runs apps."),
    ("Which type of computer did the PDP-11 and VAX families represent?",
     ["Supercomputers", "Minicomputers", "Microcomputers", "Analog computers"], 1, "DEC's PDP-11 and VAX were leading minicomputers."),
]

APPLICATIONS = [
    ("The Karnataka government's Bhoomi project is concerned with:",
     ["Online school admissions", "Computerisation of land records (RTC)", "Railway reservations", "Hospital management"], 1,
     "Bhoomi provides computerised Record of Rights, Tenancy and Crops (RTC) to farmers."),
    ("MICR technology is mainly used in which sector?",
     ["Banking (cheque processing)", "Hospitals", "Schools", "Agriculture"], 0, "Cheques carry magnetic-ink characters for fast automatic processing."),
    ("CAD stands for:",
     ["Computer-Aided Design", "Computer-Assisted Delivery", "Central Application Database", "Computer Analog Device"], 0, "CAD software helps engineers and architects create designs."),
    ("CAM stands for:",
     ["Computer-Aided Manufacturing", "Central Access Memory", "Computer-Aided Mailing", "Content Addressable Memory"], 0, "CAM uses computers to control machine tools in manufacturing."),
    ("CAI in education stands for:",
     ["Computer-Aided Instruction", "Central Academic Institute", "Computer Access Interface", "Computer-Aided Inspection"], 0, "CAI delivers lessons and drills through computers."),
    ("An ATM (Automated Teller Machine) is an application of computers in:",
     ["Defence", "Banking", "Agriculture", "Sports"], 1, "ATMs let customers withdraw cash and check balances without a teller."),
    ("POS terminals are used at:",
     ["Point of Sale in shops to record sales and accept card payments", "Post offices only", "Power stations", "Police stations"], 0, "POS = Point of Sale."),
    ("Which medical imaging techniques depend heavily on computers to construct images?",
     ["X-ray film only", "CT scan and MRI", "Stethoscope", "Thermometer"], 1, "CT and MRI reconstruct cross-sectional images using computers."),
    ("Telemedicine refers to:",
     ["Selling medicines online", "Providing medical consultation and care remotely using telecommunications and computers",
      "Robots making medicines", "Television programmes about health"], 1, "Doctors diagnose and advise patients at a distance."),
    ("ERP (Enterprise Resource Planning) software is used to:",
     ["Edit photographs", "Integrate business processes such as finance, HR, inventory and sales", "Play music", "Browse the web"], 1,
     "SAP and Oracle ERP are common examples."),
    ("GIS stands for:",
     ["Geographic Information System", "General Internet Service", "Global Input System", "Graphical Interface Software"], 0,
     "GIS stores, analyses and displays spatial (map-based) data."),
    ("EFT stands for:",
     ["Electronic Funds Transfer", "Electronic File Transmission", "External Fund Tracking", "Easy Financial Transaction"], 0,
     "EFT moves money electronically between accounts, e.g. NEFT/RTGS in India."),
    ("The use of computers to control machines that perform tasks such as welding and painting in car factories is called:",
     ["Desktop publishing", "Robotics / industrial automation", "Word processing", "Data mining"], 1, "Industrial robots are computer-controlled."),
    ("DTP (Desktop Publishing) software is used to:",
     ["Design page layouts for newspapers, magazines and brochures", "Control robots", "Manage databases", "Compile programs"], 0,
     "DTP tools such as PageMaker, InDesign and Scribus combine text and graphics."),
    ("E-governance means:",
     ["Using computers and the Internet to deliver government services and information", "Electing governments electronically only",
      "Private companies running governments", "Governments banning computers"], 0, "Examples include online certificates, tax filing and land records."),
    ("Computer simulation is especially useful because it:",
     ["Replaces all real experiments", "Allows testing of models (e.g. flight or crash tests) safely and cheaply before building real systems",
      "Needs no data", "Is always perfectly accurate"], 1, "Flight simulators and crash simulations save cost and risk."),
    ("Weather forecasting uses computers mainly to:",
     ["Print weather maps only", "Solve complex mathematical models of the atmosphere using large amounts of data", "Measure rainfall directly", "Launch satellites"], 1,
     "Numerical weather prediction requires high-performance computers."),
    ("CRM software is used for:",
     ["Customer Relationship Management", "Central Resource Monitoring", "Computer Repair Maintenance", "Crime Record Management only"], 0,
     "CRM manages interactions with customers."),
    ("E-commerce refers to:",
     ["Buying and selling goods and services over the Internet", "Electronic components manufacturing", "Email communication", "Electrical engineering"], 0,
     "Online shopping and payments are e-commerce applications."),
    ("Which application of computers is used by railways for booking tickets across the country?",
     ["Passenger Reservation System (PRS)", "CAD", "DTP", "GIS"], 0, "Indian Railways' PRS, developed by CRIS, supports nationwide booking."),
    ("CBT in education stands for:",
     ["Computer-Based Training (or Test)", "Central Board of Teachers", "Coded Binary Text", "Common Batch Test"], 0,
     "Computer-based training and computer-based tests are common today."),
    ("Which of the following is an application of computers in agriculture?",
     ["Soil analysis, crop monitoring and weather advisories", "Only printing seed packets", "Replacing rainfall", "Manual ploughing"], 0,
     "Precision agriculture and advisory systems use computers extensively."),
    ("CIM stands for:",
     ["Computer-Integrated Manufacturing", "Central Information Management", "Computer Interface Module", "Common Instruction Model"], 0,
     "CIM integrates design, production and business functions using computers."),
    ("Which of the following is an application of computers in entertainment?",
     ["Special effects and animation in films", "Brake systems", "Soil testing", "Tax collection"], 0, "Films use computer graphics and animation."),
    ("GPS is used for:",
     ["Determining location and navigation using satellite signals", "Sending emails", "Storing files", "Printing documents"], 0,
     "The Global Positioning System gives location, speed and time."),
    ("Consider the statements:\nI. Computers are used in hospitals to maintain patient records.\nII. Computers are used in banks for core banking solutions.\nWhich is/are correct?",
     I_II, 2, "Both are common applications of computers."),
    ("Assertion (A): Computers are widely used in banks.\nReason (R): MICR characters on cheques are printed with magnetic ink.",
     AR, 1, "Both are true, but R does not explain A; banks use computers because they must process huge numbers of transactions quickly and accurately."),
    ("EDI stands for:",
     ["Electronic Data Interchange", "Electrical Device Interface", "External Data Input", "Educational Development Index"], 0,
     "EDI is the computer-to-computer exchange of business documents in a standard format."),
    ("A smart classroom mainly uses computers for:",
     ["Interactive multimedia teaching with projectors and digital content", "Cooking", "Transport", "Printing money"], 0,
     "Smart classes use interactive boards, projectors and digital lessons."),
    ("In libraries, computers are commonly used for:",
     ["Cataloguing, circulation and searching books through an OPAC", "Binding books", "Cleaning shelves", "Printing newspapers"], 0,
     "OPAC = Online Public Access Catalogue."),
]

TOPICS = {
    "Introduction & Functional Components": [("1 · Introduction to Computers", INTRO),
                                             ("2 · Functional Components & Working of Each Unit", FUNCTIONAL)],
    "Evolution, Generations, Classification, Applications": [("1 · Evolution of Computers", EVOLUTION),
                                                             ("2 · Generations of Computers", GENERATIONS),
                                                             ("3 · Classification of Computers", CLASSIFICATION),
                                                             ("4 · Applications of Computers", APPLICATIONS)],
}
