"""Paper 2 · Unit 1 · topics U1-06 and U1-07 (6 sub-topics × 30)."""
from packlib import AR, I_II

CONFIG = [
    ("In the specification 'Intel Core i5-12400', the number 12 indicates the processor's:",
     ["Number of cores", "Generation", "Clock speed", "Cache size"], 1, "The first digits after the brand modifier give the generation (12th gen)."),
    ("In Intel processor names, the suffix 'K' (e.g. i7-13700K) means:",
     ["No integrated graphics", "Unlocked multiplier for overclocking", "Low-power laptop chip", "Server processor"], 1, "'F' means no integrated graphics; 'U' low-power mobile; 'H' high-performance mobile."),
    ("A processor listed as '6 cores, 12 threads' supports:",
     ["Dual CPUs", "Simultaneous multithreading (e.g. Intel Hyper-Threading), running two threads per core", "Only 6 programs", "12 GHz"], 1,
     "SMT lets each physical core execute two hardware threads."),
    ("What is the peak bandwidth of one channel of DDR4-3200 memory with a 64-bit bus?",
     ["3.2 GB/s", "12.8 GB/s", "25.6 GB/s", "51.2 GB/s"], 2, "3200 million transfers/s × 8 bytes = 25,600 MB/s = 25.6 GB/s; dual channel doubles it."),
    ("A 32-bit operating system can directly address at most about:",
     ["2 GB of RAM", "4 GB of RAM", "16 GB of RAM", "64 GB of RAM"], 1, "2^32 bytes = 4 GB; 64-bit systems are needed for more RAM."),
    ("USB 2.0 has a maximum signalling rate of:",
     ["12 Mbps", "480 Mbps", "5 Gbps", "10 Gbps"], 1, "USB 1.1 = 12 Mbps; USB 3.0 (3.2 Gen 1) = 5 Gbps; USB 3.2 Gen 2 = 10 Gbps."),
    ("USB 3.2 Gen 1 (originally USB 3.0) supports up to:",
     ["480 Mbps", "5 Gbps", "20 Gbps", "40 Gbps"], 1, "USB 3.2 Gen 2x2 reaches 20 Gbps and USB4 up to 40 Gbps."),
    ("Wi-Fi 6 corresponds to the IEEE standard:",
     ["802.11n", "802.11ac", "802.11ax", "802.3"], 2, "Wi-Fi 4 = 802.11n, Wi-Fi 5 = 802.11ac; 802.3 is Ethernet."),
    ("A 'Gigabit Ethernet' port supports a speed of:",
     ["100 Mbps", "1000 Mbps", "10 Mbps", "10 Gbps"], 1, "It uses an RJ-45 connector with Cat 5e or better cable."),
    ("Which Windows tool shows a detailed report of hardware and system configuration?",
     ["msinfo32 (System Information)", "notepad", "mspaint", "calc"], 0, "dxdiag also shows graphics and sound details."),
    ("An NVMe SSD is faster than a SATA SSD mainly because it:",
     ["Uses spinning platters", "Connects over PCI Express lanes instead of the SATA interface (limited to about 600 MB/s)", "Uses DRAM only", "Is larger"], 1,
     "PCIe 3.0 ×4 NVMe drives reach about 3,500 MB/s; PCIe 4.0 ×4 about 7,000 MB/s."),
    ("Integrated graphics differ from a dedicated graphics card because integrated graphics:",
     ["Have their own GDDR memory", "Are built into the CPU/chipset and share system RAM", "Are always faster", "Need a PCIe slot"], 1,
     "Dedicated cards have their own video memory (VRAM)."),
    ("Which of these is a minimum hardware requirement for Windows 11?",
     ["TPM 2.0", "32-bit processor", "1 GB RAM", "BIOS without UEFI"], 0, "Windows 11 requires a 64-bit CPU, 4 GB RAM, 64 GB storage, UEFI Secure Boot capability and TPM 2.0."),
    ("A monitor described as '24-inch' is measured:",
     ["Across its width", "Diagonally across the visible screen", "Across its height", "Including the stand"], 1, "Screen size is the diagonal."),
    ("In a configuration 'RAM: 16 GB DDR4-3200 (2 × 8 GB)', the '2 × 8 GB' means:",
     ["Two modules of 8 GB, allowing dual-channel operation", "8 modules of 2 GB", "16 GB soldered", "Two computers"], 0, "Two identical modules in the correct slots run in dual channel."),
    ("A processor's 'base clock 2.5 GHz, boost 4.4 GHz' means that:",
     ["It always runs at 4.4 GHz", "It runs at 2.5 GHz normally and can increase up to 4.4 GHz when thermal and power limits allow", "It has two CPUs", "It cannot exceed 2.5 GHz"], 1,
     "Turbo/boost raises the clock dynamically under load."),
    ("Which storage configuration gives the fastest boot times?",
     ["OS on a 1 TB 5400 RPM HDD", "OS on a 512 GB NVMe SSD", "OS on a DVD", "OS on a USB 2.0 pen drive"], 1, "NVMe SSDs have very low latency and high throughput."),
    ("The Performance tab of Windows Task Manager shows:",
     ["Only battery status", "Live usage of CPU, memory, disk, network and GPU", "Only installed programs", "Only printers"], 1, "It also shows details such as cores, speed and memory slots used."),
    ("A laptop processor with the suffix 'U' (e.g. i5-1235U) is designed for:",
     ["High-performance gaming desktops", "Low power consumption and long battery life", "Servers", "Overclocking"], 1, "U-series chips have low TDP for thin laptops."),
    ("How many pixels does a 1366 × 768 display have?",
     ["1,049,088", "2,073,600", "786,432", "921,600"], 0, "1366 × 768 = 1,049,088 pixels."),
    ("Which port is commonly used to connect a modern monitor carrying digital video and audio?",
     ["PS/2", "HDMI", "RJ-11", "Serial COM"], 1, "DisplayPort is another digital option; VGA is analog video only."),
    ("A computer with '1 TB HDD + 256 GB SSD' storage typically uses:",
     ["The HDD for the OS and the SSD for backups", "The SSD for the OS and programs, and the HDD for bulk data", "Both only as RAM", "The SSD as a CD drive"], 1,
     "The fast SSD speeds up booting and applications while the HDD stores large files cheaply."),
    ("Bluetooth is mainly used for:",
     ["Long-distance wired networking", "Short-range wireless connection of devices like headsets, mice and phones", "Satellite communication", "Powering devices"], 1,
     "Its typical range is about 10 m."),
    ("The L3 cache size in a processor specification refers to:",
     ["Hard-disk cache", "The shared last-level cache memory on the CPU", "The GPU memory", "The size of RAM"], 1, "A larger L3 reduces trips to main memory."),
    ("Consider the statements:\nI. A 64-bit OS can run on a 64-bit processor.\nII. A 64-bit OS can run on a 32-bit-only processor.\nWhich is/are correct?",
     I_II, 0, "A 32-bit-only processor cannot execute 64-bit code."),
    ("Assertion (A): Adding more RAM can make a computer faster when many programs are open.\nReason (R): With too little RAM, the OS must frequently move pages to the slower disk (paging).",
     AR, 0, "More RAM reduces paging to disk."),
    ("A GPU with '8 GB GDDR6' refers to:",
     ["System RAM", "The graphics card's dedicated video memory", "Hard disk size", "Cache memory"], 1, "VRAM stores textures and frame buffers."),
    ("Which of these most directly determines how many applications can stay open smoothly?",
     ["Monitor size", "Amount of RAM", "Keyboard type", "Mouse DPI"], 1, "RAM holds the working data of running programs."),
    ("The typical 'Configuration' of a school computer lab PC would NOT normally include:",
     ["A processor", "RAM", "Storage", "A supercomputer interconnect"], 3, "Supercomputer interconnects are only used in HPC clusters."),
    ("SATA III interface supports a maximum transfer rate of:",
     ["1.5 Gb/s", "3 Gb/s", "6 Gb/s", "12 Gb/s"], 2, "About 600 MB/s after encoding overhead."),
]

MB_TYPES = [
    ("The motherboard is also known as the:",
     ["Daughterboard", "Mainboard or system board", "Expansion card", "Backplane only"], 1, "Apple calls it a logic board; IBM used 'planar'."),
    ("The ATX form factor was introduced in 1995 by:",
     ["IBM", "Intel", "AMD", "Apple"], 1, "ATX replaced the older IBM AT form factor."),
    ("Which motherboard form factor is the smallest of these?",
     ["ATX", "Micro-ATX", "Mini-ITX", "E-ATX"], 2, "Mini-ITX is 170 × 170 mm."),
    ("The dimensions of a standard ATX motherboard are about:",
     ["170 × 170 mm", "244 × 244 mm", "305 × 244 mm", "330 × 305 mm"], 2, "Micro-ATX is 244 × 244 mm; E-ATX is larger than ATX."),
    ("Which form factor was developed by VIA Technologies for small, low-power systems?",
     ["BTX", "Mini-ITX", "LPX", "AT"], 1, "Mini-ITX appeared in 2001."),
    ("Compared with AT, the ATX form factor introduced:",
     ["Physical mains switches on the PSU", "Soft power control (power on/off from the motherboard via PS_ON and +5VSB)", "A 5-pin DIN keyboard only", "Larger boards only"], 1,
     "ATX allows the OS to shut down the computer and supports Wake-on-LAN."),
    ("The BTX form factor, introduced by Intel in 2004, aimed mainly to:",
     ["Reduce cost only", "Improve cooling and airflow", "Add more RAM slots", "Remove the chipset"], 1, "BTX was later abandoned."),
    ("In LGA (Land Grid Array) sockets used by Intel, the pins are located:",
     ["On the processor", "In the motherboard socket", "On both", "There are no pins"], 1, "In PGA sockets (e.g. AMD AM4) the pins are on the CPU."),
    ("AMD's AM4 socket uses ______, while AM5 uses ______.",
     ["LGA; PGA", "PGA; LGA", "BGA; LGA", "LGA; BGA"], 1, "AM5 moved to an LGA-1718 design."),
    ("In most laptops, the CPU is attached to the motherboard using:",
     ["A ZIF socket", "BGA (soldered directly)", "A slot", "Screws only"], 1, "Ball Grid Array packages are soldered, so they are not user-replaceable."),
    ("An 'integrated' motherboard is one that:",
     ["Has no CPU socket", "Has on-board components such as graphics, sound and network controllers", "Uses only expansion cards", "Cannot be upgraded at all"], 1,
     "Non-integrated boards rely on add-on cards for these functions."),
    ("The chipset of a motherboard mainly determines:",
     ["The colour of the board", "Supported features such as CPU compatibility, number of USB/SATA ports, PCIe lanes and overclocking", "The monitor size", "The keyboard layout"], 1,
     "For example, Intel Z-series chipsets allow CPU overclocking while B-series usually do not."),
    ("The old AT motherboards used which keyboard connector?",
     ["USB", "5-pin DIN", "PS/2 6-pin mini-DIN", "Bluetooth"], 1, "ATX boards moved to PS/2 and later USB."),
    ("AT power supplies connected to the motherboard using the:",
     ["24-pin ATX connector", "P8 and P9 connectors", "SATA connector", "Molex only"], 1, "Connecting P8/P9 the wrong way round could damage the board."),
    ("LPX and NLX form factors are known for using a:",
     ["Riser card on which expansion cards are mounted parallel to the motherboard", "Water cooling block", "Dual CPU sockets", "Optical interconnect"], 0,
     "They were used in slim desktop cases."),
    ("Server motherboards typically differ from desktop boards by supporting:",
     ["No RAM", "Multiple CPU sockets and ECC/registered memory", "Only integrated graphics", "Only Wi-Fi"], 1, "Reliability and scalability are key for servers."),
    ("Most motherboards are made as:",
     ["Single-layer paper boards", "Multi-layer printed circuit boards (PCBs)", "Glass sheets", "Plastic moulds without copper"], 1, "Several copper layers carry power and signal traces."),
    ("A passive board that only provides expansion slots, with the CPU on a plug-in card, is called a:",
     ["Backplane", "Daughterboard", "Riser card", "Chipset"], 0, "Backplanes are used in industrial and server systems."),
    ("Which statement about Micro-ATX boards is correct?",
     ["They cannot fit in ATX cases", "They usually fit in ATX cases but have fewer expansion slots", "They are larger than ATX", "They have no RAM slots"], 1,
     "Mounting holes are compatible with ATX cases."),
    ("A small add-on circuit board that plugs into the motherboard to add functions is called a:",
     ["Mainboard", "Daughterboard (expansion card)", "Backplane", "Chip"], 1, "Graphics and sound cards are daughterboards."),
    ("Branded PCs from some manufacturers often use:",
     ["Only standard ATX boards", "Proprietary motherboard form factors that may limit upgrades", "No motherboard", "Only Mini-ITX"], 1, "Proprietary layouts can restrict replacement parts."),
    ("The main function of the motherboard is to:",
     ["Display images", "Interconnect and allow communication among the CPU, memory, storage and peripherals, and distribute power", "Store all files permanently", "Cool the CPU"], 1,
     "It is the backbone that connects all components."),
    ("Consider the statements:\nI. AT motherboards supported soft power control through a PS_ON signal.\nII. ATX motherboards have I/O ports built onto the rear edge, covered by an I/O shield.\nWhich is/are correct?",
     I_II, 1, "Soft power control was introduced with ATX; statement II is correct."),
    ("Assertion (A): Any Intel desktop processor fits any motherboard that has an LGA socket.\nReason (R): The socket type and chipset determine which processors a motherboard supports.",
     AR, 3, "A is false: LGA sockets differ (e.g. LGA1200 and LGA1700 are incompatible). R is true."),
    ("E-ATX motherboards are mainly used in:",
     ["Smartphones", "High-end workstations and enthusiast or server builds", "Tablets", "Embedded controllers"], 1, "Extended ATX provides more slots and space."),
    ("Which of these is a motherboard manufacturer?",
     ["ASUS", "Nvidia GeForce Experience", "Microsoft Word", "Mozilla"], 0, "ASUS, Gigabyte, MSI and ASRock are major motherboard makers."),
    ("A ZIF socket stands for:",
     ["Zero Insertion Force socket", "Zinc Insulated Frame socket", "Zero Interrupt Frequency socket", "Zone Interface socket"], 0, "A lever lets the CPU be inserted without force."),
    ("Which motherboard form factor would you choose for a very compact home-theatre PC?",
     ["E-ATX", "ATX", "Mini-ITX", "SSI-EEB"], 2, "Mini-ITX boards fit small cases."),
    ("The motherboard of a Mac computer is called a:",
     ["Planar", "Logic board", "Backplane", "Riser"], 1, "Apple uses the term logic board."),
    ("Which statement about BGA packages is correct?",
     ["They are easily replaceable by users", "They are soldered to the board, saving space in thin devices", "They use a ZIF lever", "They are used only in servers"], 1,
     "BGA is common in laptops and phones."),
]

MB_COMPONENTS = [
    ("In older chipsets, the northbridge was also called the:",
     ["I/O Controller Hub (ICH)", "Memory Controller Hub (MCH)", "Super I/O", "PCH"], 1, "The southbridge was the I/O Controller Hub."),
    ("In modern Intel systems, the southbridge functions are provided by the:",
     ["Northbridge", "Platform Controller Hub (PCH)", "BIOS chip", "VRM"], 1, "The memory controller moved into the CPU."),
    ("The CMOS on a motherboard stores:",
     ["The operating system", "BIOS/UEFI configuration settings such as boot order and date/time", "User documents", "The video driver"], 1,
     "The CMOS battery keeps these settings and the real-time clock when the PC is off."),
    ("The coin cell commonly used as a CMOS battery is:",
     ["AA", "CR2032", "9 V", "AAA"], 1, "It is a 3 V lithium cell."),
    ("A 'Clear CMOS' jumper is used to:",
     ["Overclock the CPU", "Reset BIOS settings to default", "Increase RAM", "Turn off USB"], 1, "Useful after wrong settings or a forgotten BIOS password."),
    ("The VRM (Voltage Regulator Module) on a motherboard:",
     ["Stores data", "Converts 12 V to the low, stable voltage required by the CPU", "Controls the monitor", "Charges the CMOS battery"], 1,
     "Good VRMs are important for high-power CPUs and overclocking."),
    ("The main power connector from the PSU to an ATX motherboard has:",
     ["4 pins", "8 pins", "20 or 24 pins", "15 pins"], 2, "Modern boards use 24 pins; the CPU gets a separate 4/8-pin EPS connector."),
    ("The 4/8-pin EPS12V connector near the CPU socket supplies power to:",
     ["The hard disk", "The CPU (through the VRM)", "The fans", "The USB ports"], 1, "High-end boards may need two 8-pin connectors."),
    ("Which slot is used for modern graphics cards?",
     ["PCIe x16", "AGP", "ISA", "PCI"], 0, "AGP and ISA are obsolete; PCI is legacy."),
    ("Approximately how much bandwidth does one PCIe 4.0 lane provide in each direction?",
     ["250 MB/s", "About 1 GB/s", "About 2 GB/s", "About 8 GB/s"], 2, "PCIe 3.0 ≈ 1 GB/s per lane, 4.0 ≈ 2 GB/s and 5.0 ≈ 4 GB/s."),
    ("A PCIe 4.0 x16 slot provides roughly how much bandwidth in each direction?",
     ["2 GB/s", "8 GB/s", "16 GB/s", "32 GB/s"], 3, "16 lanes × about 2 GB/s ≈ 32 GB/s."),
    ("An M.2 slot with an 'M key' is typically used for:",
     ["Wi-Fi cards", "NVMe (and some SATA) SSDs", "RAM", "CPU"], 1, "E-key M.2 slots are usually for Wi-Fi/Bluetooth cards."),
    ("The BIOS/UEFI firmware is stored on the motherboard in a:",
     ["DRAM chip", "Flash memory (SPI) chip", "Hard disk", "Cache"], 1, "Flash allows BIOS updates (flashing)."),
    ("On the rear audio panel following the PC 99 colour code, the green jack is for:",
     ["Microphone", "Line out (speakers/headphones)", "Line in", "Keyboard"], 1, "Pink is microphone and light blue is line in."),
    ("In the PC 99 colour code, PS/2 purple and green ports are for:",
     ["Keyboard and mouse respectively", "Mouse and keyboard respectively", "Speakers and microphone", "Monitor and printer"], 0, "Purple = keyboard, green = mouse."),
    ("The front-panel header on a motherboard connects:",
     ["The GPU", "The case's power button, reset button and power/HDD LEDs", "The RAM", "The CPU cooler"], 1, "Pins are labelled PWR_SW, RESET_SW, PLED and HDD_LED."),
    ("A 4-pin fan header differs from a 3-pin header because it:",
     ["Supplies 24 V", "Supports PWM speed control", "Cannot report speed", "Is only for pumps"], 1, "The fourth pin carries the PWM control signal."),
    ("The crystal oscillator on the motherboard is used to:",
     ["Store BIOS settings", "Generate the reference clock signals", "Regulate voltage", "Filter audio"], 1, "Clock generators derive CPU and bus clocks from it."),
    ("SATA ports on the motherboard are used to connect:",
     ["RAM", "Hard disks, SATA SSDs and optical drives", "Monitors", "Printers"], 1, "Each device also needs a SATA power connector from the PSU."),
    ("DIMM slots on a desktop motherboard hold:",
     ["The CPU", "Memory modules (RAM)", "Graphics cards", "Hard disks"], 1, "Slots are often colour-coded by channel."),
    ("Heat sinks on the motherboard are commonly placed over:",
     ["The CMOS battery", "The VRM and chipset", "SATA ports", "Audio jacks"], 1, "These components generate heat."),
    ("A TPM (Trusted Platform Module) provides:",
     ["Extra RAM", "Hardware-based security functions such as secure key storage", "Graphics acceleration", "Faster USB"], 1, "Windows 11 requires TPM 2.0 (discrete or firmware)."),
    ("Internal USB headers on the motherboard are used to connect:",
     ["The front-panel USB ports of the case", "The CPU", "The PSU", "The monitor"], 0, "They provide USB to the case's front ports."),
    ("The printed copper lines connecting components on a motherboard are called:",
     ["Traces", "Jumpers", "Headers", "Slots"], 0, "Buses are formed by groups of traces."),
    ("Which component on the motherboard temporarily stores electrical charge to smooth the power supply?",
     ["Capacitor", "Crystal", "Jumper", "Header"], 0, "Solid polymer capacitors are common on modern boards."),
    ("Consider the statements:\nI. The CPU socket type must match the processor.\nII. Any DDR generation of RAM fits in any DIMM slot.\nWhich is/are correct?",
     I_II, 0, "DDR generations have different notch positions and are not interchangeable."),
    ("Assertion (A): Removing the CMOS battery for some time may reset the BIOS settings.\nReason (R): CMOS settings are held in memory powered by the battery when the PC is off.",
     AR, 0, "Without power the stored settings are lost and defaults are loaded."),
    ("The rear I/O panel of a motherboard with integrated graphics typically includes:",
     ["HDMI/DisplayPort, USB, Ethernet (RJ-45) and audio jacks", "Only a VGA port", "SATA ports", "DIMM slots"], 0, "These are the external connectors of the board."),
    ("A POST code display (debug LED) on a motherboard helps to:",
     ["Show the CPU temperature only", "Identify the stage at which the boot process fails", "Display the time", "Play music"], 1, "Each code corresponds to a POST step."),
    ("The legacy PCI bus (32-bit, 33 MHz) has a peak bandwidth of about:",
     ["33 MB/s", "133 MB/s", "1 GB/s", "4 GB/s"], 1, "32 bits × 33 MHz = 4 bytes × 33.3 million ≈ 133 MB/s."),
]

MEMORY_SYS = [
    ("Memory modules used in laptops are called:",
     ["DIMM", "SO-DIMM", "SIMM", "RIMM"], 1, "SO-DIMM (Small Outline DIMM) is about half the length of a desktop DIMM."),
    ("A DDR4 desktop DIMM has how many pins?",
     ["184", "240", "288", "200"], 2, "DDR = 184, DDR2 and DDR3 = 240, DDR4 and DDR5 = 288."),
    ("The standard operating voltage of DDR4 memory is:",
     ["1.8 V", "1.5 V", "1.2 V", "1.1 V"], 2, "DDR2 = 1.8 V, DDR3 = 1.5 V, DDR4 = 1.2 V, DDR5 = 1.1 V."),
    ("DDR3 and DDR4 modules cannot be interchanged because:",
     ["They have different colours", "Their notch positions, pin counts and voltages differ", "DDR4 is always larger", "DDR3 is SRAM"], 1, "The notch prevents inserting the wrong type."),
    ("A distinctive feature of DDR5 modules is:",
     ["An on-module power management IC (PMIC) and two independent sub-channels per module", "No refresh required", "They are SRAM", "They use 184 pins"], 0,
     "Moving power regulation onto the module improves signal integrity."),
    ("ECC memory can:",
     ["Increase capacity", "Detect and correct single-bit errors", "Run at higher voltage only", "Work without refresh"], 1, "ECC is common in servers and workstations."),
    ("What is the true CAS latency, in nanoseconds, of DDR4-3200 CL16?",
     ["5 ns", "10 ns", "16 ns", "20 ns"], 1, "Latency = CL × 2000 / data rate = 16 × 2000 / 3200 = 10 ns."),
    ("Intel XMP profiles are used to:",
     ["Update the BIOS", "Automatically apply the memory's rated higher speed and timings", "Encrypt RAM", "Test the hard disk"], 1, "AMD's equivalent is EXPO."),
    ("How many address lines are needed for a 1K × 8 memory chip?",
     ["8", "10", "16", "1024"], 1, "1K = 1024 = 2^10 locations, so 10 address lines; 8 data lines carry each byte."),
    ("How many 1K × 4 chips are needed to build a 4K × 8 memory?",
     ["4", "8", "16", "2"], 1, "Total bits: (4K × 8) / (1K × 4) = 8 chips (2 per row for 8 bits, 4 rows for 4K)."),
    ("A byte-addressable memory of 64 KB needs how many address lines?",
     ["14", "16", "18", "20"], 1, "64 KB = 2^16 bytes."),
    ("A 256K × 8 memory chip has a capacity of:",
     ["256 KB (2 Mbit)", "256 bits", "2 KB", "8 MB"], 0, "256K locations × 1 byte = 256 KB = 2,097,152 bits."),
    ("To build a 4K × 8 memory from four 1K × 8 chips, the chip-select signals are generated using a:",
     ["2-to-4 decoder driven by the two highest address lines", "4-to-16 decoder", "Multiplexer", "Flip-flop"], 0,
     "12 address lines are needed: 10 go to every chip and 2 select one of the four chips."),
    ("Dual-channel memory operation mainly increases:",
     ["Capacity", "Memory bandwidth", "Latency", "Voltage"], 1, "Two 64-bit channels transfer data in parallel."),
    ("The Windows 'paging file' (pagefile.sys) is used for:",
     ["Printing", "Virtual memory: storing pages of memory on disk when RAM is full", "Storing the BIOS", "Caching web pages"], 1, "Linux uses a swap partition or swap file."),
    ("SIMM modules, used in older PCs, had connectors that were:",
     ["Redundant on both sides of the module (same signals)", "Independent on each side", "Optical", "Wireless"], 0, "DIMMs have separate contacts on each side, allowing a wider data path."),
    ("RIMM modules were used with:",
     ["DDR4", "Rambus DRAM (RDRAM)", "SDRAM only", "Flash"], 1, "RDRAM was used by some Pentium 4 systems."),
    ("Which statement about installing RAM is correct?",
     ["Modules can be inserted either way round", "The notch must align with the key in the slot, and the clips lock when fully inserted", "RAM must be installed while the PC is on", "RAM needs thermal paste"], 1,
     "Incorrect alignment can damage the module or slot."),
    ("Registered (buffered) memory is mainly used in:",
     ["Smartphones", "Servers with many memory modules", "Calculators", "Graphics cards only"], 1, "A register buffers signals, allowing more modules per channel."),
    ("The effective data rate of DDR memory is twice its I/O clock because:",
     ["It uses two chips", "It transfers data on both rising and falling clock edges", "It has double capacity", "It uses two voltages"], 1, "Hence 'Double Data Rate'."),
    ("Which type of memory is used as the main system RAM in PCs?",
     ["SRAM", "DRAM (SDRAM/DDR)", "EPROM", "Magnetic core"], 1, "SRAM is used for caches."),
    ("A DDR4 SO-DIMM has how many pins?",
     ["204", "260", "288", "240"], 1, "DDR3 SO-DIMM = 204 pins; DDR4 SO-DIMM = 260; DDR5 SO-DIMM = 262."),
    ("If a PC has 8 GB of RAM installed but shows only about 3.2 GB usable, the most likely reason is:",
     ["Faulty keyboard", "A 32-bit operating system is installed", "Too many fans", "Wrong monitor"], 1, "32-bit Windows can use at most about 3–4 GB."),
    ("Consider the statements:\nI. Memory modules of different speeds usually run at the speed of the slowest module.\nII. Mixing different capacities always prevents booting.\nWhich is/are correct?",
     I_II, 0, "Different capacities often work (sometimes without full dual channel); mismatched speeds fall back to the slowest."),
    ("Assertion (A): SRAM is used for cache memory.\nReason (R): SRAM is cheaper and denser than DRAM.",
     AR, 2, "A is true, but R is false: SRAM is costlier and less dense. It is used for cache because it is faster and needs no refresh."),
    ("How many bits does a standard (non-ECC) DDR4 DIMM transfer per memory transfer?",
     ["32", "64", "72", "128"], 1, "ECC DIMMs are 72 bits wide (64 data + 8 check bits)."),
    ("The time taken to access data from DRAM is typically in the range of:",
     ["Seconds", "Milliseconds", "Tens of nanoseconds", "Picoseconds only"], 2, "Disk access is in milliseconds, which is why RAM is so much faster."),
    ("Increasing RAM from 4 GB to 16 GB mainly helps a computer to:",
     ["Store more files permanently", "Run more and larger programs simultaneously without slow paging", "Increase screen resolution", "Improve Wi-Fi range"], 1, "RAM is working memory."),
    ("Memory 'CL' in module specifications stands for:",
     ["Clock Level", "CAS Latency", "Cache Line", "Channel Length"], 1, "It is the number of clock cycles between a column command and data availability."),
    ("A computer has 4 DIMM slots and supports up to 64 GB. The largest module size it can use in each slot is most likely:",
     ["8 GB", "16 GB", "32 GB", "64 GB"], 1, "64 GB ÷ 4 slots = 16 GB per slot."),
]

POWER = [
    ("A computer's SMPS is preferred over a linear power supply because it is:",
     ["Heavier and less efficient", "Lighter, smaller and more efficient", "Only for AC devices", "Noise-free"], 1, "High-frequency switching allows small transformers and higher efficiency."),
    ("In an ATX power supply, the yellow wires carry:",
     ["+3.3 V", "+5 V", "+12 V", "Ground"], 2, "Red = +5 V, orange = +3.3 V, black = ground."),
    ("In an ATX power supply, the red wires carry:",
     ["+5 V", "+12 V", "−12 V", "+3.3 V"], 0, "Red is the +5 V rail."),
    ("The green wire (PS_ON#) of the ATX connector:",
     ["Carries +12 V", "Turns the PSU on when pulled to ground", "Is the Power Good signal", "Carries standby power"], 1, "Shorting green to black is used to test a PSU."),
    ("The purple wire (+5VSB) in an ATX PSU provides:",
     ["+12 V", "Standby power even when the PC is off, for features like wake-on-LAN", "Ground", "The Power Good signal"], 1, "It keeps soft-power circuits alive."),
    ("The grey 'Power Good' (PWR_OK) signal tells the motherboard that:",
     ["The CPU is hot", "The PSU outputs have stabilised and it is safe to start", "The battery is low", "The fan has failed"], 1, "The board holds the CPU in reset until this signal arrives."),
    ("A standard PCIe 8-pin power connector is rated for:",
     ["75 W", "150 W", "300 W", "600 W"], 1, "A 6-pin connector is rated 75 W and the PCIe x16 slot itself supplies up to 75 W."),
    ("A graphics card with one 8-pin PCIe connector plus slot power can draw a maximum of about:",
     ["150 W", "225 W", "300 W", "75 W"], 1, "150 W (8-pin) + 75 W (slot) = 225 W."),
    ("SATA power connectors have how many pins?",
     ["4", "15", "24", "8"], 1, "They supply 3.3 V, 5 V and 12 V to SATA drives."),
    ("The 4-pin Molex connector is traditionally used to power:",
     ["The CPU", "Older IDE drives, fans and peripherals", "RAM", "USB ports"], 1, "It carries +5 V and +12 V."),
    ("An '80 PLUS Gold' PSU is:",
     ["Rated at 80 W", "More efficient than an 80 PLUS Bronze PSU", "Less efficient than Bronze", "Gold-plated"], 1, "Levels in order: White, Bronze, Silver, Gold, Platinum, Titanium."),
    ("A modular power supply:",
     ["Has fixed cables", "Allows unused cables to be detached, improving airflow and neatness", "Has no fan", "Supplies only 5 V"], 1, "Semi-modular PSUs have some fixed cables."),
    ("A UPS rated 1000 VA with a power factor of 0.6 can supply a real load of about:",
     ["1000 W", "600 W", "1666 W", "400 W"], 1, "Watts = VA × power factor = 1000 × 0.6 = 600 W."),
    ("Which UPS type has zero transfer time because the load always runs from the inverter?",
     ["Offline (standby)", "Line-interactive", "Online (double conversion)", "Surge protector"], 2, "It continuously converts AC → DC → AC."),
    ("A line-interactive UPS includes an AVR, which:",
     ["Plays audio", "Corrects moderate voltage fluctuations without switching to battery", "Converts DC to AC continuously", "Charges phones"], 1, "Automatic Voltage Regulation saves battery life."),
    ("A 12 V, 7 Ah UPS battery stores about how much energy?",
     ["19 Wh", "84 Wh", "7 Wh", "120 Wh"], 1, "Energy = 12 V × 7 Ah = 84 Wh (ideal)."),
    ("Ignoring losses, how long could an 84 Wh battery run a 42 W load?",
     ["30 minutes", "1 hour", "2 hours", "4 hours"], 2, "84 Wh ÷ 42 W = 2 hours; real backup is shorter because of inverter losses."),
    ("A surge protector mainly protects equipment against:",
     ["Long power cuts", "Sudden short voltage spikes", "Low battery", "Viruses"], 1, "It does not provide backup power."),
    ("The standard mains supply in India is:",
     ["110 V, 60 Hz", "230 V, 50 Hz", "220 V, 60 Hz", "120 V, 50 Hz"], 1, "PSUs sold in India must support 230 V AC."),
    ("When choosing PSU wattage, it is recommended to:",
     ["Match exactly the total component power", "Add headroom (e.g. 20–30%) above the estimated peak load", "Use the smallest available", "Ignore the GPU"], 1,
     "Headroom improves efficiency, stability and future upgrades."),
    ("Active PFC in a power supply:",
     ["Reduces fan noise", "Improves the power factor, drawing current more efficiently from the mains", "Increases voltage to 24 V", "Stores energy"], 1,
     "It reduces reactive power and harmonics."),
    ("The −12 V rail in an ATX PSU is carried by the:",
     ["Blue wire", "Yellow wire", "Red wire", "Orange wire"], 0, "It is rarely used by modern components."),
    ("Which statement about an offline (standby) UPS is correct?",
     ["It powers the load from the inverter all the time", "It switches to battery only when mains power fails, with a short transfer time", "It has no battery", "It is the most expensive type"], 1,
     "It is common for home PCs."),
    ("The newer 12VHPWR (16-pin) connector on high-end graphics cards can deliver up to:",
     ["150 W", "300 W", "600 W", "1200 W"], 2, "It was introduced with the ATX 3.0 specification."),
    ("Consider the statements:\nI. A voltage stabiliser provides backup power during outages.\nII. A surge protector provides backup power during outages.\nWhich is/are correct?",
     I_II, 3, "Neither provides backup power; only a UPS (with a battery) does."),
    ("Assertion (A): A higher-efficiency PSU produces less heat.\nReason (R): Less input power is wasted as heat to deliver the same output power.",
     AR, 0, "Losses in a PSU appear mostly as heat."),
    ("A PSU delivers 400 W to the components at 80% efficiency. How much power does it draw from the wall?",
     ["320 W", "400 W", "480 W", "500 W"], 3, "Input = output / efficiency = 400 / 0.8 = 500 W."),
    ("The orange wires in an ATX power supply carry:",
     ["+3.3 V", "+5 V", "+12 V", "−5 V"], 0, "Orange = +3.3 V."),
    ("A 'paperclip test' on an ATX PSU involves:",
     ["Shorting the green PS_ON wire to a black ground wire to switch the PSU on without a motherboard", "Opening the PSU casing", "Connecting yellow to red", "Measuring the fan"], 0,
     "It checks whether the PSU powers on; it must be done carefully with the PSU unplugged while connecting."),
    ("Why must a PSU never be opened by an untrained person even when unplugged?",
     ["It contains a virus", "Its large capacitors can hold a dangerous charge", "It is glued", "It voids the monitor warranty"], 1, "Stored charge can cause serious electric shock."),
]

ASSEMBLY = [
    ("Before handling computer components, you should first:",
     ["Switch on the PSU", "Discharge static electricity, e.g. by using an anti-static wrist strap", "Wet your hands", "Apply thermal paste to your hands"], 1, "Electrostatic discharge can destroy chips."),
    ("When installing an Intel LGA CPU, you should:",
     ["Press hard until it clicks", "Align the triangle/notches, place it gently without force, then close the retention lever", "Bend the pins to fit", "Apply thermal paste under the CPU"], 1,
     "LGA socket pins are delicate and bend easily."),
    ("How much thermal paste is typically applied to a desktop CPU?",
     ["A thick layer covering the motherboard", "A pea-sized amount in the centre of the CPU", "None", "A full syringe"], 1, "Mounting pressure spreads it; too much can overflow."),
    ("The CPU cooler fan cable should be connected to the motherboard header labelled:",
     ["SYS_FAN", "CPU_FAN", "PWR_SW", "USB3"], 1, "Many boards refuse to boot or warn if CPU_FAN reads no speed."),
    ("Standoffs are installed in the case before mounting the motherboard to:",
     ["Hold the GPU", "Keep the board raised so its underside does not short against the metal case", "Increase airflow", "Hold RAM"], 1,
     "Standoffs must match the board's mounting holes."),
    ("The I/O shield is installed:",
     ["After the motherboard is mounted", "In the case's rear opening before mounting the motherboard", "On the GPU", "On the PSU"], 1, "Some boards come with a pre-installed shield."),
    ("A graphics card is normally installed in the:",
     ["Top-most PCIe x16 slot (connected to the CPU lanes)", "Any PCIe x1 slot", "M.2 slot", "DIMM slot"], 0, "It also needs PCIe power connectors if required."),
    ("A monitor connected to the motherboard's HDMI port shows no display, although a graphics card is installed. The likely fix is to:",
     ["Replace the CPU", "Connect the monitor to the graphics card's output port", "Remove the RAM", "Reinstall the OS"], 1,
     "When a dedicated GPU is present, integrated graphics output is often disabled."),
    ("Case front-panel connectors include:",
     ["PWR_SW, RESET_SW, POWER LED and HDD LED", "PCIe and SATA", "DIMM and M.2", "CPU and GPU"], 0, "LED connectors have polarity (+/−)."),
    ("Which is the usual airflow arrangement in a PC case?",
     ["Front fans exhaust, rear fans intake", "Front (and bottom) fans intake, rear and top fans exhaust", "All fans exhaust", "No fans are needed"], 1, "This follows the natural rise of hot air."),
    ("For dual-channel operation with two RAM modules on a four-slot board, you should usually:",
     ["Use slots 1 and 2 next to each other", "Use the slots recommended in the manual (often A2 and B2)", "Use any two slots", "Use only one module"], 1,
     "The manual shows the correct slot pairs."),
    ("Which key is commonly pressed during start-up to enter the BIOS/UEFI setup?",
     ["Esc only", "Del or F2 (depending on the manufacturer)", "Ctrl+Alt+Del", "F12 only"], 1, "F12 or F8/F11 often open a boot menu instead."),
    ("After assembling a PC and booting for the first time, you should first:",
     ["Install games", "Check in BIOS/UEFI that the CPU, RAM and drives are detected correctly", "Overclock the CPU to maximum", "Remove the cooler"], 1,
     "Then set the boot order and install the OS."),
    ("An operating system is usually installed on a new PC from:",
     ["A bootable USB drive or DVD", "The CMOS battery", "The PSU", "A keyboard"], 0, "Set the boot device in BIOS or use the one-time boot menu."),
    ("After installing the OS, the next important step is to:",
     ["Remove the RAM", "Install device drivers and updates", "Disconnect the monitor", "Clear the CMOS"], 1, "Drivers ensure devices work correctly."),
    ("Which tool is most commonly needed to assemble a PC?",
     ["Hammer", "Phillips (cross-head) screwdriver", "Soldering iron", "Wire stripper"], 1, "Most case, board and drive screws are Phillips."),
    ("When a newly assembled PC powers on but shows no display and gives repeated beeps, the first component to check is usually:",
     ["The keyboard", "The RAM (reseat the modules)", "The speakers", "The mouse"], 1, "Beep codes vary by vendor, but memory problems are a common cause."),
    ("Components such as RAM and expansion cards should be held:",
     ["By the gold contacts", "By their edges", "By the chips", "With wet hands"], 1, "Touching contacts leaves oil and risks ESD damage."),
    ("An M.2 NVMe SSD is secured on the motherboard using:",
     ["Glue", "A small screw or latch at the end of the slot", "A SATA cable", "Thermal paste"], 1, "Some boards use tool-less latches."),
    ("Good cable management in a PC mainly helps to:",
     ["Increase CPU speed directly", "Improve airflow and make maintenance easier", "Increase RAM capacity", "Reduce disk space"], 1, "Neat cables do not block airflow."),
    ("Which connection must be made for a SATA hard disk to work?",
     ["Only the SATA data cable", "Both the SATA data cable (to the motherboard) and the SATA power cable (from the PSU)", "Only the power cable", "A USB cable"], 1,
     "Data and power are separate connections."),
    ("Consider the statements:\nI. The PC should be unplugged from mains while installing components.\nII. Thermal paste is applied between the CPU and the socket.\nWhich is/are correct?",
     I_II, 0, "Thermal paste goes between the CPU's heat spreader and the cooler, not into the socket."),
    ("Assertion (A): Installing the CPU and RAM before fixing the motherboard in the case is recommended.\nReason (R): Motherboards are made as multi-layer printed circuit boards.",
     AR, 1, "Both are true, but R does not explain A; the reason is that an open board gives more working space and less risk of damage."),
    ("Overclocking a CPU means:",
     ["Running it below its rated speed", "Running it above its rated speed, usually with more heat and power", "Removing its cache", "Replacing the clock battery"], 1, "It requires good cooling and a suitable motherboard."),
    ("The main reason for applying the BIOS setting 'XMP/EXPO' after assembly is to:",
     ["Enable the RAM to run at its advertised speed", "Enable Wi-Fi", "Change the boot logo", "Reset the time"], 0, "Without it, RAM runs at default JEDEC speeds."),
    ("If the PC does not power on at all after assembly, a likely cause is:",
     ["The front-panel power switch connector is not connected correctly, or the PSU switch is off", "A wrong wallpaper", "An old keyboard", "Missing antivirus"], 0,
     "Check the PSU switch, power cable and PWR_SW header first."),
    ("Which order is correct for a typical PC build?",
     ["Mount motherboard in case → install CPU → apply paste → install PSU", "Install CPU, cooler and RAM on the board → mount board in case → install PSU and drives → connect cables → first boot",
      "Install OS → install CPU → install RAM", "Connect monitor → install CPU → install case"], 1, "This minimises risk and effort."),
    ("An anti-static bag is used for:",
     ["Storing and carrying electronic components safely", "Cooling the CPU", "Holding screws only", "Packing the monitor stand"], 0, "It shields components from static charges."),
    ("Why should the CPU cooler be mounted with even pressure on all corners?",
     ["For looks", "To ensure good, uniform contact for heat transfer and avoid damaging the CPU", "To increase clock speed", "To reduce RAM usage"], 1,
     "Tightening screws diagonally in steps is recommended."),
    ("POST stands for:",
     ["Power-On Self-Test", "Primary Operating System Test", "Processor Output Status Test", "Power Output Supply Test"], 0, "It checks basic hardware before the OS loads."),
]

TOPICS = {
    "Computer Configuration & Motherboard": [("1 · Typical Configuration of a Computer System", CONFIG),
                                             ("2 · Motherboard: Introduction and Types", MB_TYPES),
                                             ("3 · Components of the Motherboard", MB_COMPONENTS)],
    "Memory, Power Supply & Assembling": [("1 · Memory", MEMORY_SYS), ("2 · Power Supply to the Computer System", POWER),
                                          ("3 · Assembling the Computer System", ASSEMBLY)],
}
