"""Paper 2 · Unit 1 · topics U1-03 and U1-04 (5 sub-topics × 30)."""
from packlib import AR, I_II

INPUT = [
    ("The QWERTY keyboard layout was designed by:",
     ["Douglas Engelbart", "Christopher Latham Sholes", "Charles Babbage", "Bill Gates"], 1, "Sholes designed it for typewriters in the 1870s."),
    ("The computer mouse was invented in the 1960s by:",
     ["Douglas Engelbart", "Steve Jobs", "Tim Berners-Lee", "Alan Kay"], 0, "Engelbart demonstrated it at SRI in the famous 1968 'Mother of All Demos'."),
    ("Caps Lock, Num Lock and Scroll Lock are examples of:",
     ["Function keys", "Toggle keys", "Modifier keys", "Navigation keys"], 1, "Each press switches the mode on or off."),
    ("Shift, Ctrl and Alt are called modifier keys because they:",
     ["Lock the keyboard", "Change the action of other keys when held down together", "Restart the computer", "Only work with the mouse"], 1,
     "For example Ctrl+C copies, while C alone types a letter."),
    ("The MICR character set E-13B used on Indian cheques consists of:",
     ["10 digits only", "10 digits and 4 special symbols", "26 letters and 10 digits", "All ASCII characters"], 1, "E-13B has 14 characters in total."),
    ("OMR technology is most commonly used to:",
     ["Read cheques", "Evaluate multiple-choice answer sheets", "Read barcodes", "Scan photographs"], 1, "OMR detects the presence of pencil/pen marks in fixed positions."),
    ("OCR software converts:",
     ["Handwritten signatures into passwords", "Images of printed text into editable, machine-readable text", "Audio into text", "Barcodes into prices"], 1,
     "Optical Character Recognition recognises letters in scanned images."),
    ("QR codes, a type of 2D barcode, were invented in 1994 by:",
     ["IBM", "Denso Wave (Japan)", "Google", "Samsung"], 1, "Denso Wave developed QR codes to track automobile parts."),
    ("A UPC code on product packages is read by a:",
     ["MICR reader", "Barcode reader", "Light pen", "OMR"], 1, "Barcode readers decode the pattern of bars into a product number."),
    ("A light pen works by:",
     ["Detecting light emitted from a point on the CRT screen", "Emitting infrared signals to the keyboard", "Measuring pressure", "Recording sound"], 0,
     "Light pens were used with CRT displays to select or draw on the screen."),
    ("A pointing device in which the user rotates a ball held in a stationary socket is a:",
     ["Joystick", "Trackball", "Touchpad", "Stylus"], 1, "A trackball is like an upside-down mouse and needs little desk space."),
    ("A graphics tablet (digitiser) is mainly used for:",
     ["Printing", "Drawing and tracing images precisely with a stylus", "Scanning barcodes", "Recording video"], 1, "Artists and CAD users draw on the tablet surface."),
    ("Scanner resolution is expressed in:",
     ["DPI (dots per inch)", "RPM", "PPM", "Hz"], 0, "Higher DPI captures finer detail."),
    ("Which type of scanner moves the scanning head under a stationary document placed on glass?",
     ["Flatbed scanner", "Handheld scanner", "Drum scanner", "Sheet-fed scanner"], 0, "Flatbed scanners are the most common office scanners."),
    ("Fingerprint and iris scanners are examples of:",
     ["Biometric input devices", "Output devices", "Storage devices", "Processing devices"], 0, "Biometric devices identify people by physical characteristics."),
    ("India's FASTag system for electronic toll collection uses:",
     ["MICR", "RFID", "OMR", "Light pen"], 1, "An RFID tag on the windscreen is read automatically at toll plazas."),
    ("Swiping a debit card at a shop uses a:",
     ["Magnetic stripe reader (or chip reader)", "Light pen", "Plotter", "OMR reader"], 0, "The reader captures the card data stored on the magnetic stripe or EMV chip."),
    ("Which of the following is an input device?",
     ["Plotter", "Microphone", "Speaker", "Projector"], 1, "A microphone captures sound as input; the others are output devices."),
    ("A standard full-size Windows keyboard typically has about:",
     ["84 keys", "104 keys", "150 keys", "64 keys"], 1, "The common 104-key layout includes function keys, a numeric keypad and Windows keys."),
    ("The input device found on most laptops for moving the pointer by sliding a finger is the:",
     ["Trackball", "Touchpad", "Joystick", "Light pen"], 1, "A touchpad senses finger movement through capacitance."),
    ("A joystick is mainly used for:",
     ["Typing documents", "Controlling games and simulators", "Scanning documents", "Printing"], 1, "Joysticks give directional control in games and flight simulators."),
    ("Which input device converts spoken words into text?",
     ["Speech (voice) recognition system with a microphone", "Plotter", "Monitor", "Speaker"], 0, "Voice input software processes audio from a microphone."),
    ("Which device reads data from pre-printed forms by detecting marks and printed characters together, e.g. in examinations?",
     ["OMR/OCR scanner", "Joystick", "Webcam", "Plotter"], 0, "Exam sheets often combine OMR bubbles with OCR-readable text."),
    ("A webcam is:",
     ["An output device", "An input device that captures video", "A storage device", "A processing device"], 1, "It captures images and video for the computer."),
    ("Consider the statements:\nI. A touch screen can act as both an input and an output device.\nII. A scanner is an output device.\nWhich is/are correct?",
     I_II, 0, "A touch screen displays output and accepts touch input; a scanner is an input device."),
    ("Assertion (A): MICR is preferred for cheque processing in banks.\nReason (R): Magnetic-ink characters can be read accurately even if overwritten or stamped over.",
     AR, 0, "MICR reading is reliable despite marks and stamps, which suits cheque clearing."),
    ("The key F1 in most Windows applications is used to:",
     ["Save a file", "Open Help", "Close a window", "Print"], 1, "F1 opens the help system in most programs."),
    ("A stylus is used with:",
     ["A printer", "A touch screen or graphics tablet", "A hard disk", "A speaker"], 1, "It provides precise pointing and drawing."),
    ("Which of these is NOT an input device?",
     ["Keyboard", "Scanner", "Monitor", "Mouse"], 2, "A monitor is an output device."),
    ("An optical mouse detects movement using:",
     ["A rubber ball and rollers", "An LED/laser light and a small image sensor", "Magnetic ink", "Sound waves"], 1,
     "It takes rapid pictures of the surface to track movement; older mechanical mice used a ball."),
]

OUTPUT = [
    ("A printed copy of output on paper is called:",
     ["Soft copy", "Hard copy", "Back-up copy", "Carbon copy"], 1, "Output shown on a screen is a soft copy."),
    ("Which of the following is an impact printer?",
     ["Laser printer", "Inkjet printer", "Dot-matrix printer", "Thermal printer"], 2, "Dot-matrix printers strike an ink ribbon with pins."),
    ("Laser printers form images using:",
     ["Liquid ink sprayed through nozzles", "Toner powder fused onto paper after a laser charges a drum", "Heat-sensitive paper", "Pins striking a ribbon"], 1,
     "This is the electrophotographic process, similar to photocopiers."),
    ("Inkjet printers produce images by:",
     ["Striking a ribbon", "Spraying tiny droplets of liquid ink onto paper", "Burning the paper", "Using toner and a fuser"], 1, "Thermal or piezoelectric heads eject ink droplets."),
    ("Thermal printers are commonly used for:",
     ["Printing receipts at shops and ATMs", "High-quality photographs", "Engineering drawings", "Books"], 0, "They use heat-sensitive paper and need no ink."),
    ("The speed of a laser printer is usually measured in:",
     ["CPS", "PPM", "DPI", "RPM"], 1, "Pages per minute; dot-matrix printers are measured in characters per second (CPS)."),
    ("A daisy-wheel printer:",
     ["Prints high-quality graphics", "Produces letter-quality text but cannot print graphics", "Is a non-impact printer", "Uses toner"], 1,
     "Each character is a fixed shape on a spoke of the wheel."),
    ("Which printer is best suited for printing multi-part carbon forms (e.g. invoices with copies)?",
     ["Laser printer", "Inkjet printer", "Dot-matrix printer", "3D printer"], 2, "Only impact printers can print through carbon copies."),
    ("A 3D printer creates objects by:",
     ["Removing material from a block", "Adding material layer by layer (additive manufacturing)", "Printing on paper", "Scanning objects"], 1,
     "FDM printers extrude melted plastic layer by layer."),
    ("A plotter is best suited for:",
     ["Printing letters", "Large-format drawings such as maps and architectural plans", "Receipts", "Photographs"], 1, "Plotters draw continuous lines on large sheets."),
    ("Screens create colours using the ______ model, while printers use the ______ model.",
     ["CMYK; RGB", "RGB; CMYK", "RGB; RGB", "CMYK; CMYK"], 1, "Screens mix light additively (RGB); printers mix inks subtractively (CMYK)."),
    ("The smallest element of a displayed image is a:",
     ["Byte", "Pixel", "Dot pitch", "Frame"], 1, "Pixel = picture element."),
    ("A Full HD display has a resolution of:",
     ["1280 × 720", "1920 × 1080", "2560 × 1440", "3840 × 2160"], 1, "3840 × 2160 is 4K UHD; 1280 × 720 is HD."),
    ("How many bytes are needed to store one full frame of a 1920 × 1080 image with 24-bit colour?",
     ["2,073,600", "6,220,800", "49,766,400", "691,200"], 1, "1920 × 1080 = 2,073,600 pixels × 3 bytes = 6,220,800 bytes."),
    ("The refresh rate of a monitor is measured in:",
     ["DPI", "Hertz (Hz)", "PPM", "Bytes"], 1, "A 60 Hz monitor redraws the image 60 times per second."),
    ("'Dot pitch' of a monitor refers to:",
     ["The number of colours", "The distance between adjacent pixels of the same colour; smaller means sharper", "The screen size", "The brightness"], 1,
     "A smaller dot pitch gives a sharper image."),
    ("Which display technology needs a separate backlight?",
     ["OLED", "LCD", "CRT", "Plasma"], 1, "LCD pixels only block light, so they need a backlight (often LEDs); OLED pixels emit light."),
    ("An 'LED monitor' sold today is usually:",
     ["A monitor made only of LEDs as pixels", "An LCD monitor with an LED backlight", "A CRT with LEDs", "A projector"], 1, "The LEDs provide the backlighting for the LCD panel."),
    ("CRT monitors create images using:",
     ["Liquid crystals", "An electron gun firing at a phosphor-coated screen", "Organic LEDs", "Lasers"], 1, "The electron beam scans the screen line by line."),
    ("The aspect ratio of most modern widescreen monitors is:",
     ["4:3", "16:9", "1:1", "3:2"], 1, "16:9 is the standard for HD and Full HD content."),
    ("Which of the following is an output device?",
     ["Scanner", "Projector", "Microphone", "Joystick"], 1, "A projector displays computer output on a large screen."),
    ("HDMI differs from VGA because HDMI:",
     ["Carries only analog video", "Carries digital video and audio in one cable", "Carries only audio", "Is used only for keyboards"], 1, "VGA carries analog video only."),
    ("A Braille embosser is an output device for:",
     ["Visually impaired users, producing raised-dot text", "Printing photographs", "3D models", "Barcodes"], 0, "It punches Braille dots into paper."),
    ("Line printers are measured in:",
     ["LPM (lines per minute)", "PPM", "DPI", "Hz"], 0, "They print an entire line at a time, which makes them fast impact printers."),
    ("Which printer uses a drum or chain carrying characters?",
     ["Line printer", "Laser printer", "Inkjet printer", "Thermal printer"], 0, "Drum and chain printers are types of line printers."),
    ("Consider the statements:\nI. Laser printers are non-impact printers.\nII. Dot-matrix printers can print graphics.\nWhich is/are correct?",
     I_II, 2, "Dot-matrix printers print graphics as patterns of dots, though at low quality."),
    ("Assertion (A): OLED displays can show deeper blacks than LCD displays.\nReason (R): OLED pixels emit their own light and can be switched off completely.",
     AR, 0, "LCD backlights leak some light, so blacks look greyish."),
    ("A speaker is an example of a/an:",
     ["Input device", "Audio output device", "Storage device", "Processing device"], 1, "It converts electrical signals into sound."),
    ("Which printer technology is used in most office photocopier-style printers producing 30–60 pages per minute?",
     ["Laser", "Daisy-wheel", "Dot-matrix", "Plotter"], 0, "Laser printers are fast and suited to high-volume text printing."),
    ("The resolution 3840 × 2160 pixels is commonly called:",
     ["HD", "Full HD", "4K UHD", "8K"], 2, "It is four times the pixels of Full HD."),
]

MEMORY_DEVICES = [
    ("SRAM stores each bit using:",
     ["A capacitor", "A flip-flop (typically 6 transistors)", "A magnetic domain", "A laser pit"], 1, "SRAM needs no refresh but is costlier and less dense than DRAM."),
    ("PROM can be:",
     ["Erased with UV light", "Programmed only once by the user", "Erased electrically byte by byte", "Written unlimited times"], 1, "PROM fuses are blown once during programming."),
    ("EEPROM differs from EPROM because EEPROM is:",
     ["Volatile", "Erased electrically, byte by byte, without removing the chip", "Erased by UV light", "Not reprogrammable"], 1,
     "EPROM needs UV light; EEPROM can be rewritten electrically in the circuit."),
    ("Flash memory is a type of EEPROM that is erased:",
     ["One bit at a time", "In blocks", "By ultraviolet light", "By heating"], 1, "Block erasure makes flash fast and dense; it is used in SSDs and pen drives."),
    ("Which level of cache is usually the smallest and fastest?",
     ["L1", "L2", "L3", "L4"], 0, "L1 is closest to the core; L3 is larger, slower and often shared by all cores."),
    ("On a hard disk, concentric circles on a platter surface are called:",
     ["Sectors", "Tracks", "Cylinders", "Clusters"], 1, "Tracks are divided into sectors; the same track on all surfaces forms a cylinder."),
    ("The set of tracks at the same position on all platter surfaces is called a:",
     ["Sector", "Cylinder", "Block", "Cluster"], 1, "Reading a whole cylinder needs no head movement."),
    ("The time for the read/write head to move to the required track is called:",
     ["Rotational latency", "Seek time", "Transfer time", "Access time"], 1, "Access time = seek time + rotational latency + transfer time."),
    ("What is the average rotational latency of a disk spinning at 7200 RPM?",
     ["8.33 ms", "4.17 ms", "2.08 ms", "16.67 ms"], 1, "One rotation takes 60/7200 s = 8.33 ms; on average half a rotation is needed, 4.17 ms."),
    ("A disk has 8 surfaces, 1000 tracks per surface, 100 sectors per track and 512 bytes per sector. Its capacity is:",
     ["409,600,000 bytes", "51,200,000 bytes", "4,096,000 bytes", "819,200,000 bytes"], 0, "8 × 1000 × 100 × 512 = 409,600,000 bytes (about 409.6 MB)."),
    ("The typical capacity of a standard CD-ROM is about:",
     ["1.44 MB", "700 MB", "4.7 GB", "25 GB"], 1, "1.44 MB is a floppy disk, 4.7 GB a DVD and 25 GB a single-layer Blu-ray disc."),
    ("A single-layer, single-sided DVD holds about:",
     ["700 MB", "4.7 GB", "8.5 GB", "25 GB"], 1, "A dual-layer DVD holds about 8.5 GB."),
    ("Blu-ray discs get their name from the:",
     ["Blue plastic used", "Blue-violet laser (405 nm) used to read and write them", "Company that invented them", "Blue light emitted"], 1,
     "The shorter wavelength allows smaller pits and higher capacity."),
    ("Which storage medium provides only sequential access?",
     ["Hard disk", "Magnetic tape", "SSD", "RAM"], 1, "To reach data on tape, all preceding data must be passed; tapes are used for backups."),
    ("CD-R media are:",
     ["Rewritable many times", "Write once, read many (WORM)", "Read-only, factory pressed", "Volatile"], 1, "CD-RW discs can be erased and rewritten."),
    ("Which statement about SSDs is correct?",
     ["They have spinning platters", "They use NAND flash memory and have no moving parts", "They are volatile", "They are slower than HDDs"], 1,
     "SSDs are faster and more shock-resistant than HDDs."),
    ("Arrange in decreasing order of cost per bit:",
     ["Registers > Cache > RAM > HDD", "HDD > RAM > Cache > Registers", "RAM > Registers > Cache > HDD", "Cache > HDD > RAM > Registers"], 0,
     "Faster memory is more expensive per bit, which is why the memory hierarchy exists."),
    ("A pen drive stores data using:",
     ["Magnetic tape", "Flash memory", "Optical pits", "DRAM"], 1, "USB flash drives use NAND flash chips."),
    ("RAM is called 'random access' memory because:",
     ["Data are stored randomly", "Any location can be accessed directly in about the same time", "It loses data randomly", "It is used randomly"], 1,
     "Access time does not depend on the location, unlike tape."),
    ("Which memory is used to store the BIOS/UEFI firmware on modern motherboards?",
     ["DRAM", "Flash memory (EEPROM)", "SRAM cache", "Magnetic tape"], 1, "Flash allows firmware updates."),
    ("A disk spins at 5400 RPM. The time for one full rotation is approximately:",
     ["5.56 ms", "11.11 ms", "4.17 ms", "22.2 ms"], 1, "60 / 5400 s = 0.01111 s = 11.11 ms."),
    ("Which of the following is secondary storage?",
     ["Cache", "Registers", "Hard disk", "RAM"], 2, "Secondary storage is non-volatile and not directly addressed by the CPU."),
    ("The smallest addressable unit of storage on a hard disk track is the:",
     ["Cylinder", "Sector", "Platter", "Head"], 1, "Sectors traditionally hold 512 bytes; modern drives often use 4 KB."),
    ("Which laser wavelength is used for reading a standard DVD?",
     ["About 780 nm (infrared)", "About 650 nm (red)", "About 405 nm (blue-violet)", "About 1000 nm"], 1, "CD uses 780 nm, DVD 650 nm and Blu-ray 405 nm."),
    ("Consider the statements:\nI. SRAM needs to be refreshed periodically.\nII. DRAM is denser and cheaper per bit than SRAM.\nWhich is/are correct?",
     I_II, 1, "DRAM needs refreshing; SRAM does not. Statement II is correct."),
    ("Assertion (A): Hard disks are used as secondary storage rather than main memory.\nReason (R): Hard disks are volatile and lose data when power is switched off.",
     AR, 2, "A is true, but R is false: hard disks are non-volatile. They are secondary storage because they are much slower than RAM."),
    ("Access time of a hard disk is given by:",
     ["Seek time only", "Seek time + rotational latency + transfer time", "Rotational latency only", "Transfer time − seek time"], 1, "All three components add up."),
    ("Magnetic tapes are mainly used today for:",
     ["Main memory", "Long-term backup and archival storage", "Cache memory", "Booting computers"], 1, "Tape (e.g. LTO) is cheap per byte for archives."),
    ("Which of the following is volatile?",
     ["SSD", "DVD", "Cache memory", "Flash drive"], 2, "Cache is SRAM, which loses its data when power is removed."),
    ("A memory card used in cameras and phones (e.g. SD card) is based on:",
     ["Flash memory", "Magnetic disk", "Optical disc", "DRAM"], 0, "SD cards use NAND flash."),
]

SOFTWARE = [
    ("Software that manages computer hardware and provides services to other programs is:",
     ["Application software", "System software", "Utility only", "Freeware"], 1, "Operating systems, drivers and language processors are system software."),
    ("Which of the following is application software?",
     ["Windows 11", "A device driver", "MS Excel", "A compiler"], 2, "Excel performs a user task; the others are system software."),
    ("A compiler:",
     ["Translates and executes one statement at a time", "Translates the whole high-level program into object code before execution", "Converts assembly into machine code", "Loads programs into memory"], 1,
     "An interpreter works statement by statement; an assembler handles assembly language."),
    ("A linker:",
     ["Converts source code into object code", "Combines object modules and library routines into a single executable program", "Loads the program into memory", "Debugs the program"], 1,
     "The loader then places the executable into memory for execution."),
    ("A loader is a system program that:",
     ["Translates source code", "Places an executable program into main memory and prepares it for execution", "Compresses files", "Scans for viruses"], 1,
     "It may also perform relocation of addresses."),
    ("Software whose source code is available and may be studied, modified and redistributed is called:",
     ["Proprietary software", "Open-source software", "Shareware", "Freeware"], 1, "Examples include Linux, LibreOffice and Firefox."),
    ("Shareware is software that:",
     ["Is free forever with source code", "Can be tried free for a limited period, after which payment is expected", "Cannot be copied", "Is only for servers"], 1, "It is 'try before you buy'."),
    ("Freeware is software that:",
     ["Is always open source", "Can be used free of charge, but its source code is usually not available", "Must be paid for after 30 days", "Has no copyright"], 1,
     "Free of cost is not the same as free/open source."),
    ("The Linux kernel was first released in 1991 by:",
     ["Richard Stallman", "Linus Torvalds", "Dennis Ritchie", "Ken Thompson"], 1, "Torvalds released it while a student in Helsinki."),
    ("The GNU Project and the Free Software Foundation were started by:",
     ["Linus Torvalds", "Richard Stallman", "Bill Gates", "Steve Wozniak"], 1, "Stallman launched GNU in 1983 and the FSF in 1985."),
    ("The GNU General Public License (GPL) is known as a 'copyleft' licence because:",
     ["It forbids copying", "Modified versions that are distributed must also be released under the same free licence", "It is only for documents", "It allows closing the source"], 1,
     "Copyleft keeps derivative works free."),
    ("Antivirus programs, disk cleanup and file compression tools are examples of:",
     ["Utility software", "Application packages", "Language processors", "Firmware"], 0, "Utilities help maintain and optimise the system."),
    ("Software developed specifically for one organisation's needs is called:",
     ["Packaged (off-the-shelf) software", "Customised (tailor-made) software", "Freeware", "Firmware"], 1, "Packaged software like MS Office is sold to many users."),
    ("A 'patch' in software is:",
     ["A new operating system", "A small update that fixes bugs or security vulnerabilities", "A virus", "A hardware repair"], 1, "Patches are released after the main version."),
    ("A 'beta' version of software is:",
     ["The final release", "A pre-release version given to users for testing", "A pirated copy", "An obsolete version"], 1, "Beta testing collects feedback before the final release."),
    ("The term 'bug' became popular after a moth was found in the relay of the Harvard Mark II, recorded by the team of:",
     ["Grace Hopper", "Ada Lovelace", "Alan Turing", "John von Neumann"], 0, "The 1947 logbook entry reads 'First actual case of bug being found'."),
    ("Programs written by a programmer in a high-level language are called:",
     ["Object code", "Source code", "Machine code", "Executable code"], 1, "Source code is translated into object code and then linked into an executable."),
    ("Software permanently stored in hardware, such as a router's control program in flash memory, is called:",
     ["Shareware", "Firmware", "Middleware", "Malware"], 1, "Firmware bridges hardware and software."),
    ("Middleware is software that:",
     ["Runs only in the middle of the night", "Connects different applications or components, e.g. between an application and a database", "Is a type of virus", "Is the BIOS"], 1,
     "Database drivers and application servers are middleware."),
    ("Google Docs, used through a browser without installation, is an example of:",
     ["SaaS (Software as a Service)", "Firmware", "A device driver", "An assembler"], 0, "The software runs on the provider's servers."),
    ("An EULA is:",
     ["An end-user licence agreement specifying how the software may be used", "An error message", "A type of file", "A programming language"], 0,
     "Users accept it when installing proprietary software."),
    ("Unauthorised copying and distribution of copyrighted software is called:",
     ["Software piracy", "Shareware", "Open sourcing", "Patching"], 0, "It is illegal under copyright law."),
    ("In semantic versioning 'major.minor.patch', a change from 2.4.1 to 2.4.2 usually indicates:",
     ["A major incompatible change", "New features", "Backward-compatible bug fixes", "A new product"], 2, "Patch numbers increase for bug fixes."),
    ("Which language processor translates a high-level program line by line, executing each line immediately?",
     ["Compiler", "Interpreter", "Assembler", "Linker"], 1, "Python and BASIC are traditionally interpreted."),
    ("Consider the statements:\nI. All freeware is open-source software.\nII. Open-source software may be sold commercially.\nWhich is/are correct?",
     I_II, 1, "Freeware is often closed source; open-source licences such as the GPL allow selling copies."),
    ("Assertion (A): A program compiled for Windows usually cannot run directly on Linux.\nReason (R): The executable depends on the operating system's executable format and system calls.",
     AR, 0, "Executables are tied to their OS (PE format on Windows, ELF on Linux)."),
    ("A device driver is needed to:",
     ["Design documents", "Let the operating system communicate with and control a specific hardware device", "Compile programs", "Compress files"], 1,
     "Each printer, graphics card or network card needs a suitable driver."),
    ("Which of the following is an example of open-source software?",
     ["Microsoft Office", "LibreOffice", "Adobe Photoshop", "WinRAR"], 1, "LibreOffice is free and open source."),
    ("Software that is not protected by copyright and can be used by anyone for any purpose is called:",
     ["Shareware", "Public-domain software", "Proprietary software", "Trial software"], 1, "Public-domain software has no owner."),
    ("The main difference between system software and application software is that system software:",
     ["Is used only by children", "Runs and manages the computer system, while application software performs tasks for the user", "Is always free", "Cannot be updated"], 1,
     "Applications depend on system software to run."),
]

PROBLEM_SOLVING = [
    ("The correct order of steps in problem solving with a computer is:",
     ["Problem analysis → algorithm/flowchart → coding → testing and debugging → documentation", "Coding → analysis → testing → algorithm",
      "Testing → coding → analysis → documentation", "Algorithm → testing → analysis → coding"], 0, "The program development cycle starts with understanding the problem."),
    ("In a flowchart, the oval (terminal) symbol represents:",
     ["A decision", "The start or end of the flowchart", "Input/output", "Processing"], 1, "Every flowchart begins and ends with a terminal symbol."),
    ("The parallelogram symbol in a flowchart is used for:",
     ["Input or output", "Decisions", "Processing", "Connectors"], 0, "Reading data or printing results uses the parallelogram."),
    ("Which flowchart symbol has one entry and two or more exits?",
     ["Rectangle", "Decision (diamond)", "Parallelogram", "Oval"], 1, "The exits correspond to outcomes such as Yes/No."),
    ("The flowchart symbol for a predefined process (a sub-routine) is:",
     ["A rectangle with double vertical sides", "A diamond", "A circle", "A wavy-bottomed rectangle"], 0, "It refers to a process defined elsewhere."),
    ("An off-page connector in a flowchart is drawn as a:",
     ["Small circle", "Pentagon (home-plate shape)", "Diamond", "Triangle"], 1, "A small circle is an on-page connector."),
    ("According to the Böhm–Jacopini theorem, any algorithm can be expressed using only:",
     ["Sequence, selection and iteration", "GOTO statements", "Recursion only", "Sequence only"], 0, "This is the basis of structured programming."),
    ("An error such as a missing semicolon, detected during compilation, is a:",
     ["Logical error", "Syntax error", "Runtime error", "Hardware error"], 1, "Syntax errors violate the language's grammar rules."),
    ("Dividing by zero while a program is running produces a:",
     ["Syntax error", "Runtime error", "Logical error", "Compilation error"], 1, "Runtime errors occur during execution."),
    ("A program runs without crashing but calculates the average wrongly because it divides by n + 1. This is a:",
     ["Syntax error", "Runtime error", "Logical error", "Linker error"], 2, "Logical errors give wrong results without error messages."),
    ("What is printed?\nf ← 1; n ← 5\nwhile n > 1: f ← f × n; n ← n − 1\nprint f",
     ["24", "120", "60", "5"], 1, "The loop computes 5 × 4 × 3 × 2 = 120 (5 factorial)."),
    ("How many times does the loop 'for i ← 1 to 10 step 3' execute?",
     ["3", "4", "10", "5"], 1, "i takes the values 1, 4, 7 and 10."),
    ("How many times is the inner statement executed?\nfor i ← 1 to 3\n  for j ← 1 to i\n    print i, j",
     ["3", "6", "9", "12"], 1, "The inner loop runs 1 + 2 + 3 = 6 times."),
    ("What is printed?\nn ← 4567; c ← 0\nwhile n > 0: n ← n div 10; c ← c + 1\nprint c",
     ["4", "22", "7", "4567"], 0, "Each division removes one digit, so the loop counts the digits: 4."),
    ("What is printed?\nn ← 123; r ← 0\nwhile n > 0: r ← r × 10 + (n mod 10); n ← n div 10\nprint r",
     ["123", "321", "6", "0"], 1, "The algorithm reverses the digits of the number."),
    ("Using Euclid's algorithm, gcd(48, 18) is:",
     ["2", "6", "9", "18"], 1, "48 mod 18 = 12; 18 mod 12 = 6; 12 mod 6 = 0, so the gcd is 6."),
    ("Which algorithm swaps a and b without a temporary variable?",
     ["a ← a + b; b ← a − b; a ← a − b", "a ← b; b ← a", "a ← a × b; b ← a × b", "b ← a − b; a ← a + b"], 0,
     "With a = 3 and b = 5: a = 8, b = 3, a = 5. (Beware of overflow with very large numbers.)"),
    ("What is the minimum number of comparisons needed to find the largest of three distinct numbers?",
     ["1", "2", "3", "4"], 1, "Compare two, then compare the winner with the third."),
    ("In the worst case, linear search on a list of n elements needs:",
     ["1 comparison", "log2 n comparisons", "n comparisons", "n² comparisons"], 2, "The key may be the last element or absent."),
    ("Pseudocode is written using:",
     ["Strict syntax of a particular language", "Structured English-like statements that describe the logic", "Only flowchart symbols", "Binary digits"], 1,
     "It is independent of any programming language."),
    ("A decision table is used to:",
     ["Store data", "Represent complex combinations of conditions and the corresponding actions", "Draw flowcharts", "Compile code"], 1,
     "It lists conditions, condition entries and actions in tabular form."),
    ("Edsger Dijkstra's 1968 letter 'Go To Statement Considered Harmful' promoted:",
     ["Object-oriented programming", "Structured programming", "Assembly programming", "Machine learning"], 1, "It argued that unrestricted GOTOs make programs hard to understand."),
    ("Dividing a large program into independent, smaller sub-programs is called:",
     ["Modular programming", "Machine coding", "Debugging", "Compiling"], 0, "Modules can be written, tested and maintained separately."),
    ("Documentation of a program is important because it:",
     ["Makes the program run faster", "Helps others understand, use and maintain the program", "Removes all bugs", "Reduces memory use"], 1,
     "Good documentation is essential for maintenance."),
    ("What is printed?\na ← 1; b ← 1\nrepeat 5 times: c ← a + b; a ← b; b ← c\nprint b",
     ["8", "13", "21", "5"], 1, "The values of b are 2, 3, 5, 8 and 13 (Fibonacci numbers)."),
    ("What is printed?\ns ← 0\nfor i ← 1 to 10: if i mod 3 = 0 then s ← s + i\nprint s",
     ["18", "30", "12", "55"], 0, "3 + 6 + 9 = 18."),
    ("Consider the statements:\nI. A flowchart can be drawn before writing the program.\nII. Every algorithm must terminate after a finite number of steps.\nWhich is/are correct?",
     I_II, 2, "Flowcharts are planning tools, and finiteness is an essential property of algorithms."),
    ("Assertion (A): Logical errors are always detected and reported by the compiler.\nReason (R): Syntax errors are detected during compilation.",
     AR, 3, "A is false: logical errors produce wrong results without error messages. R is true."),
    ("To check whether n is prime, trial division needs to test divisors only up to:",
     ["n − 1", "n / 2", "√n", "n²"], 2, "If n = a × b, one factor must be at most √n."),
    ("Maintenance, the last phase of program development, involves:",
     ["Designing the algorithm", "Modifying the program after delivery to fix errors or meet new requirements", "Writing the first version", "Installing hardware"], 1,
     "Maintenance often consumes the largest share of software cost."),
]

TOPICS = {
    "Input, Output and Memory Devices": [("1 · Input Devices", INPUT), ("2 · Output Devices", OUTPUT), ("3 · Memory Devices", MEMORY_DEVICES)],
    "Software Concepts & Problem Solving Methodology": [("1 · Software Concepts", SOFTWARE), ("2 · Problem Solving Methodology", PROBLEM_SOLVING)],
}
