"""Paper 2 · Unit 1 · topic U1-05 (3 sub-topics × 30). Microsoft Office conventions (Office 2016/2019/365)."""
from packlib import AR, I_II

WORD = [
    ("In MS Word, Ctrl+E is used to:",
     ["Select everything", "Centre-align the paragraph", "Open the Find dialog", "Insert an equation"], 1, "Ctrl+L left, Ctrl+E centre, Ctrl+R right, Ctrl+J justify."),
    ("Which shortcut opens the Replace dialog in MS Word?",
     ["Ctrl+F", "Ctrl+H", "Ctrl+R", "Ctrl+G"], 1, "Ctrl+F finds, Ctrl+H replaces, Ctrl+G goes to a page, Ctrl+R right-aligns."),
    ("Pressing F7 in MS Word:",
     ["Saves the document", "Starts the spelling and grammar check (Editor)", "Opens the thesaurus", "Prints the document"], 1, "Shift+F7 opens the thesaurus."),
    ("Shift+F3 in MS Word is used to:",
     ["Change the case of selected text (e.g. UPPER, lower, Title)", "Open help", "Insert a table", "Insert a comment"], 0,
     "It cycles through lowercase, UPPERCASE and Capitalise Each Word."),
    ("Which key opens the 'Save As' dialog in MS Word?",
     ["F2", "F7", "F12", "F5"], 2, "F12 = Save As; Ctrl+S = Save."),
    ("Ctrl+Enter in MS Word inserts a:",
     ["Line break", "Page break", "Section break", "Column break"], 1, "Shift+Enter inserts a line break; Ctrl+Shift+Enter a column break."),
    ("Ctrl+] in MS Word:",
     ["Increases the font size by 1 point", "Decreases the font size by 1 point", "Right-aligns text", "Inserts a bracket"], 0, "Ctrl+[ decreases the size by 1 point."),
    ("The default file extension of a document saved in MS Word 2007 and later is:",
     [".doc", ".docx", ".dotx", ".rtf"], 1, ".dotx is a template and .docm a macro-enabled document."),
    ("A Word document that contains macros must be saved with the extension:",
     [".docx", ".docm", ".dotx", ".txt"], 1, ".docx cannot store macros for security reasons."),
    ("Mail Merge options in MS Word are found on the:",
     ["Review tab", "Mailings tab", "References tab", "Design tab"], 1, "The Mailings tab contains Start Mail Merge, Select Recipients and Finish & Merge."),
    ("Track Changes in MS Word is found on the:",
     ["Home tab", "Review tab", "Insert tab", "View tab"], 1, "The Review tab also contains comments and document comparison."),
    ("An automatic Table of Contents in MS Word is generated from:",
     ["Bold text", "Text formatted with heading styles (Heading 1, Heading 2…)", "Footnotes", "Comments"], 1, "The TOC command is on the References tab."),
    ("Footnotes appear ______, whereas endnotes appear ______.",
     ["At the end of the document; at the bottom of the page", "At the bottom of the page; at the end of the document or section",
      "In the header; in the footer", "In the margin; in a comment"], 1, "Both are inserted from the References tab."),
    ("Which type of section break starts the new section on the same page?",
     ["Next page", "Continuous", "Even page", "Odd page"], 1, "Continuous breaks are used, for example, to change the number of columns mid-page."),
    ("A gutter margin in Word is:",
     ["Extra margin space added for binding", "The space between columns", "The header area", "The line spacing"], 0, "It keeps text from being hidden by the binding."),
    ("'Widow/Orphan control' in MS Word prevents:",
     ["Spelling errors", "A single line of a paragraph from being left alone at the top or bottom of a page", "Blank pages", "Text overflow in tables"], 1,
     "It keeps at least two lines of a paragraph together across page breaks."),
    ("A large capital letter at the beginning of a paragraph, spanning several lines, is called a:",
     ["WordArt", "Drop cap", "Watermark", "SmartArt"], 1, "Insert → Drop Cap."),
    ("The Format Painter tool is used to:",
     ["Paint pictures", "Copy formatting from one piece of text and apply it to another", "Change the page colour", "Insert shapes"], 1,
     "Double-clicking it keeps it active for multiple applications."),
    ("Ctrl+2 applied to a paragraph in MS Word sets:",
     ["Single line spacing", "Double line spacing", "1.5 line spacing", "Two columns"], 1, "Ctrl+1 single, Ctrl+5 1.5 lines, Ctrl+2 double."),
    ("In MS Word, Ctrl+= and Ctrl+Shift+= are used for:",
     ["Subscript and superscript respectively", "Superscript and subscript respectively", "Insert equation", "Zoom in and out"], 0,
     "H2O uses subscript (Ctrl+=); x² uses superscript (Ctrl+Shift+=)."),
    ("A paragraph whose first line starts at the left margin while the remaining lines are indented has a:",
     ["First-line indent", "Hanging indent", "Right indent", "Centre alignment"], 1, "Hanging indents are common in bibliographies."),
    ("A faint text or picture such as 'CONFIDENTIAL' behind the document text is called a:",
     ["Drop cap", "Watermark", "Header", "Footnote"], 1, "Watermarks are added from the Design tab."),
    ("Which feature automatically corrects common typing mistakes, such as 'teh' to 'the', as you type?",
     ["AutoCorrect", "AutoText", "Thesaurus", "Track Changes"], 0, "AutoCorrect replaces entries from its list automatically."),
    ("Ctrl+K in MS Word is used to:",
     ["Insert a hyperlink", "Keep lines together", "Check spelling", "Insert a comment"], 0, "It opens the Insert Hyperlink dialog."),
    ("Page orientation (portrait or landscape) is set on the:",
     ["Home tab", "Layout tab", "Review tab", "Mailings tab"], 1, "Layout also contains margins, size, columns and breaks."),
    ("Consider the statements:\nI. In MS Word, footnotes appear at the end of the whole document.\nII. A Word document can have only one page orientation.\nWhich is/are correct?",
     I_II, 3, "Both are false: footnotes appear at the bottom of the page (endnotes at the end), and section breaks allow mixed orientations."),
    ("Assertion (A): Using heading styles helps create an automatic table of contents.\nReason (R): Word builds the table of contents from paragraphs that have heading styles applied.",
     AR, 0, "The TOC is generated from heading levels."),
    ("Ctrl+Z and Ctrl+Y in MS Word perform:",
     ["Undo and Redo/Repeat", "Redo and Undo", "Zoom and Yank", "Cut and Paste"], 0, "Ctrl+Z undoes the last action; Ctrl+Y redoes or repeats it."),
    ("Which view in MS Word shows the document as it will look when printed, including headers and margins?",
     ["Draft view", "Print Layout view", "Outline view", "Web Layout view"], 1, "Print Layout is the default editing view."),
    ("Ctrl+Home in MS Word moves the cursor to:",
     ["The beginning of the line", "The beginning of the document", "The end of the document", "The top of the page"], 1, "Ctrl+End moves to the end of the document."),
]

EXCEL = [
    ("In MS Excel 2007 and later, a worksheet has:",
     ["65,536 rows and 256 columns", "1,048,576 rows and 16,384 columns", "1,000,000 rows and 10,000 columns", "Unlimited rows and columns"], 1,
     "The last cell is XFD1048576; 65,536 × 256 was the limit in Excel 2003."),
    ("What is the result of the Excel formula =2+3*2^2?",
     ["14", "22", "100", "11"], 0, "Exponentiation first (2^2 = 4), then multiplication (3 × 4 = 12), then addition: 14."),
    ("In MS Excel, what does =-2^2 return?",
     ["-4", "4", "#VALUE!", "0"], 1, "In Excel the negation operator is applied before exponentiation, so it computes (-2)^2 = 4."),
    ("Which error does =10/0 produce in Excel?",
     ["#VALUE!", "#DIV/0!", "#NUM!", "#NULL!"], 1, "Division by zero or by an empty cell gives #DIV/0!."),
    ("A misspelt function name such as =SUMM(A1:A5) produces:",
     ["#NAME?", "#REF!", "#N/A", "#VALUE!"], 0, "Excel does not recognise the name."),
    ("VLOOKUP returns #N/A when:",
     ["The lookup value is not found (with exact match)", "The column is too narrow", "A cell reference is deleted", "A number is too large"], 0, "#N/A means 'value not available'."),
    ("A cell showing '#####' in Excel usually means:",
     ["A formula error", "The column is too narrow to display the value (or a negative date/time)", "The file is corrupted", "Division by zero"], 1,
     "Widening the column shows the value."),
    ("Which key toggles a cell reference between relative, absolute and mixed forms while editing a formula?",
     ["F2", "F4", "F9", "F11"], 1, "F4 cycles A1 → $A$1 → A$1 → $A1."),
    ("The formula =A1+B1 in cell C1 is copied to cell D2. It becomes:",
     ["=A1+B1", "=B2+C2", "=A2+B2", "=B1+C1"], 1, "Moving one column right and one row down shifts both relative references by the same amount."),
    ("How many cells are in the range A1:C4?",
     ["7", "12", "10", "4"], 1, "3 columns × 4 rows = 12 cells."),
    ("What does =ROUND(3.14159, 2) return?",
     ["3.14", "3.1", "3.142", "3"], 0, "It rounds to 2 decimal places."),
    ("What does =INT(-3.7) return in Excel?",
     ["-3", "-4", "3", "-3.7"], 1, "INT rounds down to the nearest integer; TRUNC(-3.7) would give -3."),
    ("What does =MOD(17, 5) return?",
     ["3", "2", "5", "12"], 1, "17 = 3 × 5 + 2, so the remainder is 2."),
    ("What does =LEN(\"Karnataka\") return?",
     ["8", "9", "10", "7"], 1, "The word has 9 characters."),
    ("What does =LEFT(\"Bengaluru\", 4) return?",
     ["Beng", "luru", "Bengal", "B"], 0, "LEFT returns the first 4 characters."),
    ("Which function counts the cells in A1:A20 whose value is greater than 50?",
     ["=COUNT(A1:A20>50)", "=COUNTIF(A1:A20,\">50\")", "=SUMIF(A1:A20,\">50\")", "=IF(A1:A20>50)"], 1, "COUNTIF(range, criteria) counts cells meeting a condition."),
    ("In =VLOOKUP(101, A2:D50, 3, FALSE), the value 3 indicates:",
     ["The row number to return", "The column of the table range from which the result is returned", "The number of matches", "An approximate match"], 1,
     "VLOOKUP searches the first column and returns the value from the 3rd column of the range; FALSE means exact match."),
    ("HLOOKUP differs from VLOOKUP in that it:",
     ["Searches the first row of the table instead of the first column", "Works only with text", "Returns multiple values", "Searches from the bottom"], 0,
     "'H' stands for horizontal."),
    ("The shortcut Alt+= in Excel inserts:",
     ["A new sheet", "AutoSum (=SUM with a suggested range)", "An equation", "The current date"], 1, "Ctrl+; inserts the current date."),
    ("To keep the header row visible while scrolling through a long worksheet, you use:",
     ["Merge & Center", "Freeze Panes", "Wrap Text", "Filter"], 1, "Freeze Panes is on the View tab."),
    ("Goal Seek in Excel is part of:",
     ["Conditional Formatting", "What-If Analysis", "Pivot Tables", "Data Validation"], 1, "It finds the input value needed to reach a desired result."),
    ("Which chart type is most suitable for showing the share of each item in a whole (e.g. budget distribution)?",
     ["Line chart", "Pie chart", "Scatter chart", "Stock chart"], 1, "Pie charts show parts of a whole for a single data series."),
    ("Which chart type is best for showing a trend over time, such as monthly sales over a year?",
     ["Pie chart", "Line chart", "Doughnut chart", "Radar chart"], 1, "Line charts connect values in time order."),
    ("By default, Excel aligns numbers ______ and text ______ in a cell.",
     ["left; right", "right; left", "centre; left", "left; centre"], 1, "Numbers are right-aligned; text is left-aligned."),
    ("A1:A5 contain 10, 20, (blank), \"abc\" and 30. What is =AVERAGE(A1:A5)?",
     ["12", "15", "20", "#VALUE!"], 2, "AVERAGE ignores blanks and text in a range: (10 + 20 + 30) / 3 = 20."),
    ("Which feature restricts the values a user can type into a cell, e.g. only whole numbers between 1 and 100?",
     ["Conditional Formatting", "Data Validation", "Freeze Panes", "Goal Seek"], 1, "Data Validation is on the Data tab."),
    ("The formula =Sheet2!B5 refers to:",
     ["Cell B5 in the current sheet", "Cell B5 in the worksheet named Sheet2", "Column B of all sheets", "An external workbook"], 1, "The exclamation mark separates the sheet name from the cell address."),
    ("Consider the statements:\nI. =SUM(A1:A3) and =A1+A2+A3 give the same result when all three cells contain numbers.\nII. =SUM ignores text in a range, while =A1+A2+A3 returns #VALUE! if one cell contains text.\nWhich is/are correct?",
     I_II, 2, "Both statements are true; this is why SUM is safer for ranges."),
    ("Assertion (A): A formula using $B$1 keeps referring to B1 when copied anywhere.\nReason (R): The dollar sign makes a cell reference relative.",
     AR, 2, "A is true, but R is false: the dollar sign makes the column/row absolute."),
    ("A PivotTable in Excel is used to:",
     ["Draw pictures", "Summarise, group and analyse large data sets interactively", "Protect a sheet", "Check spelling"], 1, "PivotTables are inserted from the Insert tab."),
]

POWERPOINT = [
    ("Which key starts a PowerPoint slide show from the first slide?",
     ["F5", "Shift+F5", "F7", "Ctrl+F5"], 0, "Shift+F5 starts from the current slide."),
    ("During a slide show, pressing 'B' will:",
     ["Go back one slide", "Turn the screen black (press again to resume)", "Bold the text", "Show the next slide"], 1, "Pressing W turns the screen white."),
    ("Which shortcut inserts a new slide in PowerPoint?",
     ["Ctrl+N", "Ctrl+M", "Ctrl+S", "Ctrl+D"], 1, "Ctrl+N creates a new presentation; Ctrl+D duplicates a slide or object."),
    ("The difference between a transition and an animation is that:",
     ["They are the same", "A transition is an effect between slides, while an animation is an effect on objects within a slide", "Transitions apply to text only",
      "Animations apply to the whole presentation only"], 1, "Transitions are on the Transitions tab; animations on the Animations tab."),
    ("In PowerPoint, the four categories of animation effects are:",
     ["Entrance, Emphasis, Exit and Motion Paths", "Start, Middle, End and Loop", "Fade, Wipe, Zoom and Spin only", "Slide, Page, Section and Show"], 0,
     "Entrance effects are shown in green, emphasis in yellow and exit in red icons."),
    ("To control the order and timing of all animations on a slide, you use the:",
     ["Slide Sorter", "Animation Pane", "Notes Pane", "Selection Pane only"], 1, "The Animation Pane lists every effect on the slide."),
    ("'Rehearse Timings' in PowerPoint is used to:",
     ["Check spelling", "Record how long each slide is shown, for automatic advancing", "Record voice only", "Print handouts"], 1, "It is on the Slide Show tab."),
    ("A PowerPoint file saved with the .ppsx extension:",
     ["Opens directly in Slide Show mode", "Is a template", "Contains macros", "Is an image"], 0, ".pptx opens for editing, .potx is a template and .pptm is macro-enabled."),
    ("Changes made in the Slide Master affect:",
     ["Only the current slide", "All slides that use its layouts", "Only the notes", "Only the handouts"], 1, "View → Slide Master."),
    ("Which view is best for rearranging the order of slides?",
     ["Notes Page view", "Slide Sorter view", "Reading view", "Outline view"], 1, "Thumbnails of all slides are shown and can be dragged."),
    ("Speaker notes in PowerPoint are:",
     ["Shown to the audience on the slide", "Notes for the presenter, visible in Presenter View and on notes pages", "Automatically read aloud", "Comments by reviewers"], 1,
     "Presenter View shows notes on the presenter's screen only."),
    ("Handouts in PowerPoint are:",
     ["Printed pages containing several slides per page for the audience", "Animation effects", "Slide transitions", "Hidden slides"], 0,
     "Handouts can have 1, 2, 3, 4, 6 or 9 slides per page."),
    ("To skip a slide during a presentation without deleting it, you:",
     ["Hide the slide", "Delete the slide", "Change its layout", "Add a transition"], 0, "Hidden slides are not shown in the slide show but remain in the file."),
    ("An action button in PowerPoint is used to:",
     ["Change the theme", "Perform an action such as jumping to another slide or running a program when clicked", "Record audio", "Print slides"], 1,
     "Action buttons create interactive presentations."),
    ("The default slide size in recent PowerPoint versions is:",
     ["4:3", "16:9 (widescreen)", "A4", "1:1"], 1, "Widescreen 16:9 has been the default since PowerPoint 2013."),
    ("Which PowerPoint option makes a presentation run continuously at a kiosk until Esc is pressed?",
     ["Rehearse Timings only", "Set Up Slide Show → 'Browsed at a kiosk (full screen)' / loop continuously", "Hide Slide", "Slide Sorter"], 1,
     "Kiosk mode loops the show automatically."),
    ("During a slide show, typing a slide number and pressing Enter:",
     ["Deletes that slide", "Jumps directly to that slide", "Hides that slide", "Prints that slide"], 1, "This is a quick way to navigate."),
    ("Which PowerPoint feature groups related slides, e.g. 'Introduction', 'Results', to organise a large presentation?",
     ["Sections", "Masters", "Handouts", "Transitions"], 0, "Sections appear in the slide thumbnail pane."),
    ("Ctrl+G in PowerPoint:",
     ["Groups the selected objects", "Opens Go To", "Inserts a graph", "Starts the slide show"], 0, "Ctrl+Shift+G ungroups them."),
    ("A presentation can be exported from PowerPoint as:",
     ["A PDF or an MP4 video", "Only a .pptx file", "Only printed pages", "Only images"], 0, "File → Export offers PDF and video options."),
    ("SmartArt in PowerPoint is used to:",
     ["Insert diagrams such as processes, cycles and hierarchies", "Check spelling", "Record narration", "Add transitions"], 0, "SmartArt converts bullet text into diagrams."),
    ("In PowerPoint, which view shows the slide in a window with simple controls, useful for reviewing without full-screen mode?",
     ["Reading view", "Slide Master view", "Outline view", "Normal view"], 0, "Reading View is on the View tab and the status bar."),
    ("The Morph transition in modern PowerPoint:",
     ["Animates smooth movement of matching objects from one slide to the next", "Deletes duplicate slides", "Converts text to SmartArt", "Records the screen"], 0,
     "It creates movement effects between similar slides."),
    ("Esc during a slide show:",
     ["Pauses the show", "Ends the slide show", "Goes to the first slide", "Hides the pointer"], 1, "It returns to the editing view."),
    ("A custom slide show lets you:",
     ["Present a selected subset of slides in a chosen order from the same file", "Change all fonts", "Print notes", "Create a template"], 0,
     "Useful when presenting to different audiences."),
    ("Consider the statements:\nI. Transitions are applied between slides.\nII. Animations can be applied to individual text boxes and images.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Changing the font in the Slide Master changes it on all slides using that master.\nReason (R): PowerPoint presentations are saved with the .pptx extension by default.",
     AR, 1, "Both are true, but R is unrelated; the real reason is that slide layouts inherit formatting from the Slide Master."),
    ("Which tab contains the Rehearse Timings, Custom Slide Show and Set Up Slide Show commands?",
     ["Design", "Slide Show", "Review", "Insert"], 1, "They are all on the Slide Show tab."),
    ("Ctrl+D applied to a selected slide thumbnail in PowerPoint:",
     ["Deletes it", "Duplicates it", "Hides it", "Designs it"], 1, "It creates a copy immediately after the original."),
    ("A template file in PowerPoint has the extension:",
     [".pptx", ".potx", ".ppsx", ".pdf"], 1, "Templates store themes, layouts and sample content."),
]

TOPICS = {"Word Processing, Spreadsheets, PowerPoint": [("1 · Word Processing", WORD), ("2 · Spreadsheets", EXCEL), ("3 · PowerPoint Presentation", POWERPOINT)]}
