"""Paper 2 · Unit 2 · topics U2-04 Counting and U2-05 Induction & Probability (7 sub-topics × 30)."""
from packlib import AR, I_II

COUNT_BASICS = [
    ("A student can choose a project from 37 in computer science or 83 in mathematics (no overlap). How many choices are there?",
     ["37", "83", "120", "3071"], 2, "Sum rule: 37 + 83 = 120."),
    ("A licence plate has 3 letters followed by 3 digits. How many plates are possible?",
     ["26³ + 10³", "26³ × 10³ = 17,576,000", "36⁶", "26 × 10"], 1, "Product rule: 26 × 26 × 26 × 10 × 10 × 10."),
    ("How many bit strings of length 7 are there?",
     ["7", "14", "49", "128"], 3, "2^7 = 128."),
    ("How many functions are there from a 3-element set to a 5-element set?",
     ["15", "60", "125", "243"], 2, "Each of the 3 elements has 5 choices: 5³ = 125."),
    ("How many one-to-one functions are there from a 3-element set to a 5-element set?",
     ["60", "125", "10", "15"], 0, "5 × 4 × 3 = 60."),
    ("How many bit strings of length 8 either start with 1 or end with 00?",
     ["128", "160", "192", "96"], 1, "Start with 1: 2^7 = 128; end with 00: 2^6 = 64; both: 2^5 = 32. 128 + 64 − 32 = 160."),
    ("How many 4-digit PINs (0000 to 9999) have all digits distinct?",
     ["10,000", "5040", "3024", "210"], 1, "10 × 9 × 8 × 7 = 5040."),
    ("How many positive integers not exceeding 1000 are divisible by 7?",
     ["140", "142", "143", "7"], 1, "⌊1000/7⌋ = 142."),
    ("How many positive integers not exceeding 1000 are divisible by both 7 and 11?",
     ["11", "12", "13", "77"], 1, "Divisible by 77: ⌊1000/77⌋ = 12."),
    ("How many positive integers not exceeding 1000 are divisible by 7 or 11?",
     ["232", "220", "208", "90"], 1, "142 + 90 − 12 = 220 (⌊1000/11⌋ = 90)."),
    ("How many 3-digit numbers (100–999) have all odd digits?",
     ["125", "100", "500", "729"], 0, "5 choices (1, 3, 5, 7, 9) for each digit: 5³ = 125."),
    ("In how many ways can a president and a vice-president be chosen from 10 people?",
     ["45", "90", "100", "20"], 1, "10 × 9 = 90 (order matters)."),
    ("In how many ways can 4 people be seated around a circular table (rotations considered the same)?",
     ["24", "6", "12", "4"], 1, "Division rule: 4!/4 = 3! = 6."),
    ("How many paths are there from (0, 0) to (3, 2) moving one unit right or up at each step?",
     ["5", "6", "10", "20"], 2, "Choose which 2 of the 5 steps are up: C(5, 2) = 10."),
    ("How many even 3-digit numbers have all distinct digits?",
     ["328", "360", "405", "450"], 0, "Ending in 0: 9 × 8 = 72. Ending in 2, 4, 6 or 8: 8 × 8 × 4 = 256. Total 328."),
    ("How many 5-letter strings can be formed from the 26 English letters if repetition is allowed?",
     ["26 × 5", "26^5 = 11,881,376", "5^26", "C(26, 5)"], 1, "Each position has 26 choices."),
    ("How many outcomes are there when two distinguishable dice are rolled?",
     ["12", "21", "36", "11"], 2, "6 × 6 = 36."),
    ("How many integers from 1 to 100 are divisible by neither 2 nor 3?",
     ["33", "34", "50", "67"], 0, "Divisible by 2 or 3: 50 + 33 − 16 = 67; so 100 − 67 = 33."),
    ("How many bit strings of length 10 contain exactly three 1s?",
     ["30", "120", "720", "1024"], 1, "C(10, 3) = 120."),
    ("In a programming language, a variable name is a letter, or a letter followed by a digit. How many names are possible?",
     ["26", "260", "286", "36"], 2, "26 + 26 × 10 = 286 (sum rule plus product rule)."),
    ("How many different 3-character codes can be formed with a letter followed by two digits?",
     ["2600", "260", "36³ = 46,656", "1000"], 0, "26 × 10 × 10 = 2600."),
    ("How many subsets does a set with 10 elements have?",
     ["100", "1024", "20", "512"], 1, "2^10 = 1024 by the product rule."),
    ("A menu has 3 starters, 4 main courses and 2 desserts. How many 3-course meals (one of each) are possible?",
     ["9", "24", "12", "18"], 1, "3 × 4 × 2 = 24."),
    ("How many bit strings of length 6 do NOT contain two consecutive 1s?",
     ["13", "21", "34", "32"], 1, "The count follows the Fibonacci numbers: length n gives F(n+2); for n = 6 this is 21."),
    ("How many ways can 5 different books be arranged on a shelf?",
     ["25", "60", "120", "3125"], 2, "5! = 120."),
    ("A password has 6 characters, each an uppercase letter or a digit. How many passwords contain at least one digit?",
     ["36^6 − 26^6", "36^6", "26^6", "10^6"], 0, "Subtract the passwords with no digits (all letters) from the total."),
    ("The 'division rule' in counting says that if a task can be done in n ways and every way corresponds to exactly d ways that are considered the same, the number of distinct ways is:",
     ["n × d", "n + d", "n / d", "n − d"], 2, "Example: circular seating divides by the number of rotations."),
    ("How many 2-digit numbers (10–99) have digits whose sum is 5?",
     ["4", "5", "6", "10"], 1, "14, 23, 32, 41, 50."),
    ("Consider the statements:\nI. The sum rule applies when a task can be done in one of several mutually exclusive ways.\nII. The product rule applies when a procedure consists of a sequence of independent tasks.\nWhich is/are correct?",
     I_II, 2, "Both describe the two basic counting principles."),
    ("Assertion (A): An n-element set has 2^n subsets.\nReason (R): For each element we independently choose whether it is in the subset or not.",
     AR, 0, "Applying the product rule to n binary choices gives 2^n."),
]

PIGEONHOLE = [
    ("In any group of 13 people, at least two were born in the same month because:",
     ["Of the birthday paradox", "Of the pigeonhole principle: 13 people, 12 months", "Of inclusion–exclusion", "Of induction"], 1, "13 > 12."),
    ("Among 100 people, at least how many were born in the same month?",
     ["8", "9", "10", "12"], 1, "Generalised pigeonhole: ⌈100/12⌉ = 9."),
    ("What is the minimum number of students needed to guarantee that at least 6 receive the same grade, if there are 5 possible grades?",
     ["25", "26", "30", "31"], 1, "5 × 5 + 1 = 26."),
    ("A drawer has socks of 2 colours. What is the minimum number of socks you must take out (in the dark) to guarantee a matching pair?",
     ["2", "3", "4", "5"], 1, "With 3 socks and 2 colours, two must match."),
    ("Among any 5 integers, at least two have the same remainder when divided by:",
     ["5", "4", "6", "10"], 1, "There are 4 possible remainders modulo 4."),
    ("What is the minimum number of people needed to guarantee that at least 3 share a birth month?",
     ["24", "25", "36", "37"], 1, "2 × 12 + 1 = 25."),
    ("If 6 numbers are chosen from {1, 2, …, 10}, then:",
     ["Two of them must sum to 11", "All must be even", "Two must be equal", "Their sum must be 30"], 0, "The pairs (1,10), (2,9), (3,8), (4,7), (5,6) are 5 boxes; 6 numbers must fill one pair."),
    ("A hash table has 100 slots and 101 keys are inserted. Then:",
     ["A collision may occur", "A collision must occur", "No collision can occur", "Exactly one slot is empty"], 1, "101 keys into 100 slots."),
    ("What is the minimum number of cards drawn from a standard deck to guarantee 3 cards of the same suit?",
     ["8", "9", "10", "12"], 1, "2 × 4 + 1 = 9."),
    ("What is the minimum number of cards drawn to guarantee at least 3 hearts?",
     ["9", "15", "42", "39"], 2, "In the worst case all 39 non-hearts come first, then 3 hearts: 42."),
    ("In any group of 6 people, there are either 3 mutual friends or 3 mutual strangers. This shows that the Ramsey number R(3, 3) is:",
     ["5", "6", "7", "9"], 1, "With 5 people it can fail, so R(3, 3) = 6."),
    ("By the Erdős–Szekeres theorem, every sequence of 10 distinct real numbers has an increasing or decreasing subsequence of length at least:",
     ["3", "4", "5", "10"], 1, "n² + 1 = 10 gives n = 3, so a monotone subsequence of length n + 1 = 4."),
    ("How many people are needed to guarantee that two have the same first initial (26 letters)?",
     ["26", "27", "52", "53"], 1, "26 + 1 = 27."),
    ("A drawer has 10 red and 10 blue socks. What is the minimum number to take out to guarantee 2 red socks?",
     ["3", "11", "12", "20"], 2, "Worst case: all 10 blue first, then 2 red: 12."),
    ("50 students are divided among 7 sections. At least one section has at least:",
     ["7 students", "8 students", "9 students", "6 students"], 1, "⌈50/7⌉ = 8."),
    ("21 objects are placed in 4 boxes. Some box contains at least:",
     ["5", "6", "7", "4"], 1, "⌈21/4⌉ = 6."),
    ("A function from a 6-element set to a 5-element set:",
     ["Can be one-to-one", "Cannot be one-to-one", "Must be onto", "Cannot be onto"], 1, "Two elements must map to the same image."),
    ("Among any 11 integers, at least two have a difference divisible by:",
     ["11", "10", "12", "2 only"], 1, "Only 10 remainders modulo 10 are possible."),
    ("How many students are needed to guarantee that at least 4 were born on the same day of the week?",
     ["21", "22", "28", "29"], 1, "3 × 7 + 1 = 22."),
    ("What is the maximum number of students in a class such that no 3 share a birth month is still possible?",
     ["12", "24", "25", "36"], 1, "Two per month: 24; the 25th forces three."),
    ("In any simple graph with at least 2 vertices, there are always two vertices with:",
     ["The same colour", "The same degree", "No edges", "Degree n"], 1, "Degrees range over 0…n−1, but 0 and n−1 cannot both occur, leaving n−1 values for n vertices."),
    ("A box has red, green and blue balls. What is the minimum number to draw to guarantee 4 balls of the same colour?",
     ["9", "10", "12", "13"], 1, "3 × 3 + 1 = 10."),
    ("Five points are placed in a square of side 2. Then two of them are at distance at most:",
     ["1", "√2", "2", "2√2"], 1, "Divide the square into four 1 × 1 squares; two points lie in the same one, whose diagonal is √2."),
    ("From {1, 2, …, 2n}, any n + 1 chosen numbers always include:",
     ["Two even numbers", "Two consecutive numbers", "Two numbers summing to 2n + 2", "The number 1"], 1, "The n pairs {1,2}, {3,4}, … act as pigeonholes."),
    ("There are 366 possible birthdays (including 29 February). How many people guarantee two with the same birthday?",
     ["365", "366", "367", "23"], 2, "366 + 1 = 367. (23 people give a probability above ½, which is a different question.)"),
    ("The generalised pigeonhole principle states that if N objects are placed into k boxes, some box contains at least:",
     ["⌊N/k⌋ objects", "⌈N/k⌉ objects", "N − k objects", "k objects"], 1, "The ceiling of N/k."),
    ("In a party of 40 people, each person shakes hands with some others. At least how many people have shaken hands the same number of times?",
     ["2", "3", "4", "40"], 0, "By the degree argument, at least two people must have the same number of handshakes."),
    ("What is the minimum number of integers to choose from {1, …, 100} to guarantee that two of them differ by exactly 50?",
     ["50", "51", "52", "100"], 1, "The pairs {1,51}, {2,52}, …, {50,100} form 50 boxes."),
    ("Consider the statements:\nI. If N objects are placed into k boxes and N > k, some box contains at least two objects.\nII. If N objects are placed into k boxes and N ≤ k, some box must be empty.\nWhich is/are correct?",
     I_II, 0, "When N = k, every box can contain exactly one object, so II is false."),
    ("Assertion (A): In any group of 12 people, at least two were born in the same month.\nReason (R): There are 12 months in a year.",
     AR, 3, "A is false: 12 people can have 12 different months. R is true; 13 people are needed."),
]

PERM_COMB = [
    ("What is P(5, 3), the number of ordered arrangements of 3 objects chosen from 5?",
     ["10", "15", "60", "125"], 2, "5 × 4 × 3 = 60."),
    ("What is C(10, 4)?",
     ["40", "210", "5040", "120"], 1, "10! / (4! 6!) = 210."),
    ("How many distinct arrangements of the letters of 'BANANA' are there?",
     ["720", "120", "60", "36"], 2, "6! / (3! 2!) = 720 / 12 = 60 (three A's, two N's)."),
    ("How many distinct arrangements of the letters of 'MISSISSIPPI' are there?",
     ["34,650", "39,916,800", "11,880", "6,930"], 0, "11! / (4! 4! 2!) = 34,650."),
    ("In how many ways can 6 people be seated around a round table?",
     ["720", "120", "60", "36"], 1, "(6 − 1)! = 120."),
    ("How many distinct necklaces can be made from 6 different beads, if both rotations and reflections are considered the same?",
     ["720", "120", "60", "30"], 2, "(6 − 1)! / 2 = 60."),
    ("A committee of 3 is chosen from 5 men and 4 women. How many committees have exactly 2 women?",
     ["30", "40", "60", "84"], 0, "C(4, 2) × C(5, 1) = 6 × 5 = 30."),
    ("A committee of 3 is chosen from 5 men and 4 women. How many include at least one woman?",
     ["74", "84", "64", "10"], 0, "Total C(9, 3) = 84 minus all-men C(5, 3) = 10 gives 74."),
    ("In how many ways can 4 doughnuts be chosen from 3 varieties (repetition allowed, order irrelevant)?",
     ["12", "15", "20", "81"], 1, "Combinations with repetition: C(3 + 4 − 1, 4) = C(6, 4) = 15."),
    ("How many non-negative integer solutions does x₁ + x₂ + x₃ = 10 have?",
     ["45", "55", "66", "78"], 2, "C(10 + 3 − 1, 3 − 1) = C(12, 2) = 66."),
    ("How many positive integer solutions does x₁ + x₂ + x₃ = 10 have?",
     ["36", "45", "66", "28"], 0, "Substitute yᵢ = xᵢ − 1: y₁ + y₂ + y₃ = 7, giving C(9, 2) = 36."),
    ("What is the coefficient of x³y² in (x + y)⁵?",
     ["5", "10", "20", "32"], 1, "C(5, 2) = 10."),
    ("What is the coefficient of x² in (1 + 2x)⁵?",
     ["10", "20", "40", "80"], 2, "C(5, 2) × 2² = 10 × 4 = 40."),
    ("What is C(6, 0) + C(6, 1) + … + C(6, 6)?",
     ["36", "64", "720", "12"], 1, "The sum of a row of Pascal's triangle is 2^n = 64."),
    ("Pascal's identity states that C(n + 1, k) equals:",
     ["C(n, k) + C(n, k + 1)", "C(n, k − 1) + C(n, k)", "C(n, k) × C(n, 1)", "2 × C(n, k)"], 1, "It generates Pascal's triangle."),
    ("What is C(20, 17)?",
     ["1140", "6840", "190", "380"], 0, "C(20, 17) = C(20, 3) = 20 × 19 × 18 / 6 = 1140."),
    ("How many diagonals does a convex decagon (10 sides) have?",
     ["35", "45", "40", "90"], 0, "C(10, 2) − 10 = 45 − 10 = 35."),
    ("If each of 10 people shakes hands with every other person exactly once, how many handshakes occur?",
     ["90", "45", "100", "20"], 1, "C(10, 2) = 45."),
    ("In how many ways can 5 different books be arranged on a shelf if two particular books must be together?",
     ["24", "48", "96", "120"], 1, "Treat the pair as one item: 4! arrangements × 2 internal orders = 48."),
    ("In how many ways can the letters of 'COMPUTER' be arranged so that the vowels (O, U, E) are always together?",
     ["720", "4320", "40320", "2160"], 1, "Treat the vowels as one block: 6! × 3! = 720 × 6 = 4320."),
    ("How many 5-card hands can be dealt from a standard 52-card deck?",
     ["311,875,200", "2,598,960", "1,326", "52^5"], 1, "C(52, 5) = 2,598,960."),
    ("In how many ways can 10 identical balls be placed in 4 distinct boxes?",
     ["210", "286", "1,048,576", "40"], 1, "Stars and bars: C(10 + 4 − 1, 4 − 1) = C(13, 3) = 286."),
    ("How many bit strings of length 8 contain exactly three 1s?",
     ["24", "56", "70", "336"], 1, "C(8, 3) = 56."),
    ("How many lattice paths are there from (0, 0) to (4, 3) using unit right and up steps?",
     ["12", "35", "70", "128"], 1, "C(7, 3) = 35."),
    ("How many 3-letter arrangements (no repetition) can be formed from the 8 distinct letters of 'EQUATION'?",
     ["56", "336", "512", "24"], 1, "P(8, 3) = 8 × 7 × 6 = 336."),
    ("In how many ways can 8 people be seated in a row?",
     ["8", "64", "40,320", "5,040"], 2, "8! = 40,320."),
    ("In how many ways can a team of 11 be chosen from 15 players if a particular player must be included?",
     ["C(14, 10) = 1001", "C(15, 11) = 1365", "C(14, 11) = 364", "C(15, 10) = 3003"], 0, "Include him, then choose 10 more from the remaining 14."),
    ("The number of ways to choose 2 items from 5 when order matters, compared with when it does not, is:",
     ["20 and 10", "10 and 20", "25 and 10", "20 and 20"], 0, "P(5, 2) = 20 and C(5, 2) = 10."),
    ("Consider the statements:\nI. P(n, r) = C(n, r) × r!\nII. C(n, r) = C(n, n − r)\nWhich is/are correct?",
     I_II, 2, "Both are standard identities."),
    ("Assertion (A): The number of ways to choose 3 people from 7 equals the number of ways to choose 4 people from 7.\nReason (R): 7 is a prime number.",
     AR, 1, "A is true (C(7, 3) = C(7, 4) = 35), but the reason is that choosing who is in equals choosing who is out, not that 7 is prime."),
]

INCL_EXCL = [
    ("For three finite sets, |A ∪ B ∪ C| equals:",
     ["|A| + |B| + |C|", "|A| + |B| + |C| − |A∩B| − |A∩C| − |B∩C| + |A∩B∩C|", "|A| + |B| + |C| − |A∩B∩C|", "|A∩B∩C|"], 1, "Add singles, subtract pairs, add the triple."),
    ("How many integers from 1 to 100 are divisible by 2, 3 or 5?",
     ["70", "74", "78", "26"], 1, "50 + 33 + 20 − 16 − 10 − 6 + 3 = 74."),
    ("How many integers from 1 to 100 are divisible by none of 2, 3 and 5?",
     ["26", "30", "24", "74"], 0, "100 − 74 = 26."),
    ("The number of derangements of 3 objects, D₃, is:",
     ["1", "2", "3", "6"], 1, "Of the 6 permutations of {1, 2, 3}, only 231 and 312 have no fixed point."),
    ("The number of derangements of 4 objects, D₄, is:",
     ["6", "8", "9", "11"], 2, "D₄ = 4!(1 − 1 + 1/2 − 1/6 + 1/24) = 24 − 24 + 12 − 4 + 1 = 9."),
    ("The number of derangements of 5 objects, D₅, is:",
     ["44", "40", "53", "120"], 0, "D₅ = 120 − 120 + 60 − 20 + 5 − 1 = 44."),
    ("Using Dₙ = (n − 1)(Dₙ₋₁ + Dₙ₋₂), what is D₆?",
     ["240", "265", "300", "720"], 1, "D₆ = 5 × (44 + 9) = 265."),
    ("As n grows, the probability that a random permutation of n objects is a derangement approaches:",
     ["1/2", "1/e ≈ 0.368", "0", "1"], 1, "Dₙ / n! → e^(−1)."),
    ("How many onto (surjective) functions are there from a 5-element set to a 3-element set?",
     ["150", "243", "125", "60"], 0, "3^5 − C(3,1)·2^5 + C(3,2)·1^5 = 243 − 96 + 3 = 150."),
    ("How many onto functions are there from a 4-element set to a 2-element set?",
     ["16", "14", "12", "8"], 1, "2^4 − 2 = 14 (exclude the two constant functions)."),
    ("In how many ways can 5 different jobs be assigned to 4 employees so that every employee gets at least one job?",
     ["240", "1024", "120", "256"], 0, "Onto functions: 4^5 − 4·3^5 + 6·2^5 − 4·1^5 = 1024 − 972 + 192 − 4 = 240."),
    ("1232 students take Spanish, 879 French and 114 Russian; 103 take Spanish and French, 23 Spanish and Russian, 14 French and Russian. If 2092 take at least one, how many take all three?",
     ["5", "7", "9", "14"], 1, "2092 = 1232 + 879 + 114 − 103 − 23 − 14 + x = 2085 + x, so x = 7."),
    ("How many positive integers not exceeding 1000 are divisible by neither 5 nor 7?",
     ["686", "658", "714", "600"], 0, "Divisible by 5 or 7: 200 + 142 − 28 = 314; 1000 − 314 = 686."),
    ("Using inclusion–exclusion, Euler's totient φ(30) is:",
     ["6", "8", "10", "15"], 1, "30 × (1 − 1/2)(1 − 1/3)(1 − 1/5) = 8."),
    ("What is φ(100)?",
     ["40", "50", "20", "60"], 0, "100 × (1 − 1/2)(1 − 1/5) = 40."),
    ("How many solutions does x₁ + x₂ + x₃ = 11 have with 0 ≤ x₁ ≤ 3, 0 ≤ x₂ ≤ 4 and 0 ≤ x₃ ≤ 6?",
     ["4", "6", "8", "78"], 1, "78 − (36 + 28 + 15) + (6 + 1 + 0) − 0 = 6."),
    ("The inclusion–exclusion formula for the union of 4 sets has how many terms?",
     ["4", "8", "15", "16"], 2, "One term for each non-empty sub-collection: 2^4 − 1 = 15."),
    ("25 students study CS, 13 study mathematics and 8 study both. How many study at least one of them?",
     ["38", "30", "33", "46"], 1, "25 + 13 − 8 = 30."),
    ("How many integers from 1 to 1000 are divisible by 3 or 5?",
     ["467", "533", "400", "466"], 0, "333 + 200 − 66 = 467."),
    ("How many integers from 1 to 1000 are divisible by exactly one of 3 and 5?",
     ["401", "467", "335", "266"], 0, "Or-count 467 minus both-count 66 = 401."),
    ("How many integers from 1 to 60 are divisible by 2 or 3?",
     ["40", "50", "30", "10"], 0, "30 + 20 − 10 = 40."),
    ("If A and B are disjoint finite sets, then |A ∪ B| equals:",
     ["|A| + |B| − 1", "|A| + |B|", "|A| × |B|", "max(|A|, |B|)"], 1, "The intersection term is zero."),
    ("What is the probability that a random permutation of 4 elements is a derangement?",
     ["1/4", "3/8", "9/16", "1/3"], 1, "D₄ / 4! = 9/24 = 3/8."),
    ("5 letters are placed at random in 5 addressed envelopes. In how many ways does every letter go into a wrong envelope?",
     ["44", "53", "60", "119"], 0, "D₅ = 44."),
    ("5 letters are placed in 5 envelopes. In how many ways is exactly one letter in its correct envelope?",
     ["44", "45", "40", "20"], 1, "Choose the correct one (5 ways) and derange the other 4 (D₄ = 9): 45."),
    ("The Sieve of Eratosthenes finds the primes up to 100 using the fact that every composite number ≤ 100 has a prime factor at most:",
     ["5", "7", "10", "50"], 1, "√100 = 10, so the primes 2, 3, 5 and 7 are enough."),
    ("How many primes are less than 100?",
     ["21", "24", "25", "30"], 2, "There are 25 primes below 100."),
    ("|A| = 10, |B| = 12 and |A ∩ B| = 4. What is |A ∪ B|?",
     ["22", "18", "26", "14"], 1, "10 + 12 − 4 = 18."),
    ("Consider the statements:\nI. |A ∪ B ∪ C| = |A| + |B| + |C| for all finite sets.\nII. |A ∪ B ∪ C| ≤ |A| + |B| + |C| for all finite sets.\nWhich is/are correct?",
     I_II, 1, "Equality holds only for pairwise disjoint sets; the inequality always holds."),
    ("Assertion (A): D₄ = 9.\nReason (R): Derangements are counted using only the product rule, without inclusion–exclusion.",
     AR, 2, "A is true. R is false: derangements are counted using inclusion–exclusion (or a recurrence)."),
]

INDUCTION = [
    ("The principle of mathematical induction proves ∀n ≥ 1 P(n) by showing:",
     ["P(1) only", "P(1) and ∀k (P(k) → P(k + 1))", "P(k + 1) → P(k)", "P(n) for several examples"], 1, "The basis step and the inductive step."),
    ("In an inductive proof, the assumption that P(k) is true is called the:",
     ["Basis step", "Inductive hypothesis", "Conclusion", "Lemma"], 1, "It is used to prove P(k + 1)."),
    ("In strong induction, the inductive step assumes:",
     ["Only P(k)", "P(1), P(2), …, P(k) are all true", "P(k + 1)", "Nothing"], 1, "It is also called complete induction."),
    ("Mathematical induction is logically equivalent to:",
     ["The pigeonhole principle", "The well-ordering principle", "Bayes' theorem", "De Morgan's laws"], 1, "Every non-empty set of positive integers has a least element."),
    ("When proving 1 + 2 + … + n = n(n + 1)/2 by induction, the inductive step adds which term to both sides?",
     ["n", "k + 1", "2k", "k²"], 1, "Show k(k + 1)/2 + (k + 1) = (k + 1)(k + 2)/2."),
    ("The sum 1 + 3 + 5 + … + (2n − 1) of the first n odd numbers equals:",
     ["n(n + 1)", "n²", "2n", "n(n + 1)/2"], 1, "For n = 4: 1 + 3 + 5 + 7 = 16 = 4²."),
    ("Using 1² + 2² + … + n² = n(n + 1)(2n + 1)/6, what is 1² + 2² + 3² + 4²?",
     ["20", "30", "36", "100"], 1, "4 × 5 × 9 / 6 = 30."),
    ("The inequality 2^n > n² holds for all n ≥ n₀. What is the smallest suitable base case n₀ (for n ≥ 1)?",
     ["1", "3", "5", "4"], 2, "It holds for n = 1 but fails for n = 2, 3, 4 (e.g. 16 = 16 at n = 4); from n = 5 (32 > 25) it holds for every larger n."),
    ("The inequality n! > 2^n holds for all integers n ≥:",
     ["2", "3", "4", "5"], 2, "4! = 24 > 16, while 3! = 6 < 8."),
    ("Induction can be used to prove that n³ − n is divisible by:",
     ["2 only", "3 (in fact 6)", "5", "7"], 1, "n³ − n = (n − 1)n(n + 1), a product of three consecutive integers."),
    ("7^n − 1 is divisible by which number for all n ≥ 1?",
     ["5", "6", "7", "8"], 1, "7^(k+1) − 1 = 7(7^k − 1) + 6."),
    ("8^n − 3^n is divisible by which number for all n ≥ 1?",
     ["3", "5", "8", "11"], 1, "8^(k+1) − 3^(k+1) = 8(8^k − 3^k) + 5 · 3^k."),
    ("In the fallacious 'proof' that all horses are the same colour, the inductive step fails when going from:",
     ["n = 0 to n = 1", "n = 1 to n = 2", "n = 2 to n = 3", "n = 10 to n = 11"], 1, "With 2 horses the two overlapping groups share no horse."),
    ("Which statement is usually proved by strong induction?",
     ["The sum of the first n integers", "Every integer n ≥ 2 is a product of primes", "2^n ≥ n + 1", "n² ≥ n"], 1, "A composite n = a·b uses the hypothesis for the smaller a and b."),
    ("To prove by strong induction that every amount of postage of 12 cents or more can be made with 4- and 5-cent stamps, the basis steps are:",
     ["12 only", "12, 13, 14 and 15", "4 and 5", "12 and 16"], 1, "Each later amount is obtained by adding a 4-cent stamp to an amount 4 less."),
    ("Structural induction is used to prove properties of:",
     ["Real numbers only", "Recursively defined sets and structures such as trees and strings", "Probabilities", "Matrices"], 1, "It follows the recursive definition."),
    ("Using 1 + 2 + 4 + … + 2^n = 2^(n+1) − 1, what is 1 + 2 + 4 + 8 + 16 + 32?",
     ["62", "63", "64", "127"], 1, "n = 5: 2^6 − 1 = 63."),
    ("If only the inductive step P(k) → P(k + 1) is proved but not the basis step, then:",
     ["The statement is proved for all n", "Nothing can be concluded; e.g. 'n = n + 1' has a valid inductive step", "It is proved for n = 1", "It is proved for even n"], 1,
     "Both steps are essential."),
    ("Loop invariants in program correctness proofs are established using:",
     ["Mathematical induction on the number of iterations", "The pigeonhole principle", "Bayes' theorem", "Truth tables only"], 0, "Initialisation is the basis; maintenance is the inductive step."),
    ("The sum of the interior angles of a convex n-gon is (n − 2) × 180°. When proving this by induction, the basis case is:",
     ["n = 1", "n = 2", "n = 3", "n = 4"], 2, "A triangle is the smallest polygon."),
    ("If P(1) and P(2) are true and P(n) → P(n + 2) for all n ≥ 1, then:",
     ["P(n) is true only for odd n", "P(n) is true for all n ≥ 1", "Only P(1) and P(2) are true", "Nothing follows"], 1, "Odd n follow from P(1) and even n from P(2)."),
    ("The Fibonacci numbers satisfy f(n) < 2^n. This is proved most naturally by:",
     ["Strong induction, since f(n) = f(n − 1) + f(n − 2)", "The pigeonhole principle", "Contradiction without induction", "Counting"], 0, "Two previous values are needed."),
    ("Mathematical induction is typically used to prove statements about:",
     ["A single integer", "All integers from some base value onwards", "Real intervals", "Only finite sets of 10 numbers"], 1, "It establishes infinitely many cases."),
    ("Which recurrence defines the factorial function recursively?",
     ["n! = n + (n − 1)!", "0! = 1 and n! = n × (n − 1)!", "n! = 2^n", "n! = n(n + 1)/2"], 1, "Induction proofs about n! use this definition."),
    ("By induction, the number of subsets of an n-element set is:",
     ["n²", "2^n", "n!", "2n"], 1, "Adding one element doubles the number of subsets."),
    ("To prove P(n) for all n ≥ 3 by induction, the basis step checks:",
     ["P(0)", "P(1)", "P(3)", "P(4)"], 2, "The basis is the first value in the range."),
    ("The harmonic numbers satisfy H(2^n) ≥ 1 + n/2. For n = 2, this says H(4) is at least:",
     ["1.5", "2", "2.5", "3"], 1, "1 + 2/2 = 2 (indeed H(4) ≈ 2.083)."),
    ("Which of the following is a correct inductive step for proving 3 | (n³ + 2n)?",
     ["(k + 1)³ + 2(k + 1) = (k³ + 2k) + 3(k² + k + 1)", "(k + 1)³ + 2(k + 1) = k³ + 2k + 1", "(k + 1)³ = k³ + 1", "n³ + 2n = 3n"], 0,
     "The first bracket is divisible by 3 by hypothesis, and the second is a multiple of 3."),
    ("Consider the statements:\nI. Strong induction can prove statements that ordinary induction cannot prove, even in principle.\nII. Strong induction and ordinary induction are equivalent in power.\nWhich is/are correct?",
     I_II, 1, "Any strong-induction proof can be converted into an ordinary one (by proving 'P(1) ∧ … ∧ P(n)')."),
    ("Assertion (A): 2^n > n² for every integer n ≥ 1.\nReason (R): 2^n > n² for every integer n ≥ 5.",
     AR, 3, "A is false (n = 2, 3, 4 fail); R is true and can be proved by induction."),
]

PROBABILITY = [
    ("Two fair dice are rolled. What is the probability that the sum is 7?",
     ["1/12", "1/6", "7/36", "1/9"], 1, "6 favourable outcomes out of 36."),
    ("Two fair dice are rolled. What is the probability that the sum is 8?",
     ["5/36", "1/6", "1/9", "7/36"], 0, "(2,6), (3,5), (4,4), (5,3), (6,2)."),
    ("Two fair dice are rolled. What is the probability of at least one six?",
     ["1/6", "1/3", "11/36", "25/36"], 2, "1 − (5/6)² = 11/36."),
    ("A card is drawn from a standard deck. What is the probability that it is a heart?",
     ["1/13", "1/4", "1/2", "4/13"], 1, "13 hearts out of 52."),
    ("A fair coin is tossed 3 times. What is the probability of at least one head?",
     ["1/8", "3/8", "1/2", "7/8"], 3, "1 − P(no heads) = 1 − 1/8."),
    ("A fair coin is tossed 3 times. What is the probability of exactly 2 heads?",
     ["1/4", "3/8", "1/2", "2/3"], 1, "C(3, 2) / 8 = 3/8."),
    ("Events A and B are independent if and only if:",
     ["P(A ∩ B) = 0", "P(A ∩ B) = P(A) P(B)", "P(A ∪ B) = P(A) + P(B)", "P(A) = P(B)"], 1, "Knowing B does not change the probability of A."),
    ("P(A) = 0.5, P(B) = 0.4 and P(A ∩ B) = 0.2. What is P(A ∪ B)?",
     ["0.9", "0.7", "0.2", "0.1"], 1, "0.5 + 0.4 − 0.2 = 0.7."),
    ("What is the expected value of the number shown by a fair six-sided die?",
     ["3", "3.5", "4", "6"], 1, "(1 + 2 + 3 + 4 + 5 + 6) / 6 = 3.5."),
    ("What is the expected number of heads in 10 tosses of a fair coin?",
     ["2.5", "5", "10", "1"], 1, "np = 10 × 0.5."),
    ("What is the probability of exactly 3 heads in 5 tosses of a fair coin?",
     ["3/5", "5/16", "1/8", "10/16"], 1, "C(5, 3) / 2^5 = 10/32 = 5/16."),
    ("What is the variance of a binomial random variable with n = 10 and p = 0.5?",
     ["5", "2.5", "0.25", "10"], 1, "np(1 − p) = 10 × 0.5 × 0.5 = 2.5."),
    ("In the birthday problem, the smallest number of people for which the probability that two share a birthday exceeds 1/2 is:",
     ["183", "23", "50", "366"], 1, "With 23 people the probability is about 0.507."),
    ("In a lottery where 6 numbers are chosen from 49, the probability of matching all 6 is:",
     ["1/49", "1/13,983,816", "6/49", "1/720"], 1, "C(49, 6) = 13,983,816."),
    ("Two cards are drawn without replacement. What is the probability that both are aces?",
     ["1/169", "1/221", "1/13", "2/52"], 1, "(4/52) × (3/51) = 12/2652 = 1/221."),
    ("The conditional probability P(A | B) is defined as:",
     ["P(A) P(B)", "P(A ∩ B) / P(B)", "P(B | A)", "P(A ∪ B) / P(A)"], 1, "It requires P(B) > 0."),
    ("A random 4-bit string starts with 0. What is the probability that it contains at least two consecutive 0s?",
     ["1/2", "5/8", "3/4", "7/8"], 1, "Of the 8 strings 0xyz, those with '00' are 0000, 0001, 0010, 0011 and 0100: 5/8."),
    ("If each trial succeeds with probability p = 1/6 (e.g. rolling a six), the expected number of trials until the first success is:",
     ["1/6", "3", "6", "36"], 2, "For a geometric distribution the expectation is 1/p."),
    ("By linearity of expectation, the expected sum of two fair dice is:",
     ["6", "7", "3.5", "12"], 1, "3.5 + 3.5 = 7, even without independence."),
    ("In the Monty Hall problem, the probability of winning by switching doors is:",
     ["1/3", "1/2", "2/3", "1"], 2, "Switching wins whenever the first choice was wrong (probability 2/3)."),
    ("What is the probability that the sum of two dice is 2 or 12?",
     ["1/36", "1/18", "1/12", "1/6"], 1, "Two outcomes out of 36."),
    ("What is the probability of at least one six in 4 rolls of a fair die?",
     ["2/3", "1 − (5/6)^4 ≈ 0.518", "4/6", "(1/6)^4"], 1, "Use the complement of 'no six in 4 rolls'."),
    ("How many outcomes are in the sample space of tossing 3 coins?",
     ["3", "6", "8", "9"], 2, "2^3 = 8."),
    ("A and B are independent with P(A) = 0.3 and P(B) = 0.4. What is P(A ∪ B)?",
     ["0.7", "0.58", "0.12", "0.42"], 1, "0.3 + 0.4 − 0.3 × 0.4 = 0.58."),
    ("The expected number of fixed points in a random permutation of n elements is:",
     ["0", "1", "n/2", "n"], 1, "Each element is fixed with probability 1/n; by linearity the total is 1."),
    ("A random variable is best defined as:",
     ["A variable in a program", "A function from the sample space to the real numbers", "A probability", "An event"], 1, "It assigns a number to each outcome."),
    ("For a Bernoulli trial with success probability p, the variance is:",
     ["p", "p(1 − p)", "p²", "1 − p"], 1, "E[X²] − E[X]² = p − p²."),
    ("If a sample space has n equally likely outcomes, the probability of an event E is:",
     ["|E|", "|E| / n", "n / |E|", "1/n"], 1, "Laplace's classical definition."),
    ("Consider the statements:\nI. Mutually exclusive events with non-zero probabilities are independent.\nII. If P(A ∩ B) = P(A) P(B), then A and B are independent.\nWhich is/are correct?",
     I_II, 1, "Mutually exclusive events with positive probabilities are dependent, since P(A ∩ B) = 0 ≠ P(A) P(B)."),
    ("Assertion (A): The probability of getting at least one head in 3 tosses of a fair coin is 7/8.\nReason (R): The probability of getting no head in 3 tosses is 1/8.",
     AR, 0, "Complement rule: 1 − 1/8 = 7/8."),
]

BAYES = [
    ("Bayes' theorem states that P(A | B) equals:",
     ["P(B | A) P(A) / P(B)", "P(A) P(B)", "P(A ∩ B) × P(B)", "P(B | A) / P(A)"], 0, "It reverses the direction of conditioning."),
    ("A disease affects 1% of people. A test detects it 99% of the time and gives false positives 5% of the time. What is P(disease | positive)?",
     ["0.99", "About 0.167", "0.05", "About 0.5"], 1, "0.99 × 0.01 = 0.0099; 0.05 × 0.99 = 0.0495; 0.0099 / 0.0594 ≈ 1/6."),
    ("A rare disease affects 1 in 100,000 people. A test is positive 99% of the time for those with the disease and 0.5% of the time for those without. P(disease | positive) is about:",
     ["0.99", "0.5", "0.002", "0.05"], 2, "0.0000099 / (0.0000099 + 0.005 × 0.99999) ≈ 0.002."),
    ("Box 1 has 2 red and 3 blue balls; Box 2 has 4 red and 1 blue. A box is chosen at random and a red ball is drawn. What is P(Box 1 | red)?",
     ["1/3", "2/5", "1/2", "2/3"], 0, "(0.5 × 2/5) / (0.5 × 2/5 + 0.5 × 4/5) = 0.2 / 0.6 = 1/3."),
    ("Factory A makes 60% of items with 2% defective; factory B makes 40% with 5% defective. A random item is defective. What is P(A | defective)?",
     ["0.6", "0.375", "0.4", "0.625"], 1, "0.012 / (0.012 + 0.020) = 0.012 / 0.032 = 0.375."),
    ("In the same situation (A: 60%, 2% defective; B: 40%, 5% defective), what is the overall probability that an item is defective?",
     ["0.07", "0.032", "0.035", "0.012"], 1, "Total probability: 0.6 × 0.02 + 0.4 × 0.05 = 0.032."),
    ("The word 'offer' appears in 40% of spam and 5% of genuine e-mails. Half of all e-mails are spam. What is P(spam | 'offer')?",
     ["0.4", "8/9 ≈ 0.889", "0.5", "0.95"], 1, "0.2 / (0.2 + 0.025) = 8/9."),
    ("With the same word frequencies (40% of spam, 5% of genuine), but only 20% of e-mails being spam, what is P(spam | 'offer')?",
     ["1/3", "2/3", "0.8", "0.4"], 1, "0.08 / (0.08 + 0.04) = 2/3."),
    ("The law of total probability states that, for a partition B₁, …, Bₙ of the sample space:",
     ["P(A) = Σ P(A | Bᵢ) P(Bᵢ)", "P(A) = Π P(Bᵢ)", "P(A) = P(B₁)", "P(A) = Σ P(Bᵢ | A)"], 0, "It gives the denominator in Bayes' theorem."),
    ("In Bayesian terminology, P(A) before observing evidence B is called the ______ and P(A | B) the ______.",
     ["posterior; prior", "prior; posterior", "likelihood; evidence", "evidence; likelihood"], 1, "Evidence updates the prior to the posterior."),
    ("One of two coins is picked at random: one fair, one two-headed. It is tossed and shows heads. What is the probability it is the two-headed coin?",
     ["1/2", "2/3", "3/4", "1"], 1, "1 × ½ / (1 × ½ + ½ × ½) = 0.5 / 0.75 = 2/3."),
    ("With the same two coins, the chosen coin is tossed twice and shows heads both times. What is the probability that it is two-headed?",
     ["2/3", "3/4", "4/5", "7/8"], 2, "½ / (½ + ½ × ¼) = 0.5 / 0.625 = 4/5."),
    ("Machine M1 produces 30% of output with 1% defective; M2 produces 70% with 2% defective. P(M2 | defective) is:",
     ["0.7", "14/17 ≈ 0.82", "3/17", "0.5"], 1, "0.014 / (0.003 + 0.014) = 14/17."),
    ("It rains on 20% of days. The forecast predicts rain on 80% of rainy days and on 10% of dry days. If rain is forecast, what is the probability of rain?",
     ["0.8", "2/3", "0.2", "0.5"], 1, "0.16 / (0.16 + 0.08) = 2/3."),
    ("The naive Bayes classifier assumes that:",
     ["All classes are equally likely", "Features are conditionally independent given the class", "Features are identical", "There is only one feature"], 1, "This simplifies computing P(features | class)."),
    ("If P(B | A) = P(B), then P(A | B) equals:",
     ["P(B)", "P(A)", "1", "0"], 1, "A and B are independent."),
    ("If B ⊆ A and P(B) > 0, then P(A | B) equals:",
     ["P(A)", "P(B)", "1", "0"], 2, "Whenever B happens, A happens."),
    ("A card drawn from a standard deck is known to be a face card (J, Q or K). What is the probability that it is a king?",
     ["1/13", "1/4", "1/3", "4/52"], 2, "4 kings among 12 face cards."),
    ("A fair die shows an even number. What is the probability that it shows 6?",
     ["1/6", "1/3", "1/2", "2/3"], 1, "6 is one of the three even outcomes."),
    ("A family has two children, and at least one is a boy. What is the probability that both are boys?",
     ["1/2", "1/3", "1/4", "2/3"], 1, "Equally likely cases BB, BG, GB; only BB qualifies."),
    ("A family has two children, and the older one is a boy. What is the probability that both are boys?",
     ["1/2", "1/3", "1/4", "2/3"], 0, "Only the younger child's sex is unknown."),
    ("30% of students pass a test. Of those who pass, 80% attended coaching; of those who fail, 40% attended. What is P(pass | attended coaching)?",
     ["0.8", "6/13 ≈ 0.46", "0.3", "0.24"], 1, "0.24 / (0.24 + 0.28) = 0.24 / 0.52 = 6/13."),
    ("Machines A, B and C make 50%, 30% and 20% of items with 3%, 4% and 5% defects respectively. What is P(C | defective)?",
     ["0.2", "10/37", "0.05", "15/37"], 1, "P(defective) = 0.015 + 0.012 + 0.010 = 0.037; P(C | D) = 0.010 / 0.037 = 10/37."),
    ("Ignoring the low base rate of a condition and trusting only a test's accuracy is called the:",
     ["Gambler's fallacy", "Base-rate fallacy", "Monty Hall problem", "Law of large numbers"], 1, "This is why positive results for rare diseases often need confirmation."),
    ("In Bayes' theorem, the denominator P(B) is often called the:",
     ["Prior", "Evidence (marginal likelihood)", "Posterior", "Odds"], 1, "It normalises the posterior."),
    ("The multiplication rule states that P(A ∩ B) equals:",
     ["P(A) + P(B)", "P(A | B) P(B)", "P(A) / P(B)", "P(B | A) / P(A)"], 1, "Equivalently P(B | A) P(A)."),
    ("In a test with no false positives (specificity 100%), a positive result implies the probability of disease is:",
     ["Equal to the prevalence", "1", "0.5", "Equal to the sensitivity"], 1, "If only diseased people can test positive, P(disease | positive) = 1."),
    ("If the prior probability of an event is 0, then after any observation its posterior probability is:",
     ["Still 0", "1", "0.5", "Undefined always"], 0, "Bayes' formula multiplies by the prior."),
    ("Consider the statements:\nI. P(A | B) = P(B | A) for all events A and B.\nII. Bayes' theorem can be derived from the definition of conditional probability.\nWhich is/are correct?",
     I_II, 1, "P(A | B) and P(B | A) differ unless P(A) = P(B); II is correct."),
    ("Assertion (A): A positive result from a very accurate test for a very rare disease may still mean the person probably does not have the disease.\nReason (R): When prevalence is very low, false positives from the large healthy population can outnumber the true positives.",
     AR, 0, "This is the classic base-rate effect."),
]

TOPICS = {
    "Counting": [("1 · Basics of Counting", COUNT_BASICS), ("2 · Pigeonhole Principle", PIGEONHOLE),
                 ("3 · Permutations and Combinations", PERM_COMB), ("4 · Inclusion–Exclusion Principle", INCL_EXCL)],
    "Mathematical Induction & Discrete Probability": [("1 · Mathematical Induction", INDUCTION), ("2 · Discrete Probability", PROBABILITY),
                                                      ("3 · Bayes' Theorem", BAYES)],
}
