"""Paper 2 · Unit 2 · topics U2-01 and U2-02 (6 sub-topics × 30). Reference: Rosen, Discrete Mathematics and Its Applications."""
from packlib import AR, I_II

PROP = [
    ("Which of the following is a proposition?",
     ["x + 1 = 5", "2 + 3 = 7", "Close the door.", "What time is it?"], 1,
     "A proposition is a declarative sentence that is either true or false. '2 + 3 = 7' is false but is still a proposition; 'x + 1 = 5' depends on x."),
    ("The conditional p → q is false only when:",
     ["p is false and q is true", "p is true and q is false", "both are false", "both are true"], 1, "An implication fails only when a true hypothesis leads to a false conclusion."),
    ("The contrapositive of p → q is:",
     ["q → p", "¬p → ¬q", "¬q → ¬p", "¬(p → q)"], 2, "q → p is the converse and ¬p → ¬q is the inverse."),
    ("Which of the following is logically equivalent to p → q?",
     ["Its converse", "Its inverse", "Its contrapositive", "p ∧ q"], 2, "An implication and its contrapositive always have the same truth value."),
    ("The contrapositive of 'If it rains, then the ground is wet' is:",
     ["If the ground is wet, then it rains", "If it does not rain, then the ground is not wet", "If the ground is not wet, then it does not rain", "It rains and the ground is not wet"], 2,
     "Contrapositive: ¬q → ¬p."),
    ("The biconditional p ↔ q is true exactly when:",
     ["p is true", "p and q have the same truth value", "p and q have different truth values", "q is false"], 1, "p ↔ q is true when both are true or both are false."),
    ("How many rows does the truth table of a compound proposition with 4 distinct variables have?",
     ["4", "8", "16", "32"], 2, "n variables give 2^n rows: 2^4 = 16."),
    ("In the usual precedence of logical operators, which is applied first?",
     ["→", "∨", "∧", "¬"], 3, "The order is ¬, then ∧, then ∨, then →, then ↔."),
    ("The exclusive OR p ⊕ q is true when:",
     ["Both are true", "Exactly one of p and q is true", "Both are false", "p is true"], 1, "XOR is true when the truth values differ."),
    ("'p only if q' is expressed as:",
     ["q → p", "p → q", "p ↔ q", "p ∧ q"], 1, "'Only if' introduces the necessary condition: p cannot be true unless q is true."),
    ("'q is necessary for p' is expressed as:",
     ["p → q", "q → p", "¬p → q", "p ∨ q"], 0, "A necessary condition is the conclusion of the implication."),
    ("'p unless q' is logically equivalent to:",
     ["p ∧ q", "¬q → p", "q → p", "p → q"], 1, "'p unless q' means 'if not q then p', which is also equivalent to p ∨ q."),
    ("Which of the following is a tautology?",
     ["p ∧ ¬p", "p ∨ ¬p", "p → q", "p ∧ q"], 1, "p ∨ ¬p is always true (law of excluded middle)."),
    ("Which of the following is a contradiction?",
     ["p ∨ ¬p", "p ∧ ¬p", "p → p", "p ↔ p"], 1, "p ∧ ¬p is always false."),
    ("A compound proposition that is neither a tautology nor a contradiction is called a:",
     ["Contingency", "Paradox", "Predicate", "Lemma"], 0, "Its truth value depends on the values of its variables, e.g. p → q."),
    ("If p is true and q is false, what is the truth value of (p ∨ q) → (p ∧ q)?",
     ["True", "False", "Cannot be determined", "Both"], 1, "p ∨ q = T and p ∧ q = F, so T → F = F."),
    ("If p is false and q is true, what is the truth value of ¬p ↔ q?",
     ["True", "False", "Undefined", "Depends on r"], 0, "¬p = T and q = T, so T ↔ T = T."),
    ("How many different truth tables (Boolean functions) are possible for compound propositions in 2 variables?",
     ["4", "8", "16", "256"], 2, "There are 4 rows, each can be T or F: 2^4 = 16."),
    ("The proposition p → (q → p) is a:",
     ["Contradiction", "Tautology", "Contingency", "Paradox"], 1, "If p is true, q → p is true; if p is false, the implication is vacuously true."),
    ("(p → q) ∧ (q → p) is logically equivalent to:",
     ["p ∧ q", "p ↔ q", "p ⊕ q", "p ∨ q"], 1, "This is the definition of the biconditional."),
    ("The sentence 'This statement is false' is:",
     ["A true proposition", "A false proposition", "Not a proposition, because it cannot consistently be assigned a truth value", "A tautology"], 2,
     "It is the liar paradox."),
    ("Let p: 'It is hot' and q: 'It is sunny'. 'It is not hot but it is sunny' is:",
     ["¬p ∨ q", "¬p ∧ q", "p ∧ ¬q", "¬(p ∧ q)"], 1, "'But' is translated as 'and'."),
    ("'Neither p nor q' is written as:",
     ["¬p ∨ ¬q", "¬p ∧ ¬q", "¬(p ∧ q)", "p ⊕ q"], 1, "It is also equal to ¬(p ∨ q), the NOR of p and q."),
    ("The NAND of p and q, written p ↑ q, is false only when:",
     ["Both are false", "Both are true", "Exactly one is true", "p is true"], 1, "p ↑ q = ¬(p ∧ q)."),
    ("The NOR of p and q, written p ↓ q, is true only when:",
     ["Both are true", "Both are false", "Exactly one is true", "q is true"], 1, "p ↓ q = ¬(p ∨ q)."),
    ("In how many of the four rows of its truth table is p → q true?",
     ["1", "2", "3", "4"], 2, "It is false only for p = T, q = F."),
    ("What is the bitwise XOR of 1011 and 0110?",
     ["0010", "1111", "1101", "0100"], 2, "Bit by bit: 1⊕0 = 1, 0⊕1 = 1, 1⊕1 = 0, 1⊕0 = 1 → 1101."),
    ("What is the bitwise AND of 1011 and 0110?",
     ["0010", "1111", "1101", "0110"], 0, "Only the second bit from the right is 1 in both."),
    ("Consider the statements:\nI. The converse of a true implication is always true.\nII. The contrapositive of a true implication is always true.\nWhich is/are correct?",
     I_II, 1, "The converse may be false (e.g. 'If x = 2 then x² = 4' vs 'If x² = 4 then x = 2'); the contrapositive is equivalent."),
    ("Assertion (A): q → p is logically equivalent to p → q.\nReason (R): ¬q → ¬p is logically equivalent to p → q.",
     AR, 3, "A is false: the converse is not equivalent. R is true: the contrapositive is equivalent."),
]

EQUIV = [
    ("By De Morgan's law, ¬(p ∧ q) is equivalent to:",
     ["¬p ∧ ¬q", "¬p ∨ ¬q", "p ∨ q", "¬p → q"], 1, "¬(p ∧ q) ≡ ¬p ∨ ¬q and ¬(p ∨ q) ≡ ¬p ∧ ¬q."),
    ("p → q is logically equivalent to:",
     ["p ∨ ¬q", "¬p ∨ q", "¬p ∧ q", "p ∧ ¬q"], 1, "The implication is false only when p is true and q is false, which is exactly when ¬p ∨ q is false."),
    ("¬(p → q) is logically equivalent to:",
     ["¬p → ¬q", "p ∧ ¬q", "¬p ∧ q", "¬p ∨ q"], 1, "¬(¬p ∨ q) ≡ p ∧ ¬q."),
    ("By the absorption law, p ∨ (p ∧ q) simplifies to:",
     ["q", "p", "p ∧ q", "p ∨ q"], 1, "Also p ∧ (p ∨ q) ≡ p."),
    ("By the distributive law, p ∨ (q ∧ r) is equivalent to:",
     ["(p ∨ q) ∧ (p ∨ r)", "(p ∧ q) ∨ (p ∧ r)", "(p ∨ q) ∨ r", "p ∧ q ∧ r"], 0, "∨ distributes over ∧ in propositional logic."),
    ("p ↔ q is equivalent to:",
     ["(p ∧ q) ∨ (¬p ∧ ¬q)", "(p ∧ ¬q) ∨ (¬p ∧ q)", "p ∨ q", "¬p ∧ ¬q"], 0, "Both true or both false."),
    ("¬(p ↔ q) is equivalent to:",
     ["p ↔ q", "p ↔ ¬q", "p ∧ q", "¬p ∧ ¬q"], 1, "The negation of a biconditional is XOR, which equals p ↔ ¬q."),
    ("(p → q) ∧ (p → r) is equivalent to:",
     ["p → (q ∨ r)", "p → (q ∧ r)", "(p ∧ q) → r", "(q ∧ r) → p"], 1, "A common hypothesis can be factored out of a conjunction of implications."),
    ("(p → r) ∧ (q → r) is equivalent to:",
     ["(p ∧ q) → r", "(p ∨ q) → r", "p → (q ∨ r)", "r → (p ∨ q)"], 1, "If each of p and q implies r, then 'p or q' implies r."),
    ("(p → q) ∨ (p → r) is equivalent to:",
     ["p → (q ∨ r)", "p → (q ∧ r)", "(p ∨ q) → r", "(p ∧ q) → r"], 0, "¬p ∨ q ∨ ¬p ∨ r ≡ ¬p ∨ (q ∨ r)."),
    ("p → (q → r) is equivalent to:",
     ["(p → q) → r", "(p ∧ q) → r", "(p ∨ q) → r", "p ∧ q ∧ r"], 1, "This is the exportation law."),
    ("Which of the following is NOT equivalent to p → q?",
     ["¬q → ¬p", "¬p ∨ q", "q → p", "¬(p ∧ ¬q)"], 2, "q → p is the converse."),
    ("A compound proposition is 'satisfiable' if:",
     ["It is true for every assignment", "It is true for at least one assignment of truth values", "It is false for every assignment", "It contains only ∧"], 1,
     "Unsatisfiable means false for all assignments (a contradiction)."),
    ("Which set of connectives is NOT functionally complete?",
     ["{¬, ∧}", "{¬, ∨}", "{∧, ∨}", "{NAND}"], 2, "Using only ∧ and ∨ you cannot express negation (they are monotone)."),
    ("The domination law states that p ∨ T is equivalent to:",
     ["p", "T", "F", "¬p"], 1, "p ∨ T ≡ T and p ∧ F ≡ F; the identity laws are p ∧ T ≡ p and p ∨ F ≡ p."),
    ("Simplify: ¬(¬p ∧ q) ∧ (p ∨ q).",
     ["p", "q", "p ∧ q", "T"], 0, "¬(¬p ∧ q) ≡ p ∨ ¬q; then (p ∨ ¬q) ∧ (p ∨ q) ≡ p ∨ (¬q ∧ q) ≡ p ∨ F ≡ p."),
    ("The proposition (p ∧ q) → (p ∨ q) is a:",
     ["Contradiction", "Contingency", "Tautology", "Paradox"], 2, "Whenever p ∧ q is true, p ∨ q is also true."),
    ("Is (p → q) → r equivalent to p → (q → r)?",
     ["Yes, always", "No; for p = F, q = T, r = F the first is false and the second is true", "Yes, because → is associative", "Only when r is true"], 1,
     "(F→T)→F = T→F = F, while F→(T→F) = T. Implication is not associative."),
    ("The dual of p ∧ (q ∨ T) is:",
     ["p ∨ (q ∧ F)", "p ∧ (q ∨ F)", "¬p ∨ (¬q ∧ F)", "p ∨ (q ∨ T)"], 0, "Swap ∧ with ∨ and T with F."),
    ("Two compound propositions P and Q are logically equivalent if and only if:",
     ["P ∧ Q is a tautology", "P ↔ Q is a tautology", "P → Q is satisfiable", "P ∨ Q is a tautology"], 1, "They must have the same truth value in every row."),
    ("¬p → (q → r) is equivalent to:",
     ["p ∨ ¬q ∨ r", "¬p ∨ q ∨ r", "p ∧ q ∧ ¬r", "p ∨ q ∨ r"], 0, "¬p → X ≡ p ∨ X, and q → r ≡ ¬q ∨ r."),
    ("How many truth assignments of p, q, r make p ∨ q ∨ r true?",
     ["1", "3", "7", "8"], 2, "Only p = q = r = F makes it false, so 8 − 1 = 7."),
    ("Which of these implications is a tautology?",
     ["(p ∧ (p → q)) → q", "(q ∧ (p → q)) → p", "(p → q) → (q → p)", "(p ∨ q) → p"], 0, "This is modus ponens written as a tautology; the second is the fallacy of affirming the consequent."),
    ("((p ∨ q) ∧ ¬p) → q is:",
     ["A contradiction", "A contingency", "A tautology", "Not well-formed"], 2, "This is disjunctive syllogism."),
    ("The idempotent law states that:",
     ["p ∨ p ≡ p", "p ∨ ¬p ≡ T", "¬¬p ≡ p", "p ∨ q ≡ q ∨ p"], 0, "Also p ∧ p ≡ p."),
    ("Using only NAND, ¬p can be written as:",
     ["p ↑ p", "(p ↑ p) ↑ (p ↑ p)", "p ↑ T ↑ F", "p ↑ ¬p"], 0, "p ↑ p = ¬(p ∧ p) = ¬p."),
    ("Using only NAND, p ∧ q can be written as:",
     ["p ↑ q", "(p ↑ q) ↑ (p ↑ q)", "(p ↑ p) ↑ (q ↑ q)", "p ↑ (q ↑ q)"], 1, "Negating p ↑ q gives p ∧ q. (p ↑ p) ↑ (q ↑ q) equals p ∨ q."),
    ("Which statement about the connective → is correct?",
     ["It is commutative", "It is associative", "It is neither commutative nor associative", "It is idempotent"], 2, "p → q ≠ q → p and (p → q) → r ≠ p → (q → r)."),
    ("Consider the statements:\nI. {¬, ∨} is functionally complete.\nII. {∧, ∨} is functionally complete.\nWhich is/are correct?",
     I_II, 0, "With ¬ and ∨ we get ∧ via De Morgan's law; without ¬, negation cannot be expressed."),
    ("Assertion (A): NAND alone is functionally complete.\nReason (R): ¬p ≡ p ↑ p and p ∧ q ≡ (p ↑ q) ↑ (p ↑ q).",
     AR, 0, "Since {¬, ∧} is functionally complete and both can be built from NAND, NAND alone is complete."),
]

NORMAL = [
    ("A formula in Disjunctive Normal Form (DNF) is a:",
     ["Conjunction of disjunctions of literals", "Disjunction of conjunctions of literals", "Formula with only implications", "Formula with only negations"], 1,
     "DNF is a 'sum of products'."),
    ("A formula in Conjunctive Normal Form (CNF) is a:",
     ["Disjunction of conjunctions", "Conjunction of disjunctions (clauses) of literals", "Single literal only", "Formula without negation"], 1, "CNF is a 'product of sums'."),
    ("The Principal Disjunctive Normal Form (PDNF) of a formula is a:",
     ["Product of maxterms", "Sum (disjunction) of minterms", "Product of minterms", "Sum of maxterms"], 1, "Each minterm corresponds to a row where the formula is true."),
    ("The Principal Conjunctive Normal Form (PCNF) is a:",
     ["Product (conjunction) of maxterms", "Sum of minterms", "Sum of maxterms", "Product of literals only"], 0, "Each maxterm corresponds to a row where the formula is false."),
    ("How many minterms are possible in n propositional variables?",
     ["n", "2n", "2^n", "n²"], 2, "One minterm for each row of the truth table."),
    ("The minterm corresponding to p = T, q = F, r = T is:",
     ["p ∧ ¬q ∧ r", "¬p ∨ q ∨ ¬r", "p ∨ ¬q ∨ r", "¬p ∧ q ∧ ¬r"], 0, "A minterm is true for exactly that one assignment."),
    ("The maxterm that is false only for p = T, q = F is:",
     ["p ∧ ¬q", "¬p ∨ q", "p ∨ ¬q", "¬p ∧ q"], 1, "A maxterm uses the complemented values: it is false only on its row."),
    ("The PDNF of p → q is:",
     ["(p ∧ q) ∨ (¬p ∧ q) ∨ (¬p ∧ ¬q)", "(p ∧ ¬q)", "(p ∧ q)", "(¬p ∧ q) ∨ (p ∧ ¬q)"], 0, "p → q is true in the rows TT, FT and FF."),
    ("The PCNF of p → q is:",
     ["(p ∨ q)", "(¬p ∨ q)", "(p ∨ ¬q)", "(¬p ∨ ¬q)"], 1, "It is false only in the row p = T, q = F, giving the single maxterm ¬p ∨ q."),
    ("A function of 3 variables has 5 minterms in its PDNF. How many maxterms does its PCNF have?",
     ["3", "5", "8", "2"], 0, "Minterms and maxterms together cover all 2³ = 8 rows."),
    ("The PCNF of a tautology contains how many maxterms?",
     ["0", "1", "2^n", "n"], 0, "A tautology is never false, so there are no maxterms (the PDNF has all 2^n minterms)."),
    ("The PDNF of p ∨ q is:",
     ["(p ∧ q) ∨ (p ∧ ¬q) ∨ (¬p ∧ q)", "(¬p ∧ ¬q)", "(p ∧ q)", "(p ∧ ¬q) ∨ (¬p ∧ q)"], 0, "p ∨ q is true in three rows."),
    ("The CNF of (p ∧ q) ∨ r is:",
     ["(p ∨ r) ∧ (q ∨ r)", "(p ∧ r) ∨ (q ∧ r)", "p ∧ q ∧ r", "(p ∨ q) ∧ r"], 0, "Distribute ∨ over ∧."),
    ("The CNF of (¬p ∧ ¬q) ∨ r is:",
     ["(¬p ∨ r) ∧ (¬q ∨ r)", "¬p ∧ ¬q ∧ r", "(¬p ∨ ¬q) ∧ r", "¬(p ∨ q ∨ r)"], 0, "Again distribute ∨ over ∧."),
    ("CNF is especially important because it is the standard input form for:",
     ["Spreadsheets", "SAT solvers and resolution-based theorem proving", "Compilers' lexical analysis", "Sorting algorithms"], 1,
     "Resolution works on clauses, and SAT solvers accept CNF."),
    ("A CNF formula is a tautology if and only if:",
     ["It has one clause", "Every clause contains some literal together with its negation", "It has no negation", "Every clause has one literal"], 1,
     "Each clause must be always true."),
    ("A DNF formula is satisfiable if and only if:",
     ["All terms are contradictory", "At least one term contains no pair of complementary literals", "It has at least two terms", "It has no negation"], 1,
     "Such a term can be made true, which makes the whole disjunction true."),
    ("How many distinct Boolean functions (and hence distinct PDNFs) exist in 3 variables?",
     ["8", "64", "256", "512"], 2, "2^(2^3) = 2^8 = 256."),
    ("The PDNF of p ↔ q is:",
     ["(p ∧ q) ∨ (¬p ∧ ¬q)", "(p ∧ ¬q) ∨ (¬p ∧ q)", "(p ∨ q)", "(¬p ∨ q) ∧ (p ∨ ¬q)"], 0, "Both true or both false."),
    ("The PDNF of p ⊕ q is:",
     ["(p ∧ ¬q) ∨ (¬p ∧ q)", "(p ∧ q) ∨ (¬p ∧ ¬q)", "(p ∨ q)", "(p ∧ q)"], 0, "XOR is true when exactly one is true."),
    ("A 3-variable function is true exactly when an odd number of its variables are true. How many minterms does its PDNF contain?",
     ["3", "4", "5", "8"], 1, "One row with three trues and three rows with exactly one true: 1 + 3 = 4."),
    ("The 3-variable majority function (true when at least two variables are true) has how many minterms?",
     ["3", "4", "6", "7"], 1, "Three rows with exactly two trues plus one with all three: 4."),
    ("With p as the most significant bit, the function Σm(1, 3, 5, 7) of p, q, r simplifies to:",
     ["p", "q", "r", "p ∧ q ∧ r"], 2, "Minterms 1, 3, 5, 7 are exactly the rows where r = 1."),
    ("If F(p, q, r) = Σm(0, 2, 4, 6), then its PCNF is:",
     ["ΠM(0, 2, 4, 6)", "ΠM(1, 3, 5, 7)", "Σm(1, 3, 5, 7)", "ΠM(0, 1, 2, 3)"], 1, "The maxterms are the rows not listed as minterms."),
    ("Which statement about the PDNF of a formula is correct?",
     ["A formula can have many different PDNFs with different minterms", "The PDNF of a formula is unique up to the order of minterms and literals",
      "Only tautologies have a PDNF", "PDNF uses maxterms"], 1, "This uniqueness makes PDNF useful for testing equivalence."),
    ("A Horn clause is a clause with:",
     ["No literals", "At most one positive (un-negated) literal", "Exactly two literals", "Only positive literals"], 1, "Horn clauses are the basis of Prolog."),
    ("A 'literal' in propositional logic is:",
     ["A connective", "A propositional variable or its negation", "A truth table", "A tautology"], 1, "For example p and ¬p are literals."),
    ("A 'clause' in CNF is:",
     ["A conjunction of literals", "A disjunction of literals", "A single variable only", "An implication"], 1, "CNF is a conjunction of clauses."),
    ("Consider the statements:\nI. Every propositional formula has an equivalent formula in CNF.\nII. Every propositional formula has an equivalent formula in DNF.\nWhich is/are correct?",
     I_II, 2, "Both normal forms exist for every formula (e.g. read them off the truth table)."),
    ("Assertion (A): Converting a formula into CNF never increases its size.\nReason (R): A CNF formula is a conjunction of clauses.",
     AR, 3, "A is false: distributing ∨ over ∧ can cause exponential growth, e.g. (p1 ∧ q1) ∨ … ∨ (pn ∧ qn). R is true."),
]

PREDICATES = [
    ("Let P(x) be 'x > 3'. What is the truth value of P(4)?",
     ["True", "False", "Undefined", "Depends on the domain"], 0, "4 > 3."),
    ("∀x P(x) is false when:",
     ["P(x) is true for every x", "There is at least one x in the domain for which P(x) is false", "P(x) is false for all x only", "The domain is infinite"], 1,
     "A single counterexample is enough."),
    ("∃x P(x) is true when:",
     ["P(x) is true for all x", "P(x) is true for at least one x in the domain", "P(x) is false for all x", "The domain is empty"], 1, "One witness is enough."),
    ("¬∀x P(x) is equivalent to:",
     ["∀x ¬P(x)", "∃x ¬P(x)", "¬∃x P(x)", "∃x P(x)"], 1, "De Morgan's law for quantifiers."),
    ("¬∃x P(x) is equivalent to:",
     ["∃x ¬P(x)", "∀x ¬P(x)", "∀x P(x)", "¬∀x ¬P(x)"], 1, "No x satisfies P means every x fails P."),
    ("With the domain of all integers, what is the truth value of ∃x (x² = 2)?",
     ["True", "False", "Undefined", "True only for x = √2"], 1, "√2 is not an integer."),
    ("With the domain of all real numbers, what is the truth value of ∃x (x² = 2)?",
     ["True", "False", "Undefined", "Depends on x"], 0, "x = √2 works."),
    ("'Every student in this class has studied calculus' (S(x): x is a student in this class, C(x): x has studied calculus; domain: all people) is:",
     ["∀x (S(x) ∧ C(x))", "∀x (S(x) → C(x))", "∃x (S(x) ∧ C(x))", "∃x (S(x) → C(x))"], 1, "∀x (S(x) ∧ C(x)) would say everyone is a student."),
    ("'Some student in this class has visited Mexico' (S(x), M(x); domain: all people) is:",
     ["∃x (S(x) → M(x))", "∃x (S(x) ∧ M(x))", "∀x (S(x) → M(x))", "∀x (S(x) ∧ M(x))"], 1,
     "∃x (S(x) → M(x)) is wrongly true whenever someone is not a student."),
    ("In ∃x P(x, y), the variable y is:",
     ["Bound", "Free", "A constant", "Quantified by ∃"], 1, "Only x is bound by the quantifier."),
    ("Because quantifiers have higher precedence than logical connectives, ∀x P(x) ∨ Q(x) means:",
     ["∀x (P(x) ∨ Q(x))", "(∀x P(x)) ∨ Q(x)", "∃x P(x) ∨ Q(x)", "It is not well-formed"], 1, "In the second part x is free."),
    ("∃!x P(x) means:",
     ["There is at least one x", "There is exactly one x such that P(x)", "For all x", "There is no x"], 1, "It is the uniqueness quantifier."),
    ("∀x (P(x) ∧ Q(x)) is equivalent to:",
     ["∀x P(x) ∧ ∀x Q(x)", "∀x P(x) ∨ ∀x Q(x)", "∃x P(x) ∧ ∃x Q(x)", "∀x P(x) → ∀x Q(x)"], 0, "∀ distributes over ∧."),
    ("∃x (P(x) ∨ Q(x)) is equivalent to:",
     ["∃x P(x) ∧ ∃x Q(x)", "∃x P(x) ∨ ∃x Q(x)", "∀x P(x) ∨ ∀x Q(x)", "∃x P(x) → Q(x)"], 1, "∃ distributes over ∨."),
    ("Which of these is always valid (true in every interpretation)?",
     ["∀x (P(x) ∨ Q(x)) → (∀x P(x) ∨ ∀x Q(x))", "(∀x P(x) ∨ ∀x Q(x)) → ∀x (P(x) ∨ Q(x))",
      "(∃x P(x) ∧ ∃x Q(x)) → ∃x (P(x) ∧ Q(x))", "∃x P(x) → ∀x P(x)"], 1,
     "If all satisfy P, or all satisfy Q, then each satisfies P ∨ Q; the converse can fail (e.g. P = even, Q = odd)."),
    ("Over the finite domain {1, 2, 3}, ∀x P(x) is equivalent to:",
     ["P(1) ∨ P(2) ∨ P(3)", "P(1) ∧ P(2) ∧ P(3)", "P(1) → P(3)", "P(2) only"], 1, "A universal statement over a finite domain is a conjunction."),
    ("Over the finite domain {1, 2, 3}, ∃x P(x) is equivalent to:",
     ["P(1) ∧ P(2) ∧ P(3)", "P(1) ∨ P(2) ∨ P(3)", "¬P(1) ∧ ¬P(2)", "P(1) ↔ P(3)"], 1, "An existential statement over a finite domain is a disjunction."),
    ("The negation of 'Every student is honest' is:",
     ["No student is honest", "There is a student who is not honest", "Every student is dishonest", "Some student is honest"], 1, "¬∀x (S(x) → H(x)) ≡ ∃x (S(x) ∧ ¬H(x))."),
    ("The negation of ∀x (x > 0 → x² > 0) is:",
     ["∃x (x > 0 ∧ x² ≤ 0)", "∀x (x ≤ 0 → x² ≤ 0)", "∃x (x > 0 → x² ≤ 0)", "∀x (x > 0 ∧ x² ≤ 0)"], 0, "¬(A → B) ≡ A ∧ ¬B, and ¬∀ becomes ∃."),
    ("Predicate logic is also known as:",
     ["Propositional calculus", "First-order logic", "Fuzzy logic", "Boolean algebra"], 1, "It extends propositional logic with predicates and quantifiers."),
    ("A propositional function P(x) becomes a proposition when:",
     ["It contains ∧", "A value is assigned to x or x is bound by a quantifier", "It is negated", "It is written twice"], 1, "Otherwise its truth value is undetermined."),
    ("Let Q(x, y) be 'x + y = 0' over the integers. What is the truth value of Q(2, −2)?",
     ["True", "False", "Undefined", "Depends on the domain of y only"], 0, "2 + (−2) = 0."),
    ("With the domain of all real numbers, ∀x (x² ≥ 0) is:",
     ["True", "False", "Undefined", "True only for positive x"], 0, "A square of a real number is never negative."),
    ("With the domain of all integers, ∀x (x² > x) is:",
     ["True", "False, e.g. x = 1 (1 > 1 is false)", "True for all x ≠ 0", "Undefined"], 1, "x = 0 and x = 1 are counterexamples."),
    ("'Not every bird can fly' is equivalent to:",
     ["No bird can fly", "There is a bird that cannot fly", "Every bird cannot fly", "Some birds can fly"], 1, "¬∀x (B(x) → F(x)) ≡ ∃x (B(x) ∧ ¬F(x))."),
    ("'No dog is a cat' (D(x), C(x)) is expressed as:",
     ["∀x (D(x) → ¬C(x))", "∃x (D(x) ∧ C(x))", "∀x (D(x) ∧ ¬C(x))", "¬∀x (D(x) → C(x))"], 0, "Equivalently ¬∃x (D(x) ∧ C(x))."),
    ("If the domain has n elements and P is a predicate of one variable, how many different truth-value patterns (predicates) are possible?",
     ["n", "2n", "2^n", "n²"], 2, "Each of the n elements can independently make P true or false."),
    ("In the statement ∀x (P(x) → ∃y Q(x, y)), the scope of ∃y is:",
     ["The whole formula", "Q(x, y)", "P(x)", "Only x"], 1, "∃y binds y in Q(x, y)."),
    ("Consider the statements:\nI. ∀x (P(x) ∧ Q(x)) ≡ ∀x P(x) ∧ ∀x Q(x).\nII. ∀x (P(x) ∨ Q(x)) ≡ ∀x P(x) ∨ ∀x Q(x).\nWhich is/are correct?",
     I_II, 0, "∀ distributes over ∧ but not over ∨."),
    ("Assertion (A): ¬∀x P(x) is logically equivalent to ∃x ¬P(x).\nReason (R): The universal quantifier distributes over disjunction.",
     AR, 2, "A is De Morgan's law for quantifiers and is true; R is false."),
]

NESTED = [
    ("Over the integers, the truth value of ∀x ∃y (x + y = 0) is:",
     ["True", "False", "Undefined", "True only for positive x"], 0, "For each x choose y = −x."),
    ("Over the integers, the truth value of ∃y ∀x (x + y = 0) is:",
     ["True", "False", "Undefined", "True for y = 0"], 1, "No single y works for every x."),
    ("Over the real numbers, ∀x ∀y (x + y = y + x) is:",
     ["True", "False", "Undefined", "True only for integers"], 0, "Addition is commutative."),
    ("Which statement about quantifier order is correct?",
     ["∀x ∀y P(x, y) ≡ ∀y ∀x P(x, y)", "∀x ∃y P(x, y) ≡ ∃y ∀x P(x, y) always", "∃x ∀y P ≡ ∀x ∃y P", "Order never matters"], 0,
     "Swapping quantifiers of the same type is allowed; mixing ∀ and ∃ is not."),
    ("Over the natural numbers, ∀x ∃y (y > x) is ______, but ∃y ∀x (y > x) is ______.",
     ["true; true", "true; false", "false; true", "false; false"], 1, "Every number has a larger one, but no number is larger than all numbers."),
    ("Over the real numbers, ∀x ∃y (x·y = 1) is:",
     ["True", "False, because x = 0 has no multiplicative inverse", "True for all x", "Undefined"], 1, "Restricting to non-zero reals makes it true."),
    ("The negation of ∀x ∃y P(x, y) is:",
     ["∃x ∀y ¬P(x, y)", "∀x ∃y ¬P(x, y)", "∃x ∃y ¬P(x, y)", "∀x ∀y ¬P(x, y)"], 0, "Move ¬ inwards, flipping each quantifier."),
    ("'There is a person who loves everyone' (L(x, y): x loves y) is:",
     ["∀x ∃y L(x, y)", "∃x ∀y L(x, y)", "∀y ∃x L(x, y)", "∃y ∀x L(x, y)"], 1, "One x loves every y."),
    ("'Everybody loves somebody' is:",
     ["∀x ∃y L(x, y)", "∃x ∀y L(x, y)", "∃y ∀x L(x, y)", "∀x ∀y L(x, y)"], 0, "For each x there is some y."),
    ("'There is someone whom everybody loves' is:",
     ["∀x ∃y L(x, y)", "∃y ∀x L(x, y)", "∃x ∀y L(x, y)", "∀y ∃x L(x, y)"], 1, "One y is loved by every x."),
    ("'Everybody is loved by somebody' is:",
     ["∀y ∃x L(x, y)", "∃x ∀y L(x, y)", "∀x ∃y L(x, y)", "∃y ∀x L(x, y)"], 0, "For every y there is an x who loves y."),
    ("'No one loves everyone' is equivalent to:",
     ["∀x ∃y ¬L(x, y)", "∃x ∀y ¬L(x, y)", "∀x ∀y ¬L(x, y)", "∃x ∃y L(x, y)"], 0, "¬∃x ∀y L(x, y) ≡ ∀x ∃y ¬L(x, y)."),
    ("The ε–δ definition of a limit has the quantifier pattern:",
     ["∃ε ∀δ ∃x", "∀ε ∃δ ∀x", "∀ε ∀δ ∀x", "∃ε ∃δ ∃x"], 1, "For every ε > 0 there exists δ > 0 such that for all x …"),
    ("Over the domain {1, 2}, ∀x ∃y P(x, y) is equivalent to:",
     ["(P(1,1) ∨ P(1,2)) ∧ (P(2,1) ∨ P(2,2))", "(P(1,1) ∧ P(1,2)) ∨ (P(2,1) ∧ P(2,2))", "P(1,1) ∧ P(2,2)", "P(1,2) ∨ P(2,1)"], 0,
     "∀ becomes a conjunction over x; ∃ becomes a disjunction over y."),
    ("Over the integers, ∀x ∃y (x = y²) is:",
     ["True", "False, e.g. x = 2 or any negative x", "True for x ≥ 0", "Undefined"], 1, "Not every integer is a perfect square."),
    ("Over the domain {1, 2, …, 10}, ∀x ∃y (x < y) is:",
     ["True", "False, because for x = 10 there is no larger y in the domain", "True for x < 5 only", "Undefined"], 1, "Over all integers the same statement is true."),
    ("Over the natural numbers {0, 1, 2, …}, ∃x ∀y (x ≤ y) is:",
     ["True (x = 0)", "False", "Undefined", "True only for y > 0"], 0, "Over all integers it would be false."),
    ("Over the integers, ∀x ∀y ∃z (z = (x + y)/2) is:",
     ["True", "False, e.g. x = 1, y = 2 gives 1.5", "True for even x only", "Undefined"], 1, "Over the real numbers it would be true."),
    ("Let Q(x, y) be 'x·y = 0' over the integers. ∃x ∀y Q(x, y) is:",
     ["True, with x = 0", "False", "Undefined", "True only for y = 0"], 0, "0 · y = 0 for every y."),
    ("The negation of ∃x ∀y (x + y ≠ 0) is:",
     ["∀x ∃y (x + y = 0)", "∃x ∃y (x + y = 0)", "∀x ∀y (x + y = 0)", "∃x ∀y (x + y = 0)"], 0, "Flip both quantifiers and negate the predicate."),
    ("'Every non-zero real number has a multiplicative inverse' is:",
     ["∀x (x ≠ 0 → ∃y (x·y = 1))", "∃y ∀x (x·y = 1)", "∀x ∃y (x·y = 1)", "∃x (x ≠ 0 ∧ ∀y (x·y = 1))"], 0, "The condition x ≠ 0 must restrict the universal quantifier."),
    ("Which implication is always valid?",
     ["∃x ∀y P(x, y) → ∀y ∃x P(x, y)", "∀y ∃x P(x, y) → ∃x ∀y P(x, y)", "∀x ∃y P → ∀x ∀y P", "∃x ∃y P → ∀x ∀y P"], 0,
     "If one x works for all y, then for each y that same x works. The reverse can fail."),
    ("Over the integers, ∀x ∃y (x + y = 5) is:",
     ["True, with y = 5 − x", "False", "Undefined", "True only for x = 0"], 0, "5 − x is always an integer."),
    ("Over the real numbers, ∃x ∃y (x² + y² = 0 ∧ x ≠ 0) is:",
     ["True", "False", "Undefined", "True for x = y"], 1, "x² + y² = 0 forces x = y = 0."),
    ("'Everyone has exactly one best friend' (B(x, y): y is the best friend of x) is:",
     ["∀x ∃y (B(x, y) ∧ ∀z ((z ≠ y) → ¬B(x, z)))", "∃x ∀y B(x, y)", "∀x ∀y B(x, y)", "∃y ∀x B(x, y)"], 0, "It combines existence and uniqueness for each x."),
    ("Evaluating ∀x ∀y P(x, y) over finite domains is analogous to:",
     ["A single loop", "Nested loops checking every pair (x, y) until a false case is found", "A recursive search for one pair", "Sorting"], 1,
     "∃ corresponds to searching until a true case is found."),
    ("Over the positive integers, ∃x ∀y (y is divisible by x) is:",
     ["True (x = 1)", "False", "Undefined", "True only for prime y"], 0, "Every integer is divisible by 1."),
    ("Over the integers, ∀x ∃y (y < x) is:",
     ["True", "False", "Undefined", "True only for positive x"], 0, "Choose y = x − 1."),
    ("Consider the statements:\nI. ∀x ∃y P(x, y) and ∃y ∀x P(x, y) are always equivalent.\nII. ∃x ∃y P(x, y) is equivalent to ∃y ∃x P(x, y).\nWhich is/are correct?",
     I_II, 1, "Mixed quantifiers cannot be swapped in general; quantifiers of the same kind can."),
    ("Assertion (A): ∀x ∃y (x + y = 0) is true over the integers.\nReason (R): For every integer x, −x is also an integer.",
     AR, 0, "Choosing y = −x works for every x."),
]

INFERENCE = [
    ("From p and p → q we conclude q. This rule is:",
     ["Modus tollens", "Modus ponens", "Hypothetical syllogism", "Disjunctive syllogism"], 1, "Modus ponens: (p ∧ (p → q)) → q."),
    ("From ¬q and p → q we conclude ¬p. This rule is:",
     ["Modus ponens", "Modus tollens", "Addition", "Resolution"], 1, "Modus tollens: (¬q ∧ (p → q)) → ¬p."),
    ("From p → q and q → r we conclude p → r. This rule is:",
     ["Hypothetical syllogism", "Disjunctive syllogism", "Simplification", "Conjunction"], 0, "Implications chain together."),
    ("From p ∨ q and ¬p we conclude q. This rule is:",
     ["Addition", "Disjunctive syllogism", "Modus ponens", "Resolution"], 1, "One disjunct is eliminated."),
    ("From p we conclude p ∨ q. This rule is:",
     ["Simplification", "Addition", "Conjunction", "Resolution"], 1, "Adding a disjunct keeps the statement true."),
    ("From p ∧ q we conclude p. This rule is:",
     ["Addition", "Simplification", "Conjunction", "Modus tollens"], 1, "A conjunct can be extracted."),
    ("From p ∨ q and ¬p ∨ r we conclude q ∨ r. This rule is:",
     ["Resolution", "Hypothetical syllogism", "Addition", "Simplification"], 0, "Resolution is the basis of automated theorem proving and Prolog."),
    ("The argument 'p → q, q, therefore p' is:",
     ["Valid (modus ponens)", "The fallacy of affirming the consequent", "Modus tollens", "Valid by resolution"], 1, "q may be true for other reasons."),
    ("The argument 'p → q, ¬p, therefore ¬q' is:",
     ["Valid", "The fallacy of denying the antecedent", "Modus tollens", "Disjunctive syllogism"], 1, "q might still be true even if p is false."),
    ("Concluding P(c) for a particular element c from ∀x P(x) is called:",
     ["Universal generalisation", "Universal instantiation", "Existential instantiation", "Existential generalisation"], 1, "Whatever holds for all holds for any particular one."),
    ("Concluding ∀x P(x) after proving P(c) for an arbitrary element c is called:",
     ["Universal generalisation", "Universal instantiation", "Existential generalisation", "Modus ponens"], 0, "c must be arbitrary, not a specific chosen element."),
    ("Concluding ∃x P(x) from P(c) for some particular c is called:",
     ["Existential instantiation", "Existential generalisation", "Universal instantiation", "Resolution"], 1, "One example proves existence."),
    ("From ∃x P(x), introducing a new element c with P(c) true is called:",
     ["Existential instantiation", "Universal generalisation", "Addition", "Existential generalisation"], 0, "c must be a new name, not one already used."),
    ("'All men are mortal. Socrates is a man. Therefore Socrates is mortal.' This uses:",
     ["Universal modus ponens", "Modus tollens", "Disjunctive syllogism", "Affirming the consequent"], 0, "∀x (M(x) → D(x)) and M(s) give D(s)."),
    ("'If it snows today, I will study. It snows today. Therefore I will study.' This is:",
     ["Modus tollens", "Modus ponens", "Addition", "Fallacy"], 1, "p → q, p ⊢ q."),
    ("'If you have the password you can log on. You cannot log on. Therefore you do not have the password.' This is:",
     ["Modus ponens", "Modus tollens", "Hypothetical syllogism", "Denying the antecedent"], 1, "p → q, ¬q ⊢ ¬p."),
    ("'It is below freezing now. Therefore it is below freezing or raining now.' This uses:",
     ["Simplification", "Addition", "Conjunction", "Resolution"], 1, "p ⊢ p ∨ q."),
    ("An argument is valid if:",
     ["All its premises are true", "Whenever all the premises are true, the conclusion must be true", "Its conclusion is true", "It has two premises"], 1,
     "Formally, (premises) → conclusion is a tautology."),
    ("A sound argument is one that is:",
     ["Valid with all premises actually true", "Invalid but convincing", "Valid with a false premise", "Any argument with a true conclusion"], 0, "Soundness = validity + true premises."),
    ("Resolving the clauses (p ∨ q) and (¬q ∨ r) gives:",
     ["p ∨ r", "p ∧ r", "q ∨ r", "¬p ∨ r"], 0, "q and ¬q cancel."),
    ("Resolving the clauses p and ¬p gives:",
     ["p", "The empty clause (a contradiction)", "T", "p ∨ ¬p"], 1, "Deriving the empty clause proves the clause set unsatisfiable."),
    ("From the premises p → q, ¬q ∨ r and ¬r, what can be concluded?",
     ["p", "¬p", "q", "r"], 1, "From ¬q ∨ r and ¬r we get ¬q (disjunctive syllogism); then p → q and ¬q give ¬p (modus tollens)."),
    ("Which argument form is INVALID?",
     ["p → q, q → r ⊢ p → r", "p ∨ q, ¬p ⊢ q", "p → q, q → r ⊢ r → p", "p ∧ q ⊢ p"], 2, "The first, second and fourth are hypothetical syllogism, disjunctive syllogism and simplification."),
    ("In a proof by contradiction of a statement S, we:",
     ["Assume S and derive S", "Assume ¬S and derive a contradiction", "Prove the converse", "Check one example"], 1, "If ¬S leads to a contradiction, S must be true."),
    ("A proof by contraposition of p → q proceeds by:",
     ["Assuming p and showing q", "Assuming ¬q and showing ¬p", "Assuming q and showing p", "Assuming p ∧ ¬q"], 1, "It proves the equivalent statement ¬q → ¬p."),
    ("A direct proof of p → q proceeds by:",
     ["Assuming ¬q", "Assuming p is true and showing q must be true", "Assuming ¬p", "Proving q → p"], 1, "This is the most straightforward proof method."),
    ("From p and q we conclude p ∧ q. This rule is:",
     ["Addition", "Conjunction", "Simplification", "Resolution"], 1, "Two established statements can be combined."),
    ("Premises: 'If I study, I pass', 'If I pass, I get a job'. Conclusion: 'If I study, I get a job'. The rule used is:",
     ["Modus ponens", "Hypothetical syllogism", "Disjunctive syllogism", "Addition"], 1, "p → q, q → r ⊢ p → r."),
    ("Consider the statements:\nI. A valid argument can have a false conclusion.\nII. A valid argument whose premises are all true must have a true conclusion.\nWhich is/are correct?",
     I_II, 2, "A valid argument with a false premise can have a false conclusion; validity guarantees truth only when premises are true."),
    ("Assertion (A): 'p → q, q ⊢ p' is a valid argument form.\nReason (R): 'p → q, p ⊢ q' is a valid argument form.",
     AR, 3, "A is the fallacy of affirming the consequent and is invalid; R is modus ponens and is valid."),
]

TOPICS = {
    "Propositional Logic": [("1 · Propositional Logic", PROP), ("2 · Propositional Equivalences", EQUIV), ("3 · Normal Forms", NORMAL)],
    "Predicate Logic & Rules of Inference": [("1 · Predicates and Quantifiers", PREDICATES), ("2 · Nested Quantifiers", NESTED),
                                             ("3 · Rules of Inference", INFERENCE)],
}
