"""Paper 2 · Unit 2 · topic U2-03 Sets and Relations (4 sub-topics × 30)."""
from packlib import AR, I_II

SETS = [
    ("If |A| = 4, how many elements does the power set P(A) have?",
     ["4", "8", "16", "24"], 2, "|P(A)| = 2^|A| = 2^4 = 16."),
    ("A = {1, 2, 3} and B = {2, 3, 4}. A ∩ B is:",
     ["{1, 4}", "{2, 3}", "{1, 2, 3, 4}", "{1}"], 1, "Elements common to both sets."),
    ("A = {1, 2, 3} and B = {2, 3, 4}. A − B is:",
     ["{1}", "{4}", "{2, 3}", "{1, 4}"], 0, "Elements of A that are not in B."),
    ("A = {1, 2, 3} and B = {2, 3, 4}. The symmetric difference A ⊕ B is:",
     ["{2, 3}", "{1, 4}", "{1, 2, 3, 4}", "∅"], 1, "Elements in exactly one of the sets: (A − B) ∪ (B − A)."),
    ("|A| = 20, |B| = 15 and |A ∩ B| = 5. What is |A ∪ B|?",
     ["35", "30", "25", "40"], 1, "|A ∪ B| = |A| + |B| − |A ∩ B| = 20 + 15 − 5 = 30."),
    ("If |A| = 3 and |B| = 4, how many elements does A × B have?",
     ["7", "12", "64", "81"], 1, "|A × B| = |A| · |B|."),
    ("When is A × B = B × A?",
     ["Always", "Only when A = B or one of the sets is empty", "Never", "Only when A and B are disjoint"], 1, "Ordered pairs (a, b) and (b, a) differ in general."),
    ("By De Morgan's law, the complement of A ∪ B equals:",
     ["A' ∪ B'", "A' ∩ B'", "A ∩ B", "A − B"], 1, "(A ∪ B)' = A' ∩ B' and (A ∩ B)' = A' ∪ B'."),
    ("How many elements does P(P(∅)) have?",
     ["0", "1", "2", "4"], 2, "P(∅) = {∅} has 1 element, so P(P(∅)) = {∅, {∅}} has 2."),
    ("Which statement is TRUE?",
     ["∅ ∈ ∅", "∅ ⊆ ∅", "∅ = {∅}", "{∅} ⊆ ∅"], 1, "The empty set is a subset of every set, including itself; it has no elements."),
    ("For A = {a, {a}}, which statement is correct?",
     ["{a} ∈ A only", "{a} ⊆ A only", "Both {a} ∈ A and {a} ⊆ A", "Neither"], 2, "{a} is listed as an element, and since a ∈ A, {a} is also a subset."),
    ("How many subsets with exactly 2 elements does a 5-element set have?",
     ["5", "10", "20", "32"], 1, "C(5, 2) = 10."),
    ("How many proper subsets does a set with 4 elements have?",
     ["16", "15", "14", "8"], 1, "All 16 subsets except the set itself."),
    ("By the absorption law, A ∪ (A ∩ B) equals:",
     ["B", "A", "A ∩ B", "A ∪ B"], 1, "Similarly A ∩ (A ∪ B) = A."),
    ("A − (B ∪ C) is equal to:",
     ["(A − B) ∪ (A − C)", "(A − B) ∩ (A − C)", "(A ∩ B) ∪ C", "A ∩ B ∩ C"], 1, "A − (B ∪ C) = A ∩ B' ∩ C'."),
    ("For any set A, A ⊕ A equals:",
     ["A", "∅", "U", "A'"], 1, "No element belongs to exactly one of the two copies."),
    ("In a group of 100 students, 60 like tea, 50 like coffee and 20 like both. How many like neither?",
     ["10", "20", "30", "0"], 0, "Tea or coffee = 60 + 50 − 20 = 90; neither = 100 − 90 = 10."),
    ("In the same group (60 tea, 50 coffee, 20 both), how many like only tea?",
     ["60", "40", "30", "20"], 1, "Only tea = 60 − 20 = 40."),
    ("Two sets A and B are disjoint if:",
     ["A ⊆ B", "A ∩ B = ∅", "A ∪ B = U", "A = B"], 1, "They have no elements in common."),
    ("How many elements does {x ∈ ℤ : x² < 10} have?",
     ["3", "6", "7", "9"], 2, "x ∈ {−3, −2, −1, 0, 1, 2, 3}."),
    ("Which of these sets is uncountable?",
     ["The natural numbers", "The integers", "The rational numbers", "The real numbers in the interval (0, 1)"], 3, "Cantor's diagonal argument shows the reals are uncountable."),
    ("Cantor's theorem states that for every set A:",
     ["|P(A)| = |A|", "|P(A)| > |A|", "|P(A)| < |A|", "P(A) is finite"], 1, "There is no surjection from A onto its power set."),
    ("With U = {1, 2, …, 10}, the bit-string representation of A = {1, 3, 5} (bit i for element i, left to right) is:",
     ["1010100000", "0000010101", "1110000000", "1010101010"], 0, "Bits 1, 3 and 5 are 1."),
    ("With the bit-string representation of subsets of a universal set, the union of two sets is computed by:",
     ["Bitwise AND", "Bitwise OR", "Bitwise XOR", "Bitwise NOT"], 1, "Intersection uses AND and symmetric difference uses XOR."),
    ("If |A| = 2, |B| = 3 and |C| = 4, then |A × B × C| is:",
     ["9", "24", "12", "10"], 1, "2 × 3 × 4 = 24."),
    ("Russell's paradox concerns:",
     ["The set of all sets that are not members of themselves", "The empty set", "Infinite sums", "Countable sets"], 0, "It showed that naive set theory is inconsistent."),
    ("How many subsets of {1, 2, 3, 4, 5} contain the element 1?",
     ["8", "16", "31", "32"], 1, "Fix 1; each of the other 4 elements is in or out: 2^4 = 16."),
    ("If A ⊆ B and B ⊆ A, then:",
     ["A ⊂ B", "A = B", "A ∩ B = ∅", "A ∪ B = ∅"], 1, "This is how set equality is usually proved."),
    ("Consider the statements:\nI. A − B = B − A for all sets A and B.\nII. A ⊕ B = (A − B) ∪ (B − A).\nWhich is/are correct?",
     I_II, 1, "Set difference is not commutative; statement II is the definition of symmetric difference."),
    ("Assertion (A): For every set A, ∅ ⊆ A.\nReason (R): For every set A, ∅ ∈ A.",
     AR, 2, "A is true (vacuously). R is false: e.g. ∅ ∉ {1, 2}."),
]

RELATIONS = [
    ("How many binary relations are there on a set with 3 elements?",
     ["9", "64", "512", "27"], 2, "A relation is any subset of A × A, which has 9 pairs: 2^9 = 512."),
    ("How many relations are there from A to B if |A| = 2 and |B| = 3?",
     ["6", "8", "64", "9"], 2, "Subsets of A × B (6 pairs): 2^6 = 64."),
    ("How many reflexive relations are there on a set with 4 elements?",
     ["2^16", "2^12", "2^10", "2^4"], 1, "The 4 diagonal pairs are fixed; the other 16 − 4 = 12 pairs are free: 2^(n² − n)."),
    ("How many symmetric relations are there on a set with 4 elements?",
     ["2^16", "2^10", "2^6", "2^8"], 1, "Choose the 4 diagonal pairs and the 6 unordered off-diagonal pairs: 2^(n(n+1)/2) = 2^10."),
    ("How many antisymmetric relations are there on a set with 3 elements?",
     ["64", "216", "512", "27"], 1, "2^n · 3^(n(n−1)/2) = 2^3 · 3^3 = 8 · 27 = 216."),
    ("How many relations on a 4-element set are both reflexive and symmetric?",
     ["2^6 = 64", "2^10", "2^12", "2^4"], 0, "Diagonal fixed; each of the 6 unordered pairs is in or out: 2^(n(n−1)/2)."),
    ("How many asymmetric relations are there on a set with 3 elements?",
     ["8", "27", "64", "216"], 1, "No diagonal pairs; for each of the 3 unordered pairs choose (a,b), (b,a) or neither: 3^3 = 27."),
    ("A relation is reflexive if and only if its matrix has:",
     ["All zeros", "All 1s on the main diagonal", "A symmetric pattern", "At least one 1 in each row"], 1, "Every element must be related to itself."),
    ("A relation is symmetric if and only if its matrix M satisfies:",
     ["M = Mᵀ", "M = I", "M has zero diagonal", "M² = M"], 0, "m_ij = m_ji for all i, j."),
    ("In the directed graph of a relation, reflexivity means:",
     ["No loops", "A loop at every vertex", "Every edge has a reverse edge", "No cycles"], 1, "Symmetry would mean every edge has a reverse edge."),
    ("On {1, 2, 3}, the relation R = {(1,1), (1,2), (2,1), (2,2), (3,3)} is:",
     ["Reflexive only", "Reflexive and symmetric but not transitive", "Reflexive, symmetric and transitive", "Antisymmetric"], 2, "It is the equivalence relation with classes {1, 2} and {3}."),
    ("On {1, 2, 3}, the relation R = {(1,2), (2,3)} is not transitive because:",
     ["(1,1) is missing", "(1,3) is missing", "(2,1) is missing", "(3,1) is missing"], 1, "(1,2) and (2,3) require (1,3)."),
    ("The relation '<' on the integers is:",
     ["Reflexive, symmetric and transitive", "Irreflexive, antisymmetric and transitive", "Symmetric only", "Reflexive and antisymmetric"], 1, "It is a strict order."),
    ("The relation 'divides' on the positive integers is:",
     ["An equivalence relation", "A partial order", "Symmetric", "Irreflexive"], 1, "It is reflexive, antisymmetric and transitive."),
    ("The relation 'divides' on all non-zero integers is NOT antisymmetric because:",
     ["2 does not divide 3", "1 | −1 and −1 | 1 but 1 ≠ −1", "It is not reflexive", "It is not transitive"], 1, "Antisymmetry fails for numbers that differ only in sign."),
    ("The empty relation on a non-empty set is:",
     ["Reflexive", "Symmetric, antisymmetric and transitive, but not reflexive", "An equivalence relation", "Not symmetric"], 1, "All conditions except reflexivity hold vacuously."),
    ("The transitive closure of R = {(1,2), (2,3)} on {1, 2, 3} is:",
     ["{(1,2), (2,3)}", "{(1,2), (2,3), (1,3)}", "{(1,2), (2,3), (3,1)}", "{(1,1), (2,2), (3,3)}"], 1, "Add (1,3); no further pairs are needed."),
    ("The reflexive closure of a relation R on A is:",
     ["R ∪ R⁻¹", "R ∪ Δ, where Δ = {(a, a) : a ∈ A}", "R ∩ Δ", "R ∘ R"], 1, "Add all missing loops."),
    ("The symmetric closure of a relation R is:",
     ["R ∪ R⁻¹", "R ∩ R⁻¹", "R ∘ R⁻¹", "R ∪ Δ"], 0, "Add the reverse of every pair."),
    ("R = {(1,2), (2,3)} and S = {(2,4), (3,5)}. The composite S ∘ R (first R, then S) is:",
     ["{(1,4), (2,5)}", "{(2,2), (3,3)}", "{(1,5)}", "{(4,1), (5,2)}"], 0, "1 →R 2 →S 4 and 2 →R 3 →S 5."),
    ("The inverse of R = {(1,2), (3,4)} is:",
     ["{(2,1), (4,3)}", "{(1,2), (3,4)}", "{(1,1), (2,2)}", "{(2,3)}"], 0, "Reverse each ordered pair."),
    ("Warshall's algorithm computes the transitive closure of a relation on n elements in:",
     ["O(n) time", "O(n log n) time", "O(n³) time", "O(2^n) time"], 2, "It uses three nested loops over the n × n matrix."),
    ("Can a relation be both symmetric and antisymmetric?",
     ["No, never", "Yes, e.g. the equality (identity) relation", "Only the universal relation", "Only on infinite sets"], 1, "Any subset of the diagonal is both."),
    ("On {1, 2, 3}, R = {(1,1), (2,2)} is:",
     ["Reflexive", "Irreflexive", "Neither reflexive nor irreflexive", "Both"], 2, "(3,3) is missing, so it is not reflexive; (1,1) is present, so it is not irreflexive."),
    ("How many 1s are there in the matrix of the identity relation on a 5-element set?",
     ["1", "5", "10", "25"], 1, "Only the diagonal entries are 1."),
    ("A relation R on A is transitive if and only if:",
     ["R ⊆ R ∘ R", "R ∘ R ⊆ R", "R = R⁻¹", "R ∩ R⁻¹ = ∅"], 1, "Whenever (a,b) and (b,c) are in R, (a,c) must be in R."),
    ("On the set of all people, the relation 'is the father of' is:",
     ["Reflexive", "Symmetric", "Transitive", "Irreflexive and asymmetric"], 3, "No one is their own father, and if a is b's father then b is not a's father; it is not transitive."),
    ("The relation {(a, b) : a + b is even} on the integers is:",
     ["Not reflexive", "An equivalence relation", "Antisymmetric", "Irreflexive"], 1, "a + b is even exactly when a and b have the same parity."),
    ("Consider the statements:\nI. Every asymmetric relation is antisymmetric.\nII. Every antisymmetric relation is asymmetric.\nWhich is/are correct?",
     I_II, 0, "Asymmetric relations have no loops; antisymmetric relations may have loops, e.g. ≤."),
    ("Assertion (A): The relation ≤ on the integers is antisymmetric.\nReason (R): If a ≤ b and b ≤ a, then a = b.",
     AR, 0, "R is exactly the definition of antisymmetry applied to ≤."),
]

EQUIVALENCE = [
    ("A relation is an equivalence relation if it is:",
     ["Reflexive, antisymmetric and transitive", "Reflexive, symmetric and transitive", "Symmetric only", "Irreflexive and transitive"], 1,
     "Reflexive, antisymmetric and transitive defines a partial order."),
    ("Congruence modulo 3 on the integers has how many equivalence classes?",
     ["1", "2", "3", "Infinitely many"], 2, "[0], [1] and [2]."),
    ("The equivalence class [2] under congruence modulo 5 is:",
     ["{2}", "{…, −8, −3, 2, 7, 12, …}", "{0, 5, 10, …}", "{2, 4, 6, …}"], 1, "All integers leaving remainder 2 when divided by 5."),
    ("The equivalence classes of an equivalence relation on A form a:",
     ["Chain", "Partition of A", "Lattice", "Power set of A"], 1, "They are non-empty, pairwise disjoint and cover A."),
    ("How many equivalence relations are there on a set with 3 elements?",
     ["3", "5", "8", "15"], 1, "It equals the Bell number B3 = 5 (the number of partitions)."),
    ("How many equivalence relations are there on a set with 4 elements?",
     ["12", "14", "15", "16"], 2, "The Bell number B4 = 15."),
    ("How many equivalence relations on a 4-element set have exactly 2 equivalence classes?",
     ["6", "7", "8", "4"], 1, "The Stirling number S(4, 2) = 2^(4−1) − 1 = 7."),
    ("The Bell number B5 (the number of partitions of a 5-element set) is:",
     ["42", "50", "52", "120"], 2, "B1..B5 = 1, 2, 5, 15, 52."),
    ("The relation 'has the same birthday as' on a set of people is:",
     ["Not reflexive", "An equivalence relation", "A partial order", "Antisymmetric"], 1, "People are grouped by birthday."),
    ("The relation 'x − y is even' on the integers has how many equivalence classes?",
     ["1", "2", "4", "Infinitely many"], 1, "Even integers and odd integers."),
    ("The largest (coarsest) equivalence relation on a set A is:",
     ["The identity relation", "A × A", "The empty relation", "The relation ≤"], 1, "It has only one class, A itself."),
    ("The smallest (finest) equivalence relation on a set A with n elements has how many classes?",
     ["1", "n", "2^n", "n²"], 1, "The identity relation puts every element in its own class."),
    ("An equivalence relation on a 5-element set has classes of sizes 2 and 3. How many ordered pairs does it contain?",
     ["5", "13", "25", "6"], 1, "Each class of size k contributes k² pairs: 2² + 3² = 4 + 9 = 13."),
    ("The equivalence relation on {1, 2, 3} corresponding to the partition {{1, 2}, {3}} contains how many ordered pairs?",
     ["3", "4", "5", "6"], 2, "(1,1), (1,2), (2,1), (2,2) and (3,3)."),
    ("Which statement is correct?",
     ["The union of two equivalence relations is always an equivalence relation", "The intersection of two equivalence relations is always an equivalence relation",
      "The complement of an equivalence relation is an equivalence relation", "The composition of equivalence relations is never an equivalence relation"], 1,
     "Reflexivity, symmetry and transitivity are preserved by intersection; the union may fail transitivity."),
    ("Is the relation ≤ on the integers an equivalence relation?",
     ["Yes", "No, because it is not symmetric", "No, because it is not reflexive", "No, because it is not transitive"], 1, "2 ≤ 3 but 3 ≰ 2."),
    ("On the set of all strings, the relation 'has the same length as' is:",
     ["A partial order", "An equivalence relation whose classes correspond to lengths", "Not reflexive", "Antisymmetric"], 1, "Each class contains all strings of one length."),
    ("For a function f : A → B, the relation x ~ y ⇔ f(x) = f(y) is:",
     ["Always an equivalence relation", "A partial order", "Never symmetric", "Only reflexive"], 0, "It is called the kernel of f."),
    ("Is 17 ≡ 5 (mod 6)?",
     ["Yes, because 6 divides 17 − 5 = 12", "No", "Only modulo 12", "Undefined"], 0, "a ≡ b (mod m) means m | (a − b)."),
    ("Which relation on the set of lines in a plane is NOT an equivalence relation?",
     ["'Is parallel to or equal to'", "'Is perpendicular to'", "'Has the same slope as'", "'Is equal to'"], 1, "Perpendicularity is not reflexive or transitive."),
    ("The set of all equivalence classes of A under R, written A/R, is called the:",
     ["Power set", "Quotient set", "Cartesian product", "Closure"], 1, "It is also called the factor set."),
    ("Which statement about equivalence classes [a] and [b] is correct?",
     ["They can overlap partially", "They are either identical or disjoint", "They are always disjoint", "They are always identical"], 1, "This is why the classes form a partition."),
    ("R = {(1,1), (2,2), (3,3), (4,4), (1,3), (3,1)} on {1, 2, 3, 4} has how many equivalence classes?",
     ["2", "3", "4", "1"], 1, "{1, 3}, {2} and {4}."),
    ("What is the minimum number of ordered pairs that must be added to R = {(1,2)} on {1, 2, 3} to make it an equivalence relation?",
     ["2", "3", "4", "5"], 2, "Add (1,1), (2,2), (3,3) and (2,1); transitivity then holds."),
    ("The relation x ~ y ⇔ x² = y² on the integers is an equivalence relation. The class of 3 is:",
     ["{3}", "{−3, 3}", "{9}", "{0, 3}"], 1, "Numbers with the same square."),
    ("Congruence modulo m partitions the integers into how many classes?",
     ["m − 1", "m", "m + 1", "2m"], 1, "The residues 0, 1, …, m − 1."),
    ("The relation 'is a sibling of' (a person is not their own sibling) is not an equivalence relation mainly because it is:",
     ["Not symmetric", "Not reflexive", "Antisymmetric", "Not defined"], 1, "No one is their own sibling (and transitivity can fail too)."),
    ("Given the partition {{a}, {b, c, d}} of {a, b, c, d}, the class [c] is:",
     ["{c}", "{b, c, d}", "{a}", "{a, b, c, d}"], 1, "c belongs to the block {b, c, d}."),
    ("Consider the statements:\nI. The union of two equivalence relations on A is always an equivalence relation.\nII. The intersection of two equivalence relations on A is always an equivalence relation.\nWhich is/are correct?",
     I_II, 1, "Union can break transitivity: {(1,2),(2,1)} ∪ {(2,3),(3,2)} plus loops lacks (1,3)."),
    ("Assertion (A): Congruence modulo n is an equivalence relation on ℤ.\nReason (R): n | (a − a); if n | (a − b) then n | (b − a); and if n | (a − b) and n | (b − c) then n | (a − c).",
     AR, 0, "R verifies reflexivity, symmetry and transitivity."),
]

POSETS = [
    ("A partial order is a relation that is:",
     ["Reflexive, symmetric and transitive", "Reflexive, antisymmetric and transitive", "Irreflexive and symmetric", "Symmetric and transitive only"], 1, "A set with a partial order is a poset."),
    ("Why is (ℤ⁺, |) not a totally ordered set?",
     ["Divisibility is not reflexive", "Some elements, such as 2 and 3, are incomparable", "It is not transitive", "It is symmetric"], 1, "Neither 2 | 3 nor 3 | 2."),
    ("A Hasse diagram of a finite poset omits:",
     ["All edges", "Loops, edges implied by transitivity, and arrow directions (drawn upward)", "The minimal elements", "Incomparable elements"], 1, "Only covering relations are drawn."),
    ("In the poset ({1, 2, 3, 4, 6, 12}, |), the greatest element is:",
     ["1", "6", "12", "There is none"], 2, "Every element divides 12."),
    ("In the poset ({2, 3, 4, 6, 8, 12}, |), the minimal elements are:",
     ["2 only", "2 and 3", "3 only", "2, 3 and 4"], 1, "No other element of the set divides 2 or 3."),
    ("In the poset ({2, 3, 4, 6, 8, 12}, |), the maximal elements are:",
     ["12 only", "8 and 12", "6 and 8", "4, 6 and 8"], 1, "Neither 8 nor 12 divides another element of the set."),
    ("In the poset of divisors of 12 under |, the least upper bound of {2, 3} is:",
     ["1", "6", "12", "4"], 1, "Upper bounds are 6 and 12; the least is lcm(2, 3) = 6."),
    ("In the lattice of divisors of n under divisibility, the meet (GLB) and join (LUB) of a and b are:",
     ["lcm and gcd", "gcd and lcm", "a + b and a × b", "min and max always"], 1, "a ∧ b = gcd(a, b) and a ∨ b = lcm(a, b)."),
    ("In the lattice (P(S), ⊆), the join and meet of A and B are:",
     ["A ∩ B and A ∪ B", "A ∪ B and A ∩ B", "A − B and B − A", "A ⊕ B and A × B"], 1, "The union is the least upper bound; the intersection is the greatest lower bound."),
    ("Which of these is well-ordered under the usual ≤?",
     ["(ℤ, ≤)", "(ℕ, ≤)", "(ℚ⁺, ≤)", "(ℝ, ≤)"], 1, "Every non-empty set of natural numbers has a least element."),
    ("A topological sort of a finite poset produces:",
     ["A partition", "A total order compatible with the partial order", "The transitive closure", "A lattice"], 1, "It is used for scheduling tasks with dependencies."),
    ("In lexicographic order on ℤ × ℤ, which is true?",
     ["(2, 1) < (1, 5)", "(1, 5) < (2, 1)", "(1, 5) and (2, 1) are incomparable", "(1, 5) = (2, 1)"], 1, "Compare first components first: 1 < 2."),
    ("How many edges does the Hasse diagram of the divisors of 12 under | have?",
     ["6", "7", "8", "12"], 1, "Covering pairs: 1–2, 1–3, 2–4, 2–6, 3–6, 4–12, 6–12."),
    ("The Hasse diagram of (P({a, b, c}), ⊆) has how many vertices and edges?",
     ["8 vertices, 12 edges", "8 vertices, 8 edges", "6 vertices, 12 edges", "8 vertices, 28 edges"], 0, "It is drawn as a cube."),
    ("In (P({a, b, c}), ⊆), the largest antichain has size:",
     ["1", "2", "3", "4"], 2, "The 1-element (or 2-element) subsets form an antichain of size C(3, 1) = 3 (Sperner's theorem)."),
    ("Which statement about a greatest element of a poset is correct?",
     ["A poset can have several greatest elements", "If it exists, it is unique", "Every poset has one", "It is always minimal"], 1, "Maximal elements, however, need not be unique."),
    ("Is the relation < on ℤ a partial order?",
     ["Yes", "No, because it is not reflexive (it is a strict order)", "No, because it is not transitive", "No, because it is symmetric"], 1, "A partial order must be reflexive."),
    ("In the lattice of divisors of 30, the complement of 2 is:",
     ["3", "5", "15", "30"], 2, "gcd(2, 15) = 1 and lcm(2, 15) = 30."),
    ("In the lattice of divisors of 12, the element 2:",
     ["Has complement 6", "Has complement 3", "Has no complement", "Has complement 12"], 2,
     "A complement c needs gcd(2, c) = 1 and lcm(2, c) = 12; c would have to be 1 or 3, but lcm(2, 3) = 6 ≠ 12."),
    ("Which of the following is a non-distributive lattice?",
     ["The divisors of 30", "The power set of {a, b}", "The diamond lattice M3", "A chain of 4 elements"], 2, "M3 (diamond) and N5 (pentagon) are the classic non-distributive lattices."),
    ("A bounded lattice has:",
     ["No elements", "A least element 0 and a greatest element 1", "Only two elements", "No meets"], 1, "Every finite lattice is bounded."),
    ("How many total orders (linear extensions) are compatible with a 3-element antichain?",
     ["1", "3", "6", "9"], 2, "Any ordering works: 3! = 6."),
    ("Tasks: A before B, A before C, B before D, C before D. Which order is a valid topological sort?",
     ["A, B, C, D", "B, A, C, D", "A, D, B, C", "D, C, B, A"], 0, "A must come first and D last."),
    ("The Hasse diagram of ({1, 2, 3}, ≤) has how many edges?",
     ["2", "3", "6", "1"], 0, "It is a chain 1 – 2 – 3; the edge 1–3 is implied by transitivity."),
    ("In the poset ({1, 2, 3, 5, 30}, |), the least upper bound of {2, 3} is:",
     ["6", "30", "5", "It does not exist"], 1, "6 is not in the set; the only upper bound is 30."),
    ("Two elements a and b of a poset are comparable if:",
     ["a = b only", "a ≼ b or b ≼ a", "Neither a ≼ b nor b ≼ a", "They are both minimal"], 1, "In a total order, every pair is comparable."),
    ("In the poset ({1, 2, 4, 8}, |), the set is:",
     ["An antichain", "A chain (totally ordered)", "Not a poset", "A non-distributive lattice"], 1, "1 | 2 | 4 | 8."),
    ("Every non-empty finite subset of a lattice has:",
     ["No upper bound", "A least upper bound and a greatest lower bound", "Only minimal elements", "Exactly one element"], 1, "This follows by repeatedly applying join and meet."),
    ("Consider the statements:\nI. Every finite non-empty poset has at least one minimal element.\nII. Every finite non-empty poset has a least element.\nWhich is/are correct?",
     I_II, 0, "An antichain has every element minimal but no least element."),
    ("Assertion (A): (ℤ, ≤) is a well-ordered set.\nReason (R): (ℕ, ≤) is a well-ordered set.",
     AR, 3, "A is false: the negative integers have no least element. R is true."),
]

TOPICS = {"Sets and Relations": [("1 · Set Operations", SETS), ("2 · Relations: Representation and Properties", RELATIONS),
                                 ("3 · Equivalence Relations", EQUIVALENCE), ("4 · Partial Ordering", POSETS)]}
