"""Paper 2 · Unit 2 · topics U2-08 Trees and U2-09 Boolean Algebra (6 sub-topics × 30)."""
from packlib import AR, I_II

TREES = [
    ("A tree is a graph that is:",
     ["Connected and acyclic", "Complete", "Bipartite and complete", "Connected with exactly one cycle"], 0, "Equivalently, there is a unique path between any two vertices."),
    ("How many edges does a tree with 20 vertices have?",
     ["20", "19", "21", "40"], 1, "A tree with n vertices has n − 1 edges."),
    ("In a tree, between any two vertices there is:",
     ["No path", "Exactly one path", "At least two paths", "A cycle"], 1, "A second path would create a cycle."),
    ("A forest with n vertices and c components (trees) has how many edges?",
     ["n − 1", "n − c", "n + c", "c − 1"], 1, "Each tree contributes (its vertices − 1)."),
    ("Every tree with at least 2 vertices has at least:",
     ["1 leaf", "2 leaves", "3 leaves", "n/2 leaves"], 1, "The two ends of a longest path are leaves."),
    ("A full m-ary tree with i internal vertices has how many vertices in total?",
     ["mi", "mi + 1", "(m − 1)i + 1", "m + i"], 1, "Each internal vertex has m children, plus the root."),
    ("A full binary tree has 10 internal vertices. How many leaves and total vertices does it have?",
     ["10 leaves, 20 vertices", "11 leaves, 21 vertices", "9 leaves, 19 vertices", "20 leaves, 30 vertices"], 1, "l = (m − 1)i + 1 = 11 and n = mi + 1 = 21."),
    ("A full 3-ary tree has 101 leaves. How many internal vertices and total vertices does it have?",
     ["50 internal, 151 total", "33 internal, 134 total", "100 internal, 201 total", "51 internal, 152 total"], 0, "101 = 2i + 1 gives i = 50; n = 3 × 50 + 1 = 151."),
    ("What is the maximum number of leaves in an m-ary tree of height h?",
     ["m × h", "m^h", "h^m", "2^h"], 1, "Each level multiplies the number of nodes by at most m."),
    ("With the root at height 0, what is the maximum number of nodes in a binary tree of height 4?",
     ["15", "16", "31", "32"], 2, "2^(h+1) − 1 = 2^5 − 1 = 31."),
    ("With height measured in edges, what is the minimum possible height of a binary tree with 100 nodes?",
     ["5", "6", "7", "50"], 1, "We need 2^(h+1) − 1 ≥ 100, so h + 1 ≥ 7 and h = 6."),
    ("By Cayley's formula, how many labelled trees are there on 5 vertices?",
     ["25", "60", "125", "625"], 2, "n^(n−2) = 5³ = 125."),
    ("How many labelled trees are there on 4 vertices?",
     ["4", "12", "16", "64"], 2, "4² = 16."),
    ("How many structurally different (unlabelled, ordered) binary trees have 3 nodes?",
     ["3", "5", "6", "8"], 1, "The Catalan number C₃ = 5."),
    ("In a rooted tree, vertices with the same parent are called:",
     ["Ancestors", "Siblings", "Descendants", "Leaves"], 1, "Ancestors lie on the path from the root."),
    ("In a rooted tree, the level of the root is usually:",
     ["0", "1", "−1", "The height"], 0, "Each child is one level below its parent."),
    ("A vertex with no children in a rooted tree is called a:",
     ["Root", "Internal vertex", "Leaf", "Ancestor"], 2, "Vertices with children are internal."),
    ("A binary tree with n nodes has how many null (empty) child links?",
     ["n", "n − 1", "n + 1", "2n"], 2, "2n links in total, of which n − 1 are used by edges."),
    ("In any binary tree, the number of leaves n₀ and the number of nodes with two children n₂ satisfy:",
     ["n₀ = n₂", "n₀ = n₂ + 1", "n₀ = 2n₂", "n₀ = n₂ − 1"], 1, "This follows from counting edges."),
    ("A binary tree has 20 nodes with two children. How many leaves does it have?",
     ["19", "20", "21", "40"], 2, "n₀ = n₂ + 1 = 21."),
    ("Adding one new edge between two existing vertices of a tree creates:",
     ["No cycle", "Exactly one cycle", "Two cycles", "A disconnected graph"], 1, "The new edge plus the unique existing path form one cycle."),
    ("Removing any edge from a tree:",
     ["Creates a cycle", "Disconnects the tree into exactly two components", "Leaves it connected", "Removes a vertex"], 1, "Every edge of a tree is a bridge."),
    ("The centre of a tree (the vertices of minimum eccentricity) consists of:",
     ["Exactly one vertex", "One or two vertices", "All leaves", "At least three vertices"], 1, "Repeatedly removing leaves leaves one or two central vertices."),
    ("The sum of the degrees of all vertices of a tree with n vertices is:",
     ["n", "n − 1", "2(n − 1)", "2n"], 2, "Twice the number of edges."),
    ("A tree has 3 vertices of degree 3 and all other vertices are leaves. How many leaves are there?",
     ["3", "4", "5", "6"], 2, "With L leaves, n = 3 + L and 9 + L = 2(n − 1) = 4 + 2L, so L = 5."),
    ("An ordered rooted tree is one in which:",
     ["The vertices are numbered", "The children of each internal vertex are ordered (left to right)", "The height is minimal", "All leaves are at the same level"], 1,
     "Binary trees distinguish left and right children."),
    ("An m-ary tree of height h is 'balanced' if all its leaves are at levels:",
     ["0 only", "h or h − 1", "h only", "1 to h"], 1, "Balanced trees keep the height close to log_m(leaves)."),
    ("A subtree rooted at vertex v consists of:",
     ["v only", "v and all its descendants with the connecting edges", "v and its ancestors", "The whole tree"], 1, "Recursive tree algorithms work on subtrees."),
    ("Consider the statements:\nI. Every tree is a bipartite graph.\nII. Every connected graph with n vertices and n − 1 edges is a tree.\nWhich is/are correct?",
     I_II, 2, "Trees have no cycles (hence no odd cycles), and connectivity with n − 1 edges forces acyclicity."),
    ("Assertion (A): A tree with n vertices has exactly n − 1 edges.\nReason (R): A tree is connected and has no cycles.",
     AR, 0, "Connectivity needs at least n − 1 edges; acyclicity allows at most n − 1."),
]

PREFIX = [
    ("A prefix code is a code in which:",
     ["All codewords have the same length", "No codeword is a prefix of another codeword", "Every codeword starts with 0", "Codewords are sorted"], 1,
     "This allows instantaneous, unambiguous decoding."),
    ("Which of these is a prefix code?",
     ["{0, 01, 11}", "{0, 10, 110, 111}", "{1, 10, 100}", "{00, 0, 11}"], 1, "In the others, some codeword begins another (0 and 01; 1 and 10; 0 and 00)."),
    ("Why is {0, 01, 11} NOT a prefix code?",
     ["It has three codewords", "0 is a prefix of 01", "11 is too long", "It contains 1"], 1, "Seeing 0, the decoder cannot tell whether the symbol has ended."),
    ("Prefix codes can be represented by binary trees in which codewords correspond to:",
     ["Internal nodes", "Leaves", "The root", "Edges only"], 1, "The path from the root (0 = left, 1 = right) spells the codeword."),
    ("With the code a = 0, b = 10, c = 110, d = 111, the bit string 11010 decodes to:",
     ["cb", "da", "bca", "cab"], 0, "110 → c and 10 → b."),
    ("With the code a = 0, b = 10, c = 110, d = 111, the word 'bad' is encoded as:",
     ["100111", "010111", "1001110", "10111"], 0, "b = 10, a = 0, d = 111."),
    ("Huffman's algorithm builds an optimal prefix code by repeatedly:",
     ["Merging the two most frequent symbols", "Merging the two least frequent (lowest-weight) trees", "Assigning codes alphabetically", "Splitting the largest group"], 1,
     "It is a greedy algorithm."),
    ("Symbols a, b, c, d have frequencies 0.4, 0.3, 0.2 and 0.1. What is the average codeword length of the Huffman code?",
     ["1.9 bits", "2.0 bits", "1.7 bits", "2.1 bits"], 0, "Code lengths are 1, 2, 3 and 3: 0.4 + 0.6 + 0.6 + 0.3 = 1.9."),
    ("In the previous example (average 1.9 bits), how many bits per symbol are saved compared with a fixed-length code?",
     ["0.1", "0.5", "1", "0"], 0, "A fixed-length code for 4 symbols needs 2 bits."),
    ("The Kraft inequality for a binary prefix code with codeword lengths l₁, …, lₙ states that:",
     ["Σ 2^(−lᵢ) ≤ 1", "Σ lᵢ ≤ n", "Σ 2^(lᵢ) ≤ 1", "Π lᵢ ≤ 2"], 0, "Such a code exists exactly when this holds."),
    ("Can a binary prefix code have codeword lengths {1, 2, 2, 2}?",
     ["Yes", "No, because 1/2 + 3/4 > 1", "Only if symbols are equally likely", "Only for 3 symbols"], 1, "The Kraft sum is 1.25."),
    ("Can a binary prefix code have codeword lengths {1, 2, 3, 3}?",
     ["Yes, e.g. 0, 10, 110, 111", "No", "Only with lengths sorted differently", "Only if all symbols are equally likely"], 0, "The Kraft sum is exactly 1."),
    ("The tree built by Huffman's algorithm is always a:",
     ["Full binary tree", "Balanced tree", "Binary search tree", "Complete graph"], 0, "Every internal node has exactly two children."),
    ("A Huffman tree for n symbols has how many internal nodes?",
     ["n", "n − 1", "n + 1", "2n"], 1, "Each merge creates one internal node, and there are n − 1 merges."),
    ("If 8 symbols are equally likely, the Huffman code assigns each symbol:",
     ["1 bit", "2 bits", "3 bits", "Different lengths"], 2, "It reduces to a fixed-length 3-bit code."),
    ("Huffman's algorithm using a priority queue (min-heap) runs in:",
     ["O(n)", "O(n log n)", "O(n²)", "O(2^n)"], 1, "n − 1 merges, each with O(log n) heap operations."),
    ("The main advantage of a prefix code is that:",
     ["It always uses the fewest bits possible for every message", "It can be decoded instantaneously and unambiguously without separators", "All codewords are equal", "It encrypts data"], 1,
     "The decoder recognises a codeword as soon as it ends."),
    ("Morse code is NOT a prefix code, which is why it needs:",
     ["Colours", "Pauses (gaps) between letters", "Parity bits", "Capital letters"], 1, "For example, E (·) is a prefix of I (··)."),
    ("For frequencies (in thousands) a 45, b 13, c 12, d 16, e 9, f 5, the Huffman code needs how many bits per 100 characters?",
     ["300", "224", "250", "200"], 1, "Lengths: a 1, b/c/d 3, e/f 4: 45 + 3 × 41 + 4 × 14 = 224 (a fixed 3-bit code needs 300)."),
    ("In the same example, the first two frequencies merged by Huffman's algorithm are:",
     ["45 and 16", "5 and 9", "12 and 13", "9 and 12"], 1, "The two smallest weights are merged first, giving 14."),
    ("In a Huffman tree, the length of a symbol's codeword equals:",
     ["Its frequency", "The depth of its leaf", "The number of symbols", "The tree height always"], 1, "Each edge from the root adds one bit."),
    ("Which of these codes is NOT a prefix code?",
     ["{00, 01, 10, 11}", "{1, 10, 100}", "{0, 10, 11}", "{11, 10, 0}"], 1, "1 is a prefix of 10 and of 100."),
    ("The code {0, 01} is:",
     ["A prefix code", "Uniquely decodable but not a prefix code", "Not uniquely decodable", "A fixed-length code"], 1,
     "No codeword is a suffix of another, so decoding from the end is unique, but 0 is a prefix of 01."),
    ("For 5 equally likely symbols, the Huffman code has average length:",
     ["2 bits", "2.4 bits", "3 bits", "2.32 bits"], 1, "Lengths 2, 2, 2, 3, 3 give 12/5 = 2.4 bits."),
    ("ASCII is a fixed-length code. Every fixed-length code is:",
     ["Not decodable", "A prefix code", "Optimal for all texts", "Variable-length"], 1, "Codewords of equal length cannot be prefixes of each other."),
    ("Huffman coding is a lossless compression method used, for example, in:",
     ["JPEG and DEFLATE (ZIP) as an entropy-coding stage", "Only audio streaming", "Encrypting passwords", "Error correction only"], 0, "It encodes frequent symbols with shorter codes."),
    ("A symbol with a higher frequency in a Huffman code typically gets:",
     ["A longer codeword", "A shorter (or equal) codeword", "No codeword", "A codeword of fixed length 8"], 1, "This is what makes the average length small."),
    ("In a binary code tree, following the path root → left → right → right gives the codeword (0 = left, 1 = right):",
     ["011", "100", "010", "110"], 0, "Left = 0, right = 1, right = 1."),
    ("Consider the statements:\nI. Every prefix code is uniquely decodable.\nII. Every uniquely decodable code is a prefix code.\nWhich is/are correct?",
     I_II, 0, "{0, 01} is uniquely decodable but not a prefix code."),
    ("Assertion (A): Huffman coding produces an optimal prefix code for given symbol frequencies.\nReason (R): Huffman's algorithm always merges the two most frequent symbols first.",
     AR, 2, "A is true, but R is false: it merges the two least frequent trees first."),
]

TRAVERSALS = [
    ("Preorder traversal of a binary tree visits nodes in the order:",
     ["Left, root, right", "Root, left, right", "Left, right, root", "Level by level"], 1, "Inorder is left-root-right; postorder is left-right-root."),
    ("Inorder traversal of a binary tree visits nodes in the order:",
     ["Root, left, right", "Left, root, right", "Left, right, root", "Right, root, left"], 1, "For a BST it gives sorted order."),
    ("Postorder traversal of a binary tree visits nodes in the order:",
     ["Root, left, right", "Left, root, right", "Left, right, root", "Level by level"], 2, "The root is visited last."),
    ("The inorder traversal of a binary search tree produces the keys in:",
     ["Random order", "Ascending (sorted) order", "Descending order", "Insertion order"], 1, "Smaller keys are in the left subtree."),
    ("Tree: root A; A's left child B (with children D and E); A's right child C (with only a right child F). The preorder traversal is:",
     ["A B D E C F", "D B E A C F", "D E B F C A", "A B C D E F"], 0, "Root first, then the left subtree, then the right subtree."),
    ("For the same tree (A; B with D, E; C with right child F), the inorder traversal is:",
     ["D B E A C F", "A B D E C F", "D E B F C A", "B D E A F C"], 0, "C has no left child, so C comes before F."),
    ("For the same tree, the postorder traversal is:",
     ["D E B F C A", "D B E A C F", "A B D E C F", "F C E D B A"], 0, "Children before parents."),
    ("For the same tree, the level-order (breadth-first) traversal is:",
     ["A B C D E F", "A B D E C F", "D E F B C A", "A C B F E D"], 0, "Visit level 0, then level 1, then level 2."),
    ("For the expression (a + b) * c, the preorder traversal of its expression tree gives the prefix form:",
     ["* + a b c", "a b + c *", "+ a * b c", "a + b * c"], 0, "The operator at the root comes first."),
    ("For the expression (a + b) * c, the postorder traversal gives the postfix form:",
     ["a b + c *", "* + a b c", "a b c + *", "a + b c *"], 0, "Operands first, operator after."),
    ("Evaluate the postfix expression 2 3 4 * +.",
     ["20", "14", "24", "9"], 1, "3 × 4 = 12, then 2 + 12 = 14."),
    ("Evaluate the prefix expression * + 2 3 4.",
     ["14", "20", "24", "10"], 1, "(2 + 3) × 4 = 20."),
    ("Evaluate the postfix expression 5 1 2 + 4 * + 3 −.",
     ["14", "18", "15", "20"], 0, "1 + 2 = 3; 3 × 4 = 12; 5 + 12 = 17; 17 − 3 = 14."),
    ("The postfix form of the infix expression A + B * C is:",
     ["A B + C *", "A B C * +", "+ A * B C", "A B C + *"], 1, "* has higher precedence, so B C * is evaluated first."),
    ("The postfix form of (A + B) * (C − D) is:",
     ["A B + C D − *", "A B C D + − *", "* + A B − C D", "A + B C D − *"], 0, "Each parenthesised part becomes postfix, then *."),
    ("The prefix form of (A + B) * C is:",
     ["* + A B C", "+ A * B C", "A B + C *", "* A + B C"], 0, "Operator before operands."),
    ("Which pair of traversals always determines a binary tree uniquely (assuming distinct labels)?",
     ["Preorder and postorder", "Inorder and preorder", "Only preorder", "Only level order"], 1, "Preorder and postorder together can be ambiguous when a node has one child."),
    ("Preorder: A B D C E; inorder: D B A E C. What is the postorder traversal?",
     ["D B E C A", "D B C E A", "B D E C A", "D E B C A"], 0, "A is the root; left subtree {D, B} with root B; right subtree {E, C} with root C and left child E."),
    ("Level-order traversal of a tree is implemented using a:",
     ["Stack", "Queue", "Heap", "Hash table"], 1, "Depth-first traversals use a stack (or recursion)."),
    ("What is the time complexity of any standard traversal of a binary tree with n nodes?",
     ["O(log n)", "O(n)", "O(n log n)", "O(n²)"], 1, "Each node is visited once."),
    ("Which traversal is used to delete (free) all nodes of a tree safely?",
     ["Preorder", "Inorder", "Postorder", "Level order only"], 2, "Children are freed before their parent."),
    ("Which traversal is used to copy a tree or print it as a prefix expression?",
     ["Preorder", "Inorder", "Postorder", "Reverse inorder"], 0, "The parent is created before its children."),
    ("A BST is built by inserting 50, 30, 70, 20, 40 in that order. Its preorder traversal is:",
     ["50 30 20 40 70", "20 30 40 50 70", "20 40 30 70 50", "50 70 30 40 20"], 0, "Root 50, then subtree 30 (20, 40), then 70."),
    ("For the same BST (50, 30, 70, 20, 40), the postorder traversal is:",
     ["20 40 30 70 50", "50 30 20 40 70", "20 30 40 50 70", "40 20 30 70 50"], 0, "Left subtree (20 40 30), right subtree (70), root 50."),
    ("For the same BST (50, 30, 70, 20, 40), the inorder traversal is:",
     ["50 30 20 40 70", "20 30 40 50 70", "20 40 30 70 50", "70 50 40 30 20"], 1, "Sorted order."),
    ("A threaded binary tree uses otherwise-null child pointers to store:",
     ["Parent pointers only", "Links to inorder predecessors/successors", "Subtree sizes", "Colours"], 1, "This allows traversal without a stack."),
    ("Prefix and postfix (Polish) notations have the advantage that:",
     ["They need parentheses", "They need no parentheses to express the order of evaluation", "They are easier to read for humans", "They work only for addition"], 1,
     "They were introduced by Jan Łukasiewicz."),
    ("A postfix expression is most naturally evaluated using a:",
     ["Queue", "Stack", "Linked list", "Tree only"], 1, "Operands are pushed; an operator pops its operands and pushes the result."),
    ("Consider the statements:\nI. Inorder and preorder traversals together determine a binary tree with distinct labels uniquely.\nII. Preorder and postorder traversals together always determine a binary tree uniquely.\nWhich is/are correct?",
     I_II, 0, "A root with only a left child and a root with only a right child have the same preorder and postorder."),
    ("Assertion (A): The inorder traversal of a binary search tree lists its keys in ascending order.\nReason (R): In a BST, all keys in the left subtree are smaller than the root and all keys in the right subtree are larger.",
     AR, 0, "Visiting left, then root, then right respects that ordering at every node."),
]

SPANNING = [
    ("A spanning tree of a connected graph G is:",
     ["Any tree in G", "A subgraph that is a tree and contains every vertex of G", "A cycle through all vertices", "The complement of G"], 1, "It keeps all vertices and just enough edges."),
    ("Which graphs have a spanning tree?",
     ["All graphs", "Exactly the connected graphs", "Only complete graphs", "Only planar graphs"], 1, "A disconnected graph has a spanning forest instead."),
    ("A spanning tree of a connected graph with n vertices has how many edges?",
     ["n", "n − 1", "n + 1", "It depends on the graph"], 1, "It is a tree on n vertices."),
    ("How many spanning trees does K4 have?",
     ["4", "8", "16", "64"], 2, "Cayley's formula: n^(n−2) = 4² = 16."),
    ("How many spanning trees does K5 have?",
     ["25", "60", "125", "625"], 2, "5³ = 125."),
    ("How many spanning trees does the cycle Cₙ have?",
     ["1", "n", "n − 1", "2^n"], 1, "Remove any one of its n edges."),
    ("How many spanning trees does K2,3 have?",
     ["6", "12", "9", "18"], 1, "For Km,n: m^(n−1) × n^(m−1) = 2² × 3¹ = 12."),
    ("Kirchhoff's matrix-tree theorem counts spanning trees using:",
     ["The adjacency list", "Any cofactor of the Laplacian matrix", "The incidence matrix only", "The distance matrix"], 1, "Laplacian = degree matrix − adjacency matrix."),
    ("Kruskal's algorithm builds a minimum spanning tree by:",
     ["Growing a tree from a start vertex", "Adding edges in increasing order of weight, skipping any edge that forms a cycle", "Removing the heaviest edge repeatedly", "Using BFS"], 1,
     "It uses a union–find structure; O(E log E)."),
    ("Prim's algorithm builds a minimum spanning tree by:",
     ["Sorting all edges first", "Growing one tree from a start vertex, always adding the cheapest edge leaving the tree", "Adding random edges", "Using Dijkstra's distances"], 1,
     "With a binary heap it runs in O(E log V)."),
    ("Edges: AB 1, BC 2, CD 3, AD 4, AC 5. What is the weight of the minimum spanning tree?",
     ["6", "7", "8", "10"], 0, "AB + BC + CD = 1 + 2 + 3 = 6."),
    ("Edges: AB 4, BC 3, CD 2, DA 1, AC 5, BD 6. What is the weight of the minimum spanning tree?",
     ["6", "7", "9", "10"], 0, "DA 1 + CD 2 + BC 3 = 6; each connects a new vertex without a cycle."),
    ("If all edge weights of a connected graph are distinct, its minimum spanning tree is:",
     ["Not guaranteed to exist", "Unique", "Always a path", "Always a star"], 1, "Ties are the only source of multiple MSTs."),
    ("A cut-set of a connected graph is:",
     ["Any set of vertices", "A minimal set of edges whose removal disconnects the graph", "A spanning tree", "A cycle"], 1, "No proper subset of it disconnects the graph."),
    ("With respect to a spanning tree of a connected graph with e edges and n vertices, the number of fundamental circuits is:",
     ["n − 1", "e − n + 1", "e", "n"], 1, "Each non-tree edge (chord) creates one fundamental circuit."),
    ("With respect to a spanning tree of a connected graph with n vertices, the number of fundamental cut-sets is:",
     ["n − 1", "e − n + 1", "n", "e"], 0, "Each tree edge (branch) defines one fundamental cut-set."),
    ("A connected graph has 10 vertices and 15 edges. What is its circuit rank (cyclomatic number)?",
     ["5", "6", "9", "25"], 1, "e − n + 1 = 15 − 10 + 1 = 6."),
    ("How many edges must be removed from a connected graph with n vertices and e edges to obtain a spanning tree?",
     ["n − 1", "e − n + 1", "e − n", "e"], 1, "The tree keeps n − 1 of the e edges."),
    ("Whitney's inequality relates vertex connectivity κ, edge connectivity λ and minimum degree δ as:",
     ["κ ≤ λ ≤ δ", "δ ≤ λ ≤ κ", "λ ≤ κ ≤ δ", "κ = λ = δ always"], 0, "Removing the edges at a minimum-degree vertex disconnects it."),
    ("A bridge in a connected graph is a cut-set containing:",
     ["No edges", "Exactly one edge", "Two edges", "All edges"], 1, "Removing it alone disconnects the graph."),
    ("The cut property of MSTs states that for any cut of the graph:",
     ["The heaviest crossing edge is in every MST", "A minimum-weight edge crossing the cut belongs to some MST", "No crossing edge is in an MST", "All crossing edges are in the MST"], 1,
     "Both Kruskal's and Prim's algorithms rely on it."),
    ("The cycle property of MSTs states that:",
     ["The lightest edge of any cycle is excluded", "A strictly heaviest edge on any cycle does not belong to any MST", "Every cycle is in the MST", "MSTs contain one cycle"], 1,
     "It justifies discarding such edges."),
    ("For a disconnected graph, the analogue of a spanning tree is a:",
     ["Spanning cycle", "Spanning forest", "Matching", "Clique"], 1, "It has one tree per connected component."),
    ("Kruskal's algorithm uses which data structure to detect cycles efficiently?",
     ["Stack", "Queue", "Disjoint-set (union–find)", "Hash table"], 2, "It checks whether both ends of an edge are already in the same set."),
    ("Prim's algorithm with an adjacency matrix and no heap runs in:",
     ["O(V)", "O(V²)", "O(E log V)", "O(V³)"], 1, "This is efficient for dense graphs."),
    ("What is the edge connectivity of the complete graph Kₙ?",
     ["1", "n − 1", "n", "n/2"], 1, "All n − 1 edges at a vertex must be removed to isolate it."),
    ("How many spanning trees does a tree have?",
     ["0", "1", "n", "n − 1"], 1, "It is its own unique spanning tree."),
    ("A DFS of a connected undirected graph classifies each edge as either a tree edge or a:",
     ["Cross edge", "Back edge", "Forward edge", "Bridge"], 1, "Undirected DFS produces no cross edges."),
    ("Consider the statements:\nI. A connected graph can have more than one spanning tree.\nII. All spanning trees of a connected graph have the same number of edges.\nWhich is/are correct?",
     I_II, 2, "Every spanning tree has n − 1 edges, but there may be many different ones."),
    ("Assertion (A): If all edge weights are distinct, the minimum spanning tree is unique.\nReason (R): Kruskal's algorithm sorts the edges by weight.",
     AR, 1, "Both are true, but sorting does not explain uniqueness; uniqueness follows from the cut/cycle properties with no ties."),
]

BOOL_FUNC = [
    ("How many distinct Boolean functions of 3 variables exist?",
     ["8", "64", "256", "512"], 2, "2^(2^3) = 2^8 = 256."),
    ("Which identity is true in Boolean algebra?",
     ["x + x' = 0", "x · x' = 1", "x + 1 = 1", "x · 1 = 0"], 2, "x + x' = 1, x · x' = 0, x + 1 = 1, x · 1 = x."),
    ("x + x'y simplifies to:",
     ["x", "y", "x + y", "xy"], 2, "x + x'y = (x + x')(x + y) = x + y."),
    ("x + xy simplifies to:",
     ["x", "y", "xy", "x + y"], 0, "This is the absorption law."),
    ("The principle of duality states that the dual of a Boolean identity is obtained by:",
     ["Complementing every variable", "Interchanging + with · and 0 with 1", "Reversing the order of variables", "Replacing x with 1"], 1, "The dual of a valid identity is also valid."),
    ("The dual of x + yz is:",
     ["x(y + z)", "x' + y'z'", "xy + z", "(x + y)z"], 0, "Swap + and ·."),
    ("By De Morgan's theorem, (x + y)' equals:",
     ["x' + y'", "x'y'", "xy", "x + y"], 1, "(xy)' = x' + y'."),
    ("For variables (x, y, z) with x as the most significant bit, minterm m5 is:",
     ["x'yz'", "xy'z", "x + y' + z", "xyz'"], 1, "5 = 101, so x = 1, y = 0, z = 1."),
    ("For variables (x, y, z), maxterm M5 is:",
     ["x' + y + z'", "xy'z", "x + y' + z", "x'yz'"], 0, "A maxterm is 0 only at row 101, so it uses complemented literals where the bit is 1."),
    ("If F(x, y, z) = Σm(1, 3, 5, 7), then its complement F' is:",
     ["Σm(1, 3, 5, 7)", "Σm(0, 2, 4, 6)", "ΠM(0, 2, 4, 6)", "Σm(0, 1, 2, 3)"], 1, "The complement is true exactly where F is false."),
    ("A Sum-of-Products (SOP) expression is:",
     ["An AND of OR terms", "An OR of AND terms", "Only a single literal", "Only NAND gates"], 1, "For example xy + x'z."),
    ("Evaluate F = x'y + xz for x = 1, y = 0, z = 1.",
     ["0", "1", "Undefined", "2"], 1, "x'y = 0 and xz = 1, so F = 1."),
    ("A Boolean algebra can be characterised as a:",
     ["Complemented distributive lattice", "Group under addition", "Chain", "Non-distributive lattice"], 0, "Every element has a complement and the lattice is distributive."),
    ("How many self-dual Boolean functions of 2 variables are there?",
     ["2", "4", "8", "16"], 1, "There are 2^(2^(n−1)) self-dual functions: 2² = 4."),
    ("x ⊕ y (XOR) can be written as:",
     ["xy + x'y'", "x'y + xy'", "x + y", "xy"], 1, "It is 1 when exactly one variable is 1."),
    ("Which property holds for XOR?",
     ["x ⊕ x = 1", "x ⊕ 0 = 0", "x ⊕ 1 = x'", "x ⊕ x' = 0"], 2, "x ⊕ x = 0, x ⊕ 0 = x and x ⊕ x' = 1."),
    ("The sum (OR) of all minterms of n variables equals:",
     ["0", "1", "n", "2^n"], 1, "Every input row makes exactly one minterm true."),
    ("The product (AND) of all maxterms of n variables equals:",
     ["0", "1", "n", "The identity function"], 0, "Every input row makes exactly one maxterm false."),
    ("The complement of F = xy + z is:",
     ["(x' + y')z'", "x'y' + z'", "(x + y)z", "x'y'z'"], 0, "(xy + z)' = (xy)' · z' = (x' + y')z'."),
    ("The 3-variable majority function Σm(3, 5, 6, 7) can be written as:",
     ["x + y + z", "xy + yz + xz", "xyz", "x ⊕ y ⊕ z"], 1, "It is 1 when at least two inputs are 1."),
    ("By the consensus theorem, xy + x'z + yz equals:",
     ["xy + x'z", "yz", "x + z", "xy + yz"], 0, "The consensus term yz is redundant."),
    ("The number of elements of any finite Boolean algebra is always:",
     ["A prime", "A power of 2", "Even but not necessarily a power of 2", "Odd"], 1, "It is isomorphic to the power set of some finite set."),
    ("Which single gate type is functionally complete?",
     ["AND", "OR", "NAND", "XOR"], 2, "NOR is also functionally complete."),
    ("A two-level AND–OR circuit directly implements an expression in:",
     ["POS form", "SOP form", "Prefix form", "Gray code"], 1, "AND gates form the products and an OR gate sums them."),
    ("How many minterms does F(x, y) = x + y have?",
     ["1", "2", "3", "4"], 2, "It is 1 for the rows 01, 10 and 11."),
    ("The canonical SOP (sum of minterms) form of a Boolean function is:",
     ["Not unique", "Unique (up to ordering)", "Always the simplest form", "Only defined for 2 variables"], 1, "Each function has exactly one set of minterms."),
    ("XNOR of x and y equals 1 when:",
     ["Exactly one of them is 1", "x and y are equal", "Both are 0 only", "x = 1 only"], 1, "It is the complement of XOR."),
    ("In Boolean algebra, x · (x + y) equals:",
     ["x", "y", "xy", "x + y"], 0, "This is the dual absorption law."),
    ("Consider the statements:\nI. In Boolean algebra, x + yz = (x + y)(x + z).\nII. In Boolean algebra, x(y + z) = xy + xz.\nWhich is/are correct?",
     I_II, 2, "Both distributive laws hold in Boolean algebra (unlike ordinary arithmetic, where only II holds)."),
    ("Assertion (A): The dual of x + 0 = x is x · 1 = x.\nReason (R): Duality interchanges + with · and 0 with 1.",
     AR, 0, "Applying R to the identity gives A."),
]

BOOL_SIMP = [
    ("xy + xy' simplifies to:",
     ["x", "y", "1", "xy"], 0, "x(y + y') = x."),
    ("(x + y)(x + y') simplifies to:",
     ["x", "y", "x + y", "0"], 0, "x + yy' = x."),
    ("xyz + xyz' + xy'z simplifies to:",
     ["xy", "x(y + z)", "xz", "x"], 1, "xy(z + z') + xy'z = xy + xy'z = x(y + y'z) = x(y + z)."),
    ("In a Karnaugh map, the columns for two variables are labelled in the order 00, 01, 11, 10 because:",
     ["It is alphabetical", "Adjacent cells must differ in exactly one variable (Gray code)", "It saves space", "It follows binary counting"], 1, "This makes adjacency visible."),
    ("Groups of 1s in a K-map must contain how many cells?",
     ["Any number", "A power of 2 (1, 2, 4, 8, …)", "An even number only", "Exactly 4"], 1, "Each doubling eliminates one variable."),
    ("Simplify F(x, y, z) = Σm(0, 2, 4, 6).",
     ["x'", "z'", "y'", "xz"], 1, "These are exactly the rows where z = 0."),
    ("Simplify F(x, y, z) = Σm(0, 1, 2, 3).",
     ["x'", "y'", "z'", "x"], 0, "These are the rows where x = 0."),
    ("Simplify F(x, y, z) = Σm(3, 5, 6, 7).",
     ["xy + yz + xz", "x + y + z", "xyz", "xy'z"], 0, "The majority function needs three groups of two."),
    ("Simplify F(w, x, y, z) = Σm(0, 2, 8, 10).",
     ["w'z'", "x'z'", "w'x'", "y'z'"], 1, "The four corner cells of a 4-variable K-map group together: x = 0 and z = 0."),
    ("Simplify F(w, x, y, z) = Σm(0, 1, …, 15).",
     ["0", "1", "w", "wxyz"], 1, "All cells are 1."),
    ("Simplify F(w, x, y, z) = Σm(0, 1, 2, 3, 4, 5, 6, 7).",
     ["w", "w'", "x'", "w'x'"], 1, "These are all the rows with w = 0."),
    ("Simplify F(x, y, z) = Σm(1, 2, 3, 5, 7).",
     ["z + x'y", "x + z", "y + z", "x'y + xz"], 0, "z covers 1, 3, 5, 7 and x'y covers 2 and 3."),
    ("Simplify x'y'z' + x'y'z + x'yz.",
     ["x'y' + x'z", "x'", "y'z", "x'z'"], 0, "Minterms 0, 1, 3: x'y' covers 0 and 1; x'z covers 1 and 3."),
    ("'Don't care' conditions in a K-map:",
     ["Must be treated as 0", "May be treated as 0 or 1, whichever gives a simpler expression", "Must be treated as 1", "Are not allowed"], 1,
     "E.g. the unused BCD codes 1010–1111."),
    ("A prime implicant is:",
     ["Any group of 1s", "A product term (group) that cannot be combined into a larger group", "A single minterm", "A maxterm"], 1, "Essential prime implicants cover some minterm that no other prime implicant covers."),
    ("An essential prime implicant is one that:",
     ["Covers the most minterms", "Covers at least one minterm not covered by any other prime implicant", "Contains all variables", "Is always a single cell"], 1, "It must appear in every minimal SOP."),
    ("Which method is systematic and suitable for simplifying functions with many variables by computer?",
     ["Karnaugh map", "Quine–McCluskey (tabular) method", "Venn diagrams", "Truth tables only"], 1, "K-maps become impractical beyond 5–6 variables."),
    ("A 4-variable K-map has how many cells?",
     ["4", "8", "16", "32"], 2, "2^4 = 16."),
    ("In a 4-variable K-map, a group of 8 adjacent 1s produces a term with how many literals?",
     ["1", "2", "3", "4"], 0, "8 = 2³ eliminates 3 of the 4 variables."),
    ("In a 4-variable K-map, a group of 4 adjacent 1s produces a term with how many literals?",
     ["1", "2", "3", "4"], 1, "4 = 2² eliminates 2 variables."),
    ("For POS simplification using a K-map, you group:",
     ["The 1s", "The 0s", "Only don't cares", "Diagonal cells"], 1, "Grouping the 0s gives F', which is complemented into POS form."),
    ("For variables (x, y), F = ΠM(0, 1) simplifies to:",
     ["x", "y", "x'", "1"], 0, "F is 0 exactly when x = 0, so F = x."),
    ("A two-level SOP circuit can be implemented using only:",
     ["NOR gates in two levels", "NAND gates in two levels", "XOR gates", "Inverters only"], 1, "AND–OR is equivalent to NAND–NAND."),
    ("A two-level POS circuit can be implemented using only:",
     ["NAND gates", "NOR gates in two levels", "XOR gates", "AND gates"], 1, "OR–AND is equivalent to NOR–NOR."),
    ("(x + y)(x' + z)(y + z) simplifies to:",
     ["(x + y)(x' + z)", "(y + z)", "x + z", "xy + z"], 0, "This is the dual of the consensus theorem."),
    ("Why can x ⊕ y = x'y + xy' not be simplified further on a K-map?",
     ["It has too many variables", "Its 1s are diagonal (checkerboard) and no two are adjacent", "It is always 0", "K-maps cannot show XOR"], 1,
     "Parity functions are the worst case for K-map simplification."),
    ("In a 3-variable K-map, which pair of cells is adjacent?",
     ["000 and 011", "001 and 011", "010 and 101", "100 and 111"], 1, "001 and 011 differ in one variable only."),
    ("In a 4-variable K-map, the cells in the leftmost and rightmost columns of a row are:",
     ["Not adjacent", "Adjacent (the map wraps around)", "Adjacent only in the first row", "Identical"], 1, "The map is effectively a torus."),
    ("Consider the statements:\nI. Every essential prime implicant must appear in the minimal SOP expression.\nII. Every prime implicant must appear in the minimal SOP expression.\nWhich is/are correct?",
     I_II, 0, "Some prime implicants are redundant, e.g. consensus terms."),
    ("Assertion (A): A group of 6 adjacent 1s can be used as one term in a K-map.\nReason (R): Every group in a K-map must contain 2^k cells.",
     AR, 3, "A is false because 6 is not a power of 2; R is true."),
]

TOPICS = {
    "Trees, Prefix Codes, Spanning Trees": [("1 · Trees and Rooted Trees", TREES), ("2 · Prefix Codes", PREFIX), ("3 · Tree Traversals", TRAVERSALS),
                                            ("4 · Spanning Trees and Cut-sets", SPANNING)],
    "Boolean Algebra": [("1 · Boolean Functions and their Representation", BOOL_FUNC), ("2 · Simplification of Boolean Functions", BOOL_SIMP)],
}
