"""Paper 2 · Unit 2 · topics U2-06 and U2-07 Graph Theory (6 sub-topics × 30)."""
from packlib import AR, I_II

GRAPH_BASICS = [
    ("A simple graph is a graph with:",
     ["No vertices of degree 0", "No loops and no multiple edges", "Exactly one cycle", "Weighted edges only"], 1, "Multigraphs allow multiple edges; pseudographs also allow loops."),
    ("A graph that allows multiple edges between the same pair of vertices, but no loops, is a:",
     ["Simple graph", "Multigraph", "Tree", "Complete graph"], 1, "A pseudograph also allows loops."),
    ("By the handshaking theorem, a graph with 10 edges has a degree sum of:",
     ["10", "20", "5", "100"], 1, "The sum of the degrees equals 2|E|."),
    ("In every undirected graph, the number of vertices of odd degree is:",
     ["Odd", "Even", "Zero", "Equal to the number of edges"], 1, "Since the degree sum is even, odd degrees must pair up."),
    ("Which degree sequence CANNOT belong to a simple graph?",
     ["(2, 2, 2)", "(3, 3, 3, 1)", "(1, 1)", "(3, 3, 3, 3)"], 1,
     "Three vertices of degree 3 in a 4-vertex simple graph must each be adjacent to all others, forcing the fourth vertex to have degree 3, not 1."),
    ("Which degree sequence is impossible for a simple graph on 4 vertices?",
     ["(3, 3, 3, 3)", "(4, 4, 3, 1)", "(2, 2, 2, 2)", "(1, 1, 1, 1)"], 1, "In a simple graph on 4 vertices the maximum degree is 3."),
    ("What is the maximum number of edges in a simple graph with 10 vertices?",
     ["90", "45", "100", "20"], 1, "n(n − 1)/2 = 10 × 9 / 2 = 45, achieved by K10."),
    ("The complete graph Kₙ is:",
     ["n-regular", "(n − 1)-regular", "2-regular", "Not regular"], 1, "Every vertex is adjacent to the other n − 1 vertices."),
    ("How many edges does a 3-regular graph with 8 vertices have?",
     ["8", "12", "24", "16"], 1, "Degree sum 8 × 3 = 24 = 2|E|, so |E| = 12."),
    ("Why can there be no 3-regular graph with 7 vertices?",
     ["7 is prime", "The degree sum 7 × 3 = 21 would be odd", "3 > 7/2", "It would be complete"], 1, "The degree sum must be even."),
    ("A simple graph has 6 vertices and 7 edges. How many edges does its complement have?",
     ["7", "8", "15", "9"], 1, "K6 has 15 edges, so the complement has 15 − 7 = 8."),
    ("The adjacency matrix of a simple undirected graph is:",
     ["Symmetric with zeros on the diagonal", "Upper triangular", "The identity matrix", "Always invertible"], 0, "No loops means zero diagonal; undirected edges make it symmetric."),
    ("The sum of all entries of the adjacency matrix of a simple undirected graph equals:",
     ["|V|", "|E|", "2|E|", "|V|²"], 2, "Each edge contributes two 1s."),
    ("Which representation needs O(V + E) space?",
     ["Adjacency matrix", "Adjacency list", "Incidence matrix", "Distance matrix"], 1, "An adjacency matrix needs O(V²) space."),
    ("In a directed graph, the sum of all in-degrees equals:",
     ["The number of vertices", "The sum of all out-degrees, which equals |E|", "2|E|", "Zero"], 1, "Each directed edge contributes one in-degree and one out-degree."),
    ("A weighted graph is a graph in which:",
     ["Vertices have colours", "Each edge is assigned a number such as a cost or distance", "There are no cycles", "All vertices have the same degree"], 1, "Weighted graphs model road networks, costs and so on."),
    ("How many different simple graphs can be drawn on 4 labelled vertices?",
     ["16", "64", "6", "256"], 1, "Each of the C(4, 2) = 6 possible edges is present or absent: 2^6 = 64."),
    ("Which property is NECESSARY (but not sufficient) for two graphs to be isomorphic?",
     ["Same number of vertices, edges and the same degree sequence", "Same drawing", "Same vertex labels", "Both are trees"], 0,
     "Isomorphic graphs share all these invariants, but sharing them does not guarantee isomorphism."),
    ("In the incidence matrix of a loop-free undirected graph, each column (edge) contains:",
     ["One 1", "Exactly two 1s", "All 1s", "No 1s"], 1, "The two 1s mark the edge's endpoints."),
    ("The wheel Wₙ (a cycle of n vertices plus a hub joined to all of them) has how many edges?",
     ["n", "n + 1", "2n", "n²"], 2, "n rim edges plus n spokes."),
    ("The hypercube Q3 has:",
     ["8 vertices and 12 edges", "6 vertices and 8 edges", "8 vertices and 8 edges", "16 vertices and 32 edges"], 0, "Qn has 2^n vertices and n · 2^(n−1) edges."),
    ("A loop at a vertex contributes how much to that vertex's degree?",
     ["0", "1", "2", "3"], 2, "Both ends of the loop are at the same vertex."),
    ("A vertex of degree 1 is called a:",
     ["Isolated vertex", "Pendant vertex", "Cut vertex", "Hub"], 1, "An isolated vertex has degree 0."),
    ("A simple graph has degree sequence (4, 3, 3, 2, 2). How many edges does it have?",
     ["14", "7", "5", "10"], 1, "Degree sum 14 = 2|E|."),
    ("The complete bipartite graph K3,3 has how many edges?",
     ["6", "9", "15", "3"], 1, "3 × 3 = 9."),
    ("An induced subgraph on a vertex subset S contains:",
     ["Only some edges among S", "All edges of the original graph that join vertices of S", "No edges", "All vertices of the graph"], 1, "Every edge with both ends in S is kept."),
    ("A graph with n vertices and no edges is called a:",
     ["Complete graph", "Null (empty) graph", "Tree", "Cycle"], 1, "Its complement is Kₙ."),
    ("The star graph K1,5 has how many edges?",
     ["5", "6", "10", "1"], 0, "One centre joined to 5 leaves."),
    ("Consider the statements:\nI. Every graph has an even number of vertices of odd degree.\nII. Every graph has an even number of vertices of even degree.\nWhich is/are correct?",
     I_II, 0, "Statement II is false, e.g. a single isolated vertex."),
    ("Assertion (A): No simple graph has the degree sequence (3, 3, 3, 3, 3).\nReason (R): The sum of the degrees of any graph must be even.",
     AR, 0, "3 × 5 = 15 is odd."),
]

PATHS = [
    ("A walk in which no edge is repeated is called a:",
     ["Path", "Trail", "Cycle", "Tour"], 1, "A path repeats no vertex (and hence no edge)."),
    ("A walk in which no vertex is repeated is called a:",
     ["Trail", "Path", "Circuit", "Loop"], 1, "Every path is a trail, but not every trail is a path."),
    ("A graph is connected if:",
     ["It has no cycles", "There is a path between every pair of vertices", "Every vertex has degree at least 1", "It is complete"], 1, "Otherwise it splits into components."),
    ("A graph with 10 vertices and 6 edges has at least how many connected components?",
     ["2", "4", "6", "10"], 1, "Each edge can reduce the number of components by at most 1: 10 − 6 = 4."),
    ("What is the minimum number of edges in a connected graph with n vertices?",
     ["n", "n − 1", "n(n − 1)/2", "2n"], 1, "A spanning tree has n − 1 edges."),
    ("What is the maximum number of edges in a disconnected simple graph with 6 vertices?",
     ["15", "10", "9", "5"], 1, "Take K5 plus an isolated vertex: C(5, 2) = 10."),
    ("A vertex whose removal increases the number of connected components is a:",
     ["Pendant vertex", "Cut vertex (articulation point)", "Leaf", "Centre"], 1, "An edge with the same property is a bridge."),
    ("If A is the adjacency matrix of a graph, the (i, j) entry of A^k gives:",
     ["The degree of vertex i", "The number of walks of length k from vertex i to vertex j", "The distance from i to j", "Whether i = j"], 1, "Matrix multiplication counts walks."),
    ("Dijkstra's algorithm correctly finds shortest paths when:",
     ["Some edge weights are negative", "All edge weights are non-negative", "The graph has negative cycles", "The graph is unweighted only"], 1, "It may fail with negative edges."),
    ("Which algorithm finds single-source shortest paths with negative edge weights and detects negative cycles?",
     ["Dijkstra", "Bellman–Ford", "Prim", "Kruskal"], 1, "Bellman–Ford runs in O(VE) time."),
    ("The Floyd–Warshall algorithm computes:",
     ["A minimum spanning tree", "Shortest paths between all pairs of vertices in O(V³)", "A topological order", "A maximum matching"], 1, "It is a dynamic programming algorithm."),
    ("With a binary heap, Dijkstra's algorithm runs in:",
     ["O(V + E)", "O((V + E) log V)", "O(V³)", "O(VE)"], 1, "Each vertex extraction and edge relaxation costs O(log V)."),
    ("Edges (undirected): A–B 4, A–C 2, C–B 1, B–D 5, C–D 8. What is the shortest distance from A to D?",
     ["8", "9", "10", "7"], 0, "A → C → B → D = 2 + 1 + 5 = 8."),
    ("Edges (undirected): A–B 1, B–C 2, A–C 4, C–D 1, B–D 5. What is the shortest distance from A to D?",
     ["5", "4", "6", "3"], 1, "A → B → C → D = 1 + 2 + 1 = 4."),
    ("The eccentricity of a vertex is:",
     ["Its degree", "Its greatest distance to any other vertex", "The number of cycles through it", "Its smallest distance to another vertex"], 1, "The radius is the minimum eccentricity; the diameter is the maximum."),
    ("In an unweighted graph, shortest paths from a source are found efficiently by:",
     ["Depth-first search", "Breadth-first search in O(V + E)", "Kruskal's algorithm", "Sorting the edges"], 1, "BFS explores vertices in order of distance."),
    ("A directed graph is strongly connected if:",
     ["Its underlying undirected graph is connected", "There is a directed path from every vertex to every other vertex", "It has no cycles", "Every vertex has in-degree 1"], 1,
     "If only the underlying undirected graph is connected, it is weakly connected."),
    ("How many edges does the path graph Pₙ with n vertices have?",
     ["n", "n − 1", "n + 1", "2n"], 1, "It is a tree."),
    ("The girth of a graph is:",
     ["Its number of edges", "The length of its shortest cycle", "The length of its longest path", "Its maximum degree"], 1, "The girth of K4 is 3; that of the Petersen graph is 5."),
    ("The girth of the Petersen graph is:",
     ["3", "4", "5", "6"], 2, "It has no triangles or 4-cycles."),
    ("The cyclomatic number (circuit rank) of a graph with m edges, n vertices and c components is:",
     ["m − n + c", "m + n − c", "n − m", "m − n − c"], 0, "It is the number of independent cycles."),
    ("In the complete graph Kₙ (n ≥ 2), the distance between any two distinct vertices is:",
     ["0", "1", "2", "n − 1"], 1, "Every pair is adjacent."),
    ("What is the diameter of the cycle C6?",
     ["2", "3", "5", "6"], 1, "Opposite vertices are 3 steps apart."),
    ("What is the diameter of the Petersen graph?",
     ["1", "2", "3", "5"], 1, "Any two non-adjacent vertices have a common neighbour."),
    ("If a graph contains a negative-weight cycle reachable from the source, then:",
     ["Dijkstra's algorithm still works", "Shortest path lengths to vertices reachable through it are undefined (can be made arbitrarily small)",
      "All shortest paths are zero", "The graph must be a tree"], 1, "Going around the cycle keeps reducing the length."),
    ("The length of a path is defined as:",
     ["The number of vertices on it", "The number of edges on it (or the sum of weights in a weighted graph)", "The largest degree on it", "The number of cycles"], 1,
     "For weighted graphs we usually add the weights."),
    ("A cycle in a graph is:",
     ["A closed trail whose only repeated vertex is the start/end vertex", "Any walk", "A path with one edge", "A tree"], 0, "Cycles need at least 3 vertices in a simple graph."),
    ("Removing a bridge from a connected graph:",
     ["Always creates a cycle", "Disconnects the graph", "Adds a vertex", "Has no effect"], 1, "A bridge lies on no cycle."),
    ("Consider the statements:\nI. Dijkstra's algorithm always gives correct shortest paths when some edge weights are negative.\nII. The Bellman–Ford algorithm can detect negative-weight cycles.\nWhich is/are correct?",
     I_II, 1, "Dijkstra's greedy choice can be wrong with negative edges."),
    ("Assertion (A): Dijkstra's algorithm may give wrong answers if some edge weights are negative.\nReason (R): Dijkstra's algorithm runs in O(V²) time with an array implementation.",
     AR, 1, "Both are true, but the running time does not explain the failure; the reason is that a finalised vertex could later get a shorter path via a negative edge."),
]

EULER_HAM = [
    ("A connected graph has an Euler circuit if and only if:",
     ["It has exactly two vertices of odd degree", "Every vertex has even degree", "It is complete", "It has a Hamiltonian cycle"], 1, "This is Euler's theorem."),
    ("A connected graph has an Euler path but not an Euler circuit if and only if it has exactly:",
     ["0 vertices of odd degree", "2 vertices of odd degree", "1 vertex of odd degree", "4 vertices of odd degree"], 1, "The path must start and end at the two odd vertices."),
    ("The Königsberg bridge problem has no solution because:",
     ["The river is too wide", "All four land masses have odd degree", "There are too many bridges", "The graph is disconnected"], 1, "More than two odd vertices means no Euler path."),
    ("The complete graph Kₙ (n ≥ 3) has an Euler circuit if and only if:",
     ["n is even", "n is odd", "n is prime", "n = 3 only"], 1, "Every vertex has degree n − 1, which must be even."),
    ("The complete bipartite graph Km,n has an Euler circuit if and only if:",
     ["m = n", "m and n are both even", "m and n are both odd", "m + n is odd"], 1, "Vertices have degrees n and m, which must be even."),
    ("A Hamiltonian circuit in a graph is a circuit that:",
     ["Uses every edge exactly once", "Visits every vertex exactly once", "Has the minimum weight", "Uses no vertex twice and no edge"], 1, "An Euler circuit uses every edge exactly once."),
    ("Dirac's theorem states that a simple graph with n ≥ 3 vertices is Hamiltonian if:",
     ["Every vertex has degree at least n/2", "It has n edges", "It is bipartite", "Every vertex has even degree"], 0, "This is a sufficient condition, not a necessary one."),
    ("Ore's theorem states that a simple graph with n ≥ 3 vertices is Hamiltonian if:",
     ["deg(u) + deg(v) ≥ n for every pair of non-adjacent vertices u, v", "It is connected", "It has an Euler circuit", "It is planar"], 0, "Dirac's theorem is a special case."),
    ("How many distinct Hamiltonian cycles does K5 have (ignoring starting point and direction)?",
     ["12", "24", "60", "120"], 0, "(n − 1)!/2 = 4!/2 = 12."),
    ("The Petersen graph:",
     ["Is Hamiltonian", "Has no Hamiltonian cycle but does have a Hamiltonian path", "Has an Euler circuit", "Is planar"], 1, "It is the standard example of a non-Hamiltonian 3-regular graph."),
    ("Which statement about complexity is correct?",
     ["Finding an Euler circuit is NP-complete", "Deciding whether a graph has a Hamiltonian cycle is NP-complete, while Euler circuits can be found in polynomial time",
      "Both are NP-complete", "Both are solvable in O(1)"], 1, "Hierholzer's algorithm finds Euler circuits in O(E)."),
    ("The complete bipartite graph Km,n has a Hamiltonian cycle if and only if:",
     ["m = n ≥ 2", "m + n is even", "m ≠ n", "m = 1"], 0, "The cycle must alternate between the two parts."),
    ("Hypercubes Qₙ (n ≥ 2) are Hamiltonian. A Hamiltonian cycle in Qₙ corresponds to a:",
     ["Huffman code", "Gray code", "BCD code", "Parity code"], 1, "Consecutive Gray code words differ in exactly one bit."),
    ("The Travelling Salesperson Problem asks for:",
     ["An Euler circuit", "A minimum-weight Hamiltonian cycle", "A minimum spanning tree", "A maximum matching"], 1, "It is NP-hard."),
    ("A graph with a cut vertex:",
     ["Always has a Hamiltonian cycle", "Cannot have a Hamiltonian cycle", "Always has an Euler circuit", "Is complete"], 1, "A Hamiltonian cycle would have to pass through the cut vertex twice."),
    ("The Chinese Postman problem is related to:",
     ["Hamiltonian cycles", "Euler circuits (traversing every edge at minimum cost)", "Graph colouring", "Planarity"], 1, "Edges are duplicated to make all degrees even."),
    ("Fleury's algorithm for finding an Euler circuit follows the rule:",
     ["Always take the cheapest edge", "Do not cross a bridge unless there is no other choice", "Visit the highest-degree vertex first", "Use BFS"], 1, "'Don't burn your bridges.'"),
    ("Drawing a figure without lifting the pen and without retracing any line is equivalent to finding a/an:",
     ["Hamiltonian path", "Euler path", "Spanning tree", "Matching"], 1, "Each line (edge) is used exactly once."),
    ("A connected graph has degree sequence (4, 2, 2, 2, 2). Does it have an Euler circuit?",
     ["Yes, because all degrees are even", "No, because one vertex has degree 4", "Only an Euler path", "Cannot be determined"], 0, "Connected with all even degrees."),
    ("A connected graph has degree sequence (3, 3, 2, 2, 2). It has:",
     ["An Euler circuit", "An Euler path but no Euler circuit", "Neither", "Both"], 1, "Exactly two odd vertices."),
    ("A connected graph has 4 vertices of odd degree. What is the minimum number of edges that must be added (duplicated) to make it Eulerian?",
     ["1", "2", "3", "4"], 1, "Each added edge can fix two odd vertices."),
    ("The cycle graph Cₙ (n ≥ 3) is:",
     ["Neither Eulerian nor Hamiltonian", "Both Eulerian and Hamiltonian", "Only Eulerian", "Only Hamiltonian"], 1, "It is itself both an Euler circuit and a Hamiltonian cycle."),
    ("The star graph K1,3 is:",
     ["Eulerian", "Hamiltonian", "Neither Eulerian nor Hamiltonian", "Both"], 2, "It has odd-degree vertices and no cycles."),
    ("A connected directed graph has a directed Euler circuit if and only if:",
     ["Every vertex has even total degree", "In-degree equals out-degree at every vertex", "It is acyclic", "It is strongly connected only"], 1, "It must also be (strongly) connected on the vertices with edges."),
    ("De Bruijn sequences, used for example in lock codes, are constructed from:",
     ["Hamiltonian cycles only", "Euler circuits in de Bruijn graphs", "Spanning trees", "Planar embeddings"], 1, "Each edge represents one overlapping window."),
    ("Every complete graph Kₙ with n ≥ 3:",
     ["Has an Euler circuit", "Is Hamiltonian", "Is bipartite", "Is a tree"], 1, "Any ordering of the vertices forms a Hamiltonian cycle."),
    ("A tree with at least 2 vertices:",
     ["Always has a Hamiltonian cycle", "Never has a Hamiltonian cycle", "Always has an Euler circuit", "Is always complete"], 1, "Trees have no cycles at all."),
    ("A Hamiltonian path in a graph with n vertices has how many edges?",
     ["n", "n − 1", "n + 1", "2n"], 1, "It visits all n vertices once."),
    ("Consider the statements:\nI. Every Eulerian graph is Hamiltonian.\nII. Every Hamiltonian graph is Eulerian.\nWhich is/are correct?",
     I_II, 3, "Two triangles sharing a vertex are Eulerian but not Hamiltonian; K4 is Hamiltonian but not Eulerian."),
    ("Assertion (A): K4 has an Euler circuit.\nReason (R): Every vertex of K4 has degree 3.",
     AR, 3, "A is false because the degrees are odd; R is true."),
]

PLANAR = [
    ("Euler's formula for a connected planar graph with v vertices, e edges and f faces is:",
     ["v + e + f = 2", "v − e + f = 2", "v − e − f = 2", "e − v + f = 2"], 1, "The outer (unbounded) face is counted."),
    ("A connected planar graph has 8 vertices and 12 edges. How many faces does it have?",
     ["4", "6", "8", "10"], 1, "f = 2 − v + e = 2 − 8 + 12 = 6."),
    ("For a connected simple planar graph with v ≥ 3 vertices, e is at most:",
     ["2v − 4", "3v − 6", "v − 1", "v²"], 1, "Each face has at least 3 edges and each edge borders at most 2 faces."),
    ("What is the maximum number of edges in a simple planar graph with 10 vertices?",
     ["30", "24", "45", "20"], 1, "3 × 10 − 6 = 24."),
    ("For a connected simple planar graph with v ≥ 3 and no triangles, e is at most:",
     ["3v − 6", "2v − 4", "v − 1", "v"], 1, "Each face then has at least 4 edges."),
    ("K5 is non-planar because:",
     ["It has 5 vertices", "e = 10 > 3v − 6 = 9", "It is bipartite", "It has a triangle"], 1, "It violates the edge bound."),
    ("K3,3 is non-planar because:",
     ["It has 6 vertices", "It has no triangles and e = 9 > 2v − 4 = 8", "e > 3v − 6", "It is not connected"], 1, "The triangle-free bound applies."),
    ("Kuratowski's theorem states that a graph is non-planar if and only if it contains a subgraph that is a subdivision of:",
     ["K4 or K2,3", "K5 or K3,3", "The Petersen graph", "Any cycle"], 1, "Wagner's theorem gives the same with minors."),
    ("Which of these graphs is planar?",
     ["K5", "K3,3", "K4", "The Petersen graph"], 2, "K4 can be drawn as a triangle with a central vertex."),
    ("Every simple planar graph has a vertex of degree at most:",
     ["3", "4", "5", "6"], 2, "This is used in the proof of the five-colour theorem."),
    ("When counting faces of a planar drawing, the unbounded outer region is:",
     ["Not counted", "Counted as a face", "Counted twice", "Counted only for trees"], 1, "A tree has exactly one face, the outer one."),
    ("In a planar graph, the sum of the degrees of all faces equals:",
     ["e", "2e", "f", "v"], 1, "Each edge borders two faces (or the same face twice)."),
    ("A connected planar graph has 6 vertices, each of degree 4. How many faces does it have?",
     ["6", "8", "10", "12"], 1, "e = 6 × 4 / 2 = 12; f = 2 − 6 + 12 = 8 (the octahedron)."),
    ("The Petersen graph is:",
     ["Planar", "Non-planar (it contains a subdivision of K3,3)", "A tree", "Bipartite"], 1, "It has 10 vertices and 15 edges."),
    ("The cube graph Q3 is planar. How many faces does its planar drawing have?",
     ["4", "6", "8", "12"], 1, "8 − 12 + f = 2 gives f = 6."),
    ("In the dual of a plane graph:",
     ["Vertices correspond to faces of the original", "Edges become vertices", "Faces become edges only", "It is always complete"], 0, "Two dual vertices are joined when the faces share an edge."),
    ("For a planar graph with c connected components, Euler's formula becomes:",
     ["v − e + f = 2", "v − e + f = 1 + c", "v − e + f = c", "v + e + f = 2c"], 1, "With c = 1 it reduces to the usual formula."),
    ("The crossing number of K5 (minimum number of edge crossings in a drawing) is:",
     ["0", "1", "2", "5"], 1, "K3,3 also has crossing number 1."),
    ("A maximal planar graph with v ≥ 3 vertices, in which every face is a triangle, has exactly:",
     ["2v − 4 edges", "3v − 6 edges", "v − 1 edges", "v(v − 1)/2 edges"], 1, "It meets the planar edge bound exactly."),
    ("A maximal planar graph with 12 vertices has how many edges and faces?",
     ["30 edges, 20 faces", "24 edges, 14 faces", "36 edges, 26 faces", "30 edges, 18 faces"], 0, "e = 3 × 12 − 6 = 30 and f = 2 − 12 + 30 = 20 (the icosahedron)."),
    ("Wagner's theorem characterises planar graphs as those that do not contain which graphs as minors?",
     ["K4 and C4", "K5 and K3,3", "K2,3 and K4", "Petersen and K4"], 1, "It is equivalent to Kuratowski's theorem."),
    ("For a tree with v vertices, Euler's formula gives:",
     ["f = 0", "f = 1", "f = v", "f = 2"], 1, "e = v − 1, so f = 2 − v + (v − 1) = 1."),
    ("A simple graph has 5 vertices and 9 edges. Based only on e ≤ 3v − 6, it:",
     ["Must be non-planar", "Could be planar (e.g. K5 minus one edge is planar)", "Must be a tree", "Is disconnected"], 1, "3 × 5 − 6 = 9, so the bound is not violated."),
    ("Planarity testing is important in which application?",
     ["Database indexing", "Designing printed circuit boards and VLSI layouts without wire crossings", "Sorting", "Compiling"], 1, "Crossings on a single layer are not allowed."),
    ("Is K2,3 planar?",
     ["Yes", "No", "Only with 2 crossings", "Planarity is undefined for bipartite graphs"], 0, "K2,n is planar for every n."),
    ("What is the smallest number of vertices a non-planar simple graph can have?",
     ["4", "5", "6", "7"], 1, "K5 is the smallest."),
    ("A connected planar graph has 7 faces and 10 edges. How many vertices does it have?",
     ["3", "5", "7", "17"], 1, "v = 2 + e − f = 2 + 10 − 7 = 5."),
    ("The graphs of the five Platonic solids are:",
     ["All non-planar", "All planar", "Only the cube is planar", "All bipartite"], 1, "Each polyhedron's skeleton can be drawn without crossings."),
    ("Consider the statements:\nI. If a simple graph satisfies e ≤ 3v − 6, it must be planar.\nII. If a simple graph with v ≥ 3 has e > 3v − 6, it is non-planar.\nWhich is/are correct?",
     I_II, 1, "The bound is necessary, not sufficient: K3,3 satisfies it but is non-planar."),
    ("Assertion (A): K3,3 is non-planar.\nReason (R): K3,3 violates the inequality e ≤ 3v − 6.",
     AR, 2, "A is true, but R is false: 9 ≤ 3 × 6 − 6 = 12. The triangle-free bound e ≤ 2v − 4 = 8 is what is violated."),
]

COLOURING = [
    ("The chromatic number χ(G) of a graph is:",
     ["The number of edges", "The minimum number of colours needed so that adjacent vertices get different colours", "The maximum degree", "The number of cycles"], 1,
     "It is a proper vertex colouring."),
    ("What is the chromatic number of the complete graph Kₙ?",
     ["2", "3", "n − 1", "n"], 3, "Every pair of vertices is adjacent."),
    ("What is the chromatic number of a cycle Cₙ?",
     ["Always 2", "2 if n is even, 3 if n is odd", "Always 3", "n"], 1, "Odd cycles are not bipartite."),
    ("What is the chromatic number of a tree with at least 2 vertices?",
     ["1", "2", "3", "It depends on the number of leaves"], 1, "Trees are bipartite."),
    ("The Four Colour Theorem (Appel and Haken, 1976) states that:",
     ["Every graph can be coloured with 4 colours", "Every planar graph can be coloured with at most 4 colours", "Every bipartite graph needs 4 colours", "K4 is non-planar"], 1,
     "It was the first major theorem proved with extensive computer assistance."),
    ("The wheel Wₙ (a cycle of n vertices plus a hub) has chromatic number:",
     ["Always 3", "3 if n is even, 4 if n is odd", "Always 4", "n + 1"], 1, "The hub needs a colour different from all rim vertices."),
    ("What is the chromatic number of the Petersen graph?",
     ["2", "3", "4", "5"], 1, "It contains odd cycles but can be coloured with 3 colours."),
    ("How many proper colourings does the path P3 (3 vertices in a line) have using 3 colours?",
     ["6", "12", "18", "27"], 1, "3 × 2 × 2 = 12; for a tree on n vertices it is k(k − 1)^(n−1)."),
    ("How many proper colourings does the triangle K3 have using 3 colours?",
     ["3", "6", "9", "27"], 1, "3 × 2 × 1 = 6."),
    ("The chromatic polynomial of Kₙ is:",
     ["kⁿ", "k(k − 1)(k − 2)…(k − n + 1)", "k(k − 1)^(n−1)", "(k − 1)ⁿ"], 1, "Each new vertex must avoid all earlier colours."),
    ("A greedy colouring algorithm uses at most how many colours, where Δ is the maximum degree?",
     ["Δ", "Δ + 1", "2Δ", "n"], 1, "Each vertex has at most Δ coloured neighbours."),
    ("Brooks' theorem states that χ(G) ≤ Δ for a connected graph G, except when G is:",
     ["A tree", "A complete graph or an odd cycle", "Bipartite", "Planar"], 1, "These exceptions need Δ + 1 colours."),
    ("Scheduling exams so that no student has two exams at the same time, using the minimum number of time slots, is equivalent to finding:",
     ["A minimum spanning tree", "The chromatic number of the conflict graph", "An Euler circuit", "A shortest path"], 1, "Courses are vertices; shared students create edges."),
    ("Graph colouring is used in compilers for:",
     ["Lexical analysis", "Register allocation", "Parsing", "Linking"], 1, "Variables alive at the same time cannot share a register."),
    ("By Vizing's theorem, the edge chromatic number (chromatic index) of a simple graph is:",
     ["Always Δ", "Either Δ or Δ + 1", "Always Δ + 1", "At most 3"], 1, "Δ is the maximum degree."),
    ("Which inequality always holds, where ω(G) is the size of the largest clique?",
     ["χ(G) ≤ ω(G)", "χ(G) ≥ ω(G)", "χ(G) = Δ", "χ(G) ≤ 2"], 1, "All vertices of a clique need different colours."),
    ("Deciding whether a graph can be coloured with 3 colours is:",
     ["Solvable in linear time", "NP-complete", "Always yes for planar graphs", "Trivial"], 1, "2-colourability, however, is easy (bipartiteness testing)."),
    ("What is the chromatic number of Km,n (m, n ≥ 1)?",
     ["1", "2", "m", "m + n"], 1, "It is bipartite with at least one edge."),
    ("What is the chromatic number of the hypercube Qₙ (n ≥ 1)?",
     ["2", "3", "n", "2^n"], 0, "Colour vertices by the parity of the number of 1s."),
    ("The chromatic number of a graph with at least one vertex and no edges is:",
     ["0", "1", "2", "n"], 1, "One colour suffices."),
    ("Colouring the regions of a map so that neighbouring regions differ corresponds to colouring the:",
     ["Map's edges", "Vertices of the dual planar graph", "Faces of a tree", "Adjacency matrix"], 1, "Regions become vertices; shared borders become edges."),
    ("How many colours are needed to colour C5?",
     ["2", "3", "4", "5"], 1, "It is an odd cycle."),
    ("What is P(K3, 2), the number of proper colourings of a triangle with 2 colours?",
     ["0", "2", "6", "8"], 0, "k(k − 1)(k − 2) = 2 × 1 × 0 = 0."),
    ("A graph containing a triangle needs at least:",
     ["2 colours", "3 colours", "4 colours", "5 colours"], 1, "The three mutually adjacent vertices need different colours."),
    ("The five-colour theorem for planar graphs was proved by:",
     ["Appel and Haken", "Heawood (1890)", "Euler", "Kuratowski"], 1, "Heawood showed Kempe's four-colour argument was flawed but that it proves five colours."),
    ("Each colour class in a proper vertex colouring is a/an:",
     ["Clique", "Independent set", "Cycle", "Tree"], 1, "No two vertices of the same colour are adjacent."),
    ("If α(G) is the size of the largest independent set of a graph with n vertices, then:",
     ["χ(G) ≥ n / α(G)", "χ(G) ≤ α(G)", "χ(G) = α(G)", "χ(G) ≥ n × α(G)"], 0, "Each colour class has at most α(G) vertices."),
    ("A graph is 2-colourable if and only if it is:",
     ["Planar", "Bipartite", "Complete", "Eulerian"], 1, "Equivalently, it has no odd cycle."),
    ("Consider the statements:\nI. Every planar graph can be properly coloured with 4 colours.\nII. Every planar graph needs exactly 4 colours.\nWhich is/are correct?",
     I_II, 0, "Many planar graphs (e.g. trees) need fewer than 4 colours."),
    ("Assertion (A): χ(C7) = 3.\nReason (R): C7 is an odd cycle and therefore not bipartite.",
     AR, 0, "Odd cycles cannot be 2-coloured, and 3 colours suffice."),
]

BIPARTITE = [
    ("A graph is bipartite if:",
     ["It has two vertices", "Its vertex set can be split into two sets so that every edge joins vertices from different sets", "It has two components", "It has an even number of edges"], 1,
     "Equivalently, it is 2-colourable."),
    ("A graph is bipartite if and only if it has no:",
     ["Even cycles", "Odd cycles", "Leaves", "Bridges"], 1, "This is König's characterisation."),
    ("How many edges does the complete bipartite graph K3,4 have?",
     ["7", "12", "21", "14"], 1, "3 × 4 = 12."),
    ("What is the maximum number of edges in a bipartite simple graph with 10 vertices?",
     ["45", "25", "20", "50"], 1, "⌊n²/4⌋ = 25, achieved by K5,5."),
    ("Which of these is always bipartite?",
     ["Any tree", "Any cycle", "Any complete graph", "Any wheel"], 0, "Trees have no cycles, so certainly no odd cycles."),
    ("The cycle C8 is ______ and the cycle C7 is ______.",
     ["bipartite; bipartite", "bipartite; not bipartite", "not bipartite; bipartite", "not bipartite; not bipartite"], 1, "Only even cycles are bipartite."),
    ("Bipartiteness can be tested efficiently by:",
     ["Trying all partitions", "BFS or DFS 2-colouring in O(V + E)", "Computing A³", "Dijkstra's algorithm"], 1, "A conflict (same colour on an edge) reveals an odd cycle."),
    ("The hypercube Qₙ is:",
     ["Never bipartite", "Bipartite", "Bipartite only for even n", "Complete"], 1, "Split vertices by the parity of the number of 1 bits."),
    ("A matching in a graph is:",
     ["A set of edges with no common vertex", "A spanning tree", "A set of vertices", "A cycle"], 0, "A perfect matching covers every vertex."),
    ("How many perfect matchings does K3,3 have?",
     ["3", "6", "9", "27"], 1, "Kn,n has n! perfect matchings: 3! = 6."),
    ("Hall's marriage theorem states that a bipartite graph with parts X and Y has a matching saturating X if and only if:",
     ["|X| = |Y|", "|N(S)| ≥ |S| for every subset S of X", "Every vertex has degree 1", "The graph is complete"], 1, "N(S) is the set of neighbours of S."),
    ("König's theorem states that in a bipartite graph:",
     ["The maximum matching size equals the minimum vertex cover size", "The chromatic number is 3", "Every matching is perfect", "There is an Euler circuit"], 0, "This fails for general graphs, e.g. triangles."),
    ("The Hopcroft–Karp algorithm finds a maximum matching in a bipartite graph in:",
     ["O(V³)", "O(E√V)", "O(2^V)", "O(V + E)"], 1, "It uses augmenting paths found in phases."),
    ("Assigning workers to jobs, where each worker is qualified for certain jobs, is modelled as:",
     ["Graph colouring", "A bipartite matching problem", "A shortest path problem", "Planarity testing"], 1, "Workers and jobs form the two parts."),
    ("Is the triangle K3 bipartite?",
     ["Yes", "No", "Only if directed", "Only with 2 colours"], 1, "It is an odd cycle."),
    ("The star graph K1,n is:",
     ["Bipartite", "Not bipartite", "Complete", "A cycle"], 0, "The centre forms one part and the leaves the other."),
    ("In a bipartite graph with parts X and Y, the sum of the degrees of the vertices in X equals:",
     ["|X|", "|E|", "2|E|", "|Y|"], 1, "Every edge has exactly one endpoint in X."),
    ("Every k-regular bipartite graph (k ≥ 1):",
     ["Has no matching", "Has a perfect matching", "Is complete", "Is a tree"], 1, "This follows from Hall's theorem."),
    ("In Km,n, each vertex of the part of size m has degree:",
     ["m", "n", "m + n", "mn"], 1, "It is adjacent to every vertex of the other part."),
    ("The complete bipartite graph K2,3 has:",
     ["5 vertices and 6 edges", "5 vertices and 5 edges", "6 vertices and 6 edges", "5 vertices and 10 edges"], 0, "2 + 3 vertices and 2 × 3 edges."),
    ("A 3-regular bipartite graph has parts of 5 vertices each. How many edges does it have?",
     ["10", "15", "30", "25"], 1, "5 × 3 = 15 edges."),
    ("The chromatic number of any bipartite graph with at least one edge is:",
     ["1", "2", "3", "4"], 1, "The two parts give a proper 2-colouring."),
    ("With the vertices ordered part X then part Y, the adjacency matrix of a bipartite graph has the block form:",
     ["[[0, B], [Bᵀ, 0]]", "[[B, 0], [0, B]]", "The identity matrix", "All ones"], 0, "There are no edges within a part."),
    ("Is the Petersen graph bipartite?",
     ["Yes", "No, it contains 5-cycles", "Only when directed", "Yes, with parts of size 5"], 1, "Its girth is 5, an odd cycle."),
    ("The hypercube Q3 has a bipartition into two parts of sizes:",
     ["4 and 4", "2 and 6", "3 and 5", "1 and 7"], 0, "Even-weight and odd-weight bit strings."),
    ("A rectangular grid graph (lattice) is:",
     ["Bipartite", "Not bipartite", "Complete", "Non-planar"], 0, "Colour cells like a chessboard."),
    ("Can a bipartite graph contain a triangle?",
     ["Yes", "No", "Only if it is complete", "Only if it is planar"], 1, "A triangle is an odd cycle."),
    ("Km,n is planar if and only if:",
     ["m = n", "min(m, n) ≤ 2", "m + n ≤ 6", "m and n are both even"], 1, "K3,3 is the smallest non-planar complete bipartite graph."),
    ("Consider the statements:\nI. Every tree is bipartite.\nII. Every bipartite graph is a tree.\nWhich is/are correct?",
     I_II, 0, "C4 is bipartite but not a tree."),
    ("Assertion (A): C5 is bipartite.\nReason (R): A graph is bipartite if and only if it contains no odd cycle.",
     AR, 3, "A is false because C5 is itself an odd cycle; R is true."),
]

TOPICS = {
    "Graph Theory – Basics & Paths": [("1 · Simple, Multi and Weighted Graphs", GRAPH_BASICS), ("2 · Paths, Circuits and Shortest Paths", PATHS),
                                      ("3 · Eulerian and Hamiltonian Paths and Circuits", EULER_HAM)],
    "Graph Theory – Planar, Colouring, Bipartite": [("1 · Planar Graphs", PLANAR), ("2 · Graph Colouring", COLOURING), ("3 · Bipartite Graphs", BIPARTITE)],
}
