"""Paper 2 · Unit 4 · Object Oriented Programming; Programming in C++ – Part 1 (6 sub-topics × 30).
References: E. Balagurusamy, Object-Oriented Programming with C++; Stroustrup, The C++ Programming Language; Grady Booch,
Object-Oriented Analysis and Design; Herbert Schildt, Java: The Complete Reference.
C++ code assumes a standard (C++17) compiler with `using namespace std;` and <iostream> included."""
from packlib import AR, I_II

CLASS_OBJECT = [
    ("A class is best described as:",
     ["A blueprint that defines the data members and member functions shared by its objects", "A variable that stores one value", "A run-time instance occupying memory", "A library of C functions"], 0, "Objects are instances created from the class blueprint."),
    ("Creating an object from a class is called:",
     ["Instantiation", "Inheritance", "Encapsulation", "Abstraction"], 0, "Each object is an instance of its class."),
    ("Memory for the (non-static) data members of a class is allocated when:",
     ["An object of the class is created", "The class is declared", "The program is compiled", "A member function is defined"], 0, "A class declaration is only a description; objects occupy memory."),
    ("According to Grady Booch, every object has:",
     ["State, behaviour and identity", "Only data", "Only methods", "Inheritance, polymorphism and encapsulation"], 0, "State = attribute values, behaviour = methods, identity = what distinguishes it from other objects."),
    ("In C++,  Student *p = new Student();  creates the object:",
     ["On the heap, and p holds its address", "On the stack", "In the static data area", "Only at compile time"], 0, "Student s; would create it on the stack (automatic storage)."),
    ("A data member declared static in a class is:",
     ["Shared by all objects of the class – only one copy exists", "Copied into every object", "Accessible only inside main", "Destroyed after each function call"], 0, "It belongs to the class rather than to any object."),
    ("A class has a static int count that its constructor increments. After creating 3 objects, count is:",
     ["3", "1", "0", "Each object has its own count of 1"], 0, "All objects update the same shared variable."),
    ("A C++ class has two int data members (4 bytes each), one static int member and three member functions. On a typical system, sizeof an object of this class is:",
     ["8", "12", "20", "4"], 0, "Static members and member functions are not stored inside each object."),
    ("In object-oriented terms, calling a method on an object is often called:",
     ["Sending a message to the object", "Inheriting the object", "Compiling the object", "Casting the object"], 0, "Objects communicate by message passing (method calls)."),
    ("Inside a C++ member function, the this pointer points to:",
     ["The object on which the function was called", "The first object ever created", "The class definition", "The base class"], 0, "It lets a member function refer to its own object."),
    ("A language that supports objects and encapsulation but NOT inheritance is called:",
     ["Object-based", "Object-oriented", "Procedural only", "Functional"], 0, "Object-oriented languages add inheritance (and dynamic binding) to object-based features."),
    ("In C++, the only difference between a class and a struct is that:",
     ["Members of a class are private by default, while those of a struct are public by default", "A struct cannot have member functions", "A class cannot have data members", "A struct cannot be instantiated"], 0, "Default inheritance access also differs in the same way."),
    ("Abstraction in OOP means:",
     ["Showing only the essential features of an object and hiding the unnecessary details", "Copying one object into another", "Deriving one class from another", "Converting one type into another"], 0, "E.g. a driver uses the steering and brakes without knowing the engine's details."),
    ("Instance variables and class variables differ in that:",
     ["Each object has its own copy of an instance variable, while a class variable is shared by all objects", "Class variables belong to a single object", "Instance variables are always static", "There is no difference"], 0, "In Java and C++ class variables are declared static."),
    ("In Java,  String s1 = new String(\"hi\"); String s2 = new String(\"hi\");  the values of  s1 == s2  and  s1.equals(s2)  are:",
     ["false and true", "true and true", "true and false", "false and false"], 0, "== compares references (identity); equals compares contents (state)."),
    ("Which language is usually called a 'pure' object-oriented language, since everything in it is an object?",
     ["Smalltalk", "C++", "Java", "C"], 0, "Java has primitive types that are not objects; C++ supports procedural code too."),
    ("In a UML class diagram, the three compartments of a class box show:",
     ["Class name, attributes and operations", "Objects, arrays and files", "Inputs, outputs and errors", "Constructors, destructors and friends"], 0, "Attributes model state; operations model behaviour."),
    ("In UML, the visibility symbols +, − and # mean respectively:",
     ["public, private, protected", "private, public, protected", "protected, private, public", "public, protected, private"], 0, "~ is used for package visibility."),
    ("The C++ declaration  Student s[10];  calls the default constructor of Student:",
     ["10 times", "Once", "Never", "11 times"], 0, "Each array element is a separately constructed object."),
    ("Match the OOP term with its meaning:\na. Class  b. Object  c. Method  d. Attribute\n1. Holds part of an object's state  2. Defines behaviour  3. Instance occupying memory  4. Blueprint or template",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-3, c-1, d-2", "a-4, b-2, c-3, d-1"], 0, "Attributes are data members; methods are member functions."),
    ("A bank account is modelled as a class. Which is the best choice of members?",
     ["Attributes: account number, balance; methods: deposit(), withdraw(), getBalance()", "Attributes: deposit(), withdraw(); methods: balance", "Only a global balance variable", "One function that does everything"], 0, "Data (state) and the operations on it are grouped in one class."),
    ("An object created without being given a name, for example  Point(2, 3).show();  in C++, is called:",
     ["An anonymous (temporary) object", "A static object", "A friend object", "An abstract object"], 0, "It exists only until the end of the full expression."),
    ("Consider the statements:\nI. A class is a logical entity, while an object is a run-time entity that occupies memory.\nII. A class definition by itself allocates memory for its non-static data members.\nWhich is/are correct?",
     I_II, 0, "Memory is allocated only when objects are created."),
    ("Consider the statements:\nI. In Java, objects are created at run time using new.\nII. In C++, objects can be created either on the stack or on the heap.\nWhich is/are correct?",
     I_II, 2, "Java objects always live on the heap; C++ allows automatic and dynamic objects."),
    ("Consider the statements:\nI. Two different objects of the same class can have the same state.\nII. Two objects with the same state are the same object.\nWhich is/are correct?",
     I_II, 0, "Identity is separate from state: equal values do not make them one object."),
    ("Assertion (A): Memory for non-static data members is allocated separately for each object.\nReason (R): Each object has its own state.",
     AR, 0, "Separate storage is needed so each object can hold its own values."),
    ("Assertion (A): A static data member is copied into every object of the class.\nReason (R): A static data member is shared by all objects of the class.",
     AR, 3, "Because it is shared, there is exactly one copy; R shows why A is false."),
    ("Assertion (A): Smalltalk is considered a pure object-oriented language.\nReason (R): Simula 67 introduced the concepts of class and object.",
     AR, 1, "Both true; Smalltalk's purity comes from treating everything as an object, not from Simula's history."),
    ("Assertion (A): The code of member functions is stored once per class, not once per object.\nReason (R): Every object keeps its own copy of the code of each member function.",
     AR, 2, "A is true; R is false – objects share the code and are passed to it through this."),
    ("A C++ class Box has a static data member count. The correct way to access it without any object is:",
     ["Box::count", "Box.count", "this->count", "count() only"], 0, "Static members can be accessed through the class name and the scope resolution operator."),
]

INHERIT_ENCAP = [
    ("Inheritance allows a new class to:",
     ["Acquire the members of an existing class and add or change features", "Hide all its data from other classes", "Be used without creating objects", "Run faster than its base class"], 0, "It supports reuse and represents an 'is-a' relationship."),
    ("Inheritance models which relationship between classes?",
     ["is-a", "has-a", "uses-a", "part-of"], 0, "A Dog is an Animal; 'has-a' is composition/aggregation."),
    ("Class C is derived from B, and B is derived from A. This is:",
     ["Multilevel inheritance", "Multiple inheritance", "Hierarchical inheritance", "Hybrid inheritance"], 0, "A chain of derivations is multilevel."),
    ("One base class Shape with derived classes Circle, Square and Triangle is an example of:",
     ["Hierarchical inheritance", "Multilevel inheritance", "Multiple inheritance", "Single inheritance"], 0, "Many derived classes share one base."),
    ("A class derived from two base classes at the same time shows:",
     ["Multiple inheritance", "Multilevel inheritance", "Hierarchical inheritance", "Single inheritance"], 0, "C++ allows it; Java allows it only through interfaces."),
    ("The 'diamond problem' of multiple inheritance is solved in C++ by:",
     ["Virtual base classes", "Friend functions", "Static members", "Inline functions"], 0, "A virtual base ensures that only one copy of the common base is inherited."),
    ("A → B → C is multilevel inheritance, and each constructor prints its class name and each destructor prints '~' and its name. Creating and then destroying an object of C prints:",
     ["A B C ~C ~B ~A", "C B A ~A ~B ~C", "A B C ~A ~B ~C", "C B A ~C ~B ~A"], 0, "Constructors run from base to derived; destructors in the reverse order."),
    ("'A Car has an Engine' is best modelled by:",
     ["Composition (the Car contains an Engine object)", "Making Car inherit from Engine", "Making Engine inherit from Car", "Multiple inheritance"], 0, "A car is not a kind of engine, so inheritance is wrong here."),
    ("Encapsulation refers to:",
     ["Binding data and the functions that operate on it into one unit and restricting direct access to the data", "Deriving new classes from old ones", "Using one name for many functions", "Converting source code into object code"], 0, "Data hiding is achieved with access specifiers."),
    ("In C++, a private member of a class can be accessed:",
     ["Only by member functions and friends of that class", "By any function in the program", "By derived classes directly", "Only by main()"], 0, "Even derived classes cannot access private members directly."),
    ("A protected member of a C++ class is accessible:",
     ["In its own class and in classes derived from it", "Only in its own class", "Everywhere in the program", "Only in friend classes of derived classes"], 0, "protected lies between private and public."),
    ("With  class B : public A ,  the public and protected members of A become in B respectively:",
     ["public and protected", "private and private", "protected and protected", "public and private"], 0, "Private members of A remain inaccessible in B."),
    ("With  class B : private A ,  the public and protected members of A become in B:",
     ["private", "public", "protected", "inaccessible even inside B"], 0, "They can be used inside B but are hidden from B's users and from classes derived from B."),
    ("A has a private x, a protected y and a public z.  class B : private A { };  class C : public B { };  Which of x, y, z can be used directly inside member functions of C?",
     ["None of them", "y and z", "Only z", "x, y and z"], 0, "In B, y and z became private, and x was never accessible; private members of B are not accessible in C."),
    ("Public 'getter' and 'setter' methods for a private field mainly help to:",
     ["Control and validate access to the data", "Make the data public", "Remove the need for a constructor", "Enable multiple inheritance"], 0, "E.g. setAge() can reject negative values."),
    ("Arrange Java access levels from most restrictive to least restrictive:",
     ["private → default (package) → protected → public", "public → protected → default → private", "default → private → protected → public", "private → protected → default → public"], 0, "protected also grants access to subclasses in other packages."),
    ("In Java, the keyword used to call the constructor of the immediate superclass is:",
     ["super", "this", "base", "parent"], 0, "super(...) must be the first statement of the subclass constructor."),
    ("In Java, a class declared final:",
     ["Cannot be inherited", "Cannot be instantiated", "Must be abstract", "Cannot have methods"], 0, "String is a final class."),
    ("Java does not allow a class to extend two classes mainly to avoid:",
     ["Ambiguity such as the diamond problem", "Faster compilation", "The use of interfaces", "Garbage collection"], 0, "Multiple inheritance of type is still possible through interfaces."),
    ("Match the inheritance type with its structure:\na. Single  b. Multiple  c. Multilevel  d. Hierarchical\n1. One base, many derived  2. A → B → C  3. Two or more bases, one derived  4. One base, one derived",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Hybrid inheritance combines two or more of these."),
    ("The principle that an object of a derived class should be usable wherever an object of its base class is expected is the:",
     ["Liskov substitution principle", "Open–closed principle", "Single-responsibility principle", "Principle of locality"], 0, "It keeps inheritance hierarchies correct (the L of SOLID)."),
    ("'A Dog is an Animal, and a Dog has a Tail.' These relationships are respectively:",
     ["Inheritance and composition", "Composition and inheritance", "Both inheritance", "Both composition"], 0, "is-a → inheritance; has-a → composition/aggregation."),
    ("Consider the statements:\nI. In multilevel inheritance the base class constructor executes before the derived class constructor.\nII. Destructors execute in the same order as constructors.\nWhich is/are correct?",
     I_II, 0, "Destructors run in the reverse order."),
    ("Consider the statements:\nI. Composition represents an is-a relationship.\nII. Inheritance represents an is-a relationship.\nWhich is/are correct?",
     I_II, 1, "Composition represents has-a."),
    ("Consider the statements:\nI. Encapsulation makes it possible to change a class's internal data representation without affecting its users.\nII. Inheritance can increase coupling between base and derived classes.\nWhich is/are correct?",
     I_II, 2, "Hidden data can change freely; derived classes depend on their base (the 'fragile base class' problem)."),
    ("Assertion (A): Inheritance promotes reuse of code.\nReason (R): A derived class acquires the members of its base class.",
     AR, 0, "Inherited members need not be rewritten."),
    ("Assertion (A): Java supports multiple inheritance through interfaces.\nReason (R): A Java class can extend more than one class.",
     AR, 2, "A is true (a class can implement many interfaces); R is false."),
    ("Assertion (A): Private members of a base class are directly accessible in a derived class in C++.\nReason (R): Private members are accessible only within the class that declares them and its friends.",
     AR, 3, "R is the rule, and it shows why A is false."),
    ("Assertion (A): Encapsulation supports data hiding.\nReason (R): C++ provides three access specifiers: public, private and protected.",
     AR, 1, "Both true; data hiding comes from restricting access, while the number of specifiers is incidental."),
    ("A combination of multiple and multilevel inheritance in one class hierarchy is called:",
     ["Hybrid inheritance", "Hierarchical inheritance", "Single inheritance", "Virtual inheritance"], 0, "The diamond shape is a common hybrid hierarchy."),
]

POLYMORPHISM = [
    ("Polymorphism in OOP means:",
     ["The same name or interface behaving differently depending on the type of object or arguments", "Hiding data inside a class", "Creating objects from classes", "Deriving a class from two classes"], 0, "Greek: 'many forms'."),
    ("Which of the following is compile-time (static) polymorphism?",
     ["Function overloading and operator overloading", "Virtual functions", "Method overriding through base references", "Dynamic binding"], 0, "The compiler chooses the function from the argument types."),
    ("Run-time polymorphism in C++ is achieved through:",
     ["Virtual functions called through base-class pointers or references", "Function overloading", "Templates", "Macros"], 0, "The call is bound at run time to the actual object's function (late binding)."),
    ("An abstract class is a class that:",
     ["Cannot be instantiated and is meant to be used as a base class", "Has no member functions", "Has only static members", "Cannot be inherited"], 0, "It usually declares abstract (pure virtual) methods that derived classes implement."),
    ("In C++, a pure virtual function is declared as:",
     ["virtual void draw() = 0;", "void draw() = 0;", "abstract void draw();", "virtual void draw() {}"], 0, "A class with at least one pure virtual function is abstract."),
    ("A class derived from an abstract class that does NOT override all the pure virtual functions:",
     ["Is also abstract", "Becomes concrete automatically", "Causes a run-time error when compiled", "Cannot have constructors"], 0, "It can be instantiated only after all pure virtual functions are defined."),
    ("What does this C++ code print?\nclass A { public: virtual void f() { cout << \"A\"; } void g() { cout << \"a\"; } };\nclass B : public A { public: void f() { cout << \"B\"; } void g() { cout << \"b\"; } };\nA *p = new B; p->f(); p->g();",
     ["Ba", "BA", "Ab", "Bb"], 0, "f is virtual, so B::f runs; g is not virtual, so the pointer type A decides: A::g."),
    ("In Java,  Animal a = new Dog();  a.sound();  where Dog overrides sound(), calls:",
     ["Dog's sound()", "Animal's sound()", "Both, in order", "Neither – it is a compile error"], 0, "Java instance methods are virtual by default (dynamic method dispatch)."),
    ("C++ compilers usually implement virtual function calls using:",
     ["A virtual table (vtable) per class and a hidden pointer (vptr) in each object", "A separate thread per object", "Macros", "The symbol table at run time"], 0, "The vptr locates the right function in the vtable."),
    ("On a typical 64-bit compiler, a class with one int data member and one virtual function has sizeof equal to:",
     ["16", "4", "8", "12"], 0, "An 8-byte vptr plus a 4-byte int, padded to a multiple of 8."),
    ("Converting a derived-class pointer to a base-class pointer is called:",
     ["Upcasting – always safe", "Downcasting – always safe", "Upcasting – never allowed", "Slicing"], 0, "Downcasting (base to derived) needs a check such as dynamic_cast."),
    ("Match the kind of polymorphism with an example:\na. Ad hoc  b. Parametric  c. Subtype (inclusion)\n1. A function template max<T>  2. Overriding draw() in subclasses of Shape  3. Overloading + for int and complex",
     ["a-3, b-1, c-2", "a-1, b-3, c-2", "a-3, b-2, c-1", "a-2, b-1, c-3"], 0, "Cardelli and Wegner's classification of polymorphism."),
    ("A virtual destructor is needed in a base class when:",
     ["Derived objects are deleted through a base-class pointer", "The class has no data members", "The class is never inherited", "Objects are created only on the stack"], 0, "Otherwise only the base destructor runs, which can leak the derived part's resources."),
    ("Which statement about interfaces and abstract classes in Java is correct?",
     ["A class can implement many interfaces but can extend only one abstract class", "A class can extend many abstract classes", "Interfaces can have constructors", "Abstract classes cannot have concrete methods"], 0, "Abstract classes can have constructors, fields and concrete methods."),
    ("In Java, a method declared final:",
     ["Cannot be overridden in a subclass", "Cannot be called", "Must be abstract", "Is always static"], 0, "final on a class prevents inheritance; on a method it prevents overriding."),
    ("Which C++ operator can NOT be overloaded?",
     [":: (scope resolution)", "+", "[]", "<<"], 0, "::, ., .*, ?: and sizeof cannot be overloaded."),
    ("Overloading and overriding differ in that:",
     ["Overloading uses the same name with different parameter lists; overriding redefines a base-class method with the same signature in a derived class", "They are the same thing", "Overriding needs different parameter lists", "Overloading needs inheritance"], 0, "Overloading is resolved at compile time; overriding (with virtual) at run time."),
    ("Java has overloaded methods  void f(int x)  and  void f(double x).  The call f('a') invokes:",
     ["f(int), because char widens to int", "f(double) only", "Neither – compile error", "Both"], 0, "The most specific applicable widening conversion (char → int) is chosen."),
    ("Which of the following is NOT a form of polymorphism?",
     ["Encapsulation", "Function overloading", "Operator overloading", "Virtual functions"], 0, "Encapsulation is about bundling and hiding data."),
    ("A Shape array holds Circle and Rectangle objects, and each class overrides area(). Calling area() on every element through Shape references is an example of:",
     ["Run-time polymorphism", "Function overloading", "Encapsulation", "Multiple inheritance"], 0, "The same call executes different code depending on each object's class."),
    ("Consider the statements:\nI. Constructors can be declared virtual in C++.\nII. Destructors can be declared virtual in C++.\nWhich is/are correct?",
     I_II, 1, "An object's exact type must be known to construct it, so constructors cannot be virtual."),
    ("Consider the statements:\nI. A reference of an abstract class type can refer to an object of a concrete derived class.\nII. An abstract class can have concrete (non-abstract) methods.\nWhich is/are correct?",
     I_II, 2, "Both are allowed in C++ and Java."),
    ("Consider the statements:\nI. In Java, static methods can be overridden like instance methods.\nII. In Java, private methods take part in dynamic dispatch.\nWhich is/are correct?",
     I_II, 3, "Static methods are hidden, not overridden, and private methods are not inherited, so neither takes part in dynamic dispatch."),
    ("Assertion (A): Virtual functions support run-time polymorphism.\nReason (R): The function to be called is chosen at run time from the type of the object actually pointed to.",
     AR, 0, "That late binding is exactly run-time polymorphism."),
    ("Assertion (A): Objects of an abstract class can be created with new.\nReason (R): In C++, an abstract class has at least one pure virtual function.",
     AR, 3, "Because of the pure virtual function, the class cannot be instantiated; R shows why A is false."),
    ("Assertion (A): Java programmers cannot overload operators such as + for their own classes.\nReason (R): Java supports method overriding.",
     AR, 1, "Both true but unrelated; Java's designers left out operator overloading for simplicity."),
    ("Assertion (A): A class that has a pure virtual function is abstract.\nReason (R): An abstract class cannot have any data members.",
     AR, 2, "A is true; R is false – abstract classes can have data members and constructors."),
    ("Assertion (A): Function overloading is resolved at compile time.\nReason (R): Overloaded functions differ in the number or types of their parameters, which the compiler can see.",
     AR, 0, "The compiler picks the best match from the argument types."),
    ("Which statement about abstract classes is TRUE in both C++ and Java?",
     ["An abstract class can have a constructor, which runs when a derived object is created", "An abstract class cannot have any methods", "An abstract class can be instantiated if it has no data", "An abstract class cannot be used as a reference type"], 0, "The constructor initialises the base part of each derived object."),
    ("Binding a function call to the function body at run time is called:",
     ["Late (dynamic) binding", "Early (static) binding", "Name mangling", "Linking"], 0, "Non-virtual calls use early binding at compile time."),
]

CPP_BASICS = [
    ("Which of the following is NOT a C++ token category?",
     ["Comments", "Keywords", "Identifiers", "Operators"], 0, "Tokens are keywords, identifiers, constants (literals), strings and operators/punctuators; comments are removed."),
    ("The values of the C++ built-in type bool are:",
     ["true and false", "0 and 1 only", "yes and no", "T and F"], 0, "bool converts to 1 and 0 in arithmetic."),
    ("What does  cout << 7 / 2 << \" \" << 7 / 2.0;  print?",
     ["3 3.5", "3.5 3.5", "3 3", "4 3.5"], 0, "int / int is integer division; one double operand gives floating division."),
    ("What does this print?\nint x = 10;\nint main() { int x = 20; cout << ::x; }",
     ["10", "20", "30", "Compile error"], 0, "::x names the global x, hidden by the local x."),
    ("What does this print?\nint a = 5; int &r = a; r = 10; cout << a;",
     ["10", "5", "15", "Address of a"], 0, "r is another name (alias) for a."),
    ("In C++, sizeof('a') is:",
     ["1, because a character literal has type char", "4, because it is an int", "2", "Implementation-defined but always 4"], 0, "This differs from C, where 'a' has type int."),
    ("With C++11,  auto x = 3.0;  gives x the type:",
     ["double", "float", "int", "auto"], 0, "auto deduces the type from the initialiser; 3.0 is a double literal."),
    ("Compared with malloc/free, the C++ operators new/delete:",
     ["Call constructors and destructors, and need no casts or size calculations", "Are slower and never call constructors", "Work only for built-in types", "Allocate on the stack"], 0, "new T returns a T*; delete calls the destructor before freeing."),
    ("In  cout << \"Hi\";  and  cin >> x; , the operators << and >> are called:",
     ["Insertion and extraction operators", "Left and right shift only", "Scope and member operators", "Increment operators"], 0, "They are overloaded for streams."),
    ("Which is NOT a C++ keyword?",
     ["then", "class", "virtual", "namespace"], 0, "C++ has no 'then'; if is followed directly by a statement."),
    ("Which cast performs a run-time checked downcast in a polymorphic class hierarchy?",
     ["dynamic_cast", "static_cast", "const_cast", "reinterpret_cast"], 0, "It returns nullptr (or throws for references) if the cast is invalid."),
    ("Match the C++ cast with its main use:\na. static_cast  b. const_cast  c. reinterpret_cast  d. dynamic_cast\n1. Checked conversion in a class hierarchy  2. Low-level reinterpretation of bits/pointers  3. Adding or removing const  4. Ordinary well-defined conversions such as double to int",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Named casts make the intent of a conversion explicit."),
    ("After  int i = 3.7;  the value of i is:",
     ["3", "4", "3.7", "Compile error"], 0, "Floating-to-integer conversion truncates toward zero."),
    ("The statement  using namespace std;  allows a program to:",
     ["Use names such as cout and endl without the std:: prefix", "Include the <iostream> header", "Create a new namespace", "Define the std library"], 0, "The header must still be included."),
    ("With C++11,  enum class Color { Red, Green };  differs from a plain enum because:",
     ["Its enumerators are scoped (Color::Red) and do not convert implicitly to int", "It cannot have values", "It stores strings", "It must be declared inside a class"], 0, "Scoped enums avoid name clashes and accidental conversions."),
    ("What does this print?\nint a[] = {1, 2, 3}; int s = 0;\nfor (int x : a) s += x;\ncout << s;",
     ["6", "3", "123", "0"], 0, "The range-based for loop visits each element."),
    ("What does this print?\nfor (int i = 10; i > 0; i -= 3) cout << i << \" \";",
     ["10 7 4 1", "10 7 4 1 -2", "10 7 4", "7 4 1"], 0, "The loop stops when i becomes −2."),
    ("What does this print?\nint i = 0, s = 0;\nwhile (i < 5) { i++; if (i == 3) continue; s += i; }\ncout << s;",
     ["12", "15", "10", "9"], 0, "1 + 2 + 4 + 5 = 12 (3 is skipped)."),
    ("What does  cout << (5 > 3 ? \"yes\" : \"no\");  print?",
     ["yes", "no", "1", "5"], 0, "The conditional operator selects the first string."),
    ("The manipulator endl differs from '\\n' in that it:",
     ["Also flushes the output buffer", "Prints two new lines", "Works only with cin", "Clears the screen"], 0, "Frequent flushing can slow down output."),
    ("A constant whose value must be computable at compile time is best declared in modern C++ with:",
     ["constexpr", "volatile", "mutable", "register"], 0, "const only promises that the value will not change after initialisation."),
    ("Consider the statements:\nI. A C++ reference must be initialised when it is declared.\nII. A C++ reference can later be changed to refer to another variable.\nWhich is/are correct?",
     I_II, 0, "A reference is bound once; assigning to it changes the referred variable instead."),
    ("Consider the statements:\nI. In C++, a variable can be declared anywhere a statement can appear, e.g. inside a for header.\nII. In C++, the type wchar_t is used for wide characters.\nWhich is/are correct?",
     I_II, 2, "Both are true."),
    ("Consider the statements:\nI. In C++, a void* can be assigned to an int* without a cast.\nII. In C++, main() must return int.\nWhich is/are correct?",
     I_II, 1, "Unlike C, C++ needs an explicit cast from void*; main must have return type int."),
    ("Assertion (A): Inside a function,  ::x  refers to the global x even when a local x exists.\nReason (R): The unary scope resolution operator selects the global namespace.",
     AR, 0, "That is the purpose of the unary :: operator."),
    ("Assertion (A): In C++, sizeof('a') equals sizeof(int).\nReason (R): In C++, a character literal has type char.",
     AR, 3, "Because 'a' is a char, sizeof('a') is 1; R shows why A is false."),
    ("Assertion (A): new calls the constructor of the object it creates.\nReason (R): new and malloc are identical in C++.",
     AR, 2, "A is true; R is false – malloc only allocates raw memory."),
    ("Assertion (A): bool is a built-in type in C++.\nReason (R): C++ supports reference variables.",
     AR, 1, "Both true but unrelated."),
    ("What does this print?\nchar c = 'A'; switch (c) { case 'A': cout << 1; case 'B': cout << 2; break; default: cout << 3; }",
     ["12", "1", "123", "2"], 0, "Without break after case 'A', control falls through to case 'B'."),
    ("Which statement about the C++ string class (std::string) is correct?",
     ["It manages its own memory and supports + for concatenation and == for comparison", "It is identical to a C char array", "It cannot be compared", "It needs strcpy for assignment"], 0, "It is defined in <string>."),
]

CPP_FUNCTIONS = [
    ("An inline function in C++:",
     ["Is a request to the compiler to expand the function body at each call, avoiding call overhead", "Is always expanded, whatever its size", "Cannot have parameters", "Runs on a separate thread"], 0, "The compiler may ignore the request, e.g. for recursive functions."),
    ("Which declaration with default arguments is valid?",
     ["void f(int a, int b = 5);", "void f(int a = 1, int b);", "void f(int a = 1, int b, int c = 3);", "void f(= 1 int a);"], 0, "Default arguments must be given from the right-most parameter leftwards."),
    ("Given  int f(int a, int b = 10) { return a * b; } ,  f(2) returns:",
     ["20", "2", "12", "Compile error"], 0, "b takes its default value 10."),
    ("Given  int g(int x = 2, int y = 3) { return x - y; } ,  what does  cout << g() << \" \" << g(5) << \" \" << g(5, 1);  print?",
     ["-1 2 4", "-1 -1 4", "2 5 4", "-1 2 -4"], 0, "g() = 2 − 3; g(5) = 5 − 3; g(5, 1) = 5 − 1."),
    ("What does this print?\nvoid swap(int &a, int &b) { int t = a; a = b; b = t; }\nint main() { int x = 1, y = 2; swap(x, y); cout << x << y; }",
     ["21", "12", "11", "22"], 0, "Reference parameters are aliases of the arguments."),
    ("What does this print?\nvoid f(int x) { x = 100; }\nint main() { int a = 1; f(a); cout << a; }",
     ["1", "100", "0", "101"], 0, "Pass by value copies the argument."),
    ("What does this print?\nvoid f(int &x) { x += 5; }\nint main() { int a = 1; f(a); f(a); cout << a; }",
     ["11", "6", "1", "10"], 0, "Each call adds 5 to a itself."),
    ("What does this print?\nvoid g(int *p) { *p = *p * 2; }\nint main() { int a = 3; g(&a); cout << a; }",
     ["6", "3", "9", "Address of a"], 0, "The function writes through the pointer."),
    ("What does this print?\nint& bigger(int &a, int &b) { return a > b ? a : b; }\nint main() { int x = 3, y = 7; bigger(x, y) = 0; cout << x << \" \" << y; }",
     ["3 0", "0 7", "3 7", "0 0"], 0, "Returning a reference lets the call be used as an l-value; the larger variable, y, becomes 0."),
    ("A large object is passed to a function that must not modify it. The best parameter type is:",
     ["const T&", "T (by value)", "T*", "T&"], 0, "No copy is made, and const prevents modification."),
    ("Which call is INVALID for  void h(int &x); ?",
     ["h(5);", "int a = 5; h(a);", "int b; h(b);", "int &r = a; h(r); (with int a)"], 0, "A non-const reference cannot bind to a literal (an r-value)."),
    ("What does this print?\nauto sq = [](int x) { return x * x; };\ncout << sq(4);",
     ["16", "8", "4", "Compile error"], 0, "A lambda expression defines an unnamed function object (C++11)."),
    ("What does f(4) return?\nint f(int n) { return n <= 1 ? 1 : n * f(n - 1); }",
     ["24", "10", "16", "4"], 0, "4 × 3 × 2 × 1."),
    ("Default argument values are normally written:",
     ["In the function declaration (prototype), and not repeated in the definition", "Only in the function call", "In both the declaration and the definition", "In a separate header only for main"], 0, "Repeating them in the definition is an error when a prototype already has them."),
    ("Returning a reference to a local (automatic) variable from a function:",
     ["Gives a dangling reference, because the local is destroyed when the function returns", "Is always safe", "Makes the local variable static", "Is required for recursion"], 0, "Returning a reference to a static or member variable is safe."),
    ("When an array is passed to a C++ function as  void f(int a[]) , the function receives:",
     ["A pointer to the first element", "A full copy of the array", "The array's size automatically", "A reference to a vector"], 0, "The size must be passed separately (or use std::array/std::vector)."),
    ("The compiler is most likely to IGNORE an inline request for a function that:",
     ["Is recursive or contains large loops", "Returns an int", "Has one parameter", "Is very small"], 0, "Expanding such functions would bloat the code or be impossible."),
    ("Match the parameter-passing method with its effect:\na. By value  b. By reference  c. By pointer  d. By const reference\n1. No copy, cannot modify the argument  2. Receives an address; changes are made through *  3. Alias of the argument; changes are visible to the caller  4. A copy; changes are not visible to the caller",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "C++ supports all four styles."),
    ("A function that calls itself directly or indirectly is called:",
     ["Recursive", "Inline", "Virtual", "Friend"], 0, "Each call has its own activation record."),
    ("In C++, main() returning 0 conventionally means:",
     ["The program ended successfully", "An error occurred", "The program will restart", "Nothing – the value is ignored by the language"], 0, "Reaching the end of main without return also returns 0."),
    ("Consider the statements:\nI. A non-const reference parameter cannot bind to a literal such as 5.\nII. A const reference parameter can bind to a literal such as 5.\nWhich is/are correct?",
     I_II, 2, "A const reference can bind to a temporary created from the literal."),
    ("Consider the statements:\nI. Returning a reference to a local variable is safe.\nII. Returning a reference to a static local variable is safe.\nWhich is/are correct?",
     I_II, 1, "A static local lives for the whole program."),
    ("Consider the statements:\nI. C++ lets a function modify the caller's variable through a reference parameter.\nII. C++ passes all arguments by reference by default.\nWhich is/are correct?",
     I_II, 0, "The default is pass by value."),
    ("Assertion (A): Passing a large object by const reference is efficient.\nReason (R): No copy is made, and the function cannot modify the object.",
     AR, 0, "It combines the efficiency of references with the safety of pass by value."),
    ("Assertion (A): Inline functions can reduce function-call overhead.\nReason (R): The compiler must always inline every function declared inline.",
     AR, 2, "A is true; R is false – inline is only a request."),
    ("Assertion (A): Default arguments may appear in any order in the parameter list.\nReason (R): Default arguments must be supplied from the right-most parameter leftwards.",
     AR, 3, "R is the rule, and it shows why A is false."),
    ("Assertion (A): In C++ a function can change the caller's variable through a reference parameter.\nReason (R): C++ also supports pointers.",
     AR, 1, "Both true, but pointers are a separate mechanism and do not explain reference parameters."),
    ("A function prototype such as  int area(int, int);  mainly allows the compiler to:",
     ["Check the number and types of arguments in each call before the function is defined", "Allocate memory for the function", "Inline the function", "Make the function recursive"], 0, "C++ requires a declaration before a function is called."),
    ("What does this print?\nint counter() { static int c = 0; return ++c; }\nint main() { counter(); counter(); cout << counter(); }",
     ["3", "1", "0", "2"], 0, "The static local keeps its value between calls."),
    ("What does this print?\nvoid show(int a, int b = 2, int c = 3) { cout << a + b + c; }\nint main() { show(1, 5); }",
     ["9", "6", "8", "11"], 0, "c takes its default: 1 + 5 + 3."),
]

CPP_CLASSES = [
    ("Members of a C++ class are, by default:",
     ["private", "public", "protected", "static"], 0, "Members of a struct are public by default."),
    ("A member function defined inside the class body is:",
     ["Implicitly inline", "Always virtual", "Always static", "Not allowed in C++"], 0, "Functions defined outside use ClassName::function and are not inline unless declared so."),
    ("To define the member function show() of class Student outside the class, one writes:",
     ["void Student::show() { … }", "void show::Student() { … }", "void Student.show() { … }", "Student void show() { … }"], 0, "The scope resolution operator ties the function to its class."),
    ("Which statement about constructors is correct?",
     ["A constructor has the same name as its class, has no return type and is called automatically when an object is created", "A constructor must return void", "A constructor must be called explicitly after creating an object", "A class can have only one constructor"], 0, "Constructors can be overloaded."),
    ("If a class declares no constructor at all, the compiler:",
     ["Supplies a default constructor", "Reports an error", "Makes the class abstract", "Prevents objects from being created"], 0, "Once any constructor is declared, the implicit default constructor is no longer generated."),
    ("A copy constructor of class A has the form:",
     ["A(const A &other)", "A(A other)", "A(int)", "~A()"], 0, "Taking the parameter by value would itself require a copy, causing infinite recursion."),
    ("In which situation is the copy constructor NOT normally called?",
     ["When an existing object is assigned to another existing object (a = b;)", "When an object is initialised from another (A b = a;)", "When an object is passed to a function by value", "When a function returns an object by value (unless elided)"], 0, "a = b; calls the copy assignment operator, not the copy constructor."),
    ("A destructor:",
     ["Has the class name preceded by ~, takes no arguments, has no return type and cannot be overloaded", "Can take arguments", "Must be called explicitly", "Can be overloaded like constructors"], 0, "A class has exactly one destructor."),
    ("What does this print?\nclass T { public: T() { cout << \"C\"; } ~T() { cout << \"D\"; } };\nint main() { T a; { T b; } T c; }",
     ["CCDCDD", "CCCDDD", "CDCDCD", "CCDDCD"], 0, "a: C; b: C then D at the end of its block; c: C; at the end of main, c then a are destroyed: DD."),
    ("What does this print?\nclass A { int x; public: A(int v) : x(v) {} int get() { return x; } };\nint main() { A a(5); cout << a.get(); }",
     ["5", "0", "Garbage", "Compile error"], 0, "The member initialiser list sets x to 5."),
    ("A constructor's member initialiser list is REQUIRED to initialise:",
     ["const data members and reference data members", "Only static members", "Only public members", "Nothing – it is always optional"], 0, "They cannot be assigned after construction."),
    ("Inside a member function,  this->x = x;  is used to:",
     ["Assign the parameter x to the data member x when the parameter hides the member", "Create a new object", "Call the destructor", "Declare a static variable"], 0, "this->x names the member; plain x names the parameter."),
    ("A static member function of a class:",
     ["Has no this pointer and can directly access only static members", "Can access every non-static member directly", "Must be virtual", "Is called only through an object"], 0, "It is called as ClassName::function()."),
    ("A friend function of a class is:",
     ["A non-member function that is allowed to access the class's private and protected members", "A member function declared public", "A function that is inherited automatically", "A constructor"], 0, "Friendship is granted by the class, and it is not inherited or transitive."),
    ("The compiler-generated copy constructor copies pointer members:",
     ["Member by member (a shallow copy), so both objects point to the same memory", "By allocating new memory (a deep copy)", "By setting them to nullptr", "It does not copy pointers at all"], 0, "Classes that own dynamic memory need a user-defined deep copy."),
    ("A member function declared as  int get() const;  :",
     ["Cannot modify the object's non-mutable data members", "Returns a constant", "Can only be called on const objects", "Is automatically static"], 0, "const objects can call only const member functions."),
    ("The 'rule of three' says that a class which needs a user-defined destructor usually also needs a user-defined:",
     ["Copy constructor and copy assignment operator", "Friend function and static member", "Virtual function and template", "Default constructor only"], 0, "All three deal with owning resources such as dynamic memory."),
    ("class A { public: A(int) {} };  The statement  A a = 5;  :",
     ["Is valid; the constructor A(int) acts as a converting constructor", "Is a compile error because 5 is not an object", "Calls the copy assignment operator", "Is valid only if A has a default constructor"], 0, "Declaring the constructor explicit would forbid this implicit conversion."),
    ("A class has  static int count;  incremented in its constructor and decremented in its destructor. main() creates objects a, b and c, and then one more object inside an inner block that ends. What is count after the block?",
     ["3", "4", "0", "1"], 0, "The block's object is destroyed at the end of the block."),
    ("Match the constructor with its description:\na. Default  b. Parameterised  c. Copy  d. Converting\n1. Single-argument constructor used for implicit conversion  2. Creates an object from another object of the same class  3. Takes arguments to initialise members  4. Takes no arguments",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "A class can have several constructors (overloading)."),
    ("For the array  Point pts[5];  to compile, class Point must have:",
     ["A default constructor", "A copy constructor only", "A virtual destructor", "A friend function"], 0, "Each element is created with the default constructor."),
    ("Which statement about a class's static data member in C++ is correct?",
     ["It is declared inside the class and (before C++17 inline variables) defined once outside it, e.g. int A::count = 0;", "It is created separately in every object", "It cannot be private", "It is destroyed with the first object"], 0, "It exists even if no objects are created."),
    ("Consider the statements:\nI. A static member function has no this pointer.\nII. A static member function can directly access non-static data members.\nWhich is/are correct?",
     I_II, 0, "Without a this pointer, it has no object whose members it could use."),
    ("Consider the statements:\nI. Const data members must be initialised in the constructor's initialiser list.\nII. Reference data members must be initialised in the constructor's initialiser list.\nWhich is/are correct?",
     I_II, 2, "Neither can be assigned in the constructor body."),
    ("Consider the statements:\nI. Constructors can be overloaded.\nII. A class can have more than one destructor.\nWhich is/are correct?",
     I_II, 0, "There is exactly one destructor per class."),
    ("Assertion (A): A destructor cannot be overloaded.\nReason (R): A destructor takes no arguments.",
     AR, 0, "Overloads need different parameter lists, and a destructor has none."),
    ("Assertion (A): A constructor must have the return type void.\nReason (R): Constructors have no return type, not even void.",
     AR, 3, "R states the rule, which shows why A is false."),
    ("Assertion (A): The compiler supplies a copy constructor if the programmer does not write one.\nReason (R): The compiler-generated copy constructor makes a deep copy of pointer members.",
     AR, 2, "A is true; R is false – it makes a shallow, member-wise copy."),
    ("Assertion (A): Members of a class are private by default.\nReason (R): Members of a struct are public by default.",
     AR, 1, "Both true, but the struct rule does not explain the class rule."),
    ("The main purpose of a destructor is to:",
     ["Release resources such as dynamic memory or files held by the object", "Create the object", "Copy the object", "Make the object static"], 0, "This is the basis of the RAII idiom in C++."),
]

TOPICS = {
    "Object Oriented Programming": [("1 · Class, Object and Instantiation", CLASS_OBJECT),
                                    ("2 · Inheritance and Encapsulation", INHERIT_ENCAP),
                                    ("3 · Abstract Classes and Polymorphism", POLYMORPHISM)],
    "Programming in C++ – Part 1": [("1 · Tokens, Variables, Constants, Data Types, Operators and Control Statements", CPP_BASICS),
                                    ("2 · Functions and Parameter Passing", CPP_FUNCTIONS),
                                    ("3 · Classes, Objects, Constructors and Destructors", CPP_CLASSES)],
}
