"""Paper 2 · Unit 4 · Web Programming – XML, Scripting, JavaScript (3 sub-topics × 30).
References: W3C XML 1.0 and XPath recommendations; David Flanagan, JavaScript: The Definitive Guide; MDN Web Docs."""
from packlib import AR, I_II

XML = [
    ("XML stands for:",
     ["eXtensible Markup Language", "eXecutable Machine Language", "eXtra Modern Link Language", "eXternal Markup Library"], 0, "XML 1.0 became a W3C Recommendation in 1998."),
    ("The main purpose of XML, compared with HTML, is to:",
     ["Describe, store and carry data with author-defined tags", "Display data with a fixed set of tags", "Replace JavaScript", "Style web pages"], 0, "HTML focuses on presentation with predefined tags; XML focuses on data."),
    ("Which of the following is NOT well-formed XML?",
     ["<a><b>text</a></b>", "<a><b>text</b></a>", "<a b=\"1\"/>", "<a><!-- note --></a>"], 0, "Elements must be properly nested: b opens inside a, so it must close before a closes."),
    ("A well-formed XML document must have:",
     ["Exactly one root element that contains all other elements", "At least two root elements", "A DTD", "Only lower-case tags"], 0, "XML is case-sensitive, but mixed case is allowed."),
    ("An XML document is called VALID when it is:",
     ["Well-formed and also conforms to its DTD or XML Schema", "Only well-formed", "Written without attributes", "Displayed correctly by a browser"], 0, "Every valid document is well-formed, but not every well-formed document is valid."),
    ("The correct XML declaration is:",
     ["<?xml version=\"1.0\" encoding=\"UTF-8\"?>", "<xml version=\"1.0\">", "<!xml version=\"1.0\">", "<?XML 1.0?>"], 0, "If present, it must be the very first thing in the document."),
    ("In the DTD declaration  <!ELEMENT note (to, from, body)> , the element note must contain:",
     ["The elements to, from and body, in that order", "Any elements in any order", "Only text", "Nothing (it is empty)"], 0, "A comma means sequence; | means choice."),
    ("In a DTD, #PCDATA means:",
     ["Parsed character data – text that the parser will examine for markup and entities", "A number", "An empty element", "Unparsed binary data"], 0, "CDATA sections contain text that is not parsed."),
    ("Match the DTD occurrence indicator with its meaning:\na. *  b. +  c. ?  d. (no indicator)\n1. Exactly once  2. Zero or one time  3. One or more times  4. Zero or more times",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "The same symbols are used in regular expressions."),
    ("An advantage of XML Schema (XSD) over a DTD is that XSD:",
     ["Is itself written in XML and supports data types such as integer and date", "Cannot express element order", "Is shorter than any DTD", "Does not support namespaces"], 0, "It also supports namespaces and more precise constraints."),
    ("XML namespaces, declared with an attribute such as xmlns:bk=\"http://example.com/books\", are used to:",
     ["Avoid name conflicts between elements from different vocabularies", "Encrypt the document", "Make tags case-insensitive", "Compress the file"], 0, "bk:title and html:title can then be told apart."),
    ("Text placed inside  <![CDATA[ … ]]>  is:",
     ["Not parsed as markup, so characters such as < and & can be written directly", "Deleted by the parser", "Treated as a comment", "Always displayed in bold"], 0, "Useful for embedding code in XML."),
    ("XML has exactly five predefined entities. They represent:",
     ["< > & \" and ' (written &lt; &gt; &amp; &quot; &apos;)", "All HTML entities such as &nbsp; and &copy;", "Only < and >", "Digits 0–4"], 0, "Others must be declared in a DTD."),
    ("A DOM parser differs from a SAX parser in that the DOM parser:",
     ["Loads the whole document into memory as a tree that can be navigated and changed", "Reads the document as a stream of events without building a tree", "Works only with HTML", "Cannot read attributes"], 0, "SAX uses little memory and suits very large files."),
    ("XPath is used to ______, and XSLT is used to ______.",
     ["select nodes in an XML document; transform XML into other formats such as HTML", "style XML; validate XML", "compress XML; encrypt XML", "send XML; receive XML"], 0, "XSLT uses XPath expressions to choose what to transform."),
    ("The XPath expression  /bookstore/book[1]/title  selects:",
     ["The title of the first book child of the root bookstore", "All titles in the document", "The first title anywhere", "The last book"], 0, "XPath positions start at 1."),
    ("The XPath expression  //title  selects:",
     ["All title elements anywhere in the document", "Only the root's title child", "The first title only", "Attributes named title"], 0, "// means descendant-or-self at any depth; @title would select attributes."),
    ("How many elements are in this document?\n<library><book><title/><author/></book><book><title/></book></library>",
     ["6", "5", "4", "7"], 0, "library (1) + book (2) + title (2) + author (1) = 6."),
    ("Which statement about XML is TRUE?",
     ["<Note> and <note> are different elements because XML is case-sensitive", "XML tags are predefined like HTML", "XML ignores the order of elements", "XML does not allow attributes"], 0, "Element and attribute names are case-sensitive."),
    ("Which of the following commonly uses XML?",
     ["RSS feeds, SOAP web services, configuration files and Office documents (e.g. .docx is zipped XML)", "Only databases", "Only images", "Only C programs"], 0, "JSON is now more common for web APIs, but XML is still widely used."),
    ("In the DTD declaration  <!ATTLIST book id ID #REQUIRED> , the attribute id:",
     ["Must be present on every book and its value must be unique in the document", "Is optional", "Has a fixed default value", "Can contain child elements"], 0, "#IMPLIED would make it optional."),
    ("Match the XML technology with its purpose:\na. DTD  b. XSLT  c. XPath  d. XSD\n1. Schema with data types, written in XML  2. Navigating and selecting nodes  3. Transforming XML documents  4. Defining allowed structure (older, non-XML syntax)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Together they form the core XML family of standards."),
    ("Consider the statements:\nI. XML attribute values must be enclosed in quotes.\nII. An XML element name may begin with a digit.\nWhich is/are correct?",
     I_II, 0, "Names must start with a letter or underscore."),
    ("Consider the statements:\nI. JSON is often used instead of XML for web APIs because it is lighter.\nII. XML carries data but has no built-in way of displaying it as HTML does.\nWhich is/are correct?",
     I_II, 2, "Display needs a style sheet (CSS or XSLT)."),
    ("Consider the statements:\nI. An empty element can be written as <br/>.\nII. XML comments are written as // comment.\nWhich is/are correct?",
     I_II, 0, "XML comments use <!-- … -->."),
    ("Assertion (A): Every well-formed XML document has exactly one root element.\nReason (R): An XML document forms a tree, and a tree has a single root.",
     AR, 0, "The single root contains all other elements."),
    ("Assertion (A): A valid XML document need not be well-formed.\nReason (R): A valid document is well-formed and also conforms to a DTD or schema.",
     AR, 3, "R is the definition, and it shows that A is false."),
    ("Assertion (A): SAX parsers are suitable for very large XML files.\nReason (R): SAX loads the whole document into memory as a tree.",
     AR, 2, "A is true; R is false – SAX streams events and keeps little in memory (that description fits DOM)."),
    ("Assertion (A): In XML, the tags are defined by the document's author.\nReason (R): XML was standardised by the W3C.",
     AR, 1, "Both true, but W3C standardisation does not explain author-defined tags."),
    ("Which attribute usage is well-formed XML?",
     ["<book lang=\"en\">", "<book lang=en>", "<book lang>", "<book \"lang\"=\"en\">"], 0, "Every attribute needs a name and a quoted value."),
]

JS_BASICS = [
    ("JavaScript was created in 1995 at Netscape by:",
     ["Brendan Eich", "James Gosling", "Tim Berners-Lee", "Guido van Rossum"], 0, "James Gosling created Java; the two languages are unrelated in design."),
    ("Client-side scripting differs from server-side scripting in that client-side scripts:",
     ["Run in the user's browser, e.g. JavaScript", "Run on the web server, e.g. PHP", "Cannot change the page", "Need a database"], 0, "Server-side scripts (PHP, JSP, ASP.NET, Node.js) produce the page on the server."),
    ("An external JavaScript file app.js is included in an HTML page with:",
     ["<script src=\"app.js\"></script>", "<link src=\"app.js\">", "<javascript href=\"app.js\">", "<script href=\"app.js\"/>"], 0, "Inline code goes between <script> and </script>."),
    ("var, let and const differ in that:",
     ["var is function-scoped, while let and const are block-scoped; const cannot be reassigned", "All three are block-scoped", "let is function-scoped", "const can be reassigned freely"], 0, "let and const were added in ES6 (2015)."),
    ("What are  typeof null  and  typeof NaN  in JavaScript?",
     ["\"object\" and \"number\"", "\"null\" and \"NaN\"", "\"undefined\" and \"number\"", "\"object\" and \"undefined\""], 0, "typeof null being \"object\" is a long-standing quirk of the language."),
    ("What are the values of  \"5\" + 3 ,  \"5\" - 3  and  \"5\" * \"2\" ?",
     ["\"53\", 2 and 10", "8, 2 and 10", "\"53\", \"2\" and \"10\"", "8, \"53\" and 10"], 0, "+ with a string concatenates; - and * convert strings to numbers."),
    ("What are the values of  0 == \"0\" ,  0 === \"0\"  and  null == undefined ?",
     ["true, false, true", "true, true, false", "false, false, true", "true, false, false"], 0, "== converts types before comparing; === does not."),
    ("Which of the following values is truthy in JavaScript?",
     ["\"0\" (a non-empty string)", "0", "\"\" (empty string)", "null"], 0, "The falsy values are false, 0, \"\", null, undefined and NaN (and 0n, -0)."),
    ("What do  parseInt(\"08px\")  and  Number(\"08px\")  return?",
     ["8 and NaN", "NaN and 8", "8 and 8", "NaN and NaN"], 0, "parseInt reads digits until the first invalid character; Number needs the whole string to be numeric."),
    ("The function prompt() returns:",
     ["The text typed by the user as a string (or null if cancelled)", "Always a number", "A boolean", "Nothing"], 0, "confirm() returns true or false."),
    ("What is printed?\nlet s = 0;\nfor (let i = 0; i < 5; i++) { if (i === 2) continue; s += i; }\nconsole.log(s);",
     ["8", "10", "6", "3"], 0, "0 + 1 + 3 + 4 = 8."),
    ("What is printed?\nlet a = [1, 2, 3];\na[5] = 6;\nconsole.log(a.length);",
     ["6", "4", "3", "5"], 0, "length is one more than the highest index; a[3] and a[4] are empty slots."),
    ("What is printed?\nlet x;\nconsole.log(x);",
     ["undefined", "null", "0", "ReferenceError"], 0, "A declared but unassigned variable is undefined."),
    ("What happens when this runs?\nconsole.log(y);\nlet y = 5;",
     ["A ReferenceError, because y is in its temporal dead zone", "It prints undefined", "It prints 5", "It prints null"], 0, "With var y the output would be undefined because of hoisting."),
    ("What are  Math.floor(3.7) ,  Math.round(2.5)  and  Math.ceil(4.1) ?",
     ["3, 3 and 5", "4, 2 and 4", "3, 2 and 5", "3, 3 and 4"], 0, "Math.round rounds halves up in JavaScript."),
    ("The expression  NaN === NaN  evaluates to:",
     ["false – NaN is not equal to anything, even itself", "true", "NaN", "undefined"], 0, "Use Number.isNaN(x) to test for NaN."),
    ("0.1 + 0.2 === 0.3 in JavaScript gives:",
     ["false, because of binary floating-point rounding", "true", "NaN", "An error"], 0, "0.1 + 0.2 is 0.30000000000000004."),
    ("The template literal  `Sum: ${2 + 3}`  produces:",
     ["\"Sum: 5\"", "\"Sum: ${2 + 3}\"", "\"Sum: 23\"", "An error"], 0, "Template literals (backticks) were added in ES6."),
    ("A JavaScript switch statement compares the expression with each case value using:",
     ["Strict equality (===)", "Loose equality (==)", "Greater than", "String length"], 0, "So switch(\"1\") does not match case 1."),
    ("JavaScript is best described as:",
     ["Dynamically and weakly typed – variables have no fixed type and values are converted implicitly", "Statically and strongly typed like Java", "A markup language", "A compiled language that produces .exe files"], 0, "Types belong to values, not variables."),
    ("Match the function with what it does:\na. alert()  b. confirm()  c. prompt()  d. console.log()\n1. Writes to the browser's developer console  2. Asks for text input  3. Asks OK/Cancel and returns true or false  4. Shows a message with an OK button",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "alert, confirm and prompt block the page until the user responds."),
    ("Which string method returns the position of the first occurrence of a substring, or −1 if it is absent?",
     ["indexOf()", "charAt()", "slice()", "search() only for numbers"], 0, "\"hello\".indexOf(\"l\") is 2."),
    ("Consider the statements:\nI. null == undefined is true.\nII. null === undefined is true.\nWhich is/are correct?",
     I_II, 0, "They are loosely equal but of different types."),
    ("Consider the statements:\nI. const prevents the variable from being reassigned.\nII. const makes the properties of an object it holds unchangeable.\nWhich is/are correct?",
     I_II, 0, "const obj = {a: 1}; obj.a = 2; is allowed; Object.freeze() makes properties read-only."),
    ("Consider the statements:\nI. JavaScript can run on servers using Node.js.\nII. JavaScript code runs only after the whole page has loaded.\nWhich is/are correct?",
     I_II, 0, "Scripts run when the browser reaches them, unless defer/async or load events are used."),
    ("Assertion (A):  \"5\" + 3  evaluates to \"53\".\nReason (R): When one operand of + is a string, JavaScript converts the other operand to a string and concatenates.",
     AR, 0, "R describes exactly what + does with a string operand."),
    ("Assertion (A): JavaScript is compiled like C into an .exe file before it runs.\nReason (R): JavaScript engines run code inside the browser, interpreting or JIT-compiling it at run time.",
     AR, 3, "R describes how JavaScript actually runs, which shows why A is false."),
    ("Assertion (A): let declarations are block-scoped.\nReason (R): A let variable can be redeclared with let in the same scope.",
     AR, 2, "A is true; R is false – redeclaring with let in the same scope is a SyntaxError."),
    ("Assertion (A): Java and JavaScript are different languages.\nReason (R): JavaScript was created by Brendan Eich.",
     AR, 1, "Both true, but who created JavaScript does not explain why the languages differ."),
    ("Which statement about JavaScript comments is correct?",
     ["// starts a single-line comment and /* … */ encloses a multi-line comment", "# starts a comment", "<!-- --> is the only comment form", "JavaScript has no comments"], 0, "The same forms are used in C, C++ and Java."),
]

JS_DOM = [
    ("An arrow function that returns the square of x is written:",
     ["const sq = x => x * x;", "const sq = function => x * x;", "const sq = (x) -> x * x;", "arrow sq(x) { x * x }"], 0, "Arrow functions were added in ES6."),
    ("What is printed?\nfunction counter() { let c = 0; return () => ++c; }\nconst f = counter(); f(); f();\nconsole.log(f());",
     ["3", "1", "0", "undefined"], 0, "The returned function keeps access to c through a closure, so c keeps growing."),
    ("What does  f(3)  return for  function f(a, b = 2) { return a * b; } ?",
     ["6", "3", "NaN", "5"], 0, "b takes its default value 2."),
    ("For  const student = { name: \"Ravi\", age: 20 }; , which expressions both give \"Ravi\"?",
     ["student.name and student[\"name\"]", "student->name and student::name", "student(name) and student.name()", "student[name] and student.get(\"name\")"], 0, "Bracket notation is needed when the property name is in a variable."),
    ("JSON.stringify() and JSON.parse() respectively:",
     ["Convert an object to a JSON string, and a JSON string back to an object", "Parse and stringify HTML", "Encrypt and decrypt data", "Send and receive data"], 0, "JSON = JavaScript Object Notation."),
    ("What are the results of  [1, 2, 3, 4].filter(x => x % 2 === 0)  and  [1, 2, 3].map(x => x * 2) ?",
     ["[2, 4] and [2, 4, 6]", "[1, 3] and [2, 4, 6]", "[2, 4] and [1, 4, 9]", "true and [2, 4, 6]"], 0, "filter keeps elements that pass the test; map transforms every element."),
    ("What does  [1, 2, 3, 4].reduce((acc, x) => acc + x, 0)  return?",
     ["10", "24", "[1, 3, 6, 10]", "0"], 0, "reduce combines all elements into one value."),
    ("document.querySelector(\".item\") returns:",
     ["The first element with class item", "All elements with class item", "The element with id item", "null always"], 0, "querySelectorAll returns all matches as a NodeList."),
    ("Which statement changes the text colour of the element with id \"msg\" to red?",
     ["document.getElementById(\"msg\").style.color = \"red\";", "document.msg.color = \"red\";", "getElement(\"msg\").colour(\"red\");", "#msg.style = red;"], 0, "CSS properties are available through the style object."),
    ("What does the page show after  document.getElementById(\"demo\").innerHTML = 5 + 6;  ?",
     ["11", "56", "5 + 6", "Nothing"], 0, "5 + 6 is evaluated as a number before it is assigned."),
    ("To add a new list item to an existing <ul id=\"list\">, a script can use:",
     ["const li = document.createElement(\"li\"); li.textContent = \"New\"; document.getElementById(\"list\").appendChild(li);", "document.write(\"list.li\");", "list.add(\"li\");", "new li(\"New\");"], 0, "The DOM can be changed without reloading the page."),
    ("The event that fires when a page has finished loading is:",
     ["load (window.onload)", "click", "change", "submit"], 0, "DOMContentLoaded fires earlier, when the HTML has been parsed."),
    ("Match the event with when it occurs:\na. click  b. change  c. mouseover  d. submit\n1. A form is being sent  2. The pointer moves onto an element  3. The value of an input changes and is committed  4. An element is clicked",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Handlers are attached with addEventListener or on… attributes."),
    ("Calling  event.preventDefault()  inside a form's submit handler:",
     ["Stops the browser from submitting the form (e.g. when validation fails)", "Stops the event from bubbling", "Deletes the form", "Reloads the page"], 0, "stopPropagation() is what stops bubbling."),
    ("What is printed?\nconsole.log(1);\nsetTimeout(() => console.log(2), 0);\nconsole.log(3);",
     ["1 3 2", "1 2 3", "2 1 3", "3 2 1"], 0, "The callback waits in the task queue until the current script has finished."),
    ("setTimeout and setInterval differ in that:",
     ["setTimeout runs a function once after a delay; setInterval runs it repeatedly at that interval", "They are identical", "setInterval runs once", "setTimeout repeats forever"], 0, "clearInterval stops a repeating timer."),
    ("localStorage in a browser:",
     ["Stores key–value strings that persist after the browser is closed", "Is cleared when the tab is closed", "Stores data on the server", "Can hold only numbers"], 0, "sessionStorage is cleared when the tab closes."),
    ("window.location.href = \"https://example.com\";  causes the browser to:",
     ["Navigate to that address", "Download a file", "Print the page", "Close the tab"], 0, "location is part of the Browser Object Model (BOM)."),
    ("What is printed?\nconst o = { a: 1 };\nconst p = o;\np.a = 5;\nconsole.log(o.a);",
     ["5", "1", "undefined", "An error"], 0, "Objects are assigned by reference; o and p refer to the same object."),
    ("fetch(url) in modern JavaScript:",
     ["Makes an asynchronous HTTP request and returns a Promise", "Reloads the page", "Runs synchronously and blocks the page", "Only works with XML"], 0, "It replaced most uses of XMLHttpRequest (AJAX)."),
    ("The three states of a JavaScript Promise are:",
     ["Pending, fulfilled and rejected", "Start, run and stop", "Open, closed and error", "Waiting, sleeping and done"], 0, "then() handles fulfilment and catch() handles rejection."),
    ("Consider the statements:\nI. querySelector returns the first matching element.\nII. querySelectorAll returns all matching elements.\nWhich is/are correct?",
     I_II, 2, "Both statements are correct."),
    ("Consider the statements:\nI. Arrow functions have their own this binding.\nII. Arrow functions can be written without the function keyword.\nWhich is/are correct?",
     I_II, 1, "Arrow functions take this from the surrounding scope."),
    ("Consider the statements:\nI. textContent treats the assigned string as plain text.\nII. innerHTML parses the assigned string as HTML.\nWhich is/are correct?",
     I_II, 2, "Assigning user input to innerHTML can be a security risk (XSS)."),
    ("Assertion (A): Clicking a button inside a div also triggers the div's click handler.\nReason (R): Events bubble up from the target element to its ancestors.",
     AR, 0, "Bubbling carries the event to the parent div."),
    ("Assertion (A): addEventListener can attach several handlers for the same event on one element.\nReason (R): Assigning to element.onclick replaces any earlier onclick handler.",
     AR, 1, "Both true; R describes a different mechanism and does not explain A."),
    ("Assertion (A): setTimeout(f, 0) runs f only after the current script has finished.\nReason (R): setTimeout(f, 0) runs f immediately, before the next statement.",
     AR, 2, "A is true; R is false – the callback is queued and runs later."),
    ("Assertion (A): Assigning \"<b>Hi</b>\" to textContent shows the word Hi in bold.\nReason (R): textContent inserts text without interpreting HTML tags.",
     AR, 3, "The tags are shown literally, so A is false; R explains why."),
    ("event.stopPropagation() is used to:",
     ["Stop the event from bubbling up to ancestor elements", "Cancel the default browser action", "Remove all event listeners", "Stop all timers"], 0, "preventDefault() cancels the default action."),
    ("A function that is passed to another function and called later, for example the handler in addEventListener(\"click\", handler), is called a:",
     ["Callback function", "Constructor", "Prototype", "Getter"], 0, "Callbacks are central to event-driven JavaScript."),
]

TOPICS = {
    "Web Programming – XML, Scripting, JavaScript": [("1 · XML", XML),
                                                     ("2 · Scripting and JavaScript Fundamentals", JS_BASICS),
                                                     ("3 · JavaScript Functions, Objects, DOM and Events", JS_DOM)],
}
