"""Paper 2 · Unit 4 · Programming in C – Part 1 and Part 2 (6 sub-topics × 30).
References: Kernighan & Ritchie, The C Programming Language; Balagurusamy, Programming in ANSI C; Pratt & Zelkowitz (subprogram control).
Unless stated, assume a typical system with 1-byte char, 4-byte int, 8-byte double, and C99 rules."""
from packlib import AR, I_II

TOKENS = [
    ("Which of the following is a valid C identifier?",
     ["_total1", "2total", "total-sum", "int"], 0, "Identifiers start with a letter or underscore, contain only letters, digits and underscores, and cannot be keywords."),
    ("How many keywords does ANSI C (C89) define?",
     ["32", "24", "37", "44"], 0, "C89 has 32 keywords; C99 added 5 more (inline, restrict, _Bool, _Complex, _Imaginary)."),
    ("Which of the following is NOT a C token?",
     ["A comment", "A keyword", "A string literal", "An operator"], 0, "Comments are removed before tokenisation (replaced by a space); tokens are keywords, identifiers, constants, string literals, operators and punctuators."),
    ("What does  printf(\"%d\", 010);  print?",
     ["8", "10", "2", "010"], 0, "A leading 0 makes an integer constant octal: 010₈ = 8."),
    ("What does  printf(\"%d\", 0x1F);  print?",
     ["31", "15", "1F", "25"], 0, "0x1F = 1×16 + 15 = 31."),
    ("In C (not C++),  sizeof('A')  on a system with 4-byte int is:",
     ["4", "1", "2", "8"], 0, "In C a character constant has type int; in C++ it has type char."),
    ("sizeof(char) in C is:",
     ["Always 1", "Always 2", "Implementation-defined, usually 4", "Equal to sizeof(int)"], 0, "The standard defines sizeof(char) as 1 byte."),
    ("The range of a signed char (8-bit, two's complement) is:",
     ["−128 to 127", "0 to 255", "−127 to 127", "−256 to 255"], 0, "8 bits give 256 values: −2⁷ to 2⁷ − 1."),
    ("With 32-bit int, what does  unsigned int x = -1;  printf(\"%u\", x);  print?",
     ["4294967295", "-1", "0", "65535"], 0, "−1 converted to unsigned wraps to 2³² − 1."),
    ("Consider the statements:\nI. In C, overflow of an unsigned integer wraps around modulo 2ⁿ.\nII. In C, overflow of a signed int is guaranteed to wrap around the same way.\nWhich is/are correct?",
     I_II, 0, "Unsigned arithmetic is modular by definition; signed overflow is undefined behaviour."),
    ("In C, the constant 3.14 has type:",
     ["double", "float", "long double", "int"], 0, "Floating constants are double unless suffixed: 3.14f is float, 3.14L is long double."),
    ("What is  strlen(\"a\\tb\")?",
     ["3", "4", "5", "2"], 0, "\\t is a single escape character: a, TAB, b."),
    ("To read a double with scanf, the correct format specifier is:",
     ["%lf", "%f", "%d", "%ld"], 0, "In scanf, %f expects float* and %lf expects double*; in printf both %f and %lf print a double."),
    ("What does  char c = 65;  printf(\"%c %d\", c, c);  print?",
     ["A 65", "65 A", "A A", "65 65"], 0, "The same value printed as a character and as an integer."),
    ("In C,  Sum  and  sum  are:",
     ["Two different identifiers", "The same identifier", "Both keywords", "Invalid identifiers"], 0, "C is case-sensitive."),
    ("What happens with  const int x = 10;  x = 20; ?",
     ["Compile-time error: assignment to a read-only variable", "x becomes 20", "Run-time error only", "x becomes 30"], 0, "A const-qualified object is not a modifiable l-value."),
    ("How many tokens are there in  int a = 10, b;",
     ["7", "6", "5", "8"], 0, "int, a, =, 10, ',', b, ; → 7."),
    ("What does  printf(\"%d\", 'a' - 'A');  print (ASCII)?",
     ["32", "0", "-32", "26"], 0, "97 − 65 = 32."),
    ("After  int x = 3.9;  the value of x is:",
     ["3", "4", "3.9", "Compile error"], 0, "Conversion from floating to integer truncates toward zero."),
    ("What does  printf(\"%x\", 255);  print?",
     ["ff", "FF00", "377", "255"], 0, "255 = 0xFF; %x prints lower-case hexadecimal (%o would give 377)."),
    ("On a typical system,  sizeof(3.0)  is:",
     ["8", "4", "2", "10"], 0, "3.0 is a double constant."),
    ("Match the type with its printf format specifier:\na. int  b. float/double  c. char  d. string (char *)\n1. %c  2. %s  3. %d  4. %f",
     ["a-3, b-4, c-1, d-2", "a-4, b-3, c-1, d-2", "a-3, b-4, c-2, d-1", "a-1, b-4, c-3, d-2"], 0, "%d, %f, %c and %s."),
    ("Which of the following is NOT a data-type modifier in C?",
     ["large", "short", "long", "unsigned"], 0, "The modifiers are short, long, signed and unsigned."),
    ("Consider the statements:\nI. Whether plain char is signed or unsigned is implementation-defined.\nII. sizeof(int) is always 2 bytes in C.\nWhich is/are correct?",
     I_II, 0, "int size depends on the implementation (commonly 4 bytes today); the standard only fixes minimum ranges."),
    ("Assertion (A): 'A' and \"A\" are the same in C.\nReason (R): \"A\" is a string literal made of the character 'A' followed by '\\0'.",
     AR, 3, "'A' is an int constant (65); \"A\" is a 2-byte char array. R is true and shows why A is false."),
    ("Assertion (A): In C, sizeof is an operator, not a library function.\nReason (R): sizeof(int) can be evaluated by the compiler at compile time.",
     AR, 1, "Both true; sizeof is an operator by definition of the language, and compile-time evaluation is a consequence, not the reason."),
    ("Assertion (A): Identifiers in C are case-sensitive.\nReason (R): C treats upper-case and lower-case letters as distinct characters.",
     AR, 0, "Because 'S' and 's' are different characters, Sum and sum are different names."),
    ("Assertion (A): In C, the value of 5 % 3 is 2.\nReason (R): The % operator in C also accepts floating-point operands.",
     AR, 2, "A is true. R is false: % needs integer operands; fmod() is used for floating-point values."),
    ("Which declaration is INVALID in C?",
     ["int 2x;", "float _y;", "char c1;", "double total_marks;"], 0, "An identifier cannot begin with a digit."),
    ("The value of the constant 1e3 in C is:",
     ["1000.0 (a double)", "1000 (an int)", "13", "e³"], 0, "Exponent notation always produces a floating (double) constant."),
]

SEQUENCE = [
    ("What is the value of  5 + 3 * 2  in C?",
     ["11", "16", "13", "10"], 0, "* has higher precedence than +: 5 + 6."),
    ("What is the value of  10 / 3 * 3  in C (int operands)?",
     ["9", "10", "1", "11"], 0, "Left to right: 10 / 3 = 3 (integer division), 3 * 3 = 9."),
    ("What is the value of  10 % 3 * 2 ?",
     ["2", "4", "6", "0"], 0, "% and * have equal precedence, left to right: 1 * 2 = 2."),
    ("In C99, the values of  -7 / 2  and  -7 % 2  are:",
     ["-3 and -1", "-4 and 1", "-3 and 1", "-4 and -1"], 0, "Division truncates toward zero, and (a/b)*b + a%b == a: (−3)(2) + (−1) = −7."),
    ("After  int i = 5, j;  j = i++ + 2;  the values of i and j are:",
     ["i = 6, j = 7", "i = 6, j = 8", "i = 5, j = 7", "i = 7, j = 8"], 0, "i++ yields the old value 5 and then increments i."),
    ("After  int a = 0, b = 5;  if (a && (b = 10)) ;  the value of b is:",
     ["5", "10", "0", "Undefined"], 0, "a is 0, so && short-circuits and the assignment b = 10 is never evaluated."),
    ("After  int a = 1, b = 5;  if (a || b++) ;  the value of b is:",
     ["5", "6", "1", "0"], 0, "a is non-zero, so || short-circuits and b++ is not evaluated."),
    ("What is the value of x after  x = (1, 2, 3);",
     ["3", "1", "6", "Compile error"], 0, "The comma operator evaluates left to right and yields its last operand."),
    ("What is the value of the expression  5 > 3 > 1  in C?",
     ["0", "1", "5", "Compile error"], 0, "(5 > 3) is 1, then 1 > 1 is 0."),
    ("What is the value of  3 == 3 == 3  in C?",
     ["0", "1", "3", "Compile error"], 0, "(3 == 3) is 1, then 1 == 3 is 0."),
    ("What are the values of  5 & 3,  5 | 3  and  5 ^ 3 ?",
     ["1, 7, 6", "1, 7, 2", "7, 1, 6", "1, 6, 7"], 0, "101 & 011 = 001; 101 | 011 = 111; 101 ^ 011 = 110."),
    ("What are the values of  1 << 4  and  20 >> 2 ?",
     ["16 and 5", "8 and 10", "16 and 80", "4 and 5"], 0, "Left shift by k multiplies by 2ᵏ; right shift of a non-negative value divides by 2ᵏ."),
    ("How many times does the body of  for (i = 0; i < 10; i += 3)  execute?",
     ["4", "3", "10", "5"], 0, "i = 0, 3, 6, 9."),
    ("How many times does the body of  for (i = 1; i <= 100; i *= 2)  execute?",
     ["7", "6", "100", "8"], 0, "i = 1, 2, 4, 8, 16, 32, 64; next 128 > 100."),
    ("After  int i = 10;  do { i++; } while (i < 5);  the value of i is:",
     ["11", "10", "5", "6"], 0, "A do-while body always runs once before the test."),
    ("With x = 0, what is x after:\nswitch (2) { case 1: x += 1; case 2: x += 2; case 3: x += 3; break; default: x += 10; }",
     ["5", "2", "15", "6"], 0, "Execution starts at case 2 and falls through case 3 to the break: 2 + 3."),
    ("In the nested loops  for (i = 0; i < 5; i++) for (j = 0; j < i; j++) count++;  starting with count = 0, the final count is:",
     ["10", "25", "15", "5"], 0, "0 + 1 + 2 + 3 + 4 = 10."),
    ("How does C parse the expression  a & b == c ?",
     ["a & (b == c)", "(a & b) == c", "It is a syntax error", "(a & b) & c"], 0, "== has higher precedence than bitwise &, a classic source of bugs."),
    ("In  a = b = c = 5;  the assignments are performed:",
     ["Right to left, so all three become 5", "Left to right, so only a becomes 5", "In an unspecified order", "It is a compile error"], 0, "Assignment is right-associative: a = (b = (c = 5))."),
    ("A break statement inside the inner loop of two nested loops:",
     ["Exits only the innermost enclosing loop", "Exits both loops", "Exits the function", "Restarts the outer loop"], 0, "break leaves only the nearest enclosing loop or switch."),
    ("The structured program theorem (Böhm and Jacopini) states that any algorithm can be written using only:",
     ["Sequence, selection and iteration", "goto statements", "Recursion and goto", "Functions and pointers"], 0, "These three control structures are sufficient, so goto is never strictly necessary."),
    ("The value of the postfix expression  2 3 4 * +  is:",
     ["14", "20", "24", "9"], 0, "3 * 4 = 12, then 2 + 12 = 14."),
    ("The postfix form of the infix expression  a + b * c  is:",
     ["a b c * +", "a b + c *", "+ a * b c", "a b * c +"], 0, "* has higher precedence, so b c * is formed first."),
    ("What does this print?\nint i, s = 0;\nfor (i = 1; i <= 10; i++) { if (i % 3 == 0) continue; s += i; }\nprintf(\"%d\", s);",
     ["37", "55", "18", "40"], 0, "55 − (3 + 6 + 9) = 37."),
    ("Match the operator with its category:\na. ?:  b. sizeof  c. ,  d. ->\n1. Member access through a pointer  2. Sequencing (comma)  3. Conditional (ternary)  4. Unary, compile-time size",
     ["a-3, b-4, c-2, d-1", "a-4, b-3, c-2, d-1", "a-3, b-2, c-4, d-1", "a-3, b-4, c-1, d-2"], 0, "?: is the only ternary operator in C."),
    ("Consider the statements:\nI. In C, the order of evaluation of the two operands of + is unspecified.\nII. The && operator guarantees left-to-right evaluation.\nWhich is/are correct?",
     I_II, 2, "&&, ||, ?: and the comma operator have sequence points; + does not."),
    ("Assertion (A): In C,  if (x = 0) { … }  never executes its body.\nReason (R): The value of an assignment expression is the value that is assigned.",
     AR, 0, "x = 0 has value 0 (false) whatever x was, so the body never runs."),
    ("Assertion (A): The && operator evaluates its right operand only when necessary.\nReason (R): && has higher precedence than ||.",
     AR, 1, "Both true, but short-circuit evaluation has nothing to do with precedence."),
    ("Assertion (A): A do-while loop executes its body at least once.\nReason (R): In a do-while loop the condition is tested before the body.",
     AR, 2, "A is true because the condition is tested after the body; R is false."),
    ("Assertion (A): case labels in a C switch statement may be floating-point constants such as 1.5.\nReason (R): case labels must be integral constant expressions.",
     AR, 3, "R is the rule, and it shows A is false."),
]

SUBPROGRAMS = [
    ("An activation record (stack frame) of a C function typically contains:",
     ["Return address, parameters, local variables and a link to the caller's frame", "Only global variables", "The source code of the function", "The function's compiled machine code"], 0, "Each call pushes a new activation record on the run-time stack."),
    ("Recursion is implemented by giving each active call:",
     ["Its own activation record on the run-time stack", "A shared static copy of its local variables", "A separate program", "A new heap object freed by the programmer"], 0, "Separate records keep the parameters and locals of different calls apart."),
    ("What is printed?\nvoid f(int x) { x = 10; }\nint main() { int a = 5; f(a); printf(\"%d\", a); }",
     ["5", "10", "0", "Garbage"], 0, "C passes by value: f changes only its own copy."),
    ("What is printed?\nvoid f(int *x) { *x = 10; }\nint main() { int a = 5; f(&a); printf(\"%d\", a); }",
     ["10", "5", "Address of a", "Compile error"], 0, "The pointer lets f store into the caller's variable (call by reference simulated)."),
    ("Procedure p(x, y) { x = x + 1; y = y + 1; } is called as p(a, a) with a = 1. With call by reference, a becomes:",
     ["3", "2", "1", "4"], 0, "x and y are aliases of a, so a is incremented twice."),
    ("The same procedure p(x, y) { x = x + 1; y = y + 1; } is called as p(a, a) with a = 1 using call by value-result (copy-in/copy-out, copied back left to right). a becomes:",
     ["2", "3", "1", "4"], 0, "x and y each start at 1 and become 2; both copies return 2 to a."),
    ("Call by name, in which an argument expression is re-evaluated at every use of the formal parameter, was introduced in:",
     ["ALGOL 60", "C", "FORTRAN", "Pascal"], 0, "Jensen's device exploits call by name in ALGOL 60."),
    ("Consider:\nint x = 1;\nvoid f() { printf(\"%d\", x); }\nvoid g() { int x = 2; f(); }\nmain calls g(). What is printed under static scoping and under dynamic scoping?",
     ["Static: 1, Dynamic: 2", "Static: 2, Dynamic: 1", "1 in both", "2 in both"], 0, "Static scope uses the x where f is defined (global); dynamic scope uses the most recent caller's x (g's)."),
    ("How many calls of fact() are made to compute fact(5) with  int fact(int n) { return n == 0 ? 1 : n * fact(n - 1); } ?",
     ["6", "5", "4", "120"], 0, "fact(5), fact(4), …, fact(0): six calls."),
    ("With  int fib(int n) { return n <= 1 ? n : fib(n-1) + fib(n-2); },  how many calls in total are made to compute fib(5)?",
     ["15", "8", "9", "5"], 0, "C(n) = 1 + C(n−1) + C(n−2) with C(0) = C(1) = 1: C(2)=3, C(3)=5, C(4)=9, C(5)=15."),
    ("What does f(7) return?\nint f(int n) { if (n <= 0) return 0; return n + f(n - 2); }",
     ["16", "28", "15", "12"], 0, "7 + 5 + 3 + 1 + 0 = 16."),
    ("What does f(5) return?\nint f(int n) { if (n == 1) return 1; return 2 * f(n - 1); }",
     ["16", "32", "10", "25"], 0, "f(n) = 2ⁿ⁻¹, so f(5) = 16."),
    ("What does g(1234) return?\nint g(int x) { return x > 9 ? x % 10 + g(x / 10) : x; }",
     ["10", "1234", "4", "24"], 0, "It adds the digits: 4 + 3 + 2 + 1."),
    ("What is printed when f() is called three times?\nvoid f() { static int c = 0; c++; printf(\"%d \", c); }",
     ["1 2 3", "1 1 1", "0 1 2", "3 3 3"], 0, "A static local is initialised once and keeps its value between calls."),
    ("The storage class specifier extern in a declaration means:",
     ["The variable is defined elsewhere (possibly in another file)", "The variable is stored in a register", "The variable is local to the block", "The variable is constant"], 0, "extern declares without defining, so the linker resolves it."),
    ("Which operation is NOT allowed on a variable declared with the register storage class?",
     ["Taking its address with &", "Assigning to it", "Using it in arithmetic", "Using it as a loop counter"], 0, "A register variable may not have an address in memory."),
    ("The main purpose of a function prototype in C is to:",
     ["Let the compiler check the number and types of arguments in calls", "Allocate memory for the function", "Make the function run faster", "Make the function recursive"], 0, "Prototypes allow argument checking and conversions at compile time."),
    ("A function is tail-recursive when:",
     ["The recursive call is the last action performed by the function", "It calls itself twice", "It has no parameters", "It uses a static variable"], 0, "A compiler can turn tail recursion into a loop, reusing the same frame."),
    ("Subprograms that can suspend their execution and later resume from the point of suspension are called:",
     ["Coroutines", "Macros", "Inline functions", "Interrupt vectors"], 0, "Pratt discusses coroutines as a generalisation of simple call-return subprograms."),
    ("In a language with nested subprograms, the static link in an activation record points to:",
     ["The activation record of the lexically enclosing subprogram", "The caller's activation record", "The heap", "The global symbol table"], 0, "The dynamic link points to the caller; the static link is used to reach non-local variables under static scoping."),
    ("With  void f(int n) { if (n > 0) f(n - 1); }  called as f(5), the maximum number of activation records of f on the stack at one time is:",
     ["6", "5", "1", "10"], 0, "f(5) down to f(0) are all active together."),
    ("Match the parameter-passing method with a language that uses it:\na. Call by name  b. Call by value  c. Call by reference (traditional)  d. In out (copy-in/copy-out for scalars)\n1. C  2. FORTRAN  3. Ada  4. ALGOL 60",
     ["a-4, b-1, c-2, d-3", "a-1, b-4, c-2, d-3", "a-4, b-2, c-1, d-3", "a-4, b-1, c-3, d-2"], 0, "ALGOL 60 – name; C – value; FORTRAN – reference; Ada in out – value-result for scalars."),
    ("Assertion (A): Recursive subprograms need a separate activation record for each active call.\nReason (R): Each activation needs its own copy of parameters and local variables.",
     AR, 0, "Without separate records, a new call would overwrite the values of the pending ones."),
    ("Assertion (A): In C, an array argument is copied element by element into the called function.\nReason (R): When an array is passed, only the address of its first element is passed.",
     AR, 3, "Only a pointer is passed, which is why the function can change the caller's array. R shows why A is false."),
    ("Assertion (A): A static local variable in C retains its value between calls.\nReason (R): Static local variables are stored on the run-time stack.",
     AR, 2, "A is true. R is false: static variables live in the static data area for the whole run."),
    ("Assertion (A): Standard C does not allow a function to be defined inside another function.\nReason (R): C supports recursion.",
     AR, 1, "Both true but unrelated; lack of nesting is why C needs no static links."),
    ("Consider the statements:\nI. With dynamic scoping, a non-local name is resolved by searching back through the chain of calling subprograms.\nII. C uses dynamic scoping.\nWhich is/are correct?",
     I_II, 0, "C (like Pascal and Ada) uses static (lexical) scoping."),
    ("Which statement about recursion is TRUE?",
     ["Every recursive function can be rewritten iteratively, possibly using an explicit stack", "Recursion always runs faster than iteration", "Recursive functions cannot have parameters", "Recursion does not use the stack"], 0, "The run-time stack can always be simulated by an explicit stack."),
    ("Two functions A and B where A calls B and B calls A are said to be:",
     ["Mutually (indirectly) recursive", "Tail recursive", "Inline", "Reentrant only"], 0, "Recursion through another function is indirect or mutual recursion."),
    ("Consider the statements:\nI. In C89, a function declared without a return type is assumed to return int.\nII. A C function can return a whole structure by value.\nWhich is/are correct?",
     I_II, 2, "Implicit int was allowed in C89 (removed in C99), and structures can be returned by value."),
]

ARRAYS_STRINGS = [
    ("After  int a[5] = {1, 2};  the value of a[3] is:",
     ["0", "2", "Garbage", "1"], 0, "Elements without an initialiser in a partly initialised array are set to 0."),
    ("For  int a[] = {1, 2, 3, 4};  the value of  sizeof(a) / sizeof(a[0])  is:",
     ["4", "16", "1", "8"], 0, "Total bytes ÷ bytes per element = number of elements."),
    ("Accessing a[5] of an array declared  int a[5];  results in:",
     ["Undefined behaviour – C does no bounds checking", "A compile-time error always", "The value 0", "An automatic resize of the array"], 0, "Valid indices are 0 to 4; C does not check bounds."),
    ("With 4-byte int,  int a[3][4];  occupies:",
     ["48 bytes", "12 bytes", "28 bytes", "16 bytes"], 0, "3 × 4 elements × 4 bytes."),
    ("For  int a[2][3] = {{1, 2, 3}, {4, 5, 6}};  the value of a[1][2] is:",
     ["6", "5", "3", "4"], 0, "Row 1 is {4, 5, 6}; column 2 is 6."),
    ("For  int a[] = {10, 20, 30, 40};  the value of  *(a + 2)  is:",
     ["30", "20", "12", "40"], 0, "a[i] ≡ *(a + i)."),
    ("strcmp(\"abc\", \"abd\") returns:",
     ["A negative value", "0", "A positive value", "3"], 0, "The first difference is 'c' < 'd'."),
    ("Given  char s[10];  the statement  s = \"hi\";  results in:",
     ["A compile error – an array cannot be assigned", "s holding \"hi\"", "A run-time error", "s[0] = 'h' only"], 0, "Use strcpy(s, \"hi\") instead."),
    ("What does  char s[] = \"GATE\";  printf(\"%s\", s + 1);  print?",
     ["ATE", "GATE", "HATE", "E"], 0, "s + 1 points to the second character."),
    ("Which statement is correct?\nchar s[] = \"hello\"; char *p = \"hello\";",
     ["s[0] = 'j' is valid, but p[0] = 'j' is undefined behaviour", "Both assignments are valid", "Both are compile errors", "p[0] = 'j' is valid, but s[0] = 'j' is not"], 0, "s is a modifiable array; p points to a string literal, which must not be modified."),
    ("strlen(\"abc\\0def\") is:",
     ["3", "7", "6", "8"], 0, "strlen stops at the first null character."),
    ("On a typical system with 4-byte int aligned on 4-byte boundaries, sizeof(struct { char c; int i; }) is:",
     ["8", "5", "4", "6"], 0, "3 bytes of padding follow c so that i is aligned."),
    ("With 4-byte aligned int, which structure is larger?\nS1: { char a; char b; int c; }   S2: { char a; int c; char b; }",
     ["S2 (12 bytes) is larger than S1 (8 bytes)", "S1 is larger than S2", "Both are 6 bytes", "Both are 8 bytes"], 0, "In S2, padding is needed after a and again after b at the end; member order affects size."),
    ("For a structure pointer p,  p->x  is equivalent to:",
     ["(*p).x", "*p.x", "&p.x", "p.x"], 0, "*p.x would mean *(p.x) because . binds tighter than *."),
    ("Consider the statements about C:\nI. Two structures of the same type can be compared with ==.\nII. A structure can be passed to and returned from a function by value.\nWhich is/are correct?",
     I_II, 1, "== is not defined for structures; compare member by member instead."),
    ("The size of  union { int i; char c[4]; }  with 4-byte int is:",
     ["4", "8", "5", "1"], 0, "Members overlap; the largest member is 4 bytes."),
    ("The range of values of the bit-field  unsigned a : 3;  is:",
     ["0 to 7", "0 to 3", "0 to 8", "−4 to 3"], 0, "3 bits give 2³ = 8 values."),
    ("A self-referential structure such as  struct node { int data; struct node *next; };  is mainly used to build:",
     ["Linked lists and trees", "Fixed-size arrays", "Macros", "Files"], 0, "The pointer member links one node to the next."),
    ("Given  struct date { int d, m, y; };  struct emp { char name[20]; struct date doj; } e;  the year of joining is accessed as:",
     ["e.doj.y", "e.y", "doj.e.y", "e->doj->y"], 0, "Nested members are accessed with successive dots."),
    ("What does this print?\nchar s[] = \"abcdef\"; int i;\nfor (i = 0; s[i]; i += 2) putchar(s[i]);",
     ["ace", "abcdef", "bdf", "ac"], 0, "Indices 0, 2 and 4 print a, c, e; at i = 6 the loop meets the terminating '\\0' and stops."),
    ("Reversing the string \"program\" in place by swapping s[i] and s[n−1−i] needs how many swaps?",
     ["3", "7", "4", "6"], 0, "n = 7, swaps = ⌊7/2⌋ = 3; the middle character stays."),
    ("Match the string function with its action:\na. strlen  b. strcpy  c. strcmp  d. strcat\n1. Joins one string to the end of another  2. Compares two strings  3. Copies a string  4. Counts characters before '\\0'",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "All are declared in <string.h>."),
    ("Assertion (A): An array name cannot appear on the left of an assignment in C.\nReason (R): An array name is not a modifiable l-value.",
     AR, 0, "That is exactly the rule that forbids array assignment."),
    ("Assertion (A): C strings store their length in the first byte.\nReason (R): C strings are terminated by the null character '\\0'.",
     AR, 3, "C finds the end by scanning for '\\0', so no length is stored (that is Pascal-style strings)."),
    ("Assertion (A): Two structure variables of the same type can be assigned using =.\nReason (R): Structures can contain members of different data types.",
     AR, 1, "Both true; whole-structure assignment is a language rule unrelated to mixed member types."),
    ("Assertion (A): sizeof a structure may be greater than the sum of the sizes of its members.\nReason (R): C compilers never insert padding between structure members.",
     AR, 2, "A is true because compilers insert padding for alignment; R is false."),
    ("To store the marks of 50 students, each with a name, roll number and marks, the most suitable declaration is:",
     ["An array of 50 structures", "A union of 50 members", "50 separate int variables", "A 2-D char array only"], 0, "Each element holds one student's mixed data."),
    ("What does this print?\nint a[5] = {5, 1, 4, 2, 3}, i, m = a[0];\nfor (i = 1; i < 5; i++) if (a[i] > m) m = a[i];\nprintf(\"%d\", m);",
     ["5", "4", "3", "1"], 0, "It finds the maximum, using n − 1 = 4 comparisons."),
    ("What is printed?\nchar s[20] = \"Hello\"; strcat(s, \" C\"); printf(\"%d\", (int)strlen(s));",
     ["7", "5", "8", "20"], 0, "\"Hello C\" has 7 characters."),
    ("Which initialisation of a 2-D array is INVALID in C?",
     ["int a[][] = {{1, 2}, {3, 4}};", "int a[][2] = {{1, 2}, {3, 4}};", "int a[2][2] = {1, 2, 3, 4};", "int a[2][2] = {{1}, {3, 4}};"], 0, "Only the first dimension may be omitted; the column size is needed for address computation."),
]

POINTERS = [
    ("After  int x = 10, *p = &x;  *p = 20;  the value of x is:",
     ["20", "10", "Address of x", "30"], 0, "*p is another name for x."),
    ("An int pointer p holds the address 1000. With 4-byte int, after p++ it holds:",
     ["1004", "1001", "1002", "1008"], 0, "Pointer arithmetic is scaled by the size of the pointed-to type."),
    ("For an int array a, the value of  &a[5] - &a[1]  is:",
     ["4", "16", "5", "1"], 0, "Pointer difference counts elements, not bytes."),
    ("For  int a[] = {5, 6, 7, 8};  what is  2[a] ?",
     ["7", "6", "Compile error", "8"], 0, "a[i] ≡ *(a + i) ≡ *(i + a) ≡ i[a]."),
    ("What does this print?\nint a[] = {10, 20, 30}; int *p = a;\nprintf(\"%d \", *p++); printf(\"%d\", *p);",
     ["10 20", "11 20", "20 30", "10 10"], 0, "*p++ yields *p (10) and then advances p to the next element."),
    ("What does this print?\nint a[] = {10, 20, 30}; int *p = a;\n(*p)++; printf(\"%d %d\", a[0], *p);",
     ["11 11", "10 20", "11 20", "10 11"], 0, "(*p)++ increments the value pointed to; p itself does not move."),
    ("For  int a[] = {1, 2, 3, 4, 5}; int *p = a + 1;  the value of  *(p + 2)  is:",
     ["4", "3", "5", "2"], 0, "p points to a[1]; p + 2 points to a[3]."),
    ("After  int x = 5; int *p = &x; int **q = &p; **q = 7;  the value of x is:",
     ["7", "5", "Address of p", "Compile error"], 0, "**q → *p → x."),
    ("For  int a[3][3] = {1, 2, 3, 4, 5, 6, 7, 8, 9};  the value of  *(*(a + 1) + 2)  is:",
     ["6", "4", "8", "5"], 0, "*(a + 1) is row 1 {4, 5, 6}; element 2 of it is 6."),
    ("What does this print?\nchar *s = \"hello\"; printf(\"%c\", *(s + 4));",
     ["o", "l", "h", "Garbage"], 0, "Indices 0–4 are h, e, l, l, o."),
    ("Which declares fp as a pointer to a function taking two ints and returning int?",
     ["int (*fp)(int, int);", "int *fp(int, int);", "int fp*(int, int);", "(int *)fp(int, int);"], 0, "Without the parentheses, int *fp(int, int) declares a function returning int *."),
    ("int *a[10];  and  int (*b)[10];  declare respectively:",
     ["An array of 10 pointers to int; a pointer to an array of 10 ints", "A pointer to an array; an array of pointers", "Two arrays of 10 ints", "Two pointers to int"], 0, "[] binds tighter than *, unless parentheses change it."),
    ("A pointer that has been declared but not initialised is called a:",
     ["Wild pointer", "Null pointer", "Void pointer", "Smart pointer"], 0, "It holds an indeterminate address; dereferencing it is undefined behaviour."),
    ("Memory allocated with malloc() that is never freed and can no longer be reached causes a:",
     ["Memory leak", "Dangling pointer", "Stack overflow", "Segmentation of code"], 0, "The memory stays allocated until the program ends."),
    ("Which statement about calloc() and malloc() is correct?",
     ["calloc(n, size) allocates n × size bytes and sets them to zero; malloc(size) does not initialise", "malloc initialises memory to zero; calloc does not", "Both always initialise to zero", "calloc allocates on the stack"], 0, "Both return NULL if allocation fails."),
    ("In  const int *p;  and  int * const q;  which statements are true?",
     ["*p cannot be changed through p, but p can point elsewhere; q cannot point elsewhere, but *q can be changed", "Both are the same", "p is a constant pointer; q points to a constant", "Neither can be changed at all"], 0, "Read declarations right to left: q is a const pointer to int; p is a pointer to const int."),
    ("On a typical 64-bit system, sizeof(int *) and sizeof(char *) are:",
     ["8 and 8", "4 and 1", "8 and 1", "4 and 4"], 0, "All data pointers are usually the size of an address."),
    ("Which pointer operation is NOT allowed in C?",
     ["Adding two pointers", "Subtracting two pointers into the same array", "Adding an integer to a pointer", "Comparing two pointers into the same array"], 0, "The sum of two addresses has no meaning."),
    ("What does this print?\nint a[5] = {1, 2, 3, 4, 5}, *p, s = 0;\nfor (p = a; p < a + 5; p++) s += *p;\nprintf(\"%d\", s);",
     ["15", "5", "10", "Address of a"], 0, "The pointer walks over all five elements: 1 + 2 + 3 + 4 + 5."),
    ("What does this print?\nvoid swap(int *x, int *y) { int t = *x; *x = *y; *y = t; }\nint main() { int a = 1, b = 2; swap(&a, &b); printf(\"%d %d\", a, b); }",
     ["2 1", "1 2", "1 1", "2 2"], 0, "Passing addresses lets swap change the caller's variables."),
    ("Match the declaration with its meaning:\na. int *p  b. int **p  c. int (*p)[5]  d. int (*p)(void)\n1. Pointer to a function returning int  2. Pointer to an array of 5 ints  3. Pointer to pointer to int  4. Pointer to int",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-3, c-1, d-2", "a-4, b-2, c-3, d-1"], 0, "Parentheses bind * to p before [] or ()."),
    ("Assertion (A): Incrementing an int pointer advances it by sizeof(int) bytes.\nReason (R): The compiler scales pointer arithmetic by the size of the pointed-to type.",
     AR, 0, "That scaling is why p + 1 always points to the next element."),
    ("Assertion (A): A C function can change the caller's variable if it receives the variable's address.\nReason (R): C passes all arguments by reference.",
     AR, 2, "A is true. R is false: C always passes by value; passing an address simulates reference."),
    ("Assertion (A): A void pointer can be dereferenced directly without a cast.\nReason (R): A void pointer carries no information about the type of the object it points to.",
     AR, 3, "Because the type is unknown, the compiler cannot dereference it; R shows why A is false."),
    ("Assertion (A): calloc() initialises the allocated memory to zero.\nReason (R): malloc() takes a single argument, the number of bytes.",
     AR, 1, "Both true, but malloc's signature does not explain calloc's zero-initialisation."),
    ("Consider the statements:\nI. Returning the address of a local (automatic) variable from a function creates a dangling pointer.\nII. Memory from malloc() is freed automatically when the calling function returns.\nWhich is/are correct?",
     I_II, 0, "Heap memory lives until free() is called; locals die when the function returns."),
    ("Consider the statements:\nI. The name of an array is a constant pointer and cannot be incremented (a++ is illegal).\nII. A pointer variable set to the array can be incremented (p++ is legal).\nWhich is/are correct?",
     I_II, 2, "a is not a modifiable l-value, but p is an ordinary variable."),
    ("What does this print?\nint x = 10; int *p = &x; int **q = &p;\nprintf(\"%d\", **q + *p);",
     ["20", "10", "Address", "Compile error"], 0, "Both **q and *p are x: 10 + 10."),
    ("The standard library function used to change the size of a block previously allocated by malloc is:",
     ["realloc()", "resize()", "calloc()", "free()"], 0, "realloc may move the block and returns its new address."),
    ("Consider the statements:\nI. malloc() returns NULL if the requested memory cannot be allocated.\nII. Calling free() twice on the same pointer is safe.\nWhich is/are correct?",
     I_II, 0, "A double free is undefined behaviour and can corrupt the heap."),
]

FILES_PREPROC = [
    ("Opening a file with fopen(name, \"w\") when the file already exists:",
     ["Truncates it to zero length and writes from the beginning", "Appends to the end", "Fails with NULL", "Opens it read-only"], 0, "Use \"a\" to append or \"r+\" to update without truncating."),
    ("fopen() returns ______ if the file cannot be opened.",
     ["NULL", "EOF", "0 bytes", "-1"], 0, "Always test the returned FILE pointer before using it."),
    ("The FILE type and functions such as fopen and fprintf are declared in:",
     ["<stdio.h>", "<stdlib.h>", "<file.h>", "<string.h>"], 0, "stdio = standard input/output."),
    ("To write one structure variable rec to a binary file fp, the correct call is:",
     ["fwrite(&rec, sizeof(rec), 1, fp);", "fwrite(rec, 1, fp);", "fprintf(fp, rec);", "fputs(&rec, fp);"], 0, "fwrite(pointer, size of each item, number of items, stream)."),
    ("After  fseek(fp, 0, SEEK_END);  the call  ftell(fp)  returns:",
     ["The size of the file in bytes", "0", "EOF", "The number of lines"], 0, "The position at the end equals the file length (for binary streams)."),
    ("rewind(fp) is equivalent to:",
     ["fseek(fp, 0, SEEK_SET) (and clearing the error indicator)", "fseek(fp, 0, SEEK_END)", "fclose(fp)", "fflush(fp)"], 0, "It moves the position back to the start."),
    ("fclose(fp) is important because it:",
     ["Flushes buffered output to the file and releases the stream", "Deletes the file", "Moves to the end of the file", "Opens the file again"], 0, "Unflushed data may be lost if a program ends abnormally without closing."),
    ("The three standard streams opened automatically for a C program are:",
     ["stdin, stdout and stderr", "stdin, stdout and stdfile", "keyboard, screen and printer", "input, output and log"], 0, "stderr is unbuffered, so error messages appear immediately."),
    ("A program is run as  ./prog one two .  In main(int argc, char *argv[]), argc and argv[2] are:",
     ["3 and \"two\"", "2 and \"two\"", "3 and \"one\"", "2 and \"one\""], 0, "argv[0] is the program name, so there are 3 arguments."),
    ("In main(int argc, char *argv[]), the element argv[argc] is:",
     ["A null pointer", "The last argument", "The program name", "Undefined"], 0, "The standard guarantees argv[argc] == NULL."),
    ("To convert the command-line argument \"25\" in argv[1] to an int, a program can use:",
     ["atoi(argv[1])", "(int) argv[1]", "argv[1] - '0'", "int(argv[1])"], 0, "Casting the pointer gives an address, not the number; strtol is a safer alternative."),
    ("With  #define SQUARE(x) x * x ,  what is the value of  SQUARE(2 + 3) ?",
     ["11", "25", "10", "13"], 0, "It expands to 2 + 3 * 2 + 3 = 11; arguments are substituted as text."),
    ("If the macro is written with full parentheses as  #define SQUARE(x) ((x) * (x)) ,  then  SQUARE(2 + 3)  evaluates to:",
     ["25", "11", "10", "13"], 0, "Parentheses keep the argument together: (5) * (5)."),
    ("With  #define CUBE(x) (x * x * x) ,  what is the value of  CUBE(1 + 1) ?",
     ["4", "8", "6", "3"], 0, "Expands to (1 + 1 * 1 + 1 * 1 + 1) = 4."),
    ("Preprocessing happens:",
     ["Before compilation proper, on the source text", "After linking", "At run time", "After code generation"], 0, "Directives beginning with # are handled by the preprocessor."),
    ("The difference between  #include <file.h>  and  #include \"file.h\"  is that:",
     ["The quoted form searches the current (source) directory first, then the system directories", "They are identical", "The angle-bracket form searches only the current directory", "The quoted form includes only the first line"], 0, "Angle brackets are used for standard/system headers."),
    ("Include guards such as  #ifndef MY_H  #define MY_H … #endif  are used to:",
     ["Prevent a header's contents from being processed twice in one translation unit", "Speed up the linker", "Make variables global", "Hide the header from the compiler"], 0, "Double inclusion would cause redefinition errors."),
    ("With  #define STR(x) #x ,  STR(hello) expands to:",
     ["\"hello\"", "hello", "#hello", "'hello'"], 0, "# is the stringizing operator."),
    ("With  #define JOIN(a, b) a##b ,  JOIN(x, 1) expands to:",
     ["x1", "x 1", "\"x1\"", "x##1"], 0, "## is the token-pasting operator."),
    ("Which of the following is a predefined macro in ANSI C?",
     ["__LINE__", "__MAIN__", "__SIZE__", "__PROGRAM__"], 0, "__FILE__, __LINE__, __DATE__, __TIME__ and __STDC__ are predefined."),
    ("#undef NAME is used to:",
     ["Remove a previous macro definition of NAME", "Declare an undefined variable", "Delete a file", "Stop compilation"], 0, "NAME can then be redefined."),
    ("With  #define MAX(a, b) ((a) > (b) ? (a) : (b)) ,  int i = 5, j = 3;  and  m = MAX(i++, j); , the final value of i is:",
     ["7", "6", "5", "8"], 0, "i++ appears twice in the expansion and is evaluated twice because i > j – a classic macro side-effect trap."),
    ("Match the function with its action:\na. fseek  b. ftell  c. rewind  d. feof\n1. Returns non-zero after an attempt to read past the end  2. Returns the current file position  3. Moves the position to a chosen place  4. Moves the position to the beginning",
     ["a-3, b-2, c-4, d-1", "a-2, b-3, c-4, d-1", "a-3, b-4, c-2, d-1", "a-3, b-2, c-1, d-4"], 0, "All take a FILE * argument."),
    ("Match the fopen mode with its meaning:\na. \"r\"  b. \"w\"  c. \"a\"  d. \"r+\"\n1. Read and update an existing file  2. Write at the end, creating the file if needed  3. Create or truncate for writing  4. Read an existing file",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Adding b (e.g. \"rb\") opens the file in binary mode."),
    ("Assertion (A): The value returned by fgetc() should be stored in an int, not a char.\nReason (R): fgetc() returns EOF, a value distinct from every valid character.",
     AR, 0, "A char cannot reliably hold both all 256 byte values and EOF (−1)."),
    ("Assertion (A): Opening an existing file in \"w\" mode appends new data to its end.\nReason (R): The \"a\" mode opens a file for appending.",
     AR, 3, "\"w\" truncates; appending is what \"a\" does, which shows A is false."),
    ("Assertion (A): Include guards prevent a header from being included twice in a translation unit.\nReason (R): The preprocessor runs before the compiler proper.",
     AR, 1, "Both true, but the guard works because of the #ifndef/#define test, not merely because preprocessing comes first."),
    ("Assertion (A): Macros can be faster than functions for very small operations.\nReason (R): Macro arguments are type-checked by the compiler just like function arguments.",
     AR, 2, "A is true (no call overhead). R is false: macros are plain text substitution with no type checking."),
    ("Consider the statements:\nI. argv[0] normally holds the name used to run the program.\nII. argc counts only the arguments after the program name.\nWhich is/are correct?",
     I_II, 0, "argc includes the program name, so argc ≥ 1."),
    ("Consider the statements:\nI. In text mode, newline characters may be translated on some systems (for example to CR-LF on Windows).\nII. In binary mode, bytes are read and written without any translation.\nWhich is/are correct?",
     I_II, 2, "This is why binary data must be written to files opened with \"wb\"."),
]

TOPICS = {
    "Programming in C – Part 1": [("1 · Tokens, Identifiers and Data Types", TOKENS),
                                  ("2 · Sequence Control: Operators, Expressions and Statements", SEQUENCE),
                                  ("3 · Subprogram Control and Functions", SUBPROGRAMS),
                                  ("4 · Arrays, Structures, Unions and Strings", ARRAYS_STRINGS)],
    "Programming in C – Part 2": [("1 · Pointers", POINTERS),
                                  ("2 · File Handling, Command Line Arguments and Preprocessors", FILES_PREPROC)],
}
