"""Paper 2 · Unit 4 · Language Design and Translation Issues; Elementary Data Types (5 sub-topics × 30).
References: Pratt & Zelkowitz, Programming Languages: Design and Implementation; Sebesta, Concepts of Programming Languages;
Aho, Lam, Sethi & Ullman (Dragon book); Hopcroft, Motwani & Ullman."""
from packlib import AR, I_II

CONCEPTS = [
    ("A program in which computation is expressed as facts and rules, and execution consists of answering queries, belongs to which paradigm?",
     ["Logic programming", "Imperative programming", "Object-oriented programming", "Functional programming"], 0,
     "Logic languages such as Prolog state facts and rules; the system answers queries by inference."),
    ("The imperative paradigm is characterised mainly by:",
     ["Statements that change program state through assignment", "Functions without side effects", "Rules and backtracking", "Message passing between objects only"], 0,
     "Imperative languages mirror the von Neumann machine: variables are memory cells updated by assignment."),
    ("Referential transparency, a key property of pure functional languages, means that:",
     ["An expression can be replaced by its value without changing the program's behaviour", "Variables can be reassigned many times", "Pointers are always visible to the programmer", "Every function must be recursive"], 0,
     "With no side effects, f(x) always gives the same value, so it can be substituted by that value."),
    ("Which language is primarily a pure functional language?",
     ["Haskell", "COBOL", "Fortran", "C"], 0, "Haskell is a lazy, purely functional language; the others are imperative."),
    ("Functional programming languages are based on which formal model of computation?",
     ["Lambda calculus", "Predicate calculus", "Relational algebra", "Petri nets"], 0,
     "Church's lambda calculus underlies LISP, ML and Haskell; logic languages are based on predicate calculus."),
    ("The 'von Neumann bottleneck' refers to:",
     ["The limited speed of transfer between memory and the CPU, which shaped imperative languages", "The limit on the number of registers in a CPU", "The cost of writing compilers", "The slowness of magnetic tape"], 0,
     "Instructions and data travel through one path between memory and processor; imperative languages model this cell-by-cell style."),
    ("Orthogonality in programming-language design means:",
     ["A small set of primitive constructs can be combined in a small number of ways, and every combination is legal and meaningful", "Every construct has exactly one syntax", "The language has no reserved words", "Programs run on every hardware platform"], 0,
     "Orthogonal features combine freely without special exceptions (Sebesta; Pratt: 'orthogonality')."),
    ("Consider the statements:\nI. Readability and writability of a language can conflict with each other.\nII. Making a language more and more orthogonal without limit always improves it.\nWhich is/are correct?",
     I_II, 0, "Too much orthogonality creates many useless combinations (ALGOL 68 is the classic example), so II is false."),
    ("Which language feature most directly reduces program reliability?",
     ["Aliasing – two or more names for the same memory cell", "Strong type checking", "Exception handling", "Restricted pointer use"], 0,
     "Aliasing lets a change through one name silently change another; the other features improve reliability."),
    ("In C, the binding of a variable to its data type occurs at:",
     ["Compile time", "Language design time", "Load time", "Run time"], 0, "C is statically typed: types are bound by declarations when the program is compiled."),
    ("The binding of the symbol '*' to the multiplication operation takes place at:",
     ["Language design time", "Compile time", "Link time", "Run time"], 0, "Operator symbols get their meaning when the language is defined."),
    ("Java is usually implemented as a:",
     ["Hybrid system: source compiled to bytecode, which a JVM interprets or JIT-compiles", "Pure interpreter of source code", "Pure compiler to native code only", "Assembler"], 0,
     "javac produces platform-independent bytecode; the JVM interprets it or compiles hot code just-in-time."),
    ("Compared with compilation, pure interpretation has which main disadvantage?",
     ["Much slower execution, because each statement is decoded every time it runs", "No run-time error messages", "Cannot run small programs", "It needs a linker"], 0,
     "Decoding high-level statements repeatedly makes interpretation typically 10–100 times slower (Sebesta)."),
    ("A 'virtual computer' in Pratt's layered view is:",
     ["Hardware together with the software layers (OS, translators) that together behave like a machine executing the language", "A computer simulated only on paper", "A cloud server", "A computer without memory"], 0,
     "Each layer of software on top of hardware presents a more convenient 'virtual machine' to the layer above."),
    ("Which of the following is NOT normally a component of a programming environment?",
     ["The arithmetic-logic unit of the target CPU", "Editor", "Debugger", "Test-data generator"], 0,
     "A programming environment is the set of software tools (editors, debuggers, verifiers, test tools) used while developing programs."),
    ("For separate compilation of a subprogram, the compiler needs to know:",
     ["The specifications (interfaces) of the other subprograms it calls", "The complete source code of every other subprogram", "The run-time values of all variables", "The machine's clock speed"], 0,
     "Header files/prototypes give the needed interface information; the linker later joins the separately compiled pieces."),
    ("Programs in an embedded-system environment differ most from batch programs in that they:",
     ["Often have real-time constraints and must run without human intervention", "Always use punched cards", "Never use interrupts", "Run only once and stop"], 0,
     "Embedded software controls devices and must respond within time limits, reliably and autonomously."),
    ("Match the paradigm with a typical language:\na. Imperative  b. Functional  c. Logic  d. Object-oriented\n1. Prolog  2. Smalltalk  3. LISP  4. C",
     ["a-4, b-3, c-1, d-2", "a-3, b-4, c-1, d-2", "a-4, b-1, c-3, d-2", "a-2, b-3, c-1, d-4"], 0,
     "C – imperative; LISP – functional; Prolog – logic; Smalltalk – pure object-oriented."),
    ("Match the language with its main original purpose or feature:\na. FORTRAN  b. COBOL  c. LISP  d. ALGOL 60\n1. Business data processing  2. First language defined using BNF  3. Scientific computation  4. List processing and AI",
     ["a-3, b-1, c-4, d-2", "a-1, b-3, c-4, d-2", "a-3, b-1, c-2, d-4", "a-4, b-1, c-3, d-2"], 0,
     "FORTRAN (1957) – scientific; COBOL (1960) – business; LISP (1958) – list processing/AI; ALGOL 60 – syntax described in BNF."),
    ("The concepts of class and object were first introduced in:",
     ["Simula 67", "Smalltalk-80", "C++", "Ada"], 0, "Simula 67 (Dahl and Nygaard) introduced classes for simulation; Smalltalk and C++ came later."),
    ("Assertion (A): Pure functional programs are comparatively easy to evaluate in parallel.\nReason (R): Without side effects, independent sub-expressions can be evaluated in any order.",
     AR, 0, "Since evaluation order cannot change results, independent parts can safely run in parallel."),
    ("Assertion (A): Java bytecode can run on any machine that has a Java Virtual Machine.\nReason (R): The Java compiler translates source code directly into the native machine code of the target processor.",
     AR, 2, "A is true. R is false: javac produces bytecode, not native code – that is exactly why it is portable."),
    ("Assertion (A): C is a strongly typed language in the strict sense.\nReason (R): C allows unions and implicit conversions that are not type-checked.",
     AR, 3, "Because of unchecked unions, casts and coercions, C is not strongly typed; R is true and shows why A is false."),
    ("Assertion (A): COBOL is widely used for business data processing.\nReason (R): COBOL was designed by a committee (CODASYL) around 1959–60.",
     AR, 1, "Both are true, but being designed by a committee does not explain its use in business; its record handling and English-like syntax do."),
    ("A language in which the order of statement execution is decided mainly by user actions such as clicks and key presses follows the:",
     ["Event-driven paradigm", "Logic paradigm", "Batch paradigm", "Functional paradigm"], 0, "Event-driven programs wait for events and run handlers; common in GUIs and JavaScript."),
    ("Consider the statements about scripting languages such as Python and JavaScript:\nI. They are usually interpreted (or compiled to bytecode at run time).\nII. They are usually dynamically typed.\nWhich is/are correct?",
     I_II, 2, "Both statements describe typical scripting languages."),
    ("SQL is best described as:",
     ["A declarative language – the user states what data is wanted, not how to get it", "An imperative language with loops over files", "A machine language", "A logic language based on backtracking"], 0,
     "The query optimiser decides the access strategy; the programmer only specifies the result."),
    ("Which statement about compilers and interpreters is INCORRECT?",
     ["An interpreter produces an object program that is saved for later execution", "A compiler translates the whole program before it runs", "An interpreter can give error messages close to the source statement", "Compiled code generally runs faster"], 0,
     "An interpreter executes directly and does not save an object program; a compiler does."),
    ("Which is NOT one of the essential features of object-oriented programming?",
     ["Pointer arithmetic", "Encapsulation (abstract data types)", "Inheritance", "Dynamic binding of method calls (polymorphism)"], 0,
     "Sebesta lists abstract data types, inheritance and dynamic binding; pointer arithmetic has nothing to do with OOP."),
    ("Which of the following contributes most to the 'cost of use' of a language, as discussed by Pratt?",
     ["Costs of program execution, translation, creation/testing and maintenance together", "Only the price of the compiler licence", "Only the cost of the hardware", "Only the time to type the program"], 0,
     "Pratt lists execution, translation, program creation/testing/use and maintenance as the costs of using a language."),
]

SYNTAX = [
    ("The syntax of a programming language specifies:",
     ["The form or structure of expressions, statements and program units", "The meaning of programs", "How fast programs run", "The hardware needed"], 0, "Syntax = form; semantics = meaning."),
    ("The output of the lexical analyser is:",
     ["A stream of tokens", "A parse tree", "Object code", "An annotated syntax tree"], 0, "The scanner groups characters into lexemes and passes tokens to the parser."),
    ("In C, a missing semicolon at the end of a statement is detected during:",
     ["Syntax analysis (parsing)", "Lexical analysis", "Code optimisation", "Linking"], 0, "Each character is a valid token; it is the sequence of tokens that violates the grammar."),
    ("An error such as adding an integer to a structure variable in C is detected during:",
     ["Semantic analysis (type checking)", "Lexical analysis", "Loading", "Code generation"], 0, "The statement may be syntactically correct; the type rules are checked in semantic analysis."),
    ("Information about identifiers – their names, types and scopes – collected during translation is stored in the:",
     ["Symbol table", "Parse stack", "Object file header", "Heap"], 0, "The symbol table is built and used by all phases of the translator."),
    ("In BNF (Backus–Naur Form), the symbol ::= means:",
     ["'is defined as'", "'is equal to' (assignment)", "'is not equal to'", "'end of rule'"], 0, "<expr> ::= <expr> + <term> reads 'expr is defined as expr + term'."),
    ("BNF was first used to describe the syntax of:",
     ["ALGOL 60", "FORTRAN I", "COBOL", "C"], 0, "John Backus and Peter Naur used it in the ALGOL 60 report."),
    ("Extended BNF (EBNF) adds which notations?",
     ["{ } for repetition and [ ] for optional parts", "Only the | symbol", "Pointers and arrays", "Semantic actions in Java"], 0, "EBNF makes grammars shorter; it does not describe more languages than BNF."),
    ("A grammar is ambiguous if:",
     ["Some sentence has two or more distinct parse trees", "It has more than one start symbol", "It has recursive rules", "It generates an infinite language"], 0, "Equivalently, some sentence has two distinct leftmost derivations."),
    ("With the grammar E → E + E | E * E | id, how many distinct parse trees does id + id * id have?",
     ["2", "1", "3", "4"], 0, "Either + or * can be the root operator: (id + id) * id or id + (id * id)."),
    ("With the ambiguous grammar E → E + E | id, how many distinct parse trees does id + id + id + id have?",
     ["5", "3", "4", "6"], 0, "Three operators can be bracketed in Catalan(3) = 5 ways."),
    ("In an unambiguous expression grammar, an operator of higher precedence is placed:",
     ["At a lower level of the grammar, so it appears nearer the leaves of the parse tree", "At the start symbol", "In a separate grammar", "Nowhere – precedence cannot be expressed in grammars"], 0,
     "E → E + T, T → T * F: * is generated lower in the tree, so it binds tighter and is evaluated first."),
    ("A left-recursive rule such as E → E − T | T gives the operator − :",
     ["Left associativity", "Right associativity", "No associativity", "Higher precedence than *"], 0, "a − b − c is parsed as (a − b) − c."),
    ("How many tokens are in the C statement:  sum = sum + x * 10;",
     ["8", "7", "6", "9"], 0, "sum, =, sum, +, x, *, 10, ; → 8 tokens."),
    ("How many tokens are in the C statement:  printf(\"%d\", a);",
     ["7", "5", "6", "8"], 0, "printf, (, \"%d\", ',', a, ), ; → 7 tokens; a string literal is a single token."),
    ("Which of the following belongs to the synthesis part of translation?",
     ["Code generation", "Lexical analysis", "Syntactic analysis", "Semantic analysis"], 0, "Analysis breaks down the source; synthesis (optimisation and code generation) builds the object program."),
    ("Resolving external references between separately compiled modules is done by the:",
     ["Linker (linkage editor)", "Lexical analyser", "Parser", "Preprocessor"], 0, "The linker combines object modules and library routines into one executable."),
    ("Relocation, done by a relocating loader or linker, means:",
     ["Adjusting addresses in object code so the program can run at a location different from the one assumed at translation", "Moving the source file to another folder", "Rewriting the program in another language", "Reordering statements for speed"], 0,
     "Address-sensitive words are modified by the load (relocation) address."),
    ("Replacing  x * 2  by  x + x  or  x << 1  is an example of:",
     ["Strength reduction", "Constant folding", "Dead-code elimination", "Loop unrolling"], 0, "An expensive operation is replaced by a cheaper equivalent one."),
    ("Evaluating  3 * 4  at compile time and using 12 in the object code is called:",
     ["Constant folding", "Strength reduction", "Inlining", "Register allocation"], 0, "Expressions with constant operands are computed by the compiler itself."),
    ("A cross-compiler is a compiler that:",
     ["Runs on one machine and produces code for a different machine", "Translates between two high-level languages only", "Compiles itself", "Works only on crossed loops"], 0, "Used to build software for embedded devices from a desktop computer."),
    ("Match the phase with its main output:\na. Lexical analyser  b. Parser  c. Semantic analyser  d. Code generator\n1. Target code  2. Tokens  3. Parse tree  4. Type-checked (annotated) tree",
     ["a-2, b-3, c-4, d-1", "a-3, b-2, c-4, d-1", "a-2, b-4, c-3, d-1", "a-1, b-3, c-4, d-2"], 0, "Tokens → parse tree → annotated tree → target code."),
    ("Match the error with the phase that normally detects it:\na. Illegal character @ in an identifier  b. Unbalanced parentheses  c. Use of an undeclared variable  d. Division by zero with values read at run time\n1. Semantic analysis  2. Syntax analysis  3. Execution  4. Lexical analysis",
     ["a-4, b-2, c-1, d-3", "a-2, b-4, c-1, d-3", "a-4, b-1, c-2, d-3", "a-4, b-2, c-3, d-1"], 0,
     "Characters → lexical; structure → syntax; declarations/types → semantic; values known only at run time → execution."),
    ("Assertion (A): Comments and white space are removed during lexical analysis.\nReason (R): They do not affect the meaning of the program.",
     AR, 0, "Because they carry no meaning for later phases, the scanner discards them."),
    ("Assertion (A): A context-free grammar can express every syntactic restriction of C.\nReason (R): The rule 'a variable must be declared before it is used' is context-sensitive.",
     AR, 3, "Declare-before-use cannot be expressed by a CFG, so such rules are checked as static semantics; A is false."),
    ("Assertion (A): Syntax diagrams (railroad diagrams) are an alternative to BNF.\nReason (R): The syntax of Pascal was popularised using syntax diagrams.",
     AR, 1, "Both are true, but Pascal's use of them does not explain why they are an alternative notation."),
    ("Assertion (A): Lexical analysers are usually built from finite automata.\nReason (R): The tokens of most languages can be described only by context-sensitive grammars.",
     AR, 2, "A is true. R is false: tokens are described by regular expressions, which is why finite automata suffice."),
    ("Consider the statements:\nI. Every regular language is context-free.\nII. Every context-free language is regular.\nWhich is/are correct?",
     I_II, 0, "Regular ⊂ context-free; {aⁿbⁿ} is context-free but not regular."),
    ("In C, in the statement  if (a) if (b) s1; else s2;  the else is associated with:",
     ["The nearest (inner) if", "The outer if", "Both ifs", "Neither – it is a syntax error"], 0, "The 'dangling else' is resolved by matching the nearest unmatched if."),
    ("Attribute grammars are mainly used to describe:",
     ["Static semantics, such as type compatibility rules", "Hardware timing", "Lexical tokens only", "Operating-system calls"], 0, "Attributes attached to grammar symbols carry types and other information checked during semantic analysis."),
]

AUTOMATA = [
    ("Match the grammar type (Chomsky hierarchy) with its recognising machine:\na. Type 0 (unrestricted)  b. Type 1 (context-sensitive)  c. Type 2 (context-free)  d. Type 3 (regular)\n1. Finite automaton  2. Pushdown automaton  3. Linear bounded automaton  4. Turing machine",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-1, b-2, c-3, d-4"], 0, "TM ⊃ LBA ⊃ PDA ⊃ FA, matching types 0 to 3."),
    ("In a deterministic finite automaton (DFA):",
     ["For each state and each input symbol there is exactly one next state", "There may be several next states for the same input", "ε-moves are allowed", "A stack is used"], 0, "Determinism = one unique transition per (state, symbol)."),
    ("An NFA with 4 states is converted to a DFA by subset construction. The DFA can have at most:",
     ["16 states", "4 states", "8 states", "24 states"], 0, "Each DFA state is a subset of the NFA's states: at most 2⁴ = 16."),
    ("The transition function of an NFA (without ε-moves) is:",
     ["δ: Q × Σ → 2^Q", "δ: Q × Σ → Q", "δ: Q → Σ", "δ: Q × Σ × Γ → Q × Γ*"], 0, "It maps a state and a symbol to a set of states; the last option is a PDA's."),
    ("The minimum number of states of a DFA over {0,1} accepting all strings whose length is divisible by 3 is:",
     ["3", "2", "4", "6"], 0, "States track length mod 3: 0, 1, 2."),
    ("The minimum number of states of a DFA over {0,1} accepting all strings that end in 01 is:",
     ["3", "2", "4", "5"], 0, "States: nothing useful seen, last symbol 0, last two symbols 01 (accepting)."),
    ("The minimum number of states of a DFA over {a,b} accepting strings with exactly two a's is:",
     ["4", "3", "2", "5"], 0, "Counts 0, 1, 2 a's plus a dead state for more than two."),
    ("The minimum number of states of a DFA over {0,1} accepting strings whose second-last symbol is 1 is:",
     ["4", "2", "3", "8"], 0, "The DFA must remember the last two symbols: 2² = 4 states."),
    ("The regular expression (a+b)*abb denotes:",
     ["All strings over {a,b} ending in abb", "All strings starting with abb", "Only the string abb", "All strings containing exactly one abb"], 0, "Any prefix (a+b)* followed by abb."),
    ("How many strings of length 3 over {a,b} are in the language of a*b*?",
     ["4", "8", "3", "2"], 0, "aaa, aab, abb, bbb – some a's followed by some b's."),
    ("Which of the following languages is NOT regular?",
     ["{ aⁿbⁿ | n ≥ 0 }", "{ aⁿ | n ≥ 0 }", "Strings over {a,b} with an even number of a's", "{ aᵐbⁿ | m, n ≥ 0 }"], 0, "Matching counts needs unbounded memory; the pumping lemma proves aⁿbⁿ is not regular."),
    ("The language { aⁿbⁿcⁿ | n ≥ 1 } is:",
     ["Context-sensitive but not context-free", "Regular", "Context-free", "Not recursively enumerable"], 0, "A single stack cannot match three counts; an LBA can."),
    ("The language { wwᴿ | w ∈ {a,b}* } (even-length palindromes) is:",
     ["Context-free but not deterministic context-free", "Regular", "Deterministic context-free", "Not context-free"], 0, "An NPDA must guess the middle; no DPDA can accept it."),
    ("The language generated by S → aSb | ε is:",
     ["{ aⁿbⁿ | n ≥ 0 }", "{ aⁿbᵐ | n, m ≥ 0 }", "(ab)*", "{ a²ⁿ | n ≥ 0 }"], 0, "Each step adds one a on the left and one b on the right."),
    ("The grammar S → aS | bS | a generates:",
     ["All strings over {a,b} that end in a", "All strings that start with a", "Only strings of a's", "Strings with exactly one a"], 0, "Any sequence of a/b followed finally by a."),
    ("In a context-sensitive grammar every production α → β satisfies:",
     ["|α| ≤ |β|", "|α| = 1", "β is a single terminal", "α is a single terminal"], 0, "Non-contracting productions define type-1 grammars."),
    ("A Moore machine differs from a Mealy machine in that its output depends on:",
     ["The current state only", "The current state and current input", "The input only", "The stack contents"], 0, "Mealy output is attached to transitions (state + input)."),
    ("For an input string of length n, a Moore machine produces an output string of length:",
     ["n + 1", "n", "n − 1", "2n"], 0, "It outputs once in the start state and once after each input symbol."),
    ("The minimum number of states of a DFA over {0,1} accepting all strings that contain at least one 1 is:",
     ["2", "1", "3", "4"], 0, "One state for 'no 1 seen yet' and one accepting state that loops on 0 and 1."),
    ("Which regular expression is NOT equivalent to (a+b)*?",
     ["(ab)*", "(a*b*)*", "(a* + b*)*", "(a+b)*(a+b)*"], 0, "(ab)* cannot generate 'a' or 'ba'; the others generate every string over {a,b}."),
    ("Consider the statements:\nI. Deterministic pushdown automata accept every context-free language.\nII. Every regular language is accepted by some deterministic pushdown automaton.\nWhich is/are correct?",
     I_II, 1, "DPDAs are weaker than NPDAs (wwᴿ), but a DPDA can simply ignore its stack and act as a DFA."),
    ("Consider the statements:\nI. Context-free languages are closed under union.\nII. Context-free languages are closed under intersection.\nWhich is/are correct?",
     I_II, 0, "aⁿbⁿcᵐ ∩ aᵐbⁿcⁿ = aⁿbⁿcⁿ, which is not context-free, so II is false."),
    ("Assertion (A): Every DFA is also an NFA.\nReason (R): A DFA is simply an NFA in which each transition leads to exactly one state.",
     AR, 0, "The definition of an NFA includes the deterministic case."),
    ("Assertion (A): A finite automaton can recognise the language of balanced parentheses.\nReason (R): A finite automaton has only a finite amount of memory in the form of its states.",
     AR, 3, "Nesting depth is unbounded, so a finite automaton cannot count it; R is true and explains why A is false."),
    ("Assertion (A): NFAs and DFAs accept exactly the same class of languages.\nReason (R): An NFA may have more than one transition for the same state and input symbol.",
     AR, 1, "Both true, but R describes nondeterminism; the equivalence follows from subset construction."),
    ("Assertion (A): The halting problem for Turing machines is undecidable.\nReason (R): Turing machines are less powerful than pushdown automata.",
     AR, 2, "A is true (Turing, 1936). R is false: Turing machines are the most powerful of these models."),
    ("Left-linear and right-linear grammars generate exactly the:",
     ["Regular languages", "Context-free languages", "Context-sensitive languages", "Recursive languages"], 0, "Linear grammars with the non-terminal at one end correspond to finite automata."),
    ("In compilers, finite automata and pushdown automata are used respectively for:",
     ["Lexical analysis and syntax analysis", "Code generation and optimisation", "Linking and loading", "Syntax analysis and lexical analysis"], 0, "Tokens are regular; program structure is context-free."),
    ("The minimum number of states of a DFA over {a,b} accepting all strings of length at least 2 is:",
     ["3", "2", "4", "1"], 0, "States for length 0, length 1 and length ≥ 2 (accepting, looping)."),
    ("The minimum number of states of a DFA that accepts binary numbers (read from the most significant bit) divisible by 3 is:",
     ["3", "2", "4", "5"], 0, "States track the value mod 3; reading bit b moves r to (2r + b) mod 3."),
]

TYPES_OBJECTS = [
    ("In Pratt's terminology, a data object is:",
     ["A run-time grouping of one or more pieces of data – a container for data values", "A class in an object-oriented language only", "A constant written in the source program", "A file on disk only"], 0, "A data object is a location (container); a data value is what it holds."),
    ("In the C assignment  x = x + 1;  the x on the left-hand side denotes its:",
     ["l-value (location)", "r-value (value)", "Type", "Scope"], 0, "The left side needs a location to store into; the right side uses x's current value."),
    ("The lifetime of a data object is:",
     ["The period of execution during which it exists and is bound to storage", "The number of lines in which its name is visible", "Its size in bytes", "The time taken to compile it"], 0, "Lifetime is temporal; scope is textual visibility."),
    ("Which group of languages relies mainly on dynamic type checking?",
     ["Python, LISP and JavaScript", "C, Pascal and Ada", "FORTRAN and COBOL", "Assembly languages only"], 0, "In these languages types belong to values and are checked when operations execute."),
    ("A language is called strongly typed if:",
     ["All type errors are always detected, either at compile time or at run time", "Every variable must be declared at the start of the program", "It has at least ten built-in types", "It allows no conversions at all"], 0, "Strong typing = no type error goes undetected (Sebesta)."),
    ("Coercion is:",
     ["An implicit type conversion inserted automatically by the translator", "An explicit cast written by the programmer", "A run-time error", "A kind of loop"], 0, "In 2 + 3.5, C coerces 2 to double."),
    ("In C, what is the value of  (float)(7 / 2) ?",
     ["3.0", "3.5", "4.0", "3"], 0, "7 / 2 is integer division = 3, which is then converted to 3.0."),
    ("In C, after  int i = 5;  double d = i / 2;  the value of d is:",
     ["2.0", "2.5", "3.0", "0.0"], 0, "i / 2 is evaluated as integer division (2) before conversion to double."),
    ("In C, what is printed by  char c = 'A' + 2;  printf(\"%c\", c); ?",
     ["C", "B", "67", "A2"], 0, "'A' is 65; 65 + 2 = 67 = 'C'."),
    ("Which conversion is a narrowing conversion that may lose information?",
     ["double to int", "int to double", "short to long", "float to double"], 0, "The fractional part (and possibly range) is lost; the others widen."),
    ("Under structural type equivalence, two types are equivalent if:",
     ["They have the same structure, even if their names differ", "They have the same name only", "They are declared on the same line", "They occupy the same address"], 0, "Name equivalence requires the same type name; structural equivalence compares components."),
    ("Which of the following is NOT a purpose of declarations (Pratt)?",
     ["To speed up the linker", "Choosing storage representations", "Storage management information such as lifetime", "Enabling static type checking and resolving overloaded operations"], 0,
     "Declarations help storage representation, storage management, polymorphic/overloaded operations and static type checking."),
    ("A binding that occurs before run time and remains unchanged throughout execution is called:",
     ["Static binding", "Dynamic binding", "Late binding", "Lazy binding"], 0, "Dynamic binding happens or can change during execution."),
    ("The specification of a data type consists of:",
     ["Its attributes, the values its objects may take and the operations defined on them", "Only its storage size", "Only its name", "Its machine instructions"], 0, "The implementation then gives storage representation and algorithms for the operations."),
    ("A run-time descriptor (dope vector) of a data object stores:",
     ["Its attributes, such as type, bounds and size, needed during execution", "The source code of the object", "The object's comments", "The compiler version"], 0, "E.g. an array descriptor holds its bounds and element size for subscript checking."),
    ("The specification  + : integer × integer → integer  is called the operation's:",
     ["Signature", "Signal", "Semantics", "Scope"], 0, "A signature gives the domain (argument types) and range (result type)."),
    ("An operation that modifies one of its arguments in addition to returning a result is said to have a:",
     ["Side effect", "Coercion", "Signature", "Binding"], 0, "E.g. x++ returns a value and also changes x."),
    ("A dangling reference is:",
     ["An access path that still exists to a data object that has been deallocated", "A data object with no access path left", "A reference to a constant", "A pointer that is always NULL"], 0, "The reverse situation – an object with no access path – is garbage."),
    ("When two names in a program refer to the same data object at the same time, this is called:",
     ["Aliasing", "Overloading", "Coercion", "Encapsulation"], 0, "E.g. passing the same variable twice by reference."),
    ("In ML or Haskell, the compiler can find the types of most expressions without declarations. This is called:",
     ["Type inference", "Dynamic typing", "Coercion", "Type erasure"], 0, "Hindley–Milner type inference deduces types statically."),
    ("Match the category of variable with the time its storage is bound:\na. Static  b. Stack-dynamic  c. Explicit heap-dynamic  d. Implicit heap-dynamic\n1. Created by new / malloc  2. For the whole program run  3. When a value is assigned, e.g. in Python  4. When its declaration is elaborated on subprogram entry",
     ["a-2, b-4, c-1, d-3", "a-4, b-2, c-1, d-3", "a-2, b-1, c-4, d-3", "a-2, b-4, c-3, d-1"], 0, "Sebesta's four categories of variables by lifetime."),
    ("Assertion (A): Dynamic type checking gives the programmer more flexibility.\nReason (R): With dynamic type checking, type information has to be kept with each data object at run time.",
     AR, 1, "Both true; R states a cost of dynamic checking, not the reason for its flexibility."),
    ("Assertion (A): C performs complete static type checking.\nReason (R): C unions allow the same storage to be read as different types without any check.",
     AR, 3, "Unchecked unions (and casts) mean C's static checking is incomplete; R shows why A is false."),
    ("Assertion (A): Coercions can reduce the reliability of programs.\nReason (R): Implicit conversions can hide type errors that the compiler would otherwise report.",
     AR, 0, "E.g. mistyping a float variable for an int one goes unnoticed when coercion is allowed."),
    ("Assertion (A): A dangling reference arises when storage is freed while a pointer still refers to it.\nReason (R): Garbage collection is the main cause of dangling references.",
     AR, 2, "A is true. R is false: garbage collection frees only unreachable objects, so it prevents dangling references."),
    ("Consider the statements:\nI. An r-value is the value stored in a data object.\nII. A named constant has an l-value that can be the target of an assignment.\nWhich is/are correct?",
     I_II, 0, "A constant's value cannot be changed by assignment, so II is false."),
    ("In Python,  x = 5  followed by  x = 'hello'  is legal because:",
     ["Python binds types to values dynamically at assignment", "Python converts 'hello' to an integer", "x is declared as a string", "Python ignores the first assignment"], 0, "The variable is only a name; its type follows the object it currently refers to."),
    ("Using + for both integer and floating-point addition is an example of:",
     ["Overloading (ad hoc polymorphism)", "Coercion only", "Aliasing", "Type inference"], 0, "The same operator symbol stands for different operations chosen by operand types."),
    ("In a statically typed language, the type of a variable is bound at:",
     ["Compile time", "Run time", "Load time", "Language design time"], 0, "Static typing = types known and checked before execution."),
    ("Consider the statements:\nI. The scope of a variable is a textual (static) property.\nII. The lifetime of a variable is a temporal (run-time) property.\nWhich is/are correct?",
     I_II, 2, "Scope = region of program text where the name is visible; lifetime = time during which storage exists. A static local in C has local scope but whole-program lifetime."),
]

SCALAR_COMPOSITE = [
    ("Which of the following is NOT a scalar data type?",
     ["Character string", "Integer", "Enumeration", "Boolean"], 0, "A scalar object holds a single value; a string is a composite of characters."),
    ("The range of a 16-bit two's-complement integer is:",
     ["−32768 to 32767", "−32767 to 32767", "0 to 65535", "−65536 to 65535"], 0, "n bits give −2ⁿ⁻¹ to 2ⁿ⁻¹ − 1."),
    ("The range of an 8-bit unsigned integer is:",
     ["0 to 255", "0 to 256", "−128 to 127", "1 to 256"], 0, "2⁸ = 256 values starting from 0."),
    ("The 8-bit two's-complement representation of −5 is:",
     ["11111011", "10000101", "11111010", "00000101"], 0, "+5 = 00000101; invert → 11111010; add 1 → 11111011."),
    ("A subrange type such as 1..10 in Pascal offers which advantages?",
     ["Less storage and automatic range checking", "Faster floating-point arithmetic", "Dynamic typing", "Unlimited range"], 0, "Values can be packed in fewer bits and out-of-range assignments are detected."),
    ("In C, given  enum colour {RED, GREEN = 5, BLUE};  the value of BLUE is:",
     ["6", "2", "5", "1"], 0, "RED = 0, GREEN = 5 explicitly, BLUE = GREEN + 1 = 6."),
    ("A Boolean value needs only one bit, but it is usually stored in a whole byte because:",
     ["The byte is normally the smallest addressable unit of memory", "Booleans need 8 values", "It is required by ASCII", "Bits cannot store true/false"], 0, "Accessing single bits needs extra masking operations."),
    ("In C, the value of  '7' − '0'  is:",
     ["7", "55", "48", "'7'"], 0, "Digit characters have consecutive codes: 55 − 48 = 7."),
    ("In IEEE 754 single precision, the fields are:",
     ["1 sign bit, 8 exponent bits, 23 fraction bits", "1 sign bit, 11 exponent bits, 52 fraction bits", "1 sign bit, 7 exponent bits, 24 fraction bits", "8 sign bits, 8 exponent bits, 16 fraction bits"], 0, "Total 32 bits; the second option is double precision."),
    ("The exponent bias used in IEEE 754 single precision is:",
     ["127", "128", "1023", "255"], 0, "Double precision uses 1023."),
    ("In IEEE 754 single precision, the stored (biased) exponent field of the number 1.0 is:",
     ["01111111", "00000000", "10000000", "00000001"], 0, "1.0 = 1.0 × 2⁰; biased exponent = 0 + 127 = 127 = 01111111."),
    ("Comparing two floating-point values with == is risky because:",
     ["Many decimal fractions such as 0.1 cannot be represented exactly in binary", "Floating-point numbers have no sign", "The == operator is illegal for floats", "Floating values are always rounded to integers"], 0, "0.1 + 0.2 == 0.3 is false in binary floating point; compare with a tolerance."),
    ("Fixed-point decimal representation is preferred for:",
     ["Money and business calculations that need exact decimal digits", "Scientific calculations with very large ranges", "Storing characters", "Graphics coordinates only"], 0, "COBOL and PL/I provide fixed-point decimal types for this reason."),
    ("In C,  strlen(\"hello\")  and  sizeof(\"hello\")  are respectively:",
     ["5 and 6", "5 and 5", "6 and 6", "6 and 5"], 0, "sizeof counts the terminating '\\0'; strlen does not."),
    ("A file differs from most other data objects because:",
     ["It resides on secondary storage and its lifetime can be longer than the program that created it", "It can hold only integers", "It is always stored in registers", "It has no type"], 0, "Pratt: files are the usual way data persists between program runs."),
    ("An array is ______, whereas a record (structure) is ______.",
     ["homogeneous; heterogeneous", "heterogeneous; homogeneous", "scalar; composite", "dynamic; static"], 0, "Array elements share one type; record fields can have different types."),
    ("A[10][20] is stored in row-major order from base address 1000, with 4 bytes per element and 0-based indices. The address of A[5][6] is:",
     ["1424", "1106", "1256", "1400"], 0, "1000 + (5 × 20 + 6) × 4 = 1000 + 424 = 1424."),
    ("A[1..10, 1..20] is stored in column-major order from base address 2000, with 2 bytes per element. The address of A[3, 4] is:",
     ["2064", "2098", "2044", "2060"], 0, "Columns before: (4 − 1) × 10 = 30; rows before in its column: 3 − 1 = 2; 2000 + 32 × 2 = 2064."),
    ("How many elements does the array A[−2..5, 3..7] have?",
     ["40", "35", "48", "30"], 0, "Rows: 5 − (−2) + 1 = 8; columns: 7 − 3 + 1 = 5; 8 × 5 = 40."),
    ("The size of a C union is (ignoring padding):",
     ["The size of its largest member", "The sum of the sizes of its members", "The size of its first member", "Always 8 bytes"], 0, "All members share the same storage."),
    ("A Pascal-style  set of 0..31  is most efficiently implemented as:",
     ["A 32-bit string with one bit per possible element", "A linked list of integers", "An array of 32 integers", "A hash table"], 0, "Union and intersection then become bitwise OR and AND."),
    ("Match the type with its usual storage representation:\na. Boolean  b. Character  c. Floating-point  d. Set (small base type)\n1. Sign, exponent and mantissa  2. Bit string  3. A code such as ASCII or Unicode  4. A single bit or byte",
     ["a-4, b-3, c-1, d-2", "a-3, b-4, c-1, d-2", "a-4, b-3, c-2, d-1", "a-2, b-3, c-1, d-4"], 0, "Standard representations described in Pratt, chapter on elementary data types."),
    ("Assertion (A): Subrange types can improve program reliability.\nReason (R): The translator or run-time system can check that assigned values stay within the declared range.",
     AR, 0, "Range checks catch errors that would otherwise produce wrong values silently."),
    ("Assertion (A): Floating-point numbers can represent every real number within their range exactly.\nReason (R): They use a fixed, finite number of bits for the mantissa.",
     AR, 3, "With finitely many bits only finitely many values are representable; R explains why A is false."),
    ("Assertion (A): In C, an array name used in an expression usually converts to a pointer to its first element.\nReason (R): C arrays store their length as part of the array object.",
     AR, 2, "A is true (array-to-pointer decay). R is false: C arrays carry no length, which is why functions need a size argument."),
    ("Assertion (A): Enumeration types make programs more readable.\nReason (R): Enumeration values are usually stored internally as small integers.",
     AR, 1, "Both true, but readability comes from meaningful names, not from the internal integer representation."),
    ("Consider the statements about a C union:\nI. It can hold valid values of all its members at the same time.\nII. Storing into one member can change the value read through another member.\nWhich is/are correct?",
     I_II, 1, "Members overlap in memory, so only the last stored member is meaningful."),
    ("To keep a student's name, roll number and marks together as one data object, the most suitable type is a:",
     ["Record (structure)", "Array of integers", "Enumeration", "Subrange"], 0, "Fields of different types are grouped in a record."),
    ("Consider the statements:\nI. A pointer data object holds the location (address) of another data object.\nII. In C, dereferencing a NULL pointer is always detected at compile time.\nWhich is/are correct?",
     I_II, 0, "II is false: a NULL dereference is a run-time error (undefined behaviour) that the compiler usually cannot detect."),
    ("Which operation is NOT normally defined on an enumeration type such as {MON, TUE, WED}?",
     ["Multiplication of two values", "Comparison (MON < TUE)", "Successor and predecessor", "Assignment"], 0, "Enumerations are ordered, so comparison and succ/pred make sense; arithmetic like MON × TUE does not."),
]

TOPICS = {
    "Language Design and Translation Issues": [("1 · Language Concepts, Paradigms, Models and Programming Environments", CONCEPTS),
                                               ("2 · Syntax and Stages in Translation", SYNTAX),
                                               ("3 · Formal Transition Models", AUTOMATA)],
    "Elementary Data Types": [("1 · Properties of Types and Objects", TYPES_OBJECTS),
                              ("2 · Scalar and Composite Data Types", SCALAR_COMPOSITE)],
}
