"""Paper 2 · Unit 4 · Programming in C++ – Part 2; Web Programming – HTML, DHTML, CSS (7 sub-topics × 30).
References: Balagurusamy, Object-Oriented Programming with C++; Stroustrup; Schildt, Java: The Complete Reference (event handling);
W3C HTML and CSS specifications; Thomas Powell, HTML & CSS: The Complete Reference.
C++ code assumes a standard (C++17) compiler with `using namespace std;` and the needed headers."""
from packlib import AR, I_II

OVERLOAD_VIRTUAL = [
    ("Two overloaded C++ functions must differ in:",
     ["The number, types or order of their parameters", "Their return types only", "Their names", "The names of their parameters only"], 0, "The return type alone is not part of what distinguishes overloads."),
    ("Which pair of declarations is INVALID as an overload in C++?",
     ["int f(int); and double f(int);", "int f(int); and int f(double);", "int f(int); and int f(int, int);", "void f(char); and void f(int);"], 0, "They differ only in return type."),
    ("Given  void f(float);  and  void f(double); , the call  f(5);  is:",
     ["Ambiguous – a compile error, since int converts equally well to float and to double", "A call to f(float)", "A call to f(double)", "A run-time error"], 0, "Both need a floating-integral conversion of the same rank."),
    ("Given  void f(char);  and  void f(int); , the call  f('a');  calls:",
     ["f(char) – an exact match", "f(int)", "Both", "Neither – ambiguous"], 0, "An exact match beats a promotion."),
    ("A binary operator overloaded as a MEMBER function of a class takes how many explicit parameters?",
     ["One – the left operand is the object itself (this)", "Two", "None", "Three"], 0, "As a non-member (e.g. friend) it takes two."),
    ("The postfix increment operator (x++) is overloaded as a member function with the signature:",
     ["T operator++(int)", "T& operator++()", "T operator++(T)", "void operator++(double)"], 0, "The dummy int parameter distinguishes postfix from prefix."),
    ("operator<< for printing an object with cout is normally written as a non-member (often friend) function because:",
     ["Its left operand is an ostream, not an object of the class", "Member functions cannot return references", "cout is a constant", "<< cannot be overloaded as a member of any class"], 0, "A member operator's left operand must be an object of that class."),
    ("Which of these operators CAN be overloaded in C++?",
     ["() (function call)", "sizeof", ". (member access)", "?: (conditional)"], 0, "Overloading () creates function objects (functors)."),
    ("Operator overloading in C++ can NOT change an operator's:",
     ["Precedence, associativity and number of operands", "Meaning for user-defined types", "Return type", "Parameter types"], 0, "It gives new meaning for class types but keeps the grammar."),
    ("An overloaded assignment operator usually returns *this by reference so that:",
     ["Assignments can be chained, as in a = b = c", "It runs faster than the default", "It becomes virtual", "It can be called without an object"], 0, "The standard signature is T& operator=(const T&)."),
    ("Which operator must be overloaded as a member function (not as a non-member)?",
     ["= (assignment)", "+", "<<", "=="], 0, "=, [], () and -> must be members."),
    ("Complex has an operator+ that adds the real and imaginary parts separately. With c1(1, 2) and c2(3, 4), c1 + c2 is:",
     ["(4, 6)", "(3, 8)", "(4, 2)", "(10, 0)"], 0, "Real parts 1 + 3, imaginary parts 2 + 4."),
    ("The C++11 specifier override on a member function:",
     ["Asks the compiler to check that the function really overrides a base-class virtual function", "Makes the function static", "Prevents the function from being overridden", "Makes the function pure virtual"], 0, "final is the specifier that prevents further overriding."),
    ("What does this print?\nclass B { public: B() { f(); } virtual void f() { cout << \"B\"; } };\nclass D : public B { public: void f() override { cout << \"D\"; } };\nint main() { D d; }",
     ["B", "D", "BD", "Nothing"], 0, "During B's constructor the object is still a B, so the virtual call resolves to B::f."),
    ("What does this print?\nclass B { public: virtual void f() { cout << \"B\"; } };\nclass D : public B { public: void f() override { cout << \"D\"; } };\nvoid show(B b) { b.f(); }\nint main() { D d; show(d); }",
     ["B", "D", "BD", "Compile error"], 0, "Passing by value copies only the B part (object slicing), so B::f runs."),
    ("With the same classes B and D as above, what does  void show(B &b) { b.f(); }  print for  show(d); ?",
     ["D", "B", "BD", "Compile error"], 0, "A reference keeps the dynamic type, so the virtual call goes to D::f."),
    ("What does this print?\nclass B { public: void f(int) { cout << \"Bi\"; } };\nclass D : public B { public: void f(double) { cout << \"Dd\"; } };\nint main() { D d; d.f(1); }",
     ["Dd", "Bi", "Ambiguous – compile error", "BiDd"], 0, "D::f hides every B::f (name hiding), so 1 is converted to double. 'using B::f;' would bring B::f back."),
    ("What does this print?\nclass B { public: virtual ~B() { cout << \"~B\"; } };\nclass D : public B { public: ~D() { cout << \"~D\"; } };\nint main() { B *p = new D; delete p; }",
     ["~D~B", "~B", "~B~D", "~D"], 0, "With a virtual destructor the derived destructor runs first, then the base destructor."),
    ("Operator overloading can create a new operator symbol such as ** for power:",
     ["False – only existing C++ operators can be overloaded", "True, for any class", "True, but only inside templates", "True, only as friend functions"], 0, "A named function such as pow() is used instead."),
    ("Match the overloaded operator with a typical use:\na. operator[]  b. operator()  c. operator<<  d. operator==\n1. Comparing two objects  2. Printing to a stream  3. Making an object callable like a function  4. Indexing a container",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These make user-defined types behave like built-in ones."),
    ("Consider the statements:\nI. Overload resolution happens at compile time.\nII. Dispatch of a virtual function call through a base pointer happens at compile time.\nWhich is/are correct?",
     I_II, 0, "Virtual dispatch happens at run time using the vtable."),
    ("Consider the statements:\nI. The postfix increment operator is overloaded as operator++(int).\nII. The int parameter of postfix operator++ carries the amount to increment by.\nWhich is/are correct?",
     I_II, 0, "The int is a dummy used only to tell postfix from prefix."),
    ("Consider the statements:\nI. A binary operator overloaded as a member function takes one explicit parameter.\nII. The same operator overloaded as a non-member function takes two parameters.\nWhich is/are correct?",
     I_II, 2, "The member version receives the left operand through this."),
    ("Assertion (A): The return type alone cannot distinguish overloaded functions.\nReason (R): In a call such as f(2), the compiler has no way to know which return type is wanted.",
     AR, 0, "Overload resolution looks only at the arguments."),
    ("Assertion (A): Operator overloading can change an operator's precedence.\nReason (R): Precedence and associativity are fixed by the language grammar.",
     AR, 3, "Because they are fixed, overloading cannot change them; R shows why A is false."),
    ("Assertion (A): operator<< for printing a class is usually a non-member function.\nReason (R): A member operator's left operand can be of any type.",
     AR, 2, "A is true; R is false – for a member operator the left operand must be an object of that class."),
    ("Assertion (A): A function declared virtual in a base class remains virtual in derived classes.\nReason (R): C++11 introduced the override specifier.",
     AR, 1, "Both true; virtualness is inherited whether or not override is written."),
    ("A function object (functor) in C++ is:",
     ["An object of a class that overloads operator()", "A pointer to a member variable", "A template parameter", "A virtual base class"], 0, "Functors are often passed to STL algorithms."),
    ("Function overloading and virtual functions are examples of, respectively:",
     ["Compile-time and run-time polymorphism", "Run-time and compile-time polymorphism", "Encapsulation and inheritance", "Both compile-time polymorphism"], 0, "Overloading is resolved statically; virtual calls dynamically."),
    ("A virtual function called through an object (not a pointer or reference), as in  d.f(); , is bound:",
     ["At compile time, using the object's static type", "At run time through the vtable only", "Never", "At link time"], 0, "Dynamic binding matters only when the static and dynamic types can differ, i.e. through pointers or references."),
]

CPP_INHERITANCE = [
    ("With  class D : B { };  (no access specifier), B is inherited as:",
     ["private", "public", "protected", "virtual"], 0, "For a struct the default is public."),
    ("A derived class passes an argument to its base-class constructor using:",
     ["The member initialiser list: D(int x) : B(x) { }", "A call B(x); in the constructor body", "The this pointer", "A friend function"], 0, "Base subobjects are constructed before the derived constructor body runs."),
    ("What does this print?\nclass A { public: A() { cout << \"A\"; } };\nclass B { public: B() { cout << \"B\"; } };\nclass C : public B, public A { public: C() { cout << \"C\"; } };\nint main() { C c; }",
     ["BAC", "ABC", "CBA", "CAB"], 0, "Base classes are constructed in the order they are listed in the derivation list, then the derived class."),
    ("In the diamond  B : A,  C : A,  D : B, C  WITHOUT virtual inheritance, a D object contains how many A subobjects?",
     ["2", "1", "3", "0"], 0, "One through B and one through C – hence the ambiguity."),
    ("In the same diamond with  B : virtual public A  and  C : virtual public A , a D object contains how many A subobjects?",
     ["1", "2", "3", "0"], 0, "Virtual inheritance shares one A subobject."),
    ("In a hierarchy with a virtual base class, the virtual base is constructed:",
     ["First, by the most-derived class, before any non-virtual bases", "Last", "Twice", "Only if explicitly called in main"], 0, "The most-derived class is responsible for initialising virtual bases."),
    ("Diamond-shaped inheritance, where a class inherits the same base through two paths, is also called:",
     ["Multipath inheritance", "Single inheritance", "Hierarchical inheritance", "Private inheritance"], 0, "It is a special case of hybrid inheritance."),
    ("A protected member of base class B can be accessed:",
     ["Inside member functions of B and of classes derived from B, but not through an object in main()", "From anywhere through an object", "Only inside B", "Only by friend functions of derived classes"], 0, "protected is hidden from outside users of the class."),
    ("With  class D : protected B , the public members of B become in D:",
     ["protected", "public", "private", "inaccessible"], 0, "Public and protected members of B both become protected in D."),
    ("What does this print?\nclass B { public: void f() { cout << \"B\"; } };\nclass D : public B { public: void f() { B::f(); cout << \"D\"; } };\nint main() { D d; d.f(); }",
     ["BD", "D", "B", "DB"], 0, "B::f() explicitly calls the base version from inside the derived function."),
    ("What does this print?\nclass A { public: int x = 1; };\nclass B : public A { public: int x = 2; };\nint main() { B b; cout << b.x << b.A::x; }",
     ["21", "12", "22", "11"], 0, "B::x hides A::x; b.A::x reaches the hidden member."),
    ("Which of the following is NOT inherited by a derived class?",
     ["Friend functions of the base class", "Public member functions", "Protected data members", "Public data members"], 0, "Friendship is not inherited; constructors are also not inherited unless 'using Base::Base;' is written."),
    ("In C++11,  using B::B;  inside class D means:",
     ["D inherits B's constructors", "D becomes an alias of B", "D cannot be instantiated", "B's destructor is removed"], 0, "These are called inheriting constructors."),
    ("B has one int data member and D (publicly derived from B, no virtual functions) adds one int. On a typical system, sizeof(D) is:",
     ["8", "4", "12", "16"], 0, "A D object contains the B subobject plus its own member."),
    ("With  class D : private B , the conversion  B *p = &d;  written in main() is:",
     ["Not allowed – the base is inaccessible outside D", "Always allowed", "Allowed only for virtual functions", "Allowed with a warning only"], 0, "Only public inheritance models 'is-a' for users of the class."),
    ("To model 'a Circle is a Shape' for all users of the classes, Circle should inherit from Shape using:",
     ["public inheritance", "private inheritance", "protected inheritance", "friend inheritance"], 0, "Private and protected inheritance model 'implemented-in-terms-of'."),
    ("Containership (composition) in C++ means:",
     ["A class has an object of another class as a data member", "A class is derived from another", "A class has only static members", "A class contains only virtual functions"], 0, "It models has-a; objects are built from other objects."),
    ("Match the inheritance mode with what a public member of the base becomes in the derived class:\na. public inheritance  b. protected inheritance  c. private inheritance\n1. private  2. protected  3. public",
     ["a-3, b-2, c-1", "a-1, b-2, c-3", "a-3, b-1, c-2", "a-2, b-3, c-1"], 0, "Private members of the base are never accessible in the derived class."),
    ("What does this print?\nclass A { public: A(int x) { cout << x; } };\nclass B : public A { public: B() : A(5) { cout << \"B\"; } };\nint main() { B b; }",
     ["5B", "B5", "B", "Compile error"], 0, "A(5) runs first, then B's constructor body."),
    ("In a D object built from the non-virtual diamond (B : A, C : A, D : B, C), the expression  d.x  where x is a member of A is:",
     ["Ambiguous – it must be written d.B::x or d.C::x", "Always A's single x", "A run-time error", "The x of D"], 0, "There are two copies of x, one through each path."),
    ("Consider the statements:\nI. In public inheritance, protected members of the base remain protected in the derived class.\nII. In public inheritance, private members of the base become protected in the derived class.\nWhich is/are correct?",
     I_II, 0, "Private members of the base stay inaccessible."),
    ("Consider the statements:\nI. A derived-class object can be assigned to a base-class object (the extra part is sliced off).\nII. A base-class object can be assigned to a derived-class object without any conversion.\nWhich is/are correct?",
     I_II, 0, "The base object has no values for the derived-class members."),
    ("Consider the statements:\nI. Constructors execute from the base class to the most-derived class.\nII. Destructors execute from the most-derived class to the base class.\nWhich is/are correct?",
     I_II, 2, "Destruction is the exact reverse of construction."),
    ("Assertion (A): In a diamond hierarchy without virtual inheritance, the most-derived object contains two copies of the top base class.\nReason (R): Each intermediate class contains its own base-class subobject.",
     AR, 0, "Both intermediate classes bring their own copy of the base."),
    ("Assertion (A): Base-class constructors run after the body of the derived-class constructor.\nReason (R): Base-class subobjects are constructed before the derived-class constructor body runs.",
     AR, 3, "R describes the real order, which shows why A is false."),
    ("Assertion (A): A derived class can call the base version of an overridden function as B::f().\nReason (R): The scope resolution operator cannot be used with member functions.",
     AR, 2, "A is true; R is false – B::f() is exactly such a use."),
    ("Assertion (A):  struct D : B { };  inherits B publicly by default.\nReason (R): C++ supports multiple inheritance.",
     AR, 1, "Both true, but the default access of struct is unrelated to multiple inheritance."),
    ("A derived class can add new members and also:",
     ["Redefine (override or hide) inherited member functions", "Remove inherited data members", "Make inherited private members public", "Change the base class's source code"], 0, "Inherited data cannot be removed, only hidden."),
    ("Which statement about a pure virtual function declared in a base class is TRUE?",
     ["Every concrete class derived from it must provide an overriding definition", "It can never be overridden", "It makes all derived classes abstract forever", "It must be static"], 0, "Until it is overridden, derived classes remain abstract."),
    ("In C++, if the base class has no default constructor, the derived class constructor must:",
     ["Call a base-class constructor explicitly in its initialiser list", "Declare the base class virtual", "Be a friend of the base", "Have no parameters"], 0, "Otherwise the compiler cannot construct the base subobject."),
]

TEMPLATES_EXCEPTIONS = [
    ("Templates in C++ support:",
     ["Generic programming – writing code once for many types", "Only run-time polymorphism", "Only exception handling", "Only file handling"], 0, "They are a form of parametric (compile-time) polymorphism."),
    ("The correct declaration of a function template is:",
     ["template <typename T> T maxOf(T a, T b);", "template T maxOf(T a, T b);", "T template maxOf(T a, T b);", "generic <T> maxOf(T a, T b);"], 0, "class and typename are interchangeable in the parameter list."),
    ("Template code for a particular type is generated (instantiated):",
     ["At compile time, when the template is used with that type", "At run time", "At link time only", "When the program is loaded"], 0, "Each used type gets its own generated code."),
    ("Given  template <class T> T maxOf(T a, T b); , the call  maxOf(3, 4.5)  is:",
     ["A compile error – T cannot be deduced as both int and double", "Deduced as maxOf<int>", "Deduced as maxOf<double>", "A run-time error"], 0, "Writing maxOf<double>(3, 4.5) fixes it."),
    ("What does this print?\ntemplate <class T> T add(T a, T b) { return a + b; }\nint main() { cout << add(2, 3) << \" \" << add(1.5, 2.0); }",
     ["5 3.5", "5 3", "5.0 3.5", "Compile error"], 0, "add<int> and add<double> are both instantiated."),
    ("What does this print?\ntemplate <int N> int twice() { return N * 2; }\nint main() { cout << twice<5>(); }",
     ["10", "5", "25", "Compile error"], 0, "N is a non-type template parameter known at compile time."),
    ("To create a stack of integers from  template <class T> class Stack { … }; , one writes:",
     ["Stack<int> s;", "Stack s<int>;", "Stack(int) s;", "template Stack<int>;"], 0, "Class template arguments are written in angle brackets."),
    ("Providing a separate definition of a template for one particular type, e.g. template <> class Stack<bool>, is called:",
     ["Explicit (full) specialisation", "Overloading", "Instantiation by the user", "Inheritance"], 0, "It lets a type get an optimised or different implementation."),
    ("The three main components of the C++ Standard Template Library (STL) are:",
     ["Containers, algorithms and iterators", "Classes, objects and methods", "Streams, files and buffers", "Macros, headers and libraries"], 0, "Iterators connect algorithms to containers."),
    ("The three C++ keywords used for exception handling are:",
     ["try, catch and throw", "try, except and raise", "begin, rescue and end", "error, handle and signal"], 0, "Code that may fail goes in try; handlers are catch blocks."),
    ("What does this print?\ntry { throw 5; } catch (int e) { cout << e * 2; }",
     ["10", "5", "Nothing", "Program terminates"], 0, "The int handler catches the thrown value 5."),
    ("What does this print?\ntry { throw 'a'; } catch (int) { cout << \"int\"; } catch (char) { cout << \"char\"; }",
     ["char", "int", "intchar", "Program terminates"], 0, "Exception matching does not apply the char-to-int promotion; the char handler matches exactly."),
    ("A handler written as  catch (...)  :",
     ["Catches an exception of any type and should be the last handler", "Catches only integer exceptions", "Must be the first handler", "Rethrows every exception"], 0, "Handlers are tried in order, so a catch-all placed first would hide the others."),
    ("If an exception is thrown and no matching handler is found anywhere, the program:",
     ["Calls std::terminate(), which normally aborts the program", "Continues after the throw statement", "Ignores the exception", "Restarts main()"], 0, "Uncaught exceptions end the program."),
    ("'Stack unwinding' during exception handling means that:",
     ["Destructors of automatic objects are called as control leaves each scope between the throw and the handler", "The stack is printed on the screen", "All heap memory is freed automatically", "The program restarts"], 0, "This is why RAII objects release resources even when exceptions occur."),
    ("Inside a catch block, the statement  throw;  (with no operand):",
     ["Rethrows the current exception to an outer handler", "Throws a null exception", "Is a syntax error", "Ends the program"], 0, "It lets an inner handler do partial work and pass the exception on."),
    ("The standard base class of C++ library exceptions, which provides the member function what(), is:",
     ["std::exception", "std::error", "std::throwable", "std::fault"], 0, "E.g. std::out_of_range and std::bad_alloc derive from it."),
    ("Handlers are written  catch (Base &)  followed by  catch (Derived &) . A Derived object is thrown. Which handler runs?",
     ["catch (Base &), because it matches first", "catch (Derived &)", "Both", "Neither"], 0, "Handlers for derived classes must come before handlers for their bases."),
    ("Declaring a function noexcept means:",
     ["The function promises not to throw exceptions; if one escapes, std::terminate is called", "The function cannot contain try blocks", "The function returns no value", "The function is inline"], 0, "It also enables some optimisations, e.g. in move operations."),
    ("Match the construct with its role:\na. try  b. throw  c. catch  d. catch (...)\n1. Handler for any exception  2. Handler for a specific type  3. Raises an exception  4. Encloses code that may raise an exception",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Together they separate error handling from normal code."),
    ("A key advantage of exceptions over returning error codes is that:",
     ["Error-handling code is separated from normal code and errors cannot be silently ignored", "They make programs smaller in all cases", "They remove the need for testing", "They run faster than any if statement"], 0, "An unhandled exception cannot pass unnoticed."),
    ("Consider the statements:\nI. catch (...) can catch an exception of any type.\nII. catch (...) should be placed first among the handlers.\nWhich is/are correct?",
     I_II, 0, "It must be last, otherwise the more specific handlers would never be reached."),
    ("Consider the statements:\nI. The type argument of a function template can often be deduced from the call's arguments.\nII. Before C++17, the type argument of a class template had to be written explicitly.\nWhich is/are correct?",
     I_II, 2, "C++17 added class template argument deduction."),
    ("Consider the statements:\nI. Templates can reduce code duplication.\nII. Every template instantiation shares a single copy of machine code for all types.\nWhich is/are correct?",
     I_II, 0, "Each type used generates its own code, which can increase program size ('code bloat')."),
    ("Assertion (A): Destructors of local objects run when an exception leaves their scope.\nReason (R): Stack unwinding destroys the automatic objects between the throw point and the handler.",
     AR, 0, "Unwinding is the mechanism that calls those destructors."),
    ("Assertion (A): An exception of type int can be caught by catch (double).\nReason (R): Exception matching does not apply ordinary arithmetic conversions.",
     AR, 3, "Because no int-to-double conversion is applied, catch (double) will not catch it; R shows why A is false."),
    ("Assertion (A): Templates let one function definition work with many types.\nReason (R): Templates are instantiated at run time.",
     AR, 2, "A is true; R is false – instantiation happens at compile time."),
    ("Assertion (A): The STL provides generic containers such as vector and map.\nReason (R): C++ supports exception handling.",
     AR, 1, "Both true but unrelated."),
    ("Which STL container stores key–value pairs sorted by key?",
     ["map", "vector", "list", "stack"], 0, "unordered_map stores them in a hash table instead."),
    ("What does this print?\nint divide(int a, int b) { if (b == 0) throw \"div0\"; return a / b; }\nint main() { try { cout << divide(8, 2); cout << divide(1, 0); } catch (const char *m) { cout << m; } }",
     ["4div0", "div0", "4", "40"], 0, "The first call prints 4; the second throws before printing, and the handler prints the message."),
]

STREAMS_EVENTS = [
    ("In C++, cin and cout are objects of the classes:",
     ["istream and ostream", "ifstream and ofstream", "string and char", "FILE and stdout"], 0, "They are declared in <iostream>."),
    ("The header needed for file stream classes such as ifstream and ofstream is:",
     ["<fstream>", "<iostream> only", "<cstdio>", "<file>"], 0, "fstream supports both reading and writing."),
    ("Which stream is unbuffered and meant for error messages?",
     ["cerr", "clog", "cout", "cin"], 0, "clog is also for diagnostics but is buffered."),
    ("To open a file so that new data is written at its end, the open mode is:",
     ["ios::app", "ios::in", "ios::trunc", "ios::nocreate"], 0, "ios::ate also starts at the end, but allows later seeking."),
    ("Which mode is used to read or write raw bytes, such as whole structures, without newline translation?",
     ["ios::binary", "ios::text", "ios::raw", "ios::app"], 0, "Used with read() and write()."),
    ("Given  string s;  and the input  Hello World , the statement  cin >> s;  stores in s:",
     ["\"Hello\"", "\"Hello World\"", "\"World\"", "An empty string"], 0, ">> stops at white space; getline(cin, s) reads the whole line."),
    ("What does  cout << fixed << setprecision(2) << 3.14159;  print?",
     ["3.14", "3.1", "3.14159", "3.141"], 0, "fixed with setprecision(2) prints 2 digits after the decimal point; <iomanip> is needed."),
    ("What does  cout << setw(5) << 42;  print (· shows a space)?",
     ["···42", "42···", "42", "00042"], 0, "setw sets the field width; numbers are right-justified by default."),
    ("To write a structure variable rec to a binary file stream out, one writes:",
     ["out.write((char *)&rec, sizeof(rec));", "out << rec; (always, for any struct)", "out.put(rec);", "write(out, rec);"], 0, "read() works the same way for input."),
    ("The functions seekg() and tellg() work with the:",
     ["Get (read) position of an input stream", "Put (write) position of an output stream", "Console only", "Standard error stream"], 0, "seekp() and tellp() work with the put position."),
    ("A common way to read integers from ifstream fin until the end of the file is:",
     ["while (fin >> x) { … }", "while (!fin.eof()) fin >> x;  (always correct)", "for (;;) fin >> x;", "fin.readAll(x);"], 0, "The extraction returns the stream, which becomes false when a read fails, e.g. at end of file."),
    ("What does this print?\nofstream f(\"a.txt\"); f << 10 << \" \" << 20; f.close();\nifstream g(\"a.txt\"); int x, y; g >> x >> y; cout << x + y;",
     ["30", "1020", "10", "20"], 0, "The two numbers written are read back and added."),
    ("A file contains the text  to be or not . How many times does  while (fin >> w) count++;  add 1 (w is a string)?",
     ["4", "3", "12", "1"], 0, "Each extraction reads one white-space-separated word."),
    ("Which stream-state function reports whether a stream is still usable (no error flags set)?",
     ["good()", "bad() only", "open()", "flush()"], 0, "eof(), fail() and bad() test specific error conditions."),
    ("A file stream object that goes out of scope:",
     ["Closes its file automatically in its destructor", "Leaves the file open until the computer restarts", "Deletes the file", "Must be closed with fclose()"], 0, "Calling close() explicitly is still useful to reuse the object or check errors."),
    ("The << operator used with cout returns ostream& so that:",
     ["Several outputs can be chained in one statement", "It can print only numbers", "It can open files", "It flushes after every item"], 0, "cout << a << b is (cout << a) << b."),
    ("In event-driven programming, the flow of the program is determined mainly by:",
     ["Events such as mouse clicks, key presses and messages, handled by event handlers", "The order of lines in main() only", "Compile-time templates", "The file system"], 0, "An event loop waits for events and dispatches them to handlers."),
    ("In Java's event delegation model, a class that wants to respond to button clicks implements the interface:",
     ["ActionListener, with the method actionPerformed(ActionEvent e)", "Runnable, with run()", "Serializable", "Comparable, with compareTo()"], 0, "It is registered with button.addActionListener(listener)."),
    ("In the event delegation model, the three participants are:",
     ["Event source, event object and event listener (handler)", "Compiler, linker and loader", "Client, server and database", "try, catch and throw"], 0, "The source generates the event object and notifies registered listeners."),
    ("A function passed to another function to be called later when something happens is called a:",
     ["Callback", "Destructor", "Template", "Macro"], 0, "In C++ callbacks are passed as function pointers, function objects or lambdas."),
    ("Match the class with its use:\na. ifstream  b. ofstream  c. fstream  d. stringstream\n1. Reading and writing strings in memory as a stream  2. Both reading and writing a file  3. Writing to a file  4. Reading from a file",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "stringstream is declared in <sstream>."),
    ("Consider the statements:\nI. seekg() moves the get (read) position of an input stream.\nII. tellp() returns the current put (write) position of an output stream.\nWhich is/are correct?",
     I_II, 2, "g stands for get and p for put."),
    ("Consider the statements:\nI. cerr is buffered.\nII. clog is buffered.\nWhich is/are correct?",
     I_II, 1, "cerr is unbuffered so that error messages appear immediately."),
    ("Consider the statements:\nI. getline(cin, s) can read a line that contains spaces.\nII. cin >> n followed directly by getline(cin, s) may read an empty line, because the newline is left in the buffer.\nWhich is/are correct?",
     I_II, 2, "cin.ignore() is used to discard the leftover newline."),
    ("Assertion (A): Opening an existing file with ofstream in its default mode erases its old contents.\nReason (R): The default mode of ofstream is ios::out, which truncates the file.",
     AR, 0, "Use ios::app to keep old contents and append."),
    ("Assertion (A):  cin >> s  reads a whole line, including spaces, into a string.\nReason (R): The >> operator stops reading a string at white space.",
     AR, 3, "R is the rule, and it shows why A is false."),
    ("Assertion (A): C++ file streams are closed automatically when the stream object goes out of scope.\nReason (R): C++ file streams must always be closed with fclose().",
     AR, 2, "A is true; R is false – fclose() is for C FILE* streams."),
    ("Assertion (A): In event-driven programs the order of execution depends on user actions.\nReason (R): Java provides the ActionListener interface.",
     AR, 1, "Both true; ActionListener is one tool for handling events, not the reason for event-driven order."),
    ("Text mode and binary mode files differ in that:",
     ["Text mode may translate newline characters; binary mode transfers bytes exactly", "Binary mode files cannot be read", "Text mode stores data in hexadecimal", "There is no difference on any system"], 0, "On Windows, text mode converts '\\n' to CR-LF."),
    ("The manipulator used to discard the rest of an input line, for example after cin >> n, is:",
     ["cin.ignore()", "cin.flush()", "cin.clear() only", "cin.close()"], 0, "clear() resets error flags; ignore() skips characters."),
]

HTML_BASICS = [
    ("HTML stands for:",
     ["HyperText Markup Language", "High-Level Text Machine Language", "Hyperlink and Text Management Language", "Home Tool Markup Language"], 0, "It was created by Tim Berners-Lee at CERN."),
    ("Which is the correct basic structure of an HTML5 document?",
     ["<!DOCTYPE html> <html> <head> … </head> <body> … </body> </html>", "<html> <body> <head> … </head> </body> </html>", "<head> <html> <body> … </body> </html> </head>", "<body> <html> … </html> </body>"], 0, "The head holds information about the page; the body holds its visible content."),
    ("The text of the <title> element appears:",
     ["In the browser's title bar or tab", "As the largest heading on the page", "At the bottom of the page", "Only in the page source, nowhere else"], 0, "<title> must be inside <head>."),
    ("Which heading tag produces the largest (most important) heading?",
     ["<h1>", "<h6>", "<head>", "<heading>"], 0, "There are six levels, <h1> to <h6>."),
    ("Which of the following is an empty (void) element with no closing tag?",
     ["<br>", "<p>", "<ul>", "<table>"], 0, "<hr>, <img>, <input> and <meta> are also void elements."),
    ("<strong> and <em> differ from <b> and <i> in that they:",
     ["Carry meaning (strong importance and emphasis), which screen readers can convey", "Cannot be styled", "Work only in tables", "Are not supported by HTML5"], 0, "<b> and <i> are presentational."),
    ("The correct way to create a hyperlink to https://example.com that opens in a new tab is:",
     ["<a href=\"https://example.com\" target=\"_blank\">Visit</a>", "<link url=\"https://example.com\" new>Visit</link>", "<a src=\"https://example.com\">Visit</a>", "<href a=\"https://example.com\">Visit</href>"], 0, "href gives the destination; target=\"_blank\" opens a new browsing context."),
    ("To link to a section with id=\"contact\" on the same page, the href value is:",
     ["#contact", "contact.html", "@contact", "?contact"], 0, "A fragment identifier jumps to the element with that id."),
    ("A link written as  <a href=\"mailto:office@school.in\">  :",
     ["Opens the user's e-mail program with that address filled in", "Downloads a file", "Opens a new web page called mailto", "Sends an e-mail automatically"], 0, "mailto: is a URL scheme for e-mail addresses."),
    ("The alt attribute of an <img> element:",
     ["Gives alternative text shown if the image cannot load and read by screen readers", "Sets the image's alignment", "Sets the image's altitude on the page", "Gives the image file path"], 0, "src gives the image's location."),
    ("Which tags create an unordered (bulleted) list with one item?",
     ["<ul><li>Item</li></ul>", "<ol><li>Item</li></ol>", "<list><item>Item</item></list>", "<ul><item>Item</item></ul>"], 0, "<ol> creates an ordered (numbered) list."),
    ("An ordered list written as  <ol type=\"A\" start=\"3\">  labels its first item:",
     ["C", "3", "A", "iii"], 0, "type=\"A\" uses capital letters, and start=\"3\" begins at the third one."),
    ("A description list uses the tags:",
     ["<dl>, <dt> and <dd>", "<ul>, <li> and <dd>", "<dl>, <li> and <dt>", "<desc>, <term> and <def>"], 0, "<dt> is the term and <dd> its description."),
    ("A comment in HTML is written as:",
     ["<!-- comment -->", "// comment", "/* comment */", "# comment"], 0, "Browsers do not display comments."),
    ("To display the character < as text in HTML, one writes the entity:",
     ["&lt;", "&gt;", "&amp;", "&nbsp;"], 0, "&gt; is >, &amp; is & and &nbsp; is a non-breaking space."),
    ("<div> and <span> differ in that:",
     ["<div> is a block-level element, while <span> is an inline element", "<span> always starts on a new line", "<div> cannot contain text", "They are identical"], 0, "Both are generic containers used mainly with CSS."),
    ("The <pre> element:",
     ["Displays text with its spaces and line breaks preserved, usually in a monospace font", "Previews a web page", "Makes text bold", "Creates a paragraph"], 0, "Useful for code and poems."),
    ("Which HTML5 elements are semantic elements that describe parts of a page?",
     ["<header>, <nav>, <article> and <footer>", "<b>, <i> and <u>", "<div> and <span>", "<font> and <center>"], 0, "They help search engines and assistive technology understand the page."),
    ("The HTML5 elements used to embed sound and video without plug-ins are:",
     ["<audio> and <video>", "<sound> and <movie>", "<media> and <film>", "<embed> only"], 0, "The controls attribute shows play/pause buttons."),
    ("The tag  <meta charset=\"UTF-8\">  is placed in:",
     ["<head>, to declare the page's character encoding", "<body>, to show a heading", "<footer> only", "Any table cell"], 0, "UTF-8 supports Kannada and other scripts."),
    ("A link written as  href=\"notes/unit4.html\"  is an example of a:",
     ["Relative URL", "Absolute URL", "mailto link", "Fragment identifier"], 0, "It is resolved relative to the current page's location; an absolute URL starts with a scheme such as https://."),
    ("Match the tag with its use:\na. <hr>  b. <br>  c. <p>  d. <img>\n1. Embeds a picture  2. Paragraph  3. Line break  4. Horizontal (thematic) break line",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Only <p> of these has a closing tag."),
    ("An attribute in HTML is written:",
     ["Inside the start tag as name=\"value\"", "Inside the end tag", "Between the start and end tags as text", "Only in a separate file"], 0, "E.g. <img src=\"a.png\" alt=\"Logo\">."),
    ("Consider the statements:\nI. <strong> indicates strong importance.\nII. <em> indicates stress emphasis.\nWhich is/are correct?",
     I_II, 2, "Both are semantic phrase elements."),
    ("Consider the statements:\nI. <ul> produces a numbered list by default.\nII. <ol> produces a bulleted list by default.\nWhich is/are correct?",
     I_II, 3, "It is the other way round: <ul> is bulleted, <ol> is numbered."),
    ("Assertion (A): The alt attribute of <img> improves accessibility.\nReason (R): Screen readers read the alt text aloud to visually impaired users.",
     AR, 0, "That is the main purpose of alt text."),
    ("Assertion (A): HTML is a programming language with variables and loops.\nReason (R): HTML is a markup language that describes the structure of a document.",
     AR, 3, "Because it only marks up structure, it is not a programming language; R shows why A is false."),
    ("Assertion (A): <br> is an empty element.\nReason (R): Every HTML element must have a closing tag.",
     AR, 2, "A is true; R is false – void elements such as <br> and <img> have no closing tag."),
    ("Assertion (A): <h1> is used for the most important heading of a page.\nReason (R): HTML was developed by Tim Berners-Lee.",
     AR, 1, "Both true but unrelated."),
    ("How many list items are displayed by:\n<ul><li>A</li><li>B<ul><li>B1</li><li>B2</li></ul></li><li>C</li></ul>",
     ["5", "3", "4", "2"], 0, "A, B, C at the outer level plus B1 and B2 in the nested list."),
]

HTML_TABLES_FORMS = [
    ("In an HTML table, the tags <tr>, <td> and <th> stand for:",
     ["Table row, table data cell and table header cell", "Table rule, text data and table heading", "Top row, total data and table height", "Table reference, table division and table header"], 0, "<th> cells are bold and centred by default."),
    ("A cell written as  <td colspan=\"3\">  :",
     ["Spans three columns", "Spans three rows", "Has a border 3 pixels wide", "Is repeated three times"], 0, "rowspan merges cells vertically."),
    ("A table has 3 <tr> rows, and each row has 4 <td> cells with no colspan or rowspan. How many cells does it have?",
     ["12", "7", "4", "3"], 0, "3 × 4."),
    ("The first row of a 2-column table is  <td rowspan=\"2\">A</td><td>B</td> . How many <td> elements does the second row need?",
     ["1", "2", "0", "3"], 0, "Cell A already occupies the first column of row 2."),
    ("The <caption> element in a table:",
     ["Gives the table a title", "Adds a footer row", "Merges two cells", "Sets the border colour"], 0, "It must be the first child of <table>."),
    ("The table sections <thead>, <tbody> and <tfoot>:",
     ["Group the header rows, body rows and footer rows of a table", "Create three separate tables", "Are used only in forms", "Set column widths"], 0, "They help styling, printing and accessibility."),
    ("In HTML tables, cellpadding and cellspacing refer respectively to:",
     ["Space between a cell's border and its content; space between adjacent cells", "Space between cells; space inside a cell", "Row height; column width", "Border width; border colour"], 0, "In modern pages these are set with CSS (padding and border-spacing)."),
    ("The action attribute of a <form> element specifies:",
     ["The URL to which the form data is sent", "The colour of the form", "The number of input fields", "The encryption key"], 0, "method says how the data is sent (get or post)."),
    ("Compared with method=\"get\", method=\"post\" for a form:",
     ["Sends the data in the request body instead of the URL, so it is better for passwords and large data", "Appends the data to the URL", "Cannot send any data", "Works only with e-mail"], 0, "GET data is visible in the address bar, history and logs."),
    ("An <input type=\"password\"> field:",
     ["Hides the typed characters on the screen but does not encrypt them by itself", "Encrypts the data automatically", "Accepts only numbers", "Cannot be submitted"], 0, "Secure transmission needs HTTPS."),
    ("Radio buttons allow only one choice from a group when:",
     ["They share the same name attribute", "They have different ids", "They are inside a table", "They use type=\"checkbox\""], 0, "Checkboxes allow several independent choices."),
    ("The elements used to create a drop-down list are:",
     ["<select> with <option> elements", "<list> with <item> elements", "<input type=\"dropdown\">", "<ul> with <li> elements"], 0, "Adding the multiple attribute allows several selections."),
    ("A multi-line text input box is created with:",
     ["<textarea>", "<input type=\"text\">", "<text>", "<input type=\"lines\">"], 0, "Its rows and cols attributes set its visible size."),
    ("The <label for=\"email\"> element:",
     ["Associates a caption with the control whose id is \"email\", so clicking the label focuses it", "Creates an e-mail field", "Sends an e-mail", "Validates the e-mail address"], 0, "Labels improve usability and accessibility."),
    ("The HTML5 attribute that prevents a form from being submitted while a field is empty is:",
     ["required", "placeholder", "readonly", "autofocus"], 0, "placeholder only shows a hint inside the field."),
    ("A form that uploads files must use:",
     ["method=\"post\" and enctype=\"multipart/form-data\"", "method=\"get\" only", "enctype=\"text/plain\"", "No special attributes"], 0, "Along with <input type=\"file\">."),
    ("An <input type=\"hidden\"> field:",
     ["Sends a value with the form without showing it to the user", "Is a password field", "Hides the whole form", "Cannot hold a value"], 0, "Hidden is not secret: the value is visible in the page source."),
    ("The data sent to the server for each form control is identified by the control's:",
     ["name attribute", "id attribute only", "class attribute", "style attribute"], 0, "Controls without a name are not submitted."),
    ("The <fieldset> and <legend> elements are used to:",
     ["Group related form controls and give the group a caption", "Create tables", "Upload files", "Make hyperlinks"], 0, "Browsers draw a box around a fieldset."),
    ("Match the input type with the control it creates:\na. checkbox  b. radio  c. submit  d. reset\n1. Clears the form to its initial values  2. Sends the form data  3. One choice among a group  4. Independent on/off choice",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "HTML5 also added types such as email, number and date."),
    ("Which HTML5 input type shows a date picker in modern browsers?",
     ["date", "calendar", "time-picker", "day"], 0, "Other HTML5 types include email, number, range and color."),
    ("A checkbox that should appear ticked when the page loads is written with the attribute:",
     ["checked", "selected", "active", "on"], 0, "selected is used for <option> elements."),
    ("Consider the statements:\nI. colspan merges cells horizontally.\nII. rowspan merges cells vertically.\nWhich is/are correct?",
     I_II, 2, "Both statements are correct."),
    ("Consider the statements:\nI. A reset button sends the form data to the server.\nII. A submit button clears the form.\nWhich is/are correct?",
     I_II, 3, "It is the other way round."),
    ("Assertion (A): Passwords should be sent with method=\"post\" rather than method=\"get\".\nReason (R): With GET, form data appears in the URL.",
     AR, 0, "Data in the URL can be seen in the address bar, history and server logs."),
    ("Assertion (A): Radio buttons with different name attributes allow only one of them to be selected.\nReason (R): Only radio buttons that share the same name form a group with a single selection.",
     AR, 3, "With different names each button is its own group; R shows why A is false."),
    ("Assertion (A): <th> cells are displayed bold and centred by default.\nReason (R): <th> can be used only in the first column of a table.",
     AR, 2, "A is true; R is false – header cells can be used in any row or column."),
    ("Assertion (A): The <select> element creates a drop-down list.\nReason (R): The <textarea> element creates a multi-line text box.",
     AR, 1, "Both true but unrelated."),
    ("A marks table must show the heading \"Marks\" once above the two columns \"Theory\" and \"Practical\". The \"Marks\" header cell should use:",
     ["colspan=\"2\"", "rowspan=\"2\"", "cellspacing=\"2\"", "border=\"2\""], 0, "It spans the two columns below it."),
    ("The value attribute of <input type=\"text\">:",
     ["Sets the field's initial content", "Sets its width", "Makes it compulsory", "Hides the field"], 0, "For buttons it sets the text shown on the button."),
]

DHTML_CSS = [
    ("DHTML (Dynamic HTML) is:",
     ["A combination of HTML, CSS, JavaScript and the DOM used to make pages interactive without reloading", "A new markup language that replaced HTML", "A server-side database", "A browser made by Microsoft only"], 0, "It is a technique, not a separate language."),
    ("The Document Object Model (DOM) represents a web page as:",
     ["A tree of objects that scripts can read and change", "A single string of text", "An image", "A table of CSS rules only"], 0, "E.g. document.getElementById('x').innerHTML = 'Hi';"),
    ("CSS stands for:",
     ["Cascading Style Sheets", "Computer Style Sheets", "Creative Style System", "Colourful Style Sheets"], 0, "CSS separates presentation from content (HTML)."),
    ("Match the way of adding CSS with its form:\na. Inline  b. Internal  c. External\n1. <link rel=\"stylesheet\" href=\"site.css\">  2. <style> … </style> in the head  3. style=\"…\" attribute on an element",
     ["a-3, b-2, c-1", "a-2, b-3, c-1", "a-3, b-1, c-2", "a-1, b-2, c-3"], 0, "An external sheet can style a whole website."),
    ("Which CSS selector selects all elements with class=\"note\"?",
     [".note", "#note", "note", "*note"], 0, "#note selects the element with id=\"note\"."),
    ("For  <p id=\"x\" class=\"y\">Text</p>  with the rules  p { color: red; }  .y { color: green; }  #x { color: blue; } , the text colour is:",
     ["blue", "red", "green", "black"], 0, "Specificity: id > class > element."),
    ("The CSS box model, from the inside out, consists of:",
     ["Content, padding, border, margin", "Margin, border, padding, content", "Content, margin, padding, border", "Padding, content, border, margin"], 0, "Padding is inside the border; margin is outside it."),
    ("An element has  width: 200px; padding: 10px; border: 5px solid; margin: 20px;  with the default box-sizing (content-box). The total horizontal space it occupies is:",
     ["270px", "200px", "230px", "250px"], 0, "200 + 2×10 + 2×5 + 2×20 = 270; its border-box width is 230px."),
    ("With  box-sizing: border-box; , the width property includes:",
     ["Content, padding and border", "Content only", "Content and margin", "Margin only"], 0, "This makes layouts easier to calculate."),
    ("display: none and visibility: hidden differ in that:",
     ["display: none removes the element from the layout, while visibility: hidden hides it but keeps its space", "They are identical", "visibility: hidden deletes the element from the DOM", "display: none keeps the element's space"], 0, "Both hide the element from view."),
    ("An element with position: absolute is positioned relative to:",
     ["Its nearest positioned (non-static) ancestor, or the initial containing block if there is none", "Always the browser window", "Its own normal position", "The next sibling"], 0, "position: fixed is relative to the viewport."),
    ("The default value of the CSS position property is:",
     ["static", "relative", "absolute", "fixed"], 0, "top, left and so on have no effect on static elements."),
    ("The colour #FF0000 in CSS is:",
     ["Red", "Green", "Blue", "White"], 0, "The pairs are red, green and blue in hexadecimal; FF is full intensity."),
    ("If the root element's font size is 16px, an element with font-size: 1.5rem is:",
     ["24px", "16px", "1.5px", "32px"], 0, "rem is relative to the root font size: 1.5 × 16."),
    ("Which CSS property is normally inherited by child elements?",
     ["color", "border", "margin", "padding"], 0, "Text properties such as color and font-family are inherited; box properties are not."),
    ("The CSS rule  a:hover { color: red; }  uses a:",
     ["Pseudo-class", "Pseudo-element", "Class selector", "Id selector"], 0, "::first-letter and ::before are pseudo-elements."),
    ("Media queries such as  @media (max-width: 600px) { … }  are used mainly for:",
     ["Responsive design – different styles for different screen sizes", "Playing audio", "Querying databases", "Loading JavaScript"], 0, "They help pages work on phones and desktops."),
    ("In a flex container (display: flex) with the default row direction, justify-content aligns items along the ______ axis and align-items along the ______ axis.",
     ["main (horizontal); cross (vertical)", "cross; main", "vertical; horizontal", "z; x"], 0, "The main axis follows flex-direction."),
    ("The z-index property controls:",
     ["The stacking order of overlapping positioned elements", "The zoom level of the page", "The font size", "The order of CSS files"], 0, "Higher values appear in front."),
    ("A comment in a CSS file is written as:",
     ["/* comment */", "<!-- comment -->", "// comment only", "# comment"], 0, "HTML comments do not work inside CSS."),
    ("The word 'cascading' in CSS refers to:",
     ["The rules for resolving conflicts when several style rules apply to the same element", "Pages falling like a waterfall", "Animations only", "Linking many HTML files"], 0, "Importance, specificity and source order decide which rule wins."),
    ("A typical DHTML effect is:",
     ["Changing an image when the mouse moves over it (a rollover) using JavaScript and CSS", "Compiling C programs in the browser", "Sending e-mail from HTML alone", "Storing data in a database with HTML tags"], 0, "Scripts react to events such as onmouseover and change the DOM or styles."),
    ("Consider the statements:\nI. Without !important, an inline style overrides a conflicting rule in an internal style sheet.\nII. The margin lies inside the border in the CSS box model.\nWhich is/are correct?",
     I_II, 0, "Margin is outside the border; padding is inside it."),
    ("Consider the statements:\nI. em is relative to the font size of the element (or its parent, when used for font-size).\nII. rem is relative to the font size of the root (html) element.\nWhich is/are correct?",
     I_II, 2, "rem avoids the compounding effect of nested em values."),
    ("Consider the statements:\nI. A grouping selector such as  h1, h2 { … }  applies the rule to both elements.\nII. The selector  div > p  selects every p anywhere inside a div, however deep.\nWhich is/are correct?",
     I_II, 0, "div > p selects only direct children; div p (descendant selector) selects all nested p elements."),
    ("Assertion (A): One external style sheet can style many pages at once.\nReason (R): Every page can link to the same .css file.",
     AR, 0, "Changing that one file updates the look of all linked pages."),
    ("Assertion (A): A class selector is more specific than an id selector.\nReason (R): An id selector is more specific than a class selector.",
     AR, 3, "R is correct, which makes A false."),
    ("Assertion (A): display: none hides an element and removes it from the layout.\nReason (R): visibility: hidden also removes the element's space from the layout.",
     AR, 2, "A is true; R is false – visibility: hidden keeps the space."),
    ("Assertion (A): DHTML pages can change their content without reloading.\nReason (R): CSS stands for Cascading Style Sheets.",
     AR, 1, "Both true but unrelated; the dynamic behaviour comes from JavaScript manipulating the DOM."),
    ("Which rule makes every paragraph's text centred and 18 pixels high?",
     ["p { text-align: center; font-size: 18px; }", "p { align: center; size: 18; }", "<p style=center 18>", "p = center, 18px;"], 0, "Declarations are property: value pairs separated by semicolons inside braces."),
]

TOPICS = {
    "Programming in C++ – Part 2": [("1 · Function and Operator Overloading, and Virtual Functions", OVERLOAD_VIRTUAL),
                                    ("2 · Inheritance in C++", CPP_INHERITANCE),
                                    ("3 · Templates and Exception Handling", TEMPLATES_EXCEPTIONS),
                                    ("4 · Streams, Files and Event Handling", STREAMS_EVENTS)],
    "Web Programming – HTML, DHTML, CSS": [("1 · HTML: Structure, Text, Links, Lists and Images", HTML_BASICS),
                                           ("2 · HTML Tables and Forms", HTML_TABLES_FORMS),
                                           ("3 · DHTML and CSS", DHTML_CSS)],
}
