"""Paper 2 · Unit 5 · ER Model & Relational Model; Relational Algebra and Relational Calculus (4 sub-topics × 30).
References: Elmasri & Navathe, Fundamentals of Database Systems; Silberschatz, Korth & Sudarshan, Database System Concepts.
"PYQ pattern" questions follow themes that recur in the downloaded KEA/KSET/GTTC/VAO papers (sources/pyq): fundamental
relational-algebra operations, referential-integrity violations, total participation (double lines), weak-entity keys,
a relation as a subset of a Cartesian product of domains, informal design guidelines."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KSET / KEA / GTTC papers). "

ER = [
    ("The Entity-Relationship (ER) model was proposed in 1976 by:",
     ["Peter Chen", "E. F. Codd", "Raymond Boyce", "Charles Bachman"], 0, PYQ + "Codd proposed the relational model (1970)."),
    ("In an ER diagram, a rectangle represents a(n):",
     ["Entity set", "Relationship set", "Attribute", "Primary key"], 0, "Diamonds are relationships and ellipses are attributes."),
    ("In an ER diagram, a double line connecting an entity set to a relationship indicates:",
     ["Total participation of that entity set in the relationship", "A many-to-many relationship", "A derived attribute", "A recursive relationship"], 0, PYQ + "Every entity in the set must take part in at least one relationship instance."),
    ("A weak entity set is one that:",
     ["Does not have a key of its own and is identified through an owner entity", "Has no attributes", "Participates in no relationships", "Has more than one primary key"], 0, PYQ + "It is shown as a double rectangle and linked by a double-diamond identifying relationship."),
    ("The partial key (discriminator) of a weak entity set is shown in an ER diagram by:",
     ["A dashed underline", "A double underline", "A double ellipse", "A dotted rectangle"], 0, "The owner's key plus the discriminator form the weak entity's key."),
    ("PAYMENT is a weak entity owned by LOAN (key loan_no); payment_no distinguishes payments of the same loan. The primary key of the PAYMENT relation is:",
     ["{loan_no, payment_no}", "{payment_no}", "{loan_no}", "{payment_no, amount}"], 0, PYQ + "Primary key of a weak entity = owner's primary key + discriminator."),
    ("An attribute such as Phone_numbers, which can hold several values for one entity, is called:",
     ["Multivalued attribute", "Composite attribute", "Derived attribute", "Key attribute"], 0, "It is drawn as a double ellipse."),
    ("An attribute such as Age, computed from Date_of_birth, is a:",
     ["Derived attribute", "Composite attribute", "Multivalued attribute", "Key attribute"], 0, "Derived attributes are drawn with dashed ellipses and usually not stored."),
    ("An attribute such as Name, made up of First_name, Middle_name and Last_name, is a:",
     ["Composite attribute", "Simple attribute", "Derived attribute", "Multivalued attribute"], 0, "Composite attributes can be divided into smaller parts."),
    ("A relationship in which an EMPLOYEE supervises another EMPLOYEE is called a:",
     ["Recursive (unary) relationship", "Ternary relationship", "Weak relationship", "Derived relationship"], 0, "The two participations are distinguished by role names (supervisor, supervisee)."),
    ("A relationship set that involves three entity sets is said to have degree:",
     ["3 (ternary)", "2 (binary)", "1 (unary)", "0"], 0, "Degree = number of participating entity sets."),
    ("In a 1 : N relationship between DEPARTMENT (1) and EMPLOYEE (N), when mapping to relations the foreign key is placed in:",
     ["EMPLOYEE, the N-side relation", "DEPARTMENT, the 1-side relation", "A separate third relation only", "Both relations"], 0, "Each employee row stores its department's key."),
    ("Entity sets A and B are related by a many-to-many relationship R with no attributes of its own. The minimum number of relations needed is:",
     ["3", "2", "1", "4"], 0, PYQ + "One relation each for A and B, and one for R holding both keys."),
    ("Entity sets A and B have a one-to-many relationship R, and every B entity participates in R. The minimum number of relations needed is:",
     ["2", "3", "1", "4"], 0, "R is absorbed into B's relation as a foreign key."),
    ("A multivalued attribute of an entity is mapped to the relational model as:",
     ["A separate relation containing the attribute and the entity's key", "Extra columns in the same relation", "A derived column", "It is dropped"], 0, "Elmasri step 6 of the ER-to-relational mapping."),
    ("Designing lower-level entity sets from a higher-level entity set by identifying distinguishing features (top-down) is called:",
     ["Specialization", "Generalization", "Aggregation", "Normalization"], 0, "Generalization is the reverse (bottom-up) process."),
    ("Combining several entity sets that share features into a higher-level entity set (bottom-up) is called:",
     ["Generalization", "Specialization", "Aggregation", "Decomposition"], 0, "E.g. CAR and TRUCK generalised into VEHICLE."),
    ("Aggregation in the ER model is used to:",
     ["Treat a relationship set as an entity so that it can take part in another relationship", "Compute sums of attributes", "Remove redundancy", "Split entity sets"], 0, "E.g. a relationship between (EMPLOYEE works-on PROJECT) and MANAGER."),
    ("In (min, max) notation, (0, N) on an entity's participation in a relationship means:",
     ["Partial participation; an entity may take part many times", "Total participation, exactly once", "Total participation, at most once", "No participation allowed"], 0, "min = 0 means participation is optional."),
    ("Hours_worked belongs to the M : N relationship WORKS_ON between EMPLOYEE and PROJECT. When mapped, Hours_worked goes into:",
     ["The WORKS_ON relation", "The EMPLOYEE relation", "The PROJECT relation", "Nowhere; it is dropped"], 0, "It describes a pair (employee, project), not either entity alone."),
    ("Entity sets A and B have a one-to-one relationship with total participation on both sides. The minimum number of relations needed is:",
     ["1", "2", "3", "0"], 0, "Both entity sets and the relationship can be merged into a single relation."),
    ("Consider the statements:\nI. A weak entity set always has total participation in its identifying relationship.\nII. A weak entity set can be identified without its owner entity.\nWhich is/are correct?",
     I_II, 0, "Weak entities depend on their owner for identification."),
    ("Consider the statements:\nI. Specialization can be disjoint or overlapping.\nII. Specialization can be total or partial.\nWhich is/are correct?",
     I_II, 2, "Both constraints apply to specialization/generalization."),
    ("Consider the statements:\nI. A derived attribute must always be stored in the database.\nII. A multivalued attribute is mapped into the same relation as extra columns.\nWhich is/are correct?",
     I_II, 3, "Derived attributes are usually computed; multivalued attributes go to a separate relation."),
    ("Assertion (A): An M : N relationship needs its own relation when mapped.\nReason (R): A foreign key in either entity's relation could hold only one value per tuple.",
     AR, 0, "So the pairs must be stored in a separate relation."),
    ("Assertion (A): Every entity set in an ER diagram must have a key attribute.\nReason (R): Weak entity sets are identified using the key of an owner entity set.",
     AR, 3, "Weak entity sets have no key of their own, so A is false."),
    ("Assertion (A): Double lines in an ER diagram show total participation.\nReason (R): Peter Chen proposed the ER model.",
     AR, 1, "Both true, but R does not explain A."),
    ("Match the ER symbol with its meaning:\na. Double rectangle  b. Double ellipse  c. Dashed ellipse  d. Double diamond\n1. Identifying relationship  2. Derived attribute  3. Multivalued attribute  4. Weak entity set",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Standard Elmasri/Chen notation."),
    ("Match the concept with an example:\na. Composite attribute  b. Multivalued attribute  c. Recursive relationship  d. Weak entity\n1. DEPENDENT of an EMPLOYEE  2. EMPLOYEE supervises EMPLOYEE  3. College_degrees of a person  4. Address (street, city, PIN)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Typical textbook examples."),
    ("In an EER diagram, a specialization is commonly shown using:",
     ["A circle (or triangle labelled ISA) connecting the superclass to its subclasses", "A double rectangle", "A dashed underline", "A diamond with double lines"], 0, "'d' in the circle means disjoint and 'o' means overlapping."),
]

RELATIONAL = [
    ("In the relational model, a relation is formally a:",
     ["Subset of the Cartesian product of a list of domains", "Subset of the Cartesian product of a list of tuples", "Set of foreign keys", "Sequence of records in a file"], 0, PYQ + "Each tuple takes one value from each attribute's domain."),
    ("The relational model of data was proposed in 1970 by:",
     ["E. F. Codd", "Peter Chen", "Ronald Fagin", "C. J. Date"], 0, PYQ + "In 'A Relational Model of Data for Large Shared Data Banks'."),
    ("The number of attributes in a relation is called its:",
     ["Degree (arity)", "Cardinality", "Domain", "Schema size"], 0, "The number of tuples is its cardinality."),
    ("A relation instance has 6 attributes and 40 tuples. Its degree and cardinality are:",
     ["6 and 40", "40 and 6", "46 and 240", "6 and 6"], 0, "Degree counts columns; cardinality counts rows."),
    ("A domain in the relational model is:",
     ["A set of atomic values an attribute can take", "A set of relations", "The primary key", "A group of tuples"], 0, "E.g. the set of valid 10-digit phone numbers."),
    ("Which property does a relation have?",
     ["Tuples are unordered and no two tuples are identical", "Tuples must be stored in key order", "Duplicate tuples are allowed", "Attribute values may be lists"], 0, "A relation is a set of tuples (in the formal model)."),
    ("A minimal superkey is called a:",
     ["Candidate key", "Foreign key", "Composite key only", "Alternate key only"], 0, "One candidate key is chosen as the primary key; the others are alternate keys."),
    ("Relation R(A, B, C, D) has A as its only candidate key. How many superkeys does R have?",
     ["8", "4", "15", "16"], 0, PYQ + "Any set containing A is a superkey: 2³ = 8 (choose any subset of B, C, D)."),
    ("Relation R(A, B, C) has two candidate keys, A and B. How many superkeys does R have?",
     ["6", "4", "8", "3"], 0, "Sets containing A: 4; containing B: 4; containing both: 2 → 4 + 4 − 2 = 6."),
    ("The entity integrity constraint states that:",
     ["No primary key value can be NULL", "Every foreign key must be NULL", "Every attribute must be unique", "A relation must have at least one tuple"], 0, PYQ + "Otherwise the tuple could not be identified."),
    ("The referential integrity constraint states that a foreign key value must:",
     ["Match a primary-key value in the referenced relation, or be NULL", "Always be NULL", "Be unique in the referencing relation", "Be larger than the primary key"], 0, PYQ + "It keeps references between relations consistent."),
    ("ENROL(roll_no) references STUDENT(roll_no). Which operation can violate referential integrity?",
     ["Deleting a STUDENT tuple whose roll_no appears in ENROL", "Inserting a new STUDENT tuple", "Deleting an ENROL tuple", "Reading STUDENT tuples"], 0, PYQ + "Inserting into ENROL with an unknown roll_no is the other way to violate it."),
    ("Inserting a new tuple into a relation can violate:",
     ["Domain, key, entity integrity and referential integrity constraints", "Only key constraints", "Only referential integrity", "No constraints"], 0, "Elmasri: insertion can violate all four kinds of constraints."),
    ("A foreign key defined with ON DELETE CASCADE means that when the referenced tuple is deleted:",
     ["The referencing tuples are also deleted", "The deletion is rejected", "The foreign keys are set to NULL", "Nothing happens"], 0, "ON DELETE SET NULL would instead set the foreign keys to NULL."),
    ("Employee.supervisor_ssn referring to Employee.ssn is an example of a:",
     ["Self-referencing (recursive) foreign key", "Candidate key", "Composite primary key", "Domain constraint"], 0, "A foreign key may refer to its own relation."),
    ("In the relational model, NULL can mean:",
     ["Unknown, unavailable or not applicable", "Zero", "An empty string only", "A duplicate value"], 0, "Its several meanings are why NULLs complicate design."),
    ("The description of a database (relation schemas and constraints), which changes rarely, is the database:",
     ["Schema", "State (instance)", "Snapshot", "Tuple"], 0, "The state is the data at a particular moment."),
    ("Elmasri lists how many informal guidelines (measures of quality) for relation schema design?",
     ["4", "5", "6", "7"], 0, PYQ + "Clear semantics; no update anomalies; few NULLs; no spurious tuples."),
    ("Storing EMPLOYEE and DEPARTMENT data in one relation EMP_DEPT, so that a new department cannot be added until it has an employee, is an example of:",
     ["Insertion anomaly", "Deletion anomaly", "Modification anomaly", "Referential integrity"], 0, "Deleting the last employee of a department would be a deletion anomaly."),
    ("A key constraint (uniqueness constraint) states that:",
     ["No two tuples can have the same value for the key", "Keys must be integers", "Keys cannot be composite", "Every attribute is a key"], 0, "Candidate keys uniquely identify tuples."),
    ("A domain constraint is violated when:",
     ["An attribute value is not from the attribute's domain, e.g. text in a numeric Age field", "A key is duplicated", "A foreign key is NULL", "A table has no rows"], 0, "Domains define allowed values and types."),
    ("Consider the statements:\nI. A relation can have more than one candidate key.\nII. A primary key may contain NULL in one of its attributes.\nWhich is/are correct?",
     I_II, 0, "Entity integrity forbids NULL in any primary-key attribute."),
    ("Consider the statements:\nI. Deleting a tuple from the referencing relation can violate referential integrity.\nII. Deleting a tuple from the referenced relation can violate referential integrity.\nWhich is/are correct?",
     I_II, 1, "Removing a referencing tuple leaves no dangling reference."),
    ("Consider the statements:\nI. A foreign key may be NULL unless declared NOT NULL.\nII. A foreign key must refer to the primary key (or a candidate key) of the referenced relation.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Duplicate tuples are not allowed in a relation (in the formal model).\nReason (R): A relation is defined as a set of tuples.",
     AR, 0, "Sets have no duplicate elements."),
    ("Assertion (A): A superkey is always a candidate key.\nReason (R): A candidate key is a minimal superkey.",
     AR, 3, "A superkey need not be minimal, so A is false."),
    ("Assertion (A): Entity integrity prevents NULL primary keys.\nReason (R): Foreign keys can never be NULL.",
     AR, 2, "A is true; R is false – foreign keys may be NULL."),
    ("Assertion (A): Insertion anomalies arise in poorly designed relations.\nReason (R): The relational model was proposed by E. F. Codd.",
     AR, 1, "Both true, but R does not explain A."),
    ("Match the term with its meaning:\na. Degree  b. Cardinality  c. Candidate key  d. Foreign key\n1. Refers to a key in another (or the same) relation  2. Minimal superkey  3. Number of tuples  4. Number of attributes",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Basic relational terminology."),
    ("Match the constraint with what violates it:\na. Domain  b. Key  c. Entity integrity  d. Referential integrity\n1. Foreign key pointing to a non-existent tuple  2. NULL primary key  3. Two tuples with the same key  4. Value outside the allowed set",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "The four basic relational constraints."),
]

ALGEBRA = [
    ("Which of the following is NOT a fundamental (basic) operation of relational algebra?",
     ["Natural join", "Cartesian product", "Set difference", "Union"], 0, PYQ + "Basic operations: select, project, union, set difference, Cartesian product, rename. Joins, intersection and division are derived."),
    ("The selection operation σ in relational algebra:",
     ["Chooses tuples that satisfy a condition (a horizontal subset)", "Chooses columns (a vertical subset)", "Joins two relations", "Renames a relation"], 0, "Projection π chooses columns."),
    ("Relation R has 10 tuples, and attribute City has 3 distinct values. How many tuples does π_City(R) return (set semantics)?",
     ["3", "10", "13", "30"], 0, "Projection removes duplicate tuples."),
    ("R has 3 attributes and 10 tuples; S has 4 attributes and 5 tuples. R × S has:",
     ["7 attributes and 50 tuples", "12 attributes and 15 tuples", "7 attributes and 15 tuples", "12 attributes and 50 tuples"], 0, PYQ + "Degrees add; cardinalities multiply."),
    ("For R ∪ S, R − S or R ∩ S to be valid, R and S must be:",
     ["Union compatible (same number of attributes with matching domains)", "Of the same cardinality", "Joined first", "Sorted"], 0, "Also called type compatible."),
    ("If R has 10 tuples and S has 6 tuples (union compatible), the number of tuples in R ∪ S lies between:",
     ["10 and 16", "6 and 10", "0 and 16", "16 and 60"], 0, PYQ + "Minimum when S ⊆ R; maximum when they share no tuples."),
    ("If R has 10 tuples and S has 6 tuples (union compatible), the maximum number of tuples in R − S is:",
     ["10", "4", "6", "16"], 0, "When R and S share no tuples, nothing is removed."),
    ("Intersection can be expressed using basic operations as:",
     ["R ∩ S = R − (R − S)", "R ∩ S = R ∪ S", "R ∩ S = R × S", "R ∩ S = σ(R) − S"], 0, "Hence intersection is not a fundamental operation."),
    ("A theta join R ⋈_θ S is equivalent to:",
     ["σ_θ(R × S)", "π_θ(R ∪ S)", "R − S", "σ_θ(R) ∪ σ_θ(S)"], 0, "Selection applied on the Cartesian product."),
    ("If R and S have no common attributes, the natural join R ⋈ S is the same as:",
     ["R × S", "R ∩ S", "R ∪ S", "The empty relation"], 0, "There is no condition to match on."),
    ("R(A, B) = {(1, a), (2, b), (3, a)} and S(B, C) = {(a, x), (a, y), (c, z)}. How many tuples are in R ⋈ S?",
     ["4", "2", "3", "9"], 0, "Matches on B = a: (1, a, x), (1, a, y), (3, a, x), (3, a, y)."),
    ("R(A, B) = {(a1, b1), (a1, b2), (a2, b1), (a3, b2)} and S(B) = {b1, b2}. R ÷ S is:",
     ["{a1}", "{a1, a2}", "{a1, a2, a3}", "{ }"], 0, "Only a1 is paired with every value of S."),
    ("The division operator is typically used for queries containing the phrase:",
     ["'for all' (e.g. students who took all courses)", "'at least one'", "'sorted by'", "'grouped by'"], 0, "Division expresses universal quantification."),
    ("A left outer join R ⟕ S:",
     ["Keeps every tuple of R, padding S's attributes with NULL where there is no match", "Keeps every tuple of S", "Keeps only matching tuples", "Removes all NULLs"], 0, "The right outer join keeps every tuple of S."),
    ("The rename operator in relational algebra is:",
     ["ρ (rho)", "σ (sigma)", "π (pi)", "÷ (division)"], 0, "It renames a relation or its attributes."),
    ("Which equivalence of selections is valid?",
     ["σ_c1 ∧ c2(R) = σ_c1(σ_c2(R))", "σ_c1 ∨ c2(R) = σ_c1(σ_c2(R))", "σ_c(R × S) = σ_c(R) × S always", "π_A(σ_c(R)) = σ_c(R) always"], 0, "Cascade of selections; selections also commute."),
    ("Which expression gives the names of employees in department 5 earning more than 50,000?",
     ["π_Name(σ_Dno = 5 ∧ Salary > 50000(EMPLOYEE))", "σ_Name(π_Dno = 5(EMPLOYEE))", "π_Dno = 5(σ_Name(EMPLOYEE))", "EMPLOYEE ÷ Salary"], 0, "Select the rows, then project the column."),
    ("Relational algebra is:",
     ["A procedural query language", "A non-procedural query language", "A data-definition language", "A host programming language"], 0, PYQ + "Relational calculus is the non-procedural counterpart."),
    ("Aggregate functions such as SUM and COUNT are provided in:",
     ["Extended relational algebra (the grouping operator 𝒢)", "Basic relational algebra", "Basic tuple relational calculus", "No query language"], 0, "They go beyond the basic algebra."),
    ("The maximum number of tuples in a natural join of R (m tuples) and S (n tuples) is:",
     ["m × n", "m + n", "max(m, n)", "min(m, n)"], 0, "When every tuple matches every tuple; the minimum is 0."),
    ("Which operation is unary?",
     ["Projection", "Union", "Cartesian product", "Natural join"], 0, "Selection, projection and rename are unary; the others are binary."),
    ("Consider the statements:\nI. Projection may reduce the number of tuples.\nII. Selection may reduce the number of attributes.\nWhich is/are correct?",
     I_II, 0, "Projection removes duplicates; selection keeps all attributes."),
    ("Consider the statements:\nI. Division can be expressed using π, × and −.\nII. Natural join can be expressed using ×, σ and π.\nWhich is/are correct?",
     I_II, 2, "Both are derived operations."),
    ("Consider the statements:\nI. Union is defined for any two relations regardless of their attributes.\nII. R × S is defined only if R and S are union compatible.\nWhich is/are correct?",
     I_II, 3, "Union needs compatibility; the Cartesian product does not."),
    ("Assertion (A): Intersection is not a fundamental relational-algebra operation.\nReason (R): It can be expressed as R − (R − S).",
     AR, 0, "Anything expressible by basic operations is derived."),
    ("Assertion (A): σ_City='Mysuru'(R) can return more tuples than R.\nReason (R): Selection returns a subset of the tuples of R.",
     AR, 3, "A subset cannot be larger, so A is false."),
    ("Assertion (A): R ⋈ S equals R × S when R and S share no attributes.\nReason (R): The natural join always removes all tuples with NULLs.",
     AR, 2, "A is true; R is false."),
    ("Assertion (A): Relational algebra is procedural.\nReason (R): Codd introduced relational algebra in 1970.",
     AR, 1, "Both true, but R does not explain A; A holds because an algebra expression states the order of operations."),
    ("Match the operator with its meaning:\na. σ  b. π  c. ρ  d. ÷\n1. 'For all' queries  2. Rename  3. Choose columns  4. Choose rows",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Common matching question."),
    ("Match the operation with its result size (R: m tuples, S: n tuples):\na. R × S  b. R ∪ S (max)  c. R − S (max)  d. R ⋈ S (min)\n1. 0  2. m  3. m + n  4. m × n",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Bounds on result sizes."),
]

CALCULUS = [
    ("A tuple relational calculus (TRC) query has the general form:",
     ["{t | P(t)}", "{<x₁, …, xₙ> | P(x₁, …, xₙ)}", "π_A(σ_c(R))", "SELECT * FROM R"], 0, "t is a tuple variable and P a formula."),
    ("A domain relational calculus (DRC) query has the general form:",
     ["{<x₁, x₂, …, xₙ> | P(x₁, x₂, …, xₙ)}", "{t | P(t)}", "σ_c(R)", "R ÷ S"], 0, "Variables range over attribute domains."),
    ("Relational calculus is:",
     ["Declarative (non-procedural): it states what to retrieve, not how", "Procedural", "A storage structure", "A transaction protocol"], 0, PYQ + "Relational algebra is procedural."),
    ("Codd's theorem states that relational algebra and safe relational calculus are:",
     ["Equivalent in expressive power", "Unrelated", "Both procedural", "Both unable to express joins"], 0, PYQ + "Any query in one can be written in the other."),
    ("A query language is called relationally complete if it can express:",
     ["Every query expressible in relational algebra", "Every possible computation", "Recursive queries", "Only selection queries"], 0, "SQL is relationally complete (and more)."),
    ("Which TRC expression is unsafe?",
     ["{t | ¬EMPLOYEE(t)}", "{t | EMPLOYEE(t) ∧ t.Salary > 50000}", "{t.Name | EMPLOYEE(t)}", "{t | EMPLOYEE(t) ∧ t.Dno = 5}"], 0, "It describes infinitely many tuples not in EMPLOYEE."),
    ("A calculus expression is safe if:",
     ["Its result is finite and all values come from the domains of the database", "It uses no quantifiers", "It uses only ∀", "It returns exactly one tuple"], 0, "Safe expressions are the ones equivalent to algebra queries."),
    ("Which TRC query finds names of employees earning more than 50,000?",
     ["{t.Name | EMPLOYEE(t) ∧ t.Salary > 50000}", "{t | t.Salary > 50000}", "{t.Name | ¬EMPLOYEE(t)}", "{t.Name | ∀t (t.Salary > 50000)}"], 0, "Range the variable over EMPLOYEE, then apply the condition."),
    ("The relational-algebra query π_A(σ_B = 5(R)) in TRC is:",
     ["{t.A | R(t) ∧ t.B = 5}", "{t | t.A = 5}", "{t.B | R(t) ∧ t.A = 5}", "{t.A | ¬R(t) ∧ t.B = 5}"], 0, "Select with the condition and output only attribute A."),
    ("The universal quantifier ∀ in relational calculus corresponds to which relational-algebra operation?",
     ["Division", "Union", "Projection", "Rename"], 0, "'For all' queries need ÷ in the algebra."),
    ("Which identity is used to remove ∀ from a calculus formula?",
     ["∀x P(x) ≡ ¬∃x ¬P(x)", "∀x P(x) ≡ ∃x P(x)", "∀x P(x) ≡ ¬P(x)", "∀x P(x) ≡ P(x) ∨ ¬P(x)"], 0, "Universal = not exists a counter-example."),
    ("In a calculus formula, P ⇒ Q is equivalent to:",
     ["¬P ∨ Q", "P ∧ ¬Q", "¬P ∧ Q", "P ∨ Q"], 0, "Implication rewritten with OR."),
    ("Query-By-Example (QBE) is based on:",
     ["Domain relational calculus", "Tuple relational calculus", "Relational algebra only", "Network data model"], 0, PYQ + "SQL draws largely on tuple relational calculus."),
    ("QUEL, the query language of the Ingres DBMS, was based on:",
     ["Tuple relational calculus", "Domain relational calculus", "Hierarchical model", "Datalog"], 0, "Like SQL, it uses tuple variables."),
    ("A variable in a calculus formula that is not quantified by ∃ or ∀ is called:",
     ["Free", "Bound", "Safe", "Constant"], 0, "Only the free tuple variable(s) appear in the result."),
    ("Which of the following CANNOT be expressed in basic relational algebra or safe relational calculus?",
     ["Transitive closure (e.g. all direct and indirect managers)", "Join of two relations", "Selection on a condition", "Projection of attributes"], 0, PYQ + "Recursive queries need extensions such as recursive SQL or Datalog."),
    ("An atom of the form t ∈ R (or R(t)) in TRC means:",
     ["Tuple variable t ranges over relation R", "t is a primary key of R", "R is empty", "t is NULL"], 0, "Other atoms compare attributes with each other or with constants."),
    ("Which DRC query finds names of employees in department 5 from EMP(Name, Dno)?",
     ["{<n> | ∃d (<n, d> ∈ EMP ∧ d = 5)}", "{<n, d> | d ≠ 5}", "{<n> | <n, d> ∉ EMP}", "{<d> | ∃n (n = 5)}"], 0, "Bind d with ∃ and test it; output n."),
    ("Aggregate functions such as AVG are:",
     ["Not part of pure relational calculus (they are extensions)", "The basis of relational calculus", "Only in DRC", "Only in TRC"], 0, "Like basic algebra, pure calculus has no aggregates."),
    ("A tuple variable in TRC ranges over:",
     ["Tuples of a relation", "Values of a single domain", "Attributes", "Indexes"], 0, "In DRC, variables range over domain values."),
    ("Consider the statements:\nI. Tuple relational calculus is non-procedural.\nII. Every safe calculus query has an equivalent relational-algebra query.\nWhich is/are correct?",
     I_II, 2, "Codd's theorem."),
    ("Consider the statements:\nI. {t | ¬R(t)} is a safe expression.\nII. Safe expressions always give finite results.\nWhich is/are correct?",
     I_II, 1, "Complements of a relation are infinite, hence unsafe."),
    ("Consider the statements:\nI. QBE is based on tuple relational calculus.\nII. Relational calculus can express transitive closure.\nWhich is/are correct?",
     I_II, 3, "QBE is DRC-based; transitive closure is not expressible."),
    ("Assertion (A): Relational calculus queries describe what data is wanted, not how to get it.\nReason (R): Calculus formulas specify properties of the result rather than a sequence of operations.",
     AR, 0, "That is what non-procedural means."),
    ("Assertion (A): Safe relational calculus is more powerful than relational algebra.\nReason (R): Calculus uses quantifiers ∃ and ∀.",
     AR, 3, "By Codd's theorem they are equally powerful; A is false."),
    ("Assertion (A): Division in the algebra corresponds to ∀ in the calculus.\nReason (R): QBE is based on tuple relational calculus.",
     AR, 2, "A is true; R is false – QBE is based on DRC."),
    ("Match the language with its basis:\na. SQL  b. QBE  c. QUEL  d. Relational algebra\n1. Procedural operators on relations  2. Tuple relational calculus (Ingres)  3. Domain relational calculus  4. Largely tuple relational calculus",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Query languages and their foundations."),
    ("Match the calculus construct with its meaning:\na. ∃t  b. ∀t  c. Free variable  d. Unsafe expression\n1. Result is infinite  2. Appears in the result  3. For every tuple  4. There exists a tuple",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Core calculus vocabulary."),
    ("Which TRC query finds students enrolled in every course (ENROL(sid, cid), COURSE(cid))?",
     ["{s.sid | STUDENT(s) ∧ ∀c (COURSE(c) ⇒ ∃e (ENROL(e) ∧ e.sid = s.sid ∧ e.cid = c.cid))}", "{s.sid | STUDENT(s) ∧ ∃c COURSE(c)}", "{s.sid | ¬STUDENT(s)}", "{s.sid | ∀c ¬COURSE(c)}"], 0, "'Every course' needs ∀ with implication."),
    ("In TRC, the formula ∃s (DEPT(s) ∧ s.Dno = t.Dno) used inside a query on t acts like a:",
     ["Join condition (semi-join) between t's relation and DEPT", "Projection", "Rename", "Union"], 0, "The existential quantifier links two relations."),
]

TOPICS = {
    "ER Model & Relational Model": [("1 · Entity-Relationship Model", ER),
                                    ("2 · Relational Model, Constraints and Update Operations", RELATIONAL)],
    "Relational Algebra and Relational Calculus": [("1 · Relational Algebra", ALGEBRA),
                                                   ("2 · Tuple and Domain Relational Calculus", CALCULUS)],
}
