"""Paper 2 · Unit 5 · P2-U5-05 SQL – Part 2 and P2-U5-06 Normalization (2 topics × 2 sub-topics × 30).
References: Elmasri & Navathe, Fundamentals of Database Systems (chs. 7, 14, 15); Silberschatz, Korth & Sudarshan, Database
System Concepts (chs. 5, 7); Oracle PL/SQL and MySQL reference manuals; OWASP SQL Injection Prevention Cheat Sheet.
Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question number)
with new questions. Official answers come from KEA's final keys: Karnataka Legislative Council Secretariat 2024 (Computer
Operator P2, Sr/Jr Programmer P2 – booklet A1; final key 09-04-2025) and GTTC 2024 (Lecturer CS – booklet A1; final key
30-12-2024). KSET 2025 and KEA 2026 questions are reused from packs/pyq-p2.json (answers worked out by ExamSim).
Obvious printing typos are corrected."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

VIEWS_PROC = [
    ("A view in SQL is best described as:",
     ["A virtual table whose rows come from a stored query on base tables", "A physical copy of a table kept on disk", "An index on a table", "A temporary table that is deleted at logout"], 0,
     PYQ + "A (non-materialised) view stores only its defining query."),
    ("Which statement creates a view?",
     ["CREATE VIEW v AS SELECT name, salary FROM emp;", "CREATE TABLE v AS VIEW emp;", "MAKE VIEW v FROM emp;", "SELECT * INTO VIEW v FROM emp;"], 0,
     "CREATE VIEW name AS query."),
    ("When a query uses an ordinary (virtual) view, the DBMS normally:",
     ["Rewrites the query on the view into a query on the base tables (query modification)", "Reads rows stored separately for the view", "Copies all base tables into memory", "Refuses the query"], 0,
     "View resolution / query modification merges the view definition into the user's query."),
    ("A materialized view differs from an ordinary view because it:",
     ["Stores the query result physically and must be refreshed when base tables change", "Cannot contain a WHERE clause", "Is always updatable", "Has no defining query"], 0,
     PYQ + "Materialised views trade storage and refresh cost for faster reads."),
    ("Which kind of view is generally NOT updatable?",
     ["A view that uses GROUP BY and aggregate functions", "A view on one table that keeps its primary key", "A view that selects some rows of one table", "A view that selects some columns of one table, including the key"], 0,
     "Rows of an aggregate view do not map back to single base rows."),
    ("The clause WITH CHECK OPTION in a view definition ensures that:",
     ["Rows inserted or updated through the view satisfy the view's WHERE condition", "The view is checked for syntax errors daily", "Only the DBA can query the view", "The view is materialized"], 0,
     PYQ + "Otherwise a row could be changed so that it 'disappears' from the view."),
    ("DROP VIEW high_paid; does what?",
     ["Removes the view definition; the base tables and their data are unchanged", "Deletes all rows of the base table", "Drops the base table", "Empties the view but keeps its rows on disk"], 0,
     "A view holds no data of its own."),
    ("Views mainly help in achieving which kind of data independence?",
     ["Logical data independence", "Physical data independence", "Hardware independence", "Network independence"], 0,
     PYQ + "Users can keep using a view even after the conceptual schema is reorganised."),
    ("Which statement changes the definition of an existing view in Oracle and MySQL without dropping it first?",
     ["CREATE OR REPLACE VIEW", "UPDATE VIEW", "MODIFY VIEW", "RENAME VIEW"], 0,
     "ALTER VIEW also exists in MySQL; CREATE OR REPLACE is common to both."),
    ("Can a view be defined on another view?",
     ["Yes – views can be nested", "No – only on base tables", "Only if the view is materialized", "Only in NoSQL databases"], 0,
     "The DBMS expands the definitions recursively."),
    ("A stored procedure is:",
     ["A named set of SQL (and procedural) statements stored in the database and run on request", "A table that stores procedures of an office", "A backup file", "A type of index"], 0,
     PYQ + "It is compiled and stored on the server and run with CALL / EXEC."),
    ("Which is a key difference between a stored function and a stored procedure?",
     ["A function returns a single value and can be used inside SQL expressions; a procedure is invoked with CALL and returns values only through OUT parameters", "A procedure must return exactly one value", "A function cannot take parameters", "There is no difference"], 0,
     PYQ + "e.g. SELECT net_pay(emp_id) FROM emp; but CALL raise_salary(10);"),
    ("The three parameter modes of a stored procedure are:",
     ["IN, OUT and INOUT", "READ, WRITE and EXECUTE", "INPUT, PROCESS and OUTPUT", "LOCAL, GLOBAL and STATIC"], 0,
     "IN passes a value in, OUT returns a value, INOUT does both."),
    ("In MySQL, a stored procedure named update_stock is run by:",
     ["CALL update_stock();", "RUN update_stock;", "EXECUTE PROCEDURE update_stock;", "START update_stock();"], 0,
     "SQL Server uses EXEC; Oracle allows EXEC in SQL*Plus or a call inside a PL/SQL block."),
    ("Which is an advantage of stored procedures?",
     ["Less network traffic and controlled access – users can be granted EXECUTE without table privileges", "They make the database schema-less", "They remove the need for indexes", "They work only offline"], 0,
     "One call replaces many SQL statements sent over the network."),
    ("The sections of a PL/SQL block, in order, are:",
     ["DECLARE → BEGIN → EXCEPTION → END", "BEGIN → DECLARE → END → EXCEPTION", "EXCEPTION → DECLARE → BEGIN → END", "DECLARE → EXCEPTION → BEGIN → END"], 0,
     PYQ + "Only the BEGIN … END executable section is compulsory."),
    ("A scalar function differs from an aggregate function because a scalar function:",
     ["Returns one value for each row, e.g. UPPER(name)", "Returns one value for a whole group of rows, e.g. SUM(salary)", "Works only on numbers", "Cannot be used in SELECT"], 0,
     "COUNT, SUM, AVG, MIN and MAX are aggregates."),
    ("An index created with CREATE INDEX idx_name ON emp(name); mainly:",
     ["Speeds up searches on name, but makes inserts and updates slightly slower", "Sorts the table permanently on disk", "Prevents duplicate names", "Encrypts the name column"], 0,
     PYQ + "CREATE UNIQUE INDEX would also prevent duplicates."),
    ("Embedded SQL means:",
     ["SQL statements written inside a host-language program such as C or COBOL", "SQL stored inside an image", "A SQL query inside a view only", "SQL used only by the DBA"], 0,
     "Statements are marked with EXEC SQL and handled by a pre-compiler."),
    ("In embedded SQL, host-language variables used inside SQL statements are written with a prefix of:",
     ["A colon, e.g. :emp_no", "A hash, e.g. #emp_no", "A dollar, e.g. $emp_no", "An ampersand only"], 0,
     "The colon separates program variables from column names."),
    ("Dynamic SQL is used when:",
     ["The SQL statement is built and executed at run time", "Only fixed queries are allowed", "The database is read-only", "The table has no primary key"], 0,
     "e.g. PREPARE / EXECUTE, or EXECUTE IMMEDIATE in Oracle."),
    ("After CREATE VIEW high_paid AS SELECT name, salary FROM emp WHERE salary > 50000; the query SELECT COUNT(*) FROM high_paid; returns:",
     ["The number of employees earning more than 50000", "The number of all employees", "The total salary of all employees", "An error, because views cannot be counted"], 0,
     "Each query on the view is evaluated against the current emp rows."),
    ("Which privilege lets a user run a stored procedure without direct rights on the tables it uses (Oracle, MySQL definer's rights)?",
     ["EXECUTE", "SELECT", "INDEX", "REFERENCES"], 0,
     "Procedures run with the definer's privileges by default."),
    ("Match the database object with its description:\na. View  b. Materialized view  c. Stored procedure  d. Index\n1. Structure that speeds up lookups on a column  2. Named block of statements run with CALL  3. Query result stored and refreshed  4. Virtual table defined by a query",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Object-to-description matching is a common KEA format."),
    ("Consider the statements:\nI. A view can hide some columns of a table from a user.\nII. Every view can be updated.\nWhich is/are correct?",
     I_II, 0, "Views with joins, aggregates or DISTINCT are usually not updatable."),
    ("Consider the statements:\nI. A stored function can be called inside a SELECT statement.\nII. A stored procedure can return values through OUT parameters.\nWhich is/are correct?",
     I_II, 2, "Both are standard features."),
    ("Assertion (A): Views are useful for security.\nReason (R): A view can expose only selected rows and columns of a table to a user.",
     AR, 0, "Grant on the view instead of the base table."),
    ("Assertion (A): A materialized view always shows up-to-date data without any refresh.\nReason (R): A materialized view stores its query result physically.",
     AR, 3, "Because the result is stored, it can become stale until refreshed – so A is false."),
    ("Which of these SQL objects does NOT store any data rows of its own?",
     ["An ordinary view", "A table", "A materialized view", "A temporary table"], 0,
     "Only the view's definition is kept in the data dictionary."),
    ("A user-defined function that returns a whole table (usable in FROM) is called a:",
     ["Table-valued function", "Scalar function", "Aggregate function", "Trigger function"], 0,
     "Supported by SQL Server and PostgreSQL (RETURNS TABLE)."),
]

TRIGGERS_SEC = [
    # --- real previous-year question (official key) ---
    ("Match the following:\nList-1: a) Oracle instance  b) Tablespace  c) Trigger  d) Synonym\nList-2: i) A database structure that contains datafiles  ii) Automatically executes in response to certain events  iii) Provides alternate names for database objects  iv) A set of memory structures and background processes",
     ["a – iv, b – ii, c – i, d – iii", "a – iv, b – i, c – ii, d – iii", "a – i, b – iii, c – iv, d – ii", "a – ii, b – i, c – iii, d – iv"], 1,
     "An instance = SGA memory + background processes; a tablespace holds datafiles; a trigger fires on events; a synonym is an alias." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q76"),
    # --- new questions ---
    ("A trigger in SQL is:",
     ["A stored program that runs automatically when a specified event such as INSERT, UPDATE or DELETE occurs on a table", "A key that links two tables", "A command to start the database", "A type of view"], 0,
     PYQ + "Triggers are not called explicitly; the event fires them."),
    ("Active database rules (triggers) follow the model:",
     ["Event – Condition – Action (ECA)", "Entity – Constraint – Attribute", "Extract – Clean – Apply", "Execute – Commit – Abort"], 0,
     PYQ + "When the event occurs and the condition holds, the action runs."),
    ("A BEFORE trigger is typically used to:",
     ["Validate or adjust the new values before the change is written", "Write an audit record after the change is committed", "Back up the database", "Create indexes"], 0,
     "e.g. reject a negative salary or fill a default value."),
    ("A trigger declared FOR EACH ROW fires:",
     ["Once for every row affected by the statement", "Once per statement, however many rows change", "Only once per day", "Only when no row is affected"], 0,
     "Without FOR EACH ROW (Oracle) it is a statement-level trigger."),
    ("In a row-level DELETE trigger, which row values are available?",
     ["Only the OLD values", "Only the NEW values", "Both OLD and NEW", "Neither"], 0,
     "INSERT has only NEW; UPDATE has both; DELETE has only OLD."),
    ("INSTEAD OF triggers are mainly defined on:",
     ["Views, to make otherwise non-updatable views updatable", "Indexes", "Sequences", "Stored procedures"], 0,
     "The trigger body performs the change on the base tables."),
    ("A trigger that records every change of salary into an audit table is best written as:",
     ["An AFTER UPDATE … FOR EACH ROW trigger", "A BEFORE SELECT trigger", "A statement-level INSTEAD OF trigger on a table", "A DCL command"], 0,
     "AFTER ensures only successful changes are logged; row-level gives each old and new value."),
    ("The correct order of steps for using an explicit cursor in PL/SQL is:",
     ["DECLARE → OPEN → FETCH → CLOSE", "OPEN → DECLARE → CLOSE → FETCH", "FETCH → OPEN → DECLARE → CLOSE", "DECLARE → FETCH → OPEN → CLOSE"], 0,
     PYQ + "A cursor processes a multi-row result one row at a time."),
    ("The PL/SQL cursor attribute that becomes TRUE when the last FETCH returned no row is:",
     ["%NOTFOUND", "%FOUND", "%ISOPEN", "%ROWTYPE"], 0,
     "%ROWCOUNT gives the number of rows fetched so far."),
    ("In PL/SQL, the predefined exception raised when a SELECT … INTO returns no row is:",
     ["NO_DATA_FOUND", "TOO_MANY_ROWS", "ZERO_DIVIDE", "VALUE_ERROR"], 0,
     "TOO_MANY_ROWS is raised when it returns more than one row."),
    ("Which commands belong to DCL (Data Control Language)?",
     ["GRANT and REVOKE", "COMMIT and ROLLBACK", "INSERT and UPDATE", "CREATE and ALTER"], 0,
     PYQ + "COMMIT, ROLLBACK and SAVEPOINT are TCL commands."),
    ("GRANT SELECT ON emp TO ravi WITH GRANT OPTION; allows Ravi to:",
     ["Query emp and also grant SELECT on emp to other users", "Drop the emp table", "Only query emp; he cannot pass the right on", "Update every column of emp"], 0,
     "Revoking with CASCADE also removes the grants he made."),
    ("A role in SQL is:",
     ["A named group of privileges that can be granted to users", "A type of trigger", "A row in a table", "A backup schedule"], 0,
     "CREATE ROLE clerk; GRANT SELECT ON emp TO clerk; GRANT clerk TO ravi;"),
    ("SQL injection is an attack in which:",
     ["Malicious SQL is supplied through user input that the program joins directly into a query", "A virus damages the hard disk", "The database server is physically stolen", "A trigger is fired twice"], 0,
     PYQ + "OWASP lists injection among the most serious web risks."),
    ("A login form builds: SELECT * FROM users WHERE name='…' AND pwd='…'. Typing ' OR '1'='1 as the password typically:",
     ["Makes the WHERE condition always true and bypasses the password check", "Encrypts the password", "Deletes the users table", "Has no effect"], 0,
     PYQ + "The OR '1'='1' part is true for every row."),
    ("The most effective defence against SQL injection is to:",
     ["Use parameterized queries (prepared statements)", "Hide error messages only", "Use longer table names", "Store passwords in plain text"], 0,
     PYQ + "Input is then always treated as data, never as SQL code."),
    ("Which practice makes SQL injection MORE likely?",
     ["Concatenating user input directly into SQL strings", "Using prepared statements", "Validating input against an allow-list", "Giving the application account only the privileges it needs"], 0,
     "Dynamic string building is the root cause."),
    ("In many SQL injection attacks, the sequence -- is added to the input in order to:",
     ["Comment out the rest of the original query", "Join two tables", "Start a transaction", "Create a view"], 0,
     "Everything after -- on that line is ignored by the SQL parser."),
    ("Running the application's database account with only the privileges it needs is called:",
     ["The principle of least privilege", "Normalization", "Referential integrity", "Denormalization"], 0,
     "It limits the damage if an injection succeeds."),
    ("In the SQL standard, a constraint that may involve several tables and is declared with CREATE ASSERTION is a(n):",
     ["Assertion", "Trigger", "Cursor", "Synonym"], 0,
     "Few products implement assertions; triggers are often used instead."),
    ("Match the command with its effect:\na. GRANT  b. REVOKE  c. COMMIT  d. SAVEPOINT\n1. Marks a point to which a transaction can later roll back  2. Makes the transaction's changes permanent  3. Withdraws a privilege  4. Gives a privilege",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "DCL and TCL commands are often matched together."),
    ("Match the trigger type with its use:\na. BEFORE row trigger  b. AFTER row trigger  c. INSTEAD OF trigger  d. Statement-level trigger\n1. Fires once per statement  2. Replaces an INSERT/UPDATE/DELETE on a view  3. Writes audit records after each changed row  4. Checks or corrects each new row before it is saved",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     "Choose the timing by what the trigger must see or change."),
    ("Consider the statements:\nI. Triggers fire automatically when their event occurs.\nII. Triggers must be called explicitly with CALL.\nWhich is/are correct?",
     I_II, 0, "Stored procedures are called; triggers are fired."),
    ("Consider the statements:\nI. Prepared statements keep SQL code separate from user data.\nII. Escaping quotes in input is a stronger defence than prepared statements.\nWhich is/are correct?",
     I_II, 0, "OWASP ranks parameterized queries first; escaping is a last resort."),
    ("Assertion (A): Parameterized queries prevent SQL injection.\nReason (R): The user's input is sent to the database as data and is never parsed as SQL code.",
     AR, 0, "That separation is why they work."),
    ("Assertion (A): INSTEAD OF triggers are commonly used to make complex views updatable.\nReason (R): A trigger can never be defined on a view.",
     AR, 2, "INSTEAD OF triggers exist precisely for views, so R is false."),
    ("In Oracle, a 'mutating table' error usually occurs when:",
     ["A row-level trigger queries or modifies the same table whose change fired it", "A view is dropped", "An index is rebuilt", "A user logs out"], 0,
     "The table is in the middle of being changed by the triggering statement."),
    ("Which statement about triggers is TRUE?",
     ["Too many triggers can make a database slow and hard to debug, because they run hidden extra work on every change", "Triggers cannot contain SQL statements", "Triggers can be fired only by SELECT", "Triggers replace the need for primary keys"], 0,
     "Use them for auditing and rules that must always hold, not for ordinary application logic."),
    ("REVOKE UPDATE ON emp FROM ravi CASCADE; also:",
     ["Withdraws the UPDATE privilege from every user to whom Ravi had granted it", "Drops the emp table", "Deletes Ravi's account", "Commits Ravi's open transactions"], 0,
     "RESTRICT instead refuses the revoke if such dependent grants exist."),
]

FD_KEYS = [
    # --- real previous-year questions (official keys) ---
    ("Match the following.\nList-1: (a) Primary key  (b) Composite key  (c) Foreign key  (d) Super key\nList-2: i) multiple attributes  ii) subset of a candidate key  iii) uniquely identify  iv) corresponding value in other table",
     ["a – ii, b – iv, c – i, d – iii", "a – iv, b – iii, c – ii, d – i", "a – iii, b – i, c – ii, d – iv", "a – iii, b – i, c – iv, d – ii"], 3,
     "A primary key uniquely identifies rows; a composite key has several attributes; a foreign key refers to a value in another table. KEA matched 'super key' with 'subset of a candidate key' – strictly, a candidate key is a minimal subset of a super key." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q21"),
    ("Match the following abbreviated notation when discussing functional dependencies.\nList-1: a) If X ⊇ Y, then X → Y  b) {X → Y} ⊨ XZ → YZ  c) {X → Y, Y → Z} ⊨ X → Z  d) {X → Y, WY → Z} ⊨ WX → Z\nList-2: i) Augmentation rule  ii) Transitive rule  iii) Reflexive rule  iv) Pseudo transitive rule",
     ["a – iii, b – i, c – ii, d – iv", "a – iv, b – iii, c – i, d – ii", "a – ii, b – iv, c – iii, d – i", "a – i, b – ii, c – iv, d – iii"], 0,
     "Elmasri & Navathe's inference rules IR1 (reflexive), IR2 (augmentation), IR3 (transitive) and IR6 (pseudotransitive). The printed '≠' is the 'implies' sign ⊨." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q85"),
    # --- new questions ---
    ("A functional dependency X → Y holds on relation R when:",
     ["Any two tuples that agree on X also agree on Y", "X and Y have the same data type", "Y is a foreign key referring to X", "X has more attributes than Y"], 0,
     PYQ + "X determines Y."),
    ("Which functional dependency is trivial?",
     ["AB → A", "A → B", "AB → C", "A → BC"], 0,
     "X → Y is trivial when Y ⊆ X."),
    ("Armstrong's axioms are:",
     ["Reflexivity, augmentation and transitivity", "Union, decomposition and projection", "Atomicity, consistency and durability", "Selection, projection and join"], 0,
     PYQ + "They are sound and complete; union, decomposition and pseudotransitivity are derived from them."),
    ("If X → Y and X → Z hold, then X → YZ holds. This rule is called:",
     ["Union (additive) rule", "Decomposition rule", "Augmentation", "Reflexivity"], 0,
     "Decomposition is the reverse: X → YZ gives X → Y and X → Z."),
    ("R(A, B, C, D) has F = {A → B, B → C, C → D}. The closure A⁺ is:",
     ["ABCD", "AB", "ABC", "A"], 0,
     PYQ + "A → B → C → D by transitivity."),
    ("R(A, B, C, D, E) has F = {A → B, BC → D, D → E}. The closure {A, C}⁺ is:",
     ["ABCDE", "ABC", "ACD", "ABCD"], 0,
     "AC gives B (A → B), then D (BC → D), then E (D → E)."),
    ("R(A, B, C, D) has F = {A → B, B → C, C → D}. The candidate key of R is:",
     ["A", "B", "AB", "CD"], 0,
     PYQ + "A⁺ = ABCD and A is not derivable from any other attribute."),
    ("R(A, B, C, D) has F = {AB → C, C → D, D → A}. Its candidate keys are:",
     ["AB, BC and BD", "AB only", "AB and CD", "A and B"], 0,
     PYQ + "B is never on a right side, so it is in every key; B with A, C or D determines everything."),
    ("R(A, B, C, D) has exactly one candidate key, A. How many superkeys does R have?",
     ["8", "4", "16", "1"], 0,
     PYQ + "A plus any subset of {B, C, D}: 2³ = 8."),
    ("R(A, B, C, D) has F = {A → B, B → A, C → D}. How many candidate keys does R have?",
     ["2", "1", "3", "4"], 0,
     "AC and BC (C is needed for C and D; A and B determine each other)."),
    ("A prime attribute is an attribute that:",
     ["Belongs to at least one candidate key", "Has a numeric data type", "Is a foreign key", "Is never NULL"], 0,
     "Non-prime attributes belong to no candidate key; 2NF and 3NF are stated in these terms."),
    ("A candidate key is:",
     ["A minimal superkey – no proper subset of it is a superkey", "Any set of attributes containing the primary key", "A key of another table", "Any attribute with unique values in today's data only"], 0,
     "Every candidate key is a superkey, not the other way round."),
    ("A minimal (canonical) cover of a set of FDs has:",
     ["Single attributes on the right, no extraneous attributes on the left and no redundant FDs", "All FDs of the closure F⁺", "Only trivial FDs", "FDs whose left sides are always candidate keys"], 0,
     "It is the starting point of the 3NF synthesis algorithm."),
    ("A minimal cover of F = {A → BC, B → C, A → B, AB → C} is:",
     ["{A → B, B → C}", "{A → BC, B → C}", "{A → B, AB → C}", "{A → C, B → C}"], 0,
     "A → C follows from A → B and B → C; AB → C is implied by B → C."),
    ("In F = {A → C, AB → C}, which attribute is extraneous in AB → C?",
     ["B", "A", "C", "None"], 0,
     "A alone already determines C."),
    ("Y is fully functionally dependent on X when:",
     ["X → Y holds and Y does not depend on any proper subset of X", "X → Y holds for some rows only", "Y → X also holds", "X is a single attribute"], 0,
     "If Y depends on part of X, the dependency is partial."),
    ("A partial dependency is one in which:",
     ["A non-prime attribute depends on only part of a composite candidate key", "A key attribute depends on a non-key attribute", "Two keys depend on each other", "An attribute depends on itself"], 0,
     PYQ + "Removing partial dependencies gives 2NF."),
    ("A transitive dependency X → Z exists when:",
     ["X → Y and Y → Z hold, Y is not a candidate key (or superkey) and Z is non-prime", "Z is part of the key", "X and Z are equal", "Z → X holds"], 0,
     "Removing transitive dependencies gives 3NF."),
    ("A multivalued dependency is written as:",
     ["X →→ Y", "X → Y", "X ⊨ Y", "X ⋈ Y"], 0,
     "MVDs are the basis of 4NF."),
    ("A binary decomposition of R into R1 and R2 is lossless if:",
     ["R1 ∩ R2 → R1 or R1 ∩ R2 → R2 is in F⁺", "R1 ∪ R2 ≠ R", "R1 and R2 have no common attribute", "R1 and R2 have the same number of attributes"], 0,
     PYQ + "The common attributes must be a superkey of one of the parts."),
    ("R(A, B, C) has F = {A → B}. The decomposition R1(A, B), R2(A, C) is:",
     ["Lossless, because A → AB", "Lossy, because C is not in R1", "Lossless only if C → A", "Not a valid decomposition"], 0,
     "R1 ∩ R2 = A, and A is a key of R1."),
    ("A decomposition is dependency-preserving when:",
     ["The FDs holding on the individual parts together imply all FDs of F", "Every part has the same key", "No attribute is repeated", "It is always lossless"], 0,
     "Then constraints can be checked without joining the parts."),
    ("Match the inference rule with its form:\na. Decomposition  b. Pseudotransitivity  c. Union  d. Reflexivity\n1. Y ⊆ X ⊨ X → Y  2. X → Y, X → Z ⊨ X → YZ  3. X → Y, WY → Z ⊨ WX → Z  4. X → YZ ⊨ X → Y",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Inference-rule matching appears in Legislative Council and KSET papers."),
    ("Consider the statements:\nI. Every candidate key is a superkey.\nII. Every superkey is a candidate key.\nWhich is/are correct?",
     I_II, 0, "A superkey need not be minimal."),
    ("Consider the statements:\nI. Armstrong's axioms are sound (they derive only valid FDs).\nII. Armstrong's axioms are complete (they derive every implied FD).\nWhich is/are correct?",
     I_II, 2, "Both properties were proved by Armstrong (1974)."),
    ("Assertion (A): In R(A, B, C) with A → B and B → C, A is a candidate key.\nReason (R): A⁺ contains all attributes of R.",
     AR, 0, "A⁺ = ABC, and a single attribute is minimal."),
    ("Assertion (A): AB → A is a non-trivial functional dependency.\nReason (R): An FD X → Y is trivial when Y ⊆ X.",
     AR, 3, "A ⊆ AB, so AB → A is trivial; A is false."),
    ("The closure F⁺ of a set of functional dependencies F is:",
     ["The set of all FDs that can be inferred from F", "The set of all candidate keys", "The smallest set of FDs equivalent to F", "The set of attributes determined by a key"], 0,
     "The smallest equivalent set is a minimal cover; X⁺ is the closure of an attribute set."),
]

NORMAL_FORMS = [
    # --- real previous-year questions (official keys) ---
    ("Match the following.\nList-1: (a) 1 NF  (b) 2 NF  (c) 3 NF  (d) BCNF\nList-2: i) Is a strict form of 3 NF  ii) Contains atomic values  iii) No non-prime attributes  iv) Non-transitively depends on primary key",
     ["a – iii, b – iv, c – ii, d – i", "a – ii, b – iii, c – iv, d – i", "a – iv, b – i, c – iii, d – ii", "a – ii, b – iv, c – i, d – iii"], 1,
     "1NF – atomic values; 3NF – non-key attributes depend non-transitively on the key; BCNF – a stricter 3NF. KEA's key pairs 2NF with item iii (read it as: no non-prime attribute depends on part of a key)." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q22"),
    ("If every non-key attribute is functionally dependent on the primary key, then the relation will be",
     ["First normal form", "Second normal form", "Third normal form", "Fourth normal form"], 2,
     "KEA's key takes this as the 3NF idea 'every non-key attribute depends on the key, the whole key and nothing but the key'." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q34"),
    ("Match the following normalization form of database based on the primary keys.\nList-1: a) Relation should have no multivalued attributes  b) Primary key contains multiple attributes  c) Relation should not have a non-key attribute functionally determined by another non-key  d) Simpler form of 3NF\nList-2: i) Second normal form  ii) Boyce-Codd normal form  iii) First normal form  iv) Third normal form",
     ["a – i, b – ii, c – iii, d – iv", "a – ii, b – iii, c – iv, d – i", "a – iii, b – i, c – iv, d – ii", "a – ii, b – iv, c – i, d – iii"], 2,
     "No multivalued attributes → 1NF; composite keys matter for 2NF; non-key → non-key forbidden in 3NF; BCNF is the 'simpler, stronger' form of 3NF (Elmasri & Navathe's wording)." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q86"),
    ("Match the following informal design guideline statements for relation schemas.\nList-1: a) Update anomalies  b) Insertion anomalies  c) Insert new tuple in employee table has no employee as yet in relation  d) Modification anomalies\nList-2: i) Enter all attribute values to insert a new tuple  ii) Place NULL values in the table  iii) Change the value of one of the attributes of a particular tuple  iv) Storing natural join of base relation leads to additional problem",
     ["a – i, b – iv, c – iii, d – ii", "a – ii, b – iii, c – iv, d – i", "a – iii, b – ii, c – i, d – iv", "a – iv, b – i, c – ii, d – iii"], 3,
     "Elmasri & Navathe: storing a natural join causes update anomalies; insertion anomalies force entering all attribute values (or NULLs for a department with no employee yet); modification anomalies mean changing a value in many tuples." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q87"),
    ("Match the following based on their normalization of relations\na. First Normal Form  b. Second Normal Form  c. Third Normal Form  d. BCNF\ni. Non-trivial functional dependency  ii. Stronger form of 3NF  iii. Single atomic value  iv. Full functional dependency",
     ["a – i, b – ii, c – iii, d – iv", "a – iii, b – iv, c – i, d – ii", "a – iii, b – iv, c – ii, d – i", "a – iii, b – i, c – ii, d – iv"], 1,
     "1NF – atomic values; 2NF – full functional dependency on the key; 3NF – conditions on non-trivial FDs; BCNF – stronger form of 3NF." + GTTC,
     "GTTC 2024 Lecturer CS · Q65"),
    ("____ eliminates relations between candidate keys.",
     ["First Normal Form", "Second Normal Form", "Third Normal Form", "Boyce-Codd Normal Form"], 3,
     "BCNF removes the anomalies 3NF allows when candidate keys overlap: every determinant must be a candidate key." + NOTE,
     "KSET 2025 CS&A · Q34"),
    ("Match the following:\na. BCNF iff\nb. 5 NF iff\nc. 1 NF iff\nd. 4 NF iff\n(i) every JD is implied by the candidate keys\n(ii) every MVD is implied by the candidate keys\n(iii) all underlying domains contain scalar values only\n(iv) every FD is implied by the candidate keys",
     ["a – iii, b – ii, c – i, d – iv", "a – iv, b – i, c – ii, d – iii", "a – iv, b – i, c – iii, d – ii", "a – iv, b – iii, c – ii, d – i"], 2,
     "BCNF: FDs; 4NF: MVDs; 5NF: JDs; 1NF: atomic domains." + NOTE,
     "KSET 2025 CS&A · Q36"),
    ("Match the following normal forms in List-I with their defining conditions mentioned in the List-II.\n(a) 1 NF\n(b) 2 NF\n(c) 3 NF\n(d) BCNF\n(i) No transitive dependency\n(ii) No partial dependency\n(iii) Atomic values only\n(iv) Every determinant is a candidate key",
     ["a – ii, b – iii, c – iv, d – i", "a – iii, b – ii, c – i, d – iv", "a – iv, b – iii, c – ii, d – i", "a – i, b – iv, c – iii, d – ii"], 1,
     "1NF atomic values, 2NF no partial dependency, 3NF no transitive dependency, BCNF every determinant a candidate key." + NOTE,
     "KEA 2026 CS Paper-2 · Q58"),
    # --- new questions ---
    ("The main purpose of normalization is to:",
     ["Reduce redundancy and avoid insertion, deletion and update anomalies", "Make every query faster", "Encrypt the data", "Increase the number of tables for its own sake"], 0,
     PYQ + "Normalization is a schema-design process based on dependencies."),
    ("In EMP_DEPT(Eno, Ename, Dno, Dname), a new department with no employees cannot be recorded. This is a(n):",
     ["Insertion anomaly", "Deletion anomaly", "Update anomaly", "Join anomaly"], 0,
     "Eno is part of the key, so it cannot be NULL."),
    ("In EMP_DEPT(Eno, Ename, Dno, Dname), deleting the last employee of a department also loses the department's name. This is a(n):",
     ["Deletion anomaly", "Insertion anomaly", "Update anomaly", "Integrity anomaly"], 0,
     "Unrelated facts are stored in one row."),
    ("A relation is in 1NF when:",
     ["Every attribute holds only atomic (indivisible) values – no repeating groups or multivalued attributes", "It has no partial dependencies", "It has no transitive dependencies", "Every determinant is a key"], 0,
     PYQ + "1NF is the basic requirement of the relational model."),
    ("A relation is in 2NF when it is in 1NF and:",
     ["No non-prime attribute is partially dependent on any candidate key", "No attribute is transitively dependent on the key", "Every determinant is a candidate key", "It has no multivalued dependencies"], 0,
     PYQ + "Partial dependencies can exist only when a candidate key is composite."),
    ("A relation in 1NF whose candidate keys are all single attributes is automatically in:",
     ["2NF", "BCNF", "4NF", "5NF"], 0,
     PYQ + "No proper subset of a single-attribute key exists, so no partial dependency is possible."),
    ("A relation is in 3NF when, for every non-trivial FD X → A:",
     ["X is a superkey or A is a prime attribute", "X is a superkey", "A is part of X", "X is a single attribute"], 0,
     "Dropping 'or A is prime' gives the BCNF condition."),
    ("A relation is in BCNF when, for every non-trivial FD X → Y:",
     ["X is a superkey", "Y is a prime attribute", "X is a foreign key", "Y is a superkey"], 0,
     PYQ + "Every determinant must be a (super)key."),
    ("Any relation with exactly two attributes is always in:",
     ["BCNF", "1NF only", "2NF but not 3NF", "No normal form"], 0,
     PYQ + "Any non-trivial FD has a single attribute on the left, which is then a key."),
    ("Which statement about decomposition is TRUE?",
     ["A lossless, dependency-preserving 3NF decomposition always exists, but a BCNF decomposition may lose dependencies", "BCNF decomposition always preserves dependencies", "3NF decomposition may be lossy", "Neither can ever be lossless"], 0,
     PYQ + "This is why 3NF is often accepted in practice."),
    ("4NF and 5NF deal respectively with:",
     ["Multivalued dependencies and join dependencies", "Partial and transitive dependencies", "Atomic values and keys", "Foreign keys and indexes"], 0,
     "5NF is also called project-join normal form (PJNF)."),
    ("R(A, B, C, D) has key AB and F = {AB → C, B → D}. The highest normal form of R is:",
     ["1NF", "2NF", "3NF", "BCNF"], 0,
     PYQ + "B → D is a partial dependency of the non-prime D on part of the key."),
    ("R(A, B, C) has key A and F = {A → B, B → C}. The highest normal form of R is:",
     ["2NF", "1NF", "3NF", "BCNF"], 0,
     "No partial dependency (single-attribute key), but A → B → C is transitive."),
    ("R(A, B, C) has F = {AB → C, C → B}. Its candidate keys are AB and AC. R is in:",
     ["3NF but not BCNF", "BCNF", "2NF but not 3NF", "1NF only"], 0,
     PYQ + "B is prime, so C → B satisfies 3NF; C is not a superkey, so BCNF fails."),
    ("Denormalization means:",
     ["Deliberately adding some redundancy to a normalized design to speed up frequent queries", "Removing all keys", "Converting a table to 1NF", "Deleting duplicate rows"], 0,
     "Common in data warehouses and reporting tables."),
    ("The correct order of normal forms from least to most strict is:",
     ["1NF → 2NF → 3NF → BCNF → 4NF → 5NF", "1NF → 3NF → 2NF → BCNF → 4NF → 5NF", "2NF → 1NF → 3NF → 4NF → BCNF → 5NF", "1NF → 2NF → BCNF → 3NF → 5NF → 4NF"], 0,
     "Each higher form implies the lower ones."),
    ("Consider the statements:\nI. Every relation in 3NF is in BCNF.\nII. Every relation in BCNF is in 3NF.\nWhich is/are correct?",
     I_II, 1, "BCNF is stricter than 3NF."),
    ("Consider the statements:\nI. Normalization reduces data redundancy.\nII. Normalization always makes every query faster.\nWhich is/are correct?",
     I_II, 0, "More tables can mean more joins, so some queries get slower."),
    ("Assertion (A): A relation in 2NF can still have update anomalies.\nReason (R): 2NF does not remove transitive dependencies.",
     AR, 0, "3NF is needed for that."),
    ("Match the problem with its description:\na. Insertion anomaly  b. Deletion anomaly  c. Update anomaly  d. Redundancy\n1. The same fact is stored in many rows  2. Changing one fact needs many row changes, or data becomes inconsistent  3. Removing a row loses an unrelated fact  4. A fact cannot be stored without some other fact",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Anomaly matching questions are common in KEA papers."),
    ("Which dependency must be removed to bring a 2NF relation to 3NF?",
     ["Transitive dependency of a non-prime attribute on a key", "Partial dependency", "Multivalued dependency", "Join dependency"], 0,
     "Split R(A, B, C) with A → B → C into R1(A, B) and R2(B, C)."),
    ("STUDENT(Roll, Name, Phones) stores several phone numbers in one Phones field. Which normal form does it violate?",
     ["1NF", "2NF only", "3NF only", "BCNF only"], 0,
     "A multivalued attribute is not atomic; move phones to STUDENT_PHONE(Roll, Phone)."),
]

TOPICS = {
    "SQL – Part 2": [("1 · Views, Stored Procedures and Functions", VIEWS_PROC),
                     ("2 · Triggers, Cursors, Privileges and SQL Injection", TRIGGERS_SEC)],
    "Normalization": [("1 · Functional Dependencies, Closure and Keys", FD_KEYS),
                      ("2 · Anomalies and Normal Forms (1NF–BCNF and beyond)", NORMAL_FORMS)],
}
