"""Paper 2 · Unit 5 · P2-U5-07 Query Processing and Optimization (1 set × 30) and P2-U5-08 Transactions & Concurrency
Control (2 sub-topics × 30).
References: Silberschatz, Korth & Sudarshan, Database System Concepts (chs. 15–18); Elmasri & Navathe, Fundamentals of
Database Systems (chs. 18–21); ISO SQL isolation levels.
Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question number)
with new questions. Official answers come from KEA's final keys for the Karnataka Legislative Council Secretariat 2024
exams (Computer Operator P2, Sr/Jr Programmer P2 – booklet A1; final key 09-04-2025). KSET 2023 and KEA 2026 questions
are reused from packs/pyq-p2.json (answers worked out by ExamSim). Obvious printing typos are corrected."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

QUERY = [
    # --- real previous-year question (official key) ---
    ("Which of the following is the correct sequence of operations in query processing?",
     ["Parsing and translation → Optimization → Evaluation", "Optimization → Parsing and translation → Evaluation", "Evaluation → Parsing and translation → Optimization", "Parsing and translation → Evaluation → Optimization"], 0,
     "The query is parsed and translated to relational algebra, the optimizer picks a plan, and the evaluation engine runs it." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q26"),
    # --- new questions ---
    ("During query processing, an SQL query is first translated into:",
     ["An internal form such as a relational-algebra expression (query tree)", "Machine code", "A B+ tree", "A transaction log"], 0,
     PYQ + "The parser also checks syntax and verifies relation names."),
    ("A query-evaluation plan is:",
     ["A relational-algebra expression annotated with the algorithm and access path for each operation", "The SQL text typed by the user", "A backup schedule", "The ER diagram of the database"], 0,
     "e.g. 'use the index on dept_id, then a hash join'."),
    ("The query optimizer chooses:",
     ["The evaluation plan with the lowest estimated cost", "The first plan it generates", "The plan with the most joins", "A plan at random"], 0,
     PYQ + "It cannot always find the true optimum, but avoids very bad plans."),
    ("In disk-based systems, the cost of a query plan is usually measured mainly by:",
     ["The number of disk block transfers and seeks", "The number of SQL keywords", "The number of users logged in", "The length of table names"], 0,
     "Disk access dominates CPU cost."),
    ("The most important heuristic in query optimization is to:",
     ["Perform selection operations as early as possible", "Perform Cartesian products first", "Sort every relation before any operation", "Delay all projections until the end"], 0,
     PYQ + "Selections shrink intermediate results; projections are also pushed down."),
    ("A Cartesian product followed by a selection on the join condition should be replaced by:",
     ["A join operation", "A union", "A projection", "A division"], 0,
     "σθ(r × s) = r ⋈θ s, which is far cheaper to evaluate."),
    ("Cost-based optimization differs from purely heuristic optimization because it:",
     ["Uses catalog statistics (number of tuples, distinct values, blocks) to estimate the cost of alternative plans", "Never uses indexes", "Always performs joins first", "Ignores the size of relations"], 0,
     "Heuristics are rules of thumb; cost-based optimizers compare estimates."),
    ("For a linear (sequential) search on a relation stored in b blocks, the worst-case cost is:",
     ["b block transfers", "log₂ b block transfers", "1 block transfer", "b² block transfers"], 0,
     "For an equality on a key, the average is b/2, since the scan can stop at the match."),
    ("A binary search for an equality condition on the ordering key of a sorted file of b blocks costs about:",
     ["⌈log₂ b⌉ block transfers", "b block transfers", "b/2 block transfers", "1 block transfer always"], 0,
     PYQ + "Requires the file to be sorted on that attribute."),
    ("Which join algorithm can be used only for equi-joins and natural joins?",
     ["Hash join", "Nested-loop join", "Block nested-loop join", "All of these work for every join condition"], 0,
     PYQ + "Merge join also needs equality (or ordering) conditions; nested loops work for any condition."),
    ("For a simple nested-loop join of r (outer, n_r tuples, b_r blocks) and s (b_s blocks), the worst-case number of block transfers is:",
     ["n_r × b_s + b_r", "b_r + b_s", "b_r × b_s", "n_r + n_s"], 0,
     "Each outer tuple scans the whole inner relation."),
    ("For block nested-loop join, the worst-case number of block transfers is:",
     ["b_r × b_s + b_r", "n_r × b_s + b_r", "b_r + b_s", "log b_r + log b_s"], 0,
     "Each block of the outer relation is paired with every block of the inner relation."),
    ("In a block nested-loop join, which relation should normally be chosen as the outer relation?",
     ["The smaller relation", "The larger relation", "The one without an index", "It never matters"], 0,
     "The b_r term is then smallest."),
    ("Sorting a relation that does not fit in main memory is done with:",
     ["External sort-merge", "Bubble sort", "Binary search", "Hashing on the primary key"], 0,
     PYQ + "Sorted runs are created and then merged in passes."),
    ("Pipelining in query evaluation means:",
     ["Passing tuples from one operation directly to the next without writing temporary relations to disk", "Running every operation twice", "Storing every intermediate result on disk", "Executing queries one user at a time"], 0,
     "Materialization writes each intermediate result to disk."),
    ("Which equivalence rule states that selections can be applied in any order?",
     ["σθ1(σθ2(E)) = σθ2(σθ1(E))", "πL1(πL2(E)) = πL2(E)", "E1 ⋈ E2 = E1 ∪ E2", "σθ(E1 − E2) = E1"], 0,
     "Selection is commutative."),
    ("The cascade-of-selection rule is:",
     ["σθ1∧θ2(E) = σθ1(σθ2(E))", "σθ1∨θ2(E) = σθ1(E) − σθ2(E)", "σθ(E1 × E2) = E1", "πA(σθ(E)) = σθ(E)"], 0,
     "A conjunctive selection can be split into a sequence of selections."),
    ("Natural join being commutative and associative mainly allows the optimizer to:",
     ["Choose the best join order", "Remove all joins", "Avoid using indexes", "Convert joins into unions"], 0,
     "Join ordering is the most important optimization for multi-table queries."),
    ("For n relations, the number of possible join orders:",
     ["Grows faster than exponentially, so optimizers use dynamic programming and heuristics", "Is always n", "Is always 2", "Does not depend on n"], 0,
     PYQ + "System R introduced dynamic programming over left-deep join trees."),
    ("In a left-deep join tree:",
     ["The right input of every join is a base relation", "Every join has two intermediate results as inputs", "No join is performed", "Only Cartesian products are used"], 0,
     "Left-deep plans work well with pipelining and index nested-loop joins."),
    ("Which SQL command displays the execution plan chosen for a query in MySQL and PostgreSQL?",
     ["EXPLAIN", "DESCRIBE TABLE", "SHOW USERS", "COMMIT"], 0,
     "Oracle uses EXPLAIN PLAN FOR …"),
    ("For a selection σA=v(r), with n_r tuples and V(A, r) distinct values of A (uniform distribution), the estimated result size is:",
     ["n_r / V(A, r)", "n_r × V(A, r)", "V(A, r)", "n_r − V(A, r)"], 0,
     PYQ + "Selectivity estimates come from catalog statistics."),
    ("For the range query salary BETWEEN 30000 AND 50000, the most useful index is a:",
     ["B+ tree index on salary", "Hash index on salary", "Bitmap index on gender", "No index can help range queries"], 0,
     "Hash indexes support only equality lookups."),
    ("Projection should be applied early in a query tree mainly to:",
     ["Remove unneeded attributes and make intermediate tuples smaller", "Add more attributes", "Increase the number of tuples", "Avoid using selections"], 0,
     "Smaller tuples mean fewer blocks to move."),
    ("Match the component with its role:\na. Parser  b. Optimizer  c. Evaluation engine  d. System catalog\n1. Stores statistics used for cost estimates  2. Executes the chosen plan  3. Picks the cheapest plan  4. Checks syntax and translates the query",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Component-role matching is a favourite KEA format."),
    ("Consider the statements:\nI. Selections should be pushed as far down the query tree as possible.\nII. Cartesian products should be performed as early as possible.\nWhich is/are correct?",
     I_II, 0, "Cartesian products create huge intermediate results; they are avoided or delayed."),
    ("Assertion (A): Hash join cannot be used for a non-equi join such as r.A < s.B.\nReason (R): Hashing places only equal values in the same bucket.",
     AR, 0, "Values satisfying '<' may fall in any bucket."),
    ("Assertion (A): Query optimization is needed.\nReason (R): One SQL query can have many equivalent evaluation plans whose costs differ greatly.",
     AR, 0, "Choosing well can save orders of magnitude in time."),
    ("Which join method is especially efficient when both relations are already sorted on the join attribute?",
     ["Merge join (sort-merge join)", "Simple nested-loop join", "Cartesian product", "Block nested-loop join with the larger relation outer"], 0,
     "Each relation is then read only once."),
]

TRANSACTIONS = [
    # --- real previous-year questions ---
    ("Which one of the following is not a desirable property of transaction?",
     ["Atomicity", "Consistency", "Durability", "Normalization"], 3,
     "The ACID properties are Atomicity, Consistency, Isolation and Durability; normalization is a schema-design process." + NOTE,
     "KSET 2023 CS&A · Q14"),
    ("Which of the following is the correct sequence in transaction commands?",
     ["Savepoint → Rollback → Commit → Begin transaction", "Begin transaction → Commit → Rollback → Savepoint", "Rollback → Commit → Savepoint → Begin transaction", "Commit → Savepoint → Begin transaction → Rollback"], 1,
     "A transaction starts with BEGIN TRANSACTION; KEA's key takes option 2 as the order in which the commands are listed and used." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q27"),
    # --- new questions ---
    ("A transaction runs UPDATE emp SET sal = sal + 100; then ROLLBACK; (autocommit off). The salaries are:",
     ["Back to their values before the UPDATE", "Increased by 100 permanently", "Increased by 200", "Set to NULL"], 0,
     PYQ + "ROLLBACK undoes every change not yet committed (a Legislative Council 2024 paper asked a DELETE / ROLLBACK version)."),
    ("A transaction is:",
     ["A logical unit of database work that must be executed completely or not at all", "A single SQL keyword", "A table that stores sales", "A type of index"], 0,
     "e.g. transferring money: debit one account and credit another."),
    ("ACID stands for:",
     ["Atomicity, Consistency, Isolation, Durability", "Accuracy, Consistency, Integrity, Durability", "Atomicity, Concurrency, Integrity, Dependency", "Availability, Consistency, Isolation, Distribution"], 0,
     PYQ + "The four properties every transaction should have."),
    ("Which ACID property is mainly ensured by the concurrency-control manager?",
     ["Isolation", "Durability", "Atomicity", "Consistency"], 0,
     PYQ + "Concurrent transactions must not interfere with one another."),
    ("Atomicity and durability are mainly ensured by the:",
     ["Recovery manager (using the log)", "Query optimizer", "Application programmer alone", "Network administrator"], 0,
     "Undo gives atomicity; redo of committed work gives durability."),
    ("Ensuring that a correct transaction run alone keeps the database consistent is mainly the responsibility of the:",
     ["Application programmer (helped by integrity constraints)", "Recovery manager", "Buffer manager", "Operating system"], 0,
     "The DBMS cannot know the meaning of every business rule."),
    ("The normal sequence of states of a transaction that completes successfully is:",
     ["Active → Partially committed → Committed", "Active → Failed → Committed", "Partially committed → Active → Committed", "Active → Aborted → Committed"], 0,
     PYQ + "A failed transaction goes Active/Partially committed → Failed → Aborted."),
    ("After a transaction is aborted and rolled back, the system can:",
     ["Restart it (if the failure was not due to its own logic) or kill it", "Only commit it", "Only make its changes permanent", "Delete the database"], 0,
     "Silberschatz: an aborted transaction may be restarted as a new transaction or killed."),
    ("A schedule of concurrent transactions is:",
     ["The chronological order in which the operations of the transactions are executed", "The timetable of the DBA", "The order of tables in a database", "A list of users"], 0,
     "It preserves the order of operations within each transaction."),
    ("A schedule is called serializable if:",
     ["It is equivalent to some serial schedule", "It runs transactions one after another only", "It never commits", "It contains only read operations"], 0,
     "Serializability is the usual correctness criterion for concurrency."),
    ("Two operations in a schedule conflict when they:",
     ["Belong to different transactions, access the same data item, and at least one of them is a write", "Belong to the same transaction", "Access different data items", "Are both reads"], 0,
     PYQ + "Conflicting pairs: R–W, W–R and W–W on the same item."),
    ("Which pair of operations does NOT conflict?",
     ["R1(X) and R2(X)", "R1(X) and W2(X)", "W1(X) and R2(X)", "W1(X) and W2(X)"], 0,
     "Two reads never conflict."),
    ("Conflict serializability of a schedule is tested by:",
     ["Checking that its precedence graph has no cycle", "Counting its write operations", "Checking that it has only one transaction", "Running it twice"], 0,
     PYQ + "An edge Ti → Tj is drawn for each conflicting pair where Ti's operation comes first."),
    ("Is the schedule R1(X), R2(X), W1(X), W2(X) conflict serializable?",
     ["No – its precedence graph has the cycle T1 → T2 → T1", "Yes – it is equivalent to T1, T2", "Yes – it is equivalent to T2, T1", "Yes – there are no conflicts"], 0,
     PYQ + "R1(X) before W2(X) gives T1 → T2; R2(X) before W1(X) gives T2 → T1."),
    ("How many different serial schedules are possible for 3 transactions?",
     ["6", "3", "9", "1"], 0,
     PYQ + "n transactions can be ordered in n! ways."),
    ("A schedule that is view serializable but not conflict serializable must contain:",
     ["Blind writes (writes without a preceding read of the item)", "Only reads", "No writes at all", "Exactly one transaction"], 0,
     "Every conflict-serializable schedule is view serializable, not the other way round."),
    ("A schedule is recoverable if:",
     ["Whenever Tj reads an item written by Ti, Ti commits before Tj commits", "No transaction ever aborts", "All transactions commit at the same time", "Each transaction reads only its own writes"], 0,
     PYQ + "Otherwise a committed Tj may depend on an aborted Ti."),
    ("A cascadeless schedule is one in which:",
     ["Transactions read only data written by committed transactions", "No transaction writes", "Every abort causes more aborts", "There are no reads"], 0,
     "It avoids cascading rollbacks."),
    ("In the 'lost update' problem:",
     ["Two transactions update the same item and one update overwrites the other", "A transaction reads uncommitted data", "New rows appear in a repeated query", "A transaction never commits"], 0,
     PYQ + "Classic concurrency problems: lost update, dirty read, unrepeatable read, phantom."),
    ("The SQL isolation level that prevents dirty reads, unrepeatable reads and phantoms is:",
     ["SERIALIZABLE", "READ UNCOMMITTED", "READ COMMITTED", "REPEATABLE READ"], 0,
     "REPEATABLE READ (standard) still allows phantoms."),
    ("Match the problem with its description:\na. Lost update  b. Dirty read  c. Unrepeatable read  d. Phantom\n1. New rows satisfying a condition appear when the query is repeated  2. Reading the same item twice gives different values  3. Reading a value that is later rolled back  4. One update is overwritten by another",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Concurrency anomalies are often matched in KSET papers."),
    ("Consider the statements:\nI. Every cascadeless schedule is recoverable.\nII. Every recoverable schedule is cascadeless.\nWhich is/are correct?",
     I_II, 0, "Recoverable schedules may still have cascading rollbacks."),
    ("Consider the statements:\nI. Every conflict-serializable schedule is view serializable.\nII. Every serial schedule is conflict serializable.\nWhich is/are correct?",
     I_II, 2, "A serial schedule is trivially equivalent to itself."),
    ("Assertion (A): A transaction must either complete all its operations or none of them.\nReason (R): This is the atomicity property of transactions.",
     AR, 0, "Partial effects are undone using the log."),
    ("Assertion (A): Once a transaction commits, its changes survive later system crashes.\nReason (R): Committed changes are recorded in the log on stable storage before the commit is acknowledged.",
     AR, 0, "This is durability, achieved by write-ahead logging."),
    ("The statement that makes all changes of the current transaction permanent is:",
     ["COMMIT", "ROLLBACK", "SAVEPOINT", "GRANT"], 0,
     "ROLLBACK undoes them; SAVEPOINT marks a point for a partial rollback."),
    ("ROLLBACK TO SAVEPOINT s1; does what?",
     ["Undoes the changes made after savepoint s1 while keeping the transaction active", "Undoes the whole database", "Commits all changes", "Deletes savepoint s1 and commits"], 0,
     "Changes made before s1 remain pending until COMMIT or ROLLBACK."),
    ("In MySQL with autocommit ON (the default), each individual SQL statement is:",
     ["Committed automatically as soon as it finishes", "Never committed", "Rolled back at logout", "Saved only after a SAVEPOINT"], 0,
     "START TRANSACTION turns autocommit off until COMMIT or ROLLBACK."),
]

CONCURRENCY = [
    # --- real previous-year questions ---
    ("In how many modes, the data items can be locked?",
     ["Three", "Four", "Two", "One"], 2,
     "Shared (S, read) and exclusive (X, write) modes." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q93"),
    ("In Multi-Data Item strict 2PL problem, the given transactions are\nT1: R(A); W(A); R(B); W(B)\nT2: R(B); W(B).\nFind the maximum locks held at peak.",
     ["2", "4", "3", "5"], 0,
     "Under strict 2PL, T1 holds locks on A and B until it commits; T2 needs B and must wait, so at most 2 locks are held at once." + NOTE,
     "KEA 2026 CS Paper-2 · Q60"),
    # --- new questions ---
    ("A shared (S) lock on an item allows the holder to:",
     ["Read the item, while other transactions may also read it", "Read and write the item exclusively", "Delete the table", "Commit other transactions"], 0,
     "An exclusive (X) lock allows read and write and blocks all other locks."),
    ("In the lock-compatibility matrix, which combination is compatible?",
     ["S with S", "S with X", "X with S", "X with X"], 0,
     PYQ + "Only shared locks can be held together."),
    ("The two phases of the two-phase locking (2PL) protocol are:",
     ["Growing phase and shrinking phase", "Read phase and write phase", "Lock phase and commit phase only", "Start phase and end phase"], 0,
     PYQ + "In the growing phase locks are only acquired; in the shrinking phase only released."),
    ("Basic two-phase locking guarantees:",
     ["Conflict serializability, but not freedom from deadlock", "Freedom from deadlock, but not serializability", "Both serializability and freedom from deadlock", "Neither"], 0,
     PYQ + "Deadlocks must still be prevented or detected."),
    ("Strict two-phase locking requires that a transaction:",
     ["Holds all its exclusive locks until it commits or aborts", "Releases all locks immediately after use", "Never takes shared locks", "Locks the whole database"], 0,
     PYQ + "This avoids cascading rollbacks."),
    ("Rigorous two-phase locking requires that a transaction:",
     ["Holds all its locks, shared and exclusive, until it commits or aborts", "Holds only shared locks until commit", "Releases locks in random order", "Uses timestamps instead of locks"], 0,
     "Transactions are then serializable in the order in which they commit."),
    ("Conservative (static) two-phase locking avoids deadlock because a transaction:",
     ["Locks all the items it needs before it starts executing", "Never locks any item", "Releases locks before acquiring new ones", "Uses only shared locks"], 0,
     "If any item is unavailable, it locks nothing and waits."),
    ("In 2PL, the lock point of a transaction is:",
     ["The point at which it obtains its final lock", "The point at which it releases its first lock", "The start of the transaction", "The commit record in the log"], 0,
     "Transactions can be ordered by their lock points."),
    ("In the timestamp-ordering protocol, the serializability order is:",
     ["The order of the transactions' timestamps", "The order of commit", "Random", "The order of lock requests"], 0,
     PYQ + "Older transactions (smaller timestamps) come first."),
    ("Under basic timestamp ordering, if transaction T issues read(Q) and TS(T) < W-timestamp(Q), then:",
     ["T is rolled back, because it would read a value already overwritten by a younger transaction", "The read succeeds", "T waits", "Q is deleted"], 0,
     "T needs a value that no longer exists."),
    ("Thomas' write rule modifies timestamp ordering by:",
     ["Ignoring an obsolete write instead of rolling back the transaction", "Rolling back every write", "Allowing dirty reads", "Using locks"], 0,
     PYQ + "It permits some view-serializable schedules that are not conflict serializable."),
    ("In the wait-die deadlock-prevention scheme, when an older transaction requests an item held by a younger one:",
     ["The older transaction waits", "The older transaction is rolled back", "The younger transaction is rolled back", "Both are rolled back"], 0,
     PYQ + "A younger requester 'dies' (is rolled back). Wait-die is non-preemptive."),
    ("In the wound-wait scheme, when an older transaction requests an item held by a younger one:",
     ["The younger transaction is rolled back (wounded)", "The older transaction waits", "The older transaction is rolled back", "Nothing happens"], 0,
     "A younger requester waits. Wound-wait is preemptive."),
    ("Deadlock detection in a DBMS commonly uses a:",
     ["Wait-for graph – a cycle means a deadlock", "Precedence graph of reads", "B+ tree", "Hash table of passwords"], 0,
     PYQ + "A victim transaction is then rolled back."),
    ("Starvation in wait-die and wound-wait is avoided by:",
     ["Restarting a rolled-back transaction with its original timestamp", "Giving it a new, younger timestamp each time", "Never restarting it", "Locking the whole database"], 0,
     "It eventually becomes the oldest transaction."),
    ("The three phases of validation-based (optimistic) concurrency control, in order, are:",
     ["Read → Validation → Write", "Write → Read → Validation", "Validation → Read → Write", "Read → Write → Validation"], 0,
     PYQ + "Work on local copies; validate; then write if validation succeeds."),
    ("In multiple-granularity locking, the lock modes IS, IX and SIX are called:",
     ["Intention locks", "Binary locks", "Deadlocks", "Timestamps"], 0,
     "They mark that finer-grained locks are held lower in the tree."),
    ("Multiversion concurrency control (MVCC) mainly benefits:",
     ["Read operations, which never have to wait because older versions are kept", "Write operations, which never conflict", "Index creation", "Backup speed"], 0,
     "Used by PostgreSQL, Oracle and MySQL InnoDB."),
    ("Locking at a coarse granularity (e.g. whole tables) compared with fine granularity (rows) gives:",
     ["Lower locking overhead but less concurrency", "Higher concurrency and higher overhead", "No change at all", "Freedom from all deadlocks"], 0,
     "Fine granularity allows more parallel work but needs more locks."),
    ("Timestamp-ordering protocols are free from deadlock because:",
     ["Transactions never wait for locks; conflicting ones are rolled back instead", "They lock all items in advance", "They never roll back", "They allow only one transaction at a time"], 0,
     "They may, however, cause cascading rollbacks unless made strict."),
    ("The tree (graph-based) locking protocol:",
     ["Ensures conflict serializability and freedom from deadlock without two-phase locking", "Allows deadlocks but not serializability", "Requires timestamps", "Locks only the root"], 0,
     "Items must be locked following a tree order."),
    ("Match the technique with its rule:\na. Wait-die  b. Wound-wait  c. Wait-for graph  d. Timeout\n1. Roll back a transaction that waits longer than a fixed time  2. Detect deadlock by looking for cycles  3. An older requester rolls back the younger holder  4. An older requester waits; a younger requester is rolled back",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Deadlock-handling schemes are matched in KSET papers."),
    ("Match the term with its meaning:\na. Shared lock  b. Exclusive lock  c. Intention-shared lock  d. Growing phase\n1. Locks are acquired, none released  2. Shared locks will be taken at a finer level below  3. Read and write access to the item  4. Read-only access to the item",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     "Locking vocabulary."),
    ("Consider the statements:\nI. Two-phase locking ensures conflict serializability.\nII. Two-phase locking ensures freedom from deadlock.\nWhich is/are correct?",
     I_II, 0, "Two transactions can each wait for a lock the other holds."),
    ("Assertion (A): Strict two-phase locking avoids cascading rollbacks.\nReason (R): Exclusive locks are released only after the transaction commits or aborts.",
     AR, 0, "No transaction can read uncommitted data."),
    ("Assertion (A): In wait-die, a younger transaction that requests an item held by an older one waits.\nReason (R): Wait-die is a non-preemptive scheme.",
     AR, 3, "The younger requester dies (is rolled back); only older ones wait. R is true."),
    ("Upgrading a lock from shared to exclusive is allowed in 2PL:",
     ["Only in the growing phase", "Only in the shrinking phase", "At any time", "Never"], 0,
     "Downgrading (X to S) is allowed only in the shrinking phase."),
    ("Which of these is a deadlock-PREVENTION scheme rather than a detection scheme?",
     ["Wait-die", "Wait-for graph", "Periodic cycle checking", "Choosing a victim after a cycle is found"], 0,
     "Wait-die and wound-wait use timestamps so that a cycle can never form."),
]

TOPICS = {
    "Query Processing and Optimization": [("1 · Query Processing, Join Algorithms and Optimization", QUERY)],
    "Transactions & Concurrency Control": [("1 · Transactions, ACID Properties and Schedules", TRANSACTIONS),
                                           ("2 · Concurrency Control – Locking, 2PL, Timestamps and Deadlocks", CONCURRENCY)],
}
