"""Paper 2 · Unit 5 · SQL – Part 1 (2 sub-topics × 30).
References: Elmasri & Navathe; Silberschatz, Korth & Sudarshan; ISO SQL / Oracle and MySQL documentation.
Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question number,
answers from KEA's official final keys) with new questions. Real ones come from: Karnataka Legislative Council Secretariat
2024 (Computer Operator P2, Sr/Jr Programmer P2, Data Entry Operator P2; final key 09-04-2025) and GTTC 2024 (Technician
Gr-III CS – booklet C1; Lecturer CS – booklet A1; final keys 30-12-2024). Obvious printing typos are corrected."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"

DDL = [
    # --- real previous-year questions (official keys) ---
    ("Which of the following command is used to remove all the records from a table in SQL without removing the table structure?",
     ["DELETE", "TRUNCATE", "DROP", "REMOVE"], 1,
     "TRUNCATE empties the table but keeps its definition; DROP removes the table itself." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q19"),
    ("Match the following.\nList-1: (a) DDL  (b) DML  (c) Normal form  (d) View\nList-2: i) Virtual table  ii) Organising the data  iii) Set of operations  iv) Defining database",
     ["a – iv, b – iii, c – ii, d – i", "a – iii, b – i, c – iv, d – ii", "a – ii, b – iv, c – i, d – iii", "a – i, b – ii, c – iv, d – iii"], 0,
     "DDL defines the database, DML is the set of data operations, normal forms organise the data, a view is a virtual table." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q20"),
    ("In a relational database, what does a 'foreign key' do?",
     ["Uniquely identifies a record in a table", "Ensures the uniqueness of data", "Establishes a relationship between two tables", "Stores large binary data like images or videos"], 2,
     "A foreign key refers to a key of another (or the same) table, linking the two." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q17"),
    ("Which of the following is an example of a relational database?",
     ["PostgreSQL", "Cassandra", "Hadoop", "Firebase"], 0,
     "Cassandra and Firebase are NoSQL stores; Hadoop is a distributed processing framework." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q18"),
    ("In an employee table to include the attributes whose value always have some value which of the following constraints must be used?",
     ["NULL", "NOT NULL", "Default", "Check"], 1,
     "NOT NULL forbids missing values in that column." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q19"),
    ("The SQL command used to modify a column inside a table",
     ["Drop", "Update", "Set", "Alter"], 3,
     "ALTER TABLE … MODIFY / ALTER COLUMN changes a column's definition; UPDATE changes data values." + GTTC,
     "GTTC 2024 Lecturer CS · Q60"),
    ("Identify the valid data types of SQL\nI) Character and numeric type\nII) Boolean and date-time type\nIII) Fuzzy and unstructured type\nIV) Matrix and vector type",
     ["I and III only", "II and IV only", "I and II only", "III and IV only"], 2,
     "Standard SQL has character, numeric, Boolean and date-time types." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q89"),
    ("Primary key in DBMS should be",
     ["Unique", "Not null", "Unique and not null", "Null"], 2,
     "A primary key must identify each row (unique) and can never be missing (entity integrity)." + KLC,
     "Legislative Council 2024 Data Entry Operator P2 · Q87"),
    ("Match the following:\nList-1: a) MYISAM  b) JOIN  c) FOREIGN KEY  d) AUTO-INCREMENT\nList-2: i) References a unique identifier in another table  ii) Automatically increases the value of a field  iii) Storage engine for MySQL  iv) Combines rows from two or more tables",
     ["a – iii, b – iv, c – i, d – ii", "a – ii, b – i, c – iii, d – iv", "a – iii, b – iv, c – ii, d – i", "a – iv, b – ii, c – iii, d – i"], 0,
     "MyISAM is a MySQL storage engine (InnoDB is the default today)." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q74"),
    # --- new questions ---
    ("Which group contains only DDL commands?",
     ["CREATE, ALTER, DROP, TRUNCATE", "INSERT, UPDATE, DELETE", "GRANT, REVOKE", "COMMIT, ROLLBACK, SAVEPOINT"], 0,
     PYQ + "DML changes data, DCL controls access, TCL controls transactions."),
    ("GRANT and REVOKE belong to which category of SQL commands?",
     ["DCL – Data Control Language", "DDL", "DML", "TCL"], 0, PYQ + "They give and take away privileges."),
    ("COMMIT, ROLLBACK and SAVEPOINT belong to:",
     ["TCL – Transaction Control Language", "DDL", "DCL", "DQL"], 0, "They end or partly undo transactions."),
    ("Which statement about DELETE, TRUNCATE and DROP is correct?",
     ["DELETE can remove selected rows with WHERE and can be rolled back; TRUNCATE removes all rows; DROP removes the table", "TRUNCATE can take a WHERE clause", "DROP keeps the table structure", "DELETE always removes the table structure"], 0,
     PYQ + "In most systems TRUNCATE (DDL) commits implicitly, unlike DELETE (DML)."),
    ("CHAR(10) differs from VARCHAR(10) in that CHAR(10):",
     ["Always uses 10 characters of storage, padding shorter values with spaces", "Stores up to 10 bytes of binary data only", "Can store at most 1 character", "Cannot store letters"], 0,
     "VARCHAR stores only the actual length (plus a small overhead)."),
    ("A column declared DECIMAL(7, 2) (NUMERIC(7, 2)) can store at most:",
     ["99999.99", "9999999.99", "9999.999", "99.99999"], 0, "7 digits in total, 2 of them after the decimal point."),
    ("Which statement correctly adds a column Email to the table STUDENT?",
     ["ALTER TABLE STUDENT ADD Email VARCHAR(50);", "UPDATE STUDENT ADD Email VARCHAR(50);", "INSERT INTO STUDENT COLUMN Email;", "MODIFY STUDENT SET Email VARCHAR(50);"], 0,
     "Structural changes use ALTER TABLE."),
    ("The difference between a PRIMARY KEY and a UNIQUE constraint is that:",
     ["A table has one primary key (no NULLs), but can have several UNIQUE constraints, which usually allow NULLs", "UNIQUE columns can never contain NULL", "A table may have many primary keys", "PRIMARY KEY allows duplicates"], 0,
     "Both enforce uniqueness of the values present."),
    ("Which constraint ensures that Age entered is between 18 and 60?",
     ["CHECK (Age BETWEEN 18 AND 60)", "DEFAULT 18", "UNIQUE (Age)", "NOT NULL"], 0, "CHECK enforces a condition on each row."),
    ("A DEFAULT constraint:",
     ["Supplies a value for a column when an INSERT does not give one", "Forbids NULLs", "Makes values unique", "Links two tables"], 0,
     "e.g. Status VARCHAR(10) DEFAULT 'Active'."),
    ("Which data type is most suitable for storing images or other large binary files?",
     ["BLOB", "VARCHAR(20)", "DATE", "INTEGER"], 0, "BLOB = Binary Large Object; CLOB is for large text."),
    ("Which command removes the table STUDENT together with its structure?",
     ["DROP TABLE STUDENT;", "DELETE FROM STUDENT;", "TRUNCATE TABLE STUDENT;", "REMOVE STUDENT;"], 0, "DROP removes both data and definition."),
    ("Consider the statements:\nI. CREATE, ALTER and DROP are DDL commands.\nII. INSERT is a DDL command.\nWhich is/are correct?",
     I_II, 0, "INSERT is DML."),
    ("Consider the statements:\nI. A table can have only one primary key.\nII. A primary key can be made of several columns.\nWhich is/are correct?",
     I_II, 2, "A composite primary key spans several columns."),
    ("Consider the statements:\nI. A FOREIGN KEY must reference a column that is a primary key or has a UNIQUE constraint.\nII. A FOREIGN KEY column can never contain NULL.\nWhich is/are correct?",
     I_II, 0, "Foreign keys may be NULL unless declared NOT NULL."),
    ("Assertion (A): TRUNCATE is usually faster than DELETE for removing all rows.\nReason (R): TRUNCATE deallocates data pages instead of deleting and logging rows one by one.",
     AR, 0, "That is why TRUNCATE cannot use a WHERE clause."),
    ("Assertion (A): UPDATE is a DDL command.\nReason (R): UPDATE changes the values stored in existing rows.",
     AR, 3, "Changing data is DML; A is false."),
    ("Assertion (A): A NOT NULL constraint forces every row to have a value in that column.\nReason (R): SQL was originally called SEQUEL at IBM.",
     AR, 1, "Both true, but R does not explain A."),
    ("Assertion (A): A UNIQUE column can never contain a NULL value.\nReason (R): A UNIQUE constraint prevents duplicate non-NULL values.",
     AR, 3, "Most systems allow NULLs in UNIQUE columns, so A is false."),
    ("Match the SQL category with its command:\na. DDL  b. DML  c. DCL  d. TCL\n1. COMMIT  2. GRANT  3. UPDATE  4. CREATE",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "The four sub-languages of SQL."),
    ("Match the constraint with its purpose:\na. PRIMARY KEY  b. FOREIGN KEY  c. CHECK  d. DEFAULT\n1. Value used when none is given  2. Condition every row must satisfy  3. Reference to another table  4. Unique and not null identifier",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Integrity constraints declared in CREATE TABLE."),
]

QUERIES = [
    # --- real previous-year questions (official keys) ---
    ("Which of the following is an example of an aggregate function in SQL?",
     ["MAX", "Group BY", "Having", "Order BY"], 0,
     "MAX, MIN, SUM, AVG and COUNT are aggregate functions; the others are clauses." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q33"),
    ("The correct order of SQL expressions is",
     ["Select, group by, where, having", "Select, having, group by, where", "Select, having, where, group by", "Select, where, group by, having"], 3,
     "Written order: SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q18"),
    ("In SQL, testing whether a subquery is empty is done using",
     ["DISTINCT", "UNIQUE", "NULL", "EXISTS"], 3,
     "EXISTS (subquery) is true when the subquery returns at least one row." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q23"),
    ("Which of the following term/terms is/are not SQL join command?\nI) Inner join\nII) Outer join\nIII) Exterior join\nIV) Interior join",
     ["I only", "I and II only", "III only", "IV and III only"], 3,
     "SQL has INNER, LEFT/RIGHT/FULL OUTER, CROSS and NATURAL joins; 'exterior' and 'interior' joins do not exist." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q82"),
    ("Name the SQL built-in functions\nI) Count\nII) Max\nIII) Min\nIV) Distinct",
     ["I only", "II only", "III only", "I, II, III and IV"], 3,
     "KEA's key accepts all four (strictly, DISTINCT is a keyword used with SELECT and inside aggregates)." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q83"),
    ("Match the following SQL commands to perform undo transactions that have not already been saved to database and in the sequence of commands are executed\nList-1: a) Perform DELETE & ROLLBACK  b) Perform ROLLBACK & DELETE  c) Perform ROLLBACK & ROLLBACK  d) Perform DELETE & DELETE\nList-2: i) Two time delete operation  ii) Delete first & Rollback  iii) Two time Rollback operation  iv) Rollback first & Delete",
     ["a – i, b – ii, c – iv, d – iii", "a – ii, b – iv, c – iii, d – i", "a – iv, b – iii, c – ii, d – i", "a – iii, b – i, c – ii, d – iv"], 1,
     "Each command pair is matched with the same sequence described in words." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q88"),
    ("A query returns a \"missing keyword\" error. What could be the issue?\nI. Missing a semicolon\nII. Incorrect function syntax\nIII. Using a reserved keyword\nChoose the correct answer from the following options",
     ["I only", "II only", "III only", "I, II and III"], 2,
     "KEA's key gives III only: a reserved word used as a name breaks the parser's expected keyword sequence (Oracle ORA-00905)." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q77"),
    ("Savepoint is a part of",
     ["Recovery measures", "Security measures", "Concurrency measures", "Authorization measures"], 0,
     "A savepoint lets a transaction roll back part of its work – a recovery feature." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q22"),
    # --- new questions ---
    ("Which clause removes duplicate rows from the result of a SELECT?",
     ["DISTINCT", "UNIQUE", "GROUP", "ORDER BY"], 0, PYQ + "SELECT DISTINCT City FROM Customer;"),
    ("The difference between WHERE and HAVING is that:",
     ["WHERE filters rows before grouping; HAVING filters groups after GROUP BY", "HAVING filters rows before grouping", "They are identical", "WHERE can use aggregate functions directly"], 0, PYQ + "Aggregates such as COUNT(*) > 5 belong in HAVING."),
    ("The default sort order of ORDER BY is:",
     ["Ascending", "Descending", "Random", "Insertion order"], 0, "Add DESC for descending order."),
    ("Table MARKS has a column Score with values 10, 20, NULL and 30. What does SELECT COUNT(*), COUNT(Score) FROM MARKS return?",
     ["4 and 3", "3 and 3", "4 and 4", "3 and 4"], 0, PYQ + "COUNT(*) counts rows; COUNT(column) ignores NULLs."),
    ("For the same Score values (10, 20, NULL, 30), AVG(Score) is:",
     ["20", "15", "60", "NULL"], 0, "Aggregates ignore NULLs: (10 + 20 + 30) / 3 = 20."),
    ("WHERE Name LIKE 'A%' selects names that:",
     ["Begin with A", "End with A", "Contain exactly two letters", "Contain the % sign"], 0, "% matches any sequence of characters; _ matches exactly one."),
    ("WHERE Name LIKE '_a%' selects names whose:",
     ["Second letter is a", "First letter is a", "Last letter is a", "Length is 2"], 0, "_ stands for exactly one character."),
    ("WHERE Salary BETWEEN 20000 AND 30000 is equivalent to:",
     ["Salary >= 20000 AND Salary <= 30000", "Salary > 20000 AND Salary < 30000", "Salary >= 20000 OR Salary <= 30000", "Salary = 20000 OR Salary = 30000"], 0, "BETWEEN includes both end values."),
    ("Which condition correctly finds rows where Phone has no value?",
     ["WHERE Phone IS NULL", "WHERE Phone = NULL", "WHERE Phone == NULL", "WHERE NULL(Phone)"], 0, PYQ + "Any comparison with NULL using = gives UNKNOWN, not TRUE."),
    ("What happens when DELETE FROM EMPLOYEE; is executed without a WHERE clause?",
     ["All rows of EMPLOYEE are deleted, but the table remains", "Nothing happens", "The table is dropped", "Only the first row is deleted"], 0, "Always check the WHERE clause in DELETE and UPDATE."),
    ("Which statement gives every employee of department 5 a 10% raise?",
     ["UPDATE EMPLOYEE SET Salary = Salary * 1.10 WHERE Dno = 5;", "ALTER EMPLOYEE SET Salary = Salary * 1.10;", "INSERT INTO EMPLOYEE Salary * 1.10;", "UPDATE Salary = Salary * 1.10 FROM EMPLOYEE;"], 0, "UPDATE … SET … WHERE …"),
    ("INSERT INTO STUDENT (Roll, Name) VALUES (7, 'Asha'); leaves the other columns of the new row:",
     ["NULL, or their DEFAULT values if defined", "Empty strings always", "Copied from the previous row", "Unchanged in all rows"], 0, "Unspecified columns take defaults or NULL (and must allow it)."),
    ("Which expression returns the number of different cities in the CUSTOMER table?",
     ["SELECT COUNT(DISTINCT City) FROM CUSTOMER;", "SELECT DISTINCT COUNT(*) FROM CUSTOMER;", "SELECT COUNT(City) FROM CUSTOMER;", "SELECT SUM(City) FROM CUSTOMER;"], 0,
     "COUNT(DISTINCT column) counts distinct non-NULL values."),
    ("In logical processing order, which part of a SELECT is evaluated first?",
     ["FROM", "SELECT", "ORDER BY", "HAVING"], 0, "FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY."),
    ("A subquery that refers to a column of the outer query and is re-evaluated for each outer row is called a:",
     ["Correlated subquery", "Scalar subquery only", "Derived table", "Cross join"], 0, "e.g. employees earning more than their own department's average."),
    ("Consider the statements:\nI. COUNT(*) counts rows including those with NULLs.\nII. SUM ignores NULL values.\nWhich is/are correct?",
     I_II, 2, "Both are standard SQL behaviour."),
    ("Consider the statements:\nI. A column in the SELECT list of a GROUP BY query must be grouped or aggregated.\nII. HAVING can be used without any aggregate condition only in Oracle.\nWhich is/are correct?",
     I_II, 0, "HAVING may use any condition on groups in standard SQL."),
    ("Consider the statements:\nI. WHERE can contain aggregate functions such as AVG(Salary) > 5000.\nII. ORDER BY must come before WHERE.\nWhich is/are correct?",
     I_II, 3, "Aggregate conditions go in HAVING; ORDER BY comes last."),
    ("Assertion (A): Aggregate conditions are written in HAVING, not WHERE.\nReason (R): WHERE is applied to individual rows before the groups are formed.",
     AR, 0, "Group values do not exist yet when WHERE is evaluated."),
    ("Assertion (A): WHERE Phone = NULL returns rows with missing phone numbers.\nReason (R): Comparisons with NULL evaluate to UNKNOWN.",
     AR, 3, "Because of R, the comparison never becomes TRUE; A is false."),
    ("Assertion (A): SELECT DISTINCT removes duplicate result rows.\nReason (R): ORDER BY sorts rows in ascending order by default.",
     AR, 1, "Both true, but R does not explain A."),
    ("Match the SQL keyword with its role:\na. GROUP BY  b. HAVING  c. ORDER BY  d. LIKE\n1. Pattern matching  2. Sorting the result  3. Condition on groups  4. Forming groups of rows",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Common SQL clause matching."),
]

TOPICS = {
    "SQL – Part 1": [("1 · Data Definition, Data Types and Constraints", DDL),
                     ("2 · Queries, Aggregate Functions and Update Statements", QUERIES)],
}
