"""Paper 2 · Unit 5 · P2-U5-09 Database Recovery Techniques (1 set × 30) and P2-U5-10 Data Warehousing and Data Mining
(2 sub-topics × 30).
References: Silberschatz, Korth & Sudarshan, Database System Concepts (ch. 19 Recovery); Elmasri & Navathe (ch. 22, 29);
Han, Kamber & Pei, Data Mining: Concepts and Techniques (3rd ed.); W. H. Inmon, Building the Data Warehouse.
Real previous-year questions (exact wording and printed option order, `source` = paper and question number) are mixed in:
GTTC 2024 Technician Gr-III CS (booklet C1) and Legislative Council 2024 Sr/Jr Programmer P2 (booklet A1) with KEA's official
final keys; KSET 2024/2025 questions reused from packs/pyq-p2.json (answers worked out by ExamSim)."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

RECOVERY = [
    # --- real previous-year questions (official keys) ---
    ("Which of the following is the preferred way to recover a database after a system failure?",
     ["Rollback", "Roll forward", "Switch to duplicate database", "Reprocess transactions"], 2,
     "KEA's key takes switching to a duplicate (standby/mirrored) database as the preferred way – it gives the fastest recovery. Textbook log-based recovery uses undo (rollback) and redo (roll forward)." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q24"),
    ("Match the following:\nList-1: a) Data Guard  b) Indexes  c) Redo Logs  d) SQL Developer\nList-2: i) Record changes to the database  ii) Ensures data protection and disaster recovery  iii) Oracle's integrated development environment  iv) Reduces the time taken to retrieve records",
     ["a – ii, b – i, c – iii, d – iv", "a – i, b – ii, c – iv, d – iii", "a – ii, b – iv, c – i, d – iii", "a – iv, b – i, c – ii, d – iii"], 2,
     "Oracle Data Guard maintains standby databases for disaster recovery; redo logs record every change so it can be replayed." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q75"),
    # --- new questions ---
    ("The main purpose of a database recovery system is to:",
     ["Restore the database to the most recent consistent state after a failure", "Speed up queries", "Create new users", "Normalize tables"], 0,
     "It preserves atomicity and durability."),
    ("A transaction that cannot continue because of bad input or an overflow suffers a:",
     ["Transaction failure (logical error)", "Disk failure", "Power failure of the whole data centre", "Network partition only"], 0,
     PYQ + "Failure classes: transaction failure, system crash, disk (media) failure."),
    ("An update log record of the form <Ti, X, V1, V2> stores:",
     ["The transaction, the data item, the old value and the new value", "Only the new value", "The user's password", "The query plan"], 0,
     PYQ + "The old value is used for undo, the new value for redo."),
    ("The write-ahead logging (WAL) rule says that:",
     ["Log records for a change must reach stable storage before the changed data block is written to disk", "Data must be written before the log", "Logs are written only at shutdown", "No log is needed for committed transactions"], 0,
     PYQ + "Otherwise an uncommitted change on disk could not be undone."),
    ("The deferred-update technique is also called:",
     ["NO-UNDO/REDO", "UNDO/NO-REDO", "UNDO/REDO", "NO-UNDO/NO-REDO"], 0,
     PYQ + "Changes reach the database only after commit, so nothing needs to be undone."),
    ("The immediate-update technique (with no restriction on when committed data is written) is:",
     ["UNDO/REDO", "NO-UNDO/REDO", "NO-UNDO/NO-REDO", "REDO only"], 0,
     "Uncommitted changes may already be on disk (undo), and committed ones may not yet be (redo)."),
    ("After a crash, with immediate update, a transaction whose log has <Ti start> but no <Ti commit> or <Ti abort> must be:",
     ["Undone", "Redone", "Ignored", "Committed"], 0,
     PYQ + "Transactions with a commit record are redone."),
    ("The main benefit of taking checkpoints is that:",
     ["Recovery need not scan or redo the whole log – only work after the last checkpoint", "No log is needed any more", "Transactions run faster", "Deadlocks are prevented"], 0,
     PYQ + "At a checkpoint, modified buffers and a <checkpoint L> record are forced to stable storage."),
    ("During recovery, undo operations are applied:",
     ["Backwards from the end of the log, and redo operations forwards", "Forwards, and redo backwards", "In random order", "Only for committed transactions"], 0,
     "Undo restores old values in reverse order of the changes."),
    ("Shadow paging recovers without a log by:",
     ["Keeping the old (shadow) page table unchanged and switching to the new page table only at commit", "Writing every change twice to the log", "Undoing every transaction at restart", "Copying the database to tape every second"], 0,
     PYQ + "Drawbacks: data fragmentation, garbage collection and difficulty with concurrency."),
    ("Stable storage is:",
     ["Storage whose contents are (practically) never lost, approximated by keeping copies on independent non-volatile devices", "Main memory", "CPU cache", "A single hard disk"], 0,
     "Implemented with mirrored disks or remote copies."),
    ("The three phases of the ARIES recovery algorithm, in order, are:",
     ["Analysis → Redo → Undo", "Undo → Redo → Analysis", "Redo → Analysis → Undo", "Analysis → Undo → Redo"], 0,
     PYQ + "ARIES (IBM, 1992) is used by most commercial DBMSs."),
    ("In ARIES, the redo phase 'repeats history', which means it:",
     ["Re-applies all logged updates, even those of transactions that will later be undone", "Redoes only committed transactions", "Skips all updates after the checkpoint", "Deletes the log"], 0,
     "The undo phase then rolls back the losers."),
    ("Each ARIES log record is identified by a monotonically increasing:",
     ["Log Sequence Number (LSN)", "Primary key", "Timestamp of the user", "Page size"], 0,
     "Each page stores the LSN of the last update applied to it (PageLSN)."),
    ("A compensation log record (CLR) is written when:",
     ["An update is undone, so the undo itself is logged and never repeated", "A transaction starts", "A checkpoint is taken", "A user logs in"], 0,
     "CLRs make undo idempotent across repeated crashes."),
    ("A buffer policy of 'steal' means that:",
     ["Pages changed by uncommitted transactions may be written to disk – so undo is needed", "Committed pages must be written at commit", "No page can ever be written", "Pages are written only at shutdown"], 0,
     "'No-force' means committed pages need not be written at commit – so redo is needed."),
    ("Recovery from a disk (media) failure normally uses:",
     ["The latest backup (archival dump) plus the log to redo changes made after the backup", "Only the buffer pool", "Undo of every transaction", "The query optimizer"], 0,
     "Backups and the log should be kept on different devices."),
    ("A remote backup (standby) system mainly provides:",
     ["High availability – processing can continue at the backup site if the primary site fails", "Faster queries on the primary", "Normalization", "Encryption"], 0,
     "Log records are shipped to the backup site and applied there."),
    ("A redo operation must be idempotent, meaning:",
     ["Applying it several times has the same effect as applying it once", "It can be applied only once", "It undoes the change", "It needs user confirmation"], 0,
     "A crash during recovery may cause redo to be repeated."),
    ("A fuzzy checkpoint differs from an ordinary checkpoint because:",
     ["Transactions may continue while modified pages are being written out", "No log record is written", "All transactions must abort", "It is taken only once a year"], 0,
     "It avoids halting the system during the checkpoint."),
    ("The correct order of steps in log-based recovery after a crash with immediate update is:",
     ["Scan the log → build undo and redo lists → redo committed transactions → undo uncommitted ones", "Undo everything → delete the log → restart", "Redo uncommitted transactions → undo committed ones", "Restore backup → ignore the log"], 0,
     "Silberschatz's restart procedure redoes first (repeating history), then undoes incomplete transactions."),
    ("A savepoint helps recovery by:",
     ["Allowing a transaction to roll back only part of its work", "Committing the transaction automatically", "Taking a full database backup", "Preventing all failures"], 0,
     "ROLLBACK TO SAVEPOINT keeps the earlier work pending."),
    ("Match the technique with its feature:\na. Deferred update  b. Immediate update  c. Shadow paging  d. Checkpoint\n1. Limits how much of the log recovery must process  2. Keeps a copy of the page table; no undo/redo log needed  3. UNDO/REDO  4. NO-UNDO/REDO",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Recovery-technique matching is a common KEA question."),
    ("Consider the statements:\nI. Write-ahead logging forces log records to stable storage before the data they describe.\nII. Deferred update needs undo operations at restart.\nWhich is/are correct?",
     I_II, 0, "Deferred update never writes uncommitted data, so no undo is needed."),
    ("Assertion (A): Checkpoints reduce recovery time.\nReason (R): Transactions that committed before the checkpoint need not be redone.",
     AR, 0, "Their changes were already forced to disk at the checkpoint."),
    ("Assertion (A): Shadow paging needs no undo operation.\nReason (R): The shadow page table, which points to the old pages, is not changed during the transaction.",
     AR, 0, "On failure the old page table simply remains current."),
    ("Assertion (A): Main memory is a form of stable storage.\nReason (R): Recovery algorithms assume that the contents of main memory may be lost in a crash.",
     AR, 3, "Main memory is volatile, so A is false."),
    ("After a crash with immediate update, the transactions whose changes must be redone are those that:",
     ["Have a <Ti commit> record in the log", "Have only a <Ti start> record", "Were never started", "Have no log records at all"], 0,
     "Their changes may not yet have reached the disk; incomplete transactions are undone instead."),
]

WAREHOUSE = [
    # --- real previous-year question ---
    ("Match the following:\na. Data warehouse\nb. Data mining\nc. OLAP\nd. Aggregation\n(i) which allows users to analyse data from multiple database systems at once\n(ii) is the summarization of fact related data\n(iii) central repository of information that can be analyzed to make more informed decisions\n(iv) is a process used to discover patterns and relationships in datasets",
     ["a – ii, b – iii, c – iv, d – i", "a – iii, b – iv, c – i, d – ii", "a – iii, b – iv, c – ii, d – i", "a – iii, b – ii, c – iv, d – i"], 1,
     "Warehouse = central repository; mining = pattern discovery; OLAP = multi-dimensional analysis; aggregation = summarisation." + NOTE,
     "KSET 2025 CS&A · Q37"),
    # --- new questions ---
    ("According to W. H. Inmon, a data warehouse is a:",
     ["Subject-oriented, integrated, time-variant and non-volatile collection of data supporting management decisions", "Collection of current transactions only", "Backup copy of one table", "Real-time operational database"], 0,
     PYQ + "Inmon is called the father of data warehousing; Ralph Kimball popularised dimensional modelling."),
    ("Which statement correctly contrasts OLTP and OLAP systems?",
     ["OLTP handles many short update transactions on current data; OLAP handles complex analytical queries on historical, summarised data", "OLTP is used only for reports", "OLAP systems never use aggregates", "Both are designed for the same workload"], 0,
     PYQ + "A classic KSET and KEA question."),
    ("ETL in data warehousing stands for:",
     ["Extract, Transform, Load", "Evaluate, Test, Launch", "Extract, Transfer, Link", "Encode, Transmit, Log"], 0,
     PYQ + "Data is extracted from sources, cleaned and transformed, then loaded."),
    ("A star schema consists of:",
     ["A central fact table linked to several dimension tables", "Only one table", "Normalized dimension tables arranged in many levels", "Several fact tables with no dimensions"], 0,
     PYQ + "It is the simplest dimensional model."),
    ("In a snowflake schema:",
     ["Dimension tables are normalized into further tables", "There is no fact table", "Fact tables are denormalized into dimensions", "All data is in a single table"], 0,
     "It saves space but needs more joins."),
    ("Several fact tables sharing common dimension tables form a:",
     ["Fact constellation (galaxy) schema", "Star schema", "Snowflake schema", "Hierarchical schema"], 0,
     "e.g. Sales and Shipping facts sharing Time and Product."),
    ("A fact table mainly contains:",
     ["Numeric measures (e.g. units sold, amount) and foreign keys to dimension tables", "Only descriptive text", "Users and passwords", "Program code"], 0,
     "Dimensions hold descriptive attributes."),
    ("A data mart is:",
     ["A smaller warehouse focused on one department or subject area", "A shop that sells data", "An index", "A backup tape"], 0,
     "e.g. a sales data mart."),
    ("day < month < quarter < year is an example of a:",
     ["Concept hierarchy", "Fact table", "Association rule", "Primary key"], 0,
     PYQ + "Concept hierarchies let OLAP operations change the level of detail."),
    ("The OLAP operation that summarises data by climbing up a concept hierarchy (e.g. city → country) is:",
     ["Roll-up", "Drill-down", "Slice", "Pivot"], 0,
     PYQ + "Roll-up is also called drill-up or consolidation."),
    ("Going from yearly sales to quarterly or monthly sales is the OLAP operation:",
     ["Drill-down", "Roll-up", "Dice", "Pivot"], 0,
     "It gives more detail."),
    ("Selecting a sub-cube by fixing ONE dimension (e.g. time = 'Q1') is called:",
     ["Slice", "Dice", "Pivot", "Roll-up"], 0,
     PYQ + "Dice selects on two or more dimensions."),
    ("Rotating the axes of a data cube to view it from a different angle is:",
     ["Pivot (rotate)", "Slice", "Drill-down", "Aggregation"], 0,
     "It changes the presentation, not the data."),
    ("For a data cube with n dimensions and no concept hierarchies, the number of cuboids is:",
     ["2ⁿ", "n", "n²", "n!"], 0,
     PYQ + "Each dimension is either included or aggregated away."),
    ("A cube on 3 dimensions (no hierarchies) has how many cuboids?",
     ["8", "3", "6", "9"], 0,
     "2³ = 8, from the base cuboid to the apex (all) cuboid."),
    ("The apex cuboid of a data cube is:",
     ["The 0-D cuboid holding the grand total over all dimensions", "The most detailed cuboid", "A dimension table", "An index"], 0,
     "The base cuboid is the least summarised one."),
    ("OLAP servers that store data in relational tables are called ____, and those that use multidimensional arrays are called ____.",
     ["ROLAP; MOLAP", "MOLAP; ROLAP", "HOLAP; ROLAP", "OLTP; OLAP"], 0,
     "HOLAP (hybrid) combines both."),
    ("Data about the data in a warehouse – source, structure, transformation rules – is called:",
     ["Metadata", "Fact data", "Raw data", "Noise"], 0,
     "It is kept in a metadata repository."),
    ("'Non-volatile' as a property of a data warehouse means:",
     ["Data is loaded and read, but not updated or deleted in place by daily transactions", "Data disappears when power fails", "Data changes every second", "Data is kept only in RAM"], 0,
     "Warehouses are refreshed periodically."),
    ("'Time-variant' as a property of a data warehouse means:",
     ["Data is kept over a long period and every record is associated with time", "Data is updated every minute", "Only current data is kept", "Queries run at fixed times"], 0,
     "Typically 5–10 years of history."),
    ("AVERAGE is classified as which type of measure in data cube computation?",
     ["Algebraic", "Distributive", "Holistic", "Nominal"], 0,
     "SUM and COUNT are distributive; AVG = SUM/COUNT is algebraic; MEDIAN is holistic."),
    ("Bitmap indexes are especially useful in data warehouses for:",
     ["Attributes with few distinct values, such as gender or region", "Primary keys with unique values", "Large text documents", "Images"], 0,
     "Bitwise AND/OR operations answer queries quickly."),
    ("Removing duplicates, filling missing values and correcting inconsistencies before loading is called:",
     ["Data cleaning (cleansing)", "Data mining", "Roll-up", "Indexing"], 0,
     "It is part of the Transform step of ETL."),
    ("Match the OLAP operation with its effect:\na. Roll-up  b. Drill-down  c. Slice  d. Pivot\n1. Rotates the view of the cube  2. Fixes one value of one dimension  3. Shows more detailed data  4. Aggregates to a higher level",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "OLAP-operation matching appears in KSET papers."),
    ("Consider the statements:\nI. OLAP systems mainly work on historical data.\nII. OLTP systems are optimised for complex analytical queries.\nWhich is/are correct?",
     I_II, 0, "OLTP systems are optimised for short transactions."),
    ("Assertion (A): A snowflake schema reduces redundancy in dimension tables.\nReason (R): Its dimension tables are normalized.",
     AR, 0, "Normalization removes repeated descriptive values."),
    ("Assertion (A): A data warehouse is updated row by row by every operational transaction in real time.\nReason (R): A data warehouse is non-volatile.",
     AR, 3, "Warehouses are loaded periodically, so A is false."),
    ("Which of these is a typical dimension in a sales data warehouse?",
     ["Time", "Units sold", "Revenue", "Profit"], 0,
     "Units sold, revenue and profit are measures in the fact table."),
    ("Ralph Kimball's approach to building a data warehouse is usually described as:",
     ["Bottom-up – build dimensional data marts first and integrate them", "Top-down – build the enterprise warehouse first", "Building only OLTP systems", "Avoiding dimensional models"], 0,
     "Inmon's approach is top-down: an enterprise warehouse first, data marts derived from it."),
]

MINING = [
    # --- real previous-year questions ---
    ("What is the process of examining large and varied data sets to uncover hidden patterns, unknown correlations, market trends, customer preferences and other useful information?",
     ["Data Mining", "Data Warehousing", "Data Integration", "Data Processing"], 0,
     "Discovering hidden patterns and correlations in data is data mining (the analytics step of KDD)." + NOTE,
     "KSET 2024 CS&A · Q32"),
    ("Which of the following can act as possible termination conditions in K-means?\n(a) For a fixed number of iterations\n(b) The assignment of observations to clusters does not change between iterations except for cases with a bad local minimum\n(c) Centroids do not change between successive iterations\n(d) Terminate when reduction in the sum of square distances between points and their assigned cluster centroids falls below threshold.",
     ["(a), (b) and (c)", "(a), (c) and (d)", "(a), (b) and (d)", "(a), (b), (c) and (d)"], 3,
     "All four are standard stopping criteria for K-means." + NOTE,
     "KSET 2024 CS&A · Q31"),
    # --- new questions ---
    ("Knowledge Discovery in Databases (KDD) proceeds in the order:",
     ["Data cleaning → integration → selection → transformation → data mining → pattern evaluation → knowledge presentation", "Data mining → cleaning → presentation → selection", "Presentation → mining → cleaning → integration", "Transformation → presentation → cleaning → mining"], 0,
     PYQ + "Han, Kamber & Pei treat data mining as one essential step of KDD."),
    ("For an association rule A ⇒ B, support and confidence are:",
     ["Support = P(A ∪ B), the fraction of transactions with both; confidence = P(B | A)", "Support = P(B | A); confidence = P(A)", "Both equal P(A)", "Support = number of items; confidence = number of rules"], 0,
     PYQ + "Rules meeting minimum support and minimum confidence are called strong."),
    ("Of 10 transactions, 5 contain bread and 4 contain both bread and butter. For bread ⇒ butter, the support and confidence are:",
     ["40% and 80%", "50% and 40%", "80% and 40%", "40% and 50%"], 0,
     PYQ + "Support = 4/10; confidence = 4/5."),
    ("The Apriori property states that:",
     ["Every non-empty subset of a frequent itemset must also be frequent", "Every superset of a frequent itemset is frequent", "Infrequent itemsets have frequent supersets", "Support increases as itemsets grow"], 0,
     PYQ + "It is anti-monotone and lets Apriori prune candidates."),
    ("FP-growth differs from Apriori because it:",
     ["Mines frequent itemsets without candidate generation, using a compact FP-tree", "Generates more candidates", "Needs class labels", "Works only on numeric data"], 0,
     PYQ + "It usually needs only two database scans."),
    ("Finding that customers who buy bread often also buy butter is an example of:",
     ["Association rule mining (market basket analysis)", "Classification", "Regression", "Outlier detection"], 0,
     "Used for shelf placement and promotions."),
    ("The basic difference between classification and clustering is:",
     ["Classification is supervised (uses labelled training data); clustering is unsupervised", "Clustering needs labelled data", "Both are supervised", "Classification has no training phase"], 0,
     PYQ + "A frequent KSET question."),
    ("The attribute-selection measure used by ID3, C4.5 and CART respectively is:",
     ["Information gain, gain ratio, Gini index", "Gini index, information gain, gain ratio", "Gain ratio, Gini index, information gain", "Support, confidence, lift"], 0,
     PYQ + "All three build decision trees top-down."),
    ("The entropy of a set containing two classes in equal proportion is:",
     ["1 bit", "0", "0.5 bit", "2 bits"], 0,
     "−(½ log₂ ½ + ½ log₂ ½) = 1. A pure set has entropy 0."),
    ("The naive Bayes classifier assumes that:",
     ["Attributes are conditionally independent of one another given the class", "All attributes are equal", "Classes are equally likely", "Data has no noise"], 0,
     "The assumption simplifies computing P(X | C)."),
    ("k-nearest-neighbour (k-NN) is called a 'lazy learner' because it:",
     ["Stores the training data and does the real work only when a new item must be classified", "Never classifies anything", "Builds a tree in advance", "Ignores distance"], 0,
     "Decision trees and naive Bayes are eager learners."),
    ("A model that fits the training data very closely but performs poorly on new data is:",
     ["Overfitting", "Underfitting", "Clustering", "Normalizing"], 0,
     "Tree pruning and cross-validation reduce overfitting."),
    ("Accuracy computed from a confusion matrix is:",
     ["(TP + TN) / (TP + TN + FP + FN)", "TP / (TP + FP)", "TP / (TP + FN)", "FP / (FP + TN)"], 0,
     "TP / (TP + FP) is precision; TP / (TP + FN) is recall."),
    ("Recall (sensitivity) is defined as:",
     ["TP / (TP + FN)", "TP / (TP + FP)", "TN / (TN + FP)", "(TP + TN) / total"], 0,
     PYQ + "It is the fraction of actual positives that are found."),
    ("Which statement about k-means clustering is TRUE?",
     ["The number of clusters k must be given in advance, and the result depends on the initial centroids", "It finds clusters of any shape and ignores noise", "It needs labelled data", "It always finds the global optimum"], 0,
     "k-medoids is less sensitive to outliers."),
    ("Agglomerative hierarchical clustering:",
     ["Starts with each object as its own cluster and repeatedly merges the closest clusters", "Starts with one cluster and splits it", "Needs k in advance", "Uses support and confidence"], 0,
     PYQ + "Divisive clustering works top-down. The result is drawn as a dendrogram."),
    ("DBSCAN is a ____ clustering method that can find clusters of arbitrary shape and mark noise points.",
     ["Density-based", "Partitioning", "Grid-based only", "Model-based neural"], 0,
     "It uses the parameters ε (radius) and MinPts."),
    ("Linear regression is used to:",
     ["Predict a continuous numeric value from one or more variables", "Predict a class label such as yes/no", "Find frequent itemsets", "Group unlabeled data"], 0,
     PYQ + "The line y = a + bx is fitted by the method of least squares."),
    ("Detecting fraudulent credit-card transactions that differ greatly from normal behaviour is an example of:",
     ["Outlier (anomaly) analysis", "Association rule mining", "Data cleaning only", "Roll-up"], 0,
     "Outliers can be the most interesting objects."),
    ("In k-fold cross-validation:",
     ["The data is split into k parts; each part is used once for testing while the rest train the model", "Only one test set is ever used", "Training and testing use the same data", "k models are averaged without testing"], 0,
     "10-fold cross-validation is common."),
    ("Lift for a rule A ⇒ B greater than 1 means that:",
     ["A and B are positively correlated – A's presence raises the chance of B", "A and B are independent", "A and B are negatively correlated", "The rule is invalid"], 0,
     "Lift = confidence(A ⇒ B) / support(B)."),
    ("Match the algorithm with its task:\na. Apriori  b. ID3  c. k-means  d. Linear regression\n1. Predicts a numeric value  2. Partitions data into k clusters  3. Builds a decision tree using information gain  4. Finds frequent itemsets",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Algorithm-task matching is common in KSET papers."),
    ("Consider the statements:\nI. Classification needs labelled training data.\nII. Clustering needs class labels for every object.\nWhich is/are correct?",
     I_II, 0, "Clustering discovers the groups itself."),
    ("Assertion (A): If {milk, bread} is not frequent, {milk, bread, eggs} cannot be frequent.\nReason (R): Every subset of a frequent itemset must be frequent.",
     AR, 0, "This is the Apriori property used for pruning."),
    ("Assertion (A): k-means always finds the globally best clustering.\nReason (R): k-means is sensitive to the choice of initial centroids.",
     AR, 3, "It may converge to a local optimum, so A is false."),
    ("Predicting whether a loan applicant is 'safe' or 'risky' is a ____ task.",
     ["Classification", "Clustering", "Association", "Regression of a continuous value"], 0,
     "The output is a categorical class label."),
    ("Precision is defined as:",
     ["TP / (TP + FP)", "TP / (TP + FN)", "(TP + TN) / total", "TN / (TN + FN)"], 0,
     "It is the fraction of predicted positives that are really positive."),
    ("Summarising the general features of a target class, such as students with high grades, is called:",
     ["Characterization", "Clustering", "Association", "Outlier analysis"], 0,
     "Discrimination compares the target class with contrasting classes."),
]

TOPICS = {
    "Database Recovery Techniques": [("1 · Log-based Recovery, Checkpoints, Shadow Paging and ARIES", RECOVERY)],
    "Data Warehousing and Data Mining": [("1 · Data Warehousing, Schemas and OLAP", WAREHOUSE),
                                         ("2 · Data Mining – Association, Classification, Clustering and Regression", MINING)],
}
