"""Paper 2 · Unit 6 · P2-U6-09 Virtual Memory (2 sub-topics × 30).
Coverage (planner): demand paging, page replacement, frame allocation, thrashing, memory-mapped files.
References: Silberschatz, Galvin & Gagne, Operating System Concepts (10th ed., ch. 10); Andrew S. Tanenbaum, Modern Operating
Systems (page-replacement algorithms). Each set mixes REAL previous-year questions (exact wording and printed option order,
`source` = paper and question number) with new ones. Official answers come from KEA's final keys: Legislative Council Secretariat
2024 (Sr/Jr Programmer P2, Junior Console Operator P2 – booklet A1; final key 09-04-2025) and GTTC 2024 (Lecturer CS – booklet A1,
Technician Gr-III CS – booklet C1; final keys 30-12-2024). KSET 2025 questions are reused from packs/pyq-p2.json; those and the
PGCET answers were worked out by ExamSim."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

DEMAND = [
    ("Consider a computer system that supports 32-bit physical as well as virtual addresses. Now since the space of the physical address is same as the virtual address, the operating system designers would decide to entirely get rid of its virtual memory. Which one of the following is true in this case?",
     ["It is no longer possible to efficiently implement multi-user support.", "It is possible to make CPU scheduling more efficient now.",
      "There would no longer be required for hardware support for memory management.", "It would be possible to make the processor cache organization more efficient now."], 2,
     "Without virtual memory there are no virtual-to-physical translations, so the MMU / page-table hardware is not needed (GATE 2016 question)." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q6"),
    ("The lowest number of page frames that are bound to be allocated in an environment of virtual memory to a running processes is determined by",
     ["the instruction set architecture", "the page size", "the size of the physical memory", "the total number of processes in memory"], 0,
     "The minimum is set by the most memory references a single instruction can make (operands, indirection), i.e. by the ISA." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q18"),
    ("The performance of process in virtual memory depends on the rate at which its components have to be loaded into memory to achieve a low rate of loading of process components virtual memory manager uses the",
     ["Law of locality objects", "Law of locality of pointer", "Thrashing", "Law of locality of reference"], 3,
     "Programs reference a small set of pages at a time (locality of reference), so keeping that set in memory keeps page faults low." + GTTC,
     "GTTC 2024 Lecturer CS · Q53"),
    ("Mapping of file is managed by",
     ["File meta data", "Page table", "Virtual Memory", "File system"], 3,
     "The official key gives the file system, which keeps track of where each file's blocks are (its metadata maps the file to disk blocks)." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q29"),
    ("Which of the following is not correct about the virtual memory management?",
     ["It is not necessary to load all of the segments of a process", "It has no internal fragmentation", "It has large virtual address space",
      "It provides lower degree of multiprogramming"], 3,
     "Virtual memory raises the degree of multiprogramming, since only part of each process need be in memory. (Option 2 holds for segmented virtual memory, which the question refers to.)" + NOTE,
     "KSET 2025 CS&A · Q46"),
    ("Virtual memory is a technique that:",
     ["Allows the execution of processes that are not completely in main memory", "Makes the hard disk faster",
      "Increases the size of the CPU cache", "Removes the need for main memory"], 0,
     PYQ + "Programs can be larger than physical memory, and more programs can run at the same time."),
    ("In demand paging, a page is brought into memory:",
     ["Only when it is needed (referenced)", "Always when the process starts", "At compile time", "When the process ends"], 0,
     "A pager that never brings in a page until it is needed is a 'lazy swapper'."),
    ("When a process refers to a page that is not in main memory, the hardware raises a:",
     ["Page fault (trap to the OS)", "Segmentation fault always", "Deadlock", "Cache hit"], 0, PYQ + "The valid–invalid bit of the page-table entry is 'invalid'."),
    ("Arrange the steps of handling a page fault in order:\n1. Find a free frame\n2. Trap to the OS and check that the reference is valid\n3. Read the page from disk into the frame\n4. Update the page table and restart the instruction",
     ["2, 1, 3, 4", "1, 2, 3, 4", "2, 3, 1, 4", "3, 2, 1, 4"], 0, "If no frame is free, a page-replacement algorithm chooses a victim."),
    ("Starting a process with no pages in memory and bringing in each page only on its first fault is called:",
     ["Pure demand paging", "Prepaging", "Swapping", "Segmentation"], 0, "Prepaging brings in several pages at once to avoid the initial burst of faults."),
    ("Memory access time is 200 ns, the average page-fault service time is 8 ms and the page-fault rate is p. The effective access time is:",
     ["(1 − p) × 200 ns + p × 8 ms", "200 ns + 8 ms", "p × 200 ns + (1 − p) × 8 ms", "8 ms / p"], 0,
     PYQ + "EAT = (1 − p) × memory access + p × page-fault time; even p = 1/1000 makes EAT about 8.2 µs."),
    ("Memory access takes 100 ns, servicing a page fault takes 10 ms, and the page-fault rate is 1 in 100,000 accesses. The effective access time is about:",
     ["200 ns", "100 ns", "10 ms", "1 ms"], 0, "(1 − 0.00001) × 100 + 0.00001 × 10,000,000 ≈ 100 + 100 = 200 ns."),
    ("Copy-on-write lets a parent and child process created by fork():",
     ["Share pages until one of them writes, when a copy of that page is made", "Never share any pages",
      "Write directly to disk", "Share only their stacks"], 0, "vfork() goes further – the parent is suspended and the child uses its address space."),
    ("The 'modify' or 'dirty' bit of a page tells the OS that:",
     ["The page has been changed and must be written to disk before replacement", "The page is invalid",
      "The page is read-only", "The page belongs to the kernel"], 0, PYQ + "An unmodified page can simply be overwritten, halving the page-fault service time."),
    ("Thrashing is a situation in which:",
     ["A process spends more time paging than executing", "The CPU is fully used by useful work",
      "The disk is idle", "Processes deadlock on I/O"], 0, PYQ + "CPU utilisation falls sharply as the degree of multiprogramming rises too far."),
    ("The main cause of thrashing is:",
     ["Processes not having enough frames to hold their working set", "Too many free frames", "A large TLB", "Very small programs"], 0,
     "When the total demand (sum of working-set sizes) exceeds available frames, thrashing starts."),
    ("The set of pages referenced in the most recent Δ page references is called the:",
     ["Working set", "Resident set limit", "Page table", "Swap space"], 0, "Denning's working-set model; Δ is the working-set window."),
    ("A strategy to prevent thrashing by setting upper and lower bounds on each process's page-fault rate is the:",
     ["Page-fault frequency (PFF) scheme", "Banker's algorithm", "Round robin", "Second-chance algorithm"], 0,
     "Too many faults → give the process more frames; too few → take frames away."),
    ("Equal allocation of 93 frames among 5 processes gives each process:",
     ["18 frames, with 3 left as a free-frame buffer", "19 frames", "20 frames", "15 frames"], 0, "93 / 5 = 18 remainder 3."),
    ("Under proportional allocation with 62 free frames, processes of 10 pages and 127 pages get about:",
     ["4 and 57 frames", "31 and 31 frames", "10 and 52 frames", "2 and 60 frames"], 0,
     PYQ + "10/137 × 62 ≈ 4 and 127/137 × 62 ≈ 57."),
    ("With global replacement, a process selects a replacement frame:",
     ["From the set of all frames, even one belonging to another process", "Only from its own frames",
      "Only from kernel frames", "Only from the free list"], 0, "Local replacement chooses only from the process's own frames; global replacement gives better throughput."),
    ("Mapping a disk file into part of a process's virtual address space, so that file I/O becomes ordinary memory access, is called:",
     ["Memory-mapped files", "Spooling", "Overlaying", "Double buffering"], 0, "On Linux it is done with mmap(); several processes can map the same file to share memory."),
    ("Allocating memory to the kernel from physically contiguous pages, in power-of-two blocks, uses the:",
     ["Buddy system", "Working-set model", "LRU algorithm", "FIFO queue"], 0, "The slab allocator is the other kernel scheme, using caches of objects."),
    ("Consider the statements:\nI. Demand paging may increase the degree of multiprogramming.\nII. In demand paging, a page that is never referenced is never loaded.",
     I_II, 2, "Both are advantages of demand paging."),
    ("Consider the statements:\nI. Increasing the degree of multiprogramming always increases CPU utilisation.\nII. Thrashing can be reduced by suspending some processes.",
     I_II, 1, "Beyond a point utilisation drops (thrashing); swapping out processes frees frames for the rest."),
    ("Assertion (A): Programs can run efficiently under demand paging even though only part of them is in memory.\nReason (R): Programs show locality of reference.",
     AR, 0, "Locality keeps the page-fault rate low."),
    ("Assertion (A): Thrashing raises CPU utilisation.\nReason (R): During thrashing, processes keep waiting for the paging device.",
     AR, 3, "Utilisation falls during thrashing because processes are queued for paging I/O."),
    ("Locking a page in memory so that it cannot be replaced is done with a:",
     ["Lock bit", "Dirty bit", "Valid bit", "Reference bit"], 0, "Useful for pages that are the target of an I/O transfer in progress."),
    ("The area of a disk used to hold pages that are not in main memory is called:",
     ["Swap space (backing store)", "Cache", "Register file", "Boot block"], 0, PYQ + "Windows uses a page file; Linux a swap partition or swap file."),
    ("Which of the following is NOT an advantage of virtual memory?",
     ["It always makes every memory access faster", "A program can be larger than physical memory",
      "More programs can run concurrently", "Less I/O is needed to load or swap programs"], 0,
     "A page fault makes that access far slower; the gains come from better memory use."),
]

REPLACE = [
    ("Consider that a virtual memory system uses a FIFO page replacement policy. For a process, it allocates a fixed number of frames. Now consider the following statements.\nA: An increase in the number of page frames that are allocated to a process sometimes leads to an increase in page fault rate.\nB: A few programs do not display the locality of reference.\nWhich one of the following option is correct?",
     ["A is true", "B is false", "Both A & B are false", "Both A & B are true"], 3,
     "A is Belady's anomaly, possible with FIFO; B is also true – some programs (e.g. jumping through large data) show poor locality." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q8"),
    ("Which of the following page replacement algorithms can lead to optimal performance?\na. Least Recently Used (LRU)\nb. Optimal Page Replacement\nc. FIFO\nd. Second Chance",
     ["a, b and c", "b and a", "b, c and d", "a, b, c and d"], 1,
     "The key takes Optimal (the true minimum) and LRU, its best practical approximation; FIFO and second chance can be far from optimal." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q51"),
    ("Identify the incorrect statement regarding the page replacement algorithms and its principle.",
     ["NRU (Not Recently Used) - Removes a page at random from the lowest numbered nonempty class", "FIFO -First In, First Out",
      "LRU -Throw out the page that has been used for the longest time", "Second chance - Simple modification of FIFO"], 2,
     "LRU throws out the page that has NOT been used for the longest time." + NOTE, "PGCET 2023 M.Tech CS · Q70"),
    ("Applying FIFO page replacement for the reference string →7, 0, 1, 2, 0, 3, 0, 4, 2, 3. The main memory can accommodate 3 pages. How many page faults will occur?",
     ["10", "6", "9", "8"], 2,
     "Faults on 7, 0, 1, 2, 3, 0, 4, 2, 3 – only the first re-use of 0 is a hit." + NOTE, "PGCET 2026 CS · Q55"),
    ("Match the following:\ni. Kernel\nii. Belady's anomaly\niii. Paging\niv. Free-space management\n(a) Ensures efficient storage utilization\n(b) Avoids external fragmentation\n(c) Provides basic low-level operations\n(d) Increase in the number of page frames leads to increase in the number of page faults",
     ["i – d, ii – c, iii – b, iv – a", "i – b, ii – d, iii – a, iv – c", "i – c, ii – d, iii – b, iv – a", "i – b, ii – a, iii – d, iv – c"], 2,
     "Kernel = low-level services; Belady = more frames, more faults (FIFO); paging avoids external fragmentation; free-space management uses storage well." + NOTE,
     "KSET 2025 CS&A · Q47"),
    ("The page-replacement algorithm that replaces the page that will not be used for the longest period of time is:",
     ["Optimal (OPT / MIN)", "LRU", "FIFO", "LFU"], 0, PYQ + "It gives the lowest possible fault rate but needs future knowledge, so it is used as a benchmark."),
    ("Belady's anomaly can occur with which page-replacement algorithm?",
     ["FIFO", "LRU", "Optimal", "Any stack algorithm"], 0, "LRU and Optimal are stack algorithms and never show the anomaly."),
    ("For the reference string 1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5 with FIFO replacement, the number of page faults with 3 frames and with 4 frames is:",
     ["9 and 10", "10 and 9", "9 and 9", "8 and 10"], 0, PYQ + "The classic example of Belady's anomaly – more frames, more faults."),
    ("Reference string 7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 2, 1, 2, 0, 1, 7, 0, 1 with 3 frames. The number of page faults under FIFO is:",
     ["15", "12", "9", "20"], 0, "Silberschatz's standard string: FIFO 15, LRU 12, Optimal 9."),
    ("For the same reference string 7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 2, 1, 2, 0, 1, 7, 0, 1 with 3 frames, LRU gives:",
     ["12 page faults", "15 page faults", "9 page faults", "10 page faults"], 0, PYQ + "LRU = 12 lies between Optimal (9) and FIFO (15)."),
    ("For the reference string 7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 2, 1, 2, 0, 1, 7, 0, 1 with 3 frames, the optimal algorithm gives:",
     ["9 page faults", "12 page faults", "15 page faults", "6 page faults"], 0, "No algorithm can do better with 3 frames."),
    ("With 3 frames, initially empty, and LRU replacement, how many page faults occur for the reference string 1, 2, 3, 1, 4, 5?",
     ["5", "4", "6", "3"], 0, "Faults on 1, 2, 3, 4 (replaces 2), 5 (replaces 3); the second reference to 1 is a hit."),
    ("With 3 frames, initially empty, and FIFO replacement, how many page faults occur for the reference string 1, 2, 3, 4, 1, 2?",
     ["6", "4", "5", "3"], 0, PYQ + "4 replaces 1, then 1 replaces 2, then 2 replaces 3 – every reference faults."),
    ("Which hardware support is commonly used to approximate LRU?",
     ["A reference bit for each page", "A dirty bit only", "A second CPU", "A larger TLB"], 0,
     "The bit is set when the page is referenced; the OS clears and checks it periodically."),
    ("The second-chance (clock) algorithm is a modification of:",
     ["FIFO, giving a page with its reference bit set another chance", "LRU, using counters", "Optimal, using future references", "LFU, using counts"], 0,
     "The pointer moves around a circular list, clearing reference bits until it finds a page with bit 0."),
    ("In the enhanced second-chance algorithm, the best page to replace has (reference bit, modify bit) =",
     ["(0, 0)", "(0, 1)", "(1, 0)", "(1, 1)"], 0, PYQ + "(0, 0) – neither recently used nor modified, so it needs no write-back."),
    ("The algorithm that replaces the page with the smallest reference count is:",
     ["LFU (Least Frequently Used)", "MFU (Most Frequently Used)", "LRU", "FIFO"], 0, "MFU replaces the page with the largest count, arguing that a small count means it was just brought in."),
    ("LRU can be implemented exactly using:",
     ["A counter (time-of-use) per page or a stack of page numbers", "Only a dirty bit", "A FIFO queue", "Random selection"], 0,
     "With a stack, the most recently used page is on top and the LRU page at the bottom."),
    ("Page buffering algorithms keep:",
     ["A pool of free frames, so a faulting page can be read in before the victim is written out", "All pages permanently in memory",
      "Only kernel pages", "No free frames at all"], 0, "This reduces the time a process waits on a page fault."),
    ("Consider the statements:\nI. LRU is a stack algorithm.\nII. FIFO never suffers from Belady's anomaly.",
     I_II, 0, "FIFO can suffer from the anomaly; LRU and Optimal cannot."),
    ("Consider the statements:\nI. The optimal algorithm needs knowledge of future references.\nII. The optimal algorithm is used mainly to compare other algorithms.",
     I_II, 2, "Both are correct."),
    ("Assertion (A): LRU does not suffer from Belady's anomaly.\nReason (R): The set of pages in memory with n frames is always a subset of the set with n + 1 frames.",
     AR, 0, "That 'inclusion property' defines stack algorithms."),
    ("Assertion (A): FIFO replaces the page that has been used least recently.\nReason (R): FIFO replaces the oldest page in memory.",
     AR, 3, "FIFO replaces the oldest loaded page, even if it is used heavily – that is LRU's idea, not FIFO's."),
    ("A page reference string of length 20 contains 6 distinct pages. With any page-replacement algorithm and frames initially empty, the minimum number of page faults is:",
     ["6", "20", "3", "0"], 0, PYQ + "Each distinct page must be loaded at least once (compulsory faults)."),
    ("For n distinct pages in a reference string of length p, the maximum number of page faults is:",
     ["p", "n", "p − n", "n/2"], 0, "At worst every reference is a fault."),
    ("Which statement about increasing the number of frames given to a process is generally true for LRU?",
     ["The number of page faults never increases", "The number of page faults always increases", "It causes Belady's anomaly", "It has no effect on faults"], 0,
     "LRU is a stack algorithm, so more frames never hurt."),
    ("With 4 frames and Optimal replacement, how many page faults occur for 1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5?",
     ["6", "8", "10", "7"], 0, "Faults: 1, 2, 3, 4 (compulsory), 5 (replaces 4, used last), and 4 again near the end = 6. FIFO with 4 frames gives 10."),
    ("Match the algorithm with its idea:\na. FIFO  b. LRU  c. Optimal  d. LFU\n1. Oldest page in memory  2. Page not used for the longest time  3. Page that will not be used for the longest time  4. Page with the smallest use count",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "A frequent KEA / KSET matching question."),
    ("In page-replacement terms, a 'victim' page is:",
     ["The page chosen to be removed from memory to make room", "A page with a hardware error", "The first page of a program", "A kernel page"], 0,
     "If the victim's dirty bit is set it is written to disk first."),
    ("Which algorithm is easiest to implement but often performs poorly?",
     ["FIFO", "Optimal", "LRU with counters", "LRU with a stack"], 0, PYQ + "It needs only a queue of the pages in memory."),
]

TOPICS = {
    "Virtual Memory": [("1 · Demand Paging, Page Faults, Frame Allocation and Thrashing", DEMAND),
                       ("2 · Page Replacement – FIFO, Optimal, LRU and Approximations", REPLACE)],
}
