"""Paper 2 · Unit 6 · P2-U6-15 Windows Operating System (2 sub-topics × 30).
Coverage (planner): design principles, system components, terminal services, fast user switching, file system, networking.
References: Silberschatz, Galvin & Gagne, Operating System Concepts (10th ed., ch. 21 'Windows 10'); Microsoft Learn documentation
(Windows architecture, NTFS, Remote Desktop Services, sfc, chkdsk). Each set mixes REAL previous-year questions (exact wording and
printed option order, `source` = paper and question number) with new ones. Official answers come from KEA's final keys:
Legislative Council Secretariat 2024 Computer Operator P2 (booklet A1; final key 09-04-2025) and GTTC 2024 Officer / Assistant
Kannada-English-Computer paper (booklet A1; final key 30-12-2024). KEA 2026 Kannada-English-Computer and PGCET MCA questions have no
published key; their answers were worked out by ExamSim."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

DESIGN = [
    ("Which of the following components in Windows handles communication between hardware and operating system?",
     ["Windows Explorer", "Kernel", "Command prompt", "Active directory"], 1,
     "The kernel (with the hardware abstraction layer below it) manages the hardware for the rest of the system; Explorer is only the shell." + NOTE,
     "KEA 2026 KEC-1 (NHK, 26 Apr 2026) · Q99"),
    ("Windows XP was released in the year :",
     ["2000", "1998", "1999", "2001"], 3,
     "Windows XP came out in October 2001 and introduced fast user switching for home users." + NOTE, "PGCET 2023 MCA · Q35"),
    ("Which mode loads the minimal set of drivers when starting windows operating system?",
     ["Safe mode", "Normal mode", "VGA mode", "Network support mode"], 0,
     "Safe mode starts Windows with only essential drivers and services, for troubleshooting." + NOTE, "PGCET 2025 MCA · Q46"),
    ("What is the main purpose of the Windows Pre-installation Environment (WinPE)?\n(a) To boot a system with a graphical user interface.\n(b) To perform disk management tasks\n(c) To connect windows update servers\n(d) To provide a minimal OS environment for installation, recovery and troubleshooting\nWhich of the above statement/statements is/are correct?",
     ["c and d only", "d only", "a only", "b only"], 1,
     "WinPE is a small Windows used to install, deploy and repair Windows." + GTTC, "GTTC 2024 Officer/Asst Gr-III KEC · Q94"),
    ("In windows, which feature allows multiple virtual desktops to be used for better organisations of open applications and windows?",
     ["SPAN asset", "Task View", "Aero peek", "Control Panel"], 1,
     "Task View (Win + Tab) shows open windows and lets you create virtual desktops (Ctrl + Win + D)." + GTTC, "GTTC 2024 Officer/Asst Gr-III KEC · Q98"),
    ("The Windows NT family of operating systems (the base of Windows 2000, XP, 7, 10 and 11) was designed by a team led by:",
     ["Dave Cutler", "Bill Gates alone", "Linus Torvalds", "Dennis Ritchie"], 0,
     PYQ + "Cutler had earlier designed VMS at DEC; Windows NT 3.1 was released in 1993."),
    ("Which of the following is NOT one of the design goals of Windows listed by Silberschatz?",
     ["Using a single-user, single-tasking design", "Security", "Reliability and compatibility", "Extensibility and portability"], 0,
     "Others include performance, international support, energy efficiency and dynamic device support."),
    ("The Windows layer that hides differences between hardware chipsets from the kernel is the:",
     ["Hardware Abstraction Layer (HAL)", "Registry", "Shell", "Win32 subsystem"], 0, PYQ + "Only the HAL needs to change when Windows is moved to new hardware."),
    ("The collection of Windows kernel-mode services such as the object manager, virtual-memory manager, I/O manager and security reference monitor is called the:",
     ["Executive", "Shell", "Task Manager", "Explorer"], 0, "The executive runs above the kernel and the HAL."),
    ("The Windows component that checks every access to an object against its access-control list is the:",
     ["Security reference monitor", "Cache manager", "Plug-and-Play manager", "Power manager"], 0, PYQ + "Each user has an access token with a security ID (SID)."),
    ("Windows' hierarchical database of configuration settings for hardware, software and users is the:",
     ["Registry", "Master File Table", "Boot sector", "Page file"], 0, "Its main hives include HKEY_LOCAL_MACHINE and HKEY_CURRENT_USER; it is edited with regedit."),
    ("Windows schedules threads using priority levels numbered:",
     ["0 to 31 – 16 to 31 for real-time and 1 to 15 for variable priority", "1 to 10", "0 to 99 with 0 highest", "Only two levels"], 0,
     PYQ + "The scheduler (dispatcher) is preemptive; priority 0 is used by the zero-page thread."),
    ("In Windows, the message-passing facility used between processes on the same machine, e.g. between a client and a subsystem server, is:",
     ["ALPC (Advanced Local Procedure Call)", "SMTP", "ARP", "FTP"], 0, "It replaced the older LPC facility."),
    ("Which statement about the Windows kernel structure is correct?",
     ["It is a hybrid: a layered, object-based kernel with many services in kernel mode", "It is a pure microkernel with all drivers in user mode",
      "It is a monolithic kernel with no layers", "It has no kernel mode"], 0, PYQ + "Graphics were moved into kernel mode in NT 4.0 for speed."),
    ("Windows Subsystem for Linux (WSL) lets users:",
     ["Run Linux command-line tools and distributions on Windows", "Run Windows inside a phone", "Replace NTFS", "Remove the kernel"], 0,
     "WSL 2 runs a real Linux kernel in a lightweight virtual machine."),
    ("Hyper-V in Windows is a:",
     ["Type-1 hypervisor for running virtual machines", "File system", "Web browser", "Antivirus"], 0, PYQ + "Virtualisation-based security also uses it."),
    ("The keyboard shortcut Ctrl + Shift + Esc opens the:",
     ["Task Manager", "Control Panel", "File Explorer", "Run dialog"], 0, "Win + R opens Run; Win + E opens File Explorer."),
    ("User Account Control (UAC) in Windows:",
     ["Asks for permission before a program makes changes that need administrator rights", "Creates new user accounts automatically", "Encrypts the disk", "Speeds up booting"], 0,
     PYQ + "It applies the principle of least privilege."),
    ("Windows Update, Windows Defender (Microsoft Defender) and BitLocker respectively provide:",
     ["Patches, anti-malware protection and full-disk encryption", "Games, email and printing", "Backup, compression and paging", "Networking, sound and graphics"], 0,
     "BitLocker usually uses the TPM chip to protect keys."),
    ("In Windows, 'fast user switching' allows:",
     ["Several users to stay logged on, switching between sessions without closing programs", "Only one user per computer", "Users to change passwords quickly", "The PC to restart faster"], 0,
     PYQ + "Each user gets a separate session; it is built on Terminal Services technology."),
    ("Terminal Services, now called Remote Desktop Services, lets a user:",
     ["Run a desktop session on a remote Windows computer over the network", "Print only", "Copy files to USB", "Format disks"], 0,
     "It uses the Remote Desktop Protocol (RDP), by default on TCP port 3389."),
    ("The protocol used by Windows Remote Desktop is:",
     ["RDP", "SMTP", "SNMP", "POP3"], 0, PYQ + "The client program is mstsc.exe."),
    ("Consider the statements:\nI. Windows supports multiple user sessions at the same time through Terminal Services.\nII. Fast user switching closes the first user's programs before the second user logs on.",
     I_II, 0, "Fast user switching keeps the first user's programs running in the background."),
    ("Assertion (A): Windows can be moved to a new hardware platform with relatively little change.\nReason (R): Hardware-dependent code is isolated in the HAL and a few kernel parts.",
     AR, 0, "Portability was one of the original NT design goals."),
    ("Assertion (A): In Windows, all device drivers run in user mode.\nReason (R): Windows has a kernel mode and a user mode.",
     AR, 3, "Most drivers run in kernel mode (user-mode drivers exist only for some devices)."),
    ("Match:\na. HAL  b. Executive  c. Registry  d. Shell (Explorer)\n1. Hides hardware differences  2. Kernel-mode services  3. Configuration database  4. User interface",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "A common component-matching question."),
    ("Windows provides several environmental subsystems; the main one, used by almost all applications, is:",
     ["Win32 (Windows API) subsystem", "POSIX only", "OS/2 subsystem", "MS-DOS subsystem only"], 0, "Older versions also had POSIX and OS/2 subsystems."),
    ("Plug and Play in Windows means:",
     ["Devices are recognised and configured automatically when connected", "All devices must be configured manually", "Only keyboards work", "Drivers are never needed"], 0,
     PYQ + "The PnP manager loads the right driver."),
    ("The Windows component that keeps a log of system, security and application events is the:",
     ["Event Viewer", "Paint", "Notepad", "Calculator"], 0, "Administrators use it to diagnose problems."),
    ("Windows 10 and Windows 11 were released in:",
     ["2015 and 2021", "2012 and 2019", "2009 and 2015", "2001 and 2007"], 0, PYQ + "Windows 7 – 2009; Windows 8 – 2012."),
]

FILES_NET = [
    ("Which tool would you use to check the corrupted system files in window?",
     ["Disk Cleanup", "CHKDSK", "sfc/Scannow", "Device Manager"], 2,
     "System File Checker (sfc /scannow) scans and repairs protected Windows system files." + KLC, "Legislative Council 2024 Computer Operator P2 · Q49"),
    ("Which command-line tool in Windows allows you to test the integrity of system files and repair missing or corrupted files?\n(a) Diskpart\n(b) Ipconfig\n(c) CHKDSK\n(d) SFC / scannow",
     ["a and c only", "d only", "c only", "d and b only"], 1,
     "sfc /scannow repairs system files; CHKDSK checks the file system and disk; Diskpart manages partitions; Ipconfig shows network settings." + GTTC,
     "GTTC 2024 Officer/Asst Gr-III KEC · Q97"),
    ("Which command line tool is used in Windows to specifically manage active directory domains and join a computer to a domain?",
     ["netsh.exe", "netdom.exe", "ipconfig.exe", "dsquery.exe"], 1,
     "netdom joins computers to domains and manages trusts; dsquery searches Active Directory; netsh configures networking." + NOTE, "KEA 2026 KEC-2 (HK, 27 Apr 2026) · Q100"),
    ("The native file system of modern Windows is:",
     ["NTFS", "ext4", "HFS+", "APFS"], 0, PYQ + "FAT32 and exFAT are still supported for removable drives; ReFS is used on servers."),
    ("In NTFS, the main structure that holds a record for every file and directory on the volume is the:",
     ["Master File Table (MFT)", "Inode table", "FAT", "Superblock"], 0, "Small files can be stored entirely inside their MFT record."),
    ("NTFS recovers quickly after a crash because it:",
     ["Logs metadata changes in a log file (journaling)", "Has no metadata", "Stores everything twice", "Uses only FAT chains"], 0,
     PYQ + "It uses transaction-based logging of metadata updates."),
    ("Which feature is supported by NTFS but NOT by FAT32?",
     ["File-level permissions (ACLs), encryption (EFS) and compression", "Storing files", "Directories", "Long file names"], 0, "FAT32 also limits single files to 4 GB."),
    ("The NTFS feature that encrypts individual files and folders for a user is:",
     ["EFS (Encrypting File System)", "BitLocker", "Disk Cleanup", "Defragmenter"], 0, PYQ + "BitLocker encrypts the whole volume."),
    ("Volume Shadow Copy in Windows is used to:",
     ["Take point-in-time snapshots of volumes for backup and 'Previous versions'", "Hide files", "Format disks", "Partition disks"], 0,
     "System Restore points also use it."),
    ("A Windows share whose name ends with '$', such as C$ or ADMIN$, is:",
     ["A hidden share that does not appear when browsing the network", "A read-only share", "A printer share", "A corrupted share"], 0,
     PYQ + "Administrative shares are created automatically."),
    ("When both share permissions and NTFS permissions apply to a folder accessed over the network, the effective permission is:",
     ["The more restrictive of the two", "The less restrictive of the two", "Always Full Control", "Only the share permission"], 0, "Locally, only NTFS permissions apply."),
    ("The Windows file-sharing protocol, also used by Samba on Linux, is:",
     ["SMB / CIFS", "NFS", "FTP", "SMTP"], 0, PYQ + "SMB 3 adds encryption."),
    ("Active Directory in Windows Server is a:",
     ["Directory service that stores users, computers and policies for a domain", "Web browser", "File system", "Antivirus"], 0,
     "It uses LDAP for queries and Kerberos for authentication."),
    ("In a Windows domain, the server that authenticates users and holds a copy of Active Directory is the:",
     ["Domain controller", "File server only", "Print server", "DHCP client"], 0, PYQ + "Group Policy settings are pushed from the domain."),
    ("The authentication protocol used by default in Active Directory domains is:",
     ["Kerberos", "Telnet", "FTP", "ARP"], 0, "NTLM is the older challenge–response protocol."),
    ("A peer-to-peer group of Windows computers without a central server is a:",
     ["Workgroup", "Domain", "Forest", "Tree"], 0, PYQ + "Domains are managed centrally; forests contain one or more domain trees."),
    ("The Windows command that shows the computer's IP address, subnet mask and default gateway is:",
     ["ipconfig", "chkdsk", "sfc", "diskpart"], 0, "ipconfig /all shows details; ipconfig /flushdns clears the DNS cache."),
    ("The Windows networking programming interface for TCP/IP sockets is:",
     ["Winsock", "NTFS", "Registry", "HAL"], 0, PYQ + "Windows also supports named pipes and RPC for networking."),
    ("Which Windows command checks a disk for file-system errors and bad sectors?",
     ["chkdsk", "ipconfig", "ping", "tracert"], 0, "chkdsk /f fixes errors; /r also locates bad sectors."),
    ("The Windows tool used to create, delete and format partitions from the command line is:",
     ["diskpart", "netstat", "tasklist", "whoami"], 0, PYQ + "Disk Management is the graphical equivalent."),
    ("The 'Map network drive' feature in Windows lets a user:",
     ["Assign a drive letter to a shared folder on another computer", "Draw a map", "Defragment a drive", "Create a new partition"], 0,
     "The command-line equivalent is 'net use'."),
    ("Consider the statements:\nI. NTFS supports access-control lists on files and folders.\nII. NTFS has no journaling, so a full disk check is always needed after a crash.",
     I_II, 0, "NTFS is a journaling file system."),
    ("Assertion (A): A file on an NTFS drive can be protected so that only selected users may read it.\nReason (R): NTFS stores an access-control list with each file.",
     AR, 0, "Permissions are set on the Security tab of the file's Properties."),
    ("Assertion (A): FAT32 is preferred for an internal Windows system drive.\nReason (R): FAT32 supports file permissions and encryption.",
     AR, 3, "Both are false – NTFS is used for system drives because FAT32 lacks permissions, encryption and journaling."),
    ("Match the Windows command with its use:\na. ping  b. tracert  c. netstat  d. nslookup\n1. Test reachability  2. Show the route to a host  3. Show network connections and ports  4. Query DNS",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Network-command matching is common."),
    ("In Windows, the 'Previous Versions' feature restores older copies of files using:",
     ["Volume shadow copies or File History", "The recycle bin only", "The registry", "The BIOS"], 0, "File History backs up libraries to another drive."),
    ("ReFS (Resilient File System) in Windows Server mainly improves:",
     ["Data integrity and resilience for large storage", "Gaming performance", "Printing", "Email delivery"], 0, PYQ + "It uses checksums for metadata and optionally data."),
    ("Which statement about NTFS file names is correct?",
     ["Names can be up to 255 characters and are case-preserving but case-insensitive by default", "Names are limited to 8.3 characters",
      "Names are case-sensitive by default", "Names cannot contain spaces"], 0, "The old 8.3 limit belonged to MS-DOS FAT."),
    ("Group Policy in a Windows domain is used to:",
     ["Centrally control settings and security for users and computers", "Create partitions", "Write documents", "Browse the web"], 0, PYQ + "Policies are stored in Group Policy Objects (GPOs)."),
    ("The Windows Firewall (Windows Defender Firewall) works by:",
     ["Allowing or blocking network traffic according to rules", "Encrypting files", "Repairing system files", "Defragmenting disks"], 0,
     "Rules can be set per program, port or network profile (domain, private, public)."),
]

TOPICS = {
    "Windows Operating System": [("1 · Design Principles, System Components, Terminal Services and Fast User Switching", DESIGN),
                                 ("2 · NTFS File System, Tools and Networking", FILES_NET)],
}
