"""Paper 2 · Unit 6 · P2-U6-03 Process Management & IPC and P2-U6-04 Process Synchronization (2 topics × 2 sub-topics × 30).
References: Silberschatz, Galvin & Gagne, Operating System Concepts (10th ed., chs. 3, 6, 7); William Stallings, Operating
Systems: Internals and Design Principles; A. S. Tanenbaum, Modern Operating Systems.
Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question number)
with new questions. Official answers come from KEA's final keys: Legislative Council Secretariat 2024 (Computer Operator P2,
Sr/Jr Programmer P2, Junior Console Operator P2, Data Entry Operator P2 – booklet A1; final key 09-04-2025) and GTTC 2024
(Technician Gr-III CS – booklet C1, Lecturer CS – booklet A1; final keys 30-12-2024). KSET 2024/2025 questions are reused
from packs/pyq-p2.json (answers worked out by ExamSim). Obvious printing typos are corrected."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

PROCESS = [
    # --- real previous-year questions (official keys) ---
    ("Identify the correct sequence of different states of process in operating system.",
     ["Running → Ready → Waiting → Terminate", "Running → Waiting → Ready → Terminate", "Ready → Waiting → Running → Terminate", "Ready → Running → Waiting → Terminate"], 3,
     "A process is admitted to ready, dispatched to running, may wait for I/O, and finally terminates." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q14"),
    ("In a time share operating system, when the time slot assigned to a process is completed, the process switches from current state to ____.",
     ["Suspended State", "Terminated State", "Ready State", "Blocked State"], 2,
     "A timer interrupt preempts the running process and puts it back in the ready queue." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q5"),
    ("What is the ready state of a process?",
     ["The process is being created", "Instructions are being executed", "Process is waiting to be assigned to a CPU", "The process is waiting for some event to occur"], 2,
     "New = being created; running = executing; waiting = waiting for an event; ready = waiting for the CPU." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q26"),
    ("When a program is loaded into the memory and it becomes a process, it can be divided into which of the section?\ni. Stack  ii. Heap  iii. Text  iv. Data",
     ["i", "i, ii", "i, ii, iii", "i, ii, iii, iv"], 3,
     "A process in memory has text (code), data, heap and stack sections." + GTTC,
     "GTTC 2024 Lecturer CS · Q50"),
    ("A process current activity is represented by\ni. Program counter\nii. Contents of process register\niii. Stack\niv. Data section",
     ["i", "i, ii", "i, ii, iii", "i, ii, iii, iv"], 1,
     "Silberschatz: the current activity is represented by the value of the program counter and the contents of the processor's registers." + GTTC,
     "GTTC 2024 Lecturer CS · Q51"),
    ("Order the following steps of process creation in an operating system.\na. Assigning a Process Control Block (PCB) to the process\nb. Loading the process in memory\nc. Assigning the process ID\nd. Creating a new entry in process table",
     ["a → c → d → b", "c → a → d → b", "c → d → a → b", "b → d → a → c"], 2,
     "KEA's key: give the process an ID, make its process-table entry, set up its PCB, then load it into memory." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q40"),
    ("In a computer system that consists of n number of CPUs, the maximum processes that can exist in the ready state would be",
     ["Independent of n", "2n", "n^2", "n"], 0,
     "At most n processes can be running, but any number may wait in the ready queue." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q7"),
    ("Which of the following does not interrupt a running process?",
     ["Power failure", "Scheduler process", "A device", "Timer"], 1,
     "The scheduler runs only after an interrupt or system call gives control to the OS; it does not itself interrupt a process." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q95"),
    ("The total time taken for switching between the user & the Kernel modes of execution is t₁, while the total time taken for switching between two processes is t₂. Out of the following, which one is true?",
     ["t₂ = t₁", "t₂ > t₁", "t₂ < t₁", "we cannot say anything about the relation between t₂ & t₁"], 1,
     "A process switch includes a mode switch plus saving and restoring the whole context, so it takes longer." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q17"),
    # --- new questions ---
    ("A process is best defined as:",
     ["A program in execution", "A file stored on disk", "A compiled object module", "A set of instructions on paper"], 0,
     PYQ + "A program is a passive entity; a process is active, with a program counter and resources."),
    ("A running process moves to the waiting (blocked) state when it:",
     ["Requests I/O or waits for some event", "Uses up its time slice", "Is admitted by the long-term scheduler", "Finishes execution"], 0,
     "When the I/O or event completes, it moves to the ready state."),
    ("On a single CPU, how many processes can be in the running state at one instant?",
     ["Only one", "Any number", "Exactly two", "None"], 0,
     "Many processes may be ready or waiting."),
    ("Which of the following is NOT normally stored in a Process Control Block (PCB)?",
     ["The source code of the program", "Process state and program counter", "CPU registers and scheduling information", "Memory-management and accounting information"], 0,
     PYQ + "The PCB also holds I/O status information such as open files."),
    ("A context switch involves:",
     ["Saving the state of the current process in its PCB and loading the saved state of the next process", "Copying a file", "Compiling a program", "Switching the computer off and on"], 0,
     PYQ + "Context-switch time is pure overhead – no useful work is done."),
    ("The long-term (job) scheduler mainly controls:",
     ["The degree of multiprogramming – how many processes are in memory", "Which ready process gets the CPU next", "Disk-arm movement", "Page replacement"], 0,
     PYQ + "It runs much less often than the CPU scheduler."),
    ("The short-term (CPU) scheduler:",
     ["Selects a process from the ready queue and allocates the CPU to it; it runs very frequently", "Admits new jobs into memory", "Swaps processes to disk", "Creates new users"], 0,
     "It may run every few milliseconds, so it must be fast."),
    ("Swapping a partially executed process out of memory and later back in is done by the:",
     ["Medium-term scheduler", "Long-term scheduler", "Short-term scheduler", "Dispatcher"], 0,
     "Swapping reduces the degree of multiprogramming temporarily."),
    ("A process that spends more time doing I/O than computation is called:",
     ["I/O-bound", "CPU-bound", "Zombie", "Orphan"], 0,
     "The long-term scheduler should admit a good mix of I/O-bound and CPU-bound processes."),
    ("Memory allocated dynamically at run time (e.g. with malloc or new) comes from the process's:",
     ["Heap", "Stack", "Text section", "PCB"], 0,
     "The heap grows upward; the stack, holding local variables and return addresses, grows downward."),
    ("Local variables and function parameters of a process are kept in its:",
     ["Stack", "Heap", "Text section", "Data section"], 0,
     "Global variables are in the data section."),
    ("The module that gives control of the CPU to the process chosen by the short-term scheduler is the:",
     ["Dispatcher", "Loader", "Long-term scheduler", "Linker"], 0,
     PYQ + "The time it takes is called dispatch latency."),
    ("In the seven-state process model, a process that is swapped out to disk while waiting for an event is in the:",
     ["Blocked/Suspend state", "Ready state", "Running state", "Exit state"], 0,
     "Stallings: Ready/Suspend and Blocked/Suspend are the two suspended states."),
    ("The queue of all processes residing in main memory and waiting to execute is the:",
     ["Ready queue", "Job queue", "Device queue", "Print queue"], 0,
     "Processes waiting for a particular I/O device are in that device's queue."),
    ("Match the scheduler with its job:\na. Long-term scheduler  b. Short-term scheduler  c. Medium-term scheduler  d. Dispatcher\n1. Switches context and jumps to the user program  2. Swaps processes out of and into memory  3. Selects a process from the ready queue  4. Selects jobs from the pool to load into memory",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Scheduler matching appears in KSET papers."),
    ("Consider the statements:\nI. A program is a passive entity, while a process is an active entity.\nII. Two processes can never run the same program.\nWhich is/are correct?",
     I_II, 0, "Several users can run separate processes of the same program, e.g. a browser."),
    ("Assertion (A): Context-switch time is pure overhead.\nReason (R): The system does no useful work for any user process while switching.",
     AR, 0, "That is why context switches should be fast and not too frequent."),
    ("Assertion (A): When its I/O completes, a waiting process moves directly to the running state.\nReason (R): After its I/O completes, a process is placed in the ready queue.",
     AR, 3, "It goes to ready and must wait for the scheduler, so A is false."),
    ("A newly created process that the OS has not yet admitted to the pool of executable processes is in the:",
     ["New state", "Ready state", "Running state", "Terminated state"], 0,
     "The long-term scheduler admits it to the ready state."),
    ("Which transition can occur directly in the five-state process model?",
     ["Running → Ready (on a timer interrupt)", "Waiting → Running", "New → Running", "Terminated → Ready"], 0,
     PYQ + "Waiting processes must first become ready."),
    ("The time the dispatcher takes to stop one process and start another is called:",
     ["Dispatch latency", "Turnaround time", "Seek time", "Burst time"], 0,
     "It should be as short as possible."),
]

IPC = [
    # --- real previous-year questions ---
    ("When a message is sent to a mailbox, the mailbox may be full. If the mailbox is not full, the message is copied to the mailbox and the sending thread continues. If the mailbox is full, then which of the following options does the sending thread have?",
     ["Wait indefinitely until there is room in the mailbox", "Wait at most n milliseconds", "Do not wait at all but rather return immediately", "All of the above"], 3,
     "Silberschatz (Windows ALPC / Mach): the sender may block, block with a timeout, or return immediately." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q10"),
    ("The OS environment which permits many processors active at the same time is.",
     ["Multiprogramming", "Time-sharing", "Multiprocessing", "Multitasking"], 2,
     "Multiprocessing uses two or more CPUs at once." + KLC,
     "Legislative Council 2024 Data Entry Operator P2 · Q73"),
    ("Which of the following is a type of technique in which dumb terminals are connected to a central computer system?",
     ["Time-sharing", "Message passing", "Batch environment", "User environment"], 0,
     "Many users at terminals share one central computer in time slices." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q78"),
    ("Match the following:\ni. Context switching\nii. Semaphores\niii. Process synchronization\niv. Message passing\n(a) process communicate by sending and receiving messages\n(b) co-ordination of the execution of multiple processes sharing the resources\n(c) enables multiple processes to share a single CPU\n(d) helps to prevent race condition",
     ["i – a, ii – b, iii – c, iv – d", "i – b, ii – c, iii – d, iv – a", "i – c, ii – d, iii – b, iv – a", "i – c, ii – d, iii – a, iv – b"], 2,
     "Context switching shares the CPU; semaphores prevent races; synchronisation coordinates; message passing communicates." + NOTE,
     "KSET 2025 CS&A · Q48"),
    # --- new questions ---
    ("In UNIX, the fork() system call:",
     ["Creates a child process that is a copy of the parent; it returns 0 in the child and the child's PID in the parent", "Replaces the current program with a new one", "Terminates the parent", "Creates a new thread only"], 0,
     PYQ + "A negative return value means fork() failed."),
    ("If a program calls fork() three times in sequence (each call made by every existing process), the total number of processes, including the original, is:",
     ["8", "3", "4", "6"], 0,
     PYQ + "Each fork doubles the count: 2³ = 8 (7 new child processes)."),
    ("How many times is 'hello' printed?\nint main() { fork(); fork(); printf(\"hello\\n\"); }",
     ["4", "2", "3", "8"], 0,
     "Two forks give 2² = 4 processes, and each prints once."),
    ("The exec() family of system calls:",
     ["Replaces the calling process's memory image with a new program", "Creates a new process", "Waits for a child", "Sends a signal"], 0,
     "fork() followed by exec() is how a shell runs a command."),
    ("A parent process waits for its child to finish by calling:",
     ["wait()", "exec()", "kill()", "pipe()"], 0,
     "wait() also collects the child's exit status."),
    ("A process that has terminated but whose parent has not yet called wait() is a(n):",
     ["Zombie process", "Orphan process", "Daemon", "Thread"], 0,
     PYQ + "Its entry stays in the process table until the parent collects the exit status."),
    ("A process whose parent has terminated without waiting for it is a(n):",
     ["Orphan process – adopted by init (systemd) in Linux", "Zombie process", "Kernel thread", "Daemon only"], 0,
     PYQ + "init periodically calls wait() to clean up such children."),
    ("When a parent terminates, some systems also terminate all its children. This is called:",
     ["Cascading termination", "Context switching", "Swapping", "Spooling"], 0,
     "It is normally initiated by the operating system."),
    ("Which is NOT a reason for allowing processes to cooperate?",
     ["To increase the number of system crashes", "Information sharing", "Computation speed-up", "Modularity and convenience"], 0,
     "Cooperating processes need IPC."),
    ("The two fundamental models of interprocess communication are:",
     ["Shared memory and message passing", "Paging and segmentation", "FCFS and Round Robin", "Polling and DMA"], 0,
     PYQ + "Asked often in KSET and KEA papers."),
    ("Compared with message passing, shared-memory IPC is generally:",
     ["Faster, because system calls are needed only to set up the shared region", "Slower, because every access needs a system call", "Impossible on a single computer", "Used only between computers on a network"], 0,
     "Message passing is easier to implement in distributed systems."),
    ("In indirect communication, messages are sent to and received from:",
     ["Mailboxes (ports)", "The CPU registers directly", "The printer queue", "The page table"], 0,
     "In direct communication, each process names the other explicitly."),
    ("When both send() and receive() are blocking, the arrangement is called a:",
     ["Rendezvous", "Deadlock", "Race condition", "Context switch"], 0,
     "Blocking = synchronous; non-blocking = asynchronous."),
    ("A message queue that can never hold any waiting message (the sender must block until the receiver takes it) has:",
     ["Zero capacity", "Bounded capacity", "Unbounded capacity", "Infinite buffering"], 0,
     "Zero-capacity systems are called message systems with no buffering."),
    ("An ordinary (anonymous) pipe in UNIX:",
     ["Is unidirectional and is usually used between a parent and its child", "Can be used by any unrelated processes on the internet", "Is bidirectional by default", "Survives after both processes exit"], 0,
     PYQ + "Named pipes (FIFOs) can be used by unrelated processes and remain in the file system."),
    ("The shell command ls | wc -l connects the two programs using a:",
     ["Pipe", "Socket on a remote host", "Semaphore", "Mailbox in the kernel only"], 0,
     "The output of ls becomes the input of wc."),
    ("A socket is identified by:",
     ["An IP address together with a port number", "A file name only", "A process ID only", "A semaphore value"], 0,
     PYQ + "Sockets are used for client–server communication across a network."),
    ("Well-known services such as HTTP (80) and FTP (21) listen on port numbers:",
     ["Below 1024", "Above 65535", "Between 50000 and 60000 only", "That change every second"], 0,
     "Ports below 1024 are well-known ports."),
    ("The IP address 127.0.0.1 used by a client to reach a server on the same machine is called the:",
     ["Loopback address", "Broadcast address", "Gateway address", "MAC address"], 0,
     "Useful for testing client–server programs locally."),
    ("A Remote Procedure Call (RPC) lets a process:",
     ["Call a procedure on another computer as if it were a local call; client and server stubs marshal the parameters", "Share memory on one computer only", "Run only batch jobs", "Avoid the network completely"], 0,
     PYQ + "External Data Representation (XDR) handles differences such as byte order."),
    ("Packing procedure parameters into a form that can be sent over a network is called:",
     ["Marshalling", "Swapping", "Paging", "Spooling"], 0,
     "The server stub unmarshals them."),
    ("In UNIX, signals such as SIGKILL and SIGINT are used to:",
     ["Notify a process that a particular event has occurred", "Allocate memory", "Format a disk", "Compile programs"], 0,
     "Ctrl + C sends SIGINT to the foreground process."),
    ("Match the IPC mechanism with its description:\na. Shared memory  b. Message passing  c. Pipe  d. Socket\n1. Endpoint identified by an IP address and port  2. A conduit such as ls | wc  3. Exchanging data with send() and receive()  4. A memory region accessible to several processes",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "IPC matching is common in KSET papers."),
    ("Consider the statements:\nI. fork() returns 0 in the child process.\nII. exec() creates a new process.\nWhich is/are correct?",
     I_II, 0, "exec() replaces the current program; it does not create a process."),
    ("Assertion (A): A zombie process still occupies an entry in the process table.\nReason (R): Its exit status must be kept until the parent calls wait().",
     AR, 0, "Too many zombies can fill the process table."),
    ("Which system call is used in UNIX to create an ordinary pipe?",
     ["pipe()", "fork()", "socket()", "mmap()"], 0,
     "pipe(fd) gives a read end fd[0] and a write end fd[1]."),
]

CRITICAL = [
    # --- real previous-year questions ---
    ("In the following execution:\nsignal(mutex);\ncritical section\nwait(mutex);\nSuppose that a process omits the wait(mutex), or the signal(mutex), or both. In this case",
     ["Process will starve to enter critical section", "Several processes may be executing in critical section", "Either mutual exclusion is violated or deadlock will occur", "Process will not starve to enter critical section"], 2,
     "Silberschatz: interchanging or omitting wait() and signal() violates mutual exclusion or causes deadlock." + GTTC,
     "GTTC 2024 Lecturer CS · Q56"),
    ("Match the following:\na. Critical region\nb. Wait signal\nc. Working set\nd. Deadlock\n(i) Hoare's monitor\n(ii) Mutual exclusion\n(iii) Principle of locality\n(iv) Circular wait",
     ["a – iv, b – i, c – iii, d – ii", "a – ii, b – i, c – iii, d – iv", "a – i, b – ii, c – iii, d – iv", "a – iv, b – iii, c – i, d – ii"], 1,
     "Critical regions need mutual exclusion; wait/signal are Hoare-monitor operations; the working set rests on locality; deadlock needs circular wait." + NOTE,
     "KSET 2025 CS&A · Q43"),
    # --- new questions ---
    ("A race condition occurs when:",
     ["Several processes access and change shared data concurrently and the result depends on the order of access", "Two processes run on different computers", "A process finishes early", "The CPU is idle"], 0,
     PYQ + "Synchronization is needed to prevent it."),
    ("The critical section of a process is:",
     ["The part of its code in which it accesses shared data or resources", "The first line of the program", "The part that handles errors", "The code of the OS kernel only"], 0,
     "Only one process should execute in its critical section at a time."),
    ("A solution to the critical-section problem must satisfy:",
     ["Mutual exclusion, progress and bounded waiting", "Speed, accuracy and fairness only", "Atomicity, consistency, isolation and durability", "Deadlock, starvation and preemption"], 0,
     PYQ + "The three classic requirements."),
    ("'Bounded waiting' means that:",
     ["There is a limit on how many times other processes may enter their critical sections after a process has requested entry", "A process may wait forever", "Only one process may ever enter", "Processes never wait"], 0,
     "It prevents starvation."),
    ("'Progress' means that:",
     ["If no process is in its critical section, only processes wanting to enter take part in the decision, and it cannot be postponed indefinitely", "Every process must run in strict turn", "A process in its remainder section decides who enters", "No process may ever wait"], 0,
     "Strict alternation violates progress."),
    ("The general structure of a process taking part in the critical-section problem is:",
     ["Entry section → critical section → exit section → remainder section", "Critical section → entry section → remainder section", "Exit section → critical section → entry section", "Remainder section → exit section → critical section"], 0,
     "The entry section requests permission; the exit section signals that the process has left."),
    ("Peterson's solution to the critical-section problem uses the shared variables:",
     ["int turn and boolean flag[2]", "A semaphore and a monitor", "A mailbox", "Only a lock variable"], 0,
     PYQ + "It is a classic software solution for two processes."),
    ("Peterson's solution satisfies:",
     ["Mutual exclusion, progress and bounded waiting for two processes", "Only mutual exclusion", "Only progress", "None of the requirements"], 0,
     "It may still fail on modern CPUs that reorder memory operations unless memory barriers are used."),
    ("A software solution that uses only a shared variable 'turn' to force the two processes to alternate strictly:",
     ["Ensures mutual exclusion but violates progress", "Violates mutual exclusion", "Satisfies all three requirements", "Causes a deadlock always"], 0,
     PYQ + "A process may be kept out even though the other does not want to enter."),
    ("Using a single shared lock variable that a process checks and then sets, without atomic hardware support:",
     ["Can let two processes enter their critical sections together", "Always guarantees mutual exclusion", "Guarantees bounded waiting", "Prevents all race conditions"], 0,
     "The check and the set are separate steps that can be interleaved."),
    ("test_and_set() is:",
     ["An atomic hardware instruction that returns the old value of a lock and sets it to true", "A software loop", "A system call to create a process", "A page-replacement algorithm"], 0,
     PYQ + "Atomic means it executes as one uninterruptible unit."),
    ("compare_and_swap(&value, expected, new_value):",
     ["Atomically sets value to new_value only if value equals expected, and returns the original value", "Swaps two processes", "Compares two files", "Always fails on multiprocessors"], 0,
     "It underlies many lock-free algorithms."),
    ("Disabling interrupts while a process is in its critical section:",
     ["Works on a single processor but is not practical on multiprocessors", "Is the best method on multiprocessors", "Has no effect on a single processor", "Is used by user programs routinely"], 0,
     "Disabling interrupts on every CPU is slow and delays entry."),
    ("A spinlock is a lock in which:",
     ["A waiting process loops continuously (busy waits) until the lock becomes free", "The waiting process sleeps in a queue", "No waiting ever happens", "Only the OS can wait"], 0,
     PYQ + "Spinlocks avoid a context switch, so they suit multiprocessors when locks are held briefly."),
    ("The main disadvantage of busy waiting is that it:",
     ["Wastes CPU cycles that another process could use", "Uses too much disk", "Causes page faults", "Needs a network"], 0,
     "Blocking (sleeping) locks avoid this."),
    ("A mutex lock is used through the two operations:",
     ["acquire() and release()", "fork() and exec()", "send() and receive()", "open() and close()"], 0,
     "Both must be atomic."),
    ("An atomic operation is one that:",
     ["Executes completely without interruption, as a single indivisible step", "Uses nuclear energy", "Always runs in user mode", "Takes many separate steps that can interleave"], 0,
     "Atomicity is the basis of all hardware synchronization."),
    ("A shared counter = 5. A producer executes counter++ and a consumer executes counter-- concurrently without synchronization. The final value may be:",
     ["4, 5 or 6", "Always 5", "Always 6", "Always 4"], 0,
     PYQ + "Each statement is several machine instructions that can interleave."),
    ("Which kind of kernel is essentially free from race conditions on kernel data structures on a single processor?",
     ["A non-preemptive kernel", "A preemptive kernel", "Every multiprocessor kernel", "A microkernel on many CPUs"], 0,
     "Only one process is active in the kernel at a time."),
    ("The first known correct software solution to the two-process critical-section problem is:",
     ["Dekker's algorithm", "Banker's algorithm", "Belady's algorithm", "Dijkstra's shortest-path algorithm"], 0,
     "Lamport's bakery algorithm solves the problem for n processes."),
    ("When a high-priority process waits for a lock held by a low-priority process that is itself preempted by a medium-priority process, the problem is:",
     ["Priority inversion", "Starvation by design", "Thrashing", "Belady's anomaly"], 0,
     PYQ + "It is solved by priority inheritance (famous in the Mars Pathfinder mission)."),
    ("A memory barrier (fence) instruction ensures that:",
     ["All earlier loads and stores are completed before later ones are performed", "Memory is cleared", "The cache is disabled", "No process can access memory"], 0,
     "Needed because modern CPUs may reorder memory operations."),
    ("Match the term with its meaning:\na. Mutual exclusion  b. Progress  c. Bounded waiting  d. Race condition\n1. The result depends on the timing of access to shared data  2. A limit on how often others can enter before a waiting process  3. The choice of who enters next cannot be postponed indefinitely  4. At most one process in its critical section",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Requirement matching appears in KSET papers."),
    ("Consider the statements:\nI. Peterson's solution is a software solution for two processes.\nII. Peterson's solution uses only the variable turn.\nWhich is/are correct?",
     I_II, 0, "It needs both turn and the flag array."),
    ("Assertion (A): Disabling interrupts is not a practical critical-section solution on multiprocessors.\nReason (R): Disabling interrupts on all processors is time-consuming and delays entry into critical sections.",
     AR, 0, "Silberschatz gives this reason."),
    ("Assertion (A): Spinlocks never waste CPU time.\nReason (R): A process waiting for a spinlock keeps looping until the lock is free.",
     AR, 3, "Looping is exactly what wastes CPU time, so A is false."),
    ("The 'bakery algorithm' for the n-process critical-section problem was proposed by:",
     ["Leslie Lamport", "Edsger Dijkstra", "Gary Peterson", "C. A. R. Hoare"], 0,
     "Each process takes a 'ticket number' like customers in a bakery."),
    ("Which of these is a hardware-based tool for solving the critical-section problem?",
     ["Atomic instructions such as test_and_set() and compare_and_swap()", "Round Robin scheduling", "Paging", "The banker's algorithm"], 0,
     "Higher-level tools (mutex locks, semaphores, monitors) are built on them."),
]

SEMAPHORES = [
    # --- real previous-year question ---
    ("Consider the following threads T1, T2, T3 executing on a single processor, synchronized using three binary semaphore variables S1, S2, S3, operated upon using standard wait() and signal(). The threads can be context switched in any order and at any time.\nT1: while (true) { wait(S3); print(\"C\"); signal(S2); }\nT2: while (true) { wait(S1); print(\"B\"); signal(S3); }\nT3: while (true) { wait(S2); print(\"A\"); signal(S1); }\nWhich initialization of the semaphores would print the sequence BCABCABCA …?",
     ["S1 = 1; S2 = 1; S3 = 1", "S1 = 1; S2 = 0; S3 = 0", "S1 = 0; S2 = 1; S3 = 1", "S1 = 1; S2 = 1; S3 = 0"], 1,
     "B must come first, so only S1 starts at 1. Then B signals S3 → C, C signals S2 → A, A signals S1 → B, and so on." + NOTE,
     "KSET 2024 CS&A · Q44"),
    # --- new questions ---
    ("A semaphore, introduced by Dijkstra, is:",
     ["An integer variable that, apart from initialization, is accessed only through the atomic operations wait() and signal()", "A hardware register", "A type of page table", "A file lock on disk only"], 0,
     PYQ + "wait() and signal() were originally called P and V."),
    ("The operations P and V on a semaphore come from the Dutch words for:",
     ["Test (proberen) and increment (verhogen)", "Push and Pop", "Pause and Verify", "Print and View"], 0,
     "P = wait(); V = signal()."),
    ("A semaphore whose value can range only between 0 and 1 is a:",
     ["Binary semaphore", "Counting semaphore", "Monitor", "Spinlock queue"], 0,
     PYQ + "It behaves much like a mutex lock."),
    ("A counting semaphore used to control access to a resource with several instances is initialised to:",
     ["The number of available instances", "0 always", "1 always", "−1"], 0,
     "Each wait() takes an instance; each signal() returns one."),
    ("A counting semaphore S is initialised to 10. Then 6 wait (P) and 4 signal (V) operations are performed. The final value of S is:",
     ["8", "10", "4", "0"], 0,
     PYQ + "10 − 6 + 4 = 8."),
    ("A counting semaphore S is initialised to 7. After 20 P operations and 15 V operations, the value of S is:",
     ["2", "−2", "12", "0"], 0,
     PYQ + "7 − 20 + 15 = 2."),
    ("To make statement S2 in process P2 run only after statement S1 in process P1, with semaphore synch initialised to 0:",
     ["P1: S1; signal(synch);  P2: wait(synch); S2;", "P1: wait(synch); S1;  P2: S2; signal(synch);", "P1: S1; wait(synch);  P2: signal(synch); S2;", "Both processes call signal(synch) first"], 0,
     "Semaphores can enforce ordering between processes."),
    ("Implementing semaphores with a waiting queue and block()/wakeup() operations mainly avoids:",
     ["Busy waiting", "Mutual exclusion", "Context switches", "System calls"], 0,
     "The waiting process sleeps instead of spinning."),
    ("In the queue-based semaphore implementation, if the semaphore value is −3, then:",
     ["Three processes are waiting on the semaphore", "Three resources are free", "The semaphore is broken", "No process is waiting"], 0,
     "A negative value's magnitude is the number of waiting processes."),
    ("P0 executes wait(S); wait(Q); and P1 executes wait(Q); wait(S); with S = Q = 1. This can lead to:",
     ["Deadlock", "A race condition only", "Faster execution", "Priority inheritance"], 0,
     PYQ + "Each holds one semaphore and waits for the other."),
    ("If processes are removed from a semaphore's waiting queue in LIFO order, the problem that may arise is:",
     ["Starvation (indefinite blocking)", "Deadlock always", "Thrashing", "Belady's anomaly"], 0,
     "FIFO removal avoids it."),
    ("In the bounded-buffer (producer–consumer) problem with n slots, the semaphores mutex, empty and full are initialised to:",
     ["mutex = 1, empty = n, full = 0", "mutex = 0, empty = 0, full = n", "mutex = n, empty = 1, full = 0", "mutex = 1, empty = 0, full = n"], 0,
     PYQ + "empty counts empty slots; full counts filled slots."),
    ("The correct order of operations in the producer of the bounded-buffer solution is:",
     ["wait(empty) → wait(mutex) → add item → signal(mutex) → signal(full)", "wait(mutex) → wait(full) → add item → signal(empty) → signal(mutex)", "signal(full) → wait(empty) → add item → wait(mutex)", "wait(full) → wait(mutex) → add item → signal(mutex) → signal(empty)"], 0,
     "The consumer does wait(full), wait(mutex), remove, signal(mutex), signal(empty)."),
    ("In the bounded-buffer solution, if the producer performs wait(mutex) BEFORE wait(empty) and the buffer is full:",
     ["Deadlock can occur – the producer sleeps holding mutex, so the consumer cannot enter", "Nothing changes", "The buffer grows automatically", "The consumer runs faster"], 0,
     "The order of wait() operations matters."),
    ("In the 'first' readers–writers problem:",
     ["No reader is kept waiting unless a writer already has permission – so writers may starve", "Writers always have priority", "Readers may never read together", "Only one reader can read at a time"], 0,
     PYQ + "In the second readers–writers problem, writers get priority and readers may starve."),
    ("In the readers–writers solution, read_count records:",
     ["How many readers are currently reading the shared data", "How many writers are waiting", "The number of files", "The value of the buffer"], 0,
     "The first reader locks out writers; the last reader lets them in."),
    ("In the dining-philosophers problem, if every philosopher picks up the left chopstick at the same time:",
     ["Deadlock occurs – each waits for the right chopstick forever", "All philosophers eat together", "Only one philosopher starves while others eat", "Nothing happens"], 0,
     PYQ + "Five philosophers share five chopsticks."),
    ("Which is a remedy for deadlock in the dining-philosophers problem?",
     ["Allow at most four philosophers to sit at the table at once", "Add more philosophers", "Let every philosopher pick the left chopstick first", "Remove the mutex"], 0,
     "Others: pick up both chopsticks together, or let odd and even philosophers pick in different orders."),
    ("A monitor is:",
     ["A high-level synchronization construct in which only one process can be active inside at a time", "A display screen", "A hardware interrupt", "A type of pipe"], 0,
     PYQ + "Proposed by C. A. R. Hoare and Per Brinch Hansen."),
    ("For a condition variable x in a monitor, x.signal() when no process is waiting on x:",
     ["Has no effect", "Increments x permanently", "Causes deadlock", "Aborts the monitor"], 0,
     "Unlike a semaphore's signal(), it does not change any stored value."),
    ("In Java, monitors are provided through:",
     ["synchronized methods and blocks with wait() and notify()", "the goto statement", "fork() and exec()", "the volatile keyword only"], 0,
     "Every Java object has an intrinsic lock."),
    ("The sleeping-barber problem is a classic synchronization problem about:",
     ["A barber who sleeps when there are no customers and customers who wait in a limited number of chairs", "Two processes sharing a printer", "Disk scheduling", "Deadlock detection in databases"], 0,
     "Tanenbaum uses it to illustrate semaphores."),
    ("A mutex differs from a binary semaphore mainly because a mutex:",
     ["Has an owner – only the thread that locked it should unlock it", "Can hold any integer value", "Is used only in hardware", "Never blocks"], 0,
     "A semaphore can be signalled by any process."),
    ("Match the classical problem with its description:\na. Bounded-buffer  b. Readers–writers  c. Dining philosophers  d. Sleeping barber\n1. Customers wait in chairs; the server sleeps when no one is waiting  2. Five processes sharing five resources arranged in a circle  3. Shared data read by many, written by one at a time  4. Producer and consumer sharing fixed slots",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Classical-problem matching is very common."),
    ("Match the operation with its effect:\na. wait(S)  b. signal(S)  c. x.wait() in a monitor  d. x.signal() in a monitor\n1. Resumes one process suspended on x  2. Suspends the caller on condition x  3. Increments S and wakes a waiting process  4. Decrements S and blocks the caller if S becomes negative",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     "Semaphore and monitor operations compared."),
    ("Consider the statements:\nI. A counting semaphore can take values over an unrestricted domain.\nII. A binary semaphore can take only the values 0 and 1.\nWhich is/are correct?",
     I_II, 2, "Both are definitions from Silberschatz."),
    ("Assertion (A): In a monitor, x.signal() with no waiting process has no effect.\nReason (R): Condition variables, unlike semaphores, have no stored value.",
     AR, 0, "So signals are not 'remembered'."),
    ("Assertion (A): Semaphores can never cause deadlock.\nReason (R): If two processes perform wait() on two semaphores in opposite orders, each may wait forever for the other.",
     AR, 3, "R shows exactly how semaphores can deadlock, so A is false."),
    ("In the bounded-buffer solution, the consumer calls wait(full) first so that:",
     ["It sleeps when the buffer is empty instead of removing a non-existent item", "It can add items", "The producer is blocked forever", "mutex is released"], 0,
     "full counts the filled slots, starting at 0."),
]

TOPICS = {
    "Process Management & IPC": [("1 · Process Concept, States, PCB and Schedulers", PROCESS),
                                 ("2 · Process Operations, IPC and Client–Server Communication", IPC)],
    "Process Synchronization": [("1 · Critical-Section Problem, Peterson's Solution and Hardware Support", CRITICAL),
                                ("2 · Semaphores, Monitors and Classical Problems", SEMAPHORES)],
}
