"""Paper 2 · Unit 6 · P2-U6-12 I/O Systems, P2-U6-13 OS Security and P2-U6-14 Linux Operating System (3 topics × 2 sub-topics × 30).
References: Silberschatz, Galvin & Gagne, Operating System Concepts (10th ed., chs. 12, 16, 17, 20); William Stallings, Cryptography
and Network Security; the Linux man pages. Each set mixes REAL previous-year questions (exact wording and printed option order,
`source` = paper and question number) with new ones. Official answers come from KEA's final keys: Legislative Council Secretariat
2024 (Junior Console Operator P2, Data Entry Operator P2, Asst/Jr Asst P2, Sr/Jr Programmer P2 – booklet A1;
final key 09-04-2025) and GTTC 2024 (Technician Gr-III CS – booklet C1; final key 30-12-2024). KSET 2023–25 and KEA 2026 questions
are reused from packs/pyq-p2.json; those, GFGC 2021, PGCET and MCA-entrance questions have no published key, so their answers were
worked out by ExamSim. Network-security and everyday cyber-security questions (firewalls, IPsec, viruses for users, hacker types)
are kept for P2 Network Security and P1 Computer Literacy Unit 6."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

IO_HW = [
    ("The time between the receival of an interrupt and its service is called",
     ["Interrupt delay", "Interrupt latency", "Cycle time", "Switching time"], 1,
     "Interrupt latency is the delay from the interrupt request to the start of its service routine." + NOTE, "KSET 2024 CS&A · Q14"),
    ("Which one of the following statements is TRUE for memory-mapped I/O?",
     ["The I/O devices have separate address space", "The I/O devices and memory share the same address space",
      "A part of the memory is specially set aside for I/O operation", "The memory and I/O devices have an associated address space"], 1,
     "In memory-mapped I/O, device registers occupy addresses in the same address space as memory and are accessed with ordinary load/store instructions." + NOTE,
     "KSET 2024 CS&A · Q15"),
    ("Match the following:\na. DRAM\nb. DMA\nc. Associative mapping\nd. Memory-mapped I/O\n(i) Offloads data transfer main memory to devices bypassing CPU\n(ii) Dynamic memory\n(iii) I/O devices treated as memory locations\n(iv) Flexible cache mapping by content",
     ["a – i, b – ii, c – iii, d – iv", "a – ii, b – i, c – iv, d – iii", "a – iii, b – iv, c – ii, d – i", "a – iv, b – iii, c – i, d – ii"], 1,
     "DRAM is dynamic memory, DMA bypasses the CPU, associative mapping places blocks anywhere, memory-mapped I/O uses memory addresses for devices." + NOTE,
     "KSET 2025 CS&A · Q18"),
    ("Consider the following steps in a DMA transfer:\n(i) Disk controller initiates DMA transfer\n(ii) Disk driver tells disk controller to transfer of bytes from disk to buffer\n(iii) Disk controller sends each byte to DMA controller\n(iv) Device driver is told to transfer disk data to buffer\nIdentify the correct sequence.",
     ["(iv), (i), (ii), (iii)", "(i), (ii), (iii), (iv)", "(i), (iii), (iv), (ii)", "(iv), (ii), (i), (iii)"], 3,
     "Silberschatz's six-step DMA example begins: driver told → driver tells controller → controller initiates DMA → controller sends bytes." + NOTE,
     "KEA 2026 CS Paper-2 · Q49"),
    ("The DMA read operation transfer data from",
     ["Memory to the I/O device", "An I/O device to the memory", "Memory to CPU registers", "An I/O device to CPU register"], 0,
     "In DMA-controller terms (e.g. Intel 8237), a 'DMA read' reads memory and writes to the I/O device; a 'DMA write' goes from the device to memory." + NOTE,
     "GFGC 2021 CS · Q21"),
    ("What is the primary function of a DMA controller in a computer system?",
     ["To manage memory hierarchy", "To provide direct access to IO devices", "To execute instructions directly", "To manage the control unit"], 1,
     "It moves blocks of data between a device and memory without the CPU copying each byte." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q31"),
    ("Consider a computer with a 4-MHz processor. Its DMA controller can transfer 8 bytes in 1 cycle from a device to main memory through cycle stealing at regular intervals. Which one of the following is the data transfer rate (in bits per second) of the DMA controller if 1% of the processor cycles are used for DMA?",
     ["2,56,000", "3,200", "25,60,000", "32,000"], 2,
     "1% of 4 × 10⁶ cycles = 40,000 cycles/s × 8 bytes = 320,000 bytes/s = 2,560,000 bits/s (a GATE 2004 question)." + NOTE,
     "PGCET 2024 M.Tech CS · Q5"),
    ("Which of the following does not interrupt a running process ?",
     ["A device", "Timer", "Scheduler process", "Power failure"], 2,
     "Devices, the timer and power failure raise hardware interrupts; the scheduler is invoked by them and does not itself interrupt." + NOTE,
     "PGCET 2024 M.Tech CS · Q13"),
    ("A device communicates with the computer through a connection point called a:",
     ["Port", "Page", "Frame", "Thread"], 0, PYQ + "A set of wires shared by several devices with a protocol is a bus (e.g. PCIe)."),
    ("In polling (busy waiting), the CPU:",
     ["Repeatedly reads the device's status register until the device is ready", "Is told by the device through an interrupt", "Sleeps until DMA finishes", "Ignores the device"], 0,
     "Polling wastes CPU cycles if the device is slow."),
    ("The routine that the CPU executes when an interrupt occurs is the:",
     ["Interrupt handler (interrupt service routine)", "Bootstrap loader", "Scheduler", "Linker"], 0, PYQ + "Its address is found through the interrupt vector."),
    ("A table of addresses of interrupt handlers, indexed by interrupt number, is the:",
     ["Interrupt vector", "Page table", "File allocation table", "Device status table"], 0, "Interrupt chaining lets each entry point to a list of handlers."),
    ("Interrupts that can be turned off by the CPU before executing critical instruction sequences are called:",
     ["Maskable interrupts", "Non-maskable interrupts", "Traps only", "Page faults"], 0, "Non-maskable interrupts are reserved for events such as unrecoverable memory errors."),
    ("A software-generated interrupt caused by an error or by a user program's request for an OS service is a:",
     ["Trap (exception)", "Non-maskable interrupt", "DMA request", "Cycle steal"], 0, PYQ + "A system call is implemented with a trap instruction."),
    ("In cycle stealing, the DMA controller:",
     ["Takes over the memory bus for one cycle at a time, slowing the CPU slightly", "Stops the CPU permanently", "Uses the CPU registers", "Runs only when the CPU is off"], 0,
     "Burst mode transfers a whole block while holding the bus."),
    ("Which of the following devices is a block device?",
     ["Hard disk", "Keyboard", "Mouse", "Serial port"], 0, PYQ + "Keyboards and serial ports are character-stream devices."),
    ("The device-controller registers that hold the device's state (busy, ready, error) form the:",
     ["Status register", "Data-in register", "Data-out register", "Control register"], 0, "The host writes commands in the control register."),
    ("An interrupt-driven I/O cycle involves:",
     ["The CPU starting I/O and continuing other work until the device signals completion", "The CPU continuously checking the device",
      "No involvement of the CPU at all", "Only DMA transfers"], 0, "It avoids busy waiting."),
    ("Match:\na. Polling  b. Interrupt  c. DMA  d. Memory-mapped I/O\n1. CPU checks a status bit repeatedly  2. Device signals the CPU  3. Block transfer without the CPU  4. Device registers in the memory address space",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "The four basic ways of handling I/O."),
    ("Consider the statements:\nI. DMA is most useful for large data transfers.\nII. With DMA the CPU must copy every byte between the device and memory.",
     I_II, 0, "With DMA the CPU only starts the transfer and is interrupted at the end."),
    ("Assertion (A): Interrupt-driven I/O is more efficient than polling for slow devices.\nReason (R): The CPU need not waste cycles waiting for the device.",
     AR, 0, "Polling can be better only when the device is very fast."),
    ("Assertion (A): Non-maskable interrupts can be disabled by the CPU.\nReason (R): Maskable interrupts can be turned off during critical sections.",
     AR, 3, "Non-maskable interrupts cannot be disabled; R is true."),
    ("In the Intel 8085, which instruction is used for I/O in isolated (I/O-mapped) I/O?",
     ["IN and OUT", "LDA and STA", "MOV only", "JMP"], 0, PYQ + "In memory-mapped I/O, ordinary memory instructions such as LDA/STA are used instead."),
    ("The interface between the hardware controller of a device and the kernel's I/O subsystem is the:",
     ["Device driver", "Shell", "Compiler", "Loader"], 0, "Drivers hide device differences from the rest of the kernel."),
    ("PCIe, USB and SATA are examples of:",
     ["Buses / interfaces that connect devices", "File systems", "Page-replacement algorithms", "Scheduling queues"], 0, PYQ + "PCIe connects fast devices such as graphics cards and NVMe SSDs."),
    ("An interrupt-priority level system lets the CPU:",
     ["Defer low-priority interrupts while handling high-priority ones", "Ignore all interrupts", "Run two handlers on one core simultaneously", "Avoid using handlers"], 0,
     "High-priority interrupts can pre-empt the handling of low-priority ones."),
    ("In a DMA transfer, the signals used between the device controller and DMA controller are:",
     ["DMA-request and DMA-acknowledge", "Read and Write only", "Fetch and Execute", "Push and Pop"], 0, PYQ + "The DMA controller then takes the bus to place each word in memory."),
    ("The main advantage of memory-mapped I/O is that:",
     ["The full instruction set can operate on device registers", "It needs special I/O instructions", "It increases memory size", "It removes the need for drivers"], 0,
     "It does use up part of the address space."),
    ("Which statement about I/O ports in x86 PCs is correct?",
     ["x86 supports both separate I/O instructions (IN/OUT) and memory-mapped I/O", "x86 has no I/O instructions", "x86 uses only DMA", "x86 cannot use interrupts"], 0,
     "Graphics memory, for example, is memory-mapped."),
    ("The keyboard sends a signal to the CPU each time a key is pressed. This is an example of:",
     ["A hardware interrupt", "A trap from software", "A page fault", "Polling by the device"], 0, PYQ + "The keyboard controller raises an interrupt request (IRQ)."),
]

IO_KERNEL = [
    ("Which of the following is an example of a synchronous I/O operation?",
     ["Reading data from a disk with no interruption", "Using an interrupt handler to signal completion of I/O",
      "A process waiting for data to arrive before continuing execution", "Writing data to a file while the process is executing"], 2,
     "In synchronous (blocking) I/O the calling process waits until the I/O completes." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q47"),
    ("A blocking I/O system call:",
     ["Suspends the calling process until the I/O completes", "Returns immediately with whatever data is available", "Never returns", "Runs on the GPU"], 0,
     PYQ + "Non-blocking calls return at once; asynchronous calls return and signal completion later."),
    ("An asynchronous I/O call:",
     ["Returns immediately and notifies the process later when the I/O completes", "Waits until the I/O is done", "Is never used", "Uses polling only"], 0,
     "The process continues running while the I/O proceeds."),
    ("A buffer is used in I/O mainly to:",
     ["Cope with speed mismatch between producer and consumer of data", "Increase the number of interrupts", "Store the page table", "Replace the CPU cache"], 0,
     PYQ + "It also handles different data-transfer sizes and supports copy semantics."),
    ("Double buffering means:",
     ["One buffer is filled while the other is emptied", "Each byte is written twice", "Two CPUs share one buffer", "The buffer is twice as fast"], 0, "It decouples the producer from the consumer."),
    ("Spooling is used for devices such as a printer that:",
     ["Can serve only one job at a time, so output is queued on disk", "Are very fast", "Have random access", "Are block devices"], 0,
     PYQ + "SPOOL = Simultaneous Peripheral Operations On-Line."),
    ("A cache differs from a buffer in that a cache:",
     ["Holds a copy of data that also exists elsewhere, to speed up access", "Holds the only copy of the data", "Is always on disk", "Is used only for printers"], 0,
     "A buffer may hold the only existing copy of a data item."),
    ("The kernel I/O subsystem provides all of the following EXCEPT:",
     ["Compiling user programs", "I/O scheduling", "Buffering, caching and spooling", "Error handling and device reservation"], 0, PYQ + "Compilation is not a kernel service."),
    ("The ioctl() system call in UNIX is used to:",
     ["Send device-specific commands to a device driver", "Open a file", "Create a process", "Allocate memory"], 0, "It is an 'escape' for functions not covered by the standard calls."),
    ("Devices accessed with get() and put() of one character at a time are:",
     ["Character-stream devices", "Block devices", "Network sockets", "Memory-mapped files"], 0, "Keyboards, mice and serial ports are examples."),
    ("Network devices are usually accessed through which interface in UNIX and Windows?",
     ["Sockets", "Block reads", "ioctl only", "Spool files"], 0, PYQ + "select() manages a set of sockets."),
    ("The clock (timer) hardware is used by the OS to:",
     ["Give the current time, measure elapsed time and trigger operations such as pre-emption", "Store files", "Translate addresses", "Encrypt data"], 0,
     "A programmable interval timer generates periodic interrupts."),
    ("Arrange the life cycle of a blocking read request in order:\n1. Process issues read() system call\n2. Driver sends commands to the controller\n3. Device controller completes the transfer and raises an interrupt\n4. Kernel moves data to the process and unblocks it",
     ["1, 2, 3, 4", "2, 1, 3, 4", "1, 3, 2, 4", "4, 3, 2, 1"], 0, PYQ + "The kernel first checks whether the data is already in the buffer cache."),
    ("STREAMS in UNIX System V provide:",
     ["A full-duplex connection between a driver and a user process, with modules in between", "A disk scheduler", "A page-replacement algorithm", "A file allocation table"], 0,
     "Modules can be pushed onto a stream to add processing."),
    ("Which technique reduces the number of context switches for high-speed network I/O?",
     ["Using larger transfers and DMA / interrupt coalescing", "More frequent polling of slow devices", "Smaller buffers", "Disabling caching"], 0, PYQ + "Context switches and interrupts are expensive."),
    ("Device reservation in the kernel provides:",
     ["Exclusive access to a device such as a tape drive", "Faster interrupts", "Virtual memory", "Paging"], 0, "The OS must then watch for deadlock."),
    ("Copy semantics in I/O ensure that:",
     ["The data written is the version at the time of the system call, even if the application changes its buffer afterwards", "Data is copied twice to disk",
      "Files are copied on open", "Buffers are never used"], 0, "The kernel copies the application's data into a kernel buffer."),
    ("I/O scheduling in the kernel means:",
     ["Ordering pending I/O requests to improve efficiency and fairness", "Assigning CPU time quanta", "Allocating memory pages", "Choosing a file name"], 0,
     PYQ + "Disk scheduling is one example."),
    ("Consider the statements:\nI. Non-blocking I/O returns as much data as is available immediately.\nII. Asynchronous I/O always blocks the process.",
     I_II, 0, "Asynchronous I/O does not block; the process is notified later."),
    ("Assertion (A): Spooling allows several processes to 'print' at the same time.\nReason (R): Each process's output is stored in a separate disk file and printed one after another.",
     AR, 0, "The spooler queues the files for the printer."),
    ("Assertion (A): A buffer always holds a copy of data that also exists elsewhere.\nReason (R): A cache holds a copy of data stored elsewhere.",
     AR, 3, "That describes a cache; a buffer may hold the only copy."),
    ("Match:\na. Buffering  b. Caching  c. Spooling  d. Device reservation\n1. Speed mismatch  2. Fast copy of data  3. Queue output for a printer  4. Exclusive access",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-3, b-2, c-1, d-4", "a-1, b-3, c-2, d-4"], 0, PYQ + "The services of the kernel I/O subsystem."),
    ("Error handling in I/O: when a disk read fails, the OS typically:",
     ["Retries the operation and returns an error code if it still fails", "Shuts down the computer", "Deletes the file", "Ignores the error"], 0,
     "UNIX sets errno; SCSI devices report sense keys."),
    ("Kernel data structures that track open-file and device state, such as the open-file table, help the I/O subsystem to:",
     ["Keep state information about the use of I/O components", "Translate virtual addresses", "Choose the CPU quantum", "Encrypt the disk"], 0, PYQ + "UNIX uses an object-oriented design with dispatch tables."),
    ("A 'vectored I/O' (scatter–gather) system call such as readv() allows:",
     ["One call to read into several buffers", "Reading only one byte", "Disabling DMA", "Running two processes"], 0, "It reduces system-call overhead."),
    ("The main reason for using device-independent I/O system calls is that:",
     ["Applications need not know the details of each device", "Devices become faster", "Interrupts are eliminated", "Drivers are not needed"], 0,
     PYQ + "New devices can be added by writing a new driver."),
    ("Power management in modern I/O systems (e.g. Android) includes:",
     ["Turning off idle components and using device trees to manage power", "Increasing clock speed always", "Disabling interrupts", "Removing caches"], 0,
     "ACPI is used on PCs."),
    ("Which call returns immediately with the data available without waiting for more, useful for user interfaces?",
     ["A non-blocking read", "A blocking read", "fork()", "exec()"], 0, PYQ + "Multithreading is another way to overlap I/O with work."),
    ("The 'kernel I/O subsystem' sits between:",
     ["The system-call interface and the device drivers", "The CPU and the cache", "Two processes", "The keyboard and the mouse"], 0, "Below the drivers are the device controllers and devices."),
    ("Which of the following is the slowest way for the CPU to handle a fast device transferring large blocks?",
     ["Programmed I/O with polling for every byte", "DMA", "Interrupt per block", "Bus mastering"], 0, PYQ + "That is why disks use DMA."),
]

SEC_PROTECT = [
    ("____ is a general model of protection that provides a mechanism for protection without imposing a particular protection policy on the system or its users.",
     ["Global table", "Capability list", "Lock-key mechanism", "Access matrix"], 3,
     "Silberschatz: the access matrix separates mechanism from policy." + NOTE, "KSET 2023 CS&A · Q27"),
    ("Which one of the following statements is FALSE?",
     ["In Discretionary Access Control, the owner can determine the access privileges", "Discretionary Access Control has tighter security compared to Mandatory Access Control",
      "Discretionary Access Control is flexible with no rules and regulations", "Decisions will be based on the identity of the user and ownership in Discretionary Access Control"], 1,
     "Mandatory Access Control, with system-enforced labels, is the stricter model; DAC is flexible and owner-controlled." + NOTE, "KSET 2024 CS&A · Q38"),
    ("Match the following:\ni. User authentication\nii. Firewalls\niii. Access control\niv. Encryption\n(a) controls incoming and outgoing traffic in a network\n(b) converts readable information into an unreadable format\n(c) process of verifying the identity of a user attempting to gain access to a computer network\n(d) authorizing the users to access the resources in a computer network",
     ["i – b, ii – c, iii – d, iv – a", "i – c, ii – a, iii – d, iv – b", "i – d, ii – a, iii – b, iv – c", "i – c, ii – d, iii – a, iv – b"], 1,
     "Authentication verifies identity, firewalls filter traffic, access control authorises, encryption makes data unreadable." + NOTE, "KSET 2025 CS&A · Q50"),
    ("Which of the following attacks is a threat to Availability?",
     ["Modification", "Replaying", "Denial of Service", "Masquerading"], 2,
     "DoS prevents legitimate use of a system; modification attacks integrity and masquerading attacks authentication." + GTTC, "GTTC 2024 Technician Gr-III CS (C1) · Q39"),
    ("____ is the most common security method with respect to using computers.",
     ["Lock and key", "Key card systems", "Passwords", "Surveillance system"], 2,
     "Passwords are the most widely used method of user authentication." + NOTE, "PGCET 2025 MCA · Q44"),
    ("Protection, in OS terms, refers to:",
     ["Mechanisms that control the access of processes and users to resources", "Encrypting all files", "Backing up the disk", "Speeding up the CPU"], 0,
     PYQ + "Security is the wider problem of defending the system against internal and external attacks."),
    ("The principle that each program and user should get only the privileges needed for its task is:",
     ["The principle of least privilege", "The principle of locality", "Belady's principle", "The 50-percent rule"], 0, "It limits the damage from errors and attacks."),
    ("In an access matrix, rows represent ____ and columns represent ____.",
     ["Domains; objects", "Objects; domains", "Users; passwords", "Files; disks"], 0, PYQ + "Entry access(i, j) is the set of operations a process in domain Di may perform on object Oj."),
    ("Storing the access matrix by columns, so that each object has a list of (domain, rights) pairs, gives:",
     ["Access-control lists", "Capability lists", "A global table", "A lock–key scheme"], 0, "Storing it by rows gives capability lists for each domain."),
    ("A capability list is associated with:",
     ["A domain (each subject), listing the objects and allowed operations", "Each object", "The whole system as one table", "A disk block"], 0,
     PYQ + "A capability is like a protected ticket that the process holds."),
    ("Revocation of access rights is easiest with:",
     ["Access-control lists", "Capability lists", "Paper records", "Page tables"], 0, "With capabilities, finding and revoking every copy is hard (back-pointers, indirection, keys)."),
    ("In UNIX, the setuid bit on an executable file causes it to run with:",
     ["The privileges of the file's owner", "The privileges of the user running it", "No privileges", "Kernel privileges always"], 0,
     "passwd uses setuid root so that ordinary users can change their own passwords."),
    ("Role-based access control (RBAC), used in Solaris and many databases, assigns privileges to:",
     ["Roles, which are then given to users", "Files only", "Disks", "Processes at random"], 0, PYQ + "It applies the principle of least privilege conveniently."),
    ("Mandatory Access Control (MAC) is typically enforced by:",
     ["The system, using security labels that users cannot change", "The file owner", "Any user", "The application only"], 0, "SELinux implements MAC on Linux."),
    ("Domain switching in UNIX happens when:",
     ["A process executes a setuid program or makes a system call into the kernel", "A file is closed", "The disk is full", "A page fault occurs"], 0,
     "The kernel runs in a privileged domain (kernel mode)."),
    ("The CIA triad of security stands for:",
     ["Confidentiality, Integrity and Availability", "Control, Identity and Access", "Cipher, Integrity and Authentication", "Confidentiality, Isolation and Audit"], 0,
     PYQ + "Authentication and non-repudiation are often added to it."),
    ("Something you know, something you have and something you are – combining two of these is called:",
     ["Two-factor (multi-factor) authentication", "Single sign-on", "Encryption", "Hashing"], 0, "Example: password plus a one-time code (OTP) sent to the phone."),
    ("Passwords are stored securely in an OS by keeping:",
     ["A salted hash of each password, not the password itself", "Plain text in a file", "The password in the boot block", "Only the first letter"], 0,
     PYQ + "Salting defeats pre-computed (rainbow-table) attacks."),
    ("Fingerprint and face recognition are examples of:",
     ["Biometric authentication", "Encryption", "Access-control lists", "Capabilities"], 0, "They authenticate by 'something you are'."),
    ("A one-time password protects against:",
     ["Replay of a captured password", "Power failure", "Disk crashes", "Page faults"], 0, PYQ + "Each password is valid only once."),
    ("Consider the statements:\nI. Protection is an internal problem of controlling access to resources.\nII. Security also considers the external environment in which the system operates.",
     I_II, 2, "Silberschatz distinguishes protection (internal) from security (internal and external)."),
    ("Consider the statements:\nI. In an access-control list, rights are stored with each object.\nII. In a capability list, rights are stored with each domain.",
     I_II, 2, "These are the two ways of storing the sparse access matrix."),
    ("Assertion (A): Capability lists make revocation of access rights difficult.\nReason (R): Capabilities are distributed throughout the system with the processes that hold them.",
     AR, 0, "Schemes such as back-pointers and keys were invented to solve this."),
    ("Assertion (A): The principle of least privilege gives every user administrator rights.\nReason (R): Least privilege limits damage when a program is compromised.",
     AR, 3, "Least privilege gives only the rights needed; R is correct."),
    ("Match:\na. Authentication  b. Authorisation  c. Auditing  d. Encryption\n1. Verifying who the user is  2. Deciding what the user may do  3. Recording what was done  4. Making data unreadable to outsiders",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Basic security vocabulary."),
    ("In Windows, the object that describes the security of a file, including its owner and ACL, is the:",
     ["Security descriptor", "Inode", "Page table entry", "Boot sector"], 0, "Each user has a security ID (SID) in an access token."),
    ("Sandboxing a program means:",
     ["Running it with strict limits on what it can access", "Giving it root privileges", "Running it twice", "Compressing it"], 0, PYQ + "Browsers and mobile apps run in sandboxes."),
    ("The 'lock–key' scheme of protection gives each object a list of locks and each domain a list of:",
     ["Keys; access is allowed if a domain key matches an object lock", "Passwords only", "Pages", "Capabilities that can never change"], 0,
     "It is a compromise between ACLs and capabilities."),
    ("Language-based protection (e.g. in Java) is enforced by:",
     ["The compiler and the run-time system (JVM) checking access", "The disk controller", "The BIOS", "The printer"], 0, "Java uses stack inspection to check permissions."),
    ("A rule saying that a process in a lower-security level may not read data at a higher level ('no read up') belongs to the:",
     ["Bell–LaPadula model", "Banker's algorithm", "Working-set model", "Producer–consumer model"], 0, PYQ + "It protects confidentiality in military-style MAC systems."),
]

SEC_THREATS = [
    ("____ is built into the software by the original programmer in order to gain access to any system without going through the usual security access procedure.",
     ["Trojan Horse", "Logic Bomb", "Trap Door", "Worm"], 2,
     "A trap door (back door) is a hidden entry point left by the programmer." + NOTE, "KSET 2023 CS&A · Q28"),
    ("Which of the following uses the spawn mechanism to duplicate itself ?",
     ["Trojan Horse", "Worm", "Keystroke Logger", "Logic Bomb"], 1,
     "A worm spawns copies of itself and spreads through networks without needing a host program (Silberschatz)." + NOTE, "PGCET 2023 MCA · Q29"),
    ("____ can result in pop-up ads or redirection of a browser to a commercial website.",
     ["Spyware", "Backdoor", "Adware", "Virus"], 2,
     "Adware displays unwanted advertisements; spyware secretly collects information." + GTTC, "GTTC 2024 Technician Gr-III CS (C1) · Q36"),
    ("The threats presented by the programs that exploit vulnerabilities in computing systems are referred to as",
     ["Spamware", "Malware", "Virus", "Software"], 1,
     "Malware (malicious software) covers viruses, worms, Trojans, ransomware and spyware." + GTTC, "GTTC 2024 Technician Gr-III CS (C1) · Q47"),
    ("If your computer is rebooting itself, then it is likely that",
     ["It does not have enough memory", "There has been a power surge", "It has a virus", "It needs a CD - ROM"], 2,
     "Unexpected restarts are a common symptom of a malware infection." + KLC, "Legislative Council 2024 Asst/Jr Asst P2 · Q92"),
    ("In Cryptography, attacks that retrieve information from the system without affecting the system resources are called",
     ["Passive attacks", "Active attacks", "Safe attacks", "Silent attacks"], 0,
     "Eavesdropping and traffic analysis are passive; modification and DoS are active." + KLC, "Legislative Council 2024 Asst/Jr Asst P2 · Q89"),
    ("Hackers often gain entry into a network by pretending to be at a legitimate computer.",
     ["Phishing", "Forging", "Spoofing", "Spamming"], 2,
     "Spoofing fakes an identity such as an IP or MAC address." + KLC, "Legislative Council 2024 Asst/Jr Asst P2 · Q90"),
    ("The art of covered writing is called as ____",
     ["Steganography", "Cryptography", "Bibliography", "Autography"], 0,
     "Steganography hides the existence of a message (e.g. inside an image); cryptography makes the message unreadable." + GTTC, "GTTC 2024 Technician Gr-III CS (C1) · Q41"),
    ("Match the following:\na) Plain text\nb) Cipher text\nc) Symmetric encryption\nd) Public key encryption\ni. Scrambled message\nii. Readable message\niii. Uses two different keys for encryption and decryption\niv. Uses single key for both Encryption and Decryption",
     ["a – iv, b – ii, c – i, d – iii", "a – ii, b – i, c – iv, d – iii", "a – ii, b – iii, c – i, d – iv", "a – iv, b – i, c – ii, d – iii"], 1,
     "Plain text is readable, cipher text is scrambled, symmetric encryption uses one key and public-key encryption uses a key pair." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q42"),
    ("____ is used in a symmetric encryption",
     ["Public key", "Private key", "Candidate key", "Secret key"], 3,
     "Sender and receiver share one secret key (e.g. AES, DES)." + KLC, "Legislative Council 2024 Data Entry Operator P2 · Q95"),
    ("Which of these are TRUE for public-private key encryption algorithm?\n(i) Private key of the receiver is used by the sender to encrypt the message\n(ii) Public key is used by the receiver to decrypt the message",
     ["Only (i) is true", "Only (ii) is true", "Both (i) and (ii) are true", "Both (i) and (ii) are false"], 3,
     "The sender encrypts with the receiver's public key and the receiver decrypts with its own private key." + NOTE, "KSET 2024 CS&A · Q88"),
    ("The four primary security principles related to a message are",
     ["Confidentiality, authentication, integrity and non-repudiation.", "Confidentiality, access control, non-repudiation and integrity.",
      "Authentication, authorization, non-repudiation and availability.", "Availability, access control, authorization and authentication."], 0,
     "These four apply to a message itself; access control and availability apply to systems." + NOTE, "GFGC 2021 CS · Q108"),
    ("In the RSA algorithm, let N = P × Q = 33, and let the decryption key D = 7. If the ciphertext corresponds to the letter \"E\", determine the original plaintext letter.\n(Assume A = 1, B = 2, ……, Z = 26).",
     ["S", "U", "N", "E"], 2,
     "M = 5⁷ mod 33: 5² = 25, 5⁴ ≡ 31, 5⁷ ≡ 31 × 25 × 5 = 3875 ≡ 14 → N." + NOTE, "KSET 2025 CS&A · Q89"),
    ("In a RSA cryptosystem, a participant A uses 2 prime numbers p = 13 and q = 17, to generate public and private keys if the public key of A is 35, then private key of A is",
     ["Private key of participant A = (d, n) = (11, 192)", "Private key of participant A = (d, n) = (11, 221)",
      "Private key of participant A = (d, n) = (7, 220)", "Private key of participant A = (d, n) = (10, 195)"], 1,
     "n = 13 × 17 = 221, φ(n) = 12 × 16 = 192, and 35 × 11 = 385 = 2 × 192 + 1, so d = 11 and the private key is (11, 221)." + NOTE, "PGCET 2026 CS · Q70"),
    ("A program that appears useful but secretly performs a harmful function is a:",
     ["Trojan horse", "Worm", "Compiler", "Daemon"], 0, PYQ + "Unlike viruses, Trojans do not replicate themselves."),
    ("Code that lies dormant until a particular date or condition occurs and then causes damage is a:",
     ["Logic bomb", "Worm", "Trap door", "Firewall"], 0, "A time bomb is a logic bomb triggered by a date."),
    ("A virus differs from a worm in that a virus:",
     ["Needs a host program and usually user action to spread", "Spreads on its own through networks", "Cannot damage files", "Is a hardware fault"], 0,
     PYQ + "The 1988 Morris worm was one of the first internet worms."),
    ("Writing more data into a buffer than it can hold, so that the return address on the stack is overwritten, is a:",
     ["Buffer-overflow (stack-overflow) attack", "Denial-of-service attack", "Phishing attack", "Brute-force attack"], 0,
     "Defences include bounds checking, non-executable stacks and address-space layout randomisation (ASLR)."),
    ("Ransomware:",
     ["Encrypts the victim's files and demands payment for the key", "Shows advertisements", "Only slows the CPU", "Speeds up the computer"], 0,
     PYQ + "WannaCry (2017) was a major ransomware worm."),
    ("Trying every possible key until the right one is found is a:",
     ["Brute-force attack", "Man-in-the-middle attack", "Replay attack", "Social engineering"], 0, "Longer keys make brute force impractical."),
    ("An attacker intercepts and possibly alters messages between two parties who believe they are talking directly. This is a:",
     ["Man-in-the-middle attack", "Logic bomb", "Worm", "Trap door"], 0, PYQ + "Authentication of keys (certificates) defends against it."),
    ("DES, 3DES and AES are examples of:",
     ["Symmetric (secret-key) block ciphers", "Public-key algorithms", "Hash functions", "Digital certificates"], 0, "AES uses 128-bit blocks and 128/192/256-bit keys."),
    ("A cryptographic hash function such as SHA-256 is used to:",
     ["Produce a fixed-size digest to check the integrity of a message", "Encrypt data so it can be decrypted", "Compress files", "Schedule processes"], 0,
     PYQ + "MD5 and SHA-1 are now considered weak."),
    ("A digital signature is created by encrypting the message digest with the sender's:",
     ["Private key", "Public key", "Session key", "Receiver's private key"], 0, "Anyone can verify it with the sender's public key, giving non-repudiation."),
    ("An intrusion-detection system (IDS) is designed to:",
     ["Detect attempted or successful intrusions and raise alerts", "Compress network traffic", "Allocate memory", "Format disks"], 0,
     PYQ + "Signature-based IDS look for known patterns; anomaly-based IDS look for unusual behaviour."),
    ("Consider the statements:\nI. A worm can spread without any user action.\nII. A Trojan horse replicates itself to other files.",
     I_II, 0, "Trojans do not replicate; viruses and worms do."),
    ("Assertion (A): Public-key cryptography solves the key-distribution problem of symmetric encryption.\nReason (R): The encryption key can be published openly while only the decryption key is kept secret.",
     AR, 0, "Diffie and Hellman introduced the idea in 1976; RSA followed in 1977."),
    ("Assertion (A): A denial-of-service attack steals confidential data.\nReason (R): A DoS attack makes a system or service unavailable to legitimate users.",
     AR, 3, "DoS attacks availability, not confidentiality."),
    ("Match:\na. Virus  b. Worm  c. Trojan horse  d. Trap door\n1. Attaches to a host program  2. Self-replicating over networks  3. Disguised as useful software  4. Secret entry left by the programmer",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Program-threat matching is very common."),
    ("Which of the following is NOT a defence against security threats?",
     ["Sharing the administrator password with all users", "Keeping software patched", "Using strong authentication", "Auditing and logging"], 0,
     "Defence in depth uses many layers of protection."),
]

LINUX_BASICS = [
    ("Which of the following is a key feature of Linux?",
     ["Closed Source", "Proprietary", "Open Source", "Single User"], 2,
     "Linux is free, open-source (GPL) and multi-user." + GTTC, "GTTC 2024 Technician Gr-III CS (C1) · Q30"),
    ("Which of the following Linux distributions is maintained by the Debian-based company Canonical?",
     ["Ubuntu", "Fedora", "openSUSE", "Arch Linux"], 0, "Fedora is sponsored by Red Hat; openSUSE by SUSE; Arch is community-run."),
    ("The Operating System which requires a command to run is",
     ["Mac-OS & Single user Operating System", "Mac-OS & Windows", "Mac-OS", "Kali Linux"], 3,
     "The key picks Kali Linux, a Linux distribution whose tools are mostly run as commands in a terminal." + KLC, "Legislative Council 2024 Sr/Jr Programmer P2 · Q12"),
    ("Which of the following is/are not TRUE?\n(a) Kernel is the program that contains core of operating system\n(b) Kernel is the first part of operating system to load into memory during booting\n(c) Kernel is made of various modules which cannot be loaded in running operating system\n(d) Kernel remains in the memory during the entire computer session",
     ["(a) and (b)", "(a) and (c)", "Only (c)", "(c) and (d)"], 2,
     "Loadable kernel modules (e.g. Linux insmod / modprobe) can be added to a running kernel, so (c) is false." + NOTE, "PGCET 2026 CS · Q50"),
    ("Given the following statements with respect to Operating System:\nS1: Kernel is the heart of Operating System\nS2: Operating System acts as an interface between user and computer\nS3: Operating System is a hardware\nWhich of the following is correct?",
     ["S1, S2 and S3 are correct", "S1 and S2 are correct and S3 is not correct", "S1, S2 and S3 are incorrect", "S1 is correct and S2 & S3 are incorrect"], 1,
     "An OS is system software, not hardware." + NOTE, "PGCET 2025 MCA · Q45"),
    ("Linus Torvalds announced the first Linux kernel in 1991 while he was a student at the University of:",
     ["Helsinki, Finland", "Cambridge, UK", "California, Berkeley", "Bell Labs, USA"], 0,
     PYQ + "Stallman founded the GNU project (1983); Ritchie and Thompson created UNIX at Bell Labs."),
    ("Linux is distributed under which licence?",
     ["GNU General Public License (GPL v2)", "Microsoft EULA", "BSD licence only", "Freeware with no source"], 0, "The GPL requires modified versions that are distributed to keep the source open."),
    ("A complete Linux system with the kernel, GNU tools, package manager and installer is called a:",
     ["Distribution (distro)", "Kernel module", "Shell", "File system"], 0, PYQ + "Examples: Ubuntu, Debian, Fedora, Red Hat Enterprise Linux, Linux Mint, Kali."),
    ("The Linux kernel design is best described as:",
     ["Monolithic, but modular with loadable kernel modules", "Pure microkernel", "Exokernel", "Layered with no modules"], 0,
     "All core services run in kernel mode for performance; modules add drivers and file systems at run time."),
    ("Which three components make up a Linux system according to Silberschatz?",
     ["Kernel, system libraries and system utilities", "BIOS, CPU and RAM", "Shell, GUI and browser", "Compiler, linker and loader"], 0,
     PYQ + "The kernel runs in kernel mode; libraries and utilities run in user mode."),
    ("Which Linux command loads a kernel module along with its dependencies?",
     ["modprobe", "chmod", "mkdir", "ping"], 0, "insmod loads one module; rmmod removes it; lsmod lists loaded modules."),
    ("The program that interprets commands typed by the user in Linux is the:",
     ["Shell (e.g. bash)", "Kernel", "BIOS", "Compiler"], 0, PYQ + "Other shells include sh, zsh, csh and ksh."),
    ("The superuser account in Linux, with full administrative rights, is called:",
     ["root", "admin", "guest", "system"], 0, "sudo lets an ordinary user run a single command as root."),
    ("Which Linux directory holds system configuration files?",
     ["/etc", "/bin", "/home", "/tmp"], 0, PYQ + "/home holds users' files, /bin essential commands, /tmp temporary files and /var logs."),
    ("In Linux, everything – including devices – is treated as a:",
     ["File", "Process", "Thread", "Socket only"], 0, "Devices appear in /dev, e.g. /dev/sda."),
    ("The first user-space process started by the Linux kernel at boot (PID 1) is today usually:",
     ["systemd (formerly init)", "bash", "cron", "sshd"], 0, PYQ + "It starts all other services."),
    ("Which statement about Linux and UNIX is correct?",
     ["Linux is a UNIX-like system written from scratch, not derived from UNIX source code", "Linux is the original UNIX from Bell Labs",
      "Linux is a version of Windows", "Linux cannot run on servers"], 0, "Linux follows POSIX standards."),
    ("Android uses which kernel?",
     ["A modified Linux kernel", "The Windows NT kernel", "The XNU kernel", "The MS-DOS kernel"], 0, PYQ + "Apple's macOS and iOS use the XNU kernel."),
    ("Consider the statements:\nI. Linux is a multi-user, multitasking operating system.\nII. Linux can run only on desktop computers.",
     I_II, 0, "Linux runs on servers, supercomputers, phones and embedded devices."),
    ("Assertion (A): A new device driver can be added to Linux without rebuilding the kernel.\nReason (R): Linux supports loadable kernel modules.",
     AR, 0, "This is why the Linux kernel is called modular."),
    ("Assertion (A): Linux is a microkernel operating system.\nReason (R): The Linux kernel is a single address space that runs all core services in kernel mode.",
     AR, 3, "R describes a monolithic kernel, which Linux is; A is false."),
    ("Match:\na. Linus Torvalds  b. Richard Stallman  c. Dennis Ritchie  d. Andrew Tanenbaum\n1. Linux kernel  2. GNU project  3. UNIX and C  4. MINIX",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Linux was inspired partly by MINIX."),
    ("The Linux command to display the manual page of a command is:",
     ["man", "help me", "info-all", "doc"], 0, "Example: man ls."),
    ("Which Linux command shows the currently running processes?",
     ["ps", "ls", "cd", "cat"], 0, PYQ + "top shows a continuously updated list; kill sends a signal to a process."),
    ("The Linux command used to search for a pattern in files is:",
     ["grep", "find-text", "search", "locate-only"], 0, "find searches for files by name or attributes."),
    ("The standard package manager commands of Debian/Ubuntu and of Fedora/RHEL are:",
     ["apt and dnf (yum)", "pip and npm", "brew and choco", "exe and msi"], 0, PYQ + "They install, update and remove software packages."),
    ("Linux's graphical desktop environments include:",
     ["GNOME and KDE Plasma", "Aero and Fluent", "Aqua", "Metro"], 0, "Both run on the X Window System or Wayland."),
    ("The Linux command 'pwd' displays:",
     ["The present working directory", "The password file", "Power settings", "Printer queue"], 0, "cd changes the directory."),
    ("Which of these is NOT a Linux distribution?",
     ["Windows Server", "Ubuntu", "Fedora", "Debian"], 0, PYQ + "Windows Server is Microsoft's server OS."),
    ("Kernel mode and user mode in Linux are used to:",
     ["Protect the kernel from faulty or malicious user programs", "Make programs run slower deliberately", "Store files", "Encrypt the disk"], 0,
     "User programs enter the kernel only through system calls."),
]

LINUX_INTERNALS = [
    ("Match the following and choose the correct option (in the Linux Virtual File System):\na) An inode object\nb) A file object\nc) A super block object\nd) A dentry object\ni. Represents an entire file system\nii. Represents an individual directory entry\niii. Represents an open file\niv. Represents an individual file",
     ["a – iii, b – ii, c – iv, d – i", "a – iv, b – iii, c – ii, d – i", "a – ii, b – i, c – iii, d – iv", "a – iv, b – iii, c – i, d – ii"], 3,
     "These are the four primary Linux VFS object types (Silberschatz)." + NOTE, "KSET 2024 CS&A · Q50"),
    ("Match the file management commands with its functionalities:\nList – I (Commands)\n(a) ls\n(b) pwd\n(c) touch\n(d) chmod\nList – II (Function)\n(i) Change file permissions\n(ii) List files and folders\n(iii) Display current working directory\n(iv) Update timestamp/create empty file",
     ["a – i, b – iv, c – iii, d – ii", "a – iii, b – ii, c – i, d – iv", "a – ii, b – iii, c – iv, d – i", "a – iv, b – i, c – ii, d – iii"], 2,
     "ls lists, pwd prints the working directory, touch updates the timestamp or creates an empty file, chmod changes permissions." + NOTE, "PGCET 2026 CS · Q47"),
    ("In Linux, a new process is created with ____ and a new program is loaded into it with ____.",
     ["fork(); exec()", "exec(); fork()", "open(); close()", "malloc(); free()"], 0,
     PYQ + "Linux also has clone(), which lets the new task share chosen resources – used to create threads."),
    ("Linux does not distinguish between processes and threads; both are called:",
     ["Tasks, created with clone()", "Jobs", "Segments", "Inodes"], 0, "Flags to clone() decide what is shared (memory, files, signal handlers)."),
    ("The default Linux scheduler from kernel 2.6.23 to 6.5 was the:",
     ["Completely Fair Scheduler (CFS)", "O(1) scheduler only", "Round robin with fixed quantum", "FCFS scheduler"], 0,
     "CFS used a red-black tree ordered by virtual run time; kernel 6.6 (2023) replaced it with EEVDF."),
    ("In Linux CFS, the 'nice' value of a process ranges from:",
     ["−20 (highest priority) to +19 (lowest)", "0 to 100", "1 to 10", "−100 to +100"], 0, PYQ + "A lower nice value gives a larger share of the CPU."),
    ("Linux real-time scheduling classes are:",
     ["SCHED_FIFO and SCHED_RR", "SCHED_LRU and SCHED_OPT", "SCHED_DISK and SCHED_NET", "SCHED_SJF only"], 0, "Real-time tasks always run before normal (SCHED_NORMAL) tasks."),
    ("Linux allocates physical pages for the kernel using the:",
     ["Buddy system, with the slab allocator for kernel objects", "First-fit list only", "Paging to tape", "FAT"], 0,
     PYQ + "Newer kernels use SLUB, a simplified slab allocator."),
    ("The standard file system of most Linux distributions today is:",
     ["ext4", "NTFS", "FAT12", "HFS"], 0, "ext4 is journaling and uses extents; XFS and Btrfs are other options."),
    ("A Linux inode stores all of these EXCEPT:",
     ["The file's name", "Owner and permissions", "Size and timestamps", "Pointers to the data blocks"], 0, PYQ + "Names are stored in directory entries, which map names to inode numbers."),
    ("The /proc file system in Linux is:",
     ["A virtual file system giving information about processes and the kernel", "A disk partition for programs", "The boot loader", "A swap file"], 0,
     "Example: /proc/cpuinfo and /proc/<pid>/status."),
    ("Linux divides devices into three classes:",
     ["Block devices, character devices and network devices", "Fast, slow and medium devices", "Input, output and storage only", "Local, remote and virtual"], 0,
     PYQ + "Network devices are accessed through the socket interface."),
    ("Which of the following is an inter-process communication mechanism in Linux?",
     ["Pipes, signals, shared memory and message queues", "Page tables", "Inodes", "The boot block"], 0, "Pipes connect commands in the shell, e.g. ls | grep txt."),
    ("A signal in Linux is:",
     ["A software notification sent to a process that an event has occurred", "A hardware wire", "A disk block", "A kind of file system"], 0,
     PYQ + "kill -9 sends SIGKILL; Ctrl + C sends SIGINT."),
    ("Linux uses which technique to avoid copying all pages when fork() is called?",
     ["Copy-on-write", "Swapping the whole process", "Compaction", "Spooling"], 0, "Pages are copied only when the parent or child writes to them."),
    ("In the permission string -rwxr-xr--, the first character '-' indicates:",
     ["A regular file", "A directory", "A symbolic link", "A device"], 0, PYQ + "'d' marks a directory, 'l' a symbolic link, 'c' and 'b' character and block devices."),
    ("The command chmod 644 report.txt gives:",
     ["Owner read–write; group and others read only", "Everyone full access", "Owner execute only", "No access for anyone"], 0, "6 = rw-, 4 = r--."),
    ("Which Linux command changes the owner of a file?",
     ["chown", "chmod", "chgrp-only", "mv"], 0, PYQ + "chgrp changes only the group."),
    ("Linux networking is built around which protocol suite?",
     ["TCP/IP, accessed through the BSD socket interface", "NetBEUI only", "AppleTalk only", "X.25 only"], 0, "Netfilter (iptables / nftables) provides the firewall."),
    ("Linux security modules that add mandatory access control include:",
     ["SELinux and AppArmor", "FAT and NTFS", "CFS and EEVDF", "GNOME and KDE"], 0, PYQ + "SELinux was developed by the US NSA."),
    ("In Linux, kernel modules are compiled as:",
     ["Object files (.ko) that can be loaded and unloaded at run time", "Shell scripts", "Executable .exe files", "Text files"], 0, "Module management, driver registration and conflict resolution are handled by the kernel."),
    ("The Linux page-replacement policy is a variation of:",
     ["LRU approximation using active and inactive lists (clock-like)", "Optimal replacement", "FIFO only", "Random replacement"], 0,
     "Pages move between the active and inactive lists according to their reference bits."),
    ("Consider the statements:\nI. In Linux, threads are created with clone().\nII. In Linux, the fork() call copies the whole address space immediately.",
     I_II, 0, "fork() uses copy-on-write, so pages are not copied immediately."),
    ("Assertion (A): Linux file names are case-sensitive.\nReason (R): Linux treats 'Report.txt' and 'report.txt' as two different files.",
     AR, 0, "Windows (NTFS by default) is case-insensitive."),
    ("Assertion (A): In Linux, the file name is stored inside the inode.\nReason (R): A file can have several hard links with different names pointing to the same inode.",
     AR, 3, "Names are stored in directories, which is exactly why several names can link to one inode."),
    ("Which command shows disk-space usage of mounted file systems in Linux?",
     ["df -h", "du -x only", "free", "uname"], 0, PYQ + "du shows the space used by files and directories; free shows memory."),
    ("The Linux command 'ls -l' displays:",
     ["A long listing with permissions, owner, size and modification time", "Only hidden files", "Only directories", "The kernel version"], 0, "ls -a also shows hidden files (names starting with '.')."),
    ("Which Linux command creates a new, empty directory?",
     ["mkdir", "rmdir", "touch", "cp"], 0, PYQ + "rmdir removes an empty directory; rm -r removes a directory with its contents."),
    ("The Linux command 'cat file1 file2 > file3' will:",
     ["Concatenate file1 and file2 and write the result into file3", "Delete file3", "Compare the files", "Copy file3 to file1"], 0, ">> appends instead of overwriting."),
    ("Match the Linux command with its use:\na. cp  b. mv  c. rm  d. cat\n1. Copy  2. Move / rename  3. Remove  4. Display file contents",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Basic command matching."),
]

TOPICS = {
    "I/O Systems": [("1 · I/O Hardware – Polling, Interrupts, DMA and Memory-mapped I/O", IO_HW),
                    ("2 · Application I/O Interface and Kernel I/O Subsystem", IO_KERNEL)],
    "OS Security": [("1 · Protection, Access Matrix, Access Control and Authentication", SEC_PROTECT),
                    ("2 · Program and System Threats, Cryptography and Defences", SEC_THREATS)],
    "Linux Operating System": [("1 · Design Principles, Kernel Modules and Basic Commands", LINUX_BASICS),
                               ("2 · Process, Scheduling, Memory, File System, I/O and IPC in Linux", LINUX_INTERNALS)],
}
