"""Paper 2 · Unit 6 · P2-U6-01 System Software and P2-U6-02 OS Basics (2 topics × 2 sub-topics × 30).
References: Silberschatz, Galvin & Gagne, Operating System Concepts (10th ed., chs. 1–2); D. M. Dhamdhere, Systems Programming;
J. J. Donovan, Systems Programming; Aho, Lam, Sethi & Ullman, Compilers.
Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question number)
with new questions. Official answers come from KEA's final keys: Legislative Council Secretariat 2024 (Computer Operator P2,
Sr/Jr Programmer P2, Junior Console Operator P2, Data Entry Operator P2 – booklet A1; final key 09-04-2025) and GTTC 2024
(Technician Gr-III CS – booklet C1, Lecturer CS – booklet A1; final keys 30-12-2024). KSET 2023/2025 questions are reused from
packs/pyq-p2.json (answers worked out by ExamSim). Obvious printing typos are corrected."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

TRANSLATORS = [
    # --- real previous-year questions ---
    ("The role of a compiler in software development is",
     ["To execute the program", "To convert high level code to machine code", "To debug errors in the code", "To store data"], 1,
     "A compiler translates the whole source program into machine (object) code." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q78"),
    ("A compiler is used for",
     ["Converting machine language to high level programming language", "Converting high level programming language to machine language", "Running software application", "Managing hardware devices"], 1,
     "Translation goes from the high-level source to machine language." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q67"),
    ("Which of the following is/are the example/examples of low-level programming language?\n(a) Python\n(b) Java\n(c) C\n(d) Machine language",
     ["a & b only", "c & d only", "a, b & c", "d only"], 3,
     "Machine (and assembly) language are low-level; KEA's key treats C as a high-level language." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q73"),
    ("Match the following:\nGeneration of Languages: a) Second generation language  b) Third generation language  c) Fourth generation language  d) Fifth generation language\nExample: i. Prolog  ii. FoxPro  iii. Assembler  iv. Pascal",
     ["a – iii, b – iv, c – ii, d – i", "a – ii, b – iii, c – iv, d – i", "a – iv, b – iii, c – ii, d – i", "a – i, b – ii, c – iii, d – iv"], 0,
     "2GL assembly, 3GL procedural languages such as Pascal, 4GL database/query tools such as FoxPro, 5GL logic languages such as Prolog." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q85"),
    ("Which of the following is NOT considered as an essential part of a computer system's hardware?",
     ["CPU", "Keyboard", "Compiler", "Monitor"], 2,
     "A compiler is system software, not hardware." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q68"),
    ("Which of the following helps Assembler to deal with branching code?",
     ["One Pass Assembler", "Two Pass Assembler", "Debugger", "Interpreter"], 1,
     "The first pass builds the symbol table, so forward branch targets are known in the second pass." + NOTE,
     "KSET 2023 CS&A · Q59"),
    ("A symbol table in assembler contains",
     ["Mapping of variables and their memory addresses", "Program code and data", "Input and output instructions", "Machine instructions and opcodes."], 0,
     "The symbol table maps labels and symbols to addresses; opcodes are in the machine-opcode table." + NOTE,
     "KSET 2025 CS&A · Q79"),
    # --- new questions ---
    ("Machine language is:",
     ["Binary instructions that the CPU executes directly; it is machine-dependent", "A language that needs a compiler", "Portable to every processor", "Written in English words"], 0,
     PYQ + "It needs no translation, but is very hard to write."),
    ("Assembly language uses ____ and is translated into machine code by a(n) ____.",
     ["Mnemonics such as MOV and ADD; assembler", "English sentences; interpreter", "Binary digits only; compiler", "Flowcharts; linker"], 0,
     PYQ + "Each assembly statement usually maps to one machine instruction."),
    ("A key difference between a compiler and an interpreter is that:",
     ["A compiler translates the whole program before execution; an interpreter translates and executes one statement at a time", "An interpreter produces an object file", "A compiler executes line by line", "There is no difference"], 0,
     PYQ + "Compiled programs usually run faster; interpreters make debugging easier."),
    ("An interpreter, on meeting an error in line 20 of a program:",
     ["Stops there after executing lines 1–19", "Reports all errors before running anything", "Ignores the error", "Converts the program to assembly"], 0,
     "A compiler reports errors for the whole program before any of it runs."),
    ("The usual order of the phases of a compiler is:",
     ["Lexical analysis → syntax analysis → semantic analysis → intermediate code → code optimization → code generation", "Syntax analysis → lexical analysis → code generation → optimization", "Code generation → lexical analysis → parsing → optimization", "Semantic analysis → lexical analysis → parsing → code generation"], 0,
     PYQ + "The symbol table and error handler are used by all phases."),
    ("The lexical analyzer (scanner) of a compiler produces:",
     ["A stream of tokens", "A parse tree", "Object code", "An optimized program"], 0,
     "The parser (syntax analyzer) then builds a parse tree from the tokens."),
    ("A cross-compiler is a compiler that:",
     ["Runs on one machine but produces code for a different machine", "Translates between two high-level languages only", "Compiles itself", "Runs only on the target machine"], 0,
     PYQ + "Used to build software for embedded systems."),
    ("In a two-pass assembler, the main task of pass 1 is to:",
     ["Assign addresses to all statements using the location counter and build the symbol table", "Generate the final machine code", "Load the program", "Execute the program"], 0,
     PYQ + "Pass 2 uses the symbol table to generate the object code."),
    ("Using a label in an instruction before the label is defined is called a:",
     ["Forward reference", "Backward reference", "Macro call", "Relocation"], 0,
     "One-pass assemblers handle it with back-patching."),
    ("Assembler directives (pseudo-ops) such as START, END and EQU:",
     ["Give instructions to the assembler and do not themselves become machine instructions", "Are executed by the CPU", "Are machine instructions", "Are system calls"], 0,
     PYQ + "DC/DS (or DB/DW) reserve or define storage."),
    ("The table that holds the mnemonic opcodes and their machine codes in an assembler is the:",
     ["Machine-opcode table (MOT / OPTAB)", "Symbol table", "Literal table", "Page table"], 0,
     "Labels and their addresses are in the symbol table."),
    ("In an assembler, the location counter is used to:",
     ["Keep track of the address of the next instruction or data item", "Count the number of errors", "Count lines of comments", "Store the program's output"], 0,
     "It is advanced by the length of each instruction."),
    ("In Java, the compiler javac translates source code into:",
     ["Bytecode, which the Java Virtual Machine interprets or compiles just-in-time", "Native machine code for one CPU only", "Assembly language", "HTML"], 0,
     "This gives 'write once, run anywhere' portability."),
    ("A program that converts machine code back into assembly language is a:",
     ["Disassembler", "Compiler", "Loader", "Linker"], 0,
     "A decompiler tries to recover high-level source."),
    ("Match the translator with its job:\na. Assembler  b. Compiler  c. Interpreter  d. Cross-compiler\n1. Produces code for a different machine  2. Translates and runs statement by statement  3. Translates a whole high-level program into object code  4. Translates assembly language into machine code",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Translator matching is common in KEA papers."),
    ("Consider the statements:\nI. Machine language is machine-dependent.\nII. Assembly language programs run unchanged on every type of processor.\nWhich is/are correct?",
     I_II, 0, "Assembly language is specific to a processor family."),
    ("Assertion (A): A two-pass assembler handles forward references easily.\nReason (R): Pass 1 records the addresses of all labels in the symbol table.",
     AR, 0, "Pass 2 can then fill in every address."),
    ("Assertion (A): An interpreter produces a separate object file that can be run later without the interpreter.\nReason (R): An interpreter translates and executes a program statement by statement.",
     AR, 3, "No object file is produced, so A is false."),
    ("Which of these is a high-level language?",
     ["Python", "Machine language", "x86 assembly language", "Binary microcode"], 0,
     "High-level languages are close to human language and machine-independent."),
    ("Code optimization in a compiler aims to:",
     ["Make the target code faster or smaller without changing what the program does", "Find spelling mistakes in comments", "Produce tokens", "Load the program into memory"], 0,
     "It works on intermediate code and/or target code."),
    ("A missing semicolon in a C statement is detected during:",
     ["Syntax analysis (parsing)", "Code optimization", "Loading", "Linking"], 0,
     PYQ + "Type mismatches and undeclared variables are found in semantic analysis."),
    ("Literals such as =F'5' in an assembly program are collected by the assembler in the:",
     ["Literal table (LITTAB)", "Opcode table", "Page table", "Macro name table"], 0,
     "They are placed in a literal pool, e.g. at an LTORG statement."),
    ("Writing a compiler for a language in that same language, and using a simpler version to compile it, is called:",
     ["Bootstrapping", "Cross-compiling", "Linking", "Interpreting"], 0,
     "Most C compilers are themselves written in C."),
]

LINK_LOAD = [
    # --- real previous-year questions ---
    ("What is the role of linker in compilation?",
     ["Translates source code to object code", "Generates intermediate code", "Combines different compiled modules", "Performs code optimization"], 2,
     "The linker combines object modules and libraries into one executable, resolving external references." + NOTE,
     "KSET 2025 CS&A · Q23"),
    ("In the process of macro expansion given:\nS₁: lexical substitution implies replacement of a character string by another string during program generation\nS₂: lexical substitution is employed to replace occurrences of formal parameters by some random values\nWhich of the following holds good?",
     ["Both S₁ and S₂ are true", "Both S₁ and S₂ are false", "S₁ is false and S₂ is true", "S₁ is true and S₂ is false"], 3,
     "Formal parameters are replaced by the actual parameters of the call, not by random values (Dhamdhere)." + NOTE,
     "KSET 2025 CS&A · Q41"),
    ("Which of the following statement/statements about software is/are correct?\n(a) Software can be categorized into system software and application software\n(b) System software includes operating system and device drives\n(c) Application software includes software for tasks like word processing\n(d) All system and application softwares are open-sources",
     ["a, b & c only", "b & c only", "a & d only", "a only"], 0,
     "Much software is proprietary, so (d) is false." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q77"),
    ("Match the following software with their respective categories\nSoftware: (a) Microsoft Word  (b) Ubuntu Linux  (c) Eclipse IDE  (d) Norton Antivirus\nCategory: i) Application software  ii) Development software  iii) Utility software  iv) System software",
     ["a – iv, b – ii, c – iii, d – i", "a – ii, b – i, c – iii, d – iv", "a – i, b – ii, c – iii, d – iv", "a – i, b – iv, c – ii, d – iii"], 3,
     "Word – application; Ubuntu – system (OS); Eclipse – development; Norton – utility." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q80"),
    ("Which of the following softwares is considered as application software?",
     ["Windows OS", "Linux OS", "Microsoft Excel", "BIOS"], 2,
     "Operating systems and firmware are system software." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q74"),
    ("Which of the following is an example of system software?",
     ["Microsoft Word", "Google Chrome", "Windows 10", "Adobe Photoshop"], 2,
     "An operating system is system software." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q75"),
    ("Which of the following is an example of application software?",
     ["Windows OS", "Google Chrome", "Linux Kernel", "Device Drivers"], 1,
     "A web browser is an application program." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q82"),
    # --- new questions ---
    ("Static linking differs from dynamic linking because in static linking:",
     ["Library code is copied into the executable at link time; in dynamic linking shared libraries (.dll, .so) are linked at load or run time", "No libraries are used", "Linking happens while the program is running", "The program cannot call functions"], 0,
     PYQ + "Dynamic linking saves memory and lets libraries be updated without relinking."),
    ("A loader is the system program that:",
     ["Places an executable program into main memory and prepares it for execution", "Translates source code", "Checks spelling", "Designs the user interface"], 0,
     PYQ + "Loading is the last step before execution."),
    ("The four functions of a loader are:",
     ["Allocation, linking, relocation and loading", "Lexing, parsing, optimizing and generating", "Reading, writing, opening and closing", "Compiling, testing, debugging and deploying"], 0,
     PYQ + "Classic textbook list (Donovan)."),
    ("Relocation means:",
     ["Adjusting the address-dependent parts of a program so it can run from a memory area other than the one assumed when it was translated", "Moving files between folders", "Renaming variables", "Copying a program to another computer"], 0,
     "Relocation bits or modification records tell the loader which words to adjust."),
    ("An absolute loader:",
     ["Loads the program at the address fixed by the assembler, with no relocation", "Relocates every address", "Performs dynamic linking", "Compiles the program"], 0,
     "Simple, but the programmer must know where the program will be loaded."),
    ("The small program, stored in ROM/firmware, that starts loading the operating system when a computer is switched on is the:",
     ["Bootstrap loader", "Linker", "Macro processor", "Debugger"], 0,
     PYQ + "It loads the boot loader or kernel from disk."),
    ("A 'compile-and-go' (assemble-and-go) loader:",
     ["Places the translated code directly in memory and starts execution, without producing an object file", "Links many modules from disk", "Relocates programs at run time", "Only loads the OS"], 0,
     "Fast, but the program must be translated again every time it is run."),
    ("Dynamic loading means that:",
     ["A routine is loaded into memory only when it is first called", "All routines are loaded at start", "The program is loaded twice", "Loading is done by the compiler"], 0,
     "Unused routines (e.g. error handlers) are never loaded."),
    ("A macro is:",
     ["A named group of statements that is substituted (expanded) wherever its name is used", "A subroutine called at run time with a return address", "A type of loader", "An operating system"], 0,
     PYQ + "Macro expansion is done by a macro processor (pre-processor) before translation."),
    ("Compared with a subroutine call, a macro call:",
     ["Is expanded in-line at every use, making the program larger but avoiding call/return overhead", "Keeps a single copy of the code", "Is slower to execute", "Needs a return instruction"], 0,
     PYQ + "Subroutines keep one copy and use CALL/RETURN."),
    ("In assembler macro definitions, the body of the macro lies between the pseudo-ops:",
     ["MACRO and MEND", "START and END", "BEGIN and STOP", "CALL and RET"], 0,
     "The macro name and its formal parameters follow MACRO."),
    ("The tables maintained by a two-pass macro processor include:",
     ["Macro Name Table (MNT), Macro Definition Table (MDT) and Argument List Array (ALA)", "Page table and frame table", "Symbol table only", "Routing table"], 0,
     "MNT points into the MDT for each macro."),
    ("A debugger is a tool that helps a programmer to:",
     ["Find and fix errors using breakpoints, single-stepping and inspection of variables", "Compile code faster", "Load the OS", "Design databases"], 0,
     PYQ + "e.g. gdb, or the debugger built into an IDE."),
    ("A breakpoint in debugging is:",
     ["A marked point where program execution pauses so the programmer can examine its state", "A syntax error", "The last line of the program", "A hardware fault"], 0,
     "Execution can then be continued or stepped."),
    ("Match the system program with its role:\na. Loader  b. Linker  c. Macro processor  d. Debugger\n1. Helps locate errors with breakpoints  2. Expands macro calls  3. Combines object modules and resolves external references  4. Places the program in memory for execution",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "System-program matching appears in KSET papers."),
    ("Consider the statements:\nI. A macro call is replaced by the macro body during expansion.\nII. A subroutine's body is copied into the program at every call.\nWhich is/are correct?",
     I_II, 0, "A subroutine has a single copy reached by CALL."),
    ("An external reference in an object module is:",
     ["A use of a symbol defined in another module, which the linker resolves", "A comment line", "A local variable", "A syntax error"], 0,
     "EXTRN / ENTRY (or extern / global) declarations mark such symbols."),
    ("The output of a linker is typically a(n):",
     ["Executable (load) module", "Source program", "Stream of tokens", "Parse tree"], 0,
     "The loader then brings the executable into memory."),
    ("Utility software includes programs such as:",
     ["Antivirus, disk defragmenter, backup and file-compression tools", "Word processors and games", "Compilers only", "Operating system kernels only"], 0,
     PYQ + "Utilities help maintain and optimise the computer."),
    ("A device driver is classified as:",
     ["System software", "Application software", "Hardware", "A programming language"], 0,
     "It lets the OS control a particular device."),
    ("Conditional macro expansion (e.g. AIF and AGO in IBM assembler) allows:",
     ["Different statements to be generated depending on the macro's arguments", "Macros to be called at run time", "Macros to be loaded dynamically", "Debugging of macros only"], 0,
     "The expansion-time variables and labels are processed by the macro processor."),
    ("Assertion (A): Relocation is needed when a program is loaded at an address different from the one assumed during translation.\nReason (R): Address-sensitive instructions contain addresses computed from the assumed origin.",
     AR, 0, "The loader adds the difference to each such address."),
    ("In system programming, a text editor is used to:",
     ["Create and modify source programs and other text files", "Execute programs", "Link object modules", "Allocate main memory"], 0,
     "e.g. vi, nano, Notepad."),
]

OS_INTRO = [
    # --- real previous-year questions (official keys) ---
    ("A set of programs that controls the resources of a system and provides it to the users with an interface that is easier to use is called",
     ["Utility programs", "Application software", "Operating system", "Firmware"], 2,
     "The OS manages resources and offers a convenient interface." + KLC,
     "Legislative Council 2024 Data Entry Operator P2 · Q89"),
    ("Which one among the following is not a basic function of operating system?",
     ["Virus protection", "File management", "Device management", "Process management"], 0,
     "Virus protection is done by separate utility (antivirus) software." + KLC,
     "Legislative Council 2024 Data Entry Operator P2 · Q74"),
    ("Which of the following is the primary goal of an operating system?",
     ["To provide a platform for running applications", "To manage hardware resources", "To execute instructions", "To manage application software"], 1,
     "KEA's key: the OS is above all a resource manager." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q48"),
    ("Which one of the following is not true?",
     ["Kernel remains in the memory during the entire computer session.", "Kernel is made of various modules which cannot be loaded in running operating system.", "Kernel is the first part of the operating system to load into the memory during booting.", "Kernel is the program that constitutes the central core of the operating system."], 1,
     "Modern kernels such as Linux support loadable modules that can be added while the system runs." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q4"),
    ("Match the following:\nOperating System: a) Android  b) Windows Operating System  c) Linux  d) OS-X\nCompanies: i. Microsoft  ii. Google  iii. Apple  iv. Open source",
     ["a - i, b - ii, c - iii, d - iv", "a - ii, b - i, c - iv, d - iii", "a - iii, b - i, c - ii, d - iv", "a - ii, b - iii, c - iv, d - i"], 1,
     "Android – Google; Windows – Microsoft; Linux – open source; OS X (macOS) – Apple." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q9"),
    ("Which of the following is/are open source operating system?\n(a) Linux  (b) Opensolaris\n(c) BSD  (d) Android",
     ["a & b only", "a, b & c only", "a & d only", "a, b, c & d"], 3,
     "All four are open source (Android's core is the Android Open Source Project)." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q79"),
    ("An example of non-real-time systems is",
     ["Nuclear reactor", "Air traffic control system", "Old email services", "Satellite tracking"], 2,
     "E-mail has no strict deadlines; the others need guaranteed response times." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q74"),
    ("Which one of the following errors will be handled by the operating system?",
     ["Power failure", "Lack of paper in printer", "Connection failure in the network", "Failure of power, connection and Lack of paper"], 3,
     "Error detection is an OS service covering hardware, I/O devices and the network." + GTTC,
     "GTTC 2024 Lecturer CS · Q49"),
    # --- new questions ---
    ("An operating system acts as:",
     ["An intermediary between the user and the computer hardware, and a manager of its resources", "A compiler for all languages", "Only a file storage area", "A type of hardware"], 0,
     PYQ + "Silberschatz: the OS is a resource allocator and a control program."),
    ("In a batch operating system:",
     ["Similar jobs are grouped and run one after another without user interaction", "Users interact with programs while they run", "Strict deadlines must always be met", "Many computers act as one"], 0,
     "Early mainframes used batch processing with punched cards."),
    ("Multiprogramming means:",
     ["Keeping several jobs in memory so the CPU can switch to another job when one waits for I/O", "Running one program at a time", "Writing programs in many languages", "Using many CPUs for one job"], 0,
     PYQ + "Its aim is to increase CPU utilisation."),
    ("A time-sharing (multitasking) system:",
     ["Switches the CPU among users' programs so quickly that each user gets fast interactive response", "Runs jobs only at night", "Never switches between processes", "Has no scheduler"], 0,
     PYQ + "Each process receives a short time slice (quantum)."),
    ("A hard real-time system is one in which:",
     ["Missing a deadline is a system failure, e.g. an airbag controller or a pacemaker", "Deadlines are only targets", "There are no deadlines", "Only batch jobs are run"], 0,
     PYQ + "In soft real-time systems, such as video streaming, an occasional missed deadline is tolerable."),
    ("Privileged instructions, such as I/O and timer management, can be executed only in:",
     ["Kernel (supervisor) mode", "User mode", "Any mode", "Debug mode only"], 0,
     PYQ + "A mode bit in hardware tells which mode the CPU is in."),
    ("In a monolithic kernel:",
     ["Most OS services run together in a single address space in kernel mode", "Only message passing is in the kernel", "There is no kernel", "Every service is a user program"], 0,
     "Traditional UNIX and Linux are monolithic (Linux with loadable modules)."),
    ("A microkernel design:",
     ["Keeps only essential functions (IPC, basic scheduling, memory) in the kernel and runs other services in user space", "Puts all drivers in the kernel", "Has no inter-process communication", "Cannot be extended"], 0,
     PYQ + "Examples: Mach, QNX, MINIX 3. It is more reliable but message passing adds overhead."),
    ("In the layered approach to OS design:",
     ["Each layer uses only the services of the layers below it; layer 0 is the hardware", "All layers can call each other freely", "There is only one layer", "The user interface is layer 0"], 0,
     "Dijkstra's THE system used this structure."),
    ("Windows NT-based systems and macOS are usually described as having a:",
     ["Hybrid kernel", "Pure microkernel", "Exokernel", "No kernel"], 0,
     "They combine features of monolithic and microkernel designs."),
    ("SPOOLING stands for:",
     ["Simultaneous Peripheral Operations On-Line", "Serial Processing Of Online Logic", "System Program Of Operating Logic", "Simple Peripheral Output Online"], 0,
     PYQ + "Print jobs are spooled to disk and printed one by one."),
    ("A timer interrupt is used by the OS mainly to:",
     ["Prevent a user program from keeping the CPU forever", "Speed up the disk", "Display the time on screen only", "Format the hard disk"], 0,
     "When the timer expires, control returns to the OS."),
    ("Match the type of OS with its feature:\na. Batch  b. Time-sharing  c. Real-time  d. Distributed\n1. Many networked computers appear as one system  2. Must respond within strict time limits  3. Interactive use by many users with time slices  4. Similar jobs grouped and run without interaction",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "OS-type matching is very common."),
    ("Consider the statements:\nI. Privileged instructions execute only in kernel mode.\nII. A microkernel runs many services, such as file systems, in user space.\nWhich is/are correct?",
     I_II, 2, "Both are standard facts."),
    ("Assertion (A): Multiprogramming increases CPU utilisation.\nReason (R): When one job waits for I/O, the CPU switches to another job in memory.",
     AR, 0, "The CPU is not left idle."),
    ("Assertion (A): Hard real-time systems may occasionally miss deadlines without harm.\nReason (R): In soft real-time systems, a missed deadline lowers quality but is not catastrophic.",
     AR, 3, "In hard real-time systems a missed deadline is a failure, so A is false."),
    ("Symmetric multiprocessing (SMP) means:",
     ["Every processor runs the OS and all processors are peers", "One master processor controls the others", "Only one processor is ever used", "Processors work in different buildings"], 0,
     "Asymmetric multiprocessing uses a master–slave arrangement."),
    ("A distributed operating system:",
     ["Manages networked computers so that they appear to users as one system", "Runs on a single CPU only", "Cannot use a network", "Is a batch system"], 0,
     PYQ + "It shares resources and computation across machines."),
    ("The program that reads and carries out typed user commands, such as bash in Linux, is the:",
     ["Shell (command interpreter)", "Kernel", "Loader", "Compiler"], 0,
     PYQ + "Windows has cmd.exe and PowerShell."),
    ("Loadable kernel modules in Linux allow:",
     ["Drivers and file systems to be added to or removed from the running kernel", "User programs to run in kernel mode", "The kernel to be deleted", "Booting without a kernel"], 0,
     "This gives a monolithic kernel some of a microkernel's flexibility."),
    ("Which of these is an embedded / real-time operating system?",
     ["VxWorks", "Microsoft Excel", "MySQL", "Google Chrome"], 0,
     "FreeRTOS and QNX are other examples."),
    ("The main disadvantage of a microkernel compared with a monolithic kernel is:",
     ["Extra overhead from message passing between user-space services", "Lower reliability", "It cannot be extended", "A much larger kernel"], 0,
     "Each service request may need several context switches."),
]

OS_SERVICES = [
    # --- real previous-year questions (official keys) ---
    ("To access the services of the operating system, the interface is provided by",
     ["Library", "System calls", "Assembly instructions", "API"], 1,
     "System calls are the interface between a running program and the OS kernel." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q3"),
    ("Match the following types of system calls with their description\nSystem calls: a. Process control  b. File management  c. Device management  d. Information maintenance\nDescription: i. Creates and deletes files  ii. Schedules and terminates processes  iii. Performs input and output operations.  iv. Retrieves system status information",
     ["a – ii, b – i, c – iii, d – iv", "a – iii, b – i, c – ii, d – iv", "a – i, b – ii, c – iii, d – iv", "a – ii, b – iii, c – i, d – iv"], 0,
     "Process control – create/terminate processes; file management – create/delete files; device management – I/O; information maintenance – time, date, system data." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q42"),
    ("Which of the following is NOT a type of system call?",
     ["Process control", "File manipulation", "Database operations", "Device management"], 2,
     "The six types: process control, file manipulation, device management, information maintenance, communications and protection." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q49"),
    ("Considering the following statements, choose the correct option.\nAssertion (A): Software drivers enable the operating system to communicate with hardware system.\nReason (R): Without the appropriate drivers, an operating system cannot operate hardware devices.",
     ["Both (A) and (R) are true and (R) is the correct explanation of (A)", "Both (A) and (R) are true but (R) is not the correct explanation of (A)", "(A) is true but (R) is false", "(A) is false but (R) is true"], 0,
     "Drivers translate the OS's generic requests into device-specific commands." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q72"),
    ("The ____ presents a uniform device access interface to the IO subsystem, much as system calls provide a standard interface between the application and the operating system",
     ["Device drivers", "I/O systems", "Devices", "Buses"], 0,
     "Silberschatz: device drivers hide device differences from the I/O subsystem." + GTTC,
     "GTTC 2024 Lecturer CS · Q46"),
    ("Where is BIOS usually stored?",
     ["Flash memory on the mother board", "Hard disk", "RAM", "Device Driver"], 0,
     "BIOS/UEFI firmware lives in flash ROM on the motherboard." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q69"),
    ("What is the correct sequence of system booting?",
     ["POST → BOOT DEVICE SELECTION → LOADING OS → BIOS", "POST → BIOS → BOOT DEVICE SELECTION → LOADING OS", "BOOT DEVICE SELECTION → BIOS → POST → LOADING OS", "BOOT DEVICE SELECTION → POST → BIOS → LOADING OS"], 1,
     "KEA's key: POST, then the BIOS hands over to the boot device, which loads the OS. (Strictly, POST is itself run by the BIOS.)" + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q75"),
    ("Which of the following is a type of BIOS used in modern systems?",
     ["POST", "UEFI (Unified Extensible Firmware Interface)", "CMOS", "USB"], 1,
     "UEFI has replaced the legacy BIOS on modern PCs." + KLC,
     "Legislative Council 2024 Computer Operator P2 · Q76"),
    # --- new questions ---
    ("Which of these is a service provided by an operating system?",
     ["Program execution, I/O operations, file-system manipulation, communication and error detection", "Writing application programs", "Designing hardware circuits", "Typing documents for the user"], 0,
     PYQ + "Also resource allocation, accounting, and protection and security."),
    ("A system call:",
     ["Is the way a program requests a service from the OS kernel; it switches the CPU from user mode to kernel mode", "Is a phone call to the system administrator", "Is a hardware fault", "Runs only in user mode"], 0,
     PYQ + "It is implemented with a trap (software interrupt)."),
    ("fork(), exec(), wait() and exit() in UNIX are examples of ____ system calls.",
     ["Process control", "File management", "Device management", "Communication"], 0,
     PYQ + "fork() creates a child process; exec() loads a new program into it."),
    ("open(), read(), write() and close() are examples of ____ system calls.",
     ["File management", "Process control", "Information maintenance", "Protection"], 0,
     "The same calls are used for many devices in UNIX."),
    ("getpid(), alarm() and sleep() in UNIX belong to the ____ category of system calls.",
     ["Information maintenance", "File management", "Device management", "Communication"], 0,
     "Windows equivalents include GetCurrentProcessID() and SetTimer()."),
    ("The Windows system call that corresponds to UNIX fork() for creating a process is:",
     ["CreateProcess()", "OpenFile()", "ReadConsole()", "SetTimer()"], 0,
     "Silberschatz lists Windows and UNIX equivalents side by side."),
    ("Application programmers usually call system services through an API such as POSIX or the Windows API because:",
     ["APIs are portable and hide the details of the actual system calls", "System calls are illegal", "APIs run faster than the hardware", "APIs avoid the kernel completely"], 0,
     PYQ + "The run-time library turns API functions into system calls."),
    ("Parameters can be passed to the OS in a system call:",
     ["In registers, in a block or table in memory whose address is in a register, or on the stack", "Only through files", "Only by the keyboard", "Only through the network"], 0,
     "Linux and Solaris combine registers and memory blocks."),
    ("On most PCs, the first sector of a boot disk (512 bytes) that holds the boot loader and partition table in the legacy scheme is the:",
     ["Master Boot Record (MBR)", "Page table", "Inode", "File Allocation Table"], 0,
     "UEFI systems use the GUID Partition Table (GPT) instead."),
    ("GRUB is:",
     ["A boot loader commonly used to start Linux", "A file system", "A text editor", "A compiler"], 0,
     PYQ + "It can offer a menu to choose between several operating systems."),
    ("After the Linux kernel is loaded and initialised, the first user-space process it starts (PID 1) is:",
     ["init (systemd on most modern distributions)", "bash", "gcc", "cron"], 0,
     "It starts all other services."),
    ("Restarting a computer that is already on, without switching off the power, is called a:",
     ["Warm boot", "Cold boot", "Hard reset of the BIOS", "Format"], 0,
     PYQ + "A cold boot starts from power off."),
    ("Separating policy from mechanism in OS design means:",
     ["The mechanism decides how something is done; the policy decides what is done, so policies can change without changing mechanisms", "Policies are written in assembly only", "Mechanisms are decided by users", "Both are the same"], 0,
     "e.g. a timer is a mechanism; how long a time slice should be is a policy."),
    ("Match the UNIX system call with its category:\na. fork()  b. open()  c. ioctl()  d. getpid()\n1. Information maintenance  2. Device management  3. File management  4. Process control",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "A frequent matching question."),
    ("Consider the statements:\nI. A system call switches the CPU from user mode to kernel mode.\nII. The bootstrap program is stored in RAM before the computer is switched on.\nWhich is/are correct?",
     I_II, 0, "RAM is empty at power-on; the bootstrap is in ROM/flash firmware."),
    ("pipe(), shmget() and send()/recv() are examples of ____ system calls.",
     ["Communication", "Process control", "File management", "Information maintenance"], 0,
     "Message passing and shared memory are the two communication models."),
    ("chmod() and umask() in UNIX are examples of ____ system calls.",
     ["Protection", "Device management", "Communication", "Process control"], 0,
     "They control access permissions on files."),
    ("POST (Power-On Self-Test) is performed to:",
     ["Check that essential hardware such as memory, keyboard and video works before the OS is loaded", "Install the OS", "Test application software", "Format the disk"], 0,
     PYQ + "Beep codes report failures."),
    ("CMOS memory on the motherboard stores:",
     ["BIOS settings such as date, time and boot order, kept alive by a small battery", "The operating system", "User documents", "The swap file"], 0,
     "Removing the battery resets these settings."),
    ("An operating system's user interface can be:",
     ["Command-line (CLI), graphical (GUI) or touch-screen", "Only graphical", "Only punched cards", "Only voice"], 0,
     "Many systems offer more than one."),
    ("Most modern operating systems are written mainly in:",
     ["C and C++, with small parts in assembly language", "Only assembly language", "Only Java", "HTML"], 0,
     "High-level languages make the OS easier to port and maintain."),
    ("Assertion (A): Application programs normally reach the kernel only through system calls.\nReason (R): User-mode programs cannot execute privileged instructions directly.",
     AR, 0, "The trap into kernel mode is controlled by the OS."),
]

TOPICS = {
    "System Software": [("1 · Language Levels and Translators – Compilers, Interpreters, Assemblers", TRANSLATORS),
                        ("2 · Linkers, Loaders, Macros, Debuggers and Types of Software", LINK_LOAD)],
    "OS Basics": [("1 · Operating System Functions, Types and Structure", OS_INTRO),
                  ("2 · OS Services, System Calls and Booting", OS_SERVICES)],
}
