"""Paper 2 · Unit 6 · P2-U6-10 Storage Management and P2-U6-11 File Systems (2 topics × 2 sub-topics × 30).
References: Silberschatz, Galvin & Gagne, Operating System Concepts (10th ed., chs. 11, 13–15); William Stallings, Operating Systems.
Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question number) with new
ones. Official answers come from KEA's final keys: Legislative Council Secretariat 2024 (Junior Console Operator P2, Data Entry
Operator P2, Computer Operator P2 – booklet A1; final key 09-04-2025) and GTTC 2024 (Technician Gr-III CS – booklet C1; final key
30-12-2024). KSET 2023–25 and KEA 2026 questions are reused from packs/pyq-p2.json; those, GFGC 2021, PGCET and the KEA 2026
Kannada-English-Computer paper have no published key, so their answers were worked out by ExamSim. Disk-scheduling and disk-address
numbers were checked by computation."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

DISK = [
    ("The smallest unit that can be written to or read from the disk is a",
     ["Track", "Head", "Byte", "Sector"], 3,
     "A disk transfers whole sectors (traditionally 512 bytes, now often 4 KB)." + KLC, "Legislative Council 2024 Data Entry Operator P2 · Q86"),
    ("Which is the correct hierarchy order of memory devices based on storage in ascending order?",
     ["Registers → Cache → RAM → Hard disk", "Cache → Registers → RAM → Hard disk", "RAM → Registers → Cache → Hard disk", "Registers → RAM → Cache → Hard disk"], 0,
     "Capacity grows (and speed and cost per bit fall) from registers to cache to main memory to disk." + KLC, "Legislative Council 2024 Computer Operator P2 · Q84"),
    ("Consider a typical disk that rotates at 180 RPM, what is the average rotational delay?",
     ["0.32 sec", "0.4 sec", "0.16 sec", "0.2 sec"], 2,
     "180 RPM = 3 rotations per second, so one rotation takes 1/3 s; the average delay is half a rotation ≈ 0.16 s." + NOTE, "GFGC 2021 CS · Q24"),
    ("A hard disk has 63 sectors per track, 10 platters each with 2 recording surfaces and 1000 cylinders. The address of a sector is given as a triple (c, h, s) where c is cylinder number, h is the surface number and s is the sector number. Thus the 0th sector is addressed as (0, 0, 0), the 1st sector as (0, 0, 1), and so on.\nThe address (400, 16, 29) corresponding to sector number",
     ["505035", "505036", "505037", "505038"], 2,
     "Sector = 400 × (20 × 63) + 16 × 63 + 29 = 504000 + 1008 + 29 = 505037 (a GATE 2009 question)." + NOTE, "PGCET 2024 M.Tech CS · Q15"),
    ("RAID level 4 provides:",
     ["Disk mirroring", "Memory style error-correcting code organization", "Block-interleaved parity organization", "Bit-interleaved parity organization"], 2,
     "RAID 1 = mirroring, RAID 2 = memory-style ECC, RAID 3 = bit-interleaved parity, RAID 4 = block-interleaved parity." + NOTE, "KSET 2023 CS&A · Q26"),
    ("The time taken by the disk arm to move the heads to the cylinder containing the desired sector is called the:",
     ["Seek time", "Rotational latency", "Transfer time", "Access bandwidth"], 0,
     PYQ + "Rotational latency is the further time for the sector to rotate under the head."),
    ("Disk access time is the sum of:",
     ["Seek time, rotational latency and transfer time", "Only seek time", "CPU time and seek time", "Transfer time and CPU burst"], 0,
     "Disk scheduling tries to reduce seek time, the largest part."),
    ("A disk rotates at 7200 RPM. Its average rotational latency is about:",
     ["4.17 ms", "8.33 ms", "2.08 ms", "16.7 ms"], 0, PYQ + "One rotation = 60/7200 s = 8.33 ms; the average is half of it."),
    ("The set of tracks at one arm position, across all platters, forms a:",
     ["Cylinder", "Sector", "Cluster", "Partition"], 0, "Data on the same cylinder can be read without moving the arm."),
    ("Writing the sector structure (header, data area, trailer with ECC) on a new disk so the controller can read and write it is called:",
     ["Low-level (physical) formatting", "Logical formatting", "Partitioning", "Defragmentation"], 0,
     "Logical formatting then creates the file system on a partition."),
    ("The small program in ROM that loads the full bootstrap program from the boot blocks of the disk is the:",
     ["Bootstrap loader", "Device driver", "Interrupt handler", "Spooler"], 0, PYQ + "On a PC, the boot code is in the MBR (or the EFI system partition)."),
    ("Replacing a bad sector with one of the spare sectors set aside by the controller is called:",
     ["Sector sparing (forwarding)", "Sector slipping only", "Swapping", "Thrashing"], 0, "Sector slipping moves every sector down one place instead."),
    ("Which device has no moving parts and therefore no seek time or rotational latency?",
     ["Solid-state drive (SSD)", "Hard disk drive", "Magnetic tape", "Floppy disk"], 0, "NAND flash wears out after many erase cycles, so SSDs use wear levelling."),
    ("RAID 1 is also known as:",
     ["Mirroring", "Striping without redundancy", "Block-interleaved distributed parity", "P + Q redundancy"], 0, PYQ + "Every write goes to two disks; capacity is halved."),
    ("RAID 0 provides:",
     ["Striping for performance but no redundancy", "Mirroring", "Parity on a dedicated disk", "Double parity"], 0, "Failure of any one disk loses the data."),
    ("Which RAID level distributes block-interleaved parity across all disks, avoiding a single parity-disk bottleneck?",
     ["RAID 5", "RAID 4", "RAID 1", "RAID 0"], 0, "RAID 6 adds a second parity (P + Q) and survives two disk failures."),
    ("RAID 6 can tolerate the failure of:",
     ["Two disks", "Only one disk", "No disk", "Half of all disks always"], 0, PYQ + "It stores two independent parity values (P + Q, e.g. Reed–Solomon)."),
    ("RAID 1+0 (RAID 10) combines:",
     ["Mirroring and striping", "Parity and compression", "Encryption and parity", "Caching and paging"], 0, "Pairs of disks are mirrored and data is striped across the pairs."),
    ("With five 1 TB disks in RAID 5, the usable capacity is:",
     ["4 TB", "5 TB", "2.5 TB", "3 TB"], 0, PYQ + "One disk's worth of space holds parity: (n − 1) × size."),
    ("Swap space on a disk is used for:",
     ["Holding pages or processes moved out of main memory", "Storing the BIOS", "Keeping the MBR", "Caching DNS entries"], 0,
     "It can be a raw partition (faster) or a file in the normal file system."),
    ("Storage attached to a network and accessed through file-level protocols such as NFS or CIFS is:",
     ["Network-attached storage (NAS)", "Direct-attached storage", "Storage-area network only", "Tertiary storage"], 0,
     "A SAN is a private network giving block-level access between servers and storage units."),
    ("Magnetic tape is mainly used today for:",
     ["Backup and archiving, since access is sequential and slow", "Main memory", "CPU registers", "Cache memory"], 0, PYQ + "Once positioned, tape can transfer data quickly."),
    ("Consider the statements:\nI. In an HDD the platter rotates at a constant angular velocity.\nII. Outer tracks of an HDD can hold more sectors than inner tracks (zoned recording).",
     I_II, 2, "Both are features of modern hard disks."),
    ("Assertion (A): RAID 5 survives the failure of any one disk.\nReason (R): Lost blocks can be rebuilt from the other data blocks and the parity block.",
     AR, 0, "Parity is the XOR of the data blocks in the stripe."),
    ("Assertion (A): RAID 0 improves reliability.\nReason (R): RAID 0 stripes data across several disks.",
     AR, 3, "Striping improves performance but makes reliability worse – the array fails if any one disk fails."),
    ("Match the RAID level with its feature:\na. RAID 0  b. RAID 1  c. RAID 5  d. RAID 6\n1. Striping, no redundancy  2. Mirroring  3. Distributed parity  4. Double parity",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "RAID matching is a favourite KSET question."),
    ("The data transfer rate of a disk depends on:",
     ["Rotational speed and the amount of data per track", "Only the size of RAM", "The CPU's clock alone", "The number of files"], 0,
     "Faster rotation and denser tracks give higher transfer rates."),
    ("Which of the following is NOT part of disk management by the OS?",
     ["Choosing the CPU time quantum", "Disk formatting", "Boot block management", "Bad-block recovery"], 0, "The time quantum belongs to CPU scheduling."),
    ("A disk with 4 platters (both surfaces used), 1024 tracks per surface, 64 sectors per track and 512-byte sectors has a capacity of:",
     ["256 MB", "128 MB", "512 MB", "64 MB"], 0, PYQ + "8 × 1024 × 64 × 512 B = 2^3 × 2^10 × 2^6 × 2^9 = 2^28 B = 256 MB."),
    ("NVM (non-volatile memory) devices such as SSDs need 'garbage collection' because:",
     ["Pages cannot be overwritten in place; blocks must be erased before reuse", "They lose data when power is off",
      "They use rotating platters", "They have a seek arm"], 0, "Over-provisioning keeps spare blocks for this work."),
]

DISK_SCHED = [
    ("Given the request sequence = {176, 79, 34, 60, 92, 11, 41, 114}. The initial head position at 50, then the total seek count using SSTF is",
     ["201", "202", "203", "204"], 3,
     "50 → 41 → 34 → 11 → 60 → 79 → 92 → 114 → 176: 9 + 7 + 23 + 49 + 19 + 13 + 22 + 62 = 204." + NOTE, "GFGC 2021 CS · Q51"),
    ("Order the steps for handling a disk I/O request in a typical disk scheduling algorithm\na. The request is placed in the disk queue\nb. The scheduler selects the next request\nc. The request is serviced by reading/writing to disk\nd. The disk arm moves to the requested location",
     ["a → b → c → d", "b → c → a → d", "a → b → d → c", "b → c → d → a"], 2,
     "Queue the request, choose it, move the arm, then read or write." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q43"),
    ("____ is the disk scheduling algorithm used in Solid State Drives (SSDs)",
     ["SCAN", "SSTF", "C-SCAN", "FCFS"], 3,
     "SSDs have no seek time, so a simple FCFS (NOOP) policy is typically used." + NOTE, "KSET 2024 CS&A · Q46"),
    ("Which of the following disk scheduling algorithms may result in starvation?",
     ["SCAN", "LOOK", "SSTF", "C-SCAN"], 2,
     "SSTF keeps serving nearby requests, so far-away requests can wait indefinitely." + NOTE, "KSET 2025 CS&A · Q49"),
    ("A disk queue has requests for cylinders 98, 183, 37, 122, 14, 124, 65, 67 and the head is at 53. The total head movement under FCFS is:",
     ["640 cylinders", "236 cylinders", "208 cylinders", "382 cylinders"], 0,
     PYQ + "45 + 85 + 146 + 85 + 108 + 110 + 59 + 2 = 640 (Silberschatz's standard example)."),
    ("For the same queue 98, 183, 37, 122, 14, 124, 65, 67 with the head at 53, SSTF gives a total head movement of:",
     ["236 cylinders", "640 cylinders", "208 cylinders", "299 cylinders"], 0,
     "53 → 65 → 67 → 37 → 14 → 98 → 122 → 124 → 183."),
    ("For the queue 98, 183, 37, 122, 14, 124, 65, 67, head at 53, the arm moving towards cylinder 0 under SCAN, the total head movement is:",
     ["236 cylinders", "208 cylinders", "640 cylinders", "183 cylinders"], 0,
     PYQ + "53 down to 0 (53), then up to 183 (183): 53 + 183 = 236."),
    ("For the queue 98, 183, 37, 122, 14, 124, 65, 67, head at 53 moving towards 0 under LOOK, the total head movement is:",
     ["208 cylinders", "236 cylinders", "299 cylinders", "640 cylinders"], 0,
     "LOOK reverses at the last request (14) instead of going to 0: 39 + 169 = 208."),
    ("The disk scheduling algorithm in which the arm moves from one end to the other servicing requests, then reverses, is:",
     ["SCAN (elevator algorithm)", "FCFS", "SSTF", "Round robin"], 0, PYQ + "It works like a lift in a building."),
    ("C-SCAN differs from SCAN in that:",
     ["On reaching one end, the head returns to the beginning without servicing requests on the return trip", "It serves the closest request first",
      "It never reaches the disk ends", "It serves requests in arrival order"], 0, "It gives more uniform waiting times by treating cylinders as a circular list."),
    ("LOOK and C-LOOK improve on SCAN and C-SCAN by:",
     ["Moving the arm only as far as the last request in each direction", "Moving the arm faster", "Serving requests randomly", "Removing the disk queue"], 0,
     PYQ + "They 'look' for a request before continuing in a direction."),
    ("SSTF scheduling is similar in nature to which CPU-scheduling algorithm?",
     ["Shortest Job First (SJF)", "Round Robin", "FCFS", "Multilevel queue"], 0, "Like SJF, it can starve some requests."),
    ("Which disk scheduling algorithm is fair (no starvation) but generally gives the most head movement?",
     ["FCFS", "SSTF", "SCAN", "LOOK"], 0, "Requests are served strictly in arrival order."),
    ("Head at 50; requests 82, 170, 43, 140, 24, 16, 190 on a 0–199 disk. The total head movement under SSTF is:",
     ["208", "332", "642", "391"], 0, PYQ + "50 → 43 → 24 → 16 → 82 → 140 → 170 → 190: 7 + 19 + 8 + 66 + 58 + 30 + 20 = 208."),
    ("Head at 50; requests 82, 170, 43, 140, 24, 16, 190 on a 0–199 disk. The total head movement under FCFS is:",
     ["642", "208", "332", "391"], 0, "32 + 88 + 127 + 97 + 116 + 8 + 174 = 642."),
    ("Head at 50 moving towards higher cylinders; requests 82, 170, 43, 140, 24, 16, 190 on a 0–199 disk. Under SCAN the total head movement is:",
     ["332", "208", "314", "642"], 0, PYQ + "50 up to 199 (149), then down to 16 (183): 149 + 183 = 332."),
    ("Head at 50 moving towards higher cylinders; requests 82, 170, 43, 140, 24, 16, 190. Under LOOK the total head movement is:",
     ["314", "332", "208", "642"], 0, "50 up to 190 (140), then down to 16 (174): 140 + 174 = 314."),
    ("The main aim of disk scheduling is to:",
     ["Minimise seek time and maximise disk bandwidth", "Increase CPU temperature", "Reduce the number of files", "Increase rotational latency"], 0,
     "Bandwidth = bytes transferred ÷ total time from request to completion."),
    ("Which of these disk-scheduling algorithms can be called 'elevator' algorithms?",
     ["SCAN and LOOK", "FCFS and SSTF", "Only FCFS", "Only SSTF"], 0, PYQ + "Both sweep back and forth across the disk."),
    ("For a heavily loaded disk, which algorithms usually perform best?",
     ["SCAN and C-SCAN", "FCFS", "Random", "LIFO"], 0, "They are less likely to cause starvation than SSTF."),
    ("Consider the statements:\nI. SSTF always gives the minimum possible total head movement.\nII. SSTF may starve requests far from the head.",
     I_II, 1, "SSTF is greedy and not always optimal; it can also starve distant requests."),
    ("Assertion (A): FCFS disk scheduling is fair.\nReason (R): Requests are serviced in the order in which they arrive.",
     AR, 0, "It is fair but usually not fast."),
    ("Assertion (A): C-SCAN gives a more uniform waiting time than SCAN.\nReason (R): C-SCAN serves requests in both directions of arm movement.",
     AR, 2, "C-SCAN serves requests in one direction only and jumps back; that is why waiting times are more uniform."),
    ("Match the disk-scheduling algorithm with its description:\na. FCFS  b. SSTF  c. SCAN  d. C-LOOK\n1. Order of arrival  2. Closest request first  3. End to end and back  4. One direction, up to the last request, then jump",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "A common matching question."),
    ("Linux's 'deadline' I/O scheduler keeps separate read and write queues mainly to:",
     ["Prevent starvation by giving each request an expiry time", "Increase seek time", "Disable caching", "Encrypt the disk"], 0,
     "Reads are given shorter deadlines because processes usually block on them."),
    ("Head at 100, requests 55, 58, 39, 18, 90, 160, 150, 38, 184. The first request served under SSTF is:",
     ["90", "160", "55", "184"], 0, "90 is 10 cylinders away – the nearest."),
    ("Which factor makes FCFS a good choice for SSDs and NVM devices?",
     ["Access time does not depend on the position of the data", "SSDs have very long seek times", "SSDs rotate slowly", "SSDs have only one sector"], 0,
     PYQ + "Linux uses the NOOP (none) scheduler for many NVM devices."),
    ("Disk bandwidth is defined as:",
     ["Total bytes transferred divided by the total time between the first request and completion of the last transfer", "The number of tracks",
      "The rotational speed", "The seek time of one request"], 0, "Scheduling improves both access time and bandwidth."),
    ("If requests arrive mostly for cylinders near the middle of the disk, which algorithm is least likely to help?",
     ["FCFS", "SSTF", "LOOK", "C-LOOK"], 0, "FCFS ignores the head position completely."),
    ("Head at 53; queue 98, 183, 37, 122, 14, 124, 65, 67; the head moves towards higher cylinders under C-LOOK. The order of service is:",
     ["65, 67, 98, 122, 124, 183, 14, 37", "37, 14, 65, 67, 98, 122, 124, 183", "65, 67, 37, 14, 98, 122, 124, 183", "98, 183, 37, 122, 14, 124, 65, 67"], 0,
     PYQ + "After 183 the head jumps back to the lowest pending request (14) and continues upwards."),
]

FILES = [
    ("The information that are associated with an open file\n(a) Creating a file, Access rights\n(b) Opening a file, File pointer\n(c) File pointer, File open count\n(d) Disk location of the file, Access rights\nWhich of the aforementioned statements are correct?",
     ["(c) and (d)", "(a) and (d)", "(b) and (d)", "(a), (b) and (c)"], 0,
     "Silberschatz: file pointer, file-open count, disk location and access rights are kept for each open file." + NOTE, "KEA 2026 CS Paper-2 · Q46"),
    ("Which is an important file used by the system and should not be altered or removed from the disk?",
     ["Hidden file", "Archived file", "System file", "Read-only file"], 2,
     "System files (marked with the S attribute in Windows) are needed for the OS to run." + NOTE, "PGCET 2023 M.Tech CS · Q14"),
    ("The command used to change file permission is",
     ["attrib", "fdisk", "change", "modify"], 0,
     "In Windows/MS-DOS, attrib sets the read-only, hidden, system and archive attributes; fdisk partitions disks. (On Linux the command is chmod.)" + NOTE,
     "KEA 2026 KEC (NHK, 11 Jan 2026) · Q73"),
    ("When a share name ends in a dollar sign, it is a ____ share",
     ["NTFS", "Hidden", "Read", "Execute"], 1,
     "In Windows, a share such as C$ or ADMIN$ does not appear when users browse the network." + GTTC, "GTTC 2024 Technician Gr-III CS (C1) · Q35"),
    ("A file is best defined as:",
     ["A named collection of related information recorded on secondary storage", "A part of the CPU", "A type of cache", "An interrupt"], 0,
     PYQ + "It is the smallest allotment of logical secondary storage."),
    ("Which of the following is NOT usually a file attribute?",
     ["The CPU burst time of the file", "Name", "Size", "Protection (access rights)"], 0, "Attributes include name, identifier, type, location, size, protection, time and user ID."),
    ("Reading records one after another in order, as on a tape, is called:",
     ["Sequential access", "Direct access", "Indexed access", "Random hashing"], 0, PYQ + "read_next() and write_next() move the file pointer forward."),
    ("Access that lets a program read or write any numbered block of a file in no particular order is:",
     ["Direct (relative) access", "Sequential access", "Tape access", "Batch access"], 0, "Databases need direct access."),
    ("Indexed sequential access (ISAM) uses:",
     ["An index to find the block, then sequential search within it", "Only a hash table", "Only a tape", "No index at all"], 0,
     "Large files may use a multilevel index."),
    ("The directory structure in which each user has his own directory under a master file directory is:",
     ["Two-level directory", "Single-level directory", "Acyclic graph", "General graph"], 0, PYQ + "It isolates users but makes sharing hard."),
    ("Which directory structure allows a file or subdirectory to be shared by appearing in more than one directory, without cycles?",
     ["Acyclic-graph directory", "Single-level directory", "Two-level directory", "Tree only"], 0, "Sharing is done with links."),
    ("In a tree-structured directory, a path that begins at the root is called:",
     ["An absolute path name", "A relative path name", "A link", "A mount point"], 0, PYQ + "A relative path begins at the current directory, e.g. ../docs."),
    ("Attaching a file system to the existing directory tree at a given directory is called:",
     ["Mounting", "Formatting", "Linking", "Booting"], 0, "The directory is the mount point, e.g. /mnt/usb on Linux."),
    ("In UNIX, file access rights are given for three classes of users:",
     ["Owner, group and others (universe)", "Admin, guest and root", "Read, write and execute", "Kernel, user and shell"], 0,
     PYQ + "Each class has read, write and execute bits – e.g. rwxr-x--- = 750."),
    ("The octal permission 754 on a UNIX file means:",
     ["Owner rwx, group r-x, others r--", "Owner r-x, group rwx, others r--", "Owner rw-, group r-x, others r--", "Everyone rwx"], 0,
     "7 = 4 + 2 + 1 (rwx), 5 = 4 + 1 (r-x), 4 = r--."),
    ("A file type is commonly indicated in Windows by:",
     ["The file-name extension, such as .exe or .docx", "The file's size", "The disk sector", "The directory's colour"], 0,
     "UNIX instead uses a 'magic number' at the start of some files."),
    ("Consistency semantics that make writes to an open file visible immediately to other users who have it open are:",
     ["UNIX semantics", "Session semantics", "Immutable-shared-file semantics", "Transaction semantics only"], 0,
     PYQ + "Session semantics (AFS) show changes only after the file is closed."),
    ("A file that, once declared shared by its creator, cannot be modified is called:",
     ["An immutable shared file", "A hidden file", "A system file", "A pipe"], 0, "Its name may not be reused and its contents cannot change."),
    ("Consider the statements:\nI. A hard link points directly to the file's inode.\nII. A symbolic (soft) link stores the path name of the target file.",
     I_II, 2, "Deleting the target leaves a dangling symbolic link, but a hard link keeps the data alive."),
    ("Assertion (A): A two-level directory solves the name-collision problem between different users.\nReason (R): Each user has a separate user file directory.",
     AR, 0, "Two users can then have files with the same name."),
    ("Assertion (A): In a single-level directory, two users can have files with the same name.\nReason (R): A single-level directory keeps all files in one directory.",
     AR, 3, "Since all files share one directory, names must be unique."),
    ("Which of the following operations on a file needs the file to be searched in the directory first?",
     ["Open", "Reposition within an already opened file", "Read from an already opened file using its file handle", "Write using an open-file index"], 0,
     PYQ + "open() searches the directory once and returns an index into the open-file table."),
    ("A lock that allows several processes to read a file at once but only one to write is:",
     ["Shared lock for readers and exclusive lock for writers", "Mandatory lock only", "Spinlock", "Deadlock"], 0, "Windows uses mandatory locks; UNIX uses advisory locks."),
    ("Match the access method with an example:\na. Sequential  b. Direct  c. Indexed\n1. Reading a tape  2. Airline seat record by number  3. Finding a book via a catalogue",
     ["a-1, b-2, c-3", "a-2, b-1, c-3", "a-3, b-2, c-1", "a-1, b-3, c-2"], 0, "Indexed access uses an index like a library catalogue."),
    ("The OS keeps a table with information about all open files. The file is removed from this table when:",
     ["The file-open count drops to zero after the last close", "The file is read once", "The disk is formatted", "The CPU is idle"], 0,
     PYQ + "Each process also has its own per-process open-file table."),
    ("In MS-DOS, the command used to create a new directory is:",
     ["MD (MKDIR)", "CD", "RD", "DIR"], 0, "CD changes, RD removes and DIR lists directories."),
    ("The Windows file system that supports file permissions, encryption, compression and journaling is:",
     ["NTFS", "FAT16", "FAT32", "CDFS"], 0, PYQ + "FAT32 is simpler and is still used on USB drives; exFAT removes FAT32's 4 GB file-size limit."),
    ("The maximum size of a single file on a FAT32 volume is:",
     ["4 GB minus 1 byte", "2 TB", "16 EB", "32 MB"], 0, "exFAT and NTFS allow much larger files."),
    ("Which of these is a garbage-collection problem specific to general-graph directories?",
     ["Cycles can make files unreachable while their reference counts are not zero", "Files cannot be named", "No sharing is possible", "Paths are too short"], 0,
     PYQ + "Acyclic graphs avoid this by forbidding links to directories."),
    ("The protection approach that associates with each file a list of users and their allowed operations is:",
     ["An access-control list (ACL)", "A page table", "A free-space list", "A FAT chain"], 0, "Condensed versions use owner, group and universe classes."),
]

ALLOC = [
    ("Which of the following file allocation methods would be efficient when dealing with a large number of small sized files?\ni. Contiguous allocation\nii. Linked allocation\niii. Indexed allocation\niv. File Allocation Table (FAT)",
     ["i and iii only", "ii and iv only", "i and ii only", "iii and iv only"], 1,
     "The official key prefers linked allocation and FAT, which waste no space on an index block for each small file." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q44"),
    ("Contiguous allocation of disk space for files suffers from:",
     ["External fragmentation and difficulty in growing files", "No problems at all", "Slow sequential access", "Pointer overhead in every block"], 0,
     PYQ + "It gives excellent sequential and direct access, as on CDs."),
    ("In contiguous allocation, a file is described in the directory by:",
     ["Starting block and length", "Only an index block", "A chain of pointers in each block", "A hash value"], 0, "Block b + i is the i-th block of a file starting at b."),
    ("Linked allocation of files gives:",
     ["No external fragmentation, but direct access is slow", "Fast direct access", "Need for compaction", "No pointer overhead"], 0,
     "To reach block i, the chain from the first block must be followed."),
    ("The File Allocation Table (FAT) used by MS-DOS is a variation of:",
     ["Linked allocation", "Contiguous allocation", "Indexed allocation with inodes", "Hashed allocation"], 0,
     PYQ + "The chain of pointers is kept in a table at the start of the volume rather than in the blocks."),
    ("Indexed allocation brings all the pointers of a file together into:",
     ["An index block", "The boot block", "The FAT", "The superblock"], 0, "Direct access is fast; small files waste most of the index block."),
    ("A UNIX inode has 12 direct pointers and single, double and triple indirect pointers. With 4 KB blocks and 4-byte pointers, a single indirect block holds:",
     ["1024 pointers", "512 pointers", "4096 pointers", "256 pointers"], 0, PYQ + "4096 / 4 = 1024 block addresses."),
    ("With 4 KB blocks, 4-byte block pointers and 12 direct pointers, the largest file reachable with only the direct and single-indirect pointers is:",
     ["4144 KB (12 × 4 KB + 1024 × 4 KB)", "48 KB", "4 MB exactly", "1 GB"], 0, "48 KB + 4096 KB = 4144 KB."),
    ("The UNIX inode scheme that combines direct and multi-level indirect blocks is called:",
     ["Combined scheme", "Contiguous scheme", "Linked scheme", "Bit-vector scheme"], 0, PYQ + "Small files need only direct blocks, so access is fast."),
    ("A bit vector (bitmap) for free-space management uses one bit per:",
     ["Disk block, 1 = free and 0 = allocated (Silberschatz convention)", "File", "Directory", "Track"], 0,
     "It is simple and makes it easy to find runs of free blocks."),
    ("A 1 TB disk with 4 KB blocks needs a free-space bitmap of about:",
     ["32 MB", "256 MB", "4 MB", "1 GB"], 0, PYQ + "2^40 / 2^12 = 2^28 blocks → 2^28 bits = 2^25 bytes = 32 MB."),
    ("Keeping the address of the first free block, with each free block pointing to the next, is the free-space method called:",
     ["Linked list", "Bit vector", "Counting", "Grouping"], 0, "Grouping stores n free-block addresses in the first free block; counting stores (address, count) pairs."),
    ("The structure on disk that contains the details of a volume – number of blocks, block size, free-block count – is called the superblock in UNIX and the ____ in NTFS.",
     ["Master file table", "Boot block", "Inode table", "FAT"], 0, PYQ + "The boot control block holds the information needed to boot from the volume."),
    ("In the layered file system design, the layer that translates logical block addresses to physical block addresses is the:",
     ["File-organisation module", "Logical file system", "I/O control (device drivers)", "Application programs"], 0,
     "Layers: application → logical file system → file-organisation module → basic file system → I/O control → devices."),
    ("A directory implemented as a linear list of file names has the disadvantage of:",
     ["Slow linear search for a file", "Collisions", "No support for deletion", "Fixed number of entries always"], 0, PYQ + "A hash table speeds up search but must handle collisions."),
    ("Keeping frequently used directory entries and disk blocks in main memory to speed up the file system uses a:",
     ["Buffer cache / page cache", "TLB", "Swap space", "Spooler"], 0, "A unified buffer cache avoids double caching of memory-mapped files."),
    ("A journaling (log-structured) file system records metadata changes in a log first so that:",
     ["The file system can be recovered quickly after a crash", "Files become read-only", "Disk space is doubled", "No backup is ever needed"], 0,
     PYQ + "ext4, NTFS and XFS are journaling file systems; fsck-style full checks are avoided."),
    ("The UNIX program that checks and repairs file-system consistency after a crash is:",
     ["fsck", "grep", "chmod", "ping"], 0, "Windows uses chkdsk."),
    ("Backing up only the files changed since the last full backup is called:",
     ["An incremental backup", "A full backup", "A mirror", "A snapshot of RAM"], 0, PYQ + "A restore needs the full backup plus every incremental backup since."),
    ("Consider the statements:\nI. Linked allocation supports efficient direct access.\nII. Indexed allocation supports direct access without external fragmentation.",
     I_II, 1, "Linked allocation needs a pointer chase for direct access."),
    ("Assertion (A): Contiguous allocation gives fast direct access.\nReason (R): The address of any block can be computed from the starting block and the block number.",
     AR, 0, "Block b + i can be reached directly."),
    ("Assertion (A): FAT allocation needs no table in memory.\nReason (R): FAT is a variation of linked allocation.",
     AR, 3, "The FAT itself is a table, and it is usually cached in memory for speed."),
    ("Match the allocation method with its drawback:\na. Contiguous  b. Linked  c. Indexed\n1. External fragmentation  2. Slow direct access  3. Index-block overhead for small files",
     ["a-1, b-2, c-3", "a-2, b-1, c-3", "a-3, b-2, c-1", "a-1, b-3, c-2"], 0, PYQ + "The basic comparison of allocation methods."),
    ("Which allocation method was used by the original UNIX file system and ext2/ext3?",
     ["Indexed allocation with inodes", "Contiguous allocation only", "FAT", "Hashing"], 0, "ext4 adds extents – contiguous runs of blocks."),
    ("An 'extent' in file systems such as ext4 and NTFS is:",
     ["A contiguous run of blocks described by a start and a length", "A single sector", "A free-space bit", "A directory name"], 0,
     PYQ + "Extents reduce metadata and fragmentation for large files."),
    ("A 'virtual file system' (VFS) layer in an OS allows:",
     ["Different file-system types to be accessed through the same system-call interface", "Files to be stored only in memory", "Only one file system", "Disk encryption"], 0,
     "Linux VFS supports ext4, XFS, NFS, FAT and many others."),
    ("Which network file system protocol was developed by Sun and is widely used in UNIX/Linux?",
     ["NFS", "SMB/CIFS", "FTP", "SMTP"], 0, PYQ + "Windows networks use SMB (CIFS)."),
    ("In a FAT file system, the FAT entry for the last block of a file contains:",
     ["A special end-of-file value", "The first block of the next file", "The file's name", "Zero always means the last block"], 0,
     "Unused blocks are shown by a table value of 0."),
    ("Defragmentation of a disk mainly helps to:",
     ["Place the blocks of each file contiguously to speed up access", "Delete viruses", "Increase disk capacity", "Encrypt files"], 0,
     "SSDs should not be defragmented in the usual way; they use TRIM instead."),
    ("The counting method of free-space management is efficient when:",
     ["Free blocks occur in contiguous runs", "Every free block is isolated", "The disk is full", "The disk is a tape"], 0,
     PYQ + "Each entry stores the first free block and the number of free blocks following it."),
]

TOPICS = {
    "Storage Management": [("1 · Disk Structure, Disk Management and RAID", DISK),
                           ("2 · Disk Scheduling – FCFS, SSTF, SCAN, C-SCAN, LOOK", DISK_SCHED)],
    "File Systems": [("1 · File Concept, Access Methods, Directories, Mounting and Sharing", FILES),
                     ("2 · Allocation Methods, Free-space Management, Efficiency and Recovery", ALLOC)],
}
