"""Paper 2 · Unit 6 · P2-U6-06 CPU Scheduling and P2-U6-07 Deadlocks (2 topics × 2 sub-topics × 30).
References: Silberschatz, Galvin & Gagne, Operating System Concepts (10th ed., chs. 5 and 8); William Stallings, Operating Systems.
Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question number) with new
ones. Official answers come from KEA's final keys: Legislative Council Secretariat 2024 (Computer Operator P2, Sr/Jr Programmer P2,
Junior Console Operator P2 – booklet A1; final key 09-04-2025) and GTTC 2024 (Technician Gr-III CS – booklet C1, Lecturer CS –
booklet A1; final keys 30-12-2024). KSET 2023/2025 and KEA 2026 questions are reused from packs/pyq-p2.json (answers worked out
by ExamSim). A question whose key was GRACE (Programmer P2 Q11) and one whose official answer contradicts the textbooks (Console
Operator P2 Q39) are left out."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

SCHED_BASIC = [
    # --- real previous-year questions ---
    ("Which of the following is not a CPU scheduling algorithm?",
     ["Shortest Job First", "FCFS", "Round Robin", "Roll Back Scheduling"], 3,
     "Rollback is a recovery action, not a scheduling algorithm." + KLC, "Legislative Council 2024 Computer Operator P2 · Q71"),
    ("Which of the following is a disadvantage of First Come First Served (FCFS) scheduling algorithm?",
     ["It leads to starvation of processes", "It may cause high waiting time for processes", "It is a preemptive scheduling algorithm", "It requires knowledge of burst times."], 1,
     "Short jobs may wait behind a long one (convoy effect), so average waiting time can be high." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q35"),
    ("Consider the following processes and their burst times\nProcess – Burst Time: P₁ – 5, P₂ – 8, P₃ – 3, P₄ – 6, P₅ – 7\nIf the CPU scheduling is performed using Shortest Job First (SJF) (non-preemptive), then what will be the correct sequence of processes executed?",
     ["P₃, P₁, P₄, P₅, P₂", "P₃, P₁, P₂, P₅, P₄", "P₁, P₃, P₄, P₅, P₂", "P₃, P₄, P₁, P₅, P₂"], 0,
     "Shortest burst first: 3, 5, 6, 7, 8." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q36"),
    ("In SRT process scheduling algorithm, the arrival & execution time of the four processes are as follows.\nArrival time – Execution time – Process: 0 – 20 – P₁; 15 – 25 – P₂; 30 – 10 – P₃; 45 – 15 – P₄\nWhat will be the process 'P₂' total waiting time?",
     ["40", "15", "55", "20"], 1,
     "P₁ runs 0–20; P₂ runs 20–30, is preempted by P₃ (30–40), resumes 40–50; P₄ runs 50–65. P₂ waits (20 − 15) + (40 − 30) = 15." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q14"),
    ("Consider a single processor system with four processes A, B, C and D represented as given below, where for each process the first value is its arrival time and second value is its CPU burst time\nA(0, 10), B(2, 6), C(4, 3) and D(6, 7)\nWhich of the following options gives the average waiting time when preemptive Shortest Remaining Time First (SRTF) and the Non-Preemptive Shortest Job First (NP-SJF) CPU scheduling algorithms are applied to the process?",
     ["SRTF = 6  NP-SJF = 7", "SRTF = 6  NP-SJF = 7.5", "SRTF = 7  NP-SJF = 7.5", "SRTF = 7  NP-SJF = 8.5"], 1,
     "SRTF: A 0–2, B 2–4, C 4–7, B 7–11, D 11–18, A 18–26 → waits 16, 3, 0, 5 → 6. NP-SJF: A 0–10, C 10–13, B 13–19, D 19–26 → waits 0, 11, 6, 13 → 7.5." + NOTE,
     "KSET 2025 CS&A · Q42"),
    ("Consider the following set of processes that arrive at time 0 with length of the CPU burst time given in milliseconds: P1 = 26, P2 = 4, P3 = 5. What is the average waiting time for the processes that arrive in the orders P1, P2, P3 and P2, P1, P3 under FCFS policy?",
     ["18.65 and 11.32", "18.66 and 11.33", "18.64 and 11.31", "18.63 and 11.32"], 1,
     "Order 1: waits 0, 26, 30 → 56/3 ≈ 18.67. Order 2: waits 0, 4, 30 → 34/3 ≈ 11.33. Option 2 is the closest (truncated) value." + NOTE,
     "KEA 2026 CS Paper-2 · Q43"),
    ("____ is invoked when there is a need to perform process scheduling, that is when a process from the ready queue is to be selected for dispatching to the CPU.",
     ["Long-Term Scheduler", "Medium-Term Scheduler", "Short-Term Scheduler", "Non-preemptive Scheduler"], 2,
     "The short-term (CPU) scheduler picks the next ready process for the CPU." + NOTE, "KSET 2023 CS&A · Q22"),
    # --- new questions ---
    ("Process execution alternates between periods of computation and waiting for I/O. This is called the:",
     ["CPU–I/O burst cycle", "Context switch", "Thrashing", "Working set"], 0,
     "CPU-bound processes have a few long bursts; I/O-bound processes many short ones."),
    ("In preemptive scheduling:",
     ["The CPU can be taken away from a running process, e.g. when a higher-priority process arrives or a time slice ends", "A process keeps the CPU until it finishes or blocks", "Only batch jobs are run", "No context switch ever happens"], 0,
     PYQ + "Non-preemptive (cooperative) scheduling switches only when the running process terminates or waits."),
    ("A good CPU scheduling algorithm tries to:",
     ["Maximise CPU utilisation and throughput; minimise turnaround, waiting and response times", "Maximise waiting time", "Minimise throughput", "Maximise response time"], 0,
     PYQ + "The five classic scheduling criteria."),
    ("Turnaround time of a process is:",
     ["Completion time − arrival time", "Burst time − arrival time", "Waiting time − burst time", "Time of first response − arrival time"], 0,
     PYQ + "Waiting time = turnaround time − burst time."),
    ("A process arrives at time 2, has a CPU burst of 5 and completes at time 10. Its waiting time is:",
     ["3", "8", "5", "10"], 0,
     "Turnaround = 10 − 2 = 8; waiting = 8 − 5 = 3."),
    ("Response time, important in interactive systems, is the time from submission of a request until:",
     ["The first response is produced", "The process completes", "The process is swapped out", "The next I/O request"], 0,
     "It is different from turnaround time."),
    ("The number of processes that complete their execution per unit time is called:",
     ["Throughput", "Turnaround time", "Waiting time", "Response time"], 0,
     "Higher throughput means more work done."),
    ("Three processes arrive at time 0 in the order P1, P2, P3 with bursts 24, 3 and 3 ms. Under FCFS the average waiting time is:",
     ["17 ms", "3 ms", "10 ms", "27 ms"], 0,
     PYQ + "Waits 0, 24, 27 → 51/3 = 17. If the order were P2, P3, P1 the average would be (0 + 3 + 6)/3 = 3."),
    ("The 'convoy effect' – many short processes waiting behind one long CPU-bound process – is typical of:",
     ["FCFS scheduling", "Round Robin scheduling", "SJF scheduling", "Multilevel feedback scheduling"], 0,
     PYQ + "It lowers CPU and device utilisation."),
    ("Which scheduling algorithm gives the minimum average waiting time for a given set of processes?",
     ["Shortest Job First (SJF)", "FCFS", "Round Robin", "Priority with random priorities"], 0,
     PYQ + "SJF is provably optimal for average waiting time."),
    ("Processes P1–P4 arrive at time 0 with bursts 6, 8, 7 and 3. Under non-preemptive SJF the average waiting time is:",
     ["7", "10.25", "8.75", "6"], 0,
     "Order P4, P1, P3, P2: waits 0, 3, 9, 16 → 28/4 = 7."),
    ("The main practical difficulty with SJF is that:",
     ["The length of the next CPU burst is not known in advance and must be predicted", "It is preemptive only", "It needs a time quantum", "It always causes deadlock"], 0,
     PYQ + "Predicted with exponential averaging: τ(n+1) = α·t(n) + (1 − α)·τ(n)."),
    ("Using exponential averaging with α = 0.5, a previous prediction τ = 10 ms and an actual last burst t = 6 ms, the next predicted burst is:",
     ["8 ms", "6 ms", "10 ms", "16 ms"], 0,
     "0.5 × 6 + 0.5 × 10 = 8."),
    ("Shortest Remaining Time First (SRTF) is:",
     ["The preemptive version of SJF", "The non-preemptive version of priority scheduling", "Another name for FCFS", "Round Robin with a small quantum"], 0,
     "A newly arrived process with a shorter remaining time preempts the running one."),
    ("A drawback of SJF and SRTF is that:",
     ["Long processes may starve if short ones keep arriving", "Short processes always wait longest", "They cannot be used in batch systems", "They have very high context-switch overhead in all cases"], 0,
     "Ageing can be used to prevent starvation."),
    ("The simplest CPU scheduling algorithm to implement, using a FIFO queue, is:",
     ["FCFS", "SRTF", "Multilevel feedback queue", "Lottery scheduling"], 0,
     "New processes join the tail; the CPU goes to the head."),
    ("Match the scheduling measure with its definition:\na. Turnaround time  b. Waiting time  c. Response time  d. Throughput\n1. Processes completed per unit time  2. Time until the first response  3. Total time spent in the ready queue  4. Completion time − arrival time",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Criteria matching is common."),
    ("Consider the statements:\nI. SJF minimises the average waiting time.\nII. FCFS is a preemptive algorithm.\nWhich is/are correct?",
     I_II, 0, "FCFS is non-preemptive."),
    ("Assertion (A): FCFS scheduling may cause the convoy effect.\nReason (R): Short processes have to wait behind a long CPU-bound process.",
     AR, 0, "That is the definition of the convoy effect."),
    ("A Gantt chart in CPU scheduling shows:",
     ["Which process runs on the CPU during each interval of time", "The memory map of processes", "The file allocation table", "The network topology"], 0,
     "Numerical scheduling questions are solved by drawing one."),
    ("Which scheduling algorithm can be either preemptive or non-preemptive?",
     ["SJF (non-preemptive SJF or preemptive SRTF)", "FCFS only", "Round Robin only", "None"], 0,
     "Priority scheduling can also be either."),
    ("In a non-preemptive scheduler, a context switch to another process happens only when the running process:",
     ["Terminates or switches to the waiting state", "Uses up a time quantum", "Is interrupted by a higher-priority arrival", "Reads a variable"], 0,
     "Windows 3.x and early Mac OS used cooperative (non-preemptive) scheduling."),
    ("Which criterion matters MOST for an interactive (time-sharing) user?",
     ["Response time", "Throughput", "Turnaround time of batch jobs", "Disk utilisation"], 0,
     "Users want the system to react quickly."),
]

SCHED_ADV = [
    # --- real previous-year questions ---
    ("There are 10 different processes running on a workstation. Idle processes are waiting for an input event in the input Queue. Busy processes are scheduled with Round Robin time sharing method. Which of the following quantum times is the best value for small response times, if the processes have a short run time, eg., less than 10 ms?",
     ["tQ = 15 ms", "tQ = 40 ms", "tQ = 45 ms", "tQ = 50 ms"], 0,
     "A quantum just above the typical burst lets most processes finish in one slice while keeping response time small." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q1"),
    ("Which of the following statement/statements is/are true?\nI. Shortest remaining time first scheduling may cause starvation.\nII. Preemptive scheduling may cause starvation.\nIII. Round Robin is better than FCFS in terms of response time.",
     ["I only", "I and III only", "II and III only", "I, II and III"], 3,
     "All three are true." + KLC, "Legislative Council 2024 Sr/Jr Programmer P2 · Q2"),
    ("Match the following with respect to scheduling algorithm\na) FCFS  b) SJF  c) RR  d) Priority Scheduling\ni. Allocation based on the lowest CPU burst time  ii. According to the arrival time of the process, the CPU is allocated.  iii. According to the priority  iv. According to the order of the process arrives with fixed time quantum.",
     ["a - i, b - iii, c - iv, d - ii", "a - ii, b - i, c - iv, d - iii", "a - iv, b - iii, c - i, d - ii", "a - iv, b - ii, c - iii, d - i"], 1,
     "FCFS – arrival order; SJF – shortest burst; RR – arrival order with a fixed quantum; Priority – by priority." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q13"),
    ("Considering the following statements, choose the correct option.\nAssertion (A): The Round Robin (RR) scheduling algorithm is considered a preemptive scheduling algorithm.\nReason (R): The Round Robin (RR) algorithm allocates a fixed time slice to each process in the ready queue before moving to the next process.",
     ["Both (A) and (R) are true but reason is not the correct explanation of assertion.", "Both (A) and (R) are true and reason is the correct explanation of assertion", "(A) is true but (R) is false", "(A) is false but (R) is true"], 1,
     "When the time slice expires the process is preempted – that is why RR is preemptive." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q41"),
    ("In a priority scheduling algorithm, which of the following are true?\na. Higher priority processes are executed first\nb. Starvation can occur if low-priority processes are never executed\nc. Equal priority processes are executed in the order they arrive.\nd. Preemption is mandatory in priority scheduling",
     ["a and b", "a, b and c", "a, b, c and d", "a, c and d"], 1,
     "Priority scheduling can be preemptive or non-preemptive, so (d) is false; ties are broken FCFS." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q46"),
    ("Which scheduling algorithm is used in realtime systems to ensure that critical processes meet their deadlines?",
     ["Round Robin (RR)", "Shortest Job First (SJF)", "Earliest Deadline First (EDF)", "First Come, First Served (FCFS)"], 2,
     "EDF gives the highest priority to the process with the nearest deadline." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q50"),
    ("Match List-I with List-II:\n(a) FCFS Scheduling\n(b) SJF Scheduling\n(c) Priority Scheduling\n(d) RR Scheduling\n(i) Shortest burst time\n(ii) Indefinite Blocking\n(iii) Time slice\n(iv) Convoy effect",
     ["a – ii, b – iii, c – i, d – iv", "a – iii, b – ii, c – iv, d – i", "a – iv, b – i, c – ii, d – iii", "a – i, b – iii, c – ii, d – iv"], 2,
     "FCFS suffers the convoy effect, SJF picks the shortest burst, priority scheduling risks starvation, RR uses a time quantum." + NOTE,
     "KEA 2026 CS Paper-2 · Q50"),
    # --- new questions ---
    ("In Silberschatz's convention for priority scheduling:",
     ["A smaller priority number means a higher priority", "A larger number always means higher priority", "All processes have equal priority", "Priority is fixed at zero"], 0,
     "Conventions differ between systems, so read each question carefully."),
    ("Starvation of low-priority processes in priority scheduling is solved by:",
     ["Ageing – gradually increasing the priority of waiting processes", "Thrashing", "Paging", "Using a smaller quantum"], 0,
     PYQ + "Ageing is the standard answer."),
    ("Round Robin scheduling is designed especially for:",
     ["Time-sharing (interactive) systems", "Batch systems only", "Real-time hard deadlines only", "Single-user embedded devices"], 0,
     PYQ + "It is FCFS with preemption after each time quantum."),
    ("In Round Robin, if the time quantum is made very large, the algorithm behaves like:",
     ["FCFS", "SJF", "Priority scheduling", "SRTF"], 0,
     PYQ + "If it is very small, context-switch overhead dominates."),
    ("Processes P1, P2, P3 arrive at time 0 with bursts 24, 3 and 3 ms. With Round Robin and quantum 4 ms, the average waiting time is about:",
     ["5.67 ms", "17 ms", "3 ms", "7 ms"], 0,
     PYQ + "Order P1(0–4), P2(4–7), P3(7–10), P1(10–30): waits 6, 4, 7 → 17/3 ≈ 5.67."),
    ("A rule of thumb for choosing the RR time quantum is that:",
     ["About 80% of CPU bursts should be shorter than the quantum", "The quantum should be 1 µs", "The quantum should be longer than every burst", "The quantum should equal the context-switch time"], 0,
     "Then most processes finish in one quantum without too many switches."),
    ("In a multilevel queue scheduler:",
     ["The ready queue is split into separate queues (e.g. foreground interactive, background batch), and a process stays permanently in one queue", "Processes freely move between queues based on behaviour", "There is only one queue", "Each process has its own CPU"], 0,
     PYQ + "Each queue may use its own algorithm, e.g. RR for foreground and FCFS for background."),
    ("A multilevel feedback queue scheduler differs from a multilevel queue because:",
     ["Processes can move between queues – CPU-hungry processes move down, long-waiting ones move up", "It has only one queue", "It is never preemptive", "It cannot use Round Robin"], 0,
     PYQ + "It is the most general – and most complex – scheduling scheme."),
    ("Rate-monotonic scheduling for periodic real-time tasks:",
     ["Assigns static priorities – the shorter the period, the higher the priority", "Assigns priorities by nearest deadline dynamically", "Uses a time quantum", "Picks tasks at random"], 0,
     PYQ + "EDF assigns dynamic priorities by deadline."),
    ("The worst-case CPU-utilisation bound for rate-monotonic scheduling of two tasks is about:",
     ["83%", "100%", "50%", "69%"], 0,
     "n(2^(1/n) − 1): about 83% for n = 2, tending to 69% as n grows. EDF can, in theory, reach 100%."),
    ("Processor affinity means:",
     ["Keeping a process on the same processor to benefit from its warm cache", "Running a process on all processors at once", "Giving a process the highest priority", "Moving processes randomly"], 0,
     "Soft affinity tries to do this; hard affinity guarantees it."),
    ("In multiprocessor scheduling, moving tasks from an overloaded processor to an idle one is:",
     ["Load balancing (push or pull migration)", "Thrashing", "Swapping", "Spooling"], 0,
     "It may conflict with processor affinity."),
    ("Linux's default scheduler for normal tasks, the Completely Fair Scheduler (CFS), keeps runnable tasks in a:",
     ["Red-black tree ordered by virtual runtime (vruntime)", "Simple FIFO queue", "Hash table by PID", "Stack"], 0,
     PYQ + "The task with the smallest vruntime runs next."),
    ("Windows schedules threads using a priority scheme with:",
     ["32 priority levels", "4 levels", "140 levels", "2 levels"], 0,
     "Levels 16–31 are the real-time class; 1–15 the variable class."),
    ("Lottery scheduling gives each process tickets and picks a random ticket. It is an example of:",
     ["Proportional-share scheduling", "FCFS", "Rate-monotonic scheduling", "SJF"], 0,
     "A process with more tickets gets more CPU time on average."),
    ("In thread scheduling, competition among the user threads of the same process (many-to-one / many-to-many models) is called:",
     ["Process-contention scope (PCS)", "System-contention scope (SCS)", "Global scope", "Kernel scope"], 0,
     "Kernel threads compete with all threads in the system (SCS)."),
    ("Match the scheduler with its key idea:\na. Rate-monotonic  b. Earliest Deadline First  c. Linux CFS  d. Multilevel feedback queue\n1. Processes move between queues according to behaviour  2. Fair share using a red-black tree of virtual runtimes  3. Dynamic priority by the nearest deadline  4. Static priority by the shortest period",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Advanced scheduling matching."),
    ("Consider the statements:\nI. Ageing prevents starvation in priority scheduling.\nII. Round Robin with a very large quantum behaves like FCFS.\nWhich is/are correct?",
     I_II, 2, "Both are standard results."),
    ("Assertion (A): A very small Round Robin quantum makes the system inefficient.\nReason (R): Context-switch overhead becomes large compared with useful work.",
     AR, 0, "The quantum should be large compared with the context-switch time."),
    ("In symmetric multiprocessing (SMP) scheduling:",
     ["Each processor is self-scheduling, from a common or private ready queue", "Only one master processor schedules all others", "Processes never move between processors", "Scheduling is done by hardware alone"], 0,
     "Asymmetric multiprocessing has one master processor doing all scheduling."),
    ("Which statement about preemptive priority scheduling is TRUE?",
     ["A newly arrived higher-priority process immediately takes the CPU from a lower-priority running process", "It never causes starvation", "It is the same as FCFS", "It cannot be used in real-time systems"], 0,
     "Non-preemptive priority would only put the new process at the head of the ready queue."),
    ("In Round Robin with n processes in the ready queue and quantum q, no process waits more than:",
     ["(n − 1) × q time units before its next quantum", "n × n × q", "q / n", "One quantum"], 0,
     "This bounded wait is why RR gives good response times."),
    ("Which algorithm is most suitable for a batch system where all job lengths are known in advance and average waiting time must be minimal?",
     ["SJF", "Round Robin", "Lottery scheduling", "Multilevel queue with random priorities"], 0,
     "SJF is optimal for average waiting time."),
]

DEAD_BASIC = [
    # --- real previous-year questions ---
    ("A process needs to release all resources before it makes any requests for another resources. Select the true statement from the following.",
     ["Deadlock cannot occur, but starvation can occur", "Both deadlock and starvation can occur", "Neither deadlock nor starvation can occur", "Deadlock can occur but starvation cannot occur"], 0,
     "This breaks the hold-and-wait condition, so deadlock is impossible, but a process may wait indefinitely for popular resources." + KLC,
     "Legislative Council 2024 Sr/Jr Programmer P2 · Q16"),
    ("Which is the correct sequence of steps involved in resolving deadlock using the resource allocation graph method?",
     ["Check for cycles → Identify deadlocked processes → Release Resources", "Identify deadlocked processes → Check for cycles → Release Resources", "Check for cycles → Release Resources → Identify deadlocked processes", "Identify deadlocked processes → Release Resources → Check for cycles"], 0,
     "A cycle reveals the deadlocked processes, whose resources are then released (by aborting or preempting)." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q38"),
    # --- new questions ---
    ("A deadlock is a situation in which:",
     ["Each process in a set waits for an event that only another process in the set can cause", "A process runs forever", "The CPU is idle because no process exists", "A process is waiting for I/O to complete"], 0,
     PYQ + "None of the processes can proceed."),
    ("The four necessary conditions for deadlock (Coffman conditions) are:",
     ["Mutual exclusion, hold and wait, no preemption and circular wait", "Mutual exclusion, starvation, ageing and paging", "Hold and wait, preemption, spooling and swapping", "Circular wait, thrashing, paging and segmentation"], 0,
     PYQ + "All four must hold at the same time for a deadlock."),
    ("Which of the following is NOT one of the necessary conditions for deadlock?",
     ["Preemption of resources", "Mutual exclusion", "Hold and wait", "Circular wait"], 0,
     "The condition is 'no preemption'."),
    ("In a resource-allocation graph, an edge Pi → Rj means:",
     ["Process Pi has requested resource Rj (request edge)", "Resource Rj is assigned to Pi", "Pi has released Rj", "Rj is unused"], 0,
     PYQ + "Rj → Pi is an assignment edge."),
    ("If a resource-allocation graph has no cycle, then:",
     ["No process is deadlocked", "A deadlock definitely exists", "The system is unsafe", "Every process is waiting"], 0,
     PYQ + "A cycle is necessary for deadlock."),
    ("If every resource type has exactly one instance, a cycle in the resource-allocation graph:",
     ["Implies that a deadlock has occurred", "Never implies deadlock", "Means the system is safe", "Means a process has finished"], 0,
     PYQ + "With several instances per type, a cycle is necessary but not sufficient."),
    ("The methods of handling deadlocks are:",
     ["Prevention, avoidance, detection and recovery, or ignoring the problem", "Paging, segmentation and swapping", "FCFS, SJF and Round Robin", "Compiling, linking and loading"], 0,
     PYQ + "Ignoring the problem (the 'ostrich algorithm') is what most general-purpose OSs, including Linux and Windows, actually do."),
    ("Deadlock prevention works by:",
     ["Ensuring that at least one of the four necessary conditions can never hold", "Granting requests only in safe states", "Detecting cycles periodically", "Killing all processes regularly"], 0,
     "Avoidance uses extra information to stay in safe states."),
    ("The mutual-exclusion condition generally cannot be denied for:",
     ["Intrinsically non-sharable resources such as a printer or a mutex", "Read-only files", "Shared code", "Constants"], 0,
     "Spooling a printer is one way around it."),
    ("Requiring a process to request all its resources before it begins execution prevents deadlock by denying:",
     ["Hold and wait", "Mutual exclusion", "Circular wait", "No preemption"], 0,
     PYQ + "Drawbacks: low resource utilisation and possible starvation."),
    ("Imposing a total ordering of resource types and requiring processes to request them in increasing order prevents:",
     ["Circular wait", "Mutual exclusion", "Hold and wait", "Preemption"], 0,
     PYQ + "The most practical prevention technique."),
    ("With the ordering F(tape drive) = 1, F(disk) = 5, F(printer) = 12, a process holding the disk may next request:",
     ["Only the printer", "Only the tape drive", "Both the tape drive and the printer", "No resource at all"], 0,
     "It may request only resources with a higher number."),
    ("If a process holding resources requests another that cannot be granted immediately, and all its held resources are released, the condition denied is:",
     ["No preemption", "Mutual exclusion", "Circular wait", "Hold and wait"], 0,
     "Its resources are implicitly preempted."),
    ("Three processes each need at most 2 units of a resource. The minimum number of units that guarantees no deadlock is:",
     ["4", "3", "6", "2"], 0,
     PYQ + "n(k − 1) + 1 = 3 × 1 + 1 = 4."),
    ("Four processes each need at most 3 tape drives. The minimum number of drives that guarantees freedom from deadlock is:",
     ["9", "8", "12", "4"], 0,
     "4 × (3 − 1) + 1 = 9."),
    ("In a livelock:",
     ["Processes keep changing state in response to each other but make no progress", "Processes are blocked waiting forever", "The CPU is switched off", "A process is swapped out"], 0,
     "Unlike deadlocked processes, livelocked processes are not blocked."),
    ("Starvation differs from deadlock because a starving process:",
     ["Waits indefinitely while other processes continue to make progress", "Holds all resources", "Is always part of a cycle", "Cannot be helped by ageing"], 0,
     "In deadlock, none of the processes in the set can proceed."),
    ("Spooling the printer helps prevent deadlocks involving the printer by removing:",
     ["Direct mutual exclusion on the printer – processes write to a spool on disk instead", "Circular wait on the CPU", "Hold and wait on memory", "Preemption"], 0,
     "Only the printer daemon uses the printer directly."),
    ("Match the deadlock condition with its description:\na. Mutual exclusion  b. Hold and wait  c. No preemption  d. Circular wait\n1. A closed chain of processes, each waiting for the next  2. A resource is released only voluntarily  3. Holding one resource while waiting for another  4. A resource can be used by only one process at a time",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Condition matching is very common."),
    ("Consider the statements:\nI. With single-instance resources, a cycle in the resource-allocation graph means deadlock.\nII. A resource-allocation graph without a cycle may still contain a deadlock.\nWhich is/are correct?",
     I_II, 0, "No cycle means no deadlock."),
    ("Assertion (A): Requesting resources in a fixed increasing order prevents deadlock.\nReason (R): With such an ordering, a circular wait cannot form.",
     AR, 0, "This is the resource-ordering technique."),
    ("Assertion (A): A deadlock can occur when only three of the four Coffman conditions hold.\nReason (R): All four conditions are necessary for a deadlock.",
     AR, 3, "All four must hold at once, so A is false."),
    ("Ignoring deadlocks and rebooting when one occurs is jokingly called the:",
     ["Ostrich algorithm", "Banker's algorithm", "Elevator algorithm", "Clock algorithm"], 0,
     "It is used when deadlocks are rare and prevention is costly."),
    ("A classic deadlock example: P1 holds the scanner and waits for the printer, while P2 holds the printer and waits for the scanner. Which condition is clearly visible?",
     ["Circular wait", "Starvation only", "Thrashing", "Paging"], 0,
     "The other three conditions also hold."),
    ("Denying 'no preemption' is most practical for resources whose state can be easily saved and restored, such as:",
     ["CPU registers and memory", "Printers", "Tape drives in the middle of writing", "Mutex locks"], 0,
     "Printers and locks cannot simply be taken away."),
    ("Deadlock is possible only if the system has at least:",
     ["Two processes competing for resources", "One process", "No processes", "One resource of each type"], 0,
     "A single process alone cannot form a circular wait."),
    ("Which statement about deadlock prevention is TRUE?",
     ["It can reduce device utilisation and system throughput", "It needs advance knowledge of maximum claims", "It detects deadlocks after they occur", "It never restricts how processes request resources"], 0,
     "Avoidance needs advance knowledge of maximum claims."),
    ("A resource-allocation graph has a cycle, but one resource in the cycle has two instances, one of which is held by a process outside the cycle. Then:",
     ["There may be no deadlock – that process can release the instance and break the cycle", "There is certainly a deadlock", "The system has crashed", "The graph is invalid"], 0,
     "With multiple instances, a cycle is necessary but not sufficient."),
]

DEAD_AVOID = [
    # --- real previous-year questions ---
    ("Which one of the following is the deadlock avoidance algorithm?",
     ["Banker's Algorithm", "Round-Robin Algorithm", "Elevator Algorithm", "Optimal Algorithm"], 0,
     "Round Robin is CPU scheduling, the elevator algorithm (SCAN) is disk scheduling, Optimal is page replacement." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q28"),
    ("A system shares 9 tapes drives. The current allocation and maximum requirements of tapes drives for that processes are shown below.\nProcess – Current Allocation – Max. Requirement: P₁ – 3 – 7; P₂ – 1 – 6; P₃ – 3 – 5\nWhich of the following is NOT best describes the system?",
     ["Safe states P₃ → P₂ → P₁ and P₃ → P₁ → P₂ exists", "Currently not in a deadlock", "Deadlock never possible as safe status are present", "Deadlock impossible in future, even though we have safe state"], 2,
     "Available = 2. P₃ can finish (needs 2), then either P₁ or P₂, so the state is safe. KEA's key: a safe state now does not by itself mean deadlock can never happen." + GTTC,
     "GTTC 2024 Lecturer CS · Q6"),
    ("Match the following terminology of Banker's Algorithm based on the functionality\na. Available  b. Max  c. Allocation  d. Need\ni. Total demand of resource  ii. Demand for the remaining resource  iii. Now ready resource  iv. Currently allocated to each process",
     ["a – iii, b – i, c – iv, d – ii", "a – i, b – ii, c – iv, d – iii", "a – ii, b – iii, c – i, d – iv", "a – iii, b – i, c – ii, d – iv"], 0,
     "Available = free now; Max = total demand; Allocation = held now; Need = Max − Allocation." + GTTC,
     "GTTC 2024 Lecturer CS · Q54"),
    ("Which one of the following is not a deadlock recovery method?",
     ["Resource preemption", "Abort the process", "Hold and wait", "Rollback"], 2,
     "Hold and wait is one of the four necessary conditions for deadlock, not a recovery method." + NOTE, "KSET 2023 CS&A · Q24"),
    ("Consider the following snapshot of a system (Banker's algorithm):\nProcess | Allocation A B C D | Max A B C D\nP0 | 0 0 1 2 | 0 0 1 2\nP1 | 1 0 0 0 | 1 7 5 0\nP2 | 1 3 5 4 | 2 3 5 6\nP3 | 0 6 3 2 | 0 6 5 2\nP4 | 0 0 1 4 | 0 6 5 6\nAvailable = 1 5 2 0.\nFor the processes (i) P0 (ii) P1 (iii) P2 (iv) P3 (v) P4, the correct safe sequence is",
     ["(i), (ii), (iv), (v), (iii)", "(i), (v), (ii), (iii), (iv)", "(i), (iii), (ii), (iv), (v)", "(i), (v), (iv), (ii), (iii)"], 2,
     "Need: P0 0000, P1 0750, P2 1002, P3 0020, P4 0642. P0 → avail 1532; P2 → 2886; P1 → 3886; P3 → 3 14 11 8; P4 finishes. P1 or P4 cannot run straight after P0." + NOTE,
     "KEA 2026 CS Paper-2 · Q47"),
    # --- new questions ---
    ("A system is in a safe state if:",
     ["There exists a safe sequence in which every process can obtain its maximum needs and finish", "No process holds any resource", "All resources are free", "A cycle exists in the resource graph"], 0,
     PYQ + "Avoidance keeps the system always in a safe state."),
    ("Which statement about unsafe states is TRUE?",
     ["Every deadlock state is unsafe, but not every unsafe state is a deadlock", "Every unsafe state is a deadlock", "Unsafe states are always safe", "Safe states can contain deadlocks"], 0,
     PYQ + "Deadlocked states are a subset of unsafe states."),
    ("The Banker's algorithm, proposed by Dijkstra, is suitable for:",
     ["Deadlock avoidance with multiple instances of each resource type", "Deadlock detection only", "Single-instance resources only", "Page replacement"], 0,
     PYQ + "For single instances, a resource-allocation graph with claim edges is enough."),
    ("In the Banker's algorithm, Need[i][j] is calculated as:",
     ["Max[i][j] − Allocation[i][j]", "Available[j] − Allocation[i][j]", "Max[i][j] + Allocation[i][j]", "Allocation[i][j] − Max[i][j]"], 0,
     PYQ + "The most frequently asked Banker's formula."),
    ("A process has Max = (7, 5, 3) and Allocation = (0, 1, 0). Its Need is:",
     ["(7, 4, 3)", "(7, 6, 3)", "(0, 1, 0)", "(7, 5, 3)"], 0,
     "Subtract element by element."),
    ("A process has a maximum claim of 7 units and holds 3. How many more units may it still request?",
     ["4", "3", "7", "10"], 0,
     "Need = 7 − 3 = 4."),
    ("The Banker's algorithm uses the data structures:",
     ["Available, Max, Allocation and Need", "Page table and frame table", "Ready queue and job queue", "Inode and superblock"], 0,
     "Its safety algorithm takes about m × n² operations (m resource types, n processes)."),
    ("In the resource-request algorithm, a request is granted only if, after pretending to allocate it:",
     ["The resulting state is safe", "The process becomes the highest priority", "No other process exists", "The resource-allocation graph has a cycle"], 0,
     "If the state would be unsafe, the process must wait and the old state is restored."),
    ("12 tape drives; P0 (max 10, holds 5), P1 (max 4, holds 2), P2 (max 9, holds 2). Available = 3. A safe sequence is:",
     ["<P1, P0, P2>", "<P0, P1, P2>", "<P2, P0, P1>", "No safe sequence exists"], 0,
     PYQ + "P1 needs 2 → done, available 5; P0 needs 5 → done, available 10; then P2 needs 7."),
    ("In the same system, if P2 is given one more drive (available becomes 2), the state becomes:",
     ["Unsafe – only P1 can finish, and then P0 and P2 cannot", "Safe", "Deadlocked immediately", "Unchanged"], 0,
     "Silberschatz's classic example of a request that must be refused."),
    ("Deadlock avoidance requires that each process declare in advance:",
     ["The maximum number of resources of each type it may need", "Its priority", "Its arrival time", "Its page size"], 0,
     "That is why avoidance is hard to use in general-purpose systems."),
    ("For single-instance resources, deadlock detection uses a:",
     ["Wait-for graph – a cycle means deadlock", "Gantt chart", "Page table", "Banker's Need matrix only"], 0,
     PYQ + "It is obtained from the resource-allocation graph by removing the resource nodes."),
    ("For resources with several instances, the deadlock-detection algorithm:",
     ["Is similar to the Banker's safety algorithm, using Available, Allocation and Request matrices", "Looks only for cycles", "Uses page faults", "Cannot be done"], 0,
     "Processes that cannot finish are deadlocked."),
    ("How often the detection algorithm should run depends mainly on:",
     ["How often deadlocks are likely to occur and how many processes they affect", "The screen resolution", "The page size", "The compiler used"], 0,
     "It can run on every request, periodically, or when CPU utilisation drops."),
    ("The two basic approaches to recovering from deadlock are:",
     ["Process termination and resource preemption", "Paging and segmentation", "Ageing and spooling", "Compiling and linking"], 0,
     PYQ + "Termination: abort all deadlocked processes or one at a time until the cycle disappears."),
    ("When choosing a victim for abortion or preemption, the system considers:",
     ["Priority, how long the process has computed, resources used and needed, and how many processes must be aborted", "Only the alphabetical order of names", "Only the size of the program file", "Nothing – the choice is random"], 0,
     "The aim is minimum cost."),
    ("If the same process is always picked as the victim during resource preemption, the result is:",
     ["Starvation – fixed by including the number of rollbacks in the cost", "Thrashing", "A safe state", "Belady's anomaly"], 0,
     "Rollback returns the victim to a safe earlier state."),
    ("The Banker's algorithm gets its name because a bank:",
     ["Never lends cash in a way that leaves it unable to satisfy all its customers' maximum needs", "Charges interest on resources", "Keeps resources in a vault forever", "Lends only to the oldest customer"], 0,
     "Dijkstra framed the problem as a banker and customers."),
    ("Match the strategy with its approach:\na. Deadlock prevention  b. Deadlock avoidance  c. Deadlock detection  d. Deadlock recovery\n1. Abort or preempt to break an existing deadlock  2. Periodically look for cycles in the wait-for graph  3. Grant a request only if the state stays safe  4. Ensure one of the four conditions can never hold",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Strategy matching is a favourite question."),
    ("Consider the statements:\nI. Every unsafe state is a deadlock.\nII. In a safe state, the OS can avoid deadlock by allocating carefully.\nWhich is/are correct?",
     I_II, 1, "An unsafe state may lead to deadlock but is not one yet."),
    ("Assertion (A): The Banker's algorithm needs each process's maximum claim in advance.\nReason (R): It must check that every process can still finish (a safe sequence) before granting a request.",
     AR, 0, "Without maximum claims, the safety check is impossible."),
    ("In the Banker's safety algorithm, when a process Pi can finish, the vector Work is updated as:",
     ["Work = Work + Allocation_i", "Work = Work − Need_i", "Work = Max_i", "Work = 0"], 0,
     "Pi releases everything it holds."),
    ("Which of these is a deadlock PREVENTION technique rather than a recovery technique?",
     ["Requiring every process to request all resources at the start", "Aborting a deadlocked process", "Rolling back a victim", "Preempting a resource from a victim"], 0,
     "It denies the hold-and-wait condition."),
    ("Which method requires the most advance information about processes?",
     ["Deadlock avoidance", "Ignoring deadlocks", "Deadlock detection", "Recovery by termination"], 0,
     "Avoidance needs each process's maximum demands."),
    ("Aborting all deadlocked processes at once is:",
     ["Certain to break the deadlock, but expensive because their work is lost", "Never effective", "A prevention method", "The same as ageing"], 0,
     "Aborting one at a time is cheaper but needs repeated detection."),
]

TOPICS = {
    "CPU Scheduling": [("1 · Scheduling Criteria, FCFS, SJF and SRTF", SCHED_BASIC),
                       ("2 · Priority, Round Robin, Multilevel, Multiprocessor and Real-time Scheduling", SCHED_ADV)],
    "Deadlocks": [("1 · Deadlock Conditions, Resource-allocation Graph and Prevention", DEAD_BASIC),
                  ("2 · Deadlock Avoidance (Banker's Algorithm), Detection and Recovery", DEAD_AVOID)],
}
