"""Paper 2 · Unit 6 · P2-U6-05 Threads (2 sub-topics × 30).
Coverage (planner): multicore programming, multithreading models, thread libraries, implicit threading, threading issues.
References: Silberschatz, Galvin & Gagne, Operating System Concepts (10th ed., ch. 4); POSIX Pthreads and Java API documentation.
Real previous-year questions (exact wording and printed option order, `source` = paper and question number): Legislative Council
2024 Junior Console Operator P2 (booklet A1, KEA official final key) and KSET 2023/2024, KEA 2026 CS and PGCET 2024 M.Tech CS
(answers worked out by ExamSim). Obvious printing typos are corrected."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

CONCEPTS = [
    # --- real previous-year questions ---
    ("A thread is a",
     ["Task", "Process", "Lightweight process", "Program"], 2,
     "A thread shares its process's code, data and files but has its own registers and stack – a lightweight process." + NOTE,
     "KSET 2023 CS&A · Q23"),
    ("Many-to-many multithreading Model multiplexes ____",
     ["Many-user-level threads to one kernel thread", "Many-user-level threads to small or equal number of kernel threads", "Each user thread to a kernel thread", "One kernel thread to many-user-level threads"], 1,
     "Silberschatz's definition of the many-to-many model." + NOTE,
     "KEA 2026 CS Paper-2 · Q44"),
    ("Listed below are some Operating System abstractions and the hardware components. Which matching pair is correct?\na) Thread\nb) Virtual address space\nc) File system\nd) Signal\ni. Interrupt\nii. Memory\niii. CPU\niv. Disc",
     ["a – iii, b – ii, c – iv, d – i", "a – iii, b – iv, c – i, d – ii", "a – ii, b – iii, c – iv, d – i", "a – iv, b – ii, c – i, d – iii"], 0,
     "Threads abstract the CPU, address spaces abstract memory, file systems abstract the disk and signals abstract interrupts." + NOTE,
     "KSET 2024 CS&A · Q47"),
    ("Which of the following is true for instruction execution multicore processor?",
     ["It contains multiple ALUs", "It only works on a single task at a time", "It can execute more instructions in parallel", "It is more power consuming"], 2,
     "Several cores execute instruction streams (threads) in parallel." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q32"),
    ("A thread is usually defined as a \"lightweight process\" because an operating system maintains smaller data structures for a thread than for a process. In relation to this, which of the following is true?",
     ["On per-thread basis, the OS maintains only CPU register state", "The OS does not maintain a separate stack for each thread", "On per-thread basis, the OS does not maintain virtual memory state", "On per-thread basis, the OS maintains only scheduling and accounting information"], 2,
     "Threads of a process share one address space, so no per-thread virtual-memory state is kept; each thread still has its own registers, stack and scheduling information." + NOTE,
     "PGCET 2024 M.Tech CS · Q45"),
    # --- new questions ---
    ("A thread is the basic unit of CPU utilisation and has its own:",
     ["Thread ID, program counter, register set and stack", "Code section and open files", "Data section and global variables", "Address space"], 0,
     PYQ + "It shares the code section, data section and OS resources such as open files with other threads of the same process."),
    ("Which of these is NOT shared by the threads of the same process?",
     ["The stack", "The code section", "Global data", "Open files"], 0,
     PYQ + "Each thread needs its own stack (and registers) for its own function calls."),
    ("The four main benefits of multithreading listed by Silberschatz are:",
     ["Responsiveness, resource sharing, economy and scalability", "Security, privacy, integrity and availability", "Speed, cost, size and weight", "Atomicity, consistency, isolation and durability"], 0,
     PYQ + "Economy: creating and switching threads is cheaper than for processes."),
    ("Compared with creating a new process, creating a new thread in the same process is:",
     ["Much cheaper, because the address space and resources are shared", "Always more expensive", "Impossible on multicore systems", "Exactly the same cost"], 0,
     "Context switching between threads of one process is also faster."),
    ("Concurrency differs from parallelism in that:",
     ["Concurrency means several tasks make progress (possible even on one core by interleaving); parallelism means tasks run at the same instant on different cores", "They mean exactly the same thing", "Parallelism is possible on a single core only", "Concurrency needs at least four cores"], 0,
     PYQ + "A single-core system can be concurrent but not parallel."),
    ("Running the same operation on different subsets of data on different cores (e.g. summing halves of an array) is:",
     ["Data parallelism", "Task parallelism", "Serial execution", "Time sharing"], 0,
     "Task parallelism distributes different tasks (operations) across cores."),
    ("By Amdahl's law, an application that is 25% serial runs on 2 cores. The maximum speed-up is about:",
     ["1.6", "2.0", "4.0", "1.25"], 0,
     PYQ + "Speed-up ≤ 1 / (S + (1 − S)/N) = 1 / (0.25 + 0.375) = 1.6."),
    ("If 50% of a program is serial, the maximum speed-up with any number of cores is:",
     ["2", "4", "Unlimited", "1.5"], 0,
     "As N → ∞, speed-up → 1/S = 1/0.5 = 2."),
    ("Which is a programming challenge of multicore systems?",
     ["Dividing work into balanced tasks, splitting data, handling data dependencies, and testing and debugging", "Choosing a keyboard layout", "Formatting the hard disk", "Selecting a screen resolution"], 0,
     "Silberschatz lists identifying tasks, balance, data splitting, data dependency, testing and debugging."),
    ("User-level threads are:",
     ["Managed by a thread library in user space, without kernel support", "Managed directly by the OS kernel", "Hardware threads of the CPU", "Separate processes"], 0,
     PYQ + "Kernel threads are supported and scheduled directly by the OS."),
    ("In the many-to-one model, if one thread makes a blocking system call:",
     ["The entire process blocks, and threads cannot run in parallel on multicore systems", "Only that thread blocks", "A new kernel thread is created", "The system crashes"], 0,
     PYQ + "All user threads share one kernel thread."),
    ("The one-to-one model, used by Linux and Windows:",
     ["Maps each user thread to its own kernel thread – more concurrency, but creating a user thread needs a kernel thread", "Maps all user threads to one kernel thread", "Has no kernel threads", "Allows only one thread per process"], 0,
     PYQ + "It allows threads to run in parallel on multiple cores."),
    ("The two-level model is a variation of the many-to-many model that also:",
     ["Allows a user thread to be bound to a particular kernel thread", "Uses only one kernel thread", "Forbids kernel threads", "Removes the thread library"], 0,
     "It combines many-to-many multiplexing with one-to-one binding."),
    ("Which model lets other threads keep running when one thread blocks AND lets threads run in parallel on several cores?",
     ["One-to-one (and many-to-many)", "Many-to-one only", "Single-threaded process", "None of the models"], 0,
     "Many-to-one fails on both counts."),
    ("Running two hardware threads on one core, so the core can switch to the other thread during a memory stall, is called:",
     ["Chip multithreading (e.g. Intel Hyper-Threading)", "Paging", "Spooling", "Swapping"], 0,
     "The OS sees each hardware thread as a logical CPU."),
    ("The data structure that holds a thread's state (ID, registers, stack pointer, state) is the:",
     ["Thread Control Block (TCB)", "File Allocation Table", "Page table", "Inode"], 0,
     "A process's PCB points to the TCBs of its threads."),
    ("A busy web server creates a separate thread for each client request mainly to:",
     ["Serve many clients at once and stay responsive", "Use more disk space", "Avoid using the network", "Reduce security"], 0,
     "Thread pools are usually used instead of creating a thread per request."),
    ("Match the multithreading model with its mapping:\na. Many-to-one  b. One-to-one  c. Many-to-many  d. Two-level\n1. Many-to-many plus binding a user thread to a kernel thread  2. Many user threads onto a smaller or equal number of kernel threads  3. Each user thread onto its own kernel thread  4. All user threads onto a single kernel thread",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "Model matching is very common in KEA and KSET papers."),
    ("Consider the statements:\nI. Threads of the same process share code and data.\nII. Threads of the same process share one stack.\nWhich is/are correct?",
     I_II, 0, "Each thread has its own stack."),
    ("Assertion (A): In the many-to-one model, threads cannot run in parallel on a multicore system.\nReason (R): Only one thread can access the kernel at a time, because all share a single kernel thread.",
     AR, 0, "That is the main limitation of the model."),
    ("Assertion (A): Concurrency is impossible on a single-core system.\nReason (R): On a single core, the CPU switches among tasks so quickly that several tasks make progress.",
     AR, 3, "R describes concurrency on one core, so A is false."),
    ("An advantage of user-level threads over kernel-level threads is that:",
     ["Switching between them needs no kernel-mode privileges, so it is fast", "A blocking system call never blocks the process", "They always run in parallel on many cores", "The kernel schedules each of them separately"], 0,
     "Their main drawback is that one blocking call can block the whole process (in many-to-one)."),
    ("Kernel-level threads are:",
     ["Created, scheduled and managed directly by the operating system", "Invisible to the operating system", "Managed only by a user library", "Used only in batch systems"], 0,
     "Linux, Windows and macOS all support kernel threads."),
    ("A word processor that checks spelling in one thread while the user types in another mainly shows the multithreading benefit of:",
     ["Responsiveness", "Scalability", "Security", "Portability"], 0,
     "The program stays interactive even while part of it is busy."),
    ("On a multiprocessor, a single-threaded process can use:",
     ["Only one processor at a time", "All processors at once", "Two processors exactly", "No processor"], 0,
     "Multithreading lets one process benefit from several cores (scalability)."),
]

LIBRARIES_ISSUES = [
    ("The three main thread libraries in use today are:",
     ["POSIX Pthreads, Windows threads and Java threads", "OpenGL, DirectX and Vulkan", "TCP, UDP and IP", "FAT, NTFS and ext4"], 0,
     PYQ + "Pthreads may be provided as a user-level or kernel-level library."),
    ("POSIX Pthreads is:",
     ["A specification (IEEE 1003.1c) for thread behaviour, not an implementation", "A Windows-only library", "A Java class", "A type of hardware thread"], 0,
     "Programs include <pthread.h>."),
    ("In Pthreads, a new thread is created with:",
     ["pthread_create()", "fork()", "CreateProcess()", "exec()"], 0,
     PYQ + "pthread_join() makes the caller wait for that thread to finish."),
    ("A thread ends its own execution in Pthreads by calling:",
     ["pthread_exit()", "pthread_join()", "pthread_create()", "wait()"], 0,
     "Returning from the thread function also ends it."),
    ("In the Windows API, threads are created with ____ and waited for with ____.",
     ["CreateThread(); WaitForSingleObject()", "fork(); wait()", "pthread_create(); pthread_join()", "start(); join()"], 0,
     "WaitForMultipleObjects() waits for several threads."),
    ("In Java, a thread can be created by:",
     ["Extending the Thread class or implementing the Runnable interface", "Only by calling fork()", "Only with CreateThread()", "Writing a main() method only"], 0,
     PYQ + "The code to run goes in the run() method."),
    ("In Java, a new thread actually begins executing when the program calls:",
     ["start()", "run() directly", "join()", "sleep()"], 0,
     "start() creates the thread and the JVM then calls run() in it."),
    ("Java's join() method makes the calling thread:",
     ["Wait until the target thread terminates", "Start a new thread", "Stop all threads", "Sleep for a fixed time"], 0,
     "It is similar to pthread_join()."),
    ("Implicit threading means that:",
     ["Compilers and run-time libraries, not the programmer, create and manage the threads", "No threads are ever created", "Threads are created by hardware only", "Each user writes their own scheduler"], 0,
     PYQ + "Examples: thread pools, fork-join, OpenMP, Grand Central Dispatch, Intel TBB."),
    ("A thread pool improves performance because:",
     ["An existing idle thread serves a request faster than creating a new thread, and the number of threads is limited", "It creates a new thread for every request", "It removes the need for a CPU", "It uses only one thread"], 0,
     PYQ + "Java offers thread pools through ExecutorService."),
    ("OpenMP supports parallel programming in C, C++ and Fortran mainly through:",
     ["Compiler directives such as #pragma omp parallel", "Separate processes created with fork()", "Message passing between computers", "Hardware interrupts"], 0,
     "The run-time creates as many threads as there are cores."),
    ("In the fork-join model:",
     ["A parent task forks child tasks that run in parallel and then joins (waits for and combines) their results", "Processes are never created", "Only one thread ever runs", "Threads communicate only by files"], 0,
     "Java's ForkJoinPool implements this model for recursive divide-and-conquer tasks."),
    ("Grand Central Dispatch, which schedules blocks of work on dispatch queues, was developed by:",
     ["Apple, for macOS and iOS", "Microsoft, for Windows", "Oracle, for Java", "IBM, for mainframes"], 0,
     "Serial queues run blocks in order; concurrent queues run them in parallel."),
    ("If one thread of a multithreaded program calls fork(), and exec() is called immediately after, the better choice is:",
     ["Duplicate only the calling thread", "Duplicate all threads", "Duplicate no threads and abort", "Duplicate all threads twice"], 0,
     PYQ + "exec() replaces the whole process image, so duplicating every thread would be wasted work."),
    ("In a multithreaded program, a signal may be delivered to:",
     ["The thread to which it applies, every thread, certain threads, or a thread designated to receive all signals", "Only the main thread always", "No thread", "Only the kernel"], 0,
     "Synchronous signals go to the thread that caused them."),
    ("Terminating a thread before it has completed is called:",
     ["Thread cancellation", "Thread pooling", "Context switching", "Spooling"], 0,
     PYQ + "The thread to be cancelled is the target thread."),
    ("In asynchronous cancellation:",
     ["One thread immediately terminates the target thread", "The target thread checks periodically whether it should terminate", "Cancellation is impossible", "All threads stop together"], 0,
     PYQ + "In deferred cancellation the target checks at safe cancellation points."),
    ("The default cancellation type in Pthreads is:",
     ["Deferred", "Asynchronous", "Immediate", "Disabled forever"], 0,
     "A thread can create a cancellation point by calling pthread_testcancel()."),
    ("Data that each thread keeps its own copy of, such as a per-thread transaction ID, is called:",
     ["Thread-local storage (TLS)", "Shared memory", "Global data", "Heap storage"], 0,
     "TLS values persist across function calls, unlike local variables."),
    ("In many-to-many and two-level models, the intermediate data structure that appears to the user-thread library as a virtual processor is the:",
     ["Lightweight process (LWP)", "Page frame", "Inode", "Semaphore"], 0,
     PYQ + "With scheduler activations, the kernel informs the library about events through upcalls."),
    ("Linux creates both processes and threads with the system call:",
     ["clone(), whose flags decide how much the child shares with the parent", "CreateThread()", "spawn()", "pthread_join()"], 0,
     PYQ + "Linux calls both 'tasks'."),
    ("Windows keeps the data of each thread in the structures:",
     ["ETHREAD, KTHREAD and TEB", "PCB, FAT and MBR", "inode, superblock and dentry", "TLB, MMU and DMA"], 0,
     "TEB (thread environment block) lives in user space."),
    ("The number of threads in a thread pool is usually chosen based on:",
     ["The number of CPUs, the amount of memory and the expected number of concurrent requests", "The size of the monitor", "The keyboard layout", "The user's age"], 0,
     "Some pools adjust their size dynamically."),
    ("Two threads increment a shared counter without a lock. The result may be wrong because of:",
     ["A race condition", "Thread-local storage", "Deferred cancellation", "Thread pooling"], 0,
     "Shared data must be protected with a mutex or other synchronization."),
    ("Match the Pthreads function with its job:\na. pthread_create()  b. pthread_join()  c. pthread_exit()  d. pthread_cancel()\n1. Requests termination of a target thread  2. Terminates the calling thread  3. Waits for a thread to finish  4. Creates a new thread",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     PYQ + "API matching is common in KEA papers."),
    ("Match the implicit-threading technique with its description:\na. Thread pool  b. OpenMP  c. Fork-join  d. Grand Central Dispatch\n1. Apple's dispatch queues  2. Parent forks subtasks and later joins their results  3. Compiler directives that mark parallel regions  4. Threads created at start-up that wait for work",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0,
     "Implicit-threading approaches."),
    ("Consider the statements:\nI. Deferred cancellation lets a thread terminate at a safe point.\nII. Asynchronous cancellation is always safe for shared data.\nWhich is/are correct?",
     I_II, 0, "Asynchronous cancellation may leave resources or shared data in an inconsistent state."),
    ("Assertion (A): Thread pools usually serve requests faster than creating a new thread for each request.\nReason (R): An existing thread is reused instead of being created and destroyed.",
     AR, 0, "Creation and destruction costs are avoided."),
    ("Assertion (A): Calling run() directly on a Java Thread object starts a new thread.\nReason (R): The start() method creates a new thread, which then calls run().",
     AR, 3, "Calling run() directly runs it in the current thread, so A is false."),
    ("Intel Threading Building Blocks (TBB) is:",
     ["A C++ template library for designing parallel applications", "A Windows system call", "A hardware cache", "A database engine"], 0,
     "It is another example of implicit threading."),
]

TOPICS = {
    "Threads": [("1 · Thread Concepts, Multicore Programming and Multithreading Models", CONCEPTS),
                ("2 · Thread Libraries, Implicit Threading and Threading Issues", LIBRARIES_ISSUES)],
}
