"""Paper 2 · Unit 8 · Linear Data Structures (4 sub-topics × 30).
References: Horowitz, Sahni & Anderson-Freed, Fundamentals of Data Structures in C; Tanenbaum, Data Structures using C;
Cormen et al., Introduction to Algorithms (heaps). Indices are 0-based unless stated."""
from packlib import AR, I_II

ARRAYS = [
    ("Accessing the i-th element of an array takes constant time because:",
     ["Elements are stored contiguously, so the address is computed directly from the index", "Arrays are always sorted", "Arrays are stored as linked lists", "The array is searched from the start"], 0, "Address = base + i × element size."),
    ("An array A[5..50] of 4-byte elements starts at address 1000. The address of A[20] is:",
     ["1060", "1080", "1020", "1076"], 0, "1000 + 4 × (20 − 5) = 1060."),
    ("How many elements does the array A[−5..20] have?",
     ["26", "25", "20", "15"], 0, "20 − (−5) + 1 = 26."),
    ("A[1..10][1..15] is stored in row-major order from address 500 with 2 bytes per element. The address of A[4][6] is:",
     ["600", "606", "598", "560"], 0, "500 + 2 × ((4 − 1) × 15 + (6 − 1)) = 500 + 2 × 50."),
    ("The same array A[1..10][1..15] (base 500, 2 bytes per element) stored in column-major order puts A[4][6] at address:",
     ["606", "600", "610", "596"], 0, "500 + 2 × ((6 − 1) × 10 + (4 − 1)) = 500 + 2 × 53."),
    ("How many elements does the 3-D array int A[2][3][4] have?",
     ["24", "9", "12", "10"], 0, "2 × 3 × 4."),
    ("Inserting a new element at the beginning of an array holding n elements requires, in the worst case:",
     ["Shifting all n elements – O(n)", "O(1) time", "O(log n) time", "O(n²) time"], 0, "Every element moves one place to the right."),
    ("Binary search on an array requires that the array be:",
     ["Sorted, and it then takes O(log n) comparisons", "Unsorted", "Stored as a linked list", "Of even length"], 0, "Linear search works on any array but takes O(n)."),
    ("A sparse matrix is a matrix in which:",
     ["Most of the elements are zero", "All elements are equal", "The number of rows equals the number of columns", "No element is zero"], 0, "Storing only the non-zero elements saves memory."),
    ("A 100 × 100 sparse matrix has 50 non-zero elements. In the triplet (row, column, value) form with one header row, how many values are stored?",
     ["153", "10,000", "150", "300"], 0, "(50 + 1) rows × 3 columns = 153, instead of 10,000."),
    ("The 'fast transpose' algorithm for a sparse matrix in triplet form runs in time proportional to:",
     ["columns + number of non-zero terms", "columns × number of terms", "rows × columns", "terms²"], 0, "It first counts the terms in each column and computes their starting positions."),
    ("A lower triangular n × n matrix has how many elements on or below the main diagonal?",
     ["n(n + 1)/2", "n²", "n(n − 1)/2", "2n − 1"], 0, "For n = 10 this is 55."),
    ("A 10 × 10 lower triangular matrix is stored row by row, keeping only elements on or below the diagonal (1-based indices). How many elements come before A[5][3]?",
     ["12", "10", "13", "22"], 0, "Rows 1–4 contribute 1 + 2 + 3 + 4 = 10, plus 2 elements before A[5][3] in row 5."),
    ("A tridiagonal n × n matrix has at most how many non-zero elements?",
     ["3n − 2", "3n", "n²/3", "2n − 1"], 0, "The main diagonal (n) plus the diagonals above and below it (n − 1 each); for n = 10, 28."),
    ("The polynomial 3x⁵ + 2x² + 7 is stored in an array indexed by exponent. The array needs at least:",
     ["6 elements (exponents 0 to 5)", "3 elements", "5 elements", "7 elements"], 0, "This form wastes space for sparse polynomials, where a list of (coefficient, exponent) pairs is better."),
    ("A dynamic array that doubles its capacity when it is full gives an append operation that costs:",
     ["O(1) amortised", "O(n) every time", "O(log n) every time", "O(n²) amortised"], 0, "Occasional O(n) copies are spread over many cheap appends."),
    ("Match the array operation with its time complexity (n elements):\na. Access by index  b. Linear search  c. Binary search on sorted data  d. Insert at the front\n1. O(n) because of shifting  2. O(log n)  3. O(n)  4. O(1)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Arrays trade fast access for slow insertion and deletion."),
    ("Which of the following is a typical application of arrays?",
     ["Representing matrices, polynomials and lookup tables", "Implementing recursion only", "Undo operations only", "Storing hierarchical data only"], 0, "Arrays also implement stacks, queues and heaps."),
    ("Deleting the element at index k from an array of n elements (keeping the order) needs how many shifts?",
     ["n − k − 1", "k", "n", "1"], 0, "Every element after position k moves one place left."),
    ("Consider the statements:\nI. Arrays allow random access to elements.\nII. The size of a static array can grow automatically at run time.\nWhich is/are correct?",
     I_II, 0, "A static array's size is fixed when it is created."),
    ("Consider the statements:\nI. Row-major order stores all elements of a row together.\nII. C stores two-dimensional arrays in column-major order.\nWhich is/are correct?",
     I_II, 0, "C uses row-major order; FORTRAN uses column-major order."),
    ("Consider the statements:\nI. The triplet representation saves space only when the matrix is sparse.\nII. Matrix addition in triplet form can be done by merging the two triplet lists.\nWhich is/are correct?",
     I_II, 2, "Merging by (row, column) order adds matching terms."),
    ("Assertion (A): Access to any array element takes O(1) time.\nReason (R): The address of an element is computed directly from the base address and the index.",
     AR, 0, "No searching is needed."),
    ("Assertion (A): Inserting into the middle of an array is as fast as appending at the end.\nReason (R): Inserting in the middle requires shifting the later elements.",
     AR, 3, "Shifting makes middle insertion O(n) while appending is O(1); R shows why A is false."),
    ("Assertion (A): Storing a sparse matrix in triplet form saves memory.\nReason (R): The triplet form stores every zero element as well.",
     AR, 2, "A is true; R is false – only non-zero elements are stored."),
    ("Assertion (A): Binary search needs a sorted array.\nReason (R): Arrays are stored in contiguous memory.",
     AR, 1, "Both true; binary search needs sorting to discard half the range, which contiguity does not explain."),
    ("For  int A[3][4]  in C (row-major, 4-byte int) starting at address 2000, the address of A[2][1] is:",
     ["2036", "2024", "2028", "2044"], 0, "2000 + 4 × (2 × 4 + 1) = 2036."),
    ("An upper triangular 5 × 5 matrix stored compactly needs how many memory locations?",
     ["15", "25", "10", "20"], 0, "5 × 6 / 2 = 15."),
    ("A symmetric n × n matrix can be stored using how many elements?",
     ["n(n + 1)/2, storing only one triangle", "n²", "2n", "n"], 0, "A[i][j] = A[j][i], so one triangle is enough."),
    ("In C, the name of a 1-D array used in an expression represents:",
     ["The address of its first element", "The number of elements", "The last element", "The sum of its elements"], 0, "Hence A[i] ≡ *(A + i)."),
]

STACKS = [
    ("A stack follows the principle:",
     ["Last In, First Out (LIFO)", "First In, First Out (FIFO)", "Highest priority first", "Random access"], 0, "Insertion (push) and deletion (pop) happen at the same end, the top."),
    ("Starting with an empty stack, the operations push 1, push 2, push 3, pop, push 4, pop, pop remove the elements in the order:",
     ["3, 4, 2", "1, 2, 3", "3, 2, 4", "4, 3, 2"], 0, "After popping 3, 4 is pushed on top of 2, so 4 and then 2 come out."),
    ("Elements 1, 2, 3, 4 are pushed in this order, with pops allowed at any time. Which output sequence is IMPOSSIBLE?",
     ["4, 1, 3, 2", "3, 2, 4, 1", "1, 2, 3, 4", "2, 1, 4, 3"], 0, "Popping 4 first leaves 3 on top, so 1 cannot come next."),
    ("How many different output sequences can be produced by passing 1, 2, 3 through a stack?",
     ["5", "6", "4", "3"], 0, "The count is the Catalan number C₃ = 5; only 3, 1, 2 is impossible."),
    ("With n = 4 elements pushed in order through a stack, the number of possible output permutations is:",
     ["14", "24", "16", "10"], 0, "Catalan number C₄ = 14."),
    ("The postfix form of  A + B * C − D  is:",
     ["A B C * + D −", "A B + C * D −", "A B C D * + −", "+ A * B C − D"], 0, "B * C is formed first, then added to A, then D is subtracted."),
    ("The postfix form of  (A + B) * (C − D)  is:",
     ["A B + C D − *", "A B C D + − *", "A + B C − D *", "* + A B − C D"], 0, "The prefix form would be * + A B − C D."),
    ("The value of the postfix expression  6 2 3 + − 3 8 2 / + *  is:",
     ["7", "1", "49", "5"], 0, "2 + 3 = 5; 6 − 5 = 1; 8 / 2 = 4; 3 + 4 = 7; 1 × 7 = 7."),
    ("The value of the prefix expression  − * 2 3 4  is:",
     ["2", "−2", "14", "10"], 0, "(2 × 3) − 4 = 2."),
    ("The prefix form of  A * B + C  is:",
     ["+ * A B C", "* A + B C", "A B * C +", "+ A * B C"], 0, "The last operator applied, +, comes first."),
    ("While evaluating the postfix expression  2 3 4 * +  with a stack, the maximum number of elements on the stack at one time is:",
     ["3", "2", "4", "5"], 0, "2, 3 and 4 are all on the stack before * is applied."),
    ("Which string of brackets is balanced?",
     ["{[()]}", "([)]", "((]", "{[}]"], 0, "Each closing bracket must match the most recent unmatched opening bracket – checked with a stack."),
    ("In an array implementation of a stack of size MAX (0-based), with top = −1 meaning empty, the stack is full when:",
     ["top == MAX − 1", "top == MAX", "top == 0", "top == −1"], 0, "Pushing when full causes overflow; popping when empty causes underflow."),
    ("Two stacks share one array of size n by growing from opposite ends. Overflow occurs only when:",
     ["The total number of elements in both stacks reaches n", "Either stack holds n/2 elements", "One stack becomes empty", "Both stacks hold the same number of elements"], 0, "This uses the space more flexibly than a fixed half each."),
    ("Pushing onto a stack implemented as a singly linked list, with the top at the head, takes:",
     ["O(1) time", "O(n) time", "O(log n) time", "O(n²) time"], 0, "The new node simply becomes the new head."),
    ("The Tower of Hanoi with 5 discs needs a minimum of how many moves?",
     ["31", "32", "25", "15"], 0, "2ⁿ − 1 = 31; the recursive solution uses the call stack."),
    ("Which of the following does NOT typically use a stack?",
     ["Breadth-first search of a graph", "Function calls and recursion", "Undo in a text editor", "Evaluating postfix expressions"], 0, "BFS uses a queue; depth-first search uses a stack."),
    ("Match the application with the data structure it mainly uses:\na. Function-call management  b. Printer job scheduling  c. Depth-first search  d. Browser Back button history\n1. Stack of visited pages  2. Stack (explicit or recursion)  3. Queue  4. Call stack",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "LIFO suits anything that must be undone in reverse order."),
    ("During infix-to-postfix conversion, an operator on the stack is popped to the output when the incoming operator has:",
     ["Lower or equal precedence (for left-associative operators)", "Higher precedence", "No precedence", "The same symbol only"], 0, "Right-associative ^ is handled differently."),
    ("A stack can be simulated using:",
     ["Two queues", "Only one variable", "A hash table only", "A binary search tree only"], 0, "Similarly, a queue can be built from two stacks."),
    ("What does the stack contain (bottom → top) after: push 5, push 7, pop, push 2, push 9, pop?",
     ["5, 2", "5, 7, 2", "5, 9", "2, 9"], 0, "7 and 9 are removed."),
    ("Consider the statements:\nI. Recursion is implemented with a stack of activation records.\nII. Every recursive program can be converted into an iterative one using an explicit stack.\nWhich is/are correct?",
     I_II, 2, "Both are standard results."),
    ("Consider the statements:\nI. Popping from an empty stack causes underflow.\nII. Pushing onto an empty stack causes overflow.\nWhich is/are correct?",
     I_II, 0, "Overflow happens when pushing onto a full stack."),
    ("Assertion (A): A stack is used to check balanced parentheses.\nReason (R): The most recently opened bracket must be the first one to be closed.",
     AR, 0, "That LIFO property matches the stack exactly."),
    ("Assertion (A): Postfix expressions need parentheses to show the order of operations.\nReason (R): In postfix notation the order of operators alone fixes the order of evaluation.",
     AR, 3, "Because the order is already fixed, postfix needs no parentheses; R shows why A is false."),
    ("Assertion (A): Push and pop on an array-based stack take O(1) time.\nReason (R): Elements of a stack are always kept in sorted order.",
     AR, 2, "A is true; R is false – stacks keep insertion order, not sorted order."),
    ("Assertion (A): Depth-first search can be implemented with a stack.\nReason (R): A stack can be implemented with a linked list.",
     AR, 1, "Both true, but the implementation detail does not explain why DFS uses a stack."),
    ("The infix form of the postfix expression  a b c * + d −  is:",
     ["a + b * c − d", "(a + b) * c − d", "a + b * (c − d)", "a * b + c − d"], 0, "b c * becomes b * c, then a + (b * c), then − d."),
    ("The value of the postfix expression  5 1 2 + 4 * + 3 −  is:",
     ["14", "18", "12", "20"], 0, "1 + 2 = 3; 3 × 4 = 12; 5 + 12 = 17; 17 − 3 = 14."),
    ("The peek (top) operation on a stack:",
     ["Returns the top element without removing it", "Removes the bottom element", "Removes the top element", "Returns the number of elements"], 0, "pop both returns and removes it."),
]

QUEUES = [
    ("A queue follows the principle:",
     ["First In, First Out (FIFO)", "Last In, First Out (LIFO)", "Highest priority first", "Random removal"], 0, "Elements are added at the rear and removed from the front."),
    ("Enqueue 1, enqueue 2, enqueue 3, dequeue, enqueue 4, dequeue. Which element is now at the front?",
     ["3", "1", "2", "4"], 0, "1 and 2 have been removed; 3 then 4 remain."),
    ("The main drawback of a simple (linear) array queue is that:",
     ["Space freed at the front cannot be reused once rear reaches the end", "It cannot store integers", "Dequeue takes O(n) always", "It must be sorted"], 0, "A circular queue wraps the indices around to reuse the space."),
    ("In a circular queue of size n that keeps one slot empty, the queue is full when:",
     ["(rear + 1) % n == front", "rear == front", "rear == n − 1", "front == 0"], 0, "So such a queue can hold at most n − 1 elements; rear == front means empty."),
    ("A circular queue has 5 slots (indices 0–4). front points to the first element and rear points to the slot after the last element. If front = 3 and rear = 1, how many elements are in the queue?",
     ["3", "2", "4", "5"], 0, "(rear − front + n) % n = (1 − 3 + 5) % 5 = 3 (slots 3, 4 and 0)."),
    ("A double-ended queue (deque) allows:",
     ["Insertion and deletion at both ends", "Insertion only at the front", "Deletion only in the middle", "Only priority-based removal"], 0, "An input-restricted deque allows insertion at one end only; an output-restricted deque allows deletion at one end only."),
    ("In a priority queue, the element removed first is:",
     ["The one with the highest priority", "The one inserted first", "The one inserted last", "A random one"], 0, "Equal priorities are often served in arrival order."),
    ("With a binary heap, the priority-queue operations insert and delete-max take:",
     ["O(log n) each, while find-max takes O(1)", "O(1) each", "O(n) each", "O(n log n) each"], 0, "The heap's height is ⌊log₂ n⌋."),
    ("A priority queue kept as an UNSORTED array has insert and delete-max costs of:",
     ["O(1) and O(n)", "O(n) and O(1)", "O(log n) and O(log n)", "O(1) and O(1)"], 0, "A sorted array reverses this: O(n) insert and O(1) delete."),
    ("In an array-based binary heap with 0-based indices, the children of the node at index i are at:",
     ["2i + 1 and 2i + 2", "2i and 2i + 1", "i + 1 and i + 2", "i/2 and i/2 + 1"], 0, "The parent of i is at ⌊(i − 1)/2⌋."),
    ("45 is inserted into the max-heap stored as [50, 30, 40, 10, 20]. The resulting array is:",
     ["[50, 30, 45, 10, 20, 40]", "[50, 45, 40, 10, 20, 30]", "[45, 50, 40, 10, 20, 30]", "[50, 30, 40, 10, 20, 45]"], 0, "45 is placed at index 5; its parent (index 2) is 40, so they swap; its new parent 50 is larger, so it stops."),
    ("The maximum is deleted from the max-heap [50, 30, 45, 10, 20, 40]. The resulting array is:",
     ["[45, 30, 40, 10, 20]", "[40, 30, 45, 10, 20]", "[45, 40, 30, 10, 20]", "[30, 45, 40, 10, 20]"], 0, "The last element 40 moves to the root and sifts down past its larger child 45."),
    ("Building a binary heap from n unsorted elements with the bottom-up (heapify) method takes:",
     ["O(n) time", "O(n log n) time always", "O(log n) time", "O(n²) time"], 0, "Most nodes are near the bottom and need little work."),
    ("Round-robin CPU scheduling is naturally implemented with a:",
     ["Circular queue", "Stack", "Binary search tree", "Hash table"], 0, "Each process gets a time slice and then goes to the back of the queue."),
    ("Which algorithm uses a priority queue?",
     ["Dijkstra's shortest-path algorithm", "Depth-first search", "Linear search", "Bubble sort"], 0, "Huffman coding and Prim's algorithm also use priority queues."),
    ("Breadth-first search of a graph uses a:",
     ["Queue", "Stack", "Priority queue only", "Deque only"], 0, "Vertices are visited level by level."),
    ("A queue implemented as a linked list with front and rear pointers supports enqueue and dequeue in:",
     ["O(1) time each", "O(n) time each", "O(log n) time each", "O(1) enqueue and O(n) dequeue always"], 0, "New nodes are added after rear; nodes are removed at front."),
    ("A queue can be implemented with two stacks so that each operation takes:",
     ["O(1) amortised time", "O(n²) time", "O(log n) time", "O(n) time for every operation"], 0, "Elements are moved from the input stack to the output stack only when the output stack is empty."),
    ("Match the structure with its typical use:\na. Queue  b. Priority queue  c. Deque  d. Circular queue\n1. Buffer that reuses space in a fixed-size array  2. Sliding-window algorithms needing both ends  3. Event simulation by earliest time  4. Printer spooling in arrival order",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "All are variations of the queue idea."),
    ("A circular queue has 8 slots, front = 6 and rear = 2 (rear points after the last element). How many free slots remain if one slot is always kept empty?",
     ["3", "4", "5", "2"], 0, "Elements = (2 − 6 + 8) % 8 = 4; usable capacity 7; free = 7 − 4 = 3."),
    ("Consider the statements:\nI. In a circular queue, front == rear usually indicates an empty queue.\nII. A circular queue avoids the wasted space of a simple array queue.\nWhich is/are correct?",
     I_II, 2, "Both are correct under the one-empty-slot convention."),
    ("Consider the statements:\nI. A max-heap stores the largest element at the root.\nII. In a max-heap every level is sorted from left to right.\nWhich is/are correct?",
     I_II, 0, "Only the parent–child order is guaranteed, not the order among siblings."),
    ("Assertion (A): A priority queue is usually implemented with a binary heap.\nReason (R): A heap supports insert and delete-max in O(log n) time.",
     AR, 0, "That balance of costs is why heaps are used."),
    ("Assertion (A): A queue removes the most recently inserted element first.\nReason (R): A queue follows the FIFO principle.",
     AR, 3, "FIFO removes the oldest element, so A is false; R explains why."),
    ("Assertion (A): Breadth-first search visits vertices level by level.\nReason (R): Breadth-first search uses a stack.",
     AR, 2, "A is true; R is false – BFS uses a queue."),
    ("Assertion (A): A deque can be used as either a stack or a queue.\nReason (R): Circular queues are used in round-robin scheduling.",
     AR, 1, "Both true but unrelated."),
    ("In an array-based max-heap (0-based), the parent of the element at index 9 is at index:",
     ["4", "5", "3", "8"], 0, "⌊(9 − 1)/2⌋ = 4."),
    ("The maximum number of nodes in a binary heap of height 3 (a single root has height 0) is:",
     ["15", "8", "7", "16"], 0, "2^(h + 1) − 1 = 15."),
    ("Heap sort sorts n elements in:",
     ["O(n log n) time in every case", "O(n²) in the worst case", "O(n) always", "O(log n)"], 0, "It builds a heap and repeatedly removes the maximum."),
    ("An output-restricted deque allows:",
     ["Insertion at both ends but deletion at one end only", "Deletion at both ends but insertion at one end only", "No deletions", "Insertion only in the middle"], 0, "An input-restricted deque is the reverse."),
]

LINKED_LISTS = [
    ("Each node of a singly linked list contains:",
     ["Data and a pointer to the next node", "Only data", "Pointers to the previous and next nodes", "An index into an array"], 0, "The last node's next pointer is NULL."),
    ("Accessing the k-th element of a singly linked list takes:",
     ["O(k) time, because the list must be traversed from the head", "O(1) time", "O(log k) time", "O(k²) time"], 0, "Linked lists have no random access."),
    ("Inserting a node at the END of a singly linked list with only a head pointer takes ______; with a tail pointer it takes ______.",
     ["O(n); O(1)", "O(1); O(n)", "O(log n); O(1)", "O(n); O(n)"], 0, "The tail pointer avoids walking the whole list."),
    ("Given only a pointer to a node (not the last one) of a singly linked list, that node can be deleted in O(1) by:",
     ["Copying the next node's data into it and deleting the next node", "Walking from the head to find its predecessor", "Setting the pointer to NULL", "It cannot be done"], 0, "This trick fails for the last node."),
    ("The main advantage of a doubly linked list over a singly linked list is that:",
     ["It can be traversed in both directions, and a given node can be deleted in O(1)", "It uses less memory", "It allows random access", "It never needs pointers"], 0, "The cost is one extra pointer per node."),
    ("Inserting a new node between two existing nodes of a doubly linked list requires setting how many pointer fields?",
     ["4", "2", "3", "6"], 0, "The new node's prev and next, the left neighbour's next and the right neighbour's prev."),
    ("In a circular singly linked list:",
     ["The last node points back to the first node", "There is no last node", "Every node points to itself", "The first node points to NULL"], 0, "Keeping a pointer to the last node gives O(1) access to both ends."),
    ("Reversing a singly linked list of n nodes iteratively takes:",
     ["O(n) time and O(1) extra space", "O(n²) time", "O(n) extra space always", "O(log n) time"], 0, "Three pointers (previous, current, next) are enough."),
    ("Floyd's 'tortoise and hare' method is used to:",
     ["Detect a cycle in a linked list", "Sort a linked list", "Reverse a linked list", "Search a sorted array"], 0, "A slow and a fast pointer meet if and only if there is a cycle."),
    ("The middle node of a singly linked list can be found in one pass by:",
     ["Moving one pointer one step and another two steps at a time", "Counting nodes twice", "Using binary search", "Sorting the list"], 0, "When the fast pointer reaches the end, the slow pointer is in the middle."),
    ("For the list 1 → 2 → 3 → 4 → 5, a loop that prints the current node and then skips the next one (p = p->next->next, checking for NULL) prints:",
     ["1 3 5", "2 4", "1 2 3 4 5", "5 3 1"], 0, "It visits every alternate node from the head."),
    ("What does this print for the list 1 → 2 → 3?\nvoid f(struct node *p) { if (p == NULL) return; f(p->next); printf(\"%d \", p->data); }",
     ["3 2 1", "1 2 3", "1 3", "3"], 0, "The recursive call comes before printf, so the list is printed in reverse."),
    ("Merging two sorted linked lists of lengths m and n into one sorted list takes:",
     ["O(m + n) time", "O(m × n) time", "O(log(m + n)) time", "O((m + n)²) time"], 0, "Nodes are relinked; no new nodes are needed."),
    ("Compared with arrays, linked lists:",
     ["Allow easy insertion and deletion but use extra memory for pointers and have poor cache locality", "Allow O(1) random access", "Always use less memory", "Need their size fixed in advance"], 0, "Arrays are better for indexed access."),
    ("After  p = head; while (p->next != NULL) p = p->next;  on a non-empty list, p points to:",
     ["The last node", "The first node", "NULL", "The second-last node"], 0, "The loop stops when p has no successor."),
    ("A header (sentinel) node in a linked list is used to:",
     ["Simplify insertion and deletion by removing special cases for an empty list or the first node", "Store the largest element", "Make the list circular", "Speed up searching to O(1)"], 0, "It holds no real data (sometimes a count)."),
    ("Polynomials such as 5x⁸ + 3x² + 1 are well represented by a linked list because:",
     ["Only non-zero terms are stored, each as a (coefficient, exponent) node", "Linked lists are faster than arrays for everything", "Polynomials must be sorted by coefficient", "Arrays cannot store integers"], 0, "Addition walks both lists in exponent order."),
    ("Given a pointer to the LAST node of a circular singly linked list, deleting the first node takes:",
     ["O(1) time", "O(n) time", "O(log n) time", "O(n²) time"], 0, "The first node is last->next, so it can be unlinked directly."),
    ("A structure such as  struct node { int data; struct node *next; };  is called:",
     ["A self-referential structure", "A union", "An array of structures", "A bit field"], 0, "It contains a pointer to its own type."),
    ("Match the list operation with its cost (singly linked list, head pointer only, n nodes):\na. Insert at the head  b. Search for a value  c. Delete the last node  d. Read the head's data\n1. O(1)  2. O(n) – the predecessor must be found  3. O(n)  4. O(1) – a new node becomes the head",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Only operations near the head are constant time."),
    ("Consider the statements:\nI. Binary search is efficient on a singly linked list.\nII. Linked lists allocate memory dynamically as nodes are added.\nWhich is/are correct?",
     I_II, 1, "Binary search needs random access, which linked lists lack."),
    ("Consider the statements:\nI. In a doubly linked list, a node can be deleted in O(1) if a pointer to it is given.\nII. A circular list can be traversed starting from any node.\nWhich is/are correct?",
     I_II, 2, "Both statements are correct."),
    ("Assertion (A): Inserting at the head of a linked list takes O(1) time.\nReason (R): Only the new node's next pointer and the head pointer change.",
     AR, 0, "No other node is touched."),
    ("Assertion (A): Linked lists allow random access to any element in O(1).\nReason (R): Nodes of a linked list are reached by following pointers from the head.",
     AR, 3, "Following pointers makes access O(n); R shows why A is false."),
    ("Assertion (A): Doubly linked lists use more memory per node than singly linked lists.\nReason (R): Doubly linked lists cannot be traversed backwards.",
     AR, 2, "A is true (an extra prev pointer); R is false."),
    ("Assertion (A): Circular linked lists are useful for round-robin scheduling.\nReason (R): A singly linked list node contains data and a next pointer.",
     AR, 1, "Both true, but R does not explain A; the circular link does."),
    ("The number of NULL pointers in a doubly linked list of n ≥ 1 nodes (not circular) is:",
     ["2", "1", "n", "n + 1"], 0, "The first node's prev and the last node's next."),
    ("To delete the node after node p in a singly linked list, one writes:",
     ["q = p->next; p->next = q->next; free(q);", "p = p->next; free(p);", "free(p->next); p->next = p;", "p->next = NULL;"], 0, "The node is unlinked before it is freed."),
    ("An orthogonal (cross) linked list is commonly used to represent:",
     ["A sparse matrix, linking the non-zero elements by row and by column", "A stack", "A queue of print jobs", "A string"], 0, "Each node belongs to one row list and one column list."),
    ("The time to concatenate two circular singly linked lists, given pointers to their last nodes, is:",
     ["O(1)", "O(n)", "O(m + n)", "O(log n)"], 0, "Only a few pointers need to be exchanged."),
]

TOPICS = {
    "Linear Data Structures": [("1 · Arrays and Sparse Matrices", ARRAYS),
                               ("2 · Stacks and Their Applications", STACKS),
                               ("3 · Queues and Priority Queues", QUEUES),
                               ("4 · Linked Lists", LINKED_LISTS)],
}
