"""Paper 2 · Unit 8 · Sets & Graph Representation; Sorting and Searching (5 sub-topics × 30).
References: Horowitz, Sahni & Anderson-Freed; Cormen et al., Introduction to Algorithms; Knuth vol. 3; Rosen (graphs)."""
from packlib import AR, I_II

SETS = [
    ("In the bit-vector representation of sets over a universe of n elements, the union of two sets is computed with:",
     ["A bitwise OR of the two bit vectors", "A bitwise AND", "A bitwise XOR", "Sorting both sets"], 0, "Intersection is a bitwise AND and difference is A AND NOT B."),
    ("Membership testing in a bit-vector set takes:",
     ["O(1) time", "O(n) time", "O(log n) time", "O(n²) time"], 0, "Just check the bit at the element's position."),
    ("A set of elements drawn from the universe {1, …, 1000} is stored as a bit vector. How much memory does it need, whatever the set's size?",
     ["125 bytes (1000 bits)", "1000 bytes", "8 bytes", "It depends only on the number of elements"], 0, "One bit per possible element: 1000 / 8 = 125 bytes."),
    ("If a set is kept as an unsorted linked list, testing membership takes:",
     ["O(n) time", "O(1) time", "O(log n) time", "O(n log n) time"], 0, "The whole list may have to be scanned."),
    ("If two sets are stored as sorted arrays of sizes m and n, their union can be computed in:",
     ["O(m + n) time by merging", "O(m × n) time only", "O(1) time", "O(log m + log n) time"], 0, "Walk both arrays once, as in the merge step of merge sort."),
    ("The disjoint-set (union–find) data structure supports which main operations?",
     ["MAKE-SET, FIND and UNION", "PUSH and POP", "ENQUEUE and DEQUEUE", "INSERT and DELETE-MIN"], 0, "It keeps a collection of non-overlapping sets."),
    ("In the forest representation of disjoint sets, FIND(x) returns:",
     ["The root (representative) of the tree that contains x", "The number of elements in the set", "The smallest element", "The parent of x"], 0, "Two elements are in the same set exactly when they have the same representative."),
    ("With both union by rank and path compression, a sequence of m operations on n elements takes:",
     ["O(m α(n)) time, where α is the very slowly growing inverse Ackermann function", "O(m n) time", "O(m log m) time always", "O(n²) time"], 0, "α(n) ≤ 4 for any practical n, so the operations are almost constant time."),
    ("Without union by rank or path compression, a disjoint-set tree can reach height:",
     ["n − 1", "log₂ n", "1", "√n"], 0, "Repeatedly attaching a larger tree under a single node builds a chain."),
    ("Path compression in FIND means:",
     ["Making every node on the search path point directly to the root", "Deleting the path", "Compressing the elements into bits", "Merging two roots"], 0, "It flattens the tree and speeds up later FINDs."),
    ("Union by rank (or by size) means that:",
     ["The root of the shorter (smaller) tree is attached under the root of the taller (larger) tree", "The larger tree is attached under the smaller", "Roots are attached randomly", "All nodes are moved to one array"], 0, "With union by rank alone, the tree height stays O(log n)."),
    ("Starting from singletons {1}, {2}, …, {6}, the operations UNION(1, 2), UNION(3, 4), UNION(2, 4) are done. How many sets remain?",
     ["3", "4", "2", "5"], 0, "{1, 2, 3, 4}, {5} and {6}."),
    ("Which algorithm uses the disjoint-set data structure to detect whether an edge would form a cycle?",
     ["Kruskal's minimum spanning tree algorithm", "Dijkstra's algorithm", "Binary search", "Heap sort"], 0, "An edge is rejected when both ends already have the same representative."),
    ("For which set operation is the bit-vector representation especially efficient?",
     ["Union, intersection and difference of sets over a small universe", "Sets over a huge or unbounded universe", "Sets of strings of unknown length", "Sets that must be listed in insertion order"], 0, "Each operation processes a machine word of elements at once."),
    ("The universe is {0, 1, …, 7}. The set {1, 3, 6} as an 8-bit vector (bit i for element i, bit 0 on the right) is:",
     ["01001010", "01010010", "10010100", "00001011"], 0, "Bits 6, 3 and 1 are set: 0100 1010."),
    ("Using a hash table to store a set gives membership tests in:",
     ["O(1) expected time", "O(log n) worst-case time always", "O(n log n) time", "O(n²) time"], 0, "The worst case can be O(n) if many keys collide."),
    ("Match the set representation with its membership cost:\na. Bit vector  b. Unsorted list  c. Sorted array  d. Balanced BST\n1. O(log n) by tree search  2. O(log n) by binary search  3. O(n)  4. O(1)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "The choice depends on the universe size and the operations needed."),
    ("Consider the statements:\nI. Disjoint-set structures can find the connected components of an undirected graph.\nII. Disjoint-set structures support deleting an element from a set efficiently.\nWhich is/are correct?",
     I_II, 0, "The standard structure supports MAKE-SET, UNION and FIND only; deletion is not a basic operation."),
    ("Consider the statements:\nI. The intersection of two bit-vector sets is a bitwise AND.\nII. A bit vector needs memory proportional to the size of the universe, not the size of the set.\nWhich is/are correct?",
     I_II, 2, "Both are correct; that is why bit vectors suit small universes."),
    ("Assertion (A): Path compression makes later FIND operations faster.\nReason (R): After compression, the nodes on the path point directly to the root.",
     AR, 0, "Shorter paths mean fewer steps next time."),
    ("Assertion (A): A bit-vector representation is ideal for sets over a very large universe with few elements.\nReason (R): A bit vector uses one bit for every element of the universe.",
     AR, 3, "Because it needs a bit for every possible element, it wastes memory for large sparse universes; A is false."),
    ("Assertion (A): Kruskal's algorithm uses a disjoint-set structure.\nReason (R): Disjoint-set structures support O(1) sorting of edges.",
     AR, 2, "A is true; R is false – the edges are sorted separately in O(e log e)."),
    ("Assertion (A): Union by rank keeps disjoint-set trees shallow.\nReason (R): Disjoint sets are used in Kruskal's algorithm.",
     AR, 1, "Both true, but the use in Kruskal's algorithm does not explain why union by rank keeps trees shallow."),
    ("The operation that combines two disjoint sets into one is:",
     ["UNION", "FIND", "MAKE-SET", "SPLIT"], 0, "It links the root of one tree under the root of the other."),
    ("In the array (parent-pointer) implementation of disjoint sets, a root is usually recognised by:",
     ["parent[i] == i (or a negative value storing the size or rank)", "parent[i] == 0 always", "Being the largest element", "Being stored at index 1"], 0, "Negative values can store the tree size for union by size."),
    ("A set of integers 0–63 is stored in a single 64-bit word. Testing whether 37 is in the set is done by:",
     ["Checking (word >> 37) & 1", "Scanning all 64 bits", "Sorting the bits", "Dividing the word by 37"], 0, "Shifting and masking checks one bit."),
    ("Which representation gives the most efficient set union when both sets are large and dense subsets of a small universe?",
     ["Bit vectors", "Unsorted linked lists", "Unbalanced BSTs", "Stacks"], 0, "One OR per machine word."),
    ("With union by size, the height of any tree containing k elements is at most:",
     ["⌊log₂ k⌋", "k − 1", "√k", "k/2"], 0, "A node's depth grows only when its tree at least doubles in size."),
    ("The inverse Ackermann function α(n) that appears in union–find analysis:",
     ["Grows so slowly that it is at most 4 for any realistic n", "Grows faster than n", "Equals log₂ n", "Is always exactly 1"], 0, "That makes union–find practically constant time per operation."),
    ("Which problem is a natural application of the union–find structure?",
     ["Checking whether two computers are in the same network after connections are added", "Finding the shortest path with weights", "Sorting names alphabetically", "Evaluating postfix expressions"], 0, "It answers 'are these connected?' as connections are added."),
]

GRAPH_REP = [
    ("An adjacency matrix of a graph with n vertices needs how much space?",
     ["O(n²)", "O(n + e)", "O(e)", "O(n)"], 0, "It has a cell for every pair of vertices."),
    ("An adjacency-list representation of a graph with n vertices and e edges needs:",
     ["O(n + e) space", "O(n²) space", "O(e²) space", "O(n e) space"], 0, "One list header per vertex plus one entry per edge (two per edge if undirected)."),
    ("Checking whether an edge (u, v) exists takes O(1) time with a(n):",
     ["Adjacency matrix", "Adjacency list", "Edge list", "Incidence list"], 0, "With an adjacency list it takes O(degree of u)."),
    ("The adjacency matrix of an undirected graph is always:",
     ["Symmetric", "Upper triangular", "The identity matrix", "Full of 1s"], 0, "An edge u–v appears at (u, v) and at (v, u)."),
    ("An undirected graph has 7 edges. The sum of the degrees of all its vertices is:",
     ["14", "7", "21", "28"], 0, "Handshaking lemma: the sum of degrees = 2e."),
    ("How many 1s are in the adjacency matrix of a simple undirected graph with 9 edges?",
     ["18", "9", "81", "36"], 0, "Each edge contributes two symmetric entries."),
    ("An undirected graph has 6 vertices and 7 edges. In its adjacency-list representation, the total number of list nodes is:",
     ["14", "7", "13", "42"], 0, "Each undirected edge appears in the lists of both its end vertices."),
    ("The maximum number of edges in a simple undirected graph with 10 vertices is:",
     ["45", "90", "100", "10"], 0, "n(n − 1)/2 = 10 × 9 / 2 = 45; a directed graph can have n(n − 1) = 90."),
    ("The complete graph K₆ has how many edges?",
     ["15", "30", "12", "36"], 0, "6 × 5 / 2 = 15."),
    ("In a directed graph, the sum of the in-degrees of all vertices equals:",
     ["The number of edges", "Twice the number of edges", "The number of vertices", "Zero"], 0, "Each edge has exactly one head; the out-degrees also sum to e."),
    ("An incidence matrix of a graph with n vertices and e edges has size:",
     ["n × e", "n × n", "e × e", "2n × e"], 0, "Entry (v, j) shows whether vertex v lies on edge j."),
    ("For a sparse graph (e much smaller than n²), the better representation is usually:",
     ["An adjacency list", "An adjacency matrix", "An incidence matrix", "A 3-D array"], 0, "It uses O(n + e) space instead of O(n²)."),
    ("Breadth-first search on a graph stored as an adjacency list takes:",
     ["O(n + e) time", "O(n²) time always", "O(e²) time", "O(log n) time"], 0, "With an adjacency matrix it takes O(n²), because each row must be scanned."),
    ("In a weighted graph's adjacency matrix, the absence of an edge is usually shown by:",
     ["∞ (or a special large value)", "0 always", "−1 always", "The vertex number"], 0, "0 can be a genuine weight, so ∞ marks 'no edge' in shortest-path algorithms."),
    ("The degree of vertex i in an undirected graph can be found from its adjacency matrix by:",
     ["Adding the entries in row i", "Looking at the diagonal entry", "Counting the columns", "Multiplying row i by column i"], 0, "In a directed graph, the row sum is the out-degree and the column sum the in-degree."),
    ("The transpose of a directed graph's adjacency matrix represents:",
     ["The same graph with every edge reversed", "The complement graph", "A spanning tree", "An undirected graph always"], 0, "Transposition swaps (u, v) with (v, u)."),
    ("If A is the adjacency matrix of a graph, the entry (i, j) of A² gives:",
     ["The number of walks of length 2 from i to j", "The shortest distance from i to j", "Whether i and j are adjacent", "The degree of i"], 0, "In general A^k counts walks of length k."),
    ("A graph with 1,000 vertices stored as an adjacency matrix of bits needs how many bits?",
     ["1,000,000", "1,000", "2,000", "500,500"], 0, "n² = 10⁶ bits, even if the graph has very few edges."),
    ("A connected acyclic undirected graph with n vertices has exactly:",
     ["n − 1 edges (it is a tree)", "n edges", "n(n − 1)/2 edges", "2n edges"], 0, "Adding any edge would create a cycle; removing any would disconnect it."),
    ("Match the representation with its typical use:\na. Adjacency matrix  b. Adjacency list  c. Edge list  d. Incidence matrix\n1. Relationships between vertices and edges in circuit/graph theory  2. Kruskal's algorithm (sort all edges)  3. BFS/DFS on large sparse graphs  4. Dense graphs and O(1) edge checks",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each representation suits different algorithms."),
    ("Depth-first search of a graph can be implemented with:",
     ["Recursion or an explicit stack", "A queue", "A priority queue only", "A hash table only"], 0, "Breadth-first search uses a queue."),
    ("Consider the statements:\nI. A directed graph's adjacency matrix need not be symmetric.\nII. A self-loop appears on the diagonal of the adjacency matrix.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Consider the statements:\nI. Adjacency lists make it O(1) to check whether a given edge exists.\nII. Adjacency lists make it easy to list all neighbours of a vertex.\nWhich is/are correct?",
     I_II, 1, "Edge lookup in a list takes O(degree); listing neighbours is exactly what lists are good at."),
    ("Assertion (A): An adjacency matrix wastes space for sparse graphs.\nReason (R): It stores an entry for every pair of vertices, whether or not an edge exists.",
     AR, 0, "Most of its n² entries are 0 when e is small."),
    ("Assertion (A): The sum of the degrees of an undirected graph can be odd.\nReason (R): Each edge adds 2 to the total degree.",
     AR, 3, "Because every edge adds 2, the sum is always even (2e); A is false."),
    ("Assertion (A): BFS with an adjacency list runs in O(n + e) time.\nReason (R): BFS finds shortest paths in weighted graphs.",
     AR, 2, "A is true; R is false – BFS gives shortest paths only in unweighted graphs."),
    ("Assertion (A): An undirected graph's adjacency matrix is symmetric.\nReason (R): Adjacency matrices need O(n²) space.",
     AR, 1, "Both true, but symmetry comes from edges having no direction."),
    ("A directed graph has 5 vertices and edges 1→2, 1→3, 2→3, 3→4, 4→1. The in-degree of vertex 3 is:",
     ["2", "1", "3", "0"], 0, "Edges into 3: 1→3 and 2→3."),
    ("Which structure stores, for each vertex, a linked list of its neighbours, and for each edge a node shared by both lists (useful for marking visited edges)?",
     ["Adjacency multilist", "Adjacency matrix", "Incidence matrix", "Hash set"], 0, "Each edge node appears once but is linked from both end vertices."),
    ("For a dense graph with n = 100 and e = 4,500, which representation is reasonable?",
     ["An adjacency matrix, since e is close to n²/2", "Only an edge list", "A linked list of vertices only", "A binary search tree"], 0, "The graph is nearly complete, so the matrix wastes little space and gives O(1) edge checks."),
]

SEARCHING = [
    ("Linear search on an array of n elements needs, on average for a successful search, about:",
     ["(n + 1)/2 comparisons", "log₂ n comparisons", "1 comparison", "n² comparisons"], 0, "Each position is equally likely to hold the key."),
    ("The maximum number of comparisons that binary search needs on a sorted array of 1,000 elements is:",
     ["10", "9", "500", "1000"], 0, "⌊log₂ 1000⌋ + 1 = 9 + 1 = 10."),
    ("The maximum number of comparisons that binary search needs on a sorted array of 1,024 elements is:",
     ["11", "10", "12", "1024"], 0, "⌊log₂ 1024⌋ + 1 = 10 + 1 = 11."),
    ("Binary search for 23 in [2, 5, 8, 12, 16, 23, 38, 56, 72, 91] (indices 0–9, mid = ⌊(low + high)/2⌋) examines which elements in order?",
     ["16, 56, 23", "16, 23", "38, 12, 23", "23"], 0, "mid 4 → 16 (go right); mid 7 → 56 (go left); mid 5 → 23 (found)."),
    ("Binary search requires that:",
     ["The data is sorted and allows random (indexed) access", "The data is in a linked list", "The data is unsorted", "The data has no duplicates"], 0, "Without random access, finding the middle costs O(n)."),
    ("Computing the middle index as low + (high − low) / 2 instead of (low + high) / 2 avoids:",
     ["Integer overflow for very large indices", "Infinite loops in every case", "Wrong answers for odd-length arrays", "The need for sorted data"], 0, "low + high can exceed the largest int value."),
    ("Interpolation search works best when the keys are:",
     ["Uniformly distributed, giving O(log log n) average time", "Randomly unsorted", "All equal", "Stored in a linked list"], 0, "It estimates the key's position from its value; its worst case is O(n)."),
    ("Jump search on a sorted array of n elements with the optimal block size needs about:",
     ["O(√n) comparisons", "O(log n) comparisons", "O(n) comparisons", "O(1) comparisons"], 0, "The optimal jump is √n; then a linear search is done inside one block."),
    ("A sentinel linear search places the key at the end of the array so that:",
     ["The loop needs no separate end-of-array test", "The array becomes sorted", "Binary search can be used", "Duplicates are removed"], 0, "It saves one comparison per step."),
    ("The recurrence for binary search is:",
     ["T(n) = T(n/2) + c, giving O(log n)", "T(n) = 2T(n/2) + n", "T(n) = T(n − 1) + c", "T(n) = 2T(n − 1)"], 0, "Each step halves the search range."),
    ("Searching for an element in an unsorted array of n elements has a worst-case time of:",
     ["O(n)", "O(log n)", "O(1)", "O(n log n)"], 0, "Every element may have to be checked."),
    ("For a sorted array that is searched many times, the best approach is:",
     ["Binary search", "Linear search", "Sorting before every search", "Bubble search"], 0, "O(log n) per search."),
    ("Exponential search first finds a range by checking indices 1, 2, 4, 8, … and then:",
     ["Performs binary search within that range", "Performs linear search over the whole array", "Sorts the range", "Stops at index 1"], 0, "It is useful for unbounded or very large sorted lists."),
    ("Binary search on a sorted array of 31 elements finds any present key using at most:",
     ["5 comparisons", "4 comparisons", "6 comparisons", "31 comparisons"], 0, "⌊log₂ 31⌋ + 1 = 4 + 1 = 5."),
    ("Which search method does NOT require the data to be sorted?",
     ["Linear search", "Binary search", "Interpolation search", "Jump search"], 0, "All the others depend on order."),
    ("Ternary search divides the range into three parts. On a sorted array, compared with binary search, it:",
     ["Makes more comparisons overall despite having fewer levels", "Is always twice as fast", "Needs unsorted data", "Uses no comparisons"], 0, "It needs 2 comparisons per level: 2 log₃ n > log₂ n."),
    ("Fibonacci search, like binary search, works on sorted arrays but divides the range using:",
     ["Fibonacci numbers, avoiding division", "Random positions", "Square roots", "Powers of 3"], 0, "It uses only addition and subtraction to compute positions."),
    ("A linear search is made for a key that is not present in an array of 50 elements. How many comparisons are made?",
     ["50", "25", "1", "6"], 0, "Every element is compared once before failure is reported."),
    ("Match the search method with its time complexity:\na. Linear search  b. Binary search  c. Interpolation search (uniform data, average)  d. Jump search\n1. O(√n)  2. O(log log n)  3. O(log n)  4. O(n)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These are typical exam comparisons."),
    ("Consider the statements:\nI. Binary search can be written either recursively or iteratively.\nII. Binary search is efficient on a singly linked list.\nWhich is/are correct?",
     I_II, 0, "A linked list lacks random access, so reaching the middle costs O(n)."),
    ("Consider the statements:\nI. Linear search works on unsorted data.\nII. Linear search's best case is O(1).\nWhich is/are correct?",
     I_II, 2, "Both are correct; the best case is when the key is the first element."),
    ("Assertion (A): Binary search runs in O(log n) time.\nReason (R): Each comparison halves the remaining search range.",
     AR, 0, "Halving n repeatedly takes about log₂ n steps."),
    ("Assertion (A): Binary search works on unsorted arrays.\nReason (R): Binary search discards half of the range after comparing with the middle element.",
     AR, 3, "Discarding half is only correct when the array is sorted, so A is false."),
    ("Assertion (A): Interpolation search can be faster than binary search on uniformly distributed data.\nReason (R): Interpolation search always takes O(log log n) time, even in the worst case.",
     AR, 2, "A is true; R is false – its worst case is O(n)."),
    ("Assertion (A): Linear search is suitable for small or unsorted lists.\nReason (R): Binary search needs random access to elements.",
     AR, 1, "Both true, but R describes binary search rather than explaining A."),
    ("In a sorted array with duplicates, finding the FIRST occurrence of a key efficiently requires:",
     ["A modified binary search that continues to the left after a match", "Linear search only", "Sorting again", "Hashing only"], 0, "It still runs in O(log n)."),
    ("Binary search for 40 in [10, 20, 30, 40, 50, 60, 70] (mid = ⌊(low + high)/2⌋) makes how many comparisons with array elements?",
     ["1", "2", "3", "4"], 0, "mid = 3 → 40 is found at once."),
    ("Binary search for 70 in [10, 20, 30, 40, 50, 60, 70] (mid = ⌊(low + high)/2⌋) makes how many comparisons?",
     ["3", "2", "1", "7"], 0, "40 → 60 → 70."),
    ("The space complexity of an iterative binary search is:",
     ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 0, "Recursive binary search needs O(log n) stack space."),
    ("Which data structure gives O(1) average-time search for keys without keeping them sorted?",
     ["A hash table", "A sorted array", "A linked list", "A stack"], 0, "Hashing computes the likely position directly from the key."),
]

ELEMENTARY_SORTS = [
    ("A sorting algorithm is called stable if:",
     ["Equal keys keep their original relative order", "It never uses extra memory", "It always runs in O(n log n)", "It works only on integers"], 0, "Stability matters when sorting records by one field after another."),
    ("A sorting algorithm is in-place if it:",
     ["Needs only O(1) (or very little) extra memory besides the input", "Never moves any element", "Sorts only part of the array", "Needs a second array of the same size"], 0, "Merge sort (array version) is not in-place."),
    ("After the first pass of bubble sort (ascending) on [5, 1, 4, 2, 8], the array is:",
     ["[1, 4, 2, 5, 8]", "[1, 2, 4, 5, 8]", "[1, 5, 4, 2, 8]", "[5, 1, 4, 2, 8]"], 0, "Adjacent swaps carry 5 past 1, 4 and 2; 8 stays at the end."),
    ("Bubble sort with a 'no swaps' flag, run on an already sorted array, takes:",
     ["O(n) time", "O(n²) time", "O(log n) time", "O(n log n) time"], 0, "One pass with no swaps shows that the array is sorted."),
    ("After two passes of selection sort (ascending) on [64, 25, 12, 22, 11], the array is:",
     ["[11, 12, 25, 22, 64]", "[11, 12, 22, 25, 64]", "[11, 25, 12, 22, 64]", "[12, 11, 22, 25, 64]"], 0, "Pass 1 swaps 11 with 64: [11, 25, 12, 22, 64]; pass 2 swaps 12 with 25: [11, 12, 25, 22, 64]."),
    ("The number of comparisons made by selection sort on 10 elements, in every case, is:",
     ["45", "100", "10", "90"], 0, "n(n − 1)/2 = 45, whatever the input order."),
    ("The maximum number of swaps made by selection sort on n elements is:",
     ["n − 1", "n(n − 1)/2", "n²", "log₂ n"], 0, "At most one swap per pass – useful when writes are expensive."),
    ("Insertion sort runs in O(n) time when the input is:",
     ["Already sorted (or nearly sorted)", "In reverse order", "Random", "All distinct and shuffled"], 0, "Each new element needs only one comparison."),
    ("The number of element shifts done by insertion sort equals the number of:",
     ["Inversions in the input", "Elements", "Comparisons in merge sort", "Distinct values"], 0, "An inversion is a pair (i, j) with i < j but a[i] > a[j]."),
    ("How many inversions are in the array [3, 1, 2]?",
     ["2", "1", "3", "0"], 0, "(3, 1) and (3, 2)."),
    ("The maximum number of inversions in an array of n distinct elements is:",
     ["n(n − 1)/2, for reverse-sorted input", "n − 1", "n", "log₂ n"], 0, "Every pair is out of order."),
    ("Which elementary sort is NOT stable in its usual form?",
     ["Selection sort", "Insertion sort", "Bubble sort", "Counting sort"], 0, "Its long-distance swaps can move equal keys past each other."),
    ("Shell sort improves insertion sort by:",
     ["Comparing and moving elements that are far apart using decreasing gaps", "Using a heap", "Using recursion to split the array", "Counting occurrences of keys"], 0, "It ends with gap 1, which is ordinary insertion sort on nearly sorted data."),
    ("Insertion sort (ascending) is run on [12, 11, 13, 5, 6]. What is the array after the first three elements are in sorted order?",
     ["[11, 12, 13, 5, 6]", "[5, 11, 12, 13, 6]", "[11, 12, 5, 13, 6]", "[5, 6, 11, 12, 13]"], 0, "11 moves before 12; 13 stays; 5 and 6 are not processed yet."),
    ("The worst-case time of bubble, selection and insertion sort is:",
     ["O(n²)", "O(n log n)", "O(n)", "O(log n)"], 0, "They are quadratic sorts."),
    ("For a small array that is almost sorted, the best choice among the elementary sorts is:",
     ["Insertion sort", "Selection sort", "Bubble sort without a flag", "Any of them equally"], 0, "It adapts to the few inversions present."),
    ("How many passes does bubble sort (with an early-exit flag) need to sort [1, 2, 3, 5, 4]?",
     ["2", "1", "4", "5"], 0, "Pass 1 swaps 5 and 4; pass 2 makes no swaps and stops."),
    ("Match the sort with its best-case time (usual implementation):\na. Bubble sort with flag  b. Selection sort  c. Insertion sort  d. Shell sort\n1. Depends on the gap sequence  2. O(n)  3. O(n²)  4. O(n)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Selection sort always scans the remaining elements."),
    ("Consider the statements:\nI. Insertion sort is stable.\nII. Insertion sort is in-place.\nWhich is/are correct?",
     I_II, 2, "It shifts elements within the array and never moves equal keys past each other."),
    ("Consider the statements:\nI. Selection sort's number of comparisons depends on the initial order of the data.\nII. Selection sort makes at most n − 1 swaps.\nWhich is/are correct?",
     I_II, 1, "Selection sort always makes n(n − 1)/2 comparisons."),
    ("Assertion (A): Insertion sort is efficient for nearly sorted data.\nReason (R): Its running time is proportional to n plus the number of inversions.",
     AR, 0, "Few inversions means little work."),
    ("Assertion (A): Selection sort is stable.\nReason (R): Selection sort swaps the minimum element into place, possibly over equal keys.",
     AR, 3, "Those long-distance swaps are exactly what make it unstable; A is false."),
    ("Assertion (A): Bubble sort with a flag stops early on sorted input.\nReason (R): Bubble sort always makes n(n − 1)/2 comparisons.",
     AR, 2, "A is true; R is false – with a flag it stops after one pass on sorted data."),
    ("Assertion (A): Shell sort is usually faster than insertion sort on large arrays.\nReason (R): Shell sort was published by Donald Shell in 1959.",
     AR, 1, "Both true, but the date does not explain the speed; the large early gaps do."),
    ("Selection sort is preferred over insertion sort mainly when:",
     ["Writing (swapping) elements is very expensive", "The data is nearly sorted", "Stability is essential", "The array is huge"], 0, "It makes at most n − 1 swaps."),
    ("How many comparisons does bubble sort without a flag make on 6 elements?",
     ["15", "36", "6", "30"], 0, "n(n − 1)/2 = 15."),
    ("After one pass of bubble sort (ascending), which element is guaranteed to be in its final position?",
     ["The largest element, at the end", "The smallest element, at the start", "The median", "No element"], 0, "The largest value bubbles to the last position."),
    ("After one pass of selection sort (ascending), which element is guaranteed to be in its final position?",
     ["The smallest element, at the start", "The largest element, at the end", "The median", "No element"], 0, "Each pass selects the minimum of the remaining part."),
    ("Which of the following sorting algorithms is adaptive (faster on partly sorted input)?",
     ["Insertion sort", "Selection sort", "Heap sort", "Standard merge sort"], 0, "Selection sort and heap sort do the same work regardless of input order."),
    ("The array [2, 1, 3, 1'] (1' is a second 1 with a different tag) is sorted by a stable sort. The result is:",
     ["[1, 1', 2, 3]", "[1', 1, 2, 3]", "[1, 2, 1', 3]", "[3, 2, 1, 1']"], 0, "A stable sort keeps 1 before 1', as in the input."),
]

ADVANCED_SORTS = [
    ("Merge sort runs in:",
     ["O(n log n) time in the best, average and worst cases", "O(n²) in the worst case", "O(n) in the worst case", "O(log n) always"], 0, "Its recurrence is T(n) = 2T(n/2) + O(n)."),
    ("The array version of merge sort needs extra memory of:",
     ["O(n)", "O(1)", "O(log n) only", "O(n²)"], 0, "The merge step copies elements into a temporary array."),
    ("Merging two sorted lists of lengths 5 and 7 needs at most how many comparisons?",
     ["11", "12", "35", "7"], 0, "m + n − 1 = 11 in the worst case."),
    ("Quick sort's worst-case time is O(n²). It occurs, for example, when:",
     ["The first element is always the pivot and the input is already sorted", "The input is random", "The median is always chosen as pivot", "All elements are distinct and shuffled"], 0, "The partitions become sizes n − 1 and 0 at every step."),
    ("Quick sort's average-case time is:",
     ["O(n log n)", "O(n²)", "O(n)", "O(log n)"], 0, "Random or median-of-three pivots make the worst case very unlikely."),
    ("Which of these sorts is NOT stable in its usual form?",
     ["Quick sort", "Merge sort", "Insertion sort", "Counting sort"], 0, "Heap sort and selection sort are also unstable."),
    ("Heap sort runs in O(n log n) time and is:",
     ["In-place but not stable", "Stable but not in-place", "Both stable and in-place", "Neither, and O(n²)"], 0, "It uses the array itself as the heap."),
    ("Every comparison-based sorting algorithm needs, in the worst case, at least:",
     ["Ω(n log n) comparisons", "Ω(n) comparisons", "Ω(n²) comparisons", "Ω(log n) comparisons"], 0, "The decision-tree argument: log₂(n!) ≈ n log₂ n."),
    ("Counting sort sorts n integers in the range 0..k in:",
     ["O(n + k) time and is stable", "O(n log n) time only", "O(n²) time", "O(k²) time and is unstable"], 0, "It is not comparison-based, so the Ω(n log n) bound does not apply."),
    ("Radix sort on n numbers of d digits in base b runs in:",
     ["O(d (n + b)) time", "O(n log n) time", "O(n²) time", "O(d n²) time"], 0, "It sorts digit by digit with a stable sort such as counting sort."),
    ("Radix sort that processes the least significant digit first requires the per-digit sort to be:",
     ["Stable", "Unstable", "In-place", "Recursive"], 0, "Stability keeps the order produced by earlier (less significant) digits."),
    ("Using the Lomuto partition scheme with the last element as pivot, partitioning [4, 7, 2, 6, 5] around 5 gives:",
     ["[4, 2, 5, 6, 7], with 5 at index 2", "[2, 4, 5, 7, 6]", "[4, 7, 2, 5, 6]", "[5, 4, 7, 2, 6]"], 0, "4 and 2 are moved to the front ([4, 2, 7, 6, 5]); then 5 is swapped with 7."),
    ("To sort a large file that does not fit in main memory, the usual method is:",
     ["External merge sort", "Quick sort in memory", "Bubble sort", "Selection sort"], 0, "Sorted runs are created and then merged in passes."),
    ("To sort a singly linked list efficiently, the preferred algorithm is:",
     ["Merge sort", "Quick sort with random access", "Heap sort", "Shell sort"], 0, "Merging needs only sequential access and relinking."),
    ("The recurrence T(n) = 2T(n/2) + n, solved with the master theorem, gives:",
     ["Θ(n log n)", "Θ(n)", "Θ(n²)", "Θ(log n)"], 0, "Case 2: f(n) = Θ(n^log₂2) = Θ(n)."),
    ("Choosing the median of the first, middle and last elements as the pivot in quick sort helps mainly to:",
     ["Avoid the worst case on sorted or reverse-sorted input", "Make quick sort stable", "Remove recursion completely", "Reduce memory to O(1)"], 0, "It gives better partitions on common input patterns."),
    ("Building a heap from n elements takes O(n); then n delete-max operations take:",
     ["O(n log n) in total", "O(n) in total", "O(n²) in total", "O(log n) in total"], 0, "Each delete-max costs O(log n)."),
    ("Bucket sort runs in O(n) average time when:",
     ["The input is uniformly distributed over the range", "The input is already sorted", "All keys are equal", "Only comparisons are allowed"], 0, "Each bucket then holds only a few elements."),
    ("Match the sorting algorithm with its worst-case time:\na. Merge sort  b. Quick sort  c. Heap sort  d. Counting sort (range k)\n1. O(n + k)  2. O(n log n)  3. O(n²)  4. O(n log n)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Only quick sort degrades to quadratic time."),
    ("Consider the statements:\nI. Merge sort is stable.\nII. Heap sort is stable.\nWhich is/are correct?",
     I_II, 0, "Heap sort's swaps across the heap break stability."),
    ("Consider the statements:\nI. Quick sort is usually faster in practice than heap sort.\nII. Quick sort's worst case is O(n log n).\nWhich is/are correct?",
     I_II, 0, "Quick sort has good cache behaviour and small constants, but its worst case is O(n²)."),
    ("Assertion (A): Counting sort can beat the Ω(n log n) lower bound.\nReason (R): Counting sort does not sort by comparing elements.",
     AR, 0, "The lower bound applies only to comparison sorts."),
    ("Assertion (A): Merge sort's worst case is O(n²).\nReason (R): Merge sort always divides the array into two halves.",
     AR, 3, "Because the halves are always balanced, merge sort is O(n log n) in every case; A is false."),
    ("Assertion (A): Randomised quick sort runs in O(n log n) expected time on every input.\nReason (R): Randomised quick sort never makes more than n log n comparisons.",
     AR, 2, "A is true; R is false – an unlucky run can still take O(n²)."),
    ("Assertion (A): Heap sort needs only O(1) extra space.\nReason (R): Heap sort was invented by J. W. J. Williams in 1964.",
     AR, 1, "Both true, but the history does not explain the space bound; building the heap inside the array does."),
    ("How many levels of recursion does merge sort have for n = 16 elements (counting the single-element level)?",
     ["5", "4", "16", "8"], 0, "Sizes 16, 8, 4, 2, 1: log₂ 16 + 1 = 5 levels."),
    ("Quick sort uses O(log n) stack space on average, but O(n) in the worst case unless:",
     ["It always recurses on the smaller partition first (and loops on the larger)", "It uses a stable partition", "It sorts in descending order", "It uses the first element as pivot"], 0, "That keeps the stack depth O(log n) even in bad cases."),
    ("Which sort would you choose to sort 1 million records where stability is required and O(n log n) worst case must be guaranteed?",
     ["Merge sort", "Quick sort", "Heap sort", "Selection sort"], 0, "It is stable and always O(n log n)."),
    ("Which sort is best for sorting 10 million integers between 0 and 999?",
     ["Counting sort", "Bubble sort", "Insertion sort", "Selection sort"], 0, "The small range k = 1000 gives O(n + k) time."),
    ("Timsort, used in Python and Java for objects, is a hybrid of:",
     ["Merge sort and insertion sort", "Quick sort and heap sort", "Radix sort and bucket sort", "Selection sort and bubble sort"], 0, "It exploits existing sorted runs in real-world data."),
]

TOPICS = {
    "Sets & Graph Representation": [("1 · Data Structures for Sets", SETS),
                                    ("2 · Graph Representation", GRAPH_REP)],
    "Sorting and Searching": [("1 · Searching Algorithms", SEARCHING),
                              ("2 · Elementary Sorting Algorithms", ELEMENTARY_SORTS),
                              ("3 · Advanced Sorting Algorithms", ADVANCED_SORTS)],
}
