"""Paper 2 · Unit 8 · Graph Algorithms (3 × 30); Complexity Theory (2 × 30).
References: Cormen et al., Introduction to Algorithms (CLRS); Horowitz, Sahni & Rajasekaran; Garey & Johnson, Computers and Intractability;
Sipser, Introduction to the Theory of Computation. Explanations starting "PYQ pattern" follow questions that recur in UGC-NET CS / GATE / KEA papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (UGC-NET / GATE / KEA). "

TRAVERSALS = [
    ("Breadth-first search is implemented using a:",
     ["Queue", "Stack", "Priority queue", "Hash table"], 0, PYQ + "Vertices are processed in the order they are discovered, level by level."),
    ("Depth-first search is implemented using:",
     ["A stack or recursion", "A queue", "A min-heap", "A circular buffer only"], 0, PYQ + "It goes as deep as possible before backtracking."),
    ("In an unweighted graph, BFS from s finds:",
     ["Shortest paths (fewest edges) from s to every reachable vertex", "Longest paths", "A minimum spanning tree of a weighted graph", "All cycles"], 0, PYQ + "A vertex first discovered at level k is at distance k."),
    ("DFS on a graph stored as an adjacency matrix takes:",
     ["O(V²) time", "O(V + E) time", "O(E log V) time", "O(V³) time"], 0, "Each vertex's whole row must be scanned for neighbours."),
    ("Undirected graph edges: A–B, A–C, B–D, C–D, D–E. BFS from A, visiting neighbours in alphabetical order, gives:",
     ["A, B, C, D, E", "A, B, D, C, E", "A, C, B, D, E", "A, B, D, E, C"], 0, "Level 0: A; level 1: B, C; level 2: D; level 3: E."),
    ("Same graph (A–B, A–C, B–D, C–D, D–E). DFS from A, visiting neighbours in alphabetical order, gives:",
     ["A, B, D, C, E", "A, B, C, D, E", "A, C, D, B, E", "A, B, D, E, C"], 0, "A → B → D → C (D's first unvisited neighbour); back to D → E."),
    ("A directed graph contains a cycle if and only if a DFS of it finds a:",
     ["Back edge", "Tree edge only", "Forward edge", "Cross edge"], 0, PYQ + "A back edge goes to an ancestor that is still on the recursion stack."),
    ("In a DFS of an undirected graph, the edges are classified only as:",
     ["Tree edges and back edges", "Tree, forward and cross edges", "Cross edges only", "Forward edges only"], 0, PYQ + "Forward and cross edges cannot occur in undirected DFS."),
    ("Topological sorting is possible only for:",
     ["Directed acyclic graphs (DAGs)", "Undirected graphs", "Graphs with cycles", "Complete graphs"], 0, PYQ + "A cycle would require a vertex to come before itself."),
    ("DAG edges: A → B, A → C, B → D, C → D. Which is a valid topological order?",
     ["A, C, B, D", "B, A, C, D", "A, D, B, C", "D, C, B, A"], 0, "Every edge must go from left to right."),
    ("How many different topological orders does the DAG A → B, A → C, B → D, C → D have?",
     ["2", "1", "4", "6"], 0, "A first, D last; B and C in either order."),
    ("Kahn's algorithm for topological sorting repeatedly removes vertices with:",
     ["In-degree 0", "Out-degree 0 only", "The largest degree", "Odd degree"], 0, "If some vertices are never removed, the graph has a cycle."),
    ("Using DFS, a topological order is obtained by listing vertices in:",
     ["Decreasing order of finishing time", "Increasing order of discovery time", "Alphabetical order", "Increasing order of degree"], 0, "A vertex finishes only after all vertices reachable from it."),
    ("The number of connected components of an undirected graph can be found by:",
     ["Running BFS or DFS from each unvisited vertex and counting the runs", "Sorting the edges", "Dijkstra's algorithm only", "Computing the adjacency matrix's determinant"], 0, "Each new start vertex begins a new component."),
    ("A graph is bipartite if and only if it has no:",
     ["Odd-length cycle", "Even-length cycle", "Vertex of degree 2", "Tree as a subgraph"], 0, PYQ + "BFS 2-colouring detects an odd cycle when two adjacent vertices get the same colour."),
    ("Kosaraju's algorithm for strongly connected components uses:",
     ["Two DFS passes, the second on the transposed graph", "One BFS pass only", "Dijkstra's algorithm", "Sorting of edges by weight"], 0, "It runs in O(V + E); Tarjan's algorithm uses a single DFS."),
    ("An articulation point (cut vertex) of a connected graph is a vertex whose removal:",
     ["Disconnects the graph", "Creates a cycle", "Removes all edges", "Makes the graph complete"], 0, "A bridge is an edge whose removal disconnects the graph."),
    ("A BFS tree of a connected graph with n vertices has:",
     ["n − 1 edges", "n edges", "2n edges", "n(n − 1)/2 edges"], 0, "It is a spanning tree."),
    ("The extra space used by BFS is:",
     ["O(V) for the queue and visited marks", "O(1)", "O(E²)", "O(V³)"], 0, "In the worst case almost all vertices can be in the queue."),
    ("Which traversal is better suited to finding a vertex that is close to the start vertex in a huge graph?",
     ["BFS", "DFS", "Both are always equal", "Neither can do it"], 0, "BFS explores nearer vertices first."),
    ("Which is NOT an application of DFS?",
     ["Finding shortest paths in a weighted graph", "Detecting cycles", "Topological sorting", "Finding strongly connected components"], 0, "Weighted shortest paths need Dijkstra or Bellman–Ford."),
    ("Consider the statements:\nI. BFS uses a queue.\nII. DFS can be written recursively.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Consider the statements:\nI. Every directed graph has a topological order.\nII. A DAG always has at least one vertex of in-degree 0.\nWhich is/are correct?",
     I_II, 1, "Graphs with cycles have no topological order."),
    ("Consider the statements:\nI. DFS of an undirected graph can produce cross edges.\nII. BFS gives shortest paths in weighted graphs.\nWhich is/are correct?",
     I_II, 3, "Neither is correct."),
    ("Assertion (A): BFS finds shortest paths in unweighted graphs.\nReason (R): BFS visits vertices in increasing order of their distance from the source.",
     AR, 0, "It finishes one level before starting the next."),
    ("Assertion (A): A DAG can have more than one topological order.\nReason (R): A DAG always has exactly one source vertex.",
     AR, 2, "A is true; R is false – a DAG can have several sources."),
    ("Assertion (A): Topological sort is possible for a graph with a directed cycle.\nReason (R): In a directed cycle, every vertex must come before another vertex of the cycle.",
     AR, 3, "Because of R, no order can satisfy a cycle; A is false."),
    ("Match the problem with the algorithm:\na. Strongly connected components  b. Topological order  c. Shortest paths in unweighted graphs  d. Bipartite testing\n1. BFS 2-colouring  2. BFS from the source  3. Kahn's algorithm  4. Kosaraju's algorithm",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "All run in O(V + E) with adjacency lists."),
    ("Match the DFS edge type (directed graph) with its description:\na. Tree edge  b. Back edge  c. Forward edge  d. Cross edge\n1. Between vertices with no ancestor–descendant relation  2. To a descendant that is not a child  3. To an ancestor  4. Edge used to discover a new vertex",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "CLRS edge classification."),
    ("In BFS of an undirected graph from vertex s, if u is at distance 3 and (u, v) is an edge, the distance of v from s can be:",
     ["2, 3 or 4", "Only 4", "Any value", "Only 3"], 0, "Adjacent vertices differ in BFS level by at most 1 (undirected graph)."),
]

SHORTEST_PATHS = [
    ("Dijkstra's algorithm solves:",
     ["Single-source shortest paths with non-negative edge weights", "All-pairs shortest paths with negative cycles", "Maximum flow", "Minimum spanning tree"], 0, PYQ + "It is a greedy algorithm."),
    ("Dijkstra's algorithm implemented with a simple array (no heap) runs in:",
     ["O(V²) time", "O(V + E) time", "O(E log E) time", "O(V³) time"], 0, "Suitable for dense graphs; a binary heap gives O((V + E) log V)."),
    ("Edges: S→A 4, S→B 1, B→A 2, A→C 1, B→C 5. The shortest distance from S to C is:",
     ["4", "5", "6", "3"], 0, "S → B → A → C = 1 + 2 + 1 = 4."),
    ("For the same graph (S→A 4, S→B 1, B→A 2, A→C 1, B→C 5), Dijkstra's algorithm finalises the vertices in the order:",
     ["S, B, A, C", "S, A, B, C", "S, B, C, A", "S, C, A, B"], 0, "Distances when finalised: S 0, B 1, A 3, C 4."),
    ("Relaxing edge (u, v) with weight w means:",
     ["If d[v] > d[u] + w, set d[v] = d[u] + w and π[v] = u", "Deleting the edge", "Setting d[v] = 0", "Doubling the weight"], 0, PYQ + "All single-source algorithms are built on relaxation."),
    ("Bellman–Ford on a graph with 6 vertices relaxes all edges how many times (before the negative-cycle check)?",
     ["5", "6", "4", "36"], 0, "V − 1 passes, because a shortest simple path has at most V − 1 edges."),
    ("Bellman–Ford detects a negative-weight cycle reachable from the source when:",
     ["An edge can still be relaxed after V − 1 passes", "All distances become 0", "The graph has no edges", "The first pass changes nothing"], 0, PYQ + "Shortest paths are then undefined."),
    ("Edges: S→A 2, S→B 5, B→A −4. Dijkstra's algorithm, which never changes a vertex's distance after removing it from the queue, reports d(A) =",
     ["2, although the true shortest distance is 1", "1, the correct value", "−4", "5"], 0, "A is finalised with 2; the cheaper path S → B → A (5 − 4 = 1) is found too late."),
    ("The Floyd–Warshall update is:",
     ["d(i, j) = min(d(i, j), d(i, k) + d(k, j))", "d(i, j) = d(i, k) × d(k, j)", "d(i, j) = max(d(i, j), d(i, k))", "d(i, j) = d(j, i)"], 0, PYQ + "k runs over the allowed intermediate vertices."),
    ("Floyd–Warshall reveals a negative cycle when, at the end:",
     ["Some diagonal entry d(i, i) is negative", "All entries are positive", "The matrix is symmetric", "Some entry is ∞"], 0, "A vertex can reach itself with negative total weight."),
    ("Three vertices: d(1, 2) = 3, d(2, 3) = 4, d(1, 3) = 10 initially. After Floyd–Warshall considers vertex 2 as an intermediate, d(1, 3) becomes:",
     ["7", "10", "3", "4"], 0, "min(10, 3 + 4) = 7."),
    ("Floyd–Warshall on 5 vertices executes its outermost loop (over k) how many times?",
     ["5", "25", "125", "4"], 0, "Once for each possible intermediate vertex."),
    ("Johnson's algorithm for all-pairs shortest paths in sparse graphs:",
     ["Reweights edges using Bellman–Ford, then runs Dijkstra from every vertex", "Runs BFS only", "Uses Kruskal's algorithm", "Works only on trees"], 0, "It runs in O(VE log V) with a binary heap."),
    ("Single-source shortest paths in a DAG (even with negative weights) can be found in:",
     ["O(V + E) time by relaxing edges in topological order", "O(V³) time only", "O(VE) time only", "Exponential time"], 0, "No cycles means no negative cycles."),
    ("Shortest paths from one source in an unweighted graph are best found by:",
     ["BFS", "Floyd–Warshall", "Bellman–Ford", "Prim's algorithm"], 0, "It runs in O(V + E)."),
    ("The optimal-substructure property of shortest paths says that:",
     ["Every subpath of a shortest path is itself a shortest path", "Every shortest path uses the heaviest edge", "Shortest paths are unique", "Shortest paths never share vertices"], 0, "This is why both greedy and DP methods work."),
    ("In the A* search algorithm, f(n) = g(n) + h(n). The heuristic h is admissible if it:",
     ["Never overestimates the true cost to reach the goal", "Always overestimates", "Is always zero", "Is negative"], 0, "With an admissible (and consistent) heuristic, A* finds optimal paths."),
    ("After running a single-source algorithm, the actual shortest path to v is recovered using:",
     ["The predecessor array π, followed back from v to the source", "The adjacency matrix only", "A second run of the algorithm", "Sorting the distances"], 0, "π[v] is the vertex before v on the shortest path."),
    ("The Floyd–Warshall algorithm needs space:",
     ["O(V²)", "O(V)", "O(V³)", "O(E)"], 0, "One V × V distance matrix (updated in place)."),
    ("If a graph has a negative-weight cycle reachable from s, the shortest distance from s to vertices reachable from that cycle is:",
     ["Undefined (−∞)", "Zero", "The number of edges", "Always positive"], 0, "Going around the cycle again always lowers the cost."),
    ("Dijkstra's algorithm with a Fibonacci heap runs in:",
     ["O(E + V log V)", "O(V²)", "O(VE)", "O(V³)"], 0, "DECREASE-KEY becomes O(1) amortised."),
    ("Consider the statements:\nI. Dijkstra's algorithm can handle negative edge weights.\nII. Bellman–Ford can handle negative edge weights.\nWhich is/are correct?",
     I_II, 1, "Only Bellman–Ford handles them correctly."),
    ("Consider the statements:\nI. Floyd–Warshall computes shortest paths between all pairs.\nII. Floyd–Warshall runs in Θ(V³) time.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Consider the statements:\nI. Adding the same positive constant to every edge weight never changes the shortest path between two vertices.\nII. Shortest paths can be found in O(V + E) time in a DAG.\nWhich is/are correct?",
     I_II, 1, "Adding a constant penalises paths with more edges, so shortest paths can change."),
    ("Assertion (A): Dijkstra's algorithm can fail with negative edges.\nReason (R): Once a vertex is finalised, Dijkstra's algorithm never updates its distance again.",
     AR, 0, "A later negative edge might have given a shorter path."),
    ("Assertion (A): Bellman–Ford needs V − 1 passes over the edges.\nReason (R): A shortest simple path contains at most V − 1 edges.",
     AR, 0, "Each pass fixes at least one more edge of every shortest path."),
    ("Assertion (A): Floyd–Warshall is a greedy algorithm.\nReason (R): Floyd–Warshall runs in Θ(V³) time.",
     AR, 3, "It is a dynamic-programming algorithm; A is false, R is true."),
    ("Assertion (A): BFS finds shortest paths in unweighted graphs in linear time.\nReason (R): A* search was introduced in 1968.",
     AR, 1, "Both true, but R does not explain A."),
    ("Match the algorithm with its time complexity:\na. Dijkstra (binary heap)  b. Bellman–Ford  c. Floyd–Warshall  d. DAG shortest paths\n1. O(V + E)  2. Θ(V³)  3. O(VE)  4. O((V + E) log V)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Standard shortest-path complexities."),
    ("Match the situation with the best algorithm:\na. Non-negative weights, one source  b. Negative weights, one source  c. All pairs, dense graph  d. Unweighted graph, one source\n1. BFS  2. Floyd–Warshall  3. Bellman–Ford  4. Dijkstra",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Choosing the right algorithm is a common question."),
]

MST_FLOW = [
    ("A minimum spanning tree of a connected weighted graph is:",
     ["A spanning tree whose total edge weight is as small as possible", "The shortest path between two vertices", "A tree containing only the lightest edge", "Any spanning tree"], 0, "It connects all vertices without cycles."),
    ("The cut property states that for any cut of the graph:",
     ["A lightest edge crossing the cut belongs to some MST", "The heaviest edge crossing the cut is in every MST", "No edge crossing the cut is in an MST", "All crossing edges are in the MST"], 0, "Both Prim's and Kruskal's algorithms rely on it."),
    ("The cycle property states that:",
     ["The unique heaviest edge on any cycle is not in any MST", "The lightest edge on a cycle is never in the MST", "Every cycle edge is in the MST", "MSTs contain exactly one cycle"], 0, "Removing it keeps connectivity at lower cost."),
    ("If all edge weights of a connected graph are distinct, then its MST is:",
     ["Unique", "Not unique", "Always a path", "Impossible to find"], 0, PYQ + "With ties, several MSTs may exist."),
    ("Edges: A–B 1, B–C 2, A–C 3, C–D 4, B–D 5. The weight of the MST is:",
     ["7", "6", "8", "10"], 0, "Kruskal picks A–B (1), B–C (2), skips A–C (cycle), picks C–D (4): 1 + 2 + 4 = 7."),
    ("For the same graph (A–B 1, B–C 2, A–C 3, C–D 4, B–D 5), Prim's algorithm from A adds edges in the order:",
     ["A–B, B–C, C–D", "A–B, A–C, C–D", "A–C, B–C, C–D", "A–B, B–D, C–D"], 0, "At each step it adds the cheapest edge leaving the current tree."),
    ("The number of spanning trees of the complete graph K₄ is:",
     ["16", "12", "4", "24"], 0, PYQ + "Cayley's formula: nⁿ⁻² = 4² = 16."),
    ("If every edge weight of a graph is increased by the same constant, the minimum spanning tree:",
     ["Stays the same set of edges", "Always changes", "Becomes a path", "Disappears"], 0, PYQ + "Every spanning tree has n − 1 edges, so all totals rise equally."),
    ("For a dense graph, which implementation of Prim's algorithm is efficient?",
     ["Adjacency matrix with an array of keys, O(V²)", "Edge list sorted by weight, O(E²)", "BFS only", "Adjacency list with no priority queue, O(V³)"], 0, "O(V²) is optimal when E ≈ V²."),
    ("The earliest known MST algorithm (1926), which repeatedly adds the cheapest edge leaving each component, is due to:",
     ["Otakar Borůvka", "Robert Prim", "Joseph Kruskal", "Edsger Dijkstra"], 0, "It is useful in parallel computation."),
    ("In a flow network, the capacity constraint says that the flow on each edge must satisfy:",
     ["0 ≤ f(u, v) ≤ c(u, v)", "f(u, v) = c(u, v) always", "f(u, v) > c(u, v)", "f(u, v) < 0"], 0, "Flow cannot exceed capacity."),
    ("Flow conservation says that, for every vertex other than the source and sink:",
     ["Total flow in equals total flow out", "Flow in is double the flow out", "No flow enters", "Flow out is zero"], 0, "Only the source produces and only the sink absorbs flow."),
    ("The Ford–Fulkerson method finds maximum flow by:",
     ["Repeatedly pushing flow along augmenting paths in the residual network", "Sorting edges by capacity", "Running DFS once", "Finding an MST"], 0, PYQ + "It stops when no augmenting path remains."),
    ("The max-flow min-cut theorem states that:",
     ["The value of a maximum flow equals the capacity of a minimum s–t cut", "Max flow is always twice the min cut", "Max flow equals the number of vertices", "Min cut is always zero"], 0, PYQ + "It is the central theorem of network flows."),
    ("The Edmonds–Karp algorithm is Ford–Fulkerson with augmenting paths found by BFS. It runs in:",
     ["O(VE²) time", "O(V + E) time", "O(E log V) time", "Exponential time"], 0, "Using shortest augmenting paths bounds the number of iterations."),
    ("Network: s→a 3, s→b 2, a→t 2, b→t 3, a→b 1. The maximum flow from s to t is:",
     ["5", "4", "6", "3"], 0, "Send 2 on s→a→t, 1 on s→a→b→t and 2 on s→b→t; the cut {s} has capacity 3 + 2 = 5."),
    ("In the same network (s→a 3, s→b 2, a→t 2, b→t 3, a→b 1), the capacity of the cut ({s, a}, {b, t}) is:",
     ["5", "4", "6", "7"], 0, "Edges leaving {s, a}: s→b 2, a→t 2, a→b 1 → 5."),
    ("An edge has capacity 10 and carries flow 7. In the residual network it gives:",
     ["A forward residual capacity of 3 and a backward residual capacity of 7", "Only a forward capacity of 10", "A forward capacity of 7 and backward 3", "No residual edges"], 0, "The backward edge allows flow to be cancelled."),
    ("If all capacities are integers, Ford–Fulkerson finds a maximum flow that is:",
     ["Integer-valued on every edge", "Always fractional", "Always zero", "Negative on some edges"], 0, "This is the integrality theorem, used for matching problems."),
    ("Maximum bipartite matching can be solved by:",
     ["Converting it to a maximum-flow problem with unit capacities", "Dijkstra's algorithm", "Topological sorting", "Heap sort"], 0, "Add a source to one side and a sink to the other."),
    ("Kruskal's algorithm is preferred over Prim's when the graph is:",
     ["Sparse, with edges readily available as a list", "Very dense and stored as a matrix", "Unweighted", "A single vertex"], 0, "Sorting E edges is cheap when E is small."),
    ("Consider the statements:\nI. A graph can have more than one MST when weights repeat.\nII. An MST of a graph with n vertices has n − 1 edges.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Consider the statements:\nI. The MST always contains the shortest path between every pair of vertices.\nII. The lightest edge of a graph with distinct weights is always in the MST.\nWhich is/are correct?",
     I_II, 1, "MST and shortest-path trees can differ; the lightest edge is always in the MST."),
    ("Consider the statements:\nI. Ford–Fulkerson always terminates with irrational capacities.\nII. The value of any flow is at most the capacity of any s–t cut.\nWhich is/are correct?",
     I_II, 1, "With irrational capacities it may not terminate; II is weak duality."),
    ("Assertion (A): Kruskal's algorithm produces a minimum spanning tree.\nReason (R): Each edge it adds is a lightest edge crossing some cut.",
     AR, 0, "That is the cut property."),
    ("Assertion (A): Increasing all edge weights by 5 changes the MST.\nReason (R): Every spanning tree has the same number of edges.",
     AR, 3, "Because every tree has n − 1 edges, all totals rise by 5(n − 1) and the MST is unchanged; A is false."),
    ("Assertion (A): Maximum flow equals the minimum cut capacity.\nReason (R): Edmonds–Karp uses DFS to find augmenting paths.",
     AR, 2, "A is true; R is false – Edmonds–Karp uses BFS."),
    ("Assertion (A): Borůvka's algorithm is suitable for parallel computers.\nReason (R): Borůvka published his algorithm in 1926.",
     AR, 1, "Both true, but the date does not explain suitability for parallelism."),
    ("Match the concept with its description:\na. Residual network  b. Augmenting path  c. Min cut  d. Flow conservation\n1. In-flow equals out-flow  2. Smallest-capacity s–t partition  3. s–t path with spare capacity  4. Graph of remaining capacities",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Network-flow vocabulary."),
    ("Match the algorithm with the problem it solves:\na. Prim  b. Edmonds–Karp  c. Kosaraju  d. Floyd–Warshall\n1. All-pairs shortest paths  2. Strongly connected components  3. Maximum flow  4. Minimum spanning tree",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Graph algorithms at a glance."),
]

P_NP = [
    ("The class P consists of decision problems that:",
     ["Can be solved by a deterministic algorithm in polynomial time", "Can be verified but never solved", "Are undecidable", "Need exponential time"], 0, PYQ + "Examples: sorting, shortest paths, MST (as decision problems)."),
    ("The class NP consists of decision problems whose 'yes' answers:",
     ["Can be verified in polynomial time given a certificate", "Can never be verified", "Always need exponential time to verify", "Are always 'no'"], 0, PYQ + "Equivalently, solvable in polynomial time by a nondeterministic machine."),
    ("NP stands for:",
     ["Nondeterministic polynomial time", "Non-polynomial", "Not possible", "Negative polynomial"], 0, "A common misconception is that it means 'non-polynomial'."),
    ("Which relation between P and NP is known to be true?",
     ["P ⊆ NP", "NP ⊆ P, proven", "P = NP, proven", "P and NP are disjoint"], 0, PYQ + "Whether P = NP is still an open question."),
    ("The P versus NP question is one of the Millennium Prize Problems of the:",
     ["Clay Mathematics Institute", "Turing Award committee", "Nobel Foundation", "ACM"], 0, "It carries a prize of US $1 million."),
    ("A certificate for the Hamiltonian-cycle problem is:",
     ["An ordering of the vertices, checked in polynomial time", "The adjacency matrix", "A spanning tree", "The number of edges"], 0, "Checking that consecutive vertices are adjacent and all appear once is easy."),
    ("Which problem is known to be in P?",
     ["2-SAT", "3-SAT", "Hamiltonian cycle", "0/1 knapsack (decision)"], 0, PYQ + "2-SAT is solvable in linear time using implication graphs."),
    ("Which graph problem is known to be solvable in polynomial time?",
     ["Checking whether a graph has an Euler circuit", "Checking whether a graph has a Hamiltonian cycle", "Graph 3-colouring", "Travelling salesman (decision)"], 0, PYQ + "Connected graph with every vertex of even degree – easy to check."),
    ("Primality testing (is n prime?) was shown to be in P in 2002 by:",
     ["Agrawal, Kayal and Saxena (AKS)", "Cook and Levin", "Karp", "Rivest, Shamir and Adleman"], 0, "The AKS test came from IIT Kanpur."),
    ("Linear programming is in P, as first shown by Khachiyan's ellipsoid method (1979). Integer linear programming is:",
     ["NP-hard", "In P", "Undecidable", "Solvable in O(n)"], 0, "Requiring integer solutions makes it much harder."),
    ("Graph 2-colouring is in P. Graph 3-colouring is:",
     ["NP-complete", "In P", "Undecidable", "Solvable by BFS"], 0, "2-colouring is just bipartiteness testing."),
    ("Finding a shortest simple path is in P. Finding a longest simple path is:",
     ["NP-hard", "In P", "Trivial", "Undecidable"], 0, "Longest path generalises the Hamiltonian-path problem."),
    ("The complement class co-NP contains problems whose:",
     ["'No' answers have polynomial-time verifiable certificates", "'Yes' answers can be verified", "Solutions are always yes", "Solutions are undecidable"], 0, "Example: TAUTOLOGY (is a formula true under every assignment?)."),
    ("The halting problem is:",
     ["Undecidable, and therefore not in NP", "In P", "NP-complete", "In co-NP"], 0, PYQ + "It is NP-hard but not in NP, because it cannot be decided at all."),
    ("The 0/1 knapsack problem has an O(nW) algorithm, yet it is NP-complete because:",
     ["O(nW) is exponential in the number of bits needed to write W", "It is not in NP", "O(nW) is truly polynomial", "It is undecidable"], 0, "Such algorithms are called pseudo-polynomial."),
    ("By the time hierarchy theorem, which is proven?",
     ["P ≠ EXPTIME", "P = NP", "NP = EXPTIME", "P = PSPACE"], 0, "P ⊆ NP ⊆ PSPACE ⊆ EXPTIME with at least P ≠ EXPTIME."),
    ("A nondeterministic algorithm can be thought of as working in two stages:",
     ["Guessing a candidate solution and then verifying it deterministically", "Sorting and searching", "Dividing and combining", "Compiling and linking"], 0, "Accepts if some guess verifies."),
    ("The Cobham–Edmonds thesis says that:",
     ["Problems solvable in polynomial time are the feasibly (efficiently) computable ones", "All problems are in P", "NP problems are undecidable", "Exponential algorithms are efficient"], 0, "It identifies 'efficient' with 'polynomial time'."),
    ("Complexity classes such as P and NP are usually defined for:",
     ["Decision problems (yes/no questions)", "Only optimisation problems", "Only sorting", "Only numerical problems"], 0, "Optimisation problems are turned into decision versions with a bound k."),
    ("If P = NP were proved, one important consequence would be that:",
     ["Many public-key cryptosystems based on hard problems could become insecure", "All problems would become undecidable", "Sorting would need exponential time", "No algorithm could be verified"], 0, "Their security assumes certain problems cannot be solved efficiently."),
    ("Sorting, stated as a decision problem, belongs to:",
     ["Both P and NP", "NP but not P", "Neither P nor NP", "co-NP but not NP"], 0, "Every problem in P is also in NP (and in co-NP)."),
    ("Consider the statements:\nI. Every problem in P is also in NP.\nII. It has been proved that P ≠ NP.\nWhich is/are correct?",
     I_II, 0, "P ≠ NP is widely believed but unproven."),
    ("Consider the statements:\nI. Graph 2-colouring is in P.\nII. Euler-circuit testing is in P.\nWhich is/are correct?",
     I_II, 2, "Both are polynomial."),
    ("Consider the statements:\nI. The halting problem is in NP.\nII. The Hamiltonian-cycle problem is known to be in P.\nWhich is/are correct?",
     I_II, 3, "The halting problem is undecidable; Hamiltonian cycle is NP-complete."),
    ("Assertion (A): SAT is in NP.\nReason (R): A satisfying assignment can be checked in polynomial time.",
     AR, 0, "The assignment is the certificate."),
    ("Assertion (A): NP means 'non-polynomial time'.\nReason (R): NP contains every problem in P.",
     AR, 3, "NP means nondeterministic polynomial; A is false, R is true."),
    ("Assertion (A): Primality testing is in P.\nReason (R): Integer factorisation is known to be NP-complete.",
     AR, 2, "A is true (AKS); R is false – factorisation is not known to be NP-complete."),
    ("Assertion (A): Euler-circuit testing is easy.\nReason (R): Euler studied the Königsberg bridges in 1736.",
     AR, 1, "Both true, but R does not explain A; the degree condition does."),
    ("Match the problem with its known status:\na. Sorting  b. SAT  c. Halting problem  d. Graph isomorphism\n1. In NP, not known to be in P or NP-complete  2. Undecidable  3. NP-complete  4. In P",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Graph isomorphism has a quasi-polynomial algorithm (Babai, 2015)."),
    ("Match the easy problem with its hard relative:\na. 2-SAT  b. Euler circuit  c. Shortest path  d. 2-colouring\n1. 3-colouring  2. Longest path  3. Hamiltonian cycle  4. 3-SAT",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Small changes to a problem can move it from P to NP-complete."),
]

NPC = [
    ("A decision problem L is NP-complete if:",
     ["L is in NP and every problem in NP is polynomial-time reducible to L", "L is in P", "L is undecidable", "L can be solved in exponential time"], 0, PYQ + "NP-complete problems are the hardest problems in NP."),
    ("A problem is NP-hard if:",
     ["Every problem in NP reduces to it in polynomial time (it need not be in NP)", "It is in P", "It is in NP and in P", "It has no solution"], 0, PYQ + "NP-complete = NP-hard ∩ NP."),
    ("The first problem proved NP-complete (Cook–Levin theorem, 1971) was:",
     ["Boolean satisfiability (SAT)", "Travelling salesman", "Vertex cover", "Graph colouring"], 0, PYQ + "All other NP-completeness proofs build on it."),
    ("In 1972 Richard Karp showed that how many well-known combinatorial problems are NP-complete?",
     ["21", "7", "100", "3"], 0, "The paper 'Reducibility Among Combinatorial Problems'."),
    ("If A ≤p B (A reduces to B in polynomial time) and B is in P, then:",
     ["A is in P", "B is NP-hard", "A is undecidable", "Nothing can be concluded"], 0, PYQ + "Solve A by transforming it and solving B."),
    ("If A ≤p B and A is NP-hard, then:",
     ["B is NP-hard", "A is in P", "B is in P", "B is undecidable"], 0, PYQ + "B is at least as hard as A – note the direction of the reduction."),
    ("To prove a new problem X is NP-complete, one must show that X is in NP and:",
     ["A known NP-complete problem reduces to X in polynomial time", "X reduces to a problem in P", "X can be solved in exponential time", "X has a DP solution"], 0, PYQ + "Reducing X to a known problem proves nothing about X's hardness."),
    ("If any NP-complete problem is solved in polynomial time, then:",
     ["P = NP", "P ≠ NP", "NP becomes empty", "All problems become undecidable"], 0, PYQ + "Every NP problem reduces to it."),
    ("A set S is an independent set of G if and only if V − S is a:",
     ["Vertex cover", "Clique", "Spanning tree", "Matching"], 0, "No edge has both ends in S ⇔ every edge has an end in V − S."),
    ("A graph has 7 vertices and its largest independent set has 3 vertices. Its smallest vertex cover has:",
     ["4 vertices", "3 vertices", "7 vertices", "10 vertices"], 0, "Minimum vertex cover = n − maximum independent set = 7 − 3."),
    ("S is a clique in G if and only if S is an independent set in:",
     ["The complement of G", "G itself", "A spanning tree of G", "The line graph of G"], 0, "Edges and non-edges swap in the complement."),
    ("The decision version of the travelling salesman problem is NP-complete; the optimisation version is:",
     ["NP-hard", "In P", "Undecidable", "Trivial"], 0, "Optimisation versions are at least as hard as their decision versions."),
    ("In 3-SAT, each clause of the CNF formula contains:",
     ["Exactly 3 literals", "At most 2 literals", "Any number of literals", "Exactly 1 literal"], 0, "3-SAT is NP-complete; SAT reduces to it."),
    ("A formula in conjunctive normal form (CNF) is:",
     ["An AND of clauses, each clause an OR of literals", "An OR of ANDs", "A single literal only", "A formula with no variables"], 0, "(x ∨ ¬y) ∧ (y ∨ z) is in CNF."),
    ("A simple 2-approximation for minimum vertex cover is obtained by:",
     ["Taking both endpoints of the edges of a maximal matching", "Taking all vertices", "Taking a random vertex", "Taking the vertex of largest degree only once"], 0, "Any cover must contain at least one endpoint of each matching edge."),
    ("For metric TSP (triangle inequality holds), Christofides' algorithm gives a tour at most how many times the optimum?",
     ["1.5", "2", "1", "log n"], 0, "It combines an MST with a minimum-weight perfect matching."),
    ("Polynomial-time reducibility is:",
     ["Transitive: if A ≤p B and B ≤p C, then A ≤p C", "Symmetric always", "Undefined for decision problems", "Only for problems in P"], 0, "Composing two polynomial transformations is polynomial."),
    ("If A ≤p B and B is in NP, then:",
     ["A is in NP", "A is NP-complete", "B is in P", "A is undecidable"], 0, "Verify A by transforming it to B."),
    ("Which of the following is NOT NP-complete (assuming P ≠ NP)?",
     ["2-SAT", "3-SAT", "Vertex cover", "Subset sum"], 0, "2-SAT is in P."),
    ("Which problem is NP-complete?",
     ["Subset sum", "Minimum spanning tree", "Shortest path", "Sorting"], 0, "The others are in P."),
    ("A polynomial-time reduction used in NP-completeness proofs must:",
     ["Run in polynomial time and preserve yes/no answers", "Run in exponential time", "Solve the problem directly", "Change yes answers to no"], 0, "x ∈ A ⇔ f(x) ∈ B."),
    ("With respect to NP, the halting problem is best classified as:",
     ["NP-hard but not NP-complete", "NP-complete", "In P", "In NP but not NP-hard"], 0, PYQ + "SAT reduces to it, but it is not in NP."),
    ("Consider the statements:\nI. Every NP-complete problem is NP-hard.\nII. Every NP-hard problem is in NP.\nWhich is/are correct?",
     I_II, 0, "NP-hard problems such as the halting problem lie outside NP."),
    ("Consider the statements:\nI. Vertex cover is NP-complete.\nII. Clique is NP-complete.\nWhich is/are correct?",
     I_II, 2, "Both are among Karp's 21 problems."),
    ("Consider the statements:\nI. If 3-SAT ≤p X, then X is NP-hard.\nII. If X ≤p 3-SAT, then X is NP-hard.\nWhich is/are correct?",
     I_II, 0, "Hardness flows towards the problem being reduced to."),
    ("Assertion (A): If vertex cover is solvable in polynomial time, then P = NP.\nReason (R): Vertex cover is NP-complete.",
     AR, 0, "Every NP problem reduces to an NP-complete one."),
    ("Assertion (A): To show X is NP-hard, it suffices to reduce X to SAT.\nReason (R): SAT is NP-complete.",
     AR, 3, "The reduction must go from SAT to X; A is false, R is true."),
    ("Assertion (A): The optimisation version of TSP is NP-hard.\nReason (R): The optimisation version of TSP is in NP.",
     AR, 2, "A is true; R is false – optimisation problems are not decision problems, so they are not in NP."),
    ("Match the problem with a problem it is commonly reduced from in NP-completeness proofs:\na. 3-SAT  b. Clique  c. Vertex cover  d. Hamiltonian cycle\n1. Vertex cover  2. Independent set  3. 3-SAT  4. SAT",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "The classic chain: SAT → 3-SAT → Clique → Independent set → Vertex cover → Hamiltonian cycle."),
    ("Match the term with its meaning:\na. NP-hard  b. NP-complete  c. Reduction  d. Certificate\n1. Evidence checked by a verifier  2. Transformation between problems  3. In NP and NP-hard  4. At least as hard as every NP problem",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Core complexity vocabulary."),
]

TOPICS = {
    "Graph Algorithms": [("1 · Breadth-First and Depth-First Search", TRAVERSALS),
                         ("2 · Shortest Paths", SHORTEST_PATHS),
                         ("3 · Minimum Spanning Trees and Maximum Flow", MST_FLOW)],
    "Complexity Theory": [("1 · P and NP Classes", P_NP),
                          ("2 · NP-Completeness and Reducibility", NPC)],
}
