"""Paper 2 · Unit 8 · Trees (3 sub-topics × 30).
References: Horowitz, Sahni & Anderson-Freed, Fundamentals of Data Structures in C; Cormen et al.; Weiss, Data Structures and
Algorithm Analysis. Height = number of edges on the longest root-to-leaf path (a single node has height 0); root is at level 0."""
from packlib import AR, I_II

BINARY_TREES = [
    ("A tree with n nodes has exactly how many edges?",
     ["n − 1", "n", "n + 1", "2n"], 0, "Every node except the root has exactly one edge to its parent."),
    ("The maximum number of nodes in a binary tree of height 4 is:",
     ["31", "16", "15", "32"], 0, "2^(h+1) − 1 = 2⁵ − 1 = 31."),
    ("The maximum number of nodes at level 5 of a binary tree (root at level 0) is:",
     ["32", "31", "16", "64"], 0, "Level i can hold at most 2^i nodes."),
    ("The minimum possible height of a binary tree with 100 nodes is:",
     ["6", "7", "5", "99"], 0, "⌈log₂(101)⌉ − 1 = 7 − 1 = 6; a tree of height 5 holds at most 63 nodes."),
    ("A binary tree has 10 nodes with two children each. How many leaves does it have?",
     ["11", "10", "9", "20"], 0, "In any binary tree, n₀ = n₂ + 1."),
    ("A full (strict) binary tree has 15 internal nodes. How many nodes does it have in total?",
     ["31", "30", "16", "29"], 0, "Leaves = internal + 1 = 16; total = 15 + 16 = 31 (2n + 1)."),
    ("In a complete binary tree stored in an array with 1-based indexing, the parent of the node at index 13 is at index:",
     ["6", "7", "12", "26"], 0, "Parent = ⌊i/2⌋; children of i are 2i and 2i + 1."),
    ("A binary tree has root A; A's left child is B with children D (left) and E (right); A's right child is C with only a right child F. Its preorder traversal is:",
     ["A B D E C F", "D B E A C F", "D E B F C A", "A B C D E F"], 0, "Preorder visits root, then left subtree, then right subtree."),
    ("For the same tree (A; B with D, E; C with right child F), the inorder traversal is:",
     ["D B E A C F", "A B D E C F", "D E B F C A", "D B E A F C"], 0, "Inorder: left subtree, root, right subtree."),
    ("For the same tree (A; B with D, E; C with right child F), the postorder traversal is:",
     ["D E B F C A", "D B E F C A", "A B D E C F", "F C E D B A"], 0, "Postorder: left subtree, right subtree, root."),
    ("A binary tree has preorder 1 2 4 5 3 6 7 and inorder 4 2 5 1 6 3 7. Its postorder traversal is:",
     ["4 5 2 6 7 3 1", "4 2 5 6 3 7 1", "7 6 3 5 4 2 1", "4 5 6 7 2 3 1"], 0, "Root 1; left subtree {4, 2, 5} with root 2; right subtree {6, 3, 7} with root 3."),
    ("Which pair of traversals does NOT, in general, uniquely determine a binary tree?",
     ["Preorder and postorder", "Preorder and inorder", "Postorder and inorder", "Level order and inorder"], 0, "Without inorder, a single child cannot be placed as left or right."),
    ("How many structurally different binary trees can be formed with 3 nodes?",
     ["5", "6", "3", "4"], 0, "Catalan number C₃ = 5 (C₄ = 14)."),
    ("In the linked representation of a binary tree with n nodes, how many child pointers are NULL?",
     ["n + 1", "n − 1", "n", "2n"], 0, "2n pointers in all; n − 1 of them point to children."),
    ("A general tree or forest is usually converted into a binary tree using the:",
     ["Left-child, right-sibling representation", "Array representation only", "Adjacency matrix", "Hash table"], 0, "The first child becomes the left child and the next sibling the right child."),
    ("A level-order (breadth-first) traversal of a binary tree is implemented with a:",
     ["Queue", "Stack", "Priority queue", "Hash table"], 0, "Nodes are processed level by level, left to right."),
    ("The extra space used by a recursive inorder traversal of a binary tree of height h is:",
     ["O(h), for the recursion stack", "O(1)", "O(n²)", "O(2ⁿ)"], 0, "O(log n) for a balanced tree and O(n) for a skewed one."),
    ("In the expression tree for (a + b) * c, the postorder traversal gives:",
     ["a b + c *", "* + a b c", "a + b * c", "c a b + *"], 0, "Postorder of an expression tree yields postfix notation; preorder yields prefix."),
    ("A skewed binary tree with n nodes has height:",
     ["n − 1", "log₂ n", "n", "n/2"], 0, "Every node has only one child, forming a chain."),
    ("The height of a complete binary tree with n nodes is:",
     ["⌊log₂ n⌋", "n − 1", "√n", "⌈n/2⌉"], 0, "A complete tree fills every level except possibly the last."),
    ("In a binary tree, the degree of a node is:",
     ["The number of its children", "Its distance from the root", "The number of its ancestors", "The height of its subtree"], 0, "In a binary tree it is 0, 1 or 2."),
    ("Match the traversal with its order:\na. Preorder  b. Inorder  c. Postorder  d. Level order\n1. Level by level, left to right  2. Left, right, root  3. Left, root, right  4. Root, left, right",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "The names describe when the root is visited."),
    ("Consider the statements:\nI. Every full (strict) binary tree has an odd number of nodes.\nII. Every complete binary tree is a full binary tree.\nWhich is/are correct?",
     I_II, 0, "n = 2i + 1 is odd; a complete tree may have a node with one (left) child, so it need not be full."),
    ("Consider the statements:\nI. A tree is a connected graph with no cycles.\nII. Adding one edge to a tree always creates exactly one cycle.\nWhich is/are correct?",
     I_II, 2, "Both are standard properties of trees."),
    ("Assertion (A): In any binary tree, the number of leaves is one more than the number of nodes with two children.\nReason (R): Counting edges gives n − 1 = n₁ + 2n₂, and n = n₀ + n₁ + n₂.",
     AR, 0, "Substituting gives n₀ = n₂ + 1."),
    ("Assertion (A): Preorder and postorder together always determine a unique binary tree.\nReason (R): Inorder traversal shows which nodes lie in the left and right subtrees of each root.",
     AR, 3, "R is true, and that information is missing without inorder, so A is false."),
    ("Assertion (A): Level-order traversal needs a queue.\nReason (R): Inorder traversal of an expression tree gives prefix notation.",
     AR, 2, "A is true; R is false – inorder gives infix notation (preorder gives prefix)."),
    ("Assertion (A): A binary tree with n nodes can be stored in an array of size n if it is complete.\nReason (R): Complete binary trees leave no gaps in level order.",
     AR, 0, "With no gaps, index formulas locate every child and parent."),
    ("The number of edges on the path from the root to a node is called the node's:",
     ["Depth (level)", "Height", "Degree", "Order"], 0, "Height is measured downwards to the deepest leaf."),
    ("Storing a skewed binary tree of height 9 in an array (1-based level-order positions) may need an array of size:",
     ["1023", "10", "512", "100"], 0, "A right-skewed chain occupies positions up to 2^(h+1) − 1 = 1023, wasting most of them."),
]

THREADED_BST = [
    ("In a threaded binary tree, the NULL child pointers are replaced by:",
     ["Pointers (threads) to the inorder predecessor and successor", "Pointers to the root", "Pointers to the parent", "Extra data values"], 0, "Threads allow inorder traversal without a stack or recursion."),
    ("A binary tree with n nodes has how many threads when it is fully (doubly) threaded?",
     ["n + 1", "n − 1", "2n", "n"], 0, "They replace the n + 1 NULL pointers (some implementations point the extreme ones to a header node)."),
    ("In a right-threaded binary tree, the right thread of a node points to its:",
     ["Inorder successor", "Inorder predecessor", "Parent", "Left child"], 0, "Left threads point to inorder predecessors."),
    ("The main advantage of a threaded binary tree is that:",
     ["Inorder traversal can be done without recursion or a stack", "It uses less memory for data", "Insertion needs no pointer changes", "It stays balanced automatically"], 0, "A tag bit per pointer marks whether it is a child link or a thread."),
    ("An inorder traversal of a binary search tree lists the keys in:",
     ["Ascending (sorted) order", "Insertion order", "Descending order always", "Random order"], 0, "Left subtree < root < right subtree at every node."),
    ("The keys 50, 30, 70, 20, 40, 60, 80 are inserted in this order into an empty BST. What is the height of the tree?",
     ["2", "3", "6", "1"], 0, "It forms a perfect tree: 50; 30 and 70; 20, 40, 60, 80."),
    ("The keys 10, 20, 30, 40, 50 are inserted in this order into an empty BST. The tree's height is:",
     ["4", "2", "3", "1"], 0, "Sorted input makes a right-skewed chain."),
    ("Searching for a key in a BST with n nodes takes, in the worst case:",
     ["O(n)", "O(log n)", "O(1)", "O(n log n)"], 0, "A skewed BST behaves like a linked list; a balanced one gives O(log n)."),
    ("The minimum key in a BST is found at:",
     ["The leftmost node, reached by following left pointers from the root", "The root", "The rightmost leaf", "Any leaf"], 0, "The maximum is at the rightmost node."),
    ("To delete a BST node that has two children, it is usually replaced by its:",
     ["Inorder successor (the minimum of its right subtree) or inorder predecessor", "Parent", "Left child always", "Root"], 0, "That keeps the BST ordering intact."),
    ("A BST has preorder 30 20 10 25 40 35 50. Its postorder traversal is:",
     ["10 25 20 35 50 40 30", "10 20 25 30 35 40 50", "30 20 40 10 25 35 50", "10 25 35 50 20 40 30"], 0, "Root 30; left subtree 20 (10, 25); right subtree 40 (35, 50)."),
    ("How many different BSTs can be built from the keys 1, 2, 3?",
     ["5", "6", "3", "1"], 0, "The count is the Catalan number C₃ = 5."),
    ("The inorder successor of a BST node that has a right subtree is:",
     ["The leftmost node of its right subtree", "Its parent", "Its right child always", "The root"], 0, "If there is no right subtree, it is the nearest ancestor of which the node lies in the left subtree."),
    ("Keys 45, 15, 79, 90, 10, 55, 12, 20, 50 are inserted into an empty BST. How many comparisons (key tests) are needed to find 50?",
     ["4", "3", "5", "2"], 0, "50 is compared with 45 → 79 → 55 → 50."),
    ("Deleting a leaf node from a BST requires:",
     ["Only setting its parent's pointer to NULL", "Rebuilding the whole tree", "Finding its inorder successor", "Rotating the tree"], 0, "Leaves have no subtrees to reattach."),
    ("Which sequence of keys, inserted in order, gives the most balanced BST for 1–7?",
     ["4, 2, 6, 1, 3, 5, 7", "1, 2, 3, 4, 5, 6, 7", "7, 6, 5, 4, 3, 2, 1", "1, 7, 2, 6, 3, 5, 4"], 0, "Inserting the median first at each level builds a perfect tree of height 2."),
    ("The average-case time for search, insert and delete in a BST built from random keys is:",
     ["O(log n)", "O(n)", "O(1)", "O(n²)"], 0, "Random insertion orders give an expected height of O(log n)."),
    ("Match the operation with where it looks in a BST:\na. Find minimum  b. Find maximum  c. Inorder successor of a node with a right subtree  d. Sorted listing\n1. Inorder traversal  2. Leftmost node of the right subtree  3. Rightmost node  4. Leftmost node",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "All follow from the BST ordering property."),
    ("Consider the statements:\nI. In a BST, every key in a node's left subtree is smaller than the node's key.\nII. A BST never needs more than O(log n) time for a search.\nWhich is/are correct?",
     I_II, 0, "An unbalanced (skewed) BST needs O(n) time."),
    ("Consider the statements:\nI. A threaded binary tree needs a flag with each pointer to tell a thread from a child link.\nII. Threads make inorder traversal possible in O(n) time without extra stack space.\nWhich is/are correct?",
     I_II, 2, "Both statements are correct."),
    ("Assertion (A): Inserting keys into a BST in sorted order gives a skewed tree.\nReason (R): Each new key is larger than all earlier keys, so it always goes to the rightmost position.",
     AR, 0, "That produces a chain of right children."),
    ("Assertion (A): Inorder traversal of a BST gives the keys in descending order.\nReason (R): In a BST, keys in the left subtree are smaller than the root.",
     AR, 3, "Because left keys are smaller, inorder is ascending; A is false."),
    ("Assertion (A): Deleting a BST node with two children can be done by copying its inorder successor into it.\nReason (R): The inorder successor of such a node has at most one child.",
     AR, 1, "Both true; the reason A works is that the successor keeps the ordering; R explains why deleting the successor afterwards is easy."),
    ("Assertion (A): Threaded binary trees remove the need for a stack in inorder traversal.\nReason (R): Threaded binary trees are always height-balanced.",
     AR, 2, "A is true; R is false – threading says nothing about balance."),
    ("The maximum number of comparisons needed to search a BST of height h is:",
     ["h + 1", "h", "2h", "log h"], 0, "One comparison per level along the longest path."),
    ("Which of these binary search trees would give the WORST search time?",
     ["One built by inserting 1, 2, 3, 4, 5, 6, 7 in order", "One built by inserting 4, 2, 6, 1, 3, 5, 7", "A perfect BST of 7 nodes", "One built by inserting 4, 6, 2, 5, 7, 1, 3"], 0, "Sorted insertion creates height 6 instead of 2."),
    ("In a BST, the key 50 is searched for along the path 60 → 30 → 45 → 55 → 50. Which statement is correct?",
     ["It is a valid BST search path", "It is invalid because 55 > 50", "It is invalid because 45 < 50", "It is invalid because 30 < 60"], 0, "60 (go left), 30 (right), 45 (right), 55 (left), 50: every step is consistent with the key 50."),
    ("The left child of a node x in a BST has the key 40 and the right child has the key 70. Which key can x have?",
     ["55", "35", "75", "40"], 0, "x must be greater than every key in its left subtree and smaller than every key in its right subtree."),
    ("A BST is used to store a dictionary where many insertions arrive in sorted order. The best fix is to:",
     ["Use a self-balancing tree such as an AVL tree", "Use a threaded tree", "Store the keys in a stack", "Use postorder insertion"], 0, "Self-balancing trees keep the height O(log n)."),
    ("In a threaded tree, the leftmost node's left thread and the rightmost node's right thread usually point to:",
     ["A header (dummy) node", "Themselves", "The root's parent", "NULL, which is not allowed"], 0, "The header node closes the thread chain."),
]

AVL = [
    ("The balance factor of a node in an AVL tree is defined as:",
     ["Height of the left subtree − height of the right subtree", "Number of left children − number of right children", "Depth of the node", "Number of nodes in the subtree"], 0, "It must be −1, 0 or +1 at every node."),
    ("An AVL tree is named after:",
     ["Adelson-Velsky and Landis", "Aho, Viterbi and Lamport", "Ackermann, Von Neumann and Lovelace", "Adleman, Vazirani and Lee"], 0, "They introduced it in 1962; it was the first self-balancing BST."),
    ("Inserting into the left subtree of a node's left child makes the node unbalanced (LL case). The fix is:",
     ["A single right rotation", "A single left rotation", "A left-right double rotation", "No rotation"], 0, "The RR case is fixed by a single left rotation."),
    ("The LR case (insertion into the right subtree of the left child) is fixed by:",
     ["A left rotation at the left child followed by a right rotation at the unbalanced node", "A single right rotation", "A single left rotation", "Deleting the node"], 0, "The RL case is the mirror image: right rotation, then left rotation."),
    ("10, 20 and 30 are inserted in this order into an empty AVL tree. The root of the final tree is:",
     ["20", "10", "30", "The tree has no single root"], 0, "RR imbalance at 10 is fixed by a left rotation, making 20 the root."),
    ("30, 10 and 20 are inserted in this order into an empty AVL tree. Which rotation is needed?",
     ["LR (double) rotation", "LL (single right) rotation", "RR (single left) rotation", "RL (double) rotation"], 0, "20 goes into the right subtree of 30's left child 10; the result has 20 at the root."),
    ("The keys 1, 2, 3, 4, 5, 6, 7 are inserted in this order into an empty AVL tree. The root of the final tree is:",
     ["4", "2", "1", "7"], 0, "The rotations produce the perfect tree 4 (2 (1, 3), 6 (5, 7))."),
    ("The height of the AVL tree formed by inserting 1 to 7 in order is:",
     ["2", "6", "3", "4"], 0, "Compare this with a plain BST, whose height would be 6."),
    ("The minimum number of nodes in an AVL tree of height 3 is:",
     ["7", "8", "15", "5"], 0, "N(h) = N(h−1) + N(h−2) + 1 with N(0) = 1, N(1) = 2: N(2) = 4, N(3) = 7."),
    ("The minimum number of nodes in an AVL tree of height 4 is:",
     ["12", "16", "31", "10"], 0, "N(4) = N(3) + N(2) + 1 = 7 + 4 + 1 = 12."),
    ("Search, insertion and deletion in an AVL tree of n nodes take:",
     ["O(log n) time in the worst case", "O(n) time in the worst case", "O(1) time", "O(n log n) time"], 0, "Its height is always O(log n) (at most about 1.44 log₂ n)."),
    ("After an insertion into an AVL tree, how many rotations (single or double) are needed at most to restore balance?",
     ["One (single or double) rotation", "O(log n) rotations", "n rotations", "None ever"], 0, "Fixing the lowest unbalanced ancestor restores its original height; deletions may need O(log n) rotations."),
    ("A node has a left subtree of height 3 and a right subtree of height 1. Its balance factor and status are:",
     ["+2, unbalanced", "+2, balanced", "−2, unbalanced", "+1, balanced"], 0, "3 − 1 = 2, which is outside −1..+1."),
    ("Compared with a red–black tree, an AVL tree is:",
     ["More strictly balanced, giving faster lookups but possibly more rotations on updates", "Less balanced than a red–black tree", "Not a binary search tree", "Unable to support deletion"], 0, "Red–black trees allow heights up to 2 log₂(n + 1)."),
    ("A single left rotation at node x (with right child y) makes:",
     ["y the new root of the subtree, x its left child, and y's old left subtree x's right subtree", "x the right child of y", "y the left child of x", "No change in the inorder sequence and no change in shape"], 0, "Rotations preserve the inorder (BST) order."),
    ("Match the imbalance case with its fix:\na. LL  b. RR  c. LR  d. RL\n1. Right rotation of the right child, then left rotation  2. Left rotation of the left child, then right rotation  3. Single left rotation  4. Single right rotation",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "The case names describe the path from the unbalanced node to the new node."),
    ("50, 40 and 30 are inserted in this order into an empty AVL tree. After rebalancing, the preorder traversal is:",
     ["40 30 50", "50 40 30", "30 40 50", "40 50 30"], 0, "An LL imbalance at 50 is fixed by a right rotation, making 40 the root."),
    ("An AVL tree has 20 nodes. Its height can be at most:",
     ["5", "4", "19", "10"], 0, "The minimum node counts are N(4) = 12 and N(5) = 20, so 20 nodes can reach height 5 but not 6 (N(6) = 33)."),
    ("Consider the statements:\nI. Every AVL tree is a binary search tree.\nII. Every binary search tree is an AVL tree.\nWhich is/are correct?",
     I_II, 0, "Only BSTs whose nodes all have balance factors −1, 0 or +1 are AVL trees."),
    ("Consider the statements:\nI. Rotations in an AVL tree preserve the inorder sequence of keys.\nII. After an insertion, only nodes on the path from the new node to the root can become unbalanced.\nWhich is/are correct?",
     I_II, 2, "Only heights along the insertion path change, and rotations keep the BST order."),
    ("Assertion (A): Searching an AVL tree takes O(log n) time even in the worst case.\nReason (R): An AVL tree's height is always O(log n).",
     AR, 0, "The search cost is bounded by the height."),
    ("Assertion (A): Inserting keys in sorted order makes an AVL tree skewed.\nReason (R): AVL trees rebalance themselves using rotations after insertions.",
     AR, 3, "Rotations keep it balanced, so it cannot become skewed; R shows why A is false."),
    ("Assertion (A): AVL trees need extra information in each node.\nReason (R): AVL trees are named after Adelson-Velsky and Landis.",
     AR, 1, "Both true; the extra field (height or balance factor) is needed to detect imbalance, not because of the name."),
    ("Assertion (A): A double rotation is needed for the LR case.\nReason (R): A single right rotation always fixes every AVL imbalance.",
     AR, 2, "A is true; R is false – single rotations fix only the LL and RR cases."),
    ("Into the AVL tree 20 (10, 30), the key 25 is inserted and then 27. Which is the LOWEST node that becomes unbalanced (the one that is fixed)?",
     ["30", "20", "25", "10"], 0, "After 27, node 30 has left height 1 (25 → 27) and right height −1: balance factor +2 (an LR case). 20 is also out of balance, but fixing 30 repairs it."),
    ("In the same situation (AVL tree 20 (10, 30), then 25 and 27 inserted), after rebalancing the right subtree of 20 is rooted at:",
     ["27", "25", "30", "20"], 0, "The LR case at 30 gives 27 (25, 30)."),
    ("A red–black tree and an AVL tree both guarantee:",
     ["O(log n) search, insertion and deletion", "O(1) search", "Exactly the same shape for the same keys", "No rotations"], 0, "They differ in how strictly they balance."),
    ("The balance factor stored in an AVL node can take how many different legal values?",
     ["3", "2", "5", "Any integer"], 0, "−1, 0 and +1."),
    ("AVL trees are preferred over plain BSTs mainly when:",
     ["Lookups are frequent and the keys may arrive in sorted or nearly sorted order", "The tree never changes and has only one node", "Keys are always random", "Memory for one extra field is unavailable"], 0, "Balancing prevents the O(n) worst case."),
    ("Deleting a key from an AVL tree may require:",
     ["Rotations at several ancestors, up to O(log n) of them", "No rotations ever", "Rebuilding the whole tree", "Exactly one double rotation always"], 0, "Unlike insertion, a rotation after deletion can reduce the subtree's height and unbalance a higher ancestor."),
]

TOPICS = {
    "Trees": [("1 · Trees, Forests and Binary Trees", BINARY_TREES),
              ("2 · Threaded Binary Trees and Binary Search Trees", THREADED_BST),
              ("3 · AVL Trees", AVL)],
}
