"""Paper 2 · Unit 8 · Design Techniques – Divide & Conquer, Greedy; DP, Backtracking, Branch & Bound (4 sub-topics × 30).
References: Cormen et al., Introduction to Algorithms (CLRS); Horowitz, Sahni & Rajasekaran, Fundamentals of Computer Algorithms;
Levitin, Introduction to the Design and Analysis of Algorithms. Explanations starting "PYQ pattern" follow questions that recur in UGC-NET CS / GATE / KEA papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (UGC-NET / GATE / KEA). "

DIVIDE_CONQUER = [
    ("The three steps of the divide-and-conquer strategy are:",
     ["Divide, conquer (solve subproblems recursively) and combine", "Guess, check and repeat", "Sort, search and merge only", "Select, reject and bound"], 0, PYQ + "Merge sort is the textbook example."),
    ("Which of the following algorithms does NOT use divide and conquer?",
     ["Prim's minimum spanning tree algorithm", "Merge sort", "Quick sort", "Strassen's matrix multiplication"], 0, PYQ + "Prim's algorithm is greedy."),
    ("In merge sort the real work is in the combine step, while in quick sort the real work is in the:",
     ["Divide (partition) step", "Combine step", "Base case", "Recursion depth"], 0, "Quick sort needs no combine step once the parts are sorted in place."),
    ("Ordinary multiplication of two n × n matrices takes:",
     ["Θ(n³) time", "Θ(n²) time", "Θ(n^2.81) time", "Θ(n log n) time"], 0, "n² entries, each a sum of n products."),
    ("Strassen's algorithm multiplies two 2 × 2 (block) matrices using how many multiplications?",
     ["7", "8", "6", "4"], 0, PYQ + "It trades one multiplication for extra additions, giving Θ(n^2.81)."),
    ("Applying Strassen's method recursively down to 1 × 1 blocks, how many scalar multiplications are needed for two 4 × 4 matrices?",
     ["49", "64", "56", "16"], 0, "7 multiplications of 2 × 2 blocks, each using 7: 7 × 7 = 49 (ordinary method: 4³ = 64)."),
    ("Karatsuba's algorithm multiplies two n-digit numbers using how many half-size multiplications?",
     ["3", "4", "2", "7"], 0, "This gives Θ(n^(log₂3)) ≈ Θ(n^1.585)."),
    ("Finding both the maximum and the minimum of n elements by divide and conquer needs how many comparisons (n a power of 2)?",
     ["3n/2 − 2", "2n − 2", "n − 1", "n log n"], 0, PYQ + "The recurrence is T(n) = 2T(n/2) + 2, T(2) = 1."),
    ("Using the divide-and-conquer max–min algorithm, how many comparisons are needed for 8 elements?",
     ["10", "14", "7", "12"], 0, "3 × 8 / 2 − 2 = 10 (the naive method uses 2 × 8 − 2 = 14)."),
    ("Computing xⁿ by repeated squaring (xⁿ = (x^(n/2))²) needs:",
     ["O(log n) multiplications", "O(n) multiplications", "O(n²) multiplications", "O(1) multiplications"], 0, "Each step halves the exponent."),
    ("How many multiplications does repeated squaring need to compute a¹⁶?",
     ["4", "15", "8", "16"], 0, "a² , a⁴, a⁸, a¹⁶."),
    ("The closest pair of points among n points in a plane can be found by divide and conquer in:",
     ["O(n log n) time", "O(n²) time only", "O(n) time", "O(log n) time"], 0, "The brute-force method checks all pairs in O(n²)."),
    ("The number of inversions in an array can be counted in O(n log n) time using a modified:",
     ["Merge sort", "Bubble sort", "Linear search", "Heap insertion"], 0, "Inversions between halves are counted during merging."),
    ("Binary search is sometimes called 'decrease and conquer' because:",
     ["It reduces the problem to only one subproblem of half the size", "It uses no comparisons", "It solves both halves", "It needs dynamic programming"], 0, "Only one half is searched further."),
    ("The key difference between divide and conquer and dynamic programming is that in divide and conquer the subproblems are:",
     ["Independent (not overlapping)", "Always overlapping", "Solved greedily", "Never recursive"], 0, PYQ + "When subproblems overlap, DP stores their solutions to avoid recomputation."),
    ("The maximum-subarray problem can be solved by divide and conquer in O(n log n); Kadane's algorithm solves it in:",
     ["O(n)", "O(n²)", "O(log n)", "O(n³)"], 0, "Kadane's algorithm is a simple dynamic-programming scan."),
    ("The median-of-medians (BFPRT) selection algorithm finds the k-th smallest element in:",
     ["O(n) worst-case time", "O(n log n) average only", "O(n²) worst-case time", "O(log n) time"], 0, "It guarantees a good pivot by recursively taking medians of groups of 5."),
    ("Quickselect (quick-sort-style selection) finds the k-th smallest element in:",
     ["O(n) expected time", "O(log n) time", "O(n log n) worst-case time", "O(1) time"], 0, "It recurses into only one partition; its worst case is O(n²)."),
    ("How many merge operations does merge sort perform on 8 elements?",
     ["7", "8", "3", "24"], 0, "The recursion tree has n − 1 = 7 internal nodes, one merge each."),
    ("The Fast Fourier Transform multiplies two polynomials of degree n in:",
     ["O(n log n) time", "O(n²) time", "O(n³) time", "O(n) time"], 0, "It is a divide-and-conquer evaluation at roots of unity."),
    ("Divide-and-conquer algorithms are well suited to parallel computers because:",
     ["Independent subproblems can be solved at the same time on different processors", "They never use recursion", "They need no memory", "They always run in O(1)"], 0, "Merge sort and quick sort parallelise naturally."),
    ("Consider the statements:\nI. Quick sort and merge sort are both divide-and-conquer algorithms.\nII. Kruskal's algorithm is a divide-and-conquer algorithm.\nWhich is/are correct?",
     I_II, 0, "Kruskal's algorithm is greedy."),
    ("Consider the statements:\nI. Strassen's algorithm is asymptotically faster than the ordinary method.\nII. Strassen's algorithm is always faster in practice for small matrices.\nWhich is/are correct?",
     I_II, 0, "Extra additions and overheads make it slower for small n."),
    ("Consider the statements:\nI. Divide and conquer usually leads to recursive algorithms.\nII. Their running time is often described by recurrence relations.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Merge sort is a divide-and-conquer algorithm.\nReason (R): It splits the array into halves, sorts them recursively and merges the results.",
     AR, 0, "Divide, conquer, combine."),
    ("Assertion (A): Divide and conquer is efficient for computing Fibonacci numbers recursively.\nReason (R): The recursive Fibonacci subproblems overlap heavily.",
     AR, 3, "Because subproblems overlap, plain recursion is exponential; A is false and R is true."),
    ("Assertion (A): Binary search takes O(log n) time.\nReason (R): Binary search solves both halves of the array recursively.",
     AR, 2, "A is true; R is false – only one half is searched."),
    ("Assertion (A): Karatsuba multiplication is faster than school multiplication for large numbers.\nReason (R): The FFT can multiply polynomials in O(n log n).",
     AR, 1, "Both true, but R does not explain A; A is explained by using 3 instead of 4 half-size multiplications."),
    ("Match the problem with its divide-and-conquer complexity:\na. Merge sort  b. Binary search  c. Strassen multiplication  d. Karatsuba multiplication\n1. Θ(n^1.585)  2. Θ(n^2.81)  3. Θ(log n)  4. Θ(n log n)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "All follow from the master theorem."),
    ("Match the algorithm with its design technique:\na. Merge sort  b. Kruskal's MST  c. Floyd–Warshall  d. N-Queens\n1. Backtracking  2. Dynamic programming  3. Greedy  4. Divide and conquer",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "A common matching question."),
]

GREEDY = [
    ("A greedy algorithm:",
     ["Makes the locally best choice at each step, hoping to reach a global optimum", "Tries all possible solutions", "Always uses recursion with memoisation", "Solves subproblems independently and combines them"], 0, PYQ + "It never reconsiders a choice once made."),
    ("A greedy algorithm gives an optimal solution when the problem has:",
     ["The greedy-choice property and optimal substructure", "Overlapping subproblems only", "No constraints", "Exponentially many solutions"], 0, "Both properties are needed for correctness."),
    ("Fractional knapsack: capacity 50; items (value, weight) = (60, 10), (100, 20), (120, 30). The maximum value is:",
     ["240", "220", "180", "160"], 0, PYQ + "Ratios 6, 5, 4: take items 1 and 2 (160, weight 30), then 20/30 of item 3 (80). Total 240."),
    ("For the same items as 0/1 knapsack (capacity 50; (60, 10), (100, 20), (120, 30)), the optimal value is 220. Greedy by value/weight ratio gives:",
     ["160", "220", "240", "180"], 0, "Greedy takes items 1 and 2 (160) and item 3 no longer fits; the optimum is items 2 and 3. Greedy fails for 0/1 knapsack."),
    ("The fractional knapsack problem is solved optimally by taking items in decreasing order of:",
     ["Value per unit weight", "Weight", "Value", "Item number"], 0, "Sorting makes it O(n log n)."),
    ("In the activity-selection problem, the greedy rule that gives an optimal solution is to pick the activity with the:",
     ["Earliest finish time", "Earliest start time", "Shortest duration", "Latest start time only"], 0, PYQ + "It leaves the most room for the remaining activities."),
    ("Activities (start, finish): (1,4), (3,5), (0,6), (5,7), (3,9), (5,9), (6,10), (8,11), (8,12), (2,14), (12,16). The maximum number of non-overlapping activities is:",
     ["4", "3", "5", "6"], 0, "Greedy by finish time picks (1,4), (5,7), (8,11), (12,16)."),
    ("Jobs (profit, deadline): J1 (100, 2), J2 (19, 1), J3 (27, 2), J4 (25, 1), J5 (15, 3); each job takes one unit of time. The maximum profit is:",
     ["142", "152", "127", "144"], 0, PYQ + "Take jobs by profit: J1 → slot 2, J3 → slot 1, J4 and J2 have no free slot, J5 → slot 3. 100 + 27 + 15 = 142."),
    ("Huffman coding builds an optimal prefix code by repeatedly:",
     ["Merging the two least frequent symbols (trees)", "Merging the two most frequent symbols", "Assigning equal-length codes", "Sorting symbols alphabetically"], 0, PYQ + "A min-priority queue gives O(n log n) time."),
    ("Frequencies: a 5, b 9, c 12, d 13, e 16, f 45. In the Huffman code, the length of the codeword for f is:",
     ["1 bit", "2 bits", "3 bits", "4 bits"], 0, "Merges: a + b = 14, c + d = 25, 14 + e = 30, 25 + 30 = 55, then f + 55 = 100, so f hangs directly from the root."),
    ("With the same frequencies (a 5, b 9, c 12, d 13, e 16, f 45), the codeword for a has length:",
     ["4 bits", "3 bits", "2 bits", "5 bits"], 0, "a and b merge first (14), then with e (30), then with the c–d subtree (55) → a is at depth 4."),
    ("A prefix code means that:",
     ["No codeword is a prefix of another codeword", "All codewords have the same length", "Every codeword starts with 0", "Codes are assigned alphabetically"], 0, "This makes decoding unambiguous without separators."),
    ("Using coins {1, 3, 4}, greedy change-making for 6 gives 4 + 1 + 1 (3 coins). The optimal number of coins is:",
     ["2", "3", "1", "4"], 0, "3 + 3; greedy is not optimal for every coin system."),
    ("Optimal merge pattern: files of sizes 20, 30 and 10 are merged two at a time. The minimum total merge cost is:",
     ["90", "110", "100", "60"], 0, "Merge 10 + 20 = 30 (cost 30), then 30 + 30 = 60 (cost 60): total 90."),
    ("Kruskal's algorithm runs in:",
     ["O(E log E) time", "O(V³) time", "O(E²) time", "O(V + E) time"], 0, PYQ + "Sorting the edges dominates; union–find handles cycle checks."),
    ("Prim's algorithm with a binary heap runs in:",
     ["O(E log V) time", "O(V³) time", "O(E²) time", "O(log V) time"], 0, "With an adjacency matrix and no heap it is O(V²)."),
    ("Dijkstra's shortest-path algorithm may give wrong answers when the graph has:",
     ["Negative edge weights", "Only positive weights", "Cycles with positive weights", "More than 100 vertices"], 0, PYQ + "Bellman–Ford handles negative edges."),
    ("A minimum spanning tree of a connected graph with n vertices has:",
     ["n − 1 edges", "n edges", "n(n − 1)/2 edges", "2n − 1 edges"], 0, "Every spanning tree has n − 1 edges."),
    ("A triangle has edges of weight 1, 2 and 3. The weight of its minimum spanning tree is:",
     ["3", "6", "5", "1"], 0, "Take the edges 1 and 2."),
    ("Which problem is NOT solved optimally by a greedy method in general?",
     ["0/1 knapsack", "Fractional knapsack", "Activity selection", "Minimum spanning tree"], 0, "0/1 knapsack needs dynamic programming or branch and bound."),
    ("The main difference between Prim's and Kruskal's algorithms is that:",
     ["Prim's grows a single tree from a start vertex, while Kruskal's adds the cheapest edges and may keep a forest", "Prim's handles only directed graphs", "Kruskal's needs a start vertex", "Prim's sorts all edges first"], 0, "Both give a minimum spanning tree."),
    ("Consider the statements:\nI. Greedy algorithms always find optimal solutions.\nII. Dijkstra's algorithm is a greedy algorithm.\nWhich is/are correct?",
     I_II, 1, "Greedy methods are optimal only for problems with the greedy-choice property."),
    ("Consider the statements:\nI. Huffman coding is a greedy algorithm.\nII. Huffman codes are prefix codes.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Greedy selection by earliest finish time solves activity selection optimally.\nReason (R): Choosing the earliest finishing activity leaves the maximum time for the remaining activities.",
     AR, 0, "This exchange argument proves optimality."),
    ("Assertion (A): Greedy by value/weight ratio is optimal for the 0/1 knapsack problem.\nReason (R): In 0/1 knapsack an item cannot be split.",
     AR, 3, "Because items cannot be split, the greedy choice can leave capacity unused; A is false."),
    ("Assertion (A): Kruskal's algorithm uses a disjoint-set structure.\nReason (R): Kruskal's algorithm processes vertices in order of their degree.",
     AR, 2, "A is true; R is false – it processes edges in order of weight."),
    ("Assertion (A): Dijkstra's algorithm fails with negative edge weights.\nReason (R): Dijkstra's algorithm was published in 1959.",
     AR, 1, "Both true, but the date does not explain A; A is explained by finalised vertices never being revisited."),
    ("Match the greedy algorithm with its problem:\na. Kruskal  b. Dijkstra  c. Huffman  d. Earliest finish time\n1. Activity selection  2. Optimal prefix codes  3. Single-source shortest paths  4. Minimum spanning tree",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "All are greedy."),
    ("Match the algorithm with its time complexity:\na. Kruskal  b. Prim (binary heap)  c. Huffman  d. Fractional knapsack\n1. O(n log n) for n items  2. O(n log n) for n symbols  3. O(E log V)  4. O(E log E)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Sorting or a priority queue dominates each."),
    ("Greedy change-making with Indian coins and notes (1, 2, 5, 10, 20, 50, 100 …) for ₹88 uses how many pieces?",
     ["6", "5", "7", "4"], 0, "50 + 20 + 10 + 5 + 2 + 1 = 88; greedy is optimal for this currency system."),
]

DP = [
    ("A problem is suitable for dynamic programming when it has:",
     ["Optimal substructure and overlapping subproblems", "Only independent subproblems", "The greedy-choice property only", "No recursive structure"], 0, PYQ + "Solutions to repeated subproblems are stored and reused."),
    ("Memoisation is:",
     ["Top-down DP: recursion that stores results of subproblems in a table", "Bottom-up filling of a table", "A greedy technique", "A sorting method"], 0, "Tabulation is the bottom-up form."),
    ("The 'principle of optimality', the basis of dynamic programming, was stated by:",
     ["Richard Bellman", "Edsger Dijkstra", "Donald Knuth", "Alan Turing"], 0, PYQ + "An optimal policy has optimal sub-policies."),
    ("Computing the n-th Fibonacci number with dynamic programming takes:",
     ["O(n) time", "O(2ⁿ) time", "O(n²) time", "O(log n) time"], 0, "Each value is computed once from the previous two."),
    ("The DP solution of the 0/1 knapsack problem with n items and capacity W runs in:",
     ["O(nW) time – pseudo-polynomial", "O(n log n) time", "O(2ⁿ) time always", "O(n) time"], 0, PYQ + "It is polynomial in the numeric value W, not in the number of bits of W."),
    ("0/1 knapsack: capacity 5; items (weight, value) = (2, 3), (3, 4), (4, 5), (5, 6). The maximum value is:",
     ["7", "6", "8", "9"], 0, "Items 1 and 2: weight 5, value 7."),
    ("The length of the longest common subsequence of 'ABCBDAB' and 'BDCABA' is:",
     ["4", "3", "5", "6"], 0, PYQ + "For example 'BCBA' (CLRS example)."),
    ("The DP algorithm for LCS of strings of lengths m and n takes:",
     ["O(mn) time", "O(m + n) time", "O(2^(m+n)) time", "O(m log n) time"], 0, "It fills an (m + 1) × (n + 1) table."),
    ("Matrices A₁ (10 × 100), A₂ (100 × 5), A₃ (5 × 50). The minimum number of scalar multiplications to compute A₁A₂A₃ is:",
     ["7,500", "75,000", "25,000", "5,000"], 0, PYQ + "(A₁A₂)A₃ = 10·100·5 + 10·5·50 = 5,000 + 2,500 = 7,500; A₁(A₂A₃) = 75,000."),
    ("The number of ways to fully parenthesise a product of 4 matrices is:",
     ["5", "4", "6", "3"], 0, "The Catalan number C₃ = 5."),
    ("The matrix-chain multiplication DP algorithm for n matrices runs in:",
     ["O(n³) time", "O(n²) time", "O(2ⁿ) time", "O(n log n) time"], 0, "O(n²) subproblems, each trying O(n) split points."),
    ("The Floyd–Warshall algorithm finds all-pairs shortest paths in:",
     ["Θ(V³) time", "Θ(E log V) time", "Θ(V + E) time", "Θ(V²) time"], 0, PYQ + "It is a DP over allowed intermediate vertices."),
    ("The Bellman–Ford algorithm runs in O(VE) time and, unlike Dijkstra's algorithm, can:",
     ["Handle negative edge weights and detect negative cycles", "Work only on trees", "Run in O(V) time", "Handle only unweighted graphs"], 0, "It relaxes all edges V − 1 times."),
    ("The edit (Levenshtein) distance between 'kitten' and 'sitting' is:",
     ["3", "2", "4", "5"], 0, "k→s, e→i, insert g."),
    ("How many ways can the amount 4 be made from coins {1, 2, 3} (order does not matter)?",
     ["4", "3", "5", "7"], 0, "1+1+1+1, 1+1+2, 2+2, 1+3."),
    ("The length of the longest increasing subsequence of [10, 9, 2, 5, 3, 7, 101, 18] is:",
     ["4", "3", "5", "6"], 0, "For example 2, 3, 7, 18."),
    ("Rod cutting: prices for lengths 1, 2, 3, 4 are 1, 5, 8, 9. The best revenue for a rod of length 4 is:",
     ["10", "9", "8", "11"], 0, "Cut into 2 + 2: 5 + 5 = 10 (CLRS example)."),
    ("The Held–Karp dynamic-programming algorithm for the travelling salesman problem takes:",
     ["O(n² 2ⁿ) time", "O(n!) time", "O(n³) time", "O(n log n) time"], 0, "Much better than n!, but still exponential."),
    ("The optimal binary search tree problem for n keys is solved by DP in:",
     ["O(n³) time (O(n²) with Knuth's improvement)", "O(n) time", "O(log n) time", "O(2ⁿ) time only"], 0, "It minimises the expected search cost."),
    ("Computing C(5, 2) with Pascal's rule C(n, k) = C(n − 1, k − 1) + C(n − 1, k) gives:",
     ["10", "20", "5", "15"], 0, "A classic small DP table."),
    ("A multistage graph shortest-path problem is typically solved using:",
     ["Dynamic programming (forward or backward approach)", "Backtracking only", "Binary search", "Hashing"], 0, "Horowitz–Sahni treat it as a DP example."),
    ("Consider the statements:\nI. Dynamic programming stores solutions of subproblems to avoid recomputation.\nII. Dynamic programming always uses less memory than plain recursion.\nWhich is/are correct?",
     I_II, 0, "DP usually trades extra memory (the table) for time."),
    ("Consider the statements:\nI. Floyd–Warshall is a dynamic-programming algorithm.\nII. Bellman–Ford is a dynamic-programming algorithm.\nWhich is/are correct?",
     I_II, 2, "Both build solutions from smaller subproblems."),
    ("Assertion (A): DP computes the n-th Fibonacci number in linear time.\nReason (R): Each subproblem is solved once and its result reused.",
     AR, 0, "Plain recursion recomputes subproblems exponentially many times."),
    ("Assertion (A): The 0/1 knapsack DP algorithm runs in polynomial time in the input size.\nReason (R): Its running time is O(nW).",
     AR, 3, "O(nW) is exponential in the number of bits of W – pseudo-polynomial; A is false."),
    ("Assertion (A): Matrix-chain order affects the number of multiplications.\nReason (R): Matrix multiplication is commutative.",
     AR, 2, "A is true; R is false – matrix multiplication is associative but not commutative."),
    ("Assertion (A): LCS can be solved using dynamic programming.\nReason (R): LCS is used in the Unix diff utility.",
     AR, 1, "Both true, but the use in diff does not explain why DP applies."),
    ("Match the problem with its DP time complexity:\na. LCS (lengths m, n)  b. 0/1 knapsack  c. Matrix chain  d. Floyd–Warshall\n1. O(V³)  2. O(n³)  3. O(nW)  4. O(mn)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Standard DP complexities."),
    ("Match the term with its meaning:\na. Memoisation  b. Tabulation  c. Optimal substructure  d. Overlapping subproblems\n1. The same subproblems recur many times  2. An optimal solution contains optimal solutions to subproblems  3. Bottom-up table filling  4. Top-down with caching",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Core DP vocabulary."),
    ("Subset sum (is there a subset of n numbers adding to S?) can be solved by DP in:",
     ["O(nS) time", "O(n log n) time", "O(n) time", "O(S) time"], 0, "Also pseudo-polynomial; the problem is NP-complete."),
]

BACKTRACK_BB = [
    ("Backtracking builds a solution step by step and:",
     ["Abandons a partial solution as soon as it cannot lead to a valid solution", "Always tries every complete solution without pruning", "Uses only greedy choices", "Solves subproblems bottom-up"], 0, PYQ + "Abandoning hopeless branches is called pruning."),
    ("The tree of all choices explored by backtracking is called the:",
     ["State-space tree", "Parse tree", "Heap", "B-tree"], 0, "Each node is a partial solution."),
    ("Backtracking explores the state-space tree in:",
     ["Depth-first order", "Breadth-first order only", "Random order", "Order of increasing cost only"], 0, "Branch and bound commonly uses BFS or least-cost order."),
    ("How many distinct solutions does the 4-Queens problem have?",
     ["2", "1", "4", "0"], 0, PYQ + "The two solutions are mirror images."),
    ("How many distinct solutions does the 8-Queens problem have?",
     ["92", "12", "64", "8"], 0, PYQ + "12 of them are fundamentally different up to rotation and reflection."),
    ("In the N-Queens problem, queens at (i, j) and (k, l) are on the same diagonal if:",
     ["|i − k| = |j − l|", "i = k", "j = l", "i + j = k − l"], 0, "Rows and columns are checked separately."),
    ("Sum of subsets: from {3, 5, 6, 7}, which subset has sum exactly 15?",
     ["{3, 5, 7}", "{5, 6, 7}", "{3, 5, 6}", "{3, 6, 7}"], 0, "3 + 5 + 7 = 15."),
    ("In the state-space tree of the subset problem with n items (include/exclude each), the number of leaves is:",
     ["2ⁿ", "n!", "n²", "n"], 0, "Each item doubles the number of paths."),
    ("For n = 4 items, the complete include/exclude state-space tree has how many leaves?",
     ["16", "8", "24", "4"], 0, "2⁴ = 16."),
    ("The graph m-colouring problem asks whether:",
     ["The vertices can be coloured with at most m colours so that adjacent vertices differ", "The edges can be sorted by weight", "A path visits every edge once", "The graph is a tree"], 0, PYQ + "It is solved by backtracking; the least such m is the chromatic number."),
    ("The minimum number of colours needed for the complete graph K₄ is:",
     ["4", "3", "2", "5"], 0, "Every pair of vertices is adjacent."),
    ("Which problem is typically solved with backtracking?",
     ["Finding a Hamiltonian cycle", "Finding a minimum spanning tree", "Sorting an array", "Computing a hash value"], 0, "Paths are extended vertex by vertex and abandoned at dead ends."),
    ("Branch and bound is used mainly for:",
     ["Optimisation problems, pruning nodes whose bound is no better than the best solution found", "Sorting problems", "Only decision problems with no costs", "Hashing"], 0, PYQ + "0/1 knapsack, TSP and job assignment are classic examples."),
    ("In branch and bound, the node currently being expanded is called the:",
     ["E-node", "Dead node", "Leaf node", "Answer node only"], 0, "Live nodes are waiting to be expanded; dead nodes are pruned or fully expanded."),
    ("FIFO branch and bound keeps live nodes in a:",
     ["Queue", "Stack", "Hash table", "Binary search tree"], 0, "LIFO branch and bound uses a stack."),
    ("Least-cost (LC) branch and bound selects the next E-node using:",
     ["An estimated cost function ĉ (the most promising node first)", "Random choice", "The order of creation only", "Alphabetical order"], 0, "A priority queue holds the live nodes."),
    ("In branch and bound for the travelling salesman problem, a common lower bound comes from:",
     ["Reducing the cost matrix (subtracting row and column minima)", "Sorting the cities by name", "Counting the edges", "Hashing the tour"], 0, "The total reduction is a lower bound on any tour."),
    ("A bounding function in backtracking is used to:",
     ["Kill nodes that cannot lead to a feasible or better solution", "Sort the input", "Allocate memory", "Print the solutions"], 0, "Good bounds greatly reduce the search."),
    ("The worst-case time of backtracking algorithms is usually:",
     ["Exponential, although pruning often makes them fast in practice", "Always O(n)", "Always O(n log n)", "O(1)"], 0, "The state-space tree can be exponentially large."),
    ("A typical example of backtracking in everyday puzzles is solving a:",
     ["Sudoku", "Bubble sort", "Binary search", "Queue simulation"], 0, "Fill a cell, and undo it when a conflict arises."),
    ("Placing one queen per row, a brute-force 8-Queens search that also keeps one queen per column checks at most:",
     ["8! = 40,320 arrangements", "8⁸ arrangements", "64 arrangements", "92 arrangements"], 0, "Backtracking prunes far more than this."),
    ("Consider the statements:\nI. Backtracking uses depth-first search of the state-space tree.\nII. Branch and bound can use breadth-first or least-cost search.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Consider the statements:\nI. Backtracking always runs in polynomial time.\nII. The 8-Queens problem can be solved by backtracking.\nWhich is/are correct?",
     I_II, 1, "Backtracking is exponential in the worst case."),
    ("Assertion (A): Pruning makes backtracking faster than exhaustive search.\nReason (R): Pruned subtrees are never explored.",
     AR, 0, "Whole subtrees of hopeless candidates are skipped."),
    ("Assertion (A): Branch and bound is mainly used for finding all solutions of a decision problem.\nReason (R): Branch and bound uses bounds on the objective value to prune nodes.",
     AR, 3, "Because it uses objective bounds, it is mainly for optimisation problems; A is false."),
    ("Assertion (A): The 4-Queens problem has two solutions.\nReason (R): Two queens attack each other only if they are in the same row.",
     AR, 2, "A is true; R is false – queens also attack along columns and diagonals."),
    ("Assertion (A): Sudoku can be solved by backtracking.\nReason (R): Sudoku was popularised in Japan.",
     AR, 1, "Both true, but R does not explain A."),
    ("Match the term with its meaning:\na. Live node  b. E-node  c. Dead node  d. Bounding function\n1. Used to kill nodes  2. Node not to be expanded further  3. Node being expanded now  4. Generated node whose children are not all generated",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, PYQ + "Horowitz–Sahni terminology."),
    ("Match the problem with the usual technique:\na. N-Queens  b. TSP with a lower bound  c. Matrix-chain order  d. Activity selection\n1. Greedy  2. Dynamic programming  3. Branch and bound  4. Backtracking",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Recognising the technique is a frequent exam question."),
    ("A rat-in-a-maze problem, where the rat retreats from dead ends and tries another path, is solved by:",
     ["Backtracking", "Hashing", "Greedy MST", "Radix sort"], 0, "It explores one path deeply and undoes moves on failure."),
]

TOPICS = {
    "Design Techniques – Divide & Conquer, Greedy": [("1 · Divide and Conquer", DIVIDE_CONQUER),
                                                     ("2 · Greedy Algorithms", GREEDY)],
    "Design Techniques – DP, Backtracking, Branch & Bound": [("1 · Dynamic Programming", DP),
                                                             ("2 · Backtracking and Branch and Bound", BACKTRACK_BB)],
}
