"""Paper 2 · Unit 8 · Hashing; Performance Analysis & Recurrences (4 sub-topics × 30).
References: Cormen et al., Introduction to Algorithms (CLRS); Horowitz, Sahni & Rajasekaran, Fundamentals of Computer Algorithms;
M. A. Weiss, Data Structures and Algorithm Analysis. Explanations starting "PYQ pattern" follow questions that recur in UGC-NET CS / GATE / KEA papers."""
from packlib import AR, I_II

PYQ = "PYQ pattern (UGC-NET / GATE / KEA). "

HASH_FUNCTIONS = [
    ("In the division method of hashing, h(k) = k mod m. Which choice of m is usually recommended?",
     ["A prime number not too close to a power of 2", "A power of 2", "A power of 10", "Any even number"], 0, PYQ + "If m = 2^p, h(k) depends only on the lowest p bits of the key."),
    ("With h(k) = k mod 11, the key 47 is stored in slot:",
     ["3", "4", "5", "2"], 0, "47 = 4 × 11 + 3."),
    ("With h(k) = k mod 7, the key 50 is stored in slot:",
     ["1", "0", "6", "7"], 0, "50 = 7 × 7 + 1."),
    ("The load factor α of a hash table with n keys and m slots is:",
     ["n / m", "m / n", "n × m", "n − m"], 0, PYQ + "It is the average number of keys per slot."),
    ("In the mid-square method, the key 4567 is squared to 20857489 and the middle two digits are taken. The hash value is:",
     ["57", "85", "74", "08"], 0, "Digits 2 0 8 5 7 4 8 9 → the 4th and 5th digits are 5 and 7."),
    ("Using fold-shift hashing with 3-digit parts and a table of 1000 slots, the key 123456789 hashes to:",
     ["368", "1368", "789", "456"], 0, "123 + 456 + 789 = 1368; keep the last 3 digits → 368."),
    ("In the multiplication method h(k) = ⌊m (kA mod 1)⌋, Knuth suggests A ≈:",
     ["(√5 − 1)/2 ≈ 0.618", "0.5", "π/4", "1.414"], 0, "The golden-ratio constant spreads keys well; m can then be a power of 2."),
    ("An ideal hash function should:",
     ["Distribute keys uniformly over the slots and be fast to compute", "Map all keys to slot 0", "Keep the keys in sorted order", "Depend on the table's current contents"], 0, "This is the simple uniform hashing assumption."),
    ("A perfect hash function is one that:",
     ["Maps a fixed set of keys to slots with no collisions", "Never needs to be computed", "Sorts the keys", "Works only for strings"], 0, "It is possible when the key set is known in advance, e.g. reserved words of a language."),
    ("A collision in hashing occurs when:",
     ["Two different keys hash to the same slot", "The table is empty", "A key hashes outside the table", "The hash function is slow"], 0, PYQ + "By the pigeonhole principle, collisions are unavoidable when the universe is larger than the table."),
    ("With h(k) = k mod 10, the keys 12, 22 and 32 all collide in slot:",
     ["2", "1", "3", "0"], 0, "This also shows why m = 10 is a poor choice for keys with the same last digit."),
    ("The expected time to search a well-designed hash table is O(1), but the worst case is:",
     ["O(n)", "O(log n)", "O(1)", "O(n log n)"], 0, PYQ + "In the worst case all keys fall into one slot."),
    ("For which task is a hash table a poor choice compared with a balanced BST?",
     ["Listing keys in sorted order or answering range queries", "Checking whether a key exists", "Inserting a new key", "Counting word frequencies"], 0, "Hashing scatters keys, so it keeps no order."),
    ("A direct-address table (one slot per possible key) is practical when:",
     ["The universe of keys is small", "Keys are long strings", "The universe is huge but few keys are used", "Keys are negative real numbers"], 0, "It gives O(1) worst-case operations but needs a slot for every possible key."),
    ("Universal hashing means:",
     ["Choosing the hash function at random from a carefully designed family", "Using the same hash function in every program", "Hashing only universal constants", "Using a table of infinite size"], 0, "No fixed input can then force bad behaviour on average."),
    ("Rehashing is done when:",
     ["The load factor exceeds a threshold, so a larger table is created and all keys are re-inserted", "A key is searched twice", "The table is empty", "A key is deleted"], 0, "The table size is usually about doubled."),
    ("The default load factor threshold at which Java's HashMap resizes is:",
     ["0.75", "0.5", "1.0", "0.25"], 0, "It balances memory use against collision chains."),
    ("A hash table is used by a compiler mainly for its:",
     ["Symbol table", "Parse tree", "Register allocation", "Object code"], 0, PYQ + "Identifiers are looked up constantly, so O(1) lookup matters."),
    ("Extendible hashing, used for database files, handles growth by:",
     ["Doubling a directory of bucket pointers and splitting only the overflowing bucket", "Rebuilding the entire file each time", "Using a single linked list", "Sorting the file"], 0, "It avoids full reorganisation of the file."),
    ("Consider the statements:\nI. A hash table keeps keys in sorted order.\nII. A good hash function spreads keys uniformly.\nWhich is/are correct?",
     I_II, 1, "Hash tables keep no order."),
    ("Consider the statements:\nI. In the division method, a table size that is a power of 2 uses only the low-order bits of the key.\nII. A perfect hash function has no collisions for its key set.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Consider the statements:\nI. The load factor of a table with 30 keys and 10 slots is 0.33.\nII. The worst-case search time in hashing is O(1).\nWhich is/are correct?",
     I_II, 3, "α = 30/10 = 3; the worst case is O(n)."),
    ("Assertion (A): Hashing gives O(1) expected search time.\nReason (R): The hash function computes the likely position of a key directly from the key.",
     AR, 0, "No comparisons with other keys are needed to reach the slot."),
    ("Assertion (A): Collisions can be completely avoided for arbitrary keys by choosing a clever hash function.\nReason (R): The universe of keys is usually much larger than the number of slots.",
     AR, 3, "Because the universe is larger than the table, collisions are unavoidable in general; A is false."),
    ("Assertion (A): m = 2^p is a poor table size for the division method.\nReason (R): The multiplication method was suggested by Knuth.",
     AR, 1, "Both true, but R does not explain A; A is explained by h(k) depending only on the low-order bits."),
    ("Assertion (A): Hash tables are suitable for range queries.\nReason (R): Hash tables give O(1) expected lookup of a single key.",
     AR, 3, "A is false – adjacent keys are scattered; R is true."),
    ("Match the hashing method with its description:\na. Division  b. Mid-square  c. Folding  d. Multiplication\n1. ⌊m (kA mod 1)⌋  2. Split the key into parts and add them  3. Square the key and take middle digits  4. k mod m",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These are the standard hash functions for integer keys."),
    ("Match the term with its meaning:\na. Load factor  b. Collision  c. Rehashing  d. Perfect hashing\n1. No collisions for a fixed key set  2. Moving all keys to a larger table  3. Two keys mapped to the same slot  4. n/m",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Core hashing vocabulary."),
    ("With h(k) = k mod 13, which two keys collide?",
     ["27 and 40", "27 and 41", "13 and 27", "40 and 52"], 0, "27 mod 13 = 1 and 40 mod 13 = 1."),
    ("A hash table of 100 slots stores 75 keys. Its load factor is:",
     ["0.75", "1.33", "75", "0.25"], 0, "α = 75 / 100."),
]

COLLISIONS = [
    ("In separate chaining, each slot of the hash table holds:",
     ["A linked list (chain) of all keys hashing to that slot", "Exactly one key", "A binary heap", "A copy of the whole table"], 0, PYQ + "Colliding keys are simply added to the slot's list."),
    ("In linear probing, the probe sequence for key k is:",
     ["h(k, i) = (h'(k) + i) mod m", "h(k, i) = (h'(k) + i²) mod m", "h(k, i) = (h₁(k) + i·h₂(k)) mod m", "h(k, i) = h'(k) × i"], 0, "Consecutive slots are tried one after another."),
    ("Primary clustering is a problem mainly of:",
     ["Linear probing", "Separate chaining", "Double hashing", "Direct addressing"], 0, PYQ + "Long runs of occupied slots form and keep growing."),
    ("Secondary clustering (keys with the same home slot follow the same probe sequence) occurs in:",
     ["Quadratic probing", "Separate chaining", "Double hashing", "Perfect hashing"], 0, "The sequence depends only on the home slot."),
    ("In double hashing h(k, i) = (h₁(k) + i·h₂(k)) mod m, the second function h₂ must:",
     ["Never be 0 and be relatively prime to m", "Always equal h₁", "Return only even values", "Be the identity function"], 0, "Otherwise the probe sequence cannot reach every slot."),
    ("Which open-addressing technique comes closest to uniform hashing and avoids both kinds of clustering?",
     ["Double hashing", "Linear probing", "Quadratic probing", "Chaining"], 0, "The step size depends on the key itself."),
    ("Keys 12, 22, 32, 42 are inserted into an empty table of size 10 with h(k) = k mod 10 and linear probing. Where does 42 go?",
     ["Slot 5", "Slot 2", "Slot 4", "Slot 6"], 0, "12 → 2, 22 → 3, 32 → 4, 42 → 2, 3, 4 taken → 5."),
    ("Keys 50, 700, 76, 85, 92, 73, 101 are inserted in that order into an empty table of size 7 with h(k) = k mod 7 and linear probing. In which slot is 101?",
     ["5", "3", "4", "6"], 0, PYQ + "50→1, 700→0, 76→6, 85→2, 92→3, 73→4, 101: 3, 4 taken → 5."),
    ("Keys 89, 18, 49, 58, 69 are inserted in that order into an empty table of size 10 with h(k) = k mod 10 and linear probing. In which slot is 69?",
     ["2", "9", "0", "1"], 0, "89→9, 18→8, 49→0 (wraps), 58→1, 69: 9, 0, 1 taken → 2."),
    ("Keys 22, 33, 44 are inserted into an empty table of size 11 with h(k) = k mod 11 and quadratic probing (h + i²) mod 11. Where does 44 go?",
     ["Slot 4", "Slot 2", "Slot 1", "Slot 3"], 0, "All hash to 0. 22 → 0; 33 → 0 + 1 = 1; 44 → 0 + 1 taken, 0 + 4 = 4."),
    ("With h₁(k) = k mod 13 and h₂(k) = 7 − (k mod 7), key 18 is already in slot 5. Using double hashing, where does 44 go?",
     ["Slot 10", "Slot 6", "Slot 12", "Slot 9"], 0, "h₁(44) = 5 (taken); h₂(44) = 7 − 2 = 5; (5 + 5) mod 13 = 10."),
    ("Keys 3, 8, 13 and 7 are inserted into a chained table of 5 slots with h(k) = k mod 5. How many keys are in slot 3?",
     ["3", "1", "2", "4"], 0, "3, 8 and 13 all give 3; 7 goes to slot 2."),
    ("In separate chaining with load factor α, an unsuccessful search takes on average:",
     ["Θ(1 + α)", "Θ(α²)", "Θ(log α)", "Θ(n)"], 0, PYQ + "Compute the hash, then scan a chain of expected length α."),
    ("100 keys are stored in a chained hash table with 25 slots under uniform hashing. The expected chain length is:",
     ["4", "25", "0.25", "100"], 0, "α = 100 / 25 = 4."),
    ("Under uniform hashing, an unsuccessful search in an open-addressing table with load factor α makes at most about how many probes?",
     ["1 / (1 − α)", "1 + α", "α / 2", "log(1/α)"], 0, PYQ + "For α = 0.5 that is 2 probes; for α = 0.9 it is 10."),
    ("An open-addressing table is 90% full (α = 0.9). The expected number of probes for an unsuccessful search under uniform hashing is about:",
     ["10", "2", "1.9", "0.9"], 0, "1 / (1 − 0.9) = 10 – performance collapses as the table fills."),
    ("Which statement about load factor is correct?",
     ["Chaining allows α > 1, but open addressing needs α ≤ 1", "Open addressing allows α > 1", "Both require α < 0.5", "Neither depends on α"], 0, "In open addressing every key is stored in the table itself."),
    ("When a key is deleted from an open-addressing table, its slot is marked 'deleted' (a tombstone) rather than 'empty' because:",
     ["An empty slot would stop later searches for keys that probed past it", "Empty slots cannot be reused", "Deletion is not allowed", "It saves memory"], 0, "Searches continue past tombstones; insertions may reuse them."),
    ("A practical advantage of linear probing over chaining is:",
     ["Better cache performance, since probes touch adjacent memory", "No clustering ever", "Unlimited load factor", "No need for a hash function"], 0, "Chains follow pointers scattered in memory."),
    ("Quadratic probing is guaranteed to find an empty slot if:",
     ["The table size is prime and the table is less than half full", "The table size is a power of 2 and full", "The keys are sorted", "Never"], 0, "Otherwise the probe sequence may cycle among occupied slots."),
    ("The worst-case search time in separate chaining occurs when:",
     ["All keys hash to the same slot, giving O(n)", "The table is empty", "Each slot has exactly one key", "The load factor is below 1"], 0, "The chain then becomes one long list."),
    ("Consider the statements:\nI. Chaining needs extra memory for pointers.\nII. Open addressing stores every key inside the table array.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Consider the statements:\nI. Linear probing suffers from primary clustering.\nII. Double hashing suffers from primary clustering.\nWhich is/are correct?",
     I_II, 0, "Double hashing's key-dependent step size avoids it."),
    ("Consider the statements:\nI. In open addressing, a deleted slot can simply be marked empty.\nII. In chaining, deletion removes a node from a list.\nWhich is/are correct?",
     I_II, 1, "Open addressing needs a 'deleted' marker."),
    ("Assertion (A): Linear probing tends to form long runs of occupied slots.\nReason (R): A key hashing anywhere into a run is placed at the end of the run, making it longer.",
     AR, 0, "That is primary clustering."),
    ("Assertion (A): Open addressing can store more keys than slots.\nReason (R): In open addressing all keys are stored in the table array itself.",
     AR, 3, "Because keys are in the array, n ≤ m; A is false."),
    ("Assertion (A): Double hashing gives a different probe sequence for keys with the same home slot.\nReason (R): Double hashing uses h₂(k) = 0 for every key.",
     AR, 2, "A is true; R is false – h₂ must never be 0."),
    ("Assertion (A): Performance of open addressing degrades sharply as α approaches 1.\nReason (R): Separate chaining uses linked lists.",
     AR, 1, "Both true, but R does not explain A; the 1/(1 − α) probe count does."),
    ("Match the collision technique with its property:\na. Separate chaining  b. Linear probing  c. Quadratic probing  d. Double hashing\n1. Step size depends on the key  2. Secondary clustering  3. Primary clustering  4. Lists outside the table",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each technique handles collisions differently."),
    ("Match the load factor (open addressing, uniform hashing) with the expected probes for an unsuccessful search:\na. α = 0.5  b. α = 0.75  c. α = 0.8  d. α = 0.9\n1. 10  2. 5  3. 4  4. 2",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "1 / (1 − α): 2, 4, 5, 10."),
]

COMPLEXITY = [
    ("f(n) = O(g(n)) means that g(n) is:",
     ["An asymptotic upper bound of f(n)", "An asymptotic lower bound of f(n)", "An exact (tight) bound only", "Unrelated to f(n)"], 0, PYQ + "f(n) ≤ c·g(n) for all n ≥ n₀, for some constants c > 0 and n₀."),
    ("f(n) = Θ(g(n)) means that:",
     ["g(n) is both an upper and a lower bound of f(n) (a tight bound)", "g(n) is only an upper bound", "g(n) is only a lower bound", "f(n) grows faster than g(n)"], 0, "c₁g(n) ≤ f(n) ≤ c₂g(n) for large n."),
    ("f(n) = Ω(g(n)) means that g(n) is:",
     ["An asymptotic lower bound of f(n)", "An asymptotic upper bound of f(n)", "Always equal to f(n)", "Smaller only for small n"], 0, "f(n) ≥ c·g(n) for large n."),
    ("f(n) = 3n² + 5n + 2 is:",
     ["Θ(n²)", "Θ(n)", "Θ(n³)", "Θ(n log n)"], 0, "The highest-order term dominates; constants are ignored."),
    ("Which is the correct increasing order of growth?",
     ["log n, √n, n, n log n, n², 2ⁿ, n!", "√n, log n, n, n², n log n, n!, 2ⁿ", "log n, n, √n, n log n, 2ⁿ, n², n!", "n, log n, √n, n², n log n, 2ⁿ, n!"], 0, PYQ + "A standard ordering to memorise."),
    ("Which function grows fastest for large n?",
     ["n!", "2ⁿ", "n¹⁰", "n^(log n)"], 0, "n¹⁰ < n^(log n) < 2ⁿ < n! for large n."),
    ("What is the time complexity of this loop?\ni = 1;\nwhile (i < n) i = i * 2;",
     ["O(log n)", "O(n)", "O(n log n)", "O(√n)"], 0, PYQ + "i doubles each time, so the loop runs about log₂ n times."),
    ("What is the time complexity?\nfor (i = 1; i <= n; i++)\n  for (j = 1; j <= i; j++)\n    count++;",
     ["O(n²)", "O(n)", "O(n log n)", "O(log n)"], 0, "1 + 2 + … + n = n(n + 1)/2."),
    ("What is the time complexity?\nfor (i = 1; i <= n; i++)\n  for (j = 1; j < n; j = j * 2)\n    count++;",
     ["O(n log n)", "O(n²)", "O(n)", "O(log² n)"], 0, "The outer loop runs n times and the inner about log₂ n times."),
    ("What is the time complexity?\nfor (i = n; i > 0; i = i / 2)\n  for (j = 0; j < i; j++)\n    count++;",
     ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], 0, PYQ + "n + n/2 + n/4 + … < 2n."),
    ("An algorithm with running time n² takes 1 second for n = 1000. For n = 2000 it will take about:",
     ["4 seconds", "2 seconds", "8 seconds", "1 second"], 0, "Doubling n multiplies n² by 4."),
    ("Which is TRUE?",
     ["2ⁿ⁺¹ = O(2ⁿ)", "2²ⁿ = O(2ⁿ)", "n² = O(n)", "n! = O(2ⁿ)"], 0, PYQ + "2ⁿ⁺¹ = 2·2ⁿ, but 2²ⁿ = 4ⁿ grows faster than any constant times 2ⁿ."),
    ("log(n!) is:",
     ["Θ(n log n)", "Θ(n)", "Θ(log n)", "Θ(n²)"], 0, "By Stirling's approximation; this gives the sorting lower bound."),
    ("log₂ n and log₁₀ n are:",
     ["Of the same order Θ(log n), since they differ by a constant factor", "Of different orders", "Both Θ(n)", "Unrelated"], 0, "log₂ n = log₁₀ n / log₁₀ 2."),
    ("The harmonic sum 1 + 1/2 + 1/3 + … + 1/n is:",
     ["Θ(log n)", "Θ(n)", "Θ(1)", "Θ(n²)"], 0, "It is approximately ln n."),
    ("The space complexity of a program consists of:",
     ["A fixed part (code, constants, simple variables) and a variable part (depending on the instance, e.g. recursion stack)", "Only the size of the input", "Only the code size", "Only the output size"], 0, "This is the Horowitz–Sahni definition."),
    ("The recursive function fact(n) = n × fact(n − 1) uses stack space:",
     ["O(n)", "O(1)", "O(log n)", "O(n²)"], 0, "n calls are active at the deepest point."),
    ("Appending n items to a dynamic array that doubles its capacity when full costs:",
     ["O(1) amortised per append", "O(n) per append always", "O(log n) per append", "O(n²) per append"], 0, "The occasional O(n) copy is spread over many cheap appends."),
    ("Which statement about little-o is correct?",
     ["n = o(n²), since n grows strictly slower than n²", "n² = o(n²)", "n² = o(n)", "o means the same as Θ"], 0, "f = o(g) means f/g → 0."),
    ("If f(n) = O(g(n)) and g(n) = O(h(n)), then f(n) = O(h(n)). This property is:",
     ["Transitivity", "Symmetry", "Reflexivity only", "Transpose symmetry"], 0, "Θ is also symmetric; O is not."),
    ("Problems solvable by polynomial-time algorithms are generally called:",
     ["Tractable", "Intractable", "Undecidable", "Exponential"], 0, "Exponential-time problems quickly become impractical."),
    ("Consider the statements:\nI. n log n = O(n^1.5).\nII. n^1.5 = O(n log n).\nWhich is/are correct?",
     I_II, 0, "log n grows slower than n^0.5."),
    ("Consider the statements:\nI. Big-O gives an upper bound.\nII. The worst-case running time of an algorithm can be written with Big-O.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Consider the statements:\nI. 100n² is Θ(n³).\nII. n³ is O(n²).\nWhich is/are correct?",
     I_II, 3, "100n² is Θ(n²); n³ is not O(n²)."),
    ("Assertion (A): Constant factors are ignored in asymptotic analysis.\nReason (R): For large n, the growth rate matters more than constant multipliers.",
     AR, 0, "That is why 5n and 100n are both Θ(n)."),
    ("Assertion (A): An O(n²) algorithm is always slower than an O(n log n) algorithm.\nReason (R): Asymptotic notation hides constant factors and lower-order terms.",
     AR, 3, "For small n or large constants the O(n²) algorithm can be faster; A is false."),
    ("Assertion (A): Linear search has Θ(1) best-case time.\nReason (R): Linear search has Θ(log n) worst-case time.",
     AR, 2, "A is true; R is false – the worst case is Θ(n)."),
    ("Match the code pattern with its complexity:\na. Single loop i = 1 … n  b. Two nested loops 1 … n  c. i = i * 2 up to n  d. Accessing A[i]\n1. O(1)  2. O(log n)  3. O(n²)  4. O(n)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "These are the basic patterns of loop analysis."),
    ("Match the notation with its meaning:\na. O  b. Ω  c. Θ  d. o\n1. Strictly smaller order  2. Tight bound  3. Lower bound  4. Upper bound",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "ω (little-omega) is the strict lower bound."),
    ("The sum 1 + 2 + 3 + … + n is:",
     ["Θ(n²)", "Θ(n)", "Θ(n log n)", "Θ(2ⁿ)"], 0, "n(n + 1)/2."),
]

RECURRENCES = [
    ("The master theorem applies to recurrences of the form:",
     ["T(n) = aT(n/b) + f(n), with a ≥ 1 and b > 1", "T(n) = T(n − 1) + T(n − 2)", "T(n) = T(n − 1) + n only", "T(n) = n T(n − 1)"], 0, PYQ + "It compares f(n) with n^(log_b a)."),
    ("Solve T(n) = 4T(n/2) + n.",
     ["Θ(n²)", "Θ(n log n)", "Θ(n)", "Θ(n² log n)"], 0, "n^(log₂4) = n² dominates f(n) = n (case 1)."),
    ("Solve T(n) = T(n/2) + 1.",
     ["Θ(log n)", "Θ(n)", "Θ(1)", "Θ(n log n)"], 0, "n^(log₂1) = 1 = f(n) (case 2) → Θ(log n)."),
    ("Solve T(n) = 2T(n/2) + 1.",
     ["Θ(n)", "Θ(log n)", "Θ(n log n)", "Θ(n²)"], 0, "n^(log₂2) = n dominates f(n) = 1 (case 1)."),
    ("Solve T(n) = T(n − 1) + n, T(1) = 1.",
     ["Θ(n²)", "Θ(n)", "Θ(n log n)", "Θ(2ⁿ)"], 0, PYQ + "T(n) = 1 + 2 + … + n = n(n + 1)/2."),
    ("Solve T(n) = T(n − 1) + 1, T(1) = 1.",
     ["Θ(n)", "Θ(log n)", "Θ(n²)", "Θ(1)"], 0, "Each level adds a constant."),
    ("The recurrence T(n) = 2T(n − 1) + 1, T(1) = 1 (Tower of Hanoi) solves to:",
     ["2ⁿ − 1", "n²", "2n − 1", "n log n"], 0, PYQ + "T(1) = 1, T(2) = 3, T(3) = 7, …"),
    ("The minimum number of moves to solve the Tower of Hanoi with 5 disks is:",
     ["31", "32", "25", "15"], 0, "2⁵ − 1 = 31."),
    ("Solve T(n) = 3T(n/2) + n (Karatsuba multiplication).",
     ["Θ(n^(log₂3)) ≈ Θ(n^1.585)", "Θ(n log n)", "Θ(n²)", "Θ(n)"], 0, "n^(log₂3) dominates n (case 1)."),
    ("Solve T(n) = 7T(n/2) + n² (Strassen's matrix multiplication).",
     ["Θ(n^(log₂7)) ≈ Θ(n^2.81)", "Θ(n³)", "Θ(n² log n)", "Θ(n²)"], 0, PYQ + "log₂7 ≈ 2.81 > 2, so case 1 applies."),
    ("Solve T(n) = 2T(n/2) + n².",
     ["Θ(n²)", "Θ(n² log n)", "Θ(n log n)", "Θ(n³)"], 0, "f(n) = n² dominates n^(log₂2) = n and satisfies the regularity condition (case 3)."),
    ("Solve T(n) = 8T(n/2) + n².",
     ["Θ(n³)", "Θ(n²)", "Θ(n² log n)", "Θ(n⁴)"], 0, "n^(log₂8) = n³ dominates n² (case 1)."),
    ("Solve T(n) = 9T(n/3) + n.",
     ["Θ(n²)", "Θ(n)", "Θ(n log n)", "Θ(n³)"], 0, "n^(log₃9) = n² dominates n."),
    ("Solve T(n) = T(n/2) + n.",
     ["Θ(n)", "Θ(n log n)", "Θ(log n)", "Θ(n²)"], 0, "n + n/2 + n/4 + … < 2n (case 3)."),
    ("Solve T(n) = T(√n) + 1.",
     ["Θ(log log n)", "Θ(log n)", "Θ(√n)", "Θ(1)"], 0, PYQ + "Put n = 2^m: S(m) = S(m/2) + 1 = Θ(log m) = Θ(log log n)."),
    ("Solve T(n) = T(n/3) + T(2n/3) + n.",
     ["Θ(n log n)", "Θ(n)", "Θ(n²)", "Θ(log n)"], 0, "Each level of the recursion tree costs n and there are Θ(log n) levels."),
    ("T(n) = 2T(n/2) + n log n does not fit the three basic master-theorem cases. Its solution is:",
     ["Θ(n log² n)", "Θ(n log n)", "Θ(n²)", "Θ(n)"], 0, "The extended case 2 gives Θ(n^(log_b a) log^(k+1) n) with k = 1."),
    ("The naive recursive Fibonacci function T(n) = T(n − 1) + T(n − 2) + 1 takes:",
     ["Exponential time, about Θ(φⁿ) where φ ≈ 1.618", "Θ(n) time", "Θ(n²) time", "Θ(log n) time"], 0, "It recomputes the same subproblems many times; DP makes it Θ(n)."),
    ("The recurrence aₙ = 2aₙ₋₁ with a₀ = 3 has the solution:",
     ["aₙ = 3 · 2ⁿ", "aₙ = 2 · 3ⁿ", "aₙ = 3n + 2", "aₙ = 6ⁿ"], 0, "Each term doubles the previous one."),
    ("The general solution of aₙ = 5aₙ₋₁ − 6aₙ₋₂ is:",
     ["aₙ = c₁·2ⁿ + c₂·3ⁿ", "aₙ = c₁·5ⁿ + c₂·6ⁿ", "aₙ = (c₁ + c₂n)·2ⁿ", "aₙ = c₁·(−2)ⁿ + c₂·(−3)ⁿ"], 0, PYQ + "The characteristic equation r² − 5r + 6 = 0 has roots 2 and 3."),
    ("T(n) = T(n − 1) + 2 with T(1) = 1. What is T(5)?",
     ["9", "10", "11", "7"], 0, "1, 3, 5, 7, 9."),
    ("In the recursion-tree method for T(n) = 2T(n/2) + n, each level costs n and the number of levels is about:",
     ["log₂ n", "n", "√n", "2"], 0, "So the total is n log₂ n."),
    ("The substitution method for solving recurrences consists of:",
     ["Guessing the form of the solution and proving it by mathematical induction", "Drawing a tree only", "Applying the master theorem directly", "Running the program and timing it"], 0, "It works even where the master theorem does not apply."),
    ("Consider the statements:\nI. The master theorem can solve T(n) = T(n − 1) + n.\nII. The master theorem can solve T(n) = 2T(n/2) + n.\nWhich is/are correct?",
     I_II, 1, "T(n − 1) is not of the form aT(n/b)."),
    ("Consider the statements:\nI. T(n) = 2T(n/2) + n describes merge sort.\nII. T(n) = T(n/2) + 1 describes binary search.\nWhich is/are correct?",
     I_II, 2, "Both are correct."),
    ("Assertion (A): T(n) = 2T(n/2) + n is Θ(n log n).\nReason (R): Its recursion tree has about log n levels, each costing n.",
     AR, 0, "Total cost = n per level × log n levels."),
    ("Assertion (A): The Tower of Hanoi with n disks needs 2ⁿ moves.\nReason (R): Its recurrence is T(n) = 2T(n − 1) + 1.",
     AR, 3, "It needs 2ⁿ − 1 moves; A is false, R is true."),
    ("Assertion (A): Strassen's algorithm is asymptotically faster than ordinary matrix multiplication.\nReason (R): Strassen's recurrence is T(n) = 8T(n/2) + n².",
     AR, 2, "A is true; R is false – Strassen uses 7 subproblems, not 8."),
    ("Match the recurrence with its solution:\na. T(n) = 2T(n/2) + n  b. T(n) = T(n/2) + 1  c. T(n) = T(n − 1) + n  d. T(n) = 2T(n − 1) + 1\n1. Θ(2ⁿ)  2. Θ(n²)  3. Θ(log n)  4. Θ(n log n)",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Four recurrences every candidate should know."),
    ("Match the algorithm with its recurrence:\na. Merge sort  b. Binary search  c. Strassen  d. Karatsuba\n1. 3T(n/2) + n  2. 7T(n/2) + n²  3. T(n/2) + 1  4. 2T(n/2) + n",
     ["a-4, b-3, c-2, d-1", "a-3, b-4, c-2, d-1", "a-4, b-2, c-3, d-1", "a-4, b-3, c-1, d-2"], 0, "Each comes from how the algorithm divides and combines."),
]

TOPICS = {
    "Hashing": [("1 · Hash Functions and Hash Tables", HASH_FUNCTIONS),
                ("2 · Collision Resolution", COLLISIONS)],
    "Performance Analysis & Recurrences": [("1 · Time and Space Complexity, Asymptotic Notation", COMPLEXITY),
                                           ("2 · Recurrence Relations", RECURRENCES)],
}
