"""Paper 2 · Unit 9 · P2-U9-03 Computer Networks & Topologies, P2-U9-04 Network Models and P2-U9-05 Data Link Layer
(3 topics × 2 sub-topics × 30).
References: Behrouz A. Forouzan, Data Communications and Networking (5th ed., chs. 1–2, 8, 9–11); Andrew S. Tanenbaum, Computer
Networks (chs. 1, 3). Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and
question number) with new ones. Official answers come from KEA's final keys: Legislative Council Secretariat 2024 (Computer
Operator P2, Junior Console Operator P2, Data Entry Operator P2, Asst/Jr Asst P2 – booklet A1; final key 09-04-2025) and GTTC 2024
(Lecturer CS – booklet A1, Technician Gr-III CS – booklet C1; final keys 30-12-2024). KSET 2023–25 and KEA 2026 questions are
reused from packs/pyq-p2.json; those, GFGC 2021 and PGCET answers were worked out by ExamSim. IP addressing, ARP, DNS, routing,
TCP and multiple-access questions found in the papers are kept for the later Unit 9 topics. CRC, Hamming and window answers were
checked by computation."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

TOPOLOGY = [
    ("In ____ topology, each device has a dedicated point-to-point connection with only the two devices on either side of it.",
     ["Bus", "Ring", "Mesh", "Star"], 1,
     "In a ring, each device links to its two neighbours and the signal passes around the ring with repeaters." + GTTC, "GTTC 2024 Technician Gr-III CS (C1) · Q43"),
    ("Match the following types of network topologies with their characteristics.\nTopology\n(a) Star\n(b) Ring\n(c) Bus\n(d) Mesh\nCharacteristics\ni) Every device is connected to every other device\nii) All devices share a single communication medium\niii) Each device is connected to its neighbour in circular fashion\niv) Single central device controls communication",
     ["a – iii, b – ii, c – iv, d – i", "a – i, b – iii, c – ii, d – iv", "a – iv, b – iii, c – ii, d – i", "a – ii, b – iii, c – iv, d – i"], 2,
     "Star – central hub/switch; ring – circular; bus – one shared cable; mesh – every device to every other." + KLC, "Legislative Council 2024 Computer Operator P2 · Q61"),
    ("For a network with n devices, the number of duplex-mode links required for mesh topology is:",
     ["n(n + 1)", "n(n − 1)", "n(n + 1) / 2", "n(n − 1) / 2"], 3,
     "Every pair needs one duplex link: C(n, 2) = n(n − 1)/2." + NOTE, "KSET 2024 CS&A · Q84"),
    ("In a mesh topology with 100 devices, the number of physical connections required is ____.",
     ["9900", "4950", "200", "9801"], 1,
     "n(n − 1)/2 = 100 × 99 / 2 = 4950." + NOTE, "KSET 2025 CS&A · Q85"),
    ("Consider the following statements regarding the interconnection topology.\ni. In star topology, if the master node is dead, the other nodes (processor) can still interact with each other.\nii. In bus topology, only two processors can interact with each other at any one given point in time.\niii. In hyper cube topology, two nodes are connected if there is change in two bits in their processor identity (processor id)",
     ["(i) is true, (ii) and (iii) are false", "(i) and (ii) are true, (iii) is false", "(ii) is true, (i) and (iii) are false", "(i) and (iii) are true, (ii) is false"], 2,
     "In a star all traffic passes through the centre; a shared bus carries one transfer at a time; hypercube neighbours differ in exactly one bit." + NOTE,
     "KSET 2025 CS&A · Q20"),
    ("In a star topology, the failure of the central hub:",
     ["Brings down the whole network", "Affects only one device", "Has no effect", "Speeds up the network"], 0, PYQ + "But a failure of one link affects only that device."),
    ("Which topology needs a terminator at each end of the cable?",
     ["Bus", "Star", "Mesh", "Ring"], 0, "Terminators absorb the signal to prevent reflections."),
    ("A disadvantage of bus topology is:",
     ["A break in the backbone cable stops all transmission", "It needs the most cable", "It needs a central hub", "Each device needs n − 1 ports"], 0, PYQ + "It is cheap and easy to install."),
    ("In a fully connected mesh of 6 devices, each device needs how many I/O ports?",
     ["5", "6", "15", "30"], 0, "Each device connects to n − 1 = 5 others; total links = 15."),
    ("The main advantage of mesh topology is:",
     ["Robustness – failure of one link does not affect the others, and dedicated links give privacy", "Lowest cost", "Least cabling", "Easiest to install"], 0,
     PYQ + "Its drawback is the large amount of cabling and ports."),
    ("A topology that combines two or more different topologies, such as several star networks joined by a bus, is:",
     ["Hybrid topology", "Ring topology", "Mesh topology", "Point-to-point"], 0, "Tree topology is a hierarchy of stars."),
    ("Token Ring networks (IEEE 802.5) use which physical/logical arrangement?",
     ["A logical ring, often wired as a star through a MAU", "A bus", "A full mesh", "A tree only"], 0, PYQ + "Only the station holding the token can transmit."),
    ("In a dual ring (as in FDDI), the second ring is used to:",
     ["Keep the network working if the primary ring breaks", "Double the cost only", "Connect printers", "Carry power"], 0, "FDDI used fibre at 100 Mbps."),
    ("A link that connects exactly two devices is called:",
     ["Point-to-point", "Multipoint", "Broadcast", "Mesh"], 0, PYQ + "In a multipoint (multidrop) link, several devices share one link."),
    ("Physical topology means:",
     ["The geometric arrangement of devices and links", "The routing protocol", "The IP addressing plan", "The application software"], 0, "Logical topology is how data actually flows."),
    ("Consider the statements:\nI. A star topology needs less cable than a mesh.\nII. In a star topology, devices communicate directly without the hub.",
     I_II, 0, "In a star, all traffic passes through the hub/switch."),
    ("Assertion (A): Adding a new device to a star network is easy.\nReason (R): Only one link between the new device and the hub is needed.",
     AR, 0, "This makes star the most popular LAN topology."),
    ("Assertion (A): Ring topology has no single point of failure.\nReason (R): In a simple ring, data travels in one direction from device to device.",
     AR, 3, "A break in a simple ring can disable the network unless a dual ring or bypass switch is used."),
    ("A mesh network requires 45 links. How many devices does it connect?",
     ["10", "9", "45", "15"], 0, PYQ + "n(n − 1)/2 = 45 → n = 10."),
    ("Match:\na. Bus  b. Star  c. Ring  d. Mesh\n1. One backbone cable  2. Central hub  3. Each node to two neighbours  4. Dedicated link between every pair",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Basic topology matching."),
    ("Which topology is used by a hub-based 10Base-T Ethernet?",
     ["Physical star, logical bus", "Physical ring", "Physical mesh", "Physical bus only"], 0, "A hub repeats every signal to all ports."),
    ("Which topology is most fault-tolerant?",
     ["Mesh", "Bus", "Ring", "Star"], 0, PYQ + "Multiple paths exist between nodes."),
    ("In a tree topology, the root is usually:",
     ["A central hub to which secondary hubs are connected", "A terminator", "A token", "A repeater at each end"], 0, "It is a hierarchy of star networks."),
    ("The number of cables needed to connect 8 computers in a star topology is:",
     ["8", "28", "7", "16"], 0, PYQ + "One cable from each computer to the hub; a mesh would need 28."),
    ("Which statement about bus topology is TRUE?",
     ["Only one device can transmit at a time, so collisions are possible", "Each device has a dedicated link", "Failure of one device stops all others", "It needs a central switch"], 0,
     "CSMA/CD was designed for shared-bus Ethernet."),
    ("A 'daisy chain' connection is closest to:",
     ["A linear bus (devices connected one after another)", "A star", "A full mesh", "A satellite link"], 0, PYQ + "USB and SCSI devices can be daisy-chained."),
    ("In a ring topology, a signal is passed along the ring in one direction and each device incorporates a:",
     ["Repeater", "Router", "Gateway", "Firewall"], 0, "The repeater regenerates the bits and passes them on."),
    ("The topology chosen for a network mainly depends on:",
     ["Cost, reliability, scalability and ease of installation", "The colour of cables", "The operating system only", "The web browser"], 0, PYQ + "No single topology is best for all cases."),
    ("In a hypercube interconnection of 2ⁿ processors, each processor is connected to:",
     ["n others (those whose IDs differ in one bit)", "2ⁿ − 1 others", "Only one other", "Two others"], 0, "An 8-node (3-cube) hypercube has 3 links per node."),
    ("Consider the statements:\nI. A full mesh of n nodes needs n(n − 1)/2 links.\nII. A star of n nodes needs n links to the hub.",
     I_II, 2, "Both formulas are correct."),
]

NETTYPES = [
    ("Match the following:\na) LAN\nb) WAN\nc) Internet\nd) Protocol\ni. Connection of two or more networks that can communicate each other\nii. A Network limited in Size, spanning an office, building or a campus\niii. A Network has a wider geographical span, spanning a town, state, country or even the world\niv. Set of rules that govern data communication",
     ["a – ii, b – iii, c – i, d – iv", "a – i, b – ii, c – iv, d – iii", "a – ii, b – i, c – iii, d – iv", "a – iv, b – ii, c – i, d – iii"], 0,
     "A LAN covers a building or campus; a WAN covers a large area; an internet is a network of networks; a protocol is a set of rules." + GTTC,
     "GTTC 2024 Technician Gr-III CS (C1) · Q44"),
    ("MAN stands for",
     ["Metropolitan Area Network", "Main Area Network", "Modified Area Network", "Middle Area Network"], 0,
     "A MAN covers a city, e.g. a cable TV network or a city-wide fibre network." + KLC, "Legislative Council 2024 Data Entry Operator P2 · Q92"),
    ("The ____ network is owned by multiple organizations.",
     ["LAN", "WAN", "MAN", "PAN"], 1,
     "A WAN spans large areas and usually uses links owned by several carriers and organisations; a LAN is normally privately owned." + KLC,
     "Legislative Council 2024 Data Entry Operator P2 · Q93"),
    ("A network that connects devices around one person, such as a phone, smartwatch and earbuds via Bluetooth, is a:",
     ["PAN", "LAN", "MAN", "WAN"], 0, PYQ + "Range is usually under 10 m."),
    ("Which of these is the correct order of networks by geographical size, from smallest to largest?",
     ["PAN, LAN, MAN, WAN", "LAN, PAN, WAN, MAN", "MAN, LAN, PAN, WAN", "WAN, MAN, LAN, PAN"], 0, "The Internet is the largest internetwork."),
    ("The most widely used wired LAN technology today is:",
     ["Ethernet (IEEE 802.3)", "Token Ring", "FDDI", "ATM"], 0, PYQ + "Wi-Fi (IEEE 802.11) is the wireless LAN standard."),
    ("The IEEE standard for wireless LANs (Wi-Fi) is:",
     ["802.11", "802.3", "802.5", "802.15"], 0, "802.15 is for wireless PANs such as Bluetooth; 802.16 is WiMAX."),
    ("Bluetooth belongs to which IEEE standard family?",
     ["802.15", "802.11", "802.3", "802.16"], 0, PYQ + "A Bluetooth piconet has one primary and up to seven active secondaries."),
    ("WiMAX (IEEE 802.16) is used mainly for:",
     ["Broadband wireless access over metropolitan distances", "Wired LANs", "Optical networks", "Personal area networks"], 0, "It is a wireless MAN technology."),
    ("A network of networks that uses a common protocol suite (TCP/IP) is called:",
     ["The Internet (an internetwork)", "A LAN", "A PAN", "An intranet only"], 0, PYQ + "An intranet is a private network using Internet technology."),
    ("An extranet is:",
     ["A private network that allows controlled access to outside partners", "The public Internet", "A home LAN", "A satellite link"], 0, "Example: a supplier portal."),
    ("The Internet grew out of ARPANET, which was started in 1969 by the:",
     ["US Department of Defense (ARPA)", "European Union", "Indian Railways", "United Nations"], 0, PYQ + "TCP/IP replaced NCP on ARPANET on 1 January 1983."),
    ("In a client–server network:",
     ["Servers provide services that clients request", "All computers have equal roles", "There is no central computer at all", "Clients store all data"], 0,
     "In a peer-to-peer network each computer can act as both client and server."),
    ("Internet Service Providers at the top of the hierarchy that connect to each other through peering points are called:",
     ["Tier-1 (backbone) ISPs", "Local ISPs", "Customers", "Hubs"], 0, PYQ + "Regional and local ISPs buy access from higher tiers."),
    ("The 'last mile' connection from a home to the ISP can be provided by:",
     ["DSL, cable, fibre (FTTH) or wireless", "Only satellite", "Only Ethernet", "Only Bluetooth"], 0, "DSL uses telephone lines; cable uses the cable-TV network."),
    ("Which technology carries Internet data over existing telephone lines while allowing voice calls at the same time?",
     ["DSL (Digital Subscriber Line)", "Dial-up only", "FDDI", "Token Ring"], 0, PYQ + "ADSL gives higher download than upload speed."),
    ("A switched WAN service in which customers' traffic is labelled and forwarded through the provider's network at 'layer 2.5' is:",
     ["MPLS", "Bluetooth", "Ethernet hub", "Token passing"], 0, "MPLS is widely used by carriers."),
    ("A wireless network without any fixed infrastructure, where devices communicate directly, is called:",
     ["Ad hoc network", "Infrastructure network", "Wired LAN", "Backbone network"], 0, PYQ + "Mobile ad hoc networks (MANETs) are an example."),
    ("Consider the statements:\nI. A LAN is usually owned privately by one organisation.\nII. LANs typically have lower data rates than WANs.",
     I_II, 0, "LANs usually have higher data rates (1–10 Gbps and more) than long-distance WAN links."),
    ("Assertion (A): The Internet is not owned by any single organisation.\nReason (R): The Internet is made up of many independently owned networks connected together.",
     AR, 0, "Bodies such as ICANN and the IETF coordinate names, numbers and standards."),
    ("Assertion (A): A PAN can cover an entire city.\nReason (R): A PAN connects devices close to one person.",
     AR, 3, "A PAN covers only a few metres."),
    ("Match:\na. PAN  b. LAN  c. MAN  d. WAN\n1. Bluetooth headset  2. College computer lab  3. City cable-TV network  4. Bank's all-India network",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Network-type matching."),
    ("Which body develops Internet standards published as RFCs?",
     ["IETF (Internet Engineering Task Force)", "IEEE only", "ITU only", "ISO only"], 0, "IEEE makes LAN standards (802.x); ITU-T makes telecom standards."),
    ("A switched WAN in which a dedicated path is set up for the duration of a call, as in the old telephone network, uses:",
     ["Circuit switching", "Packet switching", "Message switching", "Cell switching only"], 0, PYQ + "The Internet uses packet switching."),
    ("A home network in which a Wi-Fi router connects phones and laptops to the Internet is an example of:",
     ["A wireless LAN in infrastructure mode", "A WAN", "An ad hoc network only", "A MAN"], 0, "The router acts as the access point."),
    ("Which device connects a LAN to a different type of network and can translate between protocols?",
     ["Gateway", "Hub", "Repeater", "Passive cable"], 0, PYQ + "Devices are covered in detail in topic U9-06."),
    ("Wi-Fi 6 is the marketing name for:",
     ["IEEE 802.11ax", "IEEE 802.11b", "IEEE 802.3ab", "IEEE 802.15.1"], 0, "Wi-Fi 5 = 802.11ac; Wi-Fi 4 = 802.11n."),
    ("A network spread over a university campus with several buildings connected by fibre is usually called a:",
     ["Campus area network (a large LAN)", "PAN", "WAN", "Satellite network"], 0, PYQ + "It is still under one organisation's control."),
    ("Which statement about WANs is correct?",
     ["They usually use leased lines, MPLS or public networks provided by carriers", "They are limited to one building", "They never use routers", "They are always wireless"], 0,
     "Point-to-point WANs connect two sites; switched WANs connect many."),
    ("Consider the statements:\nI. The Internet uses the TCP/IP protocol suite.\nII. An intranet is open to everyone on the Internet.",
     I_II, 0, "An intranet is private to an organisation."),
]

OSI = [
    ("Which layer of OSI reference model is responsible for decomposition of messages and generation of sequence numbers, in order to ensure correct re-composition, from end-to-end of a network?",
     ["Physical", "Data-link", "Transport", "Application"], 2,
     "The transport layer segments messages and numbers the segments for end-to-end reassembly." + NOTE, "KSET 2023 CS&A · Q63"),
    ("What is the primary function of physical layer in the OSI model?",
     ["Provides routing of packets across networks", "Transmits raw bitstream over the physical medium", "Handles error correction and retransmission",
      "Manages data transfer between applications"], 1,
     "It deals with bits, signals, connectors and the medium." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q99"),
    ("In the TCP/IP model, which layer is responsible for providing end-to-end communication?",
     ["Link layer", "Transport layer", "Application layer", "Network layer"], 1,
     "TCP and UDP provide process-to-process (end-to-end) delivery." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q61"),
    ("Match the following Internal Protocols with their layer in OSI model.\nProtocol\n(a) IP\n(b) TCP\n(c) HTTP\n(d) Ethernet\nLayer\ni) Datalink layer\nii) Application layer\niii) Transport layer\niv) Network layer",
     ["a – i, b – iii, c – iii, d – iv", "a – i, b – iii, c – ii, d – iv", "a – iv, b – iii, c – ii, d – i", "a – iv, b – ii, c – iii, d – i"], 2,
     "IP – network; TCP – transport; HTTP – application; Ethernet – data link." + KLC, "Legislative Council 2024 Computer Operator P2 · Q65"),
    ("Which of the following are the examples of internet layer protocols in the TCP/IP model?\n(a) TCP\n(b) IP\n(c) ARP\n(d) HTTP",
     ["a and b", "b and c", "a, c and d", "a, b and c"], 1,
     "IP and ARP work at the internet (network) layer; TCP is transport and HTTP is application." + KLC, "Legislative Council 2024 Computer Operator P2 · Q57"),
    ("Match the following Network Models with their characteristics\nModel\na. OSI Model\nb. TCP/IP Model\nc. Hybrid Model\nd. Internet Model\nCharacteristics\ni. Used for reliable communication in the Internet\nii. Defines several layers for communication\niii. Represents structure of the Internet\niv. Combines both OSI & TCP/IP Models",
     ["a – ii, b – i, c – iv, d – iii", "a – ii, b – iv, c – i, d – iii", "a – iv, b – ii, c – iii, d – i", "a – iv, b – iii, c – ii, d – i"], 0,
     "OSI defines seven layers; TCP/IP is used in the Internet; the hybrid model combines both; the Internet model shows its structure." + KLC,
     "Legislative Council 2024 Junior Console Operator P2 · Q53"),
    ("Match the following to one or more layers of TCP/IP protocol suite.\na) route determination\nb) Connection to transmission media\nc) Providing services to the end-user\nd) Handling the frames between adjacent nodes\ni. Application layer\nii. Physical layer\niii. Network layer\niv. Data Link layer",
     ["a – i, b – ii, c – iii, d – iv", "a – ii, b – iii, c – iv, d – i", "a – iv, b – iii, c – ii, d – i", "a – iii, b – ii, c – i, d – iv"], 3,
     "Routing – network; media – physical; user services – application; frames between adjacent nodes – data link." + GTTC, "GTTC 2024 Technician Gr-III CS (C1) · Q46"),
    ("Which of the following statements is TRUE regarding the TCP/IP reference model's application layer compared to OSI reference model's application layer, presentation layer and session layer?",
     ["The TCP/IP application layer combines all functionalities of the presentation and session layers of the OSI model",
      "The TCP/IP application layer focusses only on user level data interaction", "The OSI model includes physical addressing at the application layer",
      "The TCP/IP model separates application and session functionalities distinctly"], 0,
     "TCP/IP has no separate session and presentation layers; their work is done in the application layer." + GTTC, "GTTC 2024 Lecturer CS · Q76"),
    ("Match the following\na. Physical\nb. Datalink\nc. Network\nd. Transport\ni. SCTP\nii. IP Sec\niii. PPP\niv. Cables",
     ["a – iv, b – iii, c – ii, d – i", "a – i, b – iii, c – ii, d – iv", "a – ii, b – i, c – iv, d – iii", "a – iv, b – ii, c – i, d – iii"], 0,
     "Cables – physical; PPP – data link; IPsec – network; SCTP – transport." + NOTE, "GFGC 2021 CS · Q103"),
    ("If a file is encrypted and then transmitted over a network using TCP/IP, then which layer handles the encryption and which handles retransmission if the file is lost?",
     ["Application layer - Transport layer", "Presentation layer - Data link layer", "Session layer - Network layer", "Transport layer - Application layer"], 0,
     "TCP/IP has no presentation layer, so encryption is done at the application layer; TCP (transport) retransmits lost segments." + NOTE, "KSET 2025 CS&A · Q86"),
    ("The OSI reference model was developed by:",
     ["ISO (International Organization for Standardization)", "IEEE", "IETF", "ARPA"], 0, PYQ + "OSI = Open Systems Interconnection; it has 7 layers."),
    ("The correct order of OSI layers from bottom to top is:",
     ["Physical, Data link, Network, Transport, Session, Presentation, Application", "Physical, Network, Data link, Transport, Session, Application, Presentation",
      "Application, Presentation, Session, Transport, Network, Data link, Physical", "Data link, Physical, Network, Transport, Session, Presentation, Application"], 0,
     "Memory aid: 'Please Do Not Throw Sausage Pizza Away'."),
    ("Translation, encryption and compression of data are functions of the OSI:",
     ["Presentation layer", "Session layer", "Transport layer", "Network layer"], 0, PYQ + "It deals with the syntax and semantics of the information exchanged."),
    ("Dialog control and synchronisation (checkpoints) are functions of the OSI:",
     ["Session layer", "Presentation layer", "Data link layer", "Physical layer"], 0, "Checkpoints let a long transfer resume after a failure."),
    ("Logical addressing and routing of packets from source to destination across networks are done by the:",
     ["Network layer", "Data link layer", "Transport layer", "Session layer"], 0, PYQ + "The network layer delivers host to host; the data link layer delivers hop to hop."),
    ("The data unit at the data link layer is the:",
     ["Frame", "Segment", "Packet", "Bit"], 0, "Physical – bits; data link – frames; network – packets/datagrams; transport – segments/user datagrams."),
    ("Which layer is responsible for process-to-process delivery, segmentation, flow control and error control end to end?",
     ["Transport layer", "Network layer", "Data link layer", "Physical layer"], 0, PYQ + "It uses port numbers to identify processes."),
    ("The original TCP/IP protocol suite (as described in older texts) had how many layers?",
     ["Four (host-to-network, internet, transport, application) – five in Forouzan's version", "Seven", "Three", "Nine"], 0,
     "Forouzan's five layers: physical, data link, network, transport, application."),
    ("Encapsulation in a layered model means:",
     ["Each layer adds its own header (and sometimes trailer) to the data from the layer above", "Removing headers at the sender", "Encrypting all data", "Compressing data"], 0,
     PYQ + "Decapsulation happens at the receiver."),
    ("In the OSI model, peer-to-peer processes communicate:",
     ["Logically with the same layer on the other machine, using that layer's protocol", "Only physically through the cable", "Without any protocol", "Only at the application layer"], 0,
     "Physically, data moves down the stack, across the medium and up the other stack."),
    ("Consider the statements:\nI. The OSI model is a reference model; TCP/IP is the protocol suite actually used in the Internet.\nII. The TCP/IP suite was developed after the OSI model was completed.",
     I_II, 0, "TCP/IP was developed before OSI."),
    ("Assertion (A): The data link layer is responsible for hop-to-hop (node-to-node) delivery.\nReason (R): The data link layer uses physical (MAC) addresses of the next node.",
     AR, 0, "The network layer is responsible for source-to-destination delivery."),
    ("Assertion (A): Routing is a function of the transport layer.\nReason (R): The transport layer provides process-to-process delivery.",
     AR, 3, "Routing is done at the network layer; R is true."),
    ("Match the protocol with its OSI layer:\na. FTP  b. UDP  c. ICMP  d. PPP\n1. Application  2. Transport  3. Network  4. Data link",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Protocol-to-layer mapping is a favourite."),
    ("Which device works at the physical layer only?",
     ["Repeater / hub", "Router", "Bridge", "Gateway"], 0, "Bridges and switches work at layer 2; routers at layer 3."),
    ("The layer that converts frames into bits for the medium and is concerned with bit synchronisation and line configuration is the:",
     ["Physical layer", "Session layer", "Application layer", "Transport layer"], 0, PYQ + "It also defines transmission mode and topology."),
    ("SMTP, FTP, HTTP and DNS belong to the:",
     ["Application layer", "Transport layer", "Network layer", "Data link layer"], 0, "They use the services of TCP or UDP."),
    ("In the TCP/IP model, the layer corresponding to OSI's network layer is the:",
     ["Internet layer", "Host-to-network layer", "Application layer", "Transport layer"], 0, PYQ + "Its main protocol is IP."),
    ("Which of the following is NOT a function of the data link layer?",
     ["Routing between networks", "Framing", "Flow control between adjacent nodes", "Error control and access control"], 0, "Routing belongs to the network layer."),
    ("Header added by the transport layer contains:",
     ["Source and destination port numbers", "MAC addresses", "Only IP addresses", "The URL"], 0, PYQ + "IP headers carry IP addresses; frame headers carry MAC addresses."),
]

ADDR_SWITCH = [
    ("What is the type of address used in transport layer?",
     ["Logical address", "Names", "Port number", "Link layer address"], 2,
     "Transport-layer addresses are port numbers; IP addresses are logical (network-layer) addresses." + NOTE, "KEA 2026 CS Paper-2 · Q69"),
    ("Datagram switching is done at",
     ["Data link layer", "Network layer", "Transport layer", "Physical layer"], 1,
     "Forouzan: datagram switching is normally done at the network layer." + NOTE, "KEA 2026 CS Paper-2 · Q70"),
    ("What is the maximum length of an MAC address?",
     ["32 bits", "48 bits", "64 bits", "128 bits"], 1,
     "An Ethernet MAC address is 48 bits, written as 12 hexadecimal digits, e.g. 07:01:02:01:2C:4B." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q15"),
    ("Which of the following is NOT a feature of MPLS [Multi Protocol Label Switching]?",
     ["MPLS operates at layer 2.5 between layer 2 and layer 3", "MPLS uses labels to forward packets based on predetermined routes",
      "MPLS allows for traffic engineering by controlling the path of data flows", "MPLS supports only IP traffic and does not work with non-IP protocols"], 3,
     "'Multiprotocol' means MPLS can carry many protocols, not only IP." + KLC, "Legislative Council 2024 Junior Console Operator P2 · Q2"),
    ("In a typical switching process, what is the correct order of operations for a switch when it receives a frame?",
     ["Check MAC address table → Forward the frame → compare with routing table → Determine next hop → Forward pixel",
      "Discard if unknown MAC → Forward the frame → Add MAC address to table", "Receive frame → Determine destination MAC → check MAC address table → forward frame",
      "Forward frame → check MAC address table → Receive frame"], 2,
     "A switch reads the destination MAC, looks it up in its table and forwards (or floods if unknown)." + GTTC, "GTTC 2024 Lecturer CS · Q79"),
    ("The device identification on a network is done by",
     ["TCP/IP", "FTP", "HTTP", "SMTP"], 0,
     "The key's answer: devices are identified by IP addresses under the TCP/IP suite (and MAC addresses on the local link)." + KLC, "Legislative Council 2024 Asst/Jr Asst P2 · Q99"),
    ("The four levels of addresses used in the TCP/IP suite are:",
     ["Physical (MAC), logical (IP), port and specific (application) addresses", "Only IP addresses", "Street, city, state and country", "Bit, byte, word and frame"], 0,
     PYQ + "Specific addresses include e-mail addresses and URLs."),
    ("A port number in TCP/IP is a:",
     ["16-bit number identifying a process on a host", "48-bit hardware number", "32-bit network address", "128-bit address"], 0, "Well-known ports: 0–1023, e.g. HTTP 80, HTTPS 443."),
    ("An IPv4 address is ____ bits long and an IPv6 address is ____ bits long.",
     ["32; 128", "48; 64", "16; 32", "64; 256"], 0, PYQ + "Addressing is covered in detail in U9-07 and U9-08."),
    ("Which address changes at every hop as a packet travels across networks?",
     ["The physical (MAC) address in the frame", "The destination IP address", "The source port", "The URL"], 0, "IP addresses normally stay the same end to end; MAC addresses are hop to hop."),
    ("In circuit switching, the three phases of communication are:",
     ["Connection setup, data transfer and connection teardown", "Framing, routing and delivery", "Encoding, decoding and storing", "Request, reply and caching"], 0,
     PYQ + "Resources are reserved for the whole call."),
    ("Which switching technique does the traditional telephone network use?",
     ["Circuit switching", "Datagram packet switching", "Message switching", "Cell relay only"], 0, "The Internet's network layer uses datagram switching."),
    ("In datagram (connectionless) packet switching:",
     ["Each packet is routed independently and may arrive out of order", "A dedicated path is reserved", "All packets follow the same path always", "No addresses are needed"], 0,
     PYQ + "There is no setup or teardown phase."),
    ("A virtual-circuit network:",
     ["Sets up a path before data transfer, and packets carry a virtual-circuit identifier", "Never sets up a path", "Reserves a physical wire only", "Is used only for e-mail"], 0,
     "ATM and Frame Relay used virtual circuits; it combines features of circuit and datagram switching."),
    ("Message switching is also called:",
     ["Store-and-forward switching of whole messages", "Circuit switching", "Space-division switching", "Cut-through switching"], 0, PYQ + "It is rarely used today."),
    ("A crossbar switch connecting n inputs to m outputs needs:",
     ["n × m crosspoints", "n + m crosspoints", "n crosspoints", "m crosspoints"], 0, "Multistage switches reduce the number of crosspoints."),
    ("Space-division and time-division switches are used in:",
     ["Circuit-switched networks", "Only wireless LANs", "Only optical fibre", "Only software"], 0, PYQ + "A TSI (time-slot interchange) is a time-division switch."),
    ("Compared to circuit switching, packet switching:",
     ["Uses bandwidth more efficiently but may add variable delay", "Reserves bandwidth for each call", "Has no delay at all", "Cannot be used for data"], 0, "Bursty data traffic suits packet switching."),
    ("A cut-through switch:",
     ["Starts forwarding a frame as soon as it reads the destination address", "Waits for the whole frame and checks the CRC first", "Never forwards frames", "Works at layer 7"], 0,
     PYQ + "Store-and-forward switches check the whole frame before forwarding."),
    ("Consider the statements:\nI. In circuit switching, resources are dedicated for the duration of the connection.\nII. In datagram switching, resources are allocated on demand.",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Packets in a datagram network may arrive out of order.\nReason (R): Each packet can take a different route through the network.",
     AR, 0, "The transport layer (TCP) puts them back in order."),
    ("Assertion (A): A MAC address is assigned by the user and changes every time the computer moves to a new network.\nReason (R): IP addresses can change when a computer moves to a new network.",
     AR, 3, "A MAC address is burned into the NIC by the manufacturer (though it can be spoofed); IP addresses are logical."),
    ("Match the address with its layer:\na. MAC address  b. IP address  c. Port number  d. URL / e-mail address\n1. Data link  2. Network  3. Transport  4. Application",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Address-to-layer mapping."),
    ("The first 24 bits of a MAC address identify the:",
     ["Manufacturer (OUI – Organisationally Unique Identifier)", "Network", "Country", "Port"], 0, "The rest identify the individual interface."),
    ("A unicast MAC address has the least significant bit of the first byte set to:",
     ["0 (1 indicates multicast; all 1s is broadcast)", "1", "Any value", "It has no such bit"], 0, PYQ + "The broadcast address is FF:FF:FF:FF:FF:FF."),
    ("In a datagram network, the routing (forwarding) table is based on:",
     ["Destination address", "Virtual-circuit identifier", "Source port", "Frame length"], 0, "In a virtual-circuit network it is based on the VCI."),
    ("A 'well-known' port number used by HTTP is:",
     ["80", "21", "25", "53"], 0, PYQ + "FTP 21 (control), SMTP 25, DNS 53, HTTPS 443."),
    ("Delay in a circuit-switched network after the connection is set up mainly consists of:",
     ["Propagation and data transfer time – no waiting at switches", "Queuing at every switch", "Routing table lookups for each packet", "Retransmissions"], 0,
     "Setup and teardown add delay at the start and end."),
    ("Which statement about virtual circuits is correct?",
     ["All packets of a connection follow the same path and arrive in order", "Each packet chooses its own path", "There is no connection setup", "They are used only in Ethernet hubs"], 0,
     PYQ + "Switching decisions are made using VCIs."),
    ("Consider the statements:\nI. Logical (IP) addresses are needed because physical addresses are only meaningful on a local network.\nII. Port addresses identify the application process on a host.",
     I_II, 2, "Both are correct."),
]

DLL_FRAMING = [
    ("A transmission uses CRC for error detection, the message is 1101011011 and the generator polynomial is G(x) = x⁴ + x + 1. What will be appended at the end of the message?",
     ["1111", "1110", "1101", "1100"], 1,
     "Divide 1101011011 0000 by 10011 (mod 2): the remainder is 1110 (Tanenbaum's example)." + NOTE, "KSET 2025 CS&A · Q84"),
    ("In (7,4) Hamming code ____ bits represent the message and ____ bits for error correction",
     ["4 bits and 3 bits", "3 bits and 4 bits", "4 bits and 7 bits", "7 bits and 4 bits"], 0,
     "A (7,4) code has 7-bit codewords: 4 data bits and 3 parity bits." + NOTE, "PGCET 2026 CS · Q61"),
    ("Which protocol does the PPP protocol provide for handling the capabilities of the connection/link on the network?",
     ["LCP", "NCP", "Both LCP and NCP", "TCP"], 0,
     "PPP's Link Control Protocol sets up, tests and negotiates link options; the Network Control Protocols configure network-layer protocols." + NOTE,
     "PGCET 2023 M.Tech CS · Q41"),
    ("In GSM cellular communication system, a data block of 184 bits is encoded into 224 bits of codeword on the control channel before sending it to a convolution encoder. Determine the number of parity check bits added and the code rate of the block encoder used.",
     ["40 bits, 0.82", "20 bits, 0.5", "80 bits, 1.64", "60 bits, 0.72"], 0,
     "Parity bits = 224 − 184 = 40; code rate = k/n = 184/224 ≈ 0.82." + NOTE, "GFGC 2021 CS · Q105"),
    ("Dividing the stream of bits from the physical layer into manageable units with headers and trailers is called:",
     ["Framing", "Routing", "Multiplexing", "Modulation"], 0, PYQ + "Frames can be fixed-size (as in ATM cells) or variable-size."),
    ("In a byte-oriented protocol, a special byte added before a flag-like byte inside the data is called:",
     ["An escape (ESC) byte – byte stuffing", "A parity byte", "A checksum", "A header"], 0, "If ESC itself appears in the data, it is also preceded by ESC."),
    ("In bit stuffing (as in HDLC), the sender inserts a 0 after:",
     ["Five consecutive 1s", "Six consecutive 1s", "Four consecutive 0s", "Every byte"], 0, PYQ + "This prevents the data from looking like the flag 01111110."),
    ("The HDLC flag pattern is:",
     ["01111110", "11111111", "10101010", "00000000"], 0, "The receiver removes the stuffed 0 that follows five 1s."),
    ("After bit stuffing, the data 0111111101 becomes:",
     ["01111101101", "0111111101", "01111110101", "011111101"], 0, PYQ + "A 0 is inserted after the first five 1s."),
    ("The Hamming distance between 10101 and 11110 is:",
     ["3", "2", "1", "5"], 0, "XOR = 01011, which has three 1s."),
    ("To detect up to s errors, the minimum Hamming distance of a code must be:",
     ["s + 1", "2s + 1", "s", "2s"], 0, PYQ + "To correct up to t errors, d_min must be 2t + 1."),
    ("A code with minimum Hamming distance 5 can correct up to:",
     ["2 errors", "4 errors", "5 errors", "1 error"], 0, "2t + 1 = 5 → t = 2; it can detect up to 4 errors."),
    ("For m = 7 data bits, the number of redundancy bits r in a Hamming code must satisfy 2ʳ ≥ m + r + 1, so r is:",
     ["4", "3", "5", "7"], 0, PYQ + "2⁴ = 16 ≥ 7 + 4 + 1 = 12."),
    ("Using CRC with generator 1011, the CRC appended to the data 1001 is:",
     ["110", "011", "101", "000"], 0, "Divide 1001000 by 1011 (mod 2); the remainder is 110."),
    ("CRC can detect:",
     ["All burst errors of length less than or equal to the degree of the generator polynomial", "No burst errors", "Only single-bit errors", "No errors at all"], 0,
     PYQ + "A good generator also detects all odd numbers of errors if it has the factor (x + 1)."),
    ("The Internet checksum is computed using:",
     ["One's-complement arithmetic of 16-bit words", "Polynomial division", "Hamming codes", "Parity on each bit"], 0, "IP, UDP and TCP headers use it."),
    ("A two-dimensional parity check can:",
     ["Detect all 1-, 2- and 3-bit errors and correct single-bit errors", "Correct all errors", "Detect no burst errors", "Only detect odd errors in one row"], 0,
     PYQ + "Some 4-bit error patterns are missed."),
    ("A linear block code is one in which:",
     ["The XOR of any two valid codewords is another valid codeword", "Codewords have different lengths", "Only one codeword exists", "Parity is never used"], 0, "Hamming codes are linear."),
    ("A cyclic code has the property that:",
     ["A cyclic shift of a codeword gives another codeword", "Codewords are random", "It cannot detect errors", "It uses only one bit"], 0, PYQ + "CRC is a cyclic code."),
    ("Consider the statements:\nI. Forward error correction needs more redundancy than error detection.\nII. Simple parity can correct single-bit errors.",
     I_II, 0, "Simple parity can only detect single-bit errors."),
    ("Assertion (A): Bit stuffing is needed in bit-oriented protocols such as HDLC.\nReason (R): The flag pattern might otherwise appear inside the data.",
     AR, 0, "The receiver de-stuffs the data."),
    ("Assertion (A): A code with d_min = 3 can correct two errors.\nReason (R): To correct t errors, d_min must be at least 2t + 1.",
     AR, 3, "d_min = 3 corrects only one error; R is true."),
    ("Match:\na. Parity bit  b. CRC  c. Checksum  d. Hamming code\n1. Detects odd number of errors  2. Polynomial division  3. One's-complement sum  4. Single-error correction",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Error-control matching."),
    ("The data link layer has two sublayers in IEEE LANs:",
     ["LLC (Logical Link Control) and MAC (Media Access Control)", "TCP and IP", "Session and presentation", "Physical and network"], 0, "MAC handles access to the shared medium."),
    ("The generator x³ + x + 1 written as a binary divisor is:",
     ["1011", "1101", "111", "1001"], 0, PYQ + "Coefficients of x³, x², x¹, x⁰ = 1, 0, 1, 1."),
    ("In a Hamming code with 4 data bits and 3 parity bits, the parity bits are placed at positions:",
     ["1, 2 and 4", "5, 6 and 7", "1, 3 and 5", "2, 4 and 6"], 0, "Parity bits go at powers of two."),
    ("The code rate of a block code that sends n-bit codewords for k data bits is:",
     ["k / n", "n / k", "n − k", "k × n"], 0, PYQ + "A (7,4) Hamming code has rate 4/7 ≈ 0.57."),
    ("If an even-parity bit is used and the data is 1011001, the parity bit is:",
     ["0", "1", "2", "7"], 0, "The data has four 1s, which is already even."),
    ("A burst error of length 5 means:",
     ["The first and last corrupted bits are 5 bits apart (inclusive), with possibly correct bits between", "Exactly 5 consecutive bits are wrong", "5 frames are lost", "5 bits are added"], 0,
     PYQ + "Burst length is measured from the first to the last corrupted bit."),
    ("Consider the statements:\nI. CRC is widely used in Ethernet and Wi-Fi frames.\nII. The checksum is mainly used in the network and transport layers of the Internet.",
     I_II, 2, "Both are correct."),
]

DLL_FLOW = [
    ("When data and acknowledgement are sent in a same frame, it is known as",
     ["Routing", "Synchronization", "Piggy-bagging", "Discretization"], 2,
     "Piggybacking attaches the acknowledgement to an outgoing data frame." + NOTE, "KSET 2024 CS&A · Q86"),
    ("Assume the stop-and-wait system, the bandwidth of the line is 1 Mbps and 1 bit takes 20 milliseconds to make a round trip. Compute bandwidth-delay product if the system data packets are 1000 bits in length. What is the utilization percentage of the link?",
     ["2000 bits, 10%", "2,00,000 bits, 4.5%", "20,000 bits, 4.76%", "200 bits, 50%"], 2,
     "BDP = 10⁶ × 0.02 = 20,000 bits. Sending 1000 bits takes 1 ms, so one cycle is 21 ms: 1/21 ≈ 4.76%." + NOTE, "KEA 2026 CS Paper-2 · Q63"),
    ("Imagine two hosts are connected to each other by a point-to-point and they implement the stop-and-wait protocol.\nIn which of the following scenarios the link utilization is the lowest?",
     ["Longer link length and lower transmission rate", "Longer link length and higher transmission rate", "Shorter link length and lower transmission rate",
      "Shorter link length and higher transmission rate"], 1,
     "Utilisation = Tt / (Tt + 2Tp); a long link (large Tp) with a high rate (small Tt) wastes the most time waiting." + GTTC, "GTTC 2024 Lecturer CS · Q80"),
    ("Flow control in the data link layer means:",
     ["Restricting the amount of data the sender can send before waiting for acknowledgement", "Correcting errors", "Routing frames", "Encrypting frames"], 0,
     PYQ + "It prevents a fast sender from overwhelming a slow receiver."),
    ("In the Stop-and-Wait protocol, the sender:",
     ["Sends one frame and waits for its acknowledgement before sending the next", "Sends all frames at once", "Never waits", "Sends only acknowledgements"], 0, "Sequence numbers 0 and 1 are enough."),
    ("Stop-and-Wait ARQ needs how many sequence numbers?",
     ["2 (0 and 1)", "1", "4", "8"], 0, PYQ + "It uses a 1-bit sequence number; a timer handles lost frames."),
    ("The efficiency of Stop-and-Wait is 1 / (1 + 2a), where a is:",
     ["Propagation time ÷ transmission time", "Transmission time ÷ propagation time", "Bandwidth × delay", "Frame size ÷ window size"], 0, "When a is large, efficiency is very low."),
    ("A frame takes 1 ms to transmit and the one-way propagation time is 10 ms. The Stop-and-Wait efficiency is about:",
     ["4.8%", "50%", "10%", "91%"], 0, PYQ + "1 / (1 + 2 × 10) = 1/21 ≈ 4.76%."),
    ("In Go-Back-N ARQ with m-bit sequence numbers, the maximum sender window size is:",
     ["2ᵐ − 1", "2ᵐ", "2ᵐ⁻¹", "m"], 0, "The receiver window size is 1."),
    ("In Selective Repeat ARQ with m-bit sequence numbers, the maximum sender and receiver window size is:",
     ["2ᵐ⁻¹", "2ᵐ − 1", "2ᵐ", "1"], 0, PYQ + "With m = 3, windows can be at most 4."),
    ("In Go-Back-N, when a frame is lost or damaged:",
     ["The sender resends that frame and all frames sent after it", "Only that frame is resent", "No frames are resent", "The connection is closed"], 0, "The receiver discards out-of-order frames."),
    ("In Selective Repeat ARQ:",
     ["Only the damaged or lost frames are retransmitted; the receiver buffers out-of-order frames", "All frames are resent", "The window size is always 1", "No acknowledgements are used"], 0,
     PYQ + "It uses bandwidth better but needs more receiver buffer and logic."),
    ("A sliding-window protocol with a 3-bit sequence number field uses sequence numbers:",
     ["0 to 7", "0 to 3", "1 to 8", "0 to 15"], 0, "Numbers wrap around modulo 2³."),
    ("A negative acknowledgement (NAK) is used in Selective Repeat to:",
     ["Ask for a specific damaged frame to be resent quickly", "Confirm all frames", "Close the window", "Reset the link"], 0, PYQ + "It avoids waiting for the timer to expire."),
    ("HDLC (High-level Data Link Control) defines three types of frames:",
     ["Information (I), Supervisory (S) and Unnumbered (U) frames", "Data, voice and video frames", "Small, medium and large frames", "Unicast, multicast and broadcast frames"], 0,
     "S-frames carry control such as RR, RNR, REJ and SREJ; U-frames carry link management."),
    ("The two common transfer modes of HDLC are:",
     ["Normal Response Mode (NRM) and Asynchronous Balanced Mode (ABM)", "Simplex and duplex", "Circuit and packet", "Baseband and broadband"], 0,
     PYQ + "In NRM a primary station polls secondaries; in ABM both stations are equal."),
    ("PPP (Point-to-Point Protocol) is:",
     ["A byte-oriented protocol used for point-to-point links such as dial-up and DSL", "A bit-oriented LAN protocol", "A routing protocol", "A transport protocol"], 0,
     "It uses LCP for link setup and authentication protocols PAP and CHAP."),
    ("PAP and CHAP in PPP are used for:",
     ["Authentication", "Error correction", "Routing", "Compression only"], 0, PYQ + "CHAP is more secure because the password is never sent in clear text."),
    ("Piggybacking improves efficiency because:",
     ["Acknowledgements travel inside data frames instead of separate frames", "It removes the need for sequence numbers", "It adds more frames", "It disables flow control"], 0,
     "It is used in bidirectional (full-duplex) communication."),
    ("Consider the statements:\nI. Go-Back-N receiver window size is 1.\nII. Selective Repeat receiver can accept out-of-order frames.",
     I_II, 2, "Both are correct."),
    ("Assertion (A): Sliding-window protocols improve link utilisation over Stop-and-Wait.\nReason (R): Several frames can be in transit before an acknowledgement arrives.",
     AR, 0, "The window should cover the bandwidth-delay product."),
    ("Assertion (A): In Go-Back-N, the sender window can be 2ᵐ.\nReason (R): A window of 2ᵐ could make a new frame indistinguishable from a retransmitted one.",
     AR, 3, "The maximum is 2ᵐ − 1; R explains why."),
    ("Match:\na. Stop-and-Wait  b. Go-Back-N  c. Selective Repeat  d. Piggybacking\n1. Window of 1  2. Resend from the lost frame onwards  3. Resend only lost frames  4. ACK carried in a data frame",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "ARQ protocol matching."),
    ("A link of 1 Mbps has a round-trip time of 20 ms and frames of 1000 bits. To keep the link fully busy, the sender window should be about:",
     ["21 frames", "1 frame", "2 frames", "200 frames"], 0, "BDP = 20,000 bits = 20 frames, plus the frame being sent ≈ 21."),
    ("In Stop-and-Wait ARQ, a timer is used to:",
     ["Resend a frame if its acknowledgement does not arrive in time", "Measure bandwidth", "Synchronise clocks", "Delete frames"], 0, PYQ + "Sequence numbers prevent duplicate frames from being accepted."),
    ("The ACK number in sliding-window protocols usually tells the sender:",
     ["The sequence number of the next frame the receiver expects", "The number of the last frame received", "The window size only", "The frame length"], 0, "This is cumulative acknowledgement in Go-Back-N."),
    ("In HDLC, the control field of an S-frame with code REJ means:",
     ["Reject – go back N, resend from the indicated frame", "Receive ready", "Receive not ready", "Selective reject"], 0, PYQ + "SREJ asks for one frame only (Selective Repeat)."),
    ("Which protocol is typically used on the link between a home router and the ISP over DSL (as PPPoE)?",
     ["PPP", "HDLC only", "Token Ring", "FDDI"], 0, "PPPoE carries PPP frames over Ethernet."),
    ("The main difference between flow control and error control is:",
     ["Flow control limits the rate of sending; error control detects and recovers lost or damaged frames", "They are the same", "Error control limits the rate", "Flow control fixes damaged bits"], 0,
     PYQ + "In the data link layer both are usually combined (ARQ)."),
    ("Consider the statements:\nI. HDLC is a bit-oriented protocol.\nII. PPP is a byte-oriented protocol.",
     I_II, 2, "HDLC uses bit stuffing; PPP uses byte stuffing."),
]

TOPICS = {
    "Computer Networks & Topologies": [("1 · Network Topologies and Line Configuration", TOPOLOGY),
                                       ("2 · LAN, MAN, WAN, Wireless Networks and the Internet", NETTYPES)],
    "Network Models": [("1 · Layered Architecture – OSI Model and TCP/IP Suite", OSI),
                       ("2 · Addresses (Physical, Logical, Port, Specific) and Switching Techniques", ADDR_SWITCH)],
    "Data Link Layer": [("1 · Framing, Error Detection and Correction (Parity, CRC, Hamming)", DLL_FRAMING),
                        ("2 · Flow and Error Control – Stop-and-Wait, Sliding Window, HDLC and PPP", DLL_FLOW)],
}
