"""Paper 2 · Unit 9 · P2-U9-01 Data Communication – Part 1 and P2-U9-02 Data Communication – Part 2 (2 topics × 2 sub-topics × 30).
References: Behrouz A. Forouzan, Data Communications and Networking (5th ed., chs. 1, 3–7, 10); Andrew S. Tanenbaum, Computer
Networks (ch. 2). Each set mixes REAL previous-year questions (exact wording and printed option order, `source` = paper and question
number) with new ones. Official answers come from KEA's final keys: Legislative Council Secretariat 2024 Data Entry Operator P2
(booklet A1; final key 09-04-2025) and GTTC 2024 Lecturer CS (booklet A1; final key 30-12-2024). KSET 2023–25 and KEA 2026 questions
are reused from packs/pyq-p2.json; those and the GFGC 2021 CS answers were worked out by ExamSim. Numerical answers (Nyquist,
Shannon, dB, delays, throughput, bandwidth) were checked by computation."""
from packlib import AR, I_II

PYQ = "PYQ pattern (KEA / KSET papers). "
KLC = " (Official answer: KEA final key, Legislative Council Secretariat exam 2024.)"
GTTC = " (Official answer: KEA final key, GTTC recruitment 2024.)"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

BASICS = [
    ("Data transmission used in walkie-talkie is",
     ["Simplex", "Duplex", "Half-duplex", "Complex"], 2,
     "Both sides can talk, but only one at a time (press-to-talk)." + KLC, "Legislative Council 2024 Data Entry Operator P2 · Q88"),
    ("Simplex communication system can transmit data",
     ["In one direction", "In both directions", "Switch direction each time the direction of data transfer reverses", "None of the above"], 0,
     "Examples: keyboard to computer, radio and TV broadcasting." + KLC, "Legislative Council 2024 Data Entry Operator P2 · Q90"),
    ("The five components of a data communication system are:",
     ["Message, sender, receiver, transmission medium and protocol", "CPU, RAM, ROM, disk and monitor", "Bits, bytes, words, frames and packets", "Client, server, router, switch and hub"], 0,
     PYQ + "Forouzan's basic model."),
    ("The fundamental characteristics of an effective data communication system are:",
     ["Delivery, accuracy, timeliness and jitter", "Speed, colour, size and cost", "Voltage, current, power and resistance", "Encryption, compression, caching and paging"], 0,
     "Jitter is the variation in packet arrival time, important for audio and video."),
    ("A set of rules that governs data communication is called a:",
     ["Protocol", "Medium", "Signal", "Topology"], 0, PYQ + "Its key elements are syntax, semantics and timing."),
    ("The three key elements of a protocol are:",
     ["Syntax, semantics and timing", "Bits, bytes and frames", "Sender, receiver and medium", "Speed, cost and size"], 0,
     "Syntax = format, semantics = meaning, timing = when and how fast."),
    ("A telephone conversation in which both people can talk and listen at the same time is an example of:",
     ["Full-duplex transmission", "Simplex transmission", "Half-duplex transmission", "Broadcast only"], 0, PYQ + "The channel capacity is shared in both directions at once."),
    ("A signal that can have an infinite number of values in a range is:",
     ["Analog", "Digital", "Discrete", "Binary"], 0, "A digital signal has a limited number of defined values."),
    ("A sine wave is completely described by three characteristics:",
     ["Peak amplitude, frequency and phase", "Bit rate, baud rate and voltage", "Speed, size and colour", "Bandwidth, latency and jitter"], 0,
     PYQ + "Wavelength = propagation speed × period."),
    ("A signal with frequency 1 kHz has a period of:",
     ["1 ms", "1 s", "1 µs", "10 ms"], 0, "Period = 1 / frequency = 1 / 1000 s."),
    ("A sine wave that is offset by one-quarter of a cycle with respect to time 0 has a phase of:",
     ["90°", "180°", "45°", "360°"], 0, PYQ + "One full cycle = 360°."),
    ("A periodic composite signal contains frequencies from 100 Hz to 1000 Hz. Its bandwidth is:",
     ["900 Hz", "1100 Hz", "1000 Hz", "100 Hz"], 0, "Bandwidth = highest frequency − lowest frequency."),
    ("According to Fourier analysis, any composite signal is a combination of:",
     ["Simple sine waves with different frequencies, amplitudes and phases", "Square waves only", "Random noise", "Digital pulses only"], 0,
     PYQ + "A digital signal is a composite analog signal with (in theory) infinite bandwidth."),
    ("The number of bits sent in one second is called the:",
     ["Bit rate", "Baud rate", "Bit length", "Frequency"], 0, "The bit interval is the time for one bit = 1 / bit rate."),
    ("A digital signal has 8 levels. How many bits does each level represent?",
     ["3", "8", "2", "4"], 0, PYQ + "Bits per level = log₂ L = log₂ 8."),
    ("Transmitting a digital signal without changing it to analog, using a low-pass channel, is called:",
     ["Baseband transmission", "Broadband transmission", "Modulation", "Multiplexing"], 0, "Broadband transmission uses modulation to send over a band-pass channel."),
    ("The loss of energy of a signal as it travels through a medium is called:",
     ["Attenuation", "Distortion", "Noise", "Jitter"], 0, PYQ + "Amplifiers or repeaters restore the signal."),
    ("A change in the shape of a signal because its frequency components travel at different speeds is called:",
     ["Distortion", "Attenuation", "Noise", "Crosstalk"], 0, "It matters for composite signals."),
    ("The effect of one wire on another, as when you hear another call on a telephone line, is:",
     ["Crosstalk", "Thermal noise", "Impulse noise", "Attenuation"], 0, PYQ + "Thermal noise comes from random electron motion; impulse noise from spikes like lightning."),
    ("A signal loses half its power. The loss in decibels is about:",
     ["−3 dB", "−10 dB", "−1 dB", "−6 dB"], 0, "dB = 10 log₁₀(P₂/P₁) = 10 log₁₀(0.5) ≈ −3."),
    ("Which of the following is an example of half-duplex communication?",
     ["Walkie-talkie / CB radio", "Television broadcast", "Telephone call", "Keyboard input"], 0, PYQ + "TV is simplex; telephone is full duplex."),
    ("In data communication, 'timeliness' means:",
     ["Data must be delivered in time; late real-time data (like video) is useless", "Data must be compressed", "Data must be encrypted", "Data must be delivered only at night"], 0,
     "It is one of the four fundamental characteristics."),
    ("The physical path through which a message travels from sender to receiver is the:",
     ["Transmission medium", "Protocol", "Message", "Receiver"], 0, PYQ + "Examples: twisted-pair cable, fibre, radio waves."),
    ("Consider the statements:\nI. In full-duplex mode, both stations can transmit and receive simultaneously.\nII. In simplex mode, only one of the two devices can transmit.",
     I_II, 2, "Both statements are correct."),
    ("Assertion (A): A digital signal needs a channel of very large bandwidth to be sent without distortion.\nReason (R): A digital signal is a composite analog signal with an infinite range of frequencies.",
     AR, 0, "In practice a low-pass channel of limited bandwidth gives an approximation."),
    ("Assertion (A): Attenuation increases signal strength over distance.\nReason (R): Amplifiers are used to compensate for attenuation.",
     AR, 3, "Attenuation is a loss of strength."),
    ("Match:\na. Simplex  b. Half-duplex  c. Full-duplex\n1. Radio broadcast  2. Walkie-talkie  3. Telephone",
     ["a-1, b-2, c-3", "a-2, b-1, c-3", "a-3, b-2, c-1", "a-1, b-3, c-2"], 0, PYQ + "Basic transmission-mode matching."),
    ("A periodic signal completes one cycle in 4 ms. Its frequency is:",
     ["250 Hz", "4 Hz", "400 Hz", "25 Hz"], 0, "f = 1/T = 1/0.004."),
    ("Which of the following is a digital signal characteristic, NOT an analog one?",
     ["Bit interval", "Peak amplitude", "Frequency", "Phase"], 0, PYQ + "Bit interval and bit rate describe digital signals."),
    ("Signals sent over long distances are restored by a regenerating device called a:",
     ["Repeater", "Router", "Gateway", "Modem"], 0, "A repeater regenerates the original bit pattern rather than amplifying noise."),
]

CHANNEL = [
    ("The bandwidth of a noisy channel is 3000 Hz and whose signal to noise ratio is 3162. What will be the maximum data rate of the channel?",
     ["≅ 37524 bps", "≅ 36523 bps", "≅ 35922 bps", "≅ 34890 bps"], 3,
     "Shannon: C = 3000 × log₂(1 + 3162) ≈ 3000 × 11.63 ≈ 34,880 bps." + NOTE, "KSET 2025 CS&A · Q83"),
    ("A system transmits data at 1200 bytes per second using 4 bits per signal limit. What is the baud rate?",
     ["2400 Baud", "9600 Baud", "38400 Baud", "4800 Baud"], 0,
     "1200 × 8 = 9600 bps; 9600 / 4 bits per signal = 2400 baud." + NOTE, "KSET 2025 CS&A · Q81"),
    ("A company has a secure wireless network with a maximum throughput of 600 Mbps. If 10 users are connected simultaneously and each is using 30 Mbps of bandwidth, what percentage of the total throughput is being utilized?",
     ["25%", "50%", "75%", "100%"], 1,
     "10 × 30 = 300 Mbps, which is half of 600 Mbps." + GTTC, "GTTC 2024 Lecturer CS · Q81"),
    ("For a noiseless channel of bandwidth B and L signal levels, the maximum bit rate (Nyquist) is:",
     ["2B log₂ L", "B log₂ (1 + SNR)", "B / L", "2B / L"], 0, PYQ + "Shannon's B log₂(1 + SNR) is for noisy channels."),
    ("A noiseless channel with a bandwidth of 3000 Hz transmits a signal with two signal levels. The maximum bit rate is:",
     ["6000 bps", "3000 bps", "12000 bps", "1500 bps"], 0, "2 × 3000 × log₂ 2 = 6000 bps."),
    ("The same 3000 Hz noiseless channel with four signal levels can carry:",
     ["12000 bps", "6000 bps", "24000 bps", "9000 bps"], 0, PYQ + "2 × 3000 × log₂ 4 = 12000 bps."),
    ("A noiseless 20 kHz channel uses 8 signal levels. Its maximum bit rate is:",
     ["120 kbps", "60 kbps", "160 kbps", "40 kbps"], 0, "2 × 20,000 × 3 = 120,000 bps."),
    ("A channel with 1 MHz bandwidth has SNR = 63. Its Shannon capacity is:",
     ["6 Mbps", "63 Mbps", "1 Mbps", "12 Mbps"], 0, PYQ + "1 × 10⁶ × log₂(64) = 6 × 10⁶ bps."),
    ("If the SNR of a channel is 0 (signal power is zero compared to noise), the Shannon capacity is:",
     ["Zero", "Equal to the bandwidth", "Infinite", "Twice the bandwidth"], 0, "log₂(1 + 0) = 0 – no data can be sent."),
    ("An SNR of 1000 corresponds to:",
     ["30 dB", "10 dB", "3 dB", "100 dB"], 0, PYQ + "SNR_dB = 10 log₁₀ 1000 = 30."),
    ("Increasing the number of signal levels in Nyquist's formula:",
     ["Increases the bit rate but makes the receiver's job harder and less reliable", "Always reduces errors", "Reduces bandwidth", "Has no effect"], 0,
     "Shannon's limit caps what noise allows."),
    ("The time it takes for a bit to travel from the sender to the receiver over the medium is the:",
     ["Propagation time", "Transmission time", "Queuing time", "Processing time"], 0, PYQ + "Propagation time = distance / propagation speed."),
    ("A signal travels 12,000 km at 2.4 × 10⁸ m/s. The propagation time is:",
     ["50 ms", "5 ms", "500 ms", "0.5 ms"], 0, "12 × 10⁶ / 2.4 × 10⁸ = 0.05 s."),
    ("Transmission time of a 2.5 KB (20,000-bit) message on a 1 Gbps link is:",
     ["20 µs", "20 ms", "2 ms", "200 µs"], 0, PYQ + "Transmission time = message size / bandwidth."),
    ("Latency (total delay) of a message is the sum of:",
     ["Propagation time, transmission time, queuing time and processing delay", "Only bandwidth", "Only jitter", "Bit rate and baud rate"], 0,
     "For short messages on long links propagation dominates."),
    ("The bandwidth-delay product of a 1 Mbps link with a 2 ms delay is:",
     ["2000 bits", "500 bits", "2 Mbits", "1000 bits"], 0, PYQ + "It is the number of bits that can 'fill' the link."),
    ("A network with 10 Mbps bandwidth passes an average of 12,000 frames per minute, each of 10,000 bits. Its throughput is:",
     ["2 Mbps", "10 Mbps", "12 Mbps", "1 Mbps"], 0, "12,000 × 10,000 / 60 = 2,000,000 bps – one-fifth of the bandwidth."),
    ("Throughput is best defined as:",
     ["The actual rate at which data passes through a network", "The maximum possible frequency range", "The delay of one bit", "The number of signal levels"], 0,
     PYQ + "Throughput ≤ bandwidth (bit rate) of the link."),
    ("In networking, 'bandwidth' is used in two senses:",
     ["Range of frequencies in hertz, and bit rate in bits per second", "Cable length and colour", "Number of users and routers", "Jitter and latency"], 0,
     "An increase in hertz bandwidth means an increase in bps bandwidth."),
    ("Baud rate refers to:",
     ["The number of signal elements (symbols) per second", "The number of bits per second", "The number of errors per second", "The number of frames per second"], 0,
     PYQ + "Bit rate = baud rate × bits per signal element."),
    ("A 16-QAM signal at 1000 baud carries a bit rate of:",
     ["4000 bps", "16000 bps", "1000 bps", "250 bps"], 0, "16-QAM carries log₂ 16 = 4 bits per symbol."),
    ("Jitter in a network refers to:",
     ["Variation in packet delay", "Total loss of a packet", "Signal attenuation", "Encryption delay"], 0, PYQ + "Real-time audio and video suffer from jitter."),
    ("We need to send 265 kbps over a noiseless 20 kHz channel. Using Nyquist, the number of signal levels needed is about:",
     ["128 (since 98.7 is not a power of 2)", "8", "16", "64"], 0, "265,000 = 2 × 20,000 × log₂ L → log₂ L ≈ 6.6 → L ≈ 98.7; choose 128 levels (or 64 and lower the rate)."),
    ("Consider the statements:\nI. The Shannon capacity gives the upper limit of the data rate of a noisy channel.\nII. Using more signal levels can increase the rate above the Shannon limit.",
     I_II, 0, "No method can exceed the Shannon capacity."),
    ("Assertion (A): On a satellite link, propagation time can be much larger than transmission time.\nReason (R): Satellite signals travel very long distances (about 36,000 km each way).",
     AR, 0, "Round trip to a geostationary satellite takes about a quarter of a second."),
    ("Assertion (A): Throughput is always equal to bandwidth.\nReason (R): Bandwidth is the potential capacity of a link.",
     AR, 3, "Throughput is the actual rate achieved and is usually lower than the bandwidth."),
    ("Match:\na. Nyquist  b. Shannon  c. Baud  d. Latency\n1. Noiseless channel bit rate  2. Noisy channel capacity  3. Signal elements per second  4. Total delay",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "A frequent matching question."),
    ("Telephone lines have a bandwidth of about 3000 Hz and SNR around 3162 (35 dB). Their theoretical maximum capacity is about:",
     ["35 kbps", "3 kbps", "350 kbps", "3.5 Mbps"], 0, "≈ 3000 × 11.62 ≈ 34.86 kbps (Forouzan's classic example)."),
    ("The unit used to express the ratio of two signal powers on a logarithmic scale is:",
     ["Decibel (dB)", "Hertz", "Baud", "Watt"], 0, PYQ + "dB = 10 log₁₀(P₂/P₁)."),
    ("Doubling the bandwidth of a noiseless channel (same number of levels) will:",
     ["Double the maximum bit rate", "Halve the bit rate", "Leave the bit rate unchanged", "Make the channel noisy"], 0, "Nyquist bit rate is directly proportional to B."),
]

ENCODING = [
    ("In Ethernet that uses Manchester encoding, the bit rate is",
     ["thrice the baud rate", "twice the baud rate", "half the baud rate", "same as the baud rate"], 2,
     "Manchester needs two signal elements per bit, so the baud rate is twice the bit rate." + NOTE, "KSET 2023 CS&A · Q62"),
    ("If a carrier modulated by a digital bit stream has one of the possible phases of 0, 90, 180 and 270 degrees, such modulation is called as",
     ["BPSK", "QAM", "MSK", "QPSK"], 3,
     "Four phases, each carrying 2 bits, is quadrature phase-shift keying." + NOTE, "KSET 2024 CS&A · Q81"),
    ("The process of dividing an analog signal into a string of discrete outputs, each denoting a constant amplitude is called as",
     ["Strobing", "Amplification", "Quantization", "Conditioning"], 2,
     "Quantisation maps sampled amplitudes onto a finite set of levels." + NOTE, "KSET 2024 CS&A · Q85"),
    ("____ is a digital modulation technique where the amplitude of a carrier wave is varied in accordance with the digital data being transferred, while frequency and phase remain constant.",
     ["Amplitude shift keying", "Phase shift keying", "Frequency shift keying", "Quadrature amplitude modulation"], 0,
     "ASK varies only the amplitude." + NOTE, "KSET 2025 CS&A · Q82"),
    ("Suppose a digitized voice channel is made by digitizing 6 kHz bandwidth analog voice signal. It is required to sample the signal at twice the highest frequency (two samples per Hertz). What is the bit rate required, if it is assumed that each sample requires 8 bits ?",
     ["64 kbps", "96 kbps", "128 kbps", "256 kbps"], 1,
     "12,000 samples/s × 8 bits = 96,000 bps." + NOTE, "GFGC 2021 CS · Q102"),
    ("Five channels, each with a 100 kHz bandwidth are to be multiplexed together. What is the minimum bandwidth of the link if there is a need for a guard band of 10 kHz between the channels to prevent interference?",
     ["500 kHz", "540 kHz", "550 kHz", "100 kHz"], 1,
     "5 × 100 + 4 guard bands × 10 = 540 kHz." + NOTE, "KSET 2025 CS&A · Q90"),
    ("Converting digital data to a digital signal is called:",
     ["Line coding", "Modulation", "Sampling", "Demodulation"], 0, PYQ + "Examples: NRZ, RZ, Manchester, AMI."),
    ("In NRZ-I (non-return-to-zero inverted) encoding, a '1' bit is represented by:",
     ["An inversion (transition) at the beginning of the bit", "No change in level", "A positive voltage always", "A zero voltage"], 0, "In NRZ-L the level itself represents the bit."),
    ("Differential Manchester encoding always has a transition:",
     ["In the middle of each bit (for synchronisation); a transition at the start means 0", "Only for 1s", "Never", "Only at the end of the frame"], 0,
     PYQ + "It is used in Token Ring (IEEE 802.5)."),
    ("Block coding schemes such as 4B/5B are used to:",
     ["Provide enough transitions for synchronisation and allow error detection", "Encrypt data", "Compress data", "Increase signal power"], 0,
     "4B/5B maps each 4-bit group to a 5-bit code with no long runs of zeros; used in 100Base-FX/TX."),
    ("The overhead of 4B/5B block coding is:",
     ["25% (5 bits sent for every 4 data bits)", "50%", "100%", "0%"], 0, PYQ + "8B/10B has the same 25% overhead."),
    ("Scrambling techniques such as B8ZS and HDB3 are used to:",
     ["Replace long runs of zeros so that synchronisation is not lost", "Encrypt data", "Increase bandwidth", "Add parity bits"], 0, "B8ZS is used in North America; HDB3 in Europe and Japan."),
    ("Pulse Code Modulation (PCM) converts an analog signal to digital in three steps:",
     ["Sampling, quantising and encoding", "Modulating, filtering and amplifying", "Framing, routing and switching", "Compressing, encrypting and sending"], 0,
     PYQ + "Nyquist: sample at least twice the highest frequency."),
    ("Voice of 4 kHz bandwidth sampled at the Nyquist rate with 8 bits per sample needs a bit rate of:",
     ["64 kbps", "32 kbps", "8 kbps", "128 kbps"], 0, "8000 samples/s × 8 bits = 64 kbps (a standard telephone channel, DS0)."),
    ("Converting digital data to an analog signal (for example in a modem) uses:",
     ["Digital-to-analog conversion: ASK, FSK, PSK and QAM", "Line coding only", "PCM", "Delta modulation"], 0, PYQ + "QAM changes both amplitude and phase."),
    ("Analog-to-analog modulation techniques are:",
     ["AM, FM and PM", "ASK, FSK and PSK", "NRZ and RZ", "PCM and DM"], 0, "Radio broadcasting uses AM and FM."),
    ("Multiplexing is the technique of:",
     ["Sending several signals simultaneously over a single link", "Encrypting signals", "Amplifying signals", "Converting analog to digital"], 0, PYQ + "A multiplexer (MUX) combines and a demultiplexer (DEMUX) separates."),
    ("Frequency-Division Multiplexing (FDM) is used for:",
     ["Analog signals – each signal gets its own frequency band", "Only digital signals", "Only fibre optics", "Only Ethernet"], 0, "Radio and TV broadcasting and older telephone trunks use FDM."),
    ("Wavelength-Division Multiplexing (WDM) is used in:",
     ["Optical fibre", "Twisted pair", "Coaxial cable only", "Infrared remote controls"], 0, PYQ + "WDM is FDM applied to light."),
    ("Four sources each sending at 250 kbps are combined by synchronous TDM (no framing bits). The link rate is:",
     ["1 Mbps", "250 kbps", "4 Mbps", "500 kbps"], 0, "Synchronous TDM link rate = n × source rate."),
    ("In synchronous TDM, a time slot is wasted when:",
     ["Its source has no data to send", "The link is full", "Two sources collide", "The frame has parity"], 0, PYQ + "Statistical TDM gives slots dynamically to active sources only."),
    ("Spread spectrum techniques such as FHSS and DSSS are used mainly to:",
     ["Make transmission secure and resistant to interference by spreading the signal over a wider band", "Reduce bandwidth", "Compress data", "Increase noise"], 0,
     "They are used in Wi-Fi and Bluetooth."),
    ("Consider the statements:\nI. Manchester encoding has no DC component and is self-synchronising.\nII. NRZ-L has no problem with long runs of zeros.",
     I_II, 0, "NRZ loses synchronisation during long runs of the same bit."),
    ("Assertion (A): QAM can carry more bits per symbol than simple PSK.\nReason (R): QAM varies both the amplitude and the phase of the carrier.",
     AR, 0, "64-QAM carries 6 bits per symbol."),
    ("Assertion (A): FDM is a digital multiplexing technique.\nReason (R): In FDM, signals are separated by frequency bands with guard bands between them.",
     AR, 3, "FDM is an analog technique; TDM is the digital one."),
    ("Match:\na. ASK  b. FSK  c. PSK  d. QAM\n1. Amplitude changes  2. Frequency changes  3. Phase changes  4. Amplitude and phase change",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Digital-to-analog conversion matching."),
    ("The minimum sampling rate required to reconstruct a signal with highest frequency f is:",
     ["2f (Nyquist rate)", "f", "f/2", "4f"], 0, "Sampling below 2f causes aliasing."),
    ("Delta modulation differs from PCM in that it:",
     ["Sends only one bit per sample showing whether the signal went up or down", "Sends 8 bits per sample", "Uses no sampling", "Is an analog method"], 0, PYQ + "It is simpler but needs a higher sampling rate."),
    ("BPSK carries how many bits per signal element?",
     ["1", "2", "4", "8"], 0, "BPSK has two phases (0° and 180°); QPSK carries 2 bits."),
    ("A modem is so called because it performs:",
     ["Modulation and demodulation", "Multiplexing and demultiplexing", "Encoding and encrypting", "Routing and switching"], 0, PYQ + "It converts between digital data and analog signals on telephone lines."),
]

MEDIA = [
    ("For the following encoding/decoding schemes, with respect to fast ethernet:\n(i) 100 Base-TX\n(ii) 100 Base-FX\n(iii) 100 Base-T4\nIdentify the medium support for each of the above.",
     ["Fiber, UTP or STP, UTP", "UTP or STP, Fiber, UTP", "UTP, UTP or STP, Fiber", "Fiber, UTP, UTP or STP"], 1,
     "100Base-TX: two pairs of Cat 5 UTP or STP; 100Base-FX: fibre; 100Base-T4: four pairs of Cat 3 UTP." + NOTE, "KEA 2026 CS Paper-2 · Q71"),
    ("Transmission media are broadly classified as:",
     ["Guided (wired) and unguided (wireless)", "Analog and digital", "Simplex and duplex", "Serial and parallel"], 0, PYQ + "Guided: twisted pair, coaxial, fibre. Unguided: radio, microwave, infrared."),
    ("Wires are twisted in twisted-pair cable mainly to:",
     ["Reduce noise and crosstalk", "Increase cable length", "Make the cable stronger", "Carry light"], 0, "Twisting makes interference affect both wires equally, so it cancels at the receiver."),
    ("The connector most commonly used with UTP Ethernet cable is:",
     ["RJ-45", "BNC", "RJ-11", "ST"], 0, PYQ + "RJ-11 is for telephone lines; BNC is for coaxial cable; ST/SC for fibre."),
    ("Cable TV networks traditionally use:",
     ["Coaxial cable", "Twisted pair", "Infrared", "Microwave only"], 0, "Coaxial cable has a central conductor, insulation, metallic shield and outer jacket."),
    ("Optical fibre carries signals by:",
     ["Total internal reflection of light", "Electrical current", "Radio waves", "Magnetic fields"], 0, PYQ + "The core has a higher refractive index than the cladding."),
    ("Which statement about optical fibre is correct?",
     ["It has very high bandwidth and is immune to electromagnetic interference", "It is cheaper and easier to install than copper", "It carries electricity", "It cannot carry data over long distances"], 0,
     "Its disadvantages are cost, installation skill and one-way light propagation."),
    ("Single-mode fibre, compared to multimode fibre:",
     ["Has a very narrow core, less dispersion and is used for long distances", "Has a thick core and is used for short links", "Uses many light paths", "Cannot use lasers"], 0,
     PYQ + "Multimode step-index and graded-index fibres are used for shorter links."),
    ("Microwave communication requires:",
     ["Line-of-sight between unidirectional antennas", "No antennas", "Copper cable", "Light pulses"], 0, "Towers are placed on hills or tall buildings; satellites also use microwaves."),
    ("Radio waves are mostly:",
     ["Omnidirectional and able to penetrate walls", "Unidirectional and blocked by walls", "Used only in fibre", "Limited to a room"], 0, PYQ + "AM/FM radio and paging use radio waves."),
    ("Infrared waves are used for short-range communication such as TV remotes because they:",
     ["Cannot penetrate walls, so they do not interfere with devices in other rooms", "Travel thousands of kilometres", "Need copper wires", "Are omnidirectional through walls"], 0, "IrDA was used for short-range data links."),
    ("In baseband transmission, the whole bandwidth of the medium is used for:",
     ["One digital signal", "Many analog channels", "Only radio signals", "Only light signals"], 0, PYQ + "Ethernet (10Base-T) is baseband; cable TV is broadband."),
    ("Broadband transmission:",
     ["Divides the medium's bandwidth into several channels using modulation", "Sends a single digital signal", "Uses only fibre", "Cannot carry data"], 0, "Cable modems and DSL use broadband techniques."),
    ("Category 6 UTP cable is commonly used for Ethernet speeds up to:",
     ["1 Gbps (10 Gbps for short runs)", "10 Mbps only", "100 Kbps", "1 Tbps"], 0, PYQ + "Cat 5e supports 1 Gbps; Cat 6A 10 Gbps up to 100 m."),
    ("A single-bit error means:",
     ["Only one bit of a data unit is changed", "Two or more bits are changed", "The whole frame is lost", "The frame is duplicated"], 0, "A burst error changes two or more bits, not necessarily consecutive."),
    ("Burst errors are more likely than single-bit errors in serial transmission because:",
     ["Noise usually lasts longer than one bit duration", "Single bits are never sent", "Fibre is used", "Parity prevents single-bit errors"], 0, PYQ + "At higher data rates, a noise spike affects more bits."),
    ("The basic idea behind all error detection is:",
     ["Redundancy – adding extra bits that the receiver can check", "Compression", "Encryption", "Multiplexing"], 0, "Correction needs more redundancy than detection."),
    ("Sending a request for retransmission when an error is detected is called:",
     ["Backward error correction (ARQ)", "Forward error correction", "Multiplexing", "Encoding"], 0, PYQ + "Forward error correction lets the receiver correct errors without retransmission."),
    ("Forward error correction is preferred when:",
     ["Retransmission is costly or impossible, as in deep-space or real-time links", "The link is very short", "There are no errors", "Only one bit is sent"], 0, "Hamming and Reed–Solomon codes are examples."),
    ("Which medium is the most secure against tapping?",
     ["Optical fibre", "Radio", "Coaxial cable", "Twisted pair"], 0, PYQ + "Tapping light without detection is very difficult."),
    ("The type of noise caused by random motion of electrons in a conductor is:",
     ["Thermal (white) noise", "Impulse noise", "Crosstalk", "Echo"], 0, "It is present in all electronic devices."),
    ("Shielded twisted pair (STP) differs from UTP in having:",
     ["A metal foil or braided mesh covering each pair", "No insulation", "Glass core", "Only one wire"], 0, PYQ + "STP reduces interference but is bulkier and costlier."),
    ("Satellite communication uses which frequency band mainly?",
     ["Microwaves", "Visible light", "Infrared", "Extremely low frequencies"], 0, "Geostationary satellites are at about 35,786 km."),
    ("Consider the statements:\nI. Coaxial cable has better shielding than twisted pair.\nII. Fibre optic cable is affected by electromagnetic interference.",
     I_II, 0, "Fibre carries light, so EMI does not affect it."),
    ("Assertion (A): Twisted-pair cable is the most widely used medium in LANs and telephone local loops.\nReason (R): It is cheap, flexible and easy to install.",
     AR, 0, "Its bandwidth and distance are lower than fibre's."),
    ("Assertion (A): Microwaves can penetrate walls easily and need no line of sight.\nReason (R): Microwave antennas are unidirectional.",
     AR, 3, "Higher-frequency microwaves are blocked by walls and need line of sight; R is true."),
    ("Match:\na. Twisted pair  b. Coaxial  c. Optical fibre  d. Infrared\n1. Telephone and Ethernet  2. Cable TV  3. Total internal reflection  4. TV remote",
     ["a-1, b-2, c-3, d-4", "a-2, b-1, c-3, d-4", "a-1, b-3, c-2, d-4", "a-4, b-2, c-3, d-1"], 0, PYQ + "Media matching is common."),
    ("In a simple parity check, adding a parity bit can detect:",
     ["All single-bit errors (and any odd number of bit errors)", "All burst errors", "All errors", "No errors"], 0, "Two-bit errors pass undetected."),
    ("The power of a signal falls from 100 mW to 10 mW over a cable. The attenuation is:",
     ["−10 dB", "−3 dB", "−20 dB", "−90 dB"], 0, PYQ + "10 log₁₀(10/100) = −10 dB."),
    ("Bluetooth and Wi-Fi operate in which unlicensed band (among others)?",
     ["2.4 GHz ISM band", "100 MHz FM band", "Visible light", "600 THz"], 0, "Wi-Fi also uses 5 GHz and 6 GHz bands."),
]

TOPICS = {
    "Data Communication – Part 1": [("1 · Components, Transmission Modes, Analog and Digital Signals", BASICS),
                                    ("2 · Channel Capacity (Nyquist, Shannon), Bandwidth, Throughput and Latency", CHANNEL)],
    "Data Communication – Part 2": [("1 · Line Coding, Modulation, PCM and Multiplexing", ENCODING),
                                    ("2 · Transmission Media, Baseband and Broadband, and Transmission Errors", MEDIA)],
}
