"""Pack: Paper 2 · Unit 5 (DBMS) · Database System Concepts & Architecture.
6 sub-topics × 30 questions. Reference: Elmasri & Navathe, Fundamentals of Database Systems (syllabus ref. 8)."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from packlib import AR, I_II, build_pack

DATA_MODELS = [
    ("A data model is best defined as:",
     ["A collection of concepts to describe the structure of a database (data types, relationships, constraints) together with basic operations on it",
      "The physical file layout of a database on disk", "A diagram of the network connecting clients to the server", "A set of sample records used for testing"], 0,
     "A data model describes structure (types, relationships, constraints) and usually a set of basic operations for retrievals and updates."),
    ("Which data model is classified as a high-level (conceptual) data model?",
     ["Relational model", "Entity–Relationship model", "Network model", "Hierarchical model"], 1,
     "Conceptual models such as the ER model use concepts close to how users perceive data (entities, attributes, relationships)."),
    ("Representational (implementation) data models include:",
     ["ER model and UML class diagrams", "Relational, network and hierarchical models", "Only physical storage models", "Only object models"], 1,
     "Representational models are understood by end users yet close to how data is organised in storage; the relational, network and hierarchical models are the classic ones."),
    ("Physical (low-level) data models describe:",
     ["Entities and relationships", "Record formats, record orderings and access paths on the storage medium",
      "Only the external views of users", "Business rules of the organisation"], 1,
     "Physical data models describe how data is stored as files: record formats, orderings and access paths."),
    ("In database terminology, an 'access path' is:",
     ["A network route between client and server", "A search structure, such as an index, that makes locating particular records efficient",
      "The login path of a user", "The directory in which database files are stored"], 1,
     "An access path (e.g. an index) speeds up searching for records that satisfy a condition."),
    ("In the hierarchical data model, data are organised as:",
     ["Tables of rows and columns", "A tree structure in which each child record has exactly one parent", "A general graph with many-to-many links",
      "Key–value pairs"], 1, "The hierarchical model uses parent–child (1:N) relationships arranged as trees."),
    ("IBM's IMS (Information Management System) is based on the:",
     ["Relational model", "Network model", "Hierarchical model", "Object-oriented model"], 2,
     "IMS, developed in the 1960s, is the best-known hierarchical DBMS; it uses the DL/I language."),
    ("How are many-to-many relationships handled in a pure hierarchical model?",
     ["They are supported directly", "By duplicating records or using virtual (logical) parent–child relationships",
      "By using foreign keys", "They cannot be stored at all"], 1,
     "Since each child has one parent, M:N relationships lead to duplicated records unless virtual/logical pointers are used, which is a key weakness."),
    ("The network data model was standardised by the:",
     ["ANSI/SPARC study group", "CODASYL Data Base Task Group (DBTG)", "ISO SQL committee", "ODMG"], 1,
     "The CODASYL DBTG report (1971) defined the network model; IDMS is a well-known implementation."),
    ("In the CODASYL network model, a 1:N relationship between record types is represented by a:",
     ["Foreign key", "Set type with an owner record type and a member record type", "Class hierarchy", "View"], 1,
     "A set type links one owner record to many member records; M:N needs an intermediate (link) record type."),
    ("Which DBMS is based on the network model?",
     ["IDMS", "Oracle Database", "MongoDB", "IMS"], 0, "IDMS (Integrated Database Management System) follows the CODASYL network model; IMS is hierarchical."),
    ("E. F. Codd proposed the relational model in 1970 in the paper titled:",
     ["A Relational Model of Data for Large Shared Data Banks", "The Entity–Relationship Model: Toward a Unified View of Data",
      "Structured Query Language", "Relational Completeness of Data Base Sublanguages"], 0,
     "Codd's 1970 CACM paper introduced the relational model; Chen's 1976 paper introduced the ER model."),
    ("The formal foundation of the relational model is:",
     ["Graph theory", "Set theory and first-order predicate logic", "Probability theory", "Automata theory"], 1,
     "Relations are sets of tuples, and relational algebra/calculus are based on set theory and first-order logic."),
    ("'Record-at-a-time', navigational data manipulation is characteristic of:",
     ["The relational model with SQL", "The hierarchical and network models", "Key–value stores only", "Data warehouses"], 1,
     "Legacy models navigate from record to record using pointers (e.g. DL/I, CODASYL DML); SQL is set-at-a-time."),
    ("The Entity–Relationship model was proposed by:",
     ["E. F. Codd in 1970", "Peter Chen in 1976", "Charles Bachman in 1969", "Ted Codd in 1985"], 1,
     "Peter P. Chen introduced the ER model in 1976; Bachman is known for the network model and Bachman diagrams."),
    ("Codd's well-known rules for judging a relational DBMS (1985) consist of:",
     ["10 rules numbered 1 to 10", "12 rules numbered 1 to 12 only", "13 rules numbered 0 to 12", "7 rules"], 2,
     "They are called the '12 rules' but are numbered 0 (the foundation rule) to 12, i.e. 13 rules."),
    ("Which of the following is NOT a record-based data model?",
     ["Relational model", "Network model", "Hierarchical model", "Entity–Relationship model"], 3,
     "The ER model is a conceptual (object-based) model; the other three structure the database as fixed-format records."),
    ("In a self-describing data model such as XML or many NoSQL systems:",
     ["The schema is stored only in a separate catalog", "The description of the data is stored together with the data values",
      "No data can be stored", "Data must be in first normal form"], 1,
     "Self-describing models combine data and its description, e.g. XML tags or JSON keys."),
    ("MongoDB is an example of which type of NoSQL data model?",
     ["Key–value store", "Document store", "Column-family store", "Graph database"], 1,
     "MongoDB stores JSON-like (BSON) documents, which can have nested structures."),
    ("Apache Cassandra and HBase are examples of:",
     ["Document stores", "Wide-column (column-family) stores", "Graph databases", "Hierarchical DBMSs"], 1,
     "They organise data into column families, inspired by Google's Bigtable."),
    ("Neo4j stores data as nodes and relationships (edges) with properties. It is a:",
     ["Graph database", "Document store", "Relational DBMS", "Key–value store"], 0, "Neo4j implements the property-graph data model."),
    ("A pure key–value store (for example Redis or Amazon DynamoDB in its basic form) accesses data mainly by:",
     ["Complex joins on several columns", "A unique key, with the value largely opaque to the system",
      "Navigating parent–child pointers", "Full-text search on all fields"], 1,
     "Key–value stores give very fast lookups by key; the system usually does not interpret the value's structure."),
    ("Which feature is characteristic of the object data model?",
     ["Each object has a system-generated object identity (OID) independent of its attribute values",
      "Relationships are stored only as foreign keys", "All attributes must be atomic", "Data are organised only as trees"], 0,
     "OIDs are immutable and unique; object models also support encapsulation, classes and inheritance."),
    ("The object–relational data model:",
     ["Replaces tables with files", "Extends the relational model with features such as user-defined types, inheritance and complex objects",
      "Is a NoSQL graph model", "Supports only hierarchical data"], 1,
     "Object–relational features were standardised in SQL:1999 (and later), e.g. in Oracle and PostgreSQL."),
    ("Consider the statements:\nI. A data model specifies both the structure of a database and operations on it.\nII. Physical data models are mainly intended for end users.\nWhich is/are correct?",
     I_II, 0, "Physical models are for computer specialists, not end users; statement I is correct."),
    ("Assertion (A): The relational model offers better data independence than the network model.\nReason (R): In the relational model, relationships are represented by data values (keys) rather than by physical pointers.",
     AR, 0, "Because relationships are value-based, storage structures can change without affecting how relationships are expressed."),
    ("In the relational model, a relationship between two relations is represented by:",
     ["Physical pointers between records", "Matching values of attributes, typically a foreign key referring to a primary key",
      "Owner–member set types", "Parent–child links"], 1, "Relational databases connect tables through values, e.g. EMPLOYEE.Dno referencing DEPARTMENT.Dnumber."),
    ("In the object data model, the behaviour (dynamic aspect) of objects is specified through:",
     ["Constraints", "Methods (operations) defined on classes", "Indexes", "Views"], 1,
     "Object models bundle data with operations (methods); users invoke operations instead of accessing data directly."),
    ("Which statement about the pure hierarchical model is FALSE?",
     ["Each record type except the root has exactly one parent record type", "A child record can have several parent records",
      "Access usually begins at the root and navigates downwards", "It naturally represents 1:N relationships"], 1,
     "In a pure hierarchy a child has only one parent, which is why M:N relationships are hard to model."),
    ("Conceptual data models such as the ER model are mainly used during:",
     ["The physical design phase", "Conceptual database design, independent of any specific DBMS", "Query optimisation", "Backup and recovery"], 1,
     "The conceptual schema is later mapped to a representational model (e.g. relational) during logical design."),
]

SCHEMAS = [
    ("The description of a database, specified during database design and not expected to change frequently, is called the:",
     ["Database state", "Database schema", "Database snapshot", "Database instance"], 1,
     "The schema describes the structure; the data stored at any moment is the state (instance)."),
    ("The data in a database at a particular moment in time is called the:",
     ["Schema", "Database state (instance or snapshot)", "Meta-data", "Schema construct"], 1,
     "Every insert, delete or update produces a new database state."),
    ("The schema and the database state are also called, respectively, the:",
     ["Extension and intension", "Intension and extension", "Instance and snapshot", "Catalog and dictionary"], 1,
     "Schema = intension; database state = extension of the schema."),
    ("When a new database is defined but no data has yet been loaded, it is in the:",
     ["Initial state", "Empty state", "Valid state", "Final state"], 1,
     "Specifying the schema to the DBMS creates an empty database; loading data then gives the initial state."),
    ("The state of a database when it is first populated (loaded) with data is called the:",
     ["Empty state", "Initial state", "Current state", "Transition state"], 1,
     "After defining the schema, the first loading of data produces the initial database state."),
    ("A database state that satisfies the structure and all the constraints specified in the schema is called a:",
     ["Valid state", "Initial state", "Consistent schema", "Snapshot"], 0, "Every state should be valid; the DBMS enforces the constraints."),
    ("Who is primarily responsible for ensuring that every state of the database is a valid state?",
     ["The end user", "The DBMS, by enforcing the constraints defined in the schema", "The operating system", "The network administrator"], 1,
     "The DBMS checks constraints such as keys, domains and referential integrity on each update."),
    ("In a DBMS, the database schema (meta-data) is stored in the:",
     ["Application programs", "DBMS catalog (data dictionary)", "Transaction log only", "Query results"], 1,
     "The catalog stores the schema so the DBMS and its users can refer to it; this is the self-describing nature of databases."),
    ("Which of the following is typically NOT shown in a schema diagram?",
     ["Names of record types (relations)", "Names of data items (attributes)", "Actual data values of the records", "Some constraints such as keys"], 2,
     "A schema diagram shows only aspects of the schema; data values belong to the database state."),
    ("Each object within a schema, such as STUDENT or COURSE, is called a:",
     ["Tuple", "Schema construct", "Instance", "Domain"], 1, "Record types, data items and constraints in a schema are schema constructs."),
    ("Adding a new attribute such as Date_of_birth to the STUDENT record type after the database is in use is an example of:",
     ["A change of database state", "Schema evolution", "Data mining", "Recovery"], 1,
     "Changes to the schema after the database is operational are called schema evolution; modern DBMSs allow some changes without reloading."),
    ("Which statement is correct?",
     ["The schema changes with every insertion", "The database state changes frequently, while the schema changes rarely",
      "Both change equally often", "Neither can change once created"], 1,
     "Every update changes the state; the schema changes only when requirements change."),
    ("For a relation schema R(A1, A2, …, An), n is called the:",
     ["Cardinality of R", "Degree (arity) of R", "Domain of R", "Key of R"], 1, "The degree is the number of attributes in the relation schema."),
    ("The number of tuples in a relation state r(R) is called its:",
     ["Degree", "Arity", "Cardinality", "Domain"], 2, "Cardinality = number of tuples; degree = number of attributes."),
    ("A STUDENT relation has 6 attributes and currently holds 250 tuples. Its degree and cardinality are:",
     ["Degree 250, cardinality 6", "Degree 6, cardinality 250", "Degree 6, cardinality 6", "Degree 256, cardinality 250"], 1,
     "Degree counts attributes (6) and cardinality counts tuples (250)."),
    ("Formally, a relation state r(R) of R(A1, …, An) is a subset of:",
     ["dom(A1) ∪ dom(A2) ∪ … ∪ dom(An)", "dom(A1) × dom(A2) × … × dom(An)", "The power set of R", "The catalog of R"], 1,
     "A relation state is a subset of the Cartesian product of the attribute domains."),
    ("Relation R(A, B) has |dom(A)| = 3 and |dom(B)| = 4. How many different relation states r(R) are possible?",
     ["12", "7", "2^12 = 4096", "3^4 = 81"], 2,
     "There are 3 × 4 = 12 possible tuples, and any subset of them is a possible state, so 2^12 = 4096 states."),
    ("Which statement about tuples in a relation is correct?",
     ["Tuples are stored and must be retrieved in insertion order", "The ordering of tuples in a relation is not significant",
      "Two identical tuples are allowed", "Tuples must be sorted by the primary key"], 1,
     "A relation is a set of tuples, so there is no inherent order and no duplicate tuples."),
    ("Consider the statements:\nI. The order of tuples in a relation is not significant.\nII. If a tuple is defined as an ordered list of values, the order of values within a tuple matters.\nWhich is/are correct?",
     I_II, 2, "Both are correct; with the alternative definition as a set of (attribute, value) pairs, attribute order also becomes irrelevant."),
    ("A relation that currently contains no tuples is:",
     ["An invalid relation state", "A valid relation state (an empty relation)", "Not allowed by the relational model", "A schema without attributes"], 1,
     "An empty set of tuples is a legitimate relation state."),
    ("Which SQL statement changes the database schema rather than only the database state?",
     ["INSERT INTO STUDENT VALUES (…)", "UPDATE STUDENT SET Class = 2", "ALTER TABLE STUDENT ADD Email VARCHAR(40)", "DELETE FROM STUDENT"], 2,
     "ALTER TABLE is a DDL statement that modifies the schema; INSERT, UPDATE and DELETE change only the state."),
    ("In a programming-language analogy, a database schema corresponds to a:",
     ["Value stored in a variable", "Type declaration of a variable", "Loop statement", "Function call"], 1,
     "The schema is like a type (the structure); the state is like the current value of a variable of that type."),
    ("'Meta-data' in a database system means:",
     ["Very large data", "Data about data, such as the definitions of tables, columns and constraints", "Deleted data", "Encrypted data"], 1,
     "Meta-data describes the structure of the database and is stored in the catalog."),
    ("The term 'snapshot' in database terminology usually refers to:",
     ["The schema diagram", "The database state at a particular moment", "A backup tape", "The external schema"], 1,
     "Database state, instance, occurrence and snapshot all mean the data at a particular time."),
    ("A constraint that must hold on every individual database state (for example, 'Ssn is unique') is called a:",
     ["Transition (dynamic) constraint", "State (static) constraint", "Physical constraint", "Access constraint"], 1,
     "State constraints restrict each valid state; transition constraints restrict how the database may change from one state to another."),
    ("'An employee's salary can never decrease' is an example of a:",
     ["Domain constraint", "Key constraint", "Transition (dynamic) constraint", "Entity integrity constraint"], 2,
     "It restricts the change from one state to the next, so it is a transition constraint, usually enforced with triggers or application code."),
    ("Assertion (A): The schema of a relation can remain the same while its state changes many times per second.\nReason (R): The schema is stored only inside application programs, not in the DBMS catalog.",
     AR, 2, "A is true, but R is false: the schema (meta-data) is stored in the DBMS catalog. The real reason is that the schema is the intension and the state the extension."),
    ("Loading a large amount of existing data into a newly defined database to create its first state is typically done using:",
     ["A bulk-loading utility", "A trigger", "A view", "A recovery manager"], 0,
     "DBMS loading utilities load existing files efficiently into the database to create the initial state."),
    ("In the SQL standard, schema information about tables and columns can be queried through the set of views called:",
     ["INFORMATION_SCHEMA", "SYS_LOG", "DATA_STATE", "META_BUFFER"], 0,
     "The standard INFORMATION_SCHEMA views expose catalog information such as TABLES and COLUMNS."),
    ("The SQL statement  CREATE SCHEMA COMPANY AUTHORIZATION 'Jsmith';  does what?",
     ["Creates a table named COMPANY", "Creates a schema named COMPANY owned by the user Jsmith",
      "Grants Jsmith access to all schemas", "Creates a user called COMPANY"], 1,
     "An SQL schema groups tables and other elements belonging to one application; AUTHORIZATION names its owner."),
]

THREE_SCHEMA = [
    ("The three-schema architecture of a DBMS was proposed by the:",
     ["ANSI/SPARC Study Group on Database Management Systems", "CODASYL DBTG", "IEEE", "ODMG"], 0,
     "The ANSI/SPARC architecture (1975–78) introduced the external, conceptual and internal levels."),
    ("The main goal of the three-schema architecture is to:",
     ["Increase disk capacity", "Separate user applications from the physical database", "Replace SQL", "Reduce the number of users"], 1,
     "Separating the levels supports multiple user views and data independence."),
    ("The three levels of the ANSI/SPARC architecture, from the user side to the storage side, are:",
     ["External → Conceptual → Internal", "Internal → Conceptual → External", "Conceptual → External → Internal", "External → Internal → Conceptual"], 0,
     "External level (user views), conceptual level (whole database) and internal level (physical storage)."),
    ("Which level describes the physical storage structures and access paths of the database?",
     ["External level", "Conceptual level", "Internal level", "View level"], 2, "The internal schema uses a physical data model to describe storage details."),
    ("Which level describes the structure of the whole database for a community of users, hiding physical storage details?",
     ["Internal level", "Conceptual level", "External level", "Physical level"], 1,
     "The conceptual schema describes entities, data types, relationships, user operations and constraints for the entire database."),
    ("Which level describes the part of the database that a particular user group is interested in?",
     ["Internal level", "Conceptual level", "External (view) level", "Storage level"], 2, "Each external schema (user view) hides the rest of the database from that group."),
    ("An index created on EMPLOYEE(Salary) to speed up queries is described at the:",
     ["External level", "Conceptual level", "Internal level", "User level"], 2, "Indexes are access paths, which belong to the internal schema."),
    ("A view that shows only student names and roll numbers to the library staff belongs to the:",
     ["Internal level", "Conceptual level", "External level", "Physical level"], 2, "User views that hide other data are external schemas."),
    ("The definition 'DEPARTMENT(Dnumber, Dname, Mgr_ssn) with Dnumber as the primary key' is part of the:",
     ["Internal schema", "Conceptual schema", "External schema", "Storage schema"], 1,
     "Relations, attributes and constraints for the whole database are defined in the conceptual schema."),
    ("For a single database in the three-schema architecture, how many schemas of each kind exist?",
     ["One external, many conceptual, one internal", "Many external, one conceptual, one internal", "One of each", "Many of each"], 1,
     "There are many user views but only one conceptual and one internal schema for a database."),
    ("The processes of transforming requests and results between the levels of the three-schema architecture are called:",
     ["Normalisations", "Mappings", "Indexes", "Transactions"], 1,
     "External/conceptual and conceptual/internal mappings translate requests downward and results upward."),
    ("The two mappings defined in the three-schema architecture are:",
     ["External/internal and internal/physical", "External/conceptual and conceptual/internal", "View/table and table/index", "User/DBA and DBA/system"], 1,
     "Each external schema maps to the conceptual schema, which maps to the internal schema."),
    ("A disadvantage of a strict three-schema implementation is:",
     ["Loss of security", "The overhead of transforming requests and results between levels at run time", "Inability to support views", "Data redundancy"], 1,
     "Mapping between levels takes time; many DBMSs therefore do not separate the levels completely."),
    ("When implementing the three-schema architecture, the conceptual schema is usually described using:",
     ["A physical data model", "A representational (implementation) data model, such as the relational model", "Only natural language", "Machine code"], 1,
     "In practice the conceptual schema is expressed in the DBMS's implementation data model, often derived from a high-level ER design."),
    ("In relational DBMSs, external schemas are mainly implemented using:",
     ["Indexes", "Views", "Triggers", "Clusters"], 1, "SQL views present derived, restricted pictures of the base tables to different users."),
    ("Record placement, file organisation, compression and encryption of stored data are concerns of the:",
     ["External level", "Conceptual level", "Internal level", "View level"], 2, "These are physical storage details described in the internal schema."),
    ("In the three-schema architecture, a query written against an external schema is processed by:",
     ["Executing it directly on disk", "Transforming it into a request on the conceptual schema and then into a request on the internal schema",
      "Sending it to every external schema", "Ignoring the conceptual schema"], 1,
     "The DBMS maps the request level by level down to the stored database, and maps results back up."),
    ("Which statement about the three-schema architecture is correct?",
     ["All commercial DBMSs separate the three levels strictly", "Most DBMSs support the architecture to some extent but do not separate the levels completely",
      "It applies only to hierarchical databases", "It removes the need for a catalog"], 1,
     "Many DBMSs mix conceptual and internal details in their DDL, although they support user views."),
    ("The schemas at all three levels are stored as meta-data in the:",
     ["Transaction log", "DBMS catalog", "Application code", "Query cache"], 1, "The catalog keeps the external, conceptual and internal schemas and the mappings between them."),
    ("Who is mainly responsible for defining the internal schema?",
     ["Naive end users", "The database administrator (DBA)", "Application end users", "Database designers only through views"], 1,
     "The DBA handles physical design decisions such as indexes and storage organisation."),
    ("Consider the statements:\nI. A user view may include data derived from stored data that is not physically stored.\nII. Different external schemas may present the same data differently.\nWhich is/are correct?",
     I_II, 2, "Views can contain derived attributes (e.g. age from date of birth) and each user group can see its own representation."),
    ("Assertion (A): The three-schema architecture makes it possible to provide multiple user views of the same database.\nReason (R): The conceptual schema describes the whole database, from which each external schema is derived through a mapping.",
     AR, 0, "Because every view is defined from the common conceptual schema, many different views can coexist."),
    ("The stored database on disk is described directly by the:",
     ["External schema", "Conceptual schema", "Internal schema", "Mapping"], 2, "The internal schema describes the physical storage of the database."),
    ("Which of the following changes is made at the conceptual level?",
     ["Creating a B+-tree index", "Adding a new entity type PROJECT with its attributes", "Changing the block size", "Moving files to another disk"], 1,
     "New entity types, attributes and relationships change the conceptual schema; the other options are internal-level changes."),
    ("Which user is most likely to interact only with an external schema?",
     ["The DBA tuning storage parameters", "A bank teller using a banking application", "The DBMS designer", "The system programmer"], 1,
     "End users see only the part of the database relevant to them through their application's view."),
    ("In the ANSI/SPARC architecture, security is enhanced because:",
     ["Data are always encrypted", "Each user can be restricted to their own external schema, hiding other data", "There is only one user", "Indexes are hidden"], 1,
     "Views hide data that a user group is not allowed to see."),
    ("A single conceptual schema supporting many external schemas mainly helps to:",
     ["Increase redundancy", "Integrate data in one place while serving diverse user requirements", "Remove all constraints", "Eliminate the need for mappings"], 1,
     "Data are integrated and stored once, while different users get customised views."),
    ("If only the internal schema changes (for example, a file is reorganised), what else must be changed?",
     ["All external schemas", "The conceptual/internal mapping only", "All application programs", "The conceptual schema"], 1,
     "Only the mapping between the conceptual and internal levels is updated; this is physical data independence."),
    ("In the three-schema architecture, the level at which the DBMS describes 'what data are stored and the relationships among them' is the:",
     ["Internal level", "Conceptual (logical) level", "External level", "Hardware level"], 1,
     "The conceptual (logical) level describes what data exist; the internal level describes how they are stored."),
    ("Which layer interacts directly with the operating system's file manager and the disk?",
     ["External level", "Conceptual level", "Internal level", "User interface"], 2, "The internal level deals with stored records and files on secondary storage."),
]

DATA_INDEPENDENCE = [
    ("Data independence is defined as:",
     ["The ability to store data without a DBMS", "The capacity to change the schema at one level without having to change the schema at the next higher level",
      "The ability of users to work offline", "Independence of the DBMS from the operating system"], 1,
     "Data independence follows from the three-schema architecture: only the mapping between two levels needs changing."),
    ("Logical data independence is the capacity to change the:",
     ["Internal schema without changing the conceptual schema", "Conceptual schema without changing external schemas or application programs",
      "External schema without changing the conceptual schema", "Hardware without changing the software"], 1,
     "Changes such as adding a record type or attribute should not affect users whose views do not use them."),
    ("Physical data independence is the capacity to change the:",
     ["Conceptual schema without changing external schemas", "Internal schema without changing the conceptual schema",
      "Application programs without changing the DBMS", "External schemas without changing views"], 1,
     "Reorganising files or adding access paths should not require changes to the conceptual (and hence external) schemas."),
    ("Which type of data independence is generally harder to achieve?",
     ["Physical data independence", "Logical data independence", "Both are equally easy", "Neither can be achieved"], 1,
     "Application programs depend heavily on the logical structure of the data they access, so logical changes are harder to hide."),
    ("Creating a new index on the ORDERS table to speed up queries requires which kind of data independence to avoid changing programs?",
     ["Logical", "Physical", "External", "Transactional"], 1, "An index is an internal-level change."),
    ("Changing a file organisation from heap to hashed, without affecting queries, is an example of:",
     ["Logical data independence", "Physical data independence", "Schema evolution at the external level", "View resolution"], 1,
     "The storage structure is part of the internal schema."),
    ("Adding a new attribute Email to the STUDENT relation without affecting existing applications is an example of:",
     ["Physical data independence", "Logical data independence", "Referential integrity", "Normalisation"], 1,
     "It changes the conceptual schema; existing views and programs that do not use Email need no change."),
    ("Splitting the relation EMPLOYEE into two relations and defining a view that reconstructs the original EMPLOYEE for old programs relies on:",
     ["Physical data independence", "Logical data independence", "Concurrency control", "Recovery"], 1,
     "The conceptual schema changed, but the view (external schema) hides the change from applications."),
    ("Moving the database files to a faster SSD without changing any table definitions is an example of:",
     ["Logical data independence", "Physical data independence", "Program–operation independence", "Distribution transparency"], 1,
     "Only physical storage changed."),
    ("Data independence in the three-schema architecture is achieved mainly through:",
     ["Encryption", "The mappings between levels", "Triggers", "Replication"], 1,
     "When a lower-level schema changes, only the mapping to the higher level is updated."),
    ("In traditional file-processing systems, why is there little data independence?",
     ["Files are always encrypted", "The structure of data files is embedded in the application programs",
      "Files cannot be shared", "Files are stored on tape only"], 1,
     "A change in record format requires changes to every program that uses the file (program–data dependence)."),
    ("In object-oriented databases, 'program–operation independence' means that:",
     ["Programs run on any OS", "The implementation of an operation can change without affecting the programs that invoke it",
      "Operations cannot be changed", "Every program has its own data"], 1,
     "Users call an operation through its interface (signature); the method body is hidden (encapsulation)."),
    ("Which change requires logical data independence to avoid rewriting application programs?",
     ["Adding a B+-tree index", "Compressing the data files", "Removing an attribute that some views do not use", "Changing the disk block size"], 2,
     "Removing an attribute changes the conceptual schema; it affects only views/programs that use it."),
    ("Consider the statements:\nI. Physical data independence implies that external schemas are also unaffected by internal changes.\nII. Logical data independence is usually easier to achieve than physical data independence.\nWhich is/are correct?",
     I_II, 0, "If the conceptual schema is unchanged, the external schemas are unaffected too. Statement II is false: logical independence is harder."),
    ("Assertion (A): In relational DBMSs, views help to provide logical data independence.\nReason (R): A view can present the old structure of data even after the underlying base tables have been restructured.",
     AR, 0, "Redefining the view over the new tables lets old programs keep working unchanged."),
    ("Why was physical data independence difficult in older network and hierarchical systems?",
     ["They had no disks", "Physical pointers and access paths were visible to and used by application programs",
      "They did not allow data sharing", "They had too many views"], 1,
     "Navigational programs followed pointers explicitly, so storage changes affected the programs."),
    ("Which of the following is an example of a change at the internal level?",
     ["Adding a new relation COURSE", "Changing the data type of an attribute in the conceptual schema",
      "Creating a clustered index on Emp_id", "Defining a new view for managers"], 2, "Clustered indexes are storage structures, i.e. internal level."),
    ("Which of the following is an example of a change at the conceptual level?",
     ["Reorganising a file", "Adding a new relationship WORKS_ON between EMPLOYEE and PROJECT", "Adding an index", "Changing the RAID level of the disks"], 1,
     "New relationships change the logical structure of the whole database."),
    ("With physical data independence, when the internal schema changes, what must be changed?",
     ["All user views", "The conceptual/internal mapping", "The conceptual schema", "All application programs"], 1,
     "Only the mapping is updated so the conceptual schema continues to describe the same data."),
    ("With logical data independence, when the conceptual schema changes, what must be changed?",
     ["The internal schema", "Only the view definitions and external/conceptual mappings (where affected)", "All application programs", "The hardware"], 1,
     "Application programs referring to external schemas continue to work."),
    ("Data independence is valuable mainly because it:",
     ["Increases storage cost", "Reduces the maintenance effort when the database structure or storage changes",
      "Makes queries slower", "Eliminates the need for a DBA"], 1,
     "Programs are insulated from many changes, reducing costly rewrites."),
    ("Changing the order in which records are physically stored, while SQL queries remain unchanged, is possible because of:",
     ["Logical data independence", "Physical data independence", "Referential integrity", "Atomicity"], 1, "Physical record ordering is an internal-level detail."),
    ("A DBA merges two tables DEPT_A and DEPT_B into one DEPARTMENT table and provides views with the old names. This is an application of:",
     ["Physical data independence", "Logical data independence", "Program–operation independence", "Durability"], 1,
     "The conceptual schema changed, and views keep the external schemas unchanged."),
    ("The overhead of data independence mainly arises from:",
     ["Encrypting data", "Mapping requests and results between the levels at run time or compile time", "Running backups", "Checking passwords"], 1,
     "More levels and mappings mean more work for the DBMS when processing requests."),
    ("Which of the following does NOT depend on data independence?",
     ["Adding an index without changing programs", "Restructuring tables behind views", "Changing storage devices without changing programs",
      "Enforcing that each tuple has a unique primary key"], 3, "Key constraints are about integrity, not about insulating levels from changes."),
    ("In the three-schema architecture, physical data independence exists between the:",
     ["External and conceptual levels", "Conceptual and internal levels", "User and application", "Client and server"], 1,
     "It is provided by the conceptual/internal mapping."),
    ("In the three-schema architecture, logical data independence exists between the:",
     ["External and conceptual levels", "Conceptual and internal levels", "Internal level and disk", "Two clients"], 0,
     "It is provided by the external/conceptual mappings."),
    ("Which statement is TRUE?",
     ["Data independence means data can never be changed", "Most modern relational DBMSs provide physical data independence well; logical independence is provided mainly through views",
      "Logical data independence is guaranteed for every schema change", "File systems provide full data independence"], 1,
     "Not every conceptual change can be hidden (e.g. dropping an attribute a view uses), but views handle many cases."),
    ("A program uses the view EMP_PUBLIC(Name, Dept). The base table EMPLOYEE is split into two tables and the view is redefined. The program needs:",
     ["To be completely rewritten", "No change", "To be recompiled with new table names", "A new external schema"], 1,
     "Because the view name and structure are unchanged, the program continues to work (logical data independence)."),
    ("Adding more RAM to the database server to increase the buffer pool size affects which level, if any, of the three-schema architecture?",
     ["The external level", "The conceptual level", "Only the internal/physical implementation, not the schemas seen by users", "All three levels"], 2,
     "Buffer and hardware tuning are physical concerns invisible to the conceptual and external levels."),
]

LANGUAGES = [
    ("Which language is used by the DBA and database designers to define the conceptual schema?",
     ["DML", "DDL (Data Definition Language)", "DCL", "TCL"], 1,
     "The DDL compiler processes schema definitions and stores them in the catalog."),
    ("In a DBMS with a strict separation of levels, the language used to specify the internal schema is the:",
     ["View definition language", "Storage definition language (SDL)", "Query language", "Host language"], 1,
     "The SDL specifies internal (physical) storage; in most relational DBMSs this is done through parameters and commands rather than a separate language."),
    ("The language used to specify user views and their mappings to the conceptual schema is the:",
     ["SDL", "VDL (View Definition Language)", "DCL", "Machine language"], 1, "In relational DBMSs, SQL itself serves as the VDL (CREATE VIEW)."),
    ("A high-level (non-procedural) DML such as SQL is also described as:",
     ["Record-at-a-time", "Set-at-a-time (declarative)", "Navigational", "Pointer-based"], 1,
     "Users specify what data they want, not how to retrieve it; one statement can process many records."),
    ("A low-level (procedural) DML is typically:",
     ["Set-at-a-time and declarative", "Record-at-a-time and embedded in a general-purpose programming language", "Used only for views", "Used only by naive users"], 1,
     "Procedural DMLs retrieve individual records and need loops and pointers, e.g. DL/I in IMS."),
    ("When DML statements are embedded in a general-purpose language such as C or Java, the general-purpose language is called the:",
     ["Data sublanguage", "Host language", "Query language", "Object language"], 1, "The DML is then the data sublanguage."),
    ("A high-level DML used on its own in an interactive manner is called a:",
     ["Host language", "Query language", "Storage language", "Assembly language"], 1, "SQL used interactively (e.g. at a command prompt) is a query language."),
    ("Which of the following SQL commands is a DDL command?",
     ["SELECT", "INSERT", "CREATE TABLE", "GRANT"], 2, "CREATE, ALTER and DROP are DDL; SELECT/INSERT are DML; GRANT is DCL."),
    ("GRANT and REVOKE belong to which category of SQL commands?",
     ["DDL", "DML", "DCL (Data Control Language)", "TCL"], 2, "DCL commands control access privileges."),
    ("COMMIT, ROLLBACK and SAVEPOINT belong to which category of SQL commands?",
     ["DDL", "DML", "DCL", "TCL (Transaction Control Language)"], 3, "They control the outcome of transactions."),
    ("Which statement about DELETE and TRUNCATE is correct?",
     ["Both are DDL commands", "DELETE is DML and can use a WHERE clause; TRUNCATE (usually treated as DDL) removes all rows",
      "TRUNCATE can remove selected rows using WHERE", "DELETE removes the table definition"], 1,
     "DELETE removes chosen rows row by row; TRUNCATE quickly empties the whole table; DROP removes the table itself."),
    ("Which SQL statement removes both the data and the definition of a table?",
     ["DELETE FROM T", "TRUNCATE TABLE T", "DROP TABLE T", "ALTER TABLE T"], 2, "DROP deletes the schema element itself."),
    ("The DBMS component that extracts DML commands from an application program written in a host language is the:",
     ["DDL compiler", "Precompiler", "Linker", "Runtime database processor"], 1,
     "The precompiler sends the extracted DML to the DML compiler; the rest goes to the host-language compiler."),
    ("In embedded SQL, the problem caused by SQL returning sets of rows while the host language processes one record at a time is called:",
     ["Deadlock", "Impedance mismatch", "Lost update", "Phantom problem"], 1,
     "Cursors bridge the gap by letting the program fetch the result set one row at a time."),
    ("In embedded SQL, which construct is used to process a multi-row query result one row at a time?",
     ["Trigger", "Cursor", "View", "Assertion"], 1, "DECLARE CURSOR, OPEN, FETCH and CLOSE iterate over query results."),
    ("ODBC and JDBC are examples of:",
     ["Query optimisers", "Call-level interfaces (APIs) through which programs access databases", "Storage structures", "Recovery techniques"], 1,
     "Instead of precompiling embedded SQL, programs call library functions to send SQL to the DBMS."),
    ("Bank tellers who repeatedly perform a few operations using a small set of commands or function keys are called:",
     ["Sophisticated users", "Parametric (naive) end users", "DBAs", "Casual users"], 1,
     "Parametric users run 'canned transactions' through simple interfaces designed for them."),
    ("A DBMS interface that lets users choose options from lists step by step, without knowing any query language, is a:",
     ["Natural language interface", "Menu-based interface", "Command-line interface", "Storage interface"], 1,
     "Menu-based interfaces, often used for browsing, guide users through options."),
    ("An interface in which the user fills in the fields of a displayed template to insert or retrieve data is a:",
     ["Forms-based interface", "Speech interface", "Natural language interface", "Programming interface"], 0,
     "Forms-based interfaces are common for data entry by naive users."),
    ("A natural language interface to a database:",
     ["Accepts requests written in English (or another natural language) and tries to interpret them", "Requires users to write SQL",
      "Is used only by the DBA", "Works only with hierarchical databases"], 0,
     "It uses its own schema of words and a dictionary to interpret requests and generate queries."),
    ("Privileged commands such as creating accounts, setting system parameters and changing schemas are available through:",
     ["Interfaces for parametric users", "Interfaces for the DBA", "Menu-based interfaces", "Web browsers"], 1,
     "DBA interfaces allow commands that only DBA staff may use."),
    ("Which of the following is NOT a DML operation?",
     ["Retrieval", "Insertion", "Modification", "Defining a new relation"], 3, "Defining relations is a DDL function."),
    ("In a relational DBMS such as Oracle or MySQL, which statement is TRUE?",
     ["Separate DDL, VDL and SDL languages are always used", "SQL combines the roles of DDL, VDL and DML, and storage details are set through DBA commands and parameters",
      "Only a record-at-a-time DML is available", "Views cannot be created"], 1,
     "SQL is a comprehensive language covering data definition, views, manipulation, constraints and access control."),
    ("The DBMS component that processes schema definitions and stores their descriptions in the catalog is the:",
     ["DDL compiler", "Query optimiser", "Buffer manager", "Recovery manager"], 0,
     "The catalog then provides the information needed by other modules."),
    ("Consider the statements:\nI. A non-procedural DML specifies what data to retrieve rather than how to retrieve it.\nII. A procedural DML requires the programmer to use loops to retrieve multiple records.\nWhich is/are correct?",
     I_II, 2, "Both describe the difference between declarative (SQL) and navigational DMLs."),
    ("Assertion (A): SQL is called a declarative language.\nReason (R): SQL has been standardised by ANSI and ISO.",
     AR, 1, "Both are true, but standardisation does not explain why SQL is declarative; it is declarative because users state what they want and the DBMS decides how."),
    ("Which type of user typically writes complex queries directly in SQL to analyse data, without a canned application?",
     ["Parametric end users", "Sophisticated end users (e.g. analysts, scientists)", "Naive users", "Data entry operators"], 1,
     "Sophisticated users know the DBMS facilities well and write their own requests."),
    ("Keyword-based database search, similar to web search engines, is an interface where users:",
     ["Type keywords and receive ranked results without writing structured queries", "Must write relational algebra",
      "Use only function keys", "Draw ER diagrams"], 0, "It relies on information-retrieval techniques to match keywords with stored data."),
    ("Which of the following best describes the role of the runtime database processor?",
     ["It compiles DDL statements", "It executes privileged commands, compiled queries and canned transactions, working with the stored data manager",
      "It designs the conceptual schema", "It provides the graphical user interface"], 1,
     "The runtime processor carries out execution plans and accesses the database through the stored data manager."),
    ("Which SQL command changes existing values in rows?",
     ["ALTER", "UPDATE", "MODIFY TABLE", "REPLACE SCHEMA"], 1, "UPDATE is DML and changes data; ALTER is DDL and changes the structure."),
]

ARCHITECTURES = [
    ("In a centralised DBMS architecture:",
     ["DBMS functions, application programs and the user interface all run on one central computer, with users connected through terminals",
      "Each user has a separate copy of the database", "Data is spread across many sites", "Only web browsers can access the data"], 0,
     "Early systems used mainframes with display terminals that had no processing power of their own."),
    ("A major disadvantage of a purely centralised database system is that:",
     ["Data cannot be shared", "The central computer is a single point of failure and a performance bottleneck", "It needs a network between sites", "It has no security"], 1,
     "If the central machine fails or becomes overloaded, all users are affected."),
    ("In the basic client/server architecture, a 'server' is:",
     ["Any machine used by an end user", "A system with hardware and software that provides services, such as files, printing, web pages or database access, to clients",
      "Only a printer", "A device driver"], 1, "Specialised servers provide functionality to client machines over a network."),
    ("In a two-tier client/server DBMS architecture, the user interface and application programs usually run on the:",
     ["Database server", "Client", "Web server", "Router"], 1,
     "The client side handles the interface and application logic; the server side handles query and transaction processing."),
    ("In a two-tier architecture, the database server is often called a:",
     ["File server", "Query server or transaction server (an SQL server in relational systems)", "Web server", "Mail server"], 1,
     "The server provides query and transaction functionality related to SQL processing."),
    ("A client program in a two-tier architecture typically connects to the DBMS through a standard API such as:",
     ["HTTP only", "ODBC or JDBC", "FTP", "SMTP"], 1, "ODBC and JDBC let client programs call a DBMS as long as both sides have the necessary software."),
    ("In the three-tier (web) architecture, the middle tier is the:",
     ["Client browser", "Application server or web server that runs business logic and accesses the database", "Database server", "Disk controller"], 1,
     "The middle tier stores business rules, checks client credentials and forwards requests to the database server."),
    ("Which is an advantage of the three-tier architecture over the two-tier architecture?",
     ["Clients access the database directly", "Better security, since clients never access the database server directly, and easier scaling",
      "No network is needed", "Business logic must be installed on every client"], 1,
     "The application server acts as a gatekeeper and business logic is maintained centrally."),
    ("A 'thin client' is one that:",
     ["Performs most of the processing itself", "Mainly handles presentation, while most processing happens on servers", "Has no network connection",
      "Stores the whole database locally"], 1, "Web browsers in three-tier systems are typical thin clients."),
    ("In a typical two-tier architecture with business logic on the client, the client is often described as a:",
     ["Thin client", "Fat (thick) client", "Dumb terminal", "Proxy"], 1, "Fat clients run substantial application logic and need more software installed."),
    ("An n-tier architecture:",
     ["Always has exactly three tiers", "Divides the layers between user and stored data further, e.g. separating business logic into several tiers",
      "Has no database server", "Is the same as a centralised architecture"], 1,
     "Additional tiers can be distributed across servers, for example in ERP and enterprise systems."),
    ("In the three-tier architecture, the correct flow of a request is:",
     ["Browser → database server → application server", "Browser (client) → application/web server → database server",
      "Database server → browser → application server", "Application server → browser → database server"], 1,
     "Results travel back the same way, formatted by the middle tier (e.g. as HTML) for the client."),
    ("Dumb terminals in early centralised systems:",
     ["Had powerful processors", "Provided only display and input, with all processing done on the central computer",
      "Stored the database locally", "Ran web browsers"], 1, "They were simply screens and keyboards connected to the mainframe."),
    ("Why did DBMS architectures move from centralised to client/server designs?",
     ["Mainframes became cheaper than PCs", "Falling hardware costs let PCs and workstations take over interface and processing work",
      "Networks disappeared", "SQL was abolished"], 1,
     "Powerful, cheap client machines allowed processing to be moved away from the central computer."),
    ("Which of the following is typically handled by the database server in a two-tier architecture?",
     ["Drawing the graphical user interface", "Query optimisation, transaction management, concurrency control and recovery",
      "Printing reports on the client's printer", "Spell-checking forms"], 1, "These core DBMS functions stay on the server."),
    ("Consider the statements:\nI. In a three-tier architecture, the application server can check a client's credentials before forwarding requests.\nII. In a three-tier architecture, business rules must be installed on every client.\nWhich is/are correct?",
     I_II, 0, "Business rules live on the middle tier, which is one of its main advantages."),
    ("Assertion (A): In a three-tier architecture, business rules must be installed on every client machine.\nReason (R): In a three-tier architecture, business logic resides in the middle tier.",
     AR, 3, "A is false: that describes fat clients in two-tier systems. R is true."),
    ("A web-based online banking system in which customers use a browser, a bank application server applies business rules and an Oracle server stores data is an example of:",
     ["A centralised architecture", "A two-tier architecture", "A three-tier architecture", "A peer-to-peer architecture"], 2,
     "Browser (presentation), application server (business logic) and database server (data) form three tiers."),
    ("To protect sensitive data travelling between tiers over a network, three-tier systems commonly use:",
     ["Encryption and decryption of transmitted data (e.g. TLS/SSL)", "Larger disks", "More indexes", "Normalisation"], 0,
     "Encrypting data at the sender and decrypting it at the receiver protects it in transit."),
    ("In client/server terminology, 'middleware' refers to:",
     ["The hard disk in the middle of the server rack", "Software that connects clients to servers and manages communication between them (e.g. ODBC drivers, application servers)",
      "The operating system kernel", "A type of index"], 1, "Middleware sits between client applications and back-end services."),
    ("In a two-tier architecture using ODBC, which component must be present on the client side?",
     ["The complete DBMS", "The ODBC driver/client library for the target DBMS", "A web server", "The database files"], 1,
     "The client-side driver translates API calls into requests the DBMS server understands."),
    ("Which statement about centralised versus client/server architectures is correct?",
     ["Client/server systems cannot share data", "In client/server systems, processing is divided between client and server machines",
      "Centralised systems need no hardware", "Client/server systems always use dumb terminals"], 1,
     "Dividing functions between clients and servers is the essence of client/server design."),
    ("In a client/server DBMS, which of the following is most likely performed on the client in a two-tier design?",
     ["Writing log records to disk", "Validating form input and displaying query results", "Deadlock detection", "Buffer management of database pages"], 1,
     "Presentation and input handling are client-side tasks."),
    ("In some object DBMS client/server designs, the server supplies disk pages or objects and the client performs much of the processing. Such a server is called a:",
     ["Query server", "Data server (page or object server)", "Web server", "Print server"], 1,
     "In the data-server approach, more DBMS functionality moves to the client; the server manages storage."),
    ("Which of these is a specialised server commonly found in client/server environments?",
     ["File server", "Print server", "Web server", "All of these"], 3, "Client/server systems include file, print, web, e-mail and database servers."),
    ("A key benefit of client/server DBMS architecture over file sharing on a network is that:",
     ["Whole files must be transferred to each client", "Only the query and its results travel over the network, reducing network traffic",
      "Clients need a copy of the DBMS", "No server is needed"], 1,
     "Processing happens on the server, so only the relevant results are sent to the client."),
    ("In a web-based three-tier application, the component that generates HTML pages from query results is usually the:",
     ["Database server", "Application/web server", "Client's operating system", "Disk controller"], 1,
     "The middle tier formats data (e.g. as HTML or JSON) before sending it to the client."),
    ("Scalability in a three-tier architecture is improved because:",
     ["Only one user can connect", "Application servers can be replicated and load-balanced independently of the database server",
      "Clients hold all the data", "The database server does all the work"], 1,
     "Each tier can be scaled separately, e.g. by adding more application servers."),
    ("A distributed DBMS differs from a client/server DBMS mainly in that:",
     ["It has no users", "The database itself is spread across several sites connected by a network",
      "It cannot use SQL", "It uses only dumb terminals"], 1,
     "In client/server systems the data usually reside on one server; in a distributed DBMS the data are stored at multiple sites."),
    ("Which statement about a two-tier architecture is TRUE?",
     ["The client never communicates with the DBMS", "The client communicates directly with the database server",
      "It always uses a web browser as the client", "It requires three physical machines"], 1,
     "In two-tier systems the client talks to the DBMS server directly, typically via ODBC/JDBC."),
]

SUBJECT = "P2 · Unit 5 – Database Management Systems"
TOPIC = "DBMS Concepts and Architecture"
sets = [("1 · Data Models", DATA_MODELS), ("2 · Schemas and Instances", SCHEMAS),
        ("3 · Three-Schema Architecture", THREE_SCHEMA), ("4 · Data Independence", DATA_INDEPENDENCE),
        ("5 · Database Languages and Interfaces", LANGUAGES), ("6 · Centralized and Client/Server Architectures", ARCHITECTURES)]
for name, qs in sets:
    assert len(qs) == 30, f"{name}: {len(qs)} questions"

build_pack(
    sys.argv[1],
    "P2 · Unit 5 DBMS — 1. Concepts & Architecture (180 Q)",
    "Database System Concepts and Architecture: data models; schemas and instances; three-schema architecture; data independence; "
    "database languages and interfaces; centralized and client/server architectures. 30 questions per sub-topic.",
    [{"name": SUBJECT, "icon": "🗄️", "topics": [{"name": TOPIC, "sets": [
        {"name": n, "tag": n.split(" · ", 1)[1], "questions": qs} for n, qs in sets]}]}],
)
