"""ExamSim question pack: GPSTR / CST 2026, study-plan days 1–2 (26–27 Sep).
Each question: (question, [4 options], index of correct option, explanation).
Options are shuffled deterministically to spread answers across A–D, except
ordered option sets (Only I / Both / Neither, assertion–reason)."""
import json, random, re, sys, hashlib
from pathlib import Path

OUT = Path(sys.argv[1])
SET_NAME = "Set 1 · Days 1–2 (26–27 Sep)"

P1 = {
    "PSY": ("P1 · Educational Psychology", "🧠"),
    "GK": ("P1 · General Knowledge", "🌍"),
    "KAN": ("P1 · General Kannada (ಸಾಮಾನ್ಯ ಕನ್ನಡ)", "ಕ"),
    "CL": ("P1 · Computer Literacy", "💻"),
    "ENG": ("P1 · General English", "📝"),
    "HE": ("P1 · Health Education", "🩺"),
    "VE": ("P1 · Value Education", "🌱"),
}
U1 = ("P2 · Unit 1 – Fundamentals of Computers", "🖥️")
U4 = ("P2 · Unit 4 – Programming Languages & Web", "⌨️")
AR = ["Both A and R are true, and R is the correct explanation of A",
      "Both A and R are true, but R is not the correct explanation of A",
      "A is true, but R is false", "A is false, but R is true"]
I_II = ["Only I", "Only II", "Both I and II", "Neither I nor II"]

TOPICS = []  # (subject, icon, topic name, [questions])

# ───────────────────────── PAPER 2 · UNIT 1 ─────────────────────────
TOPICS.append((*U1, "Introduction & Functional Components", [
    ("Which unit of the CPU generates the timing and control signals that direct the sequence of micro-operations, but does not itself operate on data?",
     ["Arithmetic Logic Unit", "Control Unit", "Memory Buffer Register", "Accumulator"], 1,
     "The control unit decodes instructions and issues control signals; the ALU performs the actual arithmetic and logic operations."),
    ("The 'von Neumann bottleneck' refers to:",
     ["The limited width of the ALU", "The single shared pathway between CPU and memory used for both instructions and data",
      "The slow speed of secondary storage compared with RAM", "The absence of cache memory in early computers"], 1,
     "In the von Neumann design, instructions and data travel over the same bus, so the CPU often waits for memory transfers."),
    ("Consider the statements:\nI. The Harvard architecture uses separate memories/buses for instructions and data.\nII. Most modern CPUs follow a modified Harvard design with split L1 instruction and data caches.\nWhich is/are correct?",
     I_II, 2, "Both are correct: pure Harvard separates instruction and data memory; modern CPUs split only the L1 caches while sharing main memory (modified Harvard)."),
    ("Which register holds the address of the next instruction to be fetched?",
     ["Instruction Register (IR)", "Memory Address Register (MAR)", "Program Counter (PC)", "Memory Buffer Register (MBR)"], 2,
     "The PC always points to the next instruction; its value is copied to the MAR at the start of the fetch cycle."),
    ("Which sequence of register transfers correctly describes the instruction fetch cycle?",
     ["IR ← PC; MAR ← IR; MBR ← M[MAR]", "MAR ← PC; MBR ← M[MAR], PC ← PC + 1; IR ← MBR",
      "MBR ← PC; IR ← MBR; MAR ← IR", "PC ← MAR; IR ← M[PC]; MBR ← IR"], 1,
     "The PC is copied to the MAR, memory is read into the MBR while the PC is incremented, and the instruction moves from the MBR to the IR."),
    ("The 'stored-program concept' introduced by John von Neumann means that:",
     ["Programs are permanently stored in ROM", "Instructions and data reside in the same read–write memory, so a program can be loaded and modified like data",
      "Programs are hard-wired into the control unit", "Programs are stored only on magnetic disks"], 1,
     "Before the stored-program idea, machines like ENIAC were programmed by rewiring; storing instructions in memory made computers general-purpose."),
    ("Which of the following is NOT one of the five classic functional units of a computer?",
     ["Input unit", "Control unit", "Compiler", "Arithmetic Logic Unit"], 2,
     "The five units are input, output, memory, ALU and control unit. A compiler is software, not a functional hardware unit."),
    ("A processor has a 32-bit address bus and byte-addressable memory. What is the maximum memory it can address directly?",
     ["4 GB", "2 GB", "32 MB", "4 MB"], 0,
     "2^32 addresses × 1 byte = 4,294,967,296 bytes = 4 GB."),
    ("After adding two signed (two's complement) numbers, which status flag indicates that the result is outside the representable range?",
     ["Carry flag", "Zero flag", "Overflow flag", "Parity flag"], 2,
     "The overflow flag signals signed overflow; the carry flag signals an unsigned carry out of the most significant bit."),
    ("Assertion (A): Widening the data bus can improve performance even at the same clock frequency.\nReason (R): A wider data bus transfers more bits in each bus cycle.",
     AR, 0, "Both are true and R explains A: more bits per transfer means fewer bus cycles for the same amount of data."),
]))

TOPICS.append((*U1, "Evolution, Generations, Classification, Applications", [
    ("Which generation–technology pairing is INCORRECT?",
     ["First generation – vacuum tubes", "Second generation – transistors", "Third generation – microprocessors",
      "Fifth generation – ULSI, parallel processing and AI"], 2,
     "Third generation computers used integrated circuits; microprocessors (VLSI) characterise the fourth generation."),
    ("ENIAC, completed in 1945–46, used approximately how many vacuum tubes?",
     ["About 1,800", "About 18,000", "About 180,000", "About 180"], 1,
     "ENIAC had roughly 17,468 vacuum tubes, weighed about 27 tonnes and consumed around 150 kW of power."),
    ("The Intel 4004 (1971), the first commercial single-chip microprocessor, was a:",
     ["4-bit processor", "8-bit processor", "16-bit processor", "32-bit processor"], 0,
     "The 4004 was a 4-bit CPU designed for a calculator; the 8008 (1972) and 8080 (1974) were 8-bit."),
    ("In Charles Babbage's Analytical Engine, the 'Mill' corresponds to which part of a modern computer?",
     ["Memory", "Processor (ALU)", "Input device", "Output device"], 1,
     "The 'Store' held numbers (memory) and the 'Mill' performed calculations (processor/ALU); punched cards gave input."),
    ("Which machine is credited with running the world's first stored program, in June 1948?",
     ["ENIAC", "Manchester Baby (SSEM)", "UNIVAC I", "Harvard Mark I"], 1,
     "The Small-Scale Experimental Machine at Manchester ran the first stored program on 21 June 1948; EDSAC (1949) was the first practical one."),
    ("A computer in a hospital ICU accepts continuous signals such as heartbeat and temperature, converts them to digital form and processes them. It is an example of a:",
     ["Analog computer", "Digital computer", "Hybrid computer", "Quantum computer"], 2,
     "Hybrid computers combine analog input handling with digital processing, as in ICU patient monitors."),
    ("India's first supercomputer, PARAM 8000 (1991), was developed by:",
     ["ISRO", "C-DAC, Pune", "BARC, Mumbai", "DRDO"], 1,
     "The Centre for Development of Advanced Computing (C-DAC) built PARAM 8000 after India was denied import of a Cray supercomputer."),
    ("UNIVAC I (1951) is notable because it was:",
     ["The first commercially produced computer in the United States", "The first transistorised computer",
      "The first microcomputer", "The first computer to use integrated circuits"], 0,
     "UNIVAC I was the first commercial computer produced in the US; it famously predicted the 1952 presidential election."),
    ("Moore's law, in its commonly cited (1975) form, states that:",
     ["Clock speed doubles every year", "The number of transistors on an integrated circuit doubles about every two years",
      "Memory prices halve every six months", "Processor power consumption doubles every five years"], 1,
     "Gordon Moore observed that transistor count doubles roughly every two years; clock speed is not part of the law."),
    ("Arrange in chronological order: Pascaline, Jacquard loom, Abacus, Analytical Engine.",
     ["Abacus → Pascaline → Jacquard loom → Analytical Engine", "Abacus → Jacquard loom → Pascaline → Analytical Engine",
      "Pascaline → Abacus → Jacquard loom → Analytical Engine", "Abacus → Pascaline → Analytical Engine → Jacquard loom"], 0,
     "Abacus (ancient), Pascaline (1642), Jacquard's punched-card loom (1804) and Babbage's Analytical Engine design (1837)."),
]))

TOPICS.append((*U1, "Input, Output and Memory Devices", [
    ("Which of the following is a non-impact printer?",
     ["Dot-matrix printer", "Daisy-wheel printer", "Laser printer", "Line printer"], 2,
     "Laser and inkjet printers form images without striking the paper; dot-matrix, daisy-wheel and line printers are impact printers."),
    ("MICR (Magnetic Ink Character Recognition) is mainly used for:",
     ["Processing bank cheques", "Evaluating OMR answer sheets", "Reading product barcodes", "Converting scanned text to editable text"], 0,
     "Cheques carry the MICR line printed in magnetic ink (E-13B font), which machines read quickly and reliably."),
    ("The print quality (resolution) of a laser printer is usually expressed in:",
     ["DPI", "PPM", "CPS", "LPM"], 0,
     "DPI (dots per inch) measures resolution; PPM (pages per minute) measures speed."),
    ("Which of the following memories is volatile?",
     ["ROM", "EEPROM", "SRAM", "Flash memory"], 2,
     "SRAM (like DRAM) loses its contents when power is removed; ROM, EEPROM and flash are non-volatile."),
    ("DRAM must be refreshed periodically because:",
     ["Each bit is stored as charge on a capacitor that gradually leaks", "It stores bits in flip-flops that lose state",
      "It is a non-volatile memory", "It stores data magnetically"], 0,
     "A DRAM cell is a transistor and a capacitor; the charge leaks within milliseconds, so it is refreshed. SRAM uses flip-flops and needs no refresh."),
    ("Arrange in order of decreasing access speed:",
     ["Registers > Cache > Main memory > SSD > Hard disk", "Cache > Registers > Main memory > Hard disk > SSD",
      "Registers > Main memory > Cache > SSD > Hard disk", "Cache > Main memory > Registers > SSD > Hard disk"], 0,
     "Registers are fastest, then cache (SRAM), main memory (DRAM), SSD (flash) and finally the mechanical hard disk."),
    ("The contents of an EPROM chip are erased by:",
     ["An electrical signal", "Exposure to ultraviolet light", "A strong magnetic field", "Heating the chip"], 1,
     "EPROM has a quartz window for UV erasure; EEPROM and flash are erased electrically."),
    ("Most smartphone touch screens detect a finger through a change in the electrostatic field. They are:",
     ["Resistive touch screens", "Capacitive touch screens", "Infrared touch screens", "Surface acoustic wave screens"], 1,
     "Capacitive screens sense the conductive human body; resistive screens respond to pressure and work with any stylus."),
    ("Plotters are preferred over ordinary printers mainly for:",
     ["High-volume text printing", "Large-format vector drawings such as engineering and CAD drawings",
      "Printing photographs", "Printing receipts"], 1,
     "Plotters draw continuous lines with pens or inkjets on large sheets, which suits maps and CAD drawings."),
    ("Which pair is correctly matched?",
     ["OCR – reads characters printed in magnetic ink", "OMR – detects marks made in predefined positions",
      "MICR – recognises handwritten text", "BCR – reads handwriting on forms"], 1,
     "OMR reads pencil/pen marks (e.g. answer sheets); OCR recognises printed text; MICR reads magnetic ink; BCR reads barcodes."),
]))

TOPICS.append((*U1, "Software Concepts & Problem Solving Methodology", [
    ("According to Donald Knuth, which of the following is NOT an essential property of an algorithm?",
     ["Finiteness", "Definiteness", "It must take at least one input", "Effectiveness"], 2,
     "An algorithm has zero or more inputs and one or more outputs, and must be finite, definite and effective."),
    ("Which of the following is system software?",
     ["MS Word", "A device driver", "Tally ERP", "Adobe Photoshop"], 1,
     "Device drivers let the OS control hardware; they are system software. The others are application software."),
    ("Firmware is best described as:",
     ["Software permanently stored in ROM/flash that controls a hardware device", "Software distributed free of cost",
      "Software whose source code is public", "Software that spreads without permission"], 0,
     "BIOS/UEFI and the code inside routers or printers are firmware, stored in non-volatile memory on the device."),
    ("Pseudocode is:",
     ["Code that the compiler translates directly", "An informal, language-independent description of an algorithm's logic",
      "Machine code written in hexadecimal", "A flowchart symbol"], 1,
     "Pseudocode uses structured English-like statements to plan logic before coding in any particular language."),
    ("Which kind of licence allows users to run, study, modify and redistribute the source code?",
     ["Freeware", "Shareware", "Free and open-source licence (e.g. GNU GPL)", "Proprietary end-user licence"], 2,
     "Freeware is free of cost but usually closed; open-source licences like the GPL grant the freedom to modify and share the code."),
    ("The 'top-down' approach to problem solving means:",
     ["Writing the detailed code first and combining it later", "Breaking the main problem into smaller sub-problems by stepwise refinement",
      "Testing the program before designing it", "Designing hardware before software"], 1,
     "Top-down design starts from the overall problem and refines it into modules; bottom-up design builds from small components."),
    ("What is printed by this algorithm?\nsum ← 0\nfor i ← 1 to 5\n  if i mod 2 = 1 then sum ← sum + i\nprint sum",
     ["15", "9", "6", "5"], 1, "Only odd values of i are added: 1 + 3 + 5 = 9."),
    ("Which of the following is a utility program?",
     ["Disk defragmenter", "Spreadsheet package", "Payroll system", "Railway reservation system"], 0,
     "Utilities (defragmenters, antivirus, backup tools) help maintain the computer; the others are application software."),
    ("A trace table is used to:",
     ["Dry-run an algorithm by recording the values of variables at each step", "Draw a flowchart", "Compile a program", "Test hardware components"], 0,
     "Dry-running with a trace table helps find logical errors before the program is executed."),
    ("In a flowchart, which symbol is used for a connector joining different parts of the chart?",
     ["Rectangle", "Diamond", "Small circle", "Parallelogram"], 2,
     "A small circle is an on-page connector; rectangle = process, diamond = decision, parallelogram = input/output."),
]))

TOPICS.append((*U1, "Word Processing, Spreadsheets, PowerPoint", [
    ("In MS Excel, how many cells are added by =SUM(A1:B3)?",
     ["5", "6", "3", "9"], 1, "A1:B3 is 2 columns × 3 rows = 6 cells."),
    ("In the Excel reference $A1:",
     ["The column is absolute and the row is relative", "The row is absolute and the column is relative",
      "Both row and column are absolute", "Both row and column are relative"], 0,
     "The $ fixes the part it precedes: $A1 keeps column A fixed while the row changes when copied."),
    ("Cell C1 contains =A1*$B$1. If it is copied to C3, the formula in C3 becomes:",
     ["=A3*$B$3", "=A3*$B$1", "=A1*$B$1", "=C3*$B$1"], 1,
     "The relative reference A1 shifts by two rows to A3; the absolute reference $B$1 does not change."),
    ("Mail Merge in MS Word combines:",
     ["The styles of two documents", "A main document with a data source to produce personalised copies",
      "Several macros into one", "Two tables into one"], 1,
     "Mail Merge fills fields (name, address…) from a data source such as an Excel sheet into a letter template."),
    ("Which PowerPoint view lets you rearrange slides by dragging their thumbnails, all on one screen?",
     ["Normal view", "Slide Sorter view", "Reading view", "Notes Page view"], 1,
     "Slide Sorter shows all slides as thumbnails for reordering, deleting and applying transitions."),
    ("Cells A1:A5 contain 10, \"abc\", (blank), 5 and TRUE. What does =COUNT(A1:A5) return?",
     ["2", "3", "4", "5"], 0,
     "COUNT counts only numeric values. Text, blanks and logical values inside a range are ignored, so only 10 and 5 are counted. COUNTA would return 4."),
    ("Which Excel error appears when a formula refers to a cell that is no longer valid, for example because it was deleted?",
     ["#VALUE!", "#REF!", "#NAME?", "#N/A"], 1,
     "#REF! means an invalid reference; #NAME? an unknown function name; #VALUE! a wrong type of argument; #N/A a value not available."),
    ("In MS Word, the shortcut Ctrl+J is used to:",
     ["Justify the paragraph", "Insert a hyperlink", "Centre the text", "Open the Go To dialog"], 0,
     "Ctrl+J justifies, Ctrl+E centres, Ctrl+K inserts a hyperlink and Ctrl+G opens Go To."),
    ("In PowerPoint, changes made to the Slide Master:",
     ["Apply the theme, layouts and fonts to all slides based on it", "Affect only the animations",
      "Affect only the current slide", "Change only the speaker notes"], 0,
     "The Slide Master stores the design shared by all slides, so one change updates the whole presentation."),
    ("A1 = 60 and B1 = 50. What does =IF(AND(A1>50, B1>50), \"Pass\", \"Fail\") return?",
     ["Pass", "Fail", "TRUE", "#VALUE!"], 1,
     "B1>50 is FALSE because 50 is not greater than 50, so AND returns FALSE and the formula gives \"Fail\"."),
]))

TOPICS.append((*U1, "Computer Configuration & Motherboard", [
    ("In traditional chipsets, which component linked the CPU with RAM and the graphics slot (the high-speed devices)?",
     ["Southbridge", "Northbridge", "Super I/O chip", "BIOS chip"], 1,
     "The northbridge handled high-speed links (memory, AGP/PCIe graphics); the southbridge handled slower I/O such as USB, SATA and audio."),
    ("The CMOS battery on a motherboard is used to:",
     ["Power the CPU when the mains supply fails", "Keep the real-time clock running and retain BIOS settings when the PC is off",
      "Charge the UPS", "Supply power to the hard disk"], 1,
     "A coin cell (CR2032) keeps the RTC and the CMOS settings alive while the computer is unplugged."),
    ("The Power-On Self-Test (POST) is performed by:",
     ["The operating system kernel", "The BIOS/UEFI firmware", "The OS boot loader", "A device driver"], 1,
     "POST runs from firmware immediately after power-on, before any operating system is loaded."),
    ("Which of these motherboard form factors is the smallest?",
     ["ATX", "Micro-ATX", "Mini-ITX", "E-ATX"], 2,
     "Mini-ITX is 17 × 17 cm; Micro-ATX is 24.4 × 24.4 cm; ATX is 30.5 × 24.4 cm; E-ATX is larger still."),
    ("On modern motherboards, the M.2 slot is mainly used for:",
     ["NVMe/SATA solid-state drives (and some Wi-Fi cards)", "RAM modules", "The power supply connector", "CPU fan headers"], 0,
     "M.2 is a small edge connector used mostly for NVMe SSDs running over PCIe lanes."),
    ("In modern Intel and AMD platforms, the memory controller that used to be in the northbridge is now located in:",
     ["The CPU itself", "The Platform Controller Hub", "The BIOS chip", "The SATA controller"], 0,
     "Integrating the memory controller into the CPU reduces memory latency; the remaining I/O functions sit in the PCH/chipset."),
    ("Modern graphics cards are installed in which type of expansion slot?",
     ["PCI Express x16", "AGP", "ISA", "PCI Express x1"], 0,
     "PCIe x16 provides the bandwidth that graphics cards need; AGP and ISA are obsolete."),
    ("SO-DIMM memory modules are mainly used in:",
     ["Laptops and small form-factor PCs", "Servers", "Graphics cards", "Hard disk controllers"], 0,
     "SO-DIMMs are about half the length of desktop DIMMs, which suits laptops and mini PCs."),
    ("Which feature is provided by UEFI but not by legacy BIOS?",
     ["Secure Boot and booting from GPT disks larger than 2 TB", "The Power-On Self-Test",
      "Choosing the boot device order", "Storing settings in CMOS"], 0,
     "UEFI supports GPT partitioning, Secure Boot and faster booting; POST, boot order and CMOS settings existed in legacy BIOS too."),
    ("DDR SDRAM achieves higher bandwidth than SDR SDRAM at the same clock because it:",
     ["Transfers data on both the rising and falling edges of the clock", "Uses two memory controllers",
      "Doubles the storage capacity of each chip", "Is non-volatile"], 0,
     "Double Data Rate means two transfers per clock cycle."),
]))

TOPICS.append((*U1, "Memory, Power Supply & Assembling", [
    ("An SMPS in a computer converts:",
     ["AC mains supply into regulated low-voltage DC (12 V, 5 V, 3.3 V)", "DC into high-voltage AC",
      "AC into higher-voltage AC", "Battery DC into AC for the monitor"], 0,
     "The switched-mode power supply rectifies and regulates the mains supply into the DC rails needed by the components."),
    ("How many pins does the main ATX power connector on a modern motherboard have?",
     ["20", "24", "8", "4"], 1,
     "The main ATX connector has 24 pins (older boards used 20); the separate 4/8-pin EPS connector powers the CPU."),
    ("Thermal paste is applied between the CPU and its heat sink to:",
     ["Glue the heat sink permanently", "Fill microscopic air gaps and improve heat transfer",
      "Insulate the CPU electrically", "Reduce the CPU's clock speed"], 1,
     "Air is a poor conductor; a thin layer of thermal paste fills surface irregularities so heat flows to the heat sink."),
    ("Which UPS type provides virtually zero switch-over time because the load always runs from the inverter?",
     ["Offline (standby) UPS", "Line-interactive UPS", "Online (double-conversion) UPS", "Uninterrupted transformer"], 2,
     "An online UPS continuously converts AC→DC→AC, so there is no transfer delay when mains power fails."),
    ("Cache memory is usually built from:",
     ["DRAM", "SRAM", "Flash memory", "EEPROM"], 1,
     "SRAM is faster than DRAM and needs no refresh, which suits small, fast cache memory."),
    ("Virtual memory allows a computer to:",
     ["Use part of secondary storage as an extension of main memory", "Use cache as a hard disk",
      "Store BIOS settings", "Increase the CPU clock speed"], 0,
     "Pages are swapped between RAM and a page file or swap space on disk, so programs can be larger than physical RAM."),
    ("How many bytes are there in 2 MiB?",
     ["2,000,000", "2,048,000", "2,097,152", "2,048"], 2,
     "1 MiB = 2^20 = 1,048,576 bytes, so 2 MiB = 2,097,152 bytes."),
    ("An '80 PLUS' certification on a PC power supply indicates:",
     ["An output of 80 W", "At least 80% energy efficiency at 20%, 50% and 100% load",
      "Safe operation up to 80 °C", "80 connectors"], 1,
     "80 PLUS certifies efficiency; higher grades (Bronze, Silver, Gold…) require even better efficiency."),
    ("Which is recommended practice when assembling a desktop computer?",
     ["Install the CPU, cooler and RAM on the motherboard before fixing it in the cabinet",
      "Connect the power cord before installing the RAM", "Apply thermal paste after fixing the heat sink",
      "Keep the PSU switched on while installing components"], 0,
     "Components are easier and safer to fit on an open board; all work is done with the power disconnected."),
    ("An anti-static wrist strap is worn while assembling a computer to:",
     ["Prevent electrostatic discharge damage to components", "Protect against electric shock from the mains",
      "Keep the hands cool", "Improve grip on screws"], 0,
     "Static charge from the body can destroy sensitive chips; the strap keeps you at the same potential as the chassis."),
]))

# ───────────────────────── PAPER 2 · UNIT 4 ─────────────────────────
TOPICS.append((*U4, "Language Design and Translation Issues", [
    ("Which language–paradigm pair is INCORRECT?",
     ["Prolog – logic programming", "Haskell – logic programming", "Smalltalk – object-oriented", "C – imperative/procedural"], 1,
     "Haskell is a purely functional language; Prolog is the classic logic-programming language."),
    ("What is the correct order of the main phases of a compiler?",
     ["Lexical analysis → Syntax analysis → Semantic analysis → Intermediate code → Optimisation → Code generation",
      "Syntax analysis → Lexical analysis → Semantic analysis → Code generation → Optimisation",
      "Lexical analysis → Semantic analysis → Syntax analysis → Optimisation → Code generation",
      "Parsing → Scanning → Code generation → Semantic analysis"], 0,
     "The scanner produces tokens, the parser builds a parse tree, semantic analysis checks types, then IR is generated, optimised and translated to target code."),
    ("The output of the lexical analyser is a stream of:",
     ["Parse trees", "Tokens", "Object code", "Three-address code"], 1,
     "The lexical analyser (scanner) groups characters into tokens such as identifiers, keywords and operators."),
    ("Which formal model is used to recognise the context-free syntax of programming languages?",
     ["Finite automaton", "Pushdown automaton", "Turing machine", "Mealy machine"], 1,
     "Context-free grammars are recognised by pushdown automata; finite automata recognise the regular languages used in lexical analysis."),
    ("A grammar is said to be ambiguous if:",
     ["It has left recursion", "Some string has more than one parse tree (or leftmost derivation)",
      "It contains ε-productions", "It generates an infinite language"], 1,
     "Ambiguity means one sentence can be derived in two different ways, e.g. the classic dangling-else problem."),
    ("In a dynamically typed language such as Python, the type of a variable is bound:",
     ["At language design time", "At compile time", "At run time", "At link time"], 2,
     "Dynamic typing binds types to values during execution; C and Java bind types at compile time."),
    ("Which statement is generally TRUE?",
     ["Compiled programs usually run faster than the same program interpreted", "An interpreter produces a standalone object file",
      "A compiler cannot detect syntax errors", "An interpreter translates the whole program before running any part"], 0,
     "A compiler translates the whole program in advance into machine code; an interpreter translates and executes statement by statement, which is slower."),
    ("'Orthogonality' in programming language design means:",
     ["A small set of primitive constructs can be combined in few ways, and every combination is legal and meaningful",
      "The language supports only right-angled graphics", "Every statement must end with a semicolon",
      "The language has no data types"], 0,
     "High orthogonality reduces exceptions to the rules, making a language easier to learn and read."),
    ("Just-In-Time (JIT) compilation, as used by the Java Virtual Machine, means:",
     ["Source code is compiled only once, at installation", "Bytecode is compiled into native machine code at run time, when needed",
      "The program is interpreted only", "Compilation happens on a remote server"], 1,
     "The JVM interprets bytecode and compiles frequently used parts (hot spots) into native code while the program runs."),
    ("BNF (Backus–Naur Form) is used to describe the:",
     ["Semantics of a language", "Syntax of a language", "Run-time environment", "Memory layout of a program"], 1,
     "BNF/EBNF notations formally specify the context-free syntax of programming languages."),
]))

TOPICS.append((*U4, "Elementary Data Types", [
    ("Which of the following is a composite (structured) data type?",
     ["int", "char", "enum", "array"], 3,
     "Arrays, structures and records are composite; int, char, float and enum are scalar (elementary) types."),
    ("A language is called 'strongly typed' if:",
     ["All type errors are always detected (at compile or run time)", "It has many data types", "Variables must be declared in upper case",
      "It supports only integer arithmetic"], 0,
     "Strong typing guarantees that type errors are caught; C is weakly typed because of unchecked casts and unions."),
    ("In C, the value of sizeof(char) is:",
     ["Always 1", "2 on 16-bit machines", "Always 8", "Implementation-defined, usually 4"], 0,
     "The C standard defines sizeof(char) as exactly 1 (one byte), whatever the number of bits in a byte."),
    ("What is the range of an 8-bit signed integer stored in two's complement?",
     ["−127 to +127", "−128 to +127", "−127 to +128", "0 to 255"], 1,
     "An n-bit two's complement number ranges from −2^(n−1) to 2^(n−1) − 1, i.e. −128 to +127 for 8 bits."),
    ("The automatic conversion of an int to a float in the expression 5 + 2.5 is called:",
     ["Type casting (explicit)", "Type coercion (implicit conversion)", "Type inference", "Overloading"], 1,
     "Coercion is done by the compiler implicitly; casting is written explicitly by the programmer, e.g. (float)5."),
    ("Two types are considered the same under 'structural equivalence' if:",
     ["They have the same name", "They have identical structure (same components in the same order)",
      "They are declared in the same statement", "They occupy the same memory address"], 1,
     "Name equivalence requires the same type name; structural equivalence compares the type structure."),
    ("In the IEEE 754 single-precision format, the numbers of sign, exponent and fraction bits are:",
     ["1, 8, 23", "1, 11, 52", "1, 7, 24", "2, 8, 22"], 0,
     "Single precision (32 bits) = 1 sign + 8 exponent + 23 fraction bits; double precision = 1 + 11 + 52."),
    ("In C, given enum colour { RED, GREEN = 5, BLUE };  what is the value of BLUE?",
     ["2", "5", "6", "3"], 2,
     "RED = 0, GREEN is explicitly 5, and each following enumerator is one more than the previous one, so BLUE = 6."),
    ("A descriptor (such as a dope vector for arrays) stores:",
     ["The attributes of a data object, such as its type, bounds and address", "Only the value of the variable",
      "The source code of a function", "The compiler's error messages"], 0,
     "Descriptors hold the information needed to access a data object, e.g. array bounds for index checking."),
    ("Which of the following is NOT a scalar (elementary) type in C?",
     ["float", "double", "struct", "char"], 2,
     "A struct groups several members, so it is a composite type."),
]))

TOPICS.append((*U4, "Programming in C – Part 1", [
    ("What is the output?\nint a = 10, b = 3;\nprintf(\"%d %d\", a / b, a % b);",
     ["3 1", "3.33 1", "3 0", "4 1"], 0, "Integer division truncates 10/3 to 3, and 10 % 3 = 1."),
    ("What is the output?\nchar s[] = \"hello\";\nprintf(\"%zu %zu\", sizeof(s), strlen(s));",
     ["5 5", "6 5", "5 6", "6 6"], 1,
     "The array includes the terminating '\\0', so sizeof is 6; strlen counts only the 5 visible characters."),
    ("What is the output?\nint i = 2;\nswitch (i) {\n  case 1: printf(\"A\");\n  case 2: printf(\"B\");\n  case 3: printf(\"C\"); break;\n  default: printf(\"D\");\n}",
     ["B", "BC", "BCD", "ABC"], 1,
     "Execution starts at case 2 and falls through to case 3 because there is no break after case 2; the break then stops before default."),
    ("What is the output?\nint i;\nfor (i = 0; i < 5; i++);\nprintf(\"%d\", i);",
     ["0", "4", "5", "01234"], 2,
     "The semicolon after the for makes an empty loop body; the loop ends when i becomes 5, then printf runs once."),
    ("Which of the following is a valid C identifier?",
     ["2total", "_count", "int", "my-var"], 1,
     "Identifiers may start with a letter or underscore and cannot be keywords or contain '-'."),
    ("Assuming a 4-byte int, what is sizeof(u) for:\nunion { int i; char c[8]; } u;",
     ["4", "8", "12", "16"], 1,
     "A union is as large as its largest member (8 bytes here); a struct would need space for all members."),
    ("What is the output?\nint arr[5] = {1, 2};\nprintf(\"%d\", arr[3]);",
     ["Garbage value", "0", "2", "Compile error"], 1,
     "When an array is partly initialised, the remaining elements are set to zero."),
    ("What is the value of x?\nint x = 2 + 3 * 4 > 10 && 5;",
     ["1", "14", "0", "5"], 0,
     "3*4 = 12, 2+12 = 14, 14 > 10 is 1, and 1 && 5 is 1 (true)."),
    ("What is the output?\nint n = 0;\ndo { n++; } while (n < 0);\nprintf(\"%d\", n);",
     ["0", "1", "Infinite loop", "−1"], 1,
     "A do-while body executes at least once before the condition is checked."),
    ("On a typical system with 4-byte int and 4-byte alignment, sizeof(struct { char c; int i; }) is:",
     ["5", "6", "8", "4"], 2,
     "Three padding bytes are inserted after c so that i starts on a 4-byte boundary: 1 + 3 + 4 = 8."),
]))

TOPICS.append((*U4, "Programming in C – Part 2", [
    ("What is the output?\nint a[] = {10, 20, 30};\nint *p = a;\nprintf(\"%d\", *(p + 2));",
     ["10", "20", "30", "Address of a[2]"], 2, "p + 2 points to a[2], and dereferencing it gives 30."),
    ("What is the output?\nint x = 5;\nint *p = &x;\nint **q = &p;\n**q = 10;\nprintf(\"%d\", x);",
     ["5", "10", "Address of x", "Compile error"], 1, "**q is the same object as *p, which is x, so x becomes 10."),
    ("What is the output?\nvoid f(int n) { n = 20; }\nint main() { int a = 10; f(a); printf(\"%d\", a); }",
     ["10", "20", "0", "Garbage"], 0,
     "C passes arguments by value; f changes only its local copy n."),
    ("What is the output?\nvoid f() { static int c = 0; c++; printf(\"%d\", c); }\nint main() { f(); f(); f(); }",
     ["111", "123", "000", "012"], 1,
     "A static local variable is initialised once and keeps its value between calls: 1, 2, 3."),
    ("What is the output?\n#define SQ(x) x*x\nprintf(\"%d\", SQ(2+3));",
     ["25", "11", "10", "13"], 1,
     "The macro expands to 2+3*2+3 = 2 + 6 + 3 = 11. Writing ((x)*(x)) would give 25."),
    ("A program is run as:  ./prog one two\nWhat is the value of argc?",
     ["2", "3", "1", "0"], 1, "argv[0] is the program name, so argc counts it too: prog, one, two = 3."),
    ("Which statement about fopen(\"data.txt\", \"a\") is correct?",
     ["It fails if the file does not exist", "It opens the file for appending and creates it if it does not exist",
      "It truncates the file to zero length", "It opens the file for reading only"], 1,
     "Mode \"a\" writes at the end of the file and creates the file if needed; \"w\" truncates; \"r\" fails if the file is missing."),
    ("What is the output?\nchar *s = \"ABC\";\nprintf(\"%c\", *(s + 1));",
     ["A", "B", "C", "66"], 1, "s + 1 points to the second character, 'B'."),
    ("A pointer p of type int* holds address 1000, and sizeof(int) is 4. After p++, p holds:",
     ["1001", "1002", "1004", "1008"], 2,
     "Pointer arithmetic scales by the size of the pointed-to type: 1000 + 1 × 4 = 1004."),
    ("Which statement is true of calloc() but not of malloc()?",
     ["It returns a void pointer", "It initialises the allocated memory to zero",
      "It allocates memory on the heap", "It returns NULL on failure"], 1,
     "Both allocate heap memory, return void* and can return NULL; only calloc zero-fills the block."),
]))

# ───────────────────────── PAPER 1 ─────────────────────────
TOPICS.append((*P1["PSY"], "Psychology & Educational Psychology", [
    ("Over time, psychology was successively defined as the science of:",
     ["Soul → Mind → Consciousness → Behaviour", "Mind → Soul → Behaviour → Consciousness",
      "Behaviour → Consciousness → Mind → Soul", "Soul → Consciousness → Mind → Behaviour"], 0,
     "The meaning shifted from the Greek 'psyche' (soul) to mind, then consciousness (Wundt, James) and finally behaviour (Watson)."),
    ("Who defined psychology as 'the science of behaviour'?",
     ["Wilhelm Wundt", "J. B. Watson", "William James", "Sigmund Freud"], 1,
     "Watson, founder of behaviourism (1913), rejected the study of consciousness in favour of observable behaviour."),
    ("'First psychology lost its soul, then it lost its mind, then it lost consciousness; it still has behaviour of a sort.' This remark is attributed to:",
     ["R. S. Woodworth", "E. B. Titchener", "B. F. Skinner", "Kurt Koffka"], 0,
     "Woodworth used this remark to summarise how the definition of psychology changed."),
    ("The first psychological laboratory was established in 1879 by:",
     ["William James at Harvard", "Wilhelm Wundt at Leipzig", "Ivan Pavlov at St Petersburg", "Francis Galton at London"], 1,
     "Wundt's Leipzig laboratory marks the start of experimental psychology as a separate science."),
    ("Who is regarded as the father of educational psychology?",
     ["E. L. Thorndike", "John Dewey", "B. F. Skinner", "Jean Piaget"], 0,
     "Thorndike's work 'Educational Psychology' (1903) and his laws of learning founded the field."),
    ("'Educational psychology is that branch of psychology which deals with teaching and learning.' This definition was given by:",
     ["B. F. Skinner", "Charles E. Skinner", "Crow and Crow", "Stephen"], 1,
     "The definition is by Charles E. Skinner, the educational psychologist, not the behaviourist B. F. Skinner."),
    ("The nature of educational psychology is best described as:",
     ["A normative science that prescribes ideals", "An applied, positive science of behaviour in educational situations",
      "A branch of philosophy", "A purely theoretical science"], 1,
     "It applies psychological principles to education and describes 'what is' rather than prescribing 'what ought to be'."),
    ("Which of the following is NOT usually included in the scope of educational psychology?",
     ["The learner", "The learning process", "The learning situation", "Deciding teachers' salary scales"], 3,
     "Its scope covers the learner, learning process, learning situation, evaluation and the teacher, not administrative pay matters."),
    ("Which school–founder pairing is INCORRECT?",
     ["Structuralism – E. B. Titchener", "Functionalism – William James", "Gestalt psychology – J. B. Watson", "Psychoanalysis – Sigmund Freud"], 2,
     "Gestalt psychology was founded by Max Wertheimer, with Köhler and Koffka; Watson founded behaviourism."),
    ("The principle 'the whole is different from (greater than) the sum of its parts' is central to:",
     ["Behaviourism", "Gestalt psychology", "Structuralism", "Psychoanalysis"], 1,
     "Gestalt psychologists stressed perceiving organised wholes, which led to insight learning (Köhler)."),
]))

TOPICS.append((*P1["PSY"], "Methods of Psychology", [
    ("Which method of psychology is least suitable for studying young children and people with mental disorders?",
     ["Observation", "Introspection", "Case study", "Experimental method"], 1,
     "Introspection needs a trained, articulate person to examine their own mental states, which young children cannot do."),
    ("The introspection method was mainly developed by the:",
     ["Behaviourists (Watson, Skinner)", "Structuralists (Wundt, Titchener)", "Gestaltists (Wertheimer)", "Psychoanalysts (Freud)"], 1,
     "Structuralists trained observers to report the elements of their conscious experience."),
    ("In an experiment on the effect of praise on pupils' test scores, 'praise' is the:",
     ["Dependent variable", "Independent variable", "Control variable", "Intervening variable"], 1,
     "The experimenter manipulates the independent variable (praise) and measures the dependent variable (test scores)."),
    ("A teacher studies a chronically absent pupil in depth, collecting family history, health records and interviews. This is the:",
     ["Experimental method", "Case study method", "Survey method", "Introspection method"], 1,
     "A case study is an intensive, many-sided study of one individual, often a problem child."),
    ("When the observer joins the group and takes part in its activities while observing, it is called:",
     ["Non-participant observation", "Participant observation", "Controlled observation", "Introspection"], 1,
     "In participant observation the observer becomes a member of the group being studied."),
    ("The main purpose of a control group in an experiment is to:",
     ["Receive the maximum treatment", "Provide a baseline for comparison with the experimental group",
      "Replace the experimental group if it fails", "Select the best subjects"], 1,
     "The control group does not receive the treatment, so any difference can be attributed to the independent variable."),
    ("People change their behaviour simply because they know they are being studied. This limitation of observation is known as the:",
     ["Halo effect", "Hawthorne effect", "Pygmalion effect", "Placebo effect"], 1,
     "The name comes from the Hawthorne Works studies (1920s–30s), where workers' productivity rose because they were being observed."),
    ("The experimental method is considered the most scientific method of psychology because it:",
     ["Is the cheapest", "Establishes cause-and-effect relationships under controlled conditions",
      "Needs no trained researcher", "Studies only one person at a time"], 1,
     "Controlling other variables lets the researcher conclude that changes in the dependent variable were caused by the independent variable."),
    ("Studying the same group of children from age 5 to 15 to track their development is the:",
     ["Cross-sectional method", "Longitudinal method", "Case study method", "Clinical method"], 1,
     "Longitudinal studies follow the same subjects over a long time; cross-sectional studies compare different age groups at one time."),
    ("Consider the statements:\nI. Introspection is an objective method.\nII. The experimental method can establish cause-and-effect relationships.\nWhich is/are correct?",
     I_II, 1, "Introspection is subjective, since only the person can observe their own mind; statement II is correct."),
]))

TOPICS.append((*P1["GK"], "Famous Books and Authors", [
    ("Which book did Jawaharlal Nehru write while imprisoned at Ahmednagar Fort (1942–46)?",
     ["Glimpses of World History", "The Discovery of India", "An Autobiography", "Letters from a Father to His Daughter"], 1,
     "The Discovery of India was written at Ahmednagar Fort; Glimpses of World History consists of letters written from prisons in 1930–33."),
    ("Match the books with their authors:\n(a) Anandamath (b) Nil Darpan (c) Gita Govinda (d) Mudrarakshasa\n1. Jayadeva 2. Dinabandhu Mitra 3. Vishakhadatta 4. Bankim Chandra Chattopadhyay",
     ["a-4, b-2, c-1, d-3", "a-2, b-4, c-1, d-3", "a-4, b-2, c-3, d-1", "a-1, b-2, c-4, d-3"], 0,
     "Anandamath (with 'Vande Mataram') is by Bankim Chandra, Nil Darpan by Dinabandhu Mitra, Gita Govinda by Jayadeva and Mudrarakshasa by Vishakhadatta."),
    ("The first Jnanpith Award for Kannada went to Kuvempu in 1967 for:",
     ["Malegalalli Madumagalu", "Sri Ramayana Darshanam", "Kanooru Heggadithi", "Nenapina Doniyali"], 1,
     "Kuvempu received the Jnanpith for his epic Sri Ramayana Darshanam; Malegalalli Madumagalu and Kanooru Heggadithi are his novels."),
    ("K. Shivaram Karanth received the Jnanpith Award (1977) for:",
     ["Mookajjiya Kanasugalu", "Chomana Dudi", "Marali Mannige", "Bettada Jeeva"], 0,
     "Mookajjiya Kanasugalu won the Jnanpith; Chomana Dudi, Marali Mannige and Bettada Jeeva are his other well-known novels."),
    ("Which book deeply influenced Mahatma Gandhi, who paraphrased it in Gujarati as 'Sarvodaya'?",
     ["Unto This Last – John Ruskin", "Civil Disobedience – Henry David Thoreau",
      "The Kingdom of God Is Within You – Leo Tolstoy", "Hind Swaraj – Gandhi himself"], 0,
     "Gandhi read Ruskin's Unto This Last in 1904 and translated its ideas as 'Sarvodaya' (welfare of all)."),
    ("'Poverty and Un-British Rule in India', which put forward the 'drain theory', was written by:",
     ["R. C. Dutt", "Dadabhai Naoroji", "M. G. Ranade", "Gopal Krishna Gokhale"], 1,
     "Dadabhai Naoroji argued that British rule drained India's wealth; R. C. Dutt wrote 'The Economic History of India'."),
    ("The earliest available literary work in Kannada, a treatise on poetics (c. 850 CE), is:",
     ["Vaddaradhane", "Kavirajamarga", "Vikramarjuna Vijaya", "Shabdamanidarpana"], 1,
     "Kavirajamarga, from the court of the Rashtrakuta king Amoghavarsha I (attributed to Srivijaya), is the earliest extant Kannada work."),
    ("Which pair is INCORRECTLY matched?",
     ["Indica – Megasthenes", "Rajatarangini – Kalhana", "Harshacharita – Kalidasa", "Arthashastra – Kautilya"], 2,
     "Harshacharita, the biography of King Harsha, was written by Banabhatta."),
    ("'Wings of Fire', the autobiography of Dr A. P. J. Abdul Kalam, was co-written with:",
     ["Arun Tiwari", "Y. S. Rajan", "Srijan Pal Singh", "Kushwant Singh"], 0,
     "Wings of Fire (1999) was written with Arun Tiwari; Kalam wrote 'India 2020' with Y. S. Rajan."),
    ("Adikavi Pampa's 'Vikramarjuna Vijaya' is popularly known as:",
     ["Pampa Ramayana", "Pampa Bharata", "Adipurana", "Gadayuddha"], 1,
     "Vikramarjuna Vijaya retells the Mahabharata (Pampa Bharata); Adipurana is Pampa's Jain work; Gadayuddha is by Ranna."),
]))

TOPICS.append((*P1["GK"], "Important Inventions and Discoveries", [
    ("Which discovery–scientist pair is INCORRECTLY matched?",
     ["Neutron – James Chadwick", "Radioactivity – Henri Becquerel", "Electron – Ernest Rutherford", "Penicillin – Alexander Fleming"], 2,
     "J. J. Thomson discovered the electron (1897); Rutherford discovered the atomic nucleus and the proton."),
    ("National Science Day (28 February) commemorates the discovery of:",
     ["The Bose–Einstein statistics", "The Raman Effect", "The Chandrasekhar limit", "The Saha ionisation equation"], 1,
     "C. V. Raman announced the Raman Effect on 28 February 1928 and received the Nobel Prize in Physics in 1930."),
    ("The first vaccine, against smallpox, was developed by Edward Jenner in 1796 using:",
     ["Weakened smallpox virus", "Material from cowpox lesions", "Killed bacteria", "Blood serum of horses"], 1,
     "Jenner observed that milkmaids who had cowpox did not get smallpox, and inoculated people with cowpox material."),
    ("The World Wide Web was invented in 1989 by Tim Berners-Lee at:",
     ["MIT", "CERN", "Bell Labs", "Stanford Research Institute"], 1,
     "Berners-Lee proposed the WWW at CERN, Geneva, and wrote the first web browser and server."),
    ("The transistor was invented in 1947 at Bell Labs by:",
     ["Bardeen, Brattain and Shockley", "Jack Kilby and Robert Noyce", "Edison and Tesla", "Eckert and Mauchly"], 0,
     "The three shared the 1956 Nobel Prize in Physics; Kilby and Noyce invented the integrated circuit."),
    ("Insulin was discovered in 1921 by:",
     ["Louis Pasteur", "Frederick Banting and Charles Best", "Robert Koch", "Selman Waksman"], 1,
     "Banting and Best isolated insulin at the University of Toronto; Banting shared the 1923 Nobel Prize with Macleod."),
    ("The laws of electromagnetic induction were discovered by:",
     ["Michael Faraday", "James Clerk Maxwell", "André-Marie Ampère", "Georg Ohm"], 0,
     "Faraday discovered electromagnetic induction in 1831, the basis of generators and transformers."),
    ("The circulation of blood in the human body was described by:",
     ["William Harvey", "Andreas Vesalius", "Galen", "Karl Landsteiner"], 0,
     "Harvey published De Motu Cordis in 1628; Landsteiner discovered blood groups."),
    ("Who proposed the heliocentric model, placing the Sun at the centre of the solar system?",
     ["Ptolemy", "Nicolaus Copernicus", "Tycho Brahe", "Aryabhata"], 1,
     "Copernicus published the heliocentric theory in 1543; Ptolemy's model was geocentric."),
    ("Radioactivity was discovered in 1896 by:",
     ["Marie Curie", "Henri Becquerel", "Wilhelm Röntgen", "Pierre Curie"], 1,
     "Becquerel found that uranium salts emit radiation; the Curies later discovered polonium and radium. Röntgen discovered X-rays (1895)."),
]))

TOPICS.append((*P1["KAN"], "ಕನ್ನಡ ವರ್ಣಮಾಲೆ", [
    ("ಪ್ರಸ್ತುತ ಕನ್ನಡ ವರ್ಣಮಾಲೆಯಲ್ಲಿರುವ ಒಟ್ಟು ಅಕ್ಷರಗಳ ಸಂಖ್ಯೆ ಎಷ್ಟು?",
     ["47", "49", "50", "52"], 1,
     "ಸ್ವರಗಳು 13 + ಯೋಗವಾಹಗಳು 2 + ವ್ಯಂಜನಗಳು 34 = 49 ಅಕ್ಷರಗಳು."),
    ("ಕನ್ನಡ ವರ್ಣಮಾಲೆಯಲ್ಲಿರುವ ಸ್ವರಗಳ ಸಂಖ್ಯೆ:",
     ["10", "12", "13", "14"], 2,
     "ಅ ಆ ಇ ಈ ಉ ಊ ಋ ಎ ಏ ಐ ಒ ಓ ಔ – ಒಟ್ಟು 13 ಸ್ವರಗಳು."),
    ("ಯೋಗವಾಹಗಳು ಯಾವುವು?",
     ["ಅನುಸ್ವಾರ ಮತ್ತು ವಿಸರ್ಗ", "ಋ ಮತ್ತು ೠ", "ಙ ಮತ್ತು ಞ", "ಳ ಮತ್ತು ಱ"], 0,
     "ಅನುಸ್ವಾರ (ಂ) ಮತ್ತು ವಿಸರ್ಗ (ಃ) ಯೋಗವಾಹಗಳು; ಇವು ಸ್ವತಂತ್ರವಾಗಿ ಉಚ್ಚರಿಸಲ್ಪಡದೆ ಬೇರೆ ಅಕ್ಷರಗಳ ಜೊತೆ ಸೇರಿ ಬರುತ್ತವೆ."),
    ("ವರ್ಗೀಯ ಮತ್ತು ಅವರ್ಗೀಯ ವ್ಯಂಜನಗಳ ಸಂಖ್ಯೆ ಕ್ರಮವಾಗಿ:",
     ["25 ಮತ್ತು 9", "20 ಮತ್ತು 14", "25 ಮತ್ತು 10", "24 ಮತ್ತು 10"], 0,
     "ಕ, ಚ, ಟ, ತ, ಪ ಎಂಬ ಐದು ವರ್ಗಗಳಲ್ಲಿ ತಲಾ 5 = 25 ವರ್ಗೀಯ; ಯ ರ ಲ ವ ಶ ಷ ಸ ಹ ಳ = 9 ಅವರ್ಗೀಯ ವ್ಯಂಜನಗಳು."),
    ("ಈ ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಅನುನಾಸಿಕ ಅಕ್ಷರ ಯಾವುದು?",
     ["ಘ", "ಣ", "ಳ", "ಶ"], 1,
     "ಪ್ರತಿ ವರ್ಗದ ಐದನೆಯ ಅಕ್ಷರಗಳಾದ ಙ ಞ ಣ ನ ಮ ಅನುನಾಸಿಕಗಳು."),
    ("ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಎಲ್ಲವೂ ಮಹಾಪ್ರಾಣ ಅಕ್ಷರಗಳಾಗಿರುವ ಗುಂಪು:",
     ["ಕ ಗ ಙ", "ಖ ಘ ಛ", "ಚ ಜ ಞ", "ಯ ರ ಲ"], 1,
     "ಪ್ರತಿ ವರ್ಗದ ಎರಡನೆಯ ಮತ್ತು ನಾಲ್ಕನೆಯ ಅಕ್ಷರಗಳು (ಖ ಘ, ಛ ಝ, ಠ ಢ, ಥ ಧ, ಫ ಭ) ಮಹಾಪ್ರಾಣಗಳು – ಒಟ್ಟು 10."),
    ("ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಎಲ್ಲವೂ ದೀರ್ಘ ಸ್ವರಗಳಾಗಿರುವ ಗುಂಪು:",
     ["ಆ ಈ ಏ ಐ", "ಅ ಇ ಉ ಋ", "ಎ ಒ ಆ ಈ", "ಇ ಊ ಏ ಒ"], 0,
     "ಹ್ರಸ್ವ ಸ್ವರಗಳು: ಅ ಇ ಉ ಋ ಎ ಒ (6). ದೀರ್ಘ ಸ್ವರಗಳು: ಆ ಈ ಊ ಏ ಐ ಓ ಔ (7)."),
    ("ಕೆಳಗಿನ ಪದಗಳಲ್ಲಿ ಸಜಾತೀಯ ಸಂಯುಕ್ತಾಕ್ಷರವಿರುವ ಪದ ಯಾವುದು?",
     ["ಶಕ್ತಿ", "ಅಮ್ಮ", "ವಿದ್ಯೆ", "ಸ್ವರ"], 1,
     "ಒಂದೇ ವ್ಯಂಜನ ಎರಡು ಬಾರಿ ಸೇರಿದರೆ ಸಜಾತೀಯ (ಮ್ + ಮ = ಮ್ಮ). ಶಕ್ತಿ (ಕ್+ತ), ವಿದ್ಯೆ (ದ್+ಯ), ಸ್ವರ (ಸ್+ವ) ವಿಜಾತೀಯ ಸಂಯುಕ್ತಾಕ್ಷರಗಳು."),
    ("'ಕಾ' ಎಂಬ ಗುಣಿತಾಕ್ಷರದಲ್ಲಿ ಸೇರಿರುವ ವರ್ಣಗಳು:",
     ["ಕ್ + ಆ", "ಕ + ಅ", "ಕ್ + ಅ + ಆ", "ಕ + ಆ"], 0,
     "ಗುಣಿತಾಕ್ಷರ = ವ್ಯಂಜನ (ಅರ್ಧಾಕ್ಷರ) + ಸ್ವರ. ಕ್ + ಆ = ಕಾ."),
    ("ಕೇಶಿರಾಜನು 'ಶಬ್ದಮಣಿದರ್ಪಣ'ದಲ್ಲಿ ಕನ್ನಡ ವರ್ಣಮಾಲೆಯ ಅಕ್ಷರಗಳ ಸಂಖ್ಯೆಯನ್ನು ಎಷ್ಟೆಂದು ಹೇಳಿದ್ದಾನೆ?",
     ["47", "49", "50", "34"], 0,
     "ಕೇಶಿರಾಜನ ಪ್ರಕಾರ ಕನ್ನಡದ ಅಕ್ಷರಗಳು 47. ಪ್ರಸ್ತುತ ಶಾಲಾ ಪಠ್ಯಪುಸ್ತಕಗಳಲ್ಲಿ 49 ಅಕ್ಷರಗಳನ್ನು ಗುರುತಿಸಲಾಗಿದೆ."),
]))

TOPICS.append((*P1["CL"], "Unit 1 – Introduction to Computer", [
    ("A computer inside an ATM or a washing-machine controller is an example of a:",
     ["General-purpose computer", "Special-purpose (embedded) computer", "Supercomputer", "Mainframe computer"], 1,
     "Special-purpose computers are built for one dedicated task; general-purpose computers run many kinds of programs."),
    ("SQL is classified as a:",
     ["First-generation language", "Second-generation language", "Third-generation language", "Fourth-generation language"], 3,
     "1GL = machine code, 2GL = assembly, 3GL = high-level languages like C, 4GL = non-procedural languages like SQL."),
    ("Which program translates assembly language into machine code?",
     ["Compiler", "Interpreter", "Assembler", "Linker"], 2,
     "An assembler converts mnemonics (MOV, ADD) into machine code; compilers and interpreters handle high-level languages."),
    ("Which memory can the CPU access directly?",
     ["Hard disk", "Primary memory (RAM, cache, registers)", "Pen drive", "DVD"], 1,
     "Secondary storage must first be loaded into main memory before the CPU can use it."),
    ("How many nibbles are there in 4 bytes?",
     ["4", "8", "16", "32"], 1, "1 byte = 8 bits = 2 nibbles, so 4 bytes = 8 nibbles."),
    ("Which storage device uses flash memory and has no moving parts?",
     ["Hard disk drive", "Solid-state drive (SSD)", "Magnetic tape", "Floppy disk"], 1,
     "SSDs store data in NAND flash chips, so they are faster and more shock-resistant than HDDs with spinning platters."),
    ("A computer that supports hundreds of users at once for bulk transaction processing, such as railway reservations or banking, is typically a:",
     ["Microcomputer", "Mainframe computer", "Workstation", "Embedded computer"], 1,
     "Mainframes (e.g. IBM Z) handle very large volumes of simultaneous transactions reliably."),
    ("Which of these is hardware rather than software?",
     ["BIOS", "Device driver", "Graphics card", "Compiler"], 2,
     "A graphics card is a physical component; the BIOS is firmware, and drivers and compilers are software."),
    ("Which language can be executed by the computer without any translation?",
     ["Assembly language", "Machine language", "C", "Python"], 1,
     "Machine language (binary) is the only language the CPU understands directly."),
    ("Which of these is a brand or type of operating system, not application software?",
     ["Tally", "Ubuntu", "Photoshop", "VLC Media Player"], 1,
     "Ubuntu is a Linux distribution (an operating system); the others are applications."),
]))

TOPICS.append((*P1["ENG"], "Parts of Speech", [
    ("Identify the part of speech of the word in capitals: He ran FAST to catch the bus.",
     ["Adjective", "Adverb", "Noun", "Verb"], 1, "'Fast' modifies the verb 'ran', telling how he ran, so it is an adverb."),
    ("Identify the part of speech of the word in capitals: The FAST was broken after sunset.",
     ["Noun", "Adjective", "Adverb", "Verb"], 0, "Here 'fast' means a period of not eating; it is the subject of the sentence, so it is a noun."),
    ("Identify the part of speech of the word in capitals: She is TOO tired to walk.",
     ["Adjective", "Adverb", "Preposition", "Conjunction"], 1, "'Too' modifies the adjective 'tired', so it is an adverb (of degree)."),
    ("Identify the part of speech of the word in capitals: BESIDES English, he speaks French.",
     ["Adverb", "Conjunction", "Preposition", "Adjective"], 2, "'Besides' is followed by the noun 'English' as its object, so it is a preposition."),
    ("Identify the part of speech of the word in capitals: He came AFTER I had left.",
     ["Preposition", "Adverb", "Conjunction", "Adjective"], 2,
     "'After' joins two clauses ('He came' and 'I had left'), so here it is a subordinating conjunction."),
    ("Identify the part of speech of the word in capitals: ALAS! He is no more.",
     ["Interjection", "Adverb", "Noun", "Conjunction"], 0, "'Alas' expresses sudden emotion (sorrow), so it is an interjection."),
    ("In 'SWIMMING is good exercise', the word in capitals is:",
     ["A verb", "A gerund (verbal noun)", "A present participle used as an adjective", "An adverb"], 1,
     "An -ing form used as a noun (here the subject) is a gerund."),
    ("In 'The RICH are not always happy', the word in capitals is used as a:",
     ["Adjective", "Noun", "Adverb", "Verb"], 1, "'The rich' means rich people; an adjective preceded by 'the' can work as a plural noun."),
    ("In 'This is the book THAT I bought yesterday', the word in capitals is a:",
     ["Demonstrative pronoun", "Relative pronoun", "Conjunction", "Demonstrative adjective"], 1,
     "'That' introduces a relative clause describing 'the book', so it is a relative pronoun."),
    ("In 'She sings WELL', the word in capitals is a/an:",
     ["Adjective", "Adverb", "Noun", "Interjection"], 1,
     "'Well' modifies the verb 'sings'. In 'She is well', it would be an adjective meaning healthy."),
]))

TOPICS.append((*P1["HE"], "Health Education – Basics", [
    ("Which dimension is NOT part of the WHO's original 1948 definition of health?",
     ["Physical well-being", "Mental well-being", "Social well-being", "Spiritual well-being"], 3,
     "WHO (1948): 'Health is a state of complete physical, mental and social well-being and not merely the absence of disease or infirmity.' The spiritual dimension was discussed later."),
    ("World Health Day is observed every year on:",
     ["7 April", "1 December", "31 May", "5 June"], 0,
     "It marks the founding of the WHO on 7 April 1948. 1 Dec is World AIDS Day, 31 May is World No Tobacco Day and 5 June is World Environment Day."),
    ("The word 'hygiene' is derived from Hygieia, who in Greek mythology was the goddess of:",
     ["Wisdom", "Health", "Harvest", "Water"], 1, "Hygieia, daughter of Asclepius, was the Greek goddess of health, cleanliness and sanitation."),
    ("Screening school staff for diabetes to detect it early is an example of:",
     ["Primary prevention", "Secondary prevention", "Tertiary prevention", "Health promotion"], 1,
     "Secondary prevention means early diagnosis and prompt treatment; primary prevention (e.g. immunisation) stops disease from occurring."),
    ("Immunisation of children is an example of:",
     ["Primary prevention (specific protection)", "Secondary prevention", "Tertiary prevention", "Rehabilitation"], 0,
     "Specific protection such as vaccination prevents the disease from occurring at all."),
    ("The main aim of health education is to:",
     ["Treat diseases", "Bring desirable changes in people's health knowledge, attitudes and practices",
      "Build more hospitals", "Train doctors"], 1,
     "Health education aims at voluntary behaviour change, often measured as KAP (knowledge, attitude, practice)."),
    ("Global Handwashing Day is observed on:",
     ["15 October", "2 October", "22 March", "7 April"], 0,
     "15 October promotes handwashing with soap; 2 October is Gandhi Jayanti and 22 March is World Water Day."),
    ("Swachh Bharat Mission was launched on:",
     ["15 August 2014", "2 October 2014", "26 January 2015", "2 October 2019"], 1,
     "It was launched on Gandhi Jayanti, 2 October 2014; India was declared open-defecation-free on 2 October 2019."),
    ("According to the WHO, the normal Body Mass Index (BMI) range for adults is:",
     ["16.0–18.4", "18.5–24.9", "25.0–29.9", "30.0–34.9"], 1,
     "BMI = weight (kg) ÷ height (m)². Below 18.5 is underweight, 25–29.9 overweight and 30 or more obese."),
    ("Personal hygiene such as washing hands before eating mainly prevents diseases spread through the:",
     ["Faeco-oral route, e.g. typhoid and cholera", "Airborne route, e.g. tuberculosis", "Vector route, e.g. malaria", "Sexual route"], 0,
     "Contaminated hands carry germs from faeces to the mouth; handwashing breaks this chain."),
]))

TOPICS.append((*P1["VE"], "Value Education – Basics", [
    ("The word 'value' is derived from the Latin word 'valere', which means:",
     ["To be of worth / to be strong", "To value money", "To follow rules", "To teach"], 0,
     "'Valere' means to be strong or to be of worth; values are what we consider worthwhile."),
    ("According to the NCERT document on value education, how many values were listed?",
     ["10", "37", "83", "108"], 2, "NCERT's 'Documents on Social, Moral and Spiritual Values in Education' listed 83 values."),
    ("A value that is desired for its own sake, and not as a means to something else, is called a/an:",
     ["Instrumental value", "Intrinsic value", "Material value", "Extrinsic value"], 1,
     "Intrinsic (terminal) values such as truth or happiness are ends in themselves; instrumental values such as money are means to other ends."),
    ("The five human values promoted in Sathya Sai Education in Human Values (EHV) are:",
     ["Sathya, Dharma, Shanti, Prema, Ahimsa", "Liberty, Equality, Fraternity, Justice, Dignity",
      "Honesty, Punctuality, Obedience, Cleanliness, Courtesy", "Truth, Wealth, Power, Fame, Beauty"], 0,
     "Truth, Right Conduct, Peace, Love and Non-violence are presented as the universal human values."),
    ("Which of the following is NOT a characteristic of values?",
     ["Values are learned", "Values are relatively enduring", "Values are fixed at birth and cannot change",
      "Values guide behaviour"], 2, "Values are acquired through socialisation and education and can change over time."),
    ("Which set of values is enshrined in the Preamble to the Indian Constitution?",
     ["Justice, Liberty, Equality and Fraternity", "Truth, Non-violence and Peace",
      "Duty, Discipline and Devotion", "Wealth, Health and Happiness"], 0,
     "The Preamble secures justice, liberty and equality to all citizens and promotes fraternity."),
    ("Which of the following is primarily a social value?",
     ["Punctuality", "Cooperation", "Self-discipline", "Cleanliness of one's body"], 1,
     "Cooperation concerns our relations with others; the other options are mainly personal values."),
    ("Which commission recommended a 'conscious and organised attempt' to impart education in social, moral and spiritual values?",
     ["Radhakrishnan Commission", "Kothari Commission (1964–66)", "Mudaliar Commission", "Hunter Commission"], 1,
     "The Kothari (Education) Commission stressed moral, social and spiritual values in education."),
    ("In Krathwohl's taxonomy of the affective domain, 'Valuing' comes immediately after:",
     ["Receiving", "Responding", "Organisation", "Characterisation"], 1,
     "The order is Receiving → Responding → Valuing → Organisation → Characterisation by a value."),
    ("Moral values are primarily concerned with:",
     ["Right and wrong conduct", "Economic profit", "Artistic beauty", "Physical fitness"], 0,
     "Moral values such as honesty and fairness guide judgements about right and wrong behaviour."),
]))

# ───────────────────────── build ─────────────────────────
ORDERED = re.compile(r"^(Only|Both|Neither|A is|a-\d)|→|>")


def keep_order(q, opts):
    return "Assertion (A)" in q or any(ORDERED.search(o) for o in opts)


problems, counts, seen = [], {"A": 0, "B": 0, "C": 0, "D": 0}, set()
subjects = {}
for subj, icon, topic, qs in TOPICS:
    out = []
    for i, (q, opts, ans, expl) in enumerate(qs):
        if len(opts) != 4 or len(set(opts)) != 4:
            problems.append(f"{topic} Q{i+1}: needs 4 distinct options")
        if not 0 <= ans < 4:
            problems.append(f"{topic} Q{i+1}: bad answer index")
        if q in seen:
            problems.append(f"{topic} Q{i+1}: duplicate question")
        seen.add(q)
        order = list(range(4))
        if not keep_order(q, opts):
            random.Random(hashlib.md5(q.encode()).hexdigest()).shuffle(order)
        new_opts = [opts[k] for k in order]
        letter = "ABCD"[order.index(ans)]
        counts[letter] += 1
        out.append({"question": q, "options": dict(zip("ABCD", new_opts)), "answer": letter,
                    "subject": topic, "explanation": expl})
    s = subjects.setdefault(subj, {"name": subj, "icon": icon, "topics": []})
    s["topics"].append({"name": topic, "sets": [{"name": SET_NAME, "questions": out}]})

if problems:
    print("\n".join(problems)); sys.exit(1)
pack = {"examsimPack": 1, "name": "GPSTR / CST 2026 — Days 1–2 questions (26–27 Sep)",
        "description": "Higher-difficulty questions for the study-plan topics of 26–27 September: Paper 2 Unit 1 and C/programming basics, "
                       "plus Paper 1 psychology, GK, Kannada, computer literacy, English, health and value education.",
        "subjects": list(subjects.values())}
OUT.write_text(json.dumps(pack, ensure_ascii=False, indent=1), encoding="utf-8")
total = sum(counts.values())
print(f"{len(TOPICS)} topics, {total} questions, answer spread {counts}")
