"""Previous-year paper · KEA Competitive Examination 2026 (departmental recruitment, NHK/RPC) · Specific Paper-2 · Computer Science ·
5 Jul 2026, afternoon · subject code CAA2675 · version A1 · 100 Q, 300 marks, negative marking (¼ of the marks per wrong answer).
Source: KEA question-paper archive, cetonline.karnataka.gov.in/keawebentry456/QP2026/COMPETITIVE_EXAM__04_05_JULY_26_P2_CS_RPC_05_07_26_13072026kannada.pdf
(scanned; transcribed from the page images). Options (1)–(4) are A–D in the printed order.
No key for this paper was found on KEA's site, so every answer was worked out by ExamSim and is NOT the official key.
Skipped: Q10 (the correct set {b, c} is not an option), Q21, Q25 (the Gray-code formula is printed with ⊙/XNOR), Q31 (no option
matches the register state after the step), Q41 (the correct pair ii and iii is not an option), Q52 (figure-dependent wait-for graph),
Q54 (hash and direct files both fit), Q61 (no option is a correct correlated query), Q65 (error detection and CRC both fit)."""

SRC = "KEA 2026 CS Paper-2 · Q{}"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

Q = {
1: ("Data structure used for finding whether a string is a palindrome or not is ____.",
    ["Heap", "Tree", "Priority queue", "Stack"], 3,
    "Push the characters and pop them to get the reverse; compare with the original."),
2: ("Which of the following is NOT a real world example of a stack?\n(a) Undo feature in text editors\n(b) Browser back button history\n(c) Breadth first search in programming\n(d) Queue at a ticket counter",
    ["(a), (b) and (c)", "(a) and (b)", "(c) and (d)", "(d) and (a)"], 2,
    "BFS and a ticket-counter queue are FIFO (queues); undo and back-button history are LIFO (stacks)."),
3: ("Match the following data structures in List-I with its concepts in List-II:\n(a) Binary search tree\n(b) Graph\n(c) Dynamic array\n(d) Max heap\n(i) Elements stored in contiguous memory location that can grow dynamically\n(ii) Tree where each node has at most two children\n(iii) Complete Binary tree where parent ≥ children\n(iv) Data structure consisting of nodes connected by edges can be cyclic.",
    ["a – i, b – iii, c – iv, d – ii", "a – ii, b – i, c – iii, d – iv", "a – iii, b – i, c – ii, d – iv", "a – ii, b – iv, c – i, d – iii"], 3,
    "A BST is a binary tree, a graph may contain cycles, a dynamic array is contiguous and growable, and a max heap is a complete tree with parent ≥ children."),
4: ("Arrange the following data structures in increasing order of access time for retrieving the iᵗʰ-element (average case).\n(a) Array\n(b) Singly linked list\n(c) Binary search tree\n(d) Dynamic Array",
    ["(a), (d), (c), (b)", "(d), (a), (c), (b)", "(a), (d), (b), (c)", "(c), (b), (a), (d)"], 0,
    "Arrays and dynamic arrays give O(1) indexed access (the plain array listed first), a BST O(log n), a linked list O(n)."),
5: ("In open addressing, if a collision occurs at index i, linear probing checks which index next?\n(a) i + 1\n(b) h(k)²\n(c) i/2\n(d) Random index",
    ["(a), (b), (c)", "Only (a)", "(a), (b), (d)", "Only (d)"], 1,
    "Linear probing tries (i + 1) mod m, then i + 2, and so on."),
6: ("Find the time complexity for the given algorithm.\n1. Repeat for I = 1 to N:\n2.   Repeat for J = 1 to N:\n3.     Repeat for K = 1 to N:\n4.       Module A.\n        [End of step 3 loop.]\n      [End of step 2 loop.]\n    [End of step 1 loop.]\n5. Exit",
    ["O(n²)", "O(n³)", "O(n)", "O(1)"], 1,
    "Three nested loops of N iterations each: N³ executions of Module A."),
7: ("For the graph given, find the following:\n(a) In-degree of vertex (2)\n(b) Out-degree of vertex (3)\n(c) Set of vertices adjacent from vertex (2)\n(Directed edges in the figure: 1→2, 1→4, 4→3, 3→5, 3→2, 5→2)",
    ["a – 3, b – 2, c – {1, 5, 3}", "a – 3, b – 2, c – 0", "a – {1, 5, 3}, b – 2, c – 3", "a – {1, 2}, b – 2, c – 1"], 1,
    "Edges into 2 come from 1, 5 and 3; vertex 3 points to 5 and 2; vertex 2 has no outgoing edges, so nothing is adjacent from it."),
8: ("Find the output of the given POSTFIX expression 5 3 1 * + 4 2 / −",
    ["5", "6", "7", "8"], 1,
    "3 × 1 = 3; 5 + 3 = 8; 4 / 2 = 2; 8 − 2 = 6."),
9: ("For a given AVL tree with height H, the maximum number of nodes it can have is ____.",
    ["2^(H+1) − 1", "2^(H−1)", "H + H − 1", "2^H + 3"], 0,
    "The maximum is a perfect binary tree: 2^(H+1) − 1 nodes (height counted from 0)."),
11: ("Consider a job scheduling problem with 4 jobs J1, J2, J3, J4 with deadlines (d₁, d₂, d₃, d₄) = (3, 1, 4, 2), each job takes 1 unit of time. Which of the following schedules is feasible without violating any deadline?\n(a) J2 → J4 → J1 → J3\n(b) J1 → J2 → J3 → J4\n(c) J4 → J3 → J1 → J2\n(d) J3 → J1 → J2 → J4",
    ["(a) only", "(a) and (b) only", "(c) and (d) only", "(a) and (d) only"], 0,
    "In (a) the jobs finish at 1, 2, 3, 4 against deadlines 1, 2, 3, 4. In (b), (c) and (d), J2 (deadline 1) finishes later than time 1."),
12: ("Match the following given concepts in List-I with the description in List-II.\n(a) AVL tree\n(b) B tree\n(c) Heap\n(d) Hashing\n(i) Direct access using hash function\n(ii) Complete binary tree used in priority queue\n(iii) Self balancing binary search tree\n(iv) Used in database indexing",
    ["a – iii, b – iv, c – ii, d – i", "a – ii, b – i, c – iii, d – iv", "a – i, b – ii, c – iii, d – iv", "a – iv, b – iii, c – i, d – ii"], 0,
    "AVL = self-balancing BST; B-tree = database indexes; heap = priority queue; hashing = direct access."),
13: ("Let L₁ = {w ∈ {0, 1}* | w has at least as many occurrences of (110)'s as (011)'s}\nLet L₂ = {w ∈ {0, 1}* | w has at least as many occurrences of (000)'s as (111)'s}\nWhich one of the following is true?",
    ["Both L₁ and L₂ are regular", "L₂ is regular but not L₁", "L₁ is regular but not L₂", "Neither L₁ nor L₂ is regular"], 2,
    "Occurrences of 110 and 011 can differ by at most one, so a finite automaton can track L₁; comparing counts of 000 and 111 needs unbounded counting (GATE 2014)."),
14: ("Consider the following deterministic finite automata M (it accepts exactly the strings containing 001: start state loops on 1; 0 → second state; from there 1 returns to start and 0 → third state; third state loops on 0 and goes on 1 to the accepting state, which loops on 0, 1).\nLet S be the set of seven bit binary strings in which the first, the fourth and the last bit are 1. The number of strings in S that are accepted by M is",
    ["1", "7", "5", "8"], 1,
    "Strings look like 1 b₂ b₃ 1 b₅ b₆ 1. They contain 001 exactly when b₂b₃ = 00 or b₅b₆ = 00: 4 + 4 − 1 = 7 (GATE 2003)."),
15: ("Match the following grammar machine (List-I) with its capability (List-II)\n(a) Deterministic PDA\n(b) Non-deterministic PDA\n(c) Finite Automata\n(d) Context Sensitive Grammar\n(i) Accepts exactly the class of context free languages\n(ii) Equivalent to the class of regular languages\n(iii) Accepts deterministic context-free language\n(iv) Requires a linear bounded automata",
    ["a – ii, b – iii, c – iv, d – i", "a – iv, b – ii, c – iii, d – i", "a – iii, b – iv, c – ii, d – i", "a – iii, b – i, c – ii, d – iv"], 3,
    "DPDA ↔ DCFL, NPDA ↔ CFL, FA ↔ regular, CSG ↔ linear-bounded automata."),
16: ("Which of the following statements is/are false?\n(a) Turing recognizable languages are closed under union and intersection\n(b) Turing recognizable languages are closed under union and complementation\n(c) Turing decidable languages are closed under intersection and complementation\n(d) For every non-deterministic turing machine, there exists an equivalent deterministic turing machine",
    ["Only (b)", "(a) and (b)", "(b) and (d)", "(c) and (d)"], 0,
    "Recognisable languages are not closed under complement (the halting problem's complement is not recognisable); the rest are true."),
17: ("For the given non-deterministic finite automata (A loops on 0, A –ε→ B, B loops on 1, B –ε→ C, C loops on 2; A is the start state and C is the final state), what are the final states of the deterministic finite automata (DFA) generated?",
    ["[A, B], [A, C], [ ]", "[B, C], [A], [ ]", "{{A, B, C}, {B, C}, {C}}", "{B, C, A}"], 2,
    "Start = ε-closure(A) = {A, B, C}; on 1 → {B, C}; on 2 → {C}. All three contain C, so all are final."),
18: ("Match the grammar types (List-I) with their properties (List-II).\n(a) Type regular grammar\n(b) Unrestricted grammar\n(c) Context-sensitive grammar\n(d) Type 0 grammar\n(i) No restriction on production length\n(ii) Linear bounded automaton\n(iii) Most restrictive grammar\n(iv) Generate RE language",
    ["a – iv, b – iii, c – ii, d – i", "a – iii, b – i, c – ii, d – iv", "a – ii, b – iv, c – i, d – iii", "a – iv, b – ii, c – i, d – iii"], 1,
    "Regular grammars are the most restricted; unrestricted grammars have no length limit; CSGs match LBAs; type-0 grammars generate RE languages."),
19: ("For the DFA transition table given below, give the final state for the input string \"aa\".\nState | a | b\nq0 | q1 | q0\nq1 | q2 | q1\nq2 | q2 | q0",
    ["q1", "q0", "q0, q2", "q2"], 3,
    "q0 –a→ q1 –a→ q2."),
20: ("Which of the following problems are decidable?\n(A) Does a given problem/program ever produce an output?\n(B) If L is a context-free language, then is L′ (complement of L) also context-free?\n(C) If L is a regular language, then is L′ also regular?\n(D) If L is a recursive language, then is L′ also recursive?",
    ["A, B and C", "B, C", "C, D", "A, C"], 2,
    "Regular and recursive languages are closed under complement (always 'yes'); the output problem and CFL-complement question are undecidable."),
22: ("____ is caused because of a delay in the availability of instruction.",
    ["Data Hazard", "Instruction Hazard", "Interrupt Hazard", "Structural Hazard"], 1,
    "Hamacher: an instruction (control) hazard is a pipeline stall because the next instruction is not available, e.g. after a cache miss or branch."),
23: ("In a variable entered K-MAP for a four-variable expression, if two variables are entered inside the map, how many cells/locations will the map contain?",
    ["4 locations", "8 locations", "16 locations", "2 locations"], 0,
    "Two of the four variables are entered in the cells, so the map is on the other two variables: 2² = 4 cells."),
24: ("Give the minimal SOP expression for the following expression:\nf(A, B, C) = Σm(0, 2, 4, 6)",
    ["C", "C̅", "B̅C", "BC̅"], 1,
    "Minterms 0, 2, 4, 6 are exactly the even ones, where C = 0: f = C̅."),
26: ("A 16-bit computer which generates 16-bit addresses is capable of addressing ____ memory locations.",
    ["2³² = 4 G", "2⁴⁰ = 1 T", "2¹⁶ = 64 KB", "2⁴ = 256 bytes"], 2,
    "16 address bits give 2¹⁶ = 65,536 locations (64 K)."),
27: ("Match the following.\n(a) SR flip flop\n(b) JK flip flop\n(c) D flip flop\n(d) T flip flop\n(i) Register\n(ii) Asynchronous counter design\n(iii) Race around condition\n(iv) Forbidden state",
    ["a – iii, b – i, c – ii, d – iv", "a – ii, b – i, c – iv, d – iii", "a – i, b – ii, c – iv, d – iii", "a – iv, b – iii, c – i, d – ii"], 3,
    "SR has the forbidden S = R = 1 state; JK has race-around; D flip-flops build registers; T flip-flops build ripple counters."),
28: ("Match the terms in List-I with List-II:\n(a) Decoders\n(b) Encoders\n(c) Multiplexer (Mux)\n(d) Demultiplexer (Demux)\n(i) n to 1\n(ii) 1 to n\n(iii) n to 2ⁿ line\n(iv) 2ⁿ to n line",
    ["a – ii, b – iii, c – iv, d – i", "a – iv, b – i, c – ii, d – iii", "a – iii, b – iv, c – i, d – ii", "a – iii, b – iv, c – ii, d – i"], 2,
    "Decoder n → 2ⁿ, encoder 2ⁿ → n, MUX many-to-one, DEMUX one-to-many."),
29: ("Arrange the following memory types in a memory hierarchy according to increasing speed:\n(a) Main memory\n(b) Secondary storage (magnetic disk)\n(c) Primary cache (L1)\n(d) Registers\n(e) Secondary cache (L2)",
    ["b, e, c, a, d", "a, b, d, c, e", "a, b, c, d, e", "b, a, e, c, d"], 3,
    "Disk < main memory < L2 < L1 < registers."),
30: ("Arrange the following searching methods according to average case time complexity (best to worst):\n(a) Linear search\n(b) Binary search\n(c) Hashing",
    ["(a), (b) and (c)", "(b), (c) and (a)", "(c), (b) and (a)", "(a), (c) and (b)"], 2,
    "Hashing O(1), binary search O(log n), linear search O(n)."),
32: ("Subtract the following numbers using 2's complement → 13 from 11: Perform the Subtraction 11 − 13 using two's complement method.",
    ["0010", "1110", "0001", "1101"], 1,
    "1011 + 2's complement of 1101 (0011) = 1110, with no carry: the result is −(0010) = −2, shown as 1110."),
33: ("What will be DFA for the given NFA? (NFA: q0 loops on a; q0 –b, c→ q1; q1 loops on a, c; q1 is final)",
    ["q0 loops on b, c; q0 –a→ q1 (final); q1 loops on a", "q0 loops on a; q0 –b→ q1 (final); q1 loops on c", "q0 loops on a; q0 –b, c→ q1 (final); q1 loops on b, c; q1 –a→ φ; φ loops on a, b, c", "q0 loops on a; q0 –b, c→ q1 (final); q1 loops on a, c; q1 –b→ φ (dead state); φ loops on a, b, c"], 3,
    "The NFA is already deterministic except that q1 has no b-move; adding a dead state φ for that move completes the DFA."),
34: ("For the given context-free grammar G, what is the language generated by G where S is the starting non-terminal symbol?\nS → aSb | T\nT → bT | b",
    ["{aᵐbⁿ : 0 < m < n}", "{aᵐbⁿ : 0 < n ≤ m}", "{aᵐbⁿ : 0 ≤ m < n}", "{aᵐbⁿ : 0 ≤ n}"], 2,
    "S gives aᵐ T bᵐ and T gives at least one b, so n = m + k with k ≥ 1 and m ≥ 0."),
35: ("Token recognition in a lexical analyzer is primarily based on ____.",
    ["Parse Trees", "Backtracking Algorithm", "Regular Expression", "Context-free Grammar"], 2,
    "Token patterns are regular expressions, implemented as finite automata."),
36: ("Match the following lexical analysis concept (List-I) with characteristics (List-II)\n(a) DFA\n(b) NFA\n(c) Subset Construction\n(d) Lexical Error\n(e) Tokenization\n(i) Conversion method from NFA to DFA\n(ii) No ε-moves\n(iii) Process of breaking input into token\n(iv) Multiple transitions for same input possible\n(v) Invalid character sequence",
    ["a – iii, b – i, c – iv, d – v, e – ii", "a – ii, b – iv, c – i, d – v, e – iii", "a – i, b – ii, c – iv, d – iii, e – v", "a – v, b – iii, c – ii, d – i, e – iv"], 1,
    "A DFA has no ε-moves, an NFA may have several moves on one symbol, subset construction converts NFA → DFA."),
37: ("Which of the following statements is true with respect to parsers?",
    ["LALR (1) is more powerful than canonical LR (1)", "SLR is more powerful than LALR (1)", "Canonical LR (1) is more powerful than LALR (1)", "SLR and LALR (1) have the same power"], 2,
    "SLR ⊂ LALR(1) ⊂ canonical LR(1)."),
38: ("Suppose activation records are stored in the heap instead of stack, which of the following properties is most likely affected?",
    ["Recursion support", "Parameter passing", "Automatic deallocation in LIFO order", "Contents of activation record"], 2,
    "Heap records are not freed automatically in last-in-first-out order when a call returns."),
39: ("Match the parser type (List-I) with its characteristics (List-II)\n(a) LR (0)\n(b) SLR (1)\n(c) Canonical LR (1)\n(d) LALR (1)\n(i) Uses follow sets to decide reduce actions\n(ii) Most powerful among deterministic LR parsers with single lookahead\n(iii) Constructed by merging states having identical LR (0) cores\n(iv) Reduce action applied without lookahead symbols",
    ["a – ii, b – i, c – iv, d – iii", "a – iii, b – ii, c – i, d – iv", "a – iv, b – ii, c – i, d – iii", "a – iv, b – i, c – ii, d – iii"], 3,
    "LR(0) reduces without lookahead, SLR uses FOLLOW sets, CLR(1) is the most powerful, LALR merges states with equal cores."),
40: ("Consider the following sequence of events for generating code for a function call:\n(i) Push arguments\n(ii) Allocate activation record\n(iii) Transfer control to callee\n(iv) Restore caller state\nWhich is the correct chronological order?",
    ["i → iii → ii → iv", "i → ii → iii → iv", "i → iv → ii → iii", "ii → i → iii → iv"], 0,
    "The caller pushes arguments and jumps; the callee then sets up the rest of its activation record; on return the caller's state is restored."),
42: ("A grammar contains direct left recursion\nE → E + T | T\nWhich parser type cannot handle this grammar directly?",
    ["LL (1) Parser", "LR (0) Parser", "SLR (1) Parser", "LALR (1) Parser"], 0,
    "Top-down LL parsers loop forever on left recursion; LR parsers handle it."),
43: ("Consider the following set of processes that arrive at time 0 with length of the CPU burst time given in milliseconds: P1 = 26, P2 = 4, P3 = 5. What is the average waiting time for the processes that arrive in the orders P1, P2, P3 and P2, P1, P3 under FCFS policy?",
    ["18.65 and 11.32", "18.66 and 11.33", "18.64 and 11.31", "18.63 and 11.32"], 1,
    "Order 1: waits 0, 26, 30 → 56/3 ≈ 18.67. Order 2: waits 0, 4, 30 → 34/3 ≈ 11.33. Option 2 is the closest (truncated) value."),
44: ("Many-to-many multithreading Model multiplexes ____",
    ["Many-user-level threads to one kernel thread", "Many-user-level threads to small or equal number of kernel threads", "Each user thread to a kernel thread", "One kernel thread to many-user-level threads"], 1,
    "Silberschatz's definition of the many-to-many model."),
45: ("Paging is a memory management scheme that permits\n(a) The physical address space of a process to be non-contiguous\n(b) Physical memory is divided into fixed sized blocks called pages\n(c) Eliminates the need for compaction\n(d) Logical memory is divided into blocks of the same size called frames\nWhich of the aforementioned statements are correct?",
    ["(a) and (d)", "(a) and (c)", "(b) and (d)", "(b) and (c)"], 1,
    "Physical blocks are frames and logical blocks are pages, so (b) and (d) swap the names; paging has no external fragmentation, so no compaction."),
46: ("The information that are associated with an open file\n(a) Creating a file, Access rights\n(b) Opening a file, File pointer\n(c) File pointer, File open count\n(d) Disk location of the file, Access rights\nWhich of the aforementioned statements are correct?",
    ["(c) and (d)", "(a) and (d)", "(b) and (d)", "(a), (b) and (c)"], 0,
    "Silberschatz: file pointer, file-open count, disk location and access rights are kept for each open file."),
47: ("Consider the following snapshot of a system (Banker's algorithm):\nProcess | Allocation A B C D | Max A B C D\nP0 | 0 0 1 2 | 0 0 1 2\nP1 | 1 0 0 0 | 1 7 5 0\nP2 | 1 3 5 4 | 2 3 5 6\nP3 | 0 6 3 2 | 0 6 5 2\nP4 | 0 0 1 4 | 0 6 5 6\nAvailable = 1 5 2 0.\nFor the processes (i) P0 (ii) P1 (iii) P2 (iv) P3 (v) P4, the correct safe sequence is",
    ["(i), (ii), (iv), (v), (iii)", "(i), (v), (ii), (iii), (iv)", "(i), (iii), (ii), (iv), (v)", "(i), (v), (iv), (ii), (iii)"], 2,
    "Need: P0 0000, P1 0750, P2 1002, P3 0020, P4 0642. P0 → avail 1532; P2 → 2886; P1 → 3886; P3 → 3 14 11 8; P4 finishes. P1 or P4 cannot run straight after P0."),
48: ("If the page size is 2048 bytes and a process needs 72766 bytes, find the total number of frames allocated and what is the internal fragmentation?",
    ["35 Frames 1080 bytes", "35 Frames 962 bytes", "36 Frames 1086 bytes", "36 Frames 962 bytes"], 3,
    "72766 / 2048 = 35.53 → 36 frames = 73728 bytes; 73728 − 72766 = 962 bytes wasted."),
49: ("Consider the following steps in a DMA transfer:\n(i) Disk controller initiates DMA transfer\n(ii) Disk driver tells disk controller to transfer of bytes from disk to buffer\n(iii) Disk controller sends each byte to DMA controller\n(iv) Device driver is told to transfer disk data to buffer\nIdentify the correct sequence.",
    ["(iv), (i), (ii), (iii)", "(i), (ii), (iii), (iv)", "(i), (iii), (iv), (ii)", "(iv), (ii), (i), (iii)"], 3,
    "Silberschatz's six-step DMA example begins: driver told → driver tells controller → controller initiates DMA → controller sends bytes."),
50: ("Match List-I with List-II:\n(a) FCFS Scheduling\n(b) SJF Scheduling\n(c) Priority Scheduling\n(d) RR Scheduling\n(i) Shortest burst time\n(ii) Indefinite Blocking\n(iii) Time slice\n(iv) Convoy effect",
    ["a – ii, b – iii, c – i, d – iv", "a – iii, b – ii, c – iv, d – i", "a – iv, b – i, c – ii, d – iii", "a – i, b – iii, c – ii, d – iv"], 2,
    "FCFS suffers the convoy effect, SJF picks the shortest burst, priority scheduling risks starvation, RR uses a time quantum."),
51: ("Match List-I (Address binding & space) with List-II (Performed by):\n(a) Compile time\n(b) Load time\n(c) Logical address\n(d) Physical address\n(i) One loaded into the memory address register\n(ii) Generated by CPU\n(iii) Relocatable code must be generated by compiler\n(iv) Absolute code can be generated",
    ["a – iv, b – iii, c – ii, d – i", "a – iii, b – iv, c – i, d – ii", "a – iv, b – i, c – ii, d – iii", "a – iii, b – ii, c – i, d – iv"], 0,
    "Silberschatz: compile-time binding gives absolute code, load-time binding needs relocatable code, the CPU generates logical addresses, and the MAR holds physical ones."),
53: ("A relation is in 3 NF if it has following one of the properties.",
    ["It is in 1 NF and has no partial dependency", "It is in 2 NF and has no transitive dependency", "It has no repeating groups", "It has a candidate key"], 1,
    "3NF = 2NF with no transitive dependency of non-key attributes on the key."),
55: ("An SQL command which is used to remove all rows from a table without disturbing the table structure is",
    ["DROP", "DELETE", "TRUNCATE", "REMOVE"], 2,
    "TRUNCATE empties the table; DROP removes the table itself."),
56: ("A TRC query containing ∃ t ∈ R is expressing",
    ["Join operation", "Universal condition on all tuples of R", "Projection of attributes", "Existence of at least one tuple in R satisfying the predicate"], 3,
    "∃ is the existential quantifier; ∀ would express a universal condition."),
57: ("Which relational algebra expression retrieves names of employees working in department 10?",
    ["π DeptNo (σ Name = 10 (Employee))", "σ Name = DeptNo (Employee)", "π Name (σ DeptNo = 10 (Employee))", "Employee ∩ DeptNo = 10"], 2,
    "Select the department-10 tuples, then project Name."),
58: ("Match the following normal forms in List-I with their defining conditions mentioned in the List-II.\n(a) 1 NF\n(b) 2 NF\n(c) 3 NF\n(d) BCNF\n(i) No transitive dependency\n(ii) No partial dependency\n(iii) Atomic values only\n(iv) Every determinant is a candidate key",
    ["a – ii, b – iii, c – iv, d – i", "a – iii, b – ii, c – i, d – iv", "a – iv, b – iii, c – ii, d – i", "a – i, b – iv, c – iii, d – ii"], 1,
    "1NF atomic values (printed 'Automatic values'), 2NF no partial dependency, 3NF no transitive dependency, BCNF every determinant a candidate key."),
59: ("Match the following index structures given in List-I with characteristics given in List-II.\n(a) Index File\n(b) Sequential Files\n(c) B+ Trees\n(d) Sparse Index\n(i) Indexing large datasets\n(ii) Not all key values present\n(iii) Records accessed one after another\n(iv) Speeds up records retrieval",
    ["a – iii, b – i, c – ii, d – iv", "a – iv, b – iii, c – i, d – ii", "a – ii, b – i, c – iii, d – iv", "a – iii, b – iv, c – ii, d – i"], 1,
    "An index speeds retrieval, sequential files are read in order, B+ trees index large data, a sparse index holds only some key values."),
60: ("In Multi-Data Item strict 2PL problem, the given transactions are\nT1: R(A); W(A); R(B); W(B)\nT2: R(B); W(B).\nFind the maximum locks held at peak.",
    ["2", "4", "3", "5"], 0,
    "Under strict 2PL, T1 holds locks on A and B until it commits; T2 needs B and must wait, so at most 2 locks are held at once."),
62: ("Consider a relation: Student (SID, Name, DeptID) with rows (1, Alice, CS), (2, Bob, EE), (3, Carol, CS). Find the relational algebra expression to find CS students.",
    ["π Name (σ DeptID = 'CS' (Student))", "π Name (DeptID = CS ('CS Student'))", "π Name (Name = EE ('EE Student'))", "'CS Student' ÷ DeptID"], 0,
    "Select the CS rows and project the names: Alice and Carol."),
63: ("Assume the stop-and-wait system, the bandwidth of the line is 1 Mbps and 1 bit takes 20 milliseconds to make a round trip. Compute bandwidth-delay product if the system data packets are 1000 bits in length. What is the utilization percentage of the link?",
    ["2000 bits, 10%", "2,00,000 bits, 4.5%", "20,000 bits, 4.76%", "200 bits, 50%"], 2,
    "BDP = 10⁶ × 0.02 = 20,000 bits. Sending 1000 bits takes 1 ms, so one cycle is 21 ms: 1/21 ≈ 4.76%."),
64: ("A ____ server that transfers the complete information about a zone from another server and stores the file on its local disk with respect to DNS.",
    ["Primary server", "Root server", "Secondary server", "Load server"], 2,
    "A secondary server obtains the zone by zone transfer from the primary."),
66: ("Identify the type of the following destination addresses with respect to ethernet:\n(a) 4A:30:10:21:10:1A\n(b) 47:20:1B:2E:08:EE\n(c) FF:FF:FF:FF:FF:FF",
    ["(a) Unicast, (b) Multicast, (c) Broadcast", "(a) Multicast, (b) Unicast, (c) Broadcast", "(a) Broadcast, (b) Unicast, (c) Multicast", "(a) Unicast, (b) Broadcast, (c) Multicast"], 0,
    "The least significant bit of the first byte is 0 for unicast (4A = …1010) and 1 for multicast (47 = …0111); all 1s is broadcast (Forouzan)."),
67: ("The data structure indicates types of datagrams that are to be processed by IPsec with respect to network layer security is",
    ["Security Association Database (SAD)", "Security Parameter Index (SPI)", "Security Policy Database (SPD)", "Security Datagram Database (SDD)"], 2,
    "The SPD decides which packets get IPsec processing; the SAD holds the parameters of each security association."),
68: ("The interaction sequence in DHCP client server is\n(a) DHCP Discover\n(b) DHCP Request\n(c) DHCP Offer\n(d) DHCP ACK",
    ["(a), (b), (c), (d)", "(a), (c), (b), (d)", "(a), (c), (d), (b)", "(d), (a), (b), (c)"], 1,
    "DORA: Discover, Offer, Request, Acknowledge."),
69: ("What is the type of address used in transport layer?",
    ["Logical address", "Names", "Port number", "Link layer address"], 2,
    "Transport-layer addresses are port numbers; IP addresses are logical (network-layer) addresses."),
70: ("Datagram switching is done at",
    ["Data link layer", "Network layer", "Transport layer", "Physical layer"], 1,
    "Forouzan: datagram switching is normally done at the network layer."),
71: ("For the following encoding/decoding schemes, with respect to fast ethernet:\n(i) 100 Base-TX\n(ii) 100 Base-FX\n(iii) 100 Base-T4\nIdentify the medium support for each of the above.",
    ["Fiber, UTP or STP, UTP", "UTP or STP, Fiber, UTP", "UTP, UTP or STP, Fiber", "Fiber, UTP, UTP or STP"], 1,
    "100Base-TX: two pairs of Cat 5 UTP or STP; 100Base-FX: fibre; 100Base-T4: four pairs of Cat 3 UTP."),
72: ("Match the following with respect to FTP:\n(a) 200\n(b) 230\n(c) 501\n(d) 530\n(e) 425\n(i) User login OK\n(ii) Command OK\n(iii) Cannot open data connection\n(iv) Syntax error in parameters and arguments\n(v) User not logged in",
    ["a – ii, b – i, c – iv, d – v, e – iii", "a – iii, b – ii, c – v, d – i, e – iv", "a – v, b – iii, c – iv, d – ii, e – i", "a – i, b – iii, c – iv, d – ii, e – v"], 0,
    "FTP replies: 200 command OK, 230 user logged in, 425 can't open data connection, 501 syntax error in arguments, 530 not logged in."),
73: ("What is the DOM (Document Object Model) in HTML?",
    ["Language-dependent application programming", "ASP.NET object hierarchy", "API", "HTML document object representation and interaction convention"], 3,
    "The DOM is a language-independent convention for representing and interacting with objects in HTML and XML documents."),
74: ("Which of the following statements is/are correct regarding how XML data is described?\n(a) XML uses DTD to describe the data\n(b) XML uses XSL to describe the data\n(c) XML uses a description node to describe the data codes\n(d) XML uses URL to describe the data",
    ["(a) only", "(b) only", "(a) and (b)", "(a), (c) and (d)"], 0,
    "A DTD (or schema) describes XML structure; XSL describes how to transform or present it."),
75: ("In a three-tier architecture, do the presentation tier and the data tier communicate directly with each other?",
    ["Yes always", "No, communication goes through the application tier", "Only when using specific protocol like FTP", "Yes, but only for image data"], 1,
    "The middle (application/logic) tier sits between presentation and data."),
76: ("Which of the following are the life cycle events of ASP.NET pages?\n(a) Compile document and call constructor\n(b) Initialize control state with view state\n(c) Save control state in view state\n(d) Execute instance and return results to client",
    ["(a) and (b) are correct", "(b) and (c) are correct", "(a), (b) and (d) are correct", "(a), (b), (c) and (d) are correct"], 3,
    "Sebesta describes all four: compile and construct, restore state from view state, save state back into view state, and render the result to the client."),
77: ("What problem does connection pooling solve in J2EE application?",
    ["Reduces servlet initialization time", "Minimizes database connection overhead", "Eliminates need for JDBC", "Avoids HTTP session tracking"], 1,
    "Opening database connections is costly; a pool reuses them."),
78: ("Consider the following server-side code snippet.\nRemoteService service = new RemoteServiceImpl();\nNaming.rebind(\"rmi://localhost:1099/RemoteService\", service);\nSystem.out.println(\"service bound.\");\nNaming.unbind(\"service unbound.\");\nWhat happens to the remote object instance (service) on the server after \"Naming.unbind()\" is called, assuming no clients are actively holding references?",
    ["The object is immediately garbage collected", "The object becomes unreferenced in the registry but remains active in server JVM", "The server throws remote exception", "The stub is removed from the server, but skeleton remains bound"], 1,
    "unbind only removes the registry entry; the object stays exported (and the local variable still refers to it) until unexported."),
79: ("Match the REST architectural constraints with its meaning:\n(a) Stateless\n(b) Uniform interface\n(c) Layered system\n(d) Resource identification\n(i) Uniform resource manipulation\n(ii) No client context stored on server\n(iii) Intermediaries allowed\n(iv) URI-based access",
    ["a – i, b – iii, c – ii, d – iv", "a – iii, b – ii, c – iv, d – i", "a – ii, b – i, c – iii, d – iv", "a – iv, b – ii, c – i, d – iii"], 2,
    "Stateless servers keep no client context; the uniform interface standardises manipulation; layers allow intermediaries; resources are identified by URIs."),
80: ("Match the following JSP Internal mechanisms:\n(a) jspInit()\n(b) jsp:setProperty with property = \"*\"\n(c) PageContext object\n(d) isELIgnored=\"true\"\n(i) Forces a page re-evaluation by bypassing the translation phase\n(ii) Introspects request parameters to automatically populate bean fields\n(iii) User-defined initialization logic that runs once during the JSP lifecycle\n(iv) A unified interface to access all four scopes (Page, Request, Session, App)",
    ["a – iii, b – ii, c – iv, d – i", "a – iv, b – iii, c – ii, d – i", "a – i, b – iv, c – ii, d – iii", "a – ii, b – i, c – iii, d – iv"], 0,
    "jspInit runs once, setProperty=\"*\" copies request parameters into bean properties, PageContext reaches all scopes; (d) is left for isELIgnored (which actually turns off EL evaluation)."),
81: ("What will be the output of the following program?\nint main()\n{\n  int x = 5, y = 7, z;\n  z = x + y;\n  printf(\"%d\", x);\n  printf(\"%d\", y);\n  printf(\"%d\", z);\n}",
    ["5 12 0", "0 7 12", "5 7 12", "12 12 12"], 2,
    "It prints x = 5, y = 7 and z = 12 (with no spaces in the actual output: 5712)."),
82: ("Given\nint a[3] = {1, 2, 3};\nprintf(\"%d\", a[3]);\nChoose the correct answer.",
    ["3", "garbage", "error", "0"], 1,
    "a[3] is past the end of the array: undefined behaviour, typically a garbage value; C does no bounds checking."),
83: ("Match the following functions in List-I with their purpose in List-II.\n(a) strcat(S1, S2)\n(b) strncmp(S1, S2, n)\n(c) strchr(S1, ch)\n(d) strstr(S1, S2)\n(i) Returns pointer to first occurrence ch in S1\n(ii) Returns pointer to first occurrence S2 in S1\n(iii) Concatenates S2 to S1\n(iv) Compares two strings based on n and returns a value",
    ["a – iv, b – iii, c – i, d – ii", "a – iii, b – iv, c – i, d – ii", "a – ii, b – iii, c – i, d – iv", "a – i, b – iii, c – iv, d – ii"], 1,
    "strcat appends, strncmp compares up to n characters, strchr finds a character, strstr finds a substring."),
84: ("An array has been declared as int a[] = {1, 2, 3, 4, 5, ….}; How can you find the number of elements of the array without manually counting them?",
    ["printf(\"%d\", sizeof(n));", "printf(\"%d\", sizeof(a)/sizeof(a[0]));", "printf(\"%d\", sizeof(int[a]));", "printf(\"%d\", sizeof(a[0]));"], 1,
    "Total bytes of the array divided by the bytes of one element."),
85: ("What will the following switch statement print?\nchar C = 'Y';\nswitch (C)\n{\n  case 'Y': printf(\"Yes/No\");\n  case 'N': printf(\"No/Yes\");\n            break;\n  default: printf(\"other\");\n}",
    ["Other", "Yes/No Other", "Other Yes/No", "Yes/No No/Yes"], 3,
    "case 'Y' has no break, so control falls through into case 'N' and then breaks."),
86: ("The following is a graphical representation of function f(t) = { t, 0 < t < 1; 1 − t, 1 < t < 2 }",
    ["Rises from (0, 0) to (1, 1), then falls from (1, 0) to (2, −1)", "Rises from (0, 0) to (1, 1), then rises from (1, −1) to (2, 0)", "A single line falling from (0, 1) to (2, −1)", "Falls from (0, 0) to (1, −1), then rises to (2, 0)"], 0,
    "On (0, 1) f = t rises to 1; on (1, 2) f = 1 − t starts at 0 and falls to −1."),
87: ("If n is a positive integer, then the z-transform of (n + 1)² is",
    ["(z² − z³)/(z − 1)²", "(z³ − z²)/(z + 1)²", "(z² + z³)/(z + 1)³", "(z³ + z²)/(z − 1)³"], 3,
    "Z{n²} = z(z + 1)/(z − 1)³; shifting left by one (x(0) = 0) multiplies by z: (z³ + z²)/(z − 1)³."),
88: ("Match the following Probability Distributions with their Mean:\n(a) Binomial\n(b) Poisson\n(c) Normal\n(d) Discrete\n(i) Σxᵢp(xᵢ)\n(ii) μ\n(iii) λ\n(iv) np",
    ["a – ii, b – iii, c – iv, d – i", "a – i, b – ii, c – iii, d – iv", "a – iii, b – i, c – ii, d – iv", "a – iv, b – iii, c – ii, d – i"], 3,
    "Binomial np, Poisson λ, normal μ, a discrete distribution Σ xᵢ p(xᵢ)."),
89: ("The following equations represent the equation of regression lines: x + 6y − 4 = 0; 2x + 3y + 1 = 0; then the correlation co-efficient 'r' is given by",
    ["r = 0.5", "r = −0.5", "r = 2", "r = −2"], 1,
    "Taking the first as y on x (b_yx = −1/6) and the second as x on y (b_xy = −3/2): r² = 1/4, and both slopes are negative, so r = −0.5. (The other assignment gives r² = 4, impossible.)"),
90: ("What is the order of convergence of Newton-Raphson method?",
    ["1", "1.6", "2", "3"], 2,
    "Newton–Raphson converges quadratically (the secant method about 1.618)."),
91: ("Match the following:\n(a) Diagonal matrix A\n(b) Null matrix A\n(c) Determinant of a matrix A\n(d) Trace of a matrix A\n(i) Product of the eigen values of A\n(ii) No eigen values\n(iii) Sum of the eigen values of A\n(iv) Eigen values are diagonal elements",
    ["a – ii, b – iii, c – iv, d – i", "a – iii, b – iv, c – i, d – ii", "a – iv, b – ii, c – i, d – iii", "a – i, b – iii, c – ii, d – iv"], 2,
    "Diagonal matrices have their diagonal entries as eigenvalues; det = product and trace = sum of eigenvalues. (Strictly, a null matrix has all eigenvalues 0; the paper pairs it with 'no eigenvalues'.)"),
92: ("The system of linear equations is consistent if and only if",
    ["Rank of an augmented matrix is equal to Rank of co-efficient matrix of system of equations", "Rank of an augmented matrix is not equal to Rank of co-efficient matrix of system of equations", "Rank of an augmented matrix is greater than Rank of a co-efficient matrix of the system of equations", "Rank of an augmented matrix is less than Rank of a co-efficient matrix of the system of equations"], 0,
    "Rouché–Capelli theorem."),
93: ("If z = x² + y² − axy, which of the following statements is true?",
    ["∂²z/∂x∂y = 0", "∂²z/∂x∂y = ∂²z/∂y∂x", "∂²z/∂x∂y = (∂z/∂x)(∂z/∂y)", "∂²z/∂x∂y = −∂²z/∂x∂y"], 1,
    "Both mixed partial derivatives equal −a."),
94: ("If a periodic non-zero function f(x) in (−π, π) is even, then the Euler's co-efficients\n(i) a₀ = 0 and aₙ = 0\n(ii) bₙ ≠ 0\n(iii) bₙ = 0\n(iv) a₀ = 0, aₙ = 0, bₙ = 0",
    ["(i) and (ii) correct but (iii) and (iv) incorrect", "(i), (ii) and (iii) correct but (iv) incorrect", "(i), (ii) and (iv) incorrect but (iii) correct", "(i), (ii) and (iv) correct but (iii) incorrect"], 2,
    "For an even function f(x) sin nx is odd, so every bₙ = 0; a₀ and aₙ are in general non-zero."),
95: ("In a vector point function F = f₁(x, y, z)i + f₂(x, y, z)j + f₃(x, y, z)k, if ∇·F = 0 and ∇ × F = 0, then\n(i) F is solenoidal and F is irrotational\n(ii) F is solenoidal but not irrotational\n(iii) F is irrotational but not solenoidal\n(iv) F is neither solenoidal nor irrotational",
    ["(i) correct but (ii), (iii), (iv) not correct", "(ii) correct but (i), (iii), (iv) not correct", "(iii) correct but (i), (ii), (iv) not correct", "(iv) correct but (i), (ii), (iii) not correct"], 0,
    "Zero divergence = solenoidal; zero curl = irrotational."),
96: ("If φ(x, y), Ψ(x, y), φ_y and Ψ_x are continuous in a region E of the xy plane bounded by a closed curve C, then by Green's theorem",
    ["∮_C (φ dx + Ψ dy) = ∬_E (∂Ψ/∂x − ∂φ/∂y) dx dy", "∮_C (φ dx + Ψ dy) = ∬_E (∂Ψ/∂x + ∂φ/∂y) dx dy", "∮_C (φ dx ± Ψ dy) = ∬_E (∂Ψ/∂x ± ∂φ/∂y) dx dy", "∮_C (φ dx − Ψ dy) = ∬_E (∂Ψ/∂x + ∂φ/∂y) dx dy"], 0,
    "Green's theorem in the plane: ∮(M dx + N dy) = ∬(∂N/∂x − ∂M/∂y) dx dy."),
97: ("The complete solution of a differential equation d⁴r/dθ⁴ = a⁴r is",
    ["r = C₁e^(aθ) + C₂e^(−aθ) + (C₃ + C₄θ)e^(aθ/2)", "r = C₁cos aθ + C₂sin aθ + C₃cosh aθ + C₄sinh aθ", "r = (C₁cos aθ + C₂sin aθ) + θ² + 1", "r = (C₁ + C₂θ)e^(−aθ) + (C₃ + C₄θ)e^(aθ)"], 1,
    "m⁴ = a⁴ gives m = ±a and ±ia: e^(±aθ) (cosh, sinh) and cos aθ, sin aθ."),
98: ("The order and degree of the differential equation (d³y/dx³)² + x²(dy/dx)³ − 2x + 11 = 0 is",
    ["Order – 2; degree – 3", "Order – 1; degree – 3", "Order – 3; degree – 2", "Order – 3; degree – 1"], 2,
    "The highest derivative is the third, raised to the power 2."),
99: ("A partial differential equation obtained by eliminating arbitrary constant from the function z = x/a + y/b is",
    ["z = y ∂z/∂x + x ∂z/∂y", "z = x ∂z/∂x − y ∂z/∂y", "z = x ∂z/∂x + y ∂z/∂y", "z = x² ∂²z/∂x² + y² ∂²z/∂y²"], 2,
    "p = 1/a and q = 1/b, so z = xp + yq."),
100: ("Which of the following partial differential equation represents a one dimensional wave equation?",
    ["∂u/∂t = c² ∂²u/∂x²", "(∂u/∂t)² = c² ∂²u/∂x²", "∂²u/∂t² = c² (∂u/∂x)²", "∂²u/∂t² = c² ∂²u/∂x²"], 3,
    "The wave equation is second order in time; option 1 is the heat equation."),
}


def sets():
    out = []
    for lo in (1, 26, 51, 76):
        qs = [(q, o, a, e + NOTE, SRC.format(n)) for n in sorted(Q) if lo <= n <= lo + 24 for q, o, a, e in [Q[n]]]
        out.append({"name": f"Q{lo}–{lo + 24}", "questions": qs, "keep_order": True})
    return out


TOPIC = "KEA 2026 – Computer Science Paper-2 (5 Jul 2026)"
