"""Previous-year paper · KSET 2025 (Eligibility Examination 2025) · Paper 2 · Computer Science & Applications · paper code CSA21125A · version A1.
Source: KEA question-paper archive, cetonline.karnataka.gov.in/keawebentry456/QP2025/K_SET_2025_05_07_26_COMP_SCIE_&_APL_13072026kannada.pdf
(scanned; transcribed from the page images – OCR confuses ii/iii in the matching lists). Options (1)–(4) are A–D in the printed order.
KEA's archive has only notices for the 2025 key, so every answer was worked out by ExamSim and is NOT the official key.
Skipped: Q66 (the answer depends on whether depth d counts from 0 or 1), Q99 (no standard source ranks selection 'noise')."""

SRC = "KSET 2025 CS&A · Q{}"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

Q = {
1: ("Given (¬P ∨ Q) ∧ (P ∨ Q), which of the following mathematical logics is considered as equivalent?",
    ["Q", "P ∧ Q", "P", "¬Q"], 0,
    "By resolution (or cases on P): if P is true the first clause forces Q, if P is false the second forces Q. So the formula ≡ Q."),
2: ("Match the following terms with their definitions:\na. Well-ordered Set\nb. Partial-ordered Set\nc. Totally-ordered Set\nd. Empty Set\n(i) A set where every pair of elements are comparable\n(ii) Every non-empty subset has a least element\n(iii) A set where every pair of elements not necessarily to be comparable\n(iv) A set with no elements",
    ["a – ii, b – iii, c – i, d – iv", "a – ii, b – i, c – iii, d – iv", "a – ii, b – iii, c – iv, d – i", "a – iv, b – iii, c – ii, d – i"], 0,
    "Well-ordered: every non-empty subset has a least element; poset: not all pairs comparable; total order: every pair comparable."),
3: ("Given U = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, Let A = {1, 2, 3, 4, 5}; B = {1, 2, 4, 8}; C = {1, 2, 3, 5, 7} and D = {2, 4, 6, 8}. Determine (A ∪ B) − (C ∩ D).",
    ["{1, 3, 5, 7, 9, 10}", "{1, 3, 4, 5, 6, 7, 8, 9, 10}", "{1, 2, 3, 4, 5, 8}", "{1, 3, 4, 5, 8}"], 3,
    "A ∪ B = {1, 2, 3, 4, 5, 8}; C ∩ D = {2}; removing 2 gives {1, 3, 4, 5, 8}."),
4: ("What is the probability of an odd sum when two dice are rolled?",
    ["12/36", "18/36", "24/36", "9/12"], 1,
    "The sum is odd when one die is odd and the other even: 2 × 3 × 3 = 18 of 36 outcomes."),
5: ("A party of n persons sit at a round table, find the odds against two specific individuals sitting next to each other.",
    ["(n − 3) : 2", "(n − 3) : 8", "(n + 3) : 4", "(n + 3) : 16"], 0,
    "P(adjacent) = 2/(n − 1), so the odds against are (n − 1 − 2) : 2 = (n − 3) : 2."),
6: ("Consider a connected, undirected graph G = (V, E) where |V| = n and |E| = m. Which of the following statements must be true for a spanning tree of G?\na. A spanning tree of G will always have exactly m − n + 1 edges\nb. Any subgraph of G with exactly n − 1 edges is guaranteed to be a spanning tree\nc. The number of spanning trees in G can be computed using Kirchhoff's matrix tree theorem\nd. A spanning tree of G is always unique for any given graph",
    ["(b) and (d) are correct", "only (c) is correct", "only (a) is correct", "(a) and (d) are correct"], 1,
    "A spanning tree has n − 1 edges (m − n + 1 is the number of edges left out); n − 1 edges may contain a cycle; spanning trees are generally not unique."),
7: ("Let G be a group defined by a * b = (ab/2); where the elements of G are nonzero real numbers. The solution of 3 * x = 4 is given by",
    ["8/3", "−4/5", "−3/8", "4/3"], 0,
    "3x/2 = 4 gives x = 8/3."),
8: ("For a given Boolean expression, F = X·Y·Z + X·Y·Z̅ + X·Y·Z + X̅·Y, the simplified Boolean expression is",
    ["X̅", "Y", "X̅ + Y", "X + Z̅"], 1,
    "XYZ + XYZ̅ = XY; XY + X̅Y = Y."),
9: ("Consider a weighted complete graph G on the vertex set {V₁, V₂, V₃, V₄, …, Vₙ} such that the weight of the edge (Vᵢ, Vⱼ) is 2|i − j|. The weight of minimum spanning tree of G is",
    ["n² − 1", "n²/2", "2n − 2", "n²"], 2,
    "The path V₁–V₂–…–Vₙ uses the n − 1 cheapest possible edges, each of weight 2: total 2n − 2."),
10: ("For given U = {1, 2, 3, 4, ….., 10}, Let A = {1, 2, 3, 4, 5}; B = {1, 2, 4, 8}; C = {1, 2, 3, 5, 7} and D = {2, 4, 6, 8}. Determine the following C̅ ∪ D̅.",
    ["{1, 3, 5, 7, 9, 10}", "{1, 3, 4, 5, 6, 7, 8, 9, 10}", "{1, 2, 3, 4, 5, 8}", "{1, 3, 4, 5, 8}"], 1,
    "De Morgan: C̅ ∪ D̅ = complement of (C ∩ D) = U − {2}."),
11: ("The decimal equivalent of the hexadecimal number F3E is",
    ["8530", "8544", "3902", "3888"], 2,
    "15 × 256 + 3 × 16 + 14 = 3840 + 48 + 14 = 3902."),
12: ("Match the following:\na. MAR\nb. MBR\nc. IR\nd. PC\n(i) Holds the address of the next instruction to fetch\n(ii) Holds the instruction for decoding\n(iii) Holds the address of instruction or data\n(iv) Holds the data",
    ["a – iii, b – iv, c – i, d – ii", "a – iv, b – iii, c – i, d – ii", "a – iii, b – iv, c – ii, d – i", "a – iv, b – iii, c – ii, d – i"], 2,
    "MAR holds a memory address, MBR the data, IR the current instruction and PC the address of the next instruction."),
13: ("\"Sequential portion of the program does not change with respect to machine size, however, the parallel portion is evenly executed by 'n' processors results in a reduced time\" is",
    ["Moore's Law", "Flynn's Law", "Banker's Law", "Amdahl's Law"], 3,
    "Amdahl's law: speed-up = 1 / (s + (1 − s)/n) for a fixed workload with sequential fraction s."),
14: ("The first machine cycle of an instruction is always a ____ cycle.",
    ["Memory read", "Fetch", "I/O read", "Memory write"], 1,
    "Every instruction starts with the opcode fetch cycle."),
15: ("If the operand is given explicitly in the instruction, the addressing mode is called",
    ["Immediate", "Absolute", "Direct", "Indirect"], 0,
    "In immediate mode the operand itself is part of the instruction."),
16: ("Consider cache with 128 blocks of 16 words, and main memory has 4096 blocks of 16 words, and assume 64 sets for the Set Associate Mapping. Match the addressing scheme for cache memory mapping:\na. Direct mapping\nb. Associate mapping\nc. Set associate mapping\n(i) 12 bit for tag and 4 bit for word\n(ii) 6 bit for tag, 6 bit for set and 4 bit for word\n(iii) 5 bit for tag, 7 bit for block and 4 bit for word",
    ["a → i, b → ii, c → iii", "a → iii, b → ii, c → i", "a → ii, b → iii, c → i", "a → iii, b → i, c → ii"], 3,
    "Address = 16 bits (4096 × 16 words), word = 4 bits. Direct: 7-bit block, 5-bit tag. Associative: 12-bit tag. 64 sets: 6-bit set, 6-bit tag."),
17: ("Match the following:\na. Temporal locality of reference\nb. Spatial locality of reference\nc. Sequential locality of reference\n(i) If an instruction is executed now, more likely the instruction will be executed in future\n(ii) Instructions are executed one after the other\n(iii) If a group of instructions referred now, more likely that group of instructions will be referred in future",
    ["a – i, b – iii, c – ii", "a – iii, b – i, c – ii", "a – ii, b – iii, c – i", "a – ii, b – i, c – iii"], 0,
    "Temporal: the same item again; spatial: nearby items; sequential: one after another."),
18: ("Match the following:\na. DRAM\nb. DMA\nc. Associative mapping\nd. Memory-mapped I/O\n(i) Offloads data transfer main memory to devices bypassing CPU\n(ii) Dynamic memory\n(iii) I/O devices treated as memory locations\n(iv) Flexible cache mapping by content",
    ["a – i, b – ii, c – iii, d – iv", "a – ii, b – i, c – iv, d – iii", "a – iii, b – iv, c – ii, d – i", "a – iv, b – iii, c – i, d – ii"], 1,
    "DRAM is dynamic memory, DMA bypasses the CPU, associative mapping places blocks anywhere, memory-mapped I/O uses memory addresses for devices."),
19: ("In the absence of data and control hazards, the k-unit instruction unit pipeline with n instructions has speed up",
    ["nk / (k + (n − 1))", "(k + (n − 1)) / nk", "nk / ((k − 1)*n)", "k + n / (nk)"], 0,
    "Non-pipelined time nk cycles; pipelined k + n − 1 cycles."),
20: ("Consider the following statements regarding the interconnection topology.\ni. In star topology, if the master node is dead, the other nodes (processor) can still interact with each other.\nii. In bus topology, only two processors can interact with each other at any one given point in time.\niii. In hyper cube topology, two nodes are connected if there is change in two bits in their processor identity (processor id)",
    ["(i) is true, (ii) and (iii) are false", "(i) and (ii) are true, (iii) is false", "(ii) is true, (i) and (iii) are false", "(i) and (iii) are true, (ii) is false"], 2,
    "In a star all traffic passes through the centre; a shared bus carries one transfer at a time; hypercube neighbours differ in exactly one bit."),
21: ("Match the following:\na. .wav\nb. .pdf\nc. .pcd\nd. .WMV\n(i) structured\n(ii) image\n(iii) video\n(iv) audio",
    ["a – iv, b – i, c – ii, d – iii", "a – iii, b – ii, c – i, d – iv", "a – iii, b – i, c – ii, d – iv", "a – ii, b – i, c – iv, d – iii"], 0,
    ".wav is audio, .pdf a structured document, .pcd (Kodak Photo CD) an image and .wmv Windows Media Video."),
22: ("What is the output of the following code snippet?\npublic class Test\n{\n  public int getData()   // getData() 1\n  { return 0; }\n  public long getData()  // getData() 2\n  { return 1; }\n  public static void main(String[] args)\n  {\n    Test t = new Test();\n    System.out.println(t.getData());\n  }\n}",
    ["1", "0", "Run time error", "Compilation error"], 3,
    "Java methods cannot be overloaded by return type alone: two getData() methods with the same parameter list do not compile."),
23: ("What is the role of linker in compilation?",
    ["Translates source code to object code", "Generates intermediate code", "Combines different compiled modules", "Performs code optimization"], 2,
    "The linker combines object modules and libraries into one executable, resolving external references."),
24: ("What will be the output of the following code snippet?\n#include <stdio.h>\nvoid solve()\n{\n  int x = 2;\n  printf(\"%d \", (x << 1) + (x >> 1));\n}\nint main()\n{\n  solve();\n  return 0;\n}",
    ["5", "4", "2", "1"], 0,
    "2 << 1 = 4 and 2 >> 1 = 1; 4 + 1 = 5."),
25: ("What is the output of the following program?\n#include <stdio.h>\nint main()\n{\n  struct emp\n  {\n    char name[20];\n    int age;\n    float sal;\n  };\n  struct emp e = {\"computer\", 0, 0};\n  printf(\"%d \\t %f \", e.age, e.sal);\n  return 0;\n}",
    ["Compiler error", "Computer, 0, 0.000000", "0 0.000000", "1 0.000000 computer"], 2,
    "Only age (0) and sal (0.000000) are printed, separated by a tab."),
26: ("What is the output of the following code?\n#include <stdio.h>\nunion u1\n{\n  int x;\n  char y;\n};\nunion u2\n{\n  int a[10];\n  char y1;\n};\nint main(){\n  printf(\"size of u1 = %ld/t\", sizeof(union u1));\n  printf(\"size of u2 = %ld\", sizeof(union u2));\n  return 0;\n}",
    ["2, 20", "4, 40", "2, 40", "4, 20"], 1,
    "A union is as large as its largest member: int (4 bytes) and int[10] (40 bytes), with 4-byte ints."),
27: ("A 16 × 16 array having only black and white pixels could be represented by ____",
    ["32 bytes", "64 bytes", "96 bytes", "128 bytes"], 0,
    "256 pixels × 1 bit = 256 bits = 32 bytes."),
28: ("Which of the following matrix represents a 2D rotation by an angle θ?",
    ["[cos θ  −sin θ; sin θ  cos θ]", "[1  0; 0  1]", "[cos θ  sin θ; −sin θ  cos θ]", "[sin θ  cos θ; cos θ  −sin θ]"], 0,
    "Counter-clockwise rotation: x′ = x cos θ − y sin θ, y′ = x sin θ + y cos θ. (Option 3 rotates by −θ.)"),
29: ("How much memory is required to implement a z-buffer for a 512 × 512 image with 24-bit depth?",
    ["1 MB", "1.5 MB", "500 KB", "768 KB"], 3,
    "512 × 512 × 3 bytes = 786,432 bytes = 768 KB."),
30: ("Given 3D-triangle with co-ordinate points A(3, 4, 1), B(6, 4, 2) and C(5, 6, 3). Apply the reflection on the XY plane and find out new co-ordinates of the object.",
    ["A(3, 4, −1), B(6, 4, −2) and C(5, 6, −3)", "A(3, −4, 1), B(6, −4, 2) and C(5, −6, 3)", "A(−3, 4, 1), B(−6, 4, 2) and C(−5, 6, 3)", "A(3, 4, 1), B(6, 4, −2) and C(−5, 6, 3)"], 0,
    "Reflection in the XY plane negates z."),
31: ("Identify the correctness of the following statements?\ni. Logical data independence is the ability to modify the logical schema without transforming the application programs\nii. Logical data independence modifies the logical schema as well as the application programs\niii. Logical data independence is complicated to achieve than the physical data independence",
    ["(i) and (ii) are correct and (iii) is incorrect", "(i) and (iii) are incorrect and (ii) is correct", "(i) and (iii) are correct and (ii) is incorrect", "(i) and (ii) are incorrect and (iii) is correct"], 2,
    "Logical independence means applications need not change; it is harder to achieve than physical independence."),
32: ("Identify the correctness of the following statements:\ni. The project operation is a unary operation which extracts attributes from a relation\nii. The project operation allows us to locate tuples that are in one relation but not in another relation\niii. The project operation connects the data across the relations",
    ["(i) and (ii) are incorrect and (iii) is correct", "(i) and (ii) are correct and (iii) is incorrect", "(i) is correct and (ii) and (iii) are incorrect", "(i) is incorrect and (ii) and (iii) are correct"], 2,
    "(ii) describes set difference and (iii) describes join."),
33: ("Consider the following statements:\ni. Stored procedures can be used to process multiple databases\nii. Extended stored procedures are compiled as dynamic link library files\niii. Local stored procedures are stored on user-built databases\nChoose the correct statement from the options given below:",
    ["(i), (ii) and (iii) are incorrect", "(i) is correct, (ii) and (iii) are incorrect", "(i) is incorrect, (ii) and (iii) are correct", "(i), (ii) and (iii) are correct"], 3,
    "All three hold, e.g. in SQL Server: procedures can reference several databases, extended procedures are DLLs, and local procedures live in user databases."),
34: ("____ eliminates relations between candidate keys.",
    ["First Normal Form", "Second Normal Form", "Third Normal Form", "Boyce-Codd Normal Form"], 3,
    "BCNF removes the anomalies 3NF allows when candidate keys overlap: every determinant must be a candidate key."),
35: ("In ____, whenever a new update is made, multiple versions of the data items are produced.",
    ["Normalization", "Write Ahead Logging", "Shadow Paging", "Serializability"], 2,
    "Shadow paging writes updates to new page copies while the shadow (old) version is kept until commit."),
36: ("Match the following:\na. BCNF iff\nb. 5 NF iff\nc. 1 NF iff\nd. 4 NF iff\n(i) every JD is implied by the candidate keys\n(ii) every MVD is implied by the candidate keys\n(iii) all underlying domains contain scalar values only\n(iv) every FD is implied by the candidate keys",
    ["a – iii, b – ii, c – i, d – iv", "a – iv, b – i, c – ii, d – iii", "a – iv, b – i, c – iii, d – ii", "a – iv, b – iii, c – ii, d – i"], 2,
    "BCNF: FDs; 4NF: MVDs; 5NF: JDs; 1NF: atomic domains."),
37: ("Match the following:\na. Data warehouse\nb. Data mining\nc. OLAP\nd. Aggregation\n(i) which allows users to analyse data from multiple database systems at once\n(ii) is the summarization of fact related data\n(iii) central repository of information that can be analyzed to make more informed decisions\n(iv) is a process used to discover patterns and relationships in datasets",
    ["a – ii, b – iii, c – iv, d – i", "a – iii, b – iv, c – i, d – ii", "a – iii, b – iv, c – ii, d – i", "a – iii, b – ii, c – iv, d – i"], 1,
    "Warehouse = central repository; mining = pattern discovery; OLAP = multi-dimensional analysis; aggregation = summarisation."),
38: ("Which of the following refers to the problem of finding abstracted patterns (structures) in the unlabelled data?",
    ["Supervised learning", "Unsupervised learning", "Hybrid learning", "Reinforcement learning"], 1,
    "Unsupervised learning finds structure in data without labels."),
39: ("Match the following relation R and S:\na. Theta Join\nb. Equi Join\nc. Left outer Join\nd. Right outer Join\n(i) If no matching tuples found in S, then the attributes of S are filled with NULL\n(ii) If no matching tuples found in R, then the attributes of R are filled with NULL\n(iii) Combinations of tuples of R and S that satisfies join condition\n(iv) Combinations of tuples of R and S that satisfies equality comparisons",
    ["a – iv, b – iii, c – i, d – ii", "a – iv, b – iii, c – ii, d – i", "a – iii, b – iv, c – i, d – ii", "a – iii, b – iv, c – ii, d – i"], 2,
    "Theta join: any condition; equi join: equality only; R ⟕ S pads S's attributes; R ⟖ S pads R's."),
40: ("Given the following entries of a table State_tb:\nState_id | Region | Population\nUP | N | 28\nMP | N | 08\nKAR | S | 06\nTN | S | 07\nthe SQL statement\nSELECT Sum(Population)\nFROM State_tb\nGROUP BY Region;",
    ["is syntactically wrong", "gives total sum of population of all the regions", "gives sum of population of S and N separately", "gives population of each state"], 2,
    "GROUP BY Region returns one sum per region: N = 36, S = 13."),
41: ("In the process of macro expansion given:\nS₁: lexical substitution implies replacement of a character string by another string during program generation\nS₂: lexical substitution is employed to replace occurrences of formal parameters by some random values\nWhich of the following holds good?",
    ["Both S₁ and S₂ are true", "Both S₁ and S₂ are false", "S₁ is false and S₂ is true", "S₁ is true and S₂ is false"], 3,
    "Formal parameters are replaced by the actual parameters of the call, not by random values (Dhamdhere)."),
42: ("Consider a single processor system with four processes A, B, C and D represented as given below, where for each process the first value is its arrival time and second value is its CPU burst time\nA(0, 10), B(2, 6), C(4, 3) and D(6, 7)\nWhich of the following options gives the average waiting time when preemptive Shortest Remaining Time First (SRTF) and the Non-Preemptive Shortest Job First (NP-SJF) CPU scheduling algorithms are applied to the process?",
    ["SRTF = 6  NP-SJF = 7", "SRTF = 6  NP-SJF = 7.5", "SRTF = 7  NP-SJF = 7.5", "SRTF = 7  NP-SJF = 8.5"], 1,
    "SRTF: A 0–2, B 2–4, C 4–7, B 7–11, D 11–18, A 18–26 → waits 16, 3, 0, 5 → 6. NP-SJF: A 0–10, C 10–13, B 13–19, D 19–26 → waits 0, 11, 6, 13 → 7.5."),
43: ("Match the following:\na. Critical region\nb. Wait signal\nc. Working set\nd. Deadlock\n(i) Hoare's monitor\n(ii) Mutual exclusion\n(iii) Principle of locality\n(iv) Circular wait",
    ["a – iv, b – i, c – iii, d – ii", "a – ii, b – i, c – iii, d – iv", "a – i, b – ii, c – iii, d – iv", "a – iv, b – iii, c – i, d – ii"], 1,
    "Critical regions need mutual exclusion; wait/signal are Hoare-monitor operations; the working set rests on locality; deadlock needs circular wait."),
44: ("In a system using paging with Translation Lookaside Buffer (TLB), what will be the Effective Memory Access Time (EMAT), if the memory access time is 100 ns, TLB access time is 20 ns, and the TLB hit ratio is 80%?\nAssume TLB hit requires one memory access and TLB miss requires two.",
    ["120 ns", "140 ns", "160 ns", "180 ns"], 1,
    "0.8 × (20 + 100) + 0.2 × (20 + 200) = 96 + 44 = 140 ns."),
45: ("Match the following with respect to various memory management:\na. Demand paging\nb. Segmentation\nc. Dynamic partitions\nd. Fixed partitions\n(i) Degree of multiprogramming\n(ii) Working set\n(iii) Supports user view of memory\n(iv) Compaction",
    ["a – ii, b – iv, c – iii, d – i", "a – ii, b – iii, c – i, d – iv", "a – iv, b – iii, c – ii, d – i", "a – ii, b – iii, c – iv, d – i"], 3,
    "Demand paging uses working sets; segmentation matches the user's view; dynamic partitions need compaction; fixed partitions fix the degree of multiprogramming."),
46: ("Which of the following is not correct about the virtual memory management?",
    ["It is not necessary to load all of the segments of a process", "It has no internal fragmentation", "It has large virtual address space", "It provides lower degree of multiprogramming"], 3,
    "Virtual memory raises the degree of multiprogramming, since only part of each process need be in memory. (Option 2 holds for segmented virtual memory, which the question refers to.)"),
47: ("Match the following:\ni. Kernel\nii. Belady's anomaly\niii. Paging\niv. Free-space management\n(a) Ensures efficient storage utilization\n(b) Avoids external fragmentation\n(c) Provides basic low-level operations\n(d) Increase in the number of page frames leads to increase in the number of page faults",
    ["i – d, ii – c, iii – b, iv – a", "i – b, ii – d, iii – a, iv – c", "i – c, ii – d, iii – b, iv – a", "i – b, ii – a, iii – d, iv – c"], 2,
    "Kernel = low-level services; Belady = more frames, more faults (FIFO); paging avoids external fragmentation; free-space management uses storage well."),
48: ("Match the following:\ni. Context switching\nii. Semaphores\niii. Process synchronization\niv. Message passing\n(a) process communicate by sending and receiving messages\n(b) co-ordination of the execution of multiple processes sharing the resources\n(c) enables multiple processes to share a single CPU\n(d) helps to prevent race condition",
    ["i – a, ii – b, iii – c, iv – d", "i – b, ii – c, iii – d, iv – a", "i – c, ii – d, iii – b, iv – a", "i – c, ii – d, iii – a, iv – b"], 2,
    "Context switching shares the CPU; semaphores prevent races; synchronisation coordinates; message passing communicates."),
49: ("Which of the following disk scheduling algorithms may result in starvation?",
    ["SCAN", "LOOK", "SSTF", "C-SCAN"], 2,
    "SSTF keeps serving nearby requests, so far-away requests can wait indefinitely."),
50: ("Match the following:\ni. User authentication\nii. Firewalls\niii. Access control\niv. Encryption\n(a) controls incoming and outgoing traffic in a network\n(b) converts readable information into an unreadable format\n(c) process of verifying the identity of a user attempting to gain access to a computer network\n(d) authorizing the users to access the resources in a computer network",
    ["i – b, ii – c, iii – d, iv – a", "i – c, ii – a, iii – d, iv – b", "i – d, ii – a, iii – b, iv – c", "i – c, ii – d, iii – a, iv – b"], 1,
    "Authentication verifies identity, firewalls filter traffic, access control authorises, encryption makes data unreadable."),
51: ("Arrange the component-based development process activities in the correct order:\na. Requirement analysis\nb. Component qualification\nc. System design with reuse\nd. Component adaptation\ne. Component composition\nf. Component discovery\ng. System integration and testing",
    ["f, a, b, c, d, g, e", "a, c, f, b, d, e, g", "b, a, f, c, d, e, g", "a, f, c, b, d, g, e"], 1,
    "Requirements first, then architectural design with reuse, then find, qualify, adapt and compose components, and finally integrate and test."),
52: ("In a spiral model cycle, the probability of failure for each iteration due to risk is 10%. If there are 4 cycles, then what is the probability that the project completes all cycles without failure?",
    ["0.6561", "0.9", "0.3439", "0.9999"], 0,
    "0.9⁴ = 0.6561."),
53: ("Match the Agile practices with their corresponding principles or benefits:\na. Pair Programming\nb. Test-driven Development\nc. Continuous Integration\nd. Refactoring\n(i) Avoids integration issues by validating changes frequently in shared repositories.\n(ii) Ensures correctness through automated specification before implementation.\n(iii) Facilitates early problem discovery and real-time code review.\n(iv) Improves internal code quality without altering external behaviour",
    ["a → i, b → ii, c → iii, d → iv", "a → ii, b → iii, c → iv, d → i", "a → iv, b → i, c → ii, d → iii", "a → iii, b → ii, c → i, d → iv"], 3,
    "Pair programming = continuous review; TDD = tests first; CI = frequent integration; refactoring = better structure, same behaviour."),
54: ("Assertion (A): High cohesion within a module and low coupling between modules result in increased maintainability and reusability of a software system.\nReason (R): High cohesion implies that each module performs multiple unrelated tasks, increasing its independence from other modules.",
    ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], 2,
    "High cohesion means a module does one closely related job; R describes low (coincidental) cohesion."),
55: ("In basic path testing, the number of independent paths through the code is computed using cyclomatic complexity. Which of the following statements is correct regarding cyclomatic complexity?",
    ["Cyclomatic complexity = number of nodes − number of edges + 1.", "Cyclomatic complexity provides an upper bound on the number of required performance tests.", "Cyclomatic complexity helps in identifying infeasible test cases for black-box testing.", "Cyclomatic complexity = E − N + 2P, where P is the number of connected components in the control flow graph."], 3,
    "V(G) = E − N + 2P; it bounds the number of basis-path tests, a white-box measure."),
56: ("Assertion (A): White-box testing is essential for detecting logic errors that may not be exposed through black-box testing, especially in safety-critical systems such as avionics or medical devices.\nReason (R): White-box testing allows analysis of control structures including decision points, loops and internal data flow, ensuring thorough coverage of execution paths.",
    ["Both A and R are true, and R is the correct explanation of A", "Both A and R are true, but R is not the correct explanation of A", "A is true, but R is false", "A is false, but R is true"], 0,
    "Because white-box tests exercise the internal logic, they can reveal errors that input/output tests miss."),
57: ("Which of the following best describes the purpose of a Time-Line (Gantt) chart in project scheduling?",
    ["To define critical paths and slack times between tasks", "To graphically represent task dependencies with nodes and arrows", "To display resource availability across overlapping activities", "To map task durations along a horizontal time scale for visual tracking"], 3,
    "A Gantt chart shows tasks as bars against a time axis; networks (PERT/CPM) show dependencies and critical paths."),
58: ("Which of the following best captures the distinction between change control and version control in software configuration management?",
    ["Change control handles concurrent file updates, version control manages customer requirement changes.", "Change control deals with evaluating and approving changes, version control maintains the history and integrity of source artifacts.", "Change control is applied only during testing, version control is applied during development.", "Change control eliminates the needs, version control is applied in agile environments."], 1,
    "Change control decides which changes are made; version control records and manages the versions."),
59: ("In object-oriented design, what is the primary purpose of information hiding?",
    ["Increase execution speed by avoiding modularization.", "Prevent subclassing and inheritance.", "Limit the exposure of internal module details to reduce system complexity and error propagation.", "Allow direct modification of all class members by other objects."], 2,
    "Parnas: hide design decisions behind interfaces so that changes and errors stay local."),
60: ("Assume a software team applies COCOMO II Early Design Model. If the system is later migrated to a cloud-native microservices architecture, then which cost driver becomes the most volatile and error-prone in recalculating effort?",
    ["Product Complexity", "Platform Volatility", "Required Software Reliability", "Database Size"], 1,
    "Changing the underlying platform is what platform volatility measures. (Strictly, PVOL belongs to the Post-Architecture model; this is the intended answer.)"),
61: ("Assume the following priorities in evaluating an expression (1) parenthesis (2) exponentiation (3) division and multiplication (4) addition and subtraction (5) assignment. What is the equivalent post-fix expression of the infix expression a = b/c ^ d * (e + f) − g/h.",
    ["a b c d ↑ e f / + g h − * / =", "a b c d ↑ / e f + * g h / − =", "a b c d ↑ e f / * + g h / − =", "a b c d ↑ e f / + * g h − / ="], 1,
    "c ^ d first, then b/(c^d), times (e + f), minus g/h, then assign: a b c d ↑ / e f + * g h / − =."),
62: ("Which one among the following are true about circular queue with queue capacity being n (numbered from 0 to n − 1), 'f' and 'r' being front and rear pointers to the first, and the last elements?\na. The Queue is full if (r + 1) mod n == f.\nb. The maximum number of elements that can be stored in a Queue is n − 1\nc. This is an efficient algorithm compared to linear Queue\nd. This is a non-linear data structure.",
    ["a, b and d", "b, c and d", "a, b and c", "a and b"], 2,
    "With one slot left empty to tell full from empty, (r + 1) mod n == f means full and n − 1 elements fit; a queue is a linear structure."),
63: ("Which one of the following are true about Huffman Algorithm?\na. It is Dynamic Programming Algorithm\nb. It is a Greedy Algorithm\nc. Used for text compression\nd. Used for image compression",
    ["a and c only", "b and c only", "a and d only", "b and d only"], 1,
    "Huffman coding greedily merges the two least frequent symbols; it is the textbook text-compression method."),
64: ("The cost of the Minimum spanning tree using Prim's Algorithm for the following graph is\n(edges: 1–2 = 2, 1–3 = 3, 2–3 = 2, 2–4 = 2, 3–4 = 3, 3–5 = 4, 4–5 = 1, 4–6 = 3, 5–6 = 4)",
    ["10", "11", "12", "17"], 0,
    "MST edges: 4–5 (1), 1–2 (2), 2–3 (2), 2–4 (2), 4–6 (3) → 10. (Edge weights read from the figure in the paper.)"),
65: ("Given the inorder of a tree as e, b, f, c, g, h, d and pre-order of the tree as c, b, e, f, d, g, h, the post-order of the tree is",
    ["e, f, b, h, c, g, d", "e, f, b, h, d, g, c", "f, e, b, h, g, d, c", "e, f, b, h, g, d, c"], 3,
    "Root c; left subtree b(e, f); right subtree d with left child g, which has right child h. Post-order: e f b h g d c."),
67: ("The complexity of brute force algorithm to find all the substrings in a given string of 'm' characters and a substring of length 'n' (where m >> n) is",
    ["O(mn)", "O(m)", "O(n)", "O(mn²)"], 0,
    "Try each of about m starting positions and compare up to n characters: O(mn)."),
68: ("A model which uses the previously computed values for further computation is called",
    ["Greedy Algorithm", "Backtracking", "Branch and Bound", "Dynamic Programming"], 3,
    "Dynamic programming stores and reuses the results of subproblems."),
69: ("Match the following:\na. Prim's algorithm\nb. Queen's problem\nc. Quick sort\nd. Binomial coefficient\n(i) Dynamic Programming\n(ii) Divide and conquer\n(iii) Greedy Algorithm\n(iv) Backtracking",
    ["a – iii, b – iv, c – ii, d – i", "a – iii, b – iv, c – i, d – ii", "a – iii, b – ii, c – i, d – iv", "a – iv, b – ii, c – i, d – iii"], 0,
    "Prim = greedy, N-Queens = backtracking, quick sort = divide and conquer, binomial coefficients = DP (Pascal's triangle)."),
70: ("In a multiprocessor environment, assume that there are n = 8 elements, and the number of processors given N = 4. If we use the Binary tree model to find the greatest of 'n' elements using parallel processing, then the time taken to find the greatest of 'n' elements is ____ (Assume the communication cost to be 0)",
    ["O(log₂ n)", "O(log₂ N)", "O(N log₂ n)", "O(n log₂ N)"], 0,
    "With n/2 processors the tournament tree has log₂ n = 3 levels of parallel comparisons."),
71: ("Select the invalid paradox type from the following:",
    ["Falsidical", "Veridical", "Antinomy", "Opposidical"], 3,
    "Quine's classification: veridical, falsidical and antinomies; 'opposidical' is not a paradox type."),
72: ("If the languages L and ~L are recursive enumerable, then L is",
    ["Regular", "Context-free", "Context-sensitive", "Recursive"], 3,
    "Run the recognisers for L and its complement in parallel; one of them halts, so L is decidable (recursive)."),
73: ("A grammar is called ambiguous if",
    ["Two or more productions have the same non-terminal on the left-hand side.", "A derivation has more than one associated sentence", "A sentence having more than one derivation", "Productions having mostly terminal symbols"], 2,
    "Precisely: some sentence has more than one parse tree (more than one leftmost derivation)."),
74: ("A context-sensitive language is accepted by",
    ["Finite automata", "Linear-bounded automata", "NFA", "DFA"], 1,
    "Context-sensitive languages are exactly those accepted by linear-bounded automata."),
75: ("Problems that can be solved in polynomial time are called",
    ["Tractable Problems", "Intractable Problems", "Decidable Problems", "Undecidable Problems"], 0,
    "Polynomial-time solvable problems are considered tractable."),
76: ("The time complexity of constructing an LR parser is ____, given |n| is the size of the grammar.",
    ["O(n)", "O(n log n)", "O(2^|n|)", "O(n²)"], 2,
    "The number of LR item sets (parser states) can grow exponentially with the grammar size."),
77: ("The grammar S → XYZ with rules\nY.val = X.val\nY.val = S.val\nY.val = Z.val is",
    ["S-attributed Grammar", "L-attributed Grammar", "Neither S-attributed nor L-attributed Grammar", "Both S-attributed and L-attributed Grammar"], 2,
    "Y's attribute is inherited (so not S-attributed) and one rule uses Z, a sibling to Y's right (so not L-attributed)."),
78: ("Pick the right sequence of abstract machines according to their increasing order of the power.",
    ["FA → DPDA → NDPDA → TM", "FA → NDPDA → DPDA → TM", "FA → DPDA → TM → NDPDA", "TM → DPDA → NDPDA → FA"], 0,
    "Finite automata < deterministic PDA < nondeterministic PDA < Turing machine."),
79: ("A symbol table in assembler contains",
    ["Mapping of variables and their memory addresses", "Program code and data", "Input and output instructions", "Machine instructions and opcodes."], 0,
    "The symbol table maps labels and symbols to addresses; opcodes are in the machine-opcode table."),
80: ("Which of the following is not a common type of data flow analysis performed by compilers?",
    ["Constant propagation", "Dead code elimination", "Live variable analysis", "Type checking"], 3,
    "Type checking is semantic analysis on the syntax tree, not a data-flow analysis."),
81: ("A system transmits data at 1200 bytes per second using 4 bits per signal limit. What is the baud rate?",
    ["2400 Baud", "9600 Baud", "38400 Baud", "4800 Baud"], 0,
    "1200 × 8 = 9600 bps; 9600 / 4 bits per signal = 2400 baud."),
82: ("____ is a digital modulation technique where the amplitude of a carrier wave is varied in accordance with the digital data being transferred, while frequency and phase remain constant.",
    ["Amplitude shift keying", "Phase shift keying", "Frequency shift keying", "Quadrature amplitude modulation"], 0,
    "ASK varies only the amplitude."),
83: ("The bandwidth of a noisy channel is 3000 Hz and whose signal to noise ratio is 3162. What will be the maximum data rate of the channel?",
    ["≅ 37524 bps", "≅ 36523 bps", "≅ 35922 bps", "≅ 34890 bps"], 3,
    "Shannon: C = 3000 × log₂(1 + 3162) ≈ 3000 × 11.63 ≈ 34,880 bps."),
84: ("A transmission uses CRC for error detection, the message is 1101011011 and the generator polynomial is G(x) = x⁴ + x + 1. What will be appended at the end of the message?",
    ["1111", "1110", "1101", "1100"], 1,
    "Divide 1101011011 0000 by 10011 (mod 2): the remainder is 1110 (Tanenbaum's example)."),
85: ("In a mesh topology with 100 devices, the number of physical connections required is ____.",
    ["9900", "4950", "200", "9801"], 1,
    "n(n − 1)/2 = 100 × 99 / 2 = 4950."),
86: ("If a file is encrypted and then transmitted over a network using TCP/IP, then which layer handles the encryption and which handles retransmission if the file is lost?",
    ["Application layer - Transport layer", "Presentation layer - Data link layer", "Session layer - Network layer", "Transport layer - Application layer"], 0,
    "TCP/IP has no presentation layer, so encryption is done at the application layer; TCP (transport) retransmits lost segments."),
87: ("Match the following:\ni. 0.0.0.0\nii. 127.255.255.255\niii. 192.0.2.0/24\niv. 224.0.0.1\n(a) Documentation/examples (RFC 5737)\n(b) Multicast address for all hosts on a subnet\n(c) Unknown or default route address\n(d) Local host loopback testing",
    ["i – c, ii – d, iii – a, iv – b", "i – d, ii – a, iii – b, iv – c", "i – b, ii – c, iii – a, iv – d", "i – b, ii – a, iii – d, iv – c"], 0,
    "0.0.0.0 = default/unknown, 127.x.x.x = loopback, 192.0.2.0/24 = TEST-NET-1, 224.0.0.1 = all-hosts multicast."),
88: ("In a columnar transposition cipher, the key is \"LARGE\". What will be the cipher text for the plain text \"COMPUTERSCIENCE\" (without space) using a simple columnar transposition?",
    ["CTIOEEMRNPSCUCE", "MRNCTIPSCUCEOEE", "OEEUCEPSCCTIMRN", "CETMPOIRECUSENC"], 2,
    "Rows COMPU / TERSC / IENCE under L A R G E; read columns in key order A, E, G, L, R: OEE UCE PSC CTI MRN."),
89: ("In the RSA algorithm, let N = P × Q = 33, and let the decryption key D = 7. If the ciphertext corresponds to the letter \"E\", determine the original plaintext letter.\n(Assume A = 1, B = 2, ……, Z = 26).",
    ["S", "U", "N", "E"], 2,
    "M = 5⁷ mod 33: 5² = 25, 5⁴ ≡ 31, 5⁷ ≡ 31 × 25 × 5 = 3875 ≡ 14 → N."),
90: ("Five channels, each with a 100 kHz bandwidth are to be multiplexed together. What is the minimum bandwidth of the link if there is a need for a guard band of 10 kHz between the channels to prevent interference?",
    ["500 kHz", "540 kHz", "550 kHz", "100 kHz"], 1,
    "5 × 100 + 4 guard bands × 10 = 540 kHz."),
91: ("Determine which machine (M) passes the 'Turing Test', if it is subjected to 'imitation game'; conducted in 'Controlled Environment'.",
    ["M performs calculations quickly", "M generates random responses", "M identifies emotional intelligence", "M engages in conversation without identified as non-human"], 3,
    "A machine passes if the interrogator cannot tell it from a human in conversation."),
92: ("Match the following 'Heuristic Search' with respect to \"Hill climbing\" Algorithm:\na. Steepest Ascent Hill Climbing\nb. Hill Climbing Algorithm\nc. Plateau\nd. Ridge\n(i) Variant of \"Generate and Test algorithm\"\n(ii) Gradient search\n(iii) Area higher than surrounding\n(iv) Flat area of the search space",
    ["a – ii, b – i, c – iv, d – iii", "a – i, b – iv, c – iii, d – ii", "a – i, b – ii, c – iii, d – iv", "a – iv, b – iii, c – ii, d – i"], 0,
    "Rich & Knight: hill climbing is a variant of generate-and-test; steepest ascent is gradient search; a plateau is flat; a ridge is higher than its surroundings."),
93: ("Relate the AI methodologies of knowledge representation in right match.\na. NLP\nb. Representation in structured network\nc. Classes in ontology\nd. Expert system\n(i) Inference engine\n(ii) Abstract categories of related topics/concepts\n(iii) Semantic network\n(iv) Semantic analysis",
    ["a – iv, b – iii, c – ii, d – i", "a – iv, b – ii, c – iii, d – i", "a – iii, b – iv, c – ii, d – i", "a – i, b – ii, c – iii, d – iv"], 0,
    "NLP uses semantic analysis; a structured network is a semantic network; ontology classes are abstract categories; expert systems have inference engines."),
94: ("If f(x) = x is my friend, and P(x) = x is perfect, then the correct logical translation of the statement \"Some of my friends are not perfect\" is ____.",
    ["∀x (f(x) ∧ ¬P(x))", "∃x (f(x) ∧ ¬P(x))", "¬(f(x) ∧ ¬P(x))", "∃x (¬f(x) ∧ ¬P(x))"], 1,
    "'Some' is ∃ with ∧: there is someone who is my friend and not perfect."),
95: ("Match the following List-I with List-II:\na. Fuzzy system\nb. Expert system\nc. Genetic algorithm operator\nd. Supervised technique\n(i) Decision tree\n(ii) Inversion\n(iii) Inference engine\n(iv) Dendral",
    ["a – iv, b – i, c – iii, d – ii", "a – i, b – iv, c – ii, d – iii", "a – iii, b – iv, c – ii, d – i", "a – ii, b – iii, c – i, d – iv"], 2,
    "Dendral is a classic expert system, inversion is a GA operator, decision trees are supervised; fuzzy systems use a (fuzzy) inference engine."),
96: ("Given two Fuzzy sets A and B with membership function μA(x) = {0.6, 0.5, 0.1, 0.7, 0.8}, μB(x) = {0.9, 0.2, 0.6, 0.8, 0.5}. Now calculate the value of μ(A ∪ B)′(x).",
    ["{0.1, 0.5, 0.4, 0.2, 0.3}", "{0.1, 0.5, 0.4, 0.2, 0.2}", "{0.1, 0.5, 0.4, 0.3, 0.2}", "{0.1, 0.5, 0.4, 0.3, 0.3}"], 1,
    "Union = max = {0.9, 0.5, 0.6, 0.8, 0.8}; complement = 1 − μ = {0.1, 0.5, 0.4, 0.2, 0.2}."),
97: ("Let the population of chromosomes in Genetic Algorithm is represented in terms of binary number. The strength of fitness of a chromosome in decimal form, x, is given by Sf(x) = f(x) / Σf(x) where f(x) = x².\nThe population is P = {(01101), (11000), (01000), (10011)}.\nCalculate the strength of fitness of chromosome (11000).",
    ["49.2%", "576.8%", "15.10%", "14.4%"], 0,
    "x = 13, 24, 8, 19 → f = 169, 576, 64, 361, total 1170; 576 / 1170 ≈ 49.2%."),
98: ("Given a \"feed forward\" ANN with 'n' inputs, 'h' hidden units and 'm' outputs. Compute how many trainable parameters (weights) are present in ANN, assuming there are no biases.",
    ["n + m × h", "n + h + m", "(n × h) + (h × m)", "n × h × m"], 2,
    "Input→hidden has n × h weights and hidden→output h × m."),
100: ("The back propagation algorithm calculates the gradient of the 'Loss function' with respect to each weight in the network by which of the following mathematical techniques?",
    ["Lagrange multiplier", "Gradient descent", "K means algorithm", "Chain rule of calculus"], 3,
    "Backpropagation applies the chain rule layer by layer; gradient descent then uses those gradients."),
}


def sets():
    out = []
    for lo in (1, 26, 51, 76):
        qs = [(q, o, a, e + NOTE, SRC.format(n)) for n in sorted(Q) if lo <= n <= lo + 24 for q, o, a, e in [Q[n]]]
        out.append({"name": f"Q{lo}–{lo + 24}", "questions": qs, "keep_order": True})
    return out


TOPIC = "KSET 2025 – Computer Science & Applications"
