"""Previous-year paper · KSET 2024 (24 Nov 2024) · Paper 2 · Computer Science & Application · version A1.
Source: KEA question-paper archive, cetonline.karnataka.gov.in/keawebentry456/QP2024/COMPUTER_SCIENCE_&_APPLICATIONkannada.pdf
(scanned; transcribed by hand from the page images). Options (1)–(4) of the paper are A–D here, in the printed order.
KEA's archive has no full key for this paper, so every answer was worked out by ExamSim and is NOT the official key.
Skipped (no option is clearly correct or the question is under-specified): Q10, Q11, Q19, Q37, Q41, Q45, Q76, Q80, Q93, Q96."""

SRC = "KSET 2024 CS&A · Q{}"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"

Q = {
1: ("Which one of the following logical equivalences involve biconditional statements?",
    ["p → q ≡ ¬p ∨ q", "p ∨ q ≡ ¬p → q", "(p → q) ∧ (p → r) ≡ p → (q ∧ r)", "¬(p ↔ q) ≡ p ↔ ¬q"], 3,
    "Only option 4 uses the biconditional ↔; the others use implication, disjunction and conjunction."),
2: ("From the following arguments, determine whether they are correct or incorrect.\n(i) Ice cream is delicious to eat. Rahul's dessert is not ice cream. Therefore, Rahul's dessert is not delicious to eat.\n(ii) All registered voters are eligible to participate in elections. Ranjith is not eligible to participate in elections. Therefore, Ranjith is not a registered voter.",
    ["Both (i) and (ii) are correct", "(i) is incorrect and (ii) is correct", "(i) is correct and (ii) is incorrect", "Both (i) and (ii) are incorrect"], 1,
    "(i) commits the fallacy of denying the antecedent; (ii) is valid by modus tollens (P → Q, ¬Q ⊢ ¬P)."),
3: ("Relation R is defined on set A = {a, b, c, d, e}, where R = {(a,d), (b,c), (c,a), (d,e)}. Determine if R forms a tree. If it does, find the root.",
    ["R is not a tree", "R is a tree with root a", "R is a tree with root b", "R is a tree with root d"], 2,
    "The edges form the path b → c → a → d → e: connected, acyclic, and b is the only vertex with in-degree 0, so b is the root."),
4: ("Which one of the following expressions is in canonical SoP form considering A, B, C as Boolean variables?",
    ["A + B", "A·B̅·C + A·B·C̅", "A + C", "A·B + C"], 1,
    "In canonical sum-of-products form every product term (minterm) contains all the variables, complemented or not."),
5: ("The chances of a defective material in three boxes x, y and z are 1/5, 1/6 and 1/7 respectively. A box is selected at random and the material drawn is found to be defective. Find the probability that it came from box A.",
    ["40/107", "41/107", "42/107", "43/107"], 2,
    "The paper says 'box A' for the first box, x. Bayes: (1/3·1/5) / (1/3·(1/5 + 1/6 + 1/7)) = (42/210) / (107/210) = 42/107."),
6: ("Match the following terms related to the given Pigeonhole principle scenario and choose the correct answer.\na) Pigeonhole principle\nb) Contradiction\nc) Assigned Pigeons\nd) Overcrowded hole\ni. States that when m < n, not all pigeons can be assigned\nii. More than one pigeon assigned to the same pigeonhole\niii. Each pigeonhole contains at most one pigeon\niv. The assumption that all pigeons are assigned",
    ["a – i, b – iv, c – iii, d – ii", "a – ii, b – i, c – iii, d – iv", "a – i, b – ii, c – iv, d – iii", "a – iii, b – ii, c – i, d – iv"], 0,
    "The proof assumes every pigeon gets its own hole (iv) and derives a contradiction; an overcrowded hole holds more than one pigeon."),
7: ("Let G be a group of order 6; H be a subgroup of G, such that 1 < |H| < 6. Choose the best option from below.",
    ["Both G and H may not be cyclic", "G may not be cyclic; but H is always cyclic", "G is always cyclic; but H may not be cyclic", "Both G and H are always cyclic"], 1,
    "G may be S₃, which is not cyclic. By Lagrange, |H| is 2 or 3 – a prime – and every group of prime order is cyclic."),
8: ("Match the following terms with their correct definitions and choose the correct option.\na) Weighted Graph\nb) Weight\nc) Unweighted Graph\ni. A graph with no labelled edges\nii. A graph where each edge has a numerical value\niii. A numerical value associated with an edge\niv. A graph that has no vertices",
    ["a – ii, b – iii, c – i", "a – i, b – iv, c – ii", "a – ii, b – i, c – iii", "a – iii, b – ii, c – iv"], 0,
    "A weighted graph has a number on each edge; that number is the weight; an unweighted graph has no such labels."),
9: ("Given the following Linear Programming Problem,\nminimize Z = 6x + 3y\nsubject to the constraints\n4x + y ≥ 80\nx + 5y ≥ 115\n3x + 2y ≤ 150\nx ≥ 0, y ≥ 0\nThe minimum value of Z is ____",
    ["228", "150", "285", "240"], 1,
    "Corner points: (15, 20) → 150; (2, 72) → 228; (40, 15) → 285. The minimum is 150 at x = 15, y = 20."),
12: ("Which algorithm includes repeated addition of two predetermined values A and B to a product P and then performs a rightward arithmetic shift on P?",
    ["Strassen algorithm", "Simple algorithm", "Booth's algorithm", "Specific algorithm"], 2,
    "Booth's multiplication algorithm adds or subtracts the multiplicand and then arithmetic-shifts the product register right."),
13: ("For the given decimal number 1234,\n(i) Hexadecimal equivalent is 4D2\n(ii) Octal equivalent is 2322\nFrom the above statements choose the correct option",
    ["(i) is true but (ii) is false", "Both (i) and (ii) are true", "Both (i) and (ii) are false", "(ii) is true but (i) is false"], 1,
    "4·256 + 13·16 + 2 = 1234 and 2·512 + 3·64 + 2·8 + 2 = 1234."),
14: ("The time between the receival of an interrupt and its service is called",
    ["Interrupt delay", "Interrupt latency", "Cycle time", "Switching time"], 1,
    "Interrupt latency is the delay from the interrupt request to the start of its service routine."),
15: ("Which one of the following statements is TRUE for memory-mapped I/O?",
    ["The I/O devices have separate address space", "The I/O devices and memory share the same address space", "A part of the memory is specially set aside for I/O operation", "The memory and I/O devices have an associated address space"], 1,
    "In memory-mapped I/O, device registers occupy addresses in the same address space as memory and are accessed with ordinary load/store instructions."),
16: ("In a pipeline unit, with K stages and n instructions,\n(i) Speedup of the pipeline unit compared to sequential processor is Kn / (K + (n − 1))\n(ii) The pipeline has to be flushed if the pipeline unit encounters branch instruction.\nFrom the above statements choose the correct option",
    ["Both (i) and (ii) are false", "(i) is true but (ii) is false", "Both (i) and (ii) are true", "(ii) is true but (i) is false"], 2,
    "Sequential time nK cycles vs pipelined K + n − 1 cycles; a taken branch invalidates the instructions already fetched behind it."),
17: ("In Relative Addressing Mode, the effective address = ____",
    ["address part of instruction + PC", "address part of instruction + index register", "address part of instruction + base register", "address part of instruction + register indirect"], 0,
    "Relative (PC-relative) mode adds the address field to the program counter; index and base modes use other registers."),
18: ("Which one of the following is a form of \"locality of reference\"?\n(i) temporal\n(ii) spatial\n(iii) write-through\n(iv) sequential",
    ["(i), (ii) and (iii)", "(i), (ii) and (iv)", "(i), (iii) and (iv)", "(ii), (iii) and (iv)"], 1,
    "Write-through is a cache write policy, not a kind of locality."),
20: ("How many switch points are there in a crossbar switch network that connects 9 processors to 6 memory modules?",
    ["15", "9", "6", "54"], 3,
    "A crossbar has one crosspoint for every processor–memory pair: 9 × 6 = 54."),
21: ("How many times will the following C loop execute?\nfor (j = 1; j <= 10; j = j - 1)",
    ["Forever", "Never", "0", "1"], 0,
    "j starts at 1 and keeps decreasing, so j <= 10 stays true: the loop never terminates normally."),
22: ("What will be the output of the following C code?\nint main() {\n  int a[] = {1, 2, 3, 4, 5}, *P;\n  P = a;\n  ++*P;\n  printf(\" %d \", *P);\n  P += 2;\n  printf(\" %d \", *P);\n}",
    ["2 4", "3 4", "2 2", "2 3"], 3,
    "++*P increments a[0] to 2 and prints 2; P += 2 points to a[2], which is 3."),
23: ("From the following code in 'C', what will be the output?\n#include <stdio.h>\nint main()\n{ int *ptr, a = 10;\n  ptr = &a;\n  *ptr += 1;\n  printf(\"%d, %d\", *ptr, a);\n}",
    ["10, 10", "10, 11", "11, 10", "11, 11"], 3,
    "ptr points to a, so *ptr += 1 makes a = 11; both expressions print 11."),
24: ("Predict the output of the following C++ code:\n#include <iostream>\nusing namespace std;\nint main() {\n  char arr[] = \"Hello\";\n  char *P = arr;\n  cout << P << \" \" << *P;\n  return 0;\n}",
    ["Hello Hello", "Hello H", "H H", "H Hello"], 1,
    "cout prints a char* as a C string (\"Hello\"); *P is the single character 'H'."),
25: ("Identify the output of the following C++ code\n#include <iostream>\nusing namespace std;\nint main() {\n  int a = 4, b = 0x5;\n  cout << (a & b) << endl;\n  return 0;\n}",
    ["Compiler error", "5", "4", "20"], 2,
    "The paper prints the literal as '0 × 5', which reads as the hex literal 0x5. 4 & 5 = 0100 & 0101 = 0100 = 4."),
26: ("Which function is used to remove characters from a string in C++?",
    ["remove()", "delete()", "strip()", "erase()"], 3,
    "std::string::erase removes characters; std::remove only reorders a range and needs erase to shrink the string."),
27: ("In the Digital Differential Analyser algorithm, the decision to increment either x or y is based on:",
    ["The midpoint of the line", "The product of x and y coordinates", "The error value", "Whether the slope is greater than 1 or less than 1"], 3,
    "DDA steps by 1 along the axis of greater change: x when |m| ≤ 1, y when |m| > 1."),
28: ("We rotate a point P(2,5) by 60° about a pivot point (1,2). The new transformed point P' would be ____",
    ["(−4, 1)", "(1, −4)", "(−1, 4)", "(1, 4)"], 2,
    "Relative to the pivot the point is (1, 3). Rotating: x = 0.5 − 3(0.866) ≈ −2.10, y = 0.866 + 1.5 ≈ 2.37. Adding the pivot gives ≈ (−1.1, 4.4), i.e. (−1, 4)."),
29: ("The algorithm that is typically used to compute points on a Bezier curve is ____",
    ["Midpoint algorithm", "Bresenham's algorithm", "de Casteljau's algorithm", "DDA algorithm"], 2,
    "de Casteljau's algorithm evaluates a Bézier curve by repeated linear interpolation of its control points."),
30: ("In the Cohen-Sutherland line clipping algorithm, the region codes (out codes) are:",
    ["2-bit codes for each region", "8-bit codes for each region", "16-bit codes for each region", "4-bit codes for each region"], 3,
    "One bit each for above, below, right and left of the clip window: 9 regions, 4-bit codes."),
31: ("Which of the following can act as possible termination conditions in K-means?\n(a) For a fixed number of iterations\n(b) The assignment of observations to clusters does not change between iterations except for cases with a bad local minimum\n(c) Centroids do not change between successive iterations\n(d) Terminate when reduction in the sum of square distances between points and their assigned cluster centroids falls below threshold.",
    ["(a), (b) and (c)", "(a), (c) and (d)", "(a), (b) and (d)", "(a), (b), (c) and (d)"], 3,
    "All four are standard stopping criteria for K-means."),
32: ("What is the process of examining large and varied data sets to uncover hidden patterns, unknown correlations, market trends, customer preferences and other useful information?",
    ["Data Mining", "Data Warehousing", "Data Integration", "Data Processing"], 0,
    "Discovering hidden patterns and correlations in data is data mining (the analytics step of KDD)."),
33: ("Match the following and choose the correct option:\na) Document-oriented database\nb) Key-value database\nc) Column-oriented database\nd) Graph databases\ni. HBase\nii. Neo4J\niii. Redis\niv. MongoDB",
    ["a – ii, b – iv, c – iii, d – i", "a – ii, b – iii, c – iv, d – i", "a – iv, b – iii, c – i, d – ii", "a – ii, b – i, c – iii, d – iv"], 2,
    "MongoDB stores documents, Redis is key-value, HBase is a wide-column store and Neo4j is a graph database."),
34: ("The Relational Algebra does not have",
    ["Selection Operator", "Projection Operator", "Aggregation Operator", "Division Operator"], 2,
    "Basic relational algebra has selection, projection, set operations, products, joins and division; aggregation is an extension."),
35: ("Which one of the following statements is FALSE?",
    ["Candidate keys are the minimal keys whose superset is not a subkey", "Dependent entities are also called as weak entities", "Generalization is a relationship that exists between a higher-level entity set and the lower-level entity set", "A relationship is an association among entities"], 0,
    "A candidate key is a minimal superkey – no proper subset of it is a superkey. Statement 1 does not state this."),
36: ("Let R1(a,b,c) and R2(x,y,z) be two relations in which 'a' is foreign key of R1 that refers to the primary key of R2. Consider the following four options:\n(a) Insert into R1\n(b) Insert into R2\n(c) Delete from R1\n(d) Delete from R2\nWhich of the following is correct about the referential integrity constraint with respect to above?",
    ["Operations (a) and (b) will cause violation", "Operations (b) and (c) will cause violation", "Operations (c) and (d) will cause violation", "Operations (d) and (a) will cause violation"], 3,
    "Inserting into the referencing relation R1 may add a dangling foreign key; deleting from the referenced relation R2 may orphan R1 rows."),
38: ("Which one of the following statements is FALSE?",
    ["In Discretionary Access Control, the owner can determine the access privileges", "Discretionary Access Control has tighter security compared to Mandatory Access Control", "Discretionary Access Control is flexible with no rules and regulations", "Decisions will be based on the identity of the user and ownership in Discretionary Access Control"], 1,
    "Mandatory Access Control, with system-enforced labels, is the stricter model; DAC is flexible and owner-controlled."),
39: ("In a distributed system environment the location transparency allows the database users, programmers and administrators to treat the data as if it resides in a single location. An SQL query with location transparency needs to specify ____",
    ["Fragments", "Inheritance", "Locations", "Local format"], 0,
    "With location (but not fragmentation) transparency, a query names the fragments but not the sites where they are stored."),
40: ("Data selection deals with the",
    ["actual discovery phase of a knowledge discovery process", "data collection and selection of right data for KDD process", "a subject-oriented, time-variant data collection in support of environment", "non-volatile collection of data"], 1,
    "Selection is the first KDD step: choosing the relevant data. Options 3 and 4 describe a data warehouse."),
42: ("A section of code or set of operations in which a process may be changing shared variables is known as a ____",
    ["Atom", "Procedure", "Deadlock", "Critical Section"], 3,
    "Code that accesses shared data must run under mutual exclusion – the critical section."),
43: ("Given below are two statements: One is labelled as Assertion (A) and the other is labelled as Reason (R)\nAssertion (A): Random Access Memory (RAM) is volatile and stores data/programs currently in use.\nReason (R): RAM is a storage medium that retains its contents even after the supply of electricity has been turned off.",
    ["Both (A) and (R) are true and (R) is the correct explanation of (A)", "Both (A) and (R) are true but (R) is not the correct explanation of (A)", "(A) is true but (R) is false", "(A) is false but (R) is true"], 2,
    "RAM is volatile – it loses its contents when power is removed – so R is false."),
44: ("Consider the following threads T1, T2, T3 executing on a single processor, synchronized using three binary semaphore variables S1, S2, S3, operated upon using standard wait() and signal(). The threads can be context switched in any order and at any time.\nT1: while (true) { wait(S3); print(\"C\"); signal(S2); }\nT2: while (true) { wait(S1); print(\"B\"); signal(S3); }\nT3: while (true) { wait(S2); print(\"A\"); signal(S1); }\nWhich initialization of the semaphores would print the sequence BCABCABCA …?",
    ["S1 = 1; S2 = 1; S3 = 1", "S1 = 1; S2 = 0; S3 = 0", "S1 = 0; S2 = 1; S3 = 1", "S1 = 1; S2 = 1; S3 = 0"], 1,
    "B must come first, so only S1 starts at 1. Then B signals S3 → C, C signals S2 → A, A signals S1 → B, and so on."),
46: ("____ is the disk scheduling algorithm used in Solid State Drives (SSDs)",
    ["SCAN", "SSTF", "C-SCAN", "FCFS"], 3,
    "SSDs have no seek time, so a simple FCFS (NOOP) policy is typically used."),
47: ("Listed below are some Operating System abstractions and the hardware components. Which matching pair is correct?\na) Thread\nb) Virtual address space\nc) File system\nd) Signal\ni. Interrupt\nii. Memory\niii. CPU\niv. Disc",
    ["a – iii, b – ii, c – iv, d – i", "a – iii, b – iv, c – i, d – ii", "a – ii, b – iii, c – iv, d – i", "a – iv, b – ii, c – i, d – iii"], 0,
    "Threads abstract the CPU, address spaces abstract memory, file systems abstract the disk and signals abstract interrupts."),
48: ("____ is a popular cryptographic algorithm for digital signatures and public key infrastructure.",
    ["RSA", "MD5", "AES", "SHA-1"], 0,
    "RSA is a public-key algorithm used for signatures and PKI; MD5 and SHA-1 are hashes and AES is symmetric."),
49: ("In ____ technique, Virtual Memory Managers (VMMs) do not virtualize real hardware but instead create an optimized virtual system.",
    ["Paravirtualization", "Emulator", "Application containment", "Programming-Environment Virtualization"], 3,
    "In programming-environment virtualization (e.g. the Java VM), the VMM presents an optimised virtual system rather than real hardware."),
50: ("Match the following and choose the correct option (in the Linux Virtual File System):\na) An inode object\nb) A file object\nc) A super block object\nd) A dentry object\ni. Represents an entire file system\nii. Represents an individual directory entry\niii. Represents an open file\niv. Represents an individual file",
    ["a – iii, b – ii, c – iv, d – i", "a – iv, b – iii, c – ii, d – i", "a – ii, b – i, c – iii, d – iv", "a – iv, b – iii, c – i, d – ii"], 3,
    "These are the four primary Linux VFS object types (Silberschatz)."),
51: ("What are the phases of the Adaptive Software Development Model?",
    ["Speculation, Collaboration and Learning", "Requirements, Analysis, Design, Evolution and Delivery", "Feasibility Study, Business Study, Functional Model Iteration, Design and Build Iteration, Implementation", "Planning, Design, Coding, Testing"], 0,
    "ASD (Highsmith) cycles through speculation, collaboration and learning; option 3 lists the DSDM phases."),
52: ("What is the primary purpose of Sprint Retrospective in SCRUM FRAMEWORK?",
    ["To plan for another Scrum's Sprint", "To review test cases from the beginning", "To review the past Scrum's Sprint and identify any improvement", "None of the above"], 2,
    "The retrospective inspects how the last sprint went and plans improvements; sprint planning is a separate event."),
53: ("The first step in writing a use case is to define the set of ____ that will be involved in the story.",
    ["Actors", "Devices", "User", "Storyteller"], 0,
    "Pressman: the first step in writing a use case is to define the actors."),
54: ("How to estimate the effort using cost per person-month to calculate total cost of a software, if it has 10 persons-months and the average cost per person-month as $5000. The total cost is:",
    ["$50,000", "$40,000", "$60,000", "$70,000"], 0,
    "10 person-months × $5,000 = $50,000."),
55: ("Consider the given statements.\nStatement 1: Cost of conducting technical reviews for Software Engineering work products\nStatement 2: Cost of data collection and metrics evaluation\nStatement 3: Cost of testing and debugging\nThese statements are the examples of ____",
    ["External Failure Costs", "Prevention Costs", "Internal Failure Costs", "Appraisal Costs"], 3,
    "Pressman lists technical reviews, data collection and metrics evaluation, and testing and debugging as appraisal costs."),
56: ("____ approach is used when a project encompasses the use of existing software that must be modified in some way as part of a project",
    ["Fuzzy Logic Sizing", "Standard Component Sizing", "Function Point Sizing", "Change Sizing"], 3,
    "Change sizing estimates the modifications (reuse, adding, changing, deleting code) made to existing software."),
57: ("A timeline chart is also called ____",
    ["PERT", "Gantt Chart", "CPM", "WBS"], 1,
    "Pressman: a timeline chart is also called a Gantt chart."),
58: ("A software is requiring 5000 Lines (LoC). Using basic COCOMO model, the effort E is calculated as E = 3 × (KLoC)^1.2. With these details, derive the estimated effort rightly in person-months.",
    ["E = 3 × (5)^1.2", "E = 3 × (10)^1.2", "E = 3 × (4)^1.2", "E = 3 × (2)^1.2"], 0,
    "5000 LoC = 5 KLoC, so E = 3 × 5^1.2 ≈ 20.7 person-months."),
59: ("A ____ complements the technical review by assessing a configuration object for characteristics that are generally not considered during the review.",
    ["Version Control", "Change Control", "Software Configuration Audit", "Status Reporting"], 2,
    "Pressman: the software configuration audit complements the technical review."),
60: ("A software processes user requests and produces responses as below:\n• Number of Inputs: 4\n• Number of Outputs: 2\nWhat is the 'functional independence' based on the 'output to input' ratio?",
    ["2", "4.0", "0.5", "0.0"], 2,
    "As the question defines it, the ratio is outputs / inputs = 2 / 4 = 0.5."),
61: ("The average time complexity of quick sort is ____",
    ["O(N log N)", "O(N)", "O(N²)", "O(log N)"], 0,
    "Quick sort averages O(N log N); its worst case is O(N²)."),
62: ("In a complete binary tree, if an element is assigned the number i (where 1 ≤ i ≤ n), then which of the following statements is TRUE regarding its children?",
    ["If 2i + 1 > n, the element has no right child", "If 2i > n, the element has a left child", "The left child is always assigned the number 2i − 1", "The right child is assigned the number 2i"], 0,
    "With 1-based numbering the children of i are 2i and 2i + 1; a child exists only if its number is ≤ n."),
63: ("What is the primary advantage of using balanced search trees, such as AVL or red-black trees, for solving a histogramming problem when the number of distinct keys m is small compared to n?",
    ["They require more memory to store all keys", "They are easier to implement than sorting methods", "They can solve the problem in O(m × n) time", "They can solve the problem in O(n log m) time"], 3,
    "Each of the n keys is looked up or inserted in a tree of at most m nodes: O(n log m), better than sorting in O(n log n)."),
64: ("Which one of the following is not a step of Dynamic Programming?",
    ["Characterize the structure of optimal solutions", "Recursively defines the values of optimal solutions", "Compute the value of optimal solutions in a Bottom-Up minimum", "Compute the value of optimal solutions in a Top-Down minimum"], 3,
    "CLRS's four DP steps: characterise the structure, define the value recursively, compute it bottom-up, construct a solution."),
65: ("Which of the following statements is TRUE when AVL search trees are utilized to represent a dictionary, ensuring that each dictionary operation is performed in logarithmic time?\n(i) The height of an AVL tree with n elements/nodes is O(log n) and for every value of n, n ≥ 0, there exists an AVL tree\n(ii) An n element AVL search tree can be searched in O(height) = O(log n) time\n(iii) A new element can be inserted into an n-element AVL search tree so that the result is an n + 1 element AVL tree and such insertion can be done in O(log n) time\n(iv) An element can be deleted from an n-element AVL search tree, n > 0, so that the result is an n − 1 element AVL tree and such a deletion can be done in O(log n) time",
    ["i and ii only", "i, ii, and iii only", "ii and iv only", "i, ii, iii and iv"], 3,
    "All four properties hold for AVL trees (Sahni)."),
66: ("____ are a set of problems that can be solved in polynomial time by deterministic algorithms.",
    ["NP class problems", "P class problems", "Travelling salesman problem", "Knapsack problem"], 1,
    "P is the class of problems decidable in deterministic polynomial time."),
67: ("____ are numbers that cannot form a palindrome when repeatedly reversed and added to itself.",
    ["Lemoine's numbers", "Perfect numbers", "Amicable numbers", "Lychrel numbers"], 3,
    "A Lychrel number never reaches a palindrome under the reverse-and-add process (196 is the best-known candidate)."),
68: ("Which of the following statements is TRUE regarding the time complexity of Prim's algorithm using adjacency matrix?",
    ["O(V + E)", "O(V²)", "O(E log V)", "O(V log V)"], 1,
    "With an adjacency matrix and a simple array of keys, each of V steps scans V entries: O(V²)."),
69: ("Which one of the following statements is TRUE?",
    ["Parallel merge sort is based on divide and conquer algorithm", "Parallel merge sort is based on backtracking", "Odd-Even Transposition sort is based on Insertion sort technique", "Odd-Even Transposition sort is based on Selection sort technique"], 0,
    "Merge sort is divide and conquer; odd-even transposition sort is a parallel form of bubble sort."),
70: ("____ is performed to reduce the likelihood of the erroneous outputs in randomized algorithms.",
    ["approximation", "amplification", "characterization", "randomization"], 1,
    "Probability amplification repeats a randomised algorithm independently to drive the error probability down."),
71: ("The grammar that is used to accept L = {aⁱbʲ | i > j} is given by:",
    ["S → aSb, S → aS, S → a", "S → aSb, S → bS, S → b", "S → abS, S → b", "S → abS, S → bS, S → b"], 0,
    "aSb adds a matched a…b pair, aS adds extra a's, and the base case a guarantees at least one more a than b."),
72: ("Which one of the following is TRUE for a finite-state machine L1 and regular expressions L2 both representing the same class of language?",
    ["L1 < L2", "L1 >= L2", "L1 ∪ L2 = .*", "L1 = L2"], 3,
    "Kleene's theorem: finite automata and regular expressions describe exactly the same class (the regular languages)."),
73: ("Which one of the following grammars is in Chomsky normal form?",
    ["S → AB | BC | CD, A → 0, B → 1, C → 2, D → 3", "S → AB, S → BCA | 0 | 1 | 2 | 3", "S → ABa, A → aab, B → Ac", "S → aSb, S → ab"], 0,
    "In CNF every production is A → BC or A → a; only option 1 satisfies this."),
74: ("The Halting Problem for a Turing Machine is",
    ["Solvable for all Turing Machines", "Solvable for deterministic Turing Machines only", "Solvable if the machine has a finite tape", "Undecidable"], 3,
    "Turing (1936): no algorithm decides, for every TM and input, whether the machine halts."),
75: ("Which one of the following instances of the Post Correspondence Problem has a viable sequence?",
    ["{(b, bb), (bb, bab), (bab, abb), (abb, babb)}", "{(ab, aba), (baa, aa), (aba, baa)}", "{(ab, abb), (ba, aaa), (aa, a)}", "{(ab, b), (b, a)}"], 2,
    "Pairs 1, 2, 3, 3 give ab·ba·aa·aa = abbaaaaa on top and abb·aaa·a·a = abbaaaaa below."),
77: ("Flow of information among the attributes in a parse tree is denoted by",
    ["Flow graph", "Directed graph", "Dependency graph", "Semantic graph"], 2,
    "A dependency graph shows the order in which attribute instances must be evaluated."),
78: ("The optional access link in the activation record is used for",
    ["pointing to the activation record of the cache", "referring non-local data held in other activation records", "holding temporary values", "holding all global variables"], 1,
    "The access (static) link points to the activation record of the enclosing scope, for access to non-local names."),
79: ("The primary data structure used by an LR parser to keep track of the parsing process is ____",
    ["Stack", "Queue", "Linked List", "Binary Tree"], 0,
    "An LR parser shifts states and symbols onto a stack and pops them on reductions."),
81: ("If a carrier modulated by a digital bit stream has one of the possible phases of 0, 90, 180 and 270 degrees, such modulation is called as",
    ["BPSK", "QAM", "MSK", "QPSK"], 3,
    "Four phases, each carrying 2 bits, is quadrature phase-shift keying."),
82: ("Match the following for IPv4 addressing and select the correct key\na) class A\nb) class B\nc) class C\nd) class D\n(i) 2 bytes for network portion, 2 bytes for host portion\n(ii) multicasting\n(iii) 1 byte for network portion, 3 bytes for host portion\n(iv) 3 portions for network portion, 1 byte for host portion",
    ["a – iv, b – i, c – iii, d – ii", "a – iii, b – i, c – iv, d – ii", "a – ii, b – iii, c – i, d – iv", "a – iv, b – ii, c – iii, d – i"], 1,
    "Class A = 8 network bits, class B = 16, class C = 24; class D addresses are for multicast."),
83: ("A bridge operates at the data link layer giving it access to the ____ address of all the stations connected to it.",
    ["physical", "logical", "relative", "absolute"], 0,
    "A bridge works at layer 2 and filters frames using physical (MAC) addresses."),
84: ("For a network with n devices, the number of duplex-mode links required for mesh topology is:",
    ["n(n + 1)", "n(n − 1)", "n(n + 1) / 2", "n(n − 1) / 2"], 3,
    "Every pair needs one duplex link: C(n, 2) = n(n − 1)/2."),
85: ("The process of dividing an analog signal into a string of discrete outputs, each denoting a constant amplitude is called as",
    ["Strobing", "Amplification", "Quantization", "Conditioning"], 2,
    "Quantisation maps sampled amplitudes onto a finite set of levels."),
86: ("When data and acknowledgement are sent in a same frame, it is known as",
    ["Routing", "Synchronization", "Piggy-bagging", "Discretization"], 2,
    "Piggybacking attaches the acknowledgement to an outgoing data frame."),
87: ("The role of Address Resolution Protocol (ARP) is to find the",
    ["IP address from the DNS", "IP address of the client", "IP address that corresponds to a MAC address", "MAC address that corresponds to an IP address"], 3,
    "ARP maps a known IP address to a MAC address on the local network (RARP does the reverse)."),
88: ("Which of these are TRUE for public-private key encryption algorithm?\n(i) Private key of the receiver is used by the sender to encrypt the message\n(ii) Public key is used by the receiver to decrypt the message",
    ["Only (i) is true", "Only (ii) is true", "Both (i) and (ii) are true", "Both (i) and (ii) are false"], 3,
    "The sender encrypts with the receiver's public key and the receiver decrypts with its own private key."),
89: ("Which of these statements are CORRECT?\n(i) When a router receives the packet, TTL is reduced by one\n(ii) When a router receives the packet, TTL is increased by one\n(iii) If the TTL count is zero and the packet has not reached the destination, the packet is discarded\n(iv) If the TTL count is 255 and the packet has not reached the destination, the packet is discarded",
    ["Only (i) is correct", "Only (ii) is correct", "Only (i) and (iii) are correct", "Only (ii) and (iv) are correct"], 2,
    "Each router decrements TTL and discards the packet when TTL reaches zero."),
90: ("The Mobile Application Part (MAP) is a/an ____ protocol that provides an application layer for the various nodes in GSM and UMTS mobile core networks and GPRS core networks.",
    ["SS7", "SNMP", "SMTP", "HTTP"], 0,
    "MAP is an application-layer protocol of the SS7 (Signalling System No. 7) stack."),
91: ("What is the Turing Test designed to assess?",
    ["Computing Power", "Machine's behaviour similar to human's", "Accuracy of results", "None of the above"], 1,
    "Turing's imitation game tests whether a machine's conversational behaviour is indistinguishable from a human's."),
92: ("Suppose you are constructing AI for an intergalactic travel planner. What representation handles multiple planets?",
    ["Stacking planets in a priority queue based on their beauty", "A graph connecting planets with worm hole edges for quick travel", "A hash table mapping planets to their languages", "An array of codes to encode planet coordinates"], 1,
    "Route planning needs locations as vertices and connections as edges – a graph."),
94: ("Which one of the following is used to query RDF in semantic web?",
    ["SQL", "XML", "Relation Data Query", "SPARQL"], 3,
    "SPARQL is the W3C query language for RDF data."),
95: ("Which technique considers the problem of extracting a reward function from observed optimal behaviour of an expert acting in an environment?",
    ["Inverse reinforcement learning", "Reinforcement learning", "Supervised learning", "Unsupervised learning"], 0,
    "Inverse RL infers the reward from demonstrations; ordinary RL learns behaviour from a given reward."),
97: ("Fuzzy equivalence relation is a type of fuzzy relation that satisfies",
    ["Equivalence, linearity and transitivity", "Asymmetry, commutativity and transitivity", "Irreflexivity, asymmetry and associativity", "Reflexivity, symmetry and transitivity"], 3,
    "Like a crisp equivalence relation, a fuzzy equivalence (similarity) relation is reflexive, symmetric and (max–min) transitive."),
98: ("In a multilayer perceptron, the back propagation algorithm is used",
    ["As it initializes the weights of networks", "To optimize search algorithms", "To speed up learning", "To propagate errors back through network to update the weights"], 3,
    "Backpropagation computes error gradients layer by layer, backwards, for weight updates."),
99: ("Which one of the following is not a specified method that is used for the selection of parents?",
    ["Steady state selection", "Tournament selection", "Boltzmann selection", "Elitism"], 3,
    "Elitism copies the best individuals unchanged into the next generation; it is not a parent-selection scheme."),
100: ("Which one of the following algorithm is commonly used for classification tasks in AI?",
    ["K-means clustering", "Decision Trees", "Prim's Algorithm", "Depth-first Search"], 1,
    "Decision trees are supervised classifiers; K-means is unsupervised clustering."),
}


def sets():
    nums = sorted(Q)
    out = []
    for lo in (1, 26, 51, 76):
        hi = lo + 24
        qs = [(q, o, a, e + NOTE, SRC.format(n)) for n in nums if lo <= n <= hi for q, o, a, e in [Q[n]]]
        out.append({"name": f"Q{lo}–{hi}", "questions": qs, "keep_order": True})
    return out


TOPIC = "KSET 2024 – Computer Science & Application"
