"""Previous-year paper · KSET 2023 (competitive examination 2023) · Paper II · Computer Science & Application · paper code COP202324 · version B1.
Source: KEA question-paper archive, cetonline.karnataka.gov.in/keawebentry456/QP2023/K_SET_2023_05_07_26_CS&A_13072026kannada.pdf
(scanned; OCR draft checked against the page images). Options (A)–(D) are in the printed order.
Key: KEA's revised key of 28-03-2024 (keawebentry456/kset2023/computer_science2803kannada.pdf) lists only the changed
answers – for version B1, Q30 → B and Q74 → D; those two use the official answer. Every other answer was worked out by ExamSim.
Skipped: Q1 (printed code lacks a comma, so 'syntax error' and the intended output both fit), Q8 (depends on the bit order of
the region code), Q9, Q42, Q48, Q51, Q52 (DFA and NDFA both correct), Q68, Q69, Q75, Q80 (all four are mutation operators),
Q92 (the correct value 36.246 is misprinted as 36.248)."""

SRC = "KSET 2023 CS&A · Q{}"
NOTE = " (Answer worked out by ExamSim; not KEA's official key.)"
OFFICIAL = " (Official answer: KEA revised key, 28 Mar 2024.)"

Q = {
2: ("Read the code and predict the value of x.\n#include <stdio.h>\nint main()\n{\n  int x;\n  x = 5 > 8 ? 10 : 1 != 2 < 5 ? 20 : 30;\n  printf(\"%d\", x);\n  return 0;\n}",
    ["20", "30", "8", "10"], 1,
    "5 > 8 is false, so the second conditional is evaluated. < binds tighter than !=, so 2 < 5 = 1 and 1 != 1 = 0 (false) → x = 30."),
3: ("What is the output of the following C code?\nint main()\n{\n  int ary[] = {1, 3, 5};\n  printf(\"%d %d\", ary[-1], ary[4]);\n  return 0;\n}",
    ["1 5", "0 0", "Compile error", "Garbage value"], 3,
    "C does no bounds checking: ary[-1] and ary[4] read memory outside the array (undefined behaviour), so unpredictable 'garbage' values are printed."),
4: ("Predict the output of the following C++ code.\n#include <iostream>\nusing namespace std;\ntemplate <typename T>\nT max(T &p, T &q)\n{\n  return (p > q ? p : q);\n}\nint main()\n{\n  int x = 55, y = 60, m;\n  long a = 105, b = 53, n;\n  m = max(x, y);\n  n = max(a, b);\n  cout << m << endl;\n  cout << n << endl;\n  return 0;\n}",
    ["60 60", "60 105", "50 105", "60 53"], 1,
    "The template is instantiated for int (max(55, 60) = 60) and for long (max(105, 53) = 105). (With some compilers the call can clash with std::max; the intended answer is 60 and 105.)"),
5: ("Which of the following can be considered as the correct syntax for declaring an array of pointers of integers that has a size of 20 in C++?",
    ["int arr = new int[20];", "int *arr = new int *[20];", "int **arr = new int *[20];", "int *arr = new int[20];"], 2,
    "new int*[20] allocates 20 int pointers and returns int**."),
6: ("Which of the following tag is used for inserting the largest heading in HTML?",
    ["<h3>", "<h1>", "<h5>", "<h6>"], 1,
    "<h1> is the largest heading level; <h6> is the smallest."),
7: ("Which is not a method in the life-cycle of Java servlet?",
    ["init()", "call()", "service()", "destroy()"], 1,
    "A servlet's life cycle is init() → service() (for each request) → destroy()."),
10: ("In true color RGB, the number of bits for color depth is",
    ["32", "24", "56", "18"], 1,
    "True colour uses 8 bits for each of R, G and B = 24 bits (about 16.7 million colours)."),
11: ("____ translates the DML statements embedded in an application program to normal procedure calls in the host language.",
    ["DDL Compiler", "DML Pre-compiler", "DML Compiler", "DDL Interpreter"], 1,
    "The DML pre-compiler converts embedded DML into host-language procedure calls (Silberschatz / Navathe)."),
12: ("Identify the correctness of the following statements:\nI. The aggregate functions like sum, count, etc., can be performed with the basic relational algebraic operations of relational calculus formulas.\nII. Relational calculus is a formal query language where the queries are expressed as variables and formulas on these variables.\nIII. The queries in the relational algebra are procedural.",
    ["I is correct; II and III are incorrect", "I is incorrect; II and III are correct", "I and II are correct; III is incorrect", "I and II are incorrect; III is correct"], 1,
    "Aggregates are an extension beyond basic relational algebra/calculus; calculus is declarative with variables and formulas; algebra is procedural."),
13: ("Which one of the following statements is false?",
    ["Triggers prevent invalid transactions", "Triggers does not provide transparent event logging", "Triggers provide transparent event logging", "Triggers provide complex security authorization"], 1,
    "Triggers are used to enforce complex security, prevent invalid transactions and log events transparently."),
14: ("Which one of the following is not a desirable property of transaction?",
    ["Atomicity", "Consistency", "Durability", "Normalization"], 3,
    "The ACID properties are Atomicity, Consistency, Isolation and Durability; normalization is a schema-design process."),
15: ("Identify the correctness of the statements:\nI. Object-Relational Databases are schema-less\nII. Object-Relational Databases store objects as rows in tables\nIII. Object-Relational Databases make use of pessimistic and optimistic locking",
    ["I is correct; II and III are incorrect", "I is incorrect; II and III are correct", "I and II are correct; III is incorrect", "I and II are incorrect; III is correct"], 1,
    "ORDBs keep a relational schema (not schema-less), store objects as rows, and use the usual concurrency-control methods."),
16: ("A clustering index is defined on the fields which are of the type:",
    ["Non-key and ordering", "Non-key and non-ordering", "Key and ordering", "Key and non-ordering"], 0,
    "A clustering index is on a non-key field by which the file is physically ordered; a primary index is on an ordering key field."),
17: ("The system of data warehousing is mostly used for:",
    ["Data mining and data storage", "Data integration and data storage", "Reporting and data analysis", "Data cleaning and data storage"], 2,
    "A data warehouse is designed for querying, reporting and analysis (OLAP) rather than transaction processing."),
18: ("The process of data scrubbing deals with the process to:",
    ["Upgrade the quality of data after it is moved into a data warehouse.", "Reject data from the data warehouse and to create the necessary indexes.", "Load data into data warehouse and to create necessary indexes.", "Clean and upgrade the quality of data, before it is moved into a data warehouse."], 3,
    "Scrubbing (cleansing) fixes errors and inconsistencies before loading into the warehouse."),
19: ("Which of the following statement(s) is/are true?\nI. Facebook has the world's largest Hadoop cluster\nII. Hadoop 2.0 allows live stream processing of real-time data.",
    ["I only", "II only", "Both I and II", "Neither I nor II"], 2,
    "Both are standard textbook statements: Facebook ran the largest Hadoop cluster, and Hadoop 2.0 (YARN) supports stream-processing engines alongside MapReduce."),
20: ("Which of the following is a NoSQL type?",
    ["SQL", "JSON", "Document database", "Image database"], 2,
    "NoSQL types: document, key-value, column-family and graph databases. JSON is a data format."),
21: ("____ translates the high-level language program into machine language.",
    ["Assembler", "Compiler", "Loader", "Linker"], 1,
    "A compiler translates high-level source code; an assembler translates assembly language."),
22: ("____ is invoked when there is a need to perform process scheduling, that is when a process from the ready queue is to be selected for dispatching to the CPU.",
    ["Long-Term Scheduler", "Medium-Term Scheduler", "Short-Term Scheduler", "Non-preemptive Scheduler"], 2,
    "The short-term (CPU) scheduler picks the next ready process for the CPU."),
23: ("A thread is a",
    ["Task", "Process", "Lightweight process", "Program"], 2,
    "A thread shares its process's code, data and files but has its own registers and stack – a lightweight process."),
24: ("Which one of the following is not a deadlock recovery method?",
    ["Resource preemption", "Abort the process", "Hold and wait", "Rollback"], 2,
    "Hold and wait is one of the four necessary conditions for deadlock, not a recovery method."),
25: ("____ helps to control memory wastage occurring in dynamic partitioning.",
    ["Fragmentation", "Compaction", "Garbage collection", "Segmentation"], 1,
    "Compaction shuffles memory contents to merge scattered free holes (external fragmentation) into one block."),
26: ("RAID level 4 provides:",
    ["Disk mirroring", "Memory style error-correcting code organization", "Block-interleaved parity organization", "Bit-interleaved parity organization"], 2,
    "RAID 1 = mirroring, RAID 2 = memory-style ECC, RAID 3 = bit-interleaved parity, RAID 4 = block-interleaved parity."),
27: ("____ is a general model of protection that provides a mechanism for protection without imposing a particular protection policy on the system or its users.",
    ["Global table", "Capability list", "Lock-key mechanism", "Access matrix"], 3,
    "Silberschatz: the access matrix separates mechanism from policy."),
28: ("____ is built into the software by the original programmer in order to gain access to any system without going through the usual security access procedure.",
    ["Trojan Horse", "Logic Bomb", "Trap Door", "Worm"], 2,
    "A trap door (back door) is a hidden entry point left by the programmer."),
29: ("A ____ acts as a lightweight operating system that runs natively on the hardware and manages guest operating systems.",
    ["Type 0 Hypervisor", "Type 1 Hypervisor", "Type 2 Hypervisor", "Emulator"], 1,
    "Type 1 hypervisors are special-purpose OSs running on bare hardware; type 0 is firmware-based and type 2 runs on a host OS."),
30: ("In a communication network, if a path from Site A to Site B is fixed for the duration of one session, the routing scheme adopted is called ____.",
    ["Fixed routing", "Virtual routing", "Dynamic routing", "Static routing"], 1,
    "Virtual routing fixes the path for one session; fixed routing always uses the same path; dynamic routing chooses per message.", True),
31: ("In the software generic process model, ____ executes the activities in a circular manner.",
    ["Linear Process Flow", "Iterative Process Flow", "Evolutionary Process Flow", "Parallel Process Flow"], 2,
    "Pressman: an evolutionary process flow executes the activities in a circular manner; an iterative flow repeats activities before moving on."),
32: ("____ defines a problem associated with a framework activity for the process.",
    ["Stage Pattern", "Task Pattern", "Phase Pattern", "Pattern Name"], 0,
    "Pressman: a stage pattern relates to a framework activity; a task pattern to a software engineering action; a phase pattern to the sequence of activities."),
33: ("____ depicts the information domain for the problem.",
    ["Scenario-based Models", "Flow-Oriented Models", "Class-Oriented Models", "Data Models"], 3,
    "Pressman: data models depict the information domain for the problem."),
34: ("____ architectural design model addresses the behavioural aspects of the program architecture, indicating how the structure or system configuration may change as a function of external events.",
    ["Dynamic", "Framework", "Process", "Functional"], 0,
    "Pressman lists structural, framework, dynamic, process and functional architectural models; dynamic models address behaviour."),
35: ("____ is an indication of the relative functional strength of a module.",
    ["Coupling", "Refinement", "Aspects", "Cohesion"], 3,
    "Cohesion measures a module's functional strength; coupling measures interdependence between modules."),
36: ("The extent to which a program can be expected to perform its intended function with the required precision. This definition belongs to ____ software quality factor.",
    ["Correctness", "Reliability", "Integrity", "Usability"], 1,
    "McCall: reliability is performing the intended function with required precision; correctness is satisfying the specification."),
37: ("The ____ is a dynamic multivariable model that assumes a specific distribution of effort over the life of a software development project.",
    ["COCOMO", "LOC", "Software Equation", "FP"], 2,
    "Putnam's software equation is the dynamic multivariable model described in Pressman."),
38: ("____ is not related to Black-box Testing.",
    ["Equivalence Partitioning", "Boundary Value Analysis", "Orthogonal Array Testing", "Condition Testing"], 3,
    "Condition testing exercises the logical conditions in the code – a white-box technique."),
39: ("The ____ is conducted at the developer's site by a representative group of end users.",
    ["Alpha Testing", "Beta Testing", "Configuration Review", "Recovery Testing"], 0,
    "Alpha tests happen at the developer's site; beta tests at the users' sites."),
40: ("____ combines procedures and tools to manage different versions of configuration objects that are created during the software process.",
    ["Change Control", "Version Control", "Audit Trail", "Configuration Audit"], 1,
    "Pressman's definition of version control."),
41: ("Which one of the following statements is true in the context of sparse array?",
    ["The matrices having regular non-zero elements are called unstructured non-zero region matrices.", "Addition of two sparse matrices is possible even if the order of the two matrices are unequal.", "Diagonal matrix and tridiagonal matrix are examples of structured non-zero region matrices.", "Non-zero entries that can occur only on the diagonal or on elements immediately above or below the diagonal is called triangular matrix."], 2,
    "Diagonal and tridiagonal matrices have a fixed pattern of non-zero positions; option 4 describes a tridiagonal matrix, and matrices of unequal order cannot be added."),
43: ("The maximum number of nodes of binary tree at level \"i\" is ____.",
    ["2^(i+2)", "2^(i+1)", "2^i", "i²"], 2,
    "Each level can have twice as many nodes as the one above: 2^i with the root at level 0 (2^(i−1) if the root is level 1)."),
44: ("Which one of the following is false in the context of Divide and Conquer method?",
    ["It is recursive", "It is a top-down approach", "It is a bottom-up approach", "Subproblems are independent of each other"], 2,
    "Divide and conquer splits the problem top-down; bottom-up table filling is typical of dynamic programming."),
45: ("Which one of the following technique is not used by the Lower Bound theory for calculating lower bound?",
    ["Empirical Analysis", "Comparison Trees", "State-space method", "Oracle and adversary argument"], 0,
    "Horowitz–Sahni: comparison trees, oracles and adversary arguments, and state-space methods; empirical timing does not prove bounds."),
46: ("Which one of the following statements is false?",
    ["NP problems are subset of P problems", "NP problems are non-deterministic in nature", "Solution to P class problem is easy to find", "Solutions to NP problems can be verified in polynomial time"], 0,
    "P ⊆ NP; whether NP ⊆ P is the open P vs NP question."),
47: ("In ____ every even integer greater than 2 can be expressed as the sum of 2 primes.",
    ["Fermat's last theorem", "Lemoine's conjecture", "Lychrel numbers", "Goldbach's conjecture"], 3,
    "Goldbach's conjecture; Lemoine's is about odd numbers as p + 2q."),
49: ("Determine the correct statements from the following:\nI. An approximation algorithm guarantees to run in polynomial time.\nII. An approximation algorithm does not guarantee the most effective solution.\nIII. An approximation algorithm provides solution in exponential time.",
    ["I and II are incorrect; III is correct", "I is correct; II and III are incorrect", "I is incorrect; II and III are correct", "I and II are correct; III is incorrect"], 3,
    "Approximation algorithms run in polynomial time and give near-optimal, not necessarily optimal, solutions."),
50: ("In the vertex cover problem, the optimization problem is to find the vertex cover with ____ and the approximation problem is to find the vertex cover with ____.",
    ["few vertices, few vertices", "fewest vertices, fewest vertices", "fewest vertices, few vertices", "few vertices, fewest vertices"], 2,
    "Optimisation seeks the minimum (fewest) cover; an approximation settles for a small (few) one within a guaranteed factor."),
53: ("A DPDA is a PDA in which:",
    ["No state has two outgoing transitions", "More than one state can have two or more outgoing transitions", "At least one state has more than one transition", "No state has two incoming transitions"], 0,
    "Intended meaning: in a DPDA no configuration has a choice of move – no state has two applicable outgoing transitions for the same input and stack symbol."),
54: ("The state of a Turing machine when the given input x is not defined on the current state and current input symbol is:",
    ["Moving", "Halting", "Looping", "Halting and Moving"], 1,
    "If δ is undefined for the current state and symbol, the TM halts."),
55: ("Consider the Lists A and B of three strings on {0, 1}. If:\nX: List A = 1, 10111, 10; List B = 111, 10, 0 and\nY: List A = 10, 011, 101; List B = 101, 11, 011\nthen which of the following is true?",
    ["Only PCP in X has solution", "Only PCP in Y has solution", "PCP in both X and Y has solution", "PCP neither in X nor in Y has solution"], 0,
    "X: indices 2, 1, 1, 3 give 10111·1·1·10 = 101111110 = 10·111·111·0. Y can only start with pair 1 and then B always stays one symbol ahead – no solution (Hopcroft–Ullman)."),
56: ("Which of the following derivations is used by top-down parser?",
    ["Leftmost derivation", "Leftmost derivation in reverse", "Rightmost derivation", "Rightmost derivation in reverse"], 0,
    "Top-down parsers build a leftmost derivation; bottom-up (LR) parsers build a rightmost derivation in reverse."),
57: ("Choose the correct statement suiting syntax directed definitions from the following:",
    ["Syntax directed definitions + Semantic rules = CFG", "Syntax directed definitions + CFG = Semantic rules", "CFG + Semantic rules = Syntax directed definitions", "CFG + flow graph = syntax directed definitions"], 2,
    "An SDD is a context-free grammar together with attributes and semantic rules."),
58: ("The idea of cache memory is based on the",
    ["Properties of optimizing speed", "Heuristic 90-10 rule", "Fact that references cluster", "Property of locality of reference"], 3,
    "Caches exploit temporal and spatial locality of reference."),
59: ("Which of the following helps Assembler to deal with branching code?",
    ["One Pass Assembler", "Two Pass Assembler", "Debugger", "Interpreter"], 1,
    "The first pass builds the symbol table, so forward branch targets are known in the second pass."),
60: ("Which of the following optimization technique reduces the multiple jumps?",
    ["Latter optimization", "Peephole optimization", "Local optimization", "Loop optimization"], 1,
    "Peephole optimisation includes flow-of-control optimisation such as replacing jumps to jumps."),
61: ("Consider a CSMA/CD network that transmits data at the rate of 100 Mbps (10⁸ bits per second) over 1 km cable without repeaters. Let the minimum frame size required for this network be 1250 bytes. Compute the signal speed of the cable, in terms of km/sec.",
    ["10000", "20000", "15000", "24000"], 1,
    "Frame = 10,000 bits → transmission time 10⁻⁴ s = 2 × propagation time, so propagation = 5 × 10⁻⁵ s for 1 km → 20,000 km/s."),
62: ("In Ethernet that uses Manchester encoding, the bit rate is",
    ["thrice the baud rate", "twice the baud rate", "half the baud rate", "same as the baud rate"], 2,
    "Manchester needs two signal elements per bit, so the baud rate is twice the bit rate."),
63: ("Which layer of OSI reference model is responsible for decomposition of messages and generation of sequence numbers, in order to ensure correct re-composition, from end-to-end of a network?",
    ["Physical", "Data-link", "Transport", "Application"], 2,
    "The transport layer segments messages and numbers the segments for end-to-end reassembly."),
64: ("The divisor in a cyclic code is called",
    ["Degree", "Redundancy", "Connector", "Generator"], 3,
    "The divisor in CRC is the generator polynomial."),
65: ("In computer networks, the transmission media are generally categorized as:",
    ["Fixed or dynamic", "Deterministic or non-deterministic", "Guided or unguided", "Trained or untrained"], 2,
    "Guided (cables) and unguided (wireless) media."),
66: ("The port number of POP is:",
    ["110", "220", "360", "490"], 0,
    "POP3 uses TCP port 110 (995 over TLS)."),
67: ("A piece of icon or image on a webpage, associated with another webpage is called",
    ["URL", "Plug-in", "Hyper icon", "Hyperlink"], 3,
    "Any text or image that links to another resource is a hyperlink."),
70: ("The acronym DVMRP stands for:",
    ["Distance Vector Multitask Routing Protocol", "Distance Vector Multicast Routing Protocol", "Distance Vector Mixed Routing Protocol", "Distance Vector Message Routing Protocol"], 1,
    "DVMRP is a multicast routing protocol based on distance-vector routing."),
71: ("Artificial Intelligence is a ____ approach which can make decisions based on logical reasoning and problem solving strategies.",
    ["Heuristic search approach", "Greedy search approach", "State space approach", "Rational agent approach"], 3,
    "Russell & Norvig: AI as building rational agents that act to achieve the best expected outcome."),
72: ("Identify the atomic proposition in the following statements:",
    ["Close the door", "Y > 20", "What a Large Camel!", "It is raining outside"], 3,
    "A proposition is a declarative sentence that is true or false; commands, exclamations and open statements with variables are not."),
73: ("____ search is performed by exploring all nodes at a given depth before proceeding to the next level.",
    ["Depth first search", "Depth first deepening search", "Breadth first search", "Best first search"], 2,
    "Breadth-first search expands level by level."),
74: ("Which type of knowledge representation does not exhibit any learning capabilities?",
    ["Semantic Network", "Logical Representation", "Production Rules", "Frame Representation"], 3,
    "This is the answer in KEA's revised key.", True),
76: ("What is the role of pragmatics in Natural Language Processing?",
    ["To analyze semantics of sentences", "To find contextual meaning and implied communication", "To identify syntax errors in the text", "To find morphological analysis of words"], 1,
    "Pragmatics interprets meaning in context (intent, implicature)."),
77: ("Which algorithm considers all moves from current state and selects the best move as the next state?",
    ["Steepest ascent hill climbing", "Branch and bound", "Means end analysis", "Constraint satisfaction"], 0,
    "Steepest-ascent hill climbing examines all neighbours and moves to the best one; simple hill climbing takes the first better one."),
78: ("Backpropagation Neural Network is a technique used for:",
    ["Transmission of error back through the network to adjust the inputs", "Updating weights based on error propagation", "Updating the number of hidden layers", "Adjusting hyper parameter values"], 1,
    "Backpropagation propagates the error gradient backwards to update the weights (not the inputs)."),
79: ("Which of the following introduces non-linearity into neural network?",
    ["Binary step function", "ReLU function", "Convolution function", "Identity function"], 1,
    "ReLU is the standard non-linear activation used in trainable networks; convolution and identity are linear, and the step function has no useful gradient."),
81: ("The most appropriate logical expression for the sentence \"You cannot use the waterslide if you are under 48 inches in height unless you are older than 14 years old\" is (q: you can use the waterslide, r: you are under 48 inches, s: you are older than 14):",
    ["(r ∧ s) → ¬q", "(r ∧ ¬s) → ¬q", "(r ∧ ¬s) → q", "(r ∨ ¬s) → ¬q"], 1,
    "Rosen's example: if under 48 inches and not older than 14, then you cannot ride: (r ∧ ¬s) → ¬q. (The letters are Rosen's; the paper uses them without defining them.)"),
82: ("Find out which rule of inference is used in the argument \"The meeting has been rescheduled and the conference room is empty now. Therefore, the meeting has been rescheduled now\".",
    ["Simplification rule", "Hypothetical syllogism", "Addition rule", "Conjunction rule"], 0,
    "From p ∧ q conclude p – simplification."),
83: ("A relation R on a set S is called ____ if it is reflexive, antisymmetric and transitive.",
    ["Partial ordering", "Equivalence relations", "Equivalence classes", "Transitive closure"], 0,
    "Reflexive + antisymmetric + transitive = partial order; reflexive + symmetric + transitive = equivalence relation."),
84: ("Consider the following relations on {1, 2, 3, 4}:\nR1 = {(1,1), (1,2), (2,1), (2,2), (3,4), (4,1), (4,4)},\nR2 = {(1,1), (1,2), (2,1)},\nR3 = {(1,1), (1,2), (1,4), (2,1), (2,2), (3,3), (4,1), (4,4)},\nR4 = {(2,1), (3,1), (3,2), (4,1), (4,2), (4,3)},\nR5 = {(1,1), (1,2), (1,3), (1,4), (2,2), (2,3), (2,4), (3,3), (3,4), (4,4)},\nR6 = {(3,4)}\nWhich of the relations are transitive?",
    ["R1, R2, R5, R6", "R4, R5, R6", "R1, R2, R3, R4, R5, R6", "R3, R4, R5"], 1,
    "R1 lacks (3,1) for (3,4),(4,1); R2 lacks (2,2) for (2,1),(1,2); R3 lacks (4,2) for (4,1),(1,2). R4 (>), R5 (≤) and R6 are transitive."),
85: ("In how many ways can 10 examination answer papers be arranged so that the best and worst papers never come together?",
    ["8 × 9!", "8 × 8!", "7 × 9!", "9 × 8!"], 0,
    "All arrangements 10! minus those with the two together 2 × 9! = 9!(10 − 2) = 8 × 9!."),
86: ("____ is not necessarily a property of a group.",
    ["Existence of inverse for every element", "Associativity", "Commutativity", "Existence of identity"], 2,
    "Groups need closure, associativity, identity and inverses; commutativity makes it abelian."),
87: ("Consider the set S = {1, ω, ω²} where ω and ω² are cube roots of unity. If * denotes the multiplication operation, then the structure of (S, *) forms",
    ["A group", "An integral domain", "A ring", "A field"], 0,
    "S is closed under multiplication (ω³ = 1), with identity 1 and inverses ω ↔ ω²; one operation only, so a group (cyclic of order 3)."),
88: ("Which of the following Euler circuit is impossible if number of vertices is greater than 2?",
    ["Cₙ", "Qₙ", "Kₙ", "Wₙ"], 3,
    "In a wheel every rim vertex has degree 3 (odd), so no Euler circuit; Cₙ always has one, Kₙ for odd n, Qₙ for even n."),
89: ("Consider a complete graph G with 5 vertices. The graph G has ____ spanning trees.",
    ["25", "625", "125", "525"], 2,
    "Cayley's formula nⁿ⁻² = 5³ = 125."),
90: ("The amount of time by which an activity can be delayed without affecting project completion time is:",
    ["Free float", "Total float", "Independent float", "Activity float"], 1,
    "Total float is the delay that does not delay the project; free float does not delay the next activity."),
91: ("Select the equivalent of NOR gate from the following (the paper shows gate symbols):",
    ["NAND gate (AND with output bubble)", "AND gate with both inputs inverted", "OR gate with both inputs inverted", "AND gate with both inputs and the output inverted"], 1,
    "De Morgan: (A + B)′ = A′·B′, an AND gate with inverted inputs. Option 3 equals NAND and option 4 equals OR."),
93: ("The register used as a working area in CPU is",
    ["Program counter", "Instruction register", "Pipeline register", "Accumulator"], 3,
    "The accumulator holds operands and intermediate results."),
94: ("Which of the following architecture is used in Modern computers?",
    ["Microarchitecture", "Harvard architecture", "Von-Neumann architecture", "Macro architecture"], 2,
    "General-purpose computers follow the stored-program von Neumann model (with Harvard-style split caches internally)."),
95: ("The primary objective of assembly language is:",
    ["To make programming more difficult.", "To simplify programming by providing high level language constructs.", "To provide a way to interact with hardware at a low level.", "To provide a way to interact with hardware at a high level."], 2,
    "Assembly gives symbolic access to machine instructions and registers."),
96: ("In Microprogrammed Control, the data register is sometimes called",
    ["Accumulator", "Branch register", "Sequence register", "Pipeline register"], 3,
    "Mano: the control data register is sometimes called a pipeline register."),
97: ("Specify the control word to perform addition between R2 and R3 and the result will be stored in R1.",
    ["01001100100010", "00101001100100", "01101000100101", "01001100101010"], 0,
    "Mano's 14-bit control word SELA|SELB|SELD|OPR: R2 = 010, R3 = 011, R1 = 001, ADD = 00010 → 010 011 001 00010."),
98: ("In which addressing mode, the effective address is equal to the address part of the instruction?",
    ["Indexed", "Relative", "Register", "Direct"], 3,
    "In direct addressing the instruction's address field is the effective address."),
99: ("In asynchronous serial data transfer, we use ____ number of flag bits.",
    ["1", "2", "3", "4"], 1,
    "Each character is framed by a start bit and a stop bit."),
100: ("Hit ratio of cache memory is defined as",
    ["Number of hits divided by total number of hits and misses.", "Number of hits divided by number of misses.", "Number of hits plus misses divided by number of hits.", "Number of misses divided by number of hits."], 0,
    "Hit ratio = hits / (hits + misses)."),
}


def sets():
    out = []
    for lo in (1, 26, 51, 76):
        qs = []
        for n in sorted(Q):
            if lo <= n <= lo + 24:
                q, o, a, e, *off = Q[n]
                qs.append((q, o, a, e + (OFFICIAL if off else NOTE), SRC.format(n)))
        out.append({"name": f"Q{lo}–{lo + 24}", "questions": qs, "keep_order": True})
    return out


TOPIC = "KSET 2023 – Computer Science & Application"
